### ISSUE TITLE
HttpContext.AuthenticateAsync do not return "sub" claim after update to .NET 8

### ISSUE THREAD

**Issue by julian-dimitroff** [dotnet/aspnetcore#52940]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After I updated our solution from .NET 6 to .NET 8 and Hangfire.AspNetCore to version 1.8.6, we can't access our Hangfire dashboard anymore. When I revert to an old branch with .NET 6, there's no problem.

### Expected Behavior

I was able to find the difference between the .NET 8 and .NET 6 branches, and it is in the dashboard middleware. I have the following method in the middleware that authenticates with a cookie scheme, takes the logged user, signs in, and signs out with the cookie scheme:
```cs
private async Task LoginCallback(HttpContext httpContext)
{
    var result = await httpContext.AuthenticateAsync(options.CookieAuthenticationScheme + ".external");

    if (result?.Succeeded != true)
    {
        throw new Exception("external login failed");
    }

    var token = new JwtSecurityToken(result.Properties.GetTokenValue("access_token"));

    var claims = Enumerable.Concat(
        result.Principal.Claims.Where(c => c.Type == "sub"),
        token.Claims.Where(c => new[] { "tid", "tname", "scope" }.Contains(c.Type))
    );

    var claimsIdentity = new ClaimsIdentity(claims, options.CookieAuthenticationScheme);
    var authProperties = new AuthenticationProperties();

    logger.LogInformation("External authentication of {Subject} to Hangfire Dashboard.", claims.FirstOrDefault(c => c.Type == "sub")?.Value);
    await httpContext.SignInAsync(options.CookieAuthenticationScheme, new ClaimsPrincipal(claimsIdentity), authProperties);
    await httpContext.SignOutAsync(options.CookieAuthenticationScheme + ".external");
}
```
When this method is invoked, the logger message is:
```
External authentication of null to Hangfire Dashboard. <s:STP.IM.WorkflowProcess.Auth.HangfireDashboard.HangfireDashboardAuthenticationMiddleware>
```
This means that the
```cs
claims.FirstOrDefault(c => c.Type == "sub")?.Value
```
did not find any value, and then the
```cs
httpContext.SignInAsync(options.CookieAuthenticationScheme, new ClaimsPrincipal(claimsIdentity), authProperties);
```
call does not sign the user in.

I then spotted a difference in the result.Principal.Claims IEnumerable: in the .NET 6 branch, I have an entry of type "sub" with a value that looks to me like an Guid. In the .NET 8 branch this entry is missing.

I guess that there are some changes made in the .NET 8 regarding authentication, because the httpContext.AuthenticateAsync does not return that claim with a "sub" type.

Is there a way this problem can be fixed?

Thanks in advance

### .NET Version

8

**Comment by jcmrva** [comment]
Is this blocking your update to .NET 8 or did you find a workaround?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Can you please look into this and see if this helps: https://learn.microsoft.com/en-us/dotnet/core/compatibility/aspnet-core/8.0/securitytoken-events

Specifically, configuring the `UseSecurityTokenValidators` option should help: `options.UseSecurityTokenValidators = true;`

**Comment by julian-dimitroff** [comment]
Hello,
The thing that worked for me is to clear the `JsonWebTokenHandler.DefaultInboundClaimTypeMap`. All I did is to put `Microsoft.IdentityModel.JsonWebTokens.JsonWebTokenHandler.DefaultInboundClaimTypeMap.Clear()` in my `Startup.cs` in `ConfigureServices` method.

**Comment by jchoca** [comment]
Stumbled on this, and the code above doesn't seem to work anymore. I had to use `JwtSecurityTokenHandler.DefaultMapInboundClaims = false;` (on .NET 9.0.305).
