### ISSUE TITLE
Hot reload .cshtml not working in IIS

### ISSUE THREAD

**Issue by rgroenewoudt** [dotnet/aspnetcore#52946]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hot reload in .cshtml files isn't working in combination with IIS. When using IIS Express or Kestrel, there are no issues.

Steps: Start debugging in VS, make a text change in cshtml file, press Hot reload (VS indicates 'Code changes were applied successfully') and refresh the browser.

It can be reproduced with a clean ASP.NET MVC project:
[WebApplication7.zip](https://github.com/dotnet/aspnetcore/files/13742248/WebApplication7.zip)
When debugging via IIS express: works as expected
When debugging via IIS: changes don't appear until rebuild.

### .NET Version

8.0.100

### Anything else?

VS2022 17.8.3

**Comment by javiercn** [comment]
@rgroenewoudt thanks for contacting us.

@BillHiebert is this a supported scenario? Do you have any idea of what might be going on?

**Comment by rgroenewoudt** [comment]
IIS out of process is also not supported, which I was not expecting (as Kestrel is started internally).

`dotnet watch` doesn't seem to support IIS/IIS Express (although only `dotnet run` gives an warning...)

**Comment by rgroenewoudt** [comment]
Any update?

**Comment by javiercn** [comment]
@rgroenewoudt It might help if you also file an issue via the Report a Problem dialog in Visual Studio. 

I've sent an email to see if I can get someone more knowledgeable in the area to take a look, but with the holidays and everything, all teams are a bit behind on their issues backlog.

**Comment by mkArtakMSFT** [comment]
Thanks for reporting it through VS Feedback. Closing this as the issue will be tracked by the VS Feedback ticket linked above.
