### ISSUE TITLE
In ASP.NET 8, IReadOnlyCollection<> controller parameters do not bind from request body by default

### ISSUE THREAD

**Issue by IT-CASADO** [dotnet/aspnetcore#52962]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In ASP.NET 8, a controller with an IReadOnlyCollection<> parameter is not bound from the body of the request by default. An empty array is seen by the controller. This worked in ASP.NET 6. We are currently trying to migrate from .NET 6 to .NET 8.

If the [FromBody] attribute is added to the parameter or List<>/IEnumerable<> is used instead, the binding works.

This issue is similiar to this one #45162 

### Expected Behavior

An IReadOnlyCollection<> parameter should be bound from the body by default, as it was in ASP.NET 6.

### Steps To Reproduce

Create a controller with this method:
```
[HttpPost]
public IActionResult Post(IReadOnlyCollection<SomeClass> data)
{
}
```

### .NET Version

8.0.100

**Comment by captainsafia** [comment]
@IT-CASADO Thanks for reporting this issue! It looks like the fix that we shipped earlier targeted `IEnumerable` specifically and not interfaces derived from `IEnumerable`. We can fix this for .NET 9, but may not backport given that the `[FromBody]` attribute is a viable workaround here.

We should also evaluate if we have broken binding for other collection types with the implicit services support in MVC.

**Comment by IT-CASADO** [comment]
Hmm, I added some tests to the repro project of #45162 and it seems that there are no issues with a _**small starter project**_.
Here is my extended repro: https://github.com/IT-CASADO/ParameterBindingIssue

I need to figure out why it is not working as expected in our project.

**Comment by IT-CASADO** [comment]
This is an issue with [Autofac.Extensions.DependencyInjection](https://www.nuget.org/packages/Autofac.Extensions.DependencyInjection) or [Autofac](https://www.nuget.org/packages/Autofac) itself.

autofac/Autofac.Extensions.DependencyInjection#114
