### ISSUE TITLE
Websockets and break on exception

### ISSUE THREAD

**Issue by Ti-roy** [dotnet/aspnetcore#52979]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have an application that heavily relies on websockets. But there is a problem - if exception is thrown inside websockets - debugger will not break. In any other place it will.

It makes my work extremely tedious as it requires me to catch a exception, read it, and then by callstack figure out where it was thrown.

### Expected Behavior

Debugger breaks on exception in websockets

### Steps To Reproduce

Issue can be seen here: https://github.com/Ti-roy/broken-websockets
But describing steps is not a problem:
1) Throw an exception from websocket
2) Debugger does not break on exception

### .NET Version

7

**Comment by BrennanConroy** [comment]
That has nothing to do with Websockets. You just need to configure the debugger to stop on exceptions. By default, the debugger only stops on exceptions that aren't handled by user code. If you want to stop on any exception (or a specific exception type) you can configure the exception settings.
https://learn.microsoft.com/visualstudio/debugger/managing-exceptions-with-the-debugger?view=vs-2022#tell-the-debugger-to-break-when-an-exception-is-thrown

**Comment by Ti-roy** [comment]
Thanks, thats was it.
