### ISSUE TITLE
Blazor App Login.razor Provides Input.Email as Username to SignInManager

### ISSUE THREAD

**Issue by ElliottBrand** [dotnet/aspnetcore#52983]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The login form provides the email address that is entered into the form as the Username when submitting the information to SignInManager. If the application is setup to allow customization of the username, this will result in an error signing in, as the username won't match the email address anymore.

### Expected Behavior

If the ApplicationUser username is changed, login should still function when logging in with a correct email address.

Suggested solution: The ApplicationUser should be looked up with `await UserManager.FindByEmailAsync(Input.Email);`  (or fail if not found) and passed to the SignInManager instead of the email address as the username.

### Steps To Reproduce

- Create a new Blazor solution using the .Net 8 Blazor App template with Identity.
- Create a new user account.
- Change the username in the database.
- Attempt to login.

### .NET Version

8.0.0

**Comment by halter73** [comment]
Thanks for contacting us. This ask is not aligned with our vision and we have no plans to implement this ask. Of course, you're always welcome to fork this codebase and build off of it!

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/main/docs/TriageProcess.md) writeup. [The comment I left on the PR](https://github.com/dotnet/aspnetcore/pull/52984#pullrequestreview-1834108838) goes into more detail on the specific reasoning for this issue.
