### ISSUE TITLE
[Feature Request][ Blazor New API Security end points Please have better Linkage between new security api end points /login / logout etc storing of tokens and the Blazor Web App New Project Template

### ISSUE THREAD

**Issue by davidbuckleyni** [dotnet/aspnetcore#53006]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

We have the new security api end points which is a fantastic step forward
But why must we have to use direct database connection when we generate our client.

### Describe the solution you'd like

Blazor Web App Template should give a way to point to a already setup web api with new endpoints have already been configured instead of being coded to the database the account pages should auto discover the json swagger end points.
Blazor Client should access the refresh token and berrer tokens in a clean and secure way when the user is login into the site.

### Additional context

I feel its making the blazor client dumb connecting directly to the database for the account pages and hence a security risk.

**Comment by javiercn** [comment]
@davidbuckleyni thanks for contacting us.

We recommend cookies and BFF when you are hosting the server and client bits on the same app.

> I feel its making the blazor client dumb connecting directly to the database for the account pages and hence a security risk.

It's equally safe as when the logic was implemented in MVC or Razor pages. The code for Identity only runs on the server and has the same security checks on it.

**Comment by davidbuckleyni** [comment]
This is not what a meant. again microsoft failing to understand its customers we have to do this code should be automatically generated as part of template

**Comment by davidbuckleyni** [comment]
This is not resolved why mark something resolved if customer not said resolved !
