### ISSUE TITLE
CSS block in `Blazor` component

### ISSUE THREAD

**Issue by BachiMjavanadze** [dotnet/aspnetcore#53012]
Please add CSS styles block into `*.razor` script, like in `Angular` and `Svelte`:

![image](https://github.com/dotnet/aspnetcore/assets/38082501/82df792b-9120-40c5-94be-7682e56872ad)

**Comment by javiercn** [comment]
@BachiMjavanadze thanks for contacting us.

This is not a direction we plan to take in the near future, we support collocating CSS files alongside the razor components, but putting them all together on the same file requires significant changes to the compiler and languages that we don't think justify the cost when you can already colocate the CSS in a separate file.
