### ISSUE TITLE
ClickOnce generates unnessesary and breaking staticwebassets.runtime.json file

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#53027]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/ClickOnce-generates-unnessesary-and-brea/10520709)._

---
[severity:It bothers me. A fix would be nice] [regression] [worked-in:17.7.6]
I use Wpf with Blazor (https://learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/tutorials/wpf?view=aspnetcore-7.0 like that). During publication via ClickOnce (VS 17.8) it generates staticwebassets.runtime.json file that contains absolute paths (of course wrong for another machine) to wwwroot folder and its contents. So my application doesn't start (only generates an error in Event Viewer, System.IO.DirectoryNotFoundException) before deleting that file manually after app installation/upgrade. There is no such problem with a previous version of VS.

---
#### Feedback Bot on 11/20/2023, 06:12 PM: 

(private comment, text removed)
#### Scott McLeod on 12/13/2023, 10:22 AM: 

(private comment, text removed)
#### Ian Gordon on 12/20/2023, 01:27 AM: 

(private comment, text removed)
#### Scott McLeod on 12/20/2023, 03:39 AM: 

(private comment, text removed)
#### Alpha Ori on 12/20/2023, 03:47 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by SoulsideJourney** [comment]
Fixed in VS2022 17.8.0

**Comment by mkArtakMSFT** [comment]
Great, thanks @SoulsideJourney !
