### ISSUE TITLE
.NET Core 8+ Api failing intermittently (w/ Swagger)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#53028]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/NET-Core-8-Api-failing-intermittently-/10519913)._

---
\[severity:It’s more difficult to complete my work\]  
I have just recently installed .NET 8 SDK but I am facing an issue where a minimal .NET 8 SDK fails intermittently.

App crashes immediately and / or after ~5s after the browser window is launched (localhost cannot eb contacted) . This takes place in an intermittent fashion. I have looked at EventViewer but nothing seems catchy or fishy. Any ideas if this is related to an upgrade in .NET 8 or a VS 2022 recent update?

It’s so unproductive having to launch this even three times just to get the Swagger API stuff showing 😕

These are the last log entries whenever this fails.

‘Net8MinimalWebApi.exe’ (CoreCLR: clrhost): Loaded ‘C:\\Program Files\\dotnet\\shared\\Microsoft.NETCore.App\\8.0.0\\System.Security.Cryptography.dll’. Skipped loading symbols. Module is optimized and the debugger option ‘Just My Code’ is enabled.  
‘Net8MinimalWebApi.exe’ (CoreCLR: clrhost): Loaded ‘C:\\Program Files\\dotnet\\shared\\Microsoft.NETCore.App\\8.0.0\\System.Collections.NonGeneric.dll’. Skipped loading symbols. Module is optimized and the debugger option ‘Just My Code’ is enabled.  
‘Net8MinimalWebApi.exe’ (CoreCLR: clrhost): Loaded ‘C:\\Program Files\\dotnet\\shared\\Microsoft.NETCore.App\\8.0.0\\System.Net.Security.dll’. Skipped loading symbols. Module is optimized and the debugger option ‘Just My Code’ is enabled.  
Microsoft.Hosting.Lifetime: Information: Now listening on: [https://localhost:9665](https://localhost:9665)  
Microsoft.Hosting.Lifetime: Information: Now listening on: [http://localhost:9664](http://localhost:9664)  
Microsoft.Hosting.Lifetime: Information: Application started. Press Ctrl+C to shut down.  
Microsoft.Hosting.Lifetime: Information: Hosting environment: Development  
Microsoft.Hosting.Lifetime: Information: Content root path: C:\\Users\\hdiak\\workspace\\Net8MinimalWebApi => Slight delay (~3s) here which is a sign this run will fail  
**The program ‘\[14464\] Net8MinimalWebApi.exe’ has exited with code 4294967295 (0xffffffff).**

Evidence: [NET 8 minimal API crash.mp4](https://aka.ms/dc/file?name=Bcd39b539f5f04c64a7bdd8c35468dabf638360397956530806_NET_8_minimal_API_crash.mp4&tid=cd39b539f5f04c64a7bdd8c35468dabf638360397956530806)

P.S.: I did try earlier .NET versions but this thing persists. Tried other relevant API projects and it does the same. Not sure if’s a Swagger / .NET or VS thing.  
P.S.2: I tried using Edge and the behaviour is the same except that the Edge does not force the app to crash / exit. However, it still exhibits the behaviour where the endpoint just fails and so the app has to be relaunched / stopped and started again.  
P.S.3: After some experimentation it seems after disabling ‘Just My Code’ this issue disappears. So, I guess this is a bug? 😄
P.S.:4: Still happens but the frequency is much more rarer now. I have noticed that if I debug and use breakpoints the bug is exhibited less frequently. I also have added the option to download symbols from NuGet and MS servers os I do not know if the additional overhead "hides" the bug making it less likely to exhibit itself.

---
#### Feedback Bot on 11/19/2023, 06:31 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by captainsafia** [comment]
Does the same happen when you run the app via the commandline and `dotnet run`? The updates you provided to the issue indicate that this might be moreso an issue with Visual Studio. In that case, perhaps you might try repairing your VS installation or clearing the `.vs` hidden directory adjacent to your solution to see if that will help?

**Comment by MozharAlhosni** [comment]
This also is happening to me: whenever I use the minimal API project, I always get the following error when shutting the program down:

`The program '[8800] API.exe' has exited with code 4294967295 (0xffffffff).`

**Comment by captainsafia** [comment]
@MozharAlhosni Ditto the inquiry above. Do you only run into this when running the app from Visual Studio?

**Comment by karthik9728** [comment]
Similar issue i create .Net 8 API with EF Core version of 8 migration table creation are working but In controller i've used DbContext file to perform CURD operation but it failed application crashed and closes automatically, I tried even try catch block its not even throwing error it directly crash the application 
` [Route("api/[controller]")]
 [ApiController]
 public class EmployeeController : ControllerBase
 {
     private readonly ApplicationDbContext _context;
     public EmployeeController(ApplicationDbContext context)
     {
         _context = context; 
     }

     [HttpPost]
     public ActionResult Create(Employee employee)
     {
         try
         {
             if (!ModelState.IsValid)
             {
                 return BadRequest(ModelState);
             }

             _context.Employee.Add(employee);
             _context.SaveChanges();

             return Ok();
         }
         catch (Exception ex)
         {

             throw ex;
         }
     }
 }`

**Comment by karthik9728** [comment]
I find the issue in my data mode, I've one to one relationship, where i add **new keyword for EmployeeDetails**  when i removed new keyword then its working fine, but still wonder why without giving error or throw exception it simply close the entire application automatically.  

previous code

` public class Employee
 {
     [Key]
     public int EmployeeId { get; set; }

     [Required]
     public string FirstName { get; set; } = string.Empty;

     public string? MiddleName { get; set; } = string.Empty;

     [Required]
     public string LastName { get; set; } = string.Empty;

     [Range(1980,2100,ErrorMessage = "Employed year should be between 1980 to 2100 only")]
     public int EmployedFrom { get; set; }

     //One to One Relationship
     public virtual EmployeeDetails EmployeeDetails { get; set; } = new();
}`

update code 

` public class Employee
 {
     [Key]
     public int EmployeeId { get; set; }

     [Required]
     public string FirstName { get; set; } = string.Empty;

     public string? MiddleName { get; set; } = string.Empty;

     [Required]
     public string LastName { get; set; } = string.Empty;

     [Range(1980,2100,ErrorMessage = "Employed year should be between 1980 to 2100 only")]
     public int EmployedFrom { get; set; }

     //One to One Relationship
     public virtual EmployeeDetails EmployeeDetails { get; set; }
}`

**Comment by captainsafia** [comment]
@karthik9728 Please file a new issue for this feedback since it appears unrelatedly.

Outside of that, it would be good to get a repro project for this bug report or confirmation on the difference in behavior when running via `dotnet run` over Visual Studio <kbd>F5</kbd>.

**Comment by ShiJuuRoku** [comment]
Hi, I faced a similar issue due to proxy.
I have to update the env variable `NO_PROXY=localhost,127.0.0.1`

Or override `HTTP_PROXY=""` and `HTTPS_PROXY=""` into the app profile (_launchSettings.json_)

**Comment by NabeelAfsarDev** [comment]
Has there been a solution this yet? I am running into similiar issue with Swagger UI crashing on .net 8 web api with GET operations that have a big payload (~1.7 mb). API works fine using POSTMAN etc. Just swagger UI crashes. Only happens on GET operations with big payload responses. 
I use DTO objects as well.

Any help would be great!

**Comment by captainsafia** [comment]
Triage update on this: I'm closing this issue out as non-actionable since there's no repro and no additional information about whether this is a VS-specific issue or if it manifests during `dotnet run`. New issues should be filed with clear repros for any other problems.
