### ISSUE TITLE
Unexpected exception: HRESULT 0x8007023e returned at D:\a\_work\1\s\src\Servers\IIS\AspNetCoreModuleV2\InProcessRequestHandler\inprocessapplication.cpp:268 

### ISSUE THREAD

**Issue by imranbaloch** [dotnet/aspnetcore#53036]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

During deploying using shadow copy,  sometimes application stop completely and need to restart IIS app pool to make it run again. 

### Expected Behavior

After shadow copy the application should run instead of showing Application Failed To Start

### Steps To Reproduce

Just deploy the application remotely using shadow copy and sometimes application failed to start especially when there is an internet issue. 

### Exceptions (if any)

Application 'C:\inetpub\MyApp\' was recycled after detecting file change in application directory.

Application 'MACHINE/WEBROOT/APPHOST/MyApp' has shutdown.

Application 'C:\inetpub\ShadowCopyDirectory\585' failed to start. Exception message:

Executable was not found at 'C:\inetpub\ShadowCopyDirectory\585\.\MyApp.API.exe'
Application '/LM/W3SVC/5/ROOT' with physical root 'C:\inetpub\MyApp\' failed to load coreclr. Exception message:

Unexpected exception: HRESULT 0x8007023e returned at D:\a\_work\1\s\src\Servers\IIS\AspNetCoreModuleV2\InProcessRequestHandler\inprocessapplication.cpp:268 

Application '/LM/W3SVC/5/ROOT' with physical root 'C:\inetpub\MyApp\' failed to load coreclr. Exception message:
CLR worker thread exited prematurely

### .NET Version

8.0.100

### Anything else?

App uis using 

```
<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
```

**Comment by BrennanConroy** [comment]
> 'C:\inetpub\ShadowCopyDirectory\585.\MyApp.API.exe'

Is that path correct? The `.` after 585 is suspicious.
Can you share more logs? https://learn.microsoft.com/aspnet/core/host-and-deploy/iis/logging-and-diagnostics?view=aspnetcore-8.0#enhanced-diagnostic-logs

**Comment by imranbaloch** [comment]
Yea the path is correct (hide the actual app name) as I copy pasted this from event viewer.

I don't know when this error will come again so can't share with you logs now. Will keep an eye and update. 
Thanks for the help.
