### ISSUE TITLE
 NavigationException when attempting to navigate after submitting a form #49143  still continue

### ISSUE THREAD

**Issue by SenerDemiral** [dotnet/aspnetcore#53040]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

NavigationException when attempting to navigate after submitting a form
Same at #49143

**Comment by SenerDemiral** [comment]
It is working on without debugging mode.

**Comment by samusaran** [comment]
I have the same issue but without any form.
I'm just navigating to a fake route (that I handle with a catch-all) inside `OnInitializedAsync()`

Running without a debugger solves the issue.

The exception happens here:
```
    protected override void NavigateToCore(string uri, NavigationOptions options)
    {
        Log.RequestingNavigation(_logger, uri, options);

        if (_jsRuntime == null)
        {
            var absoluteUriString = ToAbsoluteUri(uri).ToString();
            throw new NavigationException(absoluteUriString);
        }
```

It seems that `_jsRuntime` is null when a debugger is attached.

**Comment by SenerDemiral** [comment]
Thank you.

**Comment by samusaran** [comment]
I don't think this is closed. There are clearly some regressions/changes to how nav manager works.

I have an entire set of pages that just don't work on NET 8 due to infinite redirects.

Should I create a new ticket then?

Thank you
