### ISSUE TITLE
A way to modify prerendered page html

### ISSUE THREAD

**Issue by SavoInfostream** [dotnet/aspnetcore#53044]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

I was wondering if there is a way to modify html of prerendered page in Blazor .NET 8, before it is sent back as the response.

I know after the initial load it's not possible because Blazor (either WASM or Server) has to rely on HTML integrity so it could modify the view interactively, but since prerendered HTML will get replaced completely it should be technically possible?

Reason I am asking how to modify prerendered content is because I am using Web Components, and without prerendering them as well there's no point in prerendering at all.

**Comment by javiercn** [comment]
@SavoInfostream thanks for contacting us.

It's not super clear what you are trying to achieve, I'm assuming you are talking about prerendering within a Razor Component (not any sort of static prerendering (which we don't do).

If that's the case, and you want to "prerender" web components, your best option is to wrap them in a Razor Component that takes care of the prerendering on the server scenario (you can receive `[CascadingValue] HttpContext` as a parameter to determine when you are in SSR mode).

**Comment by SavoInfostream** [comment]
Hello,
This is a very limiting solution because I can't use Razor syntax in inside the component, like this:
```html
<sp-button>
  @ButtonLabel
</sp-button>
```

That is, there is no way to manipulate RenderFragment from inside the wrap component.

**Comment by SavoInfostream** [comment]
And just to make the issue clear, what I mean by server rendering web components is: write all the needed html in the document so the user won't have to wait for JavaScript to run before components are visible/displayed correctly. Here's an example:

**Single tag**
```html
<my-element>
</my-element>
```

**All necessary elements to display without JS**
```html
<my-element>
    <template shadowrootmode="open">
      <style>
        h1 {
          color: red;
        }

        ::slotted(p) {
          color: green;
        }
      </style>

      <h1>Declarative Shadow DOM</h1>
      <slot></slot>
    </template>

    <p>This is a light DOM</p>
  </my-element>
```
