### ISSUE TITLE
Omit body parameter validation when binding fails

### ISSUE THREAD

**Issue by zdenek-jelinek** [dotnet/aspnetcore#53058]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

We expose public web APIs. We typically supply the integrating parties with OpenAPI schema and examples but it is not possible to cover everything this way. It is expected that integrating parties will make errors during development and they should receive relevant error messages from the APIs.

The framework does very well out of the box in this area but when there is an input formatter binding error with a required action parameter bound from body, the produced error is misleading for a person without access to the code.

Given a default ASP.NET Core 8 app with controllers and the following code:
```csharp
[ApiController]
[Route("[controller]")]
public class PersonsController : ControllerBase
{
    [HttpPost]
    public IActionResult CreatePersonAsync(PersonRequest personRequest)
    {
        return Ok();
    }
}

public class PersonRequest
{
    public required string Name { get; init; }
    public required int Age { get; init; }
}
```
when a request is sent that fails on input formatter, e.g.
```json
{
    "Name": "Dummy Name",
    "Age": "fifty twelve"
}
```
the following error response is produced:
```json
{
    "type": "https://tools.ietf.org/html/rfc9110#section-15.5.1",
    "title": "One or more validation errors occurred.",
    "status": 400,
    "errors": {
        "personRequest": [
            "The personRequest field is required."
        ],
        "$.Age": [
            "The JSON value could not be converted to System.Int32. Path: $.Age | LineNumber: 2 | BytePositionInLine: 25."
        ]
    },
    "traceId": "00-bccf7abe931dc7b3e75bc554de1e028d-c01d345140e95c58-00"
}
```

The second error is completely fine and I'm very happy with it. `"fifty twelve"` is not an int.

But the first error concerning `personRequest` is misleading. I completely understand where this comes from: the action has a non-nullable `personRequest` parameter that was not bound because the json input formatter threw.

However, as an external consumer, this is vexing. There is no `personRequest` field anywhere in the swagger schema, it is a name of an internal parameter. In addition, it is reported first so people who don't read complete error messages may be thrown off in their attempts to resolve the issue.

A similar issue #40202 was raised previously and using `[Required]` with custom message was suggested. As a workaround, this is fine, but in general:
- If a required parameter was missing (e.g. an empty body), I want an error stating that
- If a required parameter was present, I don't want to state that it was missing

The `[Required]` approach does not let me do this, it will produce the same message for both cases, my only option is to make it vague enough to cover both cases which makes the error message useless but at least not misleading. Also, I am a bit afraid that this would become the sole error returned in some scenario and it would bite us back.

### Describe the solution you'd like

I'd prefer if the first error message was not present in this case. That is, if a parameter is bound from body and its binding fails, do not check whether it is required because it will not be present in the model state.

If at all possible, do not include names of parameters bound from body in the validation messages. Note e.g. that if I send an empty body, I get
```json
{
    "type": "https://tools.ietf.org/html/rfc9110#section-15.5.1",
    "title": "One or more validation errors occurred.",
    "status": 400,
    "errors": {
        "": [
            "A non-empty request body is required."
        ],
        "personRequest": [
            "The personRequest field is required."
        ]
    },
    "traceId": "00-fe76178f4a8fba8a9a802b157cbe583b-7d41d63f41d5bfd2-00"
}
```

I'm very happy with that `"": ["A non-empty request body is required."]` error but there's also the `personRequest`.

**Comment by zdenek-jelinek** [comment]
Regarding priority: This has been happening for years now, I don't need this tomorrow. On the other hand, I don't want to be explaining this cryptic error to some grumpy dev 10 years from now.

**Comment by jonasof** [comment]
Hi @zdenek-jelinek, In the last week I've spent some time with the same issue. One thing that seems to solve this is to make the request parameter optional with the nullable operator:

```cs
public IActionResult CreatePersonAsync(PersonRequest? personRequest)
{
  if (personRequest == null)
  {
    return BadRequest();
  }

  return Ok();
}
```

But it seems "ugly" because the request variable is not meant to be optional.

After some debugging, I created a workaround to remove the body parameter from the errors response array by disabling the "isRequired" metadata of the request body parameter:

```cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.ModelBinding.Metadata;
using Microsoft.AspNetCore.Mvc.Routing;

/// <summary>
///   When ImplicitRequiredAttributeForNonNullableReferenceTypes is enabled, the aspnet framework
///   automatically marks the FromBody parameters as required. This is not a problem except that, 
///   when some DTO field is incorrect, the response body comes as:
///   
///   {
///     "errors": {
///   ->  "request": [
///   ->    "The request field is required."
///   ->  ],
///       "someActualMissingJsonParam": [
///         "The input was not valid."
///       ]
///     }
///   }
///   
///   The "The request field is required" error is misleading to the consumers,
///   because it's not an actual JSON property, but the internal request variable name.
///   
///   To remove that error from the response body, this class sets the IsRequired validation metadata to false 
///   when it's coming from the [FromBody] attribute, or when it's coming from a complex field with no 
///   BindingSource attribute (FromQuery, FromPath, ...).
///   
///   That metadata is being set by the aspnet framework at:
/// https://github.com/dotnet/aspnetcore/blob/v6.0.25/src/Mvc/Mvc.DataAnnotations/src/DataAnnotationsMetadataProvider.cs#L412-L415
/// </summary>
public class BodyModelRequiredMetadataRemoverProvider : IValidationMetadataProvider
{
    private readonly ModelMetadataProvider _modelMetadataProvider;

    public BodyModelRequiredMetadataRemoverProvider()
    {
        _modelMetadataProvider = new EmptyModelMetadataProvider();
    }

    public void CreateValidationMetadata(ValidationMetadataProviderContext context)
    {
        if (!IsAParameterFromAControllerAction(context))
        {
            return;
        }

        if (HasFromBodyAttribute(context) || IsModelBeingImplicitlyParsedFromBody(context))
        {
            context.ValidationMetadata.IsRequired = false;
        }
    }

    private bool IsAParameterFromAControllerAction(ValidationMetadataProviderContext context)
    {
        if (context.Key.ParameterInfo == null)
        {
            return false;
        }

        return context.Key.ParameterInfo.Member.CustomAttributes.Any(
            at => at.AttributeType.BaseType?.Equals(typeof(HttpMethodAttribute)) ?? false
        );
    }

    private bool HasFromBodyAttribute(ValidationMetadataProviderContext context)
    {
        return context.Attributes.Any(
            at => at.GetType().Equals(typeof(FromBodyAttribute))
        );
    }

    private bool IsModelBeingImplicitlyParsedFromBody(ValidationMetadataProviderContext context)
    {
        return !HasAnyBindingSourceAttribute(context) && IsComplexType(context);
    }

    /// <summary>
    ///   Checks for other BindingSource attributes like "FromQuery", "FromPath"...
    ///   If they are present, returns false.
    /// 
    ///   This check is needed because for these it's not intended to override IsRequired to false.
    /// </summary>
    private bool HasAnyBindingSourceAttribute(ValidationMetadataProviderContext context)
    {
        return context.Attributes.Any(
            at => at.GetType().GetInterfaces().Any(
                i => i.Equals(typeof(IBindingMetadataProvider))
            )
        );
    }

    /// <summary>
    ///   Checks if the model being validated is from a complex type.
    ///
    ///   It's needed because the DTO classes with multiple attributes are considered complex types, 
    ///   for they we want to omit the errors in the response.
    /// 
    ///   But for the simple types, like int, string... Is not intended to hide them from the response errors.
    /// </summary>
    private bool IsComplexType(ValidationMetadataProviderContext context)
    {
        return _modelMetadataProvider.GetMetadataForType(context.Key.ModelType).IsComplexType;
    }
}
```

Then add it in the controllers option "ModelMetadataDetailsProviders":

```cs
builder.Services.AddControllers((options) => options.ModelMetadataDetailsProviders.Add(new BodyModelRequiredMetadataRemoverProvider()))
```

Now the output is:

```json
{
   "errors": {
      "someActualMissingJsonParam": [
         "The input was not valid."
       ]
    }
 }
```

Instead of:

```json
{
  "errors": {
    "request": [
      "The request field is required."
    ],
    "someActualMissingJsonParam": [
      "The input was not valid."
    ]
  }
}
```

As I said it's a workaround, I haven't tested all the scenarios but it worked as expected so far. 

I think a proper option to omit those error messages in the asp.net core framework is needed. As you mentioned, returning the internal variable name is misleading to the API consumers.

**Comment by captainsafia** [comment]
@jonasof Thanks for sharing your workarounds here.

Another possible option is to to implement a custom `ValidationProblemDetails` response object that is returned directly from the action when the model state is invalid.

You can also create a custom implementation of the `ProblemDetailsFactory` to modify the return objects as needed. See [here](https://learn.microsoft.com/en-us/aspnet/core/web-api/handle-errors?view=aspnetcore-7.0#implement-problemdetailsfactory) for more info.

Given the complex nature of MVC's model binding/validation layer, I dunno that we would change the built-in behavior here or add a specific flag for this. But I think the customization options that exist can help with this.

**Comment by zdenek-jelinek** [comment]
Thank you for your response and the proposed workaround.

Unfortunately, I think what you proposed with checking model state and returning custom response goes against the web API story with features like [ApiController]/ModelStateInvalidFilter. If I had to go to every controller to adjust this, I'd rather just make the request optional and add a custom attribute + schema filter for swashbuckle to show them as required in the swagger doc than to write model state checks everywhere.

The custom ProblemDetailsFactory, I think will need a lot of work to detect these cases reliably. Not to mention that the original type is internal so I'd have to reimplement it and keep it up to date with each release. This does not seem like a good trade-off to me.

I think the idea of @jonasof fits really well with the existing conventions model and also reflects the exact requirements/conventions for the case. I'll consider it if the official answer is negative.

As already stated, I'm in no hurry to have this but I'd be really glad if the validation story got more polished so that we don't have to debug and hack together a bunch of workarounds to get a world class web API.
