### ISSUE TITLE
Blazor Standalone Webassembly - Has no way to call Azure B2C edit profile user flow

### ISSUE THREAD

**Issue by migoldfinger** [dotnet/aspnetcore#53084]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I created an Blazor Webassembly and 2 User Flows in Azure B2C (signupsignin, editprofile).
After the user logged in the application checks if all needed claims are actually received and have sane values. If that check fails the user should be redirected to the edit profile page with the editprofile User Flow.
However, in all Templates and Examples I did not find any way to achive this very basic requirement.

### Describe the solution you'd like

I want a way to define the userflow for editprofile in the appsettings and then use something like `Navigation.NavigateTo(RemoteAuthenticationDefaults.ProfilePath);` to call the edit profile page.

**Comment by javiercn** [comment]
@migoldfinger thanks for contacting us.

This is not supported in the underlying MSAL library implementation that we use. The way B2C lets you manage the profile is not compatible with the `ProfilePath` which is meant to be a simple URL to navigate for editing user details. For B2C you need to do an auth flow.

**Comment by migoldfinger** [comment]
@javiercn  Can this be achieved any other way? Since this is a showstopper for me.

**Comment by migoldfinger** [comment]
Just to be complete, since I was trying to make this happen somehow.
I might found a way that includes 2 apps where the 2nd app is using the edit profile userflow and instantly redirecting to the 1st app. However, it is nearly impossible to debug both apps on the same machine and see what is happening under the hood and it feels a bit bumpy. Also this could fail if there are multiple accounts accessing the app from the same machine.

My 2 cents to the provided "answer":
In what reality is that answer a resolution?

The provided answer is inacceptable at best and renders the whole blazor standalone webassembly thing useless.
For any sso application to be unable to redirect to a profile editing page is a showstopper, period.

Also, this was not a bug that can be answered with "does not work".
This was a feature request. A feature that should have been already added yesterday.
Even if the used MSAL library does not support this. Then the first step should be to make the MSAL library support this,
we are in the year 2024 how are we supposed to use blazor if such fundamental functionality is missing.
At this point blazor is a nice plaything for microprojects at best that does not have a need for user profiles.
For the looks of it I will have to go back to ASP.net for the Online management system I am planning, since the functionality I need is there for years, there is not even the need to code it myself since the VS Template already covers it.
The only downside is that the apps will not have the fresh native app like look and feel I was hoping to achieve when using blazor.
