### ISSUE TITLE
How to bind a complex string type to Checkbox in Blazor?

### ISSUE THREAD

**Issue by skillmaker-dev** [dotnet/aspnetcore#53083]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm trying to bind a complex string value 'True' or 'False' to a checkbox i tried both these ways but neither seem to work:

### Expected Behavior

I want to be able to bind the string value to the checkbox in an EditForm inside a foreach loop

### Steps To Reproduce

**First Way:**

```
<EditForm Model="@Wrapper" FormName="BlogSettings" OnValidSubmit="@SaveBlogSettingsAsync" style="width: 100%" novalidate>
<DataAnnotationsValidator />

    @foreach(var item in Wrapper.BlogSettings)
    {
        <div>
        @if (item.Value.ToLower().Contains("true") | item.Value.ToLower().Contains("false"))
        {
                <InputCheckbox Value=@(Convert.ToBoolean(item.Value)) ValueChanged=@((v) => item.Value = v.ToString()) Label="@(Enum.GetName(item.Setting))" />
            }
            else
            {
            <FluentTextField Label="@(Enum.GetName(item.Setting))" TextFieldType="@TextFieldType.Text" @bind-Value="item.Value" Style="width: 100%" />                    
            }
     </div>
        
    }
     <FluentButton Type="@ButtonType.Submit" Style="width: 100%;  margin-top: 2rem;" Appearance="Appearance.Accent">Save</FluentButton>

</EditForm>
```

`InvalidOperationException: Microsoft.AspNetCore.Components.Forms.InputCheckbox requires a value for the 'ValueExpression' parameter. Normally this is provided automatically when using 'bind-Value'.`

**Second Way:**

```
<InputCheckbox @bind-Value:get="bool.Parse(item.Value)" @bind-Value:set="(val) => {item.Value = val.ToString();}" Label="@(Enum.GetName(item.Setting))" />
```

`ArgumentException: The provided expression contains a MethodCallExpression1 which is not supported. FieldIdentifier only supports simple member accessors (fields, properties) of an object.`

`BlogSettings.razor.cs` :

    partial class BlogSettings
    {
        [SupplyParameterFromForm(FormName = "BlogSettings")]
        public BlogSettingsWrapper Wrapper { get; set; } = new();
    
        [Inject]
        public ISettingsService SettingsService { get; set; }
        private async Task SaveBlogSettingsAsync()
        {
            await SettingsService.SaveSettingsAsync(Wrapper.BlogSettings);
        }
    
        protected override void OnInitialized()
        {
            Wrapper.BlogSettings = SettingsService.GetSettings().OrderBy(bs => bs.Setting).ToList();          
        }
        public class BlogSettingsWrapper
        {
            public ICollection<BlogSetting> BlogSettings { get; set; } = [];
        }
    }

`BlogSetting.cs` :

    public class BlogSetting : BaseEntity
    {
        public Setting Setting { get; set; }
        public string Value { get; set; } = string.Empty;
        public string Description { get; set; } = string.Empty;
    }

### .NET Version

8.0.1

**Comment by javiercn** [comment]
@skillmaker-dev thanks for contacting us.

InputCheckbox is for boolean values only. You need to either create your own version inheriting from `InputBase` or use a plain input element instead.
