### ISSUE TITLE
MultipartFormDataContent with CancellationToken Error

### ISSUE THREAD

**Issue by GLuca74** [dotnet/aspnetcore#53092]
I am trying to implement a `MultipartFormData` request in a `WebApi`. Simplifying, it seems that if in the `webapi `there is the `CancellationToken `parameter, the `MultipartReader.ReadNextSectionAsync()` calls faills with the message :
`System.IO.IOException: Unexpected end of Stream, the content may have already been read by another component.`
If I remove the `cancellationToken` paraeter all works without problems.
I attach a simply solution with a server and a client project that show the behavour.
The server has two actions :
```
		[HttpPost]
		[Route(nameof(UploadLargeFile))]
		[DisableRequestSizeLimitAttribute()]
		[DisableFormValueModelBindingAttribute]
		public async Task<IActionResult> UploadLargeFile()
		{
			var boundary = Request.GetMultipartBoundary();
			var reader = new MultipartReader(boundary, Request.Body);
			var section = await reader.ReadNextSectionAsync();
			while (section != null)
				section = await reader.ReadNextSectionAsync();

			return Ok();
		}

```
and

```
		[HttpPost]
		[Route(nameof(UploadLargeFileCancel))]
		[DisableRequestSizeLimitAttribute()]
		[DisableFormValueModelBindingAttribute]
		public async Task<IActionResult> UploadLargeFileCancel(CancellationToken cancellationToken)
		{
			var boundary = Request.GetMultipartBoundary();
			var reader = new MultipartReader(boundary, Request.Body);
			var section = await reader.ReadNextSectionAsync(cancellationToken);// Exception
			while (section != null)
				section = await reader.ReadNextSectionAsync(cancellationToken);
			return Ok();
		}

```
this two actions are equal except for the `cancellationToken`.

Originally, my(true) webapi action expected only one file and all worked without problems, now I have to extend the action to manage multiple files so a `MultipartFormDataContent` and I need to keep the `cancellationToken`.

the client simply call the two actions.

How can I fix?

Many thanks

[ErrorMultipart.zip](https://github.com/dotnet/aspnetcore/files/13812636/ErrorMultipart.zip)

**Comment by BrennanConroy** [comment]
Is the client closing the connection before getting a response? That cancellation token should normally be triggered when the client goes away.

If you want to provide a repro project please follow the guidelines: https://github.com/dotnet/aspnetcore/blob/main/docs/repro.md (mainly, put the project in a github repository, not a zip file)

**Comment by GLuca74** [comment]
this is the github repository:
https://github.com/GLuca74/ErrorMultipart
the client remain waiting the response, it not close the connection. Also, if I remove the cancellationToken from the read of the next section(`reader.ReadNextSectionAsync();`), the exception still raise. just removing the cancellationToken from the webApi Action let the action back to work

**Comment by BrennanConroy** [comment]
Add `factories.RemoveType<FormFileValueProviderFactory>();` to your attribute.

**Comment by GLuca74** [comment]
Thanks @BrennanConroy , adding `factories.RemoveType<FormFileValueProviderFactory>();` works.
About this attribute, where can I read wath it actually do? This webapi action is very critical, and I am introducing code that i not know, where i can read wath impact may have on performace or possible side effects?
Thank you

**Comment by BrennanConroy** [comment]
Looks like you were 90% there, it even looks like you had copied most of the code from the sample o.O
https://learn.microsoft.com/aspnet/core/mvc/models/file-uploads?view=aspnetcore-8.0#upload-large-files-with-streaming
