### ISSUE TITLE
[Infrastructure] get-version fails on our CI because node is not installed by the CI pipeline.

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#53091]
https://dev.azure.com/dnceng/internal/_build/results?buildId=2341287&view=results

The issue is that nodejs is not installed, so when we run npm run get-version, the command fails. We need to make sure that node is installed and `npm ci` is run or find an alternative way to collect the package versions for npm packages.

We can either do this in node, or get all the `package.json` files in the build and read them to get the version.

As a workaround, we simply flow the version from the build system as in https://github.com/dotnet/aspnetcore/commit/e6be3e95fec33ca3a3b576df4b265ead680a91a0 which is ok because we aren't producing individual versions for our packages, but it risks not being correct now or in the future.

**Comment by wtgodbe** [comment]
Is there a reason we need to get the npm package versions other than using it in /eng/publishing.props? Because if it's the latter, we can just choose a different project - originally the choice of an .npmproj was somewhat arbitrary.
