### ISSUE TITLE
FormFeature initialized with an IFormCollection instance throws NullReferenceException in Form property getter

### ISSUE THREAD

**Issue by johatuni** [dotnet/aspnetcore#53099]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When the FormFeature type is constructed with an IFormCollection instance, the internal field _request is initialized to "default!" (null) in the ctor. When later accessing the Form property, a NullReferenceException is thrown from inside the private ResolveHasInvalidAntiforgeryValidationFeature() method, since it does not have a null guard for the _request field.

![image](https://github.com/dotnet/aspnetcore/assets/110810564/a1fb9af0-394c-4719-a24d-5914f28ce11e)

### Expected Behavior

The Form property should in this case return the IFormCollection used when constructing the instance of the FormFeature.

### Exceptions (if any)

NullReferenceException

### .NET Version

8

**Comment by captainsafia** [comment]
@johatuni Thanks for opening this issue! Would you be interested in opening a PR to resolve this issue? Should be a matter of adding an null check to `ResolveHasInvalidAntiforgeryValidationFeature`.

**Comment by iam-black** [comment]
Are there any workarounds for this issue?

**Comment by johatuni** [comment]
> Are there any workarounds for this issue?

I changed my logic so that my controller unit tests could operate on an IFormCollection instance instead of a mock of the Request.Form property.
