### ISSUE TITLE
HttpRequest.QueryString not correctly build after decoding

### ISSUE THREAD

**Issue by antoineatrhea** [dotnet/aspnetcore#53110]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The QueryString property of the HttpRequest is not correctly set after the decoding of the URL.

### Expected Behavior

Running a GET query like http://localhost:5000/SiteDirectory%3Fextent=deep&includeReferenceData=false should set the QueryString property to "?extent=deep&includeReferenceData=false" but is set to ""

### Steps To Reproduce

- From POSTMAN, run any GET query against an Endpoint with some QueryString where the "?" is encoded as "%3F" (example  http://localhost:5000/SiteDirectory%3Fextent=deep&includeReferenceData=false)
- Check that the URL is correctly decoded but that the QueryString property of the HttpRequest is empty 
![293903541-02d24e55-524b-4b03-bde9-49afece87c32](https://github.com/dotnet/aspnetcore/assets/97221392/02e86242-a1f0-4b3e-9e49-35ca1ac19553)
- Run the same query with the "?" (example http://localhost:5000/SiteDirectory?extent=deep&includeReferenceData=false)
- Check that the URL is correctly decoded but that the QueryString property of the HttpRequest is not empty 
![293903713-e65fb535-05ab-499b-a7f9-f6e4a6000266](https://github.com/dotnet/aspnetcore/assets/97221392/8138db2a-daa8-4cf5-9151-572995be116f)

### .NET Version

8.0.100

### Anything else?

Here is an open issue on one of our project where we face the issue: https://github.com/RHEAGROUP/DEH-Capella/issues/82

**Comment by Tratcher** [comment]
This is working per spec. When the '?' is escaped it does not separate the path from the query, it's considered part of the path. part separation (scheme, host, path, query) happens before decoding, not after, otherwise there'd be no way to include the separators encoded in the values.

If the '?' wasn't intended as part of the path then the client should not have encoded it.

**Comment by antoineatrhea** [comment]
@Tratcher Thanks for your reply, wasn't aware of that spec ! I guess the issue can be closed if working as expected
