### ISSUE TITLE
Injecting DBContext in Validation Attribute randomly throws error: "Cannot access a disposed context instance"

### ISSUE THREAD

**Issue by sipi41** [dotnet/aspnetcore#53114]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I created a validation attribute that uses something like `db = (MyDbContext)validationContext                                        .GetService(typeof(MyDbContext));` to get the dbcontext injected, the problem is that it randomly throws an error saying that the dbcontext has been disposed, I injected the service in the constructor and also check if dbcontext is null, and if so, it try to create a new instance of the dbcontext, and sometimes works sometimes it does not... please check my code below and the error received on blazor.

```
public class ConstraintsV2_Require_Resolution : ValidationAttribute
    {

        private MyDbContext db { get; set; }


        private void CreateContext(ValidationContext validationContext)
        {
            db = (MyDbContext)validationContext.GetService(typeof(MyDbContext));
        }        
        protected override ValidationResult? IsValid(object? value, ValidationContext validationContext)
        {            
            FACT_Constraint_v2 fACT_Constraint_V2 = (FACT_Constraint_v2)validationContext.ObjectInstance;

            if (value == null)
            {
                
                if (db == null) CreateContext(validationContext); //db context 
//------------------------- NEXT LINE IS WHERE ERROR IS PRODUCED
                DIM_STATUS currentStatus = db.Dim_Statuses.FirstOrDefault(f => f.status_guid == fACT_Constraint_V2.status_guid);
//------------------------- 
                if (currentStatus != null)
                {
                    if (currentStatus.status.Contains("COMPLETE", StringComparison.CurrentCultureIgnoreCase))
                    {
                        return new ValidationResult("If Status is \"COMPLETE\" a Resolution must be provided.", new List<string>() { validationContext.MemberName });
                    }
                }
            }

            return ValidationResult.Success;

        }
    }
```

![image](https://github.com/dotnet/aspnetcore/assets/688562/fa289769-fb79-44cb-aeaf-90cde101656b)

### Expected Behavior

Expected behavior should be to keep the instance of dbcontext I made, not to return a disposed object.

### Exceptions (if any)

![image](https://github.com/dotnet/aspnetcore/assets/688562/b9f76813-c64c-44e0-8e31-9fc0fbdfff25)

### .NET Version

7

**Comment by javiercn** [comment]
@sipi41 thanks for contacting us.

Instead of injecting the DbContext you should inject a DbContextFactory and create an instance per validation request. It's not clear what's going on in your code, but this is likely a problem with your usage of DbContext in this scenario.

**Comment by sipi41** [comment]
Thank you @javiercn, I will try that, I do have the context factory also but I suspect if I do that, it will also be disposed the same way... I will post after trying.

**Comment by sipi41** [comment]
This IS NOT resolved
