### ISSUE TITLE
API converts SCREAMING_SNAKE_CASE to screaminG_SNAKE_CASE

### ISSUE THREAD

**Issue by JacobIhle** [dotnet/aspnetcore#53126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In a ASP.NET Core WebAPI, returning a model where the attribute names are SCREAMING_SNAKE_CASE instead returns the attribute names as screaminG_SNAKE_CASE. Where only the last letter of the first word is capitalized, and every other word is also capitalized.

### Expected Behavior

That it returns a conventional casing standard. If the attribute names are Snake_Case_Variable, it could for example return snake_Case_Variable.

### Steps To Reproduce

Clone the following repo:
https://github.com/JacobIhle/SCREAMING_SNAKE_CASE_BUG

The repo contains two projects identical projects except that one is for .net6 and the other for .net8. 
Run on of the projects, which will open the API in swagger, run the API and check the attribute names of the response,.

This is a standard project created with visual studio using the ASP.NET Core Web API project template. All I've done is alter the name of the attributes of the weather forecast model.

### .NET Version

6.0.320, 8.0.100

**Comment by BrennanConroy** [comment]
Looks like that is expected
https://github.com/dotnet/runtime/issues/46445

**Comment by JacobIhle** [comment]
Understood.
 
Thanks for the follow up! 
Easy enough fix to set JsonSerializerOptions.PropertyNamingPolicy = null; to have it not alter the formatting.
