### ISSUE TITLE
[Blazor WebApp] RenderMode InteractiveAuto and Could not reconnect to the server message

### ISSUE THREAD

**Issue by mohaaron** [dotnet/aspnetcore#53120]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am using the new Blazor WebApp template using render mode InteractiveAuto globally and am getting the SignalR reconnect message even when I'm showing that the components are running in WASM. Was I wrong to think that once the render mode changed from Server to WASM that the server reconnect would not happen anymore? I was hoping that using the new WebApp template would help with the server reconnection issues.

There is some discussion [here](https://github.com/dotnet/aspnetcore/issues/49401) regarding how to test for the current render mode. Is the code below not a good test?

```
protected override void OnInitialized()
{
    if (OperatingSystem.IsBrowser())
    {
        currentRenderMode = "WASM";
    }
    else
    {
        currentRenderMode = "Server";
    }
}
```
![image](https://github.com/dotnet/aspnetcore/assets/1719598/1402c34b-4208-4c7d-b47c-ff5a237dc13f)

### Expected Behavior

Once the render mode has automatically changed to WASM there would no longer be reconnection required due to the SignalR connection not being needed.

### Steps To Reproduce

Let a running WebApp sit idle until the reconnection message appears.

### .NET Version

8.0.100

**Comment by mohaaron** [comment]
I wonder, does this have something to do with the OIDC authentication that's happening on the server side of the app and is somehow keeping a SignalR connection open?

![image](https://github.com/dotnet/aspnetcore/assets/1719598/f1c6e022-7d5e-4167-b448-6ce2b495d28c)

**Comment by mohaaron** [comment]
I have the Github repo [here](https://github.com/mohaaron/CustomAuthorizationHandler) that I've been using to understand how authorization works in the new WebApp template, but it's not having the same SignalR reconnect issue as my other project which I have pictured here. The project having this problem is not something I can share. Does anyone have some idea why the WebApp template would have this issue? It feels to me like maybe the authorization or something is hanging on to the SignalR connection and it's preventing 100% of the functionality from moving over to using the WASM components.

**Comment by MackinnonBuck** [comment]
Thanks for reaching out. We have some auto mode improvements coming in .NET 8.0.200, but until then, could you please try the applying the fix manually as described in [this comment](https://github.com/dotnet/aspnetcore/issues/52154#issuecomment-1843535849) and see if it resolves your issue?

**Comment by mohaaron** [comment]
> Thanks for reaching out. We have some auto mode improvements coming in .NET 8.0.200, but until then, could you please try the applying the fix manually as described in [this comment](https://github.com/dotnet/aspnetcore/issues/52154#issuecomment-1843535849) and see if it resolves your issue?

Hi Buck, I appreciate your response. I will check into what you have suggested and response here with the results.

Thank you
