### ISSUE TITLE
Dotnet 8.0 issue on app with mixed razor and blazor

### ISSUE THREAD

**Issue by hagaygo** [dotnet/aspnetcore#53133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a little working dotnet 6.0 app which uses mostly razor views with controllers.

Some views have a blazor component (server side) which works just fine.

I render it using RenderComponentAsync , basically like :

````
@(await Html.RenderComponentAsync<Counter>(RenderMode.Server))
````

inside the cshtml file.

### Expected Behavior

When upgrading my app to dotnet 8.0 , nothing is rendered.

When i change my code to 

````
@(await Html.RenderComponentAsync<Counter>(RenderMode.ServerPrerendered))
````

The component is rendered , but of course it is not interactive.

I easily reproduced this issue by using the default new dotnet 8.0 blazor template , added a test controller and a view and used the code above to try to render the Counter component.

Is it not supported anymore on dotnet 8.0 ? do i need to add something in order to make it work ?

### .NET Version

8.0.0

**Comment by hagaygo** [comment]
Created a github repo as requested with a simple app based on the generic blazor template on 

https://github.com/hagaygo/BlazorRenderTest

To reproduce the issue :

Click on the new menu link called "Razor counter" , click on the button and counter increased fine.

Change the app to target dotnet 8 , rerun the app and the counter is no longer rendered.

**Comment by javiercn** [comment]
@hagaygo thanks for contacting us.

The issue is that you are loading the blazor script on the head, before any content is on the page 
https://github.com/hagaygo/BlazorRenderTest/blob/master/Views/Shared/_Layout.cshtml#L3

If you either move the script to the bottom near the `</body>` tag or use `defer` on the script, the issue goes away.

**Comment by hagaygo** [comment]
Thank you for your help.

This change works also on my real application.

While this fix the issue for dotnet 8, on dotnet 6 it worked fine without this change, it would have been better throw some error for this kinda of "mistake" on  dotnet 8.
