### ISSUE TITLE
Blazor custom router is broken on .Net 8

### ISSUE THREAD

**Issue by raphadesa** [dotnet/aspnetcore#53135]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm trying to upgrade Chris Sainty Blazor router to .NET 8.

https://chrissainty.com/routing/

While uprading all stuff to interactive server from the template (new program.cs, new router, new App.razor) I am facing a 404 error while running the project.

Does anybody know how can I make it work ?

I have a large .NET 7 project that I want to upgrade to .NET 8 but I got stuck with that problem !

Many thanks,

Raphaël

**Comment by javiercn** [comment]
@raphadesa thanks for contacting us.

You need to integrate with routing server-side too using ASP.NET Core dynamic routing. Here is an example https://github.com/javiercn/DynamicRoutingBlazor

**Comment by raphadesa** [comment]
Thanks a lot Javier, I will give it a try !!!

**Comment by sbwalker** [comment]
@raphadesa Oqtane uses a custom router on .NET 8:

**Comment by sbwalker** [comment]
@raphadesa Oqtane uses a custom router with .NET 8:

https://github.com/oqtane/oqtane.framework/blob/dev/Oqtane.Client/UI/SiteRouter.razor

However it required the addition of a custom endpoint route builder:

https://github.com/oqtane/oqtane.framework/blob/dev/Oqtane.Server/Extensions/ComponentEndpointRouteBuilderExtensions.cs

which is declared in startup:

```
            // simulate the fallback routing approach of traditional Blazor - allowing the custom SiteRouter to handle all routing concerns
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
                endpoints.MapRazorPages();
                endpoints.MapFallback();
            });
```

**Comment by raphadesa** [comment]
Hello,

Thanks for your support, I ended up with this code :

@page "/{*pageRoute:nonfile}"
@inject WebSiteService webSiteService
@inject NavigationManager navigationManager

<CascadingValue Value="pageRoute">
    @DynamicComponent
</CascadingValue>

@code {
    [Parameter]
    public string pageRoute { get; set; }
    private RenderFragment DynamicComponent { get; set; }
    List<RouteVM> routes { get; set; }
    string tmpUrl {get;set;} 
    bool isFound { get; set; }
    protected override async Task OnInitializedAsync()
    {
        routes = await webSiteService.getRoutes();
    }
    protected override void OnParametersSet()
    {                
        var route = routes.FirstOrDefault(c => c.page == "/" + pageRoute);            
        
         DynamicComponent = builder =>
        {
            builder.OpenComponent(0, Type.GetType($"eCommerce.Client.Components.Pages.{(route!=null ? route.componentName : "NotFound")}"));
            builder.CloseComponent();

        };                        
        
      }      
    }       
}

**Comment by sbwalker** [comment]
@raphadesa so you are saying that the:

@page "/{*pageRoute:nonfile}"

Is interpreted as a fallback route… brilliant! This simplifies things significantly.

**Comment by raphadesa** [comment]
@sbwalker Yes, and it's a trival way to implement Url Rewriting... Really love the KIS (Keep it Simple) coding style !!!!

**Comment by burtonrodman** [comment]
Here's what I ended up with... more "codeish", less "componentish", but same mechanism.

```
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Rendering;

namespace BlazorCMSRouter.Rendering;

[Route("/{*pageRoute:nonfile}")]
public class PageContentRenderer : ComponentBase 
{
  [Parameter]
  public string pageRoute { get; set; }

  protected override void BuildRenderTree(RenderTreeBuilder builder)
  {
    // TODO - resolve route from database and render the content
    builder.AddMarkupContent(0, $"<p>start page - {pageRoute}</p>");
    builder.AddMarkupContent(0, "<p><a href='/'>Home</a></p>");
    builder.AddMarkupContent(0, "<p><a href='/blah'>blah - WORKS, YAY!!!</a></p>");
    builder.AddMarkupContent(0, "<p><a href='/weather'>Weather</a></p>");
    builder.AddMarkupContent(0, "<p><a href='/counter'>Counter</a></p>");
    builder.AddMarkupContent(0, "<p>end page</p>");
  }
}
```

**Comment by raphadesa** [comment]
Yes, it’s the easiest way to perform custom url rewriting which can be used with the existing Blazor router. Happy coding folks !
________________________________
De : Burton Rodman ***@***.***>
Envoyé : Wednesday, May 1, 2024 6:49:05 PM
À : dotnet/aspnetcore ***@***.***>
Cc : Raphaël Desalbres ***@***.***>; Mention ***@***.***>
Objet : Re: [dotnet/aspnetcore] Blazor custom router is broken on .Net 8 (Issue #53135)


Here's what I ended up with... more "codeish", less "componentish", but same mechanism.

using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Rendering;

namespace BlazorCMSRouter.Rendering;

[Route("/{*pageRoute:nonfile}")]
public class PageContentRenderer : ComponentBase
{
  [Parameter]
  public string pageRoute { get; set; }

  protected override void BuildRenderTree(RenderTreeBuilder builder)
  {
    // TODO - resolve route from database and render the content
    builder.AddMarkupContent(0, $"<p>start page - {pageRoute}</p>");
    builder.AddMarkupContent(0, "<p><a href='/'>Home</a></p>");
    builder.AddMarkupContent(0, "<p><a href='/blah'>blah - WORKS, YAY!!!</a></p>");
    builder.AddMarkupContent(0, "<p><a href='/weather'>Weather</a></p>");
    builder.AddMarkupContent(0, "<p><a href='/counter'>Counter</a></p>");
    builder.AddMarkupContent(0, "<p>end page</p>");
  }
}

**Comment by PSCourtney** [comment]
pageRoute for me always returns null. Whereas in .NET 6 it always would return a value. 

![.NET 6.0 working](https://github.com/dotnet/aspnetcore/assets/23056141/53480231-a6c6-4ee1-8c38-d8a5fca311b2)


![.NET 8.0 returns null](https://github.com/dotnet/aspnetcore/assets/23056141/98507cfb-e0e0-45ad-9e02-39c1f1d93356)



What gives.
