### ISSUE TITLE
.NET8 routing with UrlEncode(url) in parameter does not work

### ISSUE THREAD

**Issue by TDroogers** [dotnet/aspnetcore#53138]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After updating from .NET7 (blazor server) to .NET8 the routing has broken.
On project A (still on .NET7) I forward to project B (.NET8)
```
var returnUrl = HttpUtility.UrlEncode("https://localhost:5001/authentication/login-callback");
Navigation.NavigateTo($"{url}/login/{returnUrl}");
```
returnUrl == `https%3a%2f%2flocalhost%3a5001%2fauthentication%2flogin-callback`

project B
```
@page "/login/{LoginUrl}"
```
url is not changed in the process `https://localhost:44322/login/https%3a%2f%2flocalhost%3a5001%2fauthentication%2flogin-callback`

However on project B I'm now forwarded to the 404 page.
If I change {returnUrl} to a non url like "text" I get on the page and the parameter gets the "text"

### Expected Behavior

Should work like in .NET7
Encoded url should be read as a parameter and not forwarded to 404

### Steps To Reproduce

See Describe the bug

### Exceptions (if any)

No

### .NET Version

8.0.100

### Anything else?

Same issue in azure after deployment in release mode.

~I have also tried adding some more optional paramaters, `@page "/login/{LoginUrl}/{Test1?}/{Test2?}/{Test3?}"` but I still got forwarded tot the 404~

**Comment by TDroogers** [comment]
I have added a second project in .NET7 in the same solution to prove the issue is new in .NET 8

**Comment by TDroogers** [comment]
I did some more investigation and the problem is that the encoded slash `%2F` is the problem. I have updated the reproduction project.

https://github.com/TDroogers/BugUrlRouting/commit/e9ee2fb2fc8858498aee2f6a1ef09e4b03795dce

My guess is that something goes wrong in the order of decoding the url and the decision what path to use.

**Comment by mtavares628** [comment]
I can also confirm that I have run into this same issue after upgrading my .NET 7 Blazor Server project to .NET 8.

**Comment by TDroogers** [comment]
Seems like an reincarnation of issue #28965 witch was fixed in #33364

**Comment by javiercn** [comment]
@TDroogers thanks for your patience.

I think I've tracked this down to this change https://github.com/dotnet/aspnetcore/blob/main/src/Components/Components/src/Routing/RouteContext.cs#L14 where we were previously splitting every segment and the URL decoding that and now we are URL decoding the entire path

The previous version of the code is `https://github.com/dotnet/aspnetcore/blob/771532a3a31e8df2811a6201a2d3850a4171de15/src/Components/Components/src/Routing/RouteContext.cs`

**Comment by javiercn** [comment]
Removing the decoding step makes the scenario "work consistently" across all the implementations, but I suspect there's more work to do or else we will break other scenarios.

SSR: Click on link ->                 Url: `https:%2f%2flocalhost:5001%2fauthentication%2flogin-callback`
Interactive Server click on link ->   Url: `https%3a%2f%2flocalhost%3a5001%2fauthentication%2flogin-callback`
Interactive Server click on button -> Url: `https%3a%2f%2flocalhost%3a5001%2fauthentication%2flogin-callback`

**Comment by TDroogers** [comment]
Thanks for your response!

**Comment by javiercn** [comment]
https://github.com/dotnet/aspnetcore/pull/53470 This is now fixed in main and we'll probably backport it to 8.0 in a future patch

**Comment by mtavares628** [comment]
@javiercn Thanks for fixing this.  Do you have an idea of when that 8.0 patch will be deployed?  This bug is preventing me from upgrading my project to 8.0 because a lot of my navigation encodes a return url in the querystring.

**Comment by mkArtakMSFT** [comment]
> @javiercn Thanks for fixing this. Do you have an idea of when that 8.0 patch will be deployed? This bug is preventing me from upgrading my project to 8.0 because a lot of my navigation encodes a return url in the querystring.

@mtavares628 we're probably looking to including this as part of the 8.0.3 release.
In the meantime, it would help if you could try out our nightly builds to confirm if the fix (in main) has addressed the issue you were facing.

**Comment by mtavares628** [comment]
@mkArtakMSFT What are the steps for targeting the nightly build in my project?  I downloaded and installed the latest nightly build of the SDK for .NET 9, but when I try to change the target on my project, .NET 9 isn't listed as an option.  Is there something that I'm missing to get this running?

**Comment by mkArtakMSFT** [comment]
Thanks for giving this a try, @mtavares628.
The guidance [here](https://github.com/dotnet/installer?tab=readme-ov-file#installers-and-binaries) includes information about the feeds to configure. Make sure you configure .NET 9 feeds. Basically, you create a `nuget.config` file with the content shown there and place it in the root of your project /solution.
Also make sure you update your project's .csproj file to have `<TargetFramework>net9.0</TargetFramework>`.

The option doesn't show up in the VS because most probably you are not using the latest VS preview which is required for the latest preview .NET SDKs.

**Comment by mtavares628** [comment]
Thanks @mkArtakMSFT, I was able to test it out and confirm that fix solves my problem.  Is there a general time frame planned for the 8.0.3 release?

**Comment by mkArtakMSFT** [comment]
Thanks for confirming this, @mtavares628. Most probably yes - 8.0.3. In the worst case - 8.0.4, but hopefully it won't get to that.
