### ISSUE TITLE
NavigationManager.NavigateToLogout() stuck on authentication/logout-callback after upgrade to dotnet 8

### ISSUE THREAD

**Issue by yuominae** [dotnet/aspnetcore#53131]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a dotnet-hosted blazor wasm project that I have been developing since dotnet 6. Auth is done using duende identity server with locally stored user accounts, based on the way it was done at the time I started the project.

The project was migrated to dotnet 7 about a year ago and was running in production without problems until I recently upgraded it to dotnet 8. After upgrading, the logout process gets stuck at authentication/logout-callback page with the message "processing logout callback...". Manually navigating back to "/" gets things unstuck, but previously the redirection to "/" was happening automatically. Getting stuck on logout is not optimal for the users.
The interesting part is that when I run the app in debug mode on my local environment everything works fine. The problem occurs when the app is hosted in the azure app service.

Auth is configured in the api project in the following way

```csharp
_ = services.AddDefaultIdentity<IdentityUser>(options =>
                {
                    options.SignIn.RequireConfirmedEmail = false;

                    options.SignIn.RequireConfirmedAccount = false;
                }).AddRoles<IdentityRole>()
                .AddRoleManager<RoleManager<IdentityRole>>()
                .AddEntityFrameworkStores<MycoAuthDbContext>();

            services.AddIdentityServer()
                .AddApiAuthorization<IdentityUser, MycoAuthDbContext>();

            services.AddTransient<IProfileService, ProfileService>();

            _ = JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Remove("role");

            services.AddAuthentication()
                    .AddIdentityServerJwt();

            services.AddAuthorization(options =>
            {
                foreach (var policy in Policies.GetAll())
                {
                    if (policy.HasRoles)
                    {
                        options.AddPolicy(policy.Name, apb => apb.RequireRole(policy.Roles));
                    }

                    if (policy.HasRequirements)
                    {
                        options.AddPolicy(policy.Name, abp => abp.AddRequirements(policy.Requirements));
                    }
                }
            });

            foreach (var authorizationHandlerType in Policies.GetAuthorizationHandlerTypes())
            {
                services.AddScoped(typeof(IAuthorizationHandler), authorizationHandlerType);
            }

            return services.Configure<IdentityOptions>(options => options.ClaimsIdentity.UserIdClaimType = ClaimTypes.NameIdentifier);
```

And in the client the signout code consists of

```csharp
private void BeginSignOut(MouseEventArgs args)
            => NavigationManager.NavigateToLogout(
                "authentication/logout",
                "/properties");`
```

Here's what it looks like in the hosted app

![image](https://github.com/dotnet/aspnetcore/assets/13581691/42a5b7ab-2d6c-422e-b1c4-0673a5dca85a)

And here is what it looks like locally

![image](https://github.com/dotnet/aspnetcore/assets/13581691/edd21b52-c5c4-472f-b961-6b0463600463)

### Expected Behavior

NavigationManager.NavigateToLogout() should redirect to another url after successful log out.

### Steps To Reproduce

Migrate project with identity stores from dotnet 7 to dotnet 8 and host in azure app service?

### Exceptions (if any)

None

### .NET Version

8

### Anything else?

On azure

![image](https://github.com/dotnet/aspnetcore/assets/13581691/824d97ba-e29b-414f-b264-a008a3945cc7)

Locally

dotnet 8.0.100 with VS 2022

**Comment by brandonseydel** [comment]
Same thing here.

**Comment by yuominae** [comment]
Migrated back to dotnet 7 and now it works. Also noticed that the nuget Microsoft.AspNetCore.ApiAuthorization.IdenmtityServer has no 8 version, so I assume that there is now something else in place. The documentation on how to secure a web assembly app with identity server also stops at version 7.

What I can't find is any guidance on how to migrate my solution, apart from "start a new app and start copying pages over". Surely there must be a better way than starting over ever few versions?

**Comment by javiergardella** [comment]
Same thing here.
Using @brandonseydel WA!

Also, let me add, I'm using KeyCloak, so it isn't a IdentityServer problem!

**Comment by louisbouchard** [comment]
Same issue here.  Any workaround or solution?  Thank a lot.

**Comment by halter73** [comment]
This also looks similar to #49956.

**Comment by yuominae** [comment]
Thanks for the pointer @halter73. I haven't had a look at this issue since migrating back to .Net 7.
At first glance the error looks different from #49956, but that doesn't mean it doesn't have the same cause.
I'll make a branch with my project in .Net 8 in the next few days and will report back here if the error still occurs.

**Comment by fingers10** [comment]
I was facing the same problem in dotnet 8 blazor wasm project... I did the following steps..

1. Deleted `bin` and `obj` folder.
2. Added the following code in blazor wasm `.csproj`
```csproj
<ItemGroup>
    <TrimmerRootAssembly Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication"/>
</ItemGroup>
```
3. Published the project. All worked.

Reference - https://github.com/dotnet/aspnetcore/issues/49956#issuecomment-1992857288

**Comment by yuominae** [comment]
For some reason it was working after I updated nuget packages and switched my app to dotnet 8, but after publishing again today I am getting the issue again.
Stuck on "Processing logout callback...". It's a very annoying issue to have with an app that runs in prod.
I tried the suggestion by @fingers10, but the issue persists.
