### ISSUE TITLE
Make it possible to resolve the method info from the specific delegate type when using AddRouteHandler

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspnetcore#53171]
For more NativeAOT size savings, we can avoid preserving all type information for methods pointed to by delegates if we enable this. See https://github.com/dotnet/runtime/pull/96166#issuecomment-1877438742 for more details.

We essentially need to add another thunk [here](https://github.com/dotnet/aspnetcore/blob/e6be3e95fec33ca3a3b576df4b265ead680a91a0/src/Http/Routing/src/RouteEndpointDataSource.cs#L51) to allow resolution of MethodInfo from the delegate when using RDG (the request delegate generator).

cc @captainsafia

**Comment by captainsafia** [comment]
> We essentially need to add another thunk [here](https://github.com/dotnet/aspnetcore/blob/e6be3e95fec33ca3a3b576df4b265ead680a91a0/src/Http/Routing/src/RouteEndpointDataSource.cs#L51) to allow resolution of MethodInfo from the delegate when using RDG (the request delegate generator).

Don't you mean RDF here (compile-time generation)?

I think the proposed API would look like this:

```diff
    public RouteHandlerBuilder AddRouteHandler(
        RoutePattern pattern,
        Delegate routeHandler,
        IEnumerable<string>? httpMethods,
        bool isFallback,
        Func<MethodInfo, RequestDelegateFactoryOptions?, RequestDelegateMetadataResult>? inferMetadataFunc,
-        Func<Delegate, RequestDelegateFactoryOptions, RequestDelegateMetadataResult?, RequestDelegateResult> createHandlerRequestDelegateFunc,
+        Func<RequestDelegateFactoryOptions, RequestDelegateMetadataResult?, RequestDelegateResult> createHandlerRequestDelegateFunc,
+        Func<Delegate, MethodInfo> resolveMethodInfo)
```

**Comment by jkotas** [comment]
Is the whole purpose of the extra argument to provide `routeHandler.Method`? Can the extra argument be MethodInfo instead?

**Comment by davidfowl** [comment]
Actually, you're right, we might just  be able to pass it in directly 😄

**Comment by captainsafia** [comment]
Correct, indeed. Here's the full API proposal.

## Proposed API

```diff
namespace Microsoft.AspNetCore.Routing;

public static class RouteHandlerServices
{
    public static RouteHandlerBuilder Map(
            IEndpointRouteBuilder endpoints,
            string pattern,
            Delegate handler,
            IEnumerable<string>? httpMethods,
            Func<MethodInfo, RequestDelegateFactoryOptions?, RequestDelegateMetadataResult> populateMetadata,
            Func<Delegate, RequestDelegateFactoryOptions, RequestDelegateMetadataResult?, RequestDelegateResult> createRequestDelegate,
+          MethodInfo methodInfo)
}
```


## Usage Examples

Example taken from code generated by RDG.

```csharp
internal static RouteHandlerBuilder MapCore(
            this IEndpointRouteBuilder routes,
            string pattern,
            Delegate handler,
            IEnumerable<string>? httpMethods,
            MetadataPopulator populateMetadata,
            RequestDelegateFactoryFunc createRequestDelegate,
            MethodInfo methodInfo)
        {
            return RouteHandlerServices.Map(routes, pattern, handler, httpMethods, populateMetadata, createRequestDelegate, methodInfo);
        }
```

**Comment by halter73** [comment]
API Review Notes:

- Even though it's pretty much internal, since it's technically public, let's keep the old overload.
-`MethodInfo` should not be nullable.

API Approved. We have great hopes for how much more we can trim!

```diff
namespace Microsoft.AspNetCore.Routing;

public static class RouteHandlerServices
{
    public static RouteHandlerBuilder Map(
            IEndpointRouteBuilder endpoints,
            string pattern,
            Delegate handler,
            IEnumerable<string>? httpMethods,
            Func<MethodInfo, RequestDelegateFactoryOptions?, RequestDelegateMetadataResult> populateMetadata,
            Func<Delegate, RequestDelegateFactoryOptions, RequestDelegateMetadataResult?, RequestDelegateResult> createRequestDelegate);

+    public static RouteHandlerBuilder Map(
+            IEndpointRouteBuilder endpoints,
+            string pattern,
+            Delegate handler,
+            IEnumerable<string>? httpMethods,
+            Func<MethodInfo, RequestDelegateFactoryOptions?, RequestDelegateMetadataResult> populateMetadata,
+            Func<Delegate, RequestDelegateFactoryOptions, RequestDelegateMetadataResult?, RequestDelegateResult> createRequestDelegate,
+            MethodInfo methodInfo);
}

**Comment by davidfowl** [comment]
Any reason this isn't an optional paramter?

**Comment by halter73** [comment]
> Any reason this isn't an optional parameter?

We were trying to avoid any binary breaks on principle, but I think it could actually matter if you had RDG endpoints compiled against .NET 8 running on .NET 9.

**Comment by davidfowl** [comment]
I thought there was a way to do both, but it's escaping me right now.
