### ISSUE TITLE
Scaffold + Google authentication does not sign out the google account on Logout

### ISSUE THREAD

**Issue by MAGNUM81** [dotnet/aspnetcore#53175]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After creating a Blazor Web App project in .NET 8.0 using the "Individual accounts" Authentication option, I follow a tutorial to properly add Google authentication to the app. And it works; I am able to login using Google, no problem. BUT, when I try to logout, then login through Google again, I am not redirected to Google but logged-in anyway, as if the cookie wasn't cleared at all on logout. Therefore, unless I use an incognito window or another browser OR log out manually from Google.com, I will not be able to login using another Google account.

Here is the relevant section in my Program.cs: 

```
builder.Services.AddAuthentication(options =>
    {
        options.DefaultScheme = IdentityConstants.ApplicationScheme;
        options.DefaultSignInScheme = IdentityConstants.ExternalScheme;
    })
    .AddIdentityCookies();

builder.Services.AddAuthentication()
    .AddCookie()
    .AddGoogle(googleOptions =>
    {
        googleOptions.ClientId = builder.Configuration["Google:ClientId"] ?? throw new InvalidOperationException("Google:ClientId not found in configuration.");
        googleOptions.ClientSecret = builder.Configuration["Google:ClientSecret"] ?? throw new InvalidOperationException("Google:ClientSecret not found in configuration.");
    });

```

### Expected Behavior

When logging out explicitly while using Google or other provider, I would expect all cookies to be cleared, and next login should redirect to Google, not automatically sign-in last account used.

I am aware this is probably a Code 18 on my part somewhere in my `Program.cs`, but in my defense the documentation is quite sparse on this subject, and not much is said about External Provider signout functionality in docs, tutorials or else, as if the signout flow was overlooked by most people.

### Steps To Reproduce

[Here is a scaffolded project with Google Auth enabled](https://github.com/MAGNUM81/blazor-scaffold-google)

1. Update the DB using `dotnet ef database update`
2. Make sure the localhost app uses port 7005, as this is the port allowed on my test google project
3. Run the app using `dotnet run` or something to that effect.
4. Click the "Login" menu item
5. Select "Google" as the IdentityProvider
6. Enter credentials for a Google account
7. Logout using the "logout" menu item
8. Click the "Login" menu item
9. Select "Google" as the IdentityProvider
10. ...You will not be given the chance to enter your Google credentials and your info will directly be displayed in the left panel, as if you did enter them.

Step 10 is the wrong behavior. When I log out **explicitly** from an app, I would expect the current session to basically forget about me and especially, forget my google account that I do not wish to share with other users of this device.

### .NET Version

8.0.100

**Comment by brockallen** [comment]
Do you know that Google support it (they didn't used to)? I don't see an "end_session" entry in here: https://accounts.google.com/.well-known/openid-configuration, so looks like Google still doesn't support OIDC signout.

**Comment by MAGNUM81** [comment]
> Do you know that Google support it (they didn't used to)? I don't see an "end_session" entry in here: https://accounts.google.com/.well-known/openid-configuration, so looks like Google still doesn't support OIDC signout.

Well there is a `revocation_endpoint` entry - isn't that the endpoint supposed to be used to signout the user?

**Comment by brockallen** [comment]
> Well there is a revocation_endpoint entry - isn't that the endpoint supposed to be used to signout the user?

That's for revoking tokens, not for signing out.

**Comment by MackinnonBuck** [comment]
Going to close out this issue because this is not an issue with this product. Google does not support OIDC sign out, so the fix would be on their end.
