### ISSUE TITLE
Add EndPoint

### ISSUE THREAD

**Issue by acugae** [dotnet/aspnetcore#53183]
I would like to add endpoints after the application run I need it to handle new routes at runtime

**Comment by gfoidl** [comment]
@acugae do you think about minimal APIs or the MVC model?

Keep in mind that known endpoints at build time can be optimized by the runtime (e.g. by code generation, request delegate generators) and can be AOT-friendly. While adding endpoints at runtime prohibit these, and aren't AOT friendly anymore.

**Comment by acugae** [comment]
It is a necessary feature in case we want to build an ESB engine, I need to mount enpoints not known at compile time but added later and configured on a DB.

**Comment by davidfowl** [comment]
It’s possible but an advanced scenario. You can implement an EnpointdataSource which has the ability to signal when endpoints change (this is how YARP is able to change routes at runtime via configuration)

**Comment by javiercn** [comment]
In addition to what @davidfowl, MVC and Razor Pages also have support for this if you implement your own IActionDescriptorProvider
