### ISSUE TITLE
Blazor Web App - HTTP headers missing from inside a component when using IHttpContextAccessor

### ISSUE THREAD

**Issue by damienbod** [dotnet/aspnetcore#53192]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I need to read the HTTP headers from inside a Blazor Web component. 

When using the IHttpContextAccessor, the headers are not returned even though the headers exist in all the HTTP responses.

How can I use the HTTP headers returned in the client responses when using Blazor Web?

### Expected Behavior

All headers from the HTTP response should be present in the IHttpContextAccessor

```csharp
@inject IHostEnvironment Env
@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <base href="/" />
    <link rel="stylesheet" href="css/bootstrap/bootstrap.min.css" />
    <link href="css/site.css" rel="stylesheet" />
    <link href="BlazorWebFromBlazorServerOidc.styles.css" rel="stylesheet" />
    <HeadOutlet @rendermode="InteractiveServer" />
</head>
<body>
    <Routes @rendermode="InteractiveServer" />

    <script nonce="@GetNonce()" src="_framework/blazor.web.js"></script>
</body>
</html>

@code {

    private string GetNonce()
    {
        var nonce = string.Empty;
        Microsoft.Extensions.Primitives.StringValues nonces;
        var found = HttpContextAccessor.HttpContext!.Response.Headers.TryGetValue("Content-Security-Policy", out nonces);

        if(found)
        {
            nonce = nonces.First();
        };

        return nonce!;
    }
}

```

### .NET Version

8

### Anything else?

Blazor Web (Server)

**Comment by javiercn** [comment]
@damienbod thanks for contacting us.

You can't use the HttpContext in interactive server scenarios. It's only available during SSR. You should also use `[CascadingParameter] HttpContext` to access it when it's available.

**Comment by damienbod** [comment]
Thanks @javiercn 

"If you need data from the request, you need to pass it to the interactive renderer with persistent component state or via a component parameter."

Do you have an example of this, or docs?

Greetings Damien

**Comment by damienbod** [comment]
@javiercn I could not get this to work using the state stuff I found on google. This is more of a feature request. It is no longer possible to use CSP nonces with Blazor Web, or I have not found a way. This was possible pre .NET 8. 

Maybe you could re-open this issue?

**Comment by javiercn** [comment]
Sample here https://github.com/javiercn/BlazorWebNonceService
