### ISSUE TITLE
Loading static assets from wwwroot folder returns 404 not found in Blazor8

### ISSUE THREAD

**Issue by rdileep** [dotnet/aspnetcore#53204]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm using the face-api.js to implement the face detection and tried few samples with the plain html file and it worked.  While going to implement the same with the Blazor8 application, the model files return 404 not found error.

below is my folder structure
![image](https://github.com/dotnet/aspnetcore/assets/5770587/b05f464c-3457-49e1-9702-651844a2232f)

and the result screenshot
![image](https://github.com/dotnet/aspnetcore/assets/5770587/262c54f7-1f9c-4816-b275-4c144f1da57f)

### Expected Behavior

While I'm testing with the plain html in the VS Code, it worked with the same JavaScript code and the screenshots are below.
![image](https://github.com/dotnet/aspnetcore/assets/5770587/446d743e-ad99-47df-99ec-5ea78952f25f)

![image](https://github.com/dotnet/aspnetcore/assets/5770587/159a3230-e011-423d-bc49-10fcb8516256)

### Steps To Reproduce

The code for my working sample is at below repo
https://github.com/rdileep/BlazorFaceDetection

and the html sample is at 
https://github.com/WebDevSimplified/Face-Detection-JavaScript

### Exceptions (if any)

Able to load the model files as they are in the root folder which is publicly accessible.

### .NET Version

8.0.100

### Anything else?

Host:
  Version:      8.0.0
  Architecture: x64
  Commit:       5535e31a71
  RID:          win-x64

.NET SDKs installed:
  8.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by MariovanZeist** [comment]
Hi @rdileep
The issue is that those files don't have a file extension.
By default, ASPNet core doesn't allow downloading files without a file extension. The easiest/safest solution would be to add file extensions to these files.

**Comment by rdileep** [comment]
Hi @MariovanZeist
Thanks for the response.

Those files are auto fetched by the face-api by providing the path.  So if we add extension, then face-api will not recognize files.

**Comment by javiercn** [comment]
@rdileep you need to configure the static files middleware to serve files without extensions.

See https://stackoverflow.com/questions/48769310/asp-net-core-how-to-serve-static-file-with-no-extension

I'd either serve files without the extension or (ideally) would just use an endpoint to serve them.

**Comment by rdileep** [comment]
> @rdileep you need to configure the static files middleware to serve files without extensions.
> 
> See https://stackoverflow.com/questions/48769310/asp-net-core-how-to-serve-static-file-with-no-extension
> 
> I'd either serve files without the extension or (ideally) would just use an endpoint to serve them.

Thanks [javiercn](https://github.com/javiercn).

I created controllers which serves files and solved the problem.
