### ISSUE TITLE
Blazor SSR using Iframe is not working

### ISSUE THREAD

**Issue by francislagmay24** [dotnet/aspnetcore#53205]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When i try using iframe with the link of a SSR Project, iframe not working and refuse to connect 

Difference of SSR and Server in Iframe
![SSR and Server Iframe](https://github.com/dotnet/aspnetcore/assets/39607640/0762fbbe-f647-451b-99f7-0de31aa1abe5)

Network and Response Headers of Server
![Network of Server](https://github.com/dotnet/aspnetcore/assets/39607640/dfdfe621-6a49-4445-b82e-1cd87d2e6610)

Network and Response Headers of SSR
![Network of SSR](https://github.com/dotnet/aspnetcore/assets/39607640/5efe4265-1d0c-444f-ad1e-b68ebf6b5ba6)

I try to remove the X-Frame-Options of Modify it but i think for SSR Project, X-Frame-Options is strictly applied to it.
How can i fix or Integrate my SSR Project using iframe?

Thank you for your Response

### Expected Behavior

Integrate SSR using iframe will work

### Steps To Reproduce

Step 1 - Create a new Project using Blazor Web App
Step 2 - Add iframe on html
Step 3 - Add the url of the Blazor Web App project to the iframe
Step 4 - Run it

### .NET Version

8.0.100

**Comment by javiercn** [comment]
@francislagmay24 thanks for contacting us.

You are trying to load the app in an iframe with a different origin, isn't that the case?
