### ISSUE TITLE
.NET 8 Blazor NavigationManager not always initialized when used in AuthorizationHandler

### ISSUE THREAD

**Issue by jdhuebert** [dotnet/aspnetcore#53216]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

My company is in the process of upgrading our .NET 7 blazor server application to .NET 8. We use the authorization handler pattern to handle our authorization needs. We use the NavigationManager to access the current uri to determine "area" based authorization. 

While upgrading I noticed some inconsistencies with the NavigationManger being able to initialize. Here are the two situations:

- **Where it works:** When navigating internally through the app (using links/buttons) to get to a page using the authorize attribute, the NavigationManger initializes fine and we can retrieve the URI and continue our process. This situation works fine and as expected.
- **Where it doesn't work:**  when the user hits the browser refresh button or manually enters the URL, the AuthorizationHandler injects all services successfully. Then, when we try to access the URI from the NavigationManger, the application blows up from an exception saying the RemoteNavigationManager has not been initialized.

I've recreated this issue in several of our apps, a personal project, and then [this sample project](https://github.com/jdhuebert/dotnet8-navigation-manager-issue). The sample project was created using the blazor web application template in VisualStudio. The only changes I made were to make the "/weather" page use  my TestAuthorizationHandler.

Some things to note about my discoveries while investigating on my own:

- I discovered that if I wrap my page's content using an AuthorizeView instead of using the authorize attribute, this problem goes away. I suppose there must be something in the lifecycle methods of the AuthorizeView component that initializes the NavigationManager if it isn't already initialized. I looked through some of the source code for the component but didn't find anything. So, while this is technically a work around and would get our pages to authorize correctly, using an AuthorizeView instead of an AuthorizeAttribute isn't exactly standard and would require a massive effort to convert our applications' pages.
- I tried to use the JSRuntime in my AuthorizationHandler instead to get the current uri. Interestingly, in .NET 7 this works here, but in .NET 8 I get the exception for the Js Interop calls only being available during the OnAfterRenderAsync lifecycle method. To be honest, I'm not sure if this is related or expected but thought it was something to note.

### Expected Behavior

The NavigationManager can successfuly initialize when used in an AuthorizationHandler regardeless of whether navigation occurred internally or externally.

### Steps To Reproduce

[Here is my sample project](https://github.com/jdhuebert/dotnet8-navigation-manager-issue) that can be used to reproduce the issue.

Steps to reproduce exception:
1. Start up the sample project.
2. In the browser bar type "/weather" to go to the weather page.
3. The exception should be thrown on line 21 of the TestAuthorizationHanderl.cs file.

Steps to demonstrate the NavigationManager behaving as expected:
1. Start up the sample project.
2. Click the button to navigate to the weather page.
3. The exception will **not** be thrown and you should be authorized to see the weather page.

### Exceptions (if any)

System.InvalidOperationException
  HResult=0x80131509
  Message='RemoteNavigationManager' has not been initialized.
  Source=Microsoft.AspNetCore.Components
  StackTrace:
   at Microsoft.AspNetCore.Components.NavigationManager.AssertInitialized()
   at Microsoft.AspNetCore.Components.NavigationManager.get_Uri()
   at NavigationManagerTest.Authorization.TestAuthorizationHandler.HandleRequirementAsync(AuthorizationHandlerContext context, TestAuthorizationRequirement requirement) in NavigationManagerTest\NavigationManagerTest\Authorization\TestAuthorizationHandler.cs:line 21
   at Microsoft.AspNetCore.Authorization.AuthorizationHandler`1.<HandleAsync>d__0.MoveNext()

### .NET Version

8.0.100

### Anything else?

- Using VS Version 17.8.0 on Windows 10

- Output of dotnet --info:
  .NET SDK:
   Version:           8.0.100
   Commit:            57efcf1350
   Workload version:  8.0.100-manifests.8d38d0cc
  
  Runtime Environment:
   OS Name:     Windows
   OS Version:  10.0.19045
   OS Platform: Windows
   RID:         win-x64
   Base Path:   C:\Program Files\dotnet\sdk\8.0.100\
  
  .NET workloads installed:
   Workload version: 8.0.100-manifests.8d38d0cc
  There are no installed workloads to display.
  
  Host:
    Version:      8.0.0
    Architecture: x64
    Commit:       5535e31a71
  
  .NET SDKs installed:
    3.1.426 [C:\Program Files\dotnet\sdk]
    6.0.320 [C:\Program Files\dotnet\sdk]
    8.0.100-rc.2.23502.2 [C:\Program Files\dotnet\sdk]
    8.0.100 [C:\Program Files\dotnet\sdk]
  
  .NET runtimes installed:
    Microsoft.AspNetCore.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 8.0.0-rc.2.23480.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.NETCore.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 8.0.0-rc.2.23479.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.WindowsDesktop.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.0-rc.2.23479.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  
  Other architectures found:
    x86   [C:\Program Files (x86)\dotnet]
      registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]
  
  Environment variables:
    Not set
  
  global.json file:
    Not found
  
  Learn more:
    https://aka.ms/dotnet/info
  
  Download .NET:
    https://aka.ms/dotnet/download

**Comment by gragra33** [comment]
> **Steps to reproduce exception:
> 1. Start up the sample project.
> 2. In the browser bar type "/weather" to go to the weather page.
> 3. The exception should be thrown on line 21 of the TestAuthorizationHanderl.cs file.**

Interactive Server mode for a Blazor Web App does appear to work differently to Blazor Server App (older style). This may be a bug.

However, in the meantime, you can work around this. The `AuthorizationHandlerContext` has the `HttpContext` which is the `context.Resource` property.

So, you could modify your code like this:
```cs
string _uri = string.Empty;
try
{
    _uri = this._navigationManager.Uri;
}
catch (Exception ex)
{
    _uri = (context.Resource as DefaultHttpContext)!.Request.Path;
}
```

**Comment by javiercn** [comment]
@jdhuebert thanks for contacting us.

Blazor services are only generally usable within Blazor. As @gragra33 points out you have access to the HttpContext within the context, which is what you should use to get the Url in this scenario.
