### ISSUE TITLE
Blazor webassembly application is showing wrong culture

### ISSUE THREAD

**Issue by hasnuzama** [dotnet/aspnetcore#53233]
### Is there an existing issue for this?

- [X] (https://github.com/dotnet/aspnetcore/issues/29598)

### Describe the bug

I have created blazor webassembly application with .NET 8.
System.Globalization.CultureInfo.CurrentCulture is showing as en-US

But when i do the same thing in console app, it is showing as en-IN.

I have also added below to my csproj file.
`<BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>
`

**My system settings:**
![image](https://github.com/dotnet/aspnetcore/assets/15692028/7ea105d1-ec53-47ae-a282-62886d488890)

**Console app:**
![image](https://github.com/dotnet/aspnetcore/assets/15692028/0a8d7d8b-bb37-4400-ab14-40c24b7c8a87)

**Blazor app:**
![image](https://github.com/dotnet/aspnetcore/assets/15692028/8071ee52-9be1-4d10-8502-ea4f34e2bcfd)
![image](https://github.com/dotnet/aspnetcore/assets/15692028/cf2daf30-fc3f-4ac0-8cdb-89cb812a43bb)

### Expected Behavior

Expected it to show correct culture. In my case en-IN

### .NET Version

.NET 8

**Comment by guardrex** [comment]
@hasnuzama ... It's not enough to merely enable the property. See the guidance in the article. You'll either adopt the dynamic or the static approach to setting the culture. There's a section for each in the article.

https://learn.microsoft.com/aspnet/core/blazor/globalization-localization
