### ISSUE TITLE
Disable Refresh Page When Post Form In Blazor

### ISSUE THREAD

**Issue by MahdiElahi** [dotnet/aspnetcore#53241]
Hi,
I use web App blazor , in my form when i click on submit button the form is post to server and then refreshed page 
for example : in login form when the input  is not valid , i click on submit it's refresh page then show validation message field 

i want disable reload page in blazor 
how to do it ?

notice :

when i change render mode to interactiveServer it's Ok
but in renderModes Auto & WebAssembly is page is refreshed 

why ? how to solve it ?

**Comment by javiercn** [comment]
@MahdiElahi thanks for contacting us.

Identity uses SSR Blazor only as it needs to set state on the request, login and log out using the identity components in the template can't be achieved without traditional SSR navigations.
