### ISSUE TITLE
Microsoft.IdentityModel.Protocols.OpenIdConnect 7.1.2

### ISSUE THREAD

**Issue by cheng93** [dotnet/aspnetcore#53243]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Microsoft.AspNetCore.Authentication.JwtBearer 8.0.1
Microsoft.AspNetCore.Authentication.OpenIdConnect 8.0.1

has been released, but Microsoft.IdentityModel.Protocols.OpenIdConnect 7.1.2 is not on nuget

See https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/discussions/2441

**Comment by martincostello** [comment]
It's _possible_ the packages are still in the process of being released. I would suggest waiting until .NET 8.0.1 is officially released later today (watch the dotnet/core repo for the update to the release notes) as that won't/shouldn't happen until everything that needs to be in place to use it is ready.

**Comment by martincostello** [comment]
Also, if that doesn't "fix" it, you could always unblock yourself by using the 8.0.0 packages not the 8.0.1 packages.

**Comment by KUTlime** [comment]
This happens when a floating version is being used.

I think that @cheng93 wanned point out that this should not happen, or at least I want to point it out. This temporal issue does break CI/CD.

My suggestion for updating the issue description:

## Steps to reproduce

Use `<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.*"/>` in CSProj file and try to restore NuGet package.

## Expected Behavior

`Microsoft.IdentityModel.Protocols.OpenIdConnect`  will be released prior to `Microsoft.AspNetCore.Authentication.JwtBearer` because the former is the dependency of the latter.

**Comment by rcurwen** [comment]
6.0.26 is similarly broken: 

```
warning NU1603: Microsoft.AspNetCore.Authentication.OpenIdConnect 6.0.26 dep
ends on Microsoft.IdentityModel.Protocols.OpenIdConnect (>= 6.35.0) but Microsoft.IdentityModel.Protocols.OpenIdConnect 6.35.0 was not found.
```

**Comment by martincostello** [comment]
My guess would be that the two versions available contain fixes for as-yet-announced security vulnerabilities that will be imminently responsibly disclosed for today's Patch Tuesday release and the release process is still on-going because it's a large process that can't be done atomically.

**Comment by martincostello** [comment]
FYI the release is usually "official" when a PR such as this is merged, as the files changed feed into the `dot.net` website downloads: https://github.com/dotnet/core/pull/9053

**Comment by martincostello** [comment]
[7.1.2](https://www.nuget.org/packages/Microsoft.IdentityModel.Protocols.OpenIdConnect/7.1.2) is now in NuGet. I imagine 6.35.0 will appear shortly.

**Comment by martincostello** [comment]
[6.35.0](https://www.nuget.org/packages/Microsoft.IdentityModel.Protocols.OpenIdConnect/6.35.0) is now also present.

That makes this issue resolved as far as I can see, but I'll leave this open for the team to confirm whether or not this is an expected by-design side-effect of the .NET release process being non-atomic and the full set of downloads for releases taking a period of time to propagate all of the required assets (NuGet packages, SDKs, Docker images, etc.).

**Comment by rbhanda** [comment]
> FYI the release is usually "official" when a PR such as this is merged, as the files changed feed into the `dot.net` website downloads: [dotnet/core#9053](https://github.com/dotnet/core/pull/9053)

The release is official when dot.net is populated
