### ISSUE TITLE
Error Headers are read-only, response has already started .net 8 blazor

### ISSUE THREAD

**Issue by MahdiElahi** [dotnet/aspnetcore#53240]
Hi,
the login page is refreshed because of this i change render mode to InteractiveServer to disable reload page when click submit in login form

but 
when run this code : 
` var result = await SignInManager.PasswordSignInAsync(Input.Email, Input.Password, Input.RememberMe, lockoutOnFailure: false);`

i have this error 
**Headers are read-only, response has already started**

my project is Blazor  Web App (Auto Interactivity)

you can test login in my project 
1.register new user 
2.click on confirm email
3.login

[ForumProject.zip](https://github.com/dotnet/runtime/files/13871854/ForumProject.zip)

what's is problem ?

**Comment by javiercn** [comment]
@MahdiElahi thanks for contacting us.

The Identity pages require access to the underlying HttpContext and only work in SSR mode. They don't work in interactive mode.

**Comment by javiercn** [comment]
@MahdiElahi Please provide your repro as a public github repository, otherwise we can't look at it.

**Comment by MahdiElahi** [comment]
@javiercn 
Thanks 

you can see my project is git.
it's bad identity just worked in ssr mode.
i want worked identity page without reload page and use interactive modes(wasm / server / auto ) how to do it ? 
[my repo]([javiercn](https://github.com/javiercn))

**Comment by javiercn** [comment]
> i want worked identity page without reload page and use interactive modes(wasm / server / auto ) how to do it ?

This is not something that we provide out of the box. You'll have to create your own implementation using the new identity endpoints.

**Comment by 3x0dv5** [comment]
I was having a similar problem. 
In my case the problem was caused by `@rendermode="InteractiveServer" ` in the HeadOutlet and Routes. Strangely when I had this in there I was getting the cookies error.

```html
    <HeadOutlet @rendermode="InteractiveServer"/>
</head>

<body>
<Routes @rendermode="InteractiveServer"/>
```
I really have to read a bit more about these render modes, my knowledge is lacking.

@MahdiElahi  I checked your ForumProject and made a couple of changes, now it is working
![image](https://github.com/dotnet/aspnetcore/assets/250271/0afcd5e3-48a5-49d0-9719-b6fc217492eb)
Here is a pull request:
https://github.com/MahdiElahi/AuthProject_Blazor8/pull/1

Hope this helps/

**Comment by devnuwan** [comment]
stile I have this issue

**Comment by muradzade** [comment]
I had the same issue. I forgot adding **.AddIdentityCookies()** . So it solved my problem

**Comment by vukasinpetrovic** [comment]
Did anyone figure out how to create interactive login page? It is espectially useful if we are connecting to existing/external API that uses JWT Bearer token. After httpClient calls the API, we need a way to securely persist the token and use it for further calls.

**Comment by Woudjee** [comment]
So if I understand correctly, you cannot do this when the rendermode is InteractiveServer? Why is that?

**Comment by saddamhossain** [comment]
I am facing same issue till now.

**Comment by saddamhossain** [comment]
> @attribute [StreamRendering]

Did you fix the issue?

**Comment by matiae** [comment]
+1

**Comment by Varavchik18** [comment]
@javiercn any news on that issue ? kind of weird workarounds are present but really strange is that blazor does not support classic Identity auth flow. Do you have recommendations which auth flow is better to use for newest blazor apps ?

**Comment by Zefty** [comment]
What's the alternative solution if we were to use interactive modes? Do we need to implement a webapi endpoint that we can call?
