### ISSUE TITLE
InputSelect not work in blazor .net 8

### ISSUE THREAD

**Issue by MahdiElahi** [dotnet/aspnetcore#53242]
in my project ,  use InputSelect
it's not work correctly , when refresh the book page it's ok but when navigate to other page and return to book page it's not work

 shown this problem in this video attached and share my codes
i think the javascript files must be call again to initialize select field 
please check this project

[my repo in git](https://github.com/MahdiElahi/InputSelect_Test)

https://github.com/dotnet/runtime/assets/32883870/c496a658-fe21-45f1-9508-6b686531591e

**Comment by MahdiElahi** [comment]
@SteveSandersonMS 
this my [repo](https://github.com/MahdiElahi/InputSelect_Test)

**Comment by SteveSandersonMS** [comment]
Thanks, but it appears to be private. Can you make it public?

**Comment by MahdiElahi** [comment]
Sorry , Change it to public

**Comment by SteveSandersonMS** [comment]
Glad that worked. I'm not sure about any other usage details for select2 so I'd suggest following up with that project for more information.
