### ISSUE TITLE
Frequent disconnects

### ISSUE THREAD

**Issue by alexiordan** [dotnet/aspnetcore#5324]
I cannot make a whole day without some disconnects. 
They are very short (under 1 minute, and tipically below 10 s) and appear at irregular intervals (online: 1h, offline: 2 s, online: 30 min, offline 2s and so on)

Only meaningful log I get is on client side complaining the server did not send a message:

> [Error] Connection is shutting down due to an error.
System.TimeoutException: Server timeout (6000.00ms) elapsed without receiving a message from the server.

Web app is hosted on Azure.

I have 2 clients and they both get disconnected simoultaneously. So I kind of excluding Client side errors. I can think about 2 options:

- Misconfigured SignalR server/client (please Help!)
- Network delays. As I wrote below I don't have any network traces yet, but as soon as I will have something, I'l post here.

Although I set Always On for WebApp on Azure sometimes I see request response delays... Could this be an issue?

What should I look for in server side logs to see that KeepAlive message have been sent correctly? I see in Fiddler that KeepAlive (Type: 6 messages) sometimes come at 4 seconds instead of 3. 
Could some long-running code on the web app to delay the KeepAlive sending?

Configuration below:

**Client**
Microsoft.AspNetCore.SignalR v 1.0.0 ( Just updated to 1.0.2 I'll keep testing and come up with feedback)
`HubConnection.ServerTimeout = TimeSpan.FromSeconds(6);
`
**Server**
Microsoft.AspNetCore.SignalR (1.0.0)
```

 services.AddSignalR(
                options =>
                {
                    options.KeepAliveInterval = TimeSpan.FromSeconds(3);
                });
```

I have logs according to following article:
https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide

No network traces yet.

**UPDATE:**
As can be seen below, disconnect occur due to client not receiving the KeepAlive. 
![image](https://user-images.githubusercontent.com/15249495/43461792-0265d7a0-94dd-11e8-8929-05096e4830cc.png)

1. Can someone please confirm that type:6 is the KeepAlive
2. I want to know where is the delay coming from. My code or the network. Please help.

**Comment by ashishakm** [comment]
![error1](https://user-images.githubusercontent.com/8637963/51803393-b506ff80-227a-11e9-9d90-5469fc42a77d.JPG)

Getting error as given in screenshot

**Comment by ChrisProlls** [comment]
Any news about it ? I faced with the same problem here !
@anurse

**Comment by anurse** [comment]
This thread was marked as a discussion as a result of how the initial questions concluded. If you're seeing an issue please file a new bug with the details.

**Comment by davidfowl** [comment]
Are you using the HubConnection itself anywhere in your On callback? I wonder if you're blocking the message loop on the client side in your callbacks and that's what's causing the client to miss messages. You cannot block in those handlers.
