### ISSUE TITLE
You must install or update .NET to run this application.

### ISSUE THREAD

**Issue by StiglCZ** [dotnet/aspnetcore#53260]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

So, I have been trying to make an ASP.NET core app. I normally create the app using `dotnet new webapp` and then try to build the app, which works just fine. But then when I try to run the app, it results in the folowing error:
```
You must install or update .NET to run this application.

App: /home/stigl/Projects/Cs/StiglBank/bin/Debug/net8.0/StiglBank
Architecture: x64
Framework: 'Microsoft.AspNetCore.App', version '8.0.0' (x64)
.NET location: /usr/share/dotnet

No frameworks were found.

Learn more:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=8.0.0&arch=x64&rid=arch-x64&os=arch
```

When I checked if I am missing some versions, it doesnt seem like it:
```
└─[$]  dotnet --list-sdks
6.0.125 [/usr/share/dotnet/sdk]
8.0.100 [/usr/share/dotnet/sdk]

└─[$] dotnet --list-runtimes
Microsoft.NETCore.App 6.0.25 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 8.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

Btw, This only happens for web applications, console and aws lambda works just fine

### Expected Behavior

Expected for the app to run

### Steps To Reproduce

Steps to repruduce:
- Be on linux
- Have sdks 6.0.25 & 8.0.100

 `dotnet new webapp`
`dotnet run`

### .NET Version

8.0.100

### Anything else?

Dotnet info:
```
.NET SDK:
 Version:           8.0.100
 Commit:            57efcf1350
 Workload version:  8.0.100-manifests.c8a7cd5f

Runtime Environment:
 OS Name:     arch
 OS Version:  
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/8.0.100/

.NET workloads installed:
 Workload version: 8.0.100-manifests.c8a7cd5f
There are no installed workloads to display.

Host:
  Version:      8.0.0
  Architecture: x64
  Commit:       5535e31a71

.NET SDKs installed:
  6.0.125 [/usr/share/dotnet/sdk]
  8.0.100 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.NETCore.App 6.0.25 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/usr/share/dotnet/]

global.json file:
  Not found
  ```

**Comment by captainsafia** [comment]
@StiglCZ To run ASP.NET Core apps, you'll need that runtime. It typically looks something like this:

>   Microsoft.AspNetCore.App 8.0.0 [/Users/captainsafia/.dotnet/shared/Microsoft.AspNetCore.App]

You can try downloading just the runtime from https://dotnet.microsoft.com/en-us/download/dotnet/8.0.

**Comment by captainsafia** [comment]
@StiglCZ Not quite. `Microsoft.AspNetCore.App` is a meta package that contains all of the assemblies that are part of ASP.NET Core (e.g. `Microsoft.AspNetCore.Routing`). It's including via a shared framework reference automatically when you create a project that references the `Microsoft.NET.Sdk.Web` SDK.

`Microsoft.NETCore.App` encapsulates the .NET runtime itself and supports running things like console applications for example.

**Comment by erikkipp** [comment]
I have the same issue but it appears I have all sdk and runtimes installed.

You must install .NET to run this application.

App: 
Architecture: x64
App host version: 8.0.1
.NET location: Not found

**dotnet --info**

.NET SDK:
 Version:           8.0.101
 Commit:            6eceda187b
 Workload version:  8.0.100-manifests.69afb982

Runtime Environment:
 OS Name:     linuxmint
 OS Version:  21.2
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/8.0.101/

.NET workloads installed:
 Workload version: 8.0.100-manifests.69afb982
There are no installed workloads to display.

Host:
  Version:      8.0.1
  Architecture: x64
  Commit:       bf5e279d92

.NET SDKs installed:
  8.0.101 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by StiglCZ** [comment]
> @StiglCZ Not quite. `Microsoft.AspNetCore.App` is a meta package that contains all of the assemblies that are part of ASP.NET Core (e.g. `Microsoft.AspNetCore.Routing`). It's including via a shared framework reference automatically when you create a project that references the `Microsoft.NET.Sdk.Web` SDK.
> 
> `Microsoft.NETCore.App` encapsulates the .NET runtime itself and supports running things like console applications for example.

Can i ask if there is this package avilable for arch linux, and in case it isnt how is the debian one named?

**Comment by StiglCZ** [comment]
> This issue has been resolved and has not had any activity for **1 day**. It will be closed for housekeeping purposes.
> 
> See [our Issue Management Policies](https://aka.ms/aspnet/issue-policies) for more information.

It was not

**Comment by V1ck3s** [comment]
You must have all these runtimes (my case with a dotnet 7 project), they are not the same for ASP.NET as for .NET :
![Screenshot_20240114_235041](https://github.com/dotnet/aspnetcore/assets/9383480/2ef63424-4f5a-40da-8598-2041ab0a839c)

On arch linux it's the aspnet-runtime-7.0 package (change version with yours)

**Comment by StiglCZ** [comment]
Oh i see, it now makes sence that i didnt see it at first because i was querying bu the .net not by the asp, anyway thanks so much!

**Comment by V1ck3s** [comment]
> Oh i see, it now makes sence that i didnt see it at first because i was querying bu the .net not by the asp, anyway thanks so much!

No problem, I made exactly the same mistake until I realized that I only had version 8 of aspnet in the dotnet infos command.

**Comment by minmik528** [comment]
> > @StiglCZ Not quite. `Microsoft.AspNetCore.App` is a meta package that contains all of the assemblies that are part of ASP.NET Core (e.g. `Microsoft.AspNetCore.Routing`). It's including via a shared framework reference automatically when you create a project that references the `Microsoft.NET.Sdk.Web` SDK.
> > `Microsoft.NETCore.App` encapsulates the .NET runtime itself and supports running things like console applications for example.
> 
> Can I ask if there is this package(Microsoft.AspNetCore.App) avilable for arch linux, and in case it isnt how is the debian one named? I have installed everything that could've worked from the official repos, so I am guessing it will be somewhere on the AUR, but there is hundreds of dotnet packages on it, so i dont really know which ones.

here! https://aur.archlinux.org/pkgbase/dotnet-core-bin

**Comment by LMF3z** [comment]
> aspnet-runtime-7.0

Thank you very much. just what i need

**Comment by lmihalkovic** [comment]
working with dotnet is a miserable experience ... for the better part of 15 years dealing with versions has been a glorious mess.
