### ISSUE TITLE
HttpContext is not null for the fist time call in OnInitializedAsync()

### ISSUE THREAD

**Issue by daping123** [dotnet/aspnetcore#53263]
### Description
For the official document said, `HttpContext `can be used as a cascading parameter only in statically-rendered root components for general tasks. The value is always null for interactive rendering. We know that it will call `OnInitializedAsync() `twice if the render mode is InteractiveServer. My problem is why `HttpContext `have the value for the first time call in `OnInitializedAsync()`.

### Code
```
  [CascadingParameter]
  public HttpContext? HttpContext { get; set; }
  protected override async Task OnInitializedAsync()
  {
      var data = HttpContext;
  }
```
### Environment
.NET 8 blazor web app

**Comment by SteveSandersonMS** [comment]
HttpContext is not null when the component is being prerendered. Note that being statically rendered is the same thing as being prerendered.

Interactive components go like this:

1. Prerendering (HttpContext is available)
2. Interactive (HttpContext *not* available)

SSR-only components go like this:

1. Prerendering (HttpContext is available). That's it, the end.
