### ISSUE TITLE
Blazor WebAssembly app keeps re rendering component

### ISSUE THREAD

**Issue by daniel-parra-issatec** [dotnet/aspnetcore#53287]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello,

I'm currently working on a Blazor WebAssembly app for bank customers to take turns. The last page of the navigation is a "waiting room" where a notification is prompted when the customer is called for service. This component connects to a Signal R hub in order to receive the notification when the turn is called. Here's where the issue comes into play:

When the component is rendered for the first time it keeps re rendering, it's not noticeable unless the customer scrolls down and suddenly the page displays right at the top again. If I empty the chache and reload the page eveything works as expected.

Here's a fragment of the code:

`     protected override async Task OnInitializedAsync()
    {
        //Lots of code before this...
		
        hubConnection = new HubConnectionBuilder()
        .WithUrl(signalUrl)
        .Build();
		
        hubConnection.On<int, string>("UpdateQueuePosition", (message, locationCode) =>
        {
            uiMessage = message;
            location = locationCode;
            StateHasChanged();
        });
        await hubConnection.StartAsync();
		
		//Because there will be several customers on several offices of the bank I need to save a connectionId for each of them
		//tied to their current turn.
        connId = hubConnection.ConnectionId;
        await _processService.SetProcessCustomProperty(processId, "hubConnectionId", connId); //This has to do with another separate software.
    }

    async Task Send() => await hubConnection.SendAsync("UpdateQueuePosition", uiMessage, location);

    public async ValueTask DisposeAsync()
    {
        await hubConnection.DisposeAsync();
    }`

I have searched a lot and some Microsoft sites suggest the use of event handlers in order to avoid calling StateHasChanged, but if I do that then the UI doesn't update at all.

Here's a video that shows the issue and what are the implications of it: https://youtu.be/1ShZ0cnPF0Y

### Expected Behavior

The componente should re render only once after the Signal R notification is received.

### Steps To Reproduce

Sadly I can't provide a github repo to reproduce because the app works in tandem with another software.

### .NET Version

7.0.306

### Anything else?

.Net Core 6
I'm working with Visual Studio 2022
SDK DE .NET:
 Version:   7.0.306
 Commit:    f500069cb7

Entorno de tiempo de ejecución:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.306\

Host:
  Version:      8.0.0
  Architecture: x64
  Commit:       5535e31a71

.NET SDKs installed:
  7.0.306 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Thanks in advance for your help.

Best regards,
Daniel Parra.

**Comment by javiercn** [comment]
Thanks for contacting us @daniel-parra-issatec.

It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to StackOverflow using the asp.net-core-blazor tag.

As a starting point we would suggest you turn on logging both on the server and on the client to debug level and observe what components are rendering.

Another thing you can do is place `breakpoints/console.writeline` on your app to try and understand what's causing the additional renders.

Unfortunately, nothing here points out to a clear framework issue and its outside of the scope in this repo to troubleshoot individual application issues.

If you are able to narrow down what's going on and point out an issue within the framework, we'll be happy to take another look.
