### ISSUE TITLE
The ValidateAuthenticationStateAsync in the RevalidatingAuthenticationStateProvider in 8.0.X is never called

### ISSUE THREAD

**Issue by si124** [dotnet/aspnetcore#53286]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I examined the original Blazor 8.0.X Identity template. The ValidateAuthenticationStateAsync method in the PersistingRevalidatingAuthenticationStateProvider class is never called.
If we change revalidation time to 30 seconds:
protected override TimeSpan RevalidationInterval => TimeSpan.FromSeconds(30);
we notice that the ValidateAuthenticationStateAsync method is never called.

In Blazor 7, the method ValidateAuthenticationStateAsync is periodically called as expected!!!

I think that something is wrong with RevalidatingAuthenticationStateProvider class in 8.0.X.

### Expected Behavior

The ValidateAuthenticationStateAsync method should be called periodically.

### Steps To Reproduce

It is very easy to reproduce. We choose original Blazor App 8 Template with Identity. Then we change revalidation time and check if The ValidateAuthenticationStateAsync method is called.

### Exceptions (if any)

/

### .NET Version

8.0.X

### Anything else?

/

**Comment by MackinnonBuck** [comment]
Thanks for reaching out. Could you please clarify whether the app you're creating uses server interactivity? Does the same issue occur if you create a Blazor Web app with "global server interactivity" enabled?
