### ISSUE TITLE
Consider adding Options Validation rules

### ISSUE THREAD

**Issue by anurse** [dotnet/aspnetcore#5328]
https://github.com/aspnet/Options/pull/266 adds support for "Validation" rules that throw useful errors at startup when options are invalid. We should consider applying this to `.AddSignalR` and other places where we configure `IOptions<T>`.

**Comment by muratg** [comment]
@anurse backlogging this for now. Let's discuss when you're back.

**Comment by davidfowl** [comment]
This isn't worth it. Haven't seen cases where this trips people up.
