### ISSUE TITLE
Cannot get static files like js from razor class library in Production environment

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#53285]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Cannot-get-static-files-like-js-from-raz/10398784)._

---
Hello,

I am getting an issue related to working with Razor Class Library in Production environment. I have a new  created ASP.NET Core MVC project named "app4" and a Razor Class Library project called "app4.rcl". Within the "app4.rcl" project, an additional parameter, <StaticWebAssetBasePath>/rcl</StaticWebAssetBasePath>, has been included.

In the "app4.rcl" project, there is a JavaScript file named "rcl.js" located in the "wwwroot/js" folder. This file contains the code alert('rcl');. Similarly, the "app4" project includes a JavaScript file named "app.js" in the "wwwroot/js" folder, with the code alert('app').

The "Views/Home/Index.cshtml" file in the "app4" project has been modified to include two references as follows:

<script src="~/js/app.js" type="module"></script>
<script src="~/rcl/js/rcl.js" type="module"></script>

When running the "app4" project using the https profile. Two alert messages, one displaying "app" and the other displaying "rcl", will appear. 
The problem arises when launching the "app4" project using the https-prod profile (a modified version of the https profile with the "ASPNETCORE_ENVIRONMENT" changed to "Production" in the launchSettings.json file), only the "app" alert message is displayed. The "rcl/js/rcl.js" file fails to load, resulting in a 404 error status.

I have attached the sample project described above for your reference. I have also attempted various actions such as rebuilding the project, clearing the "bin/obj/vs" folders, and switching between the HTTPS and HTTPS-Prod profiles. On some occasions, I have managed to successfully load the "rcl.js" file in the HTTPS-Prod profile, but unfortunately, this is not consistently reproducible.

Your assistance in resolving this matter would be greatly appreciated.

Thank you for your attention to this issue.

Kind regards,
Vitalii

---
#### Feedback Bot on 6/24/2023, 11:11 PM: 

(private comment, text removed)
#### Feedback Bot on 6/25/2023, 08:17 PM: 

(private comment, text removed)
#### vitalii.odiichuk on 7/5/2023, 01:51 AM: 

(private comment, text removed)
#### vitalii.odiichuk on 7/19/2023, 01:17 AM: 

(private comment, text removed)
#### vitalii.odiichuk on 8/27/2023, 11:24 PM: 

(private comment, text removed)
#### vitalii.odiichuk on 9/25/2023, 11:42 PM: 

(private comment, text removed)
#### vitalii.odiichuk on 11/22/2023, 05:25 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by odivit** [comment]
Hello, it's working! Thanks to all the participants. I re-evaluated this issue using VS 17.8.4, and it's now functioning as expected. I launched the project multiple times in both environments, and the rcl component loaded successfully.

Many thanks once again, and I wish you all a great day.

P.S. The mentioned project has been attached for reference.

[app4.zip](https://github.com/dotnet/aspnetcore/files/13900876/app4.zip)
