### ISSUE TITLE
[extensions] dependency out of date

### ISSUE THREAD

**Issue by mitchdenny** [dotnet/aspnetcore#53295]
As seen here: https://dev.azure.com/dnceng/internal/_dashboards/dashboard/755b52e7-b7a3-423b-bb60-7a01ff7241b8

**Comment by BrennanConroy** [comment]
Kicked the dep update now it's up to date. We should probably change the SLA to 11 day warning 14 day fail since the extensions trigger is once a week.
https://github.com/Pilchie/DependencyFlow/pull/38
