### ISSUE TITLE
Dev tunnels - project bound configuration

### ISSUE THREAD

**Issue by MichaMican** [dotnet/aspnetcore#53298]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am working with a few other people on a Teams App. Teams App urls have to be specified in the Manifest, we often need tools like dev tunnels / ngrok etc. to be able to test.
Currently with dev tunnels everyone has to create his/her own, meaning we need a manifest and App Registration for every developer which is a big overhead.

### Describe the solution you'd like

It would be awesome if Dev tunnels could be specified so they are bound to the project and can be checked in. So that if a coworker pulls the repository and opens the project he/she finds a configured dev tunnel that can be used, with the __same url__ as the other.
Ofc. one url can only be used at one time - but this is to be expected.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
To confirm my understanding here, what you're asking for here is a way to specify the URL during project creation so that the created project has dev-tunnel configured auto-of-the box, correct ?

**Comment by MichaMican** [comment]
Yes @mkArtakMSFT 
The goal would be that every one who starts the project has the same dev tunnel setup with the same url "out of the box"

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not part of the runtime feature-set. Please use the [VS Feedback](https://docs.microsoft.com/en-us/visualstudio/ide/feedback-options) to request this feature, so the team who owns the area can track the ask.
