### ISSUE TITLE
NamedPipeTransportOptions should support multiple PipeSecurity (DACL)

### ISSUE THREAD

**Issue by kenans** [dotnet/aspnetcore#53306]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Today, Kestrel is capable of binding to multiple `NamedPipeEndpoint`
```cs
// Kestrel will listen on both "pipe1" and "pipe2"
builder.WebHost.ConfigureKestrel(options =>
{
    options.ListenNamedPipe("pipe1");
    options.ListenNamedPipe("pipe2");
});
```

However, DACL for each Named Pipe is set up using the identical [`NamedPipeTransportOptions.PipeSecurity`](https://github.com/dotnet/aspnetcore/blob/eb3ad9beb9818f7c7f1b27707ffe08c8273a2dc5/src/Servers/Kestrel/Transport.NamedPipes/src/NamedPipeTransportOptions.cs#L61C36-L61C36) found in [`NamedPipeConnectionListener`](https://github.com/dotnet/aspnetcore/blob/eb3ad9beb9818f7c7f1b27707ffe08c8273a2dc5/src/Servers/Kestrel/Transport.NamedPipes/src/Internal/NamedPipeConnectionListener.cs#L212C1-L234C14)
```cs
if (_options.PipeSecurity != null)
{
    stream = NamedPipeServerStreamAcl.Create(
        _endpoint.PipeName,
        PipeDirection.InOut,
        NamedPipeServerStream.MaxAllowedServerInstances,
        PipeTransmissionMode.Byte,
        pipeOptions,
        inBufferSize: 0, // Buffer in System.IO.Pipelines
        outBufferSize: 0, // Buffer in System.IO.Pipelines
        _options.PipeSecurity);    // <-- NamedPipeTransportOptions.PipeSecurity is used to create NamedPipeServerStream
}
else
{
    // ...
}
```

The underlying issue for this is that [`NamedPipeTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)`](https://github.com/dotnet/aspnetcore/blob/eb3ad9beb9818f7c7f1b27707ffe08c8273a2dc5/src/Servers/Kestrel/Transport.NamedPipes/src/Internal/NamedPipeTransportFactory.cs#L35C43-L35C52) is called multiple times with each `NamedPipeEndpoint`, but they all share the same `NamedPipeTransportOptions`.
```cs
public ValueTask<IConnectionListener> BindAsync(EndPoint endpoint, CancellationToken cancellationToken = default)
{
    // ...
    
    // The same _options instance is always used here for each endpoint
    var listener = new NamedPipeConnectionListener(namedPipeEndPoint, _options, _loggerFactory, _objectPoolProvider); 

    // ...
}
```

### Describe the solution you'd like

It would be nice to be able to assign unique DACL (`PipeSecurity`) to different `NamedPipeEndpoint`.

One possible approach is to map `PipeSecurity` with the pipe name in `NamedPipeTransportOptions`,
```cs
public sealed class NamedPipeTransportOptions
{
    // ...

    IDictionary<string, PipeSecurity> PipeSecurities { get; set; }

    // ...
}
```

When `NamedPipeServerStream` is created, do something like below,
```cs
var pipeSecurity = _optionsPipeSecuriteies[endpoint.PipeName];
var stream = NamedPipeServerStreamAcl.Create(
    _endpoint.PipeName,
    PipeDirection.InOut,
    NamedPipeServerStream.MaxAllowedServerInstances,
    PipeTransmissionMode.Byte,
    pipeOptions,
    inBufferSize: 0, // Buffer in System.IO.Pipelines
    outBufferSize: 0, // Buffer in System.IO.Pipelines
    pipeSecurityy); 
```

**Comment by amcasey** [comment]
@kenans Thanks for the suggestion!  Can you tell us a bit more about what you'd do with this functionality?  What's an example of where pipes would benefit from having different `PipeSecurity`s?

**Comment by amcasey** [comment]
@JamesNK May recall our reasoning for not doing this in the first place (possibly, it was just that no one had asked).

**Comment by JamesNK** [comment]
No one had asked.

I think if we do this then we would have a func similar to [SocketTransportOptions.CreateBoundListenSocket](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.server.kestrel.transport.sockets.sockettransportoptions.createboundlistensocket?view=aspnetcore-8.0#microsoft-aspnetcore-server-kestrel-transport-sockets-sockettransportoptions-createboundlistensocket).

```cs
public sealed class NamedPipeTransportOptions
{
    // ...

    Func<EndPoint, PipeSecurity> CreatePipeSecurity { get; set; }

    // ...
}
```

Although I think we should look to see if there are any other settings that should be configurable. Maybe we should allow someone to override creating the whole pipe, e.g. `Func<EndPoint, NamedPipeServerStream> CreatePipe { get; set; }`

**Comment by JamesNK** [comment]
No one had asked.

I think if we do this then we would have a func similar to [SocketTransportOptions.CreateBoundListenSocket](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.server.kestrel.transport.sockets.sockettransportoptions.createboundlistensocket?view=aspnetcore-8.0#microsoft-aspnetcore-server-kestrel-transport-sockets-sockettransportoptions-createboundlistensocket).

```cs
public sealed class NamedPipeTransportOptions
{
    // ...

    Func<EndPoint, PipeSecurity> CreatePipeSecurity { get; set; }

    // ...
}
```

Although I think we should look to see if there are any other settings that should be configurable. Maybe we should allow someone to override creating the whole pipe, e.g. `Func<EndPoint, NamedPipeServerStream> CreatePipe { get; set; }`

**Comment by kenans** [comment]
> @kenans Thanks for the suggestion! Can you tell us a bit more about what you'd do with this functionality? What's an example of where pipes would benefit from having different `PipeSecurity`s?

The idea is to have more granular control over the named pipe permissions (DACL) via `PipeSecurity`. E.g.
- "./pipe/user" allows access from both Users and Administrators
- "./pipe/admin" only allows access from Administrators

**Comment by kenans** [comment]
@JamesNK  Thank you for the reply!

Both `NamedPipeTransportOptions.CreatePipeSecurity` and `NamedPipeTransportOptions.CreateBoundServerPipe` look good to me. 

Regarding the BYO pipe proposal, it would be nice to clarify that existing settings in `NamedPipeTransportOptions` would not apply if `CreateBoundServerPipe` is set, as `NamedPIpeServerStream` would be fully controlled by the factory method.
