### ISSUE TITLE
microsoft.aspnetcore.components.webview v8.0.1 nuget BUG

### ISSUE THREAD

**Issue by kimdiego2098** [dotnet/aspnetcore#53318]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![image](https://github.com/dotnet/aspnetcore/assets/82756760/5a2b35b3-7cee-4022-9618-941dd0549b8c)
build props import path error，and this is an unnecessary import .

that will result in compilation failure
![image](https://github.com/dotnet/aspnetcore/assets/82756760/27ae4af1-1d72-4187-a78d-b8ca9b97c46d)

### .NET Version

net8

**Comment by egvijayanand** [comment]
Yes facing this issue in v8.0.1 whereas 8.0.0 works fine.

![image](https://github.com/dotnet/aspnetcore/assets/81947404/29c03d62-60fe-49bb-820f-5b134e05299c)

**Comment by javiercn** [comment]
@kimdiego2098 thanks for contacting us.

Yes, this is a known issue in our 8.0.1 package, it's going to be addressed in 8.0.2. In the meantime, rollback to 8.0.0

**Comment by egvijayanand** [comment]
Seems this issue is also applicable to v7.0.15 NuGet package. Please check.
