### ISSUE TITLE
.NET 6/7 migration to .NET 8 with Docker container

### ISSUE THREAD

**Issue by AndreyYaskevich** [dotnet/aspnetcore#53327]
Hi. I am trying to migrate my API to the .NET 8 without any changes in my dockerfile.

Here is dockerfile and it is fully the same as it was for .NET7. They only differences are versions for sdk and for runtime-deps.

```
FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS build
COPY . .
WORKDIR /src/Api

RUN dotnet publish "Api.csproj" -c Release -o /app/ \
    --runtime linux-musl-x64 \
    --self-contained true \
    /p:PublishTrimmed=true \
    /p:PublishSingleFile=true 

FROM mcr.microsoft.com/dotnet/runtime-deps:8.0-preview-alpine AS runtime

EXPOSE 8080

RUN adduser --disabled-password \
  --home /app \
  --gecos '' dotnetuser && chown -R dotnetuser /app

USER` dotnetuser

WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["./Api"]`

```

When I try to reach any endpoint from localhost everything is ok but when I start container calls to any endpoint fail with 404. I was getting error when building container. 
```
Using member 'Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddControllers(IServiceCollection)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. MVC does not currently support trimming or native AOT.
```
Is this the root cause of my problem?

**Comment by martincostello** [comment]
MVC is not supported for native AoT ([docs](https://learn.microsoft.com/aspnet/core/fundamentals/native-aot#aspnet-core-and-native-aot-compatibility)) as noted in the compiler warning.

My guess would be that this wasn't _explicitly_ noted with an attribute in previous releases as native AoT wasn't supported, so you didn't get the warning, and for the specific code your application has it might have _happened_ to work.

**Comment by lbussell** [comment]
Also, @AndreyYaskevich, I noticed that you should remove the `preview` from your `runtime` image layer - `mcr.microsoft.com/dotnet/runtime-deps:8.0-alpine`

**Comment by davidfowl** [comment]
Before .NET 8, trimming for ASP.NET Core applications meant "partial trimming", a strange hybrid that "worked" but didn't trim as much as it could (see https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trimming-options?pivots=dotnet-8-0#trimming-granularity)

cc @agocke

**Comment by AndreyYaskevich** [comment]
> Also, @AndreyYaskevich, I noticed that you should remove the `preview` from your `runtime` image layer - `mcr.microsoft.com/dotnet/runtime-deps:8.0-alpine`

It didn't work even on 'non-preview' runtime-deps. But Thanks. I think that is enough and @martincostello said that it wasn't explicitly noted in previous releases.

**Comment by AndreyYaskevich** [comment]
Hello again. Sorry I reopened issue because I see a new one error related. I have tried non trimmed version and it still doesn't work. 

Here is the dockerfile.

```Dockerfile
FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS build
COPY . .
WORKDIR /src/Api
RUN dotnet publish "Api.csproj" -c Release -o /app/
FROM mcr.microsoft.com/dotnet/aspnet:8.0-alpine AS runtime

EXPOSE 8080

RUN adduser --disabled-password \  
	--home /app \  
	--gecos '' dotnetuser && chown -R dotnetuser /app

USER dotnetuser
WORKDIR /appCOPY --from=build /app .
ENV ASPNETCORE_URLS="http://+:8080"
ENTRYPOINT ["dotnet", "Api.dll"]
```

I have updated ports according breaking changes in .NET8. I have also tried with root user, without creating my own and with user that is predefined in image.

And the output from LogStream from the app service. This log message is looping every time I call the app.

``` 2024-01-22T12:34:07.386729381Z: [ERROR]  cp: target '/etc/pki/ca-trust/source/anchors' is not a directory
2024-01-22T12:34:10.314818843Z: [INFO]  Updated CA certificates
2024-01-22T12:34:12.951157026Z: [INFO]  {"EventId":0,"LogLevel":"Information","Category":"Program","Message":"Entering app startup."}
2024-01-22T12:34:16.887539848Z: [INFO]  Hosting environment: Production
2024-01-22T12:34:16.894896065Z: [INFO]  Content root path: /app
2024-01-22T12:34:16.896032860Z: [INFO]  Now listening on: http://[::]:8081/appsvctmp/volatile/logs/runtime/299d7557db7e90106cb4dd695c7b704ea7da8db69e5e3689c4392b4ff6f2d066.log
```

![image](https://github.com/dotnet/aspnetcore/assets/18084166/8ee7fcd3-9a17-4d52-aa03-32f79aed561b)

**Comment by AndreyYaskevich** [comment]
> Can it be related to https://learn.microsoft.com/en-us/dotnet/core/compatibility/containers/8.0/aspnet-port ?

Hi. Thanks for the response. Issue was related to the image which is runtime-deps. It doesn't support full MVC.
