### ISSUE TITLE
Grafana dashboards by dotnetteam are not working without fixing metrics names

### ISSUE THREAD

**Issue by Ne4to** [dotnet/aspnetcore#53322]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Dashboars https://grafana.com/orgs/dotnetteam need to be modified to start working.
`http_server_request_duration_seconds_bucket` should be changed to `http_server_request_duration_s_bucket` (`s` instead of `seconds`)

[HostingMetrics](https://github.com/dotnet/aspnetcore/blob/main/src/Hosting/Hosting/src/Internal/HostingMetrics.cs#L31) uses `s` for unit parameter.

### Steps To Reproduce

- Create new ASP.NET 8 project
- Add metrics - https://learn.microsoft.com/en-us/aspnet/core/log-mon/metrics/metrics?view=aspnetcore-8.0
- Setup Grafana and import dashboards from https://grafana.com/orgs/dotnetteam

### .NET Version

8.0.100

**Comment by JamesNK** [comment]
Are you using the latest version of OpenTelemetry? There are changes in the Prometheus output that might cause the mismatch that you're seeing.

**Comment by Ne4to** [comment]
I created a new project, and it works without changes in dashboards. 

The original issue was reproduced on a project that migrated from .NET 7 to .NET 8 and it used old packages.
- OpenTelemetry.Extensions.Hosting 1.4.0 instead of 1.7.0
- OpenTelemetry.Exporter.Prometheus.AspNetCore 1.4.0-rc.4 instead of 1.7.0-rc.1

Thanks
