### ISSUE TITLE
Not all libraries are publishing a grpc server with mongodb when using the 'Trim unused code' option checked

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#53331]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Not-all-libraries-are-publishing-a-grpc-/10555386)._

---
[severity:Other]
I am using Microsoft Visual Studio Community 2022 (64-bit) - Current, Version 17.8.3. Today, I published a gRPC solution to deploy it to Ubuntu. This has worked flawlessly until I found this: When the 'File Publish Options' 'Time unused code' is checked I found that not all required libraries are included in the single file output. I am using the 'Self-contained' deployment mode.

I have MongoDB in the solution. When I deployed this published output, mongod would not start because it was missing MongoDB.Libmongocrypt.dll. I then went back and unchecked the trim unused code option, deployed the app again, and low and behold, MongoDB started like normal.

So, while I am not certain what caused this, but my observation is that too much required code was trimmed.

---
#### Feedback Bot on 1/8/2024, 06:47 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by JamesNK** [comment]
This doesn't look like a gRPC issue. Trimming is causing problems with other libraries in the gRPC app.
