### ISSUE TITLE
Blazor: add support for beforetoggle event

### ISSUE THREAD

**Issue by chucker** [dotnet/aspnetcore#53336]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am trying to use [`onbeforetoggle`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/beforetoggle_event) to manipulate an element _before_ it appears.

### Describe the solution you'd like

Support `onbeforetoggle`. The event type is `ToggleEvent`, which we already have.

### Additional context

The larger goal here was to use https://developer.mozilla.org/en-US/docs/Web/API/Popover_API.

**Comment by xcaptain** [comment]
@javiercn Hello, I'm also trying the new popover api on blazor wasm, I have a similar problem, I don't need to listen to the `beforetoggle` event, I want to know how to call the `hidePopover` method of the popover dom element. For example, I want to hide the popover after I clicked the dropdown items.

![image](https://github.com/dotnet/aspnetcore/assets/4054836/97c9d341-69c5-46aa-bc82-10df6e5fbac5)

Mozilla doc: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/hidePopover
