### ISSUE TITLE
what's different between use and not use await base.OnAfterRenderAsync

### ISSUE THREAD

**Issue by MahdiElahi** [dotnet/aspnetcore#53357]
what's different between use and not use await base.OnAfterRenderAsync ?
what's different between these codes ?

```
@functions {
    protected async override Task OnAfterRenderAsync(bool firstRender)
    {

        if (!firstRender)
        {
            IsDataLoaded = true;
            StateHasChanged();
        }
        await base.OnAfterRenderAsync(firstRender);

    }
}
```
and

```
@functions {
    protected async override Task OnAfterRenderAsync(bool firstRender)
    {

        if (!firstRender)
        {
            IsDataLoaded = true;
            StateHasChanged();
        }


    }
```

**Comment by CrahunGit** [comment]
Depend on your base class. If base class has functionality you’ll need to call its method. For example, if you inherit on fluxor’s base class you’ll need this call in order to work properly.

**Comment by guardrex** [comment]
We only address calling the base class in docs for `SetParametersAsync`. I've opened an issue to add a remark to the other lifecycle method sections. https://github.com/dotnet/AspNetCore.Docs/issues/31449
