### ISSUE TITLE
Error : Normalizing '_blazor' to ... in balzor .net 8

### ISSUE THREAD

**Issue by MahdiElahi** [dotnet/aspnetcore#53356]
Hi,
My website is worked correctly and it's web app blazor 8 but when run project i have this error in inspect element ? what is the problem ?

![Capture](https://github.com/dotnet/aspnetcore/assets/32883870/9e8fad39-ca95-48ec-b63b-8ab57676172d)

**Comment by javiercn** [comment]
@MahdiElahi thanks for contacting us.

It seems in your case there is an issue with hotreload.
