### ISSUE TITLE
Default Tagless Container Component

### ISSUE THREAD

**Issue by stevenpua** [dotnet/aspnetcore#53363]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Greetings everyone, By any chance is there a default way to render multiple components without writing our own containing component? This way we can do multiple td or li with conditions or loop. More of a syntax sugar. I think this has been around in razor pages. the work around for this is usually just a partial.

** This is more of a question than a feature request. Feel free to close this if needed.**

this can be done by writing your own component
Fragment.razor
```
@ChildContent
@code{
    [Parameter]
    public RenderFragment? ChildContent { get; set; }
}
```

### Describe the solution you'd like

```
<ul>
<li>A</li>
<li>B</li>

@if(condition)
{
<>

<li>C</li>
<li>D</li>
</>

}
</ul>
```

e.g. 

```
RenderFragment<Person> RenderPerson = (person) =>
@<>
<li>@person.Name</li>
<li>@person.Age</li>
</>

```

or 

```
RenderFragment<Person> RenderPerson = (person) =>
@<Fragment>
<li>@person.Name</li>
<li>@person.Age</li>
</Fragment>
```

**Comment by javiercn** [comment]
@stevenpua thanks for contacting us.

You can already do this in Blazor without the need for `<>` or `<Fragment>`. Blazor components don't require a container tag to render.

>

**Comment by stevenpua** [comment]
Hi @javiercn Thank you for the quick response. I was able to do this with the condition. By any chance, what's the default way to do this for razor templates?

[https://learn.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-8.0#razor-templates](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-8.0#razor-templates)
