### ISSUE TITLE
Add Clear [Documentation] For [Blazor Auto Mode ]

### ISSUE THREAD

**Issue by AmBplus** [dotnet/aspnetcore#53367]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

When going in blazor doc in microsoft website , I see blazor server or assembly , now we have another aproach , the auto render mode , there some problem when running on this mode , from the send a simple request that's  need cookie of user and we don't know now we are in server or wasm to decided how handle this request to more advance senario , but the doc still are based on just assembly or just server , now many like are confused by this new approach 

### Describe the solution you'd like

Create a clear doc for this new auto render mode

**Comment by gregorygandy** [comment]
Is this what you are looking for? https://learn.microsoft.com/en-us/aspnet/core/blazor/components/render-modes?view=aspnetcore-8.0#automatic-auto-rendering

**Comment by guardrex** [comment]
@AmBplus ... Make sure that the doc version selector is set to 8.0 ...

![image](https://github.com/dotnet/aspnetcore/assets/1622880/3507af66-6f3f-4db1-ad48-2cccd89f176e)

The article on render modes is the one that @gregorygandy mentioned ...

https://learn.microsoft.com/aspnet/core/blazor/components/render-modes

**Comment by AmBplus** [comment]
@guardrex Tnx For Reply , I Can't Find Any Resource For Handling HttpClinet In Blazor Auto Render Mode , How Handle Request When We Need Get Resource From Secure Api ?  
https://stackoverflow.com/questions/78040387/handling-requests-in-blazor-auto-render-mode

**Comment by guardrex** [comment]
@AmBplus ... I just opened an issue on the docs repo from the bottom of the *Call web API* article. We have a link on each article that opens an issue with metadata for tracking.

BTW for future reference, we don't work on closed issues/PRs. Always open a new issue ... either on this repo for product unit support or from the bottom of an article for documentation support.
