### ISSUE TITLE
Error : Cannot read properties of null (reading 'removeChild'))

### ISSUE THREAD

**Issue by MahdiElahi** [dotnet/aspnetcore#53372]
Hi 
some times in project i have this error , what's problem ? 

**blazor.web.js:Error: System.AggregateException: One or more errors occurred. (TypeError: Cannot read properties of null (reading 'removeChild'))
 ---> System.InvalidOperationException: TypeError: Cannot read properties of null (reading 'removeChild')
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InvokeRenderCompletedCallsAfterUpdateDisplayTask(Task updateDisplayTask, Int32[] updatedComponents)
   --- End of inner exception stack trace ---**

**Comment by javiercn** [comment]
@MahdiElahi thanks for contacting us.

Very likely you are manipulating the DOM in a way that is not supported by Blazor.

**Comment by MahdiElahi** [comment]
Hi,
when i use show dialog  if i click cancel or click on close icon website is worked correctly 
![Capture1](https://github.com/dotnet/aspnetcore/assets/32883870/d4d71cc4-50b3-4b4f-892f-734a375ccd1e)

but when show dialog after that i click on nav menu and navigation to other page , the other page is not work and show this error : 
![Capture](https://github.com/dotnet/aspnetcore/assets/32883870/c1c9a9ac-46fd-4bc2-a010-3841997f25cb)

 

what's problem ? why i must close dialog ?

<SfDialog Width="300px" ShowCloseIcon="true" IsModal="true" @bind-Visible="@IsVisible">
    <DialogTemplates>
        <Header> Delete </Header>
        <Content> Are you want to delete this books ? </Content>
    </DialogTemplates>
    <DialogButtons>
        <DialogButton Content="Delete" IsPrimary="true" OnClick="@OkClick" />
        <DialogButton Content="Cancel" OnClick="@CancelClick" />
    </DialogButtons>
</SfDialog>
 Copy



 private void OpenDialog(int Id)
 {
     RowId = Id;
     this.IsVisible = true;
 }


 private void CancelClick()
 {
     this.IsVisible = false;
 }
 private async Task OkClick()
 {
    // Delete Record Codes

**Comment by MahdiElahi** [comment]
@javiercn 
what are you means ?  please explain more for manipulating the DOM ?? can you show an example.

**Comment by UdhayaKumarDuraisamy** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/UDHAYA~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/UDHAYA~1/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/UDHAYA~1/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">




</head>

<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>


<p class=MsoNormal><b><span style='font-size:10.0pt;line-height:107%;
mso-bidi-font-family:Calibri;mso-bidi-theme-font:minor-latin'>Title</span></b><span
style='font-size:10.0pt;line-height:107%;mso-bidi-font-family:Calibri;
mso-bidi-theme-font:minor-latin'>: Unhandled exception: When using popup
components on an InteractiveServer page and navigating to any other
InteractiveServer page<o:p></o:p></span></p>

<p class=MsoNormal><span style='font-size:10.0pt;line-height:107%;mso-bidi-font-family:
Calibri;mso-bidi-theme-font:minor-latin'>&nbsp;<o:p></o:p></span></p>

<p class=MsoNormal><span style='font-size:10.0pt;line-height:107%;mso-bidi-font-family:
Calibri;mso-bidi-theme-font:minor-latin'>I’m using DotNET 8 web app with render
mode set as InteractiveServer. I’m using the custom toast component as a
service in Home.razor, where I have used @rendermode InteractiveServer and I
have also used @rendermode InteractiveServer on the counter.razor. However, in
the weather.razor page, I <span style='mso-spacerun:yes'> </span>have not used
@rendermode InteractiveServer. The toast component is referenced in the
Home.razor page, where it is called and displayed as expected. When trying to
switch to the counter.razor page, a console error is thrown. However, when the
@rendermode InteractiveServer is used in the app.razor page, no errors occur.<o:p></o:p></span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt;line-height:107%;
mso-bidi-font-family:Calibri;mso-bidi-theme-font:minor-latin'>&nbsp;</span></b><span
style='font-size:10.0pt;line-height:107%;mso-bidi-font-family:Calibri;
mso-bidi-theme-font:minor-latin'><o:p></o:p></span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt;line-height:107%;
mso-bidi-font-family:Calibri;mso-bidi-theme-font:minor-latin'>Exception</span></b><span
style='font-size:10.0pt;line-height:107%;mso-bidi-font-family:Calibri;
mso-bidi-theme-font:minor-latin'>: <o:p></o:p></span></p>


Unhandled exception rendering   component: TypeError: Cannot read properties of null (reading 'removeChild')           System.InvalidOperationException: TypeError: Cannot read properties of   null (reading 'removeChild')            at   Microsoft.AspNetCore.Components.RenderTree.Renderer.InvokeRenderCompletedCallsAfterUpdateDisplayTask(Task   updateDisplayTask, Int32[] updatedComponents)   fail:   Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]           Unhandled exception in circuit   'CiJ96TpgM1VO65wsAsAavgXRuV_Q0U9_XIeir463WOM'.           System.AggregateException: One or more errors occurred. (TypeError:   Cannot read properties of null (reading 'removeChild'))          --->   System.InvalidOperationException: TypeError: Cannot read properties of null   (reading 'removeChild')            at   Microsoft.AspNetCore.Components.RenderTree.Renderer.InvokeRenderCompletedCallsAfterUpdateDisplayTask(Task   updateDisplayTask, Int32[] updatedComponents)            --- End of inner exception stack   trace ---
--




<p class=MsoNormal><span style='font-size:10.0pt;line-height:107%;mso-bidi-font-family:
Calibri;mso-bidi-theme-font:minor-latin'>&nbsp;<o:p></o:p></span></p>

<p class=MsoNormal><span style='font-size:10.0pt;line-height:107%;mso-bidi-font-family:
Calibri;mso-bidi-theme-font:minor-latin'>We have encountered the same issue
when using custom dialog as a service. We have not utilized or handled
&quot;removeChild&quot; on popup components. Additionally, the issue only
arises on DotNET 8 web applications. The same works on DotNET 6 &amp; 7 Blazor
applications.<o:p></o:p></span></p>


</body>

</html>

**Comment by sxjoy** [comment]
I had the same issue and seems like it was caused by  Bootstrap Dismissible Alerts. Placing them inside another div fixed the issue for me.
https://stackoverflow.com/questions/60183421/blazor-typeerror-cannot-read-property-removechild-of-null-at-object-e-as-rem

**Comment by BigBang1112** [comment]
This cryptic error happens most often when some JS library comes in to change the DOM. As mentioned above, wrapping the affected element in a div (or something else so that the affected element isn't at the root of the component) will do the job.
