### ISSUE TITLE
`UseDirectoryBrowser` option for JSON responses

### ISSUE THREAD

**Issue by lostmsu** [dotnet/aspnetcore#53421]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Between `UseStaticFiles` and `UseDirectoryBrowser` I want to be able to programmatically list and download files from the server

### Describe the solution you'd like

Ideally, Directory Browser should check `Accept` header and respond in JSON if it is set to `application/json`

**Comment by Tratcher** [comment]
You can do this by setting the IDirectoryFormatter:
https://github.com/dotnet/aspnetcore/blob/b027cc39c088e8a260a6feb496c5393729607943/src/Middleware/StaticFiles/src/DirectoryBrowserOptions.cs#L34
