### ISSUE TITLE
[NETSDKE2E]Warning "Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[16] The WebRootPath was not found: C:\Users\xxx\web\razorcli\wwwroot. Static files may be unavailable." displays after running razor.dll file in CLI.

### ISSUE THREAD

**Issue by vdanche** [dotnet/aspnetcore#53432]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

1.warning "Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[16] The WebRootPath was not found: C:\Users\xxx\web\razorcli\wwwroot. Static files may be unavailable." displayed after running razor.dll file in CLI.
![image](https://github.com/dotnet/aspnetcore/assets/65637796/f332a8e6-7c20-4b3b-abb8-0f67461defc4)
2. Click http://localhost:5000, the page cannot be displayed well
![image](https://github.com/dotnet/aspnetcore/assets/65637796/ae07b637-1095-46c7-a101-6735f9acd26b)

### Expected Behavior

There is no any errors and warning after running *dll file. and the page( http://localhost:5000) can display well

### Steps To Reproduce

Build:
dotnet-sdk-8.0.200-preview.24064.2-win-x64 from https://github.com/dotnet/installer on windows11

1.mkdir web
2. cd web
3.dotnet new sln -o razorcli
4.cd razorcli
5.dotnet new razor -o razortest
6.dotnet sln add razortest\razortest.csproj
7.dotnet build
8.dotnet C:\Users\v-danche\web\razorcli\razortest\bin\Debug\net8.0\razortest.dll
9.open the link http://localhost:500

### Exceptions (if any)

8.warning "Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[16] The WebRootPath was not found: C:\Users\xxx\web\razorcli\wwwroot. Static files may be unavailable." displayed after running razor.dll file in CLI.
![image](https://github.com/dotnet/aspnetcore/assets/65637796/d56f427d-a8c2-41cd-a60c-cc985456e131)

9.The page cannot display well.
![image](https://github.com/dotnet/aspnetcore/assets/65637796/ae07b637-1095-46c7-a101-6735f9acd26b)

C:\Users\v-danche\web\razorcli>dotnet C:\Users\v-danche\web\razorcli\razortest\bin\Debug\net8.0\razortest.dll
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[63]
      User profile is available. Using 'C:\Users\v-danche\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
warn: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[16]
      The WebRootPath was not found: C:\Users\v-danche\web\razorcli\wwwroot. Static files may be unavailable.
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\v-danche\web\razorcli
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:5000/ - - -
warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect.
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint '/Index'
info: Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker[103]
      Route matched with {page = "/Index"}. Executing page /Index
info: Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker[105]
      Executing handler method razortest.Pages.IndexModel.OnGet - ModelState is Valid
info: Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker[108]
      Executed handler method OnGet, returned result .
info: Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker[107]
      Executing an implicit handler method - ModelState is Valid
info: Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker[109]
      Executed an implicit handler method, returned result Microsoft.AspNetCore.Mvc.RazorPages.PageResult.
info: Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker[104]
      Executed page /Index in 59.1026ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint '/Index'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:5000/ - 200 - text/html;+charset=utf-8 116.7429ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:5000/lib/bootstrap/dist/css/bootstrap.min.css - - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:5000/lib/bootstrap/dist/css/bootstrap.min.css - 404 0 - 2.9657ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[16]
      Request reached the end of the middleware pipeline without being handled by application code. Request path: GET **http://localhost:5000/lib/bootstrap/dist/css/bootstrap.min.css, Response status code: 404**
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:5000/css/site.css - - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:5000/razortest.styles.css - - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:5000/razortest.styles.css - 404 0 - 0.4805ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:5000/css/site.css - 404 0 - 1.4374ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[16]
      Request reached the end of the middleware pipeline without being handled by application code. Request path: GET http://localhost:5000/razortest.styles.css, Response status code: 404
info: Microsoft.AspNetCore.Hosting.Diagnostics[16]
      Request reached the end of the middleware pipeline without being handled by application code. Request path: GET http://localhost:5000/css/site.css, Response status code: 404
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:5000/lib/jquery/dist/jquery.min.js - - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:5000/lib/jquery/dist/jquery.min.js - 404 0 - 0.0561ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[16]
      Request reached the end of the middleware pipeline without being handled by application code. Request path: GET http://localhost:5000/lib/jquery/dist/jquery.min.js, Response status code: 404
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:5000/lib/bootstrap/dist/js/bootstrap.bundle.min.js - - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:5000/lib/bootstrap/dist/js/bootstrap.bundle.min.js - 404 0 - 0.0735ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[16]
      Request reached the end of the middleware pipeline without being handled by application code. Request path: GET http://localhost:5000/lib/bootstrap/dist/js/bootstrap.bundle.min.js, Response status code: 404
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:5000/js/site.js - - -
### .NET Version

.NET SDK:
 Version:           8.0.200-preview.24064.2
 Commit:            3662b97225
 Workload version:  8.0.200-manifests.9f3f18d7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.25398
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.200-preview.24064.2\

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.0
  Architecture: x64
  Commit:       5535e31a71

.NET SDKs installed:
  8.0.200-preview.24064.2 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by v-ainigao** [comment]
This problem is also reproduced on Win ARM64.

**Comment by vdanche** [comment]
Also happens on 9.0.100-alpha.1.24066.10 SDK

**Comment by javiercn** [comment]
Can't you point here to the test case where this is defined. The steps are wrong.

I am not able to reproduce it locally. What's likely happening is that you are invoking `dotnet <<path-to-dll>>` from the solution folder instead of from inside `razortest` hence why it's not able to find the `wwwroot` folder.

This behavior hasn't changed.

**Comment by vdanche** [comment]
@javiercn I see what you mean, we re-check our steps, I did invoke dotnet <<path-to-dll>> from the solution folder instead of from inside razortest. 
I access to razortest, and then dotnet <<path-to-dll>>, the issue will not happen.
![image](https://github.com/dotnet/aspnetcore/assets/65637796/a0d9bdff-2753-4be1-834c-2b53b7087e48)
we'll close it as it's not an issue. Thanks again!🙂

**Comment by vdanche** [comment]
> @javiercn I see what you mean, we re-check our steps, I did invoke dotnet <> from the solution folder instead of from inside razortest. so this warning is expected, right? one more thing, if we invoke `dotnet <<path-to-dll>>` from the solution folder instead of from inside razortest, open the link http://localhost:5000/, it show as below and it's also expected? ![image](https://private-user-images.githubusercontent.com/65637796/297645678-805de154-d144-4a39-869b-52542d6de444.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MjE3NDIsIm5iZiI6MTcwNjUyMTQ0MiwicGF0aCI6Ii82NTYzNzc5Ni8yOTc2NDU2NzgtODA1ZGUxNTQtZDE0NC00YTM5LTg2OWItNTI1NDJkNmRlNDQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDA5NDQwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3ZjczMDlmYWJlMzI3M2Y5MGJlZjEyMzRkYmNlODhjMDJlYTM0OGRjYTM2ZmViNGYzOWQwMDBhMDI5OTIyYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vI49tc4tBBt4yb-NAsiTe5XWnp8-WkT-mVpIQwI8_vg)
> 
> I access to razortest, and then dotnet `<<path-to-dll>>`, the issue will not happen. ![image](https://private-user-images.githubusercontent.com/65637796/297575546-a0d9bdff-2753-4be1-834c-2b53b7087e48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MjE3NDIsIm5iZiI6MTcwNjUyMTQ0MiwicGF0aCI6Ii82NTYzNzc5Ni8yOTc1NzU1NDYtYTBkOWJkZmYtMjc1My00YmUxLTgzNGMtMmI1M2I3MDg3ZTQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDA5NDQwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3N2I5N2MzNDZhNmIyYjBhMjM2ZWM2N2U5MDQ1NTZlZjJmNGEyZGJmMmRmNGIzYTk4NWM2ZTUyOTJjZmRlZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kEKdEusrA0CHEM_v8CoQjNq5j6Fe8mrFS8EnbGrIA8Y)

@javiercn if it's expected that must invoke dotnet <<path-to-dll>> from inside razortest instead of from the solution folder,  then  it's also expected that the http://localhost:5000/ link cannot display normally, because we invoke dotnet <<path-to-dll>> from the solution folder. we'll not keep track this issue any more.  Thanks.🙂

**Comment by SubbuRamanathan** [comment]
I faced the same issue with VS Code but interestingly when I upgraded Visual Studio 2022 and tried from VS2022, the sites were working fine without any issues

**Comment by Bond-Addict** [comment]
@vdanche please re-open this. This is still an issue in VS2022 Version 17.12.3

**Comment by vdanche** [comment]
@Bond-Addict I do not have permissions to re-open this issue. file a new bug or ping @javiercn re-open it?

**Comment by WeaselOnaStick** [comment]
I tried booting the dll from the publish folder but I still can't load up any content. I'm trying to learn how to host blazor app and I haven't the foggiest what I'm doing

![Image](https://github.com/user-attachments/assets/22d9d353-5044-4750-afcf-f49dc0114f1f)

![Image](https://github.com/user-attachments/assets/081544c7-9e67-445a-90e7-8b7507cd3ff7)

**Comment by Bond-Addict** [comment]
@WeaselOnaStick what does your bin look like?

**Comment by WeaselOnaStick** [comment]
> @WeaselOnaStick what does your bin look like?

Turns out I had "Generate single file" publish option enabled, which prevented dll generation in bin/release/net9.0/publish.
I went through Microsoft instructions again, reinstalled nginx, edited nginx sites-available/default this time (instead of making custom one), added the forwarding lines fron MS instructions and it worked in the end

**Comment by alexeyzimarev** [comment]
This issue usually indicates that the `ASPNETCORE_ENVIRONMENT` or `DOTNET_ENVIRONMENT` isn't set to `Development`. Implicitly, the static files middleware would use the original `wwwroot` in the source files directory instead of the build output when the environment is set to `Development`. It's not easy to understand as this behaviour is documented very briefly.
