### ISSUE TITLE
Convert all the internal static readonly string values on Microsoft.AspNetCore.Identity.IdentityConstants.cs to const

### ISSUE THREAD

**Issue by asos-javierdorigoni** [dotnet/aspnetcore#53442]
### Is there an existing issue for this? No

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

When using `Authorize` Attribute on my .NET 8 AspNetCore Web API Controllers declaring a specific `AuthenticationSchemes`, I would like to be able to reference a const value from  Microsoft.AspNetCore.Identity.IdentityConstants.
Like in this attached image
![image](https://github.com/dotnet/aspnetcore/assets/88502431/ee17ad1b-675f-4a83-b4b8-a1cc7a9b0bc9)

I am receiving an error of `[CS0182](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/parameter-argument-mismatch?f1url=%3FappId%3Droslyn%26k%3Dk(CS0182)#arguments-for-attributes): An attribute argument must be a constant expression, typeof expression or array creation expression of an attribute parameter type` where it claims that an Argument must be a constant expression, but for example: 
`Microsoft.AspNetCore.Identity.IdentityConstants.ExternalScheme` is not constant.

### Describe the solution you'd like

At `\aspnetcore\src\Identity\Core\src\IdentityConstants.cs` file perform the changes to have this final content:

```
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

namespace Microsoft.AspNetCore.Identity;

/// <summary>
/// Represents all the options you can use to configure the cookies middleware used by the identity system.
/// </summary>
public class IdentityConstants
{
    private const string IdentityPrefix = "Identity";

    /// <summary>
    /// The scheme used to identify application authentication cookies.
    /// </summary>
    public const string ApplicationScheme = IdentityPrefix + ".Application";

    /// <summary>
    /// The scheme used to identify bearer authentication tokens.
    /// </summary>
    public const string BearerScheme = IdentityPrefix + ".Bearer";

    /// <summary>
    /// The scheme used to identify combination of <see cref="BearerScheme"/> and <see cref="ApplicationScheme"/>.
    /// </summary>
    internal const string BearerAndApplicationScheme = IdentityPrefix + ".BearerAndApplication";

    /// <summary>
    /// The scheme used to identify external authentication cookies.
    /// </summary>
    public const string ExternalScheme = IdentityPrefix + ".External";

    /// <summary>
    /// The scheme used to identify Two Factor authentication cookies for saving the Remember Me state.
    /// </summary>
    public const string TwoFactorRememberMeScheme = IdentityPrefix + ".TwoFactorRememberMe";

    /// <summary>
    /// The scheme used to identify Two Factor authentication cookies for round tripping user identities.
    /// </summary>
    public const string TwoFactorUserIdScheme = IdentityPrefix + ".TwoFactorUserId";
}

```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This is not something we plan to do. You are free, however, to use the string values in your apps, as you find them fit, as we also don't plan to change the values of these properties, as those will be a breaking change.
