### ISSUE TITLE
How implement json web token in .net c#?

### ISSUE THREAD

**Issue by aisakk** [dotnet/aspnetcore#53441]
### Discussed in https://github.com/dotnet/aspnetcore/discussions/53438

Hello my friends, i need help, I'm reading this documentation to [implement JWT ](https://learn.microsoft.com/es-es/aspnet/core/security/authentication/jwt-authn?view=aspnetcore-8.0) but the documentation say that this is for development local, but if i want develop the token right from the start or this documentation, Does it help me implement JWT globally?, If so, how would it be implemented?.

I would also like to know if there is documentation about jwt that I can implement in projects or should I just use dotnet new user-jwt? Please, I've been doing this for 3 days and I can't find documentation on how to generate a jwt token.

In a few words, what I want to do is generate a token and pass it through the API so that the frontend can capture it, the backend would be in .net with c#</div>

**Comment by gfoidl** [comment]
Let's resume in the [discussion](https://github.com/dotnet/aspnetcore/discussions/53438) which you also opened.
