### ISSUE TITLE
SDK 8.0.101 - Output Caching and CORS broken - CORS middleware bypassed on the next request

### ISSUE THREAD

**Issue by HummingMind** [dotnet/aspnetcore#53458]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a basic Minimal Web API set up.

The middleware is in the following order:

```
        var app = builder.Build();
        app.UseCors();
        app.UseOutputCache();
        var api = app.MapGroup("/api").RequireCors("MyCustomCorsPolicy")
        api.MapGet("test", TestDelegate).CacheOutput();
        app.Run();
```

When I call this the 1st time from an invalid origin, I get the correct status code (403 Forbidden).
When I call it the first time from a valid origin, the request is returned with a 200 and is cached. However, once it is cached,  when I call the second time with an invalid origin, I get a 200 back with the data. This shouldn't be happening. CORS is not being checked on the second request.

I have the CORS middleware first and then the output caching middleware, so the order seems correct. I also used the RequireCors on the endpoint that is being mapped via MapGroup. Am I missing something? Is this a bug?

Thank you!

### Expected Behavior

I should be getting a 403 again, on the second requst that is coming from an invalid origin.

**Comment by BrennanConroy** [comment]
403 isn't a CORS response.

**Comment by HummingMind** [comment]
> 403 isn't a CORS response.

You are correct. I had an endpoint filter that was returning that code. I disabled it, and tried again. I am getting 200 now every time, even with an invalid origin.
