### ISSUE TITLE
Blazor .net 8 Cannot access a disposed context instance 

### ISSUE THREAD

**Issue by MahdiElahi** [dotnet/aspnetcore#53450]
Hi
my project is blazor .net 8 and use syncfucion data grid 

but when user click on pager grid **continuous** (when click on pager number call service to get data by page number )  
![Capture](https://github.com/dotnet/aspnetcore/assets/32883870/04a98367-153b-440f-984e-18a3d563ff16)

in repository show this error : 

**Cannot access a disposed context instance. A common cause of this error is disposing a context instance that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling 'Dispose' on the context instance, or wrapping it in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.
Object name: 'ApplicationDbContext'.**

AircraftRepository.cs

![Capture](https://github.com/dotnet/aspnetcore/assets/32883870/163ebea9-9c84-44ca-bbe6-372857e25085)

Index.Razor
```
<SfGrid @ref="Grid" TValue="AircraftViewModel"  AllowSorting="true" AllowFiltering="true" AllowPaging="true" RowHeight="50" Height="600">

     <SfDataManager Adaptor="Adaptors.CustomAdaptor" AdaptorInstance="@typeof(CustomAdaptor)"></SfDataManager>
   
     <GridPageSettings PageSize="25" PageSizes="@pagerDropdown" PageCount="5">
     </GridPageSettings>
                <GridColumn Field=@nameof(AircraftViewModel.Country) HeaderText="Register Number" Width="150" TextAlign="TextAlign.Center"></GridColumn>

```

CustomAdaptor.cs for server side rendering Data Grid
 ```
public class CustomAdaptor : DataAdaptor
 {
     private readonly IAircraftService
     public CustomAdaptor(IAircraftService aircraftService)
     {
         this.aircraftService= aircraftService;
     }

     public override async Task<object> ReadAsync(DataManagerRequest dataManagerRequest, string additionalParam = null)
     {
         FilterViewModel filteringViewModel = new();

         var result = await aircraftService.GetAllAsync(filteringViewModel);

         DataResult dataResult = new DataResult
         {
             Count = result.Count,
             Result = result.Result
         };
         return dataResult;
     }
 }
```
AircraftService.cs
```
  public async Task<FilterResult<AircraftViewModel>> GetAllAsync(FilterViewModel filterViewModel)
  {
      var mapped = ObjectMapper.Mapper.Map<FilterResult<AircraftViewModel>>(await aircraftRepository.GetAllAsync(filterViewModel));
      return mapped;
  }

```

1 .add lifetime transient : 

```
builder.Services.AddDbContext<ApplicationDbContext>(options =>
    options.UseSqlServer(connectionString), ServiceLifetime.Transient); 
```
**but it's not worked**
    
2 . then change DBContext to AddDbContextFactory and **it's not worked**
```
 builder.Services.AddDbContextFactory<ApplicationDbContext>(options =>
    options.UseSqlServer(connectionString), ServiceLifetime.Transient);
```
  3. i use await/async in all codes and methods 

  
but i have this error ,   what's problem ?

**Comment by MariovanZeist** [comment]
@MahdiElahi The problem that you are running into has to do with the default lifetime of a DbContext when instantiated from DI.
The default lifetime is Scoped. As it turns out, the lifetime of your entire blazor application is also scoped, so in essence every time you instantiated a DbContext from DI you will get the same instance back. If at any time you dispose of the DbContext, DI will still try and return the same instance to you (which is now disposed, hence the error you get)

To work around this, you  could use the factory pattern.
More information can be found here: https://learn.microsoft.com/en-us/aspnet/core/blazor/blazor-ef-core?view=aspnetcore-8.0#new-dbcontext-instances

**Comment by MahdiElahi** [comment]
@MariovanZeist 
Thank you 
**but it's not worked** i still have above error  i change DbContext to DbContextFactory / this is my codes 
```

private readonly IDbContextFactory<ApplicationDbContext> db;
// private readonly ApplicationDbContext db;
protected IQueryable<Aircraft>? query = null;
public AircraftRepository(IDbContextFactory<ApplicationDbContext> db)
{
    this.db = db;
}

public async Task<FilterResult<Aircraft>> GetAllAsync(FilterViewModel filterViewModel)
{

    try
    {
        using (var context = db.CreateDbContext())
        {
            query = context.Set<Aircraft>();

            //Filtering(filterViewModel);
            //Sorting(filterViewModel);

            var result = await query.Skip(filterViewModel.Skip).Take(filterViewModel.Take).AsNoTracking().ToListAsync();

            return new FilterResult<Aircraft>
            {
                Result = result,
                Count = await query.CountAsync()
            };
        }
    }
    catch (Exception ex)
    {

        throw;
    }
}
}

```

and change program.cs to
`builder.Services.AddDbContextFactory<ApplicationDbContext>(options =>  options.UseSqlServer(connectionString), ServiceLifetime.Transient);`

how to solve this problem ? 

this error happend when user click continuous on pager number , and grid must get data

**Comment by javiercn** [comment]
@MahdiElahi thanks for contacting us.

What's the callstack for the exception.
