### ISSUE TITLE
[DataProtection] Lack of multitenancy is a blocker

### ISSUE THREAD

**Issue by cfauchere** [dotnet/aspnetcore#53455]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

As far as our investigation went it does not seem possible to use DataProtection in a multi tenant service. What we have been trying to do is to dedicate encryption keys to their specific tenants instead of sharing them. When doing partition move we want to move only the keys for the moving partition. Looking at the extensibility model we did not find a way to support that scenario.

### Describe the solution you'd like

As described in the problem statement instead of using a single keyring system we'd like to use a ring per tenant to enable scenarios like tenant move. We have been looking to extend DPAPI but it does not seem we have any hook to drive the generation/retrieval of tenant based keys. We investigated the source code and though there might be some possibility with some internal interfaces it seems dangerous from a maintainability perspective. Alternatively we are considering to implement our own Data Protection layer.

**Comment by amcasey** [comment]
@cfauchere Have you seen [this doc](https://learn.microsoft.com/aspnet/core/security/data-protection/consumer-apis/purpose-strings-multitenancy)?

**Comment by cfauchere** [comment]
> @cfauchere Have you seen [this doc](https://learn.microsoft.com/aspnet/core/security/data-protection/consumer-apis/purpose-strings-multitenancy)?

Yes, it does not address tenant segregation for keys. What we need is to create different encryption keys for each tenant.

**Comment by amcasey** [comment]
I'm not sure I follow.  Keys derived from different purpose strings can't decrypt each other's data or work backwards to the key from which they were both derived.  Is that not a sufficient level of protection?

**Comment by amcasey** [comment]
I believe data protection assumes the user-provided key will be used to encrypt the keyring, rather than the data itself.

Is your request essentially the same as https://github.com/dotnet/aspnetcore/issues/43500?

**Comment by cfauchere** [comment]
@amcasey, yes I think the problem is similar. if I am not mistaken they want to bring a master key based on some context which allow to bring your own master key.

**Comment by amcasey** [comment]
Thanks!  In that case, I'm going to close this one, to make it easier to track how much demand there is for that functionality.  There will be a link to this issue, but feel free to chime in there with additional requirements or considerations.
