### ISSUE TITLE
Fix skipped redis unit tests

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/aspnetcore#5345]
Updating to 2.X.X of StackExchange,Redis broke the unit tests because we can't properly mock the `ISubscriber` class.

This is for tracking https://github.com/StackExchange/StackExchange.Redis/issues/969 and fixing our unit tests once a fix has been made.

**Comment by anurse** [comment]
This is basically a 95% test fix, but we *may* need to flow a new abstraction through the product code to make it feasible. We'll get the fix ready and see how tactics feels.

**Comment by Pilchie** [comment]
@anurse is this still happening?  It's in the preview2 milestone and unassigned.

**Comment by anurse** [comment]
Nope, I'll unmilestone it and we'll schedule for 5.0 (and backport if we feel we need the coverage in 3.1.x).
