### ISSUE TITLE
OAuth token endpoint failure when token contain an empty error field

### ISSUE THREAD

**Issue by Guohui-Peng** [dotnet/aspnetcore#53457]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using AddOAuth to add authentication and the returned token contains an empty error field, an Unknown location error will be reported.

Token example:
{
    "access_token":"xxxxx",
    "refresh_token":"xxxx",
    "expires_in":7199,
    "token_type":"Bearer",
    "error":""
}

Error:
![error](https://github.com/dotnet/aspnetcore/assets/93329876/59990a07-91d2-42e4-81aa-8e328ba88ace)

### Expected Behavior

The error field does not exist, is empty, or is null, which means the acquisition is successful.

### .NET Version

.Net 7 and 8

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Which providers do you experience this behavior with?
