### ISSUE TITLE
IJSRuntime doesn't Serialize/Deserialize as expected

### ISSUE THREAD

**Issue by shui106** [dotnet/aspnetcore#53465]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I followed this Section "Save app state before an authentication operation with session storage" in the doc https://learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/additional-scenarios?view=aspnetcore-8.0.
But it doesn't work.

Here are my test codes from default Blazor Web App template(Interactive Server).

```
@page "/counter"
@using System.Text.Json
@inject IJSRuntime JS

<PageTitle>Counter</PageTitle>

<h1>Counter</h1>

<p role="status">Current count: @currentCount</p>

<button class="btn btn-primary" @onclick="IncrementCount">Click me</button>

@code {
    private int currentCount = 0;

    private async void IncrementCount()
    {
        currentCount++;

        var user = new User
            {
                Age = 10,
                Name = "Test"
            };
        await JS.InvokeVoidAsync("sessionStorage.setItem", "user", user);

        var savedUser = await JS.InvokeAsync<User>("sessionStorage.getItem", "user");
    }

    class User
    {
        public int Age { get; set; }
        public string Name { get; set; } = string.Empty;
    }
}

```

This one doesn't serialize User correctly. It only save a string value with "[object Object]" other than a JSON string.
`await JS.InvokeVoidAsync("sessionStorage.setItem", "user", user);`

And this one doesn't deserialize value to User and will cause an exception "Microsoft.JSInterop.JSException: 'An exception occurred executing JS interop: The JSON value could not be converted to ......+User."
`var savedUser = await JS.InvokeAsync<User>("sessionStorage.getItem", "user")`

### Expected Behavior

IJSRuntime should Serialize/Deserialize correctly as the doc shows.

### Steps To Reproduce

Provided in the description.

### Exceptions (if any)

Microsoft.JSInterop.JSException: 'An exception occurred executing JS interop: The JSON value could not be converted to BlazorServer.Pages.Counter+User. Path: $ | LineNumber: 0 | BytePositionInLine: 17.. See InnerException for more details.'

### .NET Version

8.0

**Comment by javiercn** [comment]
@shui106 thanks for contacting us.

That's a bug in your code, `sessionStorage.setItem` doesn't take an object, it takes in a string, so you need to serialize the object before you call JS.InvokeAsync. 

See https://developer.mozilla.org/en-US/docs/Web/API/Storage/setItem

**Comment by shui106** [comment]
Hi @javiercn , thanks for your answer. I was following the example codes in this Section "Save app state before an authentication operation with session storage" in the doc https://learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/additional-scenarios?view=aspnetcore-8.0.

Here is the official example. It is doing the same way. I guess the doc has a misleading example.
```
@using Microsoft.AspNetCore.Components.WebAssembly.Authentication
@inject IAccessTokenProvider TokenProvider
@inject IJSRuntime JS
@inject NavigationManager Navigation

<EditForm Model="User" @onsubmit="OnSaveAsync">
    <label>User
        <InputText @bind-Value="User.Name" />
    </label>
    <label>Last name
        <InputText @bind-Value="User.LastName" />
    </label>
</EditForm>

@code {
    public class Profile
    {
        public string? Name { get; set; }
        public string? LastName { get; set; }
    }

    public Profile User { get; set; } = new Profile();

    protected override async Task OnInitializedAsync()
    {
        var currentQuery = new Uri(Navigation.Uri).Query;

        if (currentQuery.Contains("state=resumeSavingProfile"))
        {
            User = await JS.InvokeAsync<Profile>("sessionStorage.getItem", 
                "resumeSavingProfile");
        }
    }

    public async Task OnSaveAsync()
    {
        var http = new HttpClient();
        http.BaseAddress = new Uri(Navigation.BaseUri);

        var resumeUri = Navigation.Uri + $"?state=resumeSavingProfile";

        var tokenResult = await TokenProvider.RequestAccessToken(
            new AccessTokenRequestOptions
            {
                ReturnUrl = resumeUri
            });

        if (tokenResult.TryGetToken(out var token))
        {
            http.DefaultRequestHeaders.Add("Authorization", 
                $"Bearer {token.Value}");
            await http.PostAsJsonAsync("Save", User);
        }
        else
        {
            await JS.InvokeVoidAsync("sessionStorage.setItem", 
                "resumeSavingProfile", User);
            Navigation.NavigateTo(tokenResult.InteractiveRequestUrl);
        }
    }
}
```

**Comment by guardrex** [comment]
It's a very OLD 👴 example. It goes back to 4+ years ago, and it might have degraded with updates because I see at least two PRs along the way that worked on it.

I'll open an issue to address it. However, I won't be able to reach it until perhaps Wednesday of next week. I have a super high priority work item that will probably take at least Monday and Tuesday of next week.

**Comment by guardrex** [comment]
@javiercn ... The code example came from your original content for the first publication of the docs at ...

https://gist.github.com/javiercn/85a6d4ce46a78239ccb427baad3a66da#handling-token-request-errors

... and you show the call not being to `getItem`/`setItem` but to some other JS FNs ... `getState`/`setState`, but I don't see that you conveyed to me what those FNs are.
