### ISSUE TITLE
in Blazor Server When I set the render mode for the entire app the prerender always false even I set it to true

### ISSUE THREAD

**Issue by sherif-hfm** [dotnet/aspnetcore#53462]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I set the render mode for the entire app 
`<Routes @rendermode="@(new InteractiveServerRenderMode(prerender: true))" />`
the prerender works as false value even if I set it inside the component 
`@rendermode @(new InteractiveServerRenderMode(prerender: true))  `
OnInitializedAsync and OnInitialized is executed one time not twice  and  PersistentComponentState not working 

### .NET Version

8

**Comment by guardrex** [comment]
@sherif-hfm ... We added a section to the *Prerendering* article to address this. See the *Interactive routing and prerendering* section at ...

https://learn.microsoft.com/aspnet/core/blazor/components/prerender#interactive-routing-and-prerendering

**Comment by sherif-hfm** [comment]
> @sherif-hfm ... We added a section to the _Prerendering_ article to address this. See the _Interactive routing and prerendering_ section at ...
> 
> https://learn.microsoft.com/aspnet/core/blazor/components/prerender#interactive-routing-and-prerendering
I tried 
`<a href="mypath" data-enhance-nav="false">`
but it dose not help

**Comment by sherif-hfm** [comment]
repro project
https://github.com/sherif-hfm/BlazorAppTest2

**Comment by javiercn** [comment]
@sherif-hfm thanks for contacting us.

https://github.com/sherif-hfm/BlazorAppTest2/blob/master/Components/App.razor#L19 <- You don't have to use that in Blazor Web apps. `<persist-component-state>` is a tag helper and doesn't do anything in a blazor web app.

As per your other original comment, it's not clear what you are suggesting is not working.

Are you talking about `prerender: false` not working and unconditionally prerendering the component? or are you talking about `prerender: true` not working?

**Comment by sherif-hfm** [comment]
Hi
Simply When I set rendermode globally by using : 
`<Routes @rendermode="@(new InteractiveServerRenderMode(prerender: false))" />`
I can not change prerender mode in specific page using :
`@rendermode @(new InteractiveServerRenderMode(prerender: true))`
also if I set enhance navigation  using 
`<NavLink class="nav-link" href="test" data-enhance-nav="false">`
OnInitializedAsync and OnInitialized still executed one time not twice as expected 
Thanks

**Comment by javiercn** [comment]
@sherif-hfm thanks for the additional details.

That's expected and by design. The root component in the hierarchy is not prerendering, so at that point, no other component is being rendered. In this case Routes is the route component, which doesn't get prerendered, which means, any child component doesn't get prerendered either.

**Comment by traiannemes** [comment]
Actually the example from the repo provided by @sherif-hfm has prerender set to true:
 <Routes @rendermode="@(new InteractiveServerRenderMode(prerender: **true**))" />
Question: if that's the only place where we specify a rendering mode and it's set to true is the expectation for child components to prerender? Right now, they don't, even if we explicitly add a render mode at the component level and set it to true. But if we remove the rendermode from Routes then it will start working.
To simply reproduce it, create a new blazor web app from template, include sample pages, pick either one of the three interactive modes (which all by default set prerendering to true), chose interactive location as **global**, set a breakpoint to weather page on OnInitializedAsync and notice the breakpoint only getting hit once. Add rendermode=InteractiveServer (or the other two, match with Routes value) and it still gets hit once. But at this point remove the rendermore from Routes and it will work, the breakpoint will get hit twice.
That to me it means if we set the render mode globally it will never be prerendered.

**Comment by guardrex** [comment]
@traiannemes ... Just out of my own curiosity, can you confirm that the behavior isn't due to enhanced nav ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/prerender?view=aspnetcore-8.0#interactive-routing-and-prerendering

... i.e., navigate to the `Weather` component after the app starts, ***and then*** perform a full page reload on the `Weather` component ... see if `OnInitializedAsync` fires twice that way.

**Comment by guardrex** [comment]
I've placed a note on the issue that Stephen Halter opened, and I think that they're going to confirm over there that this is the cause of the behavior for that issue. It's already covered, as you see. However, I didn't place a remark in the *Render Modes* article and cross-link that to where the coverage exists in the *Prerendering* article. I have a docs issue now to do that, and I'll take another look at how it's covered to see if I can make any improvements.
