### ISSUE TITLE
Rename JavaScript client package name

### ISSUE THREAD

**Issue by anurse** [dotnet/aspnetcore#5347]
With the release of the Azure SignalR service and it's server-less model, it's entirely possible for a SignalR application to have no ASP.NET Core in it at all. As a result, the name aspnet in the package seems odd. Let's rename from `@aspnet/signalr` to something else. We can't use `signalr` though because it's already in-use by ASP.NET SignalR.

Ideas:

* `@microsoft/signalr`?

**Comment by BrennanConroy** [comment]
We did this at some point
