### ISSUE TITLE
Optimizations to resolve high CPU load in SignalR Core

### ISSUE THREAD

**Issue by alex-jitbit** [dotnet/aspnetcore#53475]
## Summary

I profiled my high load SignalR app that serves thousands of concurrent users using PerfView, And found that 10-15% CPU load is wasted in this method: `HubGroupList.RemoveDisconnectedConnection` which basically performs a (not the most efficient) search within "a ConcurrentDictionary of ConcurrentDictionaries".

## Motivation and goals

It's mainly about CPU load of a busy websocket app.

I suggest some optimization in that hot path to eliminate double dictionary lookups for example. I have already started working on a PR and filing an issue b/c it seems like I shouldn't start without an issue. Please review the issue and allow me to start working on a PR.

**Comment by BrennanConroy** [comment]
Is this a dupe of https://github.com/dotnet/aspnetcore/issues/48249?

**Comment by alex-jitbit** [comment]
@BrennanConroy YES! Exactly. Sorry I must've missed that one when searching for exsiting issues. Closing.
