### ISSUE TITLE
SignalR OnDisconnect not called when client re-connects

### ISSUE THREAD

**Issue by ZisisTsatsas** [dotnet/aspnetcore#53488]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When a client drops internet connection and the client app tries to re-connect the OnDisconnect method is not called in the Hub before re-connection occurs. Is this intended behaviour?

**Comment by BrennanConroy** [comment]
> Is this intended behaviour?

Yes.

The "reconnect" is a completely new connection with no relationship to the old connection. The old connection will be cleaned up after a timeout, it won't be a graceful close because the client lost internet connection and wasn't able to notify the server that it was closing the connection.

**Comment by ZisisTsatsas** [comment]
How does the Azure SignalR Service handle disconnections? I am basically trying to keep a list of users connected to get a user count in my application. With Azure SignalR Service and the rest of my setup i can't keep a dictionary of them in memory so i keep them in a Redis cache set, I add them to the set when they connect to the hub and remove them on disconnect, but not all of the users in that cache set are removed. Should i not be expecting OnDisconnectedAsync to always be called?

**Comment by BrennanConroy** [comment]
`OnDisconnectedAsync` will always be called. Are you waiting long enough for the timeout to occur? Have you attached a debugger to the application? (that disables some timeouts while you're attached)

**Comment by ZisisTsatsas** [comment]
I've connected a debugger on my dev environment, not on prod but the issue is there on prod too. I've not really changed the default timeout configurations. Is there a way to do that?

**Comment by BrennanConroy** [comment]
https://learn.microsoft.com/aspnet/core/signalr/configuration?view=aspnetcore-8.0&tabs=dotnet#configure-server-options

**Comment by ZisisTsatsas** [comment]
what about in an autoscale setup? where theres new web apps starting and stopping all the time, could that stop the OnDisconnected from being called?

**Comment by BrennanConroy** [comment]
I would hope the app would be gracefully shutdown when scaling down. Do you have app logs for the stopped apps?
