### ISSUE TITLE
BlazorWebAssemblyStandaloneWithIdentity and Offline support

### ISSUE THREAD

**Issue by 11110011** [dotnet/aspnetcore#53484]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Running the sample BlazorWebAssemblyStandaloneWithIdentity (Core 8.0) works fine. But once the wasm is installed and then started without an internet connection (alternatively disconnect from internet after the wasm start and do a browser refresh afterwards) it is not possible to work with it anymore.
In order to have the wasm with full offline support, I think something like the PersistentAuthenticationStateProvider and a LocalStore is required (as in the example https://github.com/SteveSandersonMS/CarChecker, but unfortunately it is .Net Core 3.2).

To Reproduce

Start sample BlazorWebAssemblyStandaloneWithIdentity
Login with an account
Close internet connection (in Browser Developer Tools switch to offline)
hit F5 for a refresh
Expected behavior
Wasm in offline mode continues to function using the AuthenticationState it previously got from login in online mode.

### Describe the solution you'd like

Could you please extend the BlazorWebAssemblyStandaloneWithIdentity sample to be functional when internet connection is broken (maybe combining CookieAuthenticationStateProvider with PersistentAuthenticationStateProvider from the above mentioned example) or describe what steps need to be done to get this work?

**Comment by 11110011** [comment]
@JeremyLikness, could you please take a look on that (guardrex told me you are the PU team member who built the sample)? 

cc: @guardrex https://github.com/dotnet/blazor-samples/issues/167

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **blazor** tag.
