### ISSUE TITLE
Blazar WebAssembly with ClientCertificateMode.RequireCertificate

### ISSUE THREAD

**Issue by martinRocks** [dotnet/aspnetcore#53491]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Using the template to create a 'Blazor WebAssembly Standalone App' (as shown below) with the checkbox for 'ASP.NET Core Hosted' in .NET 7.0 works but throws errors in the visual studio output window.  However, when I add the code below to require a certificate, it throws 100s of errors.  I upgraded the dot.net to version 8 and it does the same thing but worse. When running the app, VS will open the cmd window and the browser window.  The browser window does not navigate to the application, I'm assuming because it is waiting for a certificate choice. However, there is no browser prompt to choose a certificate. If I open a new tab and put the URL ( https://localhost:7084/ ) in, the browser will ask for the certificate and will continue to the application.  However, the VS debugger will eventually crash.

I have attached the source code for a project that demonstrates this issue using dot.net 7 and dot.net 8.  I'm also using VS version 17.8.5 to do everything.

```
builder.Services.Configure<KestrelServerOptions>(options =>
{
    options.ConfigureHttpsDefaults(x => x.ClientCertificateMode = ClientCertificateMode.RequireCertificate);
});
```

The code using .Net 7
[BlazorCertDemo7.zip](https://github.com/dotnet/aspnetcore/files/13992873/BlazorCertDemo7.zip)

The code using .Net 8
[BlazorCertDemo8.zip](https://github.com/dotnet/aspnetcore/files/13992874/BlazorCertDemo8.zip)

The options to set up the project.
![template](https://github.com/dotnet/aspnetcore/assets/10621557/21d0934c-4c8e-4ffb-9442-f3102802e265)

The errors thrown in the VS output window.
![errors with cert required](https://github.com/dotnet/aspnetcore/assets/10621557/84772f1f-6116-4a6f-9029-f296ddce5eac)

The error shown when the debugger crashes.
![VS error](https://github.com/dotnet/aspnetcore/assets/10621557/3d5cfff3-ed05-4e7b-ac2c-d137c95f2609)

### Expected Behavior

There are no errors in the output window and the initial browser prompts for the certificate.

### Steps To Reproduce

see attached zips.

### Exceptions (if any)

see picture above of the output window.

### .NET Version

8.0.101

**Comment by javiercn** [comment]
@martinRocks thanks for contacting us.

This seems to be a Visual Studio related issue, for us to provide a better and faster response, please file the issue through the [report a problem dialog](https://learn.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022) in Visual Studio.
