### ISSUE TITLE
Stacking [Parameter] and [SupplyParameterFromQuery]

### ISSUE THREAD

**Issue by jcantrel** [dotnet/aspnetcore#53496]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a Blazor component that I use both as a page and a dialog box depending on what I am using it for. In .net 7 and older I was able to use [SupplyParameterFromQuery] for the page view and [Parameter] for the dialog view. 

`[Parameter][SupplyParameterFromQuery] public int clientID { get; set; }`

With .net 8 this no longer works. If I have SupplyParameterFromQuery it will not load the passed parameters in the dialog view.

### Expected Behavior

When I supply a parameter via from query, it should load that, otherwise it should load from the supplied parameter.

### .NET Version

.net 8

**Comment by javiercn** [comment]
@jcantrel thanks for contacting us.

This is likely a breaking change we took in 8.0 as `[SupplyParameterFrom*]` were converted to cascading values. @MackinnonBuck can confirm. What's likely happening is that the cascading value provider is providing "null" for the parameter values that have `[SupplyParameterFromQuery]` and that's taking precedence over the parameter definition.

What you can do in these cases is provide two separate properties for each of the sources and choose which one to use at render time. (For example, `Prop`, `QueryProp` and then use something like `_propValue = Prop ?? QueryProp`.

As far as I understand what you are saying is that in the past you combined both of them in a single property and in that case, you were able to pass in the values directly to the component as opposed to receiving them from the query string, and now you no longer can.

**Comment by jcantrel** [comment]
Yes, what you stated is correct. Creating new properties is certainly an option I had considered, but as it is inelegant I had wanted to avoid it. It adds complexity that was not previously required, and thus more chances for error.
