### ISSUE TITLE
Results.Json(null) stopped producing a response body in .NET 8 (and 7)

### ISSUE THREAD

**Issue by WGroenestein** [dotnet/aspnetcore#53509]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In .NET 8 (and 7) when a null value is given to Results.Json, it no longer outputs "null" in the response body, instead the response body is empty

### Expected Behavior

```json
null
```
is put in the response body

### Steps To Reproduce

https://github.com/WGroenestein/ResultJsonRepro

### .NET Version

8.0.100

### Anything else?

Since .NET 8 (the new LTS) was released Nov 2023 and .NET 6 (current targeted LTS) is EOL Nov 2024 we are trying to switch our projects over to .NET 8 (LTS => LTS upgrade). However this LTS upgrade causes our API contracts to break.

We didn't find anything related to this breaking change in the msdn docs (https://learn.microsoft.com/en-us/dotnet/core/compatibility/7.0 and https://learn.microsoft.com/en-us/dotnet/core/compatibility/8.0)

**Comment by teociaps** [comment]
The issue you're encountering seems to be relative to a change in JSON result handling between .NET versions 6 and 7/8, particularly in the context of minimal APIs. In .NET 6, the `JsonResult` class from MVC was used, whereas in newer versions 7 and 8, a new typed result class called `JsonHttpResult<TValue>` is utilized behind the scenes.

The key distinction lies in how null values are managed. With `JsonHttpResult<TValue>`, if the Value passed to it is null (your case), the `JsonHttpResult<TValue>.ExecuteResultAsync` method returns before writing the JSON result to the response body:

![image](https://github.com/dotnet/aspnetcore/assets/60600374/cfe25e77-0064-4f57-ac8d-5d92e355f4a4)

and then, if Value is not null:

![image](https://github.com/dotnet/aspnetcore/assets/60600374/b8053808-7014-4ff1-a122-063e0a82621d)

`JsonResult`, on the other hand, behaves differently. It sets a default content type (_application/json_) and serializes the value to the response body regardless of whether it's null or not.

This is why `Results.Json(null)` behaves as you expected only in MVC/API Controller in .NET 7/8, while in minimal API it doesn't. In contrast, in .NET 6, it works consistently across both scenarios.

**Comment by captainsafia** [comment]
@teociaps Thanks for taking the time to post this explainer.

It doesn't look like we documented this change in our announcements repo at https://github.com/aspnet/Announcements. I'll go ahead and file an issue to document this.

**Comment by captainsafia** [comment]
Still on my radar to add the breaking change notice here.
