### ISSUE TITLE
#dotnet #blazor #filesUpload => crash when OnChange occured

### ISSUE THREAD

**Issue by Mafyou** [dotnet/aspnetcore#53507]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi,

if you paste this code:
```
@page "/"

<PageTitle>Index</PageTitle>

<h1>Hello, world!</h1>

Welcome to your new app.

<SurveyPrompt Title="How is Blazor working for you?" />
<form @onsubmit="OnSubmit">
    <InputFile accept="image/png, image/gif, image/jpeg" style="background-color:var(--accent-blue);" class="btn btn-primary" id="ifMock" OnChange="@OnHandleMultipleFiles" multiple />
    <br />
    <button class="btn btn-primary" type="submit">Envoyer</button>
</form>

@code {
    private IReadOnlyList<IBrowserFile> _selectedFiles;
    private void OnHandleMultipleFiles(InputFileChangeEventArgs e)
    {
        _selectedFiles = e.GetMultipleFiles();
    }
    private void OnSubmit()
    {
    }
}
```
In a #Blazor WebApp under #dotnet8, you will see that app crash when trying to upload something.

### Expected Behavior

I tried with InteractiveMode Auto/Client/Server, same result, the app crash always
OR
It doesn't fire OnChange event and selected files are null when submitting.

### Steps To Reproduce

Create a Blazor WebApp on #dotnet8,
Paste the code that I posted.
See that it makes crash the app when you tried to upload an item!

### .NET Version

8

### Anything else?

It only happens with Brave browser.

**Comment by javiercn** [comment]
@Mafyou thanks for contacting us.

Is your page interactive or are you trying to do a traditional form post.

**Comment by Mafyou** [comment]
> @Mafyou thanks for contacting us.
> 
> Is your page interactive or are you trying to do a traditional form post.

Hi !
Sorry to be late.
Interactive and standar are failing when using Brave browser.
Other browsers are ok.

**Comment by javiercn** [comment]
@Mafyou thanks for contacting us.

This seems to be a brave specific issue. Some things to check are:
* Network tab (what is the shape of the requests being sent back and forth).
* Server logs (are there any errors on the console, or the dev tools console?).
