### ISSUE TITLE
Microsoft.AspNetCore.Components.QuickGrid CSS not loading

### ISSUE THREAD

**Issue by zandiarash** [dotnet/aspnetcore#53504]
I'm using  a **Blazor component** inside my Razor Pages ASP web project and I'm using **QuickGrid**.
But **CSS** is messy, maybe I've done something wrong or some thing.
Does **Bootstrap** affects **QuickGrid** ?

![image](https://github.com/dotnet/aspnetcore/assets/10775073/9a4bbbfb-b58a-4c92-9269-241babbfc983)

Actually I've also tested  **QuickGrid** in a fresh Blazor app with Dotnet 8, It had same problem.
Please see this links, some developers have same issue here :

[https://stackoverflow.com/questions/77571655/blazor-quickgrid-css-not-loading](https://stackoverflow.com/questions/77571655/blazor-quickgrid-css-not-loading)
[https://stackoverflow.com/questions/77523248/blazor-8-server-side-quickgrid-default-css-not-loading](https://stackoverflow.com/questions/77523248/blazor-8-server-side-quickgrid-default-css-not-loading)

**Comment by zandiarash** [comment]
I've created new clean samples of Blazor Server App and also a RazorPages WebApp which contains Blazor component with Dotnet 8
Both of them show **QuickGrid** as well and loads **Microsoft.AspNetCore.Components.QuickGrid.bundle.scp.css**
![image](https://github.com/dotnet/aspnetcore/assets/10775073/935f5eec-eec9-4b37-8a6e-1c75061b8665)

But in some existing projects when I add QuickGrid It seems **Microsoft.AspNetCore.Components.QuickGrid.bundle.scp.css** will not added to the project
Thus I've added that manually to the layout of the project and now It works.
`<link rel="stylesheet" href="_content/Microsoft.AspNetCore.Components.QuickGrid/Microsoft.AspNetCore.Components.QuickGrid.bundle.scp.css" asp-append-version="true" />`
But I know It's not a good practice and how I can do it the best way ?

**Comment by javiercn** [comment]
@zandiarash thanks for contacting us.

You shouldn't need to reference the file manually. There are a couple of things you can try:
* Perform a hard refresh (CTRL+F5) to ensure that the browser is not caching any resource locally.
* Open the browser in InPrivate mode to see if the issue still reproduces.

If you are still having issues, clean the bin and obj folders and perform a clean build to see if the issue goes away.

**Comment by javiercn** [comment]
@zandiarash thanks for the additional details.

I'm glad that you were able to resolve the issue. That file contains the bundle for all the styles coming from referenced projects and packages, hence why by deleting them it wasn't showing.

**Comment by pmarangoni** [comment]
I'm having this issue now. How do I "clean" the bin and obj folders? Do mean delete their contents?

**Comment by pmarangoni** [comment]
I figured out the issue. I had to also copy over the wwwroot/_content folder which contains all the css and js files for Blazor.
