### ISSUE TITLE
Error : ERR_EMPTY_RESPONSE On Blazor Project

### ISSUE THREAD

**Issue by MahdiElahi** [dotnet/aspnetcore#53513]
Hi,
i publish my blazor web app .net 8 on **iis** but some times show this error and after a few second go to the site?
what's problem ? how to fix it in iis ?
![Untitled](https://github.com/dotnet/aspnetcore/assets/32883870/e70f499a-717c-4514-bb34-a489834cef34)

**Comment by javiercn** [comment]
@MahdiElahi thanks for contacting us.

Can you reproduce the issue with a regular web project? (No blazor involved).

Can you turn on all the logs in ASP.NET Core as well as IIS to the maximum verbosity and see what the logs indicate?
