### ISSUE TITLE
SignalR -  Blazor Server - .Net7.0 Connection Disconnected 

### ISSUE THREAD

**Issue by plagalPatent** [dotnet/aspnetcore#53517]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When trying to add SignalR to any Blazor Server project (including like for like microsoft guides).
This is returned in Dev Tools. 
"Error: Connection disconnected with error 'Error: Server returned an error on close: Connection closed with an error.'." and then "Uncaught (in promise) Error: Server returned an error on close: Connection closed with an error."
App fails to connect. No other errors, network shows websocket is open.

### Expected Behavior

Blazor Server App allows SignalR.

### Steps To Reproduce

Start a Blazor Server template and try signalR.

### .NET Version

7.0

### Anything else?

![SignalRError](https://github.com/dotnet/aspnetcore/assets/90073159/f20bc2e8-14a3-49b2-af28-422070158912)

**Comment by BrennanConroy** [comment]
Error indicates an issue on the server, have you looked at the server logs?
https://learn.microsoft.com/aspnet/core/signalr/diagnostics?view=aspnetcore-8.0#server-side-logging
