### ISSUE TITLE
Route values are missing in SignalR hub HttpContext

### ISSUE THREAD

**Issue by DaRosenberg** [dotnet/aspnetcore#53566]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We need to parameterize the route for a hub, and make the route values accessible to the hub.

I expect to be able to do this:

```cs
app.MapHub<AccountEventHub>("/events/{accountId}");
```

And then from inside the hub do this:

```cs
var httpContext = Context.GetHttpContext();
var accountId = httpContext!.GetRouteValue("accountId") as string;
```

But the `GetRouteValue("accountId)` always returns `null` and the `Request.RouteValues` collection is always empty.

I know that this is technically possible to achieve using query string parameters instead, but that's a hacky workaround IMO and is not a good fit with our overall API design. And since:

1. The `MapHub<THub>(string pattern)` argument is actually named `pattern`, and
2. The `HttpContext.GetRouteValue()` API is actually exposed to the hub

It seems like a bug that it doesn't work as expected.

### .NET Version

8.0

### Anything else?

ASP.NET Core 8.0

**Comment by thismaker** [comment]
@DaRosenberg have you been able to find a solution? I would like to do something similar and want to know it's possible before I commit.

**Comment by DaRosenberg** [comment]
@thismaker IIRC some further research revealed that this works for regular SignalR but not when using Azure SignalR Service (which I am). Some more information is available in https://github.com/dotnet/aspnetcore/issues/53569 discussion. I intend to submit a feature request in https://github.com/azure/azure-signalr/ to have route data preserved along with query string values, but have not found the time to do so yet.

**Comment by BrennanConroy** [comment]
This can be closed then right?

**Comment by lukedukeus** [comment]
I just ran into the same issue. Below, the `GetTenant` method is called via middleware, and works for my HTTP API, but not for SignalR routes:

```
public static class RoutingHelpers
{
    [StringSyntax("Route")]
    public const string TenantPattern = "{tenant:required}";

    [StringSyntax("Route")]
    public const string VersionPattern = "{version:apiVersion}";

    [StringSyntax("Route")]
    public const string HTTPRoutePattern = $"/api/{TenantPattern}/v{VersionPattern}/[controller]";

    [StringSyntax("Route")]
    public const string SignalRRoutePattern = $"/hub/{TenantPattern}/v{VersionPattern}";

    public static string CreateSignalRPath(string tenant = "common", int version = 1)
    {
        return SignalRRoutePattern.Replace(TenantPattern, tenant).Replace(VersionPattern, version.ToString());
    }

    public static string GetTenant(HttpContext context)
    {
        object? tenantObject = context.GetRouteValue("tenant");

        if (tenantObject is null)
        {
            // if the tenant was not found in the route, make sure that the route matches at all.
            var endpoint = context.GetEndpoint();
            if (endpoint is null)
            {
                throw new KeyNotFoundException("Route not found. (Check that the tenant is correct?)");
            }

            throw new ArgumentNullException("Tenant not found");
        }

        if (tenantObject is not string tenant)
        {
            throw new FormatException($"Tenant was in unexpected format. Found: '{tenantObject}'.");
        }

        return tenant;
    }
}
```

I am using .net core 9.0, and normal self-hosted signalr. @BrennanConroy Can you provide a minimal example with this working?

**Comment by davidfowl** [comment]
Can yju provide a full sample that we can run ?

**Comment by lukedukeus** [comment]
Sure, see the attached repository. 

Making a request to `https://localhost:7179/api/common/v1/WeatherForecast` fetches weather forecast data, and the `TenantRewriteMiddleware` is able to parse the string "common" from the request path.

Visiting `https://localhost:7179/` causes `chat.js` to fetch ` https://localhost:7179/hub/common/v1`, as that is where the hub is mapped to, but the middleware is unable to parse the tenant from the request path.

Demo code: https://github.com/lukedukeus/SignalRRoutingDemo

**Comment by BrennanConroy** [comment]
You are replaced the route values so they'll no longer be in the route values dictionary...
```return SignalRRoutePattern.Replace(TenantPattern, tenant).Replace(VersionPattern, version.ToString());```

**Comment by lukedukeus** [comment]
🤦I see, before it was not matching because the `[controller]` part was still there, I was assuming that the `[controller]` would match the hub name, then I tried explicitly setting the tenant and version, which wouldn't work because it didn't know the template. 

Is there a route pattern like `[hub]` or some place where it is documented what route values are accepted?

Thanks for the help!

**Comment by davidfowl** [comment]
> Is there a route pattern like [hub] or some place where it is documented what route values are accepted?

Nope.
