### ISSUE TITLE
Status code is not updated in middleware

### ISSUE THREAD

**Issue by ssougnez** [dotnet/aspnetcore#53561]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have an application powered by Angular on the front end side and I have been using the following middleware for years now:

```
app.Use(async (context, next) =>
{
    await next();

    if (context.Response.StatusCode == 404 && !Path.HasExtension(context.Request.Path.Value))
    {
        context.Request.Path = "/index.html";

        await next();
    }
});
```

Basically, if it does not find the URL, it redirects the user to the index.html and later on, the middlewares `UseDefaultFiles` and `UseStaticFiles` found the index.html and everything was working fine.

However, since I upgraded to .NET 8, I noticed that even though the application was still working as expected, the browser console started to display a 404 error on the page (e.g. /home).

I did a bit of debugging and noticed that after the last `await next()` in the middleware above, the content of the response was indeed based on the index.html content but `context.Response.StatusCode` was still set on 404. 

It looks like that in .NET < 8, the status code was reset to 200 if the file could be found but it's not the case anymore. I fixed my middleware like this:

```
app.Use(async (context, next) =>
{
    await next();

    if (context.Response.StatusCode == 404 && !Path.HasExtension(context.Request.Path.Value))
    {
        context.Request.Path = "/index.html";
        context.Response.StatusCode = 200;

        await next();
    }
});
```

It works as expected but I can't help feeling that it smells like a regression, which is why I'm reporting it :-)

### Expected Behavior

According to me, one of the middleware (`UseDefaultFiles` or `UseStaticFile`) should reset the status code of the response of it indeed found the file.

### .NET Version

8.0.101

**Comment by Tratcher** [comment]
See https://github.com/dotnet/aspnetcore/pull/46578. You should re-set the status code before re-executing the request. E.g. `context.Response.Clear()`.

**Comment by ssougnez** [comment]
By design then :-)

Ok thanks
