### ISSUE TITLE
Change nullability annotation of HostString.Value to explictly allow nulls

### ISSUE THREAD

**Issue by sorensenmatias** [dotnet/aspnetcore#53567]
## Background and Motivation

It seems that HostString is intentionally implemented to handle null being passed to the constructor `HostString(string value)`, but currently the nullability annotation of this constructor does not allow null. I propose to explicitly allow a null value.

## Proposed API

```diff
namespace Microsoft.AspNetCore.Http;

public static class HostString
{
-    public HostString(string value)
+    public HostString(string? value)

-    public string Value
+    public string? Value
}
```

## Usage Examples

```csharp
var hostString = new HostString(null);
Console.WriteLine(hostString.Host); //outputs "" (empty string)
```

## Alternative Designs

Leave it as is

## Risks

I don't see any.

**Comment by captainsafia** [comment]
@sorensenmatias We don't typically take nullability changes through API review. In either case, I believe this change is a good one to make!

**Comment by sorensenmatias** [comment]
Alright - thanks! Is there something I can do to help with this issue?

**Comment by captainsafia** [comment]
@sorensenmatias Nope! We'll go ahead and review the PR and go from there.

**Comment by glen-84** [comment]
What is the point of allowing `null` here, simply because `ToString` currently handles `null`?

Is there any ASP.NET Core code that requires the use of `null`?

What are the use cases for this change? Why create a `HostString` object if you don't even have a `host`?
