### ISSUE TITLE
Items dictionary is always empty in SignalR hub HttpContext

### ISSUE THREAD

**Issue by DaRosenberg** [dotnet/aspnetcore#53569]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I expect to be able to integrate the mapping of a SignalR hub with endpoint route groups and endpoint filters, just like any other `MapWhatever()` method chained off `IEndpointRouteBuilder`.

For example:

```cs
var app = builder.Build();
app
    .MapGroup("/accounts/{accountId}")
    .RequireAuthorization()
    .AddEndpointFilter(async (context, next) =>
    {
        var httpContext = context.HttpContext;
        httpContext.Items["Account"] = someAccount;
        return await next(context);
    })
    .MapHub<AccountHub>("/hub");
```

And then in my hub `AccountHub.OnConnectedAsync()` I should be able to do this:

```cs
var httpContext = Context.GetHttpContext();
var account = httpContext.Items["Account"]; // NOPE!
```

And then connect a client like so:

```js
const connection = new HubConnectionBuilder()
    .withUrl("/accounts/1234/hub", {
        accessTokenFactory: async () => await authStore.acquireAccessToken()
    })
    .build();
```

Mostly this seems to work as expected, but for some reason, when the request reaches the hub, the `HttpContext.Items` dictionary is always empty.

All other parts of the request pipeline work fine. The route matching works as expected, the endpoint filter gets invoked as expected, and any other endpoints mapped upstream from this filter are able to retrieve the item from `HttpContext.Items`, but not the hub.

### .NET Version

8.0

### Anything else?

ASP.NET Core 8.0

**Comment by davidfowl** [comment]
The hub execution pipeline and the request pipeline are decoupled. This is because multiple http request might make up a signalr connection. The HttpContext is a clone of the original with a subset of the properties. The Items collection is a reasonable thing to copy over but do we were conservative about copying it because it could container things that are tied to the request lifetime (there's no way to know).

**Comment by DaRosenberg** [comment]
@davidfowl I see, thanks for clarifying that. I guess that also explains why the route values aren't there... OOC, when might a single `OnConnectedAsync()` invocation be comprised of multiple requests?

Can you think on any workaround we might employ to get this scenario working?

(OT BTW, just listened to you on .NET Rocks talking about Aspire earlier this morning. :) Awesome conversation!)

**Comment by BrennanConroy** [comment]
This works for me, if it's not working for you we'll need more info about what you're doing, and preferably a minimal repro app.

![image](https://github.com/dotnet/aspnetcore/assets/7574801/63ef4c13-9163-4626-86f1-0816ef0b1bff)
```
app.MapGroup("/a").AddEndpointFilter(async (context, next) =>
{
    var httpContext = context.HttpContext;
    httpContext.Items["Account"] = "t";
    return await next(context);
}).MapHub<ChatHub>("/chat");
```

**Comment by DaRosenberg** [comment]
@BrennanConroy Bizarre, that's the exact scenario I tested! Give me a couple of days and I will test again and either post a minimal repro or close this issue if I was mistaken somehow.

**Comment by DaRosenberg** [comment]
@BrennanConroy It took a lot of bisecting to narrow this down but I finally found the culprit.

`HttpContext.Items` is set as expected when using just plain SignalR, but as soon as I add Azure SignalR to the mix, the `HttpContext.Items` dictionary is empty in the `OnConnectedAsync()` invocation.

```cs
var signalREndpointUrl = builder.Configuration["SignalREndpointUrl"];
builder.Services
    .AddSignalR()
    .AddAzureSignalR(options =>
    {
        options.Endpoints = [new ServiceEndpoint(new Uri(signalREndpointUrl!), AzureCredential.Default)];
    });
```

I'm guessing this is because `OnConnectedAsync()` in this scenario runs in response to something coming back from Azure SignalR (to notify that the user is connected to there) and that the `HttpContext` instance I'm looking at in this case is a complete fake?

**Comment by BrennanConroy** [comment]
Yes the `HttpContext` from ASRS is fake, but you can also see that the code in `AddEndpointFilter` is never run. This is because the SignalR connections go to ASRS instead of your app.

**Comment by BrennanConroy** [comment]
> Would it be technically feasible for the app server's local SignalR to store the `HttpContext` data tied to the connection ID

There isn't a connection ID until ASRS tells us about a new connection. You could in theory write a middleware that stores info when the initial Http request comes in, store it somewhere along with association to the auth token ASRS generates, and then refresh it in `Hub.OnConnectedAsync`, but it'd be very ugly to write.

> Or alternatively, for the app server's local SignalR to hand off some `HttpContext` data to ASRS after the handshake , and for ASRS to hand this data back to the local SignalR along with the client connect notification, so that it can be made available to the hub?
> 
> Something like this must be going on already, since query string parameters do somehow survive all these hops. I'm guessing the client simply provides the query string data directly to ASRS and it's being passed along to the app server's local SignalR in the client connect notification?

Right, ASRS preserves auth and query string. Those are the only pieces of information from the original `HttpContext`.

**Comment by BrennanConroy** [comment]
https://github.com/azure/azure-signalr/

**Comment by BrennanConroy** [comment]
Close this too?

**Comment by DaRosenberg** [comment]
Yep.
