### ISSUE TITLE
Blazor web app @rendermode="InteractiveServer" Losing Claims

### ISSUE THREAD

**Issue by douglassimaodev** [dotnet/aspnetcore#53588]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am using a blazor webapp @rendermode="InteractiveServer"  global

when I do it, the page code is running twice where the first time it works fine but second time logged user loses the claims (custom ones) saved in AspNetUserClaims

### Expected Behavior

I should keep the claims

### .NET Version

8.0.101

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide [a minimalistic repro project](https://github.com/dotnet/aspnetcore/blob/main/docs/repro.md) that illustrates the problem.
