### ISSUE TITLE
Options to prevent delegate event handlers automatically trigger a UI render

### ISSUE THREAD

**Issue by Xyncgas** [dotnet/aspnetcore#53583]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

It might be great to get automatic UI update, yet the performance and battery invites me to opt in manually calling statehaschange in my EventHandler, therefore I ask the blazor team to respect me and my choices and implement the option to allow me to update the UI myself instead of automatically

There's one discussion found in 2021 : https://github.com/dotnet/aspnetcore/issues/18919

### Describe the solution you'd like

Provide options in blazor to prevent delegate event handlers automatically trigger a UI render

**Comment by Xyncgas** [comment]
If I understood the framework correctly, I can let ShouldRender return false, I can now handle events without automatic UI updates I can use statehaschanged instead to manually trigger a rendering of the UI and it would still work

**Comment by MariovanZeist** [comment]
Hi @Xyncgas 
You could also implement ``IHandleEvent`` in your component to completely control when you want StateHasChanged to be called.
[See here](https://learn.microsoft.com/en-us/aspnet/core/blazor/performance?view=aspnetcore-8.0#avoid-rerendering-after-handling-events-without-state-changes)

**Comment by javiercn** [comment]
@Xyncgas thanks for contacting us.

As @MariovanZeist there is already enough extensibility in the framework for you to do this yourself. We don't have plans to add any new mechanism.
* You can implement `IHandleEvent` on your component to decide when to trigger re-renders as part of event handling.
* You can construct a delegate whose `target` is not an `IComponent` instance to avoid your component re-rendering from any `EventCallback` you pass in to an HtmlElement/Child component.

We don't plan to offer any mechanism where you can externally alter whether a component should or shouldn't render as that would likely result in existing components breaking (each component owns when/how it needs to render).
