### ISSUE TITLE
Set the current culture at the application level in an ASP.NET Core 8.0 application

### ISSUE THREAD

**Issue by lamereactor** [dotnet/aspnetcore#53590]
[In an ASP.NET application, I can set the current culture globally at the application level in the web.config file](https://learn.microsoft.com/en-us/troubleshoot/developer/webapps/aspnet/development/set-current-culture#application-level):

```xml
<configuration>
    <system.web>
        <globalization
            culture="ja-JP"
            uiCulture="zh-HK"
        />
    </system.web>
</configuration>
```

How to do it in ASP.NET Core 8.0?
It appears that it is possible to do it in the `Program.cs` file, by specifying the instructions below at the highest level:

```csharp
CultureInfo.DefaultThreadCurrentCulture = new CultureInfo("ja-JP");
CultureInfo.DefaultThreadCurrentUICulture = new CultureInfo("zh-HK");
```

Please note that I want the culture to be set globally not only in requests but also everywhere else (Program.cs, hosted services, etc.).

Thanks for your help!

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Please follow the guidance provided in our docs: https://learn.microsoft.com/aspnet/core/fundamentals/localization/select-language-culture?view=aspnetcore-8.0#configure-localization-middleware

**Comment by lamereactor** [comment]
Thank you for your answer @mkArtakMSFT.

The documentation you provided allows me to set the current culture **only within the request pipeline**.
On my end, I would have liked to be able to configure the culture **both within and outside the request pipeline** (at the application level) in one go, similar to system.web/globalization in ASP.NET (that would have been useful for me because I have to migrate an ASP.NET application to ASP.NET Core within a very tight timeframe, so I don't have time for a complete refactor).
I guess there is nothing like that in ASP.NET Core, and given the difference in architecture between the two, I can understand.

I will stick with my initial solution by setting `CultureInfo.DefaultThreadCurrentCulture` and `CultureInfo.DefaultThreadCurrentUICulture`, but your link will undoubtedly be useful for me later on.
