### ISSUE TITLE
HttpClient behaves differently between Blazor Server and Blazor WebAssembly Projects with regard to Cookies

### ISSUE THREAD

**Issue by ahazelwood** [dotnet/aspnetcore#53609]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I have run into a situation where we use a BFF (Backend for Frontend) solution with YARP that proxies api requests to another asp.net core server.  With the same code written in Blazor, cookies from the client are not included when a request is made on the Server (running in Auto mode).  However cookies are included when running in WebAssembly mode because HttpClient is a wrapper around fetch.  This makes issues like including authentication cookies that are marked as Server-only impossible to send currently.

### Describe the solution you'd like

I would like HttpClient to be smart enough to have a boolean property added that if set, would include all Cookies sent to the server during an initial Http request to the underlying Page if it is being used in the context of a Blazor Server app, and the destination url being made on the HttpClient is of the same origin.  This would mirror the functionality that gets seen when the component then switches to WebAssembly mode.  Currently it is a large amount of work to compensate for this inconsistency.

### Additional context

Other users have run into similar issues.  For example:  [https://stackoverflow.com/questions/63831943/httpclient-doesnt-include-cookies-with-requests-in-blazor-webassembly-app](https://stackoverflow.com/questions/63831943/httpclient-doesnt-include-cookies-with-requests-in-blazor-webassembly-app)

**Comment by javiercn** [comment]
@ahazelwood thanks for contacting us.

This is expected and by design. You need to be aware of it when designing your app.

* HttpClient on Webassembly runs in the browser context (hence it will use the cookies set in the browser).
* HttpClient on Server runs in the server, not the browser, so it doesn't get access to the browser cookies.

This is one of the main reasons why its discouraged to use HttpClient to "talk to yourself" (if that's your scenario) and if the goal here is to reuse some logic, it's best to abstract that logic behind a service, route it via HttpClient on wasm, and invoke the service directly on the server.

**Comment by ahazelwood** [comment]
I understand the reasoning behind why it is currently designed this way.  However, there may be circumstances, for example our API server currently runs on asp.net Framework (and based on dependencies cannot easily be moved at this point), and our frontend is written in asp.net core.  In this case, the ability to simply reuse the logic may not be an easy fix.  On top of this, the difference in how this works across the two modes (especially when it is set as auto and will switch in subsequent loads) causes a lot of work to diagnose and come up with workarounds.

Ideally I would be able to use something like a delegating handler to add the cookies to the request by myself, but I have not been able to come up with a workable solution yet as the Request context does not expose items like the Cookies currently.

**Comment by ahazelwood** [comment]
Here is another discussion about similar issues people are having:   [https://stackoverflow.com/questions/69801603/obtaining-a-scoped-service-in-a-custom-delegating-handler-in-blazor-server](https://stackoverflow.com/questions/69801603/obtaining-a-scoped-service-in-a-custom-delegating-handler-in-blazor-server)

**Comment by rwb196884** [comment]
> This is one of the main reasons why its discouraged to use HttpClient to "talk to yourself"

Then what _are_ you supposed to do?

If I was using Angular or React then I'd be using bearer tokens to access a HTTP API.

But in Blazor this is wrong. So what do I do instead?
