### ISSUE TITLE
MVC Razor/Blazor Component Validation

### ISSUE THREAD

**Issue by nfplee** [dotnet/aspnetcore#53611]
I have the following Blazor component:

```
<PageTitle>Contact</PageTitle>

<h1>Contact</h1>

@if (!Submitted || !IsValid) {
    <EditForm FormName="ContactForm" Model="Model" Enhance>
        <ValidationSummary />
        <InputText name="Name" class="form-control" @bind-Value="Model.Name" />
        <ValidationMessage For="() => Model.Name" />
        <button class="btn">Submit</button>
    </EditForm>
} else {
    <p>Form submitted by @Model.Name!</p>
}

@code {
    [Parameter]
    public ContactModel Model { get; set; } = new();

    [Parameter]
    public bool IsValid { get; set; } = true;

    [Parameter]
    public bool Submitted { get; set; }

    public class ContactModel {
        [Required]
        public string Name { get; set; } = default!;
    }
}
```

Which is returned from the following MVC action like so:

```
[HttpGet("contact")]
public IResult Contact() {
    return new RazorComponentResult<Contact>();
}
```

I have also defined the following post method:

```
[HttpPost("contact")]
public IResult Contact(ContactModel model) {
    if (!ModelState.IsValid)
        return new RazorComponentResult<Contact>(new { Model = model, Submitted = true, IsValid = false });

    return new RazorComponentResult<Contact>(new { Model = model, Submitted = true });
}
```

This works well, however I'd like to display the `ModelState` errors within the `ValidationSummary` and `ValidationMessage` components. This is where I'm lost. I've been looking at creating an `EditContext` from my model and setting that against my form, then manually invoking the `Validate` method against it, like so:

```
<PageTitle>Contact</PageTitle>

<h1>Contact</h1>

@if (!Submitted || !IsValid) {
    <EditForm FormName="ContactForm" EditContext="editContext" Enhance>
        <ValidationSummary />
        <InputText name="Name" class="form-control" @bind-Value="Model.Name" />
        <ValidationMessage For="() => Model.Name" />
        <button class="btn">Submit</button>
    </EditForm>
} else {
    <p>Form submitted by @Model.Name!</p>
}

@code {
    private EditContext? editContext;

    [Parameter]
    public ContactModel Model { get; set; } = new();

    [Parameter]
    public bool IsValid { get; set; } = true;

    [Parameter]
    public bool Submitted { get; set; }

    protected override void OnInitialized() {
        editContext = new EditContext(Model);

        if (!IsValid)
            editContext.Validate();
    }

    public class ContactModel {
        [Required]
        public string Name { get; set; } = default!;
    }
}
```

But this didn't do anything. I know this seems slightly funky, but it's an approach I'm exploring whilst converting an MVC app to use Blazor static SSR with enhanced navigation.

I'd appreciate it if someone could point me in the right direction.

**Comment by javiercn** [comment]
@nfplee Thanks for contacting us.

We don't have integration between modelstate and EditForm, you'll need to implement it yourself. You should be able to do it following the approach we use to pass in messages for our own binding system.

See as an example https://github.com/dotnet/aspnetcore/blob/main/src/Components/Web/src/Forms/Mapping/FormMappingValidator.cs

**Comment by nfplee** [comment]
@javiercn thanks, but I can't see how that helps. Are you sure you referenced the right file?

**Comment by nfplee** [comment]
Incase anyone was wondering, I managed to get the original example working by calling the `EnableDataAnnotationsValidation` extension method against the edit context. However I didn't like how you essentially validate twice. Therefore instead I pass the `ModelState` as a parameter to the component and say the following in the `OnInitialized` method:

```cs
editContext = new EditContext(Model);

var messages = new ValidationMessageStore(editContext);

foreach (var error in ModelState.SelectMany(s => s.Value?.Errors.Select(e => (s.Key, e.ErrorMessage)) ?? [])) {
    messages.Add(editContext.Field(error.Key), error.ErrorMessage);
}
```
