### ISSUE TITLE
Minimal API with IFormFile throws when request body is missing and Content-Type header is missing or empty

### ISSUE THREAD

**Issue by balazsmeszegeto** [dotnet/aspnetcore#53630]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Having an endpoint with Minimal API and IFormFile:
```
app.MapPost("/upload", (IFormFile file) => "ok");
```

Sending a request with incorrect Content-Type, ie:
```
curl --request POST 'http://localhost:5000/upload' --header 'Content-Type: foo'
```
will return 415 status, as expected. However, missing or empty (spaces) Content-Type, ie:
```
curl --request POST 'http://localhost:5000/upload'
curl --request POST 'http://localhost:5000/upload' --header 'Content-Type:'
curl --request POST 'http://localhost:5000/upload' --header 'Content-Type:  '
```
will throw InvalidOperationException and return 500. I am not 100% familiar with the code in this area (yet), but my understanding is that routing constraint won't exclude the endpoint for missing/empty Content-type, and then parameter binding will throw, while attempting to read HttpRequest.Form. The exception thrown is related to this issue: https://github.com/dotnet/aspnetcore/issues/49096

Tried changing the signature, with attribute and optional, same behaviour:
```
app.MapPost("/upload", ([FromForm] IFormFile file) => "ok");
app.MapPost("/upload", ([FromForm] IFormFile? file) => "ok");
app.MapPost("/upload", (IFormFile? file) => "ok");
```

### Expected Behavior

I expect that for endpoints with IFormFile (or its variations like IFormFileCollection) parameters, only valid Content-Type, ie. `Content-Type: multipart/form-data; ...` will be allowed, excluding missing or empty Content-Type headers. Only valid Content-Type would result in binding parameters from form

### .NET Version

8.0.101

### Anything else?

Checked this issue: https://github.com/dotnet/aspnetcore/issues/39430 but didn't find this explicitly.

I am happy to contribute, but first would need confirmation that this is indeed a bug and not a design decision I am unaware of 😃

**Comment by davidfowl** [comment]
We should return 400 if the form isn't a valid content type rather than throwing (as part of the minimal API codegen).

**Comment by balazsmeszegeto** [comment]
> We should return 400 if the form isn't a valid content type rather than throwing (as part of the minimal API codegen).
Just to make it clear, you mean 400, _not_ 415? Because non-empty but invalid already returns 415. Should missing/empty be treated differently?

**Comment by davidfowl** [comment]
Actually, now I'm wondering why this isn't working:

https://github.com/dotnet/aspnetcore/blob/de12f70f8d536a72bd8c6a2add8f6c8ad8f344af/src/Http/Http.Extensions/src/RequestDelegateFactory.cs#L1487-L1492

**Comment by balazsmeszegeto** [comment]
> Actually, now I'm wondering why this isn't working:
> 
> https://github.com/dotnet/aspnetcore/blob/de12f70f8d536a72bd8c6a2add8f6c8ad8f344af/src/Http/Http.Extensions/src/RequestDelegateFactory.cs#L1487-L1492


I don't think that's being used here, since it'd also accept `Content-Type: application/x-www-form-urlencoded`. But if I try
```
curl --request POST 'http://localhost:5000/upload' --header 'Content-Type: application/x-www-form-urlencoded'
```
so I get 415, as expected.

**Comment by balazsmeszegeto** [comment]
Okay, so I've figured that this code will add `AcceptsMetadata` to the endpoint:
https://github.com/dotnet/aspnetcore/blob/de12f70f8d536a72bd8c6a2add8f6c8ad8f344af/src/Http/Http.Extensions/src/RequestDelegateFactory.cs#L1997

I can observe similar behaviour if explicitly add `IAcceptsMetadata`, for example:
```
app.MapGet("/foo", ([FromQuery] Foo? foo) => "ok")
    .Accepts<Foo>(contentType: "foo/bar");
```

will behave the same way, so the following invalid _and_ non-empty Content-Type return 415:
```
curl --request GET 'http://localhost:5000/foo' --header 'Content-Type: bar/baz'
curl --request GET 'http://localhost:5000/foo' --header 'Content-Type: something'
```

but these, missing or empty return 200:
```
curl --request GET 'http://localhost:5000/foo' --header 'Content-Type:'
curl --request GET 'http://localhost:5000/foo'
```

Is it correct to assume, that if `IAcceptMetadata` is present, request without or with empty Content-Type should only be accepted if `IAcceptMetadata` is "match-all" (ie. `*/*`)?

**Comment by balazsmeszegeto** [comment]
Update: the exception only happens if both of these are true:

* no request body
* Content-Type header is missing or empty

The bug is in `TryReadFormAsync`, which would return successful if `IHttpRequestBodyDetectionFeature.CanHaveBody` is false.
