### ISSUE TITLE
InputFile OnChange does not work properly

### ISSUE THREAD

**Issue by davidez** [dotnet/aspnetcore#53638]
Hello, I was writing some stuff and I found something unexpected with the InputFile so I created a basic example of the issue I am facing by modifying the counter page of the default Blazor server app:

```razor
@page "/counter"
<InputFile multiple OnChange="OnChange" class="form-control"></InputFile>

@code {
	private async Task OnChange(InputFileChangeEventArgs e) {

		foreach (var item in e.GetMultipleFiles()) {

			using FileStream fs = new($@"C:\test\{Guid.NewGuid()}.jpg", FileMode.Create);
			await item.OpenReadStream().CopyToAsync(fs);
		}
	}


}
```

If I upload some jpg images (one or more) I expect them to be copied in the C:\test folder, the file are created but those files are always empty

**Comment by davidez** [comment]
> Thank you for filing this issue. In order for us to investigate this issue, please provide [a minimal repro project](https://github.com/dotnet/aspnetcore/blob/main/docs/repro.md) that illustrates the problem without unnecessary code. Please share with us in a public GitHub repo because we cannot open ZIP attachments, and don't include any confidential content.

here it is https://github.com/davidez/ImageUpload

**Comment by PotatoDotJar** [comment]
I just created a new Blazor .NET 8 project and added the example code from [here](https://learn.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-8.0#client-side-file-upload-example) and am running into the same problem.

**Comment by PotatoDotJar** [comment]
Disregard my previous comment. I fixed my issue by adding `@rendermode InteractiveServer` to the top of my page. After reading through the docs a few times, I realized I had missed the rendermode part at the top.

https://learn.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-8.0

**Comment by davidez** [comment]
> Disregard my previous comment. I fixed my issue by adding `@rendermode InteractiveServer` to the top of my page. After reading through the docs a few times, I realized I had missed the rendermode part at the top.
> 
> https://learn.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-8.0

Is the image you were uploading above 1MB?

**Comment by PotatoDotJar** [comment]
> > Disregard my previous comment. I fixed my issue by adding `@rendermode InteractiveServer` to the top of my page. After reading through the docs a few times, I realized I had missed the rendermode part at the top.
> > https://learn.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-8.0
> 
> Is the image you were uploading above 1MB?

I was uploading a several GB zip file. After I added `@rendermode InteractiveServer`, I did not have any issues. So I think this is maybe a non-issue?

**Comment by davidez** [comment]
Idk, I think that the rendering mode should be inherited from the Program.cs AddInteractiveServerComponents() and AddInteractiveServerRenderMode(), shouldn't it?
I can retry tomorrow with that, but I still have questions about this behavior

**Comment by davidez** [comment]
And the default max file size should be around 128 MB as it is commented in the Program.cs file, but i didn't test it. I mean, that's what the documentation says

**Comment by davidez** [comment]
> > > Disregard my previous comment. I fixed my issue by adding `@rendermode InteractiveServer` to the top of my page. After reading through the docs a few times, I realized I had missed the rendermode part at the top.
> > > https://learn.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-8.0
> > 
> > 
> > Is the image you were uploading above 1MB?
> 
> I was uploading a several GB zip file. After I added `@rendermode InteractiveServer`, I did not have any issues. So I think this is maybe a non-issue?

nope, doesn't work adding the rendermode. I also tried with a 1.7 GB file and I got the same result. And I'm not gonna lie, I don't even believe that you tried it if you say it works

**Comment by PotatoDotJar** [comment]
> > > > Disregard my previous comment. I fixed my issue by adding `@rendermode InteractiveServer` to the top of my page. After reading through the docs a few times, I realized I had missed the rendermode part at the top.
> > > > https://learn.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-8.0
> > > 
> > > 
> > > Is the image you were uploading above 1MB?
> > 
> > 
> > I was uploading a several GB zip file. After I added `@rendermode InteractiveServer`, I did not have any issues. So I think this is maybe a non-issue?
> 
> nope, doesn't work adding the rendermode. I also tried with a 1.7 GB file and I got the same result. And I'm not gonna lie, I don't even believe that you tried it if you say it works

What an odd thing to claim. The whole reason I jumped into this discuss was because I was having the same issue on a project I was working on. I have added the rendermode and it is now working for me. You don't have to believe me. I am just adding what I found to the conversation. 

After further testing, I have found that most callback events in pages and components don't work unless you explicitly add the `@rendermode InteractiveServer` to the page/component OR set the route rendermode to InteractiveServer. 

I did add `AddInteractiveServerComponents()`, but my guess is that it just enables the feature. I am not sure what the default rendermode is, but if I had to guess, I think it is static.

**Comment by davidez** [comment]
> > > > > Disregard my previous comment. I fixed my issue by adding `@rendermode InteractiveServer` to the top of my page. After reading through the docs a few times, I realized I had missed the rendermode part at the top.
> > > > > https://learn.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-8.0
> > > > 
> > > > 
> > > > Is the image you were uploading above 1MB?
> > > 
> > > 
> > > I was uploading a several GB zip file. After I added `@rendermode InteractiveServer`, I did not have any issues. So I think this is maybe a non-issue?
> > 
> > 
> > nope, doesn't work adding the rendermode. I also tried with a 1.7 GB file and I got the same result. And I'm not gonna lie, I don't even believe that you tried it if you say it works
> 
> What an odd thing to claim. The whole reason I jumped into this discuss was because I was having the same issue on a project I was working on. I have added the rendermode and it is now working for me. You don't have to believe me. I am just adding what I found to the conversation.
> 
> After further testing, I have found that most callback events in pages and components don't work unless you explicitly add the `@rendermode InteractiveServer` to the page/component OR set the route rendermode to InteractiveServer.
> 
> I did add `AddInteractiveServerComponents()`, but my guess is that it just enables the feature. I am not sure what the default rendermode is, but if I had to guess, I think it is static.

Did you try with the code in my repo?

**Comment by davidez** [comment]
@javiercn  What kind of feedback is needed?

**Comment by davidez** [comment]
> > Thank you for filing this issue. In order for us to investigate this issue, please provide [a minimal repro project](https://github.com/dotnet/aspnetcore/blob/main/docs/repro.md) that illustrates the problem without unnecessary code. Please share with us in a public GitHub repo because we cannot open ZIP attachments, and don't include any confidential content.
> 
> here it is https://github.com/davidez/ImageUpload

Isn't this what you need?

**Comment by mkArtakMSFT** [comment]
@davidez I just tried out your repro and it failed from the first try.
The culprit, however, is in your code. The `OpeanReadAsync` method accepts an optional `maxAllowedSize` parameter, for which the default value is 512000. Because the file being uploaded was larger than that, the method was throwing an exception.
I tweaked your slightly simply to demonstrate that it works.
Here what you need to change it to:

```csharp
item.OpenReadStream(maxAllowedSize: Int32.MaxValue)
```

Hope this helps.
