### ISSUE TITLE
Blazor needs a "Angualr Hydration" similiar feature

### ISSUE THREAD

**Issue by shui106** [dotnet/aspnetcore#53635]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

New .net8.0 blazor full stack UI is a good start. But we can see the obvious flicker when prerender is enabled. We have some APIs to persist the state and resore the state to prevent the page flickers, but we need to do this for every parameters for every page manually. I think this will block most users to use it.

### Describe the solution you'd like

The best way is to save the state and restore the sate automatically and make this feature a buildin function and set as default when prerender is enabled. I think with this feature blazor is much perfecter.

**Comment by javiercn** [comment]
@shui106 thanks for contacting us.

That feature already exists, it's called Persistent Component State.

**Comment by shui106** [comment]
Thanks @javiercn , I know it. But it is not an automatical way still needs some user codes for each page. I meant just only one line such like UsePersistentComponentState and Blazor will do the saving and restoring state for every page automatically.
