### ISSUE TITLE
Blazor page route set to "/bin" causes 404 Error when published to Azure

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#53645]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Blazor-page-route-set-to-bin-causes-4/10565381)._

---
[severity:It bothers me. A fix would be nice]
When you set a Blazor component page route to "/bin" you get the following error when you publish the web app to Azure:

`The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.`

---
#### Will Godbe [MSFT] on 1/19/2024, 10:37 AM: 

(private comment, text removed)
#### Trevor Tosello on 1/19/2024, 00:42 PM: 

(private comment, text removed)
#### Trevor Tosello on 1/19/2024, 00:43 PM: 

(private comment, text removed)
#### Feedback Bot on 1/26/2024, 08:55 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe this is Azure-specific behavior and it's by design.
