### ISSUE TITLE
[Epic] Improve the Data Protection experience for apps with multiple instances

### ISSUE THREAD

**Issue by amcasey** [dotnet/aspnetcore#53654]
The golden path for Data Protection is having a single app instance, ideally on Windows.  In that case, pulling anti-forgery, Razor pages, etc into the app, will automatically pull in Data Protection with its default settings.  Keys will be stored locally in an XML file on disk and protected with (e.g.) Windows DPAPI.  Along the golden path, app developers don't have to think about, let alone configure, Data Protection.

Things get more complicated when there are multiple app instances.  For scalability and resilience, it's desirable for any app instance to be able to handle requests from any user session, so each app instance needs to be able to use keys generated by any other instance.  Unfortunately, a mechanism for sharing keys is not something Data Protection can figure out on its own, so explicit configuration is required.  Still more unfortunately, common approaches like storing the keys in Azure occasionally encounter races and communication failures that result in key-not-found errors.

What are we going to do about it?  In 9.0, we're going to focus on:

1. Making existing implementations more resilient against communication errors and initialization races.
2. Evaluating a different approach in which a single, external component is responsible for generating keys and pushing them to shared storage where app instances can share read-only access to them.
3. Documenting best practices for multi-instance apps.

**Comment by amcasey** [comment]
A list of key-not-found issues: #36157
New pattern issues: #52915, #52916

**Comment by josephdecock** [comment]
I'm really heartened to see this epic, because in my work on IdentityServer, the by far most common support topic is data protection. The problems that I see are all to do with  this: 
> Along the golden path, app developers don't have to think about, let alone configure, Data Protection.

My users are on the golden path on their local dev machines, but not when they deploy! And IdentityServer uses the data protection services itself to protect sensitive data at rest, some of which can be very long lived (e.g., signing keys, refresh token data, etc), so data protection issues are especially pronounced in that context. I'm really hopeful to see what all comes of this.

**Comment by amcasey** [comment]
Assuming the above is correct, we probably need:
1. better handling for `CanCreateAuthenticatedEncryptor` failures 
2. some sort of retry logic for when the failure is transient

As noted in #21096, the existing recovery mechanism (swallow and eventually generate a new key) is probably helpful in apps with session affinity (not recommended) or a single instance, so we need to try to avoid making things worse for those apps.

**Comment by amcasey** [comment]
Also potentially relevant, though only if the rethrown exception is handled upstream: https://github.com/dotnet/aspnetcore/blob/b9eaae011790c0afd86948ac3e9641a1fbd847b5/src/DataProtection/DataProtection/src/KeyManagement/KeyRingProvider.cs#L219

**Comment by amcasey** [comment]
Telemetry: https://github.com/dotnet/aspnetcore/issues/54451

**Comment by ProTip** [comment]
Further to josephdecock's point I do not like the implications of point `2` per the description. Namely needing a second, external system to handle key generation and rotation.

This seems like something that could be resolved through distributed locking either in the `IXmlRepository` or through some distributed locking service provided to DP. ie the EF Core storage already has access to the DB. It could either handle locking itself or configure DP with a db-backed lock provider.

If the external component _is_ the way forward I'd likely implement this as a background timer task that runs on each node and handles the locking.

Distributed locking is so useful and common(and with many good backing options via Redis, Dynamo, K8s, etc) that it would almost make sense to introduce the concept into Asp.Net Core.. But I digress 😄

**Comment by amcasey** [comment]
The [default application discriminator](https://github.com/dotnet/aspnetcore/blob/63c8031b6a6af5009b3c5bb4291fcc4c32b06b10/src/DataProtection/DataProtection/src/Internal/HostingApplicationDiscriminator.cs#L35) is the content root path, which can vary between a local instance and a deployed instance (e.g. to App Service).  It would be nice if we could do something about this foot-gun.

**Comment by amcasey** [comment]
@ProTip I'm not sure I fully understand your comment, so please let me know if I've missed your point.

I think you're saying that we could/should resolve key-write races using some sort of coordination mechanism.  While introducing a new component does add complexity, I think it has some advantages over keeping the logic in the app instances:
 1. The key ring can be seeded before the app starts running so that instances don't have to wait for it to be read and updated.
 2. No coordination code is required since there is only one writer
 3. The interface we use to communicate with the backing store, [IXmlRepository](https://github.com/dotnet/aspnetcore/blob/1c8f20be1fc4e97044d7ca93edae3af528bc3521/src/DataProtection/DataProtection/src/Repositories/IXmlRepository.cs#L12), is very restrictive and we can't change it without breaking numerous existing implementations

Note that there are no plans to eliminate the existing mechanisms, so you can continue to have each node do its own key generation and you're free to implement your own `IXmlRepository` with distributed locking (though, again, the interface is not very conducive to sophisticated implementations).

**Comment by ProTip** [comment]
Heya, yes I think you grok what I'm saying fully.

I think it's a great _option_ to manually handle key generation and rotation however:

> The key ring can be seeded before the app starts running so that instances don't have to wait for it to be read and updated.

Can't this be done anyway based on implementer requirements? I think a short delay when firing up a brand new application with an empty keyring isn't a concern for the vast majority.

> No coordination code is required since there is only one writer

But it won't work as expected OOTB..

> The interface we use to communicate with the backing...

I'm not as familiar with the interfaces or issues here. However this coordination logic may be able to be moved into the core DP code that reaches out to the `IXmlRepository` and work with a configured distributed lock provider. The extension methods that configure specific `IXmlRepository` implementations could also, optionally, register a bundled lock provider implementation.

Ultimately it feels a bit yucky that DP, which is supposed to just transparently work, would be the only(?) foundational Asp.Net Core component that introduces a _requirement_ on an external service to function as expected(I'm tempted to say correctly) in a multi-node environment.

**Comment by amcasey** [comment]
> I think it's a great _option_ to manually handle key generation and rotation however:

https://github.com/dotnet/aspnetcore/pull/53539 and possibly https://github.com/dotnet/aspnetcore/pull/53860 are the only changes I'm expecting to aspnetcore to support this new pattern.  Without additional configuration, I wouldn't expect either to have any effect.

> > The key ring can be seeded before the app starts running so that instances don't have to wait for it to be read and updated.
> 
> Can't this be done anyway based on implementer requirements? I think a short delay when firing up a brand new application with an empty keyring isn't a concern for the vast majority.

It's not just the delay.  Instances don't know how many other instances there are, so it's hard for them to ensure they're using a key available to all other instances (i.e. so that sessions can migrate between them).

> > No coordination code is required since there is only one writer
> 
> But it won't work as expected OOTB..

Tell me more about what it means for things to work out of the box?  It sounds like you don't mean "without user configuration", because the app developer would need to establish a shared storage location and point all the app instances at it.

> I'm not as familiar with the interfaces or issues here. However this coordination logic may be able to be moved into the core DP code that reaches out to the `IXmlRepository` and work with a configured distributed lock provider. The extension methods that configure specific `IXmlRepository` implementations could also, optionally, register a bundled lock provider implementation.

I'm not sure what design you have in mind, but it sounds like it would require instances to either know about each other or know about a shared coordination component.  Is that right?

> Ultimately it feels a bit yucky that DP, which is supposed to just transparently work, would be the only(?) foundational Asp.Net Core component that introduces a _requirement_ on an external service to function as expected(I'm tempted to say correctly) in a multi-node environment.

None of this is expected to be required.  At present, it is expected to be sample code demonstrating a way app developers can set up their application that we think will make them more reliable.  There may also be a nuget package or something, but that's TBD.

Obviously, we're a long way from actually shipping and things could change.

**Comment by lukasz-zoglowek** [comment]
@amcasey will the work also address the instabilities/transient failures described here: https://github.com/dotnet/aspnetcore/issues/33071
We discussed that back in January, and I think the proposed solution was to **not** create new keys if the remote store is not accessible

**Comment by amcasey** [comment]
@lukasz-zoglowek Sorry, you'll have to refresh my memory - a link to the conversation would help.

Having said that, https://github.com/dotnet/aspnetcore/pull/54299 should have addressed the fact that those timestamps can be out of order (which was harmless) and, yes, the goal of this epic is to eliminate most (but not all) of those cases.  Not creating a new key when a remote store is not accessible is not viable as a general solution because it can leave the app without a key to use but https://github.com/dotnet/aspnetcore/pull/54711 added some retry support and https://github.com/dotnet/aspnetcore/pull/54490 made many potentially-flaky calls unnecessary.  My expectations is that the combination of those changes will substantially mitigate the issue.  I believe all of that work made it into Preview 4 and your feedback would be greatly appreciated.

**Comment by adityamandaleeka** [comment]
@amcasey Is this epic done? It feels like the key deletion one isn't necessary to gate this on?

**Comment by md-redwan-hossain** [comment]
AES encryption of the DP key will be a very welcoming feature. Currently, the only way to encrypt the key when persisted via EF or Redis is to use a certificate. Why I can't just use AES encryption to encrypt and decrypt the key?

**Comment by amcasey** [comment]
@md-redwan-hossain Data Protection is remarkably pluggable - I'd be surprised to learn you can't do that by providing your own encryptor.  Regardless, this issue probably isn't the best place to get eyes on the question - can you please file a new one?

**Comment by amcasey** [comment]
[Key deletion](https://github.com/dotnet/aspnetcore/pull/53860) is in and the [docs PR](https://github.com/dotnet/AspNetCore.Docs/pull/33104) is looking good.
