### ISSUE TITLE
InteractiveServer StateHasChanged not firing but works with InteractiveWebAssembly

### ISSUE THREAD

**Issue by augustevn** [dotnet/aspnetcore#53662]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm noticing rendering differences when copying components from a WASM project into a project using InteractiveServer.
More specifically, `StateHasChanged` does not trigger.

Repro code:

```csharp

@inject ContactHttpClient HttpClient

<EditForm Model="@_contactModel" OnValidSubmit="HandleContactForm">
    <FluentValidationValidator/>

    <div class="mb-3">
        <label for="contact-subject" class="form-label">Subject <span class="text-danger">*</span></label>
        <InputText id="contact-subject" class="form-control" placeholder="What is it about?" @bind-Value="_contactModel.Subject" required/>
    </div>
    
    <div class="mb-3">
        <label for="contact-message" class="form-label">Message <span class="text-danger">*</span></label>
        <InputTextArea id="contact-message" class="form-control" placeholder="Reason for contact..." @bind-Value="_contactModel.Body" required/>
    </div>
    
    <div class="row mb-3">
        <div class="col">
            <label for="contact-name" class="form-label">Your name <span class="text-danger">*</span></label>
            <InputText id="contact-name" class="form-control" @bind-Value="_contactModel.Name" required/>
        </div>
        <div class="col">
            <label for="contact-email" class="form-label">Your email <span class="text-danger">*</span></label>
            <InputText type="email" id="contact-email" class="form-control" @bind-Value="_contactModel.Email" required/>
        </div>
    </div>
    
    <ValidationSummary/>
    
    <div class="d-grid mb-2">
        <button type="submit" class="btn btn-primary" disabled="@IsSubmit">
            @BtnLabel
        </button>
    </div>
</EditForm>

@if (IsSubmit && !string.IsNullOrWhiteSpace(SuccessMessage))
{
    <p class="mt-2 text-@(IsSuccess == true ? "success" : "danger")">
        @SuccessMessage
    </p>
}

@code {
    [Parameter]
    public string? BtnLabel { get; set; } = "Send";

    private bool IsSubmit { get; set; }
    private bool? IsSuccess { get; set; }
    private string? SuccessMessage { get; set; }

    private CreateContactRequest _contactModel = new();

    private async Task HandleContactForm()
    {
        IsSubmit = true;
        IsSuccess = await HttpClient.CreateContactRequest(request);
        
        SuccessMessage = IsSuccess == true ? "Thank you for contacting me!" : "Oops, could not request contact at this time.";

        Task.Delay(2000).ContinueWith(_ =>
        {
            ResetForm();
            StateHasChanged(); // <-- does not trigger with InteractiveServer, does with InteractiveWebAssembly.
        });
        
        // Or
        
        ResetForm();
        StateHasChanged(); // <-- Same issue.
    }

    private void ResetForm()
    {
        _contactModel = new CreateContactRequest();
        
        IsSubmit = false;
        IsSuccess = null;
        SuccessMessage = null;
    }

    public record CreateContactRequest
    {
        public string Subject { get; set; }
        public string Body { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
    }
}
```

The reason I'm not awaiting the `Task.Delay` is to not freeze the UI. Possibly unconventional but irrelevant to the problem since `StateHasChanged` doesn't trigger with InteractiveServer even when invoked directly in the `HandleContactForm` method.

### Expected Behavior

Expecting `StateHasChanged` to behave the same on InteractiveWebAssembly as on InteractiveServer.

### Steps To Reproduce

1. Put the above code in a .razor file as component e.g. `ContactForm.razor`.
2. Implement this component on a Razor page in a Blazor project.
3. Switch between rendermodes InteractiveWebAssembly and InteractiveServer.

### .NET Version

8.0.100

### Anything else?

Note: the `Auto` render mode will handle it correctly when using WASM, not Server.

Is this to be expected? If so, this doesn't give me great confidence in re-using components between interactivity modes since it behaves differently and requires modification / simplification to work for InteractiveServer.

I sometimes try to force it with an EventCallback but I don't manage to reach the behavior of the WASM interactivity with the Server interactivity.

**Comment by dmm-l-mediehus** [comment]
Make sure you have the SynchronizationContext when the state has changed, meaning on InteractiveServer: `await InvokeAsync(() => { YourCode(); StateHasChanged(); });` or just: `await InvokeAsync(StateHasChanged);`

You have 2 options:
```cs
Task.Delay(2000).ContinueWith(async () =>
{
      ResetForm();
      await InvokeAsync(StateHasChanged);
});
```
Or:
```cs
Task.Delay(2000).ContinueWith(_ =>
{
      ResetForm();
      await Task.Yield(); // Waits until it has the UI thread ready.
      StateHasChanged();
});
```

**Comment by augustevn** [comment]
@dmm-l-mediehus Thanks, I'll give that a go next time. 

But let's not focus on the Task.Delay, even without it, the `StateHasChanged` doesn't trigger on InteractiveServer while it does on InteractiveWebAssembly.

**Comment by gragra33** [comment]
@augustevn The reason for the issue is that on the client-side, it is single threaded but server-side it's multithreaded.

You can read more about what `InvokeAsync` is doing here: [ComponentBase.InvokeAsync Method](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.componentbase.invokeasync?view=aspnetcore-8.0)

**Comment by dmm-l-mediehus** [comment]
> @dmm-l-mediehus Thanks, that might solve it for me.
> 
> Would you recommend the same fix if I wasn't using the `Task.Delay`? Just:
> 
> ```cs
> private async Task HandleContactForm()
>     {
>         IsSubmit = true;
>         IsSuccess = await HttpClient.CreateContactRequest(request);
>         
>         SuccessMessage = IsSuccess == true ? "Thank you for contacting me!" : "Oops, could not request contact at this time.";
>         
>         ResetForm();
>         StateHasChanged(); // <-- Same issue.
>     }
> ```
> 
> Since without it, the `StateHasChanged` wouldn't fire either.
> 
> I only left that `Task.Delay` in to better illustrate the desired behaviour not to focus on it as the root cause.

You don't need the Task.Delay thingy. U can do `await InvokeAsync(StateHasChanged);` right after your changes, in this case, after `ResetForm();`

**Comment by augustevn** [comment]
Ok thanks all, this helped me out!

@dmm-l-mediehus I hadn't used `StateHasChanged` for years with WASM, first encountered it in a Blazor Server project and have since occasionally had to rely on it, mostly while going through the release-candidates.
