### ISSUE TITLE
Blazor Server Rendering does not work on iPhones with a version lower than 17.3

### ISSUE THREAD

**Issue by viknsagit** [dotnet/aspnetcore#53663]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When connecting to a site on Blazor SSR on ios, the site does not respond at all. Buttons that have @onclick and everything from the blazor don't work.

### Steps To Reproduce

To find the bug, you just need to go to the website виколь.рф via ios.

### Exceptions (if any)

I've enabled debug mode for logs.
And here is the error log itself:
log from console:
[log.txt](https://github.com/dotnet/aspnetcore/files/14072810/log.txt)

### .NET Version

8.0.1018.0.101

### Anything else?

IDE: Visual Studio 2022

**Comment by viknsagit** [comment]
Everything works well on android

**Comment by viknsagit** [comment]
The site starts working only on an iPhone with version 17.3

**Comment by javiercn** [comment]
@viknsagit thanks for contacting us.

Can you get the logs from the developer console tools?

**Comment by viknsagit** [comment]
![photo_2024-01-27_20-00-30](https://github.com/dotnet/aspnetcore/assets/80544536/61522a4f-cd92-45ad-a05e-df9adb89f8dc)
Log from Iphone

**Comment by viknsagit** [comment]
I'll try it with an empty template and different rendering later
