### ISSUE TITLE
[Blazor] IJSRuntime.InvokeVoidAsync is accessing the wrong DOM in the browser

### ISSUE THREAD

**Issue by symbiotic** [dotnet/aspnetcore#53677]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In my Blazor Server project, I have a JavaScript function `SetFocus(id)` that takes the `id` of an HTML element, and then sets the focus on that element.
In the event handler of a button:
- I want to make another button visible
- and then set the focus on the button that just became visible, using `js.InvokeVoidAsync("SetFocus", "editBtn")`

What happens:
- `SetFocus` finds the edit button, because i can see it is logged to the browser console
- but focus is not set on the edit button, because `<body>` remains logged to the browser console as the `activeElement`

This does not go wrong when the `EditForm.Model` always receives the same instance. But having to always use the same instance makes things more complicated because it requires keeping track of more state. In this case i want to easily revert changes by preplacing the model.

### Expected Behavior

- I expect that the `IJSRuntime` always accesses the current DOM, and not some old version (as it seems). So that in my case the focus gets set on the button on the screen.
- Probably off topic: I actually also expect a call to `IJSRuntime.InvokeVoidAsync` to force rendering (this should be built into this call). It seems really hacky that Blazor requires a preceding call to `Task.Delay()`. Even a dedicated Blazor function to force rendering would be better.

### Steps To Reproduce

*Use my example and watch the short clip I attached.*

JavaScript (code added to _Host.cshtml):

    <script>
        // display active element every second
        DisplayActive();
        function DisplayActive() {
            setTimeout(function () {
                console.log(document.activeElement);
                DisplayActive();
            }, 1000);
        }

        // set the focus on the element with the given id
        function SetFocus(id) {
            console.log("SetFocus('" + id + "')");
            var e = document.getElementById(id)
            
            console.log(e);
            e.focus();
        }
    </script>

FocusLost.razor

    @page "/focuslost"

    <h3>FocusLost</h3>

    <EditForm Model="@m.Data">
        @if (m.editing)
        {
            <button id="cancelBtn" type="submit" @onclick="m.CancelClick">Cancel</button>
        }
        else
        {
            <button id="editBtn" type="button" @onclick="m.EditClick">Edit</button>
        }
    </EditForm>

    @code {
        class MyModel
        {
            public IJSRuntime js { get; set; }
            public bool editing { get; set; } = false;
            public MyData Data
            {
                get
                {
                    return new();
                    //return original; // returning original instead of a new() fixes it
                }
            }
            private MyData original = new();

            public async Task EditClick()
            {
                editing = true;
            }

            public async Task CancelClick()
            {
                editing = false;
                await Task.Delay(TimeSpan.FromSeconds(5)); // why is this even necessary?
                await js.InvokeVoidAsync("SetFocus", "editBtn");
            }
        }
        class MyData
        {
            public string Dummy { get; set; }
        }

        MyModel m = new();
        [Inject] public IJSRuntime js { get; set; }

        protected override async Task OnParametersSetAsync()
        {
            await base.OnParametersSetAsync();
            m.js = js;
        }
    }

Failure Scenario:
- open Microsoft Edge Chromium and visit `/focuslost`
- open the Console (in the Developer Tools)
- note that the `activeElement` is shown every 1 second (by the function `DisplayActive`)
- click the Edit button on the page, so that it is replaced by a Cancel button
- click the Cancel button on the page, so that it is replaced again with the Edit button
- wait 5 seconds for Task.Delay in the event handler `CancelClick`
- observe the browser console: the message shows `SetFocus` was actually called
- observe the browser console: the next message shows that `getElementById` actually found the button element
- observe the browser console: the next message shows the `activeElement` is the `<body>` instead of the Edit button

Success Scenario:
Now try the above steps again but this time change the code, to always return the same instance of the model from the `MyModel.Data` getter:
- by replacing `return new();`
- with `return original;`

Observe that clicking the Cancel button now correctly sets the focus on the Edit button.

### .NET Version

TargetFramework = net7.0

### Anything else?

![FocusLost](https://github.com/dotnet/aspnetcore/assets/5098237/fd7cf208-be36-4c94-9e50-6f6880df03de)

**Comment by MariovanZeist** [comment]
Hi @symbiotic 
The main issue here is because of this part

```razor
<EditForm Model="@m.Data">
```
Because every time the ``EditForm`` gets it's model, it will get a new instance because of the getter below

```cs
public MyData Data
{
    get
        {
             return new();
             //return original; // returning original instead of a new() fixes it
         }
 }
```

And because it gets a new instance it will recreate everything inside the ``<EditForm>`` (so disposing the old components, and recreating new components) so it isn't ``rerendering``, it's actually completely rebuilding the HTML inside.

My first question would be, do you need a new Instance of MyData every time? and if you do, can't you simply use 
```razor
<EditForm Model="@m">
```
So the instance stays the same and Blazor will not need to rebuild the entire HTML inside the ``EditForm``.

Second, if you want to synchronise your JS calls in this case you could call the JS function in the ``OnAfterRender`` 
In that case it would be better to move the button events ``EventClick`` and ``CancelClick`` and the property ``editing`` outside the ``class MyModel``

```cs

   private bool focus;
    public async Task CancelClick()
        {
            editing = false;
            focus= true;
        }
    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (focus) 
        {
            focus = false;
            await js.InvokeVoidAsync("SetFocus", "editBtn");
        }
    }

This way you are assured Blazor has rendered the page, so you will focus the correct control.

**Comment by javiercn** [comment]
@symbiotic thanks for contacting us.

@MariovanZeist answer is correct here. The right time to "enhance" the dom is always within OnAfterRender, any other time its not guaranteed that the node is still there.

**Comment by symbiotic** [comment]
@MariovanZeist
Thanks for your suggestions (workarounds) which i've now tried:
- `<EditForm Model="@m">` instead of `<EditForm Model="@m.Data">` has the consequence of the `DataAnnotationsValidator` not working (no more validation messages). i have my own validator that doesn't have this issue, but the consequence is still concerning.
- always returning the same instance: as i mentioned, it requires keeping track of extra state. that's why i didn't do it. but i might still do that
- using `OnAfterRenderAsync`: it's a pity that it then isn't all handled in 1 event hander this way (spaghetti code) and i have to move the generic logic back into the page, but this is a good suggestion as it avoids the hacky `Task.Delay`
I will probably go with `OnAfterRenderAsync` and returning the same instance.

**Comment by symbiotic** [comment]
@javiercn does `OnAfterRenderAsync` have the same guarantee? i'm asking because i don't think i can `await` an `async` method (`IJSRuntime.InvokeVoidAsync`) from a synchronous method (`OnAfterRender`)

**Comment by MariovanZeist** [comment]
@symbiotic Yes both ``OnAfterRender`` and ``OnAfterRenderAsync`` are guaranteed to be called after Blazor has rendered the page.
If you need to call an async method you will have to override ``OnAfterRenderAsync`` (Which in your case applies)
