### ISSUE TITLE
There is a problem with transmitting and receiving url routing parameters

### ISSUE THREAD

**Issue by zengnanhua** [dotnet/aspnetcore#53683]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![image](https://github.com/dotnet/aspnetcore/assets/22017107/64e9774d-742f-4611-94d1-9f0bbf1a7a7f)
![image](https://github.com/dotnet/aspnetcore/assets/22017107/6212fc1b-ea02-48d6-925f-fbdd4c6fc82d)

### .NET Version

7.0.0

### Anything else?

There is a problem with transmitting and receiving url routing parameters

**Comment by martincostello** [comment]
Please provide details about the specific problem, the expected result, as well as a minimal reproducible example of how the to reproduce it with code.

Otherwise people are just guessing based on your screenshot which could lead to ambiguity and misunderstanding.
