### ISSUE TITLE
In RCL, how to deploy reusable .scss files using nuget in .NET Blazor project instead of npm while can be referenced (using @import) by other .scss within project folder?

### ISSUE THREAD

**Issue by aDisplayName** [dotnet/aspnetcore#53682]
This is a duplication of a question I've asked in (https://github.com/NuGet/Home/discussions/13201)

In Angular Project, the reusable SCSS is being deployed via node modules using npm. But for C# Blazor project, we would like to see the similar solution by using RCL / nuget. 

In our case, we have created a `common-color.scss` file to provide a common color code definitions.

*Project: SharedColor.csproj / Styles / common-color.scss*
```scss
// COMMON COLORS
$_color-black: #000;
$_color-white: #fff;
```

What we would like to achieve, is to package this `common-color.scss` into the `SharedColor.nupkg` as source code, and allow the project importing this nuget package to be able to reuse the file with their own .scss files:

*Project: BlazorApp1.csproj / Page / index.razor.scss*
```scss
@import "../Styles/common-colors.scss";

.info {
    color: $_color-black;
}

```

We are using [AspNetCore.SassCompiler](https://www.nuget.org/packages/AspNetCore.SassCompiler) to convert `index.razor.scss` into `index.razor.css` during the build.

When building project, as shown below, An error was thrown because the build task [Compile Sass](AspNetCore.SassCompiler/build/AspNetCore.SassCompiler.targets) from AspNetCore.SassCompiler could not find file `/Styles/common-colors.scss` under the project folder `BlazorApp1` at the time the task was performed, as we can see the file is actually located under `%USERPROFILE%\.nuget\packages\sharedcolor\1.0.0\contentFiles\any\net8.0\Styles\common-colors.scss`

![image](https://github.com/dotnet/razor/assets/19527258/2e53db73-d92c-463a-bb76-d37d0a2eebda)

My question is
1. What are those icons called in solution explorer mean? 
![image](https://github.com/NuGet/Home/assets/19527258/fa75fd48-b1e4-4e8d-b4ef-8a218141896f)
Is there a term/name for those items "virtually showed up" from nuget package into the host project's 'virtual folder'?
2. Is there such a task stage during the build, that all those assets from nuget packages are combined/overlayed with the files located in the project folder, so that the source code files from the nuget package, can be directly referenced in SCSS / SASS 's `import` or `use` statement? It would be useful to compile front-end artifacts without rely on NPM.

Regards

The code example can be found at [here](https://github.com/aDisplayName/bugsamplecode/tree/main/20240126/SharedScssNuget)

**Comment by javiercn** [comment]
@aDisplayName thanks for contacting us.

> Is there such a task stage during the build, that all those assets from nuget packages are combined/overlayed with the files located in the project folder, so that the source code files from the nuget package, can be directly referenced in SCSS / SASS 's import or use statement? It would be useful to compile front-end artifacts without rely on NPM.

There is no such functionality. You can either choose to include the assets in the nuget package as content (and they'll get copied on to your project) or a static web assets (works for packages and projects, but assets don't get copied, so you need to do extra work if you want to be able to reference them in scss in the way you are used to (essentially you need to write the equivalent of a node_resolver).

**Comment by aDisplayName** [comment]
@javiercn , as far as I know, the content of nuget package is not being copied to the project source code folder physically. They are only appears as if under the project folder as the screenshot shown.

They are being copied over to the project output folder, aka the `bin/<Configuration>/<tfm>` after the project is being built, but it will be too late.

Is there any SDK style property I can use in the main project's csproj file that I can use to reference the actual physical location of those contents (`common-colors.scss`) from my RCL? At least I can write some custom build targets to reference those.
