### ISSUE TITLE
[.NET 9] BlazorWebView fails to load on older Android devices `Uncaught SyntaxError: Unexpected token .`

### ISSUE THREAD

**Issue by Eilon** [dotnet/aspnetcore#53699]
The JS file generated for `blazor.webview.js` contains JS code that is not valid on older Android systems unless they update their WebView.

This error occurs immediately when loading a BlazorWebView's contents: `Uncaught SyntaxError: Unexpected token .`

And occurs on this JS line in the file:

```js
    function l(e) {
        const t = a.get(e);
        return t?.browserEventName || e   // <------------
    }
```

![image](https://github.com/dotnet/aspnetcore/assets/202643/c7bb984e-5de8-45a9-b8a4-e762ce228b56)

It seems to be [this code](https://github.com/dotnet/aspnetcore/blob/main/src/Components/Web.JS/src/Rendering/Events/EventTypes.ts#L53-L56), which oddly doesn't seem to have changed in very, _very_ long time.

I'm not sure what _did_ change that this would start happening only recently. Maybe TypeScript changed to generate different code?

This happens by default on Android Emulators with API 30 and older (we know that API 33 works, not sure about 31 and 32).

On these older Android emulator images you can update the System WebView to get newer versions, and that seems to fix the problem.

Some options to consider:

1. Do nothing. Users and/or app developers have to make sure the system is up-to-date. Well, minimally we'd want to _document_ this, but no code change.
2. Have BlazorWebView [detect older WebView on Android](https://developer.android.com/develop/ui/views/layout/webapps/managing-webview#version) and fail more gracefully. Or perhaps log something?
3. Have Blazor use JS code that is compatible with older Android WebView versions. Perhaps there is a TypeScript flag to tell it to generate 'old' JS that is more compatible?

Note: This scenarios is somewhat reminiscent of the fact that on Windows you have to have Edge WebView2 installed and that things won't work if you don't. You'll probably get some weird errors, but the BlazorWebView control doesn't do a lot to help you (for better or for worse).

**Comment by Eilon** [comment]
It seems we had a sort of similar issue in the past, which we did fix: https://github.com/dotnet/aspnetcore/issues/39086

**Comment by javiercn** [comment]
@Eilon this was likely me, as part of revamping our JS infrastructure.

We did switch bundlers and "standarized" compiler settings, etc. One of the things that we did was making sure that we targeted modern JS.

All three options you propose sound fine to me, but this comes down to the support we wanted to offer, and I think we aligned the Android support with the general platform support for Browsers we had, so I'm more inclined to suggest we tell developers to update their webview. Probably with a better error message if possible. As far as I know, webview updates automatically on Android devices too, isn't it? So this is more of an "emulator" driven issue than an issue on real devices.

Also note, that previous versions up to 8.0 are fine, as this change was introduced in January, so there's no rush for us to react. (By the time we ship again, we might consider those platforms too old (as I think we already do) and all versions we care about might not have issues).

In any case, should we need to react, there's some work that we can do to make this work if needed by providing a custom config for webview.

**Comment by Eilon** [comment]
For future reference: If we decide to make this work again on older Android/Chrome/WebView, then we also need to re-enable some tests that were disabled when this break was introduced. We added Android API 28, 29, 30 to the _excluded_ list of API levels that we test for BlazorWebView in the dotnet/maui repo. See change here: https://github.com/dotnet/maui/commit/9c03adcef4fe852f14738825a9cba8df2312b8a7#diff-d2d1c388a0fb3196dbfcdab96421bc88336637a3d44480c96717f92d000facaeL155-R155

```
<!          androidApiLevelsExclude: [ 27, 26, 25, 24, 23, 22, 21 ] # BlazorWebView requires a recent version of Chrome
!>          androidApiLevelsExclude: [ 30, 29, 28, 27, 26, 25, 24, 23, 22, 21 ] # BlazorWebView requires a recent version of Chrome
                                       ^^^^^^^^^^^^
```

**Comment by danroth27** [comment]
We believe most devices will automatically update to the latest webview, so we prefer not to make changes to accommodate older JavaScript runtimes.

**Comment by ghhv** [comment]
The only challenge with this @danroth27 is even brand new industrial Android devices are quite often running older Android versions. I'm only here because I have a set of Android 10 (v29) barcode scanners and I tried to update to .NET 9. Does this mean .NET 8 is the end of the road for me?

**Comment by caoyiliang** [comment]
Thank you for your letter, I will reply as soon as possible

**Comment by sjaakmarelis** [comment]
I have the same issue, with a zebra TC21, it does not work anymore, that is supported bij MAUI, but running blazor from a webview in maui is not working because of the script errors

**Comment by danroth27** [comment]
> The only challenge with this [@danroth27](https://github.com/danroth27) is even brand new industrial Android devices are quite often running older Android versions. I'm only here because I have a set of Android 10 (v29) barcode scanners and I tried to update to .NET 9. Does this mean .NET 8 is the end of the road for me?

@ghhv I see. So, you're seeing this on actual Android hardware, not just with local development in the Android emulator. Are you also unable to update the system web view on these barcode scanners?

**Comment by danroth27** [comment]
> I have the same issue, with a zebra TC21, it does not work anymore, that is supported bij MAUI, but running blazor from a webview in maui is not working because of the script errors

@sjaakmarelis Same question for you: Are you able to update the system web view on this device?

**Comment by caoyiliang** [comment]
> I have the same issue, with a zebra TC21, it does not work anymore, that is supported bij MAUI, but running blazor from a webview in maui is not working because of the script errors

zebra TC21 customer service said to update the system in order to upgrade, update the system also requires a foreign money, in a fit of anger, maui and zebra are deactivated, ha ha ha

**Comment by ghhv** [comment]
@danroth27 I've finally revisited this and yes, I now understand that this is only an issue with the old WebView (v74) on the emulator and I've managed to resolve (sub-optimally) as I've documented here [https://github.com/dotnet/AspNetCore.Docs/issues/34428](https://github.com/dotnet/AspNetCore.Docs/issues/34428)

I think for the sake of everyone who ends up in this rabbit hole and not realising that the issue is not their code, but the old WebView on these emulator versions (which is not readily upgradeable) that you should add this [suggested code](https://github.com/dotnet/maui/issues/7840#issuecomment-1165614284) from @javiercn to the Maui templates or even better to blazor.webview.js so it handles it properly rather than the cryptic message at the top of this issue. Would save a lot of time and frustration. Much appreciated.

**Comment by caoyiliang** [comment]
Thank you for your letter, I will reply as soon as possible

**Comment by timmac-qmc** [comment]
Kind of fixed using compiled blazor.webview.js for ES2019.
Someone posted a recent version in the commit provided in the comment here
https://github.com/Yu-Core/SwashbucklerDiary/issues/79#issuecomment-2563510353

**Comment by ghhv** [comment]
The Github Copilot answer:

The error `Uncaught SyntaxError: Unexpected token .` in older browsers is likely caused by the optional chaining operator (`?.`), which is not supported in those browsers.

To make the code compatible with older browsers, you can replace the optional chaining operator with a more traditional approach:

```typescript
export function getBrowserEventName(possibleAliasEventName: string): string {
  const eventOptions = eventTypeRegistry.get(possibleAliasEventName);
  return eventOptions && eventOptions.browserEventName ? eventOptions.browserEventName : possibleAliasEventName;
}
```

**Comment by Eilon** [comment]
Hi everyone, I've posted a step-by-step guide on how to work around this issue by using an ES2019-compatible version of `blazor.webview.js`: https://github.com/dotnet/maui/discussions/27327

If you're running into the problem described in this issue, please try that out and let us know if the workaround is working for you.

**Comment by ghhv** [comment]
FYI, maybe use the Google deprecation timeline instead of jumping ahead of it..
[https://support.google.com/chrome/thread/352616098/sunsetting-chrome-support-for-android-8-0-oreo-and-android-9-0-pie](https://support.google.com/chrome/thread/352616098/sunsetting-chrome-support-for-android-8-0-oreo-and-android-9-0-pie)

**Comment by caoyiliang** [comment]
Thank you for your letter, I will reply as soon as possible

**Comment by martinstoeckli** [comment]
> 
> All three options you propose sound fine to me, but this comes down to the support we wanted to offer, and I think we aligned the Android support with the general platform support for Browsers we had, so I'm more inclined to suggest we tell developers to update their webview. Probably with a better error message if possible. As far as I know, webview updates automatically on Android devices too, isn't it? So this is more of an "emulator" driven issue than an issue on real devices.
> 

The problem is, that as a developer you cannot update the users WebView on Android and afaik the WebView can be vendor specific. We can't even detect the error and bring a decent message, because the app already hangs with the loading screen. The user will just see that the app doesn't work and give the 1 star review.

**Comment by caoyiliang** [comment]
Thank you for your letter, I will reply as soon as possible

**Comment by St0rmyMindbender** [comment]
@danroth27 @javiercn We are having the same issue with Zebra TC26 (new device) running Android 11 and Webview v90. Can you please just Provide the Code in old ES2019? These kind of optimizations are not worth it in my opinion. Alternative für us is abandoning Blazor and using Maui native.

Thanks and br

**Comment by danroth27** [comment]
@St0rmyMindbender Take a look at the [workaround](https://github.com/dotnet/maui/discussions/27327) @Eilon [posted](https://github.com/dotnet/aspnetcore/issues/53699#issuecomment-2611087804) above for using an ES2019 compatible version *blazor.web.js* and let us know if that works for you.

**Comment by St0rmyMindbender** [comment]
> [@St0rmyMindbender](https://github.com/St0rmyMindbender) Take a look at the [workaround](https://github.com/dotnet/maui/discussions/27327) [@Eilon](https://github.com/Eilon) [posted](https://github.com/dotnet/aspnetcore/issues/53699#issuecomment-2611087804) above for using an ES2019 compatible version _blazor.web.js_ and let us know if that works for you.

.net 8 Version works
