### ISSUE TITLE
POST request returns error 400 (Bad Request) caused by CORS while fetching in JavaScript

### ISSUE THREAD

**Issue by rogulikAFC** [dotnet/aspnetcore#53691]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

API returns error 400 (Response {type: 'cors', url: 'https://localhost:7045/api/Users', redirected: false, status: 400, ok: false, …}) on POST request from React app

Thank you for help!

### Expected Behavior

API has to return 201 

### Exceptions (if any)

Error 400 (Bad Request)

### .NET Version

7.0

### Anything else?

This is the ASP.NET core project: https://github.com/rogulikAFC/School-social-media/tree/main/SchoolSocialMediaServer

The error is returned from method CreateUser in this file: https://github.com/rogulikAFC/School-social-media/blob/main/SchoolSocialMediaServer/SchoolSocialMediaServer/Controllers/UsersController.cs

This is the source code of the project: https://github.com/rogulikAFC/School-social-media

In this file method signUp cause error: https://github.com/rogulikAFC/School-social-media/blob/main/frontend/src/contexts/UserContext.tsx

**Comment by BrennanConroy** [comment]
CORS doesn't return a 400 error code. Also, I don't see a `Users` method on your controller, did you mean to send a request to `CreateUser`?

Look at server logs and see where the error is coming from.

**Comment by rogulikAFC** [comment]
I've tried to send request via Postman and it's said that it was an error that caused because of password validation, so it's not an ASP.Net bug 🤦🏻‍♂️
