### ISSUE TITLE
Performance Issues with multiple Components rendering in Blazor Web Assembly

### ISSUE THREAD

**Issue by DhivyaRajendran** [dotnet/aspnetcore#53704]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We've identified performance issues within the Blazor WebAssembly application, particularly during the rendering of multiple components.

This was a default example of the weather sample. When rendering a single table, the scripting time is approximately ~84ms. However, when rendering multiple tables, the scripting time increases to around ~145ms.

![image](https://github.com/dotnet/aspnetcore/assets/24690158/b03ea131-13a9-4131-8dd2-b053aa40374c)

![image](https://github.com/dotnet/aspnetcore/assets/24690158/0303a837-fb79-4778-b619-a22a1c80e53d)

### Expected Behavior

What led to an increase in scripting when rendering the same table for both single and multiple times?

### Steps To Reproduce

Please refer to the following link: [GitHub - BlazorWebApp](https://github.com/DhivyaRajendran/BlazorWebApp/)

1. Execute the sample.
2. There are two components: single (/singlegrid) and multiple (/multiplegrid).
3. Open the Performance tab.
4. Go to the singlegrid page.
5. Click the Refresh button to initiate profiling. Afterward, commence profiling by clicking the Toggle grid button. Stop profiling once the table is rendered.
6. Repeat the same process for multiplegrid and observe the scripting performance difference between the single and multiple tables.

### .NET Version

8.0.100

### Anything else?

**IDE: Visual Studio 2022**

.NET SDK:
 Version:           8.0.100
 Commit:            57efcf1350
 Workload version:  8.0.100-manifests.1eabc556

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100\

.NET workloads installed:
 Workload version: 8.0.100-manifests.1eabc556
 [wasm-tools-net7]
   Installation Source: VS 17.8.34330.188
   Manifest Version:    8.0.0/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.workload.mono.toolchain.net7\8.0.0\WorkloadManifest.json
   Install Type:              Msi

 [android]
   Installation Source: VS 17.8.34330.188
   Manifest Version:    34.0.43/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.android\34.0.43\WorkloadManifest.json
   Install Type:              Msi

 [ios]
   Installation Source: VS 17.8.34330.188
   Manifest Version:    17.0.8478/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.ios\17.0.8478\WorkloadManifest.json
   Install Type:              Msi

 [maui-windows]
   Installation Source: VS 17.8.34330.188
   Manifest Version:    8.0.3/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maui\8.0.3\WorkloadManifest.json
   Install Type:              Msi

 [maccatalyst]
   Installation Source: VS 17.8.34330.188
   Manifest Version:    17.0.8478/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maccatalyst\17.0.8478\WorkloadManifest.json
   Install Type:              Msi

Host:
  Version:      8.0.0
  Architecture: x64
  Commit:       5535e31a71

.NET SDKs installed:
  7.0.203 [C:\Program Files\dotnet\sdk]
  8.0.100-rc.2.23502.2 [C:\Program Files\dotnet\sdk]
  8.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-rc.2.23480.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-rc.2.23479.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-rc.2.23479.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by javiercn** [comment]
@DhivyaRajendran thanks for contacting us.

Please make your repo a public GitHub repository as per our policies we don't download zip files from GH.

**Comment by MackinnonBuck** [comment]
Hi, @DhivyaRajendran.

The difference you're seeing is due to the fact that the "singlegrid" page is not rendering the `<Grid>` component that the "multiplegrid" page is.

If you replace the table in the "singlegrid" page with the same `<Grid>` component used in the "multiplegrid" page, I think you'll observe nearly identical performance characteristics. The cause of the visible delay is that `<GridContent>` fetches forecast data on initialization, and it doesn't render any cells until the forecast data has been initialized.

There doesn't seem to be a product bug here, so I'm going to close out this issue. If you have additional questions, we recommend StackOverflow as a resource.

**Comment by dhivyasyncfusion** [comment]
Hi @MackinnonBuck ,

As per your recommendation, I have implemented both single and multiple grids using the Grid component. In the updated sample, we've employed nested components to create a table, passing the DataSource as cascading parameters for the Grid component. Despite these optimizations, we are still encountering performance issues when rendering both single and multiple Grid.

![image](https://github.com/dotnet/aspnetcore/assets/33689858/cb08fc1f-05a8-446d-81b2-4aa7f495952b)

![image](https://github.com/dotnet/aspnetcore/assets/33689858/007214d3-5715-49bd-96ac-e3a14afc902b)


For your reference, we've developed a straightforward table with nested components. We're experiencing performance issues with complex and nested-level components. Could you kindly review the situation and offer a solution?

Sample : https://github.com/DhivyaRajendran/BlazorWebApp

Regards,
R.Dhivya

**Comment by DhivyaRajendran** [comment]
Hi @MackinnonBuck ,

As per your recommendation, I have implemented both single and multiple grids using the Grid component. In the updated sample, we've employed nested components to create a table, passing the DataSource as cascading parameters for the Grid component. Despite these optimizations, we are still encountering performance issues when rendering both single and multiple Grid.

![image](https://github.com/dotnet/aspnetcore/assets/33689858/cb08fc1f-05a8-446d-81b2-4aa7f495952b)

![image](https://github.com/dotnet/aspnetcore/assets/33689858/007214d3-5715-49bd-96ac-e3a14afc902b)


For your reference, we've developed a straightforward table with nested components. We're experiencing performance issues with complex and nested-level components. Could you kindly review the situation and offer a solution?

Sample : https://github.com/DhivyaRajendran/BlazorWebApp

Regards,
R.Dhivya

**Comment by DhivyaRajendran** [comment]
Hi @MackinnonBuck,

As per your recommendation, I have implemented both single and multiple grids using the Grid component. In the updated sample, we've employed nested components to create a table, passing the DataSource as cascading parameters for the Grid component. Despite these optimizations, we are still encountering performance issues when rendering both single and multiple Grid.

**SingleGrid:**

![image](https://github.com/dotnet/aspnetcore/assets/24690158/e64ce7d3-fffc-49ea-90e2-9bb7bac9e6e8)

**MultipleGrid**

![image](https://github.com/dotnet/aspnetcore/assets/24690158/c930ef2d-7654-4f53-874e-105e0ba01d70)

For your reference, we've developed a straightforward table with nested components. We're experiencing performance issues with complex and nested-level components. Could you kindly review the situation and offer a solution?

Sample : https://github.com/DhivyaRajendran/BlazorWebApp

Regards,
R.Dhivya

**Comment by MackinnonBuck** [comment]
@DhivyaRajendran, pages that render more content will take longer to render. It's not really feasible to make the two examples you've presented have exactly identical performance characteristics.

However, there are ways you can optimize your app. For example, rather than creating components that wrap single HTML elements (e.g., `GridCell`, `HeaderCell`), inline as much as you can into the parent component.

For more performance tips, please refer to https://learn.microsoft.com/aspnet/core/blazor/performance?view=aspnetcore-8.0
