### ISSUE TITLE
Can't run Authentication Samples

### ISSUE THREAD

**Issue by ruylopez751** [dotnet/aspnetcore#53700]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi everyone!

So I just downloaded the latest release and tried to run Authentication samples as mentioned in the documentation 
(this page: https://learn.microsoft.com/en-us/aspnet/core/security/authentication/samples?view=aspnetcore-8.0)

But unfortunately I run into this error:

F:\aspnetcore-8.0.1\Directory.Build.props(236,3): error MSB4019: The imported project "F:\aspnetcore-8.0.1\artifacts\bi
n\GenerateFiles\Directory.Build.props" was not found. Confirm that the expression in the Import declaration "artifacts\
bin\GenerateFiles\Directory.Build.props" is correct, and that the file exists on disk. [F:\aspnetcore-8.0.1\src\Securit
y\samples\ClaimsTransformation\ClaimsTransformation.csproj]

It might look dumb (I'm very new to .net ecosystem)  but I even tried making the artifacts\bin\GenerateFiles directory and then copying the Directory.Build.props file into it but still get the same error (like nothing is changed)
I spent the whole night and day on it but couldn't fix it, sounds like really no one has ever ran into this issue before me. So I thought it might be a bug or something? 
Any help is so much appreciated here. Thanks!

### .NET Version

8.0.1

**Comment by Tratcher** [comment]
See https://github.com/dotnet/aspnetcore/blob/main/docs/BuildFromSource.md for building the repo from source. Also, we only recommend trying to build the main branch or the latest release/8.0 branch (or similar for prior versions). The labels for specific versions like 8.0.1 exist for historical reasons but can't always be built on their own.

**Comment by MackinnonBuck** [comment]
@Rick-Anderson we're thinking that these samples should live outside the aspnetcore repo so that they can be more easily built by customers. Is that something you could take care of?

**Comment by Tratcher** [comment]
These samples exist more for manual testing and development. Most of their content should already be covered in the docs.

**Comment by mkArtakMSFT** [comment]
@Rick-Anderson can we make sure that the docs don't references samples from the aspnetcore repo, as many from the aspnetcore repo require much more complex setup by customers (following our contributor's guidelines basically).
