### ISSUE TITLE
Api endpoint does not properly unescape strange string

### ISSUE THREAD

**Issue by jirisykora83** [dotnet/aspnetcore#53701]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Api endpoint does not properly unescape strange string even if  `System.Uri.EscapeDataString` and `System.Uri.UnescapeDataString` works for same string. 

### Steps To Reproduce

Create a simple asp mvc app.

Add endpoint:
```
app.MapGet("/api/{test}",
	(string test) =>
	{
		return test;
	});
```

send `https://localhost:7290/api/4e7b7591-f80f-4de6-8459-471f8812fce3%26set%20%2FA%20901629923%2B880816964`

which is `System.Uri.EscapeDataString("4e7b7591-f80f-4de6-8459-471f8812fce3&set /A 901629923+880816964");`

and server then return `4e7b7591-f80f-4de6-8459-471f8812fce3&set %2FA 901629923+880816964`

which isn't same and I would expect it to be parse to same value as if I call `System.Uri.UnescapeDataString(result);`

### .NET Version

8.0.100

**Comment by javiercn** [comment]
@jirisykora83 thanks for contacting us.

This is expected and by design. Servers won't unescape %2FA for security reasons as that can result in request paths being interpreted differently.
