### ISSUE TITLE
Blazor Server folder publish fails for specific configurations

### ISSUE THREAD

**Issue by mayur-ekbote** [dotnet/aspnetcore#53714]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am using Antler for my Blazor Server app. I have published the app several times on Azure App Service and VPS without any issue till .net 7.
After I upgraded to .net 8, publish started failing (both on Azure App service and folder) with the following errors:

```
Error NU1605: Warning As Error: Detected package downgrade: System.Text.Encoding.Extensions from 4.3.0 to 4.0.11. Reference the package directly from the project to select a different version. 
 Teardrop -> Antlr4.Runtime 4.6.6 -> NETStandard.Library 1.6.0 -> System.Console 4.0.0 -> runtime.win.System.Console 4.3.0 -> System.Text.Encoding.Extensions (>= 4.3.0) 
 Teardrop -> Antlr4.Runtime 4.6.6 -> NETStandard.Library 1.6.0 -> System.Text.Encoding.Extensions (>= 4.0.11)
```

I made the changes as per the guidance provided for the error [NU1605](https://learn.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1605) to the csproj:

```
    <PackageReference Include="Antlr4" Version="4.6.6">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Antlr4.CodeGenerator" Version="4.6.6">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>

  <PackageReference Include="Antlr4.Runtime" Version="4.6.6" PrivateAssets="all">
  </PackageReference>
```

This fixed the publish issue *only* for publish configuration framework dependent + portable. It fails for all other options i.e. self-contained/platform dependent. 

Note that
1. This did not happen till .net 7 (I have been using the same version of ANTLR since .net core 3.1)
2. Because of this, it is not possible to deploy the app on a linux app service on Azure directly through VS.

### .NET Version

8.0.101

**Comment by javiercn** [comment]
@mayur-ekbote thanks for contacting us.

What error are you getting, can you provide more details?

**Comment by mayur-ekbote** [comment]
The same error (NU1605) for every code reference to ANTLR dependent code. PFA the screenshots + tmp log file. 

![Console](https://github.com/dotnet/aspnetcore/assets/40038634/b3d67b89-38dc-44b2-9664-66666796cfbf)
![Dialog](https://github.com/dotnet/aspnetcore/assets/40038634/5bf30a0f-f19e-45fa-803b-5c24797f6327)
![Errors](https://github.com/dotnet/aspnetcore/assets/40038634/9eb78677-625e-42d8-a6dc-a2083a3f3f1b)
[tmpA9FE.txt](https://github.com/dotnet/aspnetcore/files/14108814/tmpA9FE.txt)

**Comment by javiercn** [comment]
@mayur-ekbote thanks for the additional details.

Does your issue reproduce in an empty web app and/or console app? (Without blazor involved)

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is caused by an issue on your end (specific to your project, rather than Blazor). While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **blazor** tag.

**Comment by mayur-ekbote** [comment]
1. If something worked on .net 7 but didn't in .net 8, then clearly there is some delta that was introduced in between (ANTLR hasn't been updated in years).
2. This is not a "how to" question. This is not "my code doesn't work, please help" type question. It pertains to build issues, and in case of an IDE, it is mostly on the builds/ compiler side (especially since no manual changes are made).
3. There is literally no benefit of posting a question on any online issue tracker such as this and waiting for an answer for days - if the answer can be simply Googled. Any developer can vouch for that :)
4. If you look up NU1605 on SO, there are many responses all the way from net core 2.0. Each of them with wildly different responses - chasing different rabbit holes. Usually, when there is clear solution to an underlying problem, one always finds an SO answer with many upvotes. 
6. One of the reasons to choose .net, is single source of truth - one doesn't have to burn hours trying to look for a solution to an error. The .net documentation is excellent. On this particular issue, unfortunately, .net documentation not very clear. In fact, as a thread on reddit points out, German and English versions of the same issue were materially different! The only solution that is on that page is already incorporated in the nuget package i.e. csproj gets updated with the solution mentioned there when you install ANTLR nuget packages. 
7. I understand that you might not want to take up one off issues (especially the one that are not reproducible - neither of us can diagnose what is going on). So it's best if the documentation provides enough clarity on the source and resolution of the issue. 
That will reduce both the developer frustration/time and your time/attention in responding on this forum.
