### ISSUE TITLE
IdentityCookieAuthenticationBuilderExtensions causing 404 Not Found

### ISSUE THREAD

**Issue by chris-briddock** [dotnet/aspnetcore#53719]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

IdentityCookieAuthenticationBuilderExtensions - Specifically where we have this hardcoded value. /Account/Login

Is causing a 404 Not Found if this is just a web api. I imagine this will cause an issue in Blazor too.

### Expected Behavior

Does not cause 404.

### Steps To Reproduce

Add Identity API endpoints to a Web API project. 
Hit an endpoint with an invalid bearer token. Should attempt to redirect to /Account/Login.

### Exceptions (if any)

N/A

### .NET Version

8.0.1

### Anything else?

N/A

**Comment by MackinnonBuck** [comment]
Seems related to https://github.com/dotnet/aspnetcore/issues/9039

**Comment by mkArtakMSFT** [comment]
Thanks @MackinnonBuck. This will indeed be fixed by the linked issue. Closing as a dupe.
