### ISSUE TITLE
UseStaticFiles, ability to log not found file's path.

### ISSUE THREAD

**Issue by dehghani-mehdi** [dotnet/aspnetcore#53711]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I want to log the URL of the requested file if the file doesn't exist, but I could not find any way to tell `UseStaticFiles` to do that.

### Describe the solution you'd like

A solution to tell `UseStaticFiles` log/report not found file's path.

**Comment by Tratcher** [comment]
UseStaticFiles intentionally does not do this because the request may not even be for a file, it may be handled by some later middleware. The file system is also abstracted by IFileProvider, UseStaticFiles doesn't even know the full file paths, only the request paths.

**Comment by dehghani-mehdi** [comment]
So, If I want to log or terminate the request, if the requested file doesn't exist, I have to write a middleware to do that?

**Comment by Tratcher** [comment]
Soft-of. Any request that is not handled by any middleware will reach the end of the pipeline and 404. Hosting will log the status of all responses. It sounds like you want a specific log for 404s though?

**Comment by dehghani-mehdi** [comment]
I should mentioned that before, my project is not a regular ASP.NET project, although the whole concept is almost the same as a standard ASP.NET project, but instead of using the built-in routing mechanism, I have a custom middleware, _PageMiddleware_, to handle the request and produce the response to the client.
Right now if the request reaches _PageMiddleware_, I have first to check if the request looks like a file request, if so, I return 404 to the client. what I want is to remove this check, because I think is not a good way to handle this situation, I assume `UseStaticFile` already knows the request is for a file and it doesn't exist (_, of course, you told me it doesn't tho_), so it should give me an option to handle it.

**Comment by Tratcher** [comment]
UseStaticFile doesn't know if a request is for a file, it's just a raw match of the request path to paths on disk. There's nothing about a request that specifically identifies it as for a file. The closest is the *.foo naming extensions which is only a heuristic, other middleware can use it and static files don't require it.

**Comment by dehghani-mehdi** [comment]
I still think UseStaticFile should give the user the option to deal with different cases, even the ability to log found files is useful in some use cases, but based on your comments adding such an option doesn't make sense to you, right?

**Comment by Tratcher** [comment]
Please do go into more detail on the scenarios you want to address. I'm just trying to clarify what the static files middleware actually knows about a given request, vs the assumptions you've made.

> even the ability to log found files is useful in some use cases

Doesn't it already log that?
https://github.com/dotnet/aspnetcore/blob/e07adfec59003776702370fe2091e731a323c67f/src/Middleware/StaticFiles/src/StaticFileContext.cs#L326

It actually does logs misses, but only at the debug level:
https://github.com/dotnet/aspnetcore/blob/e07adfec59003776702370fe2091e731a323c67f/src/Middleware/StaticFiles/src/StaticFileMiddleware.cs#L70

**Comment by dehghani-mehdi** [comment]
Ok, I disabled the built-in logger, so I didn't see those logs, that was helpful information, thank you. my main concern is terminating the request tho. the performance is critical to me, so I want to terminate the request as soon as possible. All I'm saying is, `UseStaticFile` [already knows the file doesn't exist](https://github.com/dotnet/aspnetcore/blob/e07adfec59003776702370fe2091e731a323c67f/src/Middleware/StaticFiles/src/StaticFileMiddleware.cs#L117), otherwise the `FileNotFound` doesn't make sense there, so the request was for a file, the file doesn't exist, so it can be terminated (optionally), that's why I think adding an option for it is a good thing.

> Please do go into more detail on the scenarios you want to address

I already did in [my prev. comment](https://github.com/dotnet/aspnetcore/issues/53711#issuecomment-1928735361), please let me know what part wasn't clear enough.

**Comment by Tratcher** [comment]
> All I'm saying is, UseStaticFile [already knows the file doesn't exist](https://github.com/dotnet/aspnetcore/blob/e07adfec59003776702370fe2091e731a323c67f/src/Middleware/StaticFiles/src/StaticFileMiddleware.cs#L117), otherwise the FileNotFound doesn't make sense there, so the request was for a file, the file doesn't exist, so it can be terminated (optionally), that's why I think adding an option for it is a good thing.

> so the request was for a file,

This is the assumption I'm calling out. UseStaticFiles does not know the request was for a file, only that the request path did or did not match anything on disk. It tries every request for a disk match. It can know it didn't find anything, but it doesn't know if something else will handle the request later. Any optional callback added here would be implemented by you exactly the same way as the logic you added in a follow-up middleware. Given that, I don't see any advantage to adding the callback.
