### ISSUE TITLE
Quickgrid table design problem

### ISSUE THREAD

**Issue by Zvejkus** [dotnet/aspnetcore#53729]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I implemented QuickGrid to my application(Blazor server app), I experience problems with design of the datagrid. There are not typical header columns, but sorting buttons, which should be hidden. Problem is just with the graphics side, the data and paging works.

![image](https://github.com/dotnet/aspnetcore/assets/140164170/9f0f9a84-65ba-44ff-9961-459671708a16)

Here is some code:
![image](https://github.com/dotnet/aspnetcore/assets/140164170/5c50874e-3fa7-440c-a2a2-1cca85ed26fb)
![image](https://github.com/dotnet/aspnetcore/assets/140164170/ffcaa794-37be-46db-9944-00e6c7a8c2ce)

When I try that in standalone project, it works fine. I tried to compare the two projects, but not sure, where the problem is :

![image](https://github.com/dotnet/aspnetcore/assets/140164170/64073474-92c0-45c0-b0fc-90019f7de78d)

Please, do you have any advice where I made mistake?

### .NET Version

.Net 8

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **blazor** tag.
