### ISSUE TITLE
blazor server firefox Uncaught (in promise) WebSocket is not in the OPEN state

### ISSUE THREAD

**Issue by nlpsl202** [dotnet/aspnetcore#53721]
I am using blazor server and set it on IIS10 on windows server 2019
I also install websocket, but when it run NavigationManager.NavigateTo with forceLoad=true, it will cause a error:"Uncaught (in promise) WebSocket is not in the OPEN state" in browser's console, and didn't NavigateTo, why is thas happen, and how I avoid it?
it works fine on Chrome and Edge, but on firefox it will error all the time,

**Comment by mkArtakMSFT** [comment]
Could you also share what version of the Firefox browser are you using?

**Comment by nlpsl202** [comment]
I am using the lastest version 122.0 of FireFox
and thete is the simple project will cause the error when click reload button:
https://github.com/nlpsl202/FX_TEST
I just publish it as a folder and put it on my IIS 10.0 Server, and use firefox to browser it

**Comment by javiercn** [comment]
@nlpsl202 thanks for contacting us.

This seems to be a firefox specific behavior where it continues to run some code in the document, but doesn't seem to have any side effects beyond an error displaying on the console. The page from what we can tell behaves correctly, so you can very likely just ignore the error
