### ISSUE TITLE
Pls enhance the docs about Action injection with FromServices

### ISSUE THREAD

**Issue by 1257960069** [dotnet/aspnetcore#53722]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

https://learn.microsoft.com/zh-cn/aspnet/core/mvc/controllers/dependency-injection?view=aspnetcore-8.0#action-injection-with-fromservices 
not show  property injection sample
https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.fromservicesattribute?view=aspnetcore-2.2
not show which version begin support  property injection

### Describe the solution you'd like

pls add the sample code  about property injection at docs.  It works now about [FromServices] at property

[ApiController]
[Route("[controller]")]
public class WeatherForecastController : ControllerBase
{

    [FromServices]
    public IDateTime dateTime { get; set; }

    public IActionResult About()
    {
        return Content($"Current server time: {dateTime.Now}");
    }

}

### Additional context

![image](https://github.com/dotnet/aspnetcore/assets/31265244/f75a7cea-e7bb-4c2f-a390-5962d4b7b7e2)

**Comment by davidfowl** [comment]
Why not use constructor injection? Is this an optional service?

**Comment by 1257960069** [comment]
In the past, many people believed that Microsoft.Extensions.DependencyInjection did not support attribute injection and chose third-party containers like AutoFac, but now it  has  already supported

**Comment by davidfowl** [comment]
Microsoft.Extensions.DependencyInjection still doesn't support property injection.

**Comment by 1257960069** [comment]
support.
![image](https://github.com/dotnet/aspnetcore/assets/31265244/a824dd1e-d187-40e4-84bf-5994efe48d6f)

**Comment by davidfowl** [comment]
I see this issue is about the docs for controllers specifically 😄. Got it!

**Comment by 1257960069** [comment]
I think it should works at common class  rather than just for controller.
![image](https://github.com/dotnet/aspnetcore/assets/31265244/072cecd4-d1ee-40ea-ba99-a98e960f922b)

FromServicesAttribute at namesapce Microsoft.AspNetCore.Mvc
FromKeyedServicesAttribute at namesapce Microsoft.Extensions.DependencyInjection

I think they are in same namesapce

**Comment by davidfowl** [comment]
You can vote on required property support, FromServices doesn't apply to general classes https://github.com/dotnet/runtime/issues/94323

**Comment by davidfowl** [comment]
It's supported in controllers and has been for a while via a controller specific attribute `[FromServices]`. Supporting it in more places means it has to happen as part of MEDI (Microsoft.Extensions.DependencyInection). I pointed you to the relevant issue.

**Comment by 1257960069** [comment]
I think should support by Microsoft.Extensions.DependencyInection ,rather than works just for controller. 
do you agree with me?

**Comment by davidfowl** [comment]
No, I'm not a fan of the feature, but I think with required properties maybe it's more viable.
