### ISSUE TITLE
Isolated JS for RazorComponentResult

### ISSUE THREAD

**Issue by garrettlondon1** [dotnet/aspnetcore#53741]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am trying to create per page JS files so that they are isolated from the markup like MVC.

I am using Minimal APIs, and RazorComponentResult to render HTML into the DOM. Currently all script tags must live inside of the main component and I don’t want to move them to wwwroot

### Describe the solution you'd like

Have file.razor.js just like MVC or Razor Pages for JS isolation

**Comment by javiercn** [comment]
@garrettlondon1 thanks for contacting us.

This is not a direction we plan to take. The main scenario for RazorComponentResult is rendering static HTML, other features like interactivity, streaming rendering, etc. are not guaranteed to work.

**Comment by garrettlondon1** [comment]
@javiercn is it possible to declare these routes as @page's and use:

Mackinnons' - https://github.com/MackinnonBuck/blazor-page-script

I imagine you would lose some of the benefits of minimal APIs if you do this?
