### ISSUE TITLE
HTTP 413 Payload Too Large even after setting increased request limits .net6 web API

### ISSUE THREAD

**Issue by venkata-sai-eega** [dotnet/aspnetcore#53751]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We have deployed a .net6 web api in AKS(linux) containers. Our front-end application is built with react. We are trying upload multiple files from UI and our API definition accepts List of files as a property within class.

```
[HttpPost("upload")]
public async Task<IActionResult> UploadFiles([FromForm] UploadMultipleFilesCommand uploadMultipleFilesCommand)
```
When i test in my local machine the api works fine. But when i deploy to AKS and when I try to hit the API with even with single file i am getting 413 payload too large.

I tried to increase the request limits based on various online suggestions

```
builder.Services.Configure<IISServerOptions>(options =>
{
    options.AllowSynchronousIO = true;
    options.MaxRequestBodySize = int.MaxValue;
});

builder.Services.Configure<KestrelServerOptions>(options =>
{
    options.AllowSynchronousIO = true;
    options.Limits.MaxRequestBodySize = int.MaxValue;
});

builder.Services.Configure<FormOptions>(x =>
{
    x.ValueLengthLimit = int.MaxValue;
    x.MultipartBodyLengthLimit = int.MaxValue; // if don't set default value is: 128 MB
    x.MultipartHeadersLengthLimit = int.MaxValue;
});
```
One observation was, when i try to upload any file less than 49Kb upload worked fine. In of the article, it was mentioned that 49Kb was the default limit for file upload. So i tried increasing the limits also used following attribute to disable the limit. and still not working.

`[DisableRequestSizeLimit]`

So just wanted to check if i am missing anything.

Will there be any chance of restriction at AKS Pod level that might be blocking the request or API level do I have to set anything else.

### Expected Behavior

File upload endpoint should accept the request and process the uploaded files.

### .NET Version

.NET 6

### Anything else?

IDE: VS 2022, Windows machine local, Linux Containers in AKS

I could not find anything in the pod logs related to exceeding request size.

**Comment by Tratcher** [comment]
Do not change `AllowSynchronousIO`, it's unrelated to this issue.

If it works fine locally then you must be hitting the limit with a different component in production like on a proxy. Do you have server logs for that request locally and in AKS?
