### ISSUE TITLE
Microsoft.AspNetCore.Authentication.OAuth.OAuthTokenResponse.cs does not contain id token

### ISSUE THREAD

**Issue by merijndejonge** [dotnet/aspnetcore#53761]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

When using OIDC protocol i.c.w. personal account, MS Entra returns as a response to https://login.microsoftonline.com/common/oauth2/v2.0/token made in ExchangeCodeAsync a json object that contains an id_token in addition to an access_token. In the call to OAuthTokenResponse.Success(JsonDocument.Parse(body)) the access-token is preserved but the id_token is lost because OAuthTokenResponse does not have a corresponding property.

It turns out that the access_token for personal accounts is not a JWT token while the id_token is. As a consequence, there is JTW token from which needed claims can be fetched. 

### Describe the solution you'd like

Please add IdToken property to OAuthTokenResponse and initialize it with root.GetString("id_token");

**Comment by martincostello** [comment]
Superseded by #53765.
