### ISSUE TITLE
Add IdentityToken property to Microsoft.AspNetCore.Authentication.OAuth.OAuthTokenResponse

### ISSUE THREAD

**Issue by merijndejonge** [dotnet/aspnetcore#53765]
## Background and Motivation

When using OIDC protocol i.c.w. personal account, MS Entra returns as a response to https://login.microsoftonline.com/common/oauth2/v2.0/token made in ExchangeCodeAsync a json object that contains an id_token in addition to an access_token. In the call to OAuthTokenResponse.Success(JsonDocument.Parse(body)) the access-token is preserved but the id_token is lost because OAuthTokenResponse does not have a corresponding property.

It turns out that the access_token for personal accounts is not a JWT token while the id_token is. As a consequence, there is no JTW token from which needed claims can be fetched.

Btw OAuthTokenResponse is a hard-coded class in the system, so it is a sticky dependency which cannot be changed or extended. Therefore, the implementation of OAuthTokenResponse must be changed.

## Proposed API
See also pull request https://github.com/dotnet/aspnetcore/pull/53763
Add a new property `IdentityToken` to `OAuthTokenResponse`:

```
    /// <summary>
    /// Gets or sets the identity token issued by the OAuth provider.
    /// </summary>
    public string? IdentityToken { get; set; }
```

To the (private) constructor of `OAuthTokenResponse`  add the following single line to initialise the property:
```
        IdentityToken = root.GetString("id_token");

```

**Comment by kevinchalet** [comment]
Out of curiosity, why not using the MSFT OIDC handler (`services.AddAuthentication().AddOpenIdConnect()`)?
It's much better equipped for handling OIDC flows than the base OAuth 2.0 handler (e.g it will validate the identity token and extract the claims it contains for you, unlike the OAuth 2.0 handler).

**Comment by merijndejonge** [comment]
Good question, @kevinchalet. I remember that. back then, I could not get it to work. I'm using Duende Identity Server and its documentation seems to promote both approaches. I.e., using AddOpenIdConnect (https://docs.duendesoftware.com/identityserver/v7/ui/login/external) or using AddGoogle/AddMicrosoftAccount (https://docs.duendesoftware.com/identityserver/v7/quickstarts/2_interactive/). To me it isn't clear what the exact differences are.

Can you point me to proper documentation about how to set up a configuration with AddOpenIdConnect and AAD/Entra?

**Comment by kevinchalet** [comment]
> Can you point me to proper documentation about how to set up a configuration with AddOpenIdConnect and AAD/Entra?

To integrate with Entra ID, the easiest option is probably to use `Microsoft.Identity.Web` (which is basically a wrapper around the OIDC handler). https://github.com/AzureAD/microsoft-identity-web/wiki/web-apps should put you on the right track.

**Comment by halter73** [comment]
API Review Notes:

- As a workaround is it possible to use `OAuthResponse.Response.RootElement.GetString("id_token")`?
- We do think the `AddOpenIdConnect` handler is a better option for OIDC flows than `AddOAuth` and adding OIDC features to it might increase confusion.

Let us know if you have issues with `Microsoft.Identity.Web`, but for now we are going to reject this API proposal.
