### ISSUE TITLE
ASP Net 6 does not work correctly on IIS

### ISSUE THREAD

**Issue by botaffonso** [dotnet/aspnetcore#53788]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I've a service created on c#, using BackgroundService class.
That project uses net6.0 version on TargetFramework.

When I install it on IIS, does not work correctly.
I've another services working as well at the same server, but the version of these applications are netcoreapp3.1. 
These applications are configured to work AlwaysRunning and Preload is set True, and they usually works all day long, creating only one instances/process on Task Magager.

But unfortunately the new application created on net6.0 does not work as the other services which use netcoreapp3.1. That new application creates a multiple instances/process on Task Manager.
I configured that application to run every five minutes, but instead of use only one instance as the other services which runs on netcoreapp3.1, these one creates one instance/process every time it begins.

Can anyone help me in that issue?

### Expected Behavior

I hope that new service works as the other services which runs on netcoreapp3.1, it means, create only one instance a day, and work as it configured (five minutes as example).

### .NET Version

6.0

**Comment by Tratcher** [comment]
Please provide a repro app in a github repo.

Does this application handle HTTP requests? If not, why run it in IIS? Would a Windows Service be more appropriate?

**Comment by botaffonso** [comment]
I've figured out what happened...
The issue was at the class Program.cs. This class needs to be write in a different way.
So, I did the corrections at the class, and the service works as it must.

Thanks a lot.
