### ISSUE TITLE
Dependency Injection is not working in Blazor Webassembly Layout Page

### ISSUE THREAD

**Issue by HolyOne** [dotnet/aspnetcore#53808]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have created a new Blazor Webassembly (.net8) project.
In the Client Project's Program.cs I have this line

`
builder.Services.AddTransient<MyClass>();
`

My dependency injection works on pages but not in Layout
In the Layout, I tried to inject the property by using @inject, [inject] or sp.GetRequiredService<MyClass>();

I cannot get Dependency Injection to work in anywhere under the Layout or components added to the Layout (The component works fine in Pages)

This is the Error I get

InvalidOperationException: Cannot provide a value for property 'MyComp' on type 'Test1.Client.Components.MyComponent'. There is no registered service of type 'Test1.Client.Components.MyComponent'.

Is this a known issue or a bug?
I have attached a sample project
 
[test2.zip](https://github.com/dotnet/aspnetcore/files/14158612/test2.zip)

### Expected Behavior

The dependency should have been injected to the layout's code

### .NET Version

8.0.200-preview.23624.5

**Comment by HolyOne** [comment]
I now realized, to make it work,  I have to do AddTransient to both Program.cs on the Server and Program.cs on the Client.
This is the only way I could make this work.
But it doesnt seem right to add the dependency to Server side because I do not need it in the server

**Comment by javiercn** [comment]
@HolyOne thanks for contacting us.

You need to register dependencies both on server and client if they are required by a component via [Inject] or by a service via its constructor or similar. Each Program.cs is a different process and runs in a different environment.

**Comment by HolyOne** [comment]
But this is very confusing.

I need a singleton on the client side. so If I also have to register this singleton on the Server side, is it different on each client or is it the same (since it is a singleton on server) for all clients?
