### ISSUE TITLE
NavigationException when attempting to navigate after submitting a form

### ISSUE THREAD

**Issue by darena-pjindal** [dotnet/aspnetcore#53802]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello - Was the issue reported by Daniel in https://github.com/dotnet/aspnetcore/issues/49143 fixed in the latest release? I am still having that issue. Is there a workaround for this? The code below crashes with exception. 

`@page "/"
@inject NavigationManager NavigationManager

<PageTitle>Index</PageTitle>

<h1>Hello, world!</h1>

Welcome to your new app.

<EditForm method="post" Model="new()" OnValidSubmit="Navigate">
    <button type="submit">Submit and navigate</button>
</EditForm>

@code {
    void Navigate()
    {
        Console.WriteLine("Navigate");
        NavigationManager.NavigateTo("/counter");
    }
}`

**Comment by javiercn** [comment]
@darena-pjindal thanks for contacting us.

That's an exception thrown and caught by the framework. You are only seeing it because you have configured your debugger to break on first chance exceptions. It's the legitimate mechanism that the server uses to stop the current render and emit a redirect instead.

**Comment by javiercn** [comment]
Also, please include the version that you are using, if you aren't using the latest patched version, please update to that version first.

**Comment by darena-pjindal** [comment]
Hello @javiercn - I am on the latest version of the SDK - 8.0.1. I do NOT get redirected to the correct location. I have even tried running it without the debug mode. I can provide a sample but it is EXACTLY how Daniel Roth said it in his example. https://github.com/dotnet/aspnetcore/issues/49143

**Comment by javiercn** [comment]
@darena-pjindal can you provide a minimal repro project that demonstrates the issue?

**Comment by darena-pjindal** [comment]
> @darena-pjindal can you provide a minimal repro project that demonstrates the issue?

Hi @javiercn - I got a reply from Steve Sanderson in the original issue. I can make it work now after disabling the VS exception settings. I didn't realize that we had to disable a VS setting to be able to use it. Thanks again for your help. I appreciate it.
