### ISSUE TITLE
remove pw from source

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/aspnetcore#5380]
https://github.com/aspnet/MusicStore/blob/dev/src/MusicStore/config.json#L7
https://github.com/aspnet/MusicStore/blob/dev/src/MusicStore/Models/SampleData.cs#L102

@blowdart customers are copying this - should we move pw to secrets manager?

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
