### ISSUE TITLE
Blazer Web App Scoped Service Instantiated Twice (pre-rendering disabled)

### ISSUE THREAD

**Issue by mrlife** [dotnet/aspnetcore#53804]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

A scoped service is instantiated twice in an app with an interactive server render mode and no pre-rendering.

In my project, a razor component sets a value in the scoped service after the scoped service is instantiated the first time, but then it is instantiated again, causing the value to be lost.

### Expected Behavior

A scoped service should be instantiated once when pre-rendering is disabled.

### Steps To Reproduce

Please see the linked project. With a breakpoint in the `TestService` constructor, notice the breakpoint is hit twice due to the injection of the service in `_Imports.razor`.

https://github.com/mrlife/BlazorServiceInstantiation

### .NET Version

8.0.101

### Anything else?

.NET SDK:
 Version:           8.0.101
 Commit:            6eceda187b
 Workload version:  8.0.100-manifests.69afb982

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  14.3
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/8.0.101/

.NET workloads installed:
 Workload version: 8.0.100-manifests.69afb982
 [maui]
   Installation Source: SDK 8.0.100
   Manifest Version:    8.0.3/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.sdk.maui/8.0.3/WorkloadManifest.json
   Install Type:        FileBased

Host:
  Version:      8.0.1
  Architecture: arm64
  Commit:       bf5e279d92

.NET SDKs installed:
  7.0.311 [/usr/local/share/dotnet/sdk]
  7.0.312 [/usr/local/share/dotnet/sdk]
  8.0.100 [/usr/local/share/dotnet/sdk]
  8.0.101 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.14 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.15 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.14 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.15 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

**Comment by davidalexandru11** [comment]
Hello [mrlife](https://github.com/mrlife)

I have the same problem...

Every time I use QuickGrid in my razor component it is initialized 2 times.

My itemsprovider is used in the following way: 

`itemsProviderTestModel1 = async request =>
{
    await Task.Delay(200);
    var result = await TestRepo.GetTestModelListGrid(request, 50, filteredName, "", filteredAge);
    CountTestModel1 = result.Items.Count;
    
    return result;
};`

I tried different methods to avoid this, but without success...

But I noticed that the problem persists only when pagination or virtualisation is used.

I also discovered that when I use pagination and I want, for example, to press a button that, for example, opens a modal, itemsprovider it is fired even though the button is outside the Quickgrid component.

**Comment by mrlife** [comment]
@davidalexandru11, do you have pre-rendering disabled at the app level?

**Comment by davidalexandru11** [comment]
[mrlife](https://github.com/mrlife) Yes

**Comment by mrlife** [comment]
@mkArtakMSFT Hi, I noticed the bot mislabeled this issue. Is there a way for the issue creator to set or suggest the correct label ([`area-blazor`](https://github.com/dotnet/aspnetcore/labels/area-blazor))?

**Comment by javiercn** [comment]
@mrlife thanks for contacting us.

This is by design. You have the `@inject` directive applied in _Imports.razor, which will inject it in all components on the folder hierachy, this includes the App.razor component (which always renders statically) and well as your pages

**Comment by mrlife** [comment]
Thanks, @javiercn.

For the root issue below, is there a way to access the second created scoped service in a razor component's `OnInitialized()`?

> In my project, a razor component sets a value in the scoped service after the scoped service is instantiated the first time, but then it is instantiated again, causing the value to be lost.

Is the only workaround to `@inject` into each razor component instead of in `_Imports.razor`?

**Comment by bytes00134** [comment]
Hi,

i have the same problem @mrlife -> pagination redners twice.
But i have no idea how to solve this.

> This is by design. You have the @inject directive applied in _Imports.razor, which will inject it in all components on the folder hierachy, this includes the App.razor component (which always renders statically) and well as your pages

Is there any example here for help?

**Comment by nerd-wp** [comment]
This helped me for Microsoft documentation:

Service injection via a top-level imports file (_Imports.razor)
This section only applies to Blazor Web Apps.

A top-level imports file in the Components folder (Components/_Imports.razor) injects its references into all of the components in the folder hierarchy, which includes the App component (App.razor). The App component is always rendered statically even if [prerendering](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/render-modes?view=aspnetcore-9.0#prerendering) of a page component is disabled. Therefore, injecting services via the top-level imports file results in resolving two instances of the service in page components.

To address this scenario, inject the service in a new imports file placed in the Pages folder (Components/Pages/_Imports.razor). From that location, the service is only resolved once in page components.
