### ISSUE TITLE
How to generate OpenApi-docs with required body parameter?

### ISSUE THREAD

**Issue by Robelind** [dotnet/aspnetcore#53813]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Having a controller method accepting a body, such as:
```
[HttpPost]
public IActionResult Post(Test test)

```
yields OpenApi-doc containing:
```
"requestBody": {
  "x-name": "test",
  "content": {
      "application/json": {
          "schema": {
              "nullable": true,
              "oneOf": [
                  {
                      "$ref": "#/components/schemas/Test"
                  }
              ]
          }
      }
  },
  "x-position": 1
}
```
How do you achieve output where the body parameter is required, i.e.:
```
"requestBody": {
    "x-name": "test",
    "content": {
        "application/json": {
            "schema": {
               "$ref": "#/components/schemas/Test"
            }
        }
    },
    "x-position": 1
}
```

### .NET Version

8.0.101

### Anything else?

.NET SDK:
 Version:           8.0.101
 Commit:            6eceda187b
 Workload version:  8.0.100-manifests.30fce108

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\PROGRAM FILES\DOTNET\sdk\8.0.101\

.NET workloads installed:
 Workload version: 8.0.100-manifests.30fce108
 [maui-windows]
   Installation Source: VS 17.8.34525.116
   Manifest Version:    8.0.3/8.0.100
   Manifest Path:       C:\PROGRAM FILES\DOTNET\sdk-manifests\8.0.100\microsoft.net.sdk.maui\8.0.3\WorkloadManifest.json
   Install Type:              Msi

 [maccatalyst]
   Installation Source: VS 17.8.34525.116
   Manifest Version:    17.2.8004/8.0.100
   Manifest Path:       C:\PROGRAM FILES\DOTNET\sdk-manifests\8.0.100\microsoft.net.sdk.maccatalyst\17.2.8004\WorkloadManifest.json
   Install Type:              Msi

 [ios]
   Installation Source: VS 17.8.34525.116
   Manifest Version:    17.2.8004/8.0.100
   Manifest Path:       C:\PROGRAM FILES\DOTNET\sdk-manifests\8.0.100\microsoft.net.sdk.ios\17.2.8004\WorkloadManifest.json
   Install Type:              Msi

 [android]
   Installation Source: VS 17.8.34525.116
   Manifest Version:    34.0.43/8.0.100
   Manifest Path:       C:\PROGRAM FILES\DOTNET\sdk-manifests\8.0.100\microsoft.net.sdk.android\34.0.43\WorkloadManifest.json
   Install Type:              Msi

Host:
  Version:      8.0.1
  Architecture: x64
  Commit:       bf5e279d92

.NET SDKs installed:
  3.1.426 [C:\PROGRAM FILES\DOTNET\sdk]
  8.0.100-rc.2.23502.2 [C:\PROGRAM FILES\DOTNET\sdk]
  8.0.101 [C:\PROGRAM FILES\DOTNET\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.27 [C:\PROGRAM FILES\DOTNET\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.29 [C:\PROGRAM FILES\DOTNET\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.31 [C:\PROGRAM FILES\DOTNET\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.32 [C:\PROGRAM FILES\DOTNET\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.26 [C:\PROGRAM FILES\DOTNET\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.15 [C:\PROGRAM FILES\DOTNET\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-rc.2.23480.2 [C:\PROGRAM FILES\DOTNET\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.1 [C:\PROGRAM FILES\DOTNET\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.27 [C:\PROGRAM FILES\DOTNET\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.29 [C:\PROGRAM FILES\DOTNET\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.31 [C:\PROGRAM FILES\DOTNET\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\PROGRAM FILES\DOTNET\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\PROGRAM FILES\DOTNET\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.26 [C:\PROGRAM FILES\DOTNET\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.15 [C:\PROGRAM FILES\DOTNET\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-rc.2.23479.6 [C:\PROGRAM FILES\DOTNET\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.1 [C:\PROGRAM FILES\DOTNET\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.27 [C:\PROGRAM FILES\DOTNET\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.29 [C:\PROGRAM FILES\DOTNET\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.31 [C:\PROGRAM FILES\DOTNET\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\PROGRAM FILES\DOTNET\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\PROGRAM FILES\DOTNET\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.26 [C:\PROGRAM FILES\DOTNET\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.15 [C:\PROGRAM FILES\DOTNET\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-rc.2.23479.10 [C:\PROGRAM FILES\DOTNET\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.1 [C:\PROGRAM FILES\DOTNET\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

**Comment by garrettlondon1** [comment]
Have you tried the [Required] data annotation on your Test model?

```
[Required]
public string Property { get; set; }
```

**Comment by Robelind** [comment]
> Have you tried the [Required] data annotation on your Test model?
> 
> ```
> [Required]
> public string Property { get; set; }
> ```

That works fine for properties within the model, but what I want is that the model parameter itself should be required.
I want the docs reflecting that you can't do (pseudo code): `Post(null)`

**Comment by captainsafia** [comment]
@Robelind What package are you using for your OpenAPI integration? You may be able to use Swashbuckle's `RequestBody` attribute or NSwag's config to support this.

**Comment by Robelind** [comment]
I'm using NSwag and I'm hoping to be able to use its config for this, but I would need some guidance on how to do it.

**Comment by captainsafia** [comment]
Apologies for the delay on this! Finally catching up with some issue triage 😅 

Moving forward, we plan on adding built-in support for OpenAPI document generation to ASP.NET Core (see https://github.com/dotnet/aspnetcore/issues/54599). The built-in support correctly handles generating the required annotations for non-nullable body parameters

As for this particular inquiry, I'd recommend filing a bug on the NSwag repo with this question.
