### ISSUE TITLE
Can't sent byte[] from the client to the SignalR hub

### ISSUE THREAD

**Issue by jaywork2020** [dotnet/aspnetcore#53824]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Unable to send byte[] from a client using jacvascript to the SignalR hub.

Here is the javascript code that does the recording and then when the `sendButton` is called, the byte array is send to the signalR hub using the `upload` function.

```javascript
const connection = new signalR.HubConnectionBuilder().withUrl("/hub").build();

let audioRecorder;
let data = [];

navigator.mediaDevices.getUserMedia({ audio: true })
    .then(stream => {

        audioRecorder = new MediaRecorder(stream);

        audioRecorder.addEventListener('dataavailable', e => {
            data.push(e.data);
        });

        startButton.addEventListener('click', () => {
            audioRecorder.start();
        });

        stopButton.addEventListener('click', () => {
            audioRecorder.stop();
        });

        sendButton.addEventListener('click', async () => {

            const blobObj = new Blob(audioChunks, { type: 'audio/webm' });

            var bytes = await blobObj.arrayBuffer();

            const subject = new signalR.Subject();
            subject.next(bytes)
            connection.invoke('upload', 'filename', subject);
            subject.complete();
        });
    })
```

The SignalR hub I added this code

```c#
public async Task Send(string filename, IAsyncEnumerable<byte> stream)
{
    using var memoryStream = new MemoryStream();

    await foreach (var item in stream)
    {
        memoryStream.WriteByte(item);
    }
}
```

But nothing is being sent. 

I tried to use `byte[]`, `IList<byte>` and `ArrayList` instead like this 

```
    public Task Upload(string filename, IList<byte> stream)
    {
        using var memoryStream = new MemoryStream();

        return Task.CompletedTask;
    }
```

But that throws  a Javascript error in the console.

> Error: Failed to invoke 'Upload' due to an error on the server. InvalidDataException: Error binding arguments. Make sure that the types of the provided values match the types of the hub method being invoked.

### Expected Behavior

I am expecting sending a subject with a byte array will send the byte[] to the stream property. The Send function gets called, but the stream is always empty.

```c#
public async Task Send(string filename, IAsyncEnumerable<byte> stream)
{
    using var memoryStream = new MemoryStream();

    await foreach (var item in stream)
    {
        memoryStream.WriteByte(item);
    }
}
```

### Exceptions (if any)

Error: Failed to invoke 'Upload' due to an error on the server. InvalidDataException: Error binding arguments. Make sure that the types of the provided values match the types of the hub method being invoked.

### .NET Version

8.0.101

**Comment by BrennanConroy** [comment]
Look at a network trace to see what data is being sent
https://learn.microsoft.com/aspnet/core/signalr/diagnostics?view=aspnetcore-8.0#network-traces

Your code doesn't work as is, it's referring to an `audioChunks` variable but the sound is being put into `data`.

**Comment by jaywork2020** [comment]
@BrennanConroy that is a copy/paste typo. But you are right the right value to use is `data`

Attached is a copy of the network

[localhost_test.har.json](https://github.com/dotnet/aspnetcore/files/14172950/localhost_test.har.json)

**Comment by BrennanConroy** [comment]
That didn't preserve the websocket messages. Try using Chrome or Edge instead?

**Comment by BrennanConroy** [comment]
Move `subject.next(bytes)` below `connection.invoke('upload', 'filename', subject);`
You're also sending a stream of `byte[]`s so change the hub method to `public async Task Send(string filename, IAsyncEnumerable<byte[]> stream)`
And finally, you likely need to base64 encode the byte[] from `await blobObj.arrayBuffer()` since json doesn't support binary data.

**Comment by jaywork2020** [comment]
Thank you!
