### ISSUE TITLE
Error: System.InvalidOperationException: Method calls cannot be formatted in InputNumber & InputTextArea 

### ISSUE THREAD

**Issue by EmpiteLakshitha** [dotnet/aspnetcore#53834]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

`<InputTextArea class="form-control" @bind-Value="@Request.Model.First().Description" />` 
When I upgraded .net 6.0 to .net 8.0 this controller gives me the following exception.

![image](https://github.com/dotnet/aspnetcore/assets/70133010/ef38471a-fbc2-4753-9a38-4b75348904e2)

So I had to add **name="Description"**.

### Expected Behavior

These controllers need to work same as using blazor.server.js  

### Steps To Reproduce

just create a property as `Request.Model.First().Description ` and create a EditForm . Then try to load it

### Exceptions (if any)

![image](https://github.com/dotnet/aspnetcore/assets/70133010/99580fff-aec8-4ae7-ab21-ff7680ff1acf)

### .NET Version

.net 8

**Comment by javiercn** [comment]
@EmpiteLakshitha thanks for contacting us.

As part of SSR support all input elements need to generate a `form field` name attribute, which they do by formatting the expression passed to the component (the thing inside the `@bind` expression).

There is limited support for the expressions that we support (we don't support method calls other than indexers) so there are two things you can do:
* Provide a `Name` attribute explicitly that will be respected and will avoid generating a name.
* Set `ShouldUseFieldIdentifiers` to `false` on the EditContext for the form.
