### ISSUE TITLE
ErrorBoundary not working with Blazor App with Interactive Auto

### ISSUE THREAD

**Issue by chulla** [dotnet/aspnetcore#53840]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm trying to capture and display an error message with ErrorBoundary but it doesn't work with Blazor in Auto Interactive Mode.

**In MainLayout.razor**
```

<ErrorBoundary>
        <ChildContent>
            @Body
        </ChildContent>
        <ErrorContent>
            <p class="alert alert-danger" role="alert">
                Oh, dear! Oh, my! - George Takei
            </p>
        </ErrorContent>
    </ErrorBoundary>
```

**in Counter.razor**

```
if (currentCount > 5)
        {
            throw new InvalidOperationException("Current count is too big!");
        }
```

In the official documentation, it says that interactivity must be enabled.
[[](**https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/handle-errors?view=aspnetcore-8.0**)](https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/handle-errors?view=aspnetcore-8.0)

Here I have uploaded a repo to show that when the count reaches 5, the exception is not caught inside ErrorBoundary

[](https://github.com/chulla/TestErrorBoundaryWithInteractiveAuto/tree/master)

### Expected Behavior

The error message should be displayed in ErrorBoundary

### .NET Version

8

**Comment by chulla** [comment]
Here is a repo to reproduce the problem  --> [](https://github.com/chulla/TestErrorBoundaryWithInteractiveAuto/blob/master/BlazorAppInteractiveAuto/BlazorAppInteractiveAuto.Client/Pages/Counter.razor)

**Comment by guardrex** [comment]
@chulla ... I asked about this in an earlier issue. See if https://github.com/dotnet/aspnetcore/issues/49679 helps.

**Comment by mkArtakMSFT** [comment]
Thanks for helping out with this, @guardrex !
