### ISSUE TITLE
ClaimsPrincipal on ASP.NET Core v8.0.101  Doesn't Contain All Claims From The OpenIdConnect Token

### ISSUE THREAD

**Issue by mschaefer-gresham** [dotnet/aspnetcore#53842]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The 'email' claim is not present when attempting to do a claims transformation after upgrading to 8.0.101. In my case, I'm reading the access token sent in the header.

var email = principal.Claims.FirstOrDefault(c => c.Type == "email")?.Value;

I fixed this issue by downgrading Microsoft.AspNetCore.Authentication.JwtBearer from 8.0.101 to 7.0.15.

### Expected Behavior

email claim is present.

### Steps To Reproduce

Pass email claim in jwt token.

### .NET Version

8.0.101

### Anything else?

I am reopening issue [51538](https://github.com/dotnet/aspnetcore/issues/51538) because no one has looked at the issue and it has finally auto-closed.

Can someone please have a look at this? It's been an open issue for over 3 months without any feedback.

**Comment by mkArtakMSFT** [comment]
Closing this as we have https://github.com/dotnet/aspnetcore/issues/51538 to track it.
