### ISSUE TITLE
Intermediate MTLS certificates ignored by certificate authentication

### ISSUE THREAD

**Issue by vurhanau** [dotnet/aspnetcore#53858]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

ASP.Net Core server fails to do certificate authentication when a client sends leaf + intermediate MTLS certs.
Error:
```
warn: Microsoft.AspNetCore.Authentication.Certificate.CertificateAuthenticationHandler[2]
      Certificate validation failed, subject was OID.2.5.4.45=abc, O=someorg, C=US. PartialChain One or more certificates required to validate this certificate cannot be found.
```

Server:
```cs
builder.WebHost.UseKestrel(kestrel =>
{
    kestrel.Listen(IPAddress.Any, port, listenOptions =>
    {
        listenOptions.UseHttps(new TlsHandshakeCallbackOptions
        {
            OnConnection = ctx => ValueTask.FromResult(
                new SslServerAuthenticationOptions
                {
                    ClientCertificateRequired = true,
                    RemoteCertificateValidationCallback = (_, cert, chain, _) => MyValidationCallback(cert, chain),
                    ServerCertificateContext = SslStreamCertificateContext.Create(leafCert, intermediateCerts, true),
                }),
        });
    });
});
```

Server authentication:
```cs
builder.Services.AddAuthentication(CertificateAuthenticationDefaults.AuthenticationScheme)
                .AddCertificate(opts =>
                {
                    opts.RevocationMode = X509RevocationMode.NoCheck;
                    opts.ChainTrustValidationMode = X509ChainTrustMode.CustomRootTrust;
                    opts.CustomTrustStore = GetX509Authorities(); // add root CA, intermediate CA is not available here - client sends it
                });
```

Client:
```cs
using HttpClient http = new(new SocketsHttpHandler()
{
    SslOptions = new SslClientAuthenticationOptions
    {
        RemoteCertificateValidationCallback = (_, cert, chain, _) => MyClientValidationCallback(cert, chain),
        ClientCertificateContext = SslStreamCertificateContext.Create(clientLeafCert, intermediateClientCerts, true),
    },
});
```

`Microsoft.AspNetCore.Authentication.Certificate` version is `8.0.1`

### Expected Behavior

Intermediate X509 client certs should be added to X509 chain to construct a proper CA chain.
Certificate authentication handler should validate client X509 leaf certificate successfully when all CA certs in the chain.

### .NET Version

8.0.100

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Have you tried this: https://github.com/dotnet/aspnetcore/issues/48099 ?
If that doesn't help, please generate some test certificates and build a minimal repro project utilizing those certs and provide it so that we can investigate this.

**Comment by vurhanau** [comment]
Re-opening this issue with a simple project to demonstrate the issue: https://github.com/vurhanau/aspnetcore-certchain

[CertificateAuthenticationHandler.BuildChain()](https://github.com/dotnet/aspnetcore/blob/d7130a2c5a99147005744969aab7f837c82659d5/src/Security/Authentication/Certificate/src/CertificateAuthenticationHandler.cs#L187) method ignores certificate chain sent by the client.
There are cases when intermediate CA certificate is sent by the client and this certificate is not known by the server ahead of time.
