### ISSUE TITLE
Ignore issue comments starting with "Looks like this PR hasn't been active for some time..." 

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/aspnetcore#53859]
Hello all,

We've recently switched to a new automation service for managing PRs and Issues, and hit a bug where a PR-only task accidentally applied to issues. If you see a comment with the following text on any of your issues, please ignore it while we work on cleaning things up:

> Looks like this PR hasn't been active for some time and the codebase could have been changed in the meantime.
To make sure no conflicting changes have occurred, please rerun validation before merging. You can do this by leaving an /azp run comment here (requires commit rights), or by simply closing and reopening.

Sorry for the noise!

**Comment by adityamandaleeka** [comment]
Looks like this PR hasn't been active for some time...


jk 😆

**Comment by wtgodbe** [comment]
This is resolved

**Comment by etriebe** [comment]
I see this is closed but what .net version can we expect this to be fixed in?
