### ISSUE TITLE
Invalid Anti-Forgery Token on OIDC Response

### ISSUE THREAD

**Issue by M4SX5** [dotnet/aspnetcore#53868]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I upgraded my application from .NET 7 Blazor Server App to an .NET 9 Blazor Web App. Everything is working fine. I also added an OIDC provider (Keycloak) as an authentication source to the new Blazor Web App. Redirecting to the login page works, logging in an redirecting back works as well.

Only then I get an error that the antiforgery-token is missing. I found a [related post](https://github.com/dotnet/AspNetCore.Docs/issues/31082) but the solution there is not working for me. 

I copied the code:

```
builder.Services.AddAuthentication(options =>
    {
        options.DefaultScheme = IdentityConstants.ApplicationScheme;
        options.DefaultSignInScheme = IdentityConstants.ExternalScheme;
    }).AddOpenIdConnect(OpenIdConnectDefaults.AuthenticationScheme, opt =>
    {
        opt.Authority = "https://openid.foo/realms/master";
        opt.ClientId = "FooDev";
        opt.Scope.Add("openid");
        opt.Scope.Add("profile");
        opt.Scope.Add("roles");
        opt.Scope.Add("offline_access");
        opt.SaveTokens = true;
        opt.ResponseType = "code";

        opt.Events.OnRedirectToIdentityProvider = async n =>
        {
            n.ProtocolMessage.RedirectUri = "https://foo/signin-oidc";
            await Task.FromResult(0);
        };
    })
    .AddIdentityCookies();
```

but it is still not working. I replaced https://foo/signin-oidc with my local address https://localhost:7031/signin-oidc but nothing is changing.

As I searched through the comments the documentation is not finished yet. Could you help me solve the issue or do you have a source where I can get some further information.

Any advice is much appreciated.

### Expected Behavior

I get logged in as before and don't get an Error message

### Exceptions (if any)

```
An unhandled exception occurred while processing the request.
InvalidOperationException: This form is being accessed with an invalid anti-forgery token. Validate the `IAntiforgeryValidationFeature` on the request before reading from the form.
Microsoft.AspNetCore.Http.Features.FormFeature.HandleUncheckedAntiforgeryValidationFeature()

AuthenticationFailureException: An error was encountered while handling the remote login.
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler<TOptions>.HandleRequestAsync()
```

### .NET Version

.NET 8.0

### Anything else?

cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/pull/31555

**Comment by M4SX5** [comment]
No, this line is included. I set up a new Blazor Web App and just copied the needed files into the new project. So everything is working, except of the authentication process because Keycloak is posting some data to the "signin-oidc" endpoint and there is no CSRF Token send from Keycloak to my application and therefor the error " This form is being accessed with an invalid anti-forgery token" is thrown.

**Comment by M4SX5** [comment]
I found a solution to my problem. My order of the middleware was wrong. The antiforgery middleware must come AFTER the authentication middleware.

@damienbod Thanks for sharing your code.

```
  app.UseHttpsRedirection();
  app.UseStaticFiles();
  app.UseRouting();
  app.UseAuthentication();
  app.UseAuthorization();
  app.UseAntiforgery();
  app.MapRazorComponents<App>().AddInteractiveServerRenderMode();
```

**Comment by guardrex** [comment]
We have it that way in the sample apps that will go with the new BWA+OIDC article, so we have it covered by example.
