### ISSUE TITLE
ASPNET Core 8.0 Identity Facebook External Provider Integration does not work. "The oauth state was missing or invalid."

### ISSUE THREAD

**Issue by acochavosdi** [dotnet/aspnetcore#53878]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The ASP NET Identity Individual Accounts external login Facebook provider is not working.

# Context
After following every step from the [official guide ](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/social/facebook-logins?view=aspnetcore-8.0) the integration does not work.

## Exception
The raw exception after trying to login with facebook is this one <br>

_`Microsoft.AspNetCore.Authentication.AuthenticationFailureException: An error was encountered while handling the remote login.
 ---> Microsoft.AspNetCore.Authentication.AuthenticationFailureException: The oauth state was missing or invalid.
 --- End of inner exception stack trace ---
 at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler1.HandleRequestAsync() 
 at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
 at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)`_

## Application 
Application has been created from scratch template ASP NET Core MVC.
Only added NuGet. + this lines on program.cs + the secrets well configured on appsettings.json

![image](https://github.com/dotnet/aspnetcore/assets/34022571/e8246e21-9b09-4f79-9753-432af7d51fde)
![image](https://github.com/dotnet/aspnetcore/assets/34022571/021adf5e-15da-43a8-9529-7137bdfa74d8)
![image](https://github.com/dotnet/aspnetcore/assets/34022571/0a44d5db-6d30-4759-a033-7f5bdc1d2186)

### Related dotnet issue -> Not Solved
There was another issue that was closed without resolution because people thought the integration didn't work for an SPA Angular, but its not working for regular ASP NET Core MVC Clean Template. It was this one. 
https://github.com/dotnet/aspnetcore/issues/52836 

## Possible Resolution & Investigation
There is a weird thing happening after trying to login on facebook.
The clue was here ->  https://community.auth0.com/t/facebook-login-fails-with-invalid-state-error/112930/6
![image](https://github.com/dotnet/aspnetcore/assets/34022571/f2e48a72-47f1-4af9-8656-ca707fe3e4a2) <br>
It seems that Facebook provider is adding some extra stuff to the callback (a suffix), but its not easily seen during the flow. I found it while trying to figure it out on different places from the internet.
You will not see it here but in next step.
![image](https://github.com/dotnet/aspnetcore/assets/34022571/e597d150-b026-4e03-9ac1-9ed507920bf3)
![image](https://github.com/dotnet/aspnetcore/assets/34022571/e14a69a0-48b4-4996-8376-ce0a25266a9a)
As we can see, there is a state on the callback, and no suffix in it ... BUT!!
When we click on Accept and application is returned back to Identity/account/login ...
![image](https://github.com/dotnet/aspnetcore/assets/34022571/c414eaec-9699-4052-93a3-960ddab067af)
As it was suggested in the post with the clue, the state is probably adding that extra suffix and when its processed it fails.

I guess then that .../signin-facebook endpoint should handle this extrasuffix while processing the state.

### Expected Behavior

Login properly using external provider.

### Steps To Reproduce

Explained on description! 
It is pretty easy to replicate!

### Exceptions (if any)

Microsoft.AspNetCore.Authentication.AuthenticationFailureException: An error was encountered while handling the remote login.

 ---> Microsoft.AspNetCore.Authentication.AuthenticationFailureException: The oauth state was missing or invalid.

   --- End of inner exception stack trace ---

   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()

   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)

   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

### .NET Version

8.0.101

**Comment by acochavosdi** [comment]
I made a mistake while Copy/Paste from other solution, the AddAuthentication is like this (the change is the Redirection Uri)
![image](https://github.com/dotnet/aspnetcore/assets/34022571/764e82bf-4f45-468f-91ed-d7786d002738)

**Comment by Tratcher** [comment]
That #_=_ suffix is only on the client/browser, it doesn't send url fragments to the server so it shouldn't affect anything here. More likely this is a cookie issue. Capture a Fiddler trace and make sure all of the cookies added by aspnet on the initial challenge are returned to the callback.

**Comment by acochavosdi** [comment]
I'll try to do what u suggested (after understand it :D), but please take a look into this to check if the fragment thing is possible, the guy seems to fixed it manually for MAUI

https://community.auth0.com/t/facebook-login-fails-with-invalid-state-error/112930/6

**Comment by mkArtakMSFT** [comment]
Checking the fragment will require JavaScript, which is usually meant to be used for a SPA scenario. We definitely don't plan to implement support for this on the server.
