### ISSUE TITLE
Blazor enhanced navigation "before" javascript event

### ISSUE THREAD

**Issue by Markz878** [dotnet/aspnetcore#53887]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I have a situation where I want to modify some page elements with javascript after an enhanced navigation, and I need some way to store the state of those elements in the page before the navigation, so that I know what to do after it.

### Describe the solution you'd like

There is a blazor event "enhancedload" that occurs after the enhanced navigation. I would ask that you also add a "beforeenhancedload" event.

### Additional context

Also, the documentation related to this "https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/static-server-rendering?view=aspnetcore-8.0" is super confusing, why is there a RCL required for the PageScript component? Could someone go through this and think how a beginner should be guided through this process. Or just add the BlazorPageScript package by @MackinnonBuck to Blazor directly.

**Comment by MackinnonBuck** [comment]
Done as part of #57131:
* Added an `enhancednavigationstart` event that fires before any changes have applied to the page
* Added an `enhancednavigationend` event that fires after all changes have finished applying (including streaming updates)
