### ISSUE TITLE
Blazor Inputs can't bind to variables that start with ÅÄÖ when upgrading to .net 8

### ISSUE THREAD

**Issue by poserdonut** [dotnet/aspnetcore#53891]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We upgrade one of our blazor wasm sites to .net 8. After that we get a issue with our inputs binding to variables that start with the letter Å Ä or Ö. 

E.g.  this doesn't work
`<div class="col-md-4"><InputText class="form-control" @bind-Value="@ÖvrigAnställning.Ort" /></div>`

This works (yes, you can have ä in the variable name, but not as a starting letter).
`<div class="col-md-4"><InputText class="form-control" @bind-Value="@OvrigAnställning.Ort" /></div>`

We get this error in the console:
![image](https://github.com/dotnet/aspnetcore/assets/61051475/f506a7bd-e7e3-4152-af08-c98792304acf)

### Steps To Reproduce

Here's a minimal repro of the issue
https://github.com/poserdonut/BlazorInputBug

### .NET Version

8.0.101

**Comment by javiercn** [comment]
@poserdonut thanks for contacting us.

This seems related to https://github.com/dotnet/aspnetcore/issues/52755 and fixed by https://github.com/dotnet/aspnetcore/pull/53874 which we are backporting (pending aproval) https://github.com/dotnet/aspnetcore/pull/53892

**Comment by javiercn** [comment]
https://github.com/dotnet/aspnetcore/pull/53874
