### ISSUE TITLE
a second operation was started on this context

### ISSUE THREAD

**Issue by MahdiElahi** [dotnet/aspnetcore#53910]
Hi

in Books.razor Component , this is my [Adaptor.cs](https://github.com/MahdiElahi/GridSynf/blob/main/BooksAdaptor.cs) , [Books.razor](https://github.com/MahdiElahi/GridSynf/blob/main/Books.razor) ,  [Service ](https://github.com/MahdiElahi/GridSynf/blob/main/BookService.cs)and [Repository](https://github.com/MahdiElahi/GridSynf/blob/main/BookRepository.cs)
my problem is when i Update a record in Edit.razor when the record is updated i navigate to books.razor

but when **navigate** to books.razor , 
it's get book Status On **OnInitializedAsync** then go to Adaptor to get the grid data in repository when but request to database it's show this error :
a second operation was started on this context instance before a previous operation completed. this is usually caused by different threads concurrently using the same instance of dbcontext. for more information on how to avoid threading issues with dbcontext

1.i check the async / await 
2.change program.cs to : 

builder.Services.AddDbContext<ApplicationDbContext>(options => options.UseSqlServer(connectionString),ServiceLifetime.Transient);

 and then change again to and test it 

builder.Services.AddDbContext<ApplicationDbContext>(options => options.UseSqlServer(connectionString),ServiceLifetime.Scoped);

but it's not worked and show error again

**_Note : When i Remove these codes in books.razor it's worked_**

```
   ScrambleStatus = await scrambleService.GetStatus();
   ScrambleStatus.Insert(0, "All");
   SelectedStatus = ScrambleStatus.First(); Copy

```

is problem on my call async / await ?
what's problem ?

**Comment by javiercn** [comment]
@MahdiElahi thanks for contacting us.

What's happening is that you are trying to run two Db operations simultaneously, which I believe is not supported by EF. You need to instead switch to use `DbContextFactory` and create a DbContext instance per operation https://github.com/MahdiElahi/GridSynf/blob/main/BookRepository.cs#L6

You might also benefit from using OwningComponentBase, as there might be two separate components in your app trying to reuse the same EF DbContext which will also cause this issue.
