### ISSUE TITLE
.NET Blazor - two way data binding with handler method in parent component issue

### ISSUE THREAD

**Issue by BachiMjavanadze** [dotnet/aspnetcore#53914]
I try to implement two way data binding in `Blazor` (`.Net 8`). According to documentation, new way of implementing it is [@bind:get/@bind:set][1]. This is my solution, it works perfectly:

[![enter image description here][2]][2]

    @* Components\Pages\Home.razor *@
    @page "/"
    @rendermode InteractiveServer
     
    <h4>Home component</h4>
    <About @bind-Age="age"  />
     
    @code {
      private int age = 5;
    }
    
    @* Components\Pages\About.razor *@
    <h4>About component</h4>
     
    <input type="number" @bind:get="Age" @bind:set="OnAgeChanged" />
    <h2>Age: @Age</h2>
     
    @code {
      [Parameter]
      public int Age { get; set; }
     
      [Parameter]
      public EventCallback<int> AgeChanged { get; set; }
     
      private async Task OnAgeChanged(int value)
      {
        if (value > 0 && value < 110)
          Age = value;
     
        await AgeChanged.InvokeAsync(Age);
      }
    }

now I want to define handler method (`OnAgeChanged()`) in `Home.razor` component (not in `About.razor`) and I did not succeed. this is my buggy solution (`age` does not change. remains 5):

    @* Components\Pages\Home.razor *@
    @page "/"
    @rendermode InteractiveServer
    
    <h4>Home component</h4>
    <About @bind-Age="age" />
    
    @code {
      private int age = 5;
    
      private async Task OnAgeChanged(int value)
      {
        if (value > 0 && value < 110)
          age = value;
      }
    }
        
    @* Components\Pages\About.razor *@
    <h4>About component</h4>
    
    <input type="number" @bind:get="Age" @bind:set="InvokeParentMethod" />
    <h2>Age: @Age</h2>
    
    @code {
      [Parameter]
      public int Age { get; set; }
    
      [Parameter]
      public EventCallback<int> AgeChanged { get; set; }
    
      private async Task InvokeParentMethod(int value)
      {
        await AgeChanged.InvokeAsync(Age);
      }
    }

seams it is impossible to achieve it with `@bind:get/@bind:set` so please write about it in documentation.

  [1]: https://learn.microsoft.com/en-us/aspnet/core/blazor/components/data-binding?view=aspnetcore-8.0#use-bindgetbindset-modifiers-and-avoid-event-handlers-for-two-way-data-binding
  [2]: https://i.stack.imgur.com/NnVOp.png

**Comment by MariovanZeist** [comment]
Hi @BachiMjavanadze 
The reason Age isn't updating is because of a typo in your code,

```cs
private async Task InvokeParentMethod(int value)
  {
    //await AgeChanged.InvokeAsync(Age);  //This is incorrect, and will pass 5 to your parent component
    await AgeChanged.InvokeAsync(value);   //This will correctly pass the new value to your parent component
  }
```

You are passing the original Age value, not the new value to your parent component so the Age stays on 5.

**Comment by BachiMjavanadze** [comment]
@MariovanZeist 

thanks for answer but actually it does not works; I am able to enter more than 110, restriction [0-110] does not works.

**Comment by BachiMjavanadze** [comment]
> Please share with us in a public GitHub repo 

Here is a repo with two projects: working (good) and not working (bad). I created projects with the `ASP.NET Core Empty` template and just add the required `Blazor` code, but the same result occurs when I create a project with the `Blazor Web App` template.

[https://github.com/BachiMjavanadze/Blazor-Issue](https://github.com/BachiMjavanadze/Blazor-Issue)

**Comment by MariovanZeist** [comment]
@BachiMjavanadze I see your issue.
in your ``home.razor`` file you configure the about component as
```razor
<About @bind-Age="age" />
```

In that case ``blazor`` will generate the binding for you, creating the getter and creating the setter internally
The function ``Task OnAgeChanged(int value)`` won't be called in that case, so your validation code isn't called.

If you want to call additional code to for example validate the input there you could add a function that will be called after the internal setter sets the age value by setting ``@bind-Age:after``
like so:
```razor
<About @bind-Age="age" @bind-Age:after=ValidateValue />

@code {
    private int age { get; set; } = 5;

    private void ValidateValue()
    {
        if (age <0)
        {
            age = 0;
        }
        if (age >=110)
        {
            age = 110;
        }
  }
```

**Comment by BachiMjavanadze** [comment]
@MariovanZeist 
Thanks for your answer, the issue can be closed but  I want to note that it’s a little uncomfortable that you have to change the body of the method. It’s better, of course, to have 100% compatibility and portability of code from the parent component to the child component and vice versa.

Anyway, thank you very much!
