### ISSUE TITLE
Use the updated HubConnection builder pattern in all the clients

### ISSUE THREAD

**Issue by mikaelm12** [dotnet/aspnetcore#5392]
In the Java client we introduced a new `HubConnection` builder pattern where `HubConnectionBuilder` was an abstract base class for builder implementations. The most common of which being the `HttpHubConnection` builder.
https://github.com/aspnet/SignalR/blob/c852bdcc332ffb998ec6a5b226e35d5e74d24009/clients/java/signalr/src/main/java/com/microsoft/signalr/HubConnectionBuilder.java#L16-L21

We should use this pattern across the different clients.

**Comment by davidfowl** [comment]
Not worth it. Closing
