### ISSUE TITLE
High memory usage on an idle web app

### ISSUE THREAD

**Issue by georgiosd** [dotnet/aspnetcore#53933]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We are seeing high memory usage on fairly idle web apps (2-3 users, dev environment).

On a fresh start, mem usage is ~250MB.
After some time (I haven't figured out yet how long this takes), the usage climbs to 2-4GB.

These apps are hosted on a cluster of Debian 11 servers.

### Expected Behavior

I would have expected than an idle app stays well below 500MB of memory usage.

### .NET Version

6.0.26

**Comment by gfoidl** [comment]
Can you share some more information about the app and the infrastructure to make the issue actionable?
Ideally with a self-containing repro.

Did you try [dotnet-counters](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-counters) to see if GCs are happening or not?

**Comment by georgiosd** [comment]
Hey @gfoidl thanks for picking this up on a Saturday!

I don't think I can provide a repro since I have no idea what could be causing this and the whole app won't exactly be minimal.

It's a "standard" ASP.NET app with several controllers, health checks etc. 
A couple of long running tasks running as hosted services. 
Nothing fancy like image processing or anything like that.

I've isolated the app in another box so I can install the SDK. Is this the command I should be using to collect counters?

```
dotnet-counters collect --process-id <pid> --refresh-interval 3 --format csv
```

**Comment by gfoidl** [comment]
[Debug a memory leak in .NET](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/debug-memory-leak) is a tutorial for (one way of) investigating such issue. Please give this a try, and also have a look at `dotnet-trace`.

I'd run just `dotnet-counters monitor` (with the process id or process name, of course) for a couple of minutes to see if a GC is happening or not. If no GC is done, then it may be normal GC-behavior as there was no reason to trigger one (e.g. enough memory available, etc.). If there are GCs happening, then it may be a leak which you can investigate via the other options provides in the linked tutorial.

When you have troubles investigating a memory dump we can help out (but it's always hard when one doesn't know the app).

For more in-depth infos about GC and it's investigations see https://github.com/Maoni0/mem-doc

> there is a LB that hits the health check every second or so

Can you run the app without the LB probing the health -- just to try to exclude a potential reason.
Also if you can run the app on Windows and see the same behavior maybe it's worth running the app under _PerfView_ to get more insights whats going on.

**Comment by georgiosd** [comment]
Okay, I'll see if I can replicate the issue locally and go from there.

**Comment by georgiosd** [comment]
Still on this. Will revert with my findings.

**Comment by georgiosd** [comment]
Closing this as I've failed to work on it for a few months. Will reopen if I get any evidence.
