### ISSUE TITLE
DataProtectorTokenProvider constructor with ILogger

### ISSUE THREAD

**Issue by rwb196884** [dotnet/aspnetcore#53963]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

DataProtectorTokenProvider<PrestwoodIdentityUser> does not contain a constructor that takes 3 arguments	

### Steps To Reproduce

```    public class CustomTokenProvider : DataProtectorTokenProvider<CustomIdentityUser>
    {
        public CustomTokenProvider (IDataProtectionProvider dataProtectionProvider,
            IOptions<CustomTokenProviderOptions> options,
            ILogger<CustomTokenProvider> logger
            )
           : base(dataProtectionProvider, options, logger) { }
    }
```
In a DLL that has
```
<PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.1.39" />
```
this does not work because 
> `DataProtectorTokenProvider<PrestwoodIdentityUser> does not contain a constructor that takes 3 arguments	`

However, if I copy the same code into my identity server projet then it works, but then `DataProtectorTokenProvider` seems to come from
`...AppData\Local\SourceServer\23d86a44e25e59750491d8e67db755964fc6d135e15ec1fd19909dfb9b8999a7\DataProtectorTokenProvider.cs`

If I omit the `ILogger` parameter so that the code builds then I get a runtime exdception:
> `MissingMethodException: Method not found: 'Void Microsoft.AspNetCore.Identity.DataProtectorTokenProvider`1..ctor(Microsoft.AspNetCore.DataProtection.IDataProtectionProvider, Microsoft.Extensions.Options.IOptions`1<Microsoft.AspNetCore.Identity.DataProtectionTokenProviderOptions>)'.`

What's going on?!

### .NET Version

dotnet --version

**Comment by martincostello** [comment]
Can you provide all of the dependencies your app is using - looking at the issue, my guess would be that you have one part of the app using something compiled against version 2.1.39, and then another part of the app using packages from a version of ASP.NET Core 3.1 or later where the API signature was changed, and now the two parts are incompatible with each other.

**Comment by rwb196884** [comment]
Yeah, definiely looks like something is somehow using a wrong version. But there can't be any 3.1 because I'm using 6 and 7.

**Comment by martincostello** [comment]
There's no newer packages because Identity became part of the ASP.NET Core shared framework, so it's included in Microsoft.AspNetCore.App. Try removing the reference to the 2.1 package entirely.
