### ISSUE TITLE
AddDataProtection().SetApplicationName does not allow one project to read values set by another

### ISSUE THREAD

**Issue by rwb196884** [dotnet/aspnetcore#53987]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

AddDataProtection().SetApplicationName does not allow tokens to be shared across projects.

### Expected Behavior

A token generated by the `UserManager` running in one project can be used by the same `UserManager` running in another project.

### Steps To Reproduce

The documentation at
  https://learn.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-8.0#per-application-isolation
states:
> When app isolation is disabled, all apps backed by the same keying material can share payloads as long as they provide the appropriate [purposes](https://learn.microsoft.com/en-us/aspnet/core/security/data-protection/consumer-apis/purpose-strings?view=aspnetcore-8.0). To provide app isolation in this environment, call the [SetApplicationName](https://learn.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-8.0#setapplicationname) method on the configuration object and provide a unique name for each app.

Therefore if I use the same value in two different project then they should both be able to validate codes generated in the other. However, this is not so.

### .NET Version

8.0.100

**Comment by Tratcher** [comment]
Are the apps also sharing their encryption keys?
