### ISSUE TITLE
TicketSerializer deserialized authentication ticket does not match the serialized one.

### ISSUE THREAD

**Issue by daphneSot** [dotnet/aspnetcore#53998]
### Discussed in https://github.com/dotnet/aspnetcore/discussions/53991

<div type='discussions-op-text'>

<sup>Originally posted by **daphneSot** February 13, 2024</sup>
Hello,

I am using dotnet core 6, and when i use the TicketSerialize to serialize and deserialize a ticket, some information seems to be lost.

var ticketSerializer = new TicketSerializer();         // Add
                byte[] ticketBytes = ticketSerializer.Serialize(mytickets[key]);
				Console.WriteLine(ticketBytes);
                var ticket = ticketSerializer.Deserialize(ticketBytes);

Any clue on what i am missing here?</div>

**Comment by Tratcher** [comment]
What information is lost?

**Comment by daphneSot** [comment]
Hello, it was my bad. Seems to be working fine.
