### ISSUE TITLE
Blazor WASM child component rendering, despite indentical parameters

### ISSUE THREAD

**Issue by 3dots** [dotnet/aspnetcore#53990]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

It's possible I am misunderstanding this [article ](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/rendering?view=aspnetcore-8.0#rendering-conventions-for-componentbase) about when components re-render.

One of the criteria is:
* After applying an updated set of [parameters](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/data-binding?view=aspnetcore-8.0#binding-with-component-parameters) from a parent component.

My understanding of what that means is that if you provide the same parameters, then a child component has no reason to rerender.
Is that not the case?

I noticed that my child components were always running OnAfterRender, despite there being nothing different about the parameters. So I made a new repo based on the default WASM template that demonstrates what I mean.

![image](https://github.com/dotnet/aspnetcore/assets/6589306/2c166618-4cf5-4053-8450-8ce39082bc51)
![image](https://github.com/dotnet/aspnetcore/assets/6589306/acb8ea61-6013-4a2f-b7ac-f3f15906c6cf)
![image](https://github.com/dotnet/aspnetcore/assets/6589306/042ebf23-58d1-426d-9697-323376e4832b)
![image](https://github.com/dotnet/aspnetcore/assets/6589306/808bd01a-d18a-4218-aa6f-da37159836c8)
![image](https://github.com/dotnet/aspnetcore/assets/6589306/adcfafed-594a-4005-a452-f791395cd658)
![image](https://github.com/dotnet/aspnetcore/assets/6589306/51efad32-45ab-45e1-812f-2dac997ec66b)

Is this intended behaviour?

Thank you in advance.

### Expected Behavior

The child component does not re-render.

### Steps To Reproduce

[https://github.com/3dots/BlazorAppRenderShenanigans](https://github.com/3dots/BlazorAppRenderShenanigans)

### .NET Version

8.0.101

### Anything else?

Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.8.5

PS C:\repos\2024\BlazorAppRenderShenanigans> dotnet --info
.NET SDK:
 Version:           8.0.101
 Commit:            6eceda187b
 Workload version:  8.0.100-manifests.0f7d8591

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.101\

.NET workloads installed:
 Workload version: 8.0.100-manifests.0f7d8591
 [android]
   Installation Source: VS 17.8.34511.84
   Manifest Version:    34.0.43/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.android\34.0.43\WorkloadManifest.json
   Install Type:              Msi

 [maui-windows]
   Installation Source: VS 17.8.34511.84
   Manifest Version:    8.0.3/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maui\8.0.3\WorkloadManifest.json
   Install Type:              Msi

 [maccatalyst]
   Installation Source: VS 17.8.34511.84
   Manifest Version:    17.2.8004/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maccatalyst\17.2.8004\WorkloadManifest.json
   Install Type:              Msi

 [ios]
   Installation Source: VS 17.8.34511.84
   Manifest Version:    17.2.8004/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.ios\17.2.8004\WorkloadManifest.json
   Install Type:              Msi

 [wasm-tools]
   Installation Source: VS 17.8.34511.84
   Manifest Version:    8.0.1/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.workload.mono.toolchain.current\8.0.1\WorkloadManifest.json
   Install Type:              Msi

Host:
  Version:      8.0.1
  Architecture: x64
  Commit:       bf5e279d92

.NET SDKs installed:
  7.0.100 [C:\Program Files\dotnet\sdk]
  8.0.100 [C:\Program Files\dotnet\sdk]
  8.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by MariovanZeist** [comment]
Hi @3dots 
It depends on the type of parameters you supply.
In your case, you are supplying it a class. Blazor has no (simple and performant) way of detecting if any sub-property of that class has changed, so it forces a rerender

In the article you linked it is explained as follows:
> All of the parameters are from a set of known types† or any [primitive type](https://learn.microsoft.com/en-us/dotnet/api/system.type.isprimitive) that hasn't changed since the previous set of parameters was set.

> The Blazor framework uses a set of built-in rules and explicit parameter type checks for change detection. These rules and the types are subject to change at any time. For more information, see the [ChangeDetection API in the ASP.NET Core reference source](https://github.com/dotnet/aspnetcore/blob/main/src/Components/Components/src/ChangeDetection.cs).

There are ways around this on a per-component basis if you need it, by overriding ``OnParameterSet`` to check if an object has changed, and handling ``ShouldRender`` [see:](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/rendering?view=aspnetcore-8.0#suppress-ui-refreshing-shouldrender) to return true if the Object has changed, or return false if it hasn't changed. But this is rarely needed.

**Comment by 3dots** [comment]
Ha. I suspected I was misunderstanding something.
I am using Fluxor, so I immediately thought: well, duh, change detection should be by reference.
But it makes that wouldn't be the only possible conclusion.

Hmm. Now I have to see if I can do a clean way to do "dont rerender on just parameter set, if references are the same", without having to control a shouldRender boolean across all events...
