### ISSUE TITLE
Globalization and Upgrading a Package

### ISSUE THREAD

**Issue by turkmvc** [dotnet/aspnetcore#54004]
Hello
Since the globalization part is set to true, it constantly gives errors during installation without making it false, and finally

     <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
Since this version arrives every time I create a project, I constantly have to update it every time I create a project.
I would be very happy if you would show the necessary sensitivity.

**Comment by tarekgh** [comment]
@eerhardt looks the complaint here about the VS project template that has Invariant Globalization is on by default.

**Comment by eerhardt** [comment]
> @eerhardt looks the complaint here about the VS project template that has Invariant Globalization is on by default.

https://github.com/dotnet/aspnetcore/pull/52461 fixed that problem. And it shipped today! So update to the new VS and .NET 8 SDK and new web api projects will no longer set this flag by default.

Closing as this issue has been fixed.

**Comment by turkmvc** [comment]
Thank you very much for your consideration and interest.
I wish you continued success.
