### ISSUE TITLE
.NET 8 Blazor - OnChange() Migration To Static Rendering

### ISSUE THREAD

**Issue by sbwalker** [dotnet/aspnetcore#54018]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When migrating Blazor component logic to utilize the Static rendering approach, you need to replace interactive event handlers with static equivalents. 

For example, for ```@onclick``` events:

```
<button class="btn btn-primary" @onclick="IncrementCount">Click me</button>
```

you can use a form-based approach:

```
<form method="post" @onsubmit="IncrementCount" @formname="MyUniqueForm">
    <AntiforgeryToken />
    <button type="submit" class="btn btn-primary">Click me</button>
</form>
```

However for ```@onchange``` events:

```
<select name="name" class="form-select" value="@_name" @onchange="(e => NameChanged(e))">
@foreach (var name in _names)
{
    <option value="@name">@name</option>
}
</select>
 ```

There are currently no recommendations or functional examples.

### Expected Behavior

Provide documentation examples on the recommended approach for migrating interactive ```@onchange``` events to static alternatives.

### .NET Version

8.0.1

**Comment by javiercn** [comment]
@sbwalker thanks for contacting us.

The recommended approach on those situations is to use interactivity and avoid SSR or use JS to hook into the change event via JS.

It's a non-goal to make every interactive scenario possible via SSR. It's up to the developer to choose when to apply each, but in general, SSR interactivity is limited to forms, which is the only thing that works without JS.
