### ISSUE TITLE
Only submit 1 AntiforgeryToken in Blazor SSR mode

### ISSUE THREAD

**Issue by csharpfritz** [dotnet/aspnetcore#54022]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In SSR rendering with Blazor, if you add an AntiforgeryToken to an EditForm in markup similar to the following:

```xml
<EditForm FormName="First" Model="Model" OnValidSubmit="SaveData">
	<DataAnnotationsValidator />
	<ValidationSummary />
	<AntiforgeryToken />

	<InputText @bind-Value="Model!.Name" />
	<button type="submit">Submit</button>
</EditForm>
```

Submission of the form will throw an invalid Antiforgery token error on the server due to the token automatically added to SSR EditForm at:

https://github.com/dotnet/aspnetcore/blob/893ca46171847a01fc73f315922d88a725a50cc3/src/Components/Web/src/Forms/EditForm.cs#L186

According to network traffic in the browser, there are two tokens transmitted:
![image](https://github.com/dotnet/aspnetcore/assets/78577/71e36e76-818c-4f10-b432-ea554372f131)

### Expected Behavior

No errors on submission because the AntiforgeryToken is properly provided.  

There is never a scenario where multiple AntiforgeryTokens should be submitted

### Steps To Reproduce

1. Create a new Blazor Web App from the template.
2. Add the following code to the home page:

```
<EditForm FormName="First" Model="Model" OnValidSubmit="SaveData">
	<DataAnnotationsValidator />
	<ValidationSummary />
	<AntiforgeryToken />

	<InputText @bind-Value="Model!.Name" />
	<button type="submit">Submit</button>
</EditForm>

@code {

	[SupplyParameterFromForm]
	public FormModel? Model { get; set; } = new();

	private void SaveData()
	{
		Console.WriteLine($"Data saved - {Model.Name}");
	}

	public class FormModel
	{
		[Required]
		public string Name { get; set; }
	}

}
```

3. Enter some data in the textbox and submit the form

### Exceptions (if any)

The server returns the following message:

```
A valid antiforgery token was not provided with the request. Add an antiforgery token, or disable antiforgery validation for this endpoint.
```

### .NET Version

8.0.200

### Anything else?

ASP.NET Core 8.0.2

**Comment by javiercn** [comment]
@csharpfritz thanks for contacting us.

I would say this is by design. I'm 90% sure that the same thing happens in MVC/Razor pages if you add the Antiforgery token twice. (it won't get de-duped).

**Comment by csharpfritz** [comment]
Is there ever a scenario where it is valid to have more than 1 AntiforgeryToken in a form?

No.. because the middleware fails to validate because it can't handle more than one token.  One of the tokens will be valid and the others will not. 

So why make this a valid form configuration?

If the addition of an AntiforgeryToken is being done silently in ONLY SSR rendering, it makes the portability of a form impossible between renderings.  

This is a painful developer experience.
