### ISSUE TITLE
init setter to have the same visibility as the most visible constructor, rather than the containing type

### ISSUE THREAD

**Issue by danielwagstaff** [dotnet/aspnetcore#54059]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I'm forced to use a backing field, rather than auto-properties, when I have a `required` field that should be set only by an internal method....maybe some code will help explain.

Given the following class, which is constructed by a static method:
```
public sealed class Artist : AggregateRoot<SubjectIdentifier>
{
    private Artist() { /* EF constructor */ }

    [SetsRequiredMembers]
    private Artist(SubjectIdentifier subjectIdentifier, EmailAddress email)
    {
        Id = subjectIdentifier;
        Email = email;
    }

    public required EmailAddress Email { get; init; }
```
because `EmailAddress` is `required` it cannot be `private set`, it must at least be `init`. This is not a problem, because the constructor is `private`.

However, I want to update this field, via a method internal to the class `Artist`. So, I'm forced to write:
```
    public required EmailAddress Email { get => email; init => email = value; }
    private EmailAddress email = null!;
```
which gives a code analysis warning, `S2292: Trivial properties should be auto-implemented`.

I can suppress this, but it's extra code and wouldn't it make sense that any `required` fields only require the same visibility as the most visible constructor?

### Describe the solution you'd like

Make any `required` fields only require the same visibility as the most visible constructor, i.e. in this case it would be `private set`.

**Comment by mkArtakMSFT** [comment]
@jaredpar can you please transfer this to the dotnet/roslyn repo?

**Comment by jaredpar** [comment]
This diagnostic is coming from the Sonar analyzer suite, not the C# compiler. The [sonar-dotnet](https://github.com/SonarSource/sonar-dotnet) repo is likely the best place to file this issue.

**Comment by danielwagstaff** [comment]
Is the recommendation to transfer to the sonar-dotnet repo in order to suppress the trivial properties sonar warning? If so, that wouldn't be the ideal solution, as the use of the trivial backing field was a work-around. The better solution would be to "Make any required fields only require the same visibility as the most visible constructor".

**Comment by jaredpar** [comment]
> Is the recommendation to transfer to the sonar-dotnet repo in order to suppress the trivial properties sonar warning?

My recommendation is transfer the issue to them and let them decide on how to move forward. 

>  The better solution would be to "Make any required fields only require the same visibility as the most visible constructor".

That makes intuitive sense to me but Sonar owns this analyzer not us.
