### ISSUE TITLE
httpContext.SignInAsync not working after update to .NET 8.0.2

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#54075]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/httpContextSignInAsync-not-working-afte/10585257)._

---
[severity:It bothers me. A fix would be nice] [regression] [worked-in:17.8]
i build blazor app interactive auto with custom authentication where from blazor hit additional endpoint in the same site for login to httpContext.SignInAsync at server side, in before that work nice, but after update to .NET 8.0.2, sometimes after hit that additional endpoint the IsAuthenticated still false, so the page keep at the login page, then after second hit IsAuthenticated true so the page can be redirct to main page.

---
### Original Comments
(no comments)

---
### Original Solutions
(no solutions)

**Comment by ylanls** [comment]
I encountered the same problem, when RedirectUri is set, every request will be redirected to this uri. But when I deleted RedirectUri, everything was normal.
