### ISSUE TITLE
Blazor Web Assembly + Hybrid: HttpClient Upload Progress with ProgressableStreamContent

### ISSUE THREAD

**Issue by drmaven** [dotnet/aspnetcore#54105]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

HttpClient buffers the whole request stream, when having a ProgressableStreamContent that writes the source stream in chunks to the request stream.

The request starts after the completion of SerializeToStreamAsync() method, so it renders progress reporting useless.

If this is by design, are there any workarounds?

### Expected Behavior

The request should start after the first FlushAsync(), so that progress reporting can work

### Steps To Reproduce

`public class ProgressableStreamContent : HttpContent
    {
        private readonly HttpContent content; 
        public event EventHandler<Progress2EventArgs> ProgressChanged;

        public ProgressableStreamContent(HttpContent content)
        {
            try
            {

                this.content = content ?? throw new ArgumentNullException(nameof(content));

                foreach (var header in content.Headers)
                {
                    Headers.Add(header.Key, header.Value);
                }

            }
            catch (Exception ex)
            {

            }
        }
 
        protected override async Task SerializeToStreamAsync(Stream stream, System.Net.TransportContext? context)
        {
            var buffer = new byte[1024 * 64 * 1];
            TryComputeLength(out long size);
            var uploaded = 0L;

            using (var s = await content.ReadAsStreamAsync())
            {
                while (true)
                {
                    var length = await s.ReadAsync(buffer, 0, buffer.Length);
                    if (length == 0) break;
 
                    await stream.WriteAsync(buffer, 0, length);
                    await stream.FlushAsync();

                    uploaded += length;
                     
                    ProgressChanged?.Invoke(this, new Progress2EventArgs(uploaded, size));
                }

                ProgressChanged?.Invoke(this, new Progress2EventArgs(uploaded, size));
            }

        }

        protected override bool TryComputeLength(out long length)
        {
            length = content.Headers.ContentLength.GetValueOrDefault();
            return true;
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                content.Dispose();
            }
            base.Dispose(disposing);
        }
    }`

### .NET Version

8

**Comment by javiercn** [comment]
@drmaven thanks for contacting us.

This is by design. Streaming the request body is not generally supported on the underlying web apis (only Chrome/Edge support it as of recently), so any request body needs to be completely buffered before it can be sent.
