### ISSUE TITLE
EditForm in foreach loop not working without rendermode InteractiveServer

### ISSUE THREAD

**Issue by TeaDrinkingProgrammer** [dotnet/aspnetcore#54108]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am trying to create an EditForm for every item in a list. This works when rendermode is set to InteractiveServer, but not by default (see [Reproduction Repo](https://github.com/TeaDrinkingProgrammer/ReproductionEditForm)). I am quite new to Blazor so if I am approaching this problem in the wrong way, I am open to suggestions.

Snippet (also in Reproduction Repo)
```c#
@page "/"

@* @rendermode InteractiveServer *@
@using System.ComponentModel.DataAnnotations

<PageTitle>App Versions</PageTitle>
<div>
    @foreach (var appVersion in Appversions)
    {
        var formName = appVersion.Id.ToString();
        @appVersion.VersionNumber
        <EditForm Model="appVersion" OnValidSubmit="@ValidUpdateFormSubmitted" FormName="@formName">
            <DataAnnotationsValidator/>
            <ValidationSummary/>
            <span>VersionNumber</span>
            <input type="text"
                   placeholder=""
                   class="bg-slate-700"
                   @bind="appVersion.VersionNumber"/>
            <button type="submit">
                Save
            </button>
        </EditForm>
    }
</div>

@code {

    public class AppVersion //: BaseEntity
    {
        public int Id { get; set; }

        [Required]
        public string? VersionNumber { get; set; }
    }
    
    private IList<AppVersion>? Appversions { get; set; }

    protected override void OnInitialized()
    {
        Appversions = new List<AppVersion>
        {
            new() { Id = 1, VersionNumber = "1.0.0" },
            new() { Id = 2, VersionNumber = "1.0.1" },
            new() { Id = 3, VersionNumber = "1.0.2" }
        };
    }

    private void ValidUpdateFormSubmitted(EditContext editContext)
    {
        var appVersion = editContext.Model as AppVersion;
        Console.WriteLine($"Appversion number in Blazor page: {appVersion?.VersionNumber}");
    }
}
```

### Expected Behavior

When the save button is clicked, the value is passed to the method even without InteractiveServer.

### Steps To Reproduce

1. Download the [Reproduction Repo](https://github.com/TeaDrinkingProgrammer/ReproductionEditForm)
2. Edit a value in one of the fields
3. Click save
4. The value is not changed.

### .NET Version

8.0.201

### Anything else?

.NET SDK:
 Version:           8.0.201
 Commit:            4c2d78f037
 Workload version:  8.0.200-manifests.bc6351c6

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.201\

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.2
  Architecture: x64
  Commit:       1381d5ebd2

.NET SDKs installed:
  8.0.101 [C:\Program Files\dotnet\sdk]
  8.0.102 [C:\Program Files\dotnet\sdk]
  8.0.201 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

**Comment by javiercn** [comment]
@TeaDrinkingProgrammer thanks for contacting us.

You need to use `[SupplyParameterFromForm] public YourModel SubmittedForm { get; set; }` to bind the values from the submit event to a model.

**Comment by TeaDrinkingProgrammer** [comment]
How would I do that here? I have an unknown number of forms at runtime, and it seems to me you can bind the model to only one form.

**Comment by TeaDrinkingProgrammer** [comment]
@javiercn How do I reopen this issue again?

**Comment by cisci86** [comment]
@TeaDrinkingProgrammer Did you ever find a solution? I have the same problem with EditForm in an foreach loop with validation not working

**Comment by TeaDrinkingProgrammer** [comment]
It has been quite a while, so I really don't remember if I'm honest, sorry. You're probably best of opening a new issue.
