### ISSUE TITLE
Add `AddHubOptions<>` SignalR extension to `IServiceCollection`

### ISSUE THREAD

**Issue by MikeAlhayek** [dotnet/aspnetcore#54116]
## Background and Motivation

In the SignalR library, we are able to configure the hub options using the `AddHubOptions<>` extensions on the `ISignalRServerBuilder` interface. This is great when you are adding the hub from the same project that adds the server. However, in a modular infrastructure, it hubs maybe defined in a module that does not register the server.

Today, in order for one to register a hub from a project that does not register the server, we would have to do the following

```csharp
services.AddSingleton<IConfigureOptions<HubOptions<CustomHub>>, HubOptionsSetup<CustomHub>>();
services.Configure(op => {
 // ...
});
```

It would be helpful if we can add `AddHubOptions<>` extension to the `IServiceCollection` to allow us to easily add and configure hub specific options from a project that does not register the server.

## Proposed API

Change the `AddHubOptions<>` extension 

https://github.com/dotnet/aspnetcore/blob/5c17b92560953e86f1ea8502a567bcb3a1be4a2f/src/SignalR/server/SignalR/src/SignalRDependencyInjectionExtensions.cs#L24-L31

To this instead

```csharp
    /// <summary>
    /// Adds hub specific options to an <see cref="ISignalRServerBuilder"/>.
    /// </summary>
    /// <typeparam name="THub">The hub type to configure.</typeparam>
    /// <param name="signalrBuilder">The <see cref="ISignalRServerBuilder"/>.</param>
    /// <param name="configure">A callback to configure the hub options.</param>
    /// <returns>The same instance of the <see cref="ISignalRServerBuilder"/> for chaining.</returns>
    public static ISignalRServerBuilder AddHubOptions<THub>(this ISignalRServerBuilder signalrBuilder, Action<HubOptions<THub>> configure) where THub : Hub
    {
        ArgumentNullException.ThrowIfNull(signalrBuilder);

        signalrBuilder.Services.AddHubOptions<THub>(configure);
        return signalrBuilder;
    }

    /// <summary>
    /// Adds hub specific options to an <see cref="IServiceCollection"/>.
    /// </summary>
    /// <typeparam name="THub">The hub type to configure.</typeparam>
    /// <param name="services">The <see cref="IServiceCollection"/>.</param>
    /// <param name="configure">A callback to configure the hub options.</param>
    /// <returns>The same instance of the <see cref="IServiceCollection"/> for chaining.</returns>
    public static IServiceCollection AddHubOptions<THub>(this IServiceCollection services, Action<HubOptions<THub>> configure) where THub : Hub
    {
        ArgumentNullException.ThrowIfNull(services);

        services.AddSingleton<IConfigureOptions<HubOptions<THub>>, HubOptionsSetup<THub>>();
        services.Configure(configure);
        return services;
    }
```

## Usage Examples

In module "A" we can use `services.AddSignalR()` and define global hub options.

In module "B" that depends on module "A", we can use `services.AddHubOptions<CustomHub>(options => ... )`

## Risks

None

I can submit a PR for this.

**Comment by halter73** [comment]
API Review Notes:

- How common is it to need this API? Is there anyone else who would call this? It seems weird to configure options on a specific hub in a different place than `AddSignalR()` call.
- You could call `AddSignalR()` twice to get an `ISignalRServerBuilder`, and it shouldn't cause problems because it uses `TryAdd...` This reduces the risk if change the implementation of `AddHubOptions<THub>` to add even more extra services in the future.
- Generally, we prefer if there was one correct way to do things.

Thanks for your proposal, but we've decided to reject this API.

**Comment by halter73** [comment]
Is there a problem with calling `AddSignalR` twice though? It's pretty common for "Add" methods to get repeatedly called. They should no-op if the necessary services are already registerd. This is certainly the case for lower-level dependencies that a lot of libraries depend on [like AddOptions()](https://github.com/search?q=repo%3Adotnet%2Faspnetcore+AddOptions%28%29&type=code) and [AddMetrics()](https://github.com/search?q=repo%3Adotnet%2Faspnetcore+AddMetrics%28%29&type=code).
