### ISSUE TITLE
[Blazor] Enhance form and data-permanent is not enough control.

### ISSUE THREAD

**Issue by Bartmax** [dotnet/aspnetcore#54117]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Right now, we can have data-permanent tags on many places of a webpage so when we submit a form o do some enhance nav those elements doesn't get diffed and works ok 👍 

But what I find most interesting, when using forms, is that I want to be able to "only" diff inside a element and it's parents and care less for the rest of the page, so insted of doing data-permanent on every piece of dom i need to keep, i would like to specify a piece of dom i want to only get updated.

This also enables the scenario that you can keep parent elements while updating child elements (currently not posible)

Examples:

```html
<div class="modal">
  <EditForm data-enhance=true> ... </EditForm>
</div>
```

In this example, the modal is shown via some javascript so it updates to:
```html
<div class="modal open">
  <EditForm data-enhance=true> ... </EditForm>
</div>
```

after submit, the modal closes (because the open class is not persisted).
If I add `<div class="modal" data-permanent=true>` then the form is not updated with validation errors.

### Describe the solution you'd like

What I would like in my scenario, is a way to specify which parts to update.
```html
<div class="modal">
  <EditForm data-enhance="{some identifier}"> ... </EditForm>
</div>
``` 

Where some identifier could be an element id, a component, or whatever, for example:

```html
<div class="modal">
  <div id="UpdateThisAndChildsOnPost">
    <EditForm data-enhance="UpdateThisAndChildsOnPost"> ... </EditForm>
  </div>
</div>
```

**Comment by javiercn** [comment]
@Bartmax thanks for contacting us.

This is a different model than the one Blazor uses for enhanced navigation (more like update panel or the old MVC AJAX functionality) and for the time being we don't have plans to implement that type of feature.

Is there a reason why updating the entire page doesn't work?

**Comment by Bartmax** [comment]
As I said, it's not possible to keep parent elements with data permanent (in my sample, the modal open), while updating the inner form with validation.

As soon as you put data-permament on an element, all childs updates are ignored. 

So any update via js to any parent of a part that needs to update wont be able to use data-permament.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
While this may be a great idea, it is not aligned with our long-term vision to make it part of the framework. For many other ideas which don't belong to the framework we encourage the community to build and ship on their own, contributing to the expanding .NET Ecosystem.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.

**Comment by Bartmax** [comment]
So you don't encourage users to use interaction via JavaScript, only wasm or blazor server. Noted.
