### ISSUE TITLE
Blazor server exception while running locally

### ISSUE THREAD

**Issue by setin1219** [dotnet/aspnetcore#54111]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have created a new project and used the template of blazor web app. while running locally i saw below exceptions:

Exception thrown: 'System.IO.IOException' in System.Net.Security.dll
Exception thrown: 'System.IO.IOException' in System.Net.Security.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in System.Private.CoreLib.dll
Exception thrown: 'System.ObjectDisposedException' in System.Private.CoreLib.dll
Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in System.Private.CoreLib.dll

Mostly when i visit 'weather' page, i see below exception in output->debug window.
 I ran the application in https mode.

### Expected Behavior

i expected to run it without any exception since there is no change in project and created from template.

### Steps To Reproduce

create new blazor web app.
run while https is selected.
check the output window.
![blazor web app create](https://github.com/dotnet/aspnetcore/assets/13939593/49b8903b-297e-4ab6-9413-8ba80dbaff15)
[BlazorWebTestApp.zip](https://github.com/dotnet/aspnetcore/files/14331503/BlazorWebTestApp.zip)

### Exceptions (if any)

Exception thrown: 'System.IO.IOException' in System.Net.Security.dll
Exception thrown: 'System.IO.IOException' in System.Net.Security.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in System.Private.CoreLib.dll
Exception thrown: 'System.ObjectDisposedException' in System.Private.CoreLib.dll

### .NET Version

8.0.102

### Anything else?

![blazor exception](https://github.com/dotnet/aspnetcore/assets/13939593/d8b13715-1137-47f9-a39c-3ad5397e7b9f)

below is more info on visual studio 

Microsoft Visual Studio Professional 2022
Version 17.8.7
VisualStudio.17.Release/17.8.7+34601.278
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Professional

Visual C++ 2022   00476-80000-00000-AA338
Microsoft Visual C++ 2022

ASP.NET and Web Tools   17.8.358.6298
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.8.358.6298
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   17.8.358.6298
Azure Functions and Web Jobs Tools

C# Tools   4.8.0-7.23572.1+7b75981cf3bd520b86ec4ed00ec156c8bc48e4eb
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   17.0.23262.1
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Node.js Tools   1.5.50908.1 Commit Hash:c294679b821c4b8f7f9c6db3827b7655db80fc28
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   6.8.1
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Office Developer Tools for Visual Studio   17.6.34024.01
Microsoft Office Developer Tools for Visual Studio

Python - Profiling support   17.0.23262.1
Profiling support for Python projects.

Python with Pylance   17.0.23262.1
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Razor (ASP.NET Core)   17.8.3.2405201+d135dd8d2ec1c2fbdee220e8656b308694e17a4b
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.8.120.1
Microsoft SQL Server Data Tools

TypeScript Tools   17.0.20920.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.8.0-7.23572.1+7b75981cf3bd520b86ec4ed00ec156c8bc48e4eb
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.8.0-beta.23475.2+10f956e631a1efc0f7f5e49c626c494cd32b1f50
Microsoft Visual F# Tools

Workflow Manager Tools 1.0   1.0
This package contains the necessary Visual Studio integration components for Workflow Manager.

**Comment by javiercn** [comment]
@setin1219 thanks for the additional details.

This is not specific to ASP.NET Core. Maybe the docs you are looking for are already here (or in that area) https://learn.microsoft.com/en-us/visualstudio/debugger/output-window-debugging-options-dialog-box?view=vs-2022

We suggest you open a feedback ticket on the docs page otherwise. From the framework perspective, there's nothing we can do about it because the framework is behaving as expected.

**Comment by setin1219** [comment]
Noted, I will inform my team if any one comes to me with any concern on this. Thanks for the information.

**Comment by setin1219** [comment]
Closing ticket since anwered.

**Comment by sliceofbytes** [comment]
This should be re-opened. Expected behavior is for the tooling to not throw exceptions..
