### ISSUE TITLE
Are ASP.NET scaffolded templates Section 508 (Accessibility standard) compliant?

### ISSUE THREAD

**Issue by jongalloway** [dotnet/aspnetcore#5414]
Per discussion on this week's ASP.NET Community Standup, we need to check if the scaffolded templates are compliant with [Section 508](https://www.section508.gov/content/learn).

**Comment by mkArtakMSFT** [comment]
@danroth27 bringing this back to `Preview6`

**Comment by mkArtakMSFT** [comment]
We've done a pass over the templates already and made them accessible out of the box.
