### ISSUE TITLE
.NET 8 Blazor - StreamRendering - Magic Pill or Future Headache?

### ISSUE THREAD

**Issue by sbwalker** [dotnet/aspnetcore#54157]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

For the past 3 weeks I have been migrating a traditional Blazor application (https://github.com/oqtane/oqtane.framework) to the new Blazor approach in .NET 8. The process has not been smooth. The main problems are not related to the refactoring of the code - they are related to the run-time behavior of Blazor and the fact that it is a "black box". 

More specifically, I am referring to scenarios where Blazor refuses to render a component... where it executes component logic such as StateHasChanged() and then does nothing - ie. it does not refresh the UI, it does not throw an exception, and it does not log anything in the browser console. Many days can be spent trying to track down these types of issues and in the end there is no resolution because it is not possible to identify the root cause (because the problem is occurring deep within the Blazor framework itself and there is no developer feedback loop).

Example # 1

An application which runs fine on global interactive rendering, attempts to run on static rendering. Within Visual Studio all of the logic is executing fine - no exceptions, no browser console messages - however the browser simply displays a blank page. If you view the source in the browser, you only see content from the App component - nothing else has been rendered. This resulted in 3-4 days of trying to identify the problem. 

![image](https://github.com/dotnet/aspnetcore/assets/4840590/aaceed0e-4ea0-4f66-9725-1cf4af0ff281)

Example # 2

A stattically rendered component which indicates that a variable contains content within Visual Studio and should be rendered in the UI, however the UI is never updated with the content. This provoked another 3-4 days of investigation.

![image](https://github.com/dotnet/aspnetcore/assets/4840590/b0a60f70-dc47-49ba-adab-23a94789a65a)

In both of these examples above (and a number of others) it turns out that there is a simple solution...

```@attribute [StreamRendering]```

Including this attribute within a component definition appears to be a "magic pill" to cure all sorts of strange, unexplainable rendering problems. Basically, rather than spending days trying to diagnose the Blazor "black box" I now sprinkle a component with some [StreamRendering] pixie dust, and it usually fixes the problem. From a developer productivity perspective alone, this attribute has already saved me from many days of spinning my wheels.

For Example # 1 including [StreamRendering] on the Routes component allowed the entire application to render as expected. For Example # 2 including [StreamRendering] on a custom Head component allowed page titles to be rendered as expected.

My concern is that most "magic pills" have side effects... they may solve the original problem but cause other issues in the process. In the case of [StreamRendering] there is very little documentation about what it is actually doing under the covers. Most of the information simply describes its purpose and benefits at a very high level. The fact that the Blazor Web template only includes it on the Weather component would seem to indicate that it should be used sparingly. So what are the implications from a performance, scalability, security perspective? Before I go ahead and sprinkle this attribute throughout my Blazor applications I would like to better understand the long term consequences.

### Expected Behavior

Better guidance around the usage of [StreamRendering] in terms of when it should or should not be used, and the impacts of using it within an application.

### .NET Version

8.0

**Comment by mkArtakMSFT** [comment]
Thanks for sharing your concerns, @sbwalker.
Could you please share a minimal repro for us to investigate these further. Errors during development should be discoverable and if there is a case where they are not, we will try to improve it.

**Comment by sbwalker** [comment]
@mkArtakMSFT the following repo contains a minimal repro:

https://github.com/oqtane/OqtaneSSR

Run the app and the Home page displays:

![image](https://github.com/dotnet/aspnetcore/assets/4840590/8eae7d77-a014-44da-b320-ae7cf88a28a6)

The red square indicates where content is supposed to be rendered by the OqtaneSSR.Client\Components\Modules\Home.razor component

```
<p>This component demonstrates retrieving data using the ITextService</p>

@if (_text != null)
{
    <strong>@_text</strong>
}
```

Now modify the OqtaneSSR.Client\Components\Root\Routes.razor component and add uncomment the StreamRendering attribute:

```
@attribute [StreamRendering]
```

and the content will be displayed:

![image](https://github.com/dotnet/aspnetcore/assets/4840590/7a41ca84-7139-4caa-8ac8-0c7cab86865a)

no changes to the app other than adding StreamRendering... the "magic pill".

**Comment by sbwalker** [comment]
After further testing, the answer to the title of this issue is that StreamRendering is NOT a magic pill - it IS a Future Headache. When used in a root component of an app, StreamRendering produces a "flash" effect as it progressively pushes content to the browser which can result in a poor user experience.

**Comment by sbwalker** [comment]
@MackinnonBuck please let me know if you would like to discuss this issue further.

**Comment by MackinnonBuck** [comment]
@sbwalker Do any of these problems go away after updating to the latest .NET 8 patch release? There were some servicing fixes related to stream rendering that may have resolved some of these (e.g., https://github.com/dotnet/aspnetcore/pull/52823).

**Comment by sbwalker** [comment]
@MackinnonBuck if you are referring to 8.0.3, Oqtane is already running on 8.0.3 and the problem still exists. To be clear, this issue is NOT about StreamRendering... it is that Blazor refuses to render content in SSR, and the only way to force content to be rendered is by adding the StreamRendering attribute:

![image](https://github.com/dotnet/aspnetcore/assets/4840590/16eb59c2-c7df-4472-aeff-dc7a163f4fd5)

**Comment by MackinnonBuck** [comment]
@sbwalker, the fix I was referring to was introduced in 8.0.2, so it seems like that bug isn't the cause of what you're seeing.

I briefly looked into the repro and on my machine, the "Hello StreamRendering" text displays even without stream rendering enabled. But I do see that the problematic code is called from an `async void` event handler, which stood out as a red flag. Blazor has no way of tracking `async void` invocations, so it doesn't know when the work there has completed. The renderer likely thinks that all components have finished rendering so it writes out the response without knowing that another task will later trigger a re-render.

It's possible that adding `[StreamRendering]` makes the text appear might be because there's an extra `await` call somewhere in Blazor's internals that happens to yield execution to code in the `async void` handler. But that would not indicate a bug in stream rendering.

Ultimately, I haven't been able to repro the exact behavior you're seeing so this is all a bit of a guess. I noticed that the repro uses configuration to decide render modes to use - could you provide a more minimal repro without all that machinery that demonstrates the issue you're seeing? Thanks.

**Comment by sbwalker** [comment]
@MackinnonBuck I am not sure how the code in the https://github.com/oqtane/OqtaneSSR repo could work for you? I just updated the references to 8.0.3 and tried running it locally:

![image](https://github.com/dotnet/aspnetcore/assets/4840590/69ad3752-089a-4d79-82ec-5c679ca34f5a)

Then I uncomment the StreamRendering attribute in Routes.razor:

![image](https://github.com/dotnet/aspnetcore/assets/4840590/d0fca9bd-446a-4357-b67d-c9bb161fce0b)

And run the application and it displays the content:

![image](https://github.com/dotnet/aspnetcore/assets/4840590/e3e73d2f-5c19-4356-b11f-0fb5b73eb1f1)

Your comment about the async void event handler is interesting. Specifically you are referring to this code in the custom SiteRouter:

```
    private async void LocationChanged(object sender, LocationChangedEventArgs args)
    {
        _absoluteUri = args.Location;
        await Refresh();
    }
```

This SiteRouter code was based on the default Blazor Router and that specific method has not changed since it is was introduced in 2018... but it could certainly still be a problem which has been exposed by the different run-time behavior in Static Blazor. 

In the original default Blazor Router it was simply a void method - but in Oqtane it was modified to be async because the Refresh method contains HttpClient calls (all of the routing configuration in Oqtane is stored in a database which is loaded dynamically at runtime - note that Oqtane was originally an Interactive Blazor application and still supports this render mode).

In the latest Blazor Router the method has changed slightly to be "internal virtual" (with support for navigation interception):

https://github.com/dotnet/aspnetcore/blob/ad9e0045e5cf7995805a645aa3f6dfc8923b4412/src/Components/Components/src/Routing/Router.cs#L180

```
    internal virtual void Refresh(bool isNavigationIntercepted)
    {
        // If an `OnNavigateAsync` task is currently in progress, then wait
        // for it to complete before rendering. Note: because _previousOnNavigateTask
        // is initialized to a CompletedTask on initialization, this will still
        // allow first-render to complete successfully.
```

So I think what you are suggesting is to try to find a way to avoid the async void method. Unfortunately async Task does not work because the NavigationManager.LocationChanged -= LocationChanged event handler does not like it. Which I believe is why it ended being specified as async void in the first place. Do you have a suggestion on how to declare the LocationChanged event handler in such a way that it would permit asynchronous calls within the implementation? The reason why the default Blazor Router does not suffer from this is because it relies on reflection and purely static configuration... but as soon as you try to embrace a more dynamic approach to routing, the asynchronous requirement becomes very important.

I really appreciate your assistance.

**Comment by MackinnonBuck** [comment]
@sbwalker,

I did a fresh clean of the repo, pulled the latest commit, confirmed that stream rendering was disabled in `Routes.razor`, and ran it, and got this:

![image](https://github.com/dotnet/aspnetcore/assets/10456961/fba624ee-c792-456c-8092-cf38559b8010)

Not sure what to say except the problem doesn't repro for me. The site uses static routing when I run it, so `LocationChanged` isn't even getting invoked, which makes me think there's some local configuration difference causing me not to see the problem.

> Unfortunately async Task does not work because the NavigationManager.LocationChanged -= LocationChanged event handler does not like it

You can use `NavigationManager.RegisterLocationChangingHandler()` to register an async callback that blocks the navigation until the task completes. If you switch to use that, does the problem go away?

**Comment by sbwalker** [comment]
@MackinnonBuck I was very confused why this would not repro for you... and then I noticed that there was an appsettings.Development.json file in the repo - perhaps this config was being used when you were running the solution? I have removed the file so that it now uses the appsettings.json which contains the expected configuration. When running the app it should look like:

![image](https://github.com/dotnet/aspnetcore/assets/4840590/ae6c34c6-2c44-49ac-96ae-30ab0b401f88)

And you are correct that when running on Static Rendering (the default for the app) the LocationChanged() method is not even called because this is only relevant in Interactive Rendering. So I don't think this is the source of the problem. 

However, I do think you are correct that the rendering problem is related to async calls. If you comment out the code in SiteRouter.razor in the Refresh method which is performing an HttpClient call (to simulate retrieving data from a backend API):

![image](https://github.com/dotnet/aspnetcore/assets/4840590/b6be970d-7466-41c4-9dad-676ca8c37403)

The content will be displayed as expected (even with StreamRendering commented out in Routes.razor). Note that the Refresh method is actually running synchronously in this scenario because the Refresh method no longer contains an await call.

![image](https://github.com/dotnet/aspnetcore/assets/4840590/c2df591c-3588-494f-9eb7-7ee83f68101f)

Refresh is an async Task (not async void) and if f I now add an await Task.Yield() so that the method is asynchronous: 

![image](https://github.com/dotnet/aspnetcore/assets/4840590/67a69fa9-5b71-45e5-b695-471b908af8d9)

The content is no longer displayed:

![image](https://github.com/dotnet/aspnetcore/assets/4840590/ffd701bd-334a-4a31-88ee-b7839c4e6673)

But moving the await Task.Yield() to the end of the method:

![image](https://github.com/dotnet/aspnetcore/assets/4840590/6785b118-5859-4f19-9fc5-94aa44e13914)

Allows the content to be displayed once again:

![image](https://github.com/dotnet/aspnetcore/assets/4840590/0e16af47-d7d0-404d-8372-ab39af93a9eb)

(however in practice this would not work because in a real app the HttpClient service call is necessary to set the PageState values).

**Comment by MackinnonBuck** [comment]
Thanks for the additional details, @sbwalker.

I cloned the latest version of your repro and ran it, and it still worked fine for me. Is the repro set up in a way where it can just be cloned and run without additional configuration? AFAICT, the conditions are set up correctly to reproduce the bug (stream rendering disabled, an async `Refresh()` method), but I still see the "Hello StreamRendering!!" text when visiting the site (and when navigating to another page and back, etc.).

I even tried it on a fresh machine... still worked.

Are you able to simulate a clean environment and run the project? If so, does the issue still happen after doing that?

What I did was:
* Open Windows Sandbox
* Go to https://get.dot.net
* Download the 8.0.3 SDK
* Download the code from https://github.com/oqtane/OqtaneSSR as a zip
* Unzip
* In PowerShell, go to the `<repo root>/OqtaneSSR` directory
* `dotnet run`
* Visit the app's URL

**Comment by sbwalker** [comment]
@MackinnonBuck I can’t say I have had a “it doesn’t work on my machine” moment for a long time, as .NET generally creates repeatable solutions. I will install Windows Sandbox and give it a try. I will also request the Oqtane community try to run the solution in the repo to see if they experience issues or not. At the end of the day it is not the issue in this repo, it is the Oqtane Framework rendering problem which I want to resolve… so I am now wondering if the Oqtane Framework can be run in the Windows Sandbox so that the real problem can be reproduced (blank browser screen). I will let you know.

**Comment by MackinnonBuck** [comment]
I'm glad you were able to find the cause of the issue, @sbwalker!

> the only remaining question which has not been addressed is if there is any official guidance which could be provided to developers in regards to when StreamRendering should be used - as without this guidance it will be used arbitrarily without understanding the consequences

Is there something that our [current guidance](https://learn.microsoft.com/aspnet/core/blazor/components/rendering?view=aspnetcore-8.0#streaming-rendering) is lacking that you think could use additional clarification? I'm not aware of any scenarios where toggling stream rendering breaks the app in unintuitive ways (on the latest 8.0.3 SDK, that is).

**Comment by sbwalker** [comment]
Spoke too soon... the Azure site where I deployed the bits with StreamRendering removed is still not rendering content in some scenarios:

![image](https://github.com/dotnet/aspnetcore/assets/4840590/1fbe73ca-713f-4d38-9af1-f7a6def64d3f)

So I am guessing that SDK 8.0.1 did not fix this issue... perhaps it was fixed in SDK 8.0.2 or 8.0.3. Now I need to figure out how to upgrade the SDK in my Azure App Service.

**Comment by sbwalker** [comment]
Upgraded my Azure App Service to .NET SDK 8.0.4 (using Development Tools / Extensions) and the rendering problem is resolved.

**Comment by garrettlondon1** [comment]
Thank you so much @sbwalker , I was struggling to figure out, all day, why StreamRendering was working locally, but not on App Service.

Added 8.0.4 to Extensions in App Service and now everything is working smoothly. Thanks for updating.

**Comment by MackinnonBuck** [comment]
Glad to hear that the upgrade fixed it!

> "The renderer does not have a component with ID ##" in some scenarios where you are dynamically creating components.

A new issue with a repro would be great if you'd be willing to provide one!

**Comment by MackinnonBuck** [comment]
Updated the title so that others experiencing a similar issue can find this one more easily.
