### ISSUE TITLE
OnAfterRender not called on interactive component in loop

### ISSUE THREAD

**Issue by alexvale242** [dotnet/aspnetcore#54153]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Using the Blazor Web Template as a starting point. If you have a non-interactive component which creates a large number (more than 40) of InteractiveServer components in a for loop, the render lifecycle on the interactive child components breaks. 

The OnAfterRender and OnAfterRenderAsync lifecycle methods do not fire and on page load we get the reconnection spinner. There's also two websocket connections, one which fails quickly and one which takes a while to get going. 

![image](https://github.com/dotnet/aspnetcore/assets/46447983/16b154b7-427d-4e3d-936b-5bd4ccf4dac8)
![image](https://github.com/dotnet/aspnetcore/assets/46447983/1976ab9e-b04c-4434-82c9-0e4f1c261d44)

If the parent's render mode is InteractiveServer then this works as expected. 

### Expected Behavior

Rendering should work as intended and after render lifecycle methods should be called. Page should not have to reconnect on page load. 

### Steps To Reproduce

https://github.com/alexvale242/InteractiveServerBugRepro

Repro of this bug can be found in the Home and InteractiveComponent components. 

### .NET Version

8.0.102

**Comment by javiercn** [comment]
@alexvale242 thanks for contacting us.

Can you check the browser developer tools? Very likely you've hit the signalr message size limits

**Comment by alexvale242** [comment]
Hi @javiercn, that appears to be the case. I find it interesting that the websocket connection recovers but the render cycle does not!
![image](https://github.com/dotnet/aspnetcore/assets/46447983/0aa7ad71-fdb0-4137-918b-402bda591b04)

**Comment by javiercn** [comment]
@alexvale242 thanks for the additional details.

You can increase the message size in the options. 

This is expected. From the SignalR point of view it's just a failed message. From the Blazor point of view is a terminal error as the information for all the components needs to be provided in a single message at the moment. We might relax this restriction in the future, but for the time being, the way to address this is to either:
1) Wrap in a component and make that interactive (as each component has a render size overhead)
2) Increase the message size.

This is for security reasons (availability on the server) so it's a balance between what you need and the threshold you want to establish per connection.

**Comment by alexvale242** [comment]
I see! Thank you very much for the input.
