### ISSUE TITLE
Blazor .NET 8 [RenderModeInteractiveAuto] getting an error

### ISSUE THREAD

**Issue by khushbupatel2** [dotnet/aspnetcore#54159]
The type or namespace name 'RenderModeInteractiveAuto' could not be found (are you missing a using directive or an assembly reference?)	IntroToBlazor.Client	
\dotnetblazor\IntroToBlazorApp\IntroToBlazor\IntroToBlazor.Client\Pages\Demo.razor	1

**Comment by javiercn** [comment]
@khushbupatel2 thanks for contacting us.

It's `RenderMode.InteractiveAuto` the fully qualified name is `Microsoft.AspNetCore.Components.Web.RenderMode.InteractiveAuto`

You are probably missing a using somewhere. The template normally adds a static using to `Microsoft.AspNetCore.Components.Web.RenderMode`
