### ISSUE TITLE
Blazor WASM: MSAL authentication stuck on login callback

### ISSUE THREAD

**Issue by luisabreu** [dotnet/aspnetcore#54171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This seems to be the bug mention on #43317 . It's still happening on Blazor WASM running .NET 8.0. As described on the original bug #43317, sometimes the authentication process gets stuck on the `authentication/login- callback' url and the user isn't redirected to the correct url (default page). This happens even when run on local mode (ie, no trimming configured). #43317 seems to imply that this happens due to trimming.  However, I've already setup the "msal assemblies" as trimmer root assemblies, but the issue remains:

```
    <ItemGroup>
        <TrimmerRootAssembly Include="Microsoft.Authentication.WebAssembly.Msal" />
        <TrimmerRootAssembly Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" />
    </ItemGroup>
```

### Expected Behavior

After completing the login successfully, the user should be redirected to the default page.

**Comment by halter73** [comment]
I'm having trouble reproducing the stuck on the `authentication/login-callback' when testing https://github.com/halter73/BlazorHostedWasmAAD.

When I navigate to https://localhost:7189 with a private browsing window and log in successfully without any errors in either the server logs or client developer console.

![Home page while logged in](https://github.com/dotnet/aspnetcore/assets/54385/2a563fc4-e594-4c7e-8420-e94ab218940f)

To create the BlazorHostedWasmAAD project, I did the following:

- Run `dotnet new blazorwasm -au SingleOrg -ho` using the .NET 7.0.406 SDK as specified in global.json
- Followed the guide at https://learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-microsoft-entra-id?view=aspnetcore-7.0#use-of-an-azure-active-directory-b2c-tenant to configure it with an Azure AD B2C tenant
- Then updated the TFMs from net7.0 to net8.0 and the NuGet packages to their latest 8.0 versions.

You can see each step in the projects [commits](https://github.com/halter73/BlazorHostedWasmAAD/commits/main/). Can anyone figure out what I may doing wrong? If so, can you either fork my sample repo or create your own and post it to GitHub?

**Comment by luisabreu** [comment]
Hello again.

I'm only using AzureAD (not B2C).

**Comment by halter73** [comment]
The sample is not that much different with Microsoft Entra ID. If you follow the steps at https://learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-microsoft-entra-id?view=aspnetcore-7.0 and skip the "Use of an Azure Active Directory B2C tenant", you can connect to a non-B2C tenant.

Can you please modify the sample at https://github.com/halter73/BlazorHostedWasmAAD/compare/main...halter73/entra to show what changes need to be made to repro the issue?

**Comment by luisabreu** [comment]
Hello again. I think I've got a log taken on the blazor side which might help understand what's going on
[Uploading login_callback_error2.log…]()
