### ISSUE TITLE
Mix static routing with webassemble (auto, etc) modes

### ISSUE THREAD

**Issue by CrahunGit** [dotnet/aspnetcore#54170]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I'm trying to create a web with public zone which navigates with ssr and admin zone which navigates with interactive router. Is there any way to have this 2 route modes? 

### Describe the solution you'd like

It would be fine to have the possibility to have one static router on normal project and another router on webassembly.

**Comment by javiercn** [comment]
@CrahunGit thanks for contacting us.

Setup your app as if you were using global interactivity and pass the `@rendermode` to the `Routes` component in `App.Razor` dynamically.

You can look at the current request endpoint metadata in `App.Razor` to get a hold of the `rendermode` used by the page.

**Comment by javiercn** [comment]
```
[CascadingParameter] public HttpContext Context { get; set; }

protected override OnInitialized()
{
    _renderMode = Context.GetEndpoint()!.Metadata.GetMetadata<RenderModeAttribute>().Mode;
}
```

(note that the above code is pseudocode, you'll have to slightly adjust it to compile).

**Comment by CrahunGit** [comment]
Thanks @javiercn . It worked fine. Just one drawback is if you go back with the brworser button from one interactive page to one ssr page you'll get not found until you refresh the page
