### ISSUE TITLE
Add pipeline that tests the latest IdentityModel nightlies

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/aspnetcore#54180]
Add pipeline that runs for 8.0 & main that grabs the latest IdentityModel packages from https://identitydivision.visualstudio.com/IDDP/_artifacts/feed/IDDP/NuGet/Microsoft.IdentityModel.Abstractions/, updates our dependency version in-place (https://github.com/dotnet/aspnetcore/blob/32c9ec8d9c4b7f7f544cfb39dbf31f30a860d585/eng/Versions.props#L14), and runs the relevant tests. @halter73 @eerhardt what test suites should we be running in this?

**Comment by halter73** [comment]
I'd consider running everything under `src/Security/Authentication`, `src/ProjectTemplates/test`, `src/Mvc/test/Mvc.FunctionalTests`.

**Comment by eerhardt** [comment]
https://grep.app/search?q=Reference.%2AIdentityModel&regexp=true&filter[repo][0]=dotnet/aspnetcore

That should list all the places we use IdentityModel. So any test that uses those libraries.

From @halter73's list, I'd also add

`src/Tools/dotnet-user-jwts/test`

**Comment by wtgodbe** [comment]
Done
