### ISSUE TITLE
Blazor app template does not respect RequireConfirmedAccount==false when changing email address

### ISSUE THREAD

**Issue by petergolde** [dotnet/aspnetcore#54207]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Create a new Blazor Web app with Authentication for individual accounts.

In Program.cs, change the SignIn option to: options.SignIn.RequireConfirmedAccounted=false

When you register an account (Account/Register), the template correctly checks this setting and does not attempt to send a confirmation email.

However, when you change your email via Account/Manage/Email, the template still tries to send an email confirmation.

### Expected Behavior

The template for Account/Manage/Email should check the setting of UserManager.Options.SignIn.RequireConfirmedAccount and not send a confirmation email if it is set to false, like Account register does.

### Steps To Reproduce

Create a new Blazor web app with authentication set to InvidualAccounts.

In Program.cs, change the line:

`builder.Services.AddIdentityCore<ApplicationUser>(options => options.SignIn.RequireConfirmedAccount = true)`

to 

`builder.Services.AddIdentityCore<ApplicationUser>(options => options.SignIn.RequireConfirmedAccount = false)`

Run, and Register a new account.

Note that it does not attempt to send an email. This is correct.

Once registered, click on your account email, and in the change account settings page, choose Email.

Choose a new email name and click Change Email.

Note that it still attempts to send an email. This is incorrect.

### .NET Version

8.0.200-preview.23624.5

**Comment by halter73** [comment]
> Run, and Register a new account.
>
> Note that it does not attempt to send an email. This is correct.

Register.razor sends an email regardless of the `RequireConfirmedAccount`, it simply does not require confirmation to sign in. `UserManager.IsEmailConfirmedAsync()` does reflect whether or not the confirmation link was clicked weather or not `RequireConfirmedAccount` is set to `true`.

https://github.com/dotnet/aspnetcore/blob/3e168fe85e2330621ed12d9c9524c80e0f743dc6/src/ProjectTemplates/Web.ProjectTemplates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/Components/Account/Pages/Register.razor#L92-L101

> Once registered, click on your account email, and in the change account settings page, choose Email.
> 
> Choose a new email name and click Change Email.
> 
> Note that it still attempts to send an email. This is incorrect.

I don't think attempting to send an email is a problem here, but I do see how requiring the email confirmation to update an existing account's email could be annoying considering that same user could register a new account without email confirmation. That said, it's easy to just change the code in Email.razor to call `UserManager.ChangeEmailAsync` like ConfirmEmailChange.razor, and Email.cshtml.cs has had this [same behavior](https://github.com/dotnet/aspnetcore/blob/3e168fe85e2330621ed12d9c9524c80e0f743dc6/src/Identity/UI/src/Areas/Identity/Pages/V5/Account/Manage/Email.cshtml.cs#L147) for a long time.

**Comment by mikekistler** [comment]
We think that this issue is fixed now. If you are still facing this problem, please file a new issue.
