### ISSUE TITLE
Allow access to the RequestDelegate instance from middleware 

### ISSUE THREAD

**Issue by jezzsantos** [dotnet/aspnetcore#54237]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am trying to get access to the instance of the `RequestDelegate` argument of a minimal API declaration from my own custom Middleware, rather than from a `IEndpointFilter`.

I need to do this to populate middleware with actual inbound values from the arguments from the request delegate in the handler.

I have standardized all the handlers to a known form, and each is defined by a class, like this:

```
myGroup.MapGet("/apath",  async (IMediator mediator, [AsParameters] MyRequest request) =>
                     await mediator.Send(request, CancellationToken.None))
```
At runtime, from middleware I simply want the instance of the `MyRequest` object.

I can easily get this from the `EndpointFilterInvocationContext` parameter of the `InvokeAsync()` method in a custom `IEndpointFilter`, but it is far too late in the request pipeline to capture there, long after my custom middleware has run.

Investigating how the `EndpointFilterInvocationContext` is constructed deep down within the `RequestDelegateFactory`, turns out to be very hard to access from middleware.

Surely, there has to be a way to do this from middleware?

### Describe the solution you'd like

Some way to access an instance of `EndpointFilterInvocationContext` or some other way to access the equivalent `Arguments` that it gives access to. And to do that from custom middleware.

**Comment by davidfowl** [comment]
There’s no way to get the arguments for middleware, it’s too early and they haven’t even been parsed as yet. This is the main reason why filters exist. They have the endpoint context, including arguments.

**Comment by jezzsantos** [comment]
Thanks @davidfowl,
Understood. Appreciate where you are coming from.

Okay, 
turns out that what I really need in my Authorization middleware (within a `AuthorizationHandler<T>`) is specific data from the body of the request.

We have built an abstraction (over minimal APIs) that gives us certainty about the type of the 2nd parameter in any handler, so that we can be consistent and predictable about its form in all cases (of the ones we need to deal with). 

For example, these are the two forms (the only real difference is the use of `[AsParameters]` for GET, DELETE operations:
```
           myGroup.MapDelete("/myresource/{id}",
                async (IMediator mediator, [AsParameters] DeleteResourceRequest request) =>
                     await mediator.Send(request, CancellationToken.None))
                .RequireAuthorization("Token")
                .RequireCallerAuthorization("POLICY:{|Features|:{|Tenant|:[|paidtrial_features|]},|Roles|:{|Tenant|:[|member|]}}");
            myGroup.MapPost("/myresource",
                async (IMediator mediator, CreateResourceRequest request) =>
                     await mediator.Send(request, CancellationToken.None))
                .RequireAuthorization("Token")
                .RequireCallerAuthorization("POLICY:{|Features|:{|Tenant|:[|paidtrial_features|]},|Roles|:{|Tenant|:[|member|]}}");
```

All we really need to do is know the actual runtime type of the 2nd parameter in the handler, and then if it is of certain type (say, derived from `ITenantedRequest`) then extract a certain known field of the class (in this case we want the `TenantId` field from the `ITenantedRequest`).

Then we can feed that into the Authorization middleware and authorize the call correctly (based on the specific Tenant from this specific example). (sidenote, our actual role claims - in the JWT token - contain tenant-specific roles, that need to be verified)

So, given that I can get the type of the 2nd parameters of the handler like this, from anywhere in middleware:
```
        var endpoint = httpContext.GetEndpoint();
        var method = endpoint.Metadata.GetMetadata<MethodInfo>();
        var args = method?.GetParameters();
        var requestDtoType = args?[1].ParameterType;
        if (requestDtoType.IsAssignableTo(typeof(ITenantedRequest)))
        {
            tenantId = requestDtoType.As<ITenantedRequest>().TenantId;
        }
```

to get my runtime type, 
all I would need to know is how to apply the `HttpRequest` to that specific type to see whether the Body contains the `TenantId` field I am looking for, in the case of POST, PATCH, or PUT requests.
Either as an incoming JSON body, a MultiPartFormData body, or an XML body.

I know this will incur body rewinding, so my question is:

Is there anything in the framework that can make this part easier for me to search the body for a specific field, given it will be shaped by a known runtime type?

For example, the body could take this form:

```
[Route("/bookings", ServiceOperation.Post, AccessType.Token)]
[Authorize(Roles.Tenant_Member, Features.Tenant_PaidTrial)]
public class MakeBookingRequest : ITenantedRequest<MakeBookingResponse>
{
    public required string TenantId { get; set; }

    public required string CarId { get; set; }

    public DateTime? EndUtc { get; set; }

    public required DateTime StartUtc { get; set; }
}
```

**Comment by captainsafia** [comment]
@jezzsantos If I'm understanding correctly, you're trying to access the tenant ID assocaited with the request in your custom authorization middleware. Would it be possible to encode the tenant ID in your claims principal and resolve it from there?

**Comment by jezzsantos** [comment]
Thanks for the suggestion @captainsafia 

This approach may work for certain kinds of systems but probably not in general for most systems. (particularly the kind we are building towards)

That's because of these things:
* the anonymous user would not have any claims, so you would not know what tenancy they desire to access in each request.
* In systems, where the membership to several tenants changes over time, the claims in access_tokens would need to be forceably refreshed when the membership changes. That has all kinds of downstream issues.
* Many systems in general declare the tenant id in other places in the request (i.e. host headers, query prams, body, headers etc) which is better usability for API consumers than in transparent tokens.
