### ISSUE TITLE
[NETSDKE2E]The hyperlink "https://aka.ms/aspnetcore/9.0-third-party-notices" could not be redirected to the correct page.

### ISSUE THREAD

**Issue by vdanche** [dotnet/aspnetcore#54254]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The hyperlink "https://aka.ms/aspnetcore/9.0-third-party-notices" could not be redirected to the correct page.
![image](https://github.com/dotnet/aspnetcore/assets/65637796/a5c448e2-8c64-45fd-ada6-2193efe2da00)

### Expected Behavior

The hyperlink "https://aka.ms/aspnetcore/9.0-third-party-notices" could be opened normally.

### Steps To Reproduce

1. install net9 preview 2 sdk -9.0.100-preview.2.24127.11
2. dotnet new razor
3. the hyperlink "https://aka.ms/aspnetcore/9.0-third-party-notices" is displayed and open the hyperlink via Ctrl + Click

### .NET Version
.NET SDK:
 Version:           9.0.100-preview.2.24127.11
 Commit:            2ffb0c6248
 Workload version:  9.0.100-manifests.afec3a68
 MSBuild version:   17.10.0-preview-24122-01+d4cb14fe4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.25398
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\9.0.100-preview.2.24127.11\

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      9.0.0-preview.2.24126.6
  Architecture: x64
  Commit:       0789f3b354

.NET SDKs installed:
  9.0.100-preview.2.24127.11 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 9.0.0-preview.2.24126.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 9.0.0-preview.2.24126.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 9.0.0-preview.2.24126.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

_No response_

**Comment by mkArtakMSFT** [comment]
We usually do this close to the release, so that the branches are finalized. But I've done this for now (pointing to the release/9.0-preview2 branch): https://aka.ms/aspnetcore/9.0-third-party-notices
Will update the link later in the release.
