### ISSUE TITLE
Blazor Component (using RenderMode Interactive Server) - Incorrect Behavior on Navigating between pages, Component is not re-created

### ISSUE THREAD

**Issue by htmlsplash** [dotnet/aspnetcore#54263]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have 2 pages, Page1, Page2. Both pages use the same Counter component with render mode: interactive server that is specified on the Counter components. 

`<Counter @rendermode="InteractiveServer"></Counter>`

NOTE: The Counter component inside its mark up does not specify render mode.
Each page also contains a navigation link to the other page.

When a user is on Page1 and increments the counter and then navigates (using anchor link) to Page 2 (that has also a Counter) the count is retained from Page1. Then, incrementing Counter on Page2 continues the count. When user navigates back Page1 (using anchor link) the count is now the sum of counts from Page1 and Page2.

### Expected Behavior

I expect the component to be re-created and its state reset once a user navigates to another page from current page.
That does not happen. The counter component appears to live (and retain its state) across page navigations using an anchor tag.

_If this is the correct behavior for an interactive server side component using web socket connection in an SSR page then how can we re-use components across pages without retaining component state?_

### Steps To Reproduce

Create a sample SSR blazor app, select interactivity per component. 
Create 2 pages.
Place Counter component on both pages.
NOTE: Remove from the Counter component the "@rendermode InteractiveServer", instead place render modes explicitly where you use the counter on each page as:

`<Counter @rendermode="InteractiveServer"></Counter>`

Add this mark up to navigate between the pages:

`<a href="/Page2">Go to page 2</a>`

`<a href="/Page1">Go to page 1</a>`

Go to page 1, increment counter, use link to go to page 2 (observe the count is from page 1). Increment counter again and go back to page 1 (observe the count continues from page 2).

### .NET Version

.net 8 Blazor SSR Interactive Server

**Comment by htmlsplash** [comment]
UPDATE: Interesting observation

If I inject into the SSR Page1 (or Page2) current user accessed from current Http context and pass that to the Counter component as a parameter, that triggers/forces the component to be re-created and the component state is reset.

This behavior is opposite to the re-use of the component across pages behavior reported above.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This behavior is by design and it's done to optimize DOM manipulations. The framework tries to retain as much of the content in the page as possible, so that only minimal changes are applied. In your case, you don't want this behavior, and you can control that by applying the `@key` directive to the `Counter` components on each page, specifying different values, so that the DOM Merging algorithm doesn't think that they're the same component to be preserved.

**Comment by htmlsplash** [comment]
Thanks, that resolved the issue. I don't want to be a party pooper but I think this is a dangerous default. 

Imagine a page (Page1) with many components and then another unrelated page (Page10) has also many components but one of these components is the same as on Page1. This will result in the component (and its state) to appear on Page10 (from Page1). 
To make matters worse, consider an example of user page navigation that is considered a normal flow: 

Page1, Page2, Page3. 

But in a rare case when the user performs some action that allows them to navigate like this: 

Page1, Page10, Page2, Page3.

Now you have this rare bug surface itself on the site because when going from Page1 to Page10, or from Page10 to Page1 will share the same component with its state.

With the workaround solution (in a framework were component re-use is common) and to avoid this default sharing behavior is to specify a key on every component placed on page at all times.  Otherwise, inadvertently, you might end up with undesired behavior. I wonder if could better then this?
