### ISSUE TITLE
.NET 8 Blazor - Cannot Set CloseOnAuthenticationExpiration With Global Interactive Rendering / InteractiveServerRenderMode

### ISSUE THREAD

**Issue by sbwalker** [dotnet/aspnetcore#54296]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When creating a Blazor application for .NET 8 using Global Interactive Rendering / InteractiveServerRenderMode and using cookie authentication, you often need the ability for users to be able to set an auth cookie with an expiry date. 

InteractiveServerRenderMode uses SignalR which associates a user with each connection. If the cookie expires during the lifetime of a connection, by default the connection continues to be active and the authState.User.Identity.IsAuthenticated returns True. 

The official guidance is that for connections to close when the authentication cookie expires, you needed to set the CloseOnAuthenticationExpiration property to true.

In versions of .NET prior to .NET 8 this looked like:

```
app.MapBlazorHub(option =>   
{  
    option.CloseOnAuthenticationExpiration = true; 
});  
```

However in .NET 8 if you try to set this property, it will throw an error:

An unhandled exception was thrown by the application.
Microsoft.AspNetCore.Routing.Matching.AmbiguousMatchException: The request matched multiple endpoints. Matches: 
Blazor initializers
allback {*path:nonfile}

(note that in this case a fallback route is being used).

The inability to set this property means that authState.User.Identity.IsAuthenticated remains True after a Cookie has expired.

### Expected Behavior

There should be a way to set the CloseOnAuthenticationExpiration property in .NET 8 which allows cookie expiration to work as expected. 

### .NET Version

8.0

**Comment by sbwalker** [comment]
Is the IdentityRevalidatingAuthenticationStateProvider class intended to address this scenario when using Identity auth with Blazor in .NET 8? It executes server-side... but only validates every 30 minutes by default so it does not seem to align with this use case.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @sbwalker. This is a dupe of https://github.com/dotnet/aspnetcore/issues/54080#issuecomment-1984428323
