### ISSUE TITLE
Blazor static assets not found (404) when environment is non-Development

### ISSUE THREAD

**Issue by dino182** [dotnet/aspnetcore#54291]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The `styles bundle` and `dotnet.js` assets return a HTTP 404 error when the dotnet environment is anything other than `Development`. E.g.

![image](https://github.com/dotnet/aspnetcore/assets/70717641/59fc602a-6b93-4895-912f-f6c970dda86b)

![image](https://github.com/dotnet/aspnetcore/assets/70717641/7bb9575d-0364-46df-9a8f-372948973f90)

### Expected Behavior

The assets should be found exactly as they are when the dotnet environment is `Development`. E.g.

![image](https://github.com/dotnet/aspnetcore/assets/70717641/48d1995a-bdd5-4507-b5f8-d45a4e2286dd)

![image](https://github.com/dotnet/aspnetcore/assets/70717641/c81bfd82-333b-4d67-8f1b-9218e41aad7d)

### Steps To Reproduce

* Create a project from the standard `Blazor Web App` template e.g.
![image](https://github.com/dotnet/aspnetcore/assets/70717641/029d703c-96f2-4109-8d55-1cfa35236e68)
* Launch the application with a specific environment either by:
  * changing the `ASPNETCORE_ENVIRONMENT` value in the `launchSettings.json` file e.g.
  ![image](https://github.com/dotnet/aspnetcore/assets/70717641/e8cb1236-0680-47e0-872f-68b41fe51e87)
  * using the terminal command `dotnet run --environment Staging`

### .NET Version

8.0.200

### Anything else?

IDE = Visual Studio 2022 version 17.9.2
If I publish the project as a Web Deploy package and host it on IIS, it all works perfectly fine.
I have also tried `dotnet run --environment Staging -c Release` but this results in the 404 Not Found status code.
Am I doing something wrong?

**Comment by DawgCoder** [comment]
Can confirm that I have this issue as well. .NET 8 Blazer Web App (Server)

**Comment by dino182** [comment]
Upon deeper inspection of the project files I encountered the `<StaticWebAssetProjectMode>Default</StaticWebAssetProjectMode>` property in the `.Client` project.
This led me to issue https://github.com/dotnet/AspNetCore.Docs/issues/31658 and the associated documentation https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/static-files.
As described in the **Static files in non-Development environments** section, a call to `builder.WebHost.UseStaticWebAssets()` is required in order for the static assets to be served correctly.
