### ISSUE TITLE
Blazor Server .NET 8 SEO Problem head tags

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#54300]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Blazor-Server-NET-8-SEO-Problem-head-ta/10602615)._

---
[severity:Other]
I have a Blazor Server App. using .NET 8. I have included my scripts and tags in head section of app.razor. These seem to be working well. I also have meta tags in my web pages which are populated dynamically - depending on the page content - by razor `@code{}` These are placed in `<HeadContent>` section. Although these appear in the browser devtools inspect windows, Google and Bing crawlers are not picking it up. I tried various interactive render modes trying to make it static. None of them work. My whole site appears to be missing essential tags like meta description, title even `<h1>` tags on the page. This isn't very good because I found this out after doing the whole website. It looks like it has no SEO whatsoever and I can't put those tags for search engine crawlers to see! Should I give up on this platform or will there be some kind of fix for this?

---
#### baktay2000 on 2/27/2024, 07:48 AM: 

(private comment, text removed)
#### Feedback Bot on 2/27/2024, 11:26 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by MackinnonBuck** [comment]
Thanks for reaching out. In order for `<head>` content to get picked up for SEO, the content needs to be rendered during the static server rendering (prerendering) phase. Dynamically-generated `<head>` content won't get picked up.
