### ISSUE TITLE
.NET 8 Blazor (Server with new template) - Issue with WS-Federation ChallengeAsync throwing a runtime exception

### ISSUE THREAD

**Issue by DawgCoder** [dotnet/aspnetcore#54305]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a .NET 8 Blazor web app that I've migrated from .NET 7. We use WS-Federation for authentication. When I make a call to `await HttpContext.ChallengeAsync(WsFederationDefaults.AuthenticationScheme, new AuthenticationProperties { RedirectUri = requestedUri });` in my login controller I get the following exception:

````
System.ObjectDisposedException
  HResult=0x80131622
  Message=IFeatureCollection has been disposed.
Object name: 'Collection'.
  Source=Microsoft.Extensions.Features
  StackTrace:
   at Microsoft.AspNetCore.Http.Features.FeatureReferences`1.ThrowContextDisposed()
   at Microsoft.AspNetCore.Http.Features.FeatureReferences`1.Fetch[TFeature,TState](TFeature& cached, TState state, Func`2 factory)
   at Microsoft.AspNetCore.Http.Features.FeatureReferences`1.Fetch[TFeature](TFeature& cached, Func`2 factory)
   at Microsoft.AspNetCore.Http.DefaultHttpRequest.get_Scheme()
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.BuildRedirectUri(String targetPath)
   at Microsoft.AspNetCore.Authentication.WsFederation.WsFederationHandler.<HandleChallengeAsync>d__9.MoveNext()
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.<ChallengeAsync>d__60.MoveNext()
   at Microsoft.AspNetCore.Authentication.AuthenticationService.<ChallengeAsync>d__15.MoveNext()
   at Redacted.Controllers.LoginController.<Login>d__2.MoveNext() in C:\Temp\Redacted\Controllers\LoginController.cs:line 15

  This exception was originally thrown at this call stack:
    [External Code]
    Redacted.Controllers.LoginController.Login() in LoginController.cs
````

Here's the code:

```csharp
public class LoginController : Controller
{
    protected IQueryCollection Query => Request.Query;

    [HttpGet("account/login")]
    public async void Login()
    {
        var requestedUri = Query["$Filter"].ToString().Replace("i =>", "");
        await HttpContext.ChallengeAsync(WsFederationDefaults.AuthenticationScheme, new AuthenticationProperties { RedirectUri = requestedUri });
    }
}

public class LoginService
{
    private readonly NavigationManager _navigationManager;

    public LoginService(NavigationManager navigationManager)
    {
        _navigationManager = navigationManager;
    }

    public void Login(Query query) // Query is from the Radzen libary
    {
        _navigationManager.NavigateTo(query != null ? query.ToUrl("account/login") : "account/login", true);
    }
}

public void LogInButtonClicked()
{
   // Query is from the Radzen libary
    var query = new Query { Filter = $"{NavigationManager.BaseUri}default" };
    LoginService.Login(query);
}
```

Program.cs
=================================================================

```csharp
var builder = WebApplication.CreateBuilder(args);

builder.Services.AddRazorComponents().AddInteractiveServerComponents();
builder.Services.AddControllers();
builder.Services.AddRadzenComponents();
builder.Services.AddHttpClient();
builder.Services.AddAuthentication(
       sharedOptions =>
       {
           sharedOptions.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
           sharedOptions.DefaultChallengeScheme = WsFederationDefaults.AuthenticationScheme;
       }).AddWsFederation(options =>
       {
           //options.TokenHandlers.Add(new CustomSamlSecurityTokenHandler());
           builder.Configuration.Bind("WsFederation", options);
           options.AllowUnsolicitedLogins = false;           
       }).AddCookie();

builder.Services.AddScoped<LoginService>();

var app = builder.Build();

if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Error", createScopeForErrors: true);
    app.UseHsts();
}

app.UseHttpsRedirection();
app.MapControllers();
app.UseStaticFiles();
app.UseAuthentication();
app.UseAntiforgery();
app.MapRazorComponents<App>().AddInteractiveServerRenderMode();

app.Run();
```

### Expected Behavior

This code worked in Blazor Server .NET 5, 6 and 7 and should prompt for my credentials then navigate to the default page of the web application.

### Steps To Reproduce

Just add WS-Fed to a new .NET 8 Blazor Server web app. You will need to have ADFS configured. Add a login button that calls HttpContext.ChallengeAsync

### .NET Version

.NET 8

### Anything else?

My sample using Radzen UI framework. Update, I created a plain old .NET 8 Razor web application and got the very same error. Noticed this got tagged for blazor but the issue should be tagged with asp.net core authentication.

**Comment by MackinnonBuck** [comment]
Thanks for reaching out. Could you please clarify whether this is reproducible without Blazor?

**Comment by DawgCoder** [comment]
@MackinnonBuck - Yes I can reproduce without Blazor. I created a Razor Web App and was able to see the exact same error

**Comment by DawgCoder** [comment]
> Thanks for reaching out. Could you please clarify whether this is reproducible without Blazor?

@MackinnonBuck - Yes, I can reproduce with a simple Razor Web App so it's not Blazor related.

**Comment by DawgCoder** [comment]
@MackinnonBuck - Here's a link to the repo: https://github.com/DawgCoder/WSFedBug/tree/main

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Can you please replace your Login action to return `Task` instead of `void`. That should be the cause for the problem here:

```csharp
public async Task Login()
```

**Comment by DawgCoder** [comment]
> Thanks for contacting us. Can you please replace your Login action to return `Task` instead of `void`. That should be the cause for the problem here:
> 
> ```cs
> public async Task Login()
> ```
> 
> Detecting these types of issues is something we want to help with and we track that work as part of #28217

@mkArtakMSFT 
That did not resolve the issue. It basically navigates to the URL https://redacted.com/account/login?$filter=https%3A%2F%2Fredacted.com%2Fdefault but doesn't prompt me for my CAC credentials. I turned on detailed errors and check the logs and there are no errors in the log.

**Comment by DawgCoder** [comment]
@mkArtakMSFT - Can you please unresolve this issue and assign to someone on the WS-Federation team?

**Comment by mkArtakMSFT** [comment]
@DawgCoder thanks for additional details. While we do our best to look through all the issues filed here, we are not a general-purpose forum. This particular request doesn't seem to be happening to many customers so to get a faster help we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com).
