### ISSUE TITLE
Converting existing Blazor Hosted project to Blazor Web App resulting in missing index.html

### ISSUE THREAD

**Issue by manuelelucchi** [dotnet/aspnetcore#54313]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have this existing Blazor Hosted project (Client + Shared + Server) that I migrated without problems to .NET 8. I then tried experimenting with the new Interactivity features and after following the documentation, when I start the project and navigate to the entrypoint it gives me a 404 with the following log
```
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost/ - - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost/ - 404 0 - 10.0613ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[16]
      Request reached the end of the middleware pipeline without being handled by application code. Request path: GET http://localhost/, Response status code: 404
```
Like it's missing the generated `index.html`. I tried publishing the project and the `index.html` seems correctly generated from the `App.razor`
This behavior doesn't happen in another project I converted in the same way (below the passages).

### Expected Behavior

The endpoint should hit the `index.html` correctly

### Steps To Reproduce

Starting from an existing Blazor Hosted project converted to .NET 8

- Moved the `App.razor` content into a `Routes.razor`
- Moved `App.razor` from the client to the server (under `/Components`) and copied the `index.html` component so that `App.razor` looks like this
```razor
<!DOCTYPE html>
<html>
<head>
      <!-- Stuff -->
</head>

<body>
    <Routes @rendermode="new InteractiveAutoRenderMode(prerender: false)" /> 

    <!-- Stuff -->

    <script src="_framework/blazor.web.js"></script>
</body>
</html>
```
(I need `prerender: false` since I use local storage)
- Deleted the index.html
- Deleted `builder.RootComponents.Add<App>("#app");` from the Program.cs in the Client
- In the Server project, I added the following lines
```csharp
builder.Services.AddRazorComponents()
	.AddInteractiveServerComponents()
	.AddInteractiveWebAssemblyComponents();
```
and before `app.MapRazorPages()`
```csharp
app.MapRazorComponents<App>()
	.AddInteractiveServerRenderMode()
	.AddInteractiveWebAssemblyRenderMode()
	.AddAdditionalAssemblies(typeof(_Imports).Assembly);
```

### .NET Version

8.0.200

### Anything else?

.NET SDK:
 Version:           8.0.200
 Commit:            438cab6a9d
 Workload version:  8.0.200-manifests.5638171e

Ambiente di runtime:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.200\

Carichi di lavoro .NET installati:
 [ios]
   Origine dell'installazione: SDK 8.0.200, VS 17.9.34616.47
   Versioni del manifesto:    17.2.8022/8.0.100
   Percorso del manifesto:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.ios\17.2.8022\WorkloadManifest.json
   Tipo di installazione:        FileBased

 [wasm-tools]
   Origine dell'installazione: SDK 8.0.200
   Versioni del manifesto:    8.0.2/8.0.100
   Percorso del manifesto:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.workload.mono.toolchain.current\8.0.2\WorkloadManifest.json
   Tipo di installazione:        FileBased

 [maui-windows]
   Origine dell'installazione: VS 17.9.34616.47
   Versioni del manifesto:    8.0.6/8.0.100
   Percorso del manifesto:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maui\8.0.6\WorkloadManifest.json
   Tipo di installazione:        FileBased

 [maccatalyst]
   Origine dell'installazione: VS 17.9.34616.47
   Versioni del manifesto:    17.2.8022/8.0.100
   Percorso del manifesto:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maccatalyst\17.2.8022\WorkloadManifest.json
   Tipo di installazione:        FileBased

 [android]
   Origine dell'installazione: VS 17.9.34616.47
   Versioni del manifesto:    34.0.79/8.0.100
   Percorso del manifesto:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.android\34.0.79\WorkloadManifest.json
   Tipo di installazione:        FileBased

Host:
  Version:      8.0.2
  Architecture: x64
  Commit:       1381d5ebd2

.NET SDKs installed:
  8.0.200 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.27 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by manuelelucchi** [comment]
I'm definitely not able to reproduce. I tried to create a .NET 7 Blazor Hosted project, converted to .NET 8 Web App and it works. I have no clue of what could be the difference, the steps I pointed above are the same for both my projects (and in one they work) and the repro.

I tried publishing both my projects and noticed they both don't have the `index.html` in the `wwwroot1 folder, so I assume the `MapRazorComponents` registers a middleware that generates the `index.html` per requests based on the `App.razor` and for some reasons on a single project out of three it doesn't work. 

There surely something wrong on my part but the question is what? Is there something that could interfere with the Middleware? My configuration (in Development env) is as follows 
```csharp
app.UseDeveloperExceptionPage();
app.UseWebAssemblyDebugging();

app.UseMigrationsEndPoint();
app.UseSwagger();
app.UseSwaggerUI(options =>
{
    // Stuff
});

app.UseBlazorFrameworkFiles();
app.UseStaticFiles();

app.UseRouting();
app.UseAntiforgery();

app.UseRequestLocalization(options =>
{
	// Stuff
});

app.UseAuthentication();
app.UseAuthorization();

app.MapRazorComponents<App>()
	.AddInteractiveServerRenderMode()
	.AddInteractiveWebAssemblyRenderMode()
	.AddAdditionalAssemblies(typeof(_Imports).Assembly);

app.MapRazorPages();
app.MapControllers();

app.Run();
```

The rest is as I specified above

**Comment by mkArtakMSFT** [comment]
Thanks @manuelelucchi. This seems to be an issue specific to your project / migration. For these situations we recommend you post a question to the [StackOverflow](https://stackoverflow.com) forum to get help faster.

**Comment by aledamen** [comment]
Hello, could you fix this issue? I have the same problem.

Thanks!

**Comment by ar1002-scarecrow** [comment]
Same issue. Need solution if anyone has any suggestion, i'm all ears
