### ISSUE TITLE
Documentation for integrating azure b2c on blazor interactive mode auto .net 8

### ISSUE THREAD

**Issue by vivekgalominds** [dotnet/aspnetcore#54310]
Cant find documentation for azure b2c interactive Auto for blazor .net 8

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We've already documented this scenario here: https://learn.microsoft.com/aspnet/core/blazor/security/server/blazor-web-app-with-oidc?view=aspnetcore-8.0&pivots=without-bff-pattern
