### ISSUE TITLE
Update to React 17

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#5432]
Unknown release date: https://github.com/facebook/react/milestone/40

**Comment by ryanbrandenburg** [comment]
Looks like they won't be done for preview5, bumping to preview6.

**Comment by mkArtakMSFT** [comment]
We've moved this issue to the Backlog milestone. This means that it is not going to be worked on for the coming release. We will reassess the backlog following the current release and consider this item at that time. To learn more about our issue management process and to have better expectation regarding different types of issues you can read our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md).

**Comment by HaoK** [comment]
Capturing the process for future CTIs workflow

- (prequities node >= 10.16, npm >= 5.6)
- `npx create-react-app reactapp` (create a new react app)
