### ISSUE TITLE
Minimal API does not return ProblemDetails traceid on Exception

### ISSUE THREAD

**Issue by RandomBuffer** [dotnet/aspnetcore#54325]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When and **Exception** is thrown then **Minimal API** returns **ProblemDetails** without **traceid** even though it is available. This happens in all environments and is in contrast with **Controller API**s which does log **traceid** in all scenarios. It would be good if this was automatically included and both exhibited the same behaviour. A workaround is to manually add **traceid** to **ProblemDetails.Extensions** like below. Please see the test below to reproduce.

### Expected Behavior

**Minimal API** should return **ProblemDetails**  **traceid**  just like **Controller API**s do like below.

### Steps To Reproduce

**Minimal API Test**
1 - Create a new **Minimal API** project.

2 - Enable **ProblemDetails** like below.
```
builder.Services.AddProblemDetails(po => po.CustomizeProblemDetails = pc =>
{
    pc.ProblemDetails.Extensions.Add("testSpanId", Activity.Current.SpanId.ToString());
    pc.ProblemDetails.Extensions.Add("testTraceId", Activity.Current.TraceId.ToString());
    pc.ProblemDetails.Extensions.Add("testId", Activity.Current.Id);
});
```

3 - Optionally enable ExceptionHandler like below.
`app.UseExceptionHandler();`

4 - Add test endpoint like below
```
app.MapGet("/test", () =>
{
    throw new NotImplementedException();
});
```

5 - Run project and hit the Minimal endpoint and notice the **ProblemDetails** does not include the **traceid** like below.
```
{
  "type": "https://tools.ietf.org/html/rfc9110#section-15.6.1",
  "title": "An error occurred while processing your request.",
  "status": 500,
  "testSpanId": "b462c6e945fce474",
  "testTraceId": "3949b14c78afa8febf630c6ab7b9b990",
  "testId": "00-3949b14c78afa8febf630c6ab7b9b990-b462c6e945fce474-00"
}
```

**Controller API Test**
1 - Create a new **Controller API** project.

2 - Add the above sample code.

3 - Additionally Add code to throw an **Exception** from the Controller Action.

4 - Run project and hit the Controller Endpoint and notice the **ProblemDetails** includes the **traceid** like below.
```
{
  "type": "https://tools.ietf.org/html/rfc9110#section-15.6.1",
  "title": "An error occurred while processing your request.",
  "status": 500,
  "traceId": "00-a6d6b1be7ff2d0ead53fabf178be6d71-a71db9a8a184fdec-00",
  "testSpanId": "a71db9a8a184fdec",
  "testTraceId": "a6d6b1be7ff2d0ead53fabf178be6d71",
  "testId": "00-a6d6b1be7ff2d0ead53fabf178be6d71-a71db9a8a184fdec-00"
}
```

### .NET Version

8.0.200

### Anything else?

.NET SDK:
 Version:           8.0.200
 Commit:            438cab6a9d
 Workload version:  8.0.200-manifests.cdf2cc8e

Runtime Environment:
 OS Name:     debian
 OS Version:  
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/8.0.200/

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.2
  Architecture: x64
  Commit:       1381d5ebd2

.NET SDKs installed:
  8.0.200 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by tcortega** [comment]
> @RandomBuffer Thanks for reporting this issue! I believe this is happening because the `DefaultProblemDetailsFactory` in MVC handles populating the traceId field [here](https://github.com/dotnet/aspnetcore/blob/87cde8081456ce60ad4d233361bcd07f90dc977b/src/Mvc/Mvc.Core/src/Infrastructure/DefaultProblemDetailsFactory.cs#L92-L96) but the DefaultProblemDetailsWriter used in minimal APIs doesn't.
> 
> You can use the `CustomizeProblemDetails` you used above to populate the `traceId`.
> 
> Alternatively, we'd welcome a PR updating the `WriteAsync` implementation in `DefaultProblemDetailsWriter` to set the traceId similar to what MVC does (see [here](https://github.com/dotnet/aspnetcore/blob/87cde8081456ce60ad4d233361bcd07f90dc977b/src/Http/Http.Extensions/src/DefaultProblemDetailsWriter.cs#L52)).

I'd like to take this one if possible and @RandomBuffer doesn't want to work on it.

**Comment by captainsafia** [comment]
@tcortega Absolutely! Happy to review a PR from you if you're able to send one.

**Comment by RandomBuffer** [comment]
Hi @tcortega please go ahead and submit PR

**Comment by tcortega** [comment]
Alright then. @captainsafia feel free to assign to me if you want, I plan on taking a look at it tomorrow, a bit busy today.
