### ISSUE TITLE
JWT Token Validation Fails after Upgrade from .NET 6 to .NET 8

### ISSUE THREAD

**Issue by rustam-ashurov-mcx** [dotnet/aspnetcore#54321]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Today we updated our codebase from .net 6 to .net 8. Setup is simple - Web-based FE, BE based on ASP.NET and Identity Provider as a separate web service. After updating our BE to .net 8 and all dependent packages to the newest versions all incoming HTTP requests started to fail with:

`Microsoft.IdentityModel.Tokens.SecurityTokenSignatureKeyNotFoundException: IDX10500: Signature validation failed. No security keys were provided to validate the signature.`

The Program.cs file contains auth configuration which worked for 2 years without issues, so I can say they are simple and tested:

`builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddJwtBearer(JwtBearerDefaults.AuthenticationScheme, opts =>
    {
        opts.Authority = "http://our-identity-server";
        opts.RequireHttpsMetadata = false;

        opts.TokenValidationParameters = new()
        {
            ValidIssuer = "http://our-identity-server",
            ValidateIssuer = true,
            ValidAudiences = ["our-frontend"],
            ValidateAudience = true
        };
    });`

What I've tried to investigate the reason already :
- Check identity provider, it is also based on .NET and was updated to .NET 8. In general, it works fine, able to generate JWT token, gives configurations with well known URLs, and returns public key information.
- FE is able to get before-mentioned configs from provider, issue a valid token, and send it with requests to the BE
- BE receives "Bearer ..." token in request headers, token contains all valid and expected data as issuer, audience, roles, etc.
- I tried to put some callbacks on auth events but the one that reacts on incoming requests is useful only to review auth header, and the one that reacts on auth failure doesn't contain anything what could help me (or maybe I'm not aware what to search for). For sure event related to successful authorization is never called.
- I tried to find any backward incompatible changes in .NET 7 and 8 as well as in libraries like Microsoft.AspNetCore.Authentication.JwtBearer, but it looks like nothing major was introduced, at least for such a simple auth configuration setup as ours.
- I checked whether there is in network configs, but curl from host with BE works flawlessly reaching identity-provider and it's endpoints such us jwks to get public key or configurations for endpoints metadata.

Is there any option to debug things deeper and understand what exactly is failing on BE side? Or maybe it's a well known issue related to upgrade from .NET 6 to .NET 7 or 8? I found this thread and the last comment looks like our use case, however that thread was closed and person question was unanswered: https://github.com/dotnet/aspnetcore/issues/52075

### Expected Behavior

After upgrade from .NET 6 to .NET 7 or 8 our solution still works fine

### Steps To Reproduce

I can not share the code. And can imagine that obvious answer is "it depends" since maybe something else is failing auth process. Still it worked for 2 years with no issues, and we are not really using anything extra for our auth. I really hope it's something obvious for .NET community what I just missed with .NET updates or there is an option to at least debug it better.

### Exceptions (if any)

[INF] Failed to validate the token.
Microsoft.IdentityModel.Tokens.SecurityTokenSignatureKeyNotFoundException: IDX10500: Signature validation failed. No security keys were provided to validate the signature.
   at Microsoft.IdentityModel.JsonWebTokens.JsonWebTokenHandler.ValidateSignature(JsonWebToken jwtToken, TokenValidationParameters validationParameters, BaseConfiguration configuration)
   at Microsoft.IdentityModel.JsonWebTokens.JsonWebTokenHandler.ValidateSignatureAndIssuerSecurityKey(JsonWebToken jsonWebToken, TokenValidationParameters validationParameters, BaseConfiguration configuration)
   at Microsoft.IdentityModel.JsonWebTokens.JsonWebTokenHandler.ValidateJWSAsync(JsonWebToken jsonWebToken, TokenValidationParameters validationParameters, BaseConfiguration configuration)

### .NET Version

8.0.2

### Anything else?

  Version:      8.0.2
  Architecture: x64
  Commit:       1381d5ebd2
  RID:          linux-x64

**Comment by rustam-ashurov-mcx** [comment]
It looks like in one of the libraries we used as dependency for simplifying the HTTP REST communication by http clients this line was used:

`var jwtSecurityToken = new JwtSecurityToken(_bearerToken);`

as well as this library to have JwtSecurityToken class:

`<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.4.0" />`

After changing code to:

`var jwtSecurityToken = new JsonWebToken(_bearerToken);`

and dependency to:

`<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.2" />`

Everything start working. 

I am not sure why it behaves like this since token validation logic in REST endpoints is not using this code logic, the code I shared is used when our BE service is Calling other services via REST on its own behalf. I would expect exceptions on sending HTTP requests for some business logic, but once again this code was not used for token validation or anything related to default HTTP communication outside our business logic HTTP clients.

Maybe there are some conflicts between libraries and they can not be used together in one solution, but I don't see information on the internet about it.

Maybe someone can comment on it, since possible I'm not alone in such situation after upgrade to .NET 8

**Comment by huangzhengguo** [comment]
I also ran into questions about JWT when I upgrade from 7.0 to 8.0，I use JsonWebTokenHandler replace JwtSecurityTokenHandler and add System.IdentityModel.Tokens.Jwt to resolve the issue
`        var securityTokenDescriptor = new SecurityTokenDescriptor()
        {
            Issuer = issuer,
            Claims = dicClaims,
            Audience = audience,
            Expires = expires,
            SigningCredentials = signingCredentials
        };
        var jsonWebTokenHandler = new JsonWebTokenHandler();

        return jsonWebTokenHandler.CreateToken(securityTokenDescriptor);`

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This was indeed a breaking change that we've discussed in the linked issue. Specifically, this comment from @halter73 is what you should try to follow: https://github.com/dotnet/aspnetcore/issues/52075#issuecomment-1815025177

**Comment by harman0711** [comment]
I had the same issue but it was resolved by adding <PackageReference Include="Microsoft.IdentityModel.Protocols.OpenIdConnect" Version="7.5.0" />. https://github.com/dotnet/aspnetcore/issues/52330#issuecomment-1976336097

**Comment by dramsey-dev** [comment]
> I had the same issue but it was resolved by adding `<PackageReference Include="Microsoft.IdentityModel.Protocols.OpenIdConnect" Version="7.5.0" />`
> 
> [https://github.com/dotnet/aspnetcore/issues/52330#issuecomment-1976336097`](https://github.com/dotnet/aspnetcore/issues/52330#issuecomment-1976336097%60)

Had the same issue with using `Microsoft.IdentityModel.* 8.x.x` packages alongside `Microsoft.AspNetCore.Authentication.JwtBearer 8.0.11`. Directly referencing the correct `Microsoft.IdentityModel.Protocols.OpenIdConnect` version in my app did the trick. In my case it was `<PackageReference Include="Microsoft.IdentityModel.Protocols.OpenIdConnect" Version="8.1.2" />`
