### ISSUE TITLE
Avoid the evaluation of policies if authentication not succeeded

### ISSUE THREAD

**Issue by MeMofoGit** [dotnet/aspnetcore#54329]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

After getting the authenticate result in the **AuthorizationMiddleware**, it could avoid evaluating the policies requirements. I understand that actually its neccesary because **RequireAuthenticatedUser** applied in policies adds the verification of users authentication as a requirement throught **DenyAnonymousAuthorizationRequiremen**.

¿Couldn't this be restructured in other way avoiding unnecessarily evaluating of all the requirements in the policie?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
While this may be a great idea, it is not aligned with our long-term vision to make it part of the framework. For many other ideas which don't belong to the framework we encourage the community to build and ship on their own, contributing to the expanding .NET Ecosystem.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.

**Comment by mkArtakMSFT** [comment]
Also, you can write your own custom IPolicyEvaluator to fit your needs: https://learn.microsoft.com/dotnet/api/microsoft.aspnetcore.authorization.policy.ipolicyevaluator?view=aspnetcore-8.0
