### ISSUE TITLE
[feat] Add `PasswordOptions.RequireLetter`

### ISSUE THREAD

**Issue by lonix1** [dotnet/aspnetcore#54341]
## Background and Motivation

Many modern websites changed their password policies from *"at least one lowercase, at least one uppercase"* to *"at least one letter"* - i.e. one character which is either lowercase or uppercase.

Many sites use such policies, so this is not some niche requirement. I did a quick survey of various large sites (e.g. Google, Facebook, StackOverflow, Wikipedia, Uber, Dropbox, TikTok, ...) and very few still use the old *"one of this, and one of this, and one of this..."* approach. Various policies are used:
- what we are used to: one lowercase, one uppercase, one digit, one symbol, etc. - this is impractical
- one letter and one number
- one letter and (one number or symbol)
- anything you want, but must meet a minimum strength check
- etc.
- and the minimum length now seems to be `8` across the board

So these days we need a more flexible approach.

## Proposed API

```diff
namespace Microsoft.AspNetCore.Identity
{
  public class PasswordOptions
  {
+   public bool RequireLetter { get; set; }
  }
}
```

## Usage Examples

It would work in the same way as `PasswordOptions` currently does, except if `RequireLetter` is set, then `RequireLowercase` and `RequireUppercase` would be ignored by `PasswordValidator<TUser>`.

## Alternative Designs

n/a

## Risks

None. The `RequireLowercase` and `RequireUppercase` properties are still initialised by default to `true`, so this would be a backward-compatible change.

**Comment by martincostello** [comment]
Could you recreate this as an [API proposal](https://github.com/dotnet/aspnetcore/issues/new?assignees=&labels=api-suggestion&projects=&template=30_api_proposal.md&title=) issue please?

**Comment by amcasey** [comment]
How does it interact with `RequireLowercase` and `RequireUppercase`?  (There's probably a good answer, but we don't want users to have to think about this.)

The same thing can be accomplished with a custom validator.  This isn't needed often enough to justify first-class support.

API rejected.

**Comment by amcasey** [comment]
[My previous response was on behalf of the API review group - this is just me]

> I already answered that question above.

That's fair, you did.  However, that's not the only reasonable behavior and we're concerned that users might be confused if there's no intuitively correct behavior.

> I presented results to the contrary above

One way to have made those results more convincing would have been to actually list the policy for each of those sites.  For example, Google does appear to specify "letter" without upper- or lowercase, Facebook appears to implement custom logic to rule out weak passwords, StackOverflow appears to specify "letter", Wikipedia appears to happily accept an entirely numeric password if it's long enough, etc.  Even if they all used "letter" as a requirement, which does not appear to be the case, my takeaway from visiting them was that they all seem to use custom validation, e.g. to help users avoid dictionary attacks.  If you're going to have custom validation anyway, I'm not sure how much value this additional flag adds.
