### ISSUE TITLE
[OpenIdConnect] ability to specify a different certificate at runtime, based on scope service

### ISSUE THREAD

**Issue by julienGrd** [dotnet/aspnetcore#54356]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello guys, i face problems using the OpenIdConnect package with the OpenIdConnect server i try to connect.

The OpenIdConnect server i try to implement ask for a certificate for each call we make

I see there is an option on the configuration for that

```` 
 pServices.AddAuthentication(opt =>
 {
     opt.DefaultAuthenticateScheme = CookieAuthenticationDefaults.AuthenticationScheme;
     opt.DefaultSignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
     opt.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
 }).AddCookie().AddOpenIdConnect("oidc", options =>
 {
     try
     {
         HttpClientHandler handler = new HttpClientHandler
         {
             ClientCertificateOptions = ClientCertificateOption.Manual,
             SslProtocols = SslProtocols.Tls12,
             ClientCertificates = { new X509Certificate2(lCertificatePath, lCertificatePass) },
             
         };
         options.BackchannelHttpHandler = handler;
```` 
Problem, at this time i still don't know which certificate i have to use because each certificate is dependant of the person connected in our app (not connected by oidc, but connected by our internal system).

For retrieve the user connected (so his certificate and password), i need inject scoped service "somewhere".

But i dont really know if its possible (for information my app is a blazor server side app)

i try to use a DelegatingHandler but i fall into the same problem, if i inject a scoped Service in my OpenIdConnectCustomHttpHandler, i have to furnish it when i construct the object, and where i specify the BackchannelHttpHandler its not possible to do that

````
options.BackchannelHttpHandler = new OpenIdConnectCustomHttpHandler();//cant' give a scoped service at this time, this is called at app startup
...
public class OpenIdConnectCustomHttpHandler : DelegatingHandler
{

    protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    {
       //todo override httpClient for attach a certificate based on the person connected, can be retrieved with a scoped service
        return base.SendAsync(request, cancellationToken);
    }
}
````

Do you have some ideas on how i can resolve this problem ? if its possible ?

thanks !

### Expected Behavior

have a way to inject a scoped service into the BackchannelHttpHandler

### .NET Version

8.0.2

**Comment by Tratcher** [comment]
Change HttpClientHandler to SocketsHttpHandler and use it's SslOptions.LocalCertificateSelectionCallback option to select the certificate per connection.

**Comment by julienGrd** [comment]
OK thanks for the help ! can you detail a bit more about this part ? " to select the certificate per connection." (im in blazor server side in case its specific)

I imagine i have to associate my "connexion" to a certificate and this last one will be automatically include in the localCertificates parameter of the callback right ?

i don't find code or article who speak about that.

For now my callback receive empty collection for localCertificates, null for remoteCertificate and empty collection for acceptableIssuers.  

other thing, it seem the callback is called only the first time and not at each request to the OIDC server (when i refresh the token for example). Is it normal ? does there is a way to select certificate at each OIDC request ? (because actually when the user connect to the oidc server, we most of the time don't know his personal certificate, so we will use a generic certificate for that, but later if he is correctly authentified in our app we have to use his personnal certificate, so even for one physical connection the certificate can change...)

thanks for your help !

thanks !

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. The current implementation is based on shared OIDC metadata. If you'd like to change that you'll need to customize a lot of services to achieve this. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core** tag.
