### ISSUE TITLE
BearerToken Authentication not working from Controller

### ISSUE THREAD

**Issue by gkapellmann** [dotnet/aspnetcore#54385]
### Description

I just updated from .NET 7 to .NET 8, and I am aware that there have been some breaking changes in how the Authentication is done. I used to have a JWT token auth, but now I am trying to use BearerToken.

After following multiple tutorials, I always get to the same place, which is a very basic login function:

`    Code:

    app.MapPost("/login", ([FromBody] Login model) => {
     
     var claimsPrincipal = new ClaimsPrincipal(
        new ClaimsIdentity(
          new[] { 
              new Claim(ClaimTypes.Name, model.DeviceName),
              new Claim("UniqueID", Guid.NewGuid().ToString()),
              new Claim("TimeStamp", DateTime.UtcNow.ToString()),
          },
          BearerTokenDefaults.AuthenticationScheme 
        )
      );
  
      var authProperties = new AuthenticationProperties {
          IsPersistent = true,
          AllowRefresh = true,
          IssuedUtc = DateTimeOffset.UtcNow,
          ExpiresUtc = DateTimeOffset.UtcNow.AddHours(5)
      };
  
      return Results.SignIn(claimsPrincipal, authProperties);

    });`

Here I always get a good Bearer token, but the expiration date doesnt change from 3600 seconds.

But when I try to run this fom a controller `public class AuthenticateController : ControllerBase`, the function looks like this: 

`   Code:

    [HttpPost]
    [Route("RequestToken")]

    public async Task<IActionResult> RequestToken([FromBody] Login model) {
    try {
        var user = await _userManager.FindByNameAsync(model.DeviceName);
        if (user != null && await _userManager.CheckPasswordAsync(user, model.Password)) {
            var userRoles = await _userManager.GetRolesAsync(user);

            var claimsPrincipal = new ClaimsPrincipal(
                new ClaimsIdentity(
                    new Claim[] {
                        new Claim(ClaimTypes.Name, user.UserName),
                        //new Claim("Subject", _configuration["Jwt:Subject"]),
                        new Claim("UniqueID", Guid.NewGuid().ToString()),
                        new Claim("TimeStamp", DateTime.UtcNow.ToString()),
                        new Claim(ClaimTypes.Role, userRoles[0])
                    },
                    BearerTokenDefaults.AuthenticationScheme
                )
            );

            var authProperties = new AuthenticationProperties {
                IsPersistent = true,
                AllowRefresh = true,
                ExpiresUtc = DateTimeOffset.UtcNow.AddHours(5)
            };

            var result = Results.SignIn(claimsPrincipal, authProperties);

            return Ok(new {
                Result = result
            });

        } else {
            return BadRequest("Invalid credentials");
        }
    } catch (Exception ex) {
        return BadRequest(ex.Message);
    }
    }`

Here everything works fine until the SignIn, that returns an empty { }.

I have not been able to fins any documentation on how to do this, or on what could be the problem.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @gkapellmann.
It looks like there are two issues you've mentioned here:
1. The bearer token expiration configuration isn't supported the way you're trying to do it. In fact, we ignore that setting internally. Please use the following API instead: https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.bearertoken.bearertokenoptions.bearertokenexpiration?view=aspnetcore-8.0#microsoft-aspnetcore-authentication-bearertoken-bearertokenoptions-bearertokenexpiration
2. The `Results.SignIn(claimsPrincipal, authProperties)` call returns an `IResult` which you can't wrap with an `Ok()` call and return. Intead, you should try to return the result directly:

```csharp
return Results.SignIn(claimsPrincipal, authProperties);
```

Please note, that it's ok for an action to return `Task<IResult>`.
