### ISSUE TITLE
When using Microsoft.AspNetCore.Authentication.Negotiate my dotnetcore api will not start when hosted in Azure App Services

### ISSUE THREAD

**Issue by johnkwaters** [dotnet/aspnetcore#54386]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I added this package to my csproj for a dotnet core API
<PackageReference Include="Microsoft.AspNetCore.Authentication.Negotiate" Version="8.0.2" />

And this code:

```
using Microsoft.AspNetCore.Authentication.Negotiate;
... 
        srv.AddAuthentication(NegotiateDefaults.AuthenticationScheme)
            .AddNegotiate();


```
This allows Kestrel to use NTLM/Kerberos locally on a coporate domain WITHOUT IIS.

However, when I deploy this code base to Azure App Services, the app won't start. I don't actually intend to use NTLM in this scenario - I just want to use the same code base in both deployment scenarios. 

A previous version did use IIS, with

```
using Microsoft.AspNetCore.Server.IISIntegration;
...
    srv.AddAuthentication(IISDefaults.AuthenticationScheme);
```
  
But I deleted that code as I prefer the non IIS kestrel only version.

Any idea why my code won't load with this reference and code in it when running under Azure App Services?  

### Expected Behavior

The app service to start

### Steps To Reproduce

See details above

### Exceptions (if any)

-

### .NET Version

8.0.2

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core** tag.
