### ISSUE TITLE
JSInterop: Handle that rejected JS promises can be any type.

### ISSUE THREAD

**Issue by KristofferStrube** [dotnet/aspnetcore#54383]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am trying to make interop from Blazor to JS code that uses throws.

A very minimal example is the following:
```js
function someFunction() {
    throw { "someKey": "my value", "id": 2 };
}
```

When the above method is invoked from Blazor using JSInterop it it wrapped in a promise and the promise hits its reject-case when the object is thrown. At [Microsoft.JSInterop.ts](https://github.com/dotnet/aspnetcore/blob/main/src/JSInterop/Microsoft.JSInterop.JS/src/src/Microsoft.JSInterop.ts#L540-L546) we can see the method that is responsible for formatting the reject-case:
```ts
function formatError(error: Error | string): string {
    if (error instanceof Error) {
        return `${error.message}\n${error.stack}`;
    }

    return error ? error.toString() : "null";
}
```
The above method falsely assumes that the reject case of a promise is always either an `Error` or a `String`. But in reality the reject case be any type like the object we created in the `someFunction` sample. This results in us getting the following `JSException` when some object is returned:
```console
Microsoft.JSInterop.JSException: [object Object]
```

### Describe the solution you'd like

Ideally, we would like to get a rich reference to whatever was thrown.

For this, we could add an `IJSObjectReference` to the thrown object if it is not `null`, a simple type, or some `Error` type on the `JSException` type.
```csharp
/// <summary>
/// Represents errors that occur during an interop call from .NET to JavaScript.
/// </summary>
public class JSException : Exception
{
+   /// <summary>
+   /// If the thrown thing if it is not null, undefined, a simple type, or an Error type; Then this is a reference to that element else it is null.
+   /// </summary>
+   public IJSObjectReference? RejectJSObjectReference { get; set; }

    /// <summary>
    /// Constructs an instance of <see cref="JSException"/>.
    /// </summary>
    /// <param name="message">The exception message.</param>
    public JSException(string message) : base(message)
    {
    }

    /// <summary>
    /// Constructs an instance of <see cref="JSException"/>.
    /// </summary>
    /// <param name="message">The exception message.</param>
    /// <param name="innerException">The inner exception.</param>
    public JSException(string message, Exception innerException) : base(message, innerException)
    {
    }
}
```

### Additional context

I have another task related to getting a better `JSInterop` experience when working with the reject case here:
https://github.com/dotnet/aspnetcore/issues/53620

**Comment by KristofferStrube** [comment]
A very real example of code that throws any type is the function `AbortSignal.throwIfAborted()` that simply throws whatever abort reason there was parsed as the reason to the `AbortController.abort(reason: any)` function.

**Comment by javiercn** [comment]
@KristofferStrube thanks for contacting us.

I'm not 100% sure of the implications of creating `JSObjectReference` instances for the results of an exception. It likely means bigger changes in our interop code (I believe our interop layer assumes its serializing exceptions as a string) and it can be a source of memory leaks, or at least an expensive operation as now every exception handling operation involves an extra interop call to signify that the JSObjectReference is no longer in use.

I suspect based on this that its not something we want to do, and that if you find yourself in a situation such as this, the best way to proceed is to wrap the JS into your own function and perform error handling locally before returning.

**Comment by KristofferStrube** [comment]
Thanks for giving it a look @javiercn. I will close it.
