### ISSUE TITLE
MVC view with _framework/blazor.web.js doesn't import *.lib.module.js

### ISSUE THREAD

**Issue by nfplee** [dotnet/aspnetcore#54397]
I've followed the instructions [here](https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/static-server-rendering) to add the `PageScript` Blazor component (which wraps a `page-script` web component) to my Blazor component pages.

This works great, however my application also contains some MVC views and whilst scripts added using the `page-script` web component (to my MVC views) initially appeared to be working fine, I have found this is only the case when the landing page is from a Blazor component page.

Please see here for a minimal repo which shows the problem:

[BlazorTest.zip](https://github.com/dotnet/aspnetcore/files/14512000/BlazorTest.zip)

If you navigate to the home page, you'll see in the developer tools that "Loaded" is written to the console. Also clicking on `MVC` will correctly write `MVC Loaded` to the console. Now if you refresh the app (when on the MVC page), it will no longer output anything to the console.

Looking into this further, the `_content/BlazorPageScript/BlazorPageScript.lib.module.js` is imported when the landing page is a Blazor component page, but it's not imported when landing on an MVC page. I'm not sure why this would be the case as I have referenced `_framework/blazor.web.js` within my MVC master page, similar to how I do in the `App.razor` file.

**Comment by nfplee** [comment]
@javiercn thanks for the response, but aren't module scripts (from class libraries) automatically imported on the client from the `blazor.web.js` file? If so then why would this not work if that same scripts is referenced from MVC?

**Comment by zuizuihao** [comment]
debug the usage of [var file = _environment.WebRootFileProvider.GetFileInfo($"{_environment.ApplicationName}.modules.json");](https://github.co0m/dotnet/aspnetcore/blob/08b60af1bca8cffff8ba0a72164fb7505ffe114d/src/Components/Server/src/Circuits/CircuitOptionsJavaScriptInitializersConfiguration.cs#L21), see if modules.json exists.
