### ISSUE TITLE
Change ASP.NET Core templates to use async main

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspnetcore#5440]
We should look at doing this in 3.0

**Comment by mkArtakMSFT** [comment]
PR here: https://github.com/aspnet/AspNetCore/pull/4307

**Comment by ryanbrandenburg** [comment]
Based on the feedback I received in that PR we can't merge this until Dev16RTM.

**Comment by davidfowl** [comment]
That's correct

**Comment by mkArtakMSFT** [comment]
VS 2019 is now released

**Comment by davidfowl** [comment]
We can make this change now. The only downside is that the exception handling is kinda bad. @DamianEdwards do we want to do this regardless or do we wait?

**Comment by ryanbrandenburg** [comment]
@DamianEdwards can we get a ruling here? I'd like to either merge this PR or be able to close it and keep the branch around until we're ready.

**Comment by mkArtakMSFT** [comment]
@ryanbrandenburg feel free to merge your PR earlier, if it's ready, and update the milestone, if that happens to match the milestone this makes in.

**Comment by mkArtakMSFT** [comment]
Closing as there is no much value add here.

**Comment by davidfowl** [comment]
?
