### ISSUE TITLE
[WebView2] WebViewManager does not search for the correct staticwebassets.runtime.json file when using a BlazorWebView from another csproj

### ISSUE THREAD

**Issue by Hastaroth1** [dotnet/aspnetcore#54417]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This is essentially the same issue as https://github.com/MicrosoftEdge/WebView2Feedback/issues/1797 but it doesn't seem to get much activity and I couldn't find an equivalent issue here.

If you have two projects, one with a `Wpf` `BlazorWebView` component (project `A`) and an application using those components (project `B`),

![image](https://github.com/dotnet/aspnetcore/assets/12807348/c1703f46-0da7-431e-b923-7e4bb110fe69)

 The `StaticWebAssetsLoader` does not load the correct `staticwebassets.runtime.json` file and, as a result, static assets used by project `A` are not available: 

![image](https://github.com/dotnet/aspnetcore/assets/12807348/73fedd5a-bef1-4047-8bb3-057800ce9db7)

The root cause is that when trying to create the `IFileProvider` for static web assets, the `StaticWebAssetsLoader` looks at the entry assembly to build the `staticwebassets.runtime.json` file path.
 
 https://github.com/dotnet/aspnetcore/blob/main/src/Components/WebView/WebView/src/WebViewManager.cs#L298
 
However, the entry assembly will be `B`. So it tries to load `WpfBlazorApp.staticwebassets.runtime.json` when the correct file is `WpfComponents.staticwebassets.runtime.json`

### Expected Behavior

The `WebViewManager` should load the correct `staticwebassets.runtime.json` file and as a result, files should be loaded properly.

This could also be made configurable somehow to cover any possible scenarios.

The equivalent `StaticWebAssetsLoader` for `AspNetCore` allows the path of the static asset manifest to be configured using an `IConfiguration` provider

https://github.com/dotnet/aspnetcore/blob/main/src/Hosting/Hosting/src/StaticWebAssets/StaticWebAssetsLoader.cs#L50

### Steps To Reproduce

Repository with 2 projects: https://github.com/Hastaroth1/WpfBlazorBug

### .NET Version

8.0.100

### Anything else?

For `SDK` style projects, no `staticwebassets.runtime.json` is generated:

![image](https://github.com/dotnet/aspnetcore/assets/12807348/faf81cec-516a-4f0f-9c3e-28ade37187f5)

If you change the `Sdk` project to instead also be `Sdk.Razor`, the file is generated.

![image](https://github.com/dotnet/aspnetcore/assets/12807348/24677c48-cfcc-414f-b2b9-0a58b95f9a07)

 But it may not be possible for every project to change the sdk. In our case, there is several layers of projects between the root application and the project containing the component and this is impractical.
 
 The classes around this functionality (`StaticWebAssetManifest`, etc) are also internal which make it impossible to easily fix this by providing a `IFileProvider` which points to the right `staticwebassets.runtime.json` file. It's always possible to write a custom file provider but it doesn't feel good to duplicate so much code when it's just out of reach.

**Comment by javiercn** [comment]
@Hastaroth1 thanks for contacting us.

This is by design. We don't support the app being in a class library that is part of a "larger" host, it has to be the root. In the same way that web apps can't be generally consumed as dependencies from other apps.

Unless we receive a significant amount of feedback for this functionality this is not something we plan to add/change. 

There are a couple of things you can do:
* Change your entry project to use the Razor SDK.
* Change the name of the generated file to match the one that the host project expects as a build step after the file has been generated, however this might not work in all cases and there might be other limitations you might run into.
