### ISSUE TITLE
Dynamically updating AuthentionSchemes on AuthorizationPolicies

### ISSUE THREAD

**Issue by ssteiner** [dotnet/aspnetcore#54412]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I want to be able to change the authentication to my application at runtime. The app starts out with local JWT auth, then the user may add another authentication mechanism. E.g. OpenID Connect. There's an example on how to [add/remove schemes at runtime](https://github.com/dotnet/aspnetcore/blob/5a6b6c90b6e32ecab4975c546228cc63199f168b/src/AuthSamples/samples/DynamicSchemes/Controllers/AuthController.cs) in the this very repo. However, if you use the standard '[Authorize]` tag in your controller, that alone won't do. You also have to modify the `AuthenticationSchemes` on the Default Authorization policy. But, that collection is read-only. So what I propose is an API on `AuthorizationPolicy` to add/remove schemes.

I know there's workarounds, but you have to create your own `IAuthorizationPolicyProvider`, base it on the DefaultAuthorizationPolicyProvider, and while that allows you to swap out the AuthorizationOptions.DefaultPolicy / AuthorizationOptions.FallbackPolicy, you can't do it for any named policy - the source code of `DefaultAuthorizationPolicyProvider`even states that for MVC, the [same policy must be returned](https://github.com/dotnet/aspnetcore/blob/main/src/Security/Authorization/Core/src/DefaultAuthorizationPolicyProvider.cs) when calling `GetPolicyAsync(string policyName)` - plus you can't iterate the known policies anyway because it's a private collection in `AuthorizationOptions`.

### Describe the solution you'd like

extend `AuthorizationPolicy` with two APIs:

`AddAuthenticationScheme(string scheme)`
`RemoveAuthenticationScheme(string scheme)`

Using these two methods would adapt the `AuthorizationPolicy`, adding or removing schemes so authentication could be made with the updated list of schemes.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
While this may be a great idea, it is not aligned with our long-term vision to make it part of the framework. For many other ideas which don't belong to the framework we encourage the community to build and ship on their own, contributing to the expanding .NET Ecosystem.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
