### ISSUE TITLE
[Hot Reload] Enable Blazor hot reloading for multiple browser windows at the same time

### ISSUE THREAD

**Issue by jsakamoto** [dotnet/aspnetcore#54415]
## Description

Hot Reload on a Blazor WebAssembly app doesn't work stability for multiple browser windows simultaneously. Apparently, it works fine at first. However, if you open the app with a new window once after any hot reloading is applied, the hot reloading won't be applied to that new window. Moreover, once that happens, opening the app in another new window shows the appearance before the hot reloading was applied. Please see also the video I attached.

https://github.com/dotnet/sdk/assets/95908/771728a2-0f8d-41b8-9c5a-bfced4ca49e4

## The solution I'd like

It would be great if the hot reloading worked well for multiple windows simultaneously in some edge cases. For instance, the clone of Storybook for Blazor, "Blazing Story" (https://github.com/jsakamoto/BlazingStory), requires such ability because it has to host multiple preview frames for the stories using an iframe on the same page.

![image](https://github.com/dotnet/sdk/assets/95908/370a8fb4-1c3e-4310-a437-befe4977295f)

## Remarks

I'm unsure whether the same problem will occur on a Blazor Srever app.

## Related Feature Requests

See also: [#39137 [Hot Reload] Enable hot reloading for Blazor inside an iframe](https://github.com/dotnet/aspnetcore/issues/54416)

The ability above is also required for the hot reloading on the "Blazing Story".

**Comment by mkArtakMSFT** [comment]
@BillHiebert do you know if VS keeps track only of a single WebSocket connection to the Browser instance, and that's maybe why it doesn't send the updates to all the open windows?

**Comment by mkArtakMSFT** [comment]
I just confirmed with @BillHiebert that only a single WebSocket connection is support for Hot Reload at the moment. That's something controlled on the VS side. @jsakamoto please file a VS Feedback ticket with this ask so that it gets routed to the right team. I'm going to close this issue now, given that there is no pending action for our team.

**Comment by jsakamoto** [comment]
@mkArtakMSFT Thank you for paying attention to this issue and taking your time. I'll log a ticket on the VS Feedback site. However, the problem I posted about is **not related to Visual Studio**. As you can see in the video above I attached, it is happening on **the `dotnet watch` command**.

On the `dotnet watch` command, hot reloading on multiple browsers or windows worked correctly at first. However, the app didn't show its UI correctly once the browser windows were reloaded.

On Visual Studio, hot reloading works only on one browser window. It is also a problem, and I'll log it to the VS Feedback site, but it differs from this.

I'm really sorry for bothering you; I'd be happy if you told me what I should do. Thanks!

**Comment by jsakamoto** [comment]
P.S. I logged a feedback ticket for Visual Studio as below.
https://developercommunity.visualstudio.com/t/Enable-Blazor-hot-reloading-for-multiple/10617384

**Comment by jsakamoto** [comment]
@mkArtakMSFT Sorry for bothering you, but could you please reopen this issue since this issue is a matter of dotnet SDK, not a matter of Visual Studio? Thank you for taking the time in advance.

**Comment by jsakamoto** [comment]
@mkArtakMSFT (CC: @danroth27, @MackinnonBuck) Sorry for bothering you, but could you please reopen this issue since this issue is a matter of dotnet SDK, not a matter of Visual Studio? This happens with the `dotnet watch` command.

Thank you for taking the time in advance.
