### ISSUE TITLE
Any plans for Managed Identity authentication for Microsoft.Extensions.Caching.StackExchangeRedis?

### ISSUE THREAD

**Issue by arealmaas** [dotnet/aspnetcore#54414]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am using IDistributedCache, and I want to use Redis as backing. Using the following library and guide it seems like we need to pass a connection string. We want to be able to use Managed Identity towards all our Azure services.

https://learn.microsoft.com/en-us/aspnet/core/performance/caching/distributed?view=aspnetcore-8.0#distributed-redis-cache

### Describe the solution you'd like

Being able to authenticate to Redis using Managed Identity like we can for this package: https://github.com/Azure/Microsoft.Azure.StackExchangeRedis. Are there any plans on implementing Managed Identity for this?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This doesn't seem to be an ask for the ASP.NET Core framework. Maybe the package that you're using is the right home for the feature that you're looking for.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This doesn't seem to be something worth implementing in the framework layer.

**Comment by halter73** [comment]
You could ask for https://github.com/Azure/Microsoft.Azure.StackExchangeRedis to implement `IDistributedCache`, or you could take the IConnectionMultiplexer you get from managed identity authentication with Microsoft.Azure.StackExchangeRedis, and return it from a custom [ConnectionMultiplexerFactory](https://github.com/dotnet/aspnetcore/blob/d4d6468c669d03c4e4daaea20c913b22dba636e2/src/Caching/StackExchangeRedis/src/RedisCacheOptions.cs#L29-L32).

**Comment by A-Stapleton** [comment]
This would be nice to get support for MI in this. It's a big gap in dev experience from a using Microsoft products all up perspective.

They said they won't do `IDistributedCache` https://github.com/Azure/Microsoft.Azure.StackExchangeRedis/issues/12#issuecomment-1802788948

**Comment by RichFinn-WTW** [comment]
> This would be nice to get support for MI in this. It's a big gap in dev experience from a using Microsoft products all up perspective.
> 
> They said they won't do `IDistributedCache` [Azure/Microsoft.Azure.StackExchangeRedis#12 (comment)](https://github.com/Azure/Microsoft.Azure.StackExchangeRedis/issues/12#issuecomment-1802788948)

@arealmaas @A-Stapleton - we were able to get `Microsoft.Azure.StackExchangeRedis` working with `Microsoft.Extensions.Caching.StackExchangeRedis`

check out this comment: https://github.com/Azure/Microsoft.Azure.StackExchangeRedis/issues/12#issuecomment-2271772454

**Comment by bhargav-kansagara** [comment]
Sample on how to use MSI with IDistributedCache, just add the following in startup:
```
services.AddStackExchangeRedisCache(options` =>
{
    options.ConfigurationOptions = new ConfigurationOptions
        {
            EndPoints = { "endpoint" },
        };

    options.ConnectionMultiplexerFactory = async () =>
    {
        await options.ConfigurationOptions.ConfigureForAzureWithTokenCredentialAsync(new DefaultAzureCredential()).ConfigureAwait(false);
        return await ConnectionMultiplexer.ConnectAsync(options.ConfigurationOptions).ConfigureAwait(false);
    };
});
```
