### ISSUE TITLE
NavigationManager.NavigateTo throws exception when navigating in OnInitialized

### ISSUE THREAD

**Issue by LukasKubicek** [dotnet/aspnetcore#54436]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have complex Blazor Server application.

Our .razor Pages inherit from our own BaseClass. In this Base class we are trying to load data during OnInitialized event.

When some data is not available, we need to stop loading the page (stop rendering) and redirect user to some other page.

However when we use NavigationManager in such scenario, it throws `Microsoft.AspNetCore.Components.NavigationException: 'Exception_WasThrown'`

If the loading/rendering of the page continues, the applications eventually encounters some exceptions and returns 500 response to the user.

**How can we prevent this? I need to be able to say to blazor during OnInitialized "stop whatever you are doing and navigate the user to this page instead". The navigation should be real request/response.**

**Comment by MackinnonBuck** [comment]
Thanks for reaching out. A `NavigationException` gets thrown when `NavigationManager.NavigateTo()` gets called during static server rendering. This is _by design_. The exception is intended to be caught by the framework so that a redirect can be initiated.

If you know what's directly causing the 500, could you please elaborate on what that is? The `NavigationException` alone shouldn't be causing a 500, so we anticipate that there's some additional logic in your app that might be causing it.

If possible, could you please also provide us with a minimal repro project that demonstrates the issue? This will help us investigate this further.

**Comment by LukasKubicek** [comment]
> Thanks for reaching out. A `NavigationException` gets thrown when `NavigationManager.NavigateTo()` gets called during static server rendering. This is _by design_. The exception is intended to be caught by the framework so that a redirect can be initiated.
> 
> If you know what's directly causing the 500, could you please elaborate on what that is? The `NavigationException` alone shouldn't be causing a 500, so we anticipate that there's some additional logic in your app that might be causing it.
> 
> If possible, could you please also provide us with a minimal repro project that demonstrates the issue? This will help us investigate this further.


The blazor page (e.g. `"page.razor"` inherits from `"pages_base.cs"` parent). They both (page and its parent) have `OnInitialized` method. the page calls `"base.OnInitialized"` at the start of it's `OnInitialized `method.

The problem is that in parent `OnInitialized ` I figure we don't have all the data and would need to s**top everything and navigate away**. But even when I navigate and stop the OnInitialized by "return" from the method, it then continues by executing the child (page.razor) OnInitialized and there happens the exception bc some of the data is null, but the page tries to work with it.

What I would need is something like "completly stop everything, exit rendering and navigate to new page with real hhtp request" in the parent before the child continues with its own OnInitialized.

Is this possible?

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide [a minimalistic repro project](https://github.com/dotnet/aspnetcore/blob/main/docs/repro.md) that illustrates the problem.
