### ISSUE TITLE
Installer of aspnetcore still contains wrong outdated .NET dotnet license information that makes it problematic to distribute

### ISSUE THREAD

**Issue by mgexo** [dotnet/aspnetcore#54434]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There are wrong outdated license agreements and license files mentioned in the installer of aspnetcore, which developers must distribute as dependency e.g. for CoreWCF to clients in their installers. 

This may cause software distributors of .NET Core - which is licensed under MIT - to get false warnings that they would violate some old Microsoft .NET Framework licenses which should not apply to .NET Core software components like aspnetcore (especially not the Desktop/Client part)

Is that intentional? 

Example:
Go to https://dotnet.microsoft.com/en-us/download/dotnet/8.0
Download https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-aspnetcore-8.0.2-windows-x64-installer 
Run the installer
In the first screen, click on the "license term".

It links to https://go.microsoft.com/fwlink/?LinkId=329770, which then links to https://dotnet.microsoft.com/en-us/dotnet_library_license.htm which seems to be unrelated to .net Core and does NOT reference MIT but some old Microsoft license which makes it much more difficult to distribute.

The correct link should probably this one https://github.com/dotnet/core/blob/main/license-information-windows.md 

This license text may even be contained in the installer. 

In ticket [40835](https://github.com/dotnet/aspnetcore/issues/40835) a related issue has been reported for some other part.

### Expected Behavior

No more reference to old Microsoft .NET framework licenses but correct dotnetcore MIT licenses.

### Steps To Reproduce

Go to https://dotnet.microsoft.com/en-us/download/dotnet/8.0
Download https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-aspnetcore-8.0.2-windows-x64-installer 
Run the installer
In the first screen, click on the "license term".

It links to https://go.microsoft.com/fwlink/?LinkId=329770, which then links to https://dotnet.microsoft.com/en-us/dotnet_library_license.htm which seems to be unrelated to .net Core and does NOT reference MIT but some old Microsoft license which makes it much more difficult to distribute.

**Comment by wtgodbe** [comment]
Hi, thanks for the report. It's expected that the hosting bundle uses the Microsoft license, as it redistributes some assets from dotnet/runtime & IIS that are not covered by the MIT license.

**Comment by mgexo** [comment]
@wtgodbe but how can customers then redistribute the parts that are required for client-software only e.g. for the .NET Core WCF  implementation? Do we need to create a reduced installer or can .NET CoreWCF not be shipped to clients through even though it is meant to be for client customers? We (and most likely all customers of CoreWCF ) need a redistributable installer for the respective parts

**Comment by wtgodbe** [comment]
Generally the MIT license only applies to the code itself, not the compiled bits or the installers. If you need to redistribute code or bits from WCF I recommend filing an issue in https://github.com/dotnet/wcf

**Comment by richlander** [comment]
We did a push on fixing up licensed a few years ago, mostly targeting on Linux. It looks like there is still some missing pieces.

Let's start with intent

**Comment by mgexo** [comment]
@wtgodbe  can you maybe comment (or adjust your comments) based on the new information that had been provided by @richlander and in https://github.com/dotnet/wcf/issues/5522 ?

**Comment by richlander** [comment]
Here's the intent:

- Windows builds should use .NET Library license.
- Linux and macOS builds should use MIT.

zip/tar.gz vs installer doesn't make a difference.

Windows builds can carry the .NET Library license and should ideally also point to https://github.com/dotnet/core/blob/main/license-information-windows.md.

**Comment by mgexo** [comment]
@richlander @wtgodbe will the license fix make it into dotnet9 ?

**Comment by richlander** [comment]
It seems like this fwlink is the source of it: https://go.microsoft.com/fwlink/?LinkId=329770

I don't have permission to see the link definition. If it is soley used by our installers, then we can change it.

Do you have access to the link @leecow?

**Comment by leecow** [comment]
Yes, I can access the link. Where do we want it to point?

**Comment by richlander** [comment]
If the link is specific to our installers, it can point here:

https://github.com/dotnet/core/blob/main/license-information.md

I think that page needs an update to make it the Windows differences more clear. I can do that.

They are described here: https://github.com/dotnet/core/blob/main/license-information-windows.md. We could link just there but then users would miss the bigger picture.

**Comment by leecow** [comment]
> If the link is specific to our installers ...

Looks like it is - https://github.com/search?q=org%3Adotnet%20https%3A%2F%2Fgo.microsoft.com%2Ffwlink%2F%3FLinkId%3D329770&type=code

**Comment by richlander** [comment]
Feel free to make the link change.

In parallel, I made this PR. Hopefully we can merge it soon. I think the new text is clearer and provides some links to useful information.

https://github.com/dotnet/core/pull/9440

**Comment by leecow** [comment]
Link updated

**Comment by richlander** [comment]
Resolved.
