### ISSUE TITLE
Add IsComposing Property to KeyboardEventArgs

### ISSUE THREAD

**Issue by BattlefieldDuck** [dotnet/aspnetcore#54456]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Currently, there is no way to determine if the user is composing text (e.g., using IME) in the KeyboardEventArgs class.

### Describe the solution you'd like

I would like an IsComposing property to be added to the KeyboardEventArgs class to indicate whether the user is in the midst of composing text.

### Additional context

This feature would be particularly useful for applications that need to handle text input more gracefully, especially in languages that require text composition.

**Comment by SteveSandersonMS** [comment]
Sounds reasonable to me. Thanks for the PR.
