### ISSUE TITLE
How I can implement distributed session using redis in a blazor web app? 

### ISSUE THREAD

**Issue by Z3r0J** [dotnet/aspnetcore#54477]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'd like to know if there's a way to implement distributed sessions using Blazor. I understand that HttpContext isn't available when a page is in an interactive  render mode, but when the page isn't in any render mode (i.e., SSR), it's possible to use HttpContext to manipulate the response and add sessions. However, I'm interested in implementing distributed sessions in interactive pages. Is there any method to achieve this? I appreciate any guidance or resources you can provide on this matter.

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **blazor** tag.
