### ISSUE TITLE
Update version of IdentityModel to >= 7.4.0 for 9.x

### ISSUE THREAD

**Issue by brentschmaltz** [dotnet/aspnetcore#54518]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

asp.net 9.x is currently referencing IdentityModel 7.1.2, there are known serialization issues with versions <= 7.4.0.
https://www.nuget.org/packages/Microsoft.AspNetCore.Authentication.OpenIdConnect/9.0.0-preview.2.24128.4#dependencies-body-tab

Users that update a single IdentityModel package results in a subset of IdentityModel updates and issues arise.
see: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/2514

### Describe the solution you'd like

asp.net 9.x picking up regular releases of IdentityModel so we can find issues early.

**Comment by halter73** [comment]
IdentityModel has been updated to 8.0.0-preview1 by #56342.
