### ISSUE TITLE
State is not preserved after login in .net 8.02

### ISSUE THREAD

**Issue by jbppraxis** [dotnet/aspnetcore#54514]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

We are migrating from a .net 7 blazor client side webassembly app to .net 8. But have run into an issue. When doing a successful login, we have som logic that change where the user is redirected. For this we are using the RemoteAuthenticationState.ReturnUrl on the login event.

However, Remoteauthenticationstate is null after successfull login in .net 8.02. 
It works on localhost but in staging environment and production it resolves to null. 
The staging environment is a azure webapp not a static webapp.

### Expected Behavior

State should not be null and contain a returnurl on successful login

### Steps To Reproduce

Steps to reproduce.
Create blazor webassembly standalone app template project with authentication. 
Change from Microsoft to standard OIDC authentication(we are using identityserver4).
In authentication.razor component add the following eventcallback when login is successful
 
![image](https://github.com/dotnet/aspnetcore/assets/47383719/91f8b044-d041-40e7-aa9b-416c0065674c)

Try to login and get a null exception on state.

We have tried several different implementations but it all resolves to null. 

### Exceptions (if any)

we get a null exception on the state

### .NET Version

8.02 LTS

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @jbppraxis.
@halter73 is this something you have seen already? Any thoughts regarding what's happening?

**Comment by DylanLyon** [comment]
> Found this workaround from another issue to preserve return url
> 
> In RedirectToLogin.razor
> 
> ```
> @using Microsoft.Extensions.Options
> @using Microsoft.AspNetCore.Components.WebAssembly.Authentication
> 
> @inject NavigationManager Navigation
> 
> @inject IOptionsSnapshot<RemoteAuthenticationOptions<ApiAuthorizationProviderOptions>> Options
> 
> @code {
>     protected override void OnInitialized()
>     {
>         Navigation.NavigateToLogin(Options.Get(Microsoft.Extensions.Options.Options.DefaultName).AuthenticationPaths.LogInPath);
>     }
> }
> ```

Thank you so much! This worked perfectly for me. I had tried implementing this myself but ran into issues in other places. This seems to have done the trick!
