### ISSUE TITLE
Bug or Error: Bearer error="invalid_token"

### ISSUE THREAD

**Issue by lamardlm** [dotnet/aspnetcore#54513]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We are using Microsoft Graph for authentication along with my Azure Tenant. When a user attempts to login or authenticate we get the following error. Can you please help me resolve this?

Bearer error="invalid_token", error description="The audience '00000003-0000-0000-c000-000000000000' is invalid

### Expected Behavior

We expected the user to be able to login successfully.
Code Below
`using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication.JwtBearer;
//using Microsoft.AspNetCore.Authentication.OpenIdConnect;
using Microsoft.AspNetCore.Authorization;
//using Microsoft.AspNetCore.Mvc.Authorization;
//using Microsoft.Extensions.Options;
using Microsoft.Identity.Web;
using Microsoft.Identity.Web.UI;
using Microsoft.IdentityModel.Tokens;
using ScoutWebAPI.Common;
using ScoutWebAPI.Handlers;
using ScoutWebAPI.Services;
using ScoutWebAPI.Data;
using ScoutWebAPI.Models;
using System.Configuration;
using System.Text;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.IdentityModel.Protocols.OpenIdConnect;
using System.IdentityModel.Tokens.Jwt;
using Microsoft.EntityFrameworkCore.SqlServer;
using Microsoft.Data.SqlClient;
using Microsoft.AspNetCore.Localization;
using System.Globalization;
using Microsoft.AspNetCore.Identity;
//using System.Security.Cryptography.X509Certificates;
using Microsoft.Net.Http.Headers;
using Microsoft.OpenApi.Models;
using Google.Api;

var environmentName = Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT");

var builder = WebApplication.CreateBuilder(args);

// Use the appropriate appsettings file based on the environment
if (!string.IsNullOrEmpty(environmentName))
{
    builder.Configuration.AddJsonFile($"appsettings.{environmentName}.json", optional: false, reloadOnChange: true);
}
else
{
    builder.Configuration.AddJsonFile("appsettings.Development.json", optional: false, reloadOnChange: true);
}

//Database connectiontivity
builder.Services.AddDbContext<ScoutDbContext>(options =>
    options.UseSqlServer(builder.Configuration.GetConnectionString("ScoutDboContext") ?? throw new InvalidOperationException("Connection string 'ScoutDboContext' not found.")), ServiceLifetime.Scoped);
var configuration = builder.Configuration;

//Enable CORS for Specific Origin
//var allowCORS = builder.Configuration.GetValue<string>("JwtConfig:AllowCORS");
//// Services CORS
//builder.Services.AddCors(options =>
//{
//    options.AddPolicy("AllowSpecificOrigin",
//        builder =>
//        {
//            builder.WithOrigins(allowCORS)
//                   .AllowAnyHeader()
//                   .AllowAnyMethod();
//        });
//});

builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(option =>
{
    option.SwaggerDoc("v1", new OpenApiInfo { Title = "Scout API List", Version = "v1" });
    option.AddSecurityDefinition("Bearer", new OpenApiSecurityScheme
    {
        In = ParameterLocation.Header,
        Description = "Please enter a valid token",
        Name = "Authorization",
        Type = SecuritySchemeType.Http,
        BearerFormat = "JWT",
        Scheme = "Bearer"
    });
    option.AddSecurityRequirement(new OpenApiSecurityRequirement
    {
        {
            new OpenApiSecurityScheme
            {
                Reference = new OpenApiReference
                {
                    Type = ReferenceType.SecurityScheme,
                    Id = "Bearer"
                }
            },
            new string[] { }
        }
    });
});

var validAudience = builder.Configuration.GetValue<string>("JwtConfig:Audience");
var validAuthority = builder.Configuration.GetValue<string>("JwtConfig:Authority");
var validIssuer = builder.Configuration.GetValue<string>("JwtConfig:Issuer");
var validKey = builder.Configuration.GetValue<string>("JwtConfig:Key");

//Authentication
//builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
//        .AddJwtBearer(options =>
//        {   //Need to enable below code for local testing only
//            //options.Audience = "https://localhost:5000/";
//            //options.Authority = "https://localhost:5000/identity/";
//            //Need to enable below code for Dev,QA,UAT & Prod
//            options.Audience = validAudience;
//            options.Authority = validIssuer;
//        })

//        .AddJwtBearer("AzureAD", options =>
//        {
//            options.Audience = validAudience;
//            options.Authority = validAuthority;
//        });

builder.Services.AddAuthentication(options =>
{
    options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
    options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
    options.DefaultScheme = JwtBearerDefaults.AuthenticationScheme;  
})
    .AddJwtBearer(options =>
    {
        options.IncludeErrorDetails = true;
        options.TokenValidationParameters = new TokenValidationParameters()
        {
            ClockSkew = TimeSpan.Zero,
            ValidateIssuer = true,
            ValidateAudience = true,
            ValidateLifetime = true,
            ValidateIssuerSigningKey = true,
            ValidIssuer = validIssuer,
            ValidAudience = validAudience,
            IssuerSigningKey = new SymmetricSecurityKey(
                Encoding.UTF8.GetBytes(validKey ?? throw new ArgumentNullException(nameof(validKey)))
            ),
        };
    })
    .AddJwtBearer("AzureAD", options =>
    {
        options.Audience = validAudience;
        options.Authority = validAuthority;
    });

//Authorization
builder.Services.AddAuthorization(options =>
{
    var defaultAuthorizationPolicyBuilder = new AuthorizationPolicyBuilder(
        JwtBearerDefaults.AuthenticationScheme, "AzureAD");
    defaultAuthorizationPolicyBuilder = defaultAuthorizationPolicyBuilder.RequireAuthenticatedUser();
    options.DefaultPolicy = defaultAuthorizationPolicyBuilder.Build();
    options.AddPolicy("UserGroups", policy =>
    {
        policy.RequireAuthenticatedUser();
        policy.Requirements.Add(new GroupsRequirement("BMD_SCOUT_RW_DEV", "ATL_SCOUT_RW_DEV", "DAL_SCOUT_RW_DEV", "HOU_SCOUT_RW_DEV"));
    });

    options.AddPolicy("CanAccessDivisionA", policy => policy.RequireClaim("groups", "DivisionAUsers"));
    options.AddPolicy("CanAccessDivisionB", policy => policy.RequireClaim("groups", "DivisionBUsers"));
    // ... more policies for other divisions

});

builder.Services.AddSingleton<IAuthorizationHandler, GroupsHandler>();

builder.Services.AddTransient<ITokenService, TokenService>();
builder.Services.AddSingleton<IUserService, UserService>();
//First JWT implementation
builder.Services.AddSingleton<JwtTokenValidator>();
//Second JWT implementation
builder.Services.AddSingleton<TokenValidationService>();
//Third JWT Implementation
builder.Services.AddSingleton<JwtUtils>();
builder.Services.AddHttpClient<TokenService>();

var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}
else
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

//app.UseRouting();

//This code is for DB culture localization
app.UseRequestLocalization(new RequestLocalizationOptions
{
    ApplyCurrentCultureToResponseHeaders = false
});

app.UseHttpsRedirection();
app.UseAuthentication();
app.UseAuthorization();

// Enable CORS
//app.UseCors("AllowSpecificOrigin");

app.UseCors(c => c.AllowAnyHeader().AllowAnyOrigin().AllowAnyMethod());
app.MapControllers();

app.Run();

`

### .NET Version

6 LTS

### Anything else?

ASP.NET Core version:

What is mind boggling about this issue is there have been no code changes. The code was working 7 days prior.

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core** tag.
