### ISSUE TITLE
Blazor Identity templates and CRUD scaffolding should use the DbContextFactory

### ISSUE THREAD

**Issue by sonnemaf** [dotnet/aspnetcore#54539]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

The Identity templates and CRUD scaffolding of Blazor 8 are not using the [guidelines](https://learn.microsoft.com/en-us/aspnet/core/blazor/blazor-ef-core?view=aspnetcore-8.0#new-dbcontext-instances) for using EF Core in Blazor apps. 

I think this is bad because this will cause issues because the DbContext which is used in the current solution is a scoped service. In server-side Blazor apps, scoped service registrations can be problematic because the instance is shared across components within the user's circuit. [DbContext](https://learn.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbcontext) isn't thread safe and isn't designed for concurrent use. 

The template and scaffolding should be a best practice and they are not.

### Describe the solution you'd like

Register a DbContextFactory service in the `Program.cs`

```cs
builder.Services.AddDbContext<ApplicationDbContext>(options =>
    options.UseSqlServer(connectionString));
```

This should be:

```cs
builder.Services.AddDbContextFactory<ApplicationDbContext>(options =>
    options.UseSqlServer(connectionString));
```

This will also mean that the Pages and maybe also the `AddIdentityCore` services start using the Factory. This won't be easy.

The same for the scaffolded CRUD pages. They should get a `IDbContextFactory<T>` injected and not a `DbContect`.  You will have to create a `DbContext` that exists for the [lifetime of a component](https://learn.microsoft.com/en-us/aspnet/core/blazor/blazor-ef-core?view=aspnetcore-8.0#scope-to-the-component-lifetime). 

If this is done the developers will use this solution too for their own components.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.

The current dependency on DBContext (vs DBContextFactory) is intentional, because DBContextFactory provides flexibility when dealing with more "dynamic" situations. However, the Blazor Identity UI Components in the Blazor Web project template that shipped in .NET 8 are rendered statically, and don't support interactivity out of the box. Hence, there is no need for the DBContextFactory dependency.
If we decide to change the template in the future to support interactive identity UI components, we may choose to change this too.

That said, the guidance you've linked to is valid for interactive server rendering, but no static rendering scenario.

**Comment by sonnemaf** [comment]
You are mistaking. Blazor Static Server Rendering (SSR) apps have the same issues as Blazor Server (Interactive Server Rendering) apps. 

Take a look at this [sample repository](https://github.com/sonnemaf/EFBlazorDemoApp) which is 100% SSR. It uses a LocalDB Sql Server database (Northwind). Run the app and you will see that you get the `InvalidOperationException: A second operation was started on this context instance before a previous operation completed.`. 

![image](https://github.com/dotnet/aspnetcore/assets/9335559/c219f0ee-0c79-49d9-9c94-9a4ce5d60218)

I included the DbContextFactory fix which was proposed from the he [guidelines](https://learn.microsoft.com/en-us/aspnet/core/blazor/blazor-ef-core?view=aspnetcore-8.0#new-dbcontext-instances). Something you said was not valid. I'm using a DbContextComponentBase<T> baseclass which gets the DbContectFactory injected. No need to inject it myself in every component.

![image](https://github.com/dotnet/aspnetcore/assets/9335559/1b222ec8-1322-4943-8e84-cee067d6cb73)

Change the Home.razor, use the `ProductListFixed` instead of the `ProductList`. You will see it works!

![image](https://github.com/dotnet/aspnetcore/assets/9335559/53e434e4-1fbf-4f34-af3b-3c66ce8eb8f5)

Please reopen this issue.

**Comment by guardrex** [comment]
Except weren't the Identity UI components not rendering multiple instances that rely on the same context? ... if I'm saying that right 😆. I mean if you only had ***one*** `ProductList` component there in the `Home` component, there would be no error ... correct?

**Comment by guardrex** [comment]
Fair enough ... I have an 👂 open and ready to make an update ✏️ to the content I added if this is re-opened for work. The doc can provide a remark on it and a cross-link to this issue for more information while the PU addresses it if they agree to make changes for 9.0.
