### ISSUE TITLE
Some thoughts on npm package-lock/cache in the VMR

### ISSUE THREAD

**Issue by omajid** [dotnet/aspnetcore#54541]
I have been poking around the package-lock.json file and the npm cache that's included in the VMR and found a few things that I wasn't expecting. I am posting a list of thoughts and questions here to share this information and get some feedback. Please let me know if there's a better place to take this disscussion, or if I should file specific issues to get some things fixed.

- It looks like all packages are restored from https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-public-npm.
  - Microsoft probably has equivalent or better supply chain security than npmjs.org, but depending on this custom npm registry seems a bit odd. 
  -  Is there some way to fetch packages from npmjs.org instead?
  - If not, is there some way to validate that these are the same packages as those on npmjs.org?
 
- Some packages have a different version in pakcage-lock.json than what's available on npmjs.org. `word-wrap` caught my eye, bcause the version in package-lock.json is [1.2.6](https://github.com/dotnet/dotnet/blob/901ef47572bee55d6e2ba50cbfc53c50b7377d05/src/aspnetcore/package-lock.json#L41-L49), but npmjs.com only has [1.2.5](https://www.npmjs.com/package/word-wrap?activeTab=versions)

- There are dependencies marked as `"dev": true`. Are they for testing/linting/etc? Can we build ASP.NET Core without those?

- Are the non-dev dependencies actually embedded into the product?

- Can we split dev vs product dependencies into separate caches? That would let distros delete (or not use) the devDependencies, reducing the need to worry about prebuilts, and dev-only dependncies leaking into the product.

- There are prebuilt native/unmanaged binaries in some packages in the cache - such as [rollup](https://github.com/dotnet/aspnetcore/issues/54393). It's really hard to identify and track such uses.

**Comment by mkArtakMSFT** [comment]
I've mentioned this in the other (duped) issue: we'll target to get this resolved in .NET 9 Preview 6.

**Comment by omajid** [comment]
Hey folks! Any updates on this? Preview 5 was released and I assume there's little time left before Preview 6 releases? As touched on in https://github.com/dotnet/aspnetcore/issues/54394 and https://github.com/dotnet/aspnetcore/issues/54393, we can not build .NET 9 previews on s390x or ppc64le due to this issue.

**Comment by sec** [comment]
FreeBSD folks are also unable to build :)

**Comment by wtgodbe** [comment]
There's a lot covered in the original comment - are you asking for something specific?

**Comment by MichaelSimons** [comment]
> There's a lot covered in the original comment - are you asking for something specific?

Is there a need to keep this issue open now that the npm cache direction was abandoned for .net 9.0?

**Comment by wtgodbe** [comment]
Oh, sorry, I totally misread your original comment. I believe so - @omajid feel free to re-open if there's still work you want tracked

**Comment by sec** [comment]
Hi. As #54393 was closed by @mkArtakMSFT and work was to be tracked in here. 

Trying to build `v9.0.0-preview.7.24406.2` under FreeBSD still fails with missing Rollup for this arch, like
```
  > build:debug
  > rollup -c --environment development --forceExit

  /mnt/sec/dotnet-core-freebsd-source-build/aspnetcore/node_modules/rollup/dist/native.js:84
        throw new Error(
        ^

EXEC : error : Your current platform "freebsd" and architecture "arm64" combination is not yet supported by the native Rollup build. Please use the WASM build "@rollup/wasm-node" instead. [/mnt/sec/dotnet-core-freebsd-source-build/aspnetcore/eng/Npm.Workspace.nodeproj]
#
```

So my question is, was this handled somehow/somewhere or we won't be able to source build or maybe I'm missing some switch when building?
Command I use is `aspnetcore/eng/build.sh -ci --os-name freebsd --pack -c Release --all /p:TreatWarningsAsErrors=false  --arch arm64 /p:SkipTestBuild=true`

**Comment by omajid** [comment]
Hey @sec, does your build environment have nodejs/npm installed? If so, can you try after removing nodejs/npm? I have noticed that if it's installed, the ASP.NET Core build will try and use it, which brings back the rollup issue.

Of course, I am assuming you are building this through the VMR. If you are building it standalone, you might have to take a look at the the build command VMR uses and any additional flags/options it sets up.

**Comment by sec** [comment]
Hi.
Building without node/npm ends up with
```
Build FAILED.

/mnt/sec/dotnet-core-freebsd-source-build/aspnetcore/src/Components/WebAssembly/WebAssembly/src/Microsoft.AspNetCore.Components.WebAssembly.csproj(66,5): error : '../../../Web.JS/dist/Release/blazor.webassembly.js' does not exist. Enable NodeJS to pack this project.
/mnt/sec/dotnet-core-freebsd-source-build/aspnetcore/src/Components/WebView/WebView/src/Microsoft.AspNetCore.Components.WebView.csproj(68,5): error : '../../../Web.JS/dist/Release/blazor.webview.js' does not exist. Falling back to checked-in copy.
CSC : error CS1566: Error reading resource '_framework/blazor.webview.js' -- 'Could not find a part of the path '/mnt/sec/dotnet-core-freebsd-source-build/aspnetcore/src/Components/Web.JS/dist/Release/blazor.webview.js'.' [/mnt/sec/dotnet-core-freebsd-source-build/aspnetcore/src/Components/WebView/WebView/src/Microsoft.AspNetCore.Components.WebView.csproj]
/mnt/sec/dotnet-core-freebsd-source-build/aspnetcore/src/Components/Endpoints/src/Microsoft.AspNetCore.Components.Endpoints.csproj(72,5): error : '../../Web.JS/dist/Release/blazor.web.js' does not exist. Falling back to checked-in copy.
CSC : error CS1566: Error reading resource '_framework/blazor.web.js' -- 'Could not find a part of the path '/mnt/sec/dotnet-core-freebsd-source-build/aspnetcore/src/Components/Web.JS/dist/Release/blazor.web.js'.' [/mnt/sec/dotnet-core-freebsd-source-build/aspnetcore/src/Components/Endpoints/src/Microsoft.AspNetCore.Components.Endpoints.csproj]
    0 Warning(s)
    5 Error(s)
```
as expected :)

Currently I'm doing standalone build, so I assume those assets should come from somewhere else (don't know if VMR build without node will get those, maybe from prebuilt artifacts?).
Plan is to move to VMR again, as preview.1 build didn't had those Rollup issues, but first I wanted to go with runtime/aspnet/sdk build to see if there's anything missing.
Also it would be nice to have port build of v9 once releases, just like with v8 - that will be VMR for sure, but first we need working bootstrapped SDK with everything needed/working.

**Comment by omajid** [comment]
That error is very surprising. The files exists in the repo:

-  https://github.com/dotnet/aspnetcore/blob/36332c8183f0205ec098822545dbe65d17d93405/src/Components/Web.JS/dist/Release/blazor.webview.js
- https://github.com/dotnet/aspnetcore/blob/36332c8183f0205ec098822545dbe65d17d93405/src/Components/Web.JS/dist/Release/blazor.web.js

Could something be deleting them?

**Comment by sec** [comment]
You are correct... There were those files, I assume first try of build with node deleted them, restored and trying to build now :)
