### ISSUE TITLE
Issue with Failed to load resource: net::ERR_HTTP2_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#54559]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Issue-with-Failed-to-load-resource:-net:/10612982)._

---
I've been managing an MVC project smoothly for quite some time now. However, following a recent build and deployment to the web server, I encountered an unexpected hiccup when the site is running on HTTPS (it's working properly on HTTP). Despite no changes on the server or my end, aside from routine Windows updates, I'm now encountering the error message "Failed to load resource: net::ERR_HTTP2_PROTOCOL_ERROR" on a specific page featuring a Telerik component.

---
#### Feedback Bot on 3/12/2024, 00:07 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by amcasey** [comment]
The screenshot also mentions fonticons-css, which isn't obviously specific to Telerik, though it may well appear on only that page.

I can't tell from the description whether this app is running on kestrel.  If so, Trace level kestrel logs 
The next things I would check would be the server logs - ideally, Trace level from `Microsoft.AspNetCore.Server` - would be useful.

A packet trace would be useful, but it would need to be decrypted.  It's a little more involved, but there are some details [here](https://wiki.wireshark.org/TLS).

Another approach would be to create a smaller repro for us to investigate.  For example, perhaps serving one or both of those css files as static files from a toy app that does nothing else would exhibit the same behavior.

**Comment by xenophilios** [comment]
I had been having this issue with several browsers, on which the home page of an ASP.NET Core 8 site of mine was not rendered. After today's update of Visual Studio 2022, there has been a significant improvement, but with Brave, for example, it can still be necessary to click on the Refresh button. Is there anything I can do in Visual Studio to deal with what is left of this problem?
Thank you for your trouble.

**Comment by amcasey** [comment]
@xenophilios Can you please file a new issue and include some of the information I asked for [above](https://github.com/dotnet/aspnetcore/issues/54559#issuecomment-2018869213)?

**Comment by xenophilios** [comment]
@amcasey I'm embarrassed to admit it, but that's above my current skill level. I'll see what I can figure out in the next few days. Thank you for responding so promptly.
@xenophilios

**Comment by xenophilios** [comment]
@amcasey In my case the problem was due to an anomaly on the remote server, which the hosting company has now fixed.
