### ISSUE TITLE
shaw 256 Failed to find a valid digest in the 'integrity' attribute for resource  .net 8

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#54558]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/shaw-256-Failed-to-find-a-valid-digest-i/10613879)._

---
[severity:I'm unable to use this version]
 Microsoft Visual Studio Professional 2022 (64-bit) | Version 17.9.2 | .NET 8 | Blazor Web Assembly PWA ASP.NET Core Hosted on IIS Server

Publisg Blazor WASM PWA and hosting the same on IIS Server
Access the Home page and on doing so Error in console will be displayed as follow:

---
#### Feedback Bot on 3/12/2024, 07:41 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Can you try to open the Browser DevTools (F12 should do it for Edge) and check if you see a NotFound (404) responses for some of the requests in the Network tab.

If not, then please share a minimal repro project.
