### ISSUE TITLE
Net7 regression: Kestrel HttpRequestHeaders doesn't enumerate "Content-Length" unless there's another known header also present.

### ISSUE THREAD

**Issue by Tomius** [dotnet/aspnetcore#54557]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If you add a key to a Dictionary, then enumerate its elements just afterwards, you expect the recently added key to be present.

However this is not the case for the `Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestHeaders` class starting from net7.0, if the key is `"Content-Length"`, and the dictionary does not contain any other known headers:
``` C#
httpRequestHeaders["Content-Length"] = "423";
        - Count: 1
        - Keys: []
        - Values: []
        - Enumerate: []
        - TryGetValue("Content-Length", out var _) == True
```

E.g. some of the properties on the directionary act as if the `"Content-Length"` was added, others act as if it wasn't.

What's interesting to is that if there is at least one other known header in the dictionary, regardless if it was added before or after the `"Content-Length"`, then the behaviour of the dictionary becomes normal again.

E.g. for the above example, adding `"Content-Type"` to the headers makes the `"Content-Length"` appear in the enumerated list as well:
``` C#
httpRequestHeaders["Content-Type"] = "text";
        - Count: 2
        - Keys: [Content-Type, Content-Length]
        - Values: [text, 423]
        - Enumerate: [[Content-Type, text], [Content-Length, 423]]
        - TryGetValue("Content-Length", out var _) == True 
```

### Expected Behavior

Since the `HttpRequestHeaders` implements the `IDictionary` interface, it should behave like a `Dictionary` in respect to adding and enumarating elements (e.g. how it behaved until `net6.0`), and the number of enumerated elements should always be equal to the `.Count` property.

Even if `"Content-Length"` is treated in a special way, the presence of other known headers should not impact whether `"Content-Length"` is enumerated or not.

### Steps To Reproduce

Create a console app:

## The .csproj:
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <OutputType>Exe</OutputType>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>
</Project>
```

## The Program.cs:
``` C#
using System.Text;
using Microsoft.Net.Http.Headers;

public static class Program
{
    public static void Main()
    {
        IHeaderDictionary dict =
            (IHeaderDictionary)
            typeof(Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer)
            .Assembly
            .GetType("Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestHeaders", throwOnError: true)!
            .GetConstructor([typeof(bool), typeof(Func<string, Encoding>)])!
            .Invoke([true, null]);

        AddAndPrint(dict, "a", "1");
        AddAndPrint(dict, HeaderNames.ContentLength, "423");
        AddAndPrint(dict, "b", "2");
        AddAndPrint(dict, HeaderNames.ContentType, "text");
    }

    private static void AddAndPrint(IHeaderDictionary dict, string key, string value)
    {
        Console.WriteLine($"httpRequestHeaders[\"{key}\"] = \"{value}\";");
        dict[key] = value;
        Console.WriteLine("\t- Count: " + dict.Count);
        Console.WriteLine("\t- Keys: [" + string.Join(", ", dict.Keys) + "]");
        Console.WriteLine("\t- Values: [" + string.Join(", ", dict.Values) + "]");
        Console.WriteLine("\t- Enumerate: [" + string.Join(", ", dict) + "]");
        Console.WriteLine($"\t- TryGetValue(\"{HeaderNames.ContentLength}\", out var _) == " + dict.TryGetValue(HeaderNames.ContentLength, out var x) + "\n");
    }
}


```

### .NET Version

7.0.0 or newer

**Comment by amcasey** [comment]
This screams "perf cleverness", but I'll try to track down the exact code.

**Comment by amcasey** [comment]
I'm immediately suspicious that there's [no `_bits`](https://github.com/dotnet/aspnetcore/blob/6c6361d2576da1800aeb8fa65cd2f0f94224edbd/src/Servers/Kestrel/Core/src/Internal/Http/HttpHeaders.Generated.cs#L4117) for content-length.

**Comment by amcasey** [comment]
Setting -1 [here](https://github.com/dotnet/aspnetcore/blob/bc0e86340bfb5576d1422751ca2cf849cdeb9dc5/src/Servers/Kestrel/Core/src/Internal/Http/HttpRequestHeaders.cs#L247) causes this behavior.

**Comment by amcasey** [comment]
@Tomius Can you tell us more about what impact this had?  Maybe it was just a fun puzzle for you, but it seems like a lot of work went into reducing the repro for us (thanks!) and I want to make sure that wasn't because it was causing some huge problem that would justify a backport.

**Comment by Tomius** [comment]
Hello @amcasey,

Thanks a lot for looking into the issue and finding a fix.

I'm coverting a large codebase (~3000 csproj files) from net6.0 to net8.0, and during that migration I've encountered a test that was failing on net8.0 but it was passing on net6.0. 
It was testing a user implemented http header dictionary against the kestrel's implementation and was asserting that the two dictionaries behave the same way. So luckily the failing test pointed straight to the issue, and writing the repro was trivial.

As far as I can tell, we only rely on this behaviour in the test code but nowhere in production, so the impact is negligible for us.
