### ISSUE TITLE
Razor StreamRendering bug with EF Core

### ISSUE THREAD

**Issue by cmuller29** [dotnet/aspnetcore#54569]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Related to [Razor StreamRendering bug with server side project #53936](https://github.com/dotnet/aspnetcore/issues/53936)

Hello, I am having the same issue. I have narrowed down to the async EF Core functions.
When used, it seems the stream rendering does not work...

When using this syntax `testModels = await Task.Run(() => dbContext.OkModels.ToList());` stream rendering works but not with this syntax : `testModels = await dbContext.KoModels.ToListAsync();`

Here is a repo with a basic web app with two pages (one with the stream rendering working and a second where it does not work) to reproduce the issue : https://github.com/cmuller29/TestStreamRender

Can you help with this issue ?

Thank you

### Expected Behavior

Have stream rendering working with both methods.

### Steps To Reproduce

https://github.com/cmuller29/TestStreamRender

### .NET Version

8.0.200

**Comment by mkArtakMSFT** [comment]
Can you please try to capture the task after the DBContext call and check if it's completed using `task.IsCompleted?

```csharp
var task = dbContext.KoModels.ToListAsync();
if (task.IsCompleted)
  Debugger.Break();
testModels = await task;
```
If the task is completed, then this is due to the Sqlite behavior, as documented here: https://learn.microsoft.com/dotnet/standard/data/sqlite/async
