### ISSUE TITLE
Building static resources

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#5459]

**Comment by XmlmXmlmX** [comment]
> This is my wish list, I'd like to be able to do with Blazor:
> 
> 1. Use a build tool like Webpack, ParcelJS or Gulp so I get the flexibility of being able to use the myriad of plugins and extensions to my build process. I'd like to see Blazor avoid creating it's own build ecosystem from scratch as it's probably never going to be as rich. That said, I can see why some would want Microsoft to add their own simplified build story.
> 2. I'd like to add a `<style>` tag to my `cshtml` file and use my build tool to extract the CSS into a single separate CSS file. Vue.js single file components currently does this in Webpack by providing a plugin called `vue-loader` which reads the single file components and extracts the CSS.
> 3. I'd like SASS/LESS support in my `<style>` tag. I can provide a type="{webpack loader name}" attribute in Webpack to determine which loader is capable of reading this file.
> 4. I'd like to somehow `import` images, fonts, JavaScript, TypeScript modules so that tools like Webpack can build a tree and output bundles. The scripts could be files on disk or from NPM packages like `jQuery` etc.

👍 for SASS

**Comment by mkArtakMSFT** [comment]
@javiercn how much does Client Web Assets work cover this?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
While this may be a great idea, it is not aligned with our long-term vision to make it part of the framework. For many other ideas which don't belong to the framework we encourage the community to build and ship on their own, contributing to the expanding .NET Ecosystem.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.

**Comment by mkArtakMSFT** [comment]
We're going to do some improvements in this area as part of https://github.com/dotnet/aspnetcore/issues/52819
