### ISSUE TITLE
Route Params are not able to validate Guid[] parameters

### ISSUE THREAD

**Issue by MiltoxB** [dotnet/aspnetcore#54602]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

With a simple route parameter being `Guid[]`, routing fails validation and doesn't continue the method if more than one Guid is present in the request url.  Swagger sends the request as `https://{{BASEPATH}}/method/{GUID},{GUID}`, but the request fails validation.

### Expected Behavior

I should be able to receive an array of Guids as a route parameter. Or an error should show up saying that Guid[] parameters are not allowed.

### Steps To Reproduce

Use the following `ApiController` in a web api project: 

```csharp
using Microsoft.AspNetCore.Mvc;

namespace TestWebApi.Controllers;

[ApiController]
[Route("[controller]")]
public class TestController : ControllerBase
{
    private readonly ILogger<TestController> _logger;

    public TestController(ILogger<TestController> logger)
    {
        _logger = logger;
    }

    [HttpGet("{guids}",Name = "GetWeatherForecast")]
    public IActionResult Get([FromRoute] Guid[] guids)
    {
        return Ok(new
        {
            Guids = guids,
        });
    }
}
```

Running swagger will show everything correctly and let you send any number of Guids as a comma separated list.  ASP.NET returns a 400 status with a message like: 

```json
{
  "type": "https://tools.ietf.org/html/rfc9110#section-15.5.1",
  "title": "One or more validation errors occurred.",
  "status": 400,
  "errors": {
    "guids": [
      "The value '3fa85f64-5717-4562-b3fc-2c963f66afa6,3fa85f64-5717-4562-b3fc-2c963f66afa5' is not valid."
    ]
  },
  "traceId": "00-d8ca8db2dc29df76f60dfb3aa40dae80-5cd6414134818538-00"
}
```

### .NET Version

8.0.103

### Anything else?

This happens on both mac and windows

**Comment by captainsafia** [comment]
@MiltoxB Support for array inputs in the route parameter like this isn't supported at the moment. There are a couple of options if you'd like to get this working:

- Changing the API to accept data from a query parameter and leveraging `guids=foo&guids=bar` syntax to pass multiple values.
- Accepting the input as a comma-seperated string and splitting it into an array in your controller logic.
- Implementing a custom `RouteValueProvider` to support arrays in route parameters. This approach is a little heavy handed so I wouldn't recommend it.
