### ISSUE TITLE
[NETSDKE2E]warning CS8618: Non-nullable property 'Http' must contain a non-null value when exiting constructor when building blazorWasm project.

### ISSUE THREAD

**Issue by vdanche** [dotnet/aspnetcore#54603]
1. Install 9.0.100-preview.3.24165.20 sdk
2. Install wasm-tools: dotnet workload install wasm-tools --skip-manifest-update.
3. dotnet new blazorwasm
4. dotnet build

**Expected Result:**
Build successfully.
**Actual Result:**
Build successfully, but arning CS8618: Non-nullable property 'Http' must contain a non-null value when exiting constructor when building blazorWasm project.
![image](https://github.com/dotnet/sdk/assets/65637796/f9f1f8de-a521-4190-b16e-b3af111d500f)

dotnet --info
.NET SDK:
Version:           9.0.100-preview.3.24165.20
Commit:            b40c44502d
Workload version:  9.0.100-manifests.93c1dea9
MSBuild version:   17.10.0-preview-24164-03+0764e8979
 
Runtime Environment:
OS Name:     Windows
OS Version:  10.0.20348
OS Platform: Windows
RID:         win-x64
Base Path:   C:\Program Files\dotnet\sdk\9.0.100-preview.3.24165.20\
 
.NET workloads installed:
There are no installed workloads to display.
 
Host:
  Version:      9.0.0-preview.3.24162.31
  Architecture: x64
  Commit:       596a1f7b64
 
.NET SDKs installed:
  9.0.100-preview.3.24165.20 [C:\Program Files\dotnet\sdk]
 
.NET runtimes installed:
  Microsoft.AspNetCore.App 9.0.0-preview.3.24163.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 9.0.0-preview.3.24162.31 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 9.0.0-preview.3.24163.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
 
Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
 
Environment variables:
  Not set
 
global.json file:
  Not found
 
Learn more:
https://aka.ms/dotnet/info
 
Download .NET:
https://aka.ms/dotnet/download

**Comment by v-jieyan2** [comment]
This problem is also reproduced on Win ARM64.
![image](https://github.com/dotnet/aspnetcore/assets/106043919/96e9e547-1e37-4e81-be0a-2cf6c329b3f7)

**Comment by v-jieyan2** [comment]
This issue is also repro on 8.0.300-preview.24169.31
![image](https://github.com/dotnet/aspnetcore/assets/106043919/058031f2-1f92-419a-8476-26c0df76c23d)

**Comment by mkArtakMSFT** [comment]
This was addressed by the change in Razor compiler: https://github.com/dotnet/razor/pull/10122

/cc @chsienki

**Comment by vdanche** [comment]
Currently the build version is still 9.0.100-preview.3.24165.20(runtime-9.0.0-preview.3.24162.3 and wait new bug to verify

**Comment by v-ainigao** [comment]
This issue does not repro on today’s .net9.0.100-preview.3.24175.24(runtime-9.0.0-preview.3.24172.9)SDK.
![image](https://github.com/dotnet/aspnetcore/assets/106054229/311a77a8-bd8f-42fb-81d3-47fd7160ab36)
