### ISSUE TITLE
Web analytics and diagnostics

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#5461]
- [ ] #53613
- [ ] #29846 
- [ ] #30972

**Comment by isc30** [comment]
Hi, I just created a Google Analytics extension for Blazor
https://github.com/isc30/blazor-analytics

This library can be extended for multiple analytics providers easily (+add TrackingService for complex operations)

**Comment by robdavey555** [comment]
> Hi, I just created a Google Analytics extension for Blazor. I think it could be relevant to this ticket.
> https://github.com/isc30/blazor-analytics
> 
> This library can be extended for multiple analytics providers easily (+add TrackingService for complex operations)

I hope you don't mind but I have used your library for inspiration to implement as you suggest.
https://github.com/robdavey555/Blazor.ApplicationInsights

**Comment by martinfletcher-w2** [comment]
Is there any update on this?

I would prefer to use dotnet rather than js to send telemetry events, as this would allow for easily consuming existing logging code in a wasm app.

**Comment by mehmettahameral** [comment]
Hi all, 

I also would prefer registering AI instance into DI container on the program.cs, like HttpClient, and then inject telemetry client each .razor pages. Otherwise, we can't track C# exceptions in a proper way. 

Many Thanks

**Comment by IvanJosipovic** [comment]
I just released https://github.com/IvanJosipovic/BlazorApplicationInsights
It hooks all logging to App Insights and supports App Insights Apis like Track Event etc.

**Comment by ElanHasson** [comment]
@kant2002 
> In the ASP.NET Core (and regular ASP.NET and just AI SDK) I without problem could change AI key using `appsettings.json`. Would be good to have this in the Blazor as well.

Check out https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/configuration?view=aspnetcore-5.0#app-settings-configuration

Specifically this section (no direct link available) 
![image](https://user-images.githubusercontent.com/234704/120910547-bec07f00-c64d-11eb-9261-6f1c7f44eb34.png)

Since different environments typically have different configurations (i.e. Instrumentation Key), your deployment process should be responsible for putting the correct file (i.e. `$"{environment}.json"`) in the deployed application. Then in your Startup class use `builder.HostEnvironment.Environment` to interpolate the filename.

**Comment by Liero** [comment]
Might be related to #30972

**Comment by indcoder** [comment]
@danroth27 Is there an ETA for this?  This issue has been languishing for over 4 years now; almost two years after @SteveSandersonMS has labelled it as a major severity. We had expected this to be ready with .net 6 release. The implication is that it is creating strong headwinds against us convincing folks #BlazorWASM has critical mass and is production ready.

**Comment by CoryKoehler** [comment]
> @danroth27 Is there an ETA for this? This issue has been languishing for over 4 years now; almost two years after @SteveSandersonMS has labelled it as a major severity. We had expected this to be ready with .net 6 release. The implication is that it is creating strong headwinds against us convincing folks #BlazorWASM has critical mass and is production ready.

You can use the javascript appinsights sdk -> same with google analytics.

In my production app we use the following packages
https://github.com/IvanJosipovic/BlazorApplicationInsights
https://github.com/isc30/blazor-analytics

both are working very well without much work to setup

**Comment by indcoder** [comment]
@CoryKoehler  We are aware of the two packages [they have cropped up earlier in this thread years back ]. But  the recent log4j  scare has completely changed the landscape; especially in the enterprise sector. Mind you, they are official AppInsights plugins for react and angular; we are demanding parity for BlazorWASM and we solicit your support in this regard.

**Comment by hkusulja** [comment]
Hello, I am coming from - https://github.com/microsoft/ApplicationInsights-dotnet/issues/2143 that has reference this issue.

Please inform us about plan and status for supporting Application insights in .NET 6 SDK via dotnet new blazorwasm

Thank you

**Comment by Postlagerkarte** [comment]
I can confirm that this is causing headwinds for the same reasons @indcoder pointed out.  Sentiment has shifted negatively towards third-party logging providers and having native support for Azure AI is definitely crucial.  A similar discussion can be found at https://github.com/microsoft/ApplicationInsights-dotnet/issues/2143 
@danroth27 is native Azure AI support something that the Blazor Team would even consider doing or is the SDK Team solely responsible for that?  Their current status is _"this is not being actively worked on by anyone in the SDK team'_ - so hopefully not a ping-pong problem.

**Comment by Liero** [comment]
After 4 years I still haven't been able to associate logs with username or current url in Blazor Server. How this cannot be prioritized is beyond my understanding

**Comment by hkusulja** [comment]
@Liero I think that this should be resolved under Application Insights team and their SDK which should support Blazor WASM here is feature request - https://github.com/microsoft/ApplicationInsights-dotnet/issues/2143

**Comment by kzu** [comment]
Hey @danroth27 I totally think a third party solution like @IvanJosipovic shouldn't be necessary to get all the stuff working OOB for such a key component of ASP.NET as Blazor webassembly.

Seems like the two teams should sit down and figure out what's missing on either end. It might just be that the AI team needs to get some pressure from the ASP.NET team 😉

**Comment by hkusulja** [comment]
Since no progress here for a years.
Application Insights is moving to Open Telemetry protocol and NuGets.
So in current situation, this is solution could be OpenTelemetry. NET
https://opentelemetry.io/docs/instrumentation/net/

**Comment by danroth27** [comment]
I've split this issue down in to three sub-issues that we are tracking separately. Since this issue is no longer tracking anything on its own, I'm going to go ahead and close it.
