### ISSUE TITLE
Containerizing .NET 8 Blazor WASM breaks after update from .NET 6

### ISSUE THREAD

**Issue by TasmanianDev69** [dotnet/aspnetcore#54618]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello!
After updating the .NET Version from 6 to 8 i can't use the deployed WebApp after starting the container and get the Exception listed in the Exception part.

I have this Dockerfile now, which worked fine with .NET 6. It just differs in the sdk Version.

**Dockerfile**
FROM node:21-alpine3.18 as build-npm
WORKDIR /src`
COPY ["MyProj", "MyProj"]
WORKDIR /src/MyProj/NpmJS/
RUN npm install
RUN npm run build

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY --from=build-npm /src .
COPY ["otherProj", "otherProj"]
RUN dotnet restore "MyProj/MyProj.csproj"

FROM build AS publish
ENV BuildingDocker true
RUN dotnet publish "MyProj/MyProj.csproj" -c UITest --no-restore -o /app/publish

FROM nginx:alpine AS final
WORKDIR /usr/share/nginx/html
COPY --from=publish /app/publish/wwwroot .
COPY MyProj/nginx.conf /etc/nginx/nginx.conf

I

### Expected Behavior

I should be able to access the webpage after running it without exception.

I had this Error on .NET Update locally in my Browser too. Clearing the Cache Storage fixed it but not for this Issue.

### Steps To Reproduce

Obviously you gonna need .NET 8 Workloads and Docker installed and running.

1. Create Blazor WASM Project with .NET 8
2. Adjust your launchsettings.json in the Projects/Properties Folder and set: 
 `"applicationUrl": "https://localhost:5001;http://localhost:5000"`
4. Use this Dockerfile as u wont need the NPM Part :

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY --from=build-npm /src .
COPY ["otherProj", "otherProj"]
RUN dotnet restore "MyProj/MyProj.csproj"

FROM build AS publish
ENV BuildingDocker true
RUN dotnet publish "MyProj/MyProj.csproj" -c UITest --no-restore -o /app/publish

FROM nginx:alpine AS final
WORKDIR /usr/share/nginx/html
COPY --from=publish /app/publish/wwwroot .
COPY MyProj/nginx.conf /etc/nginx/nginx.conf

5. Create nginx.conf in Project root:

events { }
http {
    include mime.types;
    server {
        listen 5001;

        location / {
            root /usr/share/nginx/html;
            try_files $uri $uri/ /index.html =404;
        }
    }
}

I dont know why it marks it as code btw. 

6. Build dockerfile with :  `docker build -t MyApp .`
7.  I start it via compose file but this command should do it for single proj:  `docker run MyApp -p 5001:5001`
8. Navigate to localhost and Open Dev Tools

### Exceptions (if any)

Uncaught TypeError: Cannot read properties of undefined (reading 'dotnet.wasm')
    at blazor.webassembly.js:1:35948
    at window.__wasmmodulecallback__ (blazor.webassembly.js:1:42668)
    at <anonymous>:1:20
    at blazor.webassembly.js:1:43463
    at blazor.webassembly.js:1:43478
    at new Promise (<anonymous>)
    at Object.start (blazor.webassembly.js:1:34639)
    at Object.At [as start] (blazor.webassembly.js:1:59571)

### .NET Version

Microsoft.NET.Sdk.BlazorWebAssembly .NET 8.0

### Anything else?

Any Help would be appreciates or a fix for it.

Thanks a lot!

**Comment by TasmanianDev69** [comment]
I provide a Repro till 3.04

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Can you please share the output of the `Network` tab from the browser DevTools?
Also, a repro too please.
