### ISSUE TITLE
Some APIs do not verify the TOKNE expiration date

### ISSUE THREAD

**Issue by SpringHgui** [dotnet/aspnetcore#54635]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

my config
```
builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
              .AddJwtBearer(options => {
                  options.TokenValidationParameters = new TokenValidationParameters {
                      ValidateIssuer = false,
                      ValidateAudience = false,
                      ValidateLifetime = true,
                      ClockSkew = TimeSpan.FromSeconds(Convert.ToInt32(Configuration.GetSection("JWT")["ClockSkew"])),
                      ValidateIssuerSigningKey = true,
                      ValidAudience = Configuration.GetSection("JWT")["ValidAudience"],
                      ValidIssuer = Configuration.GetSection("JWT")["ValidIssuer"],
                      IssuerSigningKey = new SymmetricSecurityKey(Convert.FromBase64String(Configuration.GetSection("JWT")["IssuerSigningKey"]))
                  };
              });
```

because of `  ValidateLifetime = true,`  all interfaces have an expiration time checked

But there are some interfaces that I want it to never need to check the expiration time

### Describe the solution you'd like

add Callback function in `JwtBearerEvents `

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core** tag.
