### ISSUE TITLE
Questions around PersistentComponentState in Blazor

### ISSUE THREAD

**Issue by DillionVVV** [dotnet/aspnetcore#54633]
Hi all;

A couple of questions around PersistentComponentState:

First, is PersistentComponentState tied to the SignalR circuit or global to the app? For Blazor render mode InteractiveServer Microsoft says the way to avoid reading in data twice for a page (pre-render and again post-render) is to [save it the first time using PersistentComponentState and then the second time just use the data saved off to it](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/prerender?view=aspnetcore-8.0#persist-prerendered-state).

Is this persisted data global to the app or is it scope level data tied to the session/circuit? Reading the docs it sounds like it's global, but it suggest as the key nameof({VARIABLE}) and for multiple users hitting the same page, they would have the same key.

That will work if the data is per session/circuit. That will have key name conflicts if it is global.

Second, is there any advantage to PersistentComponentState over MemoryCache? Why not use MemoryCache? Is there any downside to doing so? [Reading the Microsoft documentation](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.persistentcomponentstate?view=aspnetcore-8.0) it looks like this is an app global data store, not a per circuit store. So I think MemoryCache is basically the same thing.

The one difference is PersistentComponentState serializes the data to JSON. That's a performance hit if the data stays on the same app, but is critical if that is copied to other instances.

Thanks.

**Comment by javiercn** [comment]
@DillionVVV thanks for contacting us.

`PersistentComponentState` is scoped to the user session (the circuit) and its available only when the application is initializing (typically the first render) and afterwards it is no longer available.
