### ISSUE TITLE
Add Perhaps additional event to the component life cycle for SSR pages

### ISSUE THREAD

**Issue by htmlsplash** [dotnet/aspnetcore#54668]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Is it possible to add a new event to the components life cycle that runs after initialization but before rendering of the component takes place? Something similar to OnPreRender in Webforms. This event would run _after_ all current component life cycle methods have finished running. This would be only for SSR pages/components. If that's not possible, what about having a server version of OnAfterRender method?

Why?
SSR pages have different needs and are subject to different limitations. Sometimes, it is necessary to run a piece of logic/code later during processing of current SSR request. For example, in Webforms, the idea was to run some code after initialization and postback event handling took place but before the Control(s) was rendered.

Use case:

We have a notification manager component that is placed on the main page (in the App component). Its purpose is to render notifications. Due to lack of options (where we can place the code to check if there are any notifications created by other components during page request), it does this OnInitialized method. Unfortunately, the OnInitialized  method of the notification manager will be invoked first and then all other components will run (and maybe creating notifications). Because the components run after the notification manager component, the notifications will not be send to the client when the request completes.

### Describe the solution you'd like

Add OnPreRender event life cycle method for SSR pages/components.

**Comment by javiercn** [comment]
@htmlsplash thanks for contacting us.

OnInitialized, OnParametersSet, etc are concepts defined in ComponentBase. 

I think for your scenario there are other alternatives that would work here that don't require a custom lifecycle method. If you can think of how this would work, you can implement it in your own version of ComponentBase. 

However, from what I can tell you have a parent component that renders and within it, multiple children that render and want to add content to the parent output. In that scenario, you can render a CascadingParameter on the parent with an object that other components can use to add notifications.

The object that you pass can have a callback that you can register for in your parent component to trigger a re-render when a new notification has been added. If you want to "batch" the notifications and perform a single render, then you can use InvokeAsync within your callback, call `Task.Yield()` and then call `StateHasChanged()`

**Comment by htmlsplash** [comment]
Clarification:
"However, from what I can tell you have a parent component that renders and within it" - That's not correct. The Notification Manager component has no children, it is just a stand alone component. The message queue it reads comes from Http session.

So the flow is quite simple.

Components during the request can access the message queue stored in Http session via inject DI service. They add messages as they require to do so.
The Notification Manager accesses the messages the same way via the same DI service. Then it just renders them.

The Notification Manager has relationship nor does it know about any component that's populating the queue, and vice versa is true, components don't know anything about Notification Manager. This model simple and highly de-coupled.

Is there a reason why we cannot have OnPreRender on SSR pages? It shouldn't be that difficult as SSR components live only during a single request and the request is torn down after all components render.
