### ISSUE TITLE
State management

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#5467]

**Comment by vertonghenb** [comment]
The following repo is pretty interesting : https://github.com/TimeWarpEngineering/blazor-state, uses `MediatR`.

**Comment by guardrex** [comment]
@rynowak This issue doesn't appear on the roadmap's backlog issue list: https://github.com/aspnet/AspNetCore/issues/8177

**Comment by mkArtakMSFT** [comment]
Closing this issue as we have nothing concrete proposed here. If there is something specific you believe should be done here please file a new issue with your specific proposal.
