### ISSUE TITLE
WebSockets.AcceptWebSocketAsync disables custom exception handler

### ISSUE THREAD

**Issue by fstugren** [dotnet/aspnetcore#54671]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have an asp.net 8.0 application that I am modifying to also use web sockets and the wss protocol.

The app has an exception handler middleware that catches exceptions from the middleware chain.

```
app.UseExceptionHandler(
    new ExceptionHandlerOptions()
    {
        AllowStatusCode404Response = true,
        ExceptionHandler = this.OnUnhandledException,
    });

```
The new change registers the usage of web sockets:

`app.UseWebSockets();
`

Later, the request processing middleware accepts the web socket call:

`var sourceSocket = await context.WebSockets.AcceptWebSocketAsync(subProtocol);
`

I noticed that once **the call to AcceptSocketAsync completes any exception thrown by code that executes after that call will not be caught by the custom exception handler**. I assume that the upgrade of the connection from https to wss changes something in the application stack, which causes the http exception handler to be bypassed.

- Can someone explain what happens when the web socket is accepted and how we can preserve the exception handler?
- If the custom exception handler middleware is bypassed, what can it be replaced with? I could not find a different sequencing of the middlewares to make this work.

Thanks

### Expected Behavior

**Expected**: any exceptions from code that follows the AcceptSocketAsync call behave like the exceptions that can happen before that call. 
**Observed**: the custom exception handler middleware is not entered for any exceptions in code that follows. However, logging show that the asp.net default exception handler method Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.HandleException() is in fact still invoked.

**Comment by Tratcher** [comment]
The exception handlers only handle exceptions before the response starts, so they can generate an alternate response. Once the response starts it can't be changed so the exception handlers are skipped. AcceptWebSocketAsync is one way of starting the response. Writing to the response body and then throwing an exception would produce a similar result.

**Comment by Tratcher** [comment]
https://github.com/dotnet/aspnetcore/blob/cf46191a3a181df3e298a0e3f15b2ddb1c3308fb/src/Middleware/Diagnostics/src/ExceptionHandler/ExceptionHandlerMiddlewareImpl.cs#L133-L139

**Comment by fstugren** [comment]
Thanks @Tratcher - this makes perfect sense. It wasn't clear from the documentation that AcceptWebSocketAsync is similar to writing the response body for a regular http request. Any error from code that runs after the writing of the response body has started wouldn't hit the custom exception handler either and needs to be handled separately, like in your code sample..
