### ISSUE TITLE
NavigationManager issue in blazor webAssembly App

### ISSUE THREAD

**Issue by xccu** [dotnet/aspnetcore#54682]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

When develop blazor webAssembly app **8.0.0** with NavigationManager and QueryString in url. Add querystring in url and skip, parameters with  **[SupplyParameterFromQuery]** can not get  corrcet values from query string. 

**environment and package:**
_.net 8.0
Microsoft.AspNetCore.Components.WebAssembly 8.0.0
Microsoft.AspNetCore.Components.WebAssembly.DevServer 8.0.0_

**Demo codes**
Example1.razor
```
@page "/params-example-1"

@inject NavigationManager NavigationManager

<h3>Params Example1</h3>
<p role="status">id: @_id</p>
<button class="btn btn-primary" @onclick="OnSkip">Skip</button>
<button class="btn btn-primary" @onclick="OnSkipWithParams">Skip With Params</button>

@code {

    [Parameter]
    [SupplyParameterFromQuery]
    public string? Id { get; set; } = default!;

    private string _id;

    protected override async Task OnInitializedAsync()
    {
        _id = Id;
        await base.OnInitializedAsync();
    }

    public void OnSkip()
    {
        NavigationManager.NavigateTo("/params-example-2");
    }

    public void OnSkipWithParams()
    {
        NavigationManager.NavigateTo("/params-example-2?id=0001");
    }
}
```
Example2.razor
```
@page "/params-example-2"

@inject NavigationManager NavigationManager

<h3>Params Example2</h3>
<p role="status">id: @_id</p>
<button class="btn btn-primary" @onclick="OnSkip">Skip</button>
<button class="btn btn-primary" @onclick="OnSkipWithParams">Skip With Params</button>

@code {
    [Parameter]
    [SupplyParameterFromQuery]
    public string? Id { get; set; } = default!;

    private string _id;

    protected override async Task OnInitializedAsync()
    {
        _id = Id;
        await base.OnInitializedAsync();
    }

    public void OnSkip()
    {
        NavigationManager.NavigateTo("/params-example-1");
    }

    public void OnSkipWithParams()
    {
        NavigationManager.NavigateTo("/params-example-1?id=0002");
    }
}
```
![snapshoot](https://github.com/dotnet/aspnetcore/assets/7534189/3e7813c5-6fa7-4c43-b254-f67b5f694ee9)

### Expected Behavior

Querystring in url sholld got the correct value via **[SupplyParameterFromQuery]** as **.net 6.0**

**environment and package:**
_.net 6.0
Microsoft.AspNetCore.Components.WebAssembly 6.0.0
Microsoft.AspNetCore.Components.WebAssembly.DevServer 6.0.0_

![snapshoot2](https://github.com/dotnet/aspnetcore/assets/7534189/291eec59-825e-4fd3-894d-257eb110535b)

### .NET Version

8.0

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This should be fixed in the latest 8.0.3 release.
