### ISSUE TITLE
Redis distributed cache does not need to use Lua

### ISSUE THREAD

**Issue by mgravell** [dotnet/aspnetcore#54685]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

The [Redis implementation of `IDistributedCache`](https://github.com/dotnet/aspnetcore/blob/main/src/Caching/StackExchangeRedis/src/RedisCache.cs) uses Lua for the "set" path; this means it doesn't work without Lua. Lua is Redis v3+, but this gap impacts things like Garnet, which acts as a Redis-ish (¿Redish?) server (on top of FASTER). See https://github.com/microsoft/garnet/issues/85

Upon analysis, the current code does not actually seem to use Lua *usefully* - it *looks* like this can be replaced with either `MULTI`/`EXEC` or just F+F pipeline.

In addition to increasing backend compatibility, this would be more efficient:

- no need to `SCRIPT LOAD`
- no need to absorb the overheads of the current ad-hoc/script command API ("known" commands use a more efficient path, and have array arguments)
- no need for the server to initialize and execute the Lua runtime each time

### Describe the solution you'd like

System works without Lua

**Comment by mgravell** [comment]
(note for readers: I'm the area owner for this; this ticket is mostly intended for tracking, visibility, and gathering feedback/input)

**Comment by twenzel** [comment]
@mgravell will there be a "service release" of `Microsoft.Extensions.Caching.StackExchangeRedis` or will this feature be available fpr .NET 9+ only? Otherwise Microsoft garnet can't be used as replacement for redis server at the moment.

**Comment by mgravell** [comment]
whether something qualifies for backport is a complex discussion about whether it is a critical bugfix, security fix, or feature - in all honestly, this sounds more like "feature", in which case the *default* answer (not absolute, but general guide) would be "no"; however, in this case it might be moot - since it also targets netstandard2.0, which should work on net8 and a whole bunch of others.

**Comment by Santas** [comment]
It'd be great to see in .NET 8.
