### ISSUE TITLE
[Blazor] OnKeydown event strange behavior, use enter key to search

### ISSUE THREAD

**Issue by niltor** [dotnet/aspnetcore#54684]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Project Info

```xml
<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.3" PrivateAssets="all" />
  </ItemGroup>

</Project>
```

## Issue Description

When using the onkeydown event, a strange behavior occurs.
Look at the following sample code:
```razor
@page "/"

<PageTitle>Home</PageTitle>

<h1>Keydown Issue Sample</h1>

<input type="text" @bind="SearchKey" placeholder="SearchKey" @onkeydown="KeyDown">

<button @onclick="Search">Search</button>


<div>
    @foreach (var item in filterData)
    {
        <div>@item</div>
    }
</div>

@code {
    private string SearchKey { get; set; } = string.Empty;

    private List<string> Data = ["Keydown", "Issue", "Sample"];
    private List<string> filterData = [];

    protected override void OnInitialized()
    {
        base.OnInitialized();
    }

    private void Search()
    {
        if (string.IsNullOrEmpty(SearchKey))
        {
            filterData = Data;
        }
        else
        {
            filterData = Data.Where(x => x.ToLower().Contains(SearchKey.ToLower())).ToList();
        }
    }

    private void KeyDown(KeyboardEventArgs e)
    {
        if (e.Key == "Enter")
        {
            if (string.IsNullOrEmpty(SearchKey))
            {
                filterData = Data;
            }
            else
            {
                filterData = Data.Where(x => x.ToLower().Contains(SearchKey.ToLower())).ToList();
            }
            // StateHasChanged();
        }
    }
}
```

This is a common search function. I need to perform a search event when the enter key is pressed in the input box. Pressing enter for the first time always has no effect.

Although the event is triggered, the content does not display as expected.

When I press enter twice, or long press enter without releasing,
The page content will be displayed normally.

Here is a button event for comparison. Clicking the button can be displayed as expected.

### Expected Behavior

When the enter key is pressed, it can have the same search effect as clicking the button.

### Steps To Reproduce

[Full example repository](https://github.com/niltor/IssueSample)

### .NET Version

8.0.202

**Comment by gragra33** [comment]
try this:
```razor
<input type="text"
    @bind="SearchKey" placeholder="SearchKey"
    @onkeydown="KeyDown"
    @onkeydown:preventDefault="true"
    @onkeydown:stopPropagation="true">
```

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **blazor** tag.

**Comment by niltor** [comment]
@mkArtakMSFT 
Your responses are robotic and confusing.
I've given a detailed problem description and a complete example project.

You said you tried your best, but have you reproduced the problem?

**Comment by niltor** [comment]
I need to add `@oninput` to update the SearchText's value.

Although I solved the problem, it was very counterintuitive.

If I use Angular, I just need:
```html
<input placeholder="Search" [(ngModel)]="SearchKey" (keyup.enter)="Search">
```
Some details of Blazor are still weird
