### ISSUE TITLE
Optimize mono runtime

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#5469]
We need to figure out what parts of mono.wasm and mono.asm.js we are using and remove everything else.

The original approach is described below.

1. In your wasm binary, implement a function that takes an i32 and, when called, passes it through to
   JS code. On the JS side, track which numbers you receive.
2. Convert the original .wasm file to .wast using 'wasm2wat' from https://github.com/WebAssembly/wabt
3. Use the annotateWast function to emit an instrumented version of that .wast file. Each function
   in it will be modified so that it starts by invoking function 115, passing the ID of the caller.
   Change the '115' const to whatever else is the ID of your compiled function from step 1.
3. Convert the instrumented .wast back to .wasm using 'wat2wasm'
4. Run your application using the instrumented .wasm file. After exercising all reachable code paths,
   use the browser debug console to evaluate the list of function IDs that were invoked.
5. Update the 'usedFunctionIds' array above.
6. Use the stripWast function to generate a stripped version of your original .wast file in which all
   the uncalled functions are replaced with empty stubs.
7. Convert the stripped .wast file to .wasm using wat2wasm
8. Use the stripped .wasm file in your application
```

**Comment by pranavkm** [comment]
This should be covered as part of #22432.
