### ISSUE TITLE
SDK is missing some packages for .NET Framework targets

### ISSUE THREAD

**Issue by WenningQiu** [dotnet/aspnetcore#54696]
The SDK (Microsoft.NET.Sdk.Web) makes all ASP.NET Core packages available to .NET 6+ targets; however, some packages appear to be not accessible to .NET Framework tfms (e.g. net48). So I have to explicitly reference those missing packages:

```
  <ItemGroup Condition=" '$(TargetFramework)' == 'net48' ">
    <PackageReference Include="Microsoft.AspNetCore.Authentication" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authorization" Version="8.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Cookies" Version="2.2.0" />
  </ItemGroup>
```

Note that some of those packages (Microsoft.AspNetCore.Authentication, Microsoft.AspNetCore.Authentication.Cookies) are now deprecated, while others (Microsoft.AspNetCore.Authorization) are kept up-to-date.

So why does the SDK not make ASP.NET Core packages consistently available to all build targets? What is the right solution for my situation as I don't want to reference deprecated packages.

**Comment by martincostello** [comment]
Does a [FrameworkReference](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/target-aspnetcore?view=aspnetcore-8.0&tabs=visual-studio#use-the-aspnet-core-shared-framework) work for you?

Otherwise you'll have to reference those old deprecated versions as newer versions are not published to NuGet.org.

**Comment by WenningQiu** [comment]
I changed to "Microsoft.NET.Sdk" and added:

```
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
```

However, it does not appear to be taken:

![image](https://github.com/dotnet/aspnetcore/assets/4291622/dec118b2-3c01-4fd9-b82f-9dce986f371d)

**Comment by martincostello** [comment]
Which version of the .NET SDK are you using?

**Comment by WenningQiu** [comment]
I have two versions installed:

C:\>dotnet --list-sdks
6.0.419 [C:\Program Files\dotnet\sdk]
8.0.100 [C:\Program Files\dotnet\sdk]

**Comment by martincostello** [comment]
I'm not sure how to progress further forward with this other than suggest your downgrade to `2.1.*` version of those `2.2.*` packages. Only ASP.NET Core 2.1 still supports usage with .NET Framework.

**Comment by WenningQiu** [comment]
@martincostello, thanks for the help!
