### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by grahamehorner** [dotnet/aspnetcore#5470]
Please consider how Blazor could request or inject content/embedded resources into a browser cache form display rendering ie. images, fonts, etc

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
