### ISSUE TITLE
UsePathBase not working for Blazor Web App NET8 with individual accounts interactivity mode server

### ISSUE THREAD

**Issue by jsandv** [dotnet/aspnetcore#54723]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I created a new Blazor Web App with global server interactivity and individual accounts template in Visual Studio (17.9.4).

I need to run with PathBase middleware working.
i.e
```
var app = builder.Build();
**app.UsePathBase("/site2");**
```

### Expected Behavior

I should now be able to use an url like:
https://localhost:5001/site2 as if im on https://localhost:5001
and
https://localhost:5001/site2/counter as if im on https://localhost:5001/counter

### Exceptions (if any)

if i navigate to https://localhost:5001/site2/counter in chrome/edge, it only displays "Not Found" message. If i refresh really fast i can see that the actual page is initially loaded, then im served with the "Not found" after. My guess is that when the socket attaches the blazor router does not find "/site2/counter" in this mode.

### .NET Version

.NET SDK (8.0.203)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. It looks like you've missed to set the `base` tag with the same value. You can read more about this in our docs: https://learn.microsoft.com/aspnet/core/blazor/host-and-deploy/?view=aspnetcore-8.0&tabs=visual-studio#app-base-path

**Comment by jsandv** [comment]
Only setting app.UsePathBase("/alternate"); works in .NET6,7,8 for blazor server. 

Anyways, i did test with setting base in app.razor as well.

Steps to repro:
1:
dotnet new blazor --all-interactive --auth Individual --interactivity Server --use-local-db
in program.cs on line 39, add 
`app.UsePathBase("/alternate"); //(directly after var app = builder.Build();)`
Goto https://[localhost:7277/alternate](https://localhost:7277/alternate)
You will get "Not found" in browser. 

This workes in blazor server for .NET6,7,8

2:
Goto "app.razor"
Update line 7 to
` <base href="/alternate/" />`

3:
dotnet watch
The app will start and navigate to i.e http://localhost:5070/ in browser. 
_Side Note: The app will now fail. In blazor server 6,7,8, the app will work at both / and /alternate and /alternate/_
In browser navigate to the actual "correct" destination based on the config, i.e: http://localhost:5070/alternate
**The app will appear to work fine**
Click on the page "Auth Required"
You will be redirected to login
Click on the page "Auth Required" once more
**You will be redirected to: http://localhost:5070/alternate/auth**
And you will get this exception in console:
```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.InvalidOperationException: Endpoint /auth (/auth) contains authorization metadata, but a middleware was not found that supports authorization.
      Configure your application startup by adding app.UseAuthorization() in the application startup code. If there are calls to app.UseRouting() and app.UseEndpoints(...), the call to app.UseAuthorization() must go between them.
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.ThrowMissingAuthMiddlewareException(Endpoint endpoint)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
         at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.InvokeCore(HttpContext context, PathString matchedPath, PathString remainingPath)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

**Comment by willpinha** [comment]
I'm having the same problem mentioned by @jsandv. Any updates on?

**Comment by cdock1029** [comment]
I'm still seeing this problem with default Blazor web app template and individual accounts. I'm not using any interactivity, just server rendering.

```html
 <base href="/app/" />
```

Adding these 2 lines after UsePathBase fixes the immediate error...
```csharp
WebApplication app = builder.Build();
app.UsePathBase("/app");
app.UseRouting();
app.UseAuthorization();
```

but when accessing an authorized route when not logged in, the redirect does not honor path base.

```razor
 <AuthorizeRouteView RouteData="routeData" DefaultLayout="typeof(Layout.MainLayout)">
     <NotAuthorized>
         <RedirectToLogin />
     </NotAuthorized>
 </AuthorizeRouteView>
```

`RedirectToLogin` uses

```csharp
 protected override void OnInitialized()
 {
     NavigationManager.NavigateTo($"Account/Login?returnUrl={Uri.EscapeDataString(NavigationManager.Uri)}", forceLoad: true);
 }
```
but for some reason this does not do the redirect navigation with the path base.

**Comment by Zaraxxx** [comment]
Add this in you Program.cs:
`app.UseRouting();`
