### ISSUE TITLE
Cannot create a new Blazor(Razor Component) inside a sub folder. ( this works in .NET 8)

### ISSUE THREAD

**Issue by bhrugen** [dotnet/aspnetcore#54726]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

It gives and error and i am unable to build 
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0234	The type or namespace name 'Components' does not exist in the namespace 'LearnBlazor.Components.Pages.LearnBlazor' (are you missing an assembly reference?)	LearnBlazor	C:\Users\bhrug\OneDrive\Desktop\New Blazor Course\Source Code\LearnBlazor\Components\_Imports.razor	10	Active

### Expected Behavior

Project should build successfully

### Steps To Reproduce

1. Create a new .NET 9 project using blazor web app (server mode / interactivity as Global)
2. In the Components/Pages folder create another folder (I have called that LearnBlazor)
3. Create a new razor component in that folder.
4. Try to build the project and you will see the error.

Workaround is to remove @using LearnBlazor.Components in the _Imports.razor but then i cannot any import statements for anything inside the components folder like if i create a shared component i have to write complete path which is ugly.
![image](https://github.com/dotnet/aspnetcore/assets/20101947/b6198676-2be6-4b05-a551-7e4bb5412524)

### .NET Version

9.0.100-preview.2.24157.14

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Can you share the content of the `.csproj` file after you add the Razor component?
Also, can you try to build the project from the command line (using dotnet build) and see if that succeeds?
