### ISSUE TITLE
ASP.NET Core 8 Web API causing blocking behavior

### ISSUE THREAD

**Issue by alzubitariq** [dotnet/aspnetcore#54730]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Describe the bug

I have two methods inside the controller Test1() and Test2()

Each request to the Test1() method will enter the method and initiate the asynchronous operation of delaying for 15 seconds. However, since each request awaits the completion of this task, none of the requests will be blocked from entering the method. 

But what I saw the requests are blocked from entering the method like, In other words, if I request the Test1() twice at the same time, the first request will wait 15 seconds, and the second request will wait 30 seconds.

Test2() method within API are still accessible, but the particular method Test1() is causing blocking behavior

![blocking](https://github.com/dotnet/aspnetcore/assets/79016283/27c26c0c-f1ae-4161-9cc7-e8aa5a746773)

### Expected Behavior

How to achieve the desired behavior where each request to the API method Test1() is processed concurrently and only waits for the actual delay inside the method

### Steps To Reproduce

Create new ASP.NET Core 8 Web API
Create to action method inside the controller 

`[HttpGet]
public async Task<IActionResult> Test1()
{
    await Task.Delay(15000);
    //await Task.Run(async () => await Task.Delay(15000));
    var i = 10;
    return Ok("test1");
}

[HttpGet]
public async Task<IActionResult> Test2()
{
    //await Task.Run(async () => await Task.Delay(15000));
    //var i = 10;
    return Ok("test2");
}`

### .NET Version

8.0.202

**Comment by martincostello** [comment]
How are you calling these controller methods? Requests in a browser, with unit tests, something else?

Your code snippets also don't match the screenshot - can you clean them up to just contain the relevant minimal amount of code needed to demonstrate things (such as removing the commented-out parts)?

**Comment by alzubitariq** [comment]
@martincostello  Yes, Requests in a browser

Here is the code 

` [ApiController]
  [Route("api/[controller]/[action]")]
  public class WeatherForecastController : ControllerBase
  {

      [HttpGet]
      public async Task<IActionResult> Test1()
      {
          await Task.Delay(15000);
          return Ok("test1");
      }

      [HttpGet]
      public async Task<IActionResult> Test2()
      {
          return Ok("test2");
      }
  }`

**Comment by alzubitariq** [comment]
@martincostello  any thoughts ?

**Comment by martincostello** [comment]
Nothing obvious to me - an individual request will block for 15 seconds in `Test1()` because you've told it to do so. I can't see any reason why you couldn't execute `Test1()` in more than one thread/request at the same time and it wait for each one to finish before doing the next.

**Comment by alzubitariq** [comment]
@martincostello It's really a problem, the lock happens inside the function itself but does not block the main thread

Imagine having thousands of clients and all the them calling methods like this signature public async Task<IActionResult> with  Mr invisible Lock :)

**Comment by martincostello** [comment]
For now I suggest you create a public GitHub repo containing a project that allows others to easily reproduce the issue you're seeing. For example a project containing your controller code, and then a console application that then makes parallel requests to the endpoints and times them and shows that execution time is stacking and each one isn't taking more than 15s by itself.

I don't see anything obvious in the information you've provided that would explain what you're seeing. Are you sure that the requests are entering the method and _then_ blocking, rather than say something on your computer causing requests from the browser to the server to be serialized/rate-limited so that they happen one after the other?

**Comment by alzubitariq** [comment]
@martincostello thank you,

You are right, I created a console application and ran the load test and it worked fine.
The problem was with the browser itself
For example, using Google Chrome, opening two tabs, and trying to create two requests at the same time, here the delay occurs.
But when I open Google Chrome, open the Edge browser, and try to create two requests at the same time, it works fine
