### ISSUE TITLE
Handle scenario where an event handler was specified as the wrong type

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#5473]
Originally reported in #135 

Currently if you declare an event handler with `onsomeevent=@something`, and `@something` isn't a `UIEventHandler`, then at runtime when the event is triggered, you will get `There is no event handler with ID 0`. This is because we only assign event handler IDs when the attribute value is the type we recognize (`UIEventHandler`).

Options:

* Handle it at compile time. Helpers like `@onclick(...)` cover this already, because they are defined to accept a `UIEventHandler`, and the compiler will automatically create one of those for you if you try to pass a compatible `Action<UIEventArgs>` or similar. Or we could have tag helper-type infrastructure that limits what values you can give for all attributes whose names correspond to known HTML events.
* Handle it better at runtime. If you try to raise an event and the corresponding handler attribute didn't have an event handler ID, report something like `Cannot trigger event handler for {eventname} because is not of the correct type. Event handlers must be of type UIEventHandler; you supplied {othertype}.`

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
