### ISSUE TITLE
Design review: Layouts

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#5474]
Currently, the layouts feature uses temporary fake directives such as `@(Layout<SomeType>())`. Once we're able to put in Blazor-specific directives, we should remove this and clean up the API.

We'll also review to what extent we want to make it look similar to Razor Pages layouts. It's not the same thing as Razor Pages layouts because it's a stateful component architecture rather than a one-time HTML-string generator, but we may choose to make the APIs more similar.

**Comment by robertsundstrom** [comment]
What do you think about adding "sections" support to Layout Components?

I know that the concept to "sections" seems a little at odds with component in general, but I feel that they are useful in certain cases. 

Like for having a menu that changes depending on the page/component that uses the layout.

```csharp
@Menu

<div class="content">
    @Body
</div>

@code {
    public RenderFragment Menu { get; set; }

    public RenderFragment Body { get; set; }
}
```

```csharp
<h2>Hello, World!</h2>

<p>Foobar</p>

@section Menu {
    <NavMenu />
}
```

**Comment by robertsundstrom** [comment]
It would enable scenarios like this where you want to set parameters in a section in the LayoutComponent.

```csharp
@section Menu {
    <NavMenu CustomerNo="no" />
}
```

But then... what we actually need is template parameters.

**Comment by pranavkm** [comment]
This feature has changed quite a bit since this was initially filed. If you think there are further issues to be addressed, please file a new issue.
