### ISSUE TITLE
Run .NET in a worker thread

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#5475]
It will be a while before we get to this, but various parts of the architecture are already designed with this in mind.

We should support running Blazor in two modes, auto-selecting which one is best for the current user's browser:

 * **On the browser's main JS thread**, which is necessary for older browsers that don't support WebWorker. The .NET/JS interop can continue using shared memory if we find it's necessary to have good perf on those older browsers (and thread safety is not difficult because it's all synchronous).
 * **In a web worker (background thread) on more up-to-date browsers**. The .NET/JS interop will need to work by serializing any data that is being transferred rather than passing pointers [1].

This will be advantageous because then, even if your .NET code does something that locks up the CPU (such as a GC cycle), the UI will remain perfectly smooth (e.g., during animations or scrolling, or while the user is typing quickly into a textbox).

The existing UI update mechanism is designed around transferring batches of minimal diffs from .NET to JS, so it shouldn't be hugely difficult to have it express those diffs as serialized data rather than pointers into the WASM memory space. We'll have to be careful around things like event handling to ensure that the asynchrony can't result in inconsistency of behaviour versus the synchronous single-threaded model. For example, we will need to force all event delivery to be async as far as the JS side is concerned, even in the non-worker-thread case.

*[1] Strictly speaking, we could also do it with shared memory on even newer browsers that support SharedArrayBuffer. But if we can get satisfactory perf without this, it would be better to serialize because it would mean fewer combinations of browser scenarios, and saves us having to deal with potentially complex thread-safety concerns on the .NET side.*

**Comment by Tewr** [comment]
@cician, @vibeeshan025 would you mind giving some feedback on [this library](https://github.com/Tewr/BlazorWorker), it partially fit the usecase. It's without shared memory, just using messages.

**Comment by andersson09** [comment]
Is this still in the pipeline?

**Comment by MarioBolivar** [comment]
Hello!

Is this still in the pipeline? As a stop-gap, what is the best solution for handling long running jobs so that they don't lock the UI thread? I've seen suggestions of breaking down the jobs into smaller slices and doing something like Task.Delay() between the slices to catch the UI up. Is this the best/only solution at the moment?

**Comment by SteveSandersonMS** [comment]
This issue is a bit confusing, so I'm closing it in favour of https://github.com/dotnet/aspnetcore/issues/28360

This issue talks about running .NET in a worker thread, but that wouldn't provide actual multithreading - it would just run .NET code in a single-threaded way but off the DOM UI thread. I don't think that's what anyone here is really asking for, and if that is what someone wants, I expect they could do it on their own today (but would have to figure out for themselves how to update the DOM in this case).

@MarioBolivar For true multithreading, the issue you want is #28360. That's likely to land in .NET 7 at the earliest. In the meantime yes, you should use typical task-batching techniques to split up long jobs into multiple pieces, each of which can run asynchronously. Generally you can use `Task.Yield()` instead of `Delay` for slightly cleaner results.

**Comment by danroth27** [comment]
Reactivating this given the details in delivering mulithreading support.
