### ISSUE TITLE
Failing `signalr.client.java.Tests` on helix because of missing `java`

### ISSUE THREAD

**Issue by radical** [dotnet/aspnetcore#54775]
[Build](https://dev.azure.com/dnceng-public/public/_build/results?buildId=618695&view=logs&j=8c9dd6ae-5017-5a70-997c-c2386fed4e85&t=e6acbd31-8469-5d42-602d-cb75e71f3b60), and [log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-aspnetcore-refs-heads-main-adf7cd63cb9f494b9b/signalr.client.java.Tests--/1/console.f44ff2d7.log?helixlogtype=result):

```
Downloading from: https://netcorenativeassets.blob.core.windows.net/resource-packages/external/linux/java/jdk-10.0.2_linux-x64_bin.tar.gz
Installing java from jdk-10.0.2_linux-x64_bin.tar.gz https://netcorenativeassets.blob.core.windows.net/resource-packages/external/linux/java/jdk-10.0.2_linux-x64_bin.tar.gz
Unpacking to /root/helix/work/workitem/e/java
./installjdk.sh: line 44: tar: command not found
Failed to install java with exit code: 127
+ chmod +x ./gradlew
+ ./gradlew -Dorg.gradle.daemon=false -PpackageVersion=9.0.0-ci test

ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.
```

@wtgodbe What needs to be done here? Should the whole `signalr.client.java.Tests` be quarantined?

**Comment by wtgodbe** [comment]
@halter73 was looking at this last week: https://github.com/dotnet/aspnetcore/pull/54631

**Comment by wtgodbe** [comment]
https://github.com/dotnet/aspnetcore/pull/54421#issuecomment-2005320226 also related - CC @MackinnonBuck, @mmitche

**Comment by wtgodbe** [comment]
Looks like it's because `tar` isn't installed on the cbl-mariner docker image we switched to recently. https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/1013 should fix
