### ISSUE TITLE
Online interactive tutorials

### ISSUE THREAD

**Issue by conficient** [dotnet/aspnetcore#5478]
One of the cool features of both [KnockoutJS](http://learn.knockoutjs.com/) and [TypeScript](https://www.typescriptlang.org/play/index.html) (as well as many other libraries) is the online tutorial where users can learn by typing the code in a browser, have it compiled and run on the same page.

It would help building Blazor tutorials (as well as help adoption) if this were possible - not sure how much work it would be to the tooling/compiler setup to have a web-assembly version of it?

**Comment by conficient** [comment]
As a pointer to anyone finding this issue, there is a third-party solution available:

https://blazorfiddle.com/

**Comment by danroth27** [comment]
Also https://blazorrepl.com/

**Comment by danroth27** [comment]
Closing as this isn't something we expect to invest in. It's great to see what the community is coming up with for this scenario!

**Comment by conficient** [comment]
That's fine @danroth27 - as you say the community is filling this gap so it's not really necessary for MS to do this.
