### ISSUE TITLE
DataAnnotationsValidator fails to [in]validate on submit a model that it successfully [in]validates while editing

### ISSUE THREAD

**Issue by slepmog** [dotnet/aspnetcore#54792]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

`DataAnnotationsValidator` [is supposed to][1] validate the form both after editing each field and on submitting the form.

If the Model includes a list of validatable objects, then `DataAnnotationsValidator` correctly validates the nested fields while editing, but fails to validate them on submit. Specifically, it invokes `OnValidSubmit` when the Model object is invalid, and even draws green borders around the Input Fields that contain invalid values.

If the model is flat (only includes non-object-typed properties), `DataAnnotationsValidator` validates it correctly both while editing and on submit.

[1]: https://learn.microsoft.com/en-us/aspnet/core/blazor/forms/validation?view=aspnetcore-8.0#data-annotations-validator-component-and-custom-validation

### Expected Behavior

`DataAnnotationsValidator`'s verdict is the same during the editing of the fields and upon submit.

### Steps To Reproduce

Repo: https://github.com/slepmog/BlazorDataAnnotationBugTest

Run the project and edit the fields in both forms, putting negative values in them because those are invalid. Observe the fields get red outline, which is correct, the real time validation is working as it should.

Then click Submit in both forms.  
Observe the message from VALID SUBMIT (that is wrong) in the first form and that the fields now have green borders, despite having same invalid values in them.  
Observe the message from INVALID SUBMIT (that is correct) in the second form and that the fields remain red like they should. 

You should see:
> ![image](https://github.com/dotnet/aspnetcore/assets/7415007/1b922d78-e317-4bd8-a290-246bb6bfc784)

### .NET Version

8.0.202

### Anything else?

VS 17.9.4

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. The behavior you're observing is by-design. You can read about it in our docs: https://learn.microsoft.com/aspnet/core/blazor/forms/validation?view=aspnetcore-8.0#nested-models-collection-types-and-complex-types
