### ISSUE TITLE
Enhanced navigation triggers the initialization of layout components

### ISSUE THREAD

**Issue by MyPledge** [dotnet/aspnetcore#54794]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Enhanced navigation triggers the initialization of layout components

### Expected Behavior

Layout components has not changed and should not be reinitialized

### Steps To Reproduce

The default example of the blazor web app template can be reproduced

### .NET Version

8

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Every time a page is being rendered statically, all the components will be reinitialized. The "enhanced" behavior kicks in after the content has been rendered to "patch it" into the DOM.
