### ISSUE TITLE
Binding content in Blazor results in duplication when element is initially empty. 

### ISSUE THREAD

**Issue by AlanSamet** [dotnet/aspnetcore#54806]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![image](https://github.com/dotnet/aspnetcore/assets/5108188/91564e3e-fadf-4306-983c-a00cd6f2887c)

Binding content to an empty string in Blazor results in duplication under certain conditions. See under "steps to reproduce" where this becomes a significant issue within a foreach loop where jsinterop is needed to retrieve a value. Under normal circumstances, binding would be performed differently, but to use contenteditable attributes within a foreach loop and jsinterop for two-way binding, this became an issue. I found this in 7.0 Server and confirmed that it still exists in 8.0 Web App. I noted a workaround in the comments.

Given the following, when the focus is changed from one div to the other, if the content (DefaultEmpty in this case) is null, empty or whitespace initially and focus is changed between controls, the content within the tag will get duplicated. For this part of the example, you must focus the empty one, leave it blank, switch focus, switch back to the empty control, enter content and switch focus again, but when the control is generated after the first load, such as in the @onclick handler, it occurs during the first blur event. I have confirmed this in Chrome and Edge. The cause is that two text elements get created in the DOM if you preview it using F12 dev tools. 

```
<div @onblur="DoBlurSimpleEmpty" @ref="SimpleRefDefaultEmpty" style="border:1px dashed red;width: 50em;" contenteditable="true">@DefaultEmpty</div>
<div @onblur="DoBlurSimpleNotEmpty" @ref="SimpleRefDefaultNotEmpty" style="border:1px dashed red;width: 50em;" contenteditable="true">@DefaultNotEmpty</div>
```

...
```
    ElementReference SimpleRefDefaultEmpty {get;set;}
    ElementReference SimpleRefDefaultNotEmpty {get;set;} 

    string DefaultEmpty {get;set;}= " "; //or null, whatever. 
    string DefaultNotEmpty {get;set;}= "Not Empty";

    async Task DoBlurSimpleEmpty()
    {
        var content = await js.InvokeAsync<string>("getElementInnerText", SimpleRefDefaultEmpty);
        DefaultEmpty = content;
    }

    async Task DoBlurSimpleNotEmpty()
    {
        var content = await js.InvokeAsync<string>("getElementInnerText", SimpleRefDefaultNotEmpty);
        DefaultNotEmpty = content;
    }
```

In app.razor / _host.cshtml
```
    <script type="text/javascript">
        function getElementInnerText(element) {
            console.log(element);
            return element.innerText;
        }
    </script>
```

### Expected Behavior

The expected behavior is the content gets replaced fully. 

### Steps To Reproduce

Create a new .Net Blazor server or web app (I haven't tested this with WASM). Replace the content of counter.razor with the following. This would not be something normally encountered with the way we would typically bind, but because we have a foreach loop with contenteditable divs to allow for the user to edit inline, it requires javascript interop to facilitate two-way binding which exposed this bug. If you click the "Click me" button and edit one of the empty fields then the issue becomes apparent. 

```
@page "/counter"
@rendermode InteractiveAuto
@inject IJSRuntime js
<PageTitle>Counter</PageTitle>

<h1>Counter</h1>
<div @onblur="DoBlurSimpleEmpty" @ref="SimpleRefDefaultEmpty" style="border:1px dashed red;width: 50em;" contenteditable="true">@DefaultEmpty</div>
<div @onblur="DoBlurSimpleNotEmpty" @ref="SimpleRefDefaultNotEmpty" style="border:1px dashed red;width: 50em;" contenteditable="true">@DefaultNotEmpty</div>

@foreach(var i in Enumerable.Range(0, models.Count()))
{
    <p role="status">Current count: <div style="border:1px dashed red;width: 50em;" @ref="refs[models[i]]" contenteditable="true" onblur="@(async() => await DoBlur(models[i]))">@models[i].TextValue</div></p>
}

<button class="btn btn-primary" @onclick="IncrementCount">Click me</button>

@code {
    ElementReference SimpleRefDefaultEmpty {get;set;}
    ElementReference SimpleRefDefaultNotEmpty {get;set;} 

    string DefaultEmpty {get;set;}= " "; //or null, whatever. 
    string DefaultNotEmpty {get;set;}= "Not Empty";

    async Task DoBlurSimpleEmpty()
    {
        var content = await js.InvokeAsync<string>("getElementInnerText", SimpleRefDefaultEmpty);
        DefaultEmpty = content;
    }

    async Task DoBlurSimpleNotEmpty()
    {
        var content = await js.InvokeAsync<string>("getElementInnerText", SimpleRefDefaultNotEmpty);
        DefaultNotEmpty = content;
    }

    //This is the real-world scenario where this bug becomes an issue as I need to bind to a list of items. 
    //The workaround is to invoke a javascript "setElementInnerText" function after assigning the model.TextValue
    async Task DoBlur(Model model)
    {
        var content = await js.InvokeAsync<string>("getElementInnerText", refs[model]);
        model.TextValue = content;
        await InvokeAsync(StateHasChanged);
    }

    public class Model
    {
        public string TextValue {get;set;} //Bug occurs if the string is empty, whitespace or null. Using the expression @(models[i].TextValue ?? " ") or any variant does not fix it. 
    }

    List<Model> models {get;set;} = new();

    Dictionary<Model, ElementReference> refs { get; set; } = new();

    private void IncrementCount()
    {
        models.Add(new Model
        {
            TextValue = models.Count() % 2 == 0 ? $"{models.Count()}" : null
        });
    }
}
```

Within App.razor or _Host.cshtml (for Blazor Server), add the following script:

```
    <script type="text/javascript">
        function getElementInnerText(element) {
            console.log(element);
            return element.innerText;
        }
    </script>
```

### .NET Version

8.0.100

**Comment by javiercn** [comment]
@AlanSamet thanks for contacting us.

Please provide a minimal reproducible project as a public github repository as well as steps to trigger the issue.
