### ISSUE TITLE
Local storage backed component state

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#5480]
It would be convenient to be able to have component state backed by local storage. Something Like

```c#
[LocalStorage]
public string LocalStorageBackedProperty { get; set; }
```

Or maybe this?:

```c#
public LocalStorage<string> LocalStorageBackedProperty { get; set; }
```

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
