### ISSUE TITLE
user-jwts cannot handle comments in JSON secrets.json, and does not inform which file is the problem

### ISSUE THREAD

**Issue by fmfx-benarnold** [dotnet/aspnetcore#54814]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I sometimes keep two or more copies of a configuration value in a project's secrets.json with all but one of them commented out - so that I can quickly and easily switch between values when running the project.

    {
      "ConnectionStrings:Database": "Server=host1....",
      //"ConnectionStrings:Database": "Server=host2....",
      //"ConnectionStrings:Database": "Server=host2....",
    }

When I ran `user-jwts` today it gave me the semi-helpful error

    > dotnet user-jwts create
    '/' is an invalid start of a property name. Expected a '"'. Path: $ | LineNumber: 2 | BytePositionInLine: 2. 

Unfortunately it did not tell me that it was secrets.json to blame, and it took a little while to track down.

### Expected Behavior

Ideally `user-jwts` would simply handle the (admittedly malformed) JSON.  The secrets file has so far been accepted by all the other dotnet tools I've used on the project.

If that is not possible, then it would be incredibly helpful if the error indicated which file the user must fix.

### .NET Version

8.0.200

**Comment by martincostello** [comment]
Assuming it's using System.Text.Json to process the file, it's probably quite simple to do a PR to specify the serialiser options allow trailing commas and comments to fix this.

I made a similar change here: https://github.com/dotnet/sdk/pull/36744

**Comment by martincostello** [comment]
I think the same fix would need to be applied here to have it deserialize your file:

https://github.com/dotnet/aspnetcore/blob/1c8f20be1fc4e97044d7ca93edae3af528bc3521/src/Tools/dotnet-user-jwts/src/Helpers/JwtStore.cs#L38

I'm not sure if it would round-trip your comments when the file is saved back to disk after a change though.

**Comment by fmfx-benarnold** [comment]
Amazing, thanks @martincostello!
