### ISSUE TITLE
Normalize MSBuild paths

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#5481]
Paths in our MSBuild stuff are using `/` we want to normalize them to use `\`. We didn't do it at the time due to issues with invoking the linker. We just need to investigate if it was an error in normalizing them or if the paths need to be using '/'.

Filing this item to track this although is low priority given that it doesn't impact the build or the user experience in any way.

**Comment by pranavkm** [comment]
Closing this. This has changed a bunch since the issue was filed.
