### ISSUE TITLE
Investigate further size reduction optimizations

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#5482]
Right now we run the mono linker optionally as a build step.
By linking the app we reduce anything that is not used/referenced directly by the application.
There are things that are left behind after this process that will likely not work. For example things related to remoting, binary serialization, etc.

We should look into what we can cut while keeping the app working.
Maybe we can do something similar to what we did in the prototype and instrumentalize the linked assembly to see what actually gets used in a normal app and what is being left behind just because something is referencing it.

**Comment by pranavkm** [comment]
We did a pass over linker optimizations during 3.2 and we're happy with the current state.
