### ISSUE TITLE
[.net 8] Blazor webassembly debugger doesn't stop on exception

### ISSUE THREAD

**Issue by Kamys85** [dotnet/aspnetcore#54834]
In Visual Studio it's conveniently to stop debugger when an exception already been thrown. It's possible by mechanism of choosing to stop on specific exceptions in "Exception Settings" dialog. This fact unfortunately we can't observe while debugging WebAssembly (there is no debbuger hit on throwing exception), in server site code it's ok. The problem which I here mentioned has been described in https://github.com/dotnet/runtime/issues/50001 . 

The step to reproduce:
1 - Create Webassembly app
2 - do something that creates an exception
3 - Start in Debug mode and in the Exception Settings dialog select to stop on all CLR exceptions
4 - Expected: VS stops then the Exception happens
What happens: Nothing. You get an error in the browser and need to inspect the console for errors.

Is it must be behaviour? Is it can be changed in future?

**Comment by phil-allen-msft** [comment]
The customer is looking for the "break when exception is thrown, filtered on types" to occur debugging Blazor Wasm.  Is there anything necessary at the application layer to enable this?

**Comment by MackinnonBuck** [comment]
@thaystg, is this a supported scenario?

**Comment by thaystg** [comment]
No, we can enable pause on managed exceptions by enabling the JavaScript exceptions handled and unhandled:
![image](https://github.com/dotnet/aspnetcore/assets/4503299/2897f06b-ebd6-4c37-92c5-04155ad61e93)

**Comment by MackinnonBuck** [comment]
@Kamys85, does selecting that option work for you?
