### ISSUE TITLE
Investigate ways of making the linker faster

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#5483]
Linking adds 4.792s on my machine for Standalone app. We might need to find ways to make it faster if we want to enable it during builds. 

## "Incremental linking".
* As part of the linking process we generate a file with all the roots that we found in the linking process and the things that they reference.
* When we run the linker a second time, we load this file with the old roots and with the elements that they reference.
* We can shortcircuit things that haven't changed in the app.
* We can shortcircuit new roots that reference parts of the application that were trimmed on a previous run.
* We can improve the speed on roots that disappeared from the application as we already have collected the information that they reference.

**The hypothesis here is that on normal changes what we are doing is more of the same. We just add a new view, or reference a new type inside some class, but that the majority of the code doesn't change and doesn't need to be analyzed.**

## Linker server
Instead of running the linker as a process, start up a server that can hold information about previous runs and that already has all the required dlls loaded in memory, saving load time and some analysis time on later runs.

**Comment by redowl3** [comment]
Anything happening with this - it's absolutely killing us.  We've resorted to creating a separate ASP.NET project to make html changes and then copy across to Blazor project, surely this can't be the idea!

**Comment by pranavkm** [comment]
Closing this as this is no longer a concern. The linker is no longer run in the inner loop, and starting in 5.0, likely only going to run during publish.
