### ISSUE TITLE
MAUI Blazor Android - enter keypress on textbox causes infinite loop of form submission

### ISSUE THREAD

**Issue by nine-2-five** [dotnet/aspnetcore#54848]
### Description

On a pristine MAUI Blazor project with a /login page added, when enter button is pressed on a real keyboard, it triggers the click handler on the form's submit button, but it continues triggering it indefinetelly. This doesn't seem to happen on MAUI Blazor Windows app, I only see this behavior in Android Emulator.
Also the click event doesn't fire once, but it fires indefinitely.

### Steps to Reproduce

Here is an almost pristine NET 8 MAUI Hybrid Blazor project, with only the /login page added:
https://github.com/nine-2-five/MauiBlazorWebViewClick

Put the breakpoint on HandleButtonClick and HandleValidSubmit methods in /login page.
It only needs to be started on Android emulator, and fill the login form, then press enter on your real keyboard (not the numpad enter, and not the virtual one in Android).

### Link to public reproduction project repository

https://github.com/nine-2-five/MauiBlazorWebViewClick

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android API 30, and 34

**Comment by Eilon** [comment]
I was able to repro this in a Blazor Web project and running Chrome in an Android Emulator.

Blazor Web repro steps:

1. Create new Blazor Web .NET 8 project (I used Auth:None, HTTPS=yes, RenderMode=Server, Interactivity=Global, but this probably doesn't matter much)
2. Add a new file `~/Components/Pages/Login.razor` with the contents from https://github.com/nine-2-five/MauiBlazorWebViewClick/blob/master/Components/Pages/Login.razor
3. Add a link to the new page from NavMenu.razor: https://github.com/nine-2-five/MauiBlazorWebViewClick/blob/master/Components/Layout/NavMenu.razor#L27-L31
4. In VS set breakpoints in Login.razor in the `HandleButtonClick` and `HandleValidSubmit` methods
5. Launch the app and see URL is similar to `localhost:<PORT>` (and confirm the login page works fine on Windows - both breakpoints get hit only ONCE)
6. Launch Android Emulator
7. In emulator open Chrome and navigate to `https://10.0.2.2:<PORT>` (using same PORT as on Windows)
8. In emulator Chrome navigate to Login page
9. Click in one of the login textboxes
10. Press Enter on the physical keyboard on your computer
11. The breakpoints in VS get hit - but they will hit infinitely no matter how many times you continue

**Comment by MackinnonBuck** [comment]
@nine-2-five, is it possible to repro this on a real device (not an emulator)? If so, could you please provide us with repro steps?

**Comment by nine-2-five** [comment]
@MackinnonBuck I have tried logging an entry to click/submit methods, but no loop in the Android log file was found.
Using `adb shell logcat > log.txt`

**Comment by MackinnonBuck** [comment]
@nine-2-five

> I believe it is either debugger or emulator related.

Could you please confirm whether this can happen when the debugger is _not_ attached?

**Comment by nine-2-five** [comment]
It doesn't seem to happen in Android emulator when no debugger is attached. The API doesn't log but one call to login method, and there aren't repeated log messages for form submit handler.

**Comment by mkArtakMSFT** [comment]
@chabiss do you know who from VS Debugger side can look into this? Seems to be either an emulator issue or a debugger issue.

**Comment by mkArtakMSFT** [comment]
Ping @mauroa

**Comment by mauroa** [comment]
Sorry for the delay @mkArtakMSFT. Yes, I think the best option would be to report a VS Feedback Ticket so we can track and prioritize better. Thanks

**Comment by SteveSandersonMS** [comment]
Closing as external
