### ISSUE TITLE
blazor headcontent throws exception

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#54842]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/blazor-headcontent-throws-exception/10626726)._

---
[severity:Other]
Head content throws exceptions when using global interactive server mode.

Repro:

1) Create a new blazor server app project.

2) For "Interactive Render Mode", select "Server".

3) For "Interactivity Location", select "Global".

4) Add a HeadContent component to the "Home.razor" page.  Inside that component, and any valid HTML (doesn't have to be a blazor component).

5) Run the application.

6) From the "Home Page", navigate to the "Counter" page.

7) Click on the browsers "Back" button (using Edge in this case) or click the sidebar nav link for Counter that also has a meta tag

8) Default blazor error message appears.

Here is the error message from the Output or Immediate Window

```
Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer: Warning: Unhandled exception rendering component: TypeError: Cannot read properties of null (reading 'insertBefore')

System.InvalidOperationException: TypeError: Cannot read properties of null (reading 'insertBefore')
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InvokeRenderCompletedCallsAfterUpdateDisplayTask(Task updateDisplayTask, Int32[] updatedComponents)
Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost: Error: Unhandled exception in circuit 'XwKDhTBqDdbOIORvnq38ZTsq1zlmyisXYpb55dTgcUg'.

System.AggregateException: One or more errors occurred. (TypeError: Cannot read properties of null (reading 'insertBefore'))
 ---> System.InvalidOperationException: TypeError: Cannot read properties of null (reading 'insertBefore')
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InvokeRenderCompletedCallsAfterUpdateDisplayTask(Task updateDisplayTask, Int32[] updatedComponents)
   --- End of inner exception stack trace ---

```

Wait for the Microsoft Developer Community Bot to tell us that this is closed, not enough info or this is expected with no further explanation.

---
#### Feedback Bot on 3/28/2024, 00:45 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by TorreyGarland** [comment]
[BlazorApp4.zip](https://github.com/dotnet/aspnetcore/files/14816755/BlazorApp4.zip)

here is the minimal repo.

Remember to use the browser's back button to reproduce.

**Comment by TorreyGarland** [comment]
A zip file was originally included with the Microsoft Developer Community ticket.

Here is the address to the minimal repo as requested.


[https://github.com/TorreyGarland/BlazorApp4](url)

**Comment by TorreyGarland** [comment]
The problem is due to the default Visual Studio Blazor App template explicitly setting the render-mode for the App.razor file's HeadOutlet component.

Remove the rendermode attribute on the HeadOutlet component and the problem goes away.  

You still may want to dig deeper to find out why this is happening.  This error does not occur when using the PageTitle component, presumably due to the lack of the render mode attribute being set.

The documentation for render mode's should be updated to reflect this.

**Comment by benjaminsampica** [comment]
Seeing this as well. Same reproducible steps. Curiously, everything works as expected in Edge - just a Chrome issue (v123.0.6312.123)

**Comment by vladhorby** [comment]
Running into the same issue in .net 8.0.4.

Having a HeadOutlet with the rendermode set in App.razor and setting the PageTitle in a page results in 
```
System.InvalidOperationException: TypeError: Cannot read properties of null (reading 'insertBefore')
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InvokeRenderCompletedCallsAfterUpdateDisplayTask(Task updateDisplayTask, Int32[] updatedComponents)
```

Removing the rendermode eliminates the error, but the page title is no longer dynamically updated by the page, of course.

Workaround: Setting a default PageTitle **AFTER** the HeadOutlet fixes the problem and updates the title as expected:

```  
<HeadOutlet @rendermode="InteractiveServer"></HeadOutlet>
<PageTitle>Default Page Title</PageTitle>
```

**Comment by benjaminsampica** [comment]
If I swap the position of the isolated css file

`
    <link href="WebApplication4.styles.css" rel="stylesheet" />
    <HeadOutlet @rendermode="new InteractiveServerRenderMode(false)" />
`
to
`
    <HeadOutlet @rendermode="new InteractiveServerRenderMode(false)" />
    <link href="WebApplication4.styles.css" rel="stylesheet" />
`
it works with no issues.

**Comment by TorreyGarland** [comment]
@benjaminsampica Can confirm, this does work!

**Comment by hakenr** [comment]
This reproduces with new Blazor project template!!! (net 8.0.4)
Visual Studio 2022 v17.9.6:
1. Create new project
2. Blazor Web App
3. Next, Next
4. Additional Information
    - Framework: 8.0
    - Auth type: None
    - Configure for HTTPS: Yes
    - Interactive Render Mode: WebAssembly
    - Interactivity location: Global
    - Include sample pages: Yes
    - Do not use top-level statements: Yes
6. Create

Run such project from Visual Studio:
![image](https://github.com/dotnet/aspnetcore/assets/12828888/75f8ebfc-8d02-4350-abe4-356457d3ca8f)

```
blazor.web.js:1 
 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: TypeError: Cannot read properties of null (reading 'insertBefore')
TypeError: Cannot read properties of null (reading 'insertBefore')
Ar	@	blazor.web.js:1
```
and
```
blazor.web.js:1 
 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Error: No element is currently associated with component 1
Error: No element is currently associated with component 1
Ar	@	blazor.web.js:1
```

Moving the Blazor CSS bundle `<link />` after the `<HeadOutlet .../>` resolves the issue:
```razor
    <HeadOutlet @rendermode="InteractiveWebAssembly" />
    <link rel="stylesheet" href="BlazorApp9.styles.css" />
```

**Comment by hakenr** [comment]
It seems that ANY element after `<HeadOutlet />` resolves the issue:
```razor
    <HeadOutlet @rendermode="InteractiveWebAssembly" />
    <test />
```

**Comment by hakenr** [comment]
Woohoo, the issue is most likely caused by the updated **LastPass browser extension**. When I disable LastPass, the issue disappears. When I re-enable LastPass, the issue immediately returns.

I wish Blazor were less "vulnerable" to these situations, but I have to admit this is most likely due to external DOM manipulation without any chance for Blazor to handle it correctly.

Anyway, adding any element after the `HeadOutlet` prevents this issue from occurring.

**Comment by hakenr** [comment]
Duplicates #55085.
LastPass ticket: https://support.lastpass.com/s/question/0D5TP00000AZcL80AL/does-anyone-else-have-issue-with-latest-version-of-lastpass-in-chrome-41290-in-that-certain-websites-either-act-odd-or-cant-even-load-blank-white-screen-if-the-lastpass-extension-is-disabled-the-sites-load-fine-again-?language=en_US

**Comment by rwjdk** [comment]
LastPass 4.130.0 is out that resolves the error

**Comment by tossnet** [comment]
@rwjdk I confirm. It's resolved for Chrome and Edge and also that the trick of placing the TITLE tag after <HeadOutlet worked. 

By the way, did this trick have any side effects?

**Comment by hakenr** [comment]
> LastPass 4.130.0 is out that resolves the error

I can confirm that with 4.130.0 the issue no longer reproduces.

**Comment by MarianSWA** [comment]
@danroth27 Hi Dan, I was able to reproduce this again on .Net 9. I was presenting Blazor to my students and I got the error right after creating the template, with no modifications which was a weird thing to investigate live haha.
I used the Blazor web app template with interactive render mode set to server and the culprit was another extension this time (a crypto browser wallet called Nami). The workaround above worked however I think Blazor server should be more resilient to any extensions the user has installed.

**Comment by danroth27** [comment]
> The workaround above worked however I think Blazor server should be more resilient to any extensions the user has installed.

@MarianSWA We're open to suggestions on how to improve Blazor's resiliency to these kinds of DOM manipulations, but our understanding is that this type of issue is inherent to how DOM diffing frameworks like Blazor work.

**Comment by nssidhu** [comment]
@danroth27 
I understand that this is general accross DOM diffing frameworks. 
But it is very easy to break the entire app, We do integrate lot of external javascript libraries, which could easily update DOM outside of Blazor's watch.
May be marking certain sections of HTML for exclusion from Blazor's tracking, which can be changed by JavaScript so it does not break the Blazor, i.e let Blazor not track excluded areas, something on those lines...
Or May be update the Server side to match up to changes done to DOM.

**Comment by Mike-E-angelo** [comment]
I have been tracking down this error over many months now and for some reason did not find this thread until now.  I am so happy to find the resolution with the order of the `HeadOutlet` tag. 🙏

Another consideration, in addition to installs like LastPass and other extensions, in my case the customer was using a feature of their phone that was automatically translating from English to Spanish.  They disabled that and the errors stopped.

Unfortunately, I deployed the `HeadOutlet` fix shortly after this and haven't been able to get a confirmation if that works if the translation is turned back on, but I am very happy to find a resolution one way or another, nonetheless.
