### ISSUE TITLE
Cannot submit the form because no form on the page currently has that name.

### ISSUE THREAD

**Issue by philasmar** [dotnet/aspnetcore#54854]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am using the .NET8 Blazor Web App with Identity pages. The `ExternalLogin.razor` fails to submit with the following error:
```
Cannot submit the form 'confirmation' because no form on the page currently has that name.
```
This is the code snippet that causes the error:
```
<EditForm Model="Input" OnValidSubmit="OnValidSubmitAsync" FormName="confirmation" method="post">
    <DataAnnotationsValidator/>
    
    <div class="form-floating mb-3">
        <InputText @bind-Value="Input.Username" class="form-control" type="text" autocomplete="off" aria-required="true" placeholder="johndoe"/>
        <label class="form-label">Username</label>
        <ValidationMessage For="() => Input.Username"/>
    </div>
    <button type="submit" class="w-100 btn btn-lg btn-primary">Register</button>
</EditForm>
```

I am using the `InteractiveAuto` render mode. I have tried switching to `InteractiveServer` but that didn't help.  

### Expected Behavior

I should be able to submit the form.

### Steps To Reproduce

* Create a .NET8 Blazor Web App with Identity scaffolding
* Set up external authentication using Google
* Reach the `ExternalLogin.razor` page
* Click on `Register`

### .NET Version

8.0.203

**Comment by javiercn** [comment]
@philasmar thanks for contacting us.

Identity pages are not meant to be interactive. The only supported scenario for login is SSR.
