### ISSUE TITLE
SignalR TypeScript client - WebSocket - surface out the 'upgrade' event

### ISSUE THREAD

**Issue by Jidong-Yang** [dotnet/aspnetcore#54865]
We are using the `HubConnection` to connect to a SignalR server through WebSocket.

We are interested in the **response headers** sent back from the server when we **upgrade** the initial HTTP connection to WebSocket protocol.

However, after a bit dive into the source code of both [@microsoft/signalr](https://www.npmjs.com/package/@microsoft/signalr) and [@types/ws](https://github.com/websockets/ws), it seems that when dealing with WebSocket transport, the `class WebSocketTransport` is not listening to the `upgrade` event emitted by [WebSocket](https://github.com/websockets/ws/blob/2405c17775fb57f5e07db123c6133733dd58bbab/lib/websocket.js#L920).

Hence, I'm wondering is there a way to expose the 'upgrade' event to `HubConnection` so that we can get the http response header from the server when doing upgrade handshake?

**Comment by Jidong-Yang** [comment]
The example code would be:

```typescript
class WsClient
{
    ...
     public async CreateConnection()
    {
        this.connection = new HubConnectionBuilder()
            .withUrl(url, options)
            .withAutomaticReconnect()
            .build();

        // the implementation we wish to have:
        this.on('upgrade', (upgradeResponseMessage)=>the handler to read the response headers);
    }
    ...
}
```

**Comment by BrennanConroy** [comment]
Not a fan of exposing this.
1. The `"upgrade"` event is node specific (maybe even specific to the "ws" package), not part of the browser API
1. `connection.on(...)` is how you register methods the server calls, it's be weird to have it do something else for special string(s)
1. `connection.onupgraded` from the linked issue at least makes it strongly typed and wouldn't mix with registered methods but, we don't expose many transport specific APIs, SignalR is supposed to be transport agnostic for the most part

There is a workaround for this, you can register a custom websocket type for SignalR to use via the `IHttpConnectionOptions`:
```js
class SomeClass {
    connection;
    headerFromUpgrade;

    Start() {
        connection = new HubConnectionBuilder().withUrl("url", {
            WebSocket = MyWS
        }).build();

        const self = this;
        class MyWS extends WebSocket {
            constructor(url, protocols, options) {
                super(url, protocols, options);

                this.on("upgrade", (e) => { self.headerFromUpgrade = e.headers });
            }
        }
    }
}
```

**Comment by Jidong-Yang** [comment]
Thank Brennan for the workaround. Yep, the 'upgrade' event is specific to the `ws` package in my view, and the workaround should be the sufficient and proper solution here!
