### ISSUE TITLE
[Static web assets] Define static web asset endpoints in the SDK and generate an endpoints manifest

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#54873]
Tracks https://github.com/dotnet/sdk/pull/39636

* Introduces a `StaticWebAssetEndpoint` to represent the endpoints where any given static web asset must be available.
* Defines endpoints for all static web assets in the app.
  * Precomputes all the headers for all endpoints Content-Type, Content-Length, ETag, Last-Modified, Accept-Ranges
* Applies `Content-Negotiation` to compressed assets.
  * Maps the compressed assets to all the routes available to their respective related asset.
    * Duplicates the endpoints and points them to the compressed versions including `Content-Encoding` and `Vary` headers as well as a `Content-Encoding` selector that is used at runtime to disambiguate what asset to serve for an incoming request.
  * Updates compressed asset endpoints with `Content-Encoding` and `Vary` headers.

**Comment by javiercn** [comment]
https://github.com/dotnet/sdk/pull/39636

**Comment by dyyhf123** [comment]
应该是 Vary: Accept-Encoding 吧，不理解 Vary: Content-Encoding 有什么作用
