### ISSUE TITLE
Trigger a js custom event after Blazor boot complete

### ISSUE THREAD

**Issue by uazo** [dotnet/aspnetcore#5488]
I need to register some javascript functions (using Interop.registerFunction.ts), but currently I can't because `window ['Blazor'].registerFunction` is made available only after booting.

Is it possible to insert a 'BlazorOnLoad' event after boot() in boot.ts?

**Comment by pranavkm** [comment]
This has changed significantly since this issue was filed. `Blazor.registerFunction` and you can use \ await `blazor.start` to execute scripts before and after blazor has loaded.
