### ISSUE TITLE
[Blazor] Parameter on root page causes loss of layout/CSS

### ISSUE THREAD

**Issue by carlfranklin** [dotnet/aspnetcore#54880]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If you add an optional parameter to Home.razor in a Visual Studio Blazor template, the parameter works, but the layout goes away, as does the CSS styling for the page.

### Expected Behavior

I expected the page to render properly.

### Steps To Reproduce

- Create a new Blazor Web App in Visual Studio with Global Server interactivity
- Add a parameter (with required code) to line 2 such as @page "/{foo}"
- Run the project, and notice the lack of layout, styling, NavMenu, etc.

### Exceptions (if any)

It works fine in .NET 7

### .NET Version

8

### Anything else?

I imagine this is a bug in the router.

**Comment by javiercn** [comment]
@carlfranklin thanks for contacting us.

You are capturing all the requests to static files in that route. You need to use `@page "{foo:nonfile}"`

**Comment by carlfranklin** [comment]
Awesome. Is that documented?
