### ISSUE TITLE
Improve wrapping of values on ASP.NET Core development exception page

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#54894]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Long values on the development exception page need wrapping. Current wrapping isn't ideal:

![image](https://github.com/dotnet/aspnetcore/assets/303201/633f4eca-26e9-40c5-85dd-7e2d619c0b66)

It looks like values are wrapped on spaces and hyphens.

Also, if there are no spaces or hyphens then a horizontal scroll bar is displayed:

![image](https://github.com/dotnet/aspnetcore/assets/303201/9abd745c-36a2-4541-bc13-36ef2f29faf1)

There are CSS options that can be used to improve wrapping so long values are wrapped more consistently - https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_text/Wrapping_breaking_text

### Expected Behavior

Better wrapping. I don't know exactly what that would look like.

Should test a number of scenarios:
* lorem ipsum
* Long value on non-breaking characters
* Cookie values (long value with hypens)

### Steps To Reproduce

View developer exception page with long cookie or header values.

Remove spaces and hyphens to get a horizontal scroll bar. Or resizing the browser to have a smaller width than values.

**Comment by ElderJames** [comment]
Hello @JamesNK , I can try this.

**Comment by JamesNK** [comment]
Go ahead.

**Comment by ElderJames** [comment]
@amcasey No problem 😃
