### ISSUE TITLE
Razor Components support for VS4Mac

### ISSUE THREAD

**Issue by mhciael** [dotnet/aspnetcore#5490]
I think [that](https://developercommunity.visualstudio.com/content/problem/67655/cant-install-vsix-to-vs-for-mac.html) means I need an mpack instead of a vsix?

**Comment by leebenson** [comment]
Just curious if there's any new ETA for .razor Intellisense support in VS4Mac, with the advent of .NET Core 3.0 and Blazor in official preview now? Thanks @danroth27 and team.

**Comment by danroth27** [comment]
@leebenson We're hoping to deliver Blazor tooling support for VS4Mac in the 8.4 release of VS4Mac.

/cc @sayedihashimi

**Comment by sayedihashimi** [comment]
Yes that is correct, we (Visual Studio for Mac) are working on Blazor server side support currently and hoping to get it in the 8.4 release as Dan mentioned above.

**Comment by mrlife** [comment]
@sayedihashimi Any info yet on when the 8.4 preview will be out?

**Comment by sayedihashimi** [comment]
@mrlife I don't have any specific dates to share at this time, but my guess is that it should be before the end of the year [_no promises as usual :)_]

**Comment by mkArtakMSFT** [comment]
We're closing this as there is no action for us to take here. The support is already in preview in VS4Mac 8.4.

**Comment by sayedihashimi** [comment]
For those interested we added support for Razor Components & Blazor in 8.4 which was recently released https://devblogs.microsoft.com/visualstudio/visual-studio-2019-for-mac-version-8-4-is-now-available/.
