### ISSUE TITLE
Show Connection Status users in blaozr .net 8 with signalR 

### ISSUE THREAD

**Issue by MahdiElahi** [dotnet/aspnetcore#54919]
Hi 
i want show all users logged connection status , show user offline or online with signalR in blazor 8

but 
1. when user sign in change status online 
2.when user sign out change status offline
**3.when user close browser or session is expired change status to offline**

**Comment by BrennanConroy** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com/) using the asp.net-core tag.
