### ISSUE TITLE
Webapp default template exception

### ISSUE THREAD

**Issue by HuaFangYun** [dotnet/aspnetcore#54926]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

[BlazorApp1.zip](https://github.com/dotnet/aspnetcore/files/14853014/BlazorApp1.zip)
Open the project, run it, and then click the login menu, and the page keeps flashing. This is based on the webapp template, but only sets @ rendermode= "@ RenderMode.InteractiveServer"

### .NET Version

8.0.202

**Comment by javiercn** [comment]
@HuaFangYun thanks for contacting us.

The Identity used for login and account management do not support interactive rendering modes.
