### ISSUE TITLE
Using Multiple authentication scheme I am experiencing recursion 

### ISSUE THREAD

**Issue by Notamatall** [dotnet/aspnetcore#54929]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have tried to configure .NET 8 application which uses multiple authentication schemas. In my case I am trying to use cookie and JWTBearer.
I have also added configuration for authentication which allows to dynamically select authentication schema. ( this is crucial to reproduce bug).
Additionally I have defined policy which uses Requirement - AuthorizationHandler which requires User to be enabled.
If Requirement is not Succeeded, request goes into recursion -> authentication -> authorization handler -> forbidden endpoint.

### Expected Behavior

I expect that is should just return me 403. 

### Steps To Reproduce

Way to reproduce -> login with cookie -> requst GetWithCookie endpoint of ContentController.
[project which repoduces](https://github.com/Notamatall/MultipleAuthenticationSchemes)

### .NET Version

8

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. The issue appears to be is that your CookieAuthenticationOptions.LoginPath is redirecting to the page that requires authentication. You should have `AllowAnonymous` on that page to avoid the recursion.

**Comment by Notamatall** [comment]
Login path redirects to unauthorized which is not the case 
Because we are getting forbidden 
![image](https://github.com/dotnet/aspnetcore/assets/59046325/2735d0ab-47fb-4413-b62d-47d710f13474)
Plus both forbidden and unauthorized are not protected 
![image](https://github.com/dotnet/aspnetcore/assets/59046325/f96f642a-95d6-4e1c-8515-5fc59bb7926e)
