### ISSUE TITLE
EventReciever from OL element prevents the Bullet list after inserting hyperlink within the Text Editor in SharePoint Online Webpart

### ISSUE THREAD

**Issue by VinithaJeyakumar** [dotnet/aspnetcore#54923]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When i try to insert a bullet list after inserting hyperlink in the text editor, an eventlistener of keydown prevents the bullet list to insert. The preventDefault function is called in the **_handleKeyDown** function based on a condition. Please check the screenshot below,

<img width="935" alt="image" src="https://github.com/dotnet/aspnetcore/assets/86768683/72148171-c75d-4557-be9d-12cad5077653">

### Expected Behavior

It should be able to insert the bullet list even after inserting links into the Editor.

### Steps To Reproduce

Create a Text Editor within the sharePoint online webpart.
Insert some bullet points with texts.
Now insert a hyperlink inside the Editor.
Then again try to add more bullets to the previously inserted list.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. 
Can you please clarify how ASP.NET Core involved in all this?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This is not something related to this repository. We recommend using [StackOverflow](https://stackoverflow.com) for these types of general questions.
