### ISSUE TITLE
Blazor WebAssembly application hosted in IIS does not load until few tries and gives an ERR_HTTP2_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by goodchaitanya** [dotnet/aspnetcore#54941]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

A Blazor WASM(WebAssembly) based application is hosted on a server that runs on IIS. Every time a new version of the application is deployed to the server, accessing the same from a local browser always gives an 'ERR_HTTP2_PROTOCOL_ERROR'. The exact list of errors is as below:

![image](https://github.com/dotnet/aspnetcore/assets/19190764/8a9264f6-5326-4ac4-9ab6-6e2b2c0057d4)

There are typically a lot more list of errors all the way down, eventually, the browser's refresh icon shall appear and an 'Empty Cache and Hard Refresh' option shall load the page eventually.

If the application supports OIDC, this issue happens twice:

1. First when the application tries to contact the OIDC provider, say AzureAD.
2. Second, after a successful OIDC token issue and when the redirection to the application happens.

I understand that this could be related to network and might be tied to the browser's webassembly trying to download the appropriate Blazor files, but the issue is pretty consistent and happens every time after a new version deployment. Please help.

### Expected Behavior

The application should load fine the first time without the need to clear the cache multiple times and reloading the same.

### .NET Version

7.0.100

**Comment by javiercn** [comment]
@goodchaitanya thanks for the additional details.

Since you say you are applying `no-cache` to all responses it should probably not be a caching issue, however I would make sure by looking at all the responses just in case.

Here are a few things that I would try:
* Does it reproduce within an InPrivate browser window?
* Does the IIS server actually respond with the file?
* Does the network tab show 404, 200, or something else?

Do you try to access the site while its being deployed/inmediately after? I'm not sure what role IIS might be playing here.

**Comment by goodchaitanya** [comment]
@javiercn please find my response below for each of the points:

-     Does it reproduce within an InPrivate browser window? - Yes it is the same behavior in a private window too.
-     Does the IIS server actually respond with the file? - Some of the files are sent, but most of the files are only sent after the second or third 'Clear Cache and Hard Refresh' tries.
-     Does the network tab show 404, 200, or something else? - There are some 200s but a lot of 'fetch' failures when this issue typically happens. Few of the screenshots of the network tab when this happens are as below:
![image](https://github.com/dotnet/aspnetcore/assets/19190764/a1ed3723-704a-4cae-af40-814b783e2400)
![image](https://github.com/dotnet/aspnetcore/assets/19190764/40e3ae9d-48ef-4b88-b744-721544fc652f)

-     Are you accessing over HTTPS? - Yes
-     Do you have a valid HTTPS certificate? - Yes we have a valid https certificate 
Please ignore the issue with app.css, I believe that was more of a file placement issue and that error happens even when the site loads successfully. Also, I can confirm that we only access the site after the deployment is fully complete.

**Comment by goodchaitanya** [comment]
@MackinnonBuck I reckon checking the server side logs and not able to detect anything, however, I will check this again. Will also check if there is anything logged in the event viewer of the server when this issue happens. Unfortunately, I might not be able to provide a minimal repro project for this, but I believe this is an issue with any Blazor WASM application that has got some good MBs of data to be transferred to the server during the initial load.

**Comment by halter73** [comment]
Also, do you see anything in `c:\windows\system32\logfiles\httperr`? Perhaps something referencing "MinBytesPerSecond"?

**Comment by javiercn** [comment]
> In connections with latency and with this amount of data transfer, could it be that the browser's WASM compiler is just giving up?

This is not a thing as far as I know.

Do you have any other software on the machine that can be interfering with the site? (Web Application Firewall, Enterprise Web Firewall, Corporate Proxy, and so on). In some cases, this software analyzes the contents of the files and while doing so holds back the response, causing eventual time outs until it has successfully processed all the new files.

**Comment by goodchaitanya** [comment]
@javiercn there is just a regular Windows defender firewall, but again nothing that shall analyze the output from IIS. Also, I observed that the issue almost does not happen if we access the application without a VPN(any VPN). Do you think we need to set any specific caching headers on IIS of the server to prevent this?

**Comment by mkArtakMSFT** [comment]
Sounds like the issue is in VPN then. Given that the issue doesn't reproduce without VPN involved, we don't think there is anything worth to investigate here for us. Hopefully you will be able to get to the bottom of this and resolve it.
