### ISSUE TITLE
Cache manifest.webmanifest in PWA

### ISSUE THREAD

**Issue by tomasz-soltysik** [dotnet/aspnetcore#54953]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After file extension change done in #43756, Web Manifest is no longer added to offline cache.
Prior to this change it had json extension which is included.

### Expected Behavior

Web Manifest should be added to offline cache by default service worker implementation.

### Steps To Reproduce

- Create new project from Blazor template, with PWA option selected.
- Run published app and let service worker install.
- Check if manifest.webmanifest is in offline cache

### Anything else?

Adding `/\.webmanifest$/` to `offlineAssetsInclude` in service-worker.published.js should fix this.

**Comment by shethaadit** [comment]
Hi @mkArtakMSFT, I will work on this and raise PR soon. :)
