### ISSUE TITLE
Microsoft.IdentityModel.Protocols.OpenIdConnect OpenIdConnectConfigurationSerializer Read() method does not parse UseInfoEndpoint correctly

### ISSUE THREAD

**Issue by martinb69** [dotnet/aspnetcore#54951]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The OpenIdConnectConfigurationSerializer class does not parse the UserInfoEndpoint correctly from the OpenIdConnect discovery endpoint. As a result the next field (in my case "jwks_uri") is not parsed.

The specific line of code tries to read "**UserInfoEndpoint**" but parses this as" "**scopes_supported**"

See Microsoft.IdentityModel.Protocols.OpenIdConnect / OpenIdConnectConfigurationSerializer.cs 
	
```
else if (reader.ValueTextEquals(OpenIdProviderMetadataUtf8Bytes.UserInfoEndpoint))
{
   config.UserInfoEndpoint = JsonSerializerPrimitives.ReadString(ref reader, "scopes_supported", 
   "Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration", read: true);
}
```

### Expected Behavior

Read UserInfoEndpoint as string and continue to parse.

```
else if (reader.ValueTextEquals(OpenIdProviderMetadataUtf8Bytes.UserInfoEndpoint))
{
   config.UserInfoEndpoint = JsonSerializerPrimitives.ReadString(ref reader, "userinfo_endpoint", 
   "Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration", read: true);
}
```

### Steps To Reproduce

Parse the following document from OpenIdConnect discovery endpoint where "jwks_uri" is not parsed resulting in missing singing keys:
{
  "issuer": "https://identity_tests_dll/auth",
  "authorization_endpoint": "https://identity_tests_dll/auth/connect/authorize",
  "token_endpoint": "https://identity_tests_dll/auth/connect/token",
  "end_session_endpoint": "https://identity_tests_dll/auth/connect/logout",
  "userinfo_endpoint": "https://identity_tests_dll/auth/connect/userinfo",
  "jwks_uri": "https://identity_tests_dll/auth/.well-known/jwks",
  "grant_types_supported": [
    "authorization_code",
    "refresh_token",
    "client_credentials",
    "password"
  ],
  "response_types_supported": [
    "code"
  ],
  "response_modes_supported": [
    "form_post",
    "fragment",
    "query"
  ],
  "scopes_supported": [
    "openid",
    "email",
    "profile",
    "roles",
    "api.provision",
    "api.session",
    "api.organization",
    "user",
    "offline_access"
  ],
  "claims_supported": [
    "aud",
    "exp",
    "iat",
    "iss",
    "sub"
  ],
  "id_token_signing_alg_values_supported": [
    "RS256"
  ],
  "code_challenge_methods_supported": [
    "plain",
    "S256"
  ],
  "subject_types_supported": [
    "public"
  ],
  "token_endpoint_auth_methods_supported": [
    "client_secret_post",
    "private_key_jwt",
    "client_secret_basic"
  ],
  "claims_parameter_supported": false,
  "request_parameter_supported": false,
  "request_uri_parameter_supported": false,
  "authorization_response_iss_parameter_supported": true
}

_No response_

### .NET Version

8.0.202

**Comment by BrennanConroy** [comment]
Wrong repo?
Looks like this should go in https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues

**Comment by martinb69** [comment]
> Wrong repo? Looks like this should go in https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues

Ok, I just noticed this in the debugger bu I have created a new issue in the suggested repository.

**Comment by martinb69** [comment]
Moved to suggested repository
