### ISSUE TITLE
Issue with 1Password Extension Causing High CPU Usage in Blazor WebAssembly Application with OIDC Authentication

### ISSUE THREAD

**Issue by jbppraxis** [dotnet/aspnetcore#54959]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Not sure if this belongs here, but here we go.

We have a client-side Blazor WebAssembly application using .NET 8. 
We have implemented OpenID Connect (OIDC) authentication with IdentityServer4. The authentication process, including the call to connect/checksession, activates as expected when the user logs in or reloads the application. The application functions correctly in this scenario.

However, we've encountered an issue when the 1Password browser extension is active in Chrome or Firefox: the application's CPU usage spikes to maximum. If we disable the 1Password extension and refresh the page, the CPU usage returns to normal levels.
Upon investigating, we observed multiple calls to connect/checksession without corresponding network requests being made.
 
It appears that the 1Password extension is inadvertently causing our Blazor application to repeatedly check the session state, which leads to high CPU usage. 
![blazor_cpu_usage](https://github.com/dotnet/aspnetcore/assets/47383719/a2828564-01d1-4736-8670-1991c4fa0f52)

### Expected Behavior

No change in cpu when extension is enabled

### Steps To Reproduce

This problem is consistently reproducible by following these steps: 
create a client-side Blazor WebAssembly application, 
implement OIDC, run the application, log in, enable the 1Password extension in Chrome or Firefox, and observe the CPU usage increase.

### .NET Version

8

### Anything else?

![image](https://github.com/dotnet/aspnetcore/assets/47383719/e032b0c1-3b8e-4fc1-8a3c-0cc0fef0ac3a)

**Comment by mjpraxis** [comment]
@MariovanZeist it also happens when there is no input fields on the page.

**Comment by jbppraxis** [comment]
> Hi @jbppraxis Could you create a small GitHub repro that shows this behavior? That would be the best way to investigate this issue.
> 
> Besides that. you could "disable" 1Password on a per `<Input>` basis. Adding the following attribute `data-1p-ignore` to your input fields effectively stops 1Password from modifying the DOM. See if that changes what you see.

Sure I can do that, but that would just be a template project with OIDC implemented

**Comment by MariovanZeist** [comment]
@jbppraxis and @mjpraxis I created the default blazor wasm app, and added OidcAuthentication.
I have the latest version of 1Password running in the browser. (Chrome)
The CPU doesn't spike if I am logged in or logged out while having 1Password running. (Tried the Home / Counter and Weather pages)
So I am unable to reproduce the issue for now.
If you could create a small repro that would show the problem, I could run it on my machine. If the problem then does not occur, we could at least conclude that the problem lies in different environments (additional browser plugins/firewall settings/av software)

**Comment by MariovanZeist** [comment]
@jbppraxis I have enabled it for all sites. including all the settings you have. (It's my goto password manager so I use it daily, for private and business use)

**Comment by jbppraxis** [comment]
This issue can be resolved. Following extensive testing and research, we determined that the problem originated from the version of IdentityServer4 in use. This likely explains why @MariovanZeist  did not encounter an error in his project. The version we had was outdated, and newer versions have an altered implementation of 'CheckSession' that manages communication with extensions more effectively.
![image](https://github.com/dotnet/aspnetcore/assets/47383719/062af144-8503-411e-bc63-5d4824a76970)
