### ISSUE TITLE
Random NullReferenceException on HttpContext.User Kestrel/Outofprocess

### ISSUE THREAD

**Issue by balajigunasekaran** [dotnet/aspnetcore#54962]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Following code is randomly throwing exceptions when executed in outofprocess when hosted using Kestrel.

It works fine when I uncommented try catch block of code. I have tested using Fiddler tool to repeat the requests.

Caching issue in [FeatureCollection](https://github.com/dotnet/aspnetcore/blob/0b00a2d41823b00d798a80deaa4fb37561326caa/src/Http/Http/src/DefaultHttpContext.cs#L124) implementation. 

```
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddHttpContextAccessor();

var app = builder.Build();
app.MapGet("/test", async context =>
{
    Task[] tasks =
    [
        DoWork(context),
        DoWork(context),
    ];
    await Task.WhenAll(tasks);
    
    static async Task DoWork(HttpContext context)
    {
        await Task.Run(async () =>
        {
            await Task.Delay(100);
            //try { context!.User.ToString(); } catch { }
            context!.User.ToString();
        });
    }
});
app.Run();

```

> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Http.DefaultHttpContext.get_User()
   at Program.<>c__DisplayClass0_0.<<<Main>$>b__2>d.MoveNext() in C:\Users\BalajiGunasekaran\source\repos\Playground\HttpContextIssueSample\Program.cs:line 21
--- End of stack trace from previous location ---
   at Program.<>c.<<<Main>$>b__0_0>d.MoveNext() in C:\Users\BalajiGunasekaran\source\repos\Playground\HttpContextIssueSample\Program.cs:line 13
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

![image](https://github.com/dotnet/aspnetcore/assets/5485374/f3dfbe46-c42c-4b9a-9c5c-2960308e94b5)

### Expected Behavior

It should not be throwing exceptions randomly.

### Steps To Reproduce

https://github.com/balajigunasekaran/HttpContextIssueSample

### Exceptions (if any)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Http.DefaultHttpContext.get_User()
   at Program.<>c__DisplayClass0_0.<<<Main>$>b__2>d.MoveNext() in C:\Users\BalajiGunasekaran\source\repos\Playground\HttpContextIssueSample\Program.cs:line 21
--- End of stack trace from previous location ---
   at Program.<>c.<<<Main>$>b__0_0>d.MoveNext() in C:\Users\BalajiGunasekaran\source\repos\Playground\HttpContextIssueSample\Program.cs:line 13
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

### .NET Version

8.0.202

**Comment by martincostello** [comment]
Your repro looks like it's accessing the HttpContext from a task running in the background after the current HTTP request has ended because nothing is awaited.

You'll need to completely capture the state of the data you need before you run your background work, otherwise the pooled HttpContext will no longer be valid as it's reset and returned to the pool for use in a future request.

**Comment by balajigunasekaran** [comment]
I think i awaited here. 
`await Task.WhenAll(tasks);`

I have updated the source repo now to await at the Tasks now and the sample code here. 
But am getting the exception even after that. Is there still a problem in the sample?

Here is the context, when executing more than one healthchecks which evaluates HttpContext.User then I got the same error.

[IHealthCheck](https://github.com/dotnet/aspnetcore/blob/0b00a2d41823b00d798a80deaa4fb37561326caa/src/HealthChecks/Abstractions/src/IHealthCheck.cs)

```
services.AddHealthChecks()
    .AddCheck<HealthCheck1>(HealthCheck1.Name)
    .AddCheck<HealthCheck2>(HealthCheck2.Name);
```

**Comment by balajigunasekaran** [comment]
Also when uncommenting the following line then it runs fine.

`//try { context!.User.ToString(); } catch { }`

**Comment by amcasey** [comment]
I created and ran a new webapi project with the code in the Description.  It doesn't seem to throw when I navigate to `/test`.  Am I missing a step?  Does this happen if you just launch the sample code as a standalone kestrel app or does it need to be out-of-proc in IIS?

**Comment by balajigunasekaran** [comment]
You can just start Debug in visual studio. And send repeated requests to test. I repeated the requests using fiddler. Randomly one or two will fail out of 1000.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by davidfowl** [comment]
Don't access the HttpContext concurrently, it's not supported. See https://github.com/dotnet/aspnetcore/issues/42040 for improving the error message.

**Comment by balajigunasekaran** [comment]
Actually we are facing this issue when executing Health checks. They are executed as shown above parallelly and it is failing randomly because those health checks are accessing HttpContrxt.User. What is the alternative for this scenario?

**Comment by davidfowl** [comment]
Copy the data required into the health check and don't use the current http context directly.

**Comment by balajigunasekaran** [comment]
For others who are wondering about this issue, there are guidelines when accessing httpcontext from background thread which we have to follow as mentioned in this link below.

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/http-context?view=aspnetcore-8.0#httpcontext-access-from-a-background-thread
