### ISSUE TITLE
Setting Microsoft-related logs messages to "Information" or lower in appsetting.json causing an ASP.NET web application to stop serving page. Kestrel Web Server

### ISSUE THREAD

**Issue by Smith334** [dotnet/aspnetcore#54964]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Recently we moved from hosting our .NET Core Web Apps from IIS to Kestrel, for various reasons. Shortly after, it was also decided to do away with the appsettings.json file and use other means to load the configuration. This brings it into line with our other Java applications. During this process, it was discovered that setting the "Microsoft" property/key in the appsetting.json file to the log level "Information" or lower would cause the web server to stop responding with the web page. No matter how the application gets the configuration properties the result is the same.

Originally we expected that was due to us stress testing it, but in fact, refreshing the index page in a browser about 5-20 times would also cause the issue. The amount of times varies.
In some cases when just starting it up and leaving it overnight, not making any HTTP requests to the web application, it would cause the application to stop responding the next day. **This issue might be related to what was posted on this issue: #45215** 

Before you ask, our Index action does not do any processing, it's just a simple home page with some hardcoded text.

From what we can tell the app does not look to have crashed, as this FrontEnd web app is still sending polls across to the separate BackEnd application. The port Kestrel is listening on is also open and can be telnet to, but attempting to load **any page** in a browser will cause it to endlessly load. When using a tool like JMeter and making HTTP requests it will cause JMeter to complain about the endpoint is not reachable. **When the issue happens, the web app will never recover and will need to be restarted, to go back to functioning.**

As I already mentioned we moved from relying on the appsettings.json file and instead are now passing the configuration in through a parent application when the web app starts. But regardless of whether we use an appsettings.json file or pass the configuration in, the issue persists. The only thing that looks to fix it is setting the "Microsoft" property/key to anything above the "Information" log level, i.e. "Warning", "Error", etc.

We would not set the log level of this property/key to "Information" in a production environment given that there is a lot of noise, but there may be a scenario where it is necessary in future.

I was able to reproduce the issue on both of our web applications, which are started in similar ways, but function differently.

Currently, we are using net8.0, but it looks to also be happening on net7.0.

### appsettings.json file example with issue:
```
{
  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Debug",
      "System": "Information",
      "Microsoft": "Information"
    }
  },
//add other properties as needed  
}
```

### appsettings.json file example with fix:
```
{
  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Debug",
      "System": "Information",
      "Microsoft": "Warning"
    }
  },
 //add other properties as needed 
}
```

### Expected Behavior

We expect to be able to set the "Microsoft" property/key to "Information" and lower log levels.

### Steps To Reproduce

1. In an ASP.NET Web Application configure the appsettings.json Microsoft logging property/key to "Information" or lower:

### i.e. This will cause the issue
```
{
  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Debug",
      "System": "Information",
      "Microsoft": "Information"
    }
  },
 //add other properties as needed
}
```

2. Once started, constantly refresh the index web page or use a tool like JMeter to send HTTP requests to the index page.
3. After a little while it will die.

### .NET Version

net8.0

### Anything else?

The web app is created as a self-contained application running on Windows OS 64bit

**Comment by amcasey** [comment]
I suppose it's not inconceivable that a particular log message (with level less than Warning) might be throwing in a place that causes a retry during which the same message is logged.  Obviously, it would be very helpful to know which message it was trying to log.

It sounds like you have a reliable repro.  If you can repro it locally, I'd try breaking into it in the debugger - it will probably have the attempted logging call on the stack, which would be a great help in figuring this out.

If it's actually a perf problem (vs, e.g., an infinite loop), then dotnet-counters should be able to tell you what it's doing (burning CPU? allocating memory?).

Please let us know what you find.
