### ISSUE TITLE
X509SecurityKey could support ECDSA backed Certificates for JsonWebToken signing

### ISSUE THREAD

**Issue by jaanclaeys** [dotnet/aspnetcore#54963]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

When signing a JsonWebToken with a certificate the x5t and kid is filled in. On validation side this can be cross-referenced then with a certificate and the validity of the certificate can then be checked.
This however only works with a certificate backed by an RSA key, not with an ECDSA key.

We can sign a JsonWebToken with ECDSA keys, but we cannot link this easily with a certificate, leaving out meaningful validation on that side.

X509SecurityKey could be modified to support these ECDSA keys as well.

### Describe the solution you'd like

I would like that X509SecurityKey looks at either getting GetRsaPrivateKey or GetEcdsaPrivateKey, instead of expecting an RSA key always.

**Comment by mitchdenny** [comment]
The `X509SecurityKey` class comes from `Microsoft.IdentityModel.Tokens`. Probably best to raise the issue in their repository for this:

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/
