### ISSUE TITLE
Support Token Credential Utilities for .http Files

### ISSUE THREAD

**Issue by wsugarman** [dotnet/aspnetcore#54977]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I would like to access Azure REST APIs, like those for Azure Blob Storage, but of course these APIs require authentication. I am logged into Visual Studio with my Microsoft account, and it would be ideal if I could automatically fetch JWT tokens for my account using a built-in function. Otherwise, I have to manually fetch bearer tokens via the Entra REST APIs or the `az cli` command. Additional solutions could be the inclusion of a "client secret" in a key vault, but it's preferrable to avoid secrets altogether if possible.

### Describe the solution you'd like

I would love the addition of some function for generating tokens using the `Azure.Identity` library with a syntax similar to the [VS Code Rest Client's](https://github.com/Huachao/vscode-restclient) syntax of `$aadToken` and `$aadV2Token`.

E.g. `{{$azCredential [azcli|azdevcli|azpwsh|browser|default|env|vs|vscode] [claims:<claims>] [scopes:<scopes>] [tenantid:<tenantId>]}}`

I tried to based these names and options off of the [`DefaultAzureCredential`](https://learn.microsoft.com/en-us/dotnet/api/azure.identity.defaultazurecredential?view=azure-dotnet) and the [`TokenRequestContext`](https://learn.microsoft.com/en-us/dotnet/api/azure.core.tokenrequestcontext?view=azure-dotnet) classes. The default value for the first argument for `$azCredential` would be `default` whose behavior would mirror `DefaultAzureCredential`.

**Example**
```
@account=contosoexample
GET https://{{account}}.blob.core.windows.net/?comp=list
Authorization: {{$azCredential}}
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not part of the runtime feature-set. Please use the [VS Feedback](https://docs.microsoft.com/en-us/visualstudio/ide/feedback-options?view=vs-2019) to report this issue, so the team who owns the area can track the ask.

@sayedihashimi  FYI
