### ISSUE TITLE
Blazor Server 8 Advanced Navigation Font Awesome icons oversized

### ISSUE THREAD

**Issue by dieterdp** [dotnet/aspnetcore#54990]
Hello,

I'm experiencing issues with Font Awesome and Blazor Server 8 when using advanced navigation. I created a new basic application and placed one icon from the FontAwesome package on the homepage. When I start the application, it looks fine:

<img width="634" alt="Screenshot 2024-04-06 at 08 37 38" src="https://github.com/dotnet/aspnetcore/assets/425205/a9b048f7-fba1-4905-bb3a-93813bdbca2b">

Then I choose "Counter," and when I go back to "Home," it looks like this:

<img width="1199" alt="Screenshot 2024-04-06 at 08 37 22" src="https://github.com/dotnet/aspnetcore/assets/425205/0f85c720-1dce-4349-9c6e-7fc38c4318ec">

I have to do a hard refresh, and then it looks good again. If you repeat this process, go back to "Counter" and back to "Home," the icon is oversized again. I have read this post https://github.com/dotnet/aspnetcore/issues/51696, but I can't get this to work. 

In my app.razor i have

<script src=https://kit.fontawesome.com/xxxx.js crossorigin="anonymous" ></script>

My home.razor looks like:
  <i class="fas fa-home"></i> 

Is there an working example available, or can someone help me to fix this?

Regards,
Dieter

**Comment by MackinnonBuck** [comment]
Thanks for reaching out. This looks like a question about how to use Blazor rather than a framework bug report. We recommend asking this question on StackOverflow to get help from the community on this.

**Comment by ryanbuening** [comment]
@dieterdp - did you ever find a solution to this? We are experiencing a similar issue with Font Awesome.

**Comment by dieterdp** [comment]
Hi,

I have a solution:

Set `disableDomPreservation` in your `app.razor`:

```html
<script src="/_framework/blazor.web.js" autostart="false"></script>
<script>
    Blazor.start({
        ssr: { disableDomPreservation: true }
    });
</script>
</body>
</html>

```
I also enabled enhance-nav in app.razor:

```html
<html lang="nl" data-enhance-nav="true">
```

I still think this is something that should be fixed in Blazor.

Regards,
Dieter
