### ISSUE TITLE
Directly referencing the staticwebassets of QuickGrid results in compilation error

### ISSUE THREAD

**Issue by mdmontesinos** [dotnet/aspnetcore#55009]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I've been trying to integrate QuickGrid component into [Oqtane](https://github.com/oqtane/oqtane.framework) but, because of the decoupled and modular nature of the project, it requires extracting and manually referencing the staticwebassets of external razor class libraries.

I've replicated the issue in a standard Blazor Web App with Server interactivity.

I've added to _content the assets required by QuickGrid and referenced them in my App.razor:

![image](https://github.com/dotnet/aspnetcore/assets/90258222/008f071a-60f2-46e9-ac22-c2ef6f551f81)

```razor
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <base href="/" />
    <link rel="stylesheet" href="bootstrap/bootstrap.min.css" />
    <link rel="stylesheet" href="app.css" />
    <link rel="stylesheet" href="QuickGridIssue.styles.css" />
    <link rel="icon" type="image/png" href="favicon.png" />
    <link rel="stylesheet" href="/_content/Microsoft.AspNetCore.Components.QuickGrid/Microsoft.AspNetCore.Components.QuickGrid.bundle.scp.css" type="text/css">
    <HeadOutlet @rendermode="InteractiveServer" />
</head>

<body>
    <Routes @rendermode="InteractiveServer" />
    <script src="_framework/blazor.web.js"></script>
    <script type="module" src="_content/Microsoft.AspNetCore.Components.QuickGrid/QuickGrid.razor.js"></script>
</body>

</html>

```

As the JavaScript file is scoped to the component (QuickGrid.razor.js) but the component is not found (even after installing the NuGet package and adding it to the Imports), trying to compile the project results in the following error:

```
"Error BLAZOR106 The JS module file 'MY_PATH\wwwroot\ _content\Microsoft.AspNetCore.Components.QuickGrid\QuickGrid.razor.js' was defined but no associated razor component or view was found for it."
```

And also a permanent error:

```
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	TS6053	File 'PATH/wwwroot/_content/Microsoft.AspNetCore.Components.QuickGrid/QuickGrid.razor.js' not found.
  The file is in the program because:
    Root file specified for compilation	Oqtane.Server JavaScript Content Files	PATH\MyModule\MyModule.sln	1	Active	
```

The discussion in the Oqtane repository is available at https://github.com/oqtane/oqtane.framework/discussions/4102.

The same compilation error was reported in the aspnetcore repo at https://github.com/dotnet/aspnetcore/issues/54644.

### Steps To Reproduce

Minimal repository provided at: https://github.com/mdmontesinos/QuickGridIssue

### .NET Version

8.0.202

### Anything else?

Visual Studio 2022 17.9.5

```
SDK DE .NET:
 Version:           8.0.202
 Commit:            25674bb2f4
 Workload version:  8.0.200-manifests.8cf8de6d

Entorno de tiempo de ejecución:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.202\

Cargas de trabajo de .NET instaladas:
 [maccatalyst]
   Origen de la instalación: VS 17.9.34723.18
   Versión del manifiesto:    17.2.8004/8.0.100
   Ruta de acceso del manifiesto:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maccatalyst\17.2.8004\WorkloadManifest.json
   Tipo de instalación:        FileBased

 [maui-windows]
   Origen de la instalación: VS 17.9.34723.18
   Versión del manifiesto:    8.0.7/8.0.100
   Ruta de acceso del manifiesto:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maui\8.0.7\WorkloadManifest.json
   Tipo de instalación:        FileBased

 [android]
   Origen de la instalación: VS 17.9.34723.18
   Versión del manifiesto:    34.0.52/8.0.100
   Ruta de acceso del manifiesto:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.android\34.0.52\WorkloadManifest.json
   Tipo de instalación:        FileBased

 [ios]
   Origen de la instalación: VS 17.9.34723.18
   Versión del manifiesto:    17.2.8004/8.0.100
   Ruta de acceso del manifiesto:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.ios\17.2.8004\WorkloadManifest.json
   Tipo de instalación:        FileBased


Host:
  Version:      8.0.3
  Architecture: x64
  Commit:       9f4b1f5d66

.NET SDKs installed:
  5.0.301 [C:\Program Files\dotnet\sdk]
  6.0.200 [C:\Program Files\dotnet\sdk]
  7.0.200 [C:\Program Files\dotnet\sdk]
  7.0.407 [C:\Program Files\dotnet\sdk]
  8.0.202 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.28 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
It's not clear what you're trying to achieve really. Are you trying to override the content of the scripts that are packages in the QuickGrid package?
If not, why are you trying to keep the Quickgrid.razor.js file as is? The error you're getting is intentional and to avoid it you will have to rename that file. So understanding the problem you're trying to solve may help us suggest you a better alternative.

**Comment by mdmontesinos** [comment]
[Oqtane](https://github.com/oqtane/oqtane.framework) is a CMS/modular application framework where developed modules are decoupled from the main application and are installed by including its assemblies. External dependencies can't be added in the same way and staticwebassets from NuGet packages can't be automatically registered. Here's some info on how to [integrate an external dependency](https://blazorhelpwebsite.com/ViewBlogPost/46) (Radzen) in Oqtane. 

Therefore, I need to extract the staticwebassets of the QuickGrid NuGet package (Quickgrid.razor.js and the styles) and manually include them in my _content file and reference them in the App.razor. However, here's where I get the reported error, as I can't include the scoped js file and compile the project.

Also, I can't rename the file to QuickGrid.js (without the razor part) as you suggested because QuickGrid component specifically references the file by its original name when initializing the JSInterop. Here's the [source code](https://github.com/dotnet/aspnetcore/blob/2a04de4e70e36a37b9042f2ae0d6e9b9aa0c0ed2/src/Components/QuickGrid/Microsoft.AspNetCore.Components.QuickGrid/src/QuickGrid.razor.cs) for it:

``` c#
    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender)
        {
            _jsModule = await JS.InvokeAsync<IJSObjectReference>("import", "./_content/Microsoft.AspNetCore.Components.QuickGrid/QuickGrid.razor.js");
            _jsEventDisposable = await _jsModule.InvokeAsync<IJSObjectReference>("init", _tableReference);
        }
```

**Comment by mkArtakMSFT** [comment]
@javiercn how would you recommend @mdmontesinos to achieve what they want?

**Comment by mdmontesinos** [comment]
Any updates on how to proceed with this issue?

**Comment by javiercn** [comment]
@mdmontesinos thanks for the additional details.

After taking a look in detail, I'd say this is not a supported scenario. You can't repackage the contents of an RCL in however way you see fit and expect the framework to "just work".

The issue seems to stem from the way Oqtane operates by bypassing the usage of static web assets all together. It might be ok for Oqtane not to integrate in that way, but then its on them the responsibility to adjust the build as necessary to make this work. I would go even further and say that this is unsupported territory from a product point of view and might break at any moment in the future.

> "Error BLAZOR106 The JS module file 'MY_PATH\wwwroot\ _content\Microsoft.AspNetCore.Components.QuickGrid\QuickGrid.razor.js' was defined but no associated razor component or view was found for it."

This error happens because we detect `*.razor.js` files in the project as JS modules. You can fiddle with MSBuild to avoid it or include the content in a different way.

As for:
```
            _jsModule = await JS.InvokeAsync<IJSObjectReference>("import", "./_content/Microsoft.AspNetCore.Components.QuickGrid/QuickGrid.razor.js");
```

Use an import map in your app.

So the way you can solve this (again **UNSUPPORTED**) is by renaming the file, and using an importmap to map `_content/Microsoft.AspNetCore.Components.QuickGrid/QuickGrid.razor.js` to your file path.

**Comment by mdmontesinos** [comment]
@javiercn Thanks for the pointers on how to "solve" this issue. I'll consider if it's worthy doing it this way and also report your information back to the Oqtane community.
