### ISSUE TITLE
[SignalR Typescript client library] WebSocket: Emit 'Upgrade-to-WebSocket' HTTP response event all the way to HubConnection

### ISSUE THREAD

**Issue by Jidong-Yang** [dotnet/aspnetcore#55005]
## Summary

When the SignalR Client library is used for a **websocket** connection, maybe it is worthy surfacing out the websocket-upgrade event to `HubConnection`.

## Motivation and goals

The event itself, together with the headers included in the HTTP 'upgrade' response sent back from the server side would provide more insights for the connection.

## In scope

- Only for WebSocket typed connection.
- Only for the 'upgrade' event.

## Examples

If the upgrade event could be passed all the way from `WebSocketTransport`, and finally reach `HubConnection`, then users would be able to observe the 'upgrade' http response like below:

```TypeScript
class WsClient
{
    ...
     public async CreateConnection()
    {
        this.connection = new HubConnectionBuilder()
            .withUrl(url, options)
            .withAutomaticReconnect()
            .build();

        // the implementation we wish to have:
        this.connection.onupgraded((event: Event)=>the handler for the upgrade response);
    }
    ...
}
```

**Comment by BrennanConroy** [comment]
Dupe of your own issue last week...
https://github.com/dotnet/aspnetcore/issues/54865
