### ISSUE TITLE
Issue when trying to handle batch request in minimal api.

### ISSUE THREAD

**Issue by Bellgrad** [dotnet/aspnetcore#55008]
## The issue
I'm trying to handle multiple requests in batch with the new minimal api as do OData, and the same way MsGraph is doing it (https://learn.microsoft.com/en-us/graph/json-batching).

## Constraints
In my current context, I can't use Odata.
So I'm searching for a way with the current documentation in .NET8 for minimal apis to handle batches (not bulk request with arrays).

## Attempts
I didn't find what I was looking for, so I'm guessing there is actually no feature regarding batching multiple requests natively.

## Questions
Is there a solution ?
Can it be usefull to the community to have such a feature ?

**Comment by captainsafia** [comment]
We don't support JSON Patch by default in minimal APIs. This is tracked over at (https://github.com/dotnet/aspnetcore/issues/35237). You may consider using another [open source library](https://github.com/Morcatko/Morcatko.AspNetCore.JsonMergePatch) for this.
