### ISSUE TITLE
Ensure nested event handlers work correctly

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#5500]
If element `A` contains element `B`, and they both declare (say) an `onclick` handler, and the user clicks on `B`, then you'd expect both event handlers to run.

Currently they do both try to run (first `B`, then `A`, as the event bubbles up), but with a render cycle between them. The render cycle might dispose the handler for `A` before we try to run it, which would lead to a crash.

We should avoid this issue by capturing the list of all event handler IDs to be invoked, pass them all to .NET atomically, and have it run all the corresponding delegates before any render cycle occurs.

**Comment by mkArtakMSFT** [comment]
@SteveSandersonMS is this still an issue?

**Comment by SteveSandersonMS** [comment]
As far as I know, yes.

**Comment by mkArtakMSFT** [comment]
We're closing this as most of this work has been done as part of other issues.
