### ISSUE TITLE
[Blazor] Provide API to determine assembly for a give route

### ISSUE THREAD

**Issue by daniel-p-tech** [dotnet/aspnetcore#55004]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Before user navigates to a new page, I need to be able to load some initialization data for a set of components in a particular assembly. In order to accomplish this task, I need to determine the assembly of the new page (component) from the route.

### Describe the solution you'd like

Provide official API that replicates the functionality of the ``Find`` method in this example.

https://stackoverflow.com/a/60165714

### Additional context

Please note that the StackOverflow solution no longer works after I migrated my Blazor app from .NET 6 to .NET 8. In the meantime, can you provide a temporary solution and outline how to change the following code so that it works in .NET 8?

```csharp
        private Assembly GetRoutedComponentAssembly(string path)
        {
            var assembly = typeof(Router).Assembly;
            var routes = typeof(Router).GetProperty("Routes", BindingFlags.Instance | BindingFlags.NonPublic).GetValue(m_router);
            var type = assembly.GetTypes().FirstOrDefault(t => t.Name == "RouteContext");
            var context = Activator.CreateInstance(type, new[] { path });
            routes.GetType().GetMethod("Route", BindingFlags.Instance | BindingFlags.Public).Invoke(routes, new[] { context });
            return (type.GetProperty("Handler").GetValue(context) as Type)?.Assembly;
        }
```

This is very important - I cannot upgrade to .NET 8 until I have some sort of a solution.

Thank you very much for your help!

**Comment by MackinnonBuck** [comment]
Thanks for reaching out. That approach uses private reflection, which is not recommended or supported. Does the [top upvoted answer](https://stackoverflow.com/a/60164096) in the StackOverflow post work for you?

**Comment by daniel-p-tech** [comment]
Hi, is there any update on this? Thanks!

**Comment by mkArtakMSFT** [comment]
@daniel-p-tech what prevents you from running that custom logic you want to in the `OnInitialized` method on the page you're navigating to? Just trying to better understand the problem you're facing.

To be fair, we absolutely do not recommend using reflection to get access to internal framework information, as that can change withuot any notice, and your apps will break then, without potential path forward.

**Comment by daniel-p-tech** [comment]
Here is the long discussion of what I'd like to ultimately achieve:

https://github.com/dotnet/aspnetcore/issues/39622

The next best thing is to load all my modules (components) at the app startup and then load the application data on the first navigation to the module (component).

This is would be an acceptable solution for the time-being, but unfortunately the implementation of ``GetRoutedComponentAssembly`` method (included in my first post) no longer works.

Thanks again!

**App.razor.cs**
```csharp
protected override void OnInitialized()
{
    m_componentLookupInitializers = new()
    {
        { typeof(Comp1).Assembly, Comp1LookupInitializer },
        { typeof(Comp2).Assembly, Comp2Initializer },
    };
}
```

**App.cs**
```csharp
protected Router m_router;
protected Dictionary<Assembly, LookupInitializer> m_componentLookupInitializers;
protected LookupInitializer m_activeLookupInitializer;

private bool m_isInitialized = false;

protected async Task OnNavigateAsync(NavigationContext args)
{
    // ignore navigation to login page which may be triggered by closing GlobalErrorMessage popup in mobile view
    if (args.Path != "" && args.Path != "Account/Login")
    {
        var assembly = GetRoutedComponentAssembly(args.Path);
        if (assembly != null)
        {
            m_componentLookupInitializers.TryGetValue(assembly, out var lookupInitializer);
            if (lookupInitializer?.IsInitialized == false)
            {
                m_activeLookupInitializer = lookupInitializer;
                await m_activeLookupInitializer.InitializeAsync();
                if (m_activeLookupInitializer?.IsInitialized == false)
                {
                    // this is a workaround until Microsoft provides official solution
                    NavigationManager.NavigateTo("/ComponentInitializerError", new NavigationOptions { ReplaceHistoryEntry = true });
                }
                m_activeLookupInitializer = null;
            }
        }
    }
}
```
```

**Comment by MariovanZeist** [comment]
Hi @daniel-p-tech 
If you want to initialize some data on the first time a page is routed to 

You could create the following component:
``preload.cs``
```cs
using Microsoft.AspNetCore.Components;
using RouteData = Microsoft.AspNetCore.Components.RouteData;

namespace MyBlazorApp;

public class PreLoad : IComponent
{
	private RenderHandle _renderHandle;
	[Parameter][EditorRequired] public RouteData RouteData { get; set; } = default!;
	[Parameter][EditorRequired] public RenderFragment ChildContent { get; set; } = default!;

	public void Attach(RenderHandle renderHandle)
		=> _renderHandle = renderHandle;

	public async Task SetParametersAsync(ParameterView parameters)
	{
		parameters.SetParameterProperties(this);
		ArgumentNullException.ThrowIfNull(ChildContent);
		ArgumentNullException.ThrowIfNull(RouteData);
		await OnPageLoad(RouteData);
		_renderHandle.Render(ChildContent);
	}

	protected virtual Task OnPageLoad(RouteData routeData)
	{
		var assembly = RouteData.PageType.Assembly;
		//Do some clever work to initialize the assembly if encountered first
		return Task.CompletedTask;
	}
}
```

And use it in your router component like:
```razor
<Router AppAssembly="typeof(Program).Assembly">
    <Found Context="routeData">
        <PreLoad RouteData=routeData>
            <RouteView RouteData="routeData" DefaultLayout="typeof(Layout.MainLayout)" />
        </PreLoad>
    </Found>
</Router>
```

**Comment by mkArtakMSFT** [comment]
Nice @MariovanZeist.
@daniel-p-tech does the above suggestion work for you?

**Comment by daniel-p-tech** [comment]
@MariovanZeist sorry for the late response. Your solution seems to be working fine, thank you! @mkArtakMSFT do you see any potential issues - this goes deep into the heart of how Blazor works. Thanks again!

**Comment by mkArtakMSFT** [comment]
@daniel-p-tech glad that the suggestion from @MariovanZeist worked for you. That's actually very much aligned with what we would recommend you do here. So, there isn't a better alternative to recommend. As for creating a feature for this particular scenario, that's not something we plan to do.
