### ISSUE TITLE
Streamrendering in Blazor SSR doesn't work behind reverse proxy

### ISSUE THREAD

**Issue by urza** [dotnet/aspnetcore#55029]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

`StreamRendering ` in Blazor SSR mode doesn't work behind reverse proxy such as [Nginx Proxy Manager](https://nginxproxymanager.com/)

### Steps To Reproduce

1. Create new Blazor web in latest stable Visual Studio. Choose `"no interactivity"` and `no https` in creation dialog.
2. In Weather.razor page, line 45 increase the time delay to 7000 ms so it is more noticeable what is going on:  `await Task.Delay(7000);`
3. Compile this website to executable and run it locally from terminal with something like: `.\BlazorSSRReverseProxy.exe --urls=http://*:6599`
4. Go to your browser and navigate to Weather page - **observe that here it behaves correctly** as expected with stream rendering - the layout of the page is shown instantaneously and after 7 seconds, the weather forecast is displayed 
5. Now go to Nginx Proxy Manager that listens to incoming traffic from internet to your local network and create something reverse proxy something like weather.yourdomain.example => http://localIP:6599 
6. Go to the external URL you just created in Nginx Proxy Manager => navigate to weather page and observe that stream rendering doesn't work - whole page is loading 7 seconds without showing anything and then displays everything at once

### .NET Version

8.0.202

### Anything else?

Using Nginx Proxy Manager latest release: v2.11.1
I tried different settings such as allowing websockets, or toggling support for HTTP2, but nothing worked.

**Comment by mkArtakMSFT** [comment]
Hi.

It looks like by default, nginx is buffering responses from proxied servers. Here is a quote from the documentation:
> By default NGINX buffers responses from proxied servers. A response is stored in the internal buffers and is not sent to the client until the whole response is received.

Source: https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/

Streaming rendering requires buffering to be disabled. The documentation also shows how to disable buffering. Hope this helps.

**Comment by urza** [comment]
Hi, thanks! I disabled buffering and stream rendering started working.

For people in the future, this is how you do it in Proxy Manager UI:

![image](https://github.com/dotnet/aspnetcore/assets/189804/07483817-3032-4d5f-a04a-d7e8c7a8ac89)
