### ISSUE TITLE
Notify Unhandled Circuit Exception

### ISSUE THREAD

**Issue by EmreSURK** [dotnet/aspnetcore#55027]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am trying to catch all unhandled exceptions globally in one place. It is not possible for circuit exceptions. 

### Describe the solution you'd like

In CircuitManager.ts we have unhandledException function. It logs the exception to the browser console and closes the connection. 
Right before closing the connection, it can send the exception to the backend.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
While this may be a great idea, it is not aligned with our long-term vision to make it part of the framework. For many other ideas which don't belong to the framework we encourage the community to build and ship on their own, contributing to the expanding .NET Ecosystem.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.

**Comment by EmreSURK** [comment]
Thank you for considering it. 
I created a custom ErrorBoundary object, is this the correct way to handle unhandled circuit errors? 
If so, I may write an example tutorial and people can implement it for themselves.

Unhandled circuit exceptions may be a deal breaker for decision-makers and I wish to help people to get rid of it.

Thanks.
