### ISSUE TITLE
 Authentication for static files || OpenIDConnect || BlazoreServer App || Dotnetcore 8 

### ISSUE THREAD

**Issue by jyotikMSFT** [dotnet/aspnetcore#55057]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Issue Description: 
+ we have created a dotnet core 8 blazor server application. 
+We implemented Open ID authentication in the application.
+ The requirement is to not allow people to browse the static content available if they are not authenticated. 
 
+ we have a concern that we are able to protect the static content that we have added to the site example site.css and site.js but we are not able to protect the static content which is being delivered in below paths: 
 
/_content/
/_framework/
/_domainaddress/ 
 
When we browse: https://localhost:7053/_content/MudBlazor/MudBlazor.min.js and https://localhost:7053/_framework/aspnetcore-browser-refresh.js they are able to see content without being authenticated: 
 
![ss jpg](https://github.com/dotnet/aspnetcore/assets/153515593/5757e29a-e13a-4fc2-b1f4-26a62f495deb)
  
We tried reordering the middleware and applied the below code. This is working for the static files that are part of wwwroot. However some dynamically created static files (/_content/, /_framework/, /_domainaddress/ )  are still accessible without authentication. 
![codesnip](https://github.com/dotnet/aspnetcore/assets/153515593/6112902c-ad83-4ea3-92b5-fe3de8a6d6b3)
 
 
+ We tried by building the application in release mode and deploying it, still after deploying it I am able to browse these routes

### Expected Behavior

We should not be able to browse these static routes if we are not authenticated. 

### Steps To Reproduce

https://github.com/jyotikMSFT/-Authentication-for-static-files-OpenIDConnect-BlazoreServer-App-Dotnetcore-8-

### .NET Version

.NET 8.0

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Did you try to swap lines 96 & 97 so that the `UseAuthorization()` is called before `UseStaticFiles()`? Your repro doesn't show this.

Also, here are the docs to help you with this: https://learn.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-8.0#static-file-authorization

Please note, that if authorization middleware (with fallback policy configured) is setup before the StaticFilesMIddleware, then the request should be authorized to get access to **any** static file. So there has to be some misconfiguration in your app.

**Comment by jyotikMSFT** [comment]
> Thanks for contacting us. Did you try to swap lines 96 & 97 so that the `UseAuthorization()` is called before `UseStaticFiles()`? Your repro doesn't show this.
> 
> Also, here are the docs to help you with this: https://learn.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-8.0#static-file-authorization
> 
> Please note, that if authorization middleware (with fallback policy configured) is setup before the StaticFilesMIddleware, then the request should be authorized to get access to **any** static file. So there has to be some misconfiguration in your app.

Hi @mkArtakMSFT ,  Thankyou for your reply, 

Yes i tried swapping line no. 96 and 97 but this does not help at all. i also consulted this article https://learn.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-8.0#static-file-authorization before opening this as an issue.  

I tried adding the fall back policy again and i am having same issue. I added the fallback policy as shown in the article you shared. I am still able to browse URL's like https://localhost:7245/_framework/aspnetcore-browser-refresh.js without being authenticated.  The static files that i have added to the application is showing expected behavior when i try to reach out to the URL for my static files (localhost:7245/css/site.css) i am routed back to login page as expected. but going over the routes like /_framework/, /_content/ , /_domainaddress/ still displays me the file content without authentication.

**Comment by jyotikMSFT** [comment]
Hello!

I am having 4 routes for the static files in my application. The files that i use in my application as content for my users are outside wwroot and under StaticFiles. 

https://localhost:44318/bootstrap/bootstrap.min.css
https://localhost:44318/_framework/aspnetcore-browser-refresh.js
https://localhost:44318/_content/aspnetcore-browser-refresh.js
https://localhost:44318/StaticFiles/test.css

I tried the sugested changes
![image](https://github.com/dotnet/aspnetcore/assets/153515593/2bb3da46-c01c-4785-8dc5-d5a64b3b9822)

After that and making below change for StaticFiles:
app.UseStaticFiles(new StaticFileOptions
{
    FileProvider = new PhysicalFileProvider(
           Path.Combine(builder.Environment.ContentRootPath, "MyStaticFiles")),
    RequestPath = "/StaticFiles"
});

I can see that for below URL's when i try to browse, i get the expected login page since i am not authenticated. 
https://localhost:44318/_content/aspnetcore-browser-refresh.js
https://localhost:44318/StaticFiles/test.css


Still I am able to browse below URL's without being authenticated: 
https://localhost:44318/bootstrap/bootstrap.min.css
https://localhost:44318/_framework/aspnetcore-browser-refresh.js

**Comment by mkArtakMSFT** [comment]
The `aspnetcore-browser-refresh.js` file is a special case, as it's being injected into the app through a middleware that's injected during app startup and registered very early in the pipeline. That results in other middlewares (like Auth) to have no effect on this. In other words, this is by-design, as this is a development-only feature.

As for the bootstrap.css, it looks like you have the .UseStaticFiles middleware registration call happen before UseAuthorization. Please move it to after (as you've shown in the screenshot above) and that should take care of it.
