### ISSUE TITLE
Updating Microsoft.AspNetCore.Components.WebAssembly.DevServer to 8.0.4 causing issues

### ISSUE THREAD

**Issue by Victorolu** [dotnet/aspnetcore#55075]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have just upgraded some of my team's Blazor project's packages from 8.0.3 to 8.0.4 and it gave this error:
![image](https://github.com/dotnet/aspnetcore/assets/42678223/cde3da6b-9aac-41c7-b6da-77757553939d)

I was able to streamline which package was giving that issue on my PC and found out it was Microsoft.AspNetCore.Components.WebAssembly.DevServer. The 8.0.3 version works with the other upgraded packages but the 8.0.4 version does not.

I recreated the issue with a new Blazor Wasm App and the issue still occured.

### Expected Behavior

I should not be getting any error while starting off my Blazor project

### Steps To Reproduce

Create a Blazor Project with the updated packages especially Microsoft.AspNetCore.Components.WebAssembly.DevServer with 8.0.4 and try to run the project.

Should give the Visual Studio Error Message

### .NET Version

dotnet 8

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Can you please confirm that you've updated all your packages (and SDK) to 8.0.4? Mixing and matching those dependencies may cause unexpected behaviors.

**Comment by Victorolu** [comment]
Hi @mkArtakMSFT, I have updated all packages now and installed the SDK. That has fixed the issue.

Thanks.
