### ISSUE TITLE
Chrome 123.0.6312.123 throws errors when accessing InteractiveServer applications

### ISSUE THREAD

**Issue by csharpfritz** [dotnet/aspnetcore#55085]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The current version of Google Chrome throws errors when navigating to Blazor InteractiveServer applications with TLS enabled.

### Expected Behavior

Application opens and interacts with normally

### Steps To Reproduce

Create a new Blazor application with .NET 8 using the following configuration:

```
dotnet new blazor -int Server -ai -o TestServer
```

Run the application with the https profile:

```
dotnet run -lp https
```

Navigate to the base of the website in Chrome

### Exceptions (if any)

Errors in browser console:
```
blazor.web.js:1 [2024-04-11T15:27:46.552Z] Error: There was an error applying batch 2.
blazor.web.js:1 [2024-04-11T15:27:46.579Z] Error: There was an error applying batch 3.
blazor.web.js:1 [2024-04-11T15:27:46.643Z] Error: There was an unhandled exception on the current circuit, so this circuit will be terminated. For more details turn on detailed exceptions by setting 'DetailedErrors: true' in 'appSettings.Development.json' or set 'CircuitOptions.DetailedErrors'. 
```

Errors in server console:
```
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: TypeError: Cannot read properties of null (reading 'insertBefore')
      System.InvalidOperationException: TypeError: Cannot read properties of null (reading 'insertBefore')
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.InvokeRenderCompletedCallsAfterUpdateDisplayTask(Task updateDisplayTask, Int32[] updatedComponents)
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'BbKmOqCdix7OlK4ca5qWHln0IbV2RO8zv_GYI8R2IyI'.
      System.AggregateException: One or more errors occurred. (TypeError: Cannot read properties of null (reading 'insertBefore'))
       ---> System.InvalidOperationException: TypeError: Cannot read properties of null (reading 'insertBefore')
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.InvokeRenderCompletedCallsAfterUpdateDisplayTask(Task updateDisplayTask, Int32[] updatedComponents)
         --- End of inner exception stack trace ---
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: Error: No element is currently associated with component 1
      System.InvalidOperationException: Error: No element is currently associated with component 1
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.InvokeRenderCompletedCallsAfterUpdateDisplayTask(Task updateDisplayTask, Int32[] updatedComponents)
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'BbKmOqCdix7OlK4ca5qWHln0IbV2RO8zv_GYI8R2IyI'.
      System.AggregateException: One or more errors occurred. (Error: No element is currently associated with component 1)
       ---> System.InvalidOperationException: Error: No element is currently associated with component 1
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.InvokeRenderCompletedCallsAfterUpdateDisplayTask(Task updateDisplayTask, Int32[] updatedComponents)
         --- End of inner exception stack trace ---
```

### .NET Version

8.0.200

**Comment by rwjdk** [comment]
@csharpfritz Do you have the LastPass Chrome Extension installed? I have the exact same issue/error and if the LastPass extension is disabled, the issue goes away.

**Comment by csharpfritz** [comment]
I do... and yes, when disabled the behavior stops


Jeff

**Comment by rwjdk** [comment]
Thanks for confirming... They released a new version of the extension late last night so I think LastPass is at fault here... In Edge Extension store the new version is not yet out, but expect things might break across browsers 🙁 I also heard for a colleague that it also did odd things to a VueJS site, so hopefully they become aware of the issue (I've written on their forum but no answer yet)

**Comment by beany** [comment]
I can confirm that disabling the LastPass Extension (versin 4.129.0) for Chrome causes this problem (or, at least, disabling it will Blazor run normally). Using Firefox with LastPass 4.127 runs Blazor apps normally.

Thanks @csharpfritz for making an issue so I could find the solution @rwjdk provided. Saved me a lot of time/headache!

**Comment by augustevn** [comment]
We came to the same conclusion it's since LastPass' release on March 10...
Disabling the Chrome extension does the trick.

I first thought it was the `blazor.web.js` then it hit me that I did Windows updates etc.

Related issue: https://github.com/dotnet/aspnetcore/issues/55063

**Comment by beany** [comment]
LastPass issue: https://support.lastpass.com/s/question/0D5TP00000AZcL80AL/does-anyone-else-have-issue-with-latest-version-of-lastpass-in-chrome-41290-in-that-certain-websites-either-act-odd-or-cant-even-load-blank-white-screen-if-the-lastpass-extension-is-disabled-the-sites-load-fine-again-

**Comment by tossnet** [comment]
I have the same problem on Edge and a Blazor Server app.

**Comment by rwjdk** [comment]
LastPass 4.130.0 is out that resolves the error

**Comment by codepend** [comment]
For what it's worth, this same thing happens with RoboForm Firefox extension version 9.5.9.2 (current at this time). Does not seem to happen with Chrome/Edge.
