### ISSUE TITLE
Questions about Blazor component disposal

### ISSUE THREAD

**Issue by kjkrum** [dotnet/aspnetcore#55082]
This is a continuation of prematurely closed #54876.

Is it possible for Dispose to be called _between_ OnInit, OnInitAsync, OnParametersSet, and OnParametersSetAsync, or only _after_ those methods are called? If it can be called between them, then (for example) OnParametersSet would always have to check whether the component is disposed.

cc: @guardrex 
cc: @javiercn

**Comment by mkArtakMSFT** [comment]
Thanks for raising this.
This depends very much on your application code.
If you do expect that the component can be disposed during initialization, then you should expect that it may be disposed during OnParametersSet.

**Comment by kjkrum** [comment]
@mkArtakMSFT It was already established in the first prematurely-closed question that it cannot be disposed _during_ OnParametersSet, as Dispose and OnParametersSet are called on the same thread. I only expect that the component can be disposed during initialization because the docs say it can but say nothing else. By saying that it depends on my application code, are you asserting that it does not happen because of user interaction or navigation?
