### ISSUE TITLE
Add AuthorizationOptions.PreferAllowAnonymous option

### ISSUE THREAD

**Issue by halter73** [dotnet/aspnetcore#55093]
## Background and Motivation

To address the concerns in https://github.com/dotnet/aspnetcore/issues/43550#issuecomment-1940287150 where a more local `[Authorize]` attribute on a specific action, route handler, razor page or blazor component gets overwritten by an `[AllowAnonymous]` attribute further away on a controller or base type, we are going to start ignoring `IAllowAnonymous` metadata that is less local than `IAuthorizeData` metadata. However, it's possible that people actually want the current behavior of `[AllowAnonymous]` where it always wins.

One example of not wanting the new behavior would be someone relying on the workaround of calling `app.MapRazorComponents<App>().AllowAnonymous()` to tell the authorization middleware to let the request through even if a Blazor page has a more local `[AuthorizeAttribute]` because it will be handled later by the `AuthorizeRouteView` as described in https://github.com/dotnet/aspnetcore/issues/53732#issuecomment-2021878231.

There may be other scenarios too, since `IAllowAnonymous` metadata overriding more local `IAuthorizeData` metadata has been the behavior since ASP.NET Core 1.0. This was also [the behavior for System.Web's AllowAnonymousAttribute](https://github.com/aspnet/AspNetWebStack/blob/d3c4055b361d3644df467c52b43b80576652180c/src/System.Web.Http/AuthorizeAttribute.cs#L163-L164), so there could be a lot of legacy code relying on this behavior.

## Proposed API

```diff
namespace Microsoft.AspNetCore.Authorization;

public class AuthorizationOptions
{
{
+    public bool PreferAllowAnonymous { get; set; }
}
```

## Usage Examples

```csharp
builder.Services.AddAuthorization(options =>
{
    options.PreferAllowAnonymous = true;
});
```

## Alternative Designs

We could try using an [AppContext switch](https://learn.microsoft.com/en-us/dotnet/api/system.appcontext.setswitch?view=net-8.0) rather than add new public API if we think that this will only be necessary as a temporary stop gap.

We could also consider adding a similar option to `MvcOptions` since it checks for `IAllowAnonymous` metadata independently of the `AuthorizationMiddleware` or `AuthorizationService`. Having logic in MVC's `AuthorizeFilter` depend on `AuthorizationOptions` might be unexpected.

## Risks

People might not understand what `PreferAllowAnonymous` means without reading doc comments. I'm not sure what name would be better though. It's also possible that this option is unnecessary, and it adds noise to `AuthorizationOptions`.

**Comment by amcasey** [comment]
[API Review]

- Could this be an analyzer?
    - Not completely because AllowAnonymous can be set dynamically
- The current behavior is surprising but is probably working by accident for many apps
- This is an important part of helping our customers be secure by default - that justifies breaking people at runtime
    - An analyzer might make the failure more visible
- If we had just an appcontext switch, what would we put in the log as a suggested mitigation?
    - Maybe we should have both an option and an appcontext
    - Would we be stuck with the option forever?
- Long-term, better guidance would be an indication of which action is affected and how to fix _that_ action
- We could warn on startup
    - We're not doing that endpoint enumeration now, but we could
- What do we call the appcontext switch?
    - Microsoft.AspNetCore.Authorization.PreferAllowAnonymous 

API Approved!

```csharp
namespace Microsoft.AspNetCore.Authorization;

public class AuthorizationOptions
{
+    public bool PreferAllowAnonymous { get; set; }
}
```

**Comment by mkArtakMSFT** [comment]
Closing for now as we've decided not to move forward in this direction.
