### ISSUE TITLE
Issue with Options having an array property that is added twice

### ISSUE THREAD

**Issue by benoit-maurice** [dotnet/aspnetcore#55096]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Given an aspnet core 8.0 api
And the following option class : 

```csharp 
public class ConfigOptions
{
    public const string SectionName = "Config";
    
    public string[] List { get; init; }
}
```

and the folowing appsettings.json : 

```json
{
  // ... some irrelevant config
  "Config": {
    "List": ["1", "2", "3"]
  }
  // ... some irrelevant config
}
```

and I register the option twice : 

```csharp
builder.Services.AddOptions<ConfigOptions>().Bind(builder.Configuration.GetSection(ConfigOptions.SectionName));
builder.Services.AddOptions<ConfigOptions>().Bind(builder.Configuration.GetSection(ConfigOptions.SectionName));
```

When I inject `IOptions<ConfigOptions>` in a service

Then the List property will contain "1","2","3" twice, that is : `["1","2","3","1","2","3"]` 

    Note: If I register the option a third time then the options List will contains "1","2","3" three times

### Expected Behavior

This behaviour does not seem to be intuitive and I couldn't find any documentation explaining this.
I would have expected to List property to be overwritten instead of being concatenated. 

Following the above example, I would have expected the List property only to contain  `["1","2","3"]` 

### Steps To Reproduce

https://github.com/benoit-maurice/Bug-OptionsTable

### .NET Version

8.0.104

**Comment by martincostello** [comment]
This issue should be transferred to the [dotnet/runtime](https://github.com/dotnet/runtime) repo where the configuration binding libraries live.

**Comment by benoit-maurice** [comment]
Okay, thanks for your reply. 
I'm closing this one and create a new one on dotnet/runtime.

Here is the new issue : https://github.com/dotnet/runtime/issues/100948
