### ISSUE TITLE
You broke Blazor with RenderMode

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#55104]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/You-broke-Blazor-with-RenderMode/10632424)._

---
Something as simple as a button click used to work. I have read dozens of artidcles about RenderMode, and now none of them work. My only choice is to go back to .,NET7?

I can't believe you would create anything that would break onclick. Who wants static content? I want a button click to work. My client gave me a go ahead to create a modern version of our app, and I am stuck on button clicks don't work, so I don't get upgrade our app.

Please fire whoever thinks RenderMode was a good idea. 

---
#### Feedback Bot on 4/6/2024, 08:23 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by javiercn** [comment]
Closing as there isn't any concrete action we can take.
