### ISSUE TITLE
Cannot bind custom class or record for HTTP request header with Minimal APIs

### ISSUE THREAD

**Issue by jos3s** [dotnet/aspnetcore#55117]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The use of the FromHeader attribute in a minimum API parameter with a custom HeadersDto class or record produces an error in compilation and analysis

### Expected Behavior

The expected behavior would be for the HeadersDto properties to be linked automatically as they are in Controllers

### Steps To Reproduce

build this code:

```csharp
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Primitives;

var builder = WebApplication.CreateBuilder(args);
var app = builder.Build();

app.UseHttpsRedirection();

app.MapGet("/", ([FromHeader] HeadersDto headers) => headers);

app.Run();

record HeadersDto()
{
    public string Token {get; set;} = string.Empty;
}
```

### Exceptions (if any)

Program.cs(22,18): error ASP0020: Parameter 'headers' of type HeadersDto should define a bool TryParse(string, IFormatProvider, out HeadersDto) method, or implement IParsable<HeadersDto> (https://aka.ms/aspnet/analyzers)

### .NET Version

8.0.204

**Comment by davidfowl** [comment]
What object are you binding from headers?

**Comment by jos3s** [comment]
> What object are you binding from headers?

> ```csharp
> record HeadersDto()
> {
>     public string Token {get; set;} = string.Empty;
> }
> ```

I'm using the HeadersDto record, if I use it in a Controller the values are matched, but in a minimal api they aren't

**Comment by jos3s** [comment]
@captainsafia 

Oops, that wasn't the problem I raised. Yes, implementing the method manually solves this problem, but the question is: Why is this code mapped correctly to the controller and not to the minimal API?

**Comment by jos3s** [comment]
@captainsafia 

Oops, that wasn't the problem I raised. Yes, implementing the method manually solves this problem, but the question is: Why is this code mapped correctly to the controller and not to the minimal API?

**Comment by captainsafia** [comment]
> but the question is: Why is this code mapped correctly to the controller and not to the minimal API?

@jos3s Minimal APIs and MVC have different model binding layers so you'll see different behavior between the two in certain scenarios.
