### ISSUE TITLE
addCascadingValue consumed from a library extension method acts as a singleton in Blazor Web App 

### ISSUE THREAD

**Issue by EldinHb** [dotnet/aspnetcore#55125]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Consuming a `.addCascadingValue()` from an extension of a razor class library results in the cascaded value acting as a singleton. When the cascaded value gets changed in a session it stays changed until a rebuild occurs. Like a singleton would behave.

If `.addCascadingValue()` is called in the consumers `program.cs` the cascaded value acts like a scoped value. Every session has a clean cascaded value. 

I am not sure if this is intentional, but the behaviour is very odd which makes me believe it is not intentional. 

### Expected Behavior

For the cascaded value to behave like a scoped value.

### Steps To Reproduce

https://github.com/EldinHb/CascadingValueBug

In `BlazorApp1` in `program.cs` [line 10](https://github.com/EldinHb/CascadingValueBug/blob/cf1c299da20234c59779f3f71ee004cf1a4ffa27/BlazorApp1/Program.cs#L10) will act as a singleton. It calls [this](https://github.com/EldinHb/CascadingValueBug/blob/main/ClassLibrary1/Extensions.cs) extension method.

`Class1` holds the string value. 

In [home.razor](https://github.com/EldinHb/CascadingValueBug/blob/main/BlazorApp1/Components/Pages/Home.razor) you can change the value with the button. 

Run the project and click on the button. Refresh the page, open it in a new browser/incognito and the value will stay changed.

Comment line 10 in `program.cs` and uncomment line 11. Make sure to rerun the project. Click button then refresh, the value will reset back to its original state. 

### .NET Version

8.0.100

**Comment by MariovanZeist** [comment]
Hi @EldinHb 
Your issue has nothing to do with either ``CascadingValues`` or Blazor. It's because of a C# feature called _"closures"_

In line 10 you are calling your extension method with an instance of ``Class1``,
```cs
builder.Services.AddClassLibServices(new Class1());
```
Your extension method looks like this:

```cs
//cls1 at this time will contain an instance of Class1
public static IServiceCollection AddClassLibServices(this IServiceCollection collection, Class1? cls1 = null)
{
    collection.AddCascadingValue(p => cls1 ?? new Class1());
    //This code will "capture" the cls1 variable.
    //as cls1 is not null , instead of creating a new Class1 instance every time the delegate is called  it will return the passed-in cls1 value
    //Effectively making it a Singleton.
    return collection;
}
``` 

Then in line 11, you are passing the following delegate
```cs
builder.Services.AddCascadingValue(_ => new Class1());
//In this case you are passing a function that will return a new Class1 every time the function is called
//(this happens when you refresh)
```

That's why you see different behaviors.

**Comment by EldinHb** [comment]
Ah, I completely missed that. Thanks for the thorough explanation!
