### ISSUE TITLE
Make Blazor component libraries work with autobuild

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#5512]

**Comment by rynowak** [comment]
@danroth27 - what is autobuild? Do we need this issue?

**Comment by danroth27** [comment]
@rynowak Autobuild is when something automatically rebuilds and restarts your when you've changed a file. VS does this for you, and on the command-line we have `dotnet watch`. As far as I know, we don't have any autobuild support for referenced projects today. That said, I don't think this issue isn't specific to Blazor, so it's not really tracking anything that we can directly act upon other than to follow up with the relevant partner teams.

**Comment by rynowak** [comment]
So is this really then about rebuild working on project-to-project references the same way it does the app project?

**Comment by danroth27** [comment]
Yeah. So if you have an app that references a component library project you can update a component in the library project and have the app auto rebuild for you.

**Comment by javiercn** [comment]
Whatever we decide here we should include https://github.com/aspnet/AspNetCore/issues/17535 as part of that

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.

**Comment by mkArtakMSFT** [comment]
Looks like this has been resolved already. Thanks @danroth27 for letting me know.
