### ISSUE TITLE
how intercept the enhanced navigation calls and show & hide a loader for enhanced navigation

### ISSUE THREAD

**Issue by MahdiElahi** [dotnet/aspnetcore#55128]
Hi , i use this tutorial [Tutorial](https://www.youtube.com/watch?v=JMcCtC-ZFV4) for intercept the enhanced navigation calls and show & hide a loader for anhanced navigation

but just worked for first time it's means in first navigation just show loader topbar 
in next time dont show at all 
[My Project - Git](https://github.com/MahdiElahi/EnhancedNavigation2)
what's problem ?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is a dupe of https://github.com/dotnet/aspnetcore/issues/53887
