### ISSUE TITLE
Blazor WebApp template is not working as described

### ISSUE THREAD

**Issue by malovicg** [dotnet/aspnetcore#55133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have created solution from Blazor WebApp template, Authentication: Individual Accounts, Interactive render mode: WebAssembly, Location: Global, No sample pages. Resulting output is this:

![image](https://github.com/dotnet/aspnetcore/assets/64432887/ecd12a4d-6df5-44a8-b028-713434669fe3)

Looking at the project structure,  wwwroot is located at server project, and has app.css in it. According to this [bug report](https://github.com/dotnet/aspnetcore/issues/52476), user created solution with similar options, and was complaining that wwwroot folder contained appsettings.json file, which in his case was located at the Client project. Bug was rejected due to expected behavior.

In my case, wwwroot is located at server project, and there is no appsettings.json in it. So, I decided to create one, since I wanted to have it available in browser. I just copied existing appsettings.json (which is located in the same project's root dir), to be sure there is no typing error. I wanted to have two appsettings.json files, for both server and client. Adding appsettings.json to wwwroot achieves nothing, this file is not loaded in browser, as it can be seen in Network tab in Developer tools. I can only see app.css file loaded in browser.

Now, if I just move wwwroot folder to Client project, along with app.css and appsettings.json files, then both files are served in browser.

### Expected Behavior

I would expect wwwroot to be located at Client project, or at least that if I put appsettings.json file in it, it would be served in browser. Moving wwwroot folder to Clijent project is providing expected behavior.

### Steps To Reproduce

Create solution from Blazor WebApp template:

- Authentication: Individual Accounts
- Interactive render mode: WebAssembly
- Location: Global
- No sample pages

Add appsettings.json file to wwwroot folder (which is located in server project).
Run the app and observe that appsettings.json file is not served in browser.

### .NET Version

8.0.200

### Anything else?

VS 17.9.2
VS Preview 17.10.0 Preview 2.0

**Comment by javiercn** [comment]
@malovicg thanks for contacting us.

This is by design. The appSettings file needs to be on the webassembly project or else the project won't know about its existence at compile time and won't download it when the runtime starts. Placing it on the se server wwwroot is not valid because the webassembly project doesn't have access to it at compile time.
