### ISSUE TITLE
Fix for: There was no runtime pack for Microsoft.AspNetCore.App available for the specified RuntimeIdentifier 'browser-wasm'.

### ISSUE THREAD

**Issue by LunicLynx** [dotnet/aspnetcore#55132]
Hello, as previous issues on this topic #45078, #45031 have been closed without a solution.

## The error:
> There was no runtime pack for Microsoft.AspNetCore.App available for the specified RuntimeIdentifier 'browser-wasm'.

## Background

This problem comes up when referencing a `Class Library` from a Blazor Client (WASM) that dependents on the Asp framework:

```xml
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
``` 

## Solution / Hack

Add the following lines to your blazor client project to enable building. 

> Tested with 8.0.4

```xml
    <Target Name="AllowUsingAspNetCoreInBlazorWasm" AfterTargets="ProcessFrameworkReferences" >
        <ItemGroup>
            <UnavailableRuntimePack Remove="Microsoft.AspNetCore.App" />
        </ItemGroup>
    </Target>
```

Please be aware that this does not guarantee that everything will just work, as there is a reason why it was made unavailable.

A better fix, one that can only be done by Microsoft, would be to split asp into assemblies that are not platform dependent and those that are.

## Justification

In my case I needed:

```
Microsoft.AspNetCore.Http.Abstractions
Microsoft.AspNetCore.Mvc.Core
```

For these types:

```
// From Microsoft.AspNetCore.Http.Abstractions
IFromRouteMetadata
IFromQueryMetadata
IFromHeaderMetadata
IFromBodyMetadata

// Microsoft.AspNetCore.Mvc.Core
IActionHttpMethodProvider
IRouteTemplateProvider
```
etc.

Which in my opinion should be fair game, in regards where to use them.

**Comment by javiercn** [comment]
@LunicLynx thanks for contacting us.

It's not in our plans to re-architect the asp.net core framework to support this nor do we recommend using the approach you used above (even if it worked on a particular case) we don't guarantee it will work in the future.

We offer guidance on how to approach this by relying on platform/framework agnostic primitives on your class library and providing different implementations for server and webassembly.
