### ISSUE TITLE
AddQuickGridEntityFrameworkAdapter is missing from API docs

### ISSUE THREAD

**Issue by guardrex** [dotnet/aspnetcore#55136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Working on the QuickGrid docs and noticed that `AddQuickGridEntityFrameworkAdapter` is missing from API docs, so our article can't cross-link ...

https://learn.microsoft.com/dotnet/api/?term=AddQuickGridEntityFrameworkAdapter

API: https://github.com/dotnet/aspnetcore/blob/main/src/Components/QuickGrid/Microsoft.AspNetCore.Components.QuickGrid.EntityFrameworkAdapter/src/EntityFrameworkAdapterServiceCollectionExtensions.cs#L18

### Expected Behavior

N/A

### Steps To Reproduce

N/A

### Exceptions (if any)

N/A

### .NET Version

8.0

**Comment by mkArtakMSFT** [comment]
@Rick-Anderson do you know who can help with this?

**Comment by Rick-Anderson** [comment]
@guardrex  we could schedule an API build but why don't you just link to the source ?
cc @tdykstra

**Comment by guardrex** [comment]
The public API should be in the API docs AFAIK, and linking to source is somewhat unstable.

I thought that there was just a simple internal form/process that gets it consumed for API docs. We just went through this for QuickGrid ...

https://github.com/dotnet/aspnetcore/issues/52466

Did @v-alje help with that?

**Comment by mkArtakMSFT** [comment]
@v-alje is this something you can help with?

**Comment by v-alje** [comment]
@mkArtakMSFT What is the NuGet package for this?

**Comment by guardrex** [comment]
I think it's this one ...

https://www.nuget.org/packages/Microsoft.AspNetCore.Components.QuickGrid.EntityFrameworkAdapter/

**Comment by guardrex** [comment]
BTW @v-alje ... If I come across additional missing API in the API docs, are you the person to reach out to? If so, what's the best way to file an issue like this for you?

**Comment by v-alje** [comment]
@guardrex Yes. Please file requests using this template: https://dev.azure.com/msft-skilling/Content/_workitems/create/User%20Story?templateId=39fb91e3-64a2-4c8a-83db-b2bdf3603dd3&ownerId=c4a28f90-17ae-4384-b514-7273392b082b

**Comment by guardrex** [comment]
Sorry, I'm unable to directly do that myself. In the future, I'll ask Rick or one of the FTE MS docs folks to do it for me. Thanks for the link! This happens about once or twice a year around here.

**Comment by mkArtakMSFT** [comment]
Hi @v-alje, @guardrex. Do you want me to file the request or was it already filed ?

**Comment by guardrex** [comment]
Yes, please do. I can't reach that form.

**Comment by v-alje** [comment]
@mkArtakMSFT You can use: https://dev.azure.com/msft-skilling/Content/_workitems/edit/248694 The preview is up on the review site

**Comment by mkArtakMSFT** [comment]
@v-alje this can be closed now, correct?

**Comment by v-alje** [comment]
Yes. The Changed from processing https://www.nuget.org/packages/Microsoft.AspNetCore.Components.QuickGrid.EntityFrameworkAdapter/ has been published.
