### ISSUE TITLE
NTLM authentication not working in Linux based environment

### ISSUE THREAD

**Issue by jondoe69420** [dotnet/aspnetcore#55146]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I need to send an http request to a server which uses Windows authentication. I wrote the following code to try and send just any request to my server.

```c#
var handler = new HttpClientHandler 
{
    PreAuthenticate = true,
    UseProxy = false,
    UseDefaultCredentials = false,
    Credentials = new CredentialCache
    {
        {
            new Uri("http://otherapi"), "Negotiate", new NetworkCredential("username", "password")
        }
    }
}

using var client = new HttpClient(handler);
var stringContent = new StringContent("{}", Encoding.UTF8, "application/json");
using var request = new HttpRequestMessage(HttpMethod.Post, "http://otherapi/api/endpoint");
request.Content = stringContent;
using var res = await client.SendAsync(request);
Console.WriteLine($"{res.StatusCode}");
```

When running the above code on a Windows machine, everything works as expected, and `BadRequest` gets printed to the console ( which is what I expect to happen when sending an invalid json request ).

The problem is, I need to run this code on a Linux based machine, and when running it on an Ubuntu 22 machine (as well as the official aspnet docker image),  it fails and prints out to the console `Unauthorized`, which means the windows authentication didn't work.

I opened up Wireshark on my windows machine to try and figure out whats going on. I saw that the client initially sends a POST request to the server, and then the server responds with a `401`, and the following headers

```
WWW-Authenticate: Negotiate
WWW-Authenticate: NTLM
```

After that I saw that the client sent the same request again, this time with an `Authorization` header, which from what I understand, is the correct behaviour. After that the request continues as expected.

The problem is, when I open Wireshark on my Ubuntu machine, I see that after the server responded with the first 401, the client just stops sending requests for some reason.

### Expected Behavior

The Windows and Ubuntu behaviour to be the same.

### Steps To Reproduce

Run the following code in a Linux machine 

```c#
var handler = new HttpClientHandler 
{
    PreAuthenticate = true,
    UseProxy = false,
    UseDefaultCredentials = false,
    Credentials = new CredentialsCache
    {
        {
            new Uri("http://otherapi"), "Negotiate", new NetworkCredential("username", "password")
        }
    }
}

var client = new HttpClient(handler);
var stringContent = new StringContent(JsonSerializer.Serialize<object>("{}"), Encoding.UTF8, "application/json");
var request = new HttpRequestMessage(HttpMethod.Post, "http://otherapi/api/endpoint")
{
    Content = stringContent
}

var res = await client.SendAsync(request);
Console.WriteLine($"{res.StatusCode}");
```

### .NET Version

net7.0

**Comment by jondoe69420** [comment]
@martincostello Thanks! Will open it there. Also, I tried using .NET 8 and still no change unfortunately.

**Comment by gfoidl** [comment]
I'm closing this one here, as it will be handled in https://github.com/dotnet/runtime/issues/101058.
