### ISSUE TITLE
RequestDelegateGenerator should move to GetInterceptableLocation API

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/aspnetcore#55152]
Roslyn just introduced a [new API](https://github.com/dotnet/roslyn/issues/72133) for creating `[InterceptsLocation]` attributes in generated code. This uses a new opaque encoding for the location.

We'd like our partners to onboard to this new API as soon as is feasible. (We *just* merged it so may be a day or two before arcade will start handing out compilers which contain it.)

The old path-line-column approach is going to be deprecated and support removed prior to stable release of the feature.

**Comment by captainsafia** [comment]
Closed in above PR.
