### ISSUE TITLE
NavigationManager different behavior on WebAssembly since 8.0.3

### ISSUE THREAD

**Issue by alex-fitplans** [dotnet/aspnetcore#55171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm not exactly sure how to title this issue.

Consider the following simplified code, that adds a dummy navigation before displaying a popup (here using mudblazor, but the issue isn't specific to it), so that the user can navigate back to close it:

```razor
@page "/"
@inject NavigationManager NavigationManager
@inject IDialogService DialogService
@using MudBlazor
@implements IDisposable
@rendermode InteractiveServer

<PageTitle>Home</PageTitle>

<MudButton OnClick="Callback" Variant="Variant.Filled" Color="Color.Primary">Click Me</MudButton>

@code
{
    private IDialogReference? _currentDialog = null;
    
    protected override void OnInitialized()
    {
        base.OnInitialized();
        NavigationManager.LocationChanged += NavigationManagerOnLocationChanged; 
    }

    private void NavigationManagerOnLocationChanged(object? sender, LocationChangedEventArgs e)
    {
        if (_currentDialog != null)
            _currentDialog.Close();
    }

    private async void Callback()
    {
        var options = new DialogOptions { CloseOnEscapeKey = true };
        NavigationManager.NavigateTo("/#", false, false);
        _currentDialog = await DialogService.ShowAsync<SampleDialog>("Simple Dialog", options);
        var result = await _currentDialog.Result; 
        if (!result.Canceled)
        {
            // Do something
        }
        
        // Navigate back - example
        NavigationManager.NavigateTo("/", false, true);
    }

    public void Dispose()
    {
        NavigationManager.LocationChanged -= NavigationManagerOnLocationChanged; 
    }
}
```

This code worked fine both on WebAssembly and InteractiveServer modes until 8.0.2. After 8.0.3, the same code still works in InteractiveServer, but no longer pops the popup in WebAssembly. 

### Expected Behavior

I would expect the same behavior between WebAssembly and Interactive Server modes.

### Steps To Reproduce

I've created a small repro here: https://github.com/alex-fitplans/sample-popup
Simply click on the button on the home page.

Downgrade to 8.0.2 (or to previous commit) to restore the functionality.

### .NET Version

8.0.3

**Comment by mkArtakMSFT** [comment]
@alex-fitplans please make sure you provide a repro without any dependencies (MudBlazor in this case).
