### ISSUE TITLE
Binding to IFormFileCollection results in empty collection

### ISSUE THREAD

**Issue by frasermclean** [dotnet/aspnetcore#55174]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am migrating from a minimal API implementation to a controller-based implementation. A previously working minimal API endpoint that bound to IFormFileCollection now binds successfully in the controller method, but the collection is empty. 

```csharp
[HttpPost("{animalId:guid}/images")]
public async Task<IActionResult> AddAnimalImages(Guid animalId, IFormFileCollection formFileCollection,
    CancellationToken cancellationToken)
{
    var command = new AddAnimalImagesCommand(animalId, User.GetUserId(),
        formFileCollection.Select(formFile => new AnimalImageFileData(
            formFile.FileName,
            formFile.Name,
            formFile.ContentType,
            formFile.Length,
            formFile.OpenReadStream())));
    var result = await sender.Send(command, cancellationToken);

    return result.IsSuccess
        ? Ok(result.Value.ToResponse())
        : Problem(result.Errors);
}
```

### Expected Behavior

Expected similar behaviour to minimal API implementation.

### .NET Version

8.0.200

### Anything else?

I have tried binding to `IEnumerable<IFormFile>` and `List<IFormFile>`. All result in the same outcome.

Previously, in the minimal API implementation, I had to disable anti-forgery but not sure if that needs to be done with controller-based APIs.

**Comment by frasermclean** [comment]
The files do seem to be a part of the request as I have modified the method to the following as a workaround.

```csharp
[HttpPost("{animalId:guid}/images")]
public async Task<IActionResult> AddAnimalImages(Guid animalId, IFormFileCollection formFileCollection,
    CancellationToken cancellationToken)
{
    // TODO: Temporary workaround until https://github.com/dotnet/aspnetcore/issues/55174 is resolved
    if (formFileCollection.Count == 0)
    {
        var form = await Request.ReadFormAsync(cancellationToken);
        formFileCollection = form.Files;
    }

    var command = new AddAnimalImagesCommand(animalId, User.GetUserId(),
        formFileCollection.Select(formFile => new AnimalImageFileData(
            formFile.FileName,
            formFile.Name,
            formFile.ContentType,
            formFile.Length,
            formFile.OpenReadStream())));
    var result = await sender.Send(command, cancellationToken);

    return result.IsSuccess
        ? Ok(result.Value.ToResponse())
        : Problem(result.Errors);
}
```

**Comment by KennethHoff** [comment]
This feels related to [this issue](https://github.com/dotnet/aspnetcore/issues/54999) I posted some weeks back, but I'm not sure. What if you rename the parameter to the name of the files in the form?

**Comment by frasermclean** [comment]
> This feels related to [this issue](https://github.com/dotnet/aspnetcore/issues/54999) I posted some weeks back, but I'm not sure. What if you rename the parameter to the name of the files in the form?
> 
> How come you transitioning away from minimal API btw? Surely you'd do the opposite? Move away from controllers towards minimal?

There is no form per se as it is coming from a SPA. For my testing I am using Postman using form-data body. Unless I am misunderstanding something?

I reverted to using controllers as I wanted shared logic for response mapping across all endpoints and couldn't see a clean way to do it with minimal API static methods.

**Comment by captainsafia** [comment]
@frasermclean The form binding implementations that minimal API and MVC use are distinct so difference in behavior is expected. 

Would you be able to share a minimal repro and the sample input? I'm a little surprised that MVC is binding less than minimal is given the scope of MVC's model binding although there might be something else going on here.

**Comment by balazsmeszegeto** [comment]
Minimal repro is given in the first post, any controller action with `IFormFileCollection` parameter would result.

**Comment by captainsafia** [comment]
@balazsmeszegeto Minimal repro would ideally be self-contained (e.g. no reference to types like `AddAnimalImagesCommand` and resources resolved from DI like `sender`).

**Comment by balazsmeszegeto** [comment]
Those types does not really make any difference for parameter binding, but then here's a self-contained Program.cs

```
using Microsoft.AspNetCore.Mvc;

var builder = WebApplication.CreateBuilder(args);
builder.Services.AddControllers();
var app = builder.Build();

app.MapControllers()
    .DisableAntiforgery(); // only for easier testing

app.MapPost("/works", (IFormFileCollection files) => Results.Ok(files.Count))
    .DisableAntiforgery();

app.Run();

namespace MyNamespace
{
    public class MyController : Controller
    {
        [HttpPost("/does-not-work")]
        public async Task<IResult> UploadAsync(IFormFileCollection files)
        {
            // https://github.com/dotnet/aspnetcore/issues/55174
            // files is always empty, workaround:
            var form = await Request.ReadFormAsync();
            files = form.Files;

            return Results.Ok(files.Count);
        }
    }
}
```

**Comment by ggirard07** [comment]
Any update on this? I think I am seeing the same behavior in dotnet 8 WebAPI project for `IFormFileCollection`.
In my case, only way to get something bound to my parameter, is to actually match the name of a file in the form... which defeats the purpose of `IFormFileCollection` in the first place.

**EDIT**: I think I ultimately understood it, not sure if doc is unclear or I am just too long to catch up. All files under the same form part are returned. Only solution to access all the form files at once, regardless in how many form part they are defined, is `HttpContext.Request.Form.Files`.
