### ISSUE TITLE
No arm64 installer for .NET 8.0 Windows Hosting Bundle

### ISSUE THREAD

**Issue by nuelle16** [dotnet/aspnetcore#55180]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Like for .NET Desktop Runtime 8.0.x there should be an arm64 installer available.

![image](https://github.com/dotnet/aspnetcore/assets/118738546/af67b54e-881a-465a-96e8-141edd6d90fe)

vs.

![image](https://github.com/dotnet/aspnetcore/assets/118738546/261e8e30-0bd0-4e0a-a7f0-e061e2ae1bd4)

We are bundling a custom install-script using powershell to bring the required .Net dependencies onto a target machine (offline install is mandatory).

### Expected Behavior

Both x64 and arm64 installers available for the ASP.NET Core Runtime 8.0.x

### Steps To Reproduce

Visit: https://dotnet.microsoft.com/en-us/download/dotnet/8.0

### Exceptions (if any)

none

### .NET Version

8

**Comment by amcasey** [comment]
This might belong in `dotnet/installer`.  @wtgodbe?

**Comment by wtgodbe** [comment]
We do produce and publish them, but it looks like the links don't wind up on the release page. I'll sync up w/ @rbhanda and @mmitche on this

**Comment by wtgodbe** [comment]
Thanks for the report @nuelle16!

**Comment by wtgodbe** [comment]
We're aiming to get this fixed for the release publishing in June

**Comment by tzeejay** [comment]
@wtgodbe Hey there, we're waiting on this to get a ARM64 build of our new Guardian Firewall + VPN app built, the x86_64 version is currently in closed beta and will launch into an open beta soon. We're quite excited about the new Copilot+ PCs and would like to be ready for that on day one. 
June has come and gone without the installers being available, is there anything we can do to help the process along? I am certain that there is a very good reason for it to not have happened yet so I don't want to sound ungrateful.

**Comment by nuelle16** [comment]
So yesterday the ASP.NET Core Runtime 8.0.7 was released. Still no arm64 installer for the hosting bundle. Any updates on what is holding this back @wtgodbe ?

**Comment by martincostello** [comment]
If you look at the JSON file that powers the download page, it looks like it exists: https://github.com/dotnet/core/blob/46eab6765980914d9481ccecebec302153621c45/release-notes/8.0/releases.json#L524

Maybe it existed last month too, I'm on my phone so didn't look further as it's faff.

Maybe the issue is that the website just hasn't been updated to render the link?

**Comment by nuelle16** [comment]
Ok this way I was able to download the installer: 

![image](https://github.com/dotnet/aspnetcore/assets/118738546/03d8e94b-0b69-4672-84b4-50a4d1ac883e)

so it´s the website that is not taking this into account.

**Comment by nuelle16** [comment]
@martincostello @wtgodbe Any update on this? Will it be fixed for the august release?

**Comment by wtgodbe** [comment]
@mairaw any update on this one?

**Comment by nuelle16** [comment]
Something odd to add here.... Now that version 8.0.8 is out the [JSON ](https://github.com/dotnet/core/blob/main/release-notes/8.0/releases.json)file that @martincostello referred to earlier is still on version 8.0.7    .....1c7/aspnetcore-runtime-8.0.7-win-arm64.exe

**Comment by martincostello** [comment]
Not sure what you're looking at. The 8.0.7 file is under the 8.0.7 release, and the 8.0.8 file is under the 8.0.8 release [here](https://github.com/dotnet/core/blob/371cc791f6cac499817626c8e9a0965dc6e156a6/release-notes/8.0/releases.json#L742).

**Comment by nuelle16** [comment]
ok, that is maybe when i changed to the main branch, ok the JSON is fine. But still it is not reflected on the website,

**Comment by nuelle16** [comment]
@wtgodbe Any update? Is there a chance this is fixed in September release?

**Comment by wtgodbe** [comment]
The September release was canceled - @mairaw will the download page be updated for October?

**Comment by mairaw** [comment]
It has been updated last week. I think we can close this. But let me know if you see any other issues.
