### ISSUE TITLE
Overridden TryParseValueFromString does not appear to be used

### ISSUE THREAD

**Issue by ThinkElevenSean** [dotnet/aspnetcore#55197]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We have been developing Blazor components which inherit from InputBase<T>. We have some validation in the overridden TryParseValueFromString method, however this method does not seem to be used, the debugger never reaches it. 

Thinking we had missed something, we investigated the example at https://blazor-university.com/forms/descending-from-inputbase/.

We found when implementing this that this method was not getting used here either. We're pretty sure that not so long ago this was not the case, as we developed components that provided an error on validation, indeed the component on this page contains validation code which makes us think the author expected the same.

I have uploaded a solution at https://github.com/ThinkElevenSean/TryParseValueFromString which contains a simple component that we have made (IntegerComponent) and the one from the Blazor University Page (InputColour). I have tested both as a .Net 7 solution and a .Net 8 solution and in neither instance does execution appear to reach TryParseValueFromString.

Has something changed around the behaviour of this base class?

### Expected Behavior

TryParseValueFromString is executed when input is received from the HTML control, validation takes place and an error is produced on invalid validation

### Steps To Reproduce

https://github.com/ThinkElevenSean/TryParseValueFromString

### .NET Version

7, 8

**Comment by ThinkElevenDave** [comment]
Quick component repo here for convenience.  Render mode is InteractiveServer.
Also created a new Blazor project type in VS (.Net 8) and the same thing occurs

```
@inherits InputBase<int?>

<div>
    <input type="text" @bind=CurrentValue />
</div>

@code {
    protected override bool TryParseValueFromString(string? value, out int? result, out string validationErrorMessage)
    {
        validationErrorMessage = "";
        result = null;

        if (string.IsNullOrWhiteSpace(value))
        {
            return true;
        }

        int parsedInt;

        if (!int.TryParse(value.Trim(), out parsedInt))
        {
            validationErrorMessage = "Invalid value!";
            return false;
        }

        result = parsedInt;
        return true;
    }
}
```

**Comment by ThinkElevenSean** [comment]
After more research I believe I've worked out what I'm doing wrong - I'm binding to CurrentValue, which takes it type from the base class, in this case InputBase<int?>. So CurrentValue is an int?, the type is int?, so no conversion from a string needs to occur. If I bind to CurrentValueAsString directly in my IntegerComponent then conversion has to happen from string to int?, and the TryParseValueFromString method gets called.

Apologies for my n00bishness!

**Comment by anandgothe** [comment]
I have tried with CurrentValueAsString, it still doesn't hit the TryParseValueFromString. Has something changed recently?
