### ISSUE TITLE
Meaningless error when using both Microsoft.AspNetCore.Authentication.OpenIdConnect 8.0.4 and System.IdentityModel.Tokens.Jwt 7.5.0 or higher

### ISSUE THREAD

**Issue by CunesPoort8** [dotnet/aspnetcore#55194]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using the Microsoft.AspNetCore.Authentication.OpenIdConnect package version 8.04 and the System.IdentityModel.Tokens.Jwt package version 7.5.0 or higher, a meaningless error arises not pointing in the direction of the cause.

<img width="1186" alt="Screenshot 2024-04-18 at 09 57 14" src="https://github.com/dotnet/aspnetcore/assets/129159958/32570d33-1237-49cf-9ade-939e83458ae2">

All works well when the System.IdentityModel.Tokens.Jwt package is deleted and the Microsoft.AspNetCore.Authentication.OpenIdConnect package uses its default 7.1.2 version.

### Expected Behavior

A working login procedure with up to date System.IdentityModel.Tokens.Jwt package. Please add support for this package in the latest Microsoft.AspNetCore.Authentication.OpenIdConnect package.

### Steps To Reproduce

Install both packages and perform an open id connect login procedure with only a Authority set, so the Open ID connect middleware will figure out it's configuration from the .well-known/openid-configuration endpoint.

See https://github.com/POORT8/AspNetCore.Repro.55194 for a minimal reproduction repo.

### .NET Version

.NET 8

**Comment by utarn** [comment]
I also got this error when upgrading from Microsoft.AspNetCore.Authentication.OpenIdConnect 8.0.2 to Microsoft.AspNetCore.Authentication.OpenIdConnect 8.0.4

**Comment by CunesPoort8** [comment]
The minimal repro project can be found here: https://github.com/POORT8/AspNetCore.Repro.55194

**Comment by CunesPoort8** [comment]
Hi @halter73, yes indeed this fixes the issue both in the minimal repro project as well in our project where we encountered the issue. Is this your proposed solution? Is there any plan on updating the Microsoft.IdentityModel.Protocols.OpenIdConnect package in the Microsoft.AspNetCore.Authentication.OpenIdConnect package any time soon? Also to replace the deprecated System.IdentityModel.Tokens.Jwt which is in there?

**Comment by mkArtakMSFT** [comment]
Closing as this is similar to https://github.com/dotnet/aspnetcore/issues/55355. We're working with the Entra team to get these addressed. Given that the work is not happening in this repo, closing this issue.
