### ISSUE TITLE
npm ERR! request to https://registry.npmjs.org/@microsoft%2fsignalr failed, reason: unable to verify the first certificate

### ISSUE THREAD

**Issue by grifin85** [dotnet/aspnetcore#55203]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I try to install package @microsoft/signalr to my web client project
`npm install @microsoft/signalr`
I get an error in console
`npm ERR! code UNABLE_TO_VERIFY_LEAF_SIGNATURE`
`npm ERR! errno UNABLE_TO_VERIFY_LEAF_SIGNATURE`
`npm ERR! request to https://registry.npmjs.org/@microsoft%2fsignalr failed, reason: unable to verify the first certificate`

**Comment by adityamandaleeka** [comment]
@grifin85 This appears to be an issue with your connection to the NPM registry, not a SignalR issue. You probably will see the issue regardless of what package you're installing. It's hard to root-cause the problem just based on that message, but you can try checking if you're behind a VPN or firewall that's doing anything interesting, or if you have any modifications to how CA lookups work.
