### ISSUE TITLE
Blazor WASM App navigation won't stop image request when image is a stream (webcam)

### ISSUE THREAD

**Issue by emmuss** [dotnet/aspnetcore#55219]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When an `<img>` tag has an source attibute poiting to a never ending stream (webcam) navigation between blazor pages won't dispose the stream, the application keeps building up streams for each navigation request, even trying to remove the tag from the dom using javascript does not work.

see the attached image, 4 navigations between the two pages have been executed and the streams keep accumulating.

![image](https://github.com/dotnet/aspnetcore/assets/165521478/55a4d75d-a259-47f1-a198-23596e569b64)

### Expected Behavior

image streaming comes to a halt when the page is disposed.

### .NET Version

8.0.204

**Comment by emmuss** [comment]
This is my current solution to stop the stream:
´´´csharp
    async ValueTask IAsyncDisposable.DisposeAsync()
    {
        await JS.InvokeVoidAsync("eval", "document.getElementById('webCam').src = 'https://i.imgur.com/c24qDz2_d.jpeg?maxwidth=520&shape=thumb&fidelity=high'");
    }
´´´

**Comment by javiercn** [comment]
@emmuss thanks for contacting us.

Does setting the image source to `''` achieve the same effect?

We don't think this is something that the framework can effectively handle and its something that you have to handle in your app. In a regular navigation the page would go away, but in an enhanced nav, the document is preserved, hence the change in behavior.

There's really nothing the framework can do out of the box as we don't have a way to detect this situation (the browser is doing the request, not Blazor), so I suspect the only way to achieve this is to do something similar to what you are doing. Maybe you could think of encapsulating this in a component with its related JS and hook on to "enhancedload" to trigger the behavior to cancel the stream.
