### ISSUE TITLE
Blazor @onclick not working

### ISSUE THREAD

**Issue by eduardoxvii** [dotnet/aspnetcore#55225]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The @onclick is not trigging

### Expected Behavior

I want my page buttons to work if the user is translating the page...

### Steps To Reproduce

Create a Blazor project with interactive render mode with Auto;
Run the project;
Click on counter menu;
Translate the page for Portuguese for exemple;
Click on button;
You'll see that is not working!!! 

### .NET Version

.net 8

**Comment by MariovanZeist** [comment]
Hi @eduardoxvii 

The main issue here is that Blazor (and other frameworks) don't react well to DOM manipulations not under their control.

I would recommend you disable the automatic translation of web pages 
One way to do this globally is by adding ``translate="no"`` to the ``html`` tag (``<html translate="no"``)

Duplicates
https://github.com/dotnet/aspnetcore/issues/26945
https://github.com/dotnet/aspnetcore/issues/47111

**Comment by javiercn** [comment]
@eduardoxvii thanks for contacting us.

@MariovanZeist answer is correct here.
