### ISSUE TITLE
"Attribute 'Format' was matched by multiple bind attributes" error when a Razor component @inherits a BlazorComponent that has a [Parameter]

### ISSUE THREAD

**Issue by vatara** [dotnet/aspnetcore#5522]
### Title
"Attribute 'Format' was matched by multiple bind attributes" error when a Razor component @inherits a BlazorComponent that has a [Parameter]

### Functional impact
Won't compile while the BlazorComponent class has a [Parameter]

### Minimal repro steps
Test project: https://github.com/vatara/BlazorTest/tree/94ce188e4ff6680778a3781488149af74fa9a212

### Expected result
No error

### Actual result
This compile error:
```
The attribute 'Format' was matched by multiple bind attributes. Duplicates:
BlazorTest.Client.Pages.DateTime
BlazorTest.Client.Display.Elements.DateTime
```

### Further technical details
I have a page DateTime that uses @inherits
https://github.com/vatara/BlazorTest/blob/94ce188e4ff6680778a3781488149af74fa9a212/BlazorTest.Client/Pages/DateTime.cshtml

The DateTime BlazorComponent it @inherits has a [Parameter] named Format
https://github.com/vatara/BlazorTest/blob/94ce188e4ff6680778a3781488149af74fa9a212/BlazorTest.Client/Display/Elements/DateTime.cs#L10-L11

When a page using component tries to set the [Parameter] it gives the error above:
https://github.com/vatara/BlazorTest/blob/6445791d32d329b190448a8ae2cd92cec98fb517/BlazorTest.Client/Pages/Index.cshtml#L7

It seems like the [Parameter] is getting counted twice, once on the BlazorComponent and again on the Razor page that @inherits it.

It worked fine when I had the BlazorComponent in the Razor .cshtml page instead of inheriting.
It also works fine if I don't try to set the [Parameter] or remove it entirely.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
