### ISSUE TITLE
Resumable State Machine for Blazor

### ISSUE THREAD

**Issue by Xyncgas** [dotnet/aspnetcore#55232]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

It's related to a problem :
```Rendering components can trigger more rendering in those components```
Sometimes I can not control things or it would break my workflows so the components would be updated to contain nothing when it's reloading then when the items are fetched it lists the items again, therefore reloading my component causes the stuffs on screen to be 'flashing', I can fix the problem myself but the most simple solution I can think of is this feature I am suggesting

### Describe the solution you'd like

Two methods are introduced in Blazor : Resume & Pause
I can ```Pause``` Blazor so anything happening is not going to be updated to the browser, I can manually ```Resume``` Blazor if I desire stuffs on screen to be updated

### Additional context

It should be a global method for the entire 'Blazor' framework not just for the component

**Comment by javiercn** [comment]
@Xyncgas thanks for contacting us.

This scenario is already possible PersistentComponentState is the solution for these cases. We don't plan to introduce adhoc method to the component model for this.

If you want a different solution, you can implement it in your own component base class. We definitely do not plan to let users control things like this outside of their own components.

**Comment by Xyncgas** [comment]
thanks
