### ISSUE TITLE
HttpClient doesn't have authentication headers during OnInitialized or OnAfterRender when using global InteractiveAuto rendering

### ISSUE THREAD

**Issue by AgenChicken24** [dotnet/aspnetcore#55262]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

The issue arises when using global interactive rendering and attempting to fetch data from an authorized endpoint during OnInitializedAsync or OnAfterRenderAsync events. In this scenario, the request gets redirected to the login page instead of the intended endpoint.

### Expected Behavior

The request is sent to the right destination. The issue might be that the HttpClient lacks authorization headers during the initial server-side render when the server controls the request. This could be resolved by automatically passing the headers from the initial get request.

### Steps To Reproduce

I've uploaded a repository [repo](https://github.com/AgenChicken24/Blazor-8-Bug)  demonstrating the issue. Apply the database migrations, then log in and try manually entering the endpoints "/data" to retrieve data and "/upload" to add data to the database. You can then go to the page called "Bug" and an error should occur.

Workaround 1: Change the global render mode from InteractiveAuto to InteractiveWebAssembly
![workaround](https://github.com/dotnet/aspnetcore/assets/64702468/09305ec9-5255-45f5-81cf-45e33f97cb01)

Workaround 2 (untested): Avoid using InteractiveAuto globally and set that page to render in "InteractiveWebAssembly" mode. Request the data on the initial render.

### .NET Version

8.204

**Comment by AgenChicken24** [comment]
With more investigation into how to handle data fetching I found [this](https://stackoverflow.com/questions/77525641/net-8-blazor-handling-data-with-auto-global-interactivity) topic in StackOverflow that it is a valid solution.

If this is the intended behavior of HttpClient I apologize for the unnecessary issue report.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. The solution you've found describes why things work they way they are correctly.
