### ISSUE TITLE
Blazor SSR with streaming disabled doesn't await child components

### ISSUE THREAD

**Issue by leonverschuren** [dotnet/aspnetcore#55261]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

A Blazor SSR page with streaming disabled doesn't wait for a long running Task in a child component to complete before rendering the final HTML to the browser.

### Expected Behavior

In the repro linked below I would expect that the `Home` page would take at least 3 seconds to load (due to the `Task.Delay` in `LongRunning.razor`) and show the text `Task is completed`. Instead it always shows the text `Task is running`.

### Steps To Reproduce

See this repro: https://github.com/leonverschuren/BlazorAppSSRWithoutStreaming

### .NET Version

.NET 8.0.204

**Comment by SteveSandersonMS** [comment]
It looks like the bug is in your app code:

```razor
@if (IsTaskCompleted)
{
    <p>Task is running</p>
}
else
{
    <p>Task is completed</p>
}
```

I think your if/else conditions are the wrong way round 😄
