### ISSUE TITLE
Update the qrcode docs for authenticator apps / how to generaten qrcodes for 2fa?

### ISSUE THREAD

**Issue by LuisThe0ne** [dotnet/aspnetcore#55260]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am trying to implement qrcode generation for 2fa, but  the docs (https://learn.microsoft.com/en-us/aspnet/core/security/authentication/identity-enable-qrcodes?view=aspnetcore-8.0) seem to be outdated, since they still mention the old identity pages (cshtml), altough .NET8 uses the new Razor pages per default. The there mentioned "@section Scripts" doesnt't exist with the new template.

### Describe the solution you'd like

Docs / a tutorial that describes how to implement qrcode generation with the new identity pages in .NET8.

**Comment by SteveSandersonMS** [comment]
We think the docs you're asking for are here: https://learn.microsoft.com/en-us/aspnet/core/blazor/security/server/qrcodes-for-authenticator-apps?view=aspnetcore-8.0

I'll close but if you think this is wrong, please let us know.
