### ISSUE TITLE
Invalid route throws a silent exception

### ISSUE THREAD

**Issue by masonwheeler** [dotnet/aspnetcore#5527]
Set up a page, and put the following at the top:

`@page "/ShouldWork/{ID: int}"`

(Note the space between the `:` and the `int`.)

Build and run.  Everything builds without error, but when attempting to run, after "Loading..." disappears, no content appears to replace it; you just end up with a blank browser window, and no error in the console.

The only way to figure out what's going wrong is putting a try-catch block around the `BrowserRenderer.AddComponent` invocation in Program.cs, and having it print the error to the console.  You end up with something like this:

> WASM: BR ready MonoPlatform.ts:191:25
WASM: System.ArgumentException: Unsupported constraint ' int' in route '/ShouldWork/{ID: int}'. MonoPlatform.ts:191:25
WASM:   at Microsoft.AspNetCore.Blazor.Routing.RouteConstraint.Parse (System.String template, System.String segment, System.String constraint) <0x1c42b88 + 0x0008c> in <0d9c96ffc9704aa9b088cbbe138126c6>:0 MonoPlatform.ts:191:25
WASM:   at Microsoft.AspNetCore.Blazor.Routing.TemplateSegment+<>c__DisplayClass0_0.<.ctor>b__0 (System.String token) <0x1c42450 + 0x0001c> in <0d9c96ffc9704aa9b088cbbe138126c6>:0 MonoPlatform.ts:191:25
WASM:   at System.Linq.Enumerable+SelectListPartitionIterator\`2[TSource,TResult].ToArray () <0x1c41e90 + 0x00068> in <87b8d63555bf4cccb15cd79d953a359d>:0 MonoPlatform.ts:191:25
WASM:   at System.Linq.Enumerable.ToArray[TSource] (System.Collections.Generic.IEnumerable\`1[T] source) <0x1c41c20 + 0x0003c> in <87b8d63555bf4cccb15cd79d953a359d>:0 MonoPlatform.ts:191:25
WASM:   at Microsoft.AspNetCore.Blazor.Routing.TemplateSegment..ctor (System.String template, System.String segment, System.Boolean isParameter) <0x1c31db8 + 0x00102> in <0d9c96ffc9704aa9b088cbbe138126c6>:0 MonoPlatform.ts:191:25
WASM:   at Microsoft.AspNetCore.Blazor.Routing.TemplateParser.ParseTemplate (System.String template) <0x1c2f758 + 0x001ea> in <0d9c96ffc9704aa9b088cbbe138126c6>:0 MonoPlatform.ts:191:25
WASM:   at Microsoft.AspNetCore.Blazor.Routing.RouteTable.Create (System.Collections.Generic.IEnumerable\`1[T] types) <0x1c0e7c8 + 0x0005a> in <0d9c96ffc9704aa9b088cbbe138126c6>:0 MonoPlatform.ts:191:25
WASM:   at Microsoft.AspNetCore.Blazor.Routing.Router.SetParameters (Microsoft.AspNetCore.Blazor.Components.ParameterCollection parameters) <0x19dfd88 + 0x0003e> in <0d9c96ffc9704aa9b088cbbe138126c6>:0 MonoPlatform.ts:191:25
WASM:   at Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame (Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder+DiffContext& diffContext, System.Int32 frameIndex) <0x1bde5d0 + 0x0007a> in <0d9c96ffc9704aa9b088cbbe138126c6>:0 MonoPlatform.ts:191:25
WASM:   at Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree (Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder+DiffContext& diffContext, System.Int32 frameIndex) <0x1bde440 + 0x00086> in <0d9c96ffc9704aa9b088cbbe138126c6>:0 MonoPlatform.ts:191:25
WASM:   at Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder.InsertNewFrame (Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder+DiffContext& diffContext, System.Int32 newFrameIndex) <0x1bdde48 + 0x000bc> in <0d9c96ffc9704aa9b088cbbe138126c6>:0 MonoPlatform.ts:191:25
WASM:   at Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange (Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder+DiffContext& diffContext, System.Int32 oldStartIndex, System.Int32 oldEndIndexExcl, System.Int32 newStartIndex, System.Int32 newEndIndexExcl) <0x1bd8d68 + 0x0025e> in <0d9c96ffc9704aa9b088cbbe138126c6>:0 MonoPlatform.ts:191:25
WASM:   at Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder.ComputeDiff (Microsoft.AspNetCore.Blazor.Rendering.Renderer renderer, Microsoft.AspNetCore.Blazor.Rendering.RenderBatchBuilder batchBuilder, System.Int32 componentId, Microsoft.AspNetCore.Blazor.RenderTree.ArrayRange\`1[T] oldTree, Microsoft.AspNetCore.Blazor.RenderTree.ArrayRange\`1[T] newTree) <0x1bd87c8 + 0x000a2> in <0d9c96ffc9704aa9b088cbbe138126c6>:0 MonoPlatform.ts:191:25
WASM:   at Microsoft.AspNetCore.Blazor.Rendering.ComponentState.RenderIntoBatch (Microsoft.AspNetCore.Blazor.Rendering.RenderBatchBuilder batchBuilder, Microsoft.AspNetCore.Blazor.RenderFragment renderFragment) <0x1bd3a88 + 0x000b4> in <0d9c96ffc9704aa9b088cbbe138126c6>:0 MonoPlatform.ts:191:25
WASM:   at Microsoft.AspNetCore.Blazor.Rendering.Renderer.RenderInExistingBatch (Microsoft.AspNetCore.Blazor.Rendering.RenderQueueEntry renderQueueEntry) <0x1bd3630 + 0x00040> in <0d9c96ffc9704aa9b088cbbe138126c6>:0 MonoPlatform.ts:191:25
WASM:   at Microsoft.AspNetCore.Blazor.Rendering.Renderer.ProcessRenderQueue () <0x1bd2d88 + 0x00048> in <0d9c96ffc9704aa9b088cbbe138126c6>:0 MonoPlatform.ts:191:25
WASM:   at Microsoft.AspNetCore.Blazor.Rendering.Renderer.AddToRenderQueue (System.Int32 componentId, Microsoft.AspNetCore.Blazor.RenderFragment renderFragment) <0x1bd1e88 + 0x00068> in <0d9c96ffc9704aa9b088cbbe138126c6>:0 MonoPlatform.ts:191:25
WASM:   at Microsoft.AspNetCore.Blazor.Components.RenderHandle.Render (Microsoft.AspNetCore.Blazor.RenderFragment renderFragment) <0x1bd1b70 + 0x00036> in <0d9c96ffc9704aa9b088cbbe138126c6>:0 MonoPlatform.ts:191:25
WASM:   at Microsoft.AspNetCore.Blazor.Components.BlazorComponent.StateHasChanged () <0x1bd1a78 + 0x00048> in <0d9c96ffc9704aa9b088cbbe138126c6>:0 MonoPlatform.ts:191:25
WASM:   at Microsoft.AspNetCore.Blazor.Components.BlazorComponent.SetParameters (Microsoft.AspNetCore.Blazor.Components.ParameterCollection parameters) <0x1bc37b0 + 0x000b2> in <0d9c96ffc9704aa9b088cbbe138126c6>:0 MonoPlatform.ts:191:25
WASM:   at Microsoft.AspNetCore.Blazor.Browser.Rendering.BrowserRenderer.AddComponent (System.Type componentType, System.String domElementSelector) <0x1b9fa50 + 0x0005e> in <92ed9c6772a34798bccecc99cc26cbcd>:0 MonoPlatform.ts:191:25
WASM:   at Microsoft.AspNetCore.Blazor.Browser.Rendering.BrowserRenderer.AddComponent[TComponent] (System.String domElementSelector) <0x1b9b698 + 0x00020> in <92ed9c6772a34798bccecc99cc26cbcd>:0 MonoPlatform.ts:191:25
WASM:   at DungeonEpicSpa.Program+<>c+<<Main>b__0_0>d.MoveNext () <0x18e8038 + 0x001ce> in <66587a3e6a964a25bf7b20a708681e76>:0 MonoPlatform.ts:191:25

There are two problems here.  First, the URL parser apparently can't deal with whitespace, for no good reason.  And second, this failure causes an unhandled exception that doesn't get reported in the browser's console.  (Which means it's probably handled at some point, but not before it escapes the project code and unwinds into the Blazor framework, rendering everything useless.)

**Comment by pranavkm** [comment]
The error message shows up in the developer console now, so the previous workarounds are no longer necessary. We do not plan to change the rules about how whitespace is handled within routes. Closing since the initial issue has been addressed.
