### ISSUE TITLE
Blazor.registerCustomEventType doesn't work with static SSR

### ISSUE THREAD

**Issue by sgarnovsky** [dotnet/aspnetcore#55273]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Blazor.registerCustomEventType doesn't look working with static SSR

### Expected Behavior

It is expected that Blazor.addEventListener handler is called after as a custom event was registered with Blazor.registerCustomEventType.

### Steps To Reproduce

```
function FireCustomEvent(elem) { 
    const event = new CustomEvent("customevent", { bubbles: true, detail: elem });
    elem.dispatchEvent(event);
}

Blazor.registerCustomEventType('customevent', {
    browserEventName: 'customevent',
    createEventArgs: event => {
        return { 'prop1': 1 };
    }
});

// it doesn't work
Blazor.addEventListener('customevent', function () {
    console.log('???? customevent event handled with Blazor ????');
});
```

### .NET Version

8.0.100

**Comment by SteveSandersonMS** [comment]
It looks like you're triggering a DOM event by calling `elem.dispatchEvent(event)`

With that being the case, you would receive the event notification by using the DOM event listener API, `elem.addEventListener(...)`.

You cannot use `Blazor.addEventListener` for that because `Blazor.addEventListener` is for listening to Blazor's events, which are not DOM events. So simply change to use `elem.addEventListener(...)` and it should work.

The use of these DOM events is completely independent of Blazor.

**Comment by sgarnovsky** [comment]
> You cannot use `Blazor.addEventListener` for that because `Blazor.addEventListener` is for listening to Blazor's events, which are not DOM events. So simply change to use `elem.addEventListener(...)` and it should work.
> 
> The use of these DOM events is completely independent of Blazor.

Yes, sure, it works with elem.addEventListener fine.

Maybe, I missed the main point to ask if Blazor.registerCustomEventType can be used with Blazor static SSR. 
Really, I didn't find a sample how to dispatch a custom Blazor event with static SSR.

**Comment by SteveSandersonMS** [comment]
> Really, I didn't find a sample how to dispatch a custom Blazor event with static SSR.

Static SSR produces HTML from your server only, so the only event handlers would be those written in JavaScript. If you want to handle events with .NET code, you'll need to use an interactive rendermode. That's the key difference between static and interactive rendering.

**Comment by sgarnovsky** [comment]
> Static SSR produces HTML from your server only, so the only event handlers would be those written in JavaScript. If you want to handle events with .NET code, you'll need to use an interactive rendermode. That's the key difference between static and interactive rendering.

Thank you for the confirmation. 
It means the Blazor static SSR doesn't work with Blazor.registerCustomEventType. 
I.e. there is no way to dispatch a registered custom blazor event in this Blazor app mode.

**Comment by SteveSandersonMS** [comment]
> I.e. there is no way to dispatch a registered custom blazor event in this Blazor app mode.

Right, because there's nothing to dispatch it to. Once the page has finished rendering statically, your code has finished running.

**Comment by sgarnovsky** [comment]
> Once the page has finished rendering statically, your code has finished running.
At some point, it is not a quite right statement. 
Blazor renders the static SSR content, but a client-side code continues running and can do a lot of things.
For example, Blazor has a client-side "enhancedload" event dispatching and I've just assumed I could create a custom event at the Blazor level too instead of using a browser document level custom event.
