### ISSUE TITLE
Burstable capacity?

### ISSUE THREAD

**Issue by Leonardo-Ferreira** [dotnet/aspnetcore#55289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

My application is crashing when a burst of requests arrive.

Load testing in production (2 pods) shows that if I ramp up concurrent user count slowly (1 new concurrent user every 3 seconds for example), the 50th, 75th and 90th percentile of the response time will stay basically the same up to the point of 150 concurrent users.

But if my app is idle (handling 10-20 req/min) and a burst of about 25 users appear (raising the req rate to about 3-5 req/sec), the app crashes... My first troubleshooting session indicated that the bottleneck was the database, and by setting the min number of open connections to 75, the burstable load increased to 90 users. The thing is: increasing this further did not make my app more resilient to bursts... setting it to 120, 150, 200 did not make my app being able to handle more concurrent users! BUUUUUT, if I burst the load from 0 to 90 and THEN ramp it up as described above, very soon im on the 150 concurrent users...

Can anyone help me figure out what else I could be dealing with?

### Expected Behavior

Application handling the 150 burst concurrent users without a hick-up

### Steps To Reproduce

Could not come up with a minimalist reproducible

### .NET Version

8 latest

### Anything else?

ASP.NET Core version is 8 latest
Running on AKS using MS alpine image
Using HTTPS terminated at the pod

**Comment by gfoidl** [comment]
@Leonardo-Ferreira can you please describe a bit more about your app (minimal APIs, controllers, etc.) / ideally provide a simple self-contained sample?

Otherwise it's too little information to make this issue actionable. Thanks.
