### ISSUE TITLE
http.server.active_requests metric incorrect when behind TLS-terminating load balancer

### ISSUE THREAD

**Issue by petedishman** [dotnet/aspnetcore#55280]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

With aspnetcore hosted behind a TLS terminating load balancer and `ForwardedHeadersMiddleware` configured with `XForwardedProto` the metric for http.server.active_requests is incorrectly handled.

The ForwardedHeadersMiddleware is changing the value of `HttpContext.Request.Scheme` from `http` to `https` but this occurs after the `HostingMetrics` class has recorded the request start using `scheme=http`

At the end of the request, it records the request ending, this time with `scheme=https`

The end result is that the UpDownCounter is incremented by 1 with scheme=http, and decremented by 1 with scheme=https making a mess of the metrics after a period of running you end up with metrics like:

```
http.server.active_requests{ http_request_method="GET", url_scheme="http"} = 100
http.server.active_requests{ http_request_method="GET", url_scheme="https"} = -100
```

### Expected Behavior

The metric needs to be incremented/decremented with a consistent scheme.

In this instance `http` probably makes the most sense

### Steps To Reproduce

https://github.com/petedishman/metrics-bug contains a project that reproduces the error

- Run the project `dotnet run`
- view metrics at `http://localhost:81/metrics`
- Make a request like a load balancer: `invoke-webrequest -Uri http://localhost:81/ -Headers @{'X-Forwarded-For' = '127.0.0.1'; 'X-Forwarded-Proto' = 'https';}`
- refresh metrics and see `http_server_active_requests` values

### .NET Version

8.0.200

**Comment by amcasey** [comment]
FYI @JamesNK

**Comment by JamesNK** [comment]
Thanks for the detailed bug report.

Fix here: https://github.com/dotnet/aspnetcore/pull/55351

This will be fixed in .NET 9 but I think you can work around it in .NET 8 with some middleware.

Add this to the start of the middleware pipeline before `UseForwardedHeaders()`:

```cs
app.Use(async (context, next) =>
{
    var scheme = context.Request.Scheme;
    await next();
    context.Request.Scheme = scheme;
});
```

That should restore the original scheme before the request ends and the counter is decreased.

**Comment by petedishman** [comment]
Thanks, workaround tested and working.
