### ISSUE TITLE
Blazor Server registers page 'unload' event instead of the recommended 'pagehide' or 'visibilitychange events

### ISSUE THREAD

**Issue by DataJuggler** [dotnet/aspnetcore#55299]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There was an issue from 2020, that was closed with the same title. 

https://github.com/dotnet/aspnetcore/issues/28070

Then you said it was by design. Now in 2024, Chrome is depreciating unload events, and I get an error using Chrome. Edge works.

### Expected Behavior

Blazor.Server.js should pagehide or something else instead of unload.

I can't show my client a prototype of how much faster our app is in Blazor (compared to MVC), if it only works on Edge. They won't go for that.

### Steps To Reproduce

Create a Blazor Server project. Switch to .NET 8, and update AspNetCoreComponents and .Web to 8.x version, add some components or buttons on the page, this happens.

In Edge it works.

![image](https://github.com/dotnet/aspnetcore/assets/26331133/655fd12a-5420-4d32-a308-7f2c9779b7a2)

### Exceptions (if any)

Chrome says 'Unload' event is depreciated, and points to Blazor.Server.js.

### .NET Version

.NET 8

### Anything else?

I had other errors in your Blazor Web App, now I forgot what. I don't ever use anything but Blazor Server, so I didn't see any reason to use Blazor Web App over the older version. I do wish the Blazor Server template was upgraded to .NET 8.

**Comment by DataJuggler** [comment]
I stand corrected. Now it happens in Edge. I feel like something I just did might have caused this, because it worked earlier today.
Investigating.

**Comment by SteveSandersonMS** [comment]
Could you post a repro app and full steps to reproduce the problem?

> add some components or buttons on the page, this happens

This is a bit too vague 😄 What specifically should be added, and what gestures do you do in the browser in order to get to this warning?

**Comment by DataJuggler** [comment]
I refactored my project from the Blazor Web App Template, and I no longer have the problem. I still see the warning in Browser Dev Tools that Unload was removed, but it doesn't throw any errors.

If it happens again I will open a new issue.
