### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#5531]
Provide a model for app configuration, like specifying the URL for an API endpoint. 

Would we use Microsoft.Extensions.Configuration for this? 
Where config source would we use? Local storage? Embedded resources?
How would change notification work?

**Comment by RemiBou** [comment]
Hi,

I found a way to configure my app using the URI and Microsoft.Extensions.Configuration. https://remibou.github.io/Configuring-a-Blazor-app/, please tell me what you think about it.

**Comment by sanzor** [comment]
I am facing a similar issue when i need to  find out the hostname of the server project in the startup of my client one. Is there any way to pass data from blazor server to blazor client at startup ?

**Comment by razfriman** [comment]
I am in a similar situation to @sanzor I have my API split from the client-side blazor app. I am having trouble passing in the URL for production/local without hardcoding it

**Comment by MarkFl12** [comment]
I'm having this issue as well, settings such as the API URL to use need a way to be changed based on the environment.

**Comment by rpedretti** [comment]
I have create a sample that reads a embedded json file.
https://github.com/rpedretti/RPedretti.Grpc/blob/master/RPedretti.Grpc.BlazorWasm.Client/Configuration/ConfigurationExtensions.cs

So on statup you can just add the files and get the configurationBuilder instance to reuse later
```
var configurationBuilder = services
    .AddEmbeddedJson("Configuration/appsettings.json", true)
    .AddEmbeddedJson("otherConfig.json")
    .GetJsonConfigurationBuilderBuilder();
var configuration = configurationBuilder.Build();```

**Comment by danroth27** [comment]
We've added Microsoft.Extensions.Configuration to the Blazor WebAssembly host. Let's use https://github.com/dotnet/aspnetcore/issues/18675 to track what config source(s) we want to provide out of the box.
