### ISSUE TITLE
Blazor Component cannot be nested inside a Parent component (using render fragment) if the nested component is interactive

### ISSUE THREAD

**Issue by htmlsplash** [dotnet/aspnetcore#55319]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Why is this not allowed in .net 8? This was allowed in .net 7 Server model.
The code below generates this Exception:

InvalidOperationException: Cannot pass the parameter 'ChildContent' to component 'Placeholder' with rendermode 'InteractiveServerRenderMode'. This is because the parameter is of the delegate type 'Microsoft.AspNetCore.Components.RenderFragment', which is arbitrary code and cannot be serialized.

`<Placeholder @rendermode="InteractiveServer">
	<AutoCompleteDDL ></AutoCompleteDDL>
	<AutoCompleteDDL ></AutoCompleteDDL>
</Placeholder>`

PlaceHolder code:

`
@ChildContent

@code {

	[Parameter]
	public RenderFragment ChildContent { get; set; }
}
`

### Describe the solution you'd like

See problem description.

**Comment by halter73** [comment]
This is also not supported. In .NET 7, you could not change render mode per component so this isn't exactly the same thing. You cannot pass RenderFragments across render mode boundaries like the exception message says.

You could potentially fix this by making the parent component ServerInteractive as well, so the RenderFragment does not cross a render mode boundary.
