### ISSUE TITLE
IHttpSysRequestTimingFeature.Timestamp is empty

### ISSUE THREAD

**Issue by ycymio** [dotnet/aspnetcore#55334]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi 

We want to add Http.Sys latency in logs and I saw there is a new feature using `IHttpSysRequestTimingFeature` in .NET 8. But when using it in our service, the Timestamp is always empty. 

I debugged a little bit about it and found this timingInfo cannot be retrieved from RequestInfo. Is there any missing step? Do we need to config something? 

![image](https://github.com/dotnet/aspnetcore/assets/11717066/39257205-7781-4385-8d21-ed2bbc4e498c)

### .NET Version

8.0.4

**Comment by NGloreous** [comment]
What version of windows are you running on? This is a newer version. I'll look up the minimum version later.

**Comment by NGloreous** [comment]
You need to be running Windows Server 2022 or Windows Client version 2004 (the May 2020 update or min build number of 19041).

**Comment by adityamandaleeka** [comment]
Thanks @NGloreous. Opened docs PR to specify the min OS versions: https://github.com/dotnet/AspNetCore.Docs/pull/32469

**Comment by BrennanConroy** [comment]
Closing, this is expected behavior and now documented

**Comment by ycymio** [comment]
> Windows Server 2022

Great. Thank you @NGloreous! It works when I switch to Windows Server 2022 for testing.

**Comment by ycymio** [comment]
@NGloreous I have one more question about the Timestamps: are they in order? Or could we know what's the order of the timing type?

**Comment by NGloreous** [comment]
They aren't guaranteed to be in order. The older ones are but newer ones are added to the end for compatibility. You can use the [HttpSysRequestTimingType](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.server.httpsys.httpsysrequesttimingtype) enum as the index into the array so you know what timings are in each index or you can use the [TryGetTimestamp](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.server.httpsys.ihttpsysrequesttimingfeature.trygettimestamp) helper method to just get the ones you care about. Also make sure you read [these remarks](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.server.httpsys.ihttpsysrequesttimingfeature.timestamps#remarks)
