### ISSUE TITLE
Linker enhancements

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#5533]
Ways we'd like to improve it in the short term:

* Update to the latest linker tooling. We've heard from the Mono team that they've made many improvements.
* Add and document a simpler mechanism for customising the linker's behavior. The linker already accepts `.xml` config files to control in more detail which types/methods are strippable/retainable. We should make it easier to supply a custom config alongside (or instead of) the default one.

**Comment by pranavkm** [comment]
We've since had many updates to the linker
