### ISSUE TITLE
Microsoft.AspNetCore.Http 2.2.2

### ISSUE THREAD

**Issue by kccarter76** [dotnet/aspnetcore#55352]
### Package Id

Microsoft.AspNetCore.Http

### Package Version(s)

2.2.2

### Additional details

this package does not have a replacement and has been flagged as deprecated where is the replacement package that is in support

**Comment by martincostello** [comment]
Since .NET Core 3.0 it is part of the ASP.NET Core shared framework, so there is no direct package replacement.

Delete any references to the package and use a [FrameworkReference](https://learn.microsoft.com/aspnet/core/fundamentals/target-aspnetcore#use-the-aspnet-core-shared-framework) instead.
