### ISSUE TITLE
Upgrade Polly to v8 in Microsoft.Extensions.Http.Polly

### ISSUE THREAD

**Issue by dnperfors** [dotnet/aspnetcore#55356]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

[Polly released v8](https://www.thepollyproject.org/2023/09/28/polly-v8-officially-released/) last year and this was basically a complete rewrite. It would be great if the Microsoft.Extensions.Http.Polly library can be updated to reflect these changes as well.

**Comment by martincostello** [comment]
My understanding, the team can correct me if I'm wrong, is that the [new HTTP resilience extensions](https://learn.microsoft.com/dotnet/core/resilience/http-resilience) added in .NET 8 are the successor to these extensions, and the ones here, even if upgraded to depend on Polly 8.x.x, would stay on our "old" API as moving to the Polly.Core functionality would be breaking changes to just duplicate what's in Microsoft.Extensions.Http.Resilience.

**Comment by dnperfors** [comment]
I clearly missed that, thanks for clarifying.

**Comment by dnperfors** [comment]
After playing with the resilience library, I can conclude that it is a good successor.
