### ISSUE TITLE
Clarifying timeouts in SignalR .NET6

### ISSUE THREAD

**Issue by roijvallabb** [dotnet/aspnetcore#55359]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Background
Recently I have been investigating a bug in our testing environment relating to switchover times in SignalR using DNS failover. This is tested on .NET6, I tried to check if .NET8 had any significant changes in this area but I failed to find any. We are planning to test similar scenarios in NET8 in the future.

### Problem
Assume you have a domain name https://example/app which is configured to redirect to two redundant servers, S1 and S2. The domain server is using round robin, so the order of the DNS records can be considered random from a client perspective.

If a client is connected to S1, and S1 is disconnected, the client will eventually switchover to S2. In the best case this takes ~1-10 seconds post SignalR ServerTimeout. In the worst case it takes 50+ seconds post ServerTimeout. 

The timing seems to depend on the order of the DNS records, the best case will always occur if the server the client switches to is the first DNS record, and the worst case will always occur when the client switches to the server with the second DNS record. The difference in time is mainly the timeout the browser waits before attempting to connect to the second DNS record.

### Question
Can we configure SignalR to avoid long timeouts? I have attempted any and all options I can get my hands on, but it does not seem to affect the timeout. For example if I configure HandshakeTimeout on the connection in the client, it does not seem to affect the TCP connection timeout I see when setting up the sockets. What then does the HandshakeTimeout accomplish?

For our product it would be important to control this behavior from the application as far as possible, rather then configuring settings on a client device whether that is browser flags or OS network stack.

### Describe the solution you'd like

Clarification on which timeouts we can configure and control in SignalR/ASP.NET Core and what timeouts the browser controls.

### Additional context

My illustration of the worst case scenario:
 
![image](https://github.com/dotnet/aspnetcore/assets/151143441/57b40323-9a18-4229-a25b-59e684ac9f88)

The ServerTimeout in the picture is configured to 10 seconds. The remaining timeouts I was not able to impact.

Browser timeout on HTTP request (auth token)
![image](https://github.com/dotnet/aspnetcore/assets/151143441/65eaa69a-f554-4a7f-b792-2914c00f0164)

HTTP2 session timeout (Chromium netlog)
![image](https://github.com/dotnet/aspnetcore/assets/151143441/add89101-ee52-42d5-9f0f-50db6e951def)
Websocket timeout (Chromium netlog)
![image](https://github.com/dotnet/aspnetcore/assets/151143441/a32ccb75-5b2b-401d-b9a9-745b3b8eaf55)

**Comment by BrennanConroy** [comment]
> Can we configure SignalR to avoid long timeouts?

It almost sounds like you want to timeout http requests. You can use the `timeout` option for this.
https://github.com/dotnet/aspnetcore/blob/eb18cb23cf2be9db70ae799e9b23a74a26e78d0b/src/SignalR/clients/ts/signalr/src/IHttpConnectionOptions.ts#L75
But this would cancel the http request and fail the connection starting.

> The difference in time is mainly the timeout the browser waits before attempting to connect to the second DNS record.

However, you mention it's the browser waiting before attempting a different DNS record which wouldn't be something we can control.

**Comment by roijvallabb** [comment]
Appreciate the quick reply!  

I am not sure exactly what timing out the HTTP request specifically might accomplish, my very limited understanding is that the consequence of using HTTPS is that we require a TCP connection for secure communication to handle HTTP requests. Would cancelling the HTTP request also cancel the HTTP2 session, or would we proceed in setting up the TCP connection regardless? Because if we are able to cancel the HTTP request and as a consequence cancel the HTTP2 session it sounds like we would end up in an infinite loop of retrying without success, as long as the HTTP timeout is <21 seconds.

I would try myself and see, but I am not sure where to configure timeout using a .NET client?

I think the conclusion for us is that we need to move away from DNS failover and implement a different solution for redundancy if we want to handle it in the application instead of relying on device network stack/browser settings. 


_For anyone interested in configuring Windows TCP parameters_
It is possible for us to configure some settings in the Windows to affect the browser timeout, i.e. changing Max SYN Retransmissions 4->2 changed the timeout we see in HTTP request from ~21 seconds to ~7 seconds. There is also the Initial RTO parameter that should affect this.
![image](https://github.com/dotnet/aspnetcore/assets/151143441/ae13bb9f-9ba8-4a05-8bcf-d200606f1d0d)
