### ISSUE TITLE
Browser encryption issue Platform not supported on the latest version of dotnet

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#55382]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Browser-encryption-issue-Platform-not-su/10642330)._

---
[severity:It bothers me. A fix would be nice]
While I was using the the API System.Cryptography  the encryption is  not working PlatformNotSupportedException . I using latest version of dotnet version 8.02 . The blazor have a cryptography method but  is this work on my  api( without using blazor serverO? please give a alternative for this issue

---
#### Feedback Bot on 4/21/2024, 10:19 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide [a minimalistic repro project](https://github.com/dotnet/aspnetcore/blob/main/docs/repro.md) that illustrates the problem.
