### ISSUE TITLE
VS shouldn't offer to scaffold MVC controllers inside Blazor client apps

### ISSUE THREAD

**Issue by majorimi** [dotnet/aspnetcore#5539]
Currently with Blazor 0.4 when you try to add a new Controller VS 2017 shows the dialog below:
![image](https://user-images.githubusercontent.com/7632824/41413153-8194b6d8-6fe2-11e8-98f6-5928dada073f.png)

However no mater what you choose it will hang VS for minutes, or indefinitely. So most of the times I have to kill the process. But it doesn't mater VS was able to finish the setup or not because you wont be able to build that project again... 

Severity	Code	Description	Project	File	Line	Suppression State
Error		rzc generate exited with code 1.	BlazorTest	C:\Users\imre\.nuget\packages\microsoft.aspnetcore.blazor.build\0.4.0\targets\RazorCompilation.targets	184

**Comment by mkArtakMSFT** [comment]
@vijayrkn it looks like this is still possible (Scaffolding a controller in a Blazor WebAssembly project).

![image](https://user-images.githubusercontent.com/34246760/138203060-2a990de9-8b99-49eb-82c6-120b5a76ef15.png)

I assume this is something you control and can fix or should there be a change from our side to do this?

**Comment by mkArtakMSFT** [comment]
@vijayrkn do you have a tracking issue for this already. Should I close this now?

**Comment by mkArtakMSFT** [comment]
@vijayrkn do you have at tracking issue for this or should @majorimi report this through [VS Feedback](https://docs.microsoft.com/en-us/visualstudio/ide/feedback-options?view=vs-2019)  ?

**Comment by deepchoudhery** [comment]
@mkArtakMSFT Hey just saw this issue. Will get it in VS 17.1 Preview 3. Definitely would not qualify for a servicing fix for 17.0 at this point. Let's track it here and as soon its in, we can close it with a release going out early Jan.
