### ISSUE TITLE
add Flexible Authorisation to default templates

### ISSUE THREAD

**Issue by sardar97** [dotnet/aspnetcore#55413]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

are there any plan to add Flexible Authorisation to default templates to botnet 8 to 9 ?
to make it easier to change roles and permissions with UI.

### Describe the solution you'd like

are there any plan to add Flexible Authorisation to default templates to botnet 8 to 9 ?
to make it easier to change roles and permissions with UI.

**Comment by amcasey** [comment]
FYI @halter73

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. You can learn more about how to customize authorization from our guidance here: https://learn.microsoft.com/aspnet/core/security/authorization/roles?view=aspnetcore-8.0 and https://learn.microsoft.com/aspnet/core/security/authorization/policies?view=aspnetcore-8.0
