### ISSUE TITLE
Minify and bundle isolated css files and js scripts in Blazor Server Self Contained when publisihing : <projectname>.css file.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#55428]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Minify-and-bundle-isolated-css-files-and/10497889)._

---
I find that the isolated css files are merged into one file <projectName>.css when published to a file as self contained project (x64 IIS). This file is not minified or bundled with all other css files referenced. It would be great if there was an easy way to do this perhaps by selecting a checkbox from publishing options so that you get a clean project with two files for all css and js code - minified for performance. This was possible with .net Framework with “bundle” files. .

---
#### Feedback Bot on 10/23/2023, 06:35 PM: 

(private comment, text removed)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
While this may be a great idea, it is not aligned with our long-term vision to make it part of the framework. For many other ideas which don't belong to the framework we encourage the community to build and ship on their own, contributing to the expanding .NET Ecosystem.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
