### ISSUE TITLE
VS 2022 Preview should recognize changes to *.js files in Blazor component library

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#55429]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS-2022-Preview-should-recognize-changes/1487134)._

---
I don't know if this is a bug, but if not I would like to suggest it as a feature.
I created a new Blazor wasm project and added a Blazor component library to the solution. When I make/save changes to the *.js files in the component library VS does not include the component in a build. I either have to clean the solution or specifically select 'Rebuild All'.
I would prefer that VS include *.js changes as requiring a build for that project.

---
#### Feedback Bot on 7/26/2021, 06:57 PM: 

(private comment, text removed)

**Comment by danroth27** [comment]
I tried out taking a default Blazor Web App, adding an RCL, wiring up the `ExampleJsInterop` class as a scoped service that gets invoked from a button click, and then changing the JavaScript file in the RCL and refreshing the page. The change were picked up, so the basic scenario seems to work fine. We need more detailed steps on how to reproduce this issue.
