### ISSUE TITLE
Route Recognition of method with input type

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#55431]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Route-Recognition-of-method-with-input-t/10536952)._

---
Hi,

I'm working on ASP.NET application and have encountered a situation where the API has a method needs a overloading with various input types. For example, the inputs could be int, string etc., types.

Please give attention to the community thread from [this link](https://techcommunity.microsoft.com/t5/web-development/mvc-controller-method-overloading/m-p/3992318) to understand better. 

Community folks have provided some work around techniques, but, wondering whether this can be considered into the route engine or not!!

Thanks for reading.
Regards,

---
#### Feedback Bot on 12/8/2023, 00:20 AM: 

(private comment, text removed)

**Comment by amcasey** [comment]
The question appears to be about ASP.NET Classic (on framework 4.5).

**Comment by captainsafia** [comment]
I took a look at the question here. It looks like the user is interested in knowing if it is possible for the routing layer to disambiguate between the same overload and different type signatures:

```csharp
public ActionResult GetSomeData(int inputValue) { } 
public ActionResult GetSomeData(string inputString) { }
```

Assuming that `inputValue` is meant to be bound from the route in both cases, it should be possible to do so by taking advantage of route constraints:

```csharp
[Route("/GetSomeData/{inputValue:int}")]
public ActionResult GetSomeData(int inputValue) { } 
[Route("/GetSomeData/{inputValue:string}")]
public ActionResult GetSomeData(string inputString) { }
```

Assuming that is insufficient, I hesitate to consider changes that we could make to the routing engine (given its complexity) to achieve similar behavior without route constraints.
