### ISSUE TITLE
Run the .NET WebAssembly runtime in release mode in published Blazor apps

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#55438]
There are optimizations in the .NET WebAssembly runtime that are only used when the runtime is running release mode. We suspect that Blazor is still running the .NET WebAssembly runtime in debug mode, which may explain why some of the startup performance optimizations aren't showing up.

@lewing @kg

**Comment by kg** [comment]
In my testing, Release builds (non-published) run the interpreter in debug mode, which does increase startup overhead. I'm not sure about publish, because right now my published builds are crashing during jsexport startup.

**Comment by mkArtakMSFT** [comment]
@MackinnonBuck parking this on your plate to follow up and understand what may be causing this.

**Comment by mkArtakMSFT** [comment]
@lewing it seems that all this is now controlled by the runtime and we just pass parameters to the runtime during Blazor startup. If there are specific flags to set, etc. we can verify if they are being set or not. Other than that, it's not clear how we can address this.

**Comment by lewing** [comment]
@maraf knows the details here

**Comment by halter73** [comment]
We also don't know how to detect whether the WebAssembly runtime is in debug or release mode. What's the easiest way?

**Comment by maraf** [comment]
- Any "build" (Debug, Release or any user defined) by default results in "debugging enabled", disabling interpreter optimizations etc.
- Any "publish" results in "debugging disabled", enabling interpreter optimizations etc.
- This default behavior can be overriden by `WasmDebugLevel=0` (disable debugging) or `WasmDebugLevel=-1/1` (enable debugging).

More details in https://github.com/dotnet/runtime/issues/96239#issuecomment-1889210205

> We also don't know how to detect whether the WebAssembly runtime is in debug or release mode. What's the easiest way?

The actual value on runtime can be obtained by `getConfig().debugLevel`, in Blazor by `Blazor.runtime.getConfig().debugLevel`

**Comment by danroth27** [comment]
I created a Blazor Web App with WebAssembly interactivity enabled globally and then published the app. It looks like debugging is disabled:

![image](https://github.com/dotnet/aspnetcore/assets/1874516/8b6bbbe1-d658-4b81-bd7c-dfd286c186dd)
