### ISSUE TITLE
.NET 8 stable version of Microsoft.AspNetCore.ApiAuthorization.IdentityServer

### ISSUE THREAD

**Issue by the-gabe** [dotnet/aspnetcore#55456]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

It doesn't exist yet per https://www.nuget.org/packages/Microsoft.AspNetCore.ApiAuthorization.IdentityServer

### Expected Behavior

A stable .NET 8 version of this.

**Comment by martincostello** [comment]
Was removed in #46131 and is no longer published, which is why there's no versions beyond preview.6 of .NET 8.

**Comment by paviad** [comment]
Updated `Microsoft.AspNetCore.ApiAuthorization.IdentityServer` to support `IdentityServer` version 7 here:

https://github.com/paviad/apiauthorization-identityserver
