### ISSUE TITLE
Signalr hubconnection new parameter .WithStatefulReconnect

### ISSUE THREAD

**Issue by troubleshootdoc** [dotnet/aspnetcore#55473]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a blazor wasm (client model) only. We want to use SignalR serverless and Azure function as the Hub. If we want to use the .WithStatefulReconnect , can we do it using a blazor wasm client only application if our hub is an azure function? Is there something I would have to change in the signalr service (in serverless mode)

The blazor client would use this instead of WithAutomaticReconnect().
hubConnection = new HubConnectionBuilder()
.WithUrl(functionAppBaseUri, options =>
{
}).WithStatefulReconnect().Build();
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/32493

### Expected Behavior

I'm just asking if in my specific case if there we use the new feature do i need to change something in the Signalr Service (serverless) or in the azure function that is the Hub.

### .NET Version

.net 8

**Comment by BrennanConroy** [comment]
Doesn't look like it's supported yet.
https://github.com/Azure/azure-signalr/issues/1878

**Comment by guardrex** [comment]
Thanks @BrennanConroy ... I'll add a NOTE with a tracking item to keep an eye on that issue to remove the NOTE later.
