### ISSUE TITLE
IDictionary does not inherit from IReadOnlyDictionary

### ISSUE THREAD

**Issue by wdnijdam** [dotnet/aspnetcore#55487]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

IDictionary is declared as 

```
  public interface IDictionary<TKey, TValue> : 
    ICollection<KeyValuePair<TKey, TValue>>,
    IEnumerable<KeyValuePair<TKey, TValue>>,
    IEnumerable
```

The extension GetValueOrDefault() does not work on IDictionary because it is defined on IReadOnlyDictionary

### Expected Behavior

IDictionary should implement interface IReadOnlyDictionary as well

### Steps To Reproduce

Declare local variable of type IDictionary

Invoke var.GetValueOrDefault()

It cannot be resolved

### .NET Version

8.0.4

**Comment by campersau** [comment]
See https://github.com/dotnet/runtime/issues/31001

**Comment by martincostello** [comment]
See https://github.com/dotnet/runtime/pull/101469.

**Comment by mkArtakMSFT** [comment]
Thanks @martincostello!
