### ISSUE TITLE
After deleting a class member from the. net core and hot reloading, it is still possible to obtain this class member through reflection

### ISSUE THREAD

**Issue by 2535688890** [dotnet/aspnetcore#55486]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After deleting a class member from the. net core and hot reloading, it is still possible to obtain this class member through reflection

### Expected Behavior

I hope to delete a class member. After hot overloading, it can be completely overloaded, and reflection cannot obtain the deleted class member

### Steps To Reproduce

![E9$6J(CT1 P`~(K)0@~6G{6](https://github.com/dotnet/aspnetcore/assets/46720646/78e83ce6-bc85-4efd-800f-a5aaf7c98b54)
![ACTOHFFF(8~CB82B{VE5{{J](https://github.com/dotnet/aspnetcore/assets/46720646/0549f2b9-df38-4761-867b-1d49b180857a)
![O}W Y@HHPQQ{T8)C876T2TH](https://github.com/dotnet/aspnetcore/assets/46720646/4c7c20e2-201b-4004-815d-2ea7974a728e)

Modify class, hot overload

![1@$G8BMDWTCSR{X_Y75N%RB](https://github.com/dotnet/aspnetcore/assets/46720646/b1c2fad0-023c-4dca-bf6b-46379a0cdcce)
![D(BX)HS( )G(UL{23R IHY](https://github.com/dotnet/aspnetcore/assets/46720646/f2a36dd3-889b-4913-bc7e-2495f6b516d2)

### .NET Version

8.0.204

### Anything else?

.NET SDK:
 Version:           8.0.204
 Commit:            c338c7548c
 Workload version:  8.0.200-manifests.7d36c14f

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.204\

已安装 .NET 工作负载:
没有要显示的已安装工作负载。

Host:
  Version:      8.0.4
  Architecture: x64
  Commit:       2d7eea2529

.NET SDKs installed:
  6.0.421 [C:\Program Files\dotnet\sdk]
  8.0.204 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.29 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.29 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by mkArtakMSFT** [comment]
@tmat can you help with this one?

**Comment by tmat** [comment]
Dup of https://github.com/dotnet/runtime/issues/75154. Please vote on this issue.
