### ISSUE TITLE
In RazorCompiler, coalesce adjacent markup blocks

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#5549]
Follow up on #1146

**Comment by rynowak** [comment]
@SteveSandersonMS - this is done right?

**Comment by SteveSandersonMS** [comment]
I'm not aware that it is. I thought this was filed as a follow-up from the original enhancement that introduced markup blocks, in that we recognized there are cases where it doesn't coalesce markup that could be coalesced.

Isn't each markup blocks a top-level element, so top-level siblings aren't coalesced? Or maybe there were opportunities to coalesce elements with adjacent sibling text nodes.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
