### ISSUE TITLE
Generics in event handler tool tips aren't showing up correctly

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#5551]
![image](https://user-images.githubusercontent.com/174281/43171299-472ef918-8f5e-11e8-9567-c802d7dbc1f1.png)

My guess is that it's supposed to say 

> Sets the 'onclick' attribute to the provided string or delegate value. A delegate value should be of type `'System.Action<Microsoft.AspNetCore.Blazor.UIMouseEventArgs>'`

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
