### ISSUE TITLE
Checkbox input tag helper throws FormatException: 1 is not a valid value for Boolean

### ISSUE THREAD

**Issue by advdotnet** [dotnet/aspnetcore#55512]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

From time to time, I see a "FormatException: 1 is not a valid value for Boolean exception" in the logs of a public MVC website which occurs when submitting the login form. 
The login form contains a checkbox rendered with the input tag helper.
The problem does not occur when a user operates the login form, so I suspect bots are tampering with the form data.
I can reproduce the exception by setting the checkbox input value to "1", checking the checkbox ("Prepare" button in the repro) and submitting the form ("Submit" button).

### Expected Behavior

The view renders instead of throwing an exception and the validation message The value '1' is not valid for [bool property] could be shown.

### Steps To Reproduce

https://github.com/advdotnet/GenerateCheckboxSample/blob/master/Views/Home/Index.cshtml

### Exceptions (if any)

System.FormatException: String '1' was not recognized as a valid Boolean.
   at System.ComponentModel.BooleanConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
   at System.ComponentModel.BooleanConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ModelBindingHelper.ConvertSimpleType(Object value, Type destinationType, CultureInfo culture)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.DefaultHtmlGenerator.GetModelStateValue(ViewContext viewContext, String key, Type destinationType)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.DefaultHtmlGenerator.GenerateInput(ViewContext viewContext, InputType inputType, ModelExplorer modelExplorer, String expression, Object value, Boolean useViewData, Boolean isChecked, Boolean setId, Boolean isExplicitValue, String format, IDictionary`2 htmlAttributes)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.DefaultHtmlGenerator.GenerateCheckBox(ViewContext viewContext, ModelExplorer modelExplorer, String expression, Nullable`1 isChecked, Object htmlAttributes)
   at Microsoft.AspNetCore.Mvc.TagHelpers.InputTagHelper.GenerateCheckBox(ModelExplorer modelExplorer, TagHelperOutput output, IDictionary`2 htmlAttributes)
   at Microsoft.AspNetCore.Mvc.TagHelpers.InputTagHelper.Process(TagHelperContext context, TagHelperOutput output)
   at Microsoft.AspNetCore.Razor.TagHelpers.TagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output)
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.RunAsync(TagHelperExecutionContext executionContext)
   at AspNetCoreGeneratedDocument.Areas_Main_Views_Account_Login.<ExecuteAsync>b__20_1() in [...]

### .NET Version

8.0.200

### Anything else?

.NET SDK:
 Version:           8.0.200
 Commit:            438cab6a9d
 Workload version:  8.0.200-manifests.e575128c

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.200\

Host:
  Version:      8.0.2
  Architecture: x64
  Commit:       1381d5ebd2

.NET SDKs installed:
  8.0.200 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.27 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by mkArtakMSFT** [comment]
The exception you're experiencing is by design. The field type of `boolean` expects only ` true` or `false` as values. Anything else will result in an exception.

**Comment by davidliang2008** [comment]
I am in .NET 6 and having the same issue. I have a Remember me? checkbox on the log in page, using tag helper:

```razor
@model LoginViewModel

<form asp-area="" asp-controller="account" asp-action="login">
    ...
    <div class="form-check">
        <input class="form-check-input" asp-for="RememberMe" />
        <label class="form-check-label" asp-for="RememberMe"></label>
    </div>
    <button class="btn btn-primary w-100" type="submit">Log in</button>
</form>
```

@mkArtakMSFT: you said it's by design? Then by design, how would I build a checkbox using tag helper so that I am not getting this exception?

**Comment by SKarwasra** [comment]
To reproduce this behaviour, you need to use the "Save Password" feature provided by the browsers.
If you press the submit button on Login form then InputModel is validated and works correct, but with using Saved Credentials you choose the user name from saved and browser do not give you a chance to press the submit button but do post back directly.
The login request generated by the browser contains the wrong data type.

**Comment by davidliang2008** [comment]
@SKarwasra that's not 100% correct though, at least from my use case.

I have a login form built using MVC, and the "Remember me" checkbox is default to be `true` (checked). Even I use my user name and password from the saved storage of the browser (latest Google Chrome), I still have to click the submit button (instead of post back directly). And I still get the error message in the log.

**Comment by advdotnet** [comment]
I ended up not using the checkbox input tag helper to be able to focus on more important exceptions in the log. It's a pity that this behavior is by design.

**Comment by PaliGoga** [comment]
I had the same problem. I solved it in `Login.cshtml.cs.OnPostAsync` by checking if `ModelState["Input.RememberMe"]` has any errors. If it does, that most probably means somebody is tampering with the form, therefore I show him `400 Bad Request` page. 

Another option might be to manually change submitted value to true/false.

`Login.cshtml.cs`
```
public async Task<IActionResult> OnPostAsync(string returnUrl = null)
{
    ...
    if (ModelState["Input.RememberMe"].Errors.Count > 0)
    {
        // Option 1
        return BadRequest();

        // Option 2
        ModelState["Input.RememberMe"].AttemptedValue = "false"; // Or "true";
    }
    ...
}
```

It does not "feel right" to solve it this way, but it does the job 🙈.
