### ISSUE TITLE
[Server side] Doing a blocking call on IJSRuntime.InvokeAsync ends up locking the server

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#5553]
Super nitpicky, but doing a .`Result` or '`Wait` on the task returned by `IJSRuntime` locks up the server. E.g. 

```C#
void DoLog()
{
    JSRuntime.Current.InvokeAsync<string>("console.log", "Hello world").Wait();
}
```

The server does not respond to any further actions.

**Comment by kjeske** [comment]
Is there any chance that the fix will be included in preview6 or preview7?

**Comment by cpsaez-Lendsum** [comment]
This bug is still present rigth?

I've found this thread using LocalStorage from BlazorExtensions.Storage. 

Just for the records, this experiment:

`async void IncrementCount()
    {
        var result = 0;
        var t = Task.Run(async () => { result = await localStorage.GetItem<int>("counter"); }).ConfigureAwait(false);
        while (!t.GetAwaiter().IsCompleted)
        {
            Task.Delay(100);
        }
        return result;`

IsCompleted is always false so this never ends

**Comment by cosXsinX** [comment]
Actually to understand what happen when trying to launch a task on Blazor you should understand JavaScript execution lifecycle. 

To sum up, any task in a JavaScript environment in the context of the browser (Safari, Chrome , Edge, ...) cannot be executed when the current task is running. That means you are dead locking when trying to wait the initiated task by JSRuntime.InvokeAsync<...>(“functionName”,...).AsTask().Wait() in a “synchronous” Blazor function.

The solution is to always perform those task calls in an async containing function and call StateIsChanged() function to say to the browser that the model was updated and that it should refresh the DOM

**Comment by pranavkm** [comment]
The recommendation here is to not perform blocking calls. It's fairly likely the work that was suggested in https://github.com/dotnet/aspnetcore/issues/5553#issuecomment-437714763 has been addressed since JSInterop uses a separate hub method to invoke. In Wasm, you get a nice error if you perform a blocking call. Closing this, as there isn't any further action to take here.
