### ISSUE TITLE
Blazor SSR client validation on browser before EditForm submitting

### ISSUE THREAD

**Issue by mammadkoma** [dotnet/aspnetcore#55541]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Hello, we need Blazor SSR client validation on browser.

### Describe the solution you'd like

When the EditForm submit client validations don't fire locally on browser and it send a request to the server for validation. How to validate EditForm fields validations like [Required] on client browser like MVC Unobtrusive JavaScript?

**Comment by mammadkoma** [comment]
![image](https://github.com/dotnet/aspnetcore/assets/17564001/92d56e50-2f1c-404a-bf51-60966df6f2aa)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is something we already track as part of https://github.com/dotnet/aspnetcore/issues/51040
