### ISSUE TITLE
Enable HTTPS in all blazor templates

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#5554]

**Comment by javiercn** [comment]
Agree. We might tackle this as part of the design for static content in RCLs

**Comment by datvm** [comment]
Can you please tell how to manually launch HTTPS now or is it simply impossible? I went to `launchSettings.json` and change `sslPort` from 0 to another number, but accessing results in ERR_CONNECTION_RESET.

Thanks.

**Comment by danroth27** [comment]
If your client-side Blazor app is hosted in ASP.NET Core then you can just go into the project properties of the .Server project, select the Debug tab, and then check the "Enable SSL" checkbox:

![image](https://user-images.githubusercontent.com/1874516/58579499-15de1e80-8200-11e9-8ba0-e8260f8de6ad.png)

**Comment by datvm** [comment]
Thanks it works. I wonder why. Does VS do something else beside setting `sslPort` in `launchSettings.json` because that's the only difference I see?

> If your client-side Blazor app is hosted in ASP.NET Core

Side question: does that imply Blazor can actually be hosted somewhere/somehow else?

**Comment by danroth27** [comment]
> Does VS do something else beside setting sslPort in launchSettings.json because that's the only difference I see?

I believe VS also modifies the applicationhost.config file to setup IIS Express to support HTTPS.

> Side question: does that imply Blazor can actually be hosted somewhere/somehow else?

Sure, client-side Blazor apps are really just a bunch of static files that can be hosted [stand-alone](https://docs.microsoft.com/aspnet/core/host-and-deploy/blazor/client-side#standalone-deployment) using any static site hosting solution. You don't need .NET on the server at all. For example, you could host your app on GitHub pages or an Azure Static Site Hosting. @jeffhollan did a nice talk at the recent [BUILD conference talk](https://mybuild.techcommunity.microsoft.com/sessions/77336) on the later.

**Comment by javiercn** [comment]
@mkArtakMSFT @danroth27 Given the current priority for this item I marked it as help wanted. It should be easy I think to enable this on the templates:

This PR contains all the info needed I think, so its a matter of applying it to the hosted server-side template, and to the dev-server for client apps

https://github.com/aspnet/Templating/commit/aca30fe8a241d51be07fc941869288c59c66384a#diff-b5fa223ecb69cfdfc0b9caf4601c9358

**Comment by javiercn** [comment]
@mkArtakMSFT @danroth27 Moving this out of preview8 into 3.1

**Comment by mkArtakMSFT** [comment]
@javiercn isn't this done already?

**Comment by javiercn** [comment]
@mkArtakMSFT Nope, but this should be trivial. If @SteveSandersonMS was looking for cheap stuff, this is a candidate.

**Comment by SteveSandersonMS** [comment]
I agree this should be cheap, plus I think we'll get told it's mandatory when we go through Blazor WebAssembly security review.

**Comment by javiercn** [comment]
This is done as part of my template changes.
