### ISSUE TITLE
Project that uses Microsoft.NET.Sdk.Web copies packages.lock.json to output

### ISSUE THREAD

**Issue by flcdrg** [dotnet/aspnetcore#55568]
### Is there an existing issue for this?

- [X] #56595

### Describe the bug

Given an ASP.NET web project where the csproj has `Sdk="Microsoft.NET.Sdk.Web"`, then if that project uses a NuGet lockfile, then the lockfile is also copied to the output directory when the project is built.

### Expected Behavior

`packages.lock.json` should not be copied to the output directory.

It isn't copied to the output directory for projects that use Microsoft.NET.Sdk

This may have the potential to confuse build pipeline caching tasks as they often use wildcards to locate packages.lock.json across a solution, and this bug causes extra files to match. eg. the Azure Pipelines cache task considers this a 'cache miss' as the extra packages.lock.json files are noticed after the build has completed.

### Steps To Reproduce

1. `dotnet new web`
2. `dotnet build /p:RestorePackagesWithLockFile=True`

Note that `packages.lock.json` is now present in the bin/Debug/net8.0 output directory

### .NET Version

8.0.202

**Comment by flcdrg** [comment]
A temporary workaround is to add this to the .csproj file:

```xml
<Content Remove="packages.lock.json" />
```

**Comment by wtgodbe** [comment]
@javiercn is this something that StaticWebAssets controls, or should we ping Vijay?

**Comment by mkArtakMSFT** [comment]
Ping @javiercn

**Comment by javiercn** [comment]
@mkArtakMSFT @wtgodbe this isn't us, as the packages.lock.json is not inside the `wwwroot` folder.

It can either be console (in which case there's a fix needed in the base .NET SDK) or some Web specific behavior, in which case Vijay is likely the right person to ping.

@flcdrg does this happen on a regular console app?

**Comment by javiercn** [comment]
The fix is likely https://github.com/dotnet/sdk/blob/f6c64dcc881dbda28db6747d83ab061c8713582d/src/StaticWebAssetsSdk/Sdk/Sdk.StaticWebAssets.StaticAssets.ProjectSystem.props#L4 (This is shared between the Web SDK and us because of layering)

**Comment by mkArtakMSFT** [comment]
@javiercn do you mean this is already fixed by a change that you've done?
