### ISSUE TITLE
How to get access token in Blazor server with Azure B2C

### ISSUE THREAD

**Issue by setin1219** [dotnet/aspnetcore#55578]
Hi All,

I have been working for like few days on trying to figure out a way to fetch the access token in blazor server application, but so far it didnt worked out.

this is what i have in program.cs
.....
builder.Services.AddMicrosoftIdentityWebAppAuthentication(builder.Configuration, Constants.AzureAdB2C);
builder.Services.AddInMemoryTokenCaches();
.....

also when i try to fetch the token using ITokenAcquisition in razor page, i see another error although user is already signed in:

MSAL.NetCore.4.60.3.0.MsalUiRequiredException:
	ErrorCode: user_null
Microsoft.Identity.Client.MsalUiRequiredException: No account or login hint was passed to the AcquireTokenSilent call. 

also another problem is that i have to pass the scope for, my enterprise portal which i couldn't figure how to do in Blazor server, although below code i can see for Blazor WASM:

builder.Services.AddMsalAuthentication(options =>
 {     builder.Configuration.Bind("AzureAdB2C", 
options.ProviderOptions.Authentication);  
   options.ProviderOptions.DefaultAccessTokenScopes.Add("enterpriseportalscopeurl");    
 options.ProviderOptions.LoginMode = "redirect"; });

It will be a great help if anyone already solved this problem.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Please follow the guidance we have for this here: https://learn.microsoft.com/en-us/aspnet/core/blazor/security/blazor-web-app-with-oidc?view=aspnetcore-8.0

**Comment by setin1219** [comment]
@mkArtakMSFT thank you for the reply, I have check this url earlier, one doubt I thought had, how can I pass my enterprise portal scope to this.
The access token which is fetched from b2c is missing 'scp' scope. I got to know from enterprise portal team that we need to pass this scope while acquiring token.
