### ISSUE TITLE
close connection after HEAD handler executed

### ISSUE THREAD

**Issue by kasperk81** [dotnet/aspnetcore#55598]
```sh
$ dotnet new webapiaot

# insert a HEAD mapping
$ sed -i 's|todosApi.MapGet("/".*|&\ntodosApi.MapMethods("/", ["HEAD"], context => Task.CompletedTask);|' Program.cs
# on mac: sed -i '' 's|todos...

$ dotnet run
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5000
..

$ curl -X HEAD -v http://localhost:5000/todos
..
no chunk, no close, no size. Assume close to signal end
# and it hangs
```

we can use `-I, --head` (fetch only header) option like `curl -I http://localhost:5000/todos` to get the expected result, but the server should just close the connection when HEAD has been executed.

**Comment by Tratcher** [comment]
This is per spec, HEAD requests do not produce a response body, nor should they close the connection. Using the `--head` option is the correct client usage.

**Comment by amcasey** [comment]
curl's manpage reports

> This option only changes the actual word used in the HTTP request, it does not alter the way curl behaves. For example if you want to make a proper HEAD request, using -X HEAD does not suffice. You need to use the [-I, --head](https://curl.se/docs/manpage.html#-I) option.
