### ISSUE TITLE
Blazor bypasses running client Program.cs and client side DI fails

### ISSUE THREAD

**Issue by sam-wheat** [dotnet/aspnetcore#55648]
The attached app is a default Blazor template for an app with authentication.

I have made the following changes:

Server Project

App.razor:
	
	private IComponentRenderMode? RenderModeForPage => HttpContext.Request.Path.StartsWithSegments("/Account")
		   ? null
		   : new InteractiveWebAssemblyRenderMode(prerender: false);	
	   

Client project

Added a class called `MyObject`. 
Registered a `MyObject` singleton in `Program.cs`.  
Added a control called `Shared/LoginStatusControl.razor`.  
Inject `MyObject` in `Home.razor` and `LoginStatusControl`.
Add `LoginStatusControl` to `MainLayout`.
Add `@attribute [Authorize]` to `Home.razor`.

Problem:  

In the configuration described it appears that Blazor bypasses running Program.cs.  This causes `MyObject` to not be registered as a singleton and ultimately results in this error:

> Cannot provide a value for property 'myObject' on type 'BlazorAuthExample2.Client.Shared.LoginStatusControl'. There is no registered service of type 'BlazorAuthExample2.Client.MyObject'.

Removing `@attribute [Authorize]` from `Home.razor` appears to mitigate this issue however in my production app, all pages including "/" need to direct the user to login if they have not done so.

Also, I need to use `new InteractiveWebAssemblyRenderMode(prerender: false)` because I have some controls that render modals and they do not render correctly if I don't use that render mode.

Question:  
How can I protect all pages with `@attribute [Authorize]` and still have my client side DI work?

[BlazorAuthExample2.zip](https://github.com/dotnet/aspnetcore/files/15266819/BlazorAuthExample2.zip)

**Comment by javiercn** [comment]
@sam-wheat thanks for contacting us.

If you are using web assembly, you need to register your object in both environments.

**Comment by sam-wheat** [comment]
@javiercn  as a singleton in both environments?

**Comment by javiercn** [comment]
@sam-wheat You'll have an instance on the server and an instance on the client.

You have two processes, one running server-side and one running client-side. They are completely independent and don't automatically share any kind of state.
