### ISSUE TITLE
Buffering issues when returning an SSE response

### ISSUE THREAD

**Issue by kikaragyozov** [dotnet/aspnetcore#55654]
In the controller I'm basically returning a server-sent event by manually setting the content type, starting the response with `Response.StartAsync(cancellationToken)` and then directly writing data to `Response.Body`, finishing with a `Response.CompleteAsync()`. For additional context - another service is returning the SSE in a `Stream`, so I'm effectively just calling `Stream.CopyToAsync(Response.Body, cancellationToken)`

The issue I'm facing is that when the above code runs on Kestrel, the events in the stream are immediately returned and it seems like no buffering is being done.

The moment I switch to IIS or IIS Express though, something weird is going on as the client receives the response after writing to the response body has finished.

After investigating, I thought the Dynamic Response Caching module for IIS was at fault here. But it turns out that it was actually **not installed** on the system as shown here:
![image](https://github.com/microsoft/reverse-proxy/assets/6695731/a8cf4024-be01-4722-bb15-97ad91e18f11)

If Dynamic Response Caching is not involved, what else is going on that would screw up the SSE like that? If I have to follow common sense, does the above mean that:

1. By default, Kestrel is configured to NOT buffer the response body. (How do you control this?)
2. By default, IIS is configured to buffer the response body. (How do you control this?)

I find it weird that Kestrel would have no response body buffering by default. Is this really the case? If not, what's going on here? Am I perhaps implementing SSE in a weird way?

Calling `HttpContext!.Features.Get<IHttpResponseBodyFeature>()!.DisableBuffering()` fixes the issue when running under IIS/IIS Express.

.NET Version: 8.0.300-preview.24203.14

**Comment by Tratcher** [comment]
> Calling `HttpContext!.Features.Get<IHttpResponseBodyFeature>()!.DisableBuffering()` fixes the issue when running under IIS/IIS Express.

That's expected, SignalR's SSE implementation has to do the same. Are you still having issues, or are you just trying to understand what component was causing the problem?

**Comment by kikaragyozov** [comment]
> > Calling `HttpContext!.Features.Get<IHttpResponseBodyFeature>()!.DisableBuffering()` fixes the issue when running under IIS/IIS Express.
> 
> That's expected, SignalR's SSE implementation has to do the same. Are you still having issues, or are you just trying to understand what component was causing the problem?

I'm just trying to understand how things work under the hood, especially when switching between Kestrel and IIS. It **seems** that when running under Kestrel, there's no buffering involved? At least the SSE stream is being returned at chunks, unlike in IIS where everything's returned at once.

**Comment by davidfowl** [comment]
Here's the implementation for IIS:

https://github.com/dotnet/aspnetcore/blob/3307bf66ac87308d157ce9f9fa10bb56c1ebf602/src/Servers/IIS/IIS/src/Core/IISHttpContext.FeatureCollection.cs#L498-L508

Which calls https://learn.microsoft.com/en-us/iis/web-development-reference/native-code-api-reference/ihttpresponse-disablebuffering-method

Kestrel we control the entire stack and there's not explicit buffering (there's a "write behind buffer", but it's flushed immediately).

**Comment by kikaragyozov** [comment]
> Here's the implementation for IIS:
> 
> https://github.com/dotnet/aspnetcore/blob/3307bf66ac87308d157ce9f9fa10bb56c1ebf602/src/Servers/IIS/IIS/src/Core/IISHttpContext.FeatureCollection.cs#L498-L508
> 
> Which calls https://learn.microsoft.com/en-us/iis/web-development-reference/native-code-api-reference/ihttpresponse-disablebuffering-method
> 
> Kestrel we control the entire stack and there's not explicit buffering (there's a "write behind buffer", but it's flushed immediately).

Thank you @davidfowl for the information! This is what I needed. Am I correct in understanding that IIS buffering cannot be disabled from IIS? Compression can be though?

And finally - can one control how exactly buffering is done in IIS, like tuning the buffer size for example?

In Kestrel, there's [KestrelServerLimits.MaxResponseBufferSize](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.server.kestrel.core.kestrelserverlimits.maxresponsebuffersize?view=aspnetcore-8.0) - How does that exactly come into the picture?

**Comment by davidfowl** [comment]
> Thank you @davidfowl for the information! This is what I needed. Am I correct in understanding that IIS buffering cannot be disabled from IIS? Compression can be though?

That's right. AFAIK you have to call this API.

> In Kestrel, there's [KestrelServerLimits.MaxResponseBufferSize](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.server.kestrel.core.kestrelserverlimits.maxresponsebuffersize?view=aspnetcore-8.0) - How does that come into the picture?

It doesn't. This is about internal buffer sizes, not the operation of buffering content.

**Comment by kikaragyozov** [comment]
Closing this as I got what I was looking for. Thanks for the clarifications!

If anyone wouldn't mind sharing internally how IIS response buffering works, that'd be cool 👍
