### ISSUE TITLE
Project created by dotnet new blazor -int WebAssembly -ai cannot be deployed to a static web site

### ISSUE THREAD

**Issue by leungkimming** [dotnet/aspnetcore#55658]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In .net 7, I can create 2 projects with dotnet blazorwasm --hosted and deploy the Client project to a static web site. My usage is to load this Client project into a MAUI WebView and the Client will call a specifc API server to do business.

In .net 8, I created 2 projects with dotnet new blazor -int WebAssembly -ai but there is no way to deploy the Client to a static web site to be loaded into MAUI WebView.

### Expected Behavior

Same as previous blazorwasm --hosted,  project created with dotnet new blazor -int WebAssembly -ai should be able to deploy to static web site.

### Steps To Reproduce

1. dotnet new blazor -int WebAssembly -ai 
2. Open in VS and publish to a folder
3. Copy the folder to a static web site

### Exceptions (if any)

The static web site failed to load

### .NET Version

.net 8

**Comment by javiercn** [comment]
@leungkimming thanks for contacting us.

You need to create a standalone web assembly project and add a reference to it to an asp.net core server project. The default Blazor Web template with webassembly interactivity is configured to render the root document from a razor component and is not suitable for deploying into a static site.

**Comment by leungkimming** [comment]
I shall be most grateful if you can give us back the "dotnet blazorwasm --hosted" template in .net 8. I have developed a MAUI container App with SSO MASL authentication and uses a Web View to load many blazorwasm Apps from a static site without authentication (MASL token authentication is not supported when loading from Web View). The MAUI container will pass the MASL token to the balzor App when calling API.
