### ISSUE TITLE
NavigationException thrown in Static Server Render

### ISSUE THREAD

**Issue by mohiyo** [dotnet/aspnetcore#55685]
I have a Login Form inside a Blazor Server App which is working fine with built-in functionality. 
But now I am trying to solve a problem where I will be allowing Users to log in automatically when they reach from certain URL and with certain parameters, **Without submitting a form**

I tried this in my Login Component

```
protected override async Task OnInitializedAsync() {
  try {
    if (HttpMethods.IsGet(HttpContext.Request.Method))
      await HttpContext.SignOutAsync();

    if (parameter && condition) {
      await DirectLogin();
    }
  } catch (Exception ex) {
    _logger.LogError(message: ex.Message);
  }
}

async Task DirectLogin() {
  try {
  //Perform some logic here and then SignIn

    await HttpContext.SignInAsync(principal, new AuthenticationProperties {
      ExpiresUtc = DateTimeOffset.UtcNow.AddMinutes(5)
    });

    _navigation.NavigateTo($"/direct/page/{parameter}", true);
    //Here I get this exception "Microsoft.AspNetCore.Components.NavigationException"

  } catch (Exception ex) {
    errorMessage = $ "Error: {ex.Message}";
    _logger.LogError(message: ex.Message);
  }
}

```

This login Component is in a Static Server Render mode whereas after the successful SignIn, the User will be redirected to an Interactive Server Component. 

But Navigation is not working and I am getting this exception 

> Exception of type 'Microsoft.AspNetCore.Components.NavigationException' was thrown

_Originally posted by @mohiyo in https://github.com/dotnet/aspnetcore/issues/49472#issuecomment-2106780437_

**Comment by javiercn** [comment]
@mohiyo thanks for contacting us.

What's likely happening is that you are breaking on first chance exceptions. NavigationException is thrown by the framework to trigger an SSR navigation, but it's caught internally. 

**You should avoid capturing NavigationException.**

**Comment by mohiyo** [comment]
@javiercn  even if I don't capture the exception it still gives this error. Can you point out what's the real reason for this exception?

I never had Try/Catch block until I faced this exception, I want to get some sort of Inner Exception.

**Comment by sbwalker** [comment]
@mohiyo I believe this is the same issue as logged here: https://github.com/dotnet/aspnetcore/issues/53996

**Comment by HuaFangYun** [comment]
I would like to ask how to deal with this problem. At present, it is only reported as "Exception of type 'Microsoft.AspNetCore.Components.NavigationException' was thrown." There is no hint of anything else.

**Comment by bulsond** [comment]
![image](https://github.com/dotnet/aspnetcore/assets/2641410/8ba97447-5f75-450f-b89a-d560eba8ea92)

**Comment by mkArtakMSFT** [comment]
@halter73 isn't this something that will be addressed as part of [your PR](https://github.com/dotnet/aspnetcore/pull/58573)

**Comment by mkArtakMSFT** [comment]
Confirmed with @halter73 that the above linked PR is relevant, and it will improve the debugging experience.
Also, https://github.com/dotnet/aspnetcore/issues/53996 will allow us to not throw the exception in the first place.
