### ISSUE TITLE
UpgradeCode of .Net hosting bundle 8.0.0 installer does not work

### ISSUE THREAD

**Issue by naeddula** [dotnet/aspnetcore#55697]
We have a Wix installer to check prerequisites. We use UpgradeCode to check if specific version of hosting bundle is installed or not. For example, if 7.0.1 UpgradeCode is set and user has lower version installed, then during installation we display error indicating mandatory prerequisite software missing. In case he has 7.0.1 or higher, we don't show it. This functionality is not working with 8.0.0 UpgradeCode. If user has 8.0.1 already installed, it is indicating 8.0.0 or higher version is not installed.

**Comment by wtgodbe** [comment]
Thanks for the report - it sounds like you are relying on implementation details of the hosting bundle to determine some custom upgrade behavior. We don't provide those implementation details as API surface to depend on - I recommend installing the hosting bundle as-is & relying on the built-in upgrade behavior.
