### ISSUE TITLE
Render sequence seems to be incorrect

### ISSUE THREAD

**Issue by vrassouli** [dotnet/aspnetcore#55703]
While reviewing the source code for the EditForm, I noticed these two lines use the same sequence number 7.
Is this correct? sholdn't it be 7, 8, 9, ...?

https://github.com/dotnet/aspnetcore/blob/3307bf66ac87308d157ce9f9fa10bb56c1ebf602/src/Components/Web/src/Forms/EditForm.cs#L167
https://github.com/dotnet/aspnetcore/blob/3307bf66ac87308d157ce9f9fa10bb56c1ebf602/src/Components/Web/src/Forms/EditForm.cs#L168

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. The general rule of thumb is that you should use incremental numbers if you implement your own logic.
However, there are some "internal" nuances that we don't document which still make this code work correctly.
