### ISSUE TITLE
IStringLocalizer error: Input string was not in a correct format

### ISSUE THREAD

**Issue by yedajiang44** [dotnet/aspnetcore#55706]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Input string was not in a correct format. Failure to parse near offset 1. Expected an ASCII digit.

### Expected Behavior

format string

### Steps To Reproduce

1. create resx file
2. create key and value`{dateTime}: System is running.`
3. localizer.GetString("{dateTime}: System is running.", DateTimeOffset.Now)

If change dateTime to 0 with resx file and code, that is running well.
```
localizer.GetString("{0}: System is running.", DateTimeOffset.Now)
```

### .NET Version

8.0

**Comment by martincostello** [comment]
I think the issue here is you're using a named parameter, not an index.

Your string should be `{0}: System is running.`

**Comment by yedajiang44** [comment]
> I think the issue here is you're using a named parameter, not an index.
> 
> Your string should be `{0}: System is running.`

Yes, named parameter cannot be used? must be an index?

**Comment by martincostello** [comment]
I believe so, as ultimately `string.Format()` is used:

https://github.com/dotnet/aspnetcore/blob/3307bf66ac87308d157ce9f9fa10bb56c1ebf602/src/Localization/Localization/src/ResourceManagerStringLocalizer.cs#L119

**Comment by yedajiang44** [comment]
It's a pity! Is it possible to consider supporting named parameters?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
While this may be a great idea, it is not aligned with our long-term vision to make it part of the framework. For many other ideas which don't belong to the framework we encourage the community to build and ship on their own, contributing to the expanding .NET Ecosystem.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.

**Comment by yedajiang44** [comment]
got it. thanks reply!
