### ISSUE TITLE
Cannot supply a component of type 'Components.BookComponent' because the current platform does not support the render mode 'Microsoft.AspNetCore.Components.Web.InteractiveServerRenderMode'

### ISSUE THREAD

**Issue by MahdiElahi** [dotnet/aspnetcore#55728]
when i call component by this way i have this error

in TestComponent.razor i call BookComponent to get html
var sensorHtml = new ComponentRenderer<WeaponDetails>() .Render();

BookComponent.razor

@rendermode InteractiveServer
other codes......

but i have this error

Cannot supply a component of type 'Components.BookComponent' because the current platform does not support the render mode 'Microsoft.AspNetCore.Components.Web.InteractiveServerRenderMode'

**Comment by MackinnonBuck** [comment]
Are you using https://github.com/conficient/BlazorTemplater? If so, it might be worthwhile to file an issue over there.
