### ISSUE TITLE
UIKeyboardEventArgs.Code in Edge browser is always empty + problems with UIKeyboardEventArgs.Key

### ISSUE THREAD

**Issue by Andrzej-W** [dotnet/aspnetcore#5572]
```html
<div>
    <input onkeydown="@OnKeyDown" />
    <div>key: '@key'</div>
    <div>code: '@code'</div>
</div>
```
```c#
@functions{
    string key;
    string code;
    void OnKeyDown(UIKeyboardEventArgs eventArgs)
    {
        key = eventArgs.Key;
        code = eventArgs.Code;
    }
}
```
This code works in Firefox and Chrome but not in Edge.
On Windows 10 I have the following browsers:
* Firefox 61.0.1
* Chrome 68.0.3440.84
* Edge 16.16299

I have standard US layout keyboard and Windows with Polish language.
Edge does not return `Code` - we cannot distinguish between left and right shift/control/alt/menu start.

***Edge returns Unidentified*** in `key` for all braces, punctuation characters, etc. ,./<>?;':"[]\{}|-=_+ For all characters above numbers !@#$%^&*() it returns numbers, which is correct, but without `Code` it is hard to guess what key was pressed.

**Blazor 0.5.1**

**Comment by SteveSandersonMS** [comment]
Closing as no longer applicable. The supported version of Edge is based on Chromium so will now behave the same.
