### ISSUE TITLE
Outdated official docker images for ASP.NET Core runtime

### ISSUE THREAD

**Issue by barruka** [dotnet/aspnetcore#55727]
The official docker images for ASP.NET Core runtime at https://hub.docker.com/_/microsoft-dotnet-aspnet are outdated.

**Comment by martincostello** [comment]
All .NET container builds come from the [dotnet/dotnet-docker](https://github.com/dotnet/dotnet-docker) repository, which are published primarily to [Microsoft Artifact Registry](https://mcr.microsoft.com/catalog).

See [here](https://github.com/dotnet/dotnet-docker?tab=readme-ov-file#image-update-policy) for the policy on when container images are updated.

**Comment by barruka** [comment]
Ok but just browsing https://hub.docker.com/_/microsoft-dotnet, the first section "Featured Repos" links to [dotnet/aspnet](https://hub.docker.com/_/microsoft-dotnet-aspnet/): ASP.NET Core Runtime, where you can read:

"ASP.NET Core Runtime"
"By Microsoft"
"Official images for the ASP.NET Core runtime"

So, which team has the responsability of keeping this updated?

This repo is not fulfilling the images updated policy, because 8.0.4 was released a month ago and there a no 8.0.4 builds available.
