### ISSUE TITLE
Stop injecting "_framework/aspnetcore-browser-refresh.js" into the body of every generated web page of an asp.net core app.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#55734]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Stop-injecting-_frameworkaspnetcore-br/10655797)._

---
[severity:Other]
Please stop injecting this 

<script src="/_framework/aspnetcore-browser-refresh.js"></script>

into every one of the generated web pages while I am developing an asp.net core application.  

And yes, I've disabled all the Hot Reload features I know of.

Thank you, Paul.

And no, I am not providing any more information. This product has cost over 2000.00 in terms of man hours to battle configuration issues that seem to rear their ugly head on every update.

---
#### Feedback Bot on 5/9/2024, 03:38 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by daiplusplus** [comment]
See also: https://github.com/dotnet/aspnetcore/issues/45213

**Comment by MackinnonBuck** [comment]
@daiplusplus, could you please confirm whether you were able to disable injection of the `aspnetcore-browser-refresh.js` and `browserLink` scripts? Setting the `hotReloadEnabled` option in `launchSettings.json` to `false` should be all that's required.
