### ISSUE TITLE
Blazor-Hybrid with grpc Hot-Reload error.

### ISSUE THREAD

**Issue by a44281071** [dotnet/aspnetcore#55730]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We have 600 grpc *.proto files in project "RpcShared".
We use WPF-Blazor hybrid project "SamClient".
We load grpc datas in component OnInitAsync().

If we edit a component, and use hot-relaod, it have some error with '*.protodep' file.
like 'The file is being used by another process, so the process cannot access the file'.

### .NET Version

net8.0

### Anything else?

IDE: visual studio community 2022.

**Comment by MackinnonBuck** [comment]
@JamesNK Are you familiar with "protodep"? Do you know why this error might be occurring or if our own tooling could be the culprit here?

**Comment by a44281071** [comment]
Should I go to another place to ask questions?
Like 'grpc.net'?

**Comment by a44281071** [comment]
Sorry I can't post a project, It have 600 proto files. I can't create this test files.

**Comment by JamesNK** [comment]
I don't know what protodep is.

gRPC code generation is driven from `.proto` files and the `Grpc.Tools` NuGet package contains the `protoc` executable that is responsible for outputing generated C# code.

**Comment by MackinnonBuck** [comment]
Unfortunately, we're not able to investigate this further as it's not clear that this is a problem with ASP.NET Core. If you're using grpc.net, you could try filing an issue over there in case that's where the problem lies.
