### ISSUE TITLE
Add an InputRadio component

### ISSUE THREAD

**Issue by MarkStega** [dotnet/aspnetcore#5579]
I have the the following in my cshtml
````
    <td>
        <input type="radio" name="vacation" bind="@northwestVacation" /> Northwest @northwestVacation<br>
        <input type="radio" name="vacation" bind="@sinaiVacation" /> Sinai @sinaiVacation
    </td>
````
with corresponding properties `northwestVacation` and `sinaiVacation` in my code. During a debug session I see the `get` called numerous times for each but even with a `true` value the corresponding radio button is not in the selected state. And, as I select either button I never see the `set` called on either property.

**Comment by julienGrd** [comment]
Hello, what the current situation on this subject

I was using this kind of code until now, was worked in preview 3/4, but today i see it not work on preview 5, the checked is not render correctly, but the on change still working

```
<label class="form-check-label">
                      <input class="form-check-input" type="radio" name="rbSelectChildren" checked="@(Model.ShowAllDossiers == true)" onchange="@(() => Model.ShowAllDossiers = true)" /> 
Tous les dossiers
</label>

<label class="form-check-label">
                      <input class="form-check-input" type="radio" name="rbSelectChildren" checked="@(Model.ShowAllDossiers == false)" onchange="@(() => Model.ShowAllDossiers = false)" />
Uniquement les
</label>
```

**Comment by DanTsion** [comment]
Hello, same question to @SteveSandersonMS ...
Do you advance to the issue ?
Thanks

**Comment by robertmclaws** [comment]
Has this been figured out yet? Preview 9 (and therefore RTM) is eminent.

**Comment by SQL-MisterMagoo** [comment]
Radio buttons are not hard to work with in Blazor - I have a gist and Blazor Fiddle that demonstrates this here : https://gist.github.com/SQL-MisterMagoo/bc5713fb26bf84bf810d48d1f45c361a

**Comment by MarkStega** [comment]
Essentially a similar implementation but with an integer backing store:
```
            <tr>
                <th>
                    Saturday display:
                </th>
                <td align="left">
                    <input type="radio" name="group" checked="@(pGroupCode == 0)" @onchange="@(() => pGroupCode = 0)" /> Group with Friday<br />
                    <input type="radio" name="group" checked="@(pGroupCode == 1)" @onchange="@(() => pGroupCode = 1)" /> Group with Monday<br />
                    <input type="radio" name="group" checked="@(pGroupCode == 2)" @onchange="@(() => pGroupCode = 2)" /> Do not show
                </td>
            </tr>
```
and the code:
```
        protected int pGroupCode { get; set; }
```

**Comment by granicz** [comment]
In case anyone is interested, here is it for F# and [Bolero](https://fsbolero.io) (which implements a Model-View-Update programming model on top of Blazor): https://github.com/fsbolero/Bolero/issues/75

**Comment by RealHabix** [comment]
Solution with 2 components (RadioGroup & Radio): https://blazorfiddle.com/s/zwogor6l

**Comment by javiercn** [comment]
@SteveSandersonMS and I have chatted about this. We think that the current best solution for this is to do it manually instead of using bind, as there's more complexity involved and would likely require compiler changes.

 ```razor
@foreach (var choice in new[] { Choices.Red, Choices.Green, Choices.Blue })
{
    <label>
        <input name="yourColor" type="radio"
               value="@choice"
               checked="@(currentChoice == choice)"
               @onchange="@(() => { currentChoice = choice; })" />
        @choice.ToString()
    </label>
}

<p>You chose: @currentChoice</p>

@code {
    enum Choices { Red, Green, Blue };
    Choices currentChoice = Choices.Red;
}
```

**Comment by MarkStega** [comment]
That's exactly how I have my radio buttons implemented; It certainly works but isn't very 'pretty'. I'd still like to see bind working sometime in the future but it obviously isn't a showstopper.

**Comment by aaronhudon-ts** [comment]
> @SteveSandersonMS and I have chatted about this. We think that the current best solution for this is to do it manually instead of using bind, as there's more complexity involved and would likely require compiler changes.
> 
> ```
> @foreach (var choice in new[] { Choices.Red, Choices.Green, Choices.Blue })
> {
>    <label>
>        <input name="yourColor" type="radio"
>               value="@choice"
>               checked="@(currentChoice == choice)"
>               @onchange="@(() => { currentChoice = choice; })" />
>        @choice.ToString()
>    </label>
> }
> 
> <p>You chose: @currentChoice</p>
> 
> @code {
>    enum Choices { Red, Green, Blue };
>    Choices currentChoice = Choices.Red;
> }
> ```

@javiercn Thanks for posting this workaround - it would be nice if an area in the MSDN documentation could be created for things like this so we don't have to scour GitHub.

**Comment by aaronhudon-ts** [comment]
These solutions are still problematic if you are depending on the `EditContext` notifying you of a change through the `OnFieldChangedEvent` as it does not get fired.

**Comment by javiercn** [comment]
We don't have an InputRadio component itself that works with forms. 

This is something that could be built, but I suggest filing a separate issue to track it elsewhere instead of here.

**Comment by SteveHindmarsh** [comment]
Any news on this yet? I can't get Blazor  radio buttons to work with enums and the docs example given does not work?  https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-3.1

**Comment by chucker** [comment]
@SteveHindmarsh while binding directly may not work yet, writing a component that generates all the radio buttons from an enum isn't that hard.

**Comment by SteveHindmarsh** [comment]
Yes the Blazor paradigm makes things blisteringly simple once you start getting familiar however, if I hadn't wasted time with the incorrect documentation I may have now had exactly that. Anyhow it's allowed me to get familiar with EditContext.OnFieldChanged and the EditContext.NotifyFieldChanged event which has allowed me to program a solution. Blazor rocks!
