### ISSUE TITLE
.NET 8 Blazor - Cannot submit the form because no form on the page currently has that name.

### ISSUE THREAD

**Issue by sbwalker** [dotnet/aspnetcore#55808]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When creating a static component which has a form element that is rendered based on conditional logic, the form will be displayed:

![image](https://github.com/dotnet/aspnetcore/assets/4840590/e4281ae8-55a5-498f-9ea7-ad639555dd99)

However when a user clicks a button to submit the form it will display a message at the top of the browser window "Cannot submit the form because no form on the page currently has that name." . 

![image](https://github.com/dotnet/aspnetcore/assets/4840590/dcb69155-8886-44c6-9f03-9b2311f1006d)

No exception is raised... it is simply a hard crash of the web UI. Refreshing the page in the browser will restore the UI (because it resets the state).

### Expected Behavior

The form onsubmit handler should execute as expected, without throwing an error.

### Steps To Reproduce

The following is a minimal repro:

```
@page "/"

<PageTitle>Form Error</PageTitle>

@if (string.IsNullOrEmpty(_message))
{
    <form method="post" @formname="Form1" @onsubmit="DisplayMessage" data-enhance>
        <AntiforgeryToken />
        <button type="submit" class="btn btn-primary">Submit Form1</button>
    </form>
}
else
{
    <div class="alert alert-info" role="alert">
        @_message
        <form method="post" @formname="Form2" @onsubmit="DismissMessage" data-enhance>
            <AntiforgeryToken />
            <button type="submit" class="btn btn-primary">Submit Form2</button>
        </form>
    </div>
}

@code {
    string _message = "";

    private void DisplayMessage()
    {
        _message = "Now Click The Button To Dismiss The Message";
    }

    private void DismissMessage()
    {
        _message = "";
    }
}
```

### Exceptions (if any)

No exceptions are thrown - a message is displayed in the browser

### .NET Version

8.0.4

### Anything else?

Note that this does not appear to be an Enhanced Navigation issue, as it even occurs when the data-enhance attribute is removed from the form element.

**Comment by javiercn** [comment]
@sbwalker thanks for contacting us.

This is a developer error and by design. It's a requirement that if a form was rendered in SSR it needs to be rendered on to the page before we can dispatch the event. Otherwise, there is simply no way for us to associate the form name with the event handler nor to run any of the validations that the form might have.

**Comment by sbwalker** [comment]
@javiercn when you say "developer error" I assume you mean "Blazor limitation" as it is fairly common practice in web UX design to display a form based on a button click in order to capture some additional input. 

The scenario where I encountered this behavior was a simple form where I wanted to capture some input from a user. I did not want the form to be displayed by default... I wanted them to click a button to reveal the form. And this component needed to be statically rendered because it is on a page in a public website where I do not want Blazor interactivity (ie. SignalR or WebAssembly). 

Here is a minimal repro - however you can imagine that the real-world form may need to collect a lot more input fields than just an email address - which is why it is beneficial for the form to only be made visible when the user expresses intent.

![image](https://github.com/dotnet/aspnetcore/assets/4840590/573929f2-d458-4257-807b-67377f32ccb4)

Here is the code:

```
@page "/"

<PageTitle>Form Error</PageTitle>

<form method="post" @formname="Form1" @onsubmit="DisplayForm" data-enhance>
    <AntiforgeryToken />
    <button type="submit" class="btn btn-primary mb-3">Click Here To Provide Your Email</button>
</form>

@if (_display)
{
    <form method="post" @formname="MyForm" @onsubmit="SaveEmail" data-enhance>
        <AntiforgeryToken />
        <input name="email" class="form-control mb-3" placeholder="Enter Your Email" @bind="@_email" />
        <button type="submit" class="btn btn-success">Save Email</button>
    </form>
}

@code {
    private bool _display = false;
    private string _email = "";

    [SupplyParameterFromForm(FormName = "MyForm")]
    public string email { get => ""; set => _email = value; }

    private void DisplayForm()
    {
        _display = true;
    }

    private void SaveEmail()
    {
        // validate and save to database
        _display = true;
    }
}
```

And when clicking Save Email this crashes with the form name error:

![image](https://github.com/dotnet/aspnetcore/assets/4840590/88e47c22-de86-4d21-9d19-2a9e3785a983)

This is really strange behavior from a developer perspective, as it there is nothing wrong with the way the form element is specified in my component. I spent quite a bit of time trying to trouble-shoot this problem as I assumed I was doing something incorrectly in my code... and I can only assume other developers will find this equally confusing.

So the question is... when using static rendering and needing to capture user input based on a visibility condition, what is the recommended solution for resolving this? Do you suggest using CSS/JavaScript to hide/show the form rather than using conditional logic in the component code?

**Comment by sandyhyd2021** [comment]
Extremely poor support for Blazor in .net 8. it will die soon. you guys cann't sustain against react and angular.

**Comment by boreys** [comment]
Blazor form is not working well, so I try to use MVC view, but this Blazor form logic keep interfering with MVC view form and keep throwing error like: Cannot submit the form 'imageForm' because no form on the page currently has that name.

I'm trying to avoid Blazor form by using MVC controller and views and Ajax; and I cannot disable this form behavior.

this is frustrating

**Comment by pjc2007** [comment]
I get this without even having my form in an "if", it is there straight up. I've given the form an id everyway I can think of...

```
 <EditForm id="LoginForm" Model="@Model" OnValidateSubmit="Authenticate" @formname="LoginForm" FormName="LoginForm">
```
I cannot use `@rendermode InteractiveServer` as I then get no `HttpContext` to sign in against...

**Comment by meisam-dehghan** [comment]
> @javiercn when you say "developer error" I assume you mean "Blazor limitation" as it is fairly common practice in web UX design to display a form based on a button click in order to capture some additional input.
> 
> The scenario where I encountered this behavior was a simple form where I wanted to capture some input from a user. I did not want the form to be displayed by default... I wanted them to click a button to reveal the form. And this component needed to be statically rendered because it is on a page in a public website where I do not want Blazor interactivity (ie. SignalR or WebAssembly).
> 
> Here is a minimal repro - however you can imagine that the real-world form may need to collect a lot more input fields than just an email address - which is why it is beneficial for the form to only be made visible when the user expresses intent.
> 
> ![image](https://private-user-images.githubusercontent.com/4840590/332407935-573929f2-d458-4257-807b-67377f32ccb4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NDg3ODcsIm5iZiI6MTcyNjY0ODQ4NywicGF0aCI6Ii80ODQwNTkwLzMzMjQwNzkzNS01NzM5MjlmMi1kNDU4LTQyNTctODA3Yi02NzM3N2YzMmNjYjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MThUMDgzNDQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzFhNTI3NWQxMGQ2M2M1ZjgzY2E5NDNhZmFmMDBkYWJjM2FkOWI5ODEwOTVkOTFiMGY3OGE0Y2IxYjlkN2YyOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.vBt8OuQS5CnzUzaKjCpdKnUacnb9QIfoyb2d7Ah_ojU)
> 
> Here is the code:
> 
> ```
> @page "/"
> 
> <PageTitle>Form Error</PageTitle>
> 
> <form method="post" @formname="Form1" @onsubmit="DisplayForm" data-enhance>
>     <AntiforgeryToken />
>     <button type="submit" class="btn btn-primary mb-3">Click Here To Provide Your Email</button>
> </form>
> 
> @if (_display)
> {
>     <form method="post" @formname="MyForm" @onsubmit="SaveEmail" data-enhance>
>         <AntiforgeryToken />
>         <input name="email" class="form-control mb-3" placeholder="Enter Your Email" @bind="@_email" />
>         <button type="submit" class="btn btn-success">Save Email</button>
>     </form>
> }
> 
> @code {
>     private bool _display = false;
>     private string _email = "";
> 
>     [SupplyParameterFromForm(FormName = "MyForm")]
>     public string email { get => ""; set => _email = value; }
> 
>     private void DisplayForm()
>     {
>         _display = true;
>     }
> 
>     private void SaveEmail()
>     {
>         // validate and save to database
>         _display = false;
>     }
> }
> ```
> 
> And when clicking Save Email this crashes with the form name error:
> 
> ![image](https://private-user-images.githubusercontent.com/4840590/332410170-88e47c22-de86-4d21-9d19-2a9e3785a983.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NDg3ODcsIm5iZiI6MTcyNjY0ODQ4NywicGF0aCI6Ii80ODQwNTkwLzMzMjQxMDE3MC04OGU0N2MyMi1kZTg2LTRkMjEtOWQxOS0yYTllMzc4NWE5ODMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MThUMDgzNDQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODNkMzg4NTBhMzVkZjRhZWUxZTY1MGU2YmVlYmMxNjQ0NzE4NmNhMjFmYzljMDVmZDA4MTEwZDBlYzIzMmMxMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.V915D7lnL37My-35w4Nw6nNgTqOO73hDZel5ZViLqnI)
> 
> This is really strange behavior from a developer perspective, as it there is nothing wrong with the way the form element is specified in my component. I spent quite a bit of time trying to trouble-shoot this problem as I assumed I was doing something incorrectly in my code... and I can only assume other developers will find this equally confusing.
> 
> So the question is... when using static rendering and needing to capture user input based on a visibility condition, what is the recommended solution for resolving this? Do you suggest using CSS/JavaScript to hide/show the form rather than using conditional logic in the component code?

Mabe one thing you could do is to put the logic to render the form elements inside the form tag. This way, the form name would be rendered initially, yet the elements inside would be displayed once the user clicks the button.

**Comment by meisam-dehghan** [comment]
Mabe one thing to do is to put the logic to render the form elements inside the form tag. This way, the form name would be rendered initially, yet the elements inside would only be displayed once the user clicks the button.

**Comment by meisam-dehghan** [comment]
Maybe one thing to do is to put the logic to render the form elements inside the form tag. This way, the form name would be rendered initially, yet the elements inside would only be displayed once the user clicks the button.

**Comment by meisam-dehghan** [comment]
Another way to deal with this issue is to have a <form/> tag with just the @formname  and  @onsubmit on the page outside the condition that will render the main form with UI elements.Then within the main form that is rendered based on a specific condition,add an input with the name **_handler** and the value that correspond to name of form you specified for the form outside the condition.Here's an example:
`
@if (_showDeleteConfirmation)
{
            <form method="post" data-enhance>
                <input type="hidden" name="_handler" value="DeleteConfirmationForm" />
                <InputNumber @bind-Value="SelectedItemId" type="hidden" />
                <AntiforgeryToken />
                <p>Are you sure you want to remove this item?</p>
                <div class="justify-content-between row mx-auto">
                    <button class="btn-action mr-3 my-5" name="DeleteCanceled" value="true">
                        <span class="text-white">Cancel</span>
                    </button>
                    <button class="btn-action mr-3 my-5">
                        <span class="text-white">Remove</span>
                    </button>
                </div>
            </form>
}
<form @formname="DeleteConfirmationForm" @onsubmit="@HandleDeleteFormSubmit"></form>

`

**Comment by meisam-dehghan** [comment]
Another way to deal with this issue is to have a <form/> tag with just the @formname  and  @onsubmit on the page outside the condition that will render the main form with UI elements.Then within the main form that is rendered based on a specific condition,add an input with the name **_handler** and the value that correspond to name of form you specified for the form outside the condition.Here's an example:
`@if (_showDeleteConfirmation)
{
            <form method="post" data-enhance>
                <input type="hidden" name="_handler" value="DeleteConfirmationForm" />
                <InputNumber @bind-Value="SelectedItemId" type="hidden" />
                <AntiforgeryToken />
                <p>Are you sure you want to remove this item?</p>
                <div class="justify-content-between row mx-auto">
                    <button class="btn-action mr-3 my-5" name="DeleteCanceled" value="true">
                        <span class="text-white">Cancel</span>
                    </button>
                    <button class="btn-action mr-3 my-5">
                        <span class="text-white">Remove</span>
                    </button>
                </div>
            </form>
}
<form @formname="DeleteConfirmationForm" @onsubmit="@HandleDeleteFormSubmit"></form>
`

**Comment by meisam-dehghan** [comment]
Another way to deal with this issue is to have a <form/> tag with just the _formname_  and  _onsubmit_ on the page outside the condition that will render the main form with UI elements.Then within the main form that is rendered based on a specific condition,add an input with the name **_handler** and the value that correspond to name of form you specified for the form outside the condition
```
if (_showDeleteConfirmation)
{
 <form method="post" data-enhance>
  <input type="hidden" name="_handler" value="DeleteConfirmationForm" />
                ...
</form>
}
<form @formname="DeleteConfirmationForm" @onsubmit="@HandleDeleteFormSubmit"></form>
```

**Comment by rob-king-volpara** [comment]
This has come to bite me when using HTMX to post forms to routable SSR components. I can put a breakpoint the routable component and it receives the model perfectly well and I can handle it, but then before it renders back to the browser, this form name error jumps in and kills it.

I get why a form name is required, but at the same time, I feel like some flexibility should be added to allow for scenarios that aren't pure Blazor.

**Comment by raphadesa** [comment]
Hello, did you try something like this : 
```

<form method="post" @formname="Form1" @onsubmit="DisplayMessage" data-enhance style="@(_display ? display:block" : "display:none")">
...
</form>



```
