### ISSUE TITLE
Framework location path should be configurable

### ISSUE THREAD

**Issue by ebfortin** [dotnet/aspnetcore#5582]
I am experimenting with different hosting scenarios for a Blzaor App and thought about packaging it into a Chrome Extension / App. however, Chrome Extension do not support _ at the begining of a path because it is reserved for system use.  Blazor make extensive use of _ in the path, at least for _framework and _bin. These paths should be configurable so that scenarios like Chrome Extension can be supported / tested.

**Comment by ebfortin** [comment]
Any development on this feature?

**Comment by danroth27** [comment]
Apparently Android also doesn't like leading underscores: https://github.com/aspnet/AspNetCore/issues/10183

**Comment by JohnGalt1717** [comment]
Bump.

Anyone have this working?  I've tried adding 

    aaptOptions {
        ignoreAssetsPattern "!.svn:!.git:!.ds_store:!*.scc:.*:!CVS:!thumbs.db:!picasa.ini:!*~"
    }

to the build.gradle but it doesn't seem to work.

**Comment by pranavkm** [comment]
This should be achievable by configuring ` loadBootResource`. https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-3.1#compression has an example of configuring this for compression, but you could apply it to customize resource paths to arbitrary locations.

**Comment by danroth27** [comment]
You can customize the deployment layout, but it's a bit clunky if all you want to do is change _framework to something else. Reopening this to consider for a future release.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
