### ISSUE TITLE
Best Practices - Call Blazor base lifecycle method first / always

### ISSUE THREAD

**Issue by mstortz** [dotnet/aspnetcore#55839]
## Background and Motivation

This issue arose from the referenced documentation issue; this was the category that seemed most appropriate to me.

I have had discussions with my team regarding best practices for calling the base method from Blazor lifecycle methods OnInitialized, OnParametersSet, and OnAfterRender.

My position is that to avoid hard to find errors, you should always call the base method, and do so before any other code.  I am aware that these methods in ComponentBase do nothing, so omitting calling the base method from a direct descendent of ComponentBase has no effect.

However, once you introduce an intermediate parent class that overrides a lifecycle method, not calling that method in a grandchild class is _very probably_ an error. Also, the introduction of the intermediate parent class may well come after the child component was created, and if it did not call the base method originally because it inherited ComponentBase directly, now there is a hard to find bug.

Even when the base method is called, since the calling method (or other methods it calls) may well depend on work done in the base method, it should call the base method first before other code. This is similar to how you call a base constructor first.

While it's not determitive, I did ask GitHub Copilot about this in the new release of VS, and it responded:
> Yes, in the context of Blazor components, it's a common practice to call base.OnInitializedAsync() at the beginning of your overridden OnInitializedAsync() method.
This ensures that the base class's initialization logic is executed before your component's specific initialization logic. The base class's initialization might set up some state or perform other actions that your component relies on.

If this is, in fact, not a good practice, I would like to know why; but otherwise, even if an analyzer is not forthcoming, I would like an "probably a good idea" recommendation to this effect that I can forward to my team.

## Proposed Analyzer

Blazor Component Lifecycle

### Analyzer Behavior and Message

When a Blazor component overrides a lifecycle event, it should call the base method, and do so before any other code. 

### Category

- [X] Design
- [ ] Documentation
- [ ] Globalization
- [ ] Interoperability
- [ ] Maintainability
- [ ] Naming
- [ ] Performance
- [ ] Reliability
- [ ] Security
- [ ] Style
- [ ] Usage

### Severity Level

- [ ] Error
- [X] Warning
- [ ] Info
- [ ] Hidden

## Usage Scenarios

(These are only for the async variant of OnInitialized; but you get the idea)

```
protected override async Task OnInitializedAsync()
{
    SomeMethod();
}
```
WARNING: Base lifecycle method (OnInitializedAsync) not called.

```
protected override async Task OnInitializedAsync()
{
    SomeMethod();
    base.OnInitialized();
}
```
WARNING: Base lifecycle method (OnInitializedAsync) not called first.

## Risks

There could be cases where a child component intentionally omits calling the base lifecycle method, or intentionally does not call it first, which would then be flagged as a warning where it was not previously. However, my WAG is that these cases are few and far between, and of course the warning could be suppressed.

cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/32621

**Comment by MackinnonBuck** [comment]
Closing this issue as answered.
