### ISSUE TITLE
[9.0-preview.4] OpenAPI operations are missing the ID

### ISSUE THREAD

**Issue by martincostello** [dotnet/aspnetcore#55838]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When `WithName()` is applied to an endpoint tools such as NSwag emit this value as the `operationId`.

The new OpenAPI document generator does not appear to emit the operation IDs.

### Expected Behavior

The value passed to `WithName()` for an endpoint is emitted as the `operationId` for the definition emitted into the `paths` property.

### Steps To Reproduce

Define an endpoint such as the following for use with the new OpenAPI functionality:

```csharp
group.MapGet("/greet", () => "Hello")
     .WithName("MyOperation");
```

### .NET Version

9.0.100-preview.4.24267.66

**Comment by captainsafia** [comment]
This was recently resolved in https://github.com/dotnet/aspnetcore/commit/c64f36d2c7433de43d8fbf24d59887f829015687. Will ship in preview5.
