### ISSUE TITLE
Button's onclick triggered upon right mouse click

### ISSUE THREAD

**Issue by korsaire** [dotnet/aspnetcore#5583]
When you have onclick event e.g.
```
<button onclick="@HandleClick">Click me</button>
```
it's triggered upon both left and right button click. I think it's a bug, as you can read in living HTML [standard](https://w3c.github.io/uievents/#event-type-click):
>The click event type MUST be dispatched on the topmost event target indicated by the pointer, when the user presses down and releases the **primary** pointer button, or otherwise activates the pointer in a manner that simulates such an action.

**Comment by SteveSandersonMS** [comment]
Note: only repros in Firefox.

**Comment by mfluehr** [comment]
Modern Firefox now only fires click events for the primary mouse button. This was fixed in Firefox 68 (July, 2019). https://developer.mozilla.org/en-US/docs/Web/API/Element/click_event#browser_compatibility
