### ISSUE TITLE
[9.0-preview.4] OpenAPI response does get served if a static file with the same path exists as a file

### ISSUE THREAD

**Issue by martincostello** [dotnet/aspnetcore#55833]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

_I'm not sure if this is a bug or not, but it's certainly an unexpected behaviour to me._

Because NSwag doesn't support native AoT, I have an application where I have a setup like the following:

- NSwag renders the OpenAPI response when dynamic code is supported.
- A copy of that document is stored in wwwroot as a fall back for the deployed native AoT app.
- `UseOpenApi()` is registered before `UseStaticFiles()`.

For the purposes of comparison, I disabled NSwag and configured the new OpenAPI support for .NET 9 preview 4 to serve the new generated document from the same URL:

```csharp
app.MapOpenApi("/swagger/api/swagger.json");
app.UseStaticFiles();
```

In this scenario I would expect the application to behave the same, but instead I always get the content from the static file instead.

If I delete the file, then I get the generated content. If I then restore the file, I get the static one again.

### Expected Behavior

I would expect the generated content to always be served as the OpenAPI middleware is registered before static files.

### Steps To Reproduce

1. Configure an API application with the new OpenAPI support and static files.
1. Save the content generated by `MapOpenApi()` into wwwroot at a location that has the same path, but make a trivial edit so you can tell which content is served.
1. Run the application and request the URL for the Open API document.

### .NET Version

9.0.100-preview.4.24267.66

**Comment by captainsafia** [comment]
Interesting bug! I assume that for the purposes of this repro you don't actually need to have NSwag.AspNetCore installed in the application and that `MapOpenApi` + `UseStaticFiles` is enough . To that end, I have this Program.cs:

```csharp
var builder = WebApplication.CreateBuilder(args);

builder.Services.AddOpenApi();

var app = builder.Build();

app.MapOpenApi("/swagger/api/swagger.json");
app.UseStaticFiles();

app.MapGet("/", () => "Hello World!");

app.Run();
```

And the following directory structure:

```bash
$ tree -I "bin|obj"
.
├── NSwagOpenApi.csproj
├── NSwagOpenApi.sln
├── Program.cs
├── Properties
│   └── launchSettings.json
├── appsettings.Development.json
├── appsettings.json
└── wwwroot
    └── swagger
        └── api
            └── swagger.json

4 directories, 7 files
```

With this setup, I get the behavior that I expect to see: which is that the generated content is _always_ registered because the endpoint routing middleware runs before the static files middleware in the default setup for the minimal host. If I comment ou the `app.MapOpenApi(..)` line, I see that the static file is rendered because endpoint routing fails to resolve an endpoint and falls back to the static files middleware.

Is there a chance the middleware registration differs in your setup?

**Comment by martincostello** [comment]
I'll take a look into this again later this week and see if I can work out what the factor that causes the behaviour is (or if I was somehow being an idiot 🙃).

**Comment by captainsafia** [comment]
> I'll take a look into this again later this week and see if I can work out what the factor that causes the behaviour is (or if I was somehow being an idiot 🙃).

You? Never! Take your time. Hopefully we don't discover anything spooky here 😅

**Comment by martincostello** [comment]
I  haven't ruled out me being stupid or overlooking something, but I definitely get the wrong OpenAPI document here: https://github.com/martincostello/api/commit/ec552ac419f45f7e13f9e523a301f75d921c4bfc.

I would expect the `Dynamic_Schema_Is_Served()` test to pass because it gets the OpenAPI document with a version of 3.0.1 as it's coming from the new library, but instead I get 3.0.0 from NSwag.

**Comment by martincostello** [comment]
I've ripped out everything related to NSwag in this commit, and I can still repro it: https://github.com/martincostello/api/commit/997aa2b01bb9c67e3b4d0d6352804453386e10a6

If I delete the static file the test passes as I get the generated document, otherwise it fails because I get the content from disk.

**Comment by martincostello** [comment]
Still seeing this with preview 5.

**Comment by captainsafia** [comment]
@martincostello I think I figured out the isuse here as it pertains to the differences between my minimal repo [here](https://github.com/dotnet/aspnetcore/issues/55833#issuecomment-2136037794) and your sample app.

I believe the gotcha here is that the routing middleware is registered _after_ the static files middleware in your API:

```csharp
if (RuntimeFeature.IsDynamicCodeSupported)
{
    app.MapOpenApi("/swagger/{documentName}/swagger.json");
}

app.UseStaticFiles();

app.UseRouting();
```

In this case, the static files middleware always runs before endpoint routing terminates the middleware pipeline before endpoint routing is able to kick in and map the request to the OpenAPI document endpoint that is registered. In the repro from my comment, the endpoint routing middleware is implicitly registered first and always processes the request.

Moving endpoint routing before the static files middleware should resolve the issue. As long as you continue not registering `MapOpenApi` when dynamic code is not supported endpoint routing should 404 and fallback to static files.

**Comment by martincostello** [comment]
I've got this working as expected in my repo now with `UseRouting()` removed completely - feel free to close.
