### ISSUE TITLE
[9.0-preview.4] Remove x-aspnetcore-id from OpenAPI responses

### ISSUE THREAD

**Issue by martincostello** [dotnet/aspnetcore#55832]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Playing around with the new OpenAPI support in .NET 9 preview 4, I notice that all the operations have something like the following on all the operations:

```json
"x-aspnetcore-id": "486b77e5-5389-4ee8-aa30-e251b631a16d"
```

This appears to be an internal implementation detail related to caching that doesn't need to be rendered in the JSON document. The values also don't appear to be deterministic and change with process restarts, which would cause the values to vary over time and within a web farm making stable comparison of the generated document for changes difficult.

It also leaks an implementation detail (that the server uses ASP.NET Core) that a user may not want to be broadcast if the document is internet-facing.

### Describe the solution you'd like

The value used for caching is stored in a location that does not get serialized to the document.

**Comment by captainsafia** [comment]
TY for the bug report!

It's been on my radar to remove the `x-aspnetcore-id` attribute before RC. I wanted to wait until schema transformers had solidified a bit (schema transformers use a similar extension attribute to support mapping in `$ref`s) so we could implement scrubbing of all extension IDs at once. However, I'll just go ahead and do this now to avoid confusing folks using previews.
