### ISSUE TITLE
Blazor pages from RCL does not work in net8

### ISSUE THREAD

**Issue by FLAMESpl** [dotnet/aspnetcore#55843]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Blazor in net8 does not load pages from razor class libraries

### Expected Behavior

Home page works correctly

### Steps To Reproduce

- Create Blazor Web App
- Run the app

Result: template home page shows up

- Create Razor Class Library
- Move Home.razor component to Razor Class Library
- Add to router property `AdditionalAssemblies="[typeof(Home).Assembly]"`
- Run the app

Result: page not found (404)

[reproduction.zip](https://github.com/dotnet/aspnetcore/files/15407829/reproduction.zip)

### .NET Version

SDK: 8.0.300
Runtime: Microsoft.AspNetCore.App 8.0.5

**Comment by javiercn** [comment]
@FLAMESpl thanks for contacting us.

You also need to add the assembly using the call `AddAdditionalAssemblies` in the call to `MapComponents`.

**Comment by FLAMESpl** [comment]
Hi @javiercn thanks for the fast repsonse. Is this somewhere documented? I couldn't find this information on this page: https://learn.microsoft.com/en-us/aspnet/core/blazor/components/class-libraries?view=aspnetcore-8.0&tabs=visual-studio
