### ISSUE TITLE
Could not publish with --no-build

### ISSUE THREAD

**Issue by kant2002** [dotnet/aspnetcore#5584]
1. Have setup Two projects. First is API, second is Client Blazor app which is referenced by API.
2. I do build of solution using dotnet build
3. then I run `dotnet publish API --no-build`

Resulting the generated output does not contains .blazor.config
when I run `dotnet publish` without specifying `--no-build` produced package contains valid `blazor.config` file. This make whole published package unusable.

**Comment by kant2002** [comment]
This is still an issue with Preview 6

**Comment by pranavkm** [comment]
We have tests that verify this work with the 3.2 RTM release of Blazor WASM.
