### ISSUE TITLE
Preload Dlls and mono.wasm on build

### ISSUE THREAD

**Issue by vipero07** [dotnet/aspnetcore#5585]
The way things are currently loaded is mono.wasm first, then after it is processed the dlls get loaded and processed. After all of this is done the application will finally render in the browser. As a result the initial load is quite slow (for me its been around 4s on a fast computer with a good internet connection). The initial page load performance can be greatly improved simply by adding a preload link in the HTML for each dll. 

E.G. 
```
<link rel="preload" as="fetch" type="application/octet-stream" href="_framework/_bin/mscorlib.dll" /> 
<link rel="preload" as="fetch" type="application/octet-stream" href="_framework/_bin/System.Core.dll" />
...
```

You could also use a script like:

```
(function () {
    function preload(href) {
        var link = document.createElement('link');
        link.rel = 'preload';
        link.as = 'fetch';
        link.type = 'application/octet-stream';
        link.href = '_framework/_bin/' + href;
        document.head.appendChild(link);
    }
    [
        'mscorlib.dll',
        'System.Core.dll',
        'Microsoft.CSharp.dll',
        'System.dll',
        'Microsoft.AspNetCore.Blazor.dll',
    ].forEach(preload);
}());
```

The downside of using a script is browsers can be pushed link preloads by the server, and using the script loses the server push ability.

What would be nice is a build script that detects the generated dlls and injects the link preload into the html file head. When you preload the dlls they are generally done being retrieved before mono.wasm is even ready to look for them. This has reduced my render times down to 1s from the 4s I mentioned above, a notable improvement. 

Alternatively a service worker that prefetches the dlls would work just as well.

**Comment by pranavkm** [comment]
WASM's caching has improved significantly since the issue was filed. If you think further work needs to be done once you've tried 3.2, please file a new issue.
