### ISSUE TITLE
Blazor WebAssembly does not work after upgrade

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#55870]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Blazor-WebAssembly-does-not-work-after-u/10661389)._

---
[severity:I'm unable to use this version] [regression]
When deploy to azure webapp, portable target runtime, wasm not load.

MONO_WASM: TypeError: Cannot read properties of undefined (reading 'out')

---
#### Feedback Bot on 5/19/2024, 09:55 PM: 

(private comment, text removed)
#### Jean-Vincent LAMY on 5/20/2024, 11:54 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by knepe** [comment]
https://github.com/dotnet/aspnetcore/issues/55978
