### ISSUE TITLE
Smarter IResponse content types

### ISSUE THREAD

**Issue by matheus-kirchesch** [dotnet/aspnetcore#55882]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Right now if you use Results.BadRequest, Results.NotFound, Results...., in your endpoints, you will always be returning application/json content type.

My proposal is for these methods to return text/plain if the content is a pure string.

### Describe the solution you'd like

This can be easily done by implementing this on the [[BadRequestOfT], ...
```
        MediaTypeHeaderValue? mediaTypeHeaderValue = null;
        if (Value is string)
        {
            mediaTypeHeaderValue = MediaTypeHeaderValue.Parse(MediaTypeNames.Text.Plain);
        }
```

I have done it already locally, I am creating the issue to see if the maintainers agree, if so, I will open a PR.

**Comment by captainsafia** [comment]
Closing this based on the feedback provided in https://github.com/dotnet/aspnetcore/pull/55888#issuecomment-2270094939.
