### ISSUE TITLE
.NET location: Not found while using dotnet global tools 

### ISSUE THREAD

**Issue by phadkesharan** [dotnet/aspnetcore#55894]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

while using any dotnet global tool, it is unable to find .net runtime

You must install .NET to run this application.

App: /home/phadkesharan/.dotnet/tools/dotnetsay
Architecture: x64
App host version: 8.0.5
.NET location: Not found

This is despite adding .dotnet and .dotnet/tools location to the PATH variable

**Comment by martincostello** [comment]
This isn't an issue specific to ASP.NET Core - this should be transferred to either the dotnet/sdk or dotnet/runtime repo.
