### ISSUE TITLE
Sidebar auto-collapses any collapsable children on wide media - fix included

### ISSUE THREAD

**Issue by GodzillaDaThrilla** [dotnet/aspnetcore#5590]
Figured this out while trying to create an accordion on the sidebar. I found that the standard bootstrap collapse on child elements worked fine on small screens where the sidebar collapses to the top, but on large screens the accordion menu(s) would just keep re-collapsing (again, only only large screens, collapseable elements functioned normally in mobile view).

### The Problem:
The problem is with the default template, specifically this in NavMenu.cshtml:
![image](https://user-images.githubusercontent.com/18584301/45224021-cc842280-b2b0-11e8-9047-a30114adcc75.png)
and this in site.css:
![image](https://user-images.githubusercontent.com/18584301/45224090-048b6580-b2b1-11e8-9422-4b0a6cbc1327.png)

This means that the collapse prevention is inherited by all child elements on wide screens, which makes a hamburger/accordion-style menu impossible.

### The Fix:
Add an arbitrary class to the HTML - I called mine navInner:
![image](https://user-images.githubusercontent.com/18584301/45224401-c93d6680-b2b1-11e8-99a1-80f31b6efb68.png)
Then modify the CSS so it targets only the sidebar specifically and not its children. I did this by replacing the  ".collapse" with a combo-selector ".navInner.collapse" :
![image](https://user-images.githubusercontent.com/18584301/45224515-0dc90200-b2b2-11e8-95b2-e1b79293da91.png)

### The Result:
![image](https://user-images.githubusercontent.com/18584301/45230184-014ba600-b2c0-11e8-903d-d8693b762d89.png)
![image](https://user-images.githubusercontent.com/18584301/45230231-24765580-b2c0-11e8-8efc-2f9138c5a060.png)
Hey hey, it works!

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @GodzillaDaThrilla.
Nice fine. Feel free to send us a PR and we'll happily consider it!

**Comment by javiercn** [comment]
@GodzillaDaThrilla Thanks for reaching out. What you are describing seems to be indeed a problem. Could this be fixed with just a more specific css selector? like .sidebar>.collapse?

I'm not sure why we would change our current behavior, as templates are a starting point and can be modified/updated by users. If there is a straight forward fix (like using a more specific selector) we would gladly take it I think, but otherwise, you can always modify the document to suit your needs.

**Comment by mkArtakMSFT** [comment]
Closing as we've never received a response here nor there was general community interest here.
