### ISSUE TITLE
Blazor Authorization - AuthorizeRouteView NotAuthorized tag not triggered when directly accessing /auth from address bar in the browser

### ISSUE THREAD

**Issue by lokitech** [dotnet/aspnetcore#55911]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When creating a new Blazor WebApp with _Global_ Interactivity and _Auto_ render mode with _Individual Accounts_ the `<RedirectToLogin />` is hit within the _Routes.razor_. I changed the _RedirectToLogin.razor_ component so that it redirects to counter and it works as expected when navigating to _Auth_ page through application navigation.

Routes.razor
```
<Router AppAssembly="typeof(Program).Assembly">
    <Found Context="routeData">
        <AuthorizeRouteView RouteData="routeData" DefaultLayout="typeof(Layout.MainLayout)">
            <NotAuthorized>
                <RedirectToLogin />
            </NotAuthorized>
        </AuthorizeRouteView>
        <FocusOnNavigate RouteData="routeData" Selector="h1" />
    </Found>
</Router>
```
RedirectToLogin.razor
```
@inject NavigationManager NavigationManager

@code {
    protected override void OnInitialized()
    {
        NavigationManager.NavigateTo("counter", forceLoad: true);
    }
}
```

BUT the problem is when when you navigate to _/auth_ via address bar. In that case the OnInitialized method in _RedirectToLogin.razor_ is never hit and you get redirected to _/Account/Login?ReturnUrl=%2Fauth_ which is not specified nowhere in the newly created application. 

This is a similiar bug as in #52063 except the `<RedirectToLogin>` works when navigating to _/auth_ from the application navigation.

### Expected Behavior

The `<RedirectToLogin />` inside _Routes.razor_ `<NotAuthorized>` tags should be hit whether I navigate to _/auth_ page via the address bar or the application navigation. 
Or there should be a way to change the default navigation from  _/Account/Login?ReturnUrl=%2Fauth_ to some other route.
It seems like it's a fallback url that is set somewhere within your framework.

### Steps To Reproduce

- Create Blazor Web App with _Global_ Interactivity and _Auto_ render mode with _Individual Accounts_.
- Change _RedirectToLogin.razor_ _OnInitialized_ method to navigate to /counter `NavigationManager.NavigateTo("counter", forceLoad: true);`
- Navigate to _/auth_ via address bar -> Get redirected to _/Account/Login?ReturnUrl=%2Fauth_  :x:
- Navigate to _/auth_ via application navigation -> Get redirected to _/counter_ :white_check_mark:  

### .NET Version

8.0.5

### Anything else?
:bangbang: **I tested this in all render modes with and without prerender, the result is the same.**  :bangbang:

_No response_

**Comment by javiercn** [comment]
@lokitech thanks for contacting us.

Blazor web integrates with ASP.NET Core routing and authorization. If your page has [Authorize] on it and your user is not authorized, we'll automatically redirect to the login page.

**Comment by lokitech** [comment]
Hello @javiercn thank your for your reply.
I do not think we understood eachother. I understand that every page that has attrubute [Authorize] redirects an unauthorized user.
I'm saying that even though I change the redirection in RedirectToLogin.razor from Account/Login to something else (/counter in this example) that redirection never happens when navigating via the address bar, it only happens when navigatin through navigation menu inside the application.

Let me re-iterate:
- Change RedirectToLogin.razor OnInitialized method to navigate to /counter NavigationManager.NavigateTo("counter", forceLoad: true);
- Navigate to /auth via address bar -> Get redirected to /Account/Login?ReturnUrl=%2Fauth ❌
- Navigate to /auth via application navigation menu -> Get redirected to /counter ✅

There is no way to change the default route to Account/Login if I want that route to be something else i.e. Account/Signin or whatever else.

**Comment by lokitech** [comment]
Please reconsider this

**Comment by Appli4Ever** [comment]
Asp.Net Core Redirects you to login because the Auth.razor page has a [Authorized] Attribute which causes Asp.Net Core to Redirect you while prerendering. One Solution could also be to disable Prerendering. Other Solution is this:
```
app.MapRazorComponents<App>()
    .AddInteractiveWebAssemblyRenderMode()
    .AddAdditionalAssemblies(typeof(test.Client._Imports).Assembly)
    .AllowAnonymous();

```
which allowes App.razor to prerender even if a page has a [Authorized] Attribute. 

Don`t worry the page itself wont be prerenderd, since Routes.razor will handle the [Authorize] Attribute.

**Comment by philnwoha** [comment]
> Asp.Net Core Redirects you to login because the Auth.razor page has a [Authorized] Attribute which causes Asp.Net Core to Redirect you while prerendering. One Solution could also be to disable Prerendering. Other Solution is this:
> 
> ```
> app.MapRazorComponents<App>()
>     .AddInteractiveWebAssemblyRenderMode()
>     .AddAdditionalAssemblies(typeof(test.Client._Imports).Assembly)
>     .AllowAnonymous();
> ```
> 
> which allowes App.razor to prerender even if a page has a [Authorized] Attribute.
> 
> Don`t worry the page itself wont be prerenderd, since Routes.razor will handle the [Authorize] Attribute.

I disabled prerendering with the following and it did not working without having to specify "AlloyAnonymous()":

```
<HeadOutlet @rendermode="@(new InteractiveServerRenderMode(prerender: false))" />
<Routes @rendermode="@(new InteractiveServerRenderMode(prerender: false))" />
```
