### ISSUE TITLE
[Suggestion] Self closing tags

### ISSUE THREAD

**Issue by stsrki** [dotnet/aspnetcore#5595]
This is not really an issue, just that it would be good to have. Right now the intellisense cannot detect components that should not have closing tags(or does not need them) e.g. `<div></div>`, but instead they would have a "_self-close_" tag e.g. `<input />` or `<img />`.

Possible use case would be for components that does not have `ChildContent`. For example I have an Icon component and I define the icon name through the `Name `parameter so `ChildContent `is not needed. But every time I use it, the VS intellisense will generate closing tag.

**Current behavior:**
`<Icon Name="user"></Icon>`

**Wanted:**
`<Icon Name="user" />`

Maybe this is not connected to the Blazor team but to the VS team instead, please ignore in that case.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
