### ISSUE TITLE
Interactive Blazor application doesn't work when accessed through "Dev Tunnels"

### ISSUE THREAD

**Issue by grallbring** [dotnet/aspnetcore#55962]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When sharing a Blazor application which uses the Interactive Rendering mode through Dev Tunnels interactive content like incrementing a counter through a button click doesn't work.

The issue seems to be that it tries to connect to localhost instead of using the dev tunnels URL.

### Expected Behavior

I expect the application working normally when using Dev Tunnels.

### Steps To Reproduce

I was following the Blazor tutorial here: https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/intro

### .NET Version

8.0.300

### Anything else?

```
.NET SDK:
 Version:           8.0.300
 Commit:            326f6e68b2
 Workload version:  8.0.300-manifests.4e5ea2d8
 MSBuild version:   17.10.4+10fbfbf2e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.300\

.NET workloads installed:
 [aspire]
   Installation Source: VS 17.10.34928.147
   Manifest Version:    8.0.0/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.0.0\WorkloadManifest.json
   Install Type:        FileBased


Host:
  Version:      8.0.5
  Architecture: x64
  Commit:       087e15321b

.NET SDKs installed:
  8.0.300 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by javiercn** [comment]
@grallbring thanks for contacting us.

You might need to configure the forwarding headers on the request.

Can you try https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-8.0 and tell us if it works for you?

**Comment by grallbring** [comment]
@javiercn Yes, thank you, that worked! :)
