### ISSUE TITLE
HealthCheckMiddleware unexpected behavior, still running through the other middlewares in the chain

### ISSUE THREAD

**Issue by toanxyz** [dotnet/aspnetcore#55972]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

```
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddHealthChecks();
var app = builder.Build();

app.MapHealthChecks("/health");
app.UseAuthentication();
```

With this setup above, I'm expecting the HealthCheckMiddleware executed, then it will return and not moving to next middlewares in the pipeline.

However, the behavior is both HealthCheckMiddleware and AuthenticationMiddlware are being executed. Which led to some unwanted behavior.

I notice this setup in the HealthCheckEndpointRouteBuilderExtensions, could it be because the healthcheck is setup under a separate pipeline?
https://github.com/dotnet/aspnetcore/blob/daf411cf171c5de0c9a31bf9813a4c63063a964b/src/Middleware/HealthChecks/src/Builder/HealthCheckEndpointRouteBuilderExtensions.cs#L67

The only way I can make it's working as my expectation is:
```
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddHealthChecks();
var app = builder.Build();

app.Map("/health", _ =>
{
    app.UseMiddleware<HealthCheckMiddleware>();
});
app.UseAuthentication();
```

### Expected Behavior

With this setup above, I'm expecting the HealthcheckMiddewware executed, then it will return and not moving to next middlewares in the pipeline.

### Steps To Reproduce

```
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddHealthChecks();
var app = builder.Build();

app.MapHealthChecks("/health");
app.UseAuthentication();
```

### .NET Version

6.0

**Comment by joegoldman2** [comment]
It's explained in the documentation: https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-8.0#usehealthchecks-vs-maphealthchecks

You need to call `.ShortCircuit()` like: `app.MapHealthChecks("/health").ShortCircuit();`.
