### ISSUE TITLE
Consider splitting up AddAttribute functionality for elements/components

### ISSUE THREAD

**Issue by rynowak** [dotnet/aspnetcore#5598]
Based on: https://github.com/aspnet/Blazor/pull/1453#discussion_r219171895

We have a bunch of overloads of `AddAttribute` but we could potentially reduce runtime complexity by making more decisions at compile time based on whether we're operating on a component or an element.

**Comment by pranavkm** [comment]
Closing this since this would be a breaking change at this point.
