### ISSUE TITLE
Recursive symlink created while following Components build script

### ISSUE THREAD

**Issue by sebastienros** [dotnet/aspnetcore#55983]
Following the documentation [on this page](https://github.com/dotnet/aspnetcore/tree/main/src/Components#how-to-run-the-e2e-tests)

After running `npm install --prefix ./src/Components/test/E2ETest` a symlink pointing to a root folder is created, which then makes `./restore.cmd` hang (OOM when using msbuild 32bits) because of [this bug](https://github.com/dotnet/msbuild/issues/10187).

Repro:

```
(aspnetcore) PS D:\aspnetcore> Get-ChildItem -Path D:\aspnetcore\src\Components\test\E2ETest\node_modules -Force -Recurse -ErrorAction 'silentlycontinue' |   Where { $_.Attributes -match "ReparsePoint"}
(aspnetcore) PS D:\aspnetcore> npm install --prefix ./src/Components/test/E2ETest

added 1 package, and audited 3 packages in 522ms

found 0 vulnerabilities
(aspnetcore) PS D:\aspnetcore> Get-ChildItem -Path D:\aspnetcore\src\Components\test\E2ETest\node_modules -Force -Recurse -ErrorAction 'silentlycontinue' |   Where { $_.Attributes -match "ReparsePoint"}

    Directory: D:\aspnetcore\src\Components\test\E2ETest\node_modules

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
l----           5/30/2024  5:49 PM                aspnetcore -> D:\aspnetcore\

(aspnetcore) PS D:\aspnetcore>
```

**Comment by wtgodbe** [comment]
@sebastienros I know you opened a doc update PR last week, did that fix this & https://github.com/dotnet/aspnetcore/issues/55975?

**Comment by sebastienros** [comment]
I will create a doc update that removes the command which introduces this symlinkm haven't done the PR yet.

**Comment by sebastienros** [comment]
Fixed by https://github.com/dotnet/aspnetcore/pull/56106
