### ISSUE TITLE
Better UX - show "loading" (anything) while app is starting up the .NET WebAssembly runtime (for AutoRender, prerender false) 

### ISSUE THREAD

**Issue by Laftek** [dotnet/aspnetcore#55997]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Is there any way how to show some animation or anything while cached WASM is starting up? I found solution to force downloading resources every time so it can be render by server first but it costs resources of course.

### Describe the solution you'd like

I would like to have option to display loading animation on component level while WASMis starting up.

**Comment by javiercn** [comment]
@Laftek thanks for contacting us.

You should already be able to do this with CSS by wrapping your webassembly component in a `div` and having an animation run on the div when the element is empty.

**Comment by Laftek** [comment]
Thank you @javiercn for suggestions. What can I use as reference element for if statement? Is there any API for wasm to be “loaded”?

Also could you point me to some resources regarding prerendering different content? It sounds interesting. Is there out of box blazor solution or you meant some custom javascript script?

**Comment by javiercn** [comment]
@Laftek just HTML and CSS
```
<div class="my-class"></div>

<style>
.my-class:not(:has(*)) {
   background-image: url("data:....");
}
</style>
```

The moment that the wasm component renders inside the div the styles stop being applicable.

**Comment by Laftek** [comment]
Thanks Javier. Works like a charm!
