### ISSUE TITLE
Blazor: Error on adding new scoped CSS since last update

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#55998]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Blazor:-Error-on-adding-new-scoped-CSS-s/10672822)._

---
[severity:I'm unable to use this version] [regression] [worked-in:Just before 2022 (64-bit) V 17.10.1]
Steps to Reproduce:
1.	Open the Blazor project in Visual Studio.
2.	Navigate to the desired location in the Solution Explorer where you want to add a new CSS file.
3.	Use the shortcut Ctrl + Shift + A or right-click in the Solution Explorer and select 'Add' from the context menu to add a new CSS file.
4.	Name the new file as 'IEButton.razor.css' and place it under the 'ImportExport' directory.
5.	Ensure that the associated Razor component 'IEButton.razor' exists in the same 'ImportExport' directory.
6.	Visual Studio correctly recognizes 'IEButton.razor.css' as a style sheet scoped to 'IEButton.razor'.
7.	Attempt to compile the project.

Expected Result:
The project should compile successfully without any errors, recognizing 'IEButton.razor.css' as a scoped CSS file for the 'IEButton.razor' component.

Actual Result:
The following build error is encountered:

Error (active)	BLAZOR102	The scoped css file 'ImportExport\IEButton.razor.css' was defined but no associated razor component or view was found for it.		

Despite the existence of the associated Razor component, the compiler fails to recognize it and throws an error indicating no associated Razor component or view was found for the scoped CSS file.

Note that previously scoped CSS files remain completely functional. The compiler error only points to a newly added scoped CSS file.

I saw this behavior starting yesterday when I last updated Visual Studio Community.

---
### Original Comments
(no comments)

---
### Original Solutions
(no solutions)

**Comment by wtgodbe** [comment]
Possibly related? https://github.com/dotnet/aspnetcore/issues/39344

**Comment by javiercn** [comment]
@wtgodbe I don't think this issue is related, since the other one involved compilation.

**Comment by javiercn** [comment]
Thanks for contacting us.

Can you check on your `csproj file` if the `.razor` file that you've added has been removed for any reason from the `Content` ItemGroup? You'll see something like `<Content Remove="ImportExport.razor" />` and it typically is followed by something like `<None Include="ImportExport.razor" />`

Do you have any issue if you build from the command line with dotnet build?

If so, can you produce a minimal repro project that demonstrates the issue or attach a MSBuild binlog file to the original Visual Studio User Voice ticket? See https://github.com/dotnet/project-system-tools#build-logging for instructions on how to do this from visual studio.

Please **DO NOT INCLUDE** the binlog here, only on the original ticket.

**Comment by improwise** [comment]
Exact same problem showed up after I upgraded Visual Studio 2022 to latest version. Code compiled fine before.

**Comment by hannespreishuber** [comment]
same here

**Comment by FatAn38** [comment]
> same here
Workaround: close VS2022 - copy + rename files of any valid component. Than open VS2022 and enjoy.

**Comment by ChrisGilson** [comment]
> > same here
> > Workaround: close VS2022 - copy + rename files of any valid component. Than open VS2022 and enjoy.

Nope, this didn't work for me. Still same issue.
