### ISSUE TITLE
Blazor hybrid with WPF, memory leak.

### ISSUE THREAD

**Issue by a44281071** [dotnet/aspnetcore#55993]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

in WPF hybrid Blazor, open multi hybrid windows, BlazorWebView control will cause memory leak.

### Steps To Reproduce

- Ready to [Build a Windows Presentation Foundation (WPF) Blazor app](https://learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/tutorials/wpf?view=aspnetcore-8.0).
- Add a button in MainWindow, Open a MainWindow instance and show it.
- Open another 3 child windows, then close them.
- Create a memory snapshot, *BlazorWebView* control count is 4, it is memory leak.

### .NET Version

net8.0

### Anything else?

![image](https://github.com/dotnet/aspnetcore/assets/3114959/9d1a1f0b-aa17-4372-bfbd-9cf404169380)

Microsoft.AspNetCore.Components.WebView.Wpf.BlazorWebView	4
	Microsoft.Web.WebView2.Wpf.WebView2	4
		Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager	4
			Action<String>	4
				Microsoft.AspNetCore.Components.WebView.IpcSender	4
					Microsoft.AspNetCore.Components.WebView.Services.WebViewJSRuntime	4
						Microsoft.AspNetCore.Components.WebView.StaticContentHotReloadManager+StaticContentChangeNotifier	4
							Microsoft.AspNetCore.Components.WebView.StaticContentHotReloadManager+ContentUpdatedHandler	4
								Object[]	4
									Microsoft.AspNetCore.Components.WebView.StaticContentHotReloadManager+ContentUpdatedHandler [静态变量 Microsoft.AspNetCore.Components.WebView.StaticContentHotReloadManager.OnContentUpdated]	1

**Comment by javiercn** [comment]
@a44281071 thanks for contacting us.

If a garbage collection of the right generation hasn't happened is perfectly fine for those to still live in managed memory.

See the remarks https://learn.microsoft.com/en-us/dotnet/api/system.gc.collect?view=net-8.0#system-gc-collect(system-int32-system-gccollectionmode-system-boolean-system-boolean) here.

Do this and observe the dump afterwards
```
GCSettings.LargeObjectHeapCompactionMode = GCLargeObjectHeapCompactionMode.CompactOnce;
GC.Collect(2, GCCollectionMode.Forced, true, true);
```

**Comment by a44281071** [comment]
@javiercn Same memory leak. *Microsoft.AspNetCore.Components.WebView.Wpf.BlazorWebView*.
No improvement issues.
Should I publish any demo project? But it's small features with [Build a Windows Presentation Foundation (WPF) Blazor app](https://learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/tutorials/wpf?view=aspnetcore-8.0). Just add a button.

**Comment by javiercn** [comment]
@a44281071 thanks for the additional details.

Are you running under debug? Can you disable hot reload? Taking a second look it seems that HotReloadManager is the root, which is expected.

**Comment by a44281071** [comment]
I publish this project. Run it without debug. It have 8 child process. 
When I open a new MainWindow, It will add a new child process with *Edge WebView2*.
Then I close it, just single window, child process did not restore to the previous number 8.

**Comment by javiercn** [comment]
@a44281071 thanks for the additional details.

I've filed a separate issue for us to investigate in the maui repo, we'll track the investigation there https://github.com/dotnet/maui/issues/22818
