### ISSUE TITLE
Function call from Blazor app gets stuck, works fine from Web API app

### ISSUE THREAD

**Issue by devbaran** [dotnet/aspnetcore#56020]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

I have a .NET 5 class library that I'm using in conjunction with both a Blazor app and a Web API app. Within my Blazor app, I'm calling a function from the class library. The function executes all its steps successfully, but when it reaches the point of returning the result, it seems to get stuck. Even if I try to continue execution in debug mode, it remains stuck at that point, behaving as if the process has terminated.

To troubleshoot, I created a Web API app and defined a demo endpoint within it. From this endpoint, I call the same function from the class library, and it returns the result without any issues.

I'm unable to identify the source of this problem, and one additional challenge is that I'm unable to catch any exceptions that might be occurring during the function call from the Blazor app.

**Additional Information:**

- The class library function executes all its steps without any errors or exceptions.
- The Blazor app is unable to proceed beyond the point where the function should return its result, even in debug mode.
- The same function call from the Web API app works without any issues, returning the result promptly.
- Despite the issue, I'm unable to catch any exceptions that might be occurring during the function call from the Blazor app.

### Expected Behavior

The Blazor app should return the result of the called function to the caller, just as the Web API app does.

### Steps To Reproduce

1. Open the Blazor app.
2. Trigger the function call to the class library.
3. Observe that the function appears to get stuck or hang at the return point.

### .NET Version

8.0.201

### Anything else?

**Rider** 

Runtime version: 17.0.10+8-b1207.12 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

.NET Core v8.0.1 ARM64 (Server GC)

Operating System: macOS Big Sur 14.5 (23F79), running on an M1 chip MacBook
Development Environment: .NET 5 / .NET 8 (Both of .net sdk are installed)

**Comment by javiercn** [comment]
@devbaran thanks for contacting us.

Is this server or webassembly. Please note that .NET 5.0 is out of support, so as a first step we ask that you try and reproduce this issue with a supported version (6.0 at least, 8.0 ideally).
