### ISSUE TITLE
Support type constraints on @typeparam

### ISSUE THREAD

**Issue by neerajbharti** [dotnet/aspnetcore#5603]
This is in regards to the new @typeParam released in 0.6.0 version.
I am not sure if Type Constraints can be defined on the generic type passed to @typeParam.

 If this is something which already existing, can you please direct me to some semantics help. And if it is not there; is there any  plan to support this.

This feature will be very much helpful while developing abstract components which must take "T" of some base type for example.

**Comment by srowan** [comment]
@rynowak Will this issue be mitigated by #5487  ?  I.e. we can just put the generic constraints in the partial class?

**Comment by dazinator** [comment]
Just hit this myself, reduces the value proposition of templated components significantly with this limitation at present.

**Comment by BenGrayAdams** [comment]
Another vote.  I agree value is limited without this...I’d like to allow templated components to render markup that’s common to a family of ViewModels by using properties defined in their base type, but without generic type constraints am unable to do this cleanly.  This shortcoming wouldn't stand out as much if the rest of Blazor wasn't so damn sexy...appreciate what you guys are doing! =)

**Comment by chucker** [comment]
@srowan answer appears to be yes, but only after an explicit build (not at design time). The `.razor.g.cs` files don't have the constraint.

Given these two files:

```razor
@typeparam TItem

@code {
    [Parameter]
    public TItem Foo { get; set; }
}
```

```csharp
public partial class TestComponent<TItem> where TItem : struct
{

}
```

The following will compile: `<TestComponent Foo="1" TItem="int" />`

But once you change the constraint to `where TItem : class` and do a full build, it won't.

>CS0452 The type 'int' must be a reference type in order to use it as parameter 'TItem' in the generic type or method 'TestComponent<TItem>'

So, @OkieCoder1, this may be a feasible workaround for now. You really only need a do-nothing partial class that contains the constraint, and to be aware that at design time, changes to the constraint won't properly be considered.

**Comment by mkArtakMSFT** [comment]
We'll be handling this as part of https://github.com/dotnet/aspnetcore/issues/8433
