### ISSUE TITLE
[SignalR - Java Client] Add support for Automatic Reconnection

### ISSUE THREAD

**Issue by YohanSciubukgian** [dotnet/aspnetcore#56033]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Based on SignalR documentation, the java client doesn't support Automatic Reconnection.
https://learn.microsoft.com/en-us/aspnet/core/signalr/client-features?view=aspnetcore-8.0
![image](https://github.com/dotnet/aspnetcore/assets/30290851/e443e46d-43c9-4219-bbce-275ab0d487ec)

### Describe the solution you'd like

For java clients that could be used with an unstable connection, I would expect the JAVA client to work the same way as the JS client with Automatic Reconnections.
Could you please consider adding this feature to the JAVA client?

### Additional context

Do you have any workaround (maybe based on the JS client feature) to make it reconnect automatically until it could be implemented in the JAVA client itself?

**Comment by BrennanConroy** [comment]
Due of https://github.com/dotnet/aspnetcore/issues/8711

> Do you have any workaround (maybe based on the JS client feature) to make it reconnect automatically until it could be implemented in the JAVA client itself?

Something like:
```
hubConnection.onClosed((e) ->
{
    // consider adding random delay, adding exception handling, etc.
    hubConnection.start();
});

**Comment by YohanSciubukgian** [comment]
Thanks for the quick answer and for the workaround solution.
