### ISSUE TITLE
.NET8 QuickGrid Pagination not working

### ISSUE THREAD

**Issue by GregorySeifert** [dotnet/aspnetcore#56041]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I used the GetStarted example together with the paging example of the github page. The grid displays, but the pagination buttons do not work as in the sample. As project I created a .NET8 Blazor Web App framework as generated by the VS2022 wizard.

### Expected Behavior

When clicking the page buttons, the data in the Quickgrid is updated with the next page.

### Steps To Reproduce

1. create a new project
2. pick Blazor Web Appµ
3. Target .NET8
4. in the home page, paste the code from the getting started page found here: https://aspnet.github.io/quickgridsamples/getstarted
5. add the code from the sample page for paging 
6. Run the code => buttons do not work

@page "/Page2"
@using BlazorQuickGridTest1.Services
@using Microsoft.AspNetCore.Components.QuickGrid

<h3>page2</h3>

<div class="page-size-chooser">
    Items per page:
    <select @bind="@pagination.ItemsPerPage">
        <option>5</option>
        <option>10</option>
        <option>20</option>
        <option>50</option>
    </select>
</div>

<div class="grid">
    <QuickGrid Items="@people" Pagination="@pagination">
        <PropertyColumn Property="@(p => p.PersonId)" Sortable="true" />
        <PropertyColumn Property="@(p => p.Name)" Sortable="true" />
        <PropertyColumn Property="@(p => p.BirthDate)" Format="yyyy-MM-dd" Sortable="true" />
    </QuickGrid>
</div>

<Paginator State="@pagination" />

@code {
    record Person(int PersonId, string Name, DateOnly BirthDate);

    PaginationState pagination = new PaginationState() { ItemsPerPage = 5 };

    IQueryable<Person> people = new[]
    {
        new Person(10895, "Jean Martin", new DateOnly(1985, 3, 16)),
        new Person(10944, "António Langa", new DateOnly(1991, 12, 1)),
        new Person(11203, "Julie Smith", new DateOnly(1958, 10, 10)),
        new Person(11205, "Nur Sari", new DateOnly(1922, 4, 27)),
        new Person(11898, "Jose Hernandez", new DateOnly(2011, 5, 3)),
        new Person(12130, "Kenji Sato", new DateOnly(2004, 1, 9)),
    }.AsQueryable();
}

### .NET Version

.NET8

### Anything else?

![000643](https://github.com/dotnet/aspnetcore/assets/171580603/67aa7d7f-e6fa-484a-8f41-ce840ce9a6ce)
![000644](https://github.com/dotnet/aspnetcore/assets/171580603/95a4838c-ca41-405e-8fc7-30de3b578dd7)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is due to the fact that the Paginator component requires interactivity. But we plan to change it so that it also supports SSR model, which will allow it to also work in statically rendered scenarios: https://github.com/dotnet/aspnetcore/issues/51249

**Comment by GregorySeifert** [comment]
Hi,
my testpages are using interactivity mode?:

program.cs:

using BlazorQuickGridTest1.Components;
using BlazorQuickGridTest1.Services;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
builder.Services.AddRazorComponents()
    .AddInteractiveServerComponents();
builder.Services.AddRazorPages();
builder.Services.AddServerSideBlazor();

// Register the project master service
builder.Services.AddSingleton<ProjectMasterService>();

var app = builder.Build();

// Configure the HTTP request pipeline.
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Error", createScopeForErrors: true);
    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app.UseHsts();
}

app.UseHttpsRedirection();

app.UseStaticFiles();
app.UseAntiforgery();

app.MapRazorComponents<App>()
    .AddInteractiveServerRenderMode();

app.Run();

**Comment by GregorySeifert** [comment]
got it, add @rendermode InteractiveServer to my page :)

**Comment by mingtong** [comment]
> got it, add @rendermode InteractiveServer to my page :)

InteractiveAuto also works.
But I don't know why it wasn't InteractiveWebAssembly, isn't it client interactive?
