### ISSUE TITLE
Reconsider the Platform concept in the new render mode detection API 

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#56047]
Prior to .NET 8 we had the concept of hosting models (Blazor Server, Blazor WebAssembly, Blazor Hybrid), which took a fair amount of explaining for users to understand and choose between. Then in .NET 8 we introduced render modes, which many Blazor are still struggling to understand and rationalize. In .NET 9 as part of the new API for detecting the render mode, we're introducing the new concept of a "platform" which is separate from a render mode. I think we should discuss some more what exactly we mean by a platform in Blazor if we really need this new concept. Traditionally platform is used to refer to the underlying OS, but that's obviously not what we mean in the new API, which has the potential to create confusion. Maybe we should pick a more Blazor specific name, like `RendererType` or `RendererKind`?

**Comment by halter73** [comment]
The plan is to rename `Platform` to `RendererInfo` IIRC.
