### ISSUE TITLE
Compiler error with mixed content in onclick attribute

### ISSUE THREAD

**Issue by panda-eye** [dotnet/aspnetcore#5605]
I have a line in Teachers.cshtml:
`<button onclick="window.location.href = '/teacher/@(teacher.Id)/';">More info...</button>`
After compilation I have the following line in Teachers.g.cs (/obj/Debug/netstandart2.0/Pages/):
`builder.AddAttribute(24, "onclick", (Microsoft.AspNetCore.Blazor.Components.BindMethods.GetEventHandlerValue<Microsoft.AspNetCore.Blazor.UIMouseEventArgs>() + "window.location.href" + " =" + " \'/teacher/" + (teacher.Id) + "/\';" + ()));`
And an error message:

> CS1525	Invalid expression term ")"

**Comment by TPIvan** [comment]
Is threre any intention to correct this bug in near future?
