### ISSUE TITLE
Strange unicode characters added to DOM

### ISSUE THREAD

**Issue by divvjson** [dotnet/aspnetcore#56069]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I bootstrap my Blazor application some strange unicode characters are added to the DOM.

They are only there for a slight moment, then they disappear.

They are inserted as a text node, the characters are &#xFEFF

![hmm](https://github.com/dotnet/aspnetcore/assets/24542784/5e3e0850-b0b4-439e-9812-0d7893ff4e5d)

They are causing issues with my layout since they are taking up space in the DOM, the layout kinda "jumps".

I have no idea what's causing this or how to reproduce it.

I have fully removed the UI component library (FluentUI for Blazor) but the unicode characters are still there.

Anyone have an idea of what could be causing this?

### Expected Behavior

Not having strange unicode characters in the DOM

### .NET Version

8.0.300

### Anything else?

I am using Visual Studio.

**Comment by javiercn** [comment]
@divvjson thanks for contacting us.

Those seem like byte order marks on your file. Not sure how they got in there, but likely they are part of your file, hence why removing other things doesn't eliminate them.

You can use an editor that shows invisible characters to see them and remove them from the file.

**Comment by divvjson** [comment]
OK, so I think I have found the problem.

I have a component which at the very top of the razor file injects IJSRuntime. I remember when I added this line that the compiler complained and said _The 'inject' directive must appear at the start of the line._.

It was indeed added at the start of the line but when I moved it down one line, it stopped complaining and I moved on.

That extra line at the top is what I believe is causing the issue with the strange unicode characters.

So I guess the question now is, why is it complaining that the inject directive is not added at the start of the line?

![1](https://github.com/dotnet/aspnetcore/assets/24542784/18665240-f85d-4fce-b644-73544f193d42)

![2](https://github.com/dotnet/aspnetcore/assets/24542784/273de7bb-4b89-4715-8234-abbd23213c6b)

**Comment by divvjson** [comment]
Here's a gif illustrating the problem. If I set the cursor at the start of the line and hit backspace the error goes away.

However, the unicode characters are still there in the DOM.

Though I am quite sure this very component is causing the problem because if I exclude it from the application tree the unicode characters are not added to the DOM.

![razor](https://github.com/dotnet/aspnetcore/assets/24542784/1c93df7a-a643-46a2-8696-9b0162867208)

**Comment by divvjson** [comment]
OK the issue is now resolved. There was yet another component in the application tree that had an invisible character at the start of the line on line 1.

**It would have been awesome if Visual Studio somehow indicated that there are invisible characters in the file.**

Feel free to close the issue.

**Comment by javiercn** [comment]
@divvjson I believe you can toggle this in VS with the `ViewWhiteSpace` option.

VS Code and many other editors also show this information if you toggle the right setting.
