### ISSUE TITLE
Blazor WASM Msal race condition

### ISSUE THREAD

**Issue by cazac9** [dotnet/aspnetcore#56068]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a Blazor WASM application, which is using Microsoft Auth with Microsoft.Authentication.WebAssembly.Msal(8.0.4).
On my PC everything is working fine, but on test environment I have this strange behaviour. When I press "Login" button on our internal portal, I'm getting redirected to Microsoft login page, after successfull login portal is starting loading and then I'm getting redirected to login again. I'm able to enter site from 2nd or 3rd attempt. 

Browser console shows next error:  "Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
      Authorization failed. These requirements were not met:
      RolesAuthorizationRequirement:User.IsInRole must be true for one of the following roles..."

However I can see GET token request with successfull response. and access token from the response has  correct role value.

Few lines regarding my project:

My csproj has <TrimmerRootAssembly Include="Microsoft.Authentication.WebAssembly.Msal" />

Auth cofigured with next code: 
builder.Services.AddMsalAuthentication<RemoteAuthenticationState, UserAccount>(options =>
{
	builder.Configuration.Bind("AzureAd", options.ProviderOptions.Authentication);
	options.ProviderOptions.Cache.CacheLocation = "localStorage";
	options.ProviderOptions.Cache.StoreAuthStateInCookie = true;
	options.ProviderOptions.AdditionalScopesToConsent.Add("offline_access");
	options.ProviderOptions.DefaultAccessTokenScopes.Add(builder.Configuration["UserScope"]);
	options.ProviderOptions.Authentication.PostLogoutRedirectUri = CommonConsts.WelcomePage;
	options.ProviderOptions.Authentication.RedirectUri = "login-callback";
	options.ProviderOptions.Authentication.NavigateToLoginRequestUrl = false;
	options.ProviderOptions.LoginMode = "redirect";
	options.AuthenticationPaths.LogInFailedPath = CommonConsts.WelcomePage;
	options.AuthenticationPaths.LogInPath = CommonConsts.WelcomePage;
	options.AuthenticationPaths.LogOutSucceededPath = CommonConsts.WelcomePage;
	options.AuthenticationPaths.LogOutPath = CommonConsts.WelcomePage;
}).AddAccountClaimsPrincipalFactory<RemoteAuthenticationState, UserAccount, CustomUserFactory>();

### Expected Behavior

Authorization is working stable

### .NET Version

8

**Comment by halter73** [comment]
> Browser console shows next error: "Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
> Authorization failed. These requirements were not met:
> RolesAuthorizationRequirement:User.IsInRole must be true for one of the following roles..."

Does the browser console show what roles you are missing after the `...`? Usually there's [something there](https://github.com/dotnet/aspnetcore/blob/afa0b365a9bc4a45e3b245903ce3eacfe2658d40/src/Security/Authorization/Core/src/RolesAuthorizationRequirement.cs#L69). It looks like you have an endpoint that has roles required. Usually this is done with something like `[Authorize(Roles = "admin")]` or something like that.

I would look at your `CustomUserFactory.CreateUserAsync`. Is it creating a `ClaimsPrincipal` that is in the roles it needs to be in? You can check what roles your `ClaimsPrincipal` is in using something like this to check if `CreateUserAsync` is intermittently creating users without the 

```csharp
    public override async ValueTask<ClaimsPrincipal> CreateUserAsync(
        UserAccount account,
        RemoteAuthenticationUserOptions options)
    {
        var myClaimsPrincipal = await base.CreateUserAsync(account, options);
        var roleClaimType = myClaimsPrincipal.Identities.First().RoleClaimType;

        foreach (Claim claim in myClaimsPrincipal.Claims)
        {
            if (claim.Type == roleClaimType)
            {
                Console.WriteLine($"Role: {claim.Value}");
            }
        }

        return myClaimsPrincipal;
    }
```

If that doesn't help you figure out what's going on, we'll need a complete repro project to investigate further.
