### ISSUE TITLE
Blazor multiple @page with parameters on Home component results in missing static files

### ISSUE THREAD

**Issue by Liandrel** [dotnet/aspnetcore#56072]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When you create second @page route on Home component with parameters, for example
`@page "/"
@page "/{Test1}/{Test2}"

@code {
    [Parameter]
    public string? Test1 { get; set; }
    [Parameter]
    public string? Test2 { get; set; }
}`

When trying to start the app css/js etc static files are not loading and it results in buggy UI
![image](https://github.com/dotnet/aspnetcore/assets/109763767/55ea8d5f-e4f8-4369-8e73-1daeeef5544c)

When I checked Sources in DevTools bootstrap.min.css is swapped with page source html ?
![image](https://github.com/dotnet/aspnetcore/assets/109763767/ac3f4d97-3d63-49f4-8ab3-daa6877bb803)

This behaviour was present in base Blazor Web App project
.NET 8.0,
Authentication type: none
Configure for https: true,
Interactive render mode: Server,
Interactivity location: Global,
Include sample pages: true,

only thing that was changed is Home.razor with code provided earlier

### Steps To Reproduce

1.Create Blazor Web App project
2.Change Home.razor with provided code,
3.Run application

**Comment by javiercn** [comment]
@Liandrel thanks for contacting us.

Your route `/{Test1}/{Test2}` is likely capturing files. Use `/{Test1}/{Test2:nonfile}`

**Comment by Liandrel** [comment]
Yes, that was it, with :nonfile it works and renders correctly, Thank You, it would be great if  Blazor routing and navigation docs contained info about that tho, It was really hard trying to debug that this was the couse of the problem

**Comment by guardrex** [comment]
@Liandrel ... I'll open a docs issue to get it covered. We do have it in a few buried spots for special scenarios. I'll surface it in the Blazor *Routing and Navigation* article.
