### ISSUE TITLE
NetMaui Blazor + RazorClass Library

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#56071]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/NetMaui-Blazor--RazorClass-Library/10394209)._

---
[regression] [worked-in:before 17.6.3]
Hi,
1. I create a new project . NetMauiBlazor
2. I create a new project in the same solution RazorClassLibrary
3. Build succeed both projects
4. I added reference in . NetMaui project to de RazorClassLibrary
5. I get the issue: 
  **Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1605	Warning As Error: Detected package downgrade: Microsoft.Extensions.Logging.Abstractions from 7.0.1 to 7.0.0. Reference the package directly from the project to select a different version. 
 MauiApp2 -> RazorClassLibrary1 -> Microsoft.AspNetCore.Components.Web 7.0.7 -> Microsoft.AspNetCore.Components 7.0.7 -> Microsoft.AspNetCore.Authorization 7.0.7 -> Microsoft.Extensions.Logging.Abstractions (>= 7.0.1) 
 MauiApp2 -> Microsoft.Extensions.Logging.Abstractions (>= 7.0.0)	MauiApp2	C:\Users\liviup\source\repos\MauiApp2\MauiApp2\MauiApp2.csproj	1**	

[VS2022_1.png](https://aka.ms/dc/file?name=B8cb6fdaec35740dc8636ed296d203b6c638225206181712659_VS2022_1.png&tid=8cb6fdaec35740dc8636ed296d203b6c638225206181712659)

I updated the package Microsoft.Extensions.Logging.Abstractions from 7.0.0 to 7.0.1.
[VS2022_2.png](https://aka.ms/dc/file?name=Bfa5afd17f9044f508f495cedc9063f5d638225207320952426_VS2022_2.png&tid=fa5afd17f9044f508f495cedc9063f5d638225207320952426)

After build, the reference to the package Microsoft.Extensions.Logging.Abstractions downgrade again to 7.0.0

---
#### Mackinnon Buck [MSFT] on 6/16/2023, 10:39 AM: 

(private comment, text removed)
#### Blaine Manock on 6/27/2023, 04:36 AM: 

(private comment, text removed)
#### Harry v on 6/23/2023, 04:51 AM: 

(private comment, text removed)
#### Feedback Bot on 6/25/2023, 11:43 PM: 

(private comment, text removed)
#### Alexander Freistetter on 6/27/2023, 02:59 AM: 

(private comment, text removed)
#### Isaac Borrero on 7/3/2023, 07:48 AM: 

(private comment, text removed)
#### Dylan Snel on 7/12/2023, 01:11 PM: 

(private comment, text removed)
#### jpuebla on 7/14/2023, 04:13 AM: 

(private comment, text removed)
#### Stephen Brown on 7/19/2023, 04:19 AM: 

(private comment, text removed)
#### Ivan Rossouw on 10/8/2023, 03:33 AM: 

(private comment, text removed)

---
#### Blaine Manock solved on 6/20/2023, 03:12 PM, 2 votes: 

<p>Hi <a target='_blank' href="/user/1042144">Mackinnon Buck [MSFT]</a>, I too have encountered this today.</p>
<p>The problem is that <a target='_blank' href="http://Microsoft.AspNetCore.Components.Web">Microsoft.AspNetCore.Components.Web</a> 7.0.7 references Microsoft.Extensions.Logging.Abstractions <strong>7.0.1</strong> (via Microsoft.AspNetCore.Components 7.0.7 and Microsoft.AspNetCore.Authorization 7.0.7) - as <a target='_blank' href="https:///user/1203031">Niculescu Camil Mihai</a> has noted.</p>
<p>Unfortunately, version <strong>7.0.0</strong> of Microsoft.Extensions.Logging.Abstractions is provided by the NET7 SDK (net7-android, net7-ios, net7-maccatalyst, net7.0-windows10.0.19041.0) and has been marked as “IsImplicitlyDefined”, therefore cannot be updated independently.</p>
<p>The current workaround is to downgrade <a target='_blank' href="http://Microsoft.AspNetCore.Components.Web">Microsoft.AspNetCore.Components.Web</a> to 7.0.5, which references Microsoft.Extensions.Logging.Abstractions 7.0.0.</p>

**Comment by javiercn** [comment]
@mkArtak Any reason why this got moved? Seems very old, so I'm going to close it unless we receive new data that this is an issue.

Specially since 7.0 is out of support already.
