### ISSUE TITLE
MapOpenApi() Response.ContentType=null causes garbled characters in Chinese and other languages

### ISSUE THREAD

**Issue by vipwan** [dotnet/aspnetcore#56095]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![image](https://github.com/dotnet/aspnetcore/assets/13956765/5431dd6c-4cb3-44b1-97c6-998d65bafd46)
@captainsafia , 

https://github.com/dotnet/aspnetcore/blob/main/src/OpenApi/src/Extensions/OpenApiEndpointRouteBuilderExtensions.cs
There doesn't seem to be set ContentType to the doc returned
I solved this issue temporarily using middleware, and of course it would be nice to fix this internally
```csharp
internal class OpenApiDocMiddleware
{
    private readonly RequestDelegate _next;
    public OpenApiDocMiddleware(RequestDelegate next)
    {
        _next = next;
    }
    public async Task Invoke(HttpContext context)
    {
        if (context.GetEndpoint()?.Metadata.GetMetadata<IRouteDiagnosticsMetadata>() is { } route &&
            route.Route.EndsWith("{documentName}.json"))
        {
            context.Response.ContentType = "application/json";
        }
        await _next(context);
    }
}
```

### .NET Version

9.0.0-preview.4.24267.6

**Comment by captainsafia** [comment]
@vipwan Thanks for the bug report! Should be a quick fix. PR incoming soon.
