### ISSUE TITLE
Identity based authentication using OpenIdConnect

### ISSUE THREAD

**Issue by mradulmodi** [dotnet/aspnetcore#56108]
I am trying to use OpenIdConnectExtensions code [here ](https://github.com/dotnet/aspnetcore/blob/main/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectExtensions.cs)

`AddOpenIdConnect` provided by the SDK doesn't seem to support using identity and adding `client_assertion` in the request. Is there a plan to introduce support for using identity with SDK. What is the alternate recommended approach for using identity with OpenIdConnect

**Comment by halter73** [comment]
It should be possible to provide an `OnRedirectToIdentityProvider` callback to add the `client_assertion` parameter similar to the workaround presented in https://github.com/dotnet/aspnetcore/issues/51250.

```csharp
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddAuthentication().AddOpenIdConnect(options =>
{
   options.Events.OnRedirectToIdentityProvider = context =>
   {
       context.ProtocolMessage.SetParameter("client_assertion", "something");
       return Task.CompletedTask;
   };
});
```

Once .NET 9 is released, you can use the new `AdditionalAuthorizationParameters` API proposed by that issue.
