### ISSUE TITLE
Add an option to enforce case-sensitive URLs

### ISSUE THREAD

**Issue by Eptagone** [dotnet/aspnetcore#56118]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Currently ASPNET urls are case-insensitive. So, no matter if you use upper or lower characters, you can access to a page anyway.
Example: https://learn.microsoft.com/EN-us/AsPNet/cORe/TEST/tRouBLEsHOoT?view=aspnetcore-8.0

I don't want that. Instead, I prefer to return a 404 or 301 like many other websites do. Also, as I know, for SEO the current behavior could be catastrophic because search engines treat URLs as `case-sensitive` like possible different pages.

Forcing and/or rewriting the URL to lower case is not an option because it restricts the ability to use capital letters when needed as mentioned earlier in this [issue](https://github.com/dotnet/aspnetcore/issues/42625).

### Describe the solution you'd like

Add an option in **RouteOptions** to enforce case-sensitive URLs and return 404 or 301 if needed.

### Additional context

This is an example of what I want to be able to do with a page `/example` and maybe an optional parameter like `/example/{fileId}`:
```log
# Example URL | Expected Response Code
/example < 200
/eXaMPle < 404 or 301|/example
/EXAMPLE < 404 or 301|/example
/example/Rx45Z < 200
/eXAmple/Rx45Z < 404 or 301|/example/Rx45Z
```

**Comment by javiercn** [comment]
@Eptagone thanks for contacting us.

Routing has historically been case-insensitive and it's not trivial to make it case-sensitive as that choice is baked in many places fundamentally in the framework.

If you want to ensure that your URLs are case-sensitive, then you can use a middleware to check the request and redirect to a lowercase URL in that situation or return a 401 if you prefer.
