### ISSUE TITLE
SVG not rendering properly with Blazor

### ISSUE THREAD

**Issue by mdegroot71** [dotnet/aspnetcore#5613]
_Originally posted by @mdegroot71 in https://github.com/aspnet/Blazor/issue_comments#issuecomment-430270522_

I am having the same issues.  I've taken all of the same CSS, Javascript and produced HTML from Blazor, popped it into a static HTML page and ran it.  The SVG scales as it should without any workarounds.  I'm using Chrome.  When I run it with Blazor, the SVG behaves in a weird way.  This isn't a CSS issue.  This is definitely a rendering issue b/c no matter how I inject the SVG, it still does not behave as if Blazor was not present.

**Comment by ElderJames** [comment]
In my project, I can render the svg icon in components.
I use HttpClient to download the file and render it by converting to MarkupString.
https://github.com/ElderJames/ant-design-blazor/blob/master/components/icon/AntIcon.razor
https://ant-design-blazor.gitee.io/

**Comment by mkArtakMSFT** [comment]
Closing as we will be tackling this as part of https://github.com/dotnet/aspnetcore/issues/18271
