### ISSUE TITLE
Blazor WebAssembly does not reload dotnet.js after .NET 8 update

### ISSUE THREAD

**Issue by Forestbrook** [dotnet/aspnetcore#56168]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We have a severe caching problem after upgrading to .NET 8.

We followed the instructions described in [Append a query string to the Blazor script tag](https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly-caching/http-caching-issues?view=aspnetcore-8.0#append-a-query-string-to-the-blazor-script-tag)

But it looks like blazor.webassembly.js is loading some other scripts, like:
- dotnet.js
- dotnet.native.8.0.6.ec3c6v5ch4.js
- dotnet.runtime.8.0.6.cfhqwq2l7j.js

The last two scripts are no problem, because they include a version number, but `dotnet.js` does NOT include a version number. This way, after every update an OLD version of `dotnet.js` is loaded from cache, causing errors preventing our blazor app to start.

This is a huge problem for us. We have 10.000 users and a lot of them calling our helpdesk after every update because "the website does not work anymore".

1. PLEASE add a version number for `dotnet.js` in the next update to make sure the correct version of `dotnet.js` is loaded!

2. Is there a way we can add a version number for dotnet.js now?

### .NET Version

8

### Anything else?

As a workaround we added a link to the "loading..." text to load the website with a Clear-Site-Data="cache" header. The user can click that link when the website does not load to reload with a cleared cache.

This works fine on Edge and Chrome (both Windows and Apple), but on Safari you still need to refresh several times.
On Firefox we get a strange error: a 404 on loading dotnet.js.
Any suggestions how to solve these issues?

**Comment by Forestbrook** [comment]
@javiercn the app is Asp.NET Core hosted.
We added the `?v=11` to `blazor.webassembly.js` in index.html.
If we look in Chrome with F12 at sources, we do not see any options or version numbers for `dotnet.js`:
![BlazorScripts](https://github.com/dotnet/aspnetcore/assets/19266638/57caaa39-9088-4cb4-bd96-748f2eb814fd)

We are having issues after upgrading to .NET 8.
Could it be that something had to be added after upgrading which is missing?

**Comment by javiercn** [comment]
@Forestbrook the location you should be looking at is in the response headers from the request. There should be a no-cache directive there.

**Comment by javiercn** [comment]
For reference, just tried with a new blazor web project with webassembly.

![image](https://github.com/dotnet/aspnetcore/assets/6995051/9aaf95d0-b016-45df-a4e2-0085516a81ba)

**Comment by javiercn** [comment]
@Forestbrook If you determine that the header is not being sent. Please share your `Program.cs` for your asp.net core host, so that we can try and determine if there's something that's not correctly configured in that case.

**Comment by Forestbrook** [comment]
@javiercn I think I found the cause.
This is a large Blazor project started 4 years ago.
I always updated it to the latest .NET version, but the asp.net core host has still a Program.cs and a Startup.cs.
In the Program.cs I see at CreateHostBuilder: `Host.CreateDefaultBuilder(args)`

We have another Blazor web assembly project with the new startup structure.
In that project I see in Program.cs: `WebAssemblyHostBuilder.CreateDefault(args);`

When I run the new app and do a refresh I see in the debug output dotnet.js reloading
When I run the old app and do a refresh I see in the debug output dotnet.js NOT reloading, only when I do a hard refresh with ctrl-F5.

I will update next week the old app to use the new startup structure in the asp.net core host with only Program.cs and the WebAssemblyHostBuilder.CreateDefault to see if this solves the problem.

**Comment by javiercn** [comment]
@Forestbrook Thanks for the additional details.

Could you share a `censored` version of the old project Startup where you are having the issue? We would like to get a peek and see if something broke across version updates and we are not setting the headers appropriately with older configurations.

**Comment by Forestbrook** [comment]
> @Forestbrook Thanks for the additional details.
> 
> Could you share a `censored` version of the old project Startup where you are having the issue? We would like to get a peek and see if something broke across version updates and we are not setting the headers appropriately with older setups.
> 
> It's important for us not to regress cases where you update the target framework.


[Startup.zip](https://github.com/user-attachments/files/15858127/Startup.zip)
Here it is. Nothing to censor, but I'm using some custom extensions, so let me know if something needs more clarification.

**Comment by javiercn** [comment]
@Forestbrook thanks for the additional details.

In your case this was the issue. At some point you must have reordered these lines and in doing so, the static files middleware has served the files instead of Blazor, which doesn't add the logic that Blazor includes to avoid caching issues.

```csharp
app.UseStaticFiles();
app.UseBlazorFrameworkFiles();
```

**Comment by Forestbrook** [comment]
Thank you @javiercn, I can confirm this solved the problem.

So the correct order is:
```
app.UseBlazorFrameworkFiles();
app.UseStaticFiles();
```
Mind that I had to do a hard refresh with ctrl-F5 one time, because dotnet.js was still in cache from the previous test. But after that dotnet.js was always reloaded on startup and on a soft refresh (F5).
