### ISSUE TITLE
Produces generic variants of `ProducesProblem` extension methods

### ISSUE THREAD

**Issue by mikekistler** [dotnet/aspnetcore#56178]
## Background and Motivation

The `ProducesProblem` extension method can be specified on a `RouteHandlerBuilder` to specify that the route handler may return a ProblemDetails response. But unlike similar extension methods to add endpoint metadata, e.g. `WithDescription` or `WithTags`, the `ProducesProblem` extension method is not supported on `RouteGroupBuilder`. Since nearly every operation can fail in some way or other, it seems desirable to be able to easily mark all route handlers in a group as potentially returning ProblemDetails, and doing this with the `ProducesProblem` method on the `RouteGroupBuilder` is the most natural way to do this.

## Proposed API

```diff
// Assembly: Microsoft.AspNetCore.Routing

namespace Microsoft.AspNetCore.Http;

public static class OpenApiRouteHandlerBuilderExtensions
{
+	public static TBuilder ProducesProblem<TBuilder>(this TBuilder builder, int statusCode, string? contentType = null) where TBuilder : IEndpointConventionBuilder { }
+	public static ProducesValidationProblem<TBuilder>(this TBuilder builder, int statusCode = StatusCodes.Status400BadRequest, string? contentType = null) where TBuilder : IEndpointConventionBuilder { }
}
```

## Usage Examples

```csharp
var app = WebApplication.Create();

var todos = app.MapGroup("/todos")
	.ProducesProblem(statusCode: 500, "application/json+problem");
```

**Comment by amcasey** [comment]
[API Review]

No objections in principle.

Some notes from [last time](https://github.com/dotnet/aspnetcore/issues/41428):
> Remove the MapGroup-supporting TBuilder overloads for Produces/ProducesProblem/ProducesValidationProblem/Accepts because people don’t need them on groups.
> we can always add the Produces/ProducesProblem/ProducesValidationProblem/Accepts overloads

We now think our previous decision may have been over-cautious.

We still don't have reasons (other than consistency) to update `Produces` and `Accepts`.

PR Approved!

```diff
// Assembly: Microsoft.AspNetCore.Routing

namespace Microsoft.AspNetCore.Http;

public static class OpenApiRouteHandlerBuilderExtensions
{
+	public static TBuilder ProducesProblem<TBuilder>(this TBuilder builder, int statusCode, string? contentType = null) where TBuilder : IEndpointConventionBuilder { }
+	public static TBuilder ProducesValidationProblem<TBuilder>(this TBuilder builder, int statusCode = StatusCodes.Status400BadRequest, string? contentType = null) where TBuilder : IEndpointConventionBuilder { }
}
```
