### ISSUE TITLE
WsFed Authentication Broken when using Lax for Correlation Cookie

### ISSUE THREAD

**Issue by pcibraro** [dotnet/aspnetcore#56195]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

WsFed authentication fails with the error "AuthenticationFailureException: Correlation failed" when the Identity Provider (e.g. Microsoft Entra ID) submits the response with the authentication token. The WsFed authentication middleware relies on the correlation cookie for encrypting the wctx parameter with the return url. That cookie only works with samesite policy equal to "none". However, that cookie won't be passed by the browser from the Identity Provider when the samesite policy is set to "lax" so the application breaks. This works with an ugly workaround that intercepts the redirection to the Identity Provider and sends the wctx parameter as plain text with no encryption. As the wctx is not encrypted, the correlation cookie is not needed anymore.

### Expected Behavior

User should be authenticated in a browser with (third-party cookies restrictions enabled)[https://developers.google.com/privacy-sandbox/3pcd].  

### Steps To Reproduce

https://github.com/pcibraro/wsfedlax/blob/23ef60f563e81ffd6004e123da0843f932cdc788/Startup.cs#L37

### Exceptions (if any)

AuthenticationFailureException: Correlation failed

### .NET Version

8

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We recommend using SameSiteMode.None for correlation cookies. But if you have to use Lax, the workaround will do the trick.

**Comment by pcibraro** [comment]
SameSite.None will be unsupported in Chrome starting in 2025.
