### ISSUE TITLE
User Login Session could not maintain in Blazor Client Server Interactive Auto render mode.

### ISSUE THREAD

**Issue by manoj321** [dotnet/aspnetcore#56203]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a blazor client server project configured with interactive auto mode for performance purpose and need to keep user login session, have tried session or cookies and found session and cookies can not be accessible in pre rendering mode as JS interop not available this time. I don't want to make server rendering to fix this. I have created user claim based identity and kept used details in it but on redirecting page to dashboard from user login user identity(authentication state) in my custom authentication class became reset. I have tried middleware things but still no luck, how MS has made it small things very complicated in blazor.

### Expected Behavior

either user authentication state in my custom authentication provider class should persist and session or cookies should be accessible in pre rendering as I have to show user based data on page load without showing any loader there. state only persists if I kept it as singleton but it should be scoped or transient to make it user wise session data.

### .NET Version

.Net Core 8 Blazor Razor pages

**Comment by javiercn** [comment]
@manoj321 thanks for contacting us.

It's not clear to us what you are trying to achieve. When you talk about session, do you mean `window.sessionStorage`?

Assuming that's the case, that will never be available during prerendering.

If you have setup a cookie for your client, then you should be able to access it during prerendering through the HttpContext.

**Comment by manoj321** [comment]
create cookie is also not supporting in interactive mode pre rendering, please suggest the correct way to achieve maintain user login session state in pre rendering so same details will be available on next page under onintializedasync event of razor page.

**Comment by manoj321** [comment]
When I am trying to set cookies getting error "System.InvalidOperationException: Headers are read-only, response has already started."

**Comment by manoj321** [comment]
I am trying to set cookie using js on login button click and trying to get same on next page in oninitializedasync event , this cookie should be persistent unless user logs out. so I can access user details using cookie anywhere on different pages in oninitializedasync event.

**Comment by javiercn** [comment]
@manoj321 thanks for the additional details.

How are you setting the cookie, is it for the same domain? You mention a redirect, and maybe what you are trying to accomplish is not possible.

Keep in mind that you can't access any form of storage across domains, so depending on what you are trying to accomplish it might not be possible, or you might need to find a different way.

**Comment by manoj321** [comment]
Thanks team, I could now create, access, authenticate and remove my application user cookie from client side js, thanks for your suggestion. this one is the only integration works with blazor interactive auto render mode client server app.

**Comment by slynch401k** [comment]
@manoj321 do you have a sample repo. I have wasted days on this.  All I want to do is session like webforms. Everyday I get bogged down on gotcha's.
