### ISSUE TITLE
Build in AuthenticationStateProvider breaks after trimming

### ISSUE THREAD

**Issue by iits-timon-holzhaeuser** [dotnet/aspnetcore#56207]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Just tried the new API from #52769 and replaced my implementation with it.
After the trimming during dotnet publish I get an exception as soon as the app tries to hand over to WebAssembly:
![Screenshot 2024-06-12 205246](https://github.com/dotnet/aspnetcore/assets/139224358/51d8e694-deca-4654-9898-cca3d3376c39)

May relate to #52947 as I noticed that the `AuthenticationStateData` is using a `IList<KeyValuePair<string, string>>` but that is only my wild guess.

I'm **not** using the JSON Source Code Generation Serialization

After removing this line on client:
```
builder.Services.AddAuthenticationStateDeserialization();
```
And this line on the server side:
```
.AddAuthenticationStateSerialization(options => options.SerializeAllClaims = true)
```

The app worked again as expected.

### Expected Behavior

The handover to Web Assembly should work flawless.

### .NET Version

9.0.0-preview.5.24306.7

**Comment by mguinness** [comment]
Also try adding the following to `PropertyGroup` section in the `csproj` file.

`<_ExtraTrimmerArgs>--keep-metadata parametername</_ExtraTrimmerArgs>`

**Comment by iits-timon-holzhaeuser** [comment]
This fixed the issue, thanks 🎉 Added the Property to the client project, and now it works as expected.

So, most likely this will be fixed by PR https://github.com/dotnet/runtime/pull/102850? Or is this the PR which made the _ExtraTrimmerArgs possible?

**Comment by mguinness** [comment]
The PR should obliviate the need for `_ExtraTrimmerArgs `, maybe @sbomer can clarify further.

**Comment by halter73** [comment]
I'm reopening because while there are workarounds, we want to make sure nothing is over-trimmed in the default configuration.
