### ISSUE TITLE
Properties with the `[Required]` attribute should be required in the generated OpenAPI document

### ISSUE THREAD

**Issue by mikekistler** [dotnet/aspnetcore#56212]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

A property of a class or record that has the `[Required]` attribute is currently not a required property of the schema produced by the .NET 9 OpenAPI document generation feature.

### Expected Behavior

A property with the `[Required]` attribute should be a required property of the OpenAPI schema.

### Steps To Reproduce

Not minimal, but there is a recreate in the "Schemas" section of my [aspnet-openapi-examples](https://github.com/mikekistler/aspnet-openapi-examples) project.

### .NET Version

9.0-preview4

**Comment by KennethHoff** [comment]
Iirc, System.Text.Json does not respect these attributes; does Asp.Net Core "override" it so that it does?

If it does, then this makes sense.

If it doesn't, then this doesn't sound like a good change.
