### ISSUE TITLE
asp-append-version only works for StaticFiles in wwwroot

### ISSUE THREAD

**Issue by boggye** [dotnet/aspnetcore#56224]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There is already an issue, https://github.com/dotnet/AspNetCore.Docs/issues/25744, that unfortunately has been classified as "doc-bug".

All the details are included in issue #25744 and I am not going to repeat them here. I attempted to re-open the other issue but it got no attention.

### Expected Behavior

See: https://github.com/dotnet/AspNetCore.Docs/issues/25744

### Steps To Reproduce

See: https://github.com/dotnet/AspNetCore.Docs/issues/25744

### .NET Version

8.0.301

### Anything else?

https://github.com/dotnet/AspNetCore.Docs/issues/25744

**Comment by javiercn** [comment]
@boggye thanks for contacting us.

You should be able to implement your own `IFileVersionProvider`, replace ours and use whatever file provider you want to look in a different location.

**Comment by boggye** [comment]
Don't you think this is a bug?
