### ISSUE TITLE
Connection Close Behavior on HTTP1.0 Requests

### ISSUE THREAD

**Issue by xiaozhao018** [dotnet/aspnetcore#56223]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

https://github.com/dotnet/aspnetcore/blob/83573c72d12e1c2018805bc5d461d730bcb9dcc4/src/Servers/HttpSys/src/RequestProcessing/Response.cs#L406

> if (requestVersion <= Constants.V1_0 // Http.Sys does not support "Keep-Alive: true" or "Connection: Keep-Alive"

The comment in the code indicates http.sys does not support "Connection: Keep-Alive". However, we certainly see that header got to work in IIS, so the comment might be wrong. Thus, we want to change the behavior so that it aligns with IIS.

The reason we want to change this behavior on the server-side is that we don't want to keep closing connections on every request for http1.0, that will increase TLS costs on our end for subsequent re-connects. Given http1.0 traffic is not trivial amount.

### Expected Behavior

If the request is http1.0 AND the request contains "Connection: keep-alive", we also send the "Connection: keep-alive" header in the response.

### Steps To Reproduce

Send http 1.0 request using curl to ASP.NET endpoint with "Connection: keep-alive" header
> curl.exe --http1.0 -i <ASP.NET endpoint uri> -H "Connection: keep-alive"

From the response, you'll see the "Connection: close" header.

### .NET Version

6.0.131

**Comment by BrennanConroy** [comment]
> Given http1.0 traffic is not trivial amount

Why do you have a non-trivial amount of http1.0 traffic?

**Comment by xiaozhao018** [comment]
> > Given http1.0 traffic is not trivial amount
> 
> Why do you have a non-trivial amount of http1.0 traffic?

I guess it's just because there are a lot of http1.0 clients sending the requests. We collected the data based on our service's telemetry.

**Comment by adityamandaleeka** [comment]
Reopening this for servicing.

**Comment by adityamandaleeka** [comment]
This went in for September on 6.0 and 8.0
