### ISSUE TITLE
Server side Blazor + Paste large amount of text into text area with binding = Disconnection of client

### ISSUE THREAD

**Issue by MarkStega** [dotnet/aspnetcore#5623]
I have a server side execution Blazor app that is displaying a text area with a simple 'bind="@backingProperty"'. If I paste moderate amounts of text into the text area everything functions as it should. However, if I paste a large amount of text (it happens to be a base64 representation of an image in some html) then the connection is closed with the following error appearing:

```
Error: Connection disconnected with error 'Error: Server returned an error on close: Connection closed with an error.'. blazor.server.js:16:6839
	I</e.prototype.log https://localhost:44379/_framework/blazor.server.js:16:6839
	P</e.prototype.stopConnection/</< https://localhost:44379/_framework/blazor.server.js:16:27531
	a/</< https://localhost:44379/_framework/blazor.server.js:16:1652
	a/< https://localhost:44379/_framework/blazor.server.js:16:970
	s/< https://localhost:44379/_framework/blazor.server.js:16:697
	s https://localhost:44379/_framework/blazor.server.js:16:474
	P</e.prototype.stopConnection https://localhost:44379/_framework/blazor.server.js:16:27424
	P</e.prototype.startInternal/</</this.transport.onclose https://localhost:44379/_framework/blazor.server.js:16:23753
	U</e.prototype.connect/</</</i.onclose https://localhost:44379/_framework/blazor.server.js:16:20576

Blazor 0.6.0
Firefox 63.0
Window 10 Pro x64
IIS Express hosted server side Blazor

**Comment by Styx8888** [comment]
How to do it using .netcore 3.0 and blazor ? 

Is there any workaround for this using .net core 3.0 ?
I tried something like below, but it is not working:

app.UseEndpoints(endpoints => {
endpoints.MapBlazorHub(o =>
{
o.ApplicationMaxBufferSize = 92233720; // larger size
o.TransportMaxBufferSize = 92233720; // larger size
});

                           endpoints.MapFallbackToPage("/_Host");
        });

**Comment by tarek1243** [comment]
had the same issue 
adding this to the startup fixed it for me 

using Microsoft.AspNetCore.SignalR;
..........
///increase size of textarea accepted value  value
            services.Configure<HubOptions>(options =>
            {
                options.MaximumReceiveMessageSize = null;
            });

**Comment by JvanderStad** [comment]
> I am also seeing this error if I put 31085 chars in a textarea with a bind property in blazor server-side. If i put 31084 chars it works, anything higher i see the same error.
> 
> 31085 chars is not much, if you write a blog article in a textarea it will exceed that probably.
> 
> Any solution or workaround for that?

Max size I can paste is **16290** chars.

**Comment by JvanderStad** [comment]
This fixed my problem:

```c#
services
	.AddServerSideBlazor()
	.AddCircuitOptions(o =>
	{
		var env = services.GetSingleton<IWebHostEnvironment>();
		if (env.IsDevelopment())
		{
			//Details als we aan het debuggen zijn
			o.DetailedErrors = true;
		}
	})
	.AddHubOptions(x => x.MaximumReceiveMessageSize = 102400000);
```

**Comment by Aculeo** [comment]
Can confirm the comment above worked for me as well. This seems like a pretty big issue.

I have a razor page with a decently long table (79 rows), and for each row I added a razor component, this was enough to make the request 33KB and I got this error, took me an hour to figure out what is happening (initially thought my component was broken).

**Comment by sven5** [comment]
While increasing the buffer size is a valid workaround there still is a huge problem: We see high latency when sending "big" data. 
I see a delay of about ~10 seconds with a message size of about 678kb. This is really an issue.

**Comment by TanayParikh** [comment]
Hello, thanks for contacting us. This issue was also discussed as part of https://github.com/dotnet/aspnetcore/issues/30291, and we added a sample app to document working with large text areas in Blazor:

https://github.com/aspnet/samples/tree/main/samples/aspnetcore/blazor/InputLargeTextArea
