### ISSUE TITLE
.NET Core 8 cookie value getting escaped

### ISSUE THREAD

**Issue by saurav-milestone** [dotnet/aspnetcore#56256]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have an api which I migrated from .NetFramework to .Net 8.

The API returns a string `a,b`. While the string value is properly stored in .Net Framework. In .net core 8, it is getting replaced with `a%2cb`.

I have appended the cookie using

`cookieValue = "a,b";`
`CookieOptions cookieOptions = new()`
`{`
`    Expires = DateTime.Now.AddYears(1),`
`    Secure = true`
`};`
`HttpContext.Response.Cookies.Append("test", cookieValue, cookieOptions)`

I was expecting a,b to be set in the browser. Is this a bug in .Net core 8?

### Expected Behavior

Cookie should be created as `a,b`.

### Steps To Reproduce

Create a simple API and add cookie using the below code.

`cookieValue = "a,b";`
`CookieOptions cookieOptions = new()`
`{`
`    Expires = DateTime.Now.AddYears(1),`
`    Secure = true`
`};`
`HttpContext.Response.Cookies.Append("test", cookieValue, cookieOptions)`

### .NET Version

8

**Comment by amcasey** [comment]
I don't think `cookie-value` is allowed to contain a comma?

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#cookie-namecookie-value

Seems more like a bug in Framework that got fixed in Core.

**Comment by amcasey** [comment]
@saurav-milestone This seems by-design, but maybe you could say more about what you're trying to accomplish and why you expected it to work?
