### ISSUE TITLE
JS interop with event named "close" breaks Blazor 8.0 event handling

### ISSUE THREAD

**Issue by cookston** [dotnet/aspnetcore#56255]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Issue with custom events (as outlined in https://learn.microsoft.com/en-us/aspnet/core/blazor/components/event-handling?view=aspnetcore-8.0#custom-event-arguments-1)

The issue can be easily reproduced by using `customEvent.js` to register a custom event named 'close", e.g. 

``` js
Blazor.registerCustomEventType('close', {
    createEventArgs: () => { return {}; }
});
```

And of course adding this to index.html:

``` html
    <script src="_framework/blazor.webassembly.js"></script>
    <script src="scripts/customEvent.js"></script>
```
Then a console error appears as: 

```
Error: The event 'close' is already registered.
    at Object.registerCustomEventType (blazor.webassembly.js:1:37172)
    at customEvent.js:54:8
```

Also no other custom events will register successfully (meaning event handling occurs but data is not received).

This was not an issue in Blazor 7.0 but is new in Blazor 8.0.  What are the reserved custom event names now in Blazor 8.0?

### Expected Behavior

No error or documentation to explain reserved events.

### Steps To Reproduce

The issue can be easily reproduced by using `customEvent.js` to register a custom event named 'close", e.g. 

``` js
Blazor.registerCustomEventType('close', {
    createEventArgs: () => { return {}; }
});
```

And of course adding this to index.html:

``` html
    <script src="_framework/blazor.webassembly.js"></script>
    <script src="scripts/customEvent.js"></script>
```
Then a console error appears as: 

```Error: The event 'close' is already registered.
    at Object.registerCustomEventType (blazor.webassembly.js:1:37172)
    at customEvent.js:54:8```


### Exceptions (if any)


```Error: The event 'close' is already registered.
    at Object.registerCustomEventType (blazor.webassembly.js:1:37172)
    at customEvent.js:54:8```


### .NET Version

8.0.5

### Anything else?

_No response_

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. You're right, the `close` event got added during .NET 8. To find the complete list of reserved event names, you can take a look at https://github.com/dotnet/aspnetcore/blob/main/src/Components/Web.JS/src/Rendering/Events/EventTypes.ts.
Please make sure you pick the appropriate release branch that you're working on to find the correct version.

@guardrex not sure if we have this documented or not, but if not, it may be worth having a section in the custom event args docs on this.
