### ISSUE TITLE
Why @ref or ElementReference always has a value after first set value into it and when it does not rendered throw an exception?

### ISSUE THREAD

**Issue by NaserParhizkar** [dotnet/aspnetcore#56250]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

As you can see in the following code @ref here which is a InputText component after first render always has value even when I don't want render it in the page 

```
<div>
    <input type="button" style="margin:5px;" @onclick="@(() => flag = false)" value="Hide Input" />
    <input type="button" style="margin:5px;" @onclick="@(() => flag = true)" value="Show Input" />
</div>

<div>
    <input type="button" style="margin:5px;" @onclick="focus" value="focus" />
    @if (flag)
    {
        <InputText @ref="inTextElement" @bind-Value="textValue" />
    }
</div>

@code {
    InputText inTextElement;
    string textValue;
    bool flag = true;

    async Task focus()
    {
        if (inTextElement.Element.HasValue)
        {
            await inTextElement.Element.Value.FocusAsync();
        }
    }
}

```

### Expected Behavior

I expect Element.HasValue will be false when it does not rendered in the page

```
   async Task focus()
   {
       if (inTextElement.Element.HasValue)
       {
           await inTextElement.Element.Value.FocusAsync();
       }
   }
```

### .NET Version

8.0.0.2

**Comment by javiercn** [comment]
@NaserParhizkar thanks for contacting us.

Element references are values and we only set them when the element renders. If the element doesn't render, we don't set it to a default value again. 

That's something your app needs to do if its conditionally rendering the element, otherwise we would need to reset all the elements on every render which would incur on a perf-hit.

**Comment by NaserParhizkar** [comment]
I think prevent to raise an exception is better than to have much attention on perf-hit and consequently loose the reliability.
