### ISSUE TITLE
Blazor web app auto mode stop working some times.

### ISSUE THREAD

**Issue by itkunalce** [dotnet/aspnetcore#56282]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Some time it gives error like this

AggregateException_ctor_DefaultMessage (Root component type 'Fbnt.SharedRCL.Components.Layout.Shared.HeaderControl' could not be found in the assembly 'Fbnt.SharedRCL'.)

at Jn (dotnet.runtime.8.0.3.76cp6ozpzf.js:3:31614)
at xl (dotnet.runtime.8.0.3.76cp6ozpzf.js:3:182162)
at 00b217ca:0x1fa8f
at 00b217ca:0x1bf5a
at 00b217ca:0xf141
at 00b217ca:0x1e7a9
at 00b217ca:0x1ef9f
at 00b217ca:0xcfbb
at 00b217ca:0x4412f
at e. (dotnet.runtime.8.0.3.76cp6ozpzf.js:3:215234)

For which I need to clear cache and then it start working.

I need to do it manaully. 

Till that it stop working.

### Expected Behavior

It should work always..

my website is emi-calculator.co.in

I can tell my general user to if you get error just clear cashe...

### .NET Version

8.0.3

**Comment by itkunalce** [comment]
![image](https://github.com/dotnet/aspnetcore/assets/46489996/a1fc9d39-a8ed-49bf-b63f-935052df27f4)

**Comment by javiercn** [comment]
@itkunalce thanks for contacting us.

Does this happen only in production or in development too? Have you tried disabling trimming? `<PublishTrimmed>false</PublishTrimmed>`

**Comment by itkunalce** [comment]
On webassembly it works currectly in development but on live publish it always give this error

you can check on www.emi-calculator.co.in

Error: AggregateException_ctor_DefaultMessage (Root component type 'Fbnt.SharedClient.Components.Layout.Shared.HeaderControl' could not be found in the assembly 'Fbnt.SharedClient'.)
    at Jn (dotnet.runtime.8.0.3.76cp6ozpzf.js:3:31614)
    at xl (dotnet.runtime.8.0.3.76cp6ozpzf.js:3:182162)
    at 00b217ca:0x1fa8f
    at 00b217ca:0x1bf5a
    at 00b217ca:0xf141
    at 00b217ca:0x1e7a9
    at 00b217ca:0x1ef9f
    at 00b217ca:0xcfbb
    at 00b217ca:0x4412f
    at e.<computed> (dotnet.runtime.8.0.3.76cp6ozpzf.js:3:215234)

**Comment by itkunalce** [comment]
> @itkunalce is your library lazy loaded?

what ever in default 8.0.3 have I have that setting.

**Comment by javiercn** [comment]
@itkunalce thanks for the additional details.

That likely points out to a trimming error as it seems is failing to find the constructor, which might mean it has been trimmed away.

As a first step, please upgrade to the latest 8.0.x release and disable trimming within your client project via `<PublishTrimmed>false</PublishTrimmed>`

**Comment by itkunalce** [comment]
same error with <PublishTrimmed>false</PublishTrimmed>

**Comment by itkunalce** [comment]
Just my thought

I have HeaderControl in MainLayout which is not set with any interactivity mode...

and web assembly try to access that headercontrol may be gives error ?

**Comment by itkunalce** [comment]
[Fbnt.Maui-DemoTest.zip](https://github.com/user-attachments/files/15897961/Fbnt.Maui-DemoTest.zip)

If you can check this code

**Comment by javiercn** [comment]
@itkunalce your package is not up to date.

```
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.0" />
```

That needs to be `8.0.5`.

**Comment by itkunalce** [comment]
Ok Will Update

**Comment by halter73** [comment]
I also noticed that `HeaderControl.razor` is in the `Fbnt.SharedRCL` project. Not `Fbnt.SharedClient` where `Fbnt.SharedClient` looking. I recommend running `git clean -xdf` to clear out the `bin/` and `obj/` folders and rebuilding. You might also need to add a project reference to `Fbnt.SharedRCL` from `Fbnt.SharedClient` to get it to rebuild.

**Comment by itkunalce** [comment]
@javiercn 

> That needs to be 8.0.5.

This is also not worked..

@halter73 Yes previously `HeaderControl.razor` is in `Fbnt.SharedClient` so I just move all layout and it component from `Fbnt.SharedClient` to `Fbnt.SharedRCL` 

Now it change the error to `Root component type 'Fbnt.SharedClient.Components.Pages.Home' could not be found in the assembly 'Fbnt.SharedClient'.`

So I have just create step by step all setup again in different solution and it start working...

So I am closing this issue as I don't know what exact reason and exact solution

you can check that [www.emi-calculator.co.in](https://www.emi-calculator.co.in)

Thanks for your valuable time.
