### ISSUE TITLE
When calling httpclient in injecting func

### ISSUE THREAD

**Issue by wisamidris7** [dotnet/aspnetcore#56306]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

```c#
services.AddScoped(e =>
{
     HttpClient client = new HttpClient();
     return AsyncContext.Run(() => client.GetAsync("some-route"));
});
```

This is code uses Nito.AsyncEx for async and await and the problem is only in webassembly
I know that looking something not clean but this code changed a lot in my code and made it cleaner from outside but not inside.

This is the error that appeared

![image](https://github.com/dotnet/aspnetcore/assets/104096256/db9bbc66-b9b7-4550-84f5-0342ffccbbc3)
![image](https://github.com/dotnet/aspnetcore/assets/104096256/b8ff9764-a629-4929-a0ab-aeb0375bfd98)

So can you give me a solution for this issue.
Thanks!

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
It looks like the `AsyncContext.Run` method from the referenced library has a blocking code and that's what is causing the error. Browsers don't permit blocking on the UI thread hence it won't be possible to do this in Web Assembly.

**Comment by halter73** [comment]
It seems like the purpose of blocking is to make an `HttpClient` that's retrieved asynchronously available from DI. We'd recommend registering an async factory service with a method like `Task<HttpClient> GetHttpClientAsync()` for this purpose. Or you could directly register `Task<HttpClient>` as a service if you want something quick and dirty.

**Comment by wisamidris7** [comment]
Thanks!
