### ISSUE TITLE
How to send a Microsoft Identity Platform sign in request?

### ISSUE THREAD

**Issue by sam-wheat** [dotnet/aspnetcore#56302]
I followed [this document](https://learn.microsoft.com/en-us/entra/identity-platform/v2-protocols-oidc#send-the-sign-in-request) for instructions on how to send a sign-in request and I am getting an error with state as discussed below.

My company wants to implement an internal portal where users are able to navigate to the portal and use it without logging in.  If they choose to log in at a later time they will have access to various protected features. 

To accomplish this I commented out the section of code shown below:

    // Comment lines below to prevent user from being logged in immediately.
    //builder.Services.AddAuthorization(options =>
    //{
    //    options.FallbackPolicy = options.DefaultPolicy;
    //});

I created a control with a sign in button and the handler looks like this:

	private async Task SignIn()
	{
		 string callbackpath = System.Web.HttpUtility.UrlEncode(NavigationManager.BaseUri.Substring(0, NavigationManager.BaseUri.LastIndexOf("/"))) + azureConfig.CallbackPath;
		 string loginURL = $"https://login.microsoftonline.com/{azureConfig.TenantId}/oauth2/v2.0/authorize?client_id={azureConfig.ClientId}" +
		 $"&response_type=code&redirect_uri={callbackpath}&response_mode=form_post&scope=openid&state=1&nonce=2";
		 
		 NavigationManager.NavigateTo(loginURL);
	}

Per [this document](https://learn.microsoft.com/en-us/entra/identity-platform/v2-protocols-oidc#send-the-sign-in-request) state is "Recommended" not required and is "A value included in the request that also will be returned in the token response. It can be a string of any content you want".

If I leave State set to "a string of any content you want" I get this error message:

> AuthenticationFailureException: Unable to unprotect the message.State.

If I remove the "Recommended" state parameter I get this error:

> AuthenticationFailureException: OpenIdConnectAuthenticationHandler: message.State is null or empty.

Question:  How do I allow the user to log in manually using a button click?

Update: 

When I un-comment this code the site works as expected:

    builder.Services.AddAuthorization(options =>
    {
        options.FallbackPolicy = options.DefaultPolicy;
    });

Thanks

**Comment by halter73** [comment]
You can create sign-in and sigin-out buttons that point to custom "/login" and "/logout" endpoints that call `HttpContext.ChallengeAsync()` and `HttpContext.SignOutAsync()` respectively or return results that do the same thing. For example:

    group.MapGet("/login", (string? returnUrl) => TypedResults.Challenge(GetAuthProperties(returnUrl)))
        .AllowAnonymous();

    group.MapPost("/logout", ([FromForm] string? returnUrl) => TypedResults.SignOut(GetAuthProperties(returnUrl),
        [CookieAuthenticationDefaults.AuthenticationScheme, OpenIdConnectDefaults.AuthenticationScheme]));

The code is modified from [this sample](https://github.com/dotnet/blazor-samples/blob/31b59a54a172a3ee18dde49dbbea83e41ca8e757/8.0/BlazorWebAppOidcBff/BlazorWebAppOidc/LoginLogoutEndpointRouteBuilderExtensions.cs#L9-L23). And you can see how it's [used from LogInOrOut.razor here](https://github.com/dotnet/blazor-samples/blob/31b59a54a172a3ee18dde49dbbea83e41ca8e757/8.0/BlazorWebAppOidcBff/BlazorWebAppOidc.Client/Layout/LogInOrOut.razor). These endpoints will redirect to the appropriate `https://login.microsoftonline.com/...` url for, you and handle the callback and state variable.

You could also use something like `AddMicrosoftIdentityUI` which adds endpoints like these for you via [its `AccountsController`](https://github.com/AzureAD/microsoft-identity-web/blob/60821501ac7585ba68633cba3c7982287fa92181/src/Microsoft.Identity.Web.UI/Areas/MicrosoftIdentity/Controllers/AccountController.cs#L43-L62), so feel free to just link to `MicrosoftIdentity/Account/SignIn` and `MicrosoftIdentity/Account/SignOut`. But if you set up the endpoints yourself, you shouldn't need to call `builder.Services.AddControllersWithViews().AddMicrosoftIdentityUI()` at all.

> When I un-comment this code the site works as expected:

`options.FallbackPolicy = options.DefaultPolicy` forces sign in for every page. The `DefaultPolicy` is used for requests to endpoints with an `[Authorize]` attribute (or some other form of `IAuthorizeData` to be pedantic) but no named policy like `[Authorize(Policy = "RequiresAdmin")]`. The default `DefaultPolicy` only requires that the user is authenticated.

The `FallbackPolicy` policy is used for requests where there's no relevant `[Authorize]` attribute. The default `FallbackPolicy` is `null` which means there are no requirements at all and anyone including anonymous users can access the endpoint. By setting `options.FallbackPolicy = options.DefaultPolicy`, you're changing the normally `null` fallback policy to require authenticated users for all endpoints.

If you add `[AllowAnonymous]` to your endpoint, you can let anonymous requests through regardless of the `FallbackPolicy`. But if you want most of your endpoints to be accessible anonymously, I recommend keeping `FallbackPolicy` set to `null` and adding `[Authorize]` to the endpoints that need them.

If you have an entire folder that should require auth, you can put `[Authorize]` in an `_Imports.razor` file in that folder. You'll need to use [`<AuthorizeRouteView>`](https://learn.microsoft.com/en-us/aspnet/core/blazor/security/?view=aspnetcore-8.0#resource-authorization) for these attributes to work on Razor components with `@page` directives. `[Authorize]` and `[AllowAnonymous]` do not work with non-`@page` components with or without `<AuthorizeRouteView>`.

For Razor components that accept both anonymous and authenticated requests, but need to show different content to anonymous and authenticated users like login and logout buttons you should use [`<AuthorizeView>`](https://learn.microsoft.com/en-us/aspnet/core/blazor/security/?view=aspnetcore-8.0#authorizeview-component).

**Comment by sam-wheat** [comment]
Thank you Stephen for pointing me in the right direction.  `MicrosoftIdentityUI.AccountController` looks like the best option.
