### ISSUE TITLE
Component/syntax for rendering other components dynamically by type

### ISSUE THREAD

**Issue by tidyui** [dotnet/aspnetcore#5631]
It would be very helpful to be able to invoke a component by its **name** instead of its **tagname**. If I for example create the component:

`~/Components/MyComponent.cshtml`

this is used from my page by writing.

`<MyComponent></MyComponent>`

Consider the use case where the data model I want to render using Blazor looks something like this:

    public class MyDataModel
    {
        public IEnumerable<IField> Fields { get; set; }
    }

Fields are registered through code at Startup, for example like this:

    MyApp.Fields.Register<StringField>();
    MyApp.Fields.Register<IntegerField>();

where both `StringField` and `IntegerField` implement `IField`. When rendering the page I want these fields to be handled by the components `StringField.cshtml` and `IntegerField.cshtml` but **without** actually knowing which components are available (as these are registered at startup by the main application). This would require the option to invoke a component with a syntax similar to this (example):

    @foreach (var field in Data.Fields)
    {
        @Component(field.GetType().Name, new { InputParamName = field })
    }

This functionality would support the same use case as `@Html.Editor` does in MVC which is very useful for handling composite data models.

Best regards

**Comment by pranavkm** [comment]
This should be resolved as part of the `DynamicComponent` work done in 6.0-preview1.
