### ISSUE TITLE
Google Pagespeed Insight is flagging blazor.server.js

### ISSUE THREAD

**Issue by lancecarlson** [dotnet/aspnetcore#56323]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Have you had any issues with getting _framework/blazor.server.js to pass the Google Pagespeed Insights analysis? Without editing the js file, I'm not sure how to make it pass errors such as "using deprecated api", or 20kb+ is unused dead code. It would be nice if you split up the file so you could decide which parts you're including at any given moment.

### Expected Behavior

It would be nice if you could split out what js files load if you don't need certain features.

### Steps To Reproduce

Goto https://pagespeed.web.dev/ and point it at any blazor SSR application. It should flag the issues it is having.

### Exceptions (if any)

I expect it to pass Google's Pagespeed insight test. If the solution is to allow you to split up the js file, they could be nice. Also resolving whatever deprecated API is being used would be nice.

### .NET Version

8.0.201

### Anything else?

https://pagespeed.web.dev/
https://github.com/dotnet/aspnetcore/issues/56081

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We do plan to break up the large js files and we track that work as part of https://github.com/dotnet/aspnetcore/issues/53214.

As for the deprecated APIs, we plan to address that as part of https://github.com/dotnet/aspnetcore/issues/54793
