### ISSUE TITLE
IRouteConstraints with Blazor components

### ISSUE THREAD

**Issue by dartemage** [dotnet/aspnetcore#56320]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I would like to have the ability to use custom `IRouteConstraints` in the context of Blazor components.

Currently, this is not possible because the initialization of `DefaultInlineConstraintResolver` does not occur using the `IServiceProvider`, and what is defined in

`services.AddRouting` is not applied.

`Microsoft.AspNetCore.Components.RouteTableFactory.Create`

`var builder = new TreeRouteBuilder(
    serviceProvider.GetRequiredService<ILoggerFactory>(),
    new DefaultInlineConstraintResolver(Options.Create(new RouteOptions()), serviceProvider));`

### Describe the solution you'd like

It is necessary to change the method to correctly handle the `IInlineConstraintResolver` interface from `IServiceProvider` and enable the application of custom options from `RouteOptions` in `services.AddRouting`.

**Comment by javiercn** [comment]
@dartemage thanks for contacting us.

Custom routing constraints are not supported in the Blazor Routing system. In .NET 9.0 there is support for using Regex constraints, which should allow you to express the constraint as a regex.

**Comment by AndreyZ1** [comment]
solution can be found here: https://github.com/dotnet/aspnetcore/issues/28938#issuecomment-2220190992
