### ISSUE TITLE
Security concern with accessing server-side Blazor services from a different DI scope / semaphore needed?

### ISSUE THREAD

**Issue by habex-ch** [dotnet/aspnetcore#56341]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

On the page https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/dependency-injection?view=aspnetcore-8.0#access-server-side-blazor-services-from-a-different-di-scope it is described how to access a service from a different scope.

Using a static field for transfering the IServiceProvider from one scope to another seems to be a security threat. 

Microsoft writes that on interactive server-side rendering no singleton should be used (see https://learn.microsoft.com/en-us/aspnet/core/blazor/security/server/interactive-server-side-rendering?view=aspnetcore-8.0&preserve-view=true#shared-state). 

The same could be said about the static field `blazorServices` in the class `CircuitServicesAccessor`.

If different users calls at the same time to the following inline function in the method CreateInboundActivityHandler inside the class ServicesAccessorCircuitHandler
```
        async context =>
        {
            circuitServicesAccessor.Services = services;
            await next(context);
            circuitServicesAccessor.Services = null;
        }
```
then the call could go to the wrong IServiceProvider.
Shouldn't there be some sort of lock or semaphore be in place?

cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/32904

### Expected Behavior

A clear way how we can access a service from a different scope especially AuthenticationStateProvider without any security concerns.

### Steps To Reproduce

See Microsoft documenation at 

- https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/dependency-injection?view=aspnetcore-8.0#access-server-side-blazor-services-from-a-different-di-scope 
- https://learn.microsoft.com/en-us/aspnet/core/blazor/security/server/additional-scenarios?view=aspnetcore-8.0#access-authenticationstateprovider-in-outgoing-request-middleware

### .NET Version

.NET 8

**Comment by guardrex** [comment]
Thanks @habex-ch! ... I'll keep an :eye: on this and add remarks to the article depending on what the product unit engineer(s) say.

**Comment by javiercn** [comment]
@habex-ch thanks for contacting us.

It's not a security threat. It's an async local which is not really static but scoped to the current async call context. See https://learn.microsoft.com/en-us/dotnet/api/system.threading.asynclocal-1?view=net-8.0 for details.

**Comment by habex-ch** [comment]
@javiercn Thank you very much for your explanation. 

I totally missed the concept behind AsyncLocal because it is hidden behind the value-property setter.
I have done a deep dive into the AsyncLocal concept and I get it now.

I am relieved that there is no security issue there.
