### ISSUE TITLE
[API Proposal]: Add new constructor for `HttpValidationProblemDetails` that accepts a `IEnumerable<KeyValuePair<string, string[]>>`

### ISSUE THREAD

**Issue by joegoldman2** [dotnet/aspnetcore#56370]
## Background and Motivation

#41899 introduces new overloads for `Results.ValidationProblem` and `TypedResults.ValidationProblem` that accepts a `IEnumerable<KeyValuePair<string, string[]>>` for the errors.

For the sake of consistency, it would be good to have a constructor in `HttpValidationProblemDetails` that also accepts a  `IEnumerable<KeyValuePair<string, string[]>>`.

More context: https://github.com/dotnet/aspnetcore/issues/41899#issuecomment-2181727711

## Proposed API

```diff
namespace Microsoft.AspNetCore.Http;

public partial class HttpValidationProblemDetails : ProblemDetails
{
     // existing
     public HttpValidationProblemDetails()
     public HttpValidationProblemDetails(IDictionary<string, string[]> errors)

     // new
+    public HttpValidationProblemDetails(IEnumerable<KeyValuePair<string, string[]>> errors);
}
```

## Usage Examples

```csharp
var errors = new List<KeyValuePair<string, string[]>> { new("testField", new[] { "test error" }) };
var problemDetails = new HttpValidationProblemDetails(errors);
```

## Risks

Nothing I can see now.

**Comment by amcasey** [comment]
API Approved!
