### ISSUE TITLE
Make EventCallback returnable like Func<in, out>

### ISSUE THREAD

**Issue by Kebechet** [dotnet/aspnetcore#56425]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Current problem is described in the [StackOverflow](https://stackoverflow.com/questions/61345648/how-to-get-return-value-from-eventcallback-in-blazor) post:

**TLDR:** When child component want to call something from parent we can use `EventCallback` or `Action`. `EventCallback` has an advantage that it can automatically trigger `StateHasChanged` but if it is called by action we have to trigget `StateHasChanged` manually. The problem begins when we want to perform `Func` like behavior in form of `EventCallback`. So not only accept input parameter but also return a value.

### Describe the solution you'd like

Create type `ReturnableEventCallback` that can take input/output parameters like `Func`

### Additional context

Currently the only workaround for this is to put into `EventCallback` a complex object that doesnt represent only input parameters but also the output one. That way parent can adjust properties of the input object and after that child component can read it.

**Comment by MackinnonBuck** [comment]
Thanks for reaching out. This isn't a direction we plan to take at this time. If you want a callback to both return a value and trigger a re-render, we'd recommend calling `StateHasChanged` as you described.

**Comment by Kebechet** [comment]
@MackinnonBuck thank you for the answer. But can you please also provide reasoning behind this decision ?
Isn't this usecase common enough ?
