### ISSUE TITLE
Blazor projects won't load on .NET 9 Preview 5

### ISSUE THREAD

**Issue by los93sol** [dotnet/aspnetcore#56438]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I created a Blazor Web App from the template in Visual Studio 2022 Preview and when it starts up Chrome loads an empty tab with about:blank in the url.

**Comment by los93sol** [comment]
If you add docker support to the project it does load, but breakpoints in webassembly components still do not hit.

**Comment by MackinnonBuck** [comment]
Thanks for reaching out. This seems like an issue in VS rather than an issue in ASP.NET Core. Could you please file a Visual Studio feedback ticket using the "Provide Feedback" button in VS? That will help this issue get routed to the right team.
