### ISSUE TITLE
End of message callback for connections

### ISSUE THREAD

**Issue by klowdo** [dotnet/aspnetcore#56449]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I want to send an extra set of bytes when websocket has read a full message.
This is the because i want to leverage same as signalR does and finds the `RecordSeparator` with `TextMessageFormatter` to  extract messages in the pipe. I don't have control over the client like signalR.

### Describe the solution you'd like

My idea is to do something like this [commit](https://github.com/klowdo/aspnetcore/commit/d2a8a4506acf81f6c640ca24dbd59a31b7b20eb4) 

```c#

// in WebSocketsServerTransport.cs
_application.Output.Advance(receiveResult.Count);
// this is what i suggest
if(receiveResult.EndOfMessage && _connection.OnMessageReceived != null)
{
    _connection.OnMessageReceived.Invoke(_application.Output);
}
          
```

pass on a action to write to the stream when we know that the websocket frame is finished and we can add more bytes to the frame before flushing.

**Comment by klowdo** [comment]
Thank you for a quick response

essentially what i want to use this class(TextMessageParser) to find the byte frames(the whole message) where my message content is in the stream.
There will be one json message between the `receiveResult.EndOfMessage` so after that i want to add this byte at the end in the websocket message.
Since i don't have control over the client messages like the signalR client has i need to do this in the transport.

and just to make it clear. i don't want to use signalR just the http.Connection part :)

what i would hope to achive here is
```c#
var result = socket.ReceiveAsync(....);
/// buffer = {"jsonpoperty": "first part of message", 
result.EndOfMessage == false
///...next iteration
var result = socket.ReceiveAsync(....);
/// buffer =  "secondProperty": "last part of message"}
result.EndOfMessage == true

if(receiveResult.EndOfMessage)
 //append TextMessageFormatter.RecordSeparator to buffer

//flush
```

and just like the reader in SignalR i will wait for read of the pipe and if don't find the `RecordSeparator` i will just mark the as `examined` and wait for the rest of the message will arrive

```c#
internal static class TextMessageParser
{
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool TryParseMessage(ref ReadOnlySequence<byte> buffer, out ReadOnlySequence<byte> payload)
    {
        if (buffer.IsSingleSegment)
        {
            var span = buffer.First.Span;
            var index = span.IndexOf(TextMessageFormatter.RecordSeparator);
            if (index == -1)
            {
                payload = default;
                return false;
            }

            payload = buffer.Slice(0, index);

            buffer = buffer.Slice(index + 1);

            return true;
        }
        else
        {
            return TryParseMessageMultiSegment(ref buffer, out payload);
        }
    }

    private static bool TryParseMessageMultiSegment(ref ReadOnlySequence<byte> buffer, out ReadOnlySequence<byte> payload)
    {
        var position = buffer.PositionOf(TextMessageFormatter.RecordSeparator);
        if (position == null)
        {
            payload = default;
            return false;
        }

        payload = buffer.Slice(0, position.Value);

        // Skip record separator
        buffer = buffer.Slice(buffer.GetPosition(1, position.Value));

        return true;
    }
}
```

**Comment by davidfowl** [comment]
I would just copy the code you need. This callback feels very out of place if you care about the underlying websocket protocol. If you do truly want to use the websocket like a pure stream of bytes, then you don't need the end of message flag.

**Comment by klowdo** [comment]
Thank for a quick response. 
That correct I don't use it as pure streams.

I'll do that!
