### ISSUE TITLE
Memory leak in ASP.NET Core 8

### ISSUE THREAD

**Issue by doboczyakos** [dotnet/aspnetcore#56465]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![image](https://github.com/dotnet/aspnetcore/assets/53097414/a8a326c3-112e-441a-90a6-d5a1c8510feb)

### Steps To Reproduce

I can send memory dump if requested

7f2511bc0430	198656	7846912	System.Reflection.Emit.RuntimeGenericTypeParameterBuilder[]
7f25101039b8	136577	9138200	System.Reflection.Emit.RuntimeMethodBuilder[]
7f250f3f20f8	384896	9237504	System.Reflection.Emit.RuntimeGenericTypeParameterBuilder
7f25101c0c18	266944	12167680    System.Type[][]
7f2511bc09c8	384896	12316672    System.Collections.Generic.List<System.Reflection.Emit.RuntimeTypeBuilder+CustAttr>
7f250f3f3798	384896	15395840	System.Reflection.Emit.RuntimeTypeBuilder+CustAttr
7f25050d6410	521671	16693472	System.Collections.Generic.List<System.Type>
7f25012b9db0	431526	17261040	System.RuntimeType
7f2502a711e8	423512	20328576	System.Reflection.Emit.ScopeTree
7f2511bc0f10	384897	21554200	System.Reflection.Emit.RuntimeTypeBuilder+CustAttr[]
556160c08a80	16301	29831240	Free
7f2502a5e168	839682	40304736	System.Reflection.Emit.SignatureHelper
7f2501e79750	1418698	42763680	System.Type[]
7f25013689e0	529508	45988208	System.Int32[]
7f2502a5b648	415936	56567296	System.Reflection.Emit.RuntimeILGenerator
7f250136d7c8	764591	72146418	System.String
7f2502a71c20	415936	73204736	System.Reflection.Emit.RuntimeMethodBuilder
7f2502a70018	524576	88128768	System.Reflection.Emit.RuntimeTypeBuilder
7f2501e74c60	1785663	151565211	System.Byte[]
Total	12056751	896193916	

!GCRoot 7f23244b6818

HandleTable:
    00007f257e541328 (strong handle)

          -> 7f230c01fea0     System.Object[] 
          -> 7f231447ad28     System.Collections.Generic.Dictionary<System.Reflection.Assembly, System.Boolean>
          -> 7f2317761148     System.Collections.Generic.Dictionary<System.Reflection.Assembly, System.Boolean>+Entry[] 
          -> 7f2324400028     System.Reflection.Emit.RuntimeAssemblyBuilder 
          -> 7f23244000c0     System.Reflection.Emit.RuntimeModuleBuilder 
          -> 7f23244001c0     System.Collections.Generic.Dictionary<System.String, System.Type>
          -> 7f23244bb460     System.Collections.Generic.Dictionary<System.String, System.Type>+Entry[] 
          -> 7f23244b5b58     System.Reflection.Emit.RuntimeTypeBuilder 
          -> 7f23244b5ca0     System.Collections.Generic.List<System.Reflection.Emit.RuntimeMethodBuilder>
          -> 7f23244b6388     System.Reflection.Emit.RuntimeMethodBuilder[] 
          -> 7f23244b6428     System.Reflection.Emit.RuntimeMethodBuilder 
          -> 7f23244b66a0     System.Reflection.Emit.RuntimeILGenerator 
          -> 7f23244b6818     System.Byte[] 

Found 1 unique roots.

### .NET Version

8.0.6

### Anything else?

![image](https://github.com/dotnet/aspnetcore/assets/53097414/9c8f51f1-6b89-49e0-9f88-c1f380436f07)

We moved to 8.0.6 from 8.0.2 on 2024.06.11.

**Comment by davidfowl** [comment]
Did you look at the roots of those objects? What makes this an asp.net core issue?

**Comment by doboczyakos** [comment]
> Did you look at the roots of those objects? What makes this an asp.net core issue?

Yes, I pasted a gcroot.
The fact that we updated the base image first from .net 7 to .net 8.0.2 then to 8.0.6 and it caused increasing memory usage and it is an asp.net core application

**Comment by davidfowl** [comment]
There's nothing in that gcroot that says ASP.NET Core to me. Are there other clues that narrow down what it might be?

**Comment by doboczyakos** [comment]
> There's nothing in that gcroot that says ASP.NET Core to me. Are there other clues that narrow down what it might be?

I can send the memory dump. If it is not asp.net core can you please forward the issue to the appropriate team?
I can not see other things than millions of objects from the System.Reflection.Emit namespace held by and object[] and we have no code change in relation with the memory usage changes, but a base image update from 8.0.2 to 8.0.6 seems to be the beginning of the problem.
We are now moving back to the 8.0.2 base image with the same code and we will see what happens in cca 1 week.

**Comment by davidfowl** [comment]
If downgrading to 8.0.2 fixes the problem then maybe the first place to start is looking at the commit delta in both ASP.NET Core and .NET.

@wtgodbe is there an easy way to look at commits between 8.0.2 and 8.0.6?

> I can send the memory dump. If it is not asp.net core can you please forward the issue to the appropriate team?

I think the problem is time, that's why we'd like more indication that there might be an issue here coming from the framework itself. From the looks of it, it could be anything that does dynamic code generation... Unclear if that's coming from your app code, a library, asp.net core itself.

If you can collect a gc-verbose trace https://learn.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-trace#dotnet-trace-collect, you might be able to figure out where those allocations are coming from.

**Comment by doboczyakos** [comment]
Analysing the memory dump shows the same objects with 8.0.2 so sorry, there's no connection between changing the base image version and the increase of used memory

**Comment by davidfowl** [comment]
It's likely a static somewhere.  It could be in one of the libraries you are using...

**Comment by doboczyakos** [comment]
Yes, but there are random things in that object[] from random parts of the application so I can't figure out who has a static object[] and why

**Comment by wtgodbe** [comment]
> @wtgodbe is there an easy way to look at commits between 8.0.2 and 8.0.6?

https://github.com/dotnet/aspnetcore/compare/v8.0.2...v8.0.6

**Comment by doboczyakos** [comment]
> > @wtgodbe is there an easy way to look at commits between 8.0.2 and 8.0.6?
> 
> [v8.0.2...v8.0.6](https://github.com/dotnet/aspnetcore/compare/v8.0.2...v8.0.6)

Thanks, but unfortunately it doesn't help us in this case.
Somehow I have to find a Dictionary<Assembly, bool> and I'm afraid it's in an assembly of the Sdk.

**Comment by davidfowl** [comment]
https://github.com/dotnet/aspnetcore/issues/56465#issuecomment-2191842813

> If you can collect a gc-verbose trace https://learn.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-trace#dotnet-trace-collect, you might be able to figure out where those allocations are coming from.

**Comment by doboczyakos** [comment]
![image](https://github.com/dotnet/aspnetcore/assets/53097414/d9eafc26-2f40-410b-b9b0-6139ed68894d)

**Comment by doboczyakos** [comment]
I'm closing this because it has no connection with any parts of the framework. Thanks for the support.

**Comment by davidfowl** [comment]
No problem. IF you do find anything else feel free to open an issue or discussion.

**Comment by doboczyakos** [comment]
https://github.com/castleproject/Core/issues/594
