### ISSUE TITLE
Push minified .js files to submodule

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/aspnetcore#56472]
Plan of record to fix the NPM build for source-build in .NET 9:

1. Push minified .js files to https://github.com/dotnet/BlazorMinifiedJs
2. Add https://github.com/dotnet/BlazorMinifiedJs as a submodule
3. In source-build, don't build node/npm components - instead reference the minified .js files from the submodule
4. Error whenever the files in the submodule don't match what's in the repo
5. In any PR that would change the contents of the minified .js files, push the updated files to the submodule repo & ingest it in that same PR (so that we are testing changes here at the source, in the same way we would for full .NET source build)

CC @javiercn @dotnet/source-build-contrib

**Comment by MichaelSimons** [comment]
cc @dotnet/distro-maintainers

**Comment by tmds** [comment]
cc @Swapnali911 @uweigand @Vishwanatha-HD

**Comment by tmds** [comment]
@wtgodbe is there some progress?

This has blocked us to build .NET 9 on ppc64le and s390x for all .NET 9 previews so far.

**Comment by wtgodbe** [comment]
Sorry, have been on vacation. Just opened https://github.com/dotnet/aspnetcore/pull/56864 for preview7.
