### ISSUE TITLE
 Identity RemoveClaimsAsync(userById, claimsToRemove) method is resetting the primary key to the last removed claim's primary key

### ISSUE THREAD

**Issue by sukelali** [dotnet/aspnetcore#56476]
The last primary key in the **UserClaims** table is 1115. I removed a record with the primary key 181 using the `RemoveClaimsAsync(userById, claimsToRemove)` method. When I started to add new data to the **UserClaims** table using the `AddClaimAsync()` method, it threw a duplicate primary key violation error. The `AddClaimAsync()` method started to add new data with the primary key 182.

The` AddClaimAsync()` method should insert new data with the primary key of 1116

### .NET Version

net6.0

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We don't set the primary keys manually in the framework, rather we rely on the underlying database to assign these automatically. So if you're getting unexpected assignments, that indicates an issue with the database itself.
What database do you use?

**Comment by mkArtakMSFT** [comment]
Also, feel free to share a minimal repro project in case there is something interesting for us to see there.

**Comment by sukelali** [comment]
> Thanks for contacting us. We don't set the primary keys manually in the framework, rather we rely on the underlying database to assign these automatically. So if you're getting unexpected assignments, that indicates an issue with the database itself. What database do you use?

PostgreSQL 13
