### ISSUE TITLE
Multiple Browser Tabs, Keeping Authentication State in Sync

### ISSUE THREAD

**Issue by htmlsplash** [dotnet/aspnetcore#56473]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

All,

We have a Blazor app that is static SSR first, but hosts interactive server components. These components require information about currently authenticated user to render. We have an issue with current implementation of authenticated user state when using multiple browser tabs.

In our application a user can open multiple tabs that display page with interactive server components that use the currently authenticated user to render information. We inject inside the interactive server components the AuthenticationStateProvider to get information about currently logged in user.
When the user logs out of their account or switches to another user account on Tab 1, the Tab 2, Tab 3, still have the previous authenticated user/information. The server components then displayed information on based previously logged in user. A hard page refresh does reset the user state to current but without doing that (or knowing to do it) any interaction on the component still uses the previous user account.

What I would like to see if the user logs out or switches user account information on Tab 1, the new user account state of the currently logged-in user should be propagated to Tab 2, Tab 3 (or at least display a message to the user to refresh their page)... so that the user can continue to interact with components on Tab 2, Tab 3 with the "current" user account.
What's the approach to get as close to this behavior as possible.

I know why this is happening, ie, Tab 2, Tab 3, use separate circuits but is there a solution to this problem?

**Solution 1**
The Solution I came up with is to pass the user object from the static SSR page as a parameter to the interactive server component. Although the component UI still uses the old user, but when I navigate away to another page with interactive server component, because the user travels across rendering boundary from static SSR to interactive server, it gets refreshed/synced to the currently logged-in user.

**Solution 2**
Implement custom RevalidatingServerAuthenticationStateProvider? Does this handle updating ClaimsPrincipal on all active circuits (ie running separate tabs) and the HttpContext's user object (our code needs to use HttpContext because we're converting a webforms app)? In other words, if I check the HttpContext.User, it will have the same value for all circuits (and this means whether the user logged out or switched an account by logging as some one else)?
If yes, link to an example?

### Describe the solution you'd like

For static SSR pages (displayed in multiple browser tabs) that display components rendered using interactive server render mode:

Switching user account in one browser tab (by logging as different user) should be propagated to the other opened tabs. Otherwise when the user selects the other tab (and doesn't check or see the currently authenticated user information) may continue editing information under the previous user account.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. There is no simple solution here that you can out of the box. So, you'll need to build a custom solution for this. Here are a few options:
1. Utilize some common service on the server, that will be accessible from both circuits that they can share information about user and notify changes through. (similar to your Solution # 2)
2. Utilize [JS APIs](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) to communicate between tabs within the browser to notify each other about user changes and react to these accordingly.
