### ISSUE TITLE
Override/add to the auto-genrated IIS rewrite rules for standalone apps

### ISSUE THREAD

**Issue by ransagy** [dotnet/aspnetcore#5647]
When using the standalone hosting model, The publish process generates a swanky `web.config` for us with some rewrite rules to make sure static files and urls are handled correctly in the SPA context.

I'm trying to add an initial redirect to HTTPS on top of that. Following [this](https://www.hanselman.com/blog/HowToEnableHTTPStrictTransportSecurityHSTSInIIS7.aspx) article, for example, means that i want to add two rules to my web.config - one for HTTP->HTTPS redirection and one for adding an HSTS header to better protect such a redirect.

Right now, The only way is to inject it into the web.config after the build/publish process is done. I'm wondering if there could be a way to define/add to the generated content as part of the process rather than outside of it.

**Comment by pranavkm** [comment]
This was changed as part of the 3.2 release. If a web.config exists, it is no longer overwritten.
