### ISSUE TITLE
Problem With some extensions like tronlink

### ISSUE THREAD

**Issue by anik76** [dotnet/aspnetcore#56512]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

in blazor .net 8 web app sample on google chrome when tronlink extension is on app not working and console show errors:
`blazor.web.js:1 [2024-06-28T16:42:46.352Z] Error: There was an error applying batch 2.
blazor.web.js:1 [2024-06-28T16:42:46.358Z] Error: There was an error applying batch 3.
blazor.web.js:1 [2024-06-28T16:42:46.414Z] Error: System.AggregateException: One or more errors occurred. (TypeError: Cannot read properties of null (reading 'insertBefore'))
 ---> System.InvalidOperationException: TypeError: Cannot read properties of null (reading 'insertBefore')
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InvokeRenderCompletedCallsAfterUpdateDisplayTask(Task updateDisplayTask, Int32[] updatedComponents)
   --- End of inner exception stack trace ---`

### Exceptions (if any)

blazor.web.js:1 [2024-06-28T16:42:46.352Z] Error: There was an error applying batch 2.
blazor.web.js:1 [2024-06-28T16:42:46.358Z] Error: There was an error applying batch 3.
blazor.web.js:1 [2024-06-28T16:42:46.414Z] Error: System.AggregateException: One or more errors occurred. (TypeError: Cannot read properties of null (reading 'insertBefore'))
 ---> System.InvalidOperationException: TypeError: Cannot read properties of null (reading 'insertBefore')
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InvokeRenderCompletedCallsAfterUpdateDisplayTask(Task updateDisplayTask, Int32[] updatedComponents)
   --- End of inner exception stack trace ---

### .NET Version

8

**Comment by javiercn** [comment]
@anik76 thanks for contacting us.

Do any of these extensions manipulate the DOM In any way? Can you provide links to these extensions in the chrome extensions web store?

**Comment by anik76** [comment]
The extension link in chrome web extension store

[Tron link extension](https://chromewebstore.google.com/detail/tronlink/ibnejdfjmmkpcnlpebklmnkoeoihofec?hl=en&pli=1)

**Comment by javiercn** [comment]
@anik76 thanks for contacting us.

This points out to this extension modifying the DOM in ways not supported by Blazor. This is a problem with this extension rather than a Blazor issue.

**Comment by anik76** [comment]
Thanks.

Blazor .net6 is ok with this extension. And website users can't find out the problem source easily
