### ISSUE TITLE
Add PageModel SignIn and Signout methods to ComponentBase for OIDC

### ISSUE THREAD

**Issue by dgxhubbard** [dotnet/aspnetcore#56510]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I tried to do OIDC using Blazor but could not because the methods SignIn and SignOut in mvc PageModel do not exist.

### Describe the solution you'd like

I am new to OIDC I would like to have the mvc PageModel methods SignIn and SignOut added to Blazor ComponentBase in order to implement login and logout pages in blazor. I do not know if this would be complex but I hope it is not.

**Comment by javiercn** [comment]
@dgxhubbard thanks for contacting us.

That's not something we ever plan to do for layering reasons. ComponentBase is not tied to HTTP nor ASP.NET and its not the right place to locate those helper methods.

If you are using SSR and want to have something like that, our recommendation is that you create your own base class, add that functionality and apply it to the components you want to use it on.
