### ISSUE TITLE
How to get response typed result in minimal api filter

### ISSUE THREAD

**Issue by andrew-vdb** [dotnet/aspnetcore#56524]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

- I have minimal api filter
- I have minimal api that return TypedResult.BadRequest
- The HttpContext.Response.StatusCode within the filter value still 200 OK

![image](https://github.com/dotnet/aspnetcore/assets/12871379/a0ada14a-d60d-49c9-b4a0-11eeb026aed6)

### Expected Behavior

If possible, when TypedResult.BadRequest is returned, Response.StatusCode adjusted according to the returned value,
so when minimal api return TypedResult.BadRequest, httpContext.Response.StatusCode should be 400 

### Steps To Reproduce

```
internal static async Task<Results<RedirectHttpResult, BadRequest>> Post(HttpContext httpContext){
return TypedResults.BadRequest()
}
```
```
public class EndpointFilter : IEndpointFilter
{
    public async ValueTask<object?> InvokeAsync(EndpointFilterInvocationContext context, EndpointFilterDelegate next)
    {

        var result = await next(context); // result.Result =  TypedResult.BadRequest
        var debug = context.HttpContext.Response.StatusCode; // 200 OK
        
       //How to get result.Result over here without using dynamic ????
        
        return result;
    }
}
```

### .NET Version

8

**Comment by andrew-vdb** [comment]
Workaround 1
```
public class EndpointFilter : IEndpointFilter
{
    public async ValueTask<object?> InvokeAsync(EndpointFilterInvocationContext context, EndpointFilterDelegate next)
    {
        dynamic result = await next(context);
        int statusCode = result.Result.StatusCode; // 400       
        return result;
    }
}
```

**Comment by andrew-vdb** [comment]
Workaround 2
```
public class EndpointFilter : IEndpointFilter
{
    public async ValueTask<object?> InvokeAsync(EndpointFilterInvocationContext context, EndpointFilterDelegate next)
    {
        var result = await next(context);
        await (result as IResult).ExecuteAsync(context.HttpContext); // Response will become 400, but next middleware will execute this i think     
        return result;
    }
}
```

**Comment by WeihanLi** [comment]
maybe you could consider using pattern-matching with `IValueHttpResult`(API introduced in .NET 7, https://github.com/dotnet/aspnetcore/issues/42187)


```c#
if (result is IValueHttpResult valueHttpResult)
{
    // valueHttpResult.Value
}
```

and I've developed an endpoint filter to implement unified API output here: 

https://github.com/WeihanLi/WeihanLi.Web.Extensions/blob/92676cdeb829cabe4622642d6aa519508c5ca529/src/WeihanLi.Web.Extensions/Filters/ApiResultFilter.cs#L42

hope it helps

**Comment by andrew-vdb** [comment]
the delegate not returning IValueHttpResult

<img width="454" alt="image" src="https://github.com/dotnet/aspnetcore/assets/12871379/9a26555d-4b42-4ac2-98ed-197161b90cb4">

**Comment by andrew-vdb** [comment]
@WeihanLi is right

**Comment by laventnc** [comment]
Incase anyone stumbles upon this, the problem originates from using the typed union `Results<>`. You need to cast to an interface to get the inner result, then you can check the StatusCode by casting the inner to `IStatusCodeHttpResult`.
```c#
if ( response is INestedHttpResult nestedResult )
{
    if ( response.Result is IStatusCodeHttpResult res && res.StatusCode >= 200 && res.StatusCode < 300 )
}
```
