### ISSUE TITLE
User is authenticated false, when using multiple cookie authentications

### ISSUE THREAD

**Issue by guilhermesuzuki** [dotnet/aspnetcore#56540]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After successfully authenticating the user, the blazor page is accessible as expected, but the user information is unavailable (**IsAuthenticated False**). If you run the repro project attached to this issue, you can notice the username flickering.

### Expected Behavior

User information to be available according to authentication performed.

### Steps To Reproduce

Here's the GitHub reproduction project:
- https://github.com/guilhermesuzuki/NET8-BlazorServerApp-UserIsAuthenticatedFalse.git

### .NET Version

8.0.6

**Comment by javiercn** [comment]
@guilhermesuzuki thanks for contacting us.

Blazor will use the authentication schemes configured in the default policy. For you to use a different scheme you need to provide your own `AuthenticationStateProvider` that uses whatever policy you want.

**Comment by guilhermesuzuki** [comment]
Yeah, it works... thanks! But it feels more like a temporary fix though, since the circuit gets it right for the first couple of times.

**Comment by guilhermesuzuki** [comment]
I need to identify the page Blazor is rendering, to try and authenticate the user based on the path. Can please you point me at the **right documentation** to do so?

**Comment by guilhermesuzuki** [comment]
I think I am getting a grip of the issue: ASP.NET core authenticates and authorizes the user as expected. Blazor connects to the server (without the context path) and defaults the authentication. So that's why the username quickly appears on the screen and then disappears. Is this right, @javiercn?

**Comment by javiercn** [comment]
@guilhermesuzuki you are not setting a default policy on your example, so when the circuit starts the user is not authenticated because it wasn't authenticated on the connection request that established the circuit.

**Comment by guilhermesuzuki** [comment]
I updated the example with a default policy, but the `User.Identity.IsAuthenticated` is false for the circuit. Well, the application works because I am always returning a principal.

What am I doing wrong?

**Comment by ejgeneral** [comment]
@guilhermesuzuki I think the default policy must be set in line 13 in Program.cs? Kind of wondering about this myself on how to set the custom implementation of AuthenticationStateProvider to use a specific authentication.

**Comment by guilhermesuzuki** [comment]
> @guilhermesuzuki I think the default policy must be set in line 13 in Program.cs? Kind of wondering about this myself on how to set the custom implementation of AuthenticationStateProvider to use a specific authentication.

No, I am pretty sure it has been set at the right place (line 49). If you are talking about the default authentication scheme, then it's in line 13. But I still think Blazor should work with the authentication setup I am trying to achieve with the repro.

**Comment by ejgeneral** [comment]
@guilhermesuzuki I see, yup I agree. I pretty much have same setup as your repro for testing. The default is CustomPolicy1 and all my pages using that authorization policy can display the claims no problem. Other pages using a different policy would display claims from CustomPolicy1 if I authenticated there first.

**Comment by guilhermesuzuki** [comment]
I have looked around and it seems this [issue](https://github.com/dotnet/aspnetcore/issues/50122) is related.

**Comment by halter73** [comment]
> I have looked around and it seems this [issue](https://github.com/dotnet/aspnetcore/issues/50122) is related.

I think you're right. I reopened #50122 to track this.
