### ISSUE TITLE
Change wwwroot to Assets in Razor Class Library

### ISSUE THREAD

**Issue by nfplee** [dotnet/aspnetcore#56552]
For a Razor Class Library I can specify "StaticWebAssetBasePath" to override the default path where my assets are exposed. However is it possible to change the directory name where my assets are originally placed? Currently I have to place them within a "wwwroot" within my class library, but ideally I'd like them to be within an "Assets" directory.

Please note that I originally posted it [here](https://github.com/dotnet/sdk/issues/41818), but I'm yet to receive a response, so I'm guessing the repo isn't as active as this one.

**Comment by javiercn** [comment]
@nfplee thanks for contacting us.

Why would you want to use a different folder as opposed to wwwroot.

**Comment by nfplee** [comment]
I have two versions of my framework, one which runs on .Net 4.6.2 and one which runs on .Net (Core) 8.

Modules which run on the older .Net 4.6.2 framework pre-dates ASP.Net core and my static assets are included in an Assets directory.

I've now decided to remove the .Net 4.6.2 framework. If it was just me maintaining the modules, then it wouldn't be a problem. But I have thousands of modules across hundreds of sites and I'm trying to make the upgrade process as simple as creating a Razor Class Library and then copying and pasting the content from old module into it. So far everything has gone to plan (since ASP.Net Core MVC is largely compatible with ASP.Net MVC (pre-core) but this has been my first minor stumbling block.

I hoped there was a simple build property which would allow me to use Assets instead of wwwroot.

**Comment by javiercn** [comment]
@nfplee why does in your case renaming `Assets` to `wwwroot`. It's an extra step, but not something that can't be done programatically with a script.

**Comment by nfplee** [comment]
@javiercn renaming isn't too difficult. It's just an extra step to remember. The less module differences, the easier it will be to upgrade. For example, here are the differences I have encountered:

- No DependencyResolver
- Model binding (need to declare a provider)
- Assets now within wwwroot

I have workarounds for the first 2 issues. If this is not possible, please say and I can just accept it's another change I'll have to make.

**Comment by javiercn** [comment]
@nfplee thanks for the additional details.

It's not possible out of the box and would likely require a feature, we always ask for details because we want to know how hard it is to achieve without a feature, as that influences our decision making.

In this case, seems that the alternative is reasonable, even if it's a bit more work.
