### ISSUE TITLE
Register Location Changing Handler unexpectedly refresh the application when trying to set a hash

### ISSUE THREAD

**Issue by likquietlyy** [dotnet/aspnetcore#56574]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I registers a handler to process incoming navigation events (**NavigationManager.RegisterLocationChangingHandler**) and trying to **set hash** (window.location.hash) using _JsInterop_ (or browser _console_) the application restarts unexpectedly

### Expected Behavior

Setting hash without restarting the app and with registered location changing handler

### Steps To Reproduce

1. [Create Blazor Web App using template](https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/create)
2. [Run app](https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/run) and make sure that setting the hash via the console does not restart the application
![image](https://github.com/dotnet/aspnetcore/assets/158453143/b9b41287-ac93-46f7-a0bc-fd8ec535bab3)
3. Create Home.razor.cs
```
public partial class Home : IDisposable
{
  [Inject] NavigationManager NavigationManager { get; init; } = default!;

  private IDisposable? _registration;

  protected override void OnAfterRender(bool firstRender)
  {
    if (firstRender)
    {
      _registration = NavigationManager.RegisterLocationChangingHandler(OnBeforeLocationChanging);
    }
  }

  private ValueTask OnBeforeLocationChanging(LocationChangingContext context)
  {
    //some code
    return ValueTask.CompletedTask;
  }

  public void Dispose()
  {
    _registration?.Dispose();
  }
}
```
4. Make sure that setting the hash via the console restart the application

### .NET Version

8.0.302

**Comment by MackinnonBuck** [comment]
Thanks for reaching out, @likquietlyy.

I tried following your repro steps but don't observe any unusual behavior. Could you describe what you mean when you say that the application restarts? Is the page reloading or is something else going on?

If possible, please provide us with a minimal repro project that demonstrates the issue, hosted as a public GitHub repository. This will allow us to investigate the problem further. Thanks!

**Comment by likquietlyy** [comment]
Hello, @MackinnonBuck, [repo](https://github.com/likquietlyy/RegisterLocationChangingHandler) is here. Yes, the page is reloading. I'm added a "set hash" button to the home page and serilog console provider. At the screenshot below 10:08:30 - click on the set hash button
![ConsoleOutput](https://github.com/user-attachments/assets/356eb1b9-4d0e-4f50-84c2-c9e672e96c4d)

**Comment by MackinnonBuck** [comment]
@likquietlyy, Blazor doesn't support modifying the `location` object manually. Blazor stores framework-related state in the history stack, and setting `href` appends a new history entry without that state. This can cause navigation to behave unexpectedly.

If you instead set the hash like this:
```csharp
var uri = new UriBuilder(NavigationManager.Uri);
uri.Fragment = "some-hash";
NavigationManager.NavigateTo(uri.ToString());
```

...then it should work as expected.

Could you confirm whether this solves the problem for you? Thanks!
