### ISSUE TITLE
About RateLimiting middleware get RateLimiterOptions

### ISSUE THREAD

**Issue by ayrloong** [dotnet/aspnetcore#56573]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

I use RateLimiting middleware in aspnetcore, but I encounter a problem that I cannot get its RateLimiterOptions value in real time because it is fixed when injected.
![WechatIMG324](https://github.com/dotnet/aspnetcore/assets/19401853/c493e4d7-153b-4ec4-bb68-e6175238610a)

**Comment by endless001** [comment]
There is an ICorsPolicyProvider interface in CorsMiddleware that can be well implemented
![WechatIMG325](https://github.com/dotnet/aspnetcore/assets/19401853/ca135350-a7df-4066-8f1f-cb3656f85812)

**Comment by ks1990cn** [comment]
Hi @amcasey , Why you need to get your options for rate limiting? You can see the configured options from your code. Why you need during run time?

**Comment by ayrloong** [comment]
@ks1990cn  Thank you for your reply, because I want to modify RateLimiterOptions at runtime to make the entire configuration policy dynamic.

**Comment by ks1990cn** [comment]
Hi @ayrloong , Consider a case you are doing at runtime. Anyone can touch it and impact your api. Will it not create your api more vulnerable?

**Comment by ks1990cn** [comment]
What if you create environment parameter & use it for configuration during startup? Then change parameters & restart your api.

**Comment by ayrloong** [comment]
duplicate https://github.com/dotnet/aspnetcore/issues/45407
