### ISSUE TITLE
basic Hot Reload fails when modifying razor pages in external library/project

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#56600]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/basic-Hot-Reload-fails-when-modifying-ra/10516468)._

---
[severity:It's more difficult to complete my work]
I have prepared my project for Blazor Hybrid model, I have all my pages/components in a library project, the Client.Wasm project references the SharedUi project and all the pages/components are in the SharedUi project. Making a simple edit to a div in the razor page breaks Hot Reload.

---
#### Bill Hiebert [MSFT] on 11/15/2023, 11:07 AM: 

(private comment, text removed)
#### Henok Girma on 11/19/2023, 06:25 AM: 

(private comment, text removed)
#### Feedback Bot on 12/12/2023, 05:45 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by javiercn** [comment]
Thanks for contacting us.

If for blazor hybrid you mean Blazor running on Maui, WPF or Windows forms. Is there a reason why you are trying to run blazor webassembly inside the native/mobile application?

We would need a minimal repro to better understand what you are trying to accomplish and determine why it doesn't work.
