### ISSUE TITLE
SignInManager.ValidateTwoFactorSecurityStampAsync is incorrectly passing userName to FindByIdAsync

### ISSUE THREAD

**Issue by paulduran** [dotnet/aspnetcore#56625]
In SignInManager.ValidateTwoFactorSecurityStampAsync  line 301:

https://github.com/dotnet/aspnetcore/blob/75368e2d448d34180e55857cfd98aa080435d309/src/Identity/Core/src/SignInManager.cs#L301

There is a call:

`var user = await UserManager.FindByIdAsync(principal.Identity.Name);`.

This results in the code passing the username to the 'FindById' method instead of the user ID. It should be changed to

`var user = await UserManager.GetUserAsync(principal);`

(same as line 278 in `ValidateSecurityStampAsync`)

https://github.com/dotnet/aspnetcore/blob/75368e2d448d34180e55857cfd98aa080435d309/src/Identity/Core/src/SignInManager.cs#L278

**Comment by halter73** [comment]
I think the issues is that we're dealing with two different `ClaimsPrincipal` instances with different names from two different cookies. On line 278, in `ValidateSecurityStampAsync`, the `ClaimsPrincipal` comes from the normal `IdentityConstants.ApplicationScheme` cookie that stores the logged in user. This is called by `SecurityStampValidator.ValidatePrincipalAsync` and uses `UserManager.GetUserAsync(ClaimsPrincipal)` which in turn uses `IdentityOptions.UserIdClaimType` to retrieve the user ID before calling `FindByIdAsync` as you'd expect for the main `ClaimsPrincipal`.

https://github.com/dotnet/aspnetcore/blob/fed7b428b2c34cc1850557111f945e4cbe5d1268/src/Identity/Core/src/IdentityServiceCollectionExtensions.cs#L59-L66

On line 301, in `ValidateTwoFactorSecurityStampAsync`, the `ClaimsPrincipal` comes from a different `IdentityConstants.TwoFactorRememberMeScheme` cookie that stores the just the user ID and security stamp and stores the user ID using `ClaimTypes.Name`. This is called by `SecurityStampValidator.ValidateAsync` and correctly uses `UserManager.FindByIdAsync(principal.Identity.Name)`.

https://github.com/dotnet/aspnetcore/blob/fed7b428b2c34cc1850557111f945e4cbe5d1268/src/Identity/Core/src/SignInManager.cs#L785-L796

https://github.com/dotnet/aspnetcore/blob/fed7b428b2c34cc1850557111f945e4cbe5d1268/src/Identity/Core/src/IdentityServiceCollectionExtensions.cs#L72-L79
