### ISSUE TITLE
Question: How to detect whether the current app is a normal ASP.NET Core application or a Blazor app?

### ISSUE THREAD

**Issue by zhiyuanliang-ms** [dotnet/aspnetcore#56633]
Knowing the approximate proportion of different kinds of ASP.NET applications out of all customers could be helpful for us.

May I ask some instruction or advice on how to detech whether the current application is a Blazor app(Blazor server app or webassembly) or not?

**Comment by javiercn** [comment]
@zhiyuanliang-ms thanks for contacting us.

There's no way for you to do this at runtime from outside the application. At compile time you can look at the project files and SDKs being referenced by csproj files to determine if the app includes components (.razor files) or references webassembly, but in general, there's no fool proof method to do this, as an app can contain server, webassembly, and non blazor UI.
