### ISSUE TITLE
EditForm that is placed on an interactive server page does not trigger submit handler.

### ISSUE THREAD

**Issue by htmlsplash** [dotnet/aspnetcore#56634]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Context:
Blazor Web app project, static SSR as default.

Problem described is on the page (with Interactive Server render mode) that contains EditForm that captures user's input but OnSubmit doesn't fire it's corresponding event handler.
I can see in the browser the web-socket sending message, but nothing happens, no event handler is triggered.

Here's the Code:

`@page "/clientsearch2"
@layout PimarcLayout
@rendermode InteractiveServer
`

`<EditForm Model="ClientCriteria" OnSubmit="OnClientSearch">`

Content of Edit From:

`  <InputText @bind-Value="ClientCriteria.ClientNumber" class="form-control" />
				<button class="btn btn-primary">Search</button>
				<button class="btn btn-secondary" type="reset">Reset</button>`

`Received Client #: @ClientCriteria.ClientNumber
<p />
Submitted flag: @_submittedFlag

@code {

	public ClientSearchCriteria2 ClientCriteria { get; set; } = new();
	private string _submittedFlag;

	public void OnClientSearch()
	{
		_clientCriteria = ClientCriteria;
	}

	private ClientSearchCriteria2 _clientCriteria = new();

	protected override void OnInitialized()
	{
	}

	private void OnCriteriaChanged(ClientSearchCriteria2 clientCriteria)
	{
		_clientCriteria = clientCriteria;
		_submittedFlag = "form submitted";
	}

	
}`

**Comment by htmlsplash** [comment]
I figured out the problem, it works.

**Comment by olaande** [comment]
@htmlsplash what was the problem?

**Comment by htmlsplash** [comment]
@olaande Sorry, I cannot recall by now. Sometimes I noticed that when an unhandled exception is thrown it will break functionality. The way I find out about the exception is by attaching the debugger.
