### ISSUE TITLE
blazor.web.js using deprecated API according to Chrome Lighthouse.

### ISSUE THREAD

**Issue by richardaubin** [dotnet/aspnetcore#56637]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When running a lighthouse audit on my website, the following Best Practice warning is returned:

![image](https://github.com/dotnet/aspnetcore/assets/37956997/d7dbc5a0-d4d8-46a8-941c-2c78692cea0c)

Depecration expected to be final by end of Q1 2025

### Expected Behavior

Visit https://developer.chrome.com/docs/web-platform/deprecating-unload#alternatives_to_unload_events for more information.

### Steps To Reproduce

Run a blazor web application.
Open Chrome DevTools
Open Lighthouse
Perform audit.

### .NET Version

8.0.302

**Comment by richardaubin** [comment]
found duplicate issue

**Comment by coderdnewbie** [comment]
This issue is still happening. Can it be examined again?

See https://github.com/dotnet/aspnetcore/issues/56081#issuecomment-2282780229 for a possible solution.
