### ISSUE TITLE
Use System.Threading.Lock in hybrid cache when locking

### ISSUE THREAD

**Issue by Meir017** [dotnet/aspnetcore#56638]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

The new HybridCache library doesn't use the new Lock object when locking

### Describe the solution you'd like

in https://github.com/dotnet/aspnetcore/blob/main/src/Caching/Hybrid/src/Internal/DefaultHybridCache.SyncLock.cs plain objects are used for locking, we could use the new Lock object

**Comment by JamesNK** [comment]
Using it is worth looking at. I created a new issue that considers replacing it everywhere: https://github.com/dotnet/aspnetcore/issues/56638

Closing this in favor of the broader issue.

**Comment by JamesNK** [comment]
Opps. This one: https://github.com/dotnet/aspnetcore/issues/56794
