### ISSUE TITLE
Can I do this with client-side only programming with Balzor

### ISSUE THREAD

**Issue by zydjohnHotmail** [dotnet/aspnetcore#5665]
Hello:
I want to know if I can do this with client-side only programming with Blazor.
I need to monitor a remote web site"www.randomNum.com", (a fake domain name), which has a lot of JavaScript scripts, one of them is like this one:

<!doctype html>
<title>Simple Random Generator</title> 
<script type="text/javascript"> 
document.getElementById("CurrentNumber").innerHTML = Math.random().toString(); 
</script>
</html>
 
The web site will from time to time run the JavaScript to show a random number on its web site, the time, when the script run is totally random. 
I want to write a C# project using Blazor client-side to monitor the web site and get the random numbers generated by the JavaScript.
As most of documents I read about Blazor are talking about using Blazor to build a web site using .cshtml as file name extension.  
But here, what I want to do, the server side is totally out of my control, I can only do some client-side job.
I want to know if Blazor on client-side can do this or not? Like visit a remote web site, and  render the HTML contents, and listen to the DOM events, i.e. DOMContentLoaded, etc.
If it is possible, it is better to show me some sample code here for my current question: to get the dynamic contents generated by JavaScript.
I am using VS2017 Version 15.9.3 and latest Blazor version on Windows 10.
If Blazor can't do this at the moment, please also advice if Blazor could do this in the future.  I don't think many people need to build a Web Server using C#, they could build a Web Server using JavaScript for the dynamic contents, which is standard way nowadays.  But I believe, many people could like to use .NET based browser to visit web sites built by other people.
Thanks,

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're closing this issue as there was no community involvement here for quite a while now.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
