### ISSUE TITLE
PolicyEvaluator doesn't have correct logic

### ISSUE THREAD

**Issue by slowjams** [dotnet/aspnetcore#56656]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

https://source.dot.net/#Microsoft.AspNetCore.Authorization.Policy/PolicyEvaluator.cs,99

I believe the logic is wrong here, so if authorization pass while authentication doesn't pass, the response is 200 not 401.

e.g an endpoint accessed by an unauthenticated user below

```
[HttpGet]
[Authorize(Policy = "AtLeast18")]
public IEnumerable<string> GetBeer()
       => new[] { "Tsingtao", "Carlton"};

```

```
builder.Services.AddAuthorization(options =>
{
    options.AddPolicy("AtLeast18", policyBuider => policyBuider.Requirements.Add(new MinimumAgeRequirement(18)));
});
```

```
public class MinimumAgeHandler : AuthorizationHandler<MinimumAgeRequirement>
{
    protected override Task HandleRequirementAsync(AuthorizationHandlerContext context, MinimumAgeRequirement requirement)
    {
        context.Succeed(requirement);  // a junior developer make a mistake in checking user's age and make it equivalent as everyone is over 18

        return Task.CompletedTask;
    }
}
```

despite of the mistake made by the junior developer, and I would still expect the response to be 401 rather than 200

### Expected Behavior

he response to be 401 rather than 200

### .NET Version

.NET 8

**Comment by joegoldman2** [comment]
The requirement `DenyAnonymousAuthorizationRequirement` is missing from your policy. You can call `RequireAuthenticatedUser` to add it:

```cs
builder.Services.AddAuthorization(options =>
{
    options.AddPolicy("AtLeast18",
        policyBuider =>
        {
            policyBuider.RequireAuthenticatedUser();
            policyBuider.Requirements.Add(new MinimumAgeRequirement());
        });
});
```

**Comment by joegoldman2** [comment]
The requirement `DenyAnonymousAuthorizationRequirement` is missing from your policy. You can call `RequireAuthenticatedUser` to add it:

```cs
builder.Services.AddAuthorization(options =>
{
    options.AddPolicy("AtLeast18",
        policyBuider =>
        {
            policyBuider.RequireAuthenticatedUser();
            policyBuider.Requirements.Add(new MinimumAgeRequirement(18));
        });
});
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.

Did you get chance to validate @joegoldman2 's suggestion above? That seems reasonable.
