### ISSUE TITLE
Add a feature to Server-driven, client-rendered applications just like Hybirdly.

### ISSUE THREAD

**Issue by sardar97** [dotnet/aspnetcore#56657]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I like to have a blazor web app which render from client with full interactivity and also access to database without using API.

### Describe the solution you'd like

**Hybirdly** is one of the newest technologies which is working on Server-driven, client-rendered applications.
I would really like to see this feature in blazor. I want to be able to create a full stack blazor web app without writing API.
I really hope to see this great feature in .Net 10 with Blazor.

[Hybirdly Website](https://hybridly.dev)

**Comment by javiercn** [comment]
@sardar97 thanks for contacting us.

We already have other issues tracking improvements in this space.

**Comment by sardar97** [comment]
> @sardar97 thanks for contacting us.
> 
> We already have other issues tracking improvements in this space.

can u provide them here please?

**Comment by 544609380** [comment]
Hi Any one can help me to register in mobile bank application using an authentication app having my data but unverified user , and here is the issue I can’t make the authentication app verified .If any one interested please contact me ( ***@***.*** )   and this service is definitely will be paid. ‫أُرسلت من الـ iPhone‬‫في 07‏/07‏/2024 الساعة 13:32، كتب/كتبت ‏sardar ***@***.***>:‬﻿

@sardar97 thanks for contacting us.
We already have other issues tracking improvements in this space.

can u provide them here please?

**Comment by sardar97** [comment]
@jongalloway
