### ISSUE TITLE
[Blazor Webapp] Handling browser close/reload in server and wasm mode

### ISSUE THREAD

**Issue by julienGrd** [dotnet/aspnetcore#56683]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello guys, i have a blazor webapp (.net 8) which can run both in webassembly and server mode.

For different reasons, i have to "know" when a client reload the app or close it.

For the server mode, it seem it can be handle by the OnCircuitClosedAsync of the circuitHandler, or by the dispose method of a top level component of the app (for example the Routes component). These event are also called when the circuit is closed which is perfect for me

For the wasm mode, the OnCircuitClosedAsync is obviously not useable, but im very surprised the dispose seem not called in the Routes Component.

So for now, the only way i find to catch that in wasm mode is to implement someting like that in js
````
 window.addEventListener('unload', (event) => {
     if (self.appInstance) {
         self.appInstance.invokeMethodAsync("Close");//appinstance is the Routes component inject at startup, this method call a JsInvokable in the c# side 
     }
 });
````

surprisely also, in server side, the solution above seem not work.

so for now i was stay on the idea :
- use the Dispose when the app is server
- use the js unload event when the app is wasm

But in production i have very strange behavior in my app, it seem the uload is sometimes not call for a wasm client (so i never detect it) and sometimes it start to work for a serverside client (so it detect two times which is not good for me).

first, I would like to know if the behavior i describe is something expected regarding these two execution mode
Second, what your general guideline for handle this scenario in these modes ?

thanks for your help !

### Expected Behavior

Have a unique way to handle properly an app which unload (by closing browser, reload, or lost signalr connection in case of server)

### .NET Version

8.0.300

**Comment by javiercn** [comment]
@julienGrd thanks for contacting us.

Dispose doesn't get on the client on reload because the runtime gets destroyed, so you need to use the `unload` event. You can't really differentiate between "reload" or "close" afaik. 

The one thing you could try, which I'm not sure will work, is to put some data in `sessionStorage` and make your `decision` based on that, I don't remember however if session state gets cleared on F5.
