### ISSUE TITLE
Minimal API Endpoint gives "Invalid antiforgery token" error

### ISSUE THREAD

**Issue by iustin94** [dotnet/aspnetcore#56687]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have an API endpoint mapped to handle a Logout request. 

![image](https://github.com/dotnet/aspnetcore/assets/13846875/cebc9fda-df6b-4476-8a40-c8a141f15a57)

In my client component, when I try to make a request to this endpoint I get the error: 

![image](https://github.com/dotnet/aspnetcore/assets/13846875/a78b98e1-4b7c-4dc6-b9ec-10c8182ea67b)

I tried making this work by following the documentation example at https://learn.microsoft.com/en-us/aspnet/core/blazor/call-web-api?view=aspnetcore-8.0#antiforgery-support but failed.

First, because the documentation example is outdated. The AntiforgeryRequestToken has no RequestToken field.

![image](https://github.com/dotnet/aspnetcore/assets/13846875/7990d39b-ef8b-423a-82a0-fd2c63074f4a)

I tried making it work using the GetAndStoreTokens call, which seems to be the up to date API for this.
![image](https://github.com/dotnet/aspnetcore/assets/13846875/046daa77-c1be-4b95-8aa5-776e1cb4c785)

However when the request is posted, the same error says again:
 
![image](https://github.com/dotnet/aspnetcore/assets/13846875/1b8de31c-5a53-4433-9d7c-e9a5386be695)

As far as I can tell, the cookie is not being set in the HttpClient headers properly. I do set the token, but the cookie is missing.
I have tried setting the header to different names but nothing has worked so far.

The use of a <form> element however, works just fine, with the request passing.
![image](https://github.com/dotnet/aspnetcore/assets/13846875/cd1ccccc-1e40-4b40-95ef-3e87f690884b) 

### Expected Behavior

I expect to have the same bahavior possible through using a <form> element or programmatically making an HttpClient and a request.

### Steps To Reproduce

Follow the documentation. Create a template project, use the example code and it will not work.

### .NET Version

.net8

**Comment by iustin94** [comment]
I forgot to mention that there was this issue #49929 which had a similar problem, but it was accepted as fixed with the conclusion being to not use antiforgery at all at the endpoint?

**Comment by javiercn** [comment]
@iustin94 thanks for contacting us.\

It's not clear that what you are doing is correct. When you say client component do you mean `Blazor WebAssembly`? If that's the case, `GetAndStoreTokens` is not something that you can use. Not sure how you are getting a reference to `IAntiforgery` on the client.

What might be happening in this case is that the antiforgery token might have been discarded if it wasn't consumed during the initial render of the app (we have a bug to fix it). You can try resolving the `AntiforgeryStateProvider` on Program.cs and try and access it there and that should restore it and cache it in memory.

**Comment by iustin94** [comment]
@javiercn So the client component is a blazor SSR rendered component. The GetAndStoreTokens works fine as I sayd previously, but the issue that I have is that when I make the request from my component, by using the instantiated HttpClient, the middleware throws an error saying that the request is bad.

Here is the full code for my component. This is a .net8 project using Blazor Server Side. This is the code for the MainLayout component. In the navigation bar you can see I have both a Logout button and a Logout form element. When the form submits, everything seems to work as it should. When the Logout button is clicked on the other hand, the Logout method fails and gets the BadRequest error.


`
@inherits LayoutComponentBase
@using System.Security.Claims
@using Application.Company.DtO
@using Application.UserAccount.Queries
@using MediatR
@using Microsoft.AspNetCore.Antiforgery
@inject IAntiforgery Antiforgery
@inject IHttpContextAccessor HttpContextAccessor

@if (model == null)
{
    <div class="text-center">
        <RadzenProgressBar Style="width: 51%" />
    </div>
    return;
}

<RadzenLayout>
    <RadzenHeader>
        <RadzenStack Orientation="Orientation.Horizontal" AlignItems="AlignItems.Center" Gap="0">
            <RadzenSidebarToggle Click="@(() => _sidebarExpanded = !_sidebarExpanded)" />
            <RadzenLabel Text="@model.UserName" />
            <RadzenButton Click="@Logout" Text="Logout"></RadzenButton>
            <form action="Account/Logout" method="post">
                <AntiforgeryToken/>
                <input type="hidden" name="ReturnUrl" value="@NavigationManager.Uri"/>
                <button type="submit" class="nav-link">
                    <span class="bi bi-arrow-bar-left-nav-menu" aria-hidden="true"></span> Logout
                </button>
            </form>
        </RadzenStack>
    </RadzenHeader>
    <RadzenSidebar @bind-Expanded="@_sidebarExpanded">
        <RadzenPanelMenu>
            <RadzenPanelMenuItem
                Text="Company"
                Icon="business"
                Click="@(() => NavigationManager.NavigateTo($"/company/{model.Company.Id}"))"/>
        </RadzenPanelMenu> 
        <div class="rz-p-4">
            Sidebar
        </div>
    </RadzenSidebar>
    <RadzenBody>
        <div class="rz-p-4">
            @Body
        </div>
    </RadzenBody>
    <RadzenFooter>
        Footer
    </RadzenFooter>
</RadzenLayout>

RadzenDialog></RadzenDialog>

@code {
    [Inject] public required NavigationManager NavigationManager { get; set; }
    [Inject] IHttpClientFactory HttpClientFactory { get; set; }
    [Inject] AuthenticationStateProvider AuthenticationStateProvider { get; set; }
    [Inject] public IMediator Mediator { get; set; }
    
    private class MainLayoutModel(string userName, string identityUserId, CompanyDtO company)
    {
        public string UserName { get; set; } = userName;
        public string IdentityUserId { get; set; } = identityUserId;
        public CompanyDtO Company { get; set; } = company;
    }

    bool _sidebarExpanded = true;

    private ClaimsPrincipal currentUser;
    private MainLayoutModel model;

    protected override async Task OnInitializedAsync()
    {
        var authState = await AuthenticationStateProvider.GetAuthenticationStateAsync();
        currentUser = authState.User;

        if (currentUser.Identity.IsAuthenticated)
        {
            var userName = currentUser.Identity.Name;
            var identityUserId = currentUser.FindFirst(ClaimTypes.NameIdentifier).Value;
            var command = new GetOwnedCompany(identityUserId);
            var company = await Mediator.Send(command, CancellationToken.None);
            
            model = new MainLayoutModel(userName, identityUserId, company);
        }
        
        await base.OnInitializedAsync();
    }

    
    private HttpClient HttpClient
    {
        get
        {
            var client = HttpClientFactory.CreateClient();
            client.BaseAddress = new Uri(NavigationManager.BaseUri);
            return client;
        }
    }

    public async Task Logout()
    {
        var antiforgery = Antiforgery.GetAndStoreTokens(HttpContextAccessor.HttpContext);
        
        var requestMessage = new HttpRequestMessage(HttpMethod.Post, "Account/Logout");
        requestMessage.Headers.Add(antiforgery.HeaderName, antiforgery.RequestToken);
        
        // Add returnUrl content to the request
        var content = new FormUrlEncodedContent(new Dictionary<string, string>
        {
            { antiforgery.FormFieldName, antiforgery.RequestToken},
            {"ReturnUrl", NavigationManager.Uri}
        });
        requestMessage.Content = content;
        
        // Send the request
        var response = await HttpClient.SendAsync(requestMessage);

        // Handle the response (e.g., redirect the user to the login page)
        if (response.IsSuccessStatusCode)
        {
            NavigationManager.NavigateTo("/Account/Login");
        }
    }
}`

**Comment by javiercn** [comment]
@iustin94 thanks for the additional details.

So to make sure we understand. You have an SSR component and from within that component you are making an HTTP Client call to yourself?

**Comment by iustin94** [comment]
> @iustin94 thanks for the additional details.
> 
> So to make sure we understand. You have an SSR component and from within that component you are making an HTTP Client call to yourself?

Yes, it is all in the "Logout" method of the component I posted above.

**Comment by javiercn** [comment]
@iustin94 thanks for the additional details.

That's likely not going to work. You need to setup the HttpClient instance with the auth cookie you received on the request to the server + the antiforgery cookie + antiforgery request token in the header.

Based on this, we don't think there's a bug here, just missing requirements on a scenario we don't directly support/recommend.

I'm not sure why you are trying to log out via an additional API call to the server as opposed to logging out directly. The Identity endpoints are meant to be used by JS clients and native apps and not by an SSR app.

**Comment by iustin94** [comment]
> @iustin94 thanks for the additional details.
> 
> That's likely not going to work. You need to setup the HttpClient instance with the auth cookie you received on the request to the server + the antiforgery cookie + antiforgery request token in the header.
> 
> Based on this, we don't think there's a bug here, just missing requirements on a scenario we don't directly support/recommend.
> 
> I'm not sure why you are trying to log out via an additional API call to the server as opposed to logging out directly. The Identity endpoints are meant to be used by JS clients and native apps and not by an SSR app.

Thank you for the input. The 3 conditions are what I though I was missing and am trying to understand why they are missing and am looking  to see an example of how to set this up properly. I think at this point it's not a reason to other than on my part understanding the mechanism of how this works.

Regarding the identity endpoint comment, I don't think I am using the ones you mention, the standard ones. I have some simple defined endpoints, and the logout one is the following: 

```
  public static IEndpointConventionBuilder MapAdditionalIdentityEndpoints(this IEndpointRouteBuilder endpoints)
    {
        ArgumentNullException.ThrowIfNull(endpoints);

        var accountGroup = endpoints.MapGroup("/Account");
        accountGroup.MapPost("/Logout", async (
            ClaimsPrincipal user,
            SignInManager<IdentityUser> signInManager,
            [FromForm] string returnUrl) =>
        {
            await signInManager.SignOutAsync();
            return TypedResults.LocalRedirect($"~/{returnUrl}");
        });
   }
```

Is this what you mean by endpoint mean to be used by JSClients?
