### ISSUE TITLE
PageTitle component added in BuildRenderTree do not update the "title".

### ISSUE THREAD

**Issue by rpc-scandinavia** [dotnet/aspnetcore#56708]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The page title is not updated from a `PageTitle` component, added to a component in `BuildRenderTree`.

### Expected Behavior

The `title` in the `head` should be updated with the text.

### Steps To Reproduce

`dotnet new blazor`

Add `Render.razor.cs` to the `Pages` directory:

```
using System;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Rendering;
using Microsoft.AspNetCore.Components.Web;
namespace Test.Components.Pages;

[Route("/render")]
public class Render : ComponentBase {

    protected override void OnAfterRender(bool firstRender) {
        if (firstRender) {
            StateHasChanged();
        }
    }

    protected override void BuildRenderTree(RenderTreeBuilder builder) {
        base.BuildRenderTree(builder);

        // Add PageTitle component
        builder.OpenComponent<PageTitle>(0);
        builder.AddContent(1, "Test Title Here");
        builder.CloseComponent();

        // Add other components or content here
        builder.OpenElement(2, "div");
        builder.AddContent(3, "Content of Component A");
        builder.CloseElement();
    }
}
```

Add the `render` page to the menu in `NavMenu.razor`.

`dotnet run`

Notice that the page title is updated on all the other pages, but not the "/render" page.
When navigating to the `render` page, the `title` is emptied/cleared.

### .NET Version

8.0.303

**Comment by javiercn** [comment]
@rpc-scandinavia thanks for contacting us.

There's no difference between compiled razor code and handcrafted rendertrees. We suggest you look at the generated razor code for another component where it works to spot the differences between the generated code and your code.

**Comment by rpc-scandinavia** [comment]
@javiercn, I did not think of looking in the generated file.
This works:

```
// Add PageTitle component
builder.OpenComponent<PageTitle>(0);
builder.AddAttribute(1, "ChildContent", (RenderFragment)((builder2) => {
    builder2.AddContent(2, "Test Title Here");
}));
builder.CloseComponent();
```

This don't work:

```
// Add PageTitle component
builder.OpenComponent<PageTitle>(0);
builder.AddContent(1, "Test Title Here");
builder.CloseComponent();
```

Normally you use the component like this: `<PageTitle>Test Title Here</PageTitle>`, so I assumed that the title text should be added with `AddContent`.

Thank you for the hint.
