### ISSUE TITLE
System.NullReferenceException at Microsoft.AspNetCore.Mvc.ModelBinding.QueryStringValueProviderFactory.CreateValueProviderAsync

### ISSUE THREAD

**Issue by mohamadLy** [dotnet/aspnetcore#56722]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am getting a null reference from `Microsoft.AspNetCore.Mvc.ModelBinding.QueryStringValueProviderFactory.CreateValueProviderAsync` for some request

Call stack

![image](https://github.com/dotnet/aspnetcore/assets/9387199/09bf28d7-73cd-41b3-b250-c69da3894a45)

### Exceptions (if any)

![image](https://github.com/dotnet/aspnetcore/assets/9387199/bda28f4f-0e1e-4a9e-a442-dea6b106ab27)

### .NET Version

8

**Comment by martincostello** [comment]
Are you dispatching any work onto a background thread or anything? The only obvious source of a `NullReferenceException` at that location would be this line:

https://github.com/dotnet/aspnetcore/blob/a78ef02aeadf84869a0c35f915a2e46a762b00cd/src/Mvc/Mvc.Core/src/ModelBinding/QueryStringValueProviderFactory.cs#L21

The `HttpContext` being null can often happen when the `HttpContext` is accessed off the HTTP request's thread.
