### ISSUE TITLE
[Component Vulnerability]please consider to upgrade ws in @microsoft/signalr from @^7.4.5 to @^7.5.10

### ISSUE THREAD

**Issue by tmbp95** [dotnet/aspnetcore#56723]
### Is there an existing issue for this?
- [x] I have searched the existing issues
### Describe the bug
The @microsoft/signalr has ws@^7.4.5 as a dependency ([here](https://github.com/dotnet/aspnetcore/blob/v7.0.14/src/SignalR/clients/ts/signalr/package.json#L58)) that is vulnerable to Denial of Service (DoS) when the number of received headers exceed the server.maxHeadersCount or request.maxHeadersCount threshold.
snyk suggests that the affecting [ws](https://security.snyk.io/package/npm/ws) versions are >=2.1.0 <5.2.4 >=6.0.0 <6.2.3 >=7.0.0 <7.5.10 >=8.0.0 <8.17.1 (more [info](https://security.snyk.io/vuln/SNYK-JS-WS-7266574))

### Expected Behavior
upgrade ws in @microsoft/signalr from @^7.4.5 to @^7.5.10 to solve this problem.

**Comment by resmipremjith** [comment]
Can you please tell when this fix will be available in SignalR npm package?

**Comment by stasberkov** [comment]
Please fix this. Trivy audit highlights this issue.

**Comment by wtgodbe** [comment]
We will publish a new package for the July release with the dependency patched
