### ISSUE TITLE
NavigationManager.NavigateToLogout() stuck on authentication/logout-callback

### ISSUE THREAD

**Issue by dean-azure** [dotnet/aspnetcore#56732]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This task https://github.com/dotnet/aspnetcore/issues/53131

Is marked as closed but I am still experiencing a very similr issue.

In our deployed environments when the user logs out it navigates to **/authentication/logout-callback**

Displays:
Processing logout callback...

But I cannot replicate this locally.   So when I run in localhost the logout works as expected.   But, I cannot diagnose what the problem is locally since the deployed version has different behavior

Our project has the 8.x Microsoft.AspNetCore.Components.WebAssembly.Authentication library the service is configured to use .net 8

The problem persists.

Additionally, I looked at the session values, the user remains logged in.

### Expected Behavior

The user should be fully logged out

### Steps To Reproduce

Already described above

### .NET Version

8.0

**Comment by javiercn** [comment]
@dean-azure thanks for contacting us.

Can you provide more details?
* What auth provider are you trying to use.
* Are there any errors on the developer console? (F12).
* Have you turned logging to Debug level on the client?
  * That will produce a detailed log of every operation the client is doing.

**Comment by dean-azure** [comment]
Our provider is OKTA

No errors are logged in the console.

[beta.commoditysolutions.stonex.com-1721069751141.log](https://github.com/user-attachments/files/16238963/beta.commoditysolutions.stonex.com-1721069751141.log)

I've attached a the debug log output from edge in debug mode.

**Comment by javiercn** [comment]
@dean-azure thanks for the additional details.

Unfortunately, we don't think you've setup the login level to debug correctly. There should be way more logs appearing on the console if that were the case. Ensure you set the log level for `Microsoft.AspNetCore.Components.WebAssembly.Authentication` to debug.

What might have happened is that the directive for Microsoft.AspNetCore has overridden the log level you might have setup. If for some reason setting it up in config doesn't work, set it on Program.cs too

You should see logs that have [Microsoft.AspNetCore.Components.WebAssembly.Authentication] in the console when things are correctly setup.

**Comment by dean-azure** [comment]
"**Ensure you set the log level for Microsoft.AspNetCore.Components.WebAssembly.Authentication to debug.**"

Where/how do I set this?

**Comment by javiercn** [comment]
@dean-azure here is a sample

https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/logging?view=aspnetcore-8.0#client-side-authentication-logging

**Comment by dean-azure** [comment]
> @dean-azure here is a sample
> 
> https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/logging?view=aspnetcore-8.0#client-side-authentication-logging

Sorry, this I know how to do.   I thought you were referring to a browser setting.   I can do this later.   Setting logging to debug brings the UI to a halt practically so I have to schedule.   Will get it back to you within the next day or so.

**Comment by dean-azure** [comment]
Sorry for the delay in getting this to you other production issues have kept me busy recently.   :D

[Debugoutput.zip](https://github.com/user-attachments/files/16515842/Debugoutput.zip)
