### ISSUE TITLE
Hard to debug role-based authorization failures

### ISSUE THREAD

**Issue by chitturs** [dotnet/aspnetcore#56734]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I followed this snippet https://learn.microsoft.com/en-us/aspnet/core/security/authorization/roles?view=aspnetcore-8.0#policy-based-role-checks. But, was getting access denied. I already validate the token claims having the right "roles" claim type. However, these issues made debugging way harder than it should be (several days).

### Describe the solution you'd like

1. ASP.NET authorization failures are not logged if LoggingLevel is NOT "Debug".
2. The ASP.NET logging showed an authorization failure but did not indicate that it was due to the claim type being "roles" which apparently is not what the claim check code checks.
3. https://learn.microsoft.com/en-us/dotnet/api/system.security.claims.claimsidentity.roleclaimtype?view=net-8.0 nugget was hidden deep which was all I needed to add to TokenValidationParameters to get this fixed.

**Comment by MackinnonBuck** [comment]
Thanks for reaching out, @chitturs.

Could you please share the complete logs and explain which specific log messages you think should have increased severity? Please exclude sensitive information, if present in the logs.

**Comment by chitturs** [comment]
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
      Authorization failed. These requirements were not met:
      RolesAuthorizationRequirement:User.IsInRole must be true for one of the following roles: (HelloAzureAdmin|HelloAzureUser)
      RolesAuthorizationRequirement:User.IsInRole must be true for one of the following roles: (HelloAzureAdmin)

That only shows if I set the logging level to "Debug". It also doesn't say what claim type it is checking. In this case, "roles" claim has HelloAzureAdmin.

**Comment by mkArtakMSFT** [comment]
Thanks for the information, @chitturs.
Choosing to log more information is somewhat dangerous and we are very considerable when it comes to choosing a log level for messages. The more logs, the noisier a service will be and so will the cost associated to it will increase. These particular messages seem to be logged with the correct level and we think it will continue to be logged as `Debug`.
Given that we haven't heard other requests similar to this one, we'll close this issue for now. If more feedback comes in the future with similar requests, we may start tracking these for future consideration.

**Comment by chitturs** [comment]
May I suggest adding one piece of additional information to the Debug log per below?

_The ASP.NET logging showed an authorization failure but did not indicate that it was due to the claim type being "roles" which apparently is not what the claim check code checks.
https://learn.microsoft.com/en-us/dotnet/api/system.security.claims.claimsidentity.roleclaimtype?view=net-8.0 nugget was hidden deep which was all I needed to add to TokenValidationParameters to get this fixed._
