### ISSUE TITLE
JsonSerializerIsReflectionDisabled exception in Blazor despite using Source Generator.

### ISSUE THREAD

**Issue by voroninp** [dotnet/aspnetcore#56752]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

First, I am surprised that AOTed Blazor does not disable reflection-based serialization by default.
Second, when I set `<JsonSerializerIsReflectionEnabledByDefault>false</JsonSerializerIsReflectionEnabledByDefault>` I get 
> Error: AggregateException_ctor_DefaultMessage (JsonSerializerIsReflectionDisabled)

![image](https://github.com/dotnet/aspnetcore/assets/9202028/df484120-f4ad-4378-b07f-7757fe7d7c93)

Despite the fact that I use SourceGenerator.
> System.InvalidOperationException: JsonSerializerIsReflectionDisabled
at Microsoft.JSInterop.JSInProcessRuntime.Invoke[Boolean](String , Int64 , Object[] )
at Microsoft.JSInterop.JSInProcessRuntime.Invoke[Boolean](String , Object[] )
at Blazored.LocalStorage.BrowserStorageProvider.ContainKey(String key)
at DutchVerbs.Spa.Infrastructure.Application.TryGetStateFromStorage(ApplicationStateDto& stateDto)
at DutchVerbs.Spa.Infrastructure.Application.InitializeAsync()

### Expected Behavior

Well, my expectation is that is should work.

### Steps To Reproduce

See solution https://github.com/voroninp/DutchVerbs
and publsihed version https://voroninp.github.io/DutchVerbs/

### .NET Version

8.0.303

**Comment by javiercn** [comment]
@voroninp thanks for contacting us.

This is by design. Blazor relies on reflection for JSON serialization.

**Comment by voroninp** [comment]
@guardrex , can we document it somewhere? ;-)

@javiercn , then having at least a warning if it is disabled would be nice, IMO.
