### ISSUE TITLE
Future of standalone WASM applications

### ISSUE THREAD

**Issue by akozhikkot** [dotnet/aspnetcore#56761]
Hello Team,

This is a general question regarding the future of "Standalone WASM" projects now that we have the Blazor Web app providing options for Global Web assembly interaction model. 

From a strategic perspective _is Blazor Web App with Interaction mode preferred over Standalone WASM model_. 

We are starting a new project which is a strategic project. 

It is an internal project so initial load times etc. are not very big factors here. _But framework and model being supported and continuously updated is a big consideration._ 

We are also seeing the new set of frameworks on the JS front Next.JS etc which (I think) is following a similar approach to Blazor Web App with interactivity.

Could you share if there is any thought process along these lines or any documentation I can refer to

**Comment by javiercn** [comment]
@akozhikkot thanks for contacting us.

No model is preferred over the other, it depends on your needs/preferences. Blazor Web is the equivalent of the old WebAssembly Hosted model just with increased capabilities.

We don't see Webassembly standalone any separate from any other Blazor flavor and we offer the same level of support to it. 

Your choice depends likely on your requirements and the trade-offs you want to make. Blazor web + webassembly adds additional complexity if you want to effectively leverage prerendering, streaming rendering, etc. But in many cases, it also simplifies things as you don't have to make the entire app a webassembly app and in that way you avoid the extra overhead of having to access data from the server via HttpClient + separate endpoint.
