### ISSUE TITLE
ApiDescriptionProvider does not return SupportedResponseTypes when using controllers with Results<T>

### ISSUE THREAD

**Issue by jgarciadelanoceda** [dotnet/aspnetcore#56763]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have been studyng the issue domaindrivendev/Swashbuckle.AspNetCore#2595 and have been playing with the new package Microsoft.AspNetCore.OpenApi, and when the response of a Controller is a Results<T> I do not see the response in either SwashBuckle or AspNetCore.OpenApi.

I have just created a repro: https://github.com/jgarciadelanoceda/OpenApiResults where you can see that the OpenApi generated is missing the response for the Controller.

This is the generated schema:

```javascript
"/api/Enum": {
      "get": {
        "tags": [
          "Enum"
        ],
        "parameters": [
          {
            "name": "logLevel",
            "in": "query",
            "schema": {
              "type": "integer",
              "default": 4,
              "nullable": true
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        },
        "x-aspnetcore-id": "5e99fe30-6a3d-4302-8ddf-c3098e430266"
      }
    }
``` 
Please note that there is no reference to the enum neither in parameters or in the responseType.

For the response, I guess that the thing that is missing is the SupportedResponseTypes

### Expected Behavior

I expect the response of the OpenApi generated schema to have the enum reference:

```javascript
 "/api/Enum": {
      "get": {
        "tags": [
          "Enum"
        ],
        "parameters": [
          {
            "name": "logLevel",
            "in": "query",
            "schema": {
              "allOf": [
                {
                  "$ref": "#/components/schemas/LogLevel"
                }
              ],
              "default": 4
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
 "content": {
              "text/plain; v=1.0": {
                "schema": {
                  "$ref": "#/components/schemas/LogLevel"
                }
              },
              "application/json; v=1.0": {
                "schema": {
                  "$ref": "#/components/schemas/LogLevel"
                }
              },
              "text/json; v=1.0": {
                "schema": {
                  "$ref": "#/components/schemas/LogLevel"
                }
              }
            }
          }
        }
      }
    }
``` 

### .NET Version

Net9

**Comment by vernou** [comment]
In your example, the controller action is :
```
[HttpGet]
public IResult Get(LogLevel? logLevel = LogLevel.Error)
{ ... }
```
The controller action return `IResult`, this can be any type of response. So **AspNetCore.OpenApi** generator can't generate the OpenAPI with the specific response.

---

You can add metadata to the controller action with `[ProducesResponseType]` to specify the expected response or return **TypedResult**.

**Comment by jgarciadelanoceda** [comment]
In any case if I change the method signature to be:
```c#
[HttpGet]
public Results<Ok<Person>, NotFound> Get(LogLevel? logLevel = LogLevel.Error) =>
	logLevel == LogLevel.Error ?
	TypedResults.Ok(new Person("a", "b")) :
	TypedResults.NotFound();
``` 

The result is the same

**Comment by vernou** [comment]
ASP.NET Core generate metadata to each endpoint and OpenAPI generator use this metadata.
But **TypedResult** metadata aren't inferred from MVC controller (see #44988).

**Comment by jgarciadelanoceda** [comment]
I close it as dupe of #44988
