### ISSUE TITLE
What should I do to build aspnet offline?

### ISSUE THREAD

**Issue by YDV-AS** [dotnet/aspnetcore#56776]
Hi!

It is necessary to build aspnet 6.0.26-linux-x64 offline. I have problems. When I turn off the internet dotnet-servicing.tar.gz cannot be downloaded. I commented InstallDotNet func in dotnet-install.sh, but the next problem is npm installing. I get errors that there is no internet connection. The last error I get is that there is still no dotnet-servicing. How to build aspnet offline? 

![image](https://github.com/user-attachments/assets/ed4c843c-0f29-445b-b3b3-e71ba9334db6)
![image](https://github.com/user-attachments/assets/b360a892-8c90-467f-a0b8-57f55b81bc0c)
![image](https://github.com/user-attachments/assets/b26bcab6-d40a-4f13-864d-cb16e2c88ce7)

**Comment by amcasey** [comment]
How are you getting the source code onto this machine without internet access?  Can you run the restore script _before_ bundling up source and transferring it, so that the `.dotnet` and `node_modules` folders are copied as well?

**Comment by mkArtakMSFT** [comment]
Try to pass the `-NoBuildNodeJS` parameter to the build command.
