### ISSUE TITLE
Expose method for testing for a local URL consumable without depending on MVC

### ISSUE THREAD

**Issue by martincostello** [dotnet/aspnetcore#56770]
## Background and Motivation

I have an endpoint in an Minimal API application using Razor Slices so that native AoT could be supported whilst having a web UI that has an endpoint for handling rendering a sign in page similar to this:

```csharp
builder.MapGet("/sign-in", (HttpContext context) =>
{
    if (context.User.Identity?.IsAuthenticated == true)
    {
        string url = "/";

        if (context.Request.Query.TryGetValue("ReturnUrl", out var returnUrl))
        {
            url = returnUrl.ToString();
        }

        return Results.LocalRedirect(url);
    }

    return Results.Extensions.RazorSlice<Slices.SignIn>();
});
```

This protects against open redirects via `?ReturnUrl={value}` using `Results.LocalRedirect()`, but in the case that a non-local URL is provided, this causes an HTTP 500 due to these lines of code:

https://github.com/dotnet/aspnetcore/blob/90a622d4f3f377dcf4eabbbbb8765ba9d3e65415/src/Http/Http.Results/src/RedirectHttpResult.cs#L99-L102

`IUrlHelper.IsLocal()` isn't usable here because it's part of MVC which I don't have otherwise added to the application.

To get the desired behaviour of _"use `ReturnUrl` if local, otherwise just ignore it and go to the homepage"_ I'm left with a few options including:

1. Bring in MVC to use `IUrlHelper.IsLocalUrl()`;
2. Copy the implementation of [`SharedUrlHelper.IsLocalUrl()`](https://github.com/dotnet/aspnetcore/blob/90a622d4f3f377dcf4eabbbbb8765ba9d3e65415/src/Shared/ResultsHelpers/SharedUrlHelper.cs#L33);
3. Use reflection to invoke `SharedUrlHelper.IsLocalUrl()`.

This feels like a "missing piece" of functionality for general utility of lightweight Minimal APIs where MVC isn't a desired dependency of the application.

## Proposed API

```diff
namespace Microsoft.AspNetCore.Http;

+public static class UrlHelper
+{
+    public static bool IsLocalUrl(string? url) => SharedUrlHelper.IsLocalUrl(url);
+}
```

## Usage Examples

```csharp
builder.MapGet("/sign-in", (HttpContext context) =>
{
    if (context.User.Identity?.IsAuthenticated == true)
    {
        string url = "/";

        if (context.Request.Query.TryGetValue("ReturnUrl", out var returnUrl))
        {
            var maybeLocal = returnUrl.ToString();
            if (UrlHelper.IsLocalUrl(maybeLocal))
            {
                url = maybeLocal;
            }
        }

        return Results.LocalRedirect(url);
    }

    return Results.Extensions.RazorSlice<Slices.SignIn>();
});
```

## Alternative Designs

```diff
namespace Microsoft.AspNetCore.Http;

public sealed partial class RedirectHttpResult
{
+   public static bool IsLocalUrl(string? url) => SharedUrlHelper.IsLocalUrl(url);
}
```

Or, a new abstraction similar to [`IUrlHelper`]() that is uncoupled from MVC, but then there's lots more open questions about what other functionality should or shouldn't be in it.

## Risks

Duplication of class name with [`Microsoft.AspNetCore.Mvc.Routing.UrlHelper`](https://github.com/dotnet/aspnetcore/blob/90a622d4f3f377dcf4eabbbbb8765ba9d3e65415/src/Mvc/Mvc.Core/src/Routing/UrlHelper.cs#L13C14-L13C23).

**Comment by amcasey** [comment]
[API Review]

1. Do we want to expose this?
1. Where do we want to put it?
  1. `RedirectHttpResult`?
  1. A new static helper type?

- This would have been useful [here](https://github.com/dotnet/blazor-samples/blob/446d842239ab655add0d48e46a7abf7397b88804/8.0/BlazorWebAppOidc/BlazorWebAppOidc/LoginLogoutEndpointRouteBuilderExtensions.cs#L31-L32)
- Concern: "local url" isn't standard terminology and might be misunderstood
- MVC exposes it via DI, possibly so that it can be overridden
- The argument against reimplementation is that the user's version could end up being inconsistent with ours, causing problems
- We don't have a lot of precedent for a static utility class
    - Putting it on `RedirectHttpResult` might be a good compromise

```diff
namespace Microsoft.AspNetCore.Http;

public sealed partial class RedirectHttpResult
{
+   public static bool IsLocalUrl(string? url) => SharedUrlHelper.IsLocalUrl(url);
}
```

API approved!
