### ISSUE TITLE
`Enhance your security on the web` feature of microsoft edge, slow downs blazor webassembly as hell

### ISSUE THREAD

**Issue by ysmoradi** [dotnet/aspnetcore#56806]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

As you can see in the video, when I turn `Enhance your security on the web` [feature](https://support.microsoft.com/en-us/microsoft-edge/enhance-your-security-on-the-web-with-microsoft-edge-b8199f13-b21b-4a08-a806-daed31a1929d) `on` or `off`, it slow downs blazor webassembly websites such as [bitplatform.dev](https://bitplatform.dev) startup time from 1 seconds to more than 7 seconds on a powerful desktop PC!
It happens for our website which is really fast, for the rest of the blazor webassembly websites out there, the time increases to about 15 seconds!
During this period, CPU usage is high.

https://github.com/user-attachments/assets/4b3786ea-96d7-442e-9bf6-bb2448bc10aa

### Expected Behavior

Our website should get refreshed in 1 second on a powerful desktop PC

### Steps To Reproduce

Just enable/disable that feature and refresh any blazor webassembly powered website on the net on your device.

### .NET Version

N/A

### Anything else?

dotnet 8.0.303

**Comment by danroth27** [comment]
Hi @ysmoradi. Unfortunately, the Edge enhanced security feature isn't something we have any control over. Please share this feedback with the Edge folks using the Edge Send Feedback tool (Help and feedback > Send Feedback).
