### ISSUE TITLE
Update ASP.NET Core to use C# 8's nullable reference types

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#5680]
Updating ASP.NET Core to use C# 8's nullable reference types would:

1. Help ASP.NET Core libraries avoid null reference exceptions internally. It will help us find and prevent our bugs and increase our developer productivity
2. Provide guidance to developers who are using ASP.NET Core about which APIs can accept and return a null reference and which APIs can't. This would improve the developer experience of using ASP.NET Core

@rynowak @davidfowl @DamianEdwards @Eilon 

----------------------
## Projects in no particular order

* [x] Microsoft.AspNetCore.DataProtection.EntityFrameworkCore
* [x] Microsoft.AspNetCore.DataProtection.StackExchangeRedis
* [x] Microsoft.AspNetCore.TestHost
* [x] Microsoft.AspNetCore.Hosting.WindowsServices
* [ ] Microsoft.AspNetCore.ApiAuthorization.IdentityServer
* [x] Microsoft.AspNetCore.Identity.EntityFrameworkCore
* [ ] Microsoft.AspNetCore.Identity.Specification.Tests
* [x] Microsoft.AspNetCore.Identity.UI
* [x] Microsoft.AspNetCore.Authentication.Certificate
* [x] Microsoft.AspNetCore.Authentication.Facebook
* [x] Microsoft.AspNetCore.Authentication.Google
* [x] Microsoft.AspNetCore.Authentication.JwtBearer
* [x] Microsoft.AspNetCore.Authentication.MicrosoftAccount
* [x] Microsoft.AspNetCore.Authentication.Negotiate
* [x] Microsoft.AspNetCore.Authentication.OpenIdConnect
* [x] Microsoft.AspNetCore.Authentication.Twitter
* [x] Microsoft.AspNetCore.Authentication.WsFederation
* [ ] Microsoft.Extensions.Logging.AzureAppServices
* [x] Microsoft.AspNetCore.ConcurrencyLimiter
* [x] Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore
* [x] Microsoft.AspNetCore.HeaderPropagation
* [x] Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore
* [x] Microsoft.AspNetCore.MiddlewareAnalysis
* [x] Microsoft.AspNetCore.SpaServices.Extensions
* [x] Microsoft.AspNetCore.Mvc.NewtonsoftJson
* [x] Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation
* [x] Microsoft.AspNetCore.Mvc.Testing
* [x] Microsoft.AspNetCore.AzureAppServicesIntegration
* [x] Microsoft.AspNetCore.SignalR.Client.Core
* [x] Microsoft.AspNetCore.SignalR.Client
* [x] Microsoft.AspNetCore.Http.Connections.Client
* [x] Microsoft.AspNetCore.SignalR.Protocols.MessagePack
* [x] Microsoft.AspNetCore.SignalR.Protocols.NewtonsoftJson
* [ ] Microsoft.AspNetCore.SignalR.Specification.Tests
* [x] Microsoft.AspNetCore.SignalR.StackExchangeRedis
* [x] Microsoft.Authentication.WebAssembly.Msal
* [x] Microsoft.JSInterop.WebAssembly
* [x] Microsoft.AspNetCore.Components.WebAssembly.Server
* [x] Microsoft.AspNetCore.Components.WebAssembly.Authentication
* [x] Microsoft.AspNetCore.Components.WebAssembly
* [x] Microsoft.AspNetCore
* [x] Microsoft.AspNetCore.DataProtection.Abstractions
* [x] Microsoft.AspNetCore.Cryptography.Internal
* [x] Microsoft.AspNetCore.Cryptography.KeyDerivation
* [x] Microsoft.AspNetCore.DataProtection
* [x] Microsoft.AspNetCore.DataProtection.Extensions
* [x] Microsoft.AspNetCore.Antiforgery
* [x] Microsoft.AspNetCore.Hosting.Abstractions
* [x] Microsoft.AspNetCore.Hosting
* [x] Microsoft.AspNetCore.Hosting.Server.Abstractions
* [x] Microsoft.AspNetCore.Authentication.Abstractions
* [x] Microsoft.AspNetCore.Authentication.Core
* [x] Microsoft.Net.Http.Headers
* [x] Microsoft.AspNetCore.Http.Abstractions
* [x] Microsoft.AspNetCore.Http.Extensions
* [x] Microsoft.AspNetCore.Http.Features
* [x] Microsoft.AspNetCore.Http
* [x] Microsoft.AspNetCore.Metadata
* [x] Microsoft.AspNetCore.Routing.Abstractions
* [x] Microsoft.AspNetCore.Routing
* [x] Microsoft.AspNetCore.WebUtilities
* [x] Microsoft.AspNetCore.Html.Abstractions
* [x] Microsoft.AspNetCore.Identity
* [x] Microsoft.Extensions.Identity.Core
* [x] Microsoft.Extensions.Identity.Stores
* [x] Microsoft.AspNetCore.Connections.Abstractions
* [x] Microsoft.AspNetCore.Server.HttpSys
* [x] Microsoft.AspNetCore.Server.IISIntegration
* [x] Microsoft.AspNetCore.Server.IIS
* [x] Microsoft.AspNetCore.Server.Kestrel.Core
* [x] Microsoft.AspNetCore.Server.Kestrel
* [x] Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets
* [x] Microsoft.AspNetCore.Authentication.Cookies
* [x] Microsoft.AspNetCore.Authentication
* [x] Microsoft.AspNetCore.Authentication.OAuth
* [x] Microsoft.AspNetCore.Authorization
* [x] Microsoft.AspNetCore.Authorization.Policy
* [x] Microsoft.AspNetCore.CookiePolicy
* [x] Microsoft.AspNetCore.Cors
* [x] Microsoft.AspNetCore.Diagnostics.Abstractions
* [x] Microsoft.AspNetCore.Diagnostics
* [x] Microsoft.AspNetCore.Diagnostics.HealthChecks
* [x] Microsoft.AspNetCore.HostFiltering
* [x] Microsoft.AspNetCore.HttpOverrides
* [x] Microsoft.AspNetCore.HttpsPolicy
* [x] Microsoft.AspNetCore.Localization.Routing
* [x] Microsoft.AspNetCore.Localization
* [x] Microsoft.AspNetCore.ResponseCaching.Abstractions
* [x] Microsoft.AspNetCore.ResponseCaching
* [x] Microsoft.AspNetCore.ResponseCompression
* [x] Microsoft.AspNetCore.Rewrite
* [x] Microsoft.AspNetCore.Session
* [x] Microsoft.AspNetCore.StaticFiles
* [x] Microsoft.AspNetCore.WebSockets
* [x] Microsoft.AspNetCore.Razor.Runtime
* [x] Microsoft.AspNetCore.Razor
* [x] Microsoft.AspNetCore.Mvc.Abstractions
* [x] Microsoft.AspNetCore.Mvc.ApiExplorer
* [x] Microsoft.AspNetCore.Mvc.Core
* [x] Microsoft.AspNetCore.Mvc.Cors
* [x] Microsoft.AspNetCore.Mvc.DataAnnotations
* [x] Microsoft.AspNetCore.Mvc.Formatters.Json
* [x] Microsoft.AspNetCore.Mvc.Formatters.Xml
* [x] Microsoft.AspNetCore.Mvc.Localization
* [x] Microsoft.AspNetCore.Mvc.RazorPages
* [x] Microsoft.AspNetCore.Mvc.Razor
* [ ] Microsoft.AspNetCore.Mvc.TagHelpers
* [ ] Microsoft.AspNetCore.Mvc.ViewFeatures
* [x] Microsoft.AspNetCore.Mvc
* [x] Microsoft.AspNetCore.Http.Connections.Common
* [x] Microsoft.AspNetCore.Http.Connections
* [x] Microsoft.AspNetCore.SignalR.Protocols.Json
* [x] Microsoft.AspNetCore.SignalR.Common
* [x] Microsoft.AspNetCore.SignalR.Core
* [x] Microsoft.AspNetCore.SignalR
* [x] Microsoft.AspNetCore.Components.Authorization
* [x] Microsoft.AspNetCore.Components
* [x] Microsoft.AspNetCore.Components.Forms
* [x] Microsoft.AspNetCore.Components.Server
* [x] Microsoft.AspNetCore.Components.Web
* [x] Microsoft.Extensions.FileProviders.Embedded
* [x] Microsoft.Extensions.Caching.SqlServer
* [x] Microsoft.Extensions.Caching.StackExchangeRedis
* [x] Microsoft.Extensions.Configuration.KeyPerFile
* [x] Microsoft.Extensions.Localization.Abstractions
* [x] Microsoft.Extensions.Localization
* [x] Microsoft.Extensions.ObjectPool
* [x] Microsoft.JSInterop
* [x] Microsoft.Extensions.WebEncoders
* [x] Microsoft.Extensions.Diagnostics.HealthChecks.Abstractions
* [x] Microsoft.Extensions.Diagnostics.HealthChecks

## Skipped (potentially no longer commonly used, potential future removal, only used in tests, internal project, etc)

* [x] Microsoft.AspNetCore.Owin
* [x] Microsoft.AspNetCore.Testing
* [x] Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv
* [x] Microsoft.AspNetCore.Authentication.AzureAD.UI
* [x] Microsoft.AspNetCore.Authentication.AzureADB2C.UI
* [ ] Microsoft.AspNetCore.JsonPatch
* [ ] Microsoft.AspNetCore.NodeServices
* [ ] Microsoft.AspNetCore.SpaServices

## Skipped (not for public consumption)
* [x] Microsoft.AspNetCore.DeveloperCertificates.XPlat

**Comment by rynowak** [comment]
I hereby certify this idea as good.

**Comment by Eilon** [comment]
Assigning to @JamesNK to give this some more thought on what can concretely be done in ASP.NET Core and what value it would provide.

**Comment by JamesNK** [comment]
Over Christmas I'm going to play around with C# 8.0 and update Newtonsoft.Json to use nullable reference types. Will be able to give some more feedback then about how much work it will be. I suspect it will be large.

Some random thoughts:
1. It will probably require VS2019. VS2017 won't understand the syntax and will no longer compile
2. Lower level libraries should be updated first, e.g. Http should be updated before MVC so that MVC doesn't need to unnecessarily assert that types that come from Http are not null

**Comment by JamesNK** [comment]
If you had certified it spicy then you would have this label to use
> certified spicy 🌶️

🙃

**Comment by Eilon** [comment]
@JamesNK - maybe start with @joshfree to see if his team is planning to take advantage of this.

**Comment by JamesNK** [comment]
> This is concerning because we all really enjoy warnings as errors.

Totes, warning as errors is the best. But there is a way to *allow-list* (@Eilon 😋) some warnings. See `WarningsNotAsErrors` - https://github.com/dotnet/project-system/pull/4404/files#diff-6483fde6c45c90fdfe98ca72eadfa651

**Comment by JamesNK** [comment]
I discussed this with Mads and Immo. The corefx approach is to have a sidecar file format containing metadata. The file format should be usable by all packages.

Some reasons for this approach:
1. It can be applied to older versions of the framework, including .NET Framework, without having to update code
2. It is faster and easier to add nullable metadata to only the public API compared to updating all source code to use nullable reference types.

I don't think (1) is much of a concern for us. We'd be happy including nullable metadata from the latest version going forward.

(2) would be much faster for us. Disadvantage is we'd miss out on catching nulls in our own code, and there would be ongoing upkeep of the sidecar file. When a new API is added then the nullable metadata would also need to be added to the file.

**Comment by mkArtakMSFT** [comment]
Moving this to backlog as we have no capacity to handle this in 3.0 release.

**Comment by magnusbakken** [comment]
Now that C#8 and VS16.3, etc. have been officially released, will you start looking into this again?

**Comment by fubar-coder** [comment]
Any plans for this feature? I currently have to work around this issue when I implement my own `IConnectionUserFeature` (and others).

**Comment by magnusbakken** [comment]
The main place this becomes an annoyance is when you're working in a project with Nullable=true and implementing an ASP.NET Core interface/abstract class with methods that ought to have question marks in them, but of course don't.

I think the only place I've actually run into myself is in `IUserStore<T>`. The methods `FindByIdAsync` and `FindByNameAsync` need to be able to return null if the user isn't found, but since the interface returns `Task<T>` the compiler won't allow it without a type assertion. In my implementation I basically just do `if (user == null) return null!`; The construct `null!` is pretty bizarre, but at least it's obvious when you look at it that it's a temporary workaround.

When you're calling an ASP.NET Core method that ought to return `Foo?` but actually returns `Foo` you just have to remember to check if it's null anyway, but with interfaces it's a little worse.

**Comment by fubar-coder** [comment]
My workaround is to temporarily disable NRT and restore it again, like this:

```csharp
class YourImpl : IConnectionUserFeature {
#nullable disable
    public ClaimsPrincipal User { get; set; }
#nullable restore
}
```

It works, but the need to disable NRT checks is not what I expected.

**Comment by JamesNK** [comment]
Bad bot

**Comment by JunTaoLuo** [comment]
FYI Caching.Redis and Caching.SqlServer blocked on https://github.com/dotnet/runtime/issues/52148

Specifically for Caching.Redis, we'll need something like a revert of https://github.com/dotnet/aspnetcore/pull/32266/commits/5d43330657783458450ca638c57842a72857c2b3.

**Comment by mkArtakMSFT** [comment]
Moving to area-identity as that's where next set of changes need to happen

**Comment by JamesNK** [comment]
I split the remaining projects that are missing nullability into separate issues. Closing this issue.
