### ISSUE TITLE
Uncaught Error: No interop methods are registered for renderer 1

### ISSUE THREAD

**Issue by zuizuihao** [dotnet/aspnetcore#56813]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Recently we upgraded our Blazor Server App from .NET 7 to .NET 8, before that, we never encounter below issues. after investigate the source code, maybe related with below code. one thing to mention, we still use the blazor.server.js, will [Convert a Blazor Server app into a Blazor Web App](https://learn.microsoft.com/en-us/aspnet/core/migration/70-80?view=aspnetcore-7.0&tabs=visual-studio#convert-a-blazor-server-app-into-a-blazor-web-app) solve our issue? it's on the progress.
[dispatchEvent](https://github.com/dotnet/aspnetcore/blob/6a2ad656a8d670500643209b8ba4ad984b95cb7f/src/Components/Web.JS/src/Rendering/WebRendererInteropMethods.ts#L66)
[getInteropMethods](https://github.com/dotnet/aspnetcore/blob/6a2ad656a8d670500643209b8ba4ad984b95cb7f/src/Components/Web.JS/src/Rendering/WebRendererInteropMethods.ts#L78)

Uncaught Error: No interop methods are registered for renderer 1
at T (_framework/blazor.server.js:1:13936)
at <anonymous> (_framework/blazor.server.js:1:13842)
at D (_framework/blazor.server.js:1:14025)
at k (_framework/blazor.server.js:1:13816)
at dispatchGlobalEventToAllElements (_framework/blazor.server.js:1:16418)
at onGlobalEvent (_framework/blazor.server.js:1:15611)

### .NET Version

8.0.100

### Anything else?

<PackageVersion Include="Microsoft.AspNetCore.Components" Version="8.0.0" />
<PackageVersion Include="Microsoft.AspNetCore.Components.Web" Version="8.0.00" />
<PackageVersion Include="Microsoft.AspNetCore.SignalR.Client" Version="7.0.20" />

**Comment by javiercn** [comment]
@zuizuihao thanks for contacting us.

You can't use `MapRazorComponents with `blazor.server.js` they aren't compatible. You need to use `blazor.web.js`

**Comment by zuizuihao** [comment]
> @zuizuihao thanks for contacting us.
> 
> You can't use `MapRazorComponents with `blazor.server.js`they aren't compatible. You need to use`blazor.web.js`

Thanks for this clue, now we are using MapRazorPages like below, not sure if it's also not compatible with blazor.server.js.

```
services.AddServerSideBlazor().AddCircuitOptions(o =>
{
  if (HostEnvironment.IsDevelopmentOrIntegrationTest())
  {
    o.DetailedErrors = true;
  }
}).AddHubOptions(o => o.DisableImplicitFromServicesParameters = true);

endpoints.MapBlazorHub(
  // Long-polling produces such a bad user experience that we can't support it
  configureOptions: options => { options.Transports = HttpTransportType.WebSockets; }
);
endpoints.MapRazorPages();
```

**Comment by zuizuihao** [comment]
this issue still exists even after applying blazor.web.js.

```
Uncaught Error: No interop methods are registered for renderer 1
at A (_framework/blazor.web.js?version=8:1:13826)
at <anonymous> (_framework/blazor.web.js?version=8:1:13732)
at D (_framework/blazor.web.js?version=8:1:13915)
at R (_framework/blazor.web.js?version=8:1:13706)
at dispatchGlobalEventToAllElements (_framework/blazor.web.js?version=8:1:16308)
at onGlobalEvent (_framework/blazor.web.js?version=8:1:15501)
```

**Comment by danielheddelin** [comment]
I have the exact same issue after having upgraded my Blazor server app from .Net7 to .Net8. Any kind of feedback would be appreciated.
These are my Razor related lines in Program.cs (and I can't recall seeing any advice on removing/reworking these in the upgrade docs):
`builder.Services.AddRazorPages();`
`app.MapRazorPages();`

**Comment by Alino** [comment]
Same here, I didn't even migrate from 7 to 8. But I am using 8 from the start of the project.
This issue should be reopened.

**Comment by Alino** [comment]
I figured it out what was causing this for me. Because I had constant issues with dropping connections and websockets errors complaining. I followed some docs to do this:

```
    <script src="_framework/blazor.web.js" autostart="false"></script>
    <script>
        Blazor.start({
            circuit: {
                configureSignalR: function (builder) {
                    builder.withServerTimeout(30000).withKeepAliveInterval(15000);
                },
                reconnectionHandler: {
                    onConnectionDown: (options, error) => console.error(error),
                    onConnectionUp: () => console.log("Up, up, and away!")
                }
            }
        });
    </script>
```

I have completely removed this and reverted back to use (no autostart)
`   <script src="_framework/blazor.web.js"></script>`

**Comment by tomvandyckVdP** [comment]
Experiencing the same issue here ... no clue on how to tackle this :-|
Anyone. @Alino 's suggestion does not fix it for me.
I (think I) understand the problem ('something is trying to render, but there is no-one to render it'), I just can't figure out where this render-request is coming from ... I assume it is related to a non-ui thread triggering a render action or something.
Any ideas or suggestions are more than welcome.

**Comment by jlchavez** [comment]
> @zuizuihao thanks for contacting us.
> 
> You can't use `MapRazorComponents with `blazor.server.js`they aren't compatible. You need to use`blazor.web.js`

Nope, 

`<script src="/_framework/blazor.web.js"></script>`

Has the same problem. Using Microsoft.AspNetCore.Components.WebAssembly.Server 8.0.7, so the problem comes from somewhere else.

**Comment by zuizuihao** [comment]
I found the ROOT CAUSE, @javiercn can we clean up the global event listener, when connection closed?
when Blazor connection closed, the [detachWebRendererInterop](https://github.com/dotnet/aspnetcore/blob/7e21f2e65a5dfaed143015cfbcf0139ce3cce8da/src/Components/Web.JS/src/Platform/Circuits/CircuitManager.ts#L160C45-L160C69) in the callback of connection.onclose will be invoked. here, it will invoke [interopMethodsByRenderer.delete(rendererId);](https://github.com/dotnet/aspnetcore/blob/7e21f2e65a5dfaed143015cfbcf0139ce3cce8da/src/Components/Web.JS/src/Rendering/WebRendererInteropMethods.ts#L48C1-L49C1), all the interopMethodsByRenderer will be cleaned. also There are lots of global event listener in [form.js](https://devops.wisetechglobal.com/wtg/CargoWise/_git/Dev?path=%2FWinzor%2FBArchitecture.GUI%2Fwwwroot%2Fjs%2Fmodule%2Fform.js&version=GBmaster&line=55&lineEnd=55&lineStartColumn=2&lineEndColumn=12&lineStyle=plain&_a=contents) like window.addEventListener('focus'), window.addEventListener('keydown'). if user still interact with our app like focus, click, the global event will be triggered, then invoked [EventDelegator.onGlobalEvent](https://github.com/dotnet/aspnetcore/blob/7e21f2e65a5dfaed143015cfbcf0139ce3cce8da/src/Components/Web.JS/src/Rendering/Events/EventDelegator.ts#L134), invoked [EventDelegator.dispatchGlobalEventToAllElements](https://github.com/dotnet/aspnetcore/blob/7e21f2e65a5dfaed143015cfbcf0139ce3cce8da/src/Components/Web.JS/src/Rendering/Events/EventDelegator.ts#L153) invoked [WebRendererInteropMethods.dispatchEvent](https://github.com/dotnet/aspnetcore/blob/7e21f2e65a5dfaed143015cfbcf0139ce3cce8da/src/Components/Web.JS/src/Rendering/WebRendererInteropMethods.ts#L66C17-L66C30) invoked [WebRendererInteropMethods.getInteropMethods](https://github.com/dotnet/aspnetcore/blob/7e21f2e65a5dfaed143015cfbcf0139ce3cce8da/src/Components/Web.JS/src/Rendering/WebRendererInteropMethods.ts#L78C10-L78C27), here since the interopMethodsByRenderer is empty, will throw this exception.

**Comment by DataJuggler** [comment]
I am getting this issue in .NET 9 today. Not sure what I changed that caused this because it worked Friday.

**Comment by simeyla** [comment]
It's possible to get this error if you throw an exception in `SetParametersAsync` (such as trying to do something with a parameter member property that isn't yet initialized).

It's easy to accidentally 'stub out' `SetParametersAsync` because it's a public override. The mostly-more-useful `OnParametersSetAsync` is protected so the compiler won't suggest it if you just type `public override...`. The same exception in `OnParametersSetAsync` will get propagated to the UI error console.

        [Parameter] public int OrderId {get; set;}

        public override Task SetParametersAsync(ParameterView parameters)
        {
            async LoadOrder(OrderId);    // ❌ OrderId isn't actually set yet
            return base.SetParametersAsync(parameters);
        }

        protected override async Task OnParametersSetAsync()
        {
            async LoadOrder(OrderId);  // ✅ OrderId is set
            await base.OnParametersSetAsync();
        }
