### ISSUE TITLE
`IEmailSender` does not exist in Microsoft.AspNetCore.Identity.UI when targeting .NET 7

### ISSUE THREAD

**Issue by kikaragyozov** [dotnet/aspnetcore#56823]
When using the latest version of Microsoft.AspNetCore.Identity.UI, which currently stands to be v8.0.7, if you're targeting .NET 7, the type `IEmailSender` is missing.

Interestingly enough, if you downgrade to version 7 (7.X.X), the type becomes visible to you when running under .NET 7.

If you're targeting .NET 8, the type is visible in 8.X.X.

I don't think this is in any way the expected behavior.

I'd expect when you install the latest version to the library, `IEmailSender` to be there, regardless if you're running .NET 7, or .NET 8, as stated in the [documentation](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.identity.ui.services.iemailsender?view=aspnetcore-8.0#applies-to) for the type.

**Comment by javiercn** [comment]
@kikaragyozov thanks for contacting us.

.NET 7.0 is out of support, we recommend you upgrade to .NET 8.0. As per our support policy we don't look into issues for unsupported releases.

**Comment by kikaragyozov** [comment]
@javiercn The issue exists for both .NET 6 and .NET 5 and probably any other version out there. Could you please re-open the issue and have this investigated? Or should I make a new one?
