### ISSUE TITLE
IMemoryCache duplicating records(from enum key) in blazor wasm

### ISSUE THREAD

**Issue by thepra** [dotnet/aspnetcore#56826]
### Description

I have a 2 layer data handling on the browser client, the usual IndexedDb and IMemoryCache, the IMemoryCache is used first and the most, here the issue happen between the navigation of 2 pages that call the same type of data from the memory cache.
Upon and the first `.Get<>(key)` it gives back 1 record as it should and then another one from another key(total 2 records that are compined into the same list in that page), then I navigate to the other page and now the first Get gives back 3 records instead of 1 that shouldn't even be in that collection(the underlying list of class type is the same and the data is from the second key with 2 copies of the same record) and now I have 4 records, then I go back and forth and records continue to duplicate  each time.

### Reproduction Steps

2 pages
```
[Inject] IMemoryCache cache {get;set;}

List<ViewUser> users = [];
protected override async Task OnInitializedAsync()
{
  var users = cache.Get<List<ViewUser>>(DbStoresEnum.Admins);
  users.AddRange(cache.Get<List<ViewUser>>(DbStoresEnum.Teachers));
}
```

### Expected behavior

don't have duplicated entries.

### Actual behavior

Data is duplicated each time I go back and forth.

### Regression?

Indeed, or I must be using that kind of cache wrongly.

### Known Workarounds

Use indexeddb instead of the cache

### Configuration

- .NET 8.0
- Windows 10 Pro
- x64
- No
- Edge

**Comment by adamsitnik** [comment]
My impression is that `MemoryCache` works as expected and this is more of a general question about `OnInitializedAsync` and component lifecycle, that is  why I've transferred this issue to ASP.NET.
