### ISSUE TITLE
.NET 8 Blazor "No authenticationScheme was specified, and there was no DefaultChallengeScheme found" on Authorize Attribute after updating from .NET6

### ISSUE THREAD

**Issue by SaschaWillems** [dotnet/aspnetcore#56820]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We are in the process of upgrading a production application using Blazor (formerly Server) from .NET6 to .NET8. Some pages us the `Authorize` attribute:

```c#
@page "/somepage"
@attribute [Authorize(Roles = "Admin")]
```

We use a custom authentication state provider derived from `AuthenticationStateProvider`.

After upgrading the app to .NET8 the first page load works fine, but refreshing the page yields the following error:

```InvalidOperationException: No authenticationScheme was specified, and there was no DefaultChallengeScheme found. The default schemes can be set using either AddAuthentication(string defaultScheme) or AddAuthentication(Action<AuthenticationOptions> configureOptions).```

The app does not use a default challenge scheme (or tokens) at all.

### Expected Behavior

Refreshing Razor pages using the `Authorize` attribute properly displays the page instead of displaying aforementioned error message.

### .NET Version

8.0.303

**Comment by SaschaWillems** [comment]
Since this is a larger proprietary application, I won't be able to share a simple repo case.

**Comment by Hweidii** [comment]
Hi, I have the same issue, what is the solution?

**Comment by Xilmirius** [comment]
Hi, same here, whats the solutions ?
