### ISSUE TITLE
Blazor hybrid navigation failed

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#56838]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Blazor-hybrid-navigation-failed/10694261)._

---
Hi
The context is :
- solution composed of a Blazor server project and a web assembly client project (based on the vs default template)
- Blazor server has some pages (for example /fooOnServer url)
- web assembly client has also some pages (for example /fooOnClient url)

If I run that,
Navigation on the web assembly client pages works well !
But…
For the server /fooOnServer page, it depends on the @rendermode defined in <headOutlet /> and <routes /> in the server app.razor file.
If not defined : navigation works, 
If value is defined (whatever rendermode is ) behaviour sequence become  
1. Open the view /fooOnServer 
2. After 1 sec (more or less) , fallback to the router notfound template (even if not defined in routes.razor)

Is it the expected behaviour ? Which is strange…
What is the default rendermode if nothing is defined.

Thanks for that 

Regards 

Ps: my vs is 17.10.3 and I run Blazor on dotnet 8.

---
#### Feedback Bot on 7/1/2024, 10:15 PM: 

(private comment, text removed)

**Comment by javiercn** [comment]
Thanks for contacting us.

As a starting point, make sure that all the routes, server and client are registered both on the Blazor router as well as the asp.net core router via `AddAdditionalAssemblies`

If your problem persists, please include a repro project as a public github repository so that we can help.

**Comment by benjamin-devuyst** [comment]
> Thanks for contacting us.
> 
> 
> 
> As a starting point, make sure that all the routes, server and client are registered both on the Blazor router as well as the asp.net core router via `AddAdditionalAssemblies`
> 
> 
> 
> If your problem persists, please include a repro project as a public github repository so that we can help.

Hi 

Thanks for your answer,
as I remember , we already use addAdditionnalAssemblies

I can push you a solution. 

On the other hand, the bug occurs with the default VS template (webassembly with server created, and Check of adding sample pages), wich you add in the server app a blazor component within @page directive

And of course, debug it from the server app.

If needed gonna try to bring you a sample on next week (I do not take computer on holliday)

Regards

Benjamin
