### ISSUE TITLE
Cannot use AddJwtBearer with alternate scheme name

### ISSUE THREAD

**Issue by Coder3333** [dotnet/aspnetcore#56834]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If I use AddJwtBearer with any scheme other than "Bearer", the handler fails to authenticate.  The logic in JwtBearerHandler hard codes "Bearer ", instead of relying on the provided scheme name, therefore, it does not properly parse the token.

```c#
builder.Services.AddAuthentication();
			 .AddJwtBearer("AlternateScheme", options =>
			 {
				 options.Authority = "Authority";
				 options.Audience = "Audience";
			 });

```

### Expected Behavior

The JwtBearer logic should use the provided Scheme name to parse the token from the Authentication header, instead of hard coded "Bearer ".  I am able to create the desired provider using the OnMessageReceived handler, but this should be the standard behavior.

```c#
                             options.Events.OnMessageReceived = async context => {
                                 if (string.Equals(context.Scheme.Name, AuthenticationScheme, StringComparison.OrdinalIgnoreCase))
                                 {
                                     // only perform if it is the configured scheme

                                     var authorization = context?.Request.Headers?["Authorization"] ?? new Microsoft.Extensions.Primitives.StringValues();
                                     var testString = $"{AuthenticationScheme} ";
                                     var matchingAuthorization = authorization.FirstOrDefault(a => a.StartsWith(testString, StringComparison.OrdinalIgnoreCase));
                                     if (!string.IsNullOrWhiteSpace(matchingAuthorization))
                                     {
                                         context.Token = matchingAuthorization.Substring(testString.Length).Trim();
                                     }

                                 }
                             };


```

### Steps To Reproduce

Call AddJwtBearer with any scheme name other than "Bearer", and then provide an Authentication token using the alternate scheme.

```c#
builder.Services.AddAuthentication();
			 .AddJwtBearer("AlternateScheme", options =>
			 {
				 options.Authority = "Authority";
				 options.Audience = "Audience";
			 });

```

```c#
message.Headers.Authorization = new AuthenticationHeaderValue("AlternateScheme", "access token");

```

### Exceptions (if any)

The handler will fail to authenticate the user with the token, because it will not know to parse it with the custom scheme name.

### .NET Version

all

**Comment by martincostello** [comment]
Raised again by #57174.

**Comment by yowl** [comment]
There should be something about this here https://learn.microsoft.com/en-us/aspnet/core/security/authorization/limitingidentitybyscheme?view=aspnetcore-9.0#use-multiple-authentication-schemes IMHO.

Why accept a scheme, have a `Scheme` property, and then hard code "Bearer", it is not intuitive.
