### ISSUE TITLE
VS-CODE HTTP launch configuration trusted certificate required

### ISSUE THREAD

**Issue by omatrot** [dotnet/aspnetcore#56853]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm having trouble debugging an ASP.NET 8 MVC project on a MacBook because of the development certificate.

I have the following message over and over again at every launch

`The selected launch configuration is configured to launch a web browser but no trusted development certificate was found. Create a trusted self-signed certificate?
`
 
Despite the fact that there is a trusted certificate that is configured.

![Screenshot 2024-07-17 at 17 07 59](https://github.com/user-attachments/assets/cff8884b-003a-4e51-888f-b14b29a48343)

Furthermore, the selected configuration is not HTTPS because it just does not work. It is HTTP.

I have tried cleaning and reinstalling the certificate but the problem persists.

For reference, below are my launch settings files:

launch.json

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Janus 7 lieues",
            "type": "coreclr",
            "request": "launch",
            "program": "${workspaceFolder}/SCTM.Web/bin/Debug/net8.0/SCTM.Web.dll",
            "cwd": "${workspaceFolder}/SCTM.Web",
            "launchSettingsFilePath": "${workspaceFolder}/SCTM.Web/Properties/launchSettings.json",
            "launchSettingsProfile": "SCTM.Web",
            "serverReadyAction": {
                "action": "openExternally",
                "pattern": "\\bNow listening on:\\s+http?://\\S",
                "uriFormat": "http://7lieues.talentmanager.com:5001"
            }
        }
    ]
}
```

launchsettings.json

```
{
  "profiles": {
    "SCTM.Web": {
      "commandName": "Project",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      },
      "applicationUrl": "http://7lieues.talentmanager.com:5001"
    }
  }
}
```

### Expected Behavior

I expect the ability to debug over an https connection.

### Steps To Reproduce

N/A

### .NET Version

8.0.201

### Anything else?

.NET SDK:
 Version:           8.0.201
 Commit:            4c2d78f037
 Workload version:  8.0.200-manifests.3097af8b

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  14.5
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/8.0.201/

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.2
  Architecture: arm64
  Commit:       1381d5ebd2

.NET SDKs installed:
  6.0.202 [/usr/local/share/dotnet/sdk]
  6.0.203 [/usr/local/share/dotnet/sdk]
  6.0.300 [/usr/local/share/dotnet/sdk]
  6.0.401 [/usr/local/share/dotnet/sdk]
  6.0.402 [/usr/local/share/dotnet/sdk]
  6.0.403 [/usr/local/share/dotnet/sdk]
  6.0.404 [/usr/local/share/dotnet/sdk]
  6.0.405 [/usr/local/share/dotnet/sdk]
  6.0.406 [/usr/local/share/dotnet/sdk]
  6.0.407 [/usr/local/share/dotnet/sdk]
  6.0.408 [/usr/local/share/dotnet/sdk]
  6.0.410 [/usr/local/share/dotnet/sdk]
  7.0.100 [/usr/local/share/dotnet/sdk]
  7.0.101 [/usr/local/share/dotnet/sdk]
  7.0.200 [/usr/local/share/dotnet/sdk]
  7.0.202 [/usr/local/share/dotnet/sdk]
  7.0.203 [/usr/local/share/dotnet/sdk]
  7.0.302 [/usr/local/share/dotnet/sdk]
  7.0.304 [/usr/local/share/dotnet/sdk]
  8.0.201 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.10 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.11 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.12 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.13 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.14 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.15 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.16 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.18 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.9 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.10 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.11 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.12 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.13 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.14 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.15 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.16 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.18 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  x64   [/usr/local/share/dotnet/x64]
    registered at [/etc/dotnet/install_location_x64]

Environment variables:
  Not set

global.json file:
  Not found

**Comment by amcasey** [comment]
What do you see when you run `dotnet dev-certs https --trust --check --verbose`?

**Comment by amcasey** [comment]
Is there a copy of your cert in `~/.aspnet/dev-certs/https`?

**Comment by omatrot** [comment]
This is the output of the command:

```
[1] Listing certificates from CurrentUser\My
[70] The file '/Users/oliviermatrot/.aspnet/dev-certs/https/aspnetcore-localhost-E83F2361E21707218F4D84A776C49D114EB27E76.pfx' is not a valid certificate.
[7] An error occurred while listing the certificates: System.UnauthorizedAccessException: Access to the path '/Users/oliviermatrot/.aspnet/dev-certs/https/aspnetcore-localhost-E83F2361E21707218F4D84A776C49D114EB27E76.pfx' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.ReadAllBytes(String path)
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
   at Microsoft.AspNetCore.Certificates.Generation.MacOSCertificateManager.GetCertsFromDisk()
   at Microsoft.AspNetCore.Certificates.Generation.MacOSCertificateManager.PopulateCertificatesFromStore(X509Store store, List`1 certificates, Boolean requireExportable)
   at Microsoft.AspNetCore.Certificates.Generation.CertificateManager.ListCertificates(StoreName storeName, StoreLocation location, Boolean isValid, Boolean requireExportable)
No valid certificate found.
```

**Comment by omatrot** [comment]
In the folder there is this file:
aspnetcore-localhost-E83F2361E21707218F4D84A776C49D114EB27E76.pfx

**Comment by amcasey** [comment]
Sounds like the files are in the right place but something is off with the permissions.  I don't believe macOS locks files while other processes are using them, so it's probably file system restrictions.  Can you confirm the obvious things?  The user running dotnet (you?) has read and execute permissions to the containing folders and read access to the file?

I can't, off the top of my head, recall whether macOS has something like [handle](https://learn.microsoft.com/en-us/sysinternals/downloads/handle) or `lsof`, but checking for other processes accessing that file wouldn't hurt.

**Comment by omatrot** [comment]
Humm, permission issue for my own files ?

**Comment by omatrot** [comment]
More info on the file says :
You have no access ;)
System : Read & Write
Everyone : No Access

**Comment by amcasey** [comment]
The quick fix would be to give yourself access.  If you want to investigate further, the next thing I'd try is deleting it (manually, not with --clean) and then generating a new one to see if it has the same problem.

**Comment by amcasey** [comment]
It kind of sounds like you're not the owner of the file, which suggests that you don't own the containing folders.  Were you running as sudo when you generating the cert?

**Comment by omatrot** [comment]
Yes, I'm the only user of the MacBook, so I suspect this is a bug.

I gave me read permission and ran the command again. This time it says:

```
[1] Listing certificates from CurrentUser\My
[2] Found certificates: 1 certificate
    1) 0F21BB212F3ACBDD932D8E9FC908DD8AAF7998DA - CN=localhost - Valid from 2024-07-17 16:48:26Z to 2025-07-17 16:48:26Z - IsHttpsDevelopmentCertificate: true - IsExportable: true
[3] Checking certificates validity
[4] Valid certificates: 1 certificate
    1) 0F21BB212F3ACBDD932D8E9FC908DD8AAF7998DA - CN=localhost - Valid from 2024-07-17 16:48:26Z to 2025-07-17 16:48:26Z - IsHttpsDevelopmentCertificate: true - IsExportable: true
[5] Invalid certificates: no certificates
[6] Finished listing certificates.
The ASP.NET Core developer certificate is in an invalid state. To fix this issue, run 'dotnet dev-certs https --clean' and 'dotnet dev-certs https' to remove all existing ASP.NET Core development certificates and create a new untrusted developer certificate. On macOS or Windows, use 'dotnet dev-certs https --trust' to trust the new certificate.
```

Better but not enough. So I ran the suggested command `dotnet dev-certs https --trust`

It says the trust was successful but I checked again, and it still states that the certificate is in an invalid state.

**Comment by omatrot** [comment]
But, running my ASP.NET web site now does not trigger the need to trust a certificate...

**Comment by amcasey** [comment]
AFAICT, that message is only printed when the file doesn't exist, which we've established it does: https://github.com/dotnet/aspnetcore/blob/105a25ff220b6cf3cf23152f9691a59ac8aaa7ed/src/Shared/CertificateGeneration/MacOSCertificateManager.cs#L125

It's not impossible it prints that warning and then corrects things itself.  Buggy but not fatal.

Did you have a chance to check which user owned the certificate before you made your changes?

**Comment by omatrot** [comment]
I would say this is system, because it has read & write permissions

**Comment by amcasey** [comment]
I tried on a lab machine and when I ran `sudo dotnet dev-certs https --trust`, the file ended up owned by root, rather than my user.  I'm not aware of another way that could happen, at least on a single-user machine.

Sounds like you're unblocked?

**Comment by omatrot** [comment]
Yes it is ok now. Thanks to you and the verbose option :)

**Comment by omatrot** [comment]
I have switched back to HTTPS for my launch configuration and there is still an issue:

```
{System.InvalidOperationException: Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found or is out of date.
To generate a developer certificate run 'dotnet dev-certs https'. To trust the certificate (Windows and macOS only) run 'dotnet dev-certs https --trust'.
For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
   at Microsoft.AspNetCore.Server.Kestrel.Core.TlsConfigurationLoader.UseHttpsWithSni(ListenOptions listenOptions, HttpsConnectionAdapterOptions httpsOptions, EndpointConfig endpoint)
   at Microsoft.AspNetCore.Server.Kestrel.KestrelConfigurationLoader.Reload()
   at Microsoft.AspNetCore.Server.Kestrel.KestrelConfigurationLoader.LoadInternal()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
   at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Program.<Main>$(String[] args) in /Users/oliviermatrot/Documents/SoftConvergence/Janus/SoftConvergence.TalentManger.Web/Program.cs:line 155}

```

I have removed the certificate and have created a new one per the instruction found above and launch a new check:

```
% dotnet dev-certs https --trust --check --verbose
[1] Listing certificates from CurrentUser\My
[2] Found certificates: 1 certificate
    1) 0189345FA755EED9D2CC930E9C7DCD30B4304429 - CN=localhost - Valid from 2024-08-08 08:06:34Z to 2025-08-08 08:06:34Z - IsHttpsDevelopmentCertificate: true - IsExportable: true
[3] Checking certificates validity
[4] Valid certificates: 1 certificate
    1) 0189345FA755EED9D2CC930E9C7DCD30B4304429 - CN=localhost - Valid from 2024-08-08 08:06:34Z to 2025-08-08 08:06:34Z - IsHttpsDevelopmentCertificate: true - IsExportable: true
[5] Invalid certificates: no certificates
[6] Finished listing certificates.
The ASP.NET Core developer certificate is in an invalid state. To fix this issue, run 'dotnet dev-certs https --clean' and 'dotnet dev-certs https' to remove all existing ASP.NET Core development certificates and create a new untrusted developer certificate. On macOS or Windows, use 'dotnet dev-certs https --trust' to trust the new certificate.
```

I don't understand why at first, there is no Invalid Certificate at step [5] and then it is invalid at the end...

**Comment by amcasey** [comment]
Sorry, the text is confusing: the first "invalid" is about date ranges and the second is about the absence of (or permission issue with) `~/.aspnet/dev-certs/https`.  If that file isn't readable by kestrel, you'll see the `InvalidOperationException` above.

**Comment by omatrot** [comment]
This time, I have no file in `~/.aspnet/dev-certs/https`. What can I do to make it appear ?
Again this is an M1 machine. Never had this issue on mon intel based iMac.

**Comment by amcasey** [comment]
I would be pretty surprised to learn the behavior varied based on the hardware architecture, but we _are_ using system tools to manage certificates, so it's not impossible.

Did you also pass `--verbose` when you originally generated the certificate?  It should have printed an error.  Based on our previous discussion, my guess would be that it didn't have access to the containing folder and couldn't copy the certificate there.

To start fresh, you can `--clean` and then `--trust`.  I suggest passing `--verbose` for both.
