### ISSUE TITLE
[Blazor MAUI] Byte Array Interop Still Serializes `byte[]` as string?

### ISSUE THREAD

**Issue by Khongchai** [dotnet/aspnetcore#56850]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi, .NET team

[Here](https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet?view=aspnetcore-8.0#byte-array-support), the docs says

> Blazor supports optimized byte array JavaScript (JS) interop that **avoids** encoding/decoding byte arrays into Base64

But when I did the same thing I found that my byte[] is still serialized as string.

<img width="605" alt="image" src="https://github.com/user-attachments/assets/9291b206-8b6b-4ad5-9188-8dc57793f9b6">

The string is then forwarded to a minified string deserialization method, corresponds to [this line of code](https://github.com/dotnet/aspnetcore/blob/6548eba17fb3e8cee3815b69609ff16f0f08c4f9/src/Components/Web.JS/src/Platform/WebView/WebViewIpcReceiver.ts#L67)

<img width="191" alt="image" src="https://github.com/user-attachments/assets/165c1ef3-658d-435d-8b59-1f1abea54e9b">

### Expected Behavior

If I understand the docs correctly, the data should not be serialized as a string. 

The `SendByteArrayToJS` still serializes its message as a string https://github.com/dotnet/aspnetcore/blob/6548eba17fb3e8cee3815b69609ff16f0f08c4f9/src/Components/WebView/WebView/src/IpcSender.cs#L64

### Steps To Reproduce

C#
```cs
await jsRuntime.InvokeVoidAsync("receiveBytes", bytes);
```
JS
```js
export function receiveBytes(bytes) {
  // do something
}
```

Then put a debugger or log the value here

https://github.com/dotnet/aspnetcore/blob/6548eba17fb3e8cee3815b69609ff16f0f08c4f9/src/Components/Web.JS/src/Platform/WebView/WebViewIpcReceiver.ts#L55

### .NET Version

8.0.22

**Comment by javiercn** [comment]
@Khongchai thanks for contacting us.

Yes, this is the case, as the interop channels between webviews and native apps only allow passing strings between each other as a common denominator, meaning there's no common way for us to pass byte buffers around that is supported on all the target webviews.

**Comment by Khongchai** [comment]
@javiercn I see. Thanks for the answer! I'll close this issue
