### ISSUE TITLE
An unhandled exception of type 'System.ArgumentException' occurred in Microsoft.Extensions.FileProviders.Physical.dll: 'The path must be absolute.'

### ISSUE THREAD

**Issue by mscheinholtz** [dotnet/aspnetcore#56883]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There seems to be an issue between debugging a solution using Docker in VS 2022 (17.10.4) and Docker Desktop 4.32.0. When I toggle from Debug to Release it works but it fails with this error An unhandled exception of type 'System.ArgumentException' occurred in Microsoft.Extensions.FileProviders.Physical.dll: 'The path must be absolute.' I tried reverting to dotnet6 but that does not fix it

### Expected Behavior

When running the solution in debug mode for docker i expect it to startup the same as release

### Steps To Reproduce

There seems to be an issue between debugging a solution using Docker in VS 2022 (17.10.4) and Docker Desktop 4.32.0. When I toggle from Debug to Release it works but it fails with this error

### Exceptions (if any)

An unhandled exception of type 'System.ArgumentException' occurred in Microsoft.Extensions.FileProviders.Physical.dll: 'The path must be absolute.'

### .NET Version

8.0.7

### Anything else?

Docker Desktop 4.32.0

**Comment by BrennanConroy** [comment]
Is AspNetCore related to the problem in some way? Otherwise, I'll move the issue to dotnet/runtime.

**Comment by mscheinholtz** [comment]
No longer need this
