### ISSUE TITLE
[6.0] Bad template configuration

### ISSUE THREAD

**Issue by smitpatel** [dotnet/aspnetcore#56904]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

For Blazore WebAssembly App project template in 6.0
https://github.com/dotnet/aspnetcore/tree/bedac1ec8a086c3c5c7b7563af6ad97f287bc55d/src/ProjectTemplates/Web.ProjectTemplates/content/ComponentsWebAssembly-CSharp

The template has Hosted flag which is false by default.
When Hosted is false, source modifiers renames `.Client.csproj` to `.csproj` (https://github.com/dotnet/aspnetcore/blob/bedac1ec8a086c3c5c7b7563af6ad97f287bc55d/src/ProjectTemplates/Web.ProjectTemplates/content/ComponentsWebAssembly-CSharp/.template.config/template.json#L66-L75)
But primaryOutput still refers to it with old name (https://github.com/dotnet/aspnetcore/blob/bedac1ec8a086c3c5c7b7563af6ad97f287bc55d/src/ProjectTemplates/Web.ProjectTemplates/content/ComponentsWebAssembly-CSharp/.template.config/template.json#L39-L42)

This gives incorrect primary output path error.

### Expected Behavior

primaryOutputs matches what is on disk.

**Comment by javiercn** [comment]
@smitpatel good catch.

@mkArtak Given that this is 6.0 and that doesn't happen in later versions, I think we aren't taking any action (we wouldn't service this).
