### ISSUE TITLE
Need custom configurations and New Default implementations for Identity Endpoints

### ISSUE THREAD

**Issue by Snowlights2022** [dotnet/aspnetcore#56914]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

While selecting an authentication framework, I discovered that .NET8 introduced a new API, **_public static IEndpointConventionBuilder MapIdentityApi<TUser>(this IEndpointRouteBuilder endpoints)_**,
 for authentication. My team and I then planned to use it to replace the tedious work we would encounter - implementing authentication based on cluttered, poorly directed documentation on top of the various authentication frameworks; and providing role-based protection support for the minimal API server-side application we were working on.
From this point on, the trouble started. My team of three and I were all current college students enrolled in non-computer science majors, and probably had just limited C# development skills. We found that the minimal API implemented by this addition had some features that didn't fit our needs, such as most of the confirmation of identity revolving around **email addresses**. Considering the cultural differences around the world, such a default implementation was possible. So I travelled to MS learn, StackOverflow and other technical sites to find possible documentation and tutorials in order to implement an identity system that **revolves around purely numeric accounts**. Strangely enough including MS learn, it was hard to find articles mentioning changes to the new API. In the meantime, we tried to navigate to the source code in Visual Studio to see the definitions, and found that there was no place to customize it unless we spent more time downloading the source code to modify it and reconfigure it as described in #55792 . Unfortunately, we don't have the ability to re-modify and re-apply the official source code without conflicting with other official source code.
So, we tried to do this at another level - a simple login, logout, password reset, and role-based authorization and authentication on a lower level manager. However, the usermanager, signinmanager, and rolemanager parts of the implementation _lacked documentation_ for the relatively new .NET8 and minimal APIs, making it difficult to implement the functionality ourselves from the lower level of the manager.
This problem has taken us five days of finding the problem, searching for ideas, and long hours of experimentation, resulting in more and more problems and technical blind spots.
And I'm frustrated. I don't think it fits the design aesthetic of C#.NET - _simple_ enough to use out of the box, flexible enough to be fully _customizable_ and _extensible_, and _enjoyable_ to work with for all levels of developers, from beginners to proficients.

### Describe the solution you'd like

I'd like to be able to **_expose_** this customizable or extensible method **_separately and independently_** to _IEndpointRouteBuilder_ or _IdentityBuilder_ for custom configuration. Providing this one line of elegant API to do most of the functionality in a simple way, while leaving room for developers with different needs to _modify_ it. Considering that there are quite a few national and regional customs and many identity processing scenarios that _don't require the use of email addresses_, such as identity systems within schools that are closely related to staff numbers and identity systems in various countries that use ID cards as the default account, there should be _an additional set of default implementations_ **_based on simple combinations of numbers and letters as the account_** for developers to choose from.

### Additional context

If possible, I would like to query here how to implement an identity system with simple functionality based on purely numeric accounts based on ASP.NET Identity here? Any idea, roadmap or tutorial would be appreciated! Thx!

**Comment by mkArtakMSFT** [comment]
Thanks for reaching out. We've heard similar feedback from other customers asking to provide extensibility in this area and we track that work as part of the issue that you've discovered and linked above: https://github.com/dotnet/aspnetcore/issues/55792

But for now, you can only copy the content from a single file to your project and implement your own set of APIs for this very purpose: https://github.com/dotnet/aspnetcore/blob/main/src/Identity/Core/src/IdentityApiEndpointRouteBuilderExtensions.cs
