### ISSUE TITLE
ASP.NET Core default authentication handler doesn't make any sense with AllowAnonymous

### ISSUE THREAD

**Issue by foriequal0** [dotnet/aspnetcore#56925]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Default authentication handler behavior doesn't make any sense with AllowAnonymous.

### Expected Behavior

AllowAnonymous should not invoke the default authentication handler unless 

### Steps To Reproduce

Program.cs
```csharp
using WebApplication1;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddControllers();
builder.Services.AddAuthorization();
builder.Services.AddAuthentication()
    .AddScheme<BasicAuthenticationOptions, BasicAuthenticationHandler>(
        BasicAuthenticationHandler.SchemeName, null);

var app = builder.Build();
app.UseRouting();
app.UseAuthentication();
app.UseAuthorization();
app.MapControllers();
app.Run();
```

WeatherController.cs
```csharp
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace WebApplication1;

[AllowAnonymous]
[Route("weather")]
public class WeatherController : Controller
{
    [HttpGet]
    public string Get()
    {
        return "sunny";
    }
}
```

BasicScheme.cs
```csharp
using System.Security.Claims;
using System.Text.Encodings.Web;
using Microsoft.AspNetCore.Authentication;
using Microsoft.Extensions.Options;

namespace WebApplication1;

internal sealed class BasicAuthenticationHandler : AuthenticationHandler<BasicAuthenticationOptions>
{
    public static readonly string SchemeName = "Basic";

    public BasicAuthenticationHandler(
        IOptionsMonitor<BasicAuthenticationOptions> options,
        ILoggerFactory logger,
        UrlEncoder encoder,
        ISystemClock clock)
        : base(options, logger, encoder, clock)
    {
    }

    protected override Task<AuthenticateResult> HandleAuthenticateAsync()
    {
        var authz = Context.Request.Headers.Authorization;
        if (authz.Count == 0)
        {
            throw new InvalidOperationException("Authorization header is missing");
        }

        // Suppose this is a basic auth
        var identity = new ClaimsIdentity(nameof(BasicAuthenticationHandler));
        var ticket = new AuthenticationTicket(new ClaimsPrincipal(identity), SchemeName);
        return Task.FromResult(AuthenticateResult.Success(ticket));
    }
}

internal sealed class BasicAuthenticationOptions : AuthenticationSchemeOptions
{
}
```

invoke `curl localhost:5274/weather`, and get 500 error.

### .NET Version

7.0.203

### Anything else?

https://github.com/dotnet/aspnetcore/blob/4cf89470a7866a963d7118bb1ba90dc35683965c/src/Http/Authentication.Core/src/AuthenticationSchemeProvider.cs#L212 
The related code hasn't been changed since this issue https://github.com/dotnet/aspnetcore/issues/44661, so it still applies to ASP.NET Core 8.0, 9.0.

I really want to throw the exception when something goes wrong, especially for authz/authn related code.
Silencing exceptions and logging then returning `AuthenticateResult` there might allow anonymous access to controllers whenever any exceptions occur if I accidentally expose any of the controllers without proper authentication policy even if I have a default auth scheme (it's easy to expose them accidentally without knowing for ASP.NET Core)

**Comment by mkArtakMSFT** [comment]
Thank you for your feedback.
We're closing this issue as the behavior discussed is by design.

It looks like your custom authentication handler throws from inside `HandleAuthenticateAsync` method, which is not correct. Instead, you should return `AuthenticateResult.NoResult()`. This will result the endpoint (decorated with the `AllowAnonymous` attribute) to be accessed even when not authenticated.

**Comment by foriequal0** [comment]
I understand that it is by design but I think they can be more coherent, less-subtle, safe-by-default. Thank you.
