### ISSUE TITLE
Blazor SSR page - start downloading WASM in background

### ISSUE THREAD

**Issue by Laftek** [dotnet/aspnetcore#56944]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Is there any way how to load (even start up maybe) WASM files on other endpoints (e.g. “/counter”) while visitor is on landing page (e.g. home “/“) which is only SSR (only static file, no interactivity)?

### Describe the solution you'd like

What I want is to load WASM component even if not visited. So when someone visit landing page e.g. example.com I already want to start downloading WASM in background which is used on example.com/counter so when I navigate from example.com to example.com/counter, only start up of WASM occur (if download was finished) not downloading. If would be even better to even start up WASM this way but probably not possible.

**Comment by javiercn** [comment]
@Laftek thanks for contacting us.

You can already do this. Use `<link rel="preload"` tags which you can set on the head of your page either during SSR or at a later point (maybe when the loaded event has fired). That said, I would be wary of doing this. It's possible for you to download all the files, but that will likely make your first page load slower if you aren't careful.
