### ISSUE TITLE
8.0 Templates.Mvc.Tests consistently timing out on Debian machines

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#56953]
## Failing Test(s)
Templates.Mvc.Tests

-

## Error Message
Timeout.

The tests have been timing out for a few weeks now (starting July 11th).

```text

```

## Stacktrace

<details>

```text

```
</details>

## Logs

<details>

```text
If you’re reading this, that means the Helix work item you’re trying to find the logs for has dead-lettered.

What this means:

- All attempts to retry execution of this work item were unable to complete.  This can be both for infrastructure reasons (problems within Azure) or issues with the work item (for instance, causing a machine to reboot unexpectedly or killing the Helix client on the machine will force a retry).
- No further work will be done for this specific work item, and its exit code is set to an artificial -1 (since it did not complete, there is no real exit code).

Common causes:

- Disabled queue (end-of-life Helix queues are automatically forwarded to deadletter and will fail instantly)
- Unhealthy Helix Client machine(s)
- Queue has been backed up heavily by a large amount of work and was manually purged by the engineering team
- Azure issues (e.g. Service Bus is overloaded)
- Malformed payloads; if Helix cannot download and unzip all payloads successfully, work will retry until dead-lettered.

For follow up:

- Check if your Helix Queue is still enabled, either via the metadata you see by browsing to https://helix.dot.net/api/info/queues?api-version=2019-06-17 or recent emails from the .NET Engineering Infrastructure team.
- Check that all work item payloads are accessible using a browser.
- If you are sending to a non-disabled queue and find this error repeatedly occurring, please contact the dnceng team.
- If a single, specific work item dead letters and others do not, consider local debugging; it may be causing spontaneous reboot (or trigging one intentionally).
```
</details>

## Build

https://dev.azure.com/dnceng-public/public/_build/results?buildId=751578

**Comment by javiercn** [comment]
@mkArtakMSFT seems that you didn't include the relevant information on the issue.

@SteveSandersonMS this is something you recently investigated, didn't you?

**Comment by SteveSandersonMS** [comment]
@javiercn Yes, if you check the past build ops issues there should be descriptions of what we thought about this at different times and what attempts we made to fix or at least bypass it. The main thing I recall was proposing that we skip these tests on Debian/Mariner until we can understand it better, though I don't know if that happened in the end.

**Comment by mkArtakMSFT** [comment]
Here is a change @SteveSandersonMS did to mitigate this in main: https://github.com/dotnet/aspnetcore/pull/56291
Let's take this into 8.0 for now.

**Comment by mkArtakMSFT** [comment]
Here is the port PR for 8.0: https://github.com/dotnet/aspnetcore/actions/runs/10080675797
@wtgodbe can you please handle merging it? Thanks!

**Comment by wtgodbe** [comment]
https://github.com/dotnet/aspnetcore/pull/56978

**Comment by mkArtakMSFT** [comment]
@wtgodbe should this be closed now?
