### ISSUE TITLE
.NET 8 - '_framework/blazor.web.js' requires Authentication for some reason

### ISSUE THREAD

**Issue by SpodoY** [dotnet/aspnetcore#56970]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a Blazor Application using AspNetCore.Authentication.JwtBearer for Authentication. While one page requires users to be authorized, Page 2 allows anonymous users. The problem I encountered was that, without a token, on Page 2, basic UI Interactions seem to fail / not work. After checking the Network Tab in Edge, all files get loaded but when trying to access the contents of _framework/blazor.web.js, a redirect to the Microsoft Auth happens. I am using the DefaultPolicy as a FallbackPolicy and it seems that the 'blazor.web.js' is the only file that requires authentication.

### Expected Behavior

Button click triggers the code specified in the "onclick"

Instead nothing happens - No errors shown

### Steps To Reproduce

Snippets of `Program.cs`
```cs
builder.Services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
    .AddMicrosoftIdentityWebApp(builder.Configuration.GetSection("AzureAd"));

builder.Services.AddControllersWithViews().AddMicrosoftIdentityUI();

builder.Services.AddAuthorization(options =>
{
    options.FallbackPolicy = options.DefaultPolicy;
});

builder.Services.AddServerSideBlazor().AddMicrosoftIdentityConsentHandler();

...
app.UseStaticFiles();

app.UseAuthentication();
app.UseAuthorization();

```

Code from the 2. Page that should work without Authentication
```erb
<MudButton Color="Color.Primary" Variant="Variant.Filled" OnClick="checkAuthCode">
    @if (isLoading)
    {
        <MudProgressCircular Class="ms-n1" Size="Size.Small" Indeterminate="true" />
        <MudText Class="ms-2"> Entsperren </MudText>
    } else
    {
        <MudText> Entsperren </MudText>
    }
</MudButton>

...
public async void checkAuthCode()
{
    Console.WriteLine("Got clicked");
}
```

### .NET Version

8.0.204

**Comment by javiercn** [comment]
@SpodoY thanks for contacting us.

`_framework/blazor.web.js` is registered as an endpoint, so if you have a fallback policy auth is going to apply to it too. You need in that case to apply `AllowAnonymous` to the `_framework/blazor.web.js` endpoint explicitly.

You can do so with something like this:
```
app.MapRazorComponents<App>()
  .Add(e => {
    if(e is RouteEndpointBuilder routeBuilder && string.equals(routeBuilder.Route.RawPattern,"_framework/blazor.web.js", StringComparison.OrdinalIgnoreCase)){
  routeBuilder.Metadata.Add(new AllowAnonymousAttribute());
}
});

**Comment by SpodoY** [comment]
@javiercn Thank you for the fast reply.

Sorry for bothering once more but I took your pseudo code and altered it a bit so it looked like this:
```
app.MapRazorComponents<App>()
    .AddInteractiveServerRenderMode()
    .Add(e =>
    {
        if (e is RouteEndpointBuilder routeBuilder)
        {
            Console.WriteLine($"Raw Text: {routeBuilder.RoutePattern.RawText}");

            if (string.Equals(routeBuilder.RoutePattern.RawText, "_framework/blazor.web.js", StringComparison.OrdinalIgnoreCase))
            {
                routeBuilder.Metadata.Add(new AllowAnonymousAttribute());
            }
        }
    });
```
Which resulted in multiple endpoints:
```
Raw Text: /Error
Raw Text: /
Raw Text: /unlock/{id}
Raw Text: /_blazor/negotiate
Raw Text: /_blazor
Raw Text: /_blazor/disconnect/
Raw Text: /_blazor/initializers/
Raw Text: /_framework/blazor.server.js
```
but not the one I thought I would see -  Could you provide me with further assistance if possible ?

**Comment by javiercn** [comment]
@SpodoY You need to call Add right after `MapRazorComponents` I believe.

**Comment by SpodoY** [comment]
@javiercn That prevents me from calling `AddInteractiveServerRenderMode()` afterwards and breaks even more functionalities when called separate like this:

```
app.MapRazorComponents<App>()
    .Add(e =>
    {
        if (e is RouteEndpointBuilder routeBuilder)
        {
            Console.WriteLine($"Raw Text: {routeBuilder.RoutePattern.RawText}");

            if (string.Equals(routeBuilder.RoutePattern.RawText, "_framework/blazor.web.js", StringComparison.OrdinalIgnoreCase))
            {
                routeBuilder.Metadata.Add(new AllowAnonymousAttribute());
            }
        }
    });

app.MapRazorComponents<App>()
    .AddInteractiveServerRenderMode();
```

**Comment by javiercn** [comment]
@SpodoY capture the result from MapRazorComponents into a variable.

**Comment by david-palladino** [comment]
I'm seeing the same issue.

**Comment by donnykwitty** [comment]
same problem here

**Comment by donnykwitty** [comment]
I think I can get this to work by putting the following code before app.UseAuthentication(); app,UseAuthorization(); ...

```
app
    .UseRouting()
    .UseAntiforgery()
    .UseEndpoints(b =>
    {
        b.MapGroup("/_framework/blazor.web.js").AllowAnonymous();
    });
```

But what will this break???

**Comment by javiercn** [comment]
Upon further investigation there seems to be an issue in the way we register the `blazor.web.js` endpoint. There's a separate issue tracking a fix https://github.com/dotnet/aspnetcore/issues/57081

**Comment by halter73** [comment]
I think you might be better off putting the `[Authorize]` attribute in `_Imports.razor` rather than configuring `options.FallbackPolicy` like @MackinnonBuck suggested in https://github.com/dotnet/aspnetcore/issues/57063#issuecomment-2256401649. If that doesn't work, you can probably use `MapGroup` to work around the issue @javiercn is fixing in #57086 but not just by doing `b.MapGroup("/_framework/blazor.web.js").AllowAnonymous()`. Instead, you'd probably want to write the code as follows:

```csharp
var blazorGroup = app.MapGroup("");

blazorGroup.MapRazorComponent<App>();
    .AddInteractiveServerRenderMode();

blazorGroup.Add(endpointBuilder =>
{
    if (endpointBuilder is RouteEndpointBuilder routeEndpointBuilder)
    {
        if (string.Equals(routeEndpointBuilder.RoutePattern.RawText, "_framework/blazor.web.js", StringComparison.OrdinalIgnoreCase))
        {
            routeEndpointBuilder.Metadata.Add(new AllowAnonymousAttribute());
        }
    }
});
```

**Comment by poiug07** [comment]
> I think you might be better off putting the `[Authorize]` attribute in `_Imports.razor` rather than configuring `options.FallbackPolicy` like @MackinnonBuck suggested in [#57063 (comment)](https://github.com/dotnet/aspnetcore/issues/57063#issuecomment-2256401649). If that doesn't work, you can probably use `MapGroup` to work around the issue @javiercn is fixing in #57086 but not just by doing `b.MapGroup("/_framework/blazor.web.js").AllowAnonymous()`. Instead, you'd probably want to write the code as follows:
> 
> ```cs
> var blazorGroup = app.MapGroup("");
> 
> blazorGroup.MapRazorComponent<App>();
>     .AddInteractiveServerRenderMode();
> 
> blazorGroup.Add(endpointBuilder =>
> {
>     if (endpointBuilder is RouteEndpointBuilder routeEndpointBuilder)
>     {
>         if (string.Equals(routeEndpointBuilder.RoutePattern.RawText, "_framework/blazor.web.js", StringComparison.OrdinalIgnoreCase))
>         {
>             routeEndpointBuilder.Metadata.Add(new AllowAnonymousAttribute());
>         }
>     }
> });
> ```

This solution does not work for me, but I understand what it meant to do. Compiler throws `cannot use explicit Add method` error. In addition, removing FallbackPolicy and adding [Authorize] attribute in import does not work with Negotiate, but I guess it is a different issue.

**Comment by abhiraam97** [comment]
var blazorGroup = app.MapGroup("");

            blazorGroup.MapRazorComponents<App>()
                .AddInteractiveServerRenderMode();

            blazorGroup.AllowAnonymous();

This worked for me!

**Comment by ilovefox-jp** [comment]
> This worked for me!
its is worked for me too.
is there anything wrong with it?
