### ISSUE TITLE
The website is called before pressing enter ASP.NET Core MVC

### ISSUE THREAD

**Issue by ThanhDeveloper** [dotnet/aspnetcore#56971]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I created new project with ASP.NET Core MVC latest version. It shows a strange behavior.
When I launch the project and navigate to https://localhost:7266/ and add / manually after the url, the browser suggests the previous url visited. I pressed the scroll key on the keyboard to the url https://localhost:7266/email-verification without pressing the enter key. Debug will touch the code with the router above (but browser will not do anything and will not change. just hit breakpoint in my code).

Is this behavior correct? Is there any documentation about this? It would be a waste if users misuse this and affect the performance of the website.

Then pressed enter and it will be call again:

![image](https://github.com/user-attachments/assets/e8536a24-668f-4b64-9817-2d3bff7a352f)

![image](https://github.com/user-attachments/assets/38f87e04-2b72-4681-8159-ad8d8787c4e6)

My code:
```
public class VerificationController(TimeProvider timeProvider) : Controller
{
    [Route("email-verification")]
    public IActionResult EmailVerification()
    {
        ViewBag.CurrentYear = timeProvider.GetUtcNow().Year;
        Console.WriteLine("Called");
        return View();
    }
}
```

program.cs
```
var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
builder.Services.AddControllersWithViews();

builder.Services.AddSingleton<TimeProvider, ZonedTimeProvider>();

builder.Services
    .AddDbContext<IdentityPortalDbContext>(options =>
        options.UseSqlServer(builder.Configuration.GetConnectionString("Sql")));

var app = builder.Build();

if (builder.Configuration.ShouldMigrateDatabases())
{
    await app.MigrateDatabase();
}

app.UseHttpsRedirection();
app.UseStaticFiles();

app.UseRouting();

app.UseAuthorization();

app.MapControllerRoute(
    name: "default",
    pattern: "{controller=Home}/{action=Index}/{id?}");

await app.RunAsync();
```

### Expected Behavior

Breakpoints should not fire when pressing enter on the browser

### .NET Version

8.0.300

**Comment by martincostello** [comment]
This is probably Chrome trying to pre-fetch page metadata.

**Comment by ThanhDeveloper** [comment]
> This is probably Chrome trying to pre-fetch page metadata.

But let's imagine that we do a lot of things before return view. Will it waste resources?

**Comment by ThanhDeveloper** [comment]
It seems to be happening on chrome. edge does not have this happen

> I don't know - it depends what your application does.
> 
> If it is Chrome pre-fetching, then it has nothing to do with ASP.NET Core anyway and won't be something the team can do anything about.
> 
> Do you see same behaviour in other browsers such as Edge, Firefox, Safari etc.?

It seems to be happening on chrome. edge does not have this happen

**Comment by ThanhDeveloper** [comment]
It seems like this is happening because of the browser. So I will close the issue. Thank
