### ISSUE TITLE
TypeError: Failed to execute 'fetch' in Blazor Webassembly

### ISSUE THREAD

**Issue by fabiohcnobre** [dotnet/aspnetcore#57015]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am using the code below

```csharp
var client = new HttpClient();
var request = new HttpRequestMessage(HttpMethod.Get, "http://apibihml.com.br/obter-acesso/");
request.Headers.Add("Host", "apibihml.com.br");
request.Headers.Add("AcceptCharset", "utf-8");
var response = await client.SendAsync(request);
response.EnsureSuccessStatusCode();
Console.WriteLine(await response.Content.ReadAsStringAsync());
```

Erro in blazor

▶ | ErrorMessage | 'TypeError: Failed to execute 'fetch' |

### .NET Version

8

### Anything else?

OS: Windows
.NET version 8
Blazor Webassembly

**Comment by javiercn** [comment]
@fabiohcnobre thanks for contacting us.

That sounds like the request is failing on the network. Open the dev tools on your browser and check the response. If the request is cross-origin, you might need to enable CORS. See https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.webassembly.http.webassemblyhttprequestmessageextensions?view=aspnetcore-8.0

In any case, make sure that your request succeeds first with a plain `fetch` (you can do so from the console) then the equivalent should work in wasm.

**Comment by fabiohcnobre** [comment]
The page at 'https://localhost:7297/users' was loaded over HTTPS, but requested an insecure resource 'http://apibihml.value4u.com.br/obter-acesso'. This request has been blocked; the content must be served over HTTPS.


![image](https://github.com/user-attachments/assets/96c7a40a-f8ef-490b-8e29-c453a20d2b19)

**Comment by javiercn** [comment]
@fabiohcnobre thanks for the additional details.

Seems that you issue is not Blazor specific, but a standard web issue. It's not clear what you mean by "removing authentication" but the message is clearly telling you that you are trying to call an HTTP api from a document that is served over HTTPS, which is not something that you should do as it leaks information from a secure context.

You can check if the API is also served over HTTPS (which it should) and in that case use that. You could also use HTTP for local development, but that will just avoid the problem temporarily until you deploy the app.

**Comment by fabiohcnobre** [comment]
When I'm talking about disabling I'm talking about disabling CORS.

![image](https://github.com/user-attachments/assets/5c7c9746-a4e0-4db8-bea9-9182cdbb1737)

**Comment by fabiohcnobre** [comment]
I use 

![image](https://github.com/user-attachments/assets/2d81e2b9-4bcb-4e17-a522-78759ee489b5)
