### ISSUE TITLE
Blazor needs to be more object oriented and event handlers need to be revised.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#57024]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Blazor-needs-to-be-more-object-oriented-/10708004)._

---
![Screenshot 2024-07-23 031031.png](https://aka.ms/dc/image?name=B79b72313ed294361a7265ee021053e37638572902980042421_Screenshot_2024-07-23_031031.png&tid=79b72313ed294361a7265ee021053e37638572902980042421)
Blazor is great but it needs to be more object oriented and there are a lot of Un-logical issues in control event handling that should be solved.

See the following code:  
@page “/ComponentBuilder”  
@inject DialogService DialogService  
@inject NavigationManager Navigation  
@using blzHMIS.Components.Layout  
@using blzHMIS.fldHMISData.Models.TyMng.GetTyChNSpc  
@inject GetTyChNSpcProcedures GetTyChNSpcProc  
@using blzHMIS.fldHMISData.Models.TyMng.GetTyDt  
@inject GetTyDtProcedures GetTyDtProc  
@using blzHMIS.fldHMISData.Models.TyMng.GetModPath  
@inject GetModPathProcedures GetModPathProc  
@using blzHMIS.fldHMISData.Models.TyMng.TyInsUpd  
@inject TyInsUpdProcedures TyInsUpdProc  
@rendermode InteractiveServer  
<RadzenDialog />  
<RadzenNotification />

<table style=“width:100%;”>  
<tr>  
<td style=“padding-left:10px;”>  
<span style=“display:inline-block; color: royalblue; font-weight: bolder; font-size: 20px;”>System Type Manager</span>  
</td>  
<td style=“padding-right:10px;” class=“cssAlignRt”>  
<label>@strLogins</label>  
<a style=“margin-left:30px;” href=“/UMLoggedTr”>Back to your home page</a>  
<a style=“margin-left:30px;” href=“/UMLoggedTr”>Logout</a>  
</td>  
</tr>  
</table>  
<div style=“height:800px; padding-left:10px; padding-right:10px;”>  
<span style=“display:block; color: orangered; font-size: 14px;” class=“cssBorderTopBottom”>Add a child node under a parent node, update or relocate a selected node:</span>  
<table style=“width:100%; margin-top:3px;”>  
<tr>  
<td>  
<div style=“margin-left:10px; padding-bottom:6px;”>  
<InputCheckbox @bind-Value=“bolShowReserved” disabled=“@bolIsUser” @onchange=“GetRootNode” /> Show reserved nodes  
</div>  
<div class=“cssBorderAll” style=“width:400px; border-radius:0.5em;”>  
<span class=“cssLinkButton2” @onclick=“GetRootNode” style=“margin-top:6px; padding-left:2px; font-weight:bold;”>System Types</span><span style=“font-size:smaller; color:blue;”> Click it to refresh tree</span>  
<RadzenTree @ref=“tvwPage” Data=“@enuTysByRef” Expand=@OnExpand Change=“@OnNodeSelect” style=“padding-left:30px; height: 710px; width:398px;” SingleExpand=“false”>  
<RadzenTreeLevel TextProperty=“TyNameA” HasChildren=@(e =>!( e as TblGetTyChNSpc). IsEndLeaf)>  
<Template>  
<span style=“font-weight:500;” class=“cssNodeLevel2”>@context. Text</span>  
</Template>  
</RadzenTreeLevel>

</RadzenTree>  
</div>  
</td>  
<td>  
<fieldset disabled=“@bolEnableUpdate”>  
<div>  
<div style=“padding-top: 8px;”>  
<span style=“margin-left:20px;”>Leaf lable1: </span>  
<InputText class=“cssTextLtrCenter” @bind-Value=“strTyNameA” type=“text” style=“width:600px;” />  
<span style=“margin-left:20px;” />  
<InputCheckbox @bind-Value=“bolIsEndLeaf” /> Is end leaf  
<span style=“margin-left:160px;” />  
<InputCheckbox @bind-Value=“bolIsHidden” /> Is hidden  
<span style=“margin-left:100px;” />  
<InputCheckbox @bind-Value=“bolSaveAsModule” /> Auto save as module  
</div>  
<br style=“content: ‘’; display: block; margin-bottom:10px;” />  
<div>  
<span style=“margin-left:20px;”>Leaf lable2: </span>  
<input class=“cssTextLtrCenter cssArFont” @bind-value=“strTyNameB” style=“width:600px;” />  
<span style=“margin-left:20px;”>Abbreviation: </span>  
<input class=“cssTextLtrCenter” @bind-value=strTyAbr style=“width:100px;” />  
<span style=“margin-left:56px;”>Order: </span>  
<input class=“cssTextLtrCenter” @bind-value=“intLO” style=“width:100px;” />  
</div>  
<br style=“content: ‘’; display: block; margin-bottom:10px;” />  
<div>  
<span style=“margin-left:20px;”>Leaf lable3: </span>  
<input class=“cssTextLtrCenter” @bind-value=“strTyNameC” style=“width:600px;” />  
<span style=“margin-left:20px;”>Module path: </span>  
<input class=“cssTextLtrLeft” style=“width:300px;” @bind-value=strModPath />  
</div>  
<hr />  
</div>

</fieldset>  
<fieldset style=“height: 90px; margin-left: 20px; margin-top: 10px; margin-bottom: 10px; border-style: solid; border-width: 1px; background-color: rgb(238, 241, 255); border-radius: 0.5em;” disabled=“@bolChk”>  
<span style=“color: rgb(50, 95, 178); font-weight: bold; font-size: 12px; padding-left: 10px;”>Reserving node placeholders and updating references and module path:</span>  
<br style=“content: ‘’; display: block; margin-bottom: 2px;” />  
<span style=“margin-left: 20px; margin-right: 5px;” />  
<InputCheckbox @bind-Value=“bolChk” /> Enable generating placeholders  
is that input enabled:  
<input class=“cssTextLtrCenter” style=“width:100px; font-size:12px;” />  
<hr />  
</fieldset>

<div style=“margin-left:10px; width:1490px;”>  
<RadzenHtmlEditor @bind-Value=“@strRemark” style=“height:470px; width:100%;margin-bottom:5px;” />  
<div>  
<br style=“content: ‘’; display: block; margin-bottom: 10px;” />  
<span style=“margin-left:30px;” class=“cssLinkButton1” onclick=“@AddNode”>Add new leaf</span>  
<span style=“margin-left:30px;” class=“cssLinkButton1” onclick=“@UpdateNode”>Update selected leaf</span>  
<span style=“margin-left:30px;” class=“cssLinkButton1” onclick=“@CancelChanges”>Cancel changes</span>  
<span style=“margin-left:30px;” class=“cssLinkButton1” onclick=“@SaveNode”>Save changes</span>  
<span style=“margin-left:30px;” class=“cssLinkButton1” onclick=“@UpdateRemark”>Remark direct save</span>  
</div>  
</div>  
</td>  
</tr>  
</table>

</div>

@code  
{  
int intUAcsPriv = Convert.ToInt32(MainLayout.SessionDic\[“UAcsPriv”\]);  
int? intUIDf = Convert.ToInt32(MainLayout.SessionDic\[“UIDf”\]);  
bool bolIsUser = true;  
bool bolChk = false;  
string? strOpt;  
string? strLogins;  
string? strUserNote;  
bool bolEnableUpdate = true;  
bool bolAddToRoot = false;  
bool bolShowReserved = false;  
bool bolSaveAsModule = false;  
RadzenTree? tvwPage;  
RadzenNotification notification;  
//----------------------Controls Binding------------------------  
int? intTyIDf;  
int? intTyRef;  
string? strTyNameA;  
string? strTyNameB;  
string? strTyNameC;  
string? strTyAbr;  
int? intLO;  
string? strTyPath;  
bool bolIsEndLeaf;  
bool bolIsHidden;  
string? strRemark;  
string? strModPath;  
//--------------------------------------------------------------

IEnumerable<TblGetTyChNSpc>? enuTysByRef;  
private TblGetTyChNSpc? nodSelected;  
private RadzenTreeItem? nodItem;  
private RadzenTextBox inpTyNameA;

protected override async Task OnInitializedAsync()  
{

if(intUAcsPriv == 3)  
{  
bolShowReserved = true;  
bolIsUser = false;  
}  
await GetTyByRef(0);  
await GetTyDt(0);  
strLogins = $“{“Login: " + MainLayout.SessionDic\[“UName”\]}{”, ID: \[” + MainLayout.SessionDic\[“UIDf”\] + “\] p” + MainLayout.SessionDic\[“UAcsPriv”\] + " m?“}”;  
strUserNote = “String that is used to display instructions to users using this component.”;  
}

protected async Task GetRootNode()  
{  
await Task.Delay(2000);  
await GetTyByRef(0);  
await GetTyDt(0);  
}  
private void ClearNodeData()  
{  
strTyNameA = string. Empty;  
strTyNameB=string. Empty;  
strTyNameC=string. Empty;  
strTyAbr = string. Empty;  
intLO = 0;  
strTyPath=string. Empty;  
bolIsEndLeaf=false;  
bolIsHidden=false;  
strRemark=string. Empty;  
}

private async void AddNode()  
{  
strOpt = “Ins”;  
if(bolIsEndLeaf)  
{  
string strSweetHtml =  
$“{”<div class=‘cssAlignLt’><span class=‘cssSwalCause’>The node you selected is an end leaf.</span><br>“}”+  
$“{”<span class=‘cssSwalDetails’>We can not insert child nodes under a parent marked as end leaf.</span>“}” +  
$“{”<br><span class=‘cssSwalToDo’>You may un-mark the selected node as normal node or select another parent for this procedure to be done.</span></div>“}”;  
await Swal.FireAsync(new SweetAlertOptions  
{  
Title = “<span class=‘cssSwalTError’>Error encountered</span><hr class=‘cssSwalHr’/>”,  
Html = strSweetHtml,  
//Icon = SweetAlertIcon.Success,  
ConfirmButtonText = “Cancel”  
});  
return;  
}  
ClearNodeData();  
bolEnableUpdate = false;  
strUserNote = strOpt;  
StateHasChanged();  
}

private async void UpdateNode()  
{  
strOpt = “Upd”;  
bolEnableUpdate = false;  
strUserNote = strOpt;  
}  
private void CancelChanges()  
{  
bolEnableUpdate = true;  
}  
private async void SaveNode()  
{  
var intIden = new blzHMIS.fldHMISData.Models.TyMng.TyInsUpd.OutputParameter<int?>();  
switch(strOpt)  
{  
case “Ins”:

if(bolAddToRoot)  
{  
intTyIDf = 0;  
}

await TyInsUpdProc.TyMngSPAsync(“InsTy”, null, intTyIDf, strTyNameA, strTyNameB, strTyNameC, strTyAbr, intLO, bolIsEndLeaf, bolIsHidden, strRemark, null, intUIDf, intIden);  
break;

case “Upd”:  
await TyInsUpdProc.TyMngSPAsync(“UpdTy”, intTyIDf, null, strTyNameA, strTyNameB, strTyNameC, strTyAbr, intLO, bolIsEndLeaf, bolIsHidden, strRemark, null, intUIDf, intIden);

if(nodSelected != null)  
{  
nodSelected.TyNameA = strTyNameA;  
strUserNote = $“Node updated: {nodSelected.TyNameA}”;  
}  
else  
{  
strUserNote = “No selected node found for update”;  
}  
break;

default:  
strUserNote = “Nothing found to update or insert to apply, action denied.”;  
break;  
}  
strOpt = string. Empty;  
bolEnableUpdate = true;  
bolAddToRoot = false;  
StateHasChanged();  
}  
private async void UpdateRemark()  
{  
var intIden = new blzHMIS.fldHMISData.Models.TyMng.TyInsUpd.OutputParameter<int?>();  
await TyInsUpdProc.TyMngSPAsync(“UpdRemark”, intTyIDf, null, null, null, null, null, null, null, null, strRemark, null, null, intIden);  
}

protected async Task GetTyByRef(int intTyIDf)  
{

var intIden = new blzHMIS.fldHMISData.Models.TyMng.GetTyChNSpc.OutputParameter<int?>();  
if(intUAcsPriv == 3 && bolShowReserved == true)  
{

enuTysByRef = await GetTyChNSpcProc.TyMngSPAsync(“GetTyChildren”, null, intTyIDf, null, null, null, null, null, null, null, null, null, null, intIden);  
}  
else  
{  
enuTysByRef = await GetTyChNSpcProc.TyMngSPAsync(“GetTyChildrenNotReserved”, null, intTyIDf, null, null, null, null, null, null, null, null, null, null, intIden);  
}

}

async Task OnExpand(TreeExpandEventArgs args)  
{  
var nodExpanded = args. Value as TblGetTyChNSpc;  
if(nodExpanded != null)  
{  
var intIden = new blzHMIS.fldHMISData.Models.TyMng.GetTyChNSpc.OutputParameter<int?>();  
var nodChildren = await GetTyChNSpcProc.TyMngSPAsync(“GetTyChildren”, null, nodExpanded.TyIDf, null, null, null, null, null, null, null, null, null, null, intIden);  
args. Children.Data = nodChildren;  
args. Children.TextProperty = “TyNameA”;  
args. Children.HasChildren = e => ! (e as TblGetTyChNSpc). IsEndLeaf;  
args. Children.Template = nodFound => (builder) =>  
{  
builder. OpenElement(0, “span”);  
builder. AddAttribute(1, “class”, “cssNodeLevel1”);  
builder. AddContent(2, nodFound.Text);  
builder. CloseElement();  
};  
strUserNote = nodChildren.Count(). ToString();  
}  
StateHasChanged();  
}

async void OnNodeSelect(TreeEventArgs args)  
{  
nodSelected = args. Value as TblGetTyChNSpc;  
int TyIDf = nodSelected.TyIDf;  
await GetTyDt(TyIDf);  
await GetModPath(TyIDf);  
strUserNote = $“{“Path: " + nodSelected.TyPath}{”; " + nodSelected.TyIDf}{”, IsEndleaf = " + nodSelected.IsEndLeaf.ToString()}";  
tvwPage.Value = nodSelected;  
bolAddToRoot = false;  
StateHasChanged();  
}  
protected async Task GetTyDt(int TyIDf)  
{  
var intIden = new blzHMIS.fldHMISData.Models.TyMng.GetTyDt.OutputParameter<int?>();  
List<TblGetTyDt> lstGetTyDt = await GetTyDtProc.TyMngSPAsync(“GetTyByIDf”, TyIDf, null, null, null, null, null, null, null, null, null, null, null, intIden);  
intTyIDf = TyIDf;  
intTyRef = lstGetTyDt\[0\]. TyRef;  
strTyNameA = lstGetTyDt\[0\]. TyNameA;  
strTyNameB = lstGetTyDt\[0\]. TyNameB;  
strTyNameC = lstGetTyDt\[0\]. TyNameC;  
strTyAbr=lstGetTyDt\[0\]. TyAbr;  
intLO = lstGetTyDt\[0\].LO;  
strTyPath = lstGetTyDt\[0\]. TyPath;  
bolIsEndLeaf = lstGetTyDt\[0\]. IsEndLeaf;  
bolIsHidden = lstGetTyDt\[0\]. IsHidden;  
strRemark = lstGetTyDt\[0\]. Remark;  
}  
protected async Task GetModPath(int TyIDf)  
{  
var intIden = new blzHMIS.fldHMISData.Models.TyMng.GetModPath.OutputParameter<int?>();  
List<TblGetModPath> lstGetModPath = await GetModPathProc.TyMngSPAsync(“GetModPath”, TyIDf, null, null, null, null, null, null, null, null, null, null, null, intIden);  
if(lstGetModPath.Count() > 0)  
{  
strModPath = lstGetModPath\[0\]. ModPath;  
}  
else  
{  
strModPath = “Not a module”;  
}  
}  
}

<style>  
.cssTest  
{  
color: blue;  
width: 300px;  
}  
</style>  
<div style=“height: 20px;” class=“cssBorderTop”>  
<span id=“spnNote” style=“padding-left:5px; font-style: italic;”>@strUserNote</span>  
</div>

In \[<InputCheckbox @bind-Value=“bolShowReserved” disabled=“@bolIsUser” @onchange=“GetRootNode” /> Show reserved nodes\], the GetRootNode will never execute in the previous code, while it’s normally executed with \[<span class=“cssLinkButton2” @onclick=“GetRootNode” style=“margin-top:6px; padding-left:2px; font-weight:bold;”>System Types</span><span style=“font-size:smaller; color:blue;”> Click it to refresh tree</span>\] this needs an explanation please.

---
#### Feedback Bot on 7/22/2024, 06:24 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by javiercn** [comment]
Thanks for contacting us.

It's unclear what you are trying to communicate. The problem is not clearly described in a way that we can understand or action on. Please clearly specify the problem with the simplest code snippet you can come up with. Ideally, as a minimal repro project that we can look at with detailed steps that illustrate the problem.
