### ISSUE TITLE
.NET 8 Blazor Web App Scoped Dependency Injection Behavior

### ISSUE THREAD

**Issue by donnykwitty** [dotnet/aspnetcore#57022]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Start with the standard Blazor Web App template.
Create a new "service" class and add it as scoped in program.cs, as such

`builder.Services.AddScoped<MyService>();
`

Upon first navigation to the home page, a new instance of MyService is created--during pre-rendering. Another, seperate instance is created on the client. This second instance is then re-used for any additonal navigation from the client, until any page is refreshed--at which point, two instances are created again.

This would seem to me to be a bug. Why isn't the instance created during pre-rendering passed into the client?

Note that for a singleton dependency, the single instance created on the server is, indeed, passed to the client. 

### Expected Behavior

I would expect that a scoped dependency instantiated on the server would be used on the client. This works as expected for singletons.

The current behavior is completely unintuitive. 

### Steps To Reproduce

Standard .NET 8 Blazor Web App template.
Observe a scoped dependency be instantiated twice for every server request.

### .NET Version

8

**Comment by javiercn** [comment]
@donnykwitty thanks for contacting us.

Not a bug, by design. Different render modes have different DI scopes. Especially, when we talk about Webassembly where the client runs effectively in a separate process.

**Comment by donnykwitty** [comment]
@javiercn I understand different render modes have different DI scopes. But please explain why the situation I've described would be by *design*. Why would you *design* it in such a way that a "scoped" dependency would be different while pre-rendering on the server? Why wouldn't you *prefer* to have the same instance of a "scoped" dependency be used on both the server & the client. Is there a technical reason for this? Somehow sharing the same instance for singletons works. Why not for scoped items?

**Comment by donnykwitty** [comment]
Eventually--if more people start using Blazor--you'll hear from others, and you'll realize this isn't a good "design".
