### ISSUE TITLE
SignalR Streaming Channel cancellation issue

### ISSUE THREAD

**Issue by Rishi201685** [dotnet/aspnetcore#57051]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Describe the bug

Hi Signalr teams, when I use signalr streaming with channel then when i request to stop the streaming to the channel , when client is disconnected but producer produce the data, that time also i removed the channel on disconnection of client and also pass the cancellation token in async writer to stop the write , in that time multiple infinte time loop exeception occure & hub fail after reconnection client to send data

### Expected Behavior

Expected Behaviour is to stop the write to channel and when reconnection attempted then that connection not close, or in infinte time execption stop by the provided package

### Steps To Reproduce

.

### Exceptions (if any)

.

### .NET Version

.net 6

### Anything else?

.

**Comment by BrennanConroy** [comment]
Please provide a repro, I don't understand what you're trying to describe.

**Comment by Rishi201685** [comment]
---------------------------- When Client disconnected , I subscribe cancellation token to cancel the write to the channel but it's throw infinite time Exception --------------


public override Task OnDisconnectedAsync(Exception exception)
{
    
    cts.cancel();
    return base.OnDisconnectedAsync(exception);
}

var cts = new CancellationTokenSource();

 public async Task StartStream(string streamName, IAsyncEnumerable<string> streamContent, cts.token)
 {
    
         var streamTask = _streamManager.RunStreamAsync(streamName, streamContent,cts.token);
         await streamTask;
     
    
 }


------------------ My Stream_Manager side written code ---------------------

public async Task RunStreamAsync(string streamName, IAsyncEnumerable<string> stream, CancellationToken cancellationToken)
{
    var channel = GetOrCreateChannel(streamName);

    try
    {
        await foreach (var item in stream.WithCancellation(cancellationToken))
        {
            try
            {
                await channel.Writer.WriteAsync(item, cancellationToken);
            }
            catch (OperationCanceledException)
            {
                Console.WriteLine("Write operation was canceled.");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error writing to channel: {ex.Message}");
                
            }
        }
    }
    catch (OperationCanceledException)
    {
        Console.WriteLine("Streaming was canceled.");
    }
    catch (Exception ex)
    {
        Console.WriteLine($"Error during streaming: {ex.Message}");
    }
    finally
    {
        channel.Writer.Complete();
    }
}

**Comment by BrennanConroy** [comment]
Without seeing the `IAsyncEnumerable` you're passing in, it looks like you're not honoring the cancallation token in your `IAsyncEnumerable`. See https://stackoverflow.com/questions/58234775/how-to-force-an-iasyncenumerable-to-respect-a-cancellationtoken

So what happens is `await foreach (var item in stream.WithCancellation(cancellationToken))` never looks at the `cancellationToken` so it keeps iterating over the stream and you get an exception from `await channel.Writer.WriteAsync(item, cancellationToken);` but catch the exception and keep the loop going.
