### ISSUE TITLE
RequestStream’s `Flush` should not throw

### ISSUE THREAD

**Issue by vcsjones** [dotnet/aspnetcore#57064]
The `RequestStream` class is a read only stream, and throws for `Flush`

https://github.com/dotnet/aspnetcore/blob/f0120ae63e1c7bf6dc77116bf18c7d90c15ee855/src/Servers/HttpSys/src/RequestProcessing/RequestStream.cs#L80

Over in `dotnet/runtime`, an [issue was filed](https://github.com/dotnet/runtime/issues/105592) because this is incompatible with `CryptoStream`, which expects to be able to call `Flush` on any stream, even if it is read only (and for historical and compatibility reasons, needs to continue to do so).

The expected contract for `Stream.Flush` is to not throw for read only streams. From [the docs](https://learn.microsoft.com/en-us/dotnet/api/system.io.stream.flush?view=net-8.0&redirectedfrom=MSDN#System_IO_Stream_Flush)

> In a class derived from Stream that doesn't support writing, Flush is typically implemented as an empty method to ensure full compatibility with other Stream types since it's valid to flush a read-only stream.

(This is also applicable to `FlushAsync` and any other `Stream`-derived class, not just `RequestStream`)

**Comment by teo-tsirpanis** [comment]
There are other streams whose `Flush` method throws. Here are some examples:

https://github.com/dotnet/aspnetcore/blob/27ae0821dded5d31b8f7a1cd4519a8ef3ccd6cc3/src/Hosting/TestHost/src/ResponseBodyReaderStream.cs#L51
https://github.com/dotnet/aspnetcore/blob/27ae0821dded5d31b8f7a1cd4519a8ef3ccd6cc3/src/Components/Server/src/Circuits/RemoteJSDataStream.cs#L163-L164
https://github.com/dotnet/aspnetcore/blob/27ae0821dded5d31b8f7a1cd4519a8ef3ccd6cc3/src/Components/Shared/src/PullFromJSDataStream.cs#L57-L58
https://github.com/dotnet/aspnetcore/blob/27ae0821dded5d31b8f7a1cd4519a8ef3ccd6cc3/src/Mvc/shared/Mvc.Core.TestCommon/NonSeekableReadableStream.cs#L39-L42
https://github.com/dotnet/aspnetcore/blob/27ae0821dded5d31b8f7a1cd4519a8ef3ccd6cc3/src/Shared/SegmentWriteStream.cs#L100-L106

**Comment by martincostello** [comment]
I've pushed up #57079 which changes all the specific examples called out above. I didn't spot any `FlushAsync()` overrides from a cursory search that just threw and otherwise did nothing.
