### ISSUE TITLE
WebSocket keep-alive timeout API

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/aspnetcore#57072]
## Background and Motivation

dotnet/runtime is adding an API to control the keep-alive timeout see https://github.com/dotnet/runtime/issues/48729#issuecomment-1979542776
Our WebSocket middleware exposes options to control the websocket options being used so we would want to expose an equivalent option.

## Proposed API

```diff
namespace Microsoft.AspNetCore.Builder;

public class WebSocketOptions
{
    public TimeSpan KeepAliveInterval { get; set; }
+   public TimeSpan KeepAliveTimeout { get; set; }
}
```

## Usage Examples

```csharp
builder.AddWebSockets(o =>
{
    o.KeepAliveTimeout = TimeSpan.FromMinutes(1);
});
```

**Comment by amcasey** [comment]
What's the distinction between KeepAliveInterval and KeepAliveTimeout?

**Comment by BrennanConroy** [comment]
KeepAliveInterval determined how often a Pong is sent to the other side. However, with the introduction of KeepAliveTimeout, if the value of KeepAliveTimeout is non-zero or non-infinite then KeepAliveInterval is how often a Ping is sent, and KeepAliveTimeout is how long we wait for a Pong response before closing the connection due to a timeout.

**Comment by amcasey** [comment]
Background: a Pong is a Ping for which no response/acknowledgement is expected

To paraphrase:

A KeepAliveInterval of 5 seconds with no (i.e. zero or infinite) KeepAliveTimeout means "send a Pong every 5 seconds".

A KeepAliveInterval of 5 seconds with a KeepAliveTimeout of 1 second means "send a Ping every 5 seconds and kill the connection if any ping acknowledgement (i.e. Pong) takes more than 1 second".

Is that right?

**Comment by amcasey** [comment]
I think another way to look at it would be that a keep alive frame with no timeout has no reason to look for a response, so it degrades from a Ping to a Pong?

**Comment by amcasey** [comment]
- What are the default values?
    - We can, but don't have to, use the same ones as runtime
- We also have KestrelServerLimits.KeepAliveTimeout
    - It doesn't accept 0
    - It defaults to 130 seconds
- What value do we use to express that there is no timeout?
    - MaxValue?
    - 0?
    - Timeout.InfiniteTimeSpan?
- Validate with a test that passing MaxValue doesn't break things (regardless of whether it means no timeout)
- A comment on the runtime PR suggests it was Ping before it was Pong

API Approved!

**Comment by BrennanConroy** [comment]
While implementing this we realized we should add the option to `WebSocketAcceptContext` as well.
Additional API below:

```diff
public class WebSocketAcceptContext
{
     public virtual TimeSpan? KeepAliveInterval { get; set; }
+    public TimeSpan? KeepAliveTimeout { get; set; }
}
```

The reason for nullability is so we can choose the “global” value from `WebSocketOptions` instead when null. And the reason it’s not virtual when the `KeepAliveInterval` is, is due to legacy reasons where we have a `ExtendedWebSocketAcceptContext` type that implements `WebSocketAcceptContext` but it is now obsolete and we’ve moved away from that concept.

```csharp
builder.AddWebSockets(o =>
{
    o.KeepAliveTimeout = TimeSpan.FromMinutes(1);
});

var app = builder.Build();
app.UseWebSockets();

app.Use(async (context, next) =>
{
    if (context.WebSockets.IsWebSocketRequest)
    {
        var webSocket = await context.WebSockets.AcceptWebSocketAsync(new WebSocketAcceptContext()
        {
            KeepAliveTimeout = TimeSpan.FromSeconds(2)
        });

        // websocket send/receive

        return;
    }

    await n(c);
});
```
