### ISSUE TITLE
CORS policy.AllowAnyHeader() does not appear to work

### ISSUE THREAD

**Issue by catmanjan** [dotnet/aspnetcore#57071]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have the following Program.cs as part of a dotnet 8 web API project:

```
var builder = WebApplication.CreateBuilder(args);
builder.Logging.ClearProviders();
builder.Logging.AddConsole();

builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();
builder.Services.AddCors(options =>
{
    options.AddDefaultPolicy(
        policy =>
        {
            policy.AllowAnyHeader();
            policy.AllowAnyMethod();
            policy.AllowAnyOrigin();
        });
});

var app = builder.Build();

if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection();
app.UseCors();
app.UseAuthorization();
app.MapControllers();

app.Run();
```

Notice policy.AllowAnyHeader();. If I browse to my API in the latest Google Chrome I get the following headers, but no Access-Control-Allow-Headers.
![image](https://github.com/user-attachments/assets/0cd67514-b481-477d-8791-aea0855fa99d)

### Expected Behavior

I would expect to be receiving an Access-Control-Allow-Headers value of *

**Comment by BrennanConroy** [comment]
Did you request contain an `Access-Control-Request-Headers`? If not then that's the expected behavior
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Headers

**Comment by catmanjan** [comment]
Ok
