### ISSUE TITLE
[Blazor] JS initializers declared in RCLs run twice

### ISSUE THREAD

**Issue by MackinnonBuck** [dotnet/aspnetcore#57087]
## Summary

JS initializers declared in a Razor Class Libraries have each of their callbacks executed twice.

## Steps to reproduce

1. Install versions 8.0.303 and 9.0.100-preview.6.24328.19 of the .NET SDK
3. Run `dotnet new blazor -int None -o ./BlazorApp -f net8.0`
4. Run `dotnet new razorclasslib -o ./RazorClassLibrary -f net8.0`
5. Run `dotnet add ./BlazorApp/BlazorApp.csproj reference ./RazorClassLibrary/RazorClassLibrary.csproj`
6. Create the file `./RazorClassLibrary/wwwroot/RazorClassLibrary.lib.module.js` and add the following content:
    ```js
    export function afterWebStarted() {
        console.log('Hello, world!');
    }
    ```
7. Run `dotnet run --project .\BlazorApp\BlazorApp.csproj`
8. ❌ **Observe that the browser console window logged "Hello, world!" twice**
9. Run `dotnet new globaljson --sdk-version 8.0.303`
10. Run `dotnet run --project .\BlazorApp\BlazorApp.csproj`
11. 🟢  **Observe that the browser console window now only logs "Hello, world!" once**

## Other notes

1. This issue also occurs when creating projects with a `net9.0` TFM
2. The .NET 8 SDK is not required to reproduce the bug - it was included in the repro steps only to demonstrate that the issue is unique to the .NET 9 SDK.

**Comment by javiercn** [comment]
@MackinnonBuck is this an 8.0 app compiled with the 9.0 SDK?

**Comment by MackinnonBuck** [comment]
@javiercn yes, but it also reproduces for a 9.0 app as well.

**Comment by MackinnonBuck** [comment]
@javiercn yes, that's correct

**Comment by MackinnonBuck** [comment]
No longer reproduces in the latest SDK build.

It looks like https://github.com/dotnet/sdk/pull/41995 was the culprit, and this is now fixed.
