### ISSUE TITLE
Attributes on FromForm parameters are not applied in generated OpenAPI

### ISSUE THREAD

**Issue by mikekistler** [dotnet/aspnetcore#57082]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Attributes such as `[Description]`, `[Required]`, `[MaxLength]`, `[RegularExpression]`, and `[Range]` can be specified on query, route, and header parameters and these will be reflected in the schema for the parameter in the generated OpenAPI. But this is not the case for `FromForm` parameters.

The following endpoint:
```csharp
        group.MapPost("/from-form",
        (
            [FromForm][Description("Name")][Required][MaxLength(26)][RegularExpression(@"^[A-Za-z0-9-]*$")] string Name,
            [FromForm][Description("Age")][Range(0,100)] int Age,
            [FromForm][Description("Photo")][MaxLength(1024*1024)] byte[] photo
        ) =>
        {
            // Create a dynamic object to return the values
            return TypedResults.Ok(new { Name, Age });
        })
        .DisableAntiforgery(); // Anitforgery is enabled by default for form endpoints
```

Has the following request body in the generated OpenAPI document -- note that none of the attributes on the FromForm parameters have produced corresponding schema assertions.

```json
"requestBody": {
  "content": {
    "multipart/form-data": {
      "schema": {
        "type": "object",
        "allOf": [
          {
            "type": "object",
            "properties": {
              "Name": {
                "type": "string"
              }
            }
          },
          {
            "type": "object",
            "properties": {
              "Age": {
                "type": "integer",
                "format": "int32"
              }
            }
          },
          {
            "type": "object",
            "properties": {
              "photo": {
                "type": "string",
                "format": "byte"
              }
            }
          }
        ]
      }
```

This inconsistency should be corrected if possible.

### Expected Behavior

FromForm parameters with attributes such as `[Description]`, `[Required]`, `[MaxLength]`, `[RegularExpression]`, and `[Range]` should have the appropriate schema assertions in the generated OpenAPI.

### Steps To Reproduce

I will create a branch in my [aspnet-openapi-examples]() project to reproduce the behavior described above.

Here's the branch: https://github.com/mikekistler/aspnet-openapi-examples/tree/bug-57082

### .NET Version

9.0.100-rc.1.24380.1

**Comment by captainsafia** [comment]
Resolved via https://github.com/dotnet/aspnetcore/pull/56957.
