### ISSUE TITLE
Blazor _framework/blazor.web.js endpoint is not configurable.

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#57081]
We register the endpoint, but we don't add it to an endpoint data source and the endpoint builder is not exposed, which means we aren't able to add conventions to it.

https://github.com/dotnet/aspnetcore/blob/27f2a011a4211118552dfb8f38d36e8629267d2b/src/Components/Endpoints/src/Builder/RazorComponentsEndpointRouteBuilderExtensions.cs#L47-L68

**Comment by donnykwitty** [comment]
Will this change still require the developer to explicitly apply the anonymous attribute to this file? Or will this change result in things working as one would expect and not require additional configuration?

**Comment by javiercn** [comment]
@donnykwitty you will still need the `AllowAnonymous`.

If you define a global policy, then you need to explicitly carve holes in it, we can't simply decide that it's always ok to access this file
