### ISSUE TITLE
InvalidOperation_NotGenericType in AOT problem

### ISSUE THREAD

**Issue by wisamidris7** [dotnet/aspnetcore#57084]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

In my webassembly blazor 8.0 application.
I don't know why but when I published my application as aot this problem appeared
InvalidOperation_NotGenericType
but without AOT there no problem like this.

### Describe the solution you'd like

I don't know why and my application is large application (ERP) that requires aot to work

**Comment by martincostello** [comment]
I think this is going to need a minimal reproducible example for someone to be able to do anything actionable with this issue.

**Comment by wisamidris7** [comment]
thanks @martincostello 

And I don't know from where the problem cause I'm still figuring this issue
And I was think that this problem has been for someone before me

When I see the issue I will comment with the line that don't work in aot

**Comment by wisamidris7** [comment]
Okay Thanks It seems that the problem from the publishTrimmed
I setted it false and it worked

**Comment by wisamidris7** [comment]
Cause I used a reflection with getting the genericTypes
