### ISSUE TITLE
Dependencies of bootstrap and jquery-validation in templates are out of date.

### ISSUE THREAD

**Issue by v-qushi** [dotnet/aspnetcore#57119]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

**REPRO STEPS:**

1.  File > New > Project > ASP.NET Core Web App (Model-View Controller)>Select .NET 8.0 > Create.
2. Open Views->Shared->_Layout.cshtml file, TypeScript typings will be installed automatically, then observe error list window

**Actual**: The dependencies are out of date.  It only repro on 17.11.0(pre-release – GA build for August monthly update)

![image](https://github.com/user-attachments/assets/7c3a7a2e-475f-4fe5-817f-d5c3a3d804da)

### Expected Behavior

The versions of these dependencies should be updated to the latest version.

**Comment by v-qushi** [comment]
We found the dependencies were out of date when we were investigating this bug [TS/JS Warnings after creating a .NET 8 ASP.NET Core Web App](https://github.com/dotnet/aspnetcore/issues/56471), so open this new bug to track updating dependencies, maybe need to update the versions of these dependencies to the latest version – at least for 9.0.

**Comment by balachir** [comment]
There might be other dependencies that we want to review as well.

**Comment by balachir** [comment]
Including @javiercn and @mkArtakMSFT for awareness.

**Comment by AslamNazeerShaikh** [comment]
Hi @javiercn & @mkArtakMSFT 
I request if this can be possible, please update bootstrap & jQuery versions to latest in ASP.NET Core MVC, ASP.NET Core WebApp Templates.

**Comment by javiercn** [comment]
https://github.com/dotnet/aspnetcore/pull/57864
