### ISSUE TITLE
How can I use the @rendermode InteractiveServer in the Index.cshtml file?

### ISSUE THREAD

**Issue by SubaMoorthy99** [dotnet/aspnetcore#57113]
I am experiencing an issue where I am unable to define the **@rendermode InteractiveServer** directive in the Index.cshtml file of my ASP.NET Core WebApp (Razor Page) project while trying to integrate Blazor components.

**Comment by javiercn** [comment]
@SubaMoorthy99 thanks for contacting us.

No, you can't. That's only for Blazor Web. Integration with Razor Pages and MVC remains through the Component Tag helper.
