### ISSUE TITLE
[dotnet-sdk-9.0.100-preview.7.24379.15] Fail to launch SPOTClient app after retargeting it to .NET 9.0 with error: Microsoft.JSInterop.JSException: Could not find 'PlatformHelpers.initSearchInputFocus'

### ISSUE THREAD

**Issue by Junjun-zhao** [dotnet/aspnetcore#57138]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When retarget the 3rd party application to net9.0, build and run with the latest .NET 9 build, it failed to load page with error: ```Microsoft.JSInterop.JSException: Could not find 'PlatformHelpers.initSearchInputFocus'```.  **Please refer to the repro machine information from** [Internal Bug](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2183587)

**Findings:**
If we retarget this app to net9.0 and build with dotnet-sdk-9.0.100-preview.5.24307.3 or lower .NET 9.0 versions, the app can run successfully with dotnet-sdk-9.0.100-preview.7.24379.15.

**Application Name**: SPOTClient
**OS**：Windows 10 21H2
**CPU**: X64
**.NET Build Number**: dotnet-sdk-9.0.100-preview.7.24379.15

**App Source or repro machine Checking at**:https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2183587

**Verify Scenarios:**
1). Windows 10 21H2 AMD64 + default target net5.0 + default dotnet-sdk-5.0.100: Pass
2). Windows 10 21H2 AMD64 + default target net5.0 + dotnet-sdk-9.0.100-preview.7.24379.15: Pass
3). Windows 10 21H2 AMD64 + target net9.0 + dotnet-sdk-9.0.100-preview.5.24307.3: Pass
4). Windows 10 21H2 AMD64 + target net9.0 + dotnet-sdk-9.0.100-preview.6.24328.19: Fail
5). Windows 10 21H2 AMD64 + target net9.0 + dotnet-sdk-9.0.100-preview.7.24375.12: Fail
6). Windows 10 21H2 AMD64 + target net9.0 + dotnet-sdk-9.0.100-preview.7.24379.15: Fail
### Expected Behavior

App launch successfully in Visual Studio.

### Steps To Reproduce

**Repro Steps:**
1.Open "Desktop\Source\SPOTClient\SPOT.Platform.Client.Host\SPOT.Platform.Client.Host.csproj" with Visual Studio.
2. Retarget SPOT.Platform.Client.Host to net9.0.
<TargetFramework>net9.0</TargetFramework>
3. Build the app with dotnet-sdk-9.0.100-preview.7.24379.15.
4. Run the app.

### Exceptions (if any)

**App launch failed with error:**
```
Microsoft.JSInterop.JSException: Could not find 'PlatformHelpers.initSearchInputFocus' ('PlatformHelpers' was undefined).
Error: Could not find 'PlatformHelpers.initSearchInputFocus' ('PlatformHelpers' was undefined).
    at https://localhost:5005/_framework/blazor.server.js:1:374
    at Array.forEach (<anonymous>)
    at l.findFunction (https://localhost:5005/_framework/blazor.server.js:1:342)
    at b (https://localhost:5005/_framework/blazor.server.js:1:5091)
    at https://localhost:5005/_framework/blazor.server.js:1:2884
    at new Promise (<anonymous>)
    at w.beginInvokeJSFromDotNet (https://localhost:5005/_framework/blazor.server.js:1:2847)
    at Gt._invokeClientMethod (https://localhost:5005/_framework/blazor.server.js:1:63868)
    at Gt._processIncomingData (https://localhost:5005/_framework/blazor.server.js:1:61257)
    at Gt.connection.onreceive (https://localhost:5005/_framework/blazor.server.js:1:54898)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at SPOT.Platform.Client.UI.LoginPage.OnAfterRenderAsync(Boolean firstRender) in C:\Users\test01\Desktop\Source\SPOTClient\SPOT.Platform.Client\UI\Login\LoginPage.razor.cs:line 72
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

StackTrace:
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1.MoveNext()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at SPOT.Platform.Client.UI.LoginPage.<OnAfterRenderAsync>d__7.MoveNext() in ...\SPOTClient\SPOT.Platform.Client\UI\Login\LoginPage.razor.cs:line 72
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.<GetErrorHandledTask>d__89.MoveNext()

```

### .NET Version

9.0.100-preview.7.24379.15

### Anything else?

**Dotnet Info:**
```
.NET SDK:
 Version:           9.0.100-preview.7.24379.15
 Commit:            812e813ae9
 Workload version:  9.0.100-manifests.28aae763
 MSBuild version:   17.12.0-preview-24374-02+48e81c6f1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\9.0.100-preview.7.24379.15\

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
There are no installed workloads to display.

Host:
  Version:      9.0.0-preview.7.24376.15
  Architecture: x64
  Commit:       static

.NET SDKs installed:
  3.0.103 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]
  8.0.400-preview.0.24324.5 [C:\Program Files\dotnet\sdk]
  9.0.100-preview.7.24379.15 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0-preview.7.24379.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0-preview.7.24376.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 9.0.0-preview.7.24379.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
@dotnet-actwx-bot @dotnet/compat

**Comment by Junjun-zhao** [comment]
Hi @mkArtakMSFT @javiercn, this issue is found during our Source Compat Testing for 3rd party apps that fail to launch it after retargeting the app to .net9.0 with latest .NET 9.0 build. It passed on dotnet-sdk-9.0.100-preview.5.24307.3.   Could you please look into this issue and confirm if this is a blocker issue for .NET 9 Preview7?  Thanks very much.

Note: Please kindly help to transfer to the right team if this is incorrect. Thanks.

**Comment by javiercn** [comment]
@chsienki @jaredpar this seems to be a regression in the compiler.

The attribute `type="module"` is being completely removed for some reason.

The cshtml file has `    <script src="ts/main.js" type="module"></script>` and `<script src="ts/main.js"></script>` is what I see on the wire. 

Can you take a look?

**Comment by harshit7962** [comment]
@Junjun, as discussed, the bug is reproduced if an application uses a `DynamicResource` incorrectly. 
With our changes to deal with dynamic resources to enhance performance, we have enforced the applications to crash if such practice is employed. In this specific case, a similar error was thrown at a different point in time and was consumed during the runtime and hence the crash did not occur.

This **does not stand as a blocker** for .NET 9, preview 7 release and developers can mitigate this crash on their end. Although, we are in process of providing an opt-out switch to this in rc1 release that would ease in mitigating this crash.

**Comment by javiercn** [comment]
The script attribute was fixed as part of https://github.com/dotnet/aspnetcore/pull/57170
