### ISSUE TITLE
Remove hard code casting

### ISSUE THREAD

**Issue by VincentWangWTG** [dotnet/aspnetcore#57133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I'm trying to implement a decorated `IJSRuntime` with logging added. But [this line](https://github.com/dotnet/aspnetcore/blob/06155c05af89c957de20d2c53cee0e37171b9a09/src/Components/Server/src/Circuits/CircuitFactory.cs#L46) has a hard-coded cast while `RemoteJSRuntime` is an internal class can't be inherited.

### Goal
Make it possible for `IJSRuntime` can be registered as a decorator.
### Solution
1. Remove the hard-coded casting.
2. Or, make `RemoteJSRuntime` can be inherited to enable the casting.

**Comment by javiercn** [comment]
@VincentWangWTG thanks for contacting us.

Replacing the `IJSRuntime` provided by the hosting platform is not a supported scenario.
