### ISSUE TITLE
Intermittent Error on Build

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#57147]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Intermittent-Error-on-Build/10709560)._

---
[severity:It's more difficult to complete my work]
I am getting an intermittent error on building my solution and the error states that a sepcific css file is missing but when i check it does exist on disk.  The following is the error in the Error Window of Visual Studio...

Severity	Code	Description	Project	File	Line	Suppression State	Details
Error (active)		System.InvalidOperationException: No file exists for the asset at either location 'wwwroot\css\dx-reporting-skeleton-screen.css' or 'wwwroot\css\dx-reporting-skeleton-screen.css'.
   at Microsoft.AspNetCore.StaticWebAssets.Tasks.StaticWebAsset.ComputeFingerprintAndIntegrity(String identity, String originalItemSpec)
   at Microsoft.AspNetCore.StaticWebAssets.Tasks.DefineStaticWebAssets.Execute()	Opg.Business.Web.Ui.Realty.Portal	C:\Program Files\dotnet\sdk\9.0.100-preview.5.24307.3\Sdks\Microsoft.NET.Sdk.StaticWebAssets\targets\Microsoft.NET.Sdk.StaticWebAssets.targets	597		

---
#### Feedback Bot on 7/24/2024, 07:06 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by halter73** [comment]
@javiercn FYI

**Comment by javiercn** [comment]
@halter73 this likely means the file is being added/deleted as part of the build process at the wrong time.

**Comment by ray440** [comment]
This is happening to me too.

**Comment by drmcclelland** [comment]
This started happening to me as well after .NET 9 was released.  I upgraded to Visual Studio 2022 v17.12.0, and tried compiling a .NET 8 ASP.NET MVC Core project (which started being compiled by the latest .NET 9 SDK):

```
C:\Program Files\dotnet\sdk\9.0.100\Sdks\Microsoft.NET.Sdk.StaticWebAssets\targets\Microsoft.NET.Sdk.StaticWebAssets.targets(662,5): error : System.InvalidOperationException: No file exists for the asset at either location 'wwwroot\css\multiStepIndicator.min.css' or 'wwwroot\css\multiStepIndicator.min.css'.
C:\Program Files\dotnet\sdk\9.0.100\Sdks\Microsoft.NET.Sdk.StaticWebAssets\targets\Microsoft.NET.Sdk.StaticWebAssets.targets(662,5): error :    at Microsoft.AspNetCore.StaticWebAssets.Tasks.StaticWebAsset.ComputeFingerprintAndIntegrity(String identity, String originalItemSpec)
C:\Program Files\dotnet\sdk\9.0.100\Sdks\Microsoft.NET.Sdk.StaticWebAssets\targets\Microsoft.NET.Sdk.StaticWebAssets.targets(662,5): error :    at Microsoft.AspNetCore.StaticWebAssets.Tasks.DefineStaticWebAssets.Execute()
```

Workaround:  

1. I downloaded the latest .NET 8 SDK (as of now v8.0.404)
2. Added a `global.json` at the root level of my C# solution with the following content:

```
{
  "sdk": {
    "version": "8.0.404",
    "rollForward": "latestPatch"
  }
}
```

**Comment by sandeepksharma15** [comment]
> {
>   "sdk": {
>     "version": "8.0.404",
>     "rollForward": "latestPatch"
>   }
> }

This solution works! As long as the right SDK is installed on the system :-) Thanks

**Comment by fmir864** [comment]
I can confirm this happening again after VS 17.12 update. @drmcclelland solution fixed.

**Comment by jeffdahlcorpay** [comment]
Still an issue with VS 17.12.2

**Comment by VictorioBerra** [comment]
Hitting this with VS Version 17.12.3

**Comment by tkardaridis** [comment]
Still an issue with VS 17.12.3

**Comment by Elimi81** [comment]
The issue is not resolved, still happens in VS 17.12.3. 

Started after installing .net 9 SDK as others mentioned.

**Comment by buist-sharris** [comment]
Just updated VS from 17.11.x to 17.12.3 and now running into this as well (and there's nothing intermittent about it).  The solution does not work.  "Unable to resolve the .NET SDK version as specified in the global.json located at <my project path>\global.json"

Is there a way roll back to an unbroken version so I can continue to do my job?

**Comment by buist-sharris** [comment]
Just updated VS from 17.11.x to 17.12.3 and now running into this as well (and there's nothing intermittent about it). 

The solution did not work initially. "Unable to resolve the .NET SDK version as specified in the global.json located at \global.json".   Installed the 8.0.404 sdk and it's now working.

Is there an easy way to just roll back VS to an unbroken version?  Workarounds and hacks have a tendency to get buried and lost and become like stray cats that never leave.

**Comment by Marius-du-Toit** [comment]
https://improveandrepeat.com/2024/11/how-to-fix-missing-css-js-files-at-build-time-in-visual-studio-17-12/

**Comment by ighristov** [comment]
Reproducing it intermittently with latest .NET 9 SDK 9.0.101 and I think I understood what causes it.
The issue is **not** reproducible with .NET 8 SDK - uninstalled .NET 9 SDK several times to confirm this.

In my scenario the exception is thrown during execution of a MSBuild task in a MSBuild project file. The project file is started from console - not using Visual Studio at all. The exception is thrown when bundling and minifying a bunch of .js files using the BuildBundlerMinifier package.

The exception is thrown every second time when executing the MSBuild task. So it passes one time, then fails next time, then passes again third time and so on. The problem on my end seems to be caused by the contents of the **.\wwwroot\js\bundles** folder where the bundled assets are copied after processing the BundlerMinifier.BundlerBuildTask. If the **.\wwwroot\js\bundles** folder is not empty when the build is started, the build fails when it gets to the ResolveProjectStaticWebAssets task:

````
(ResolveProjectStaticWebAssets target) ->
  C:\Program Files\dotnet\sdk\9.0.101\Sdks\Microsoft.NET.Sdk.StaticWebAssets\targets\Microsoft.NET.Sdk.StaticWebAssets.targets(662,5): error : System.InvalidOperationException: No file exists for the asset at either location 'wwwroot\js\bundles\accessibility.js' or 'wwwroot\js\bundles\accessibility.js'. [D:\Work\my-project-path.csproj] 
  C:\Program Files\dotnet\sdk\9.0.101\Sdks\Microsoft.NET.Sdk.StaticWebAssets\targets\Microsoft.NET.Sdk.StaticWebAssets.targets(662,5): error :    at Microsoft.AspNetCore.StaticWebAssets.Tasks.StaticWebAsset.ComputeFingerprintAndIntegrity(String identity, String originalItemSpec) [D:\Work\my-project-path.csproj]
C:\Program Files\dotnet\sdk\9.0.101\Sdks\Microsoft.NET.Sdk.StaticWebAssets\targets\Microsoft.NET.Sdk.StaticWebAssets.targets(662,5): error :    at Microsoft.AspNetCore.StaticWebAssets.Tasks.DefineStaticWebAssets.Execute() [D:\Work\my-project-path.csproj]
````

The strange thing is that the **.\wwwroot\js\bundles** folder gets cleaned even when the build has failed - that's why it passes the next time I started it. So in my scenario the workaround is to manually delete the folder **.\wwwroot\js\bundles** folder before starting the build.

Hope this helps.

**Comment by ltctech** [comment]
I am using webpack 5 and had the same error with bundled files.

I added a dependency on ResolveBuildRelatedStaticWebAssets by looking through the targets in the source:

https://github.com/dotnet/sdk/blob/main/src/StaticWebAssetsSdk/Targets/Microsoft.NET.Sdk.StaticWebAssets.targets

This is my csproj and now it works for the time being. It'll likely be broken when they get around to fixing this bug:
``` 
  <PropertyGroup>
    <ResolveBuildRelatedStaticWebAssetsDependsOn>
      ReleaseBuildClientApp;$(ResolveBuildRelatedStaticWebAssetsDependsOn)
    </ResolveBuildRelatedStaticWebAssetsDependsOn>
  </PropertyGroup>

  <!-- As part of release build, ensure the JS resources are freshly built in production mode -->
  <!-- Runs before compile as webpack layout template is cshtml and needs to be compiled by .NET -->
  <Target Name="ReleaseBuildClientApp" Condition=" '$(Configuration)' == 'Release' And '$(DeployOnBuild)' != 'true' ">
    <!-- Ensure Node.js is installed -->
    <Exec Command="node --version" ContinueOnError="true">
      <Output TaskParameter="ExitCode" PropertyName="ErrorCode" />
    </Exec>
    <Error Condition="'$(ErrorCode)' != '0'" Text="Node.js is required to build and run this project. To continue, please install Node.js from https://nodejs.org/, and then restart your command prompt or IDE." />
    <Message Importance="high" Text="ClientApp production build started!" />
    <Exec WorkingDirectory="$(SpaRoot)" Command="npm install" />
    <Exec WorkingDirectory="$(SpaRoot)" Command="npm run prod" />
    <Message Importance="high" Text="ClientApp production build ended!" />
  </Target>
````

**Comment by pspro0305** [comment]
Same issue exists in VS 17.12.3 using .Net SDK 9.0.101, the exception is thrown when bundling and minifying a bunch of .js files using the BuildBundlerMinifier package as @ighristov mentioned. Workaround is to manually delete the folders everytime before build.
Let me know if anyone has found the fix for this.

**Comment by IndigoHealth** [comment]
I just discovered that the problem happens consistently if I "rebuild" the solution. It does **not** happen if I just build the solution. That's a workaround of sorts...

**Comment by maxim-remizov** [comment]
The same after updating to latest VS 2022.

**Comment by onetsmr** [comment]
The same issue after updating to latest VS 2022 (17.12.3). And solution with sdk version in global.json doesn't work for me. It's ignored.

**Comment by michaeldevenney** [comment]
The solution @Scanixx linked to on the VS Developer Community site worked for me without so much as a restart.  Simply pasted that <PropertyGroup> snippet into my web project, saved it and off we went, rebuilding happily.

**Comment by rahulsaini09** [comment]
Add below line  in .csproj file    
 <PrepareForBuildDependsOn>BundleMinify;$(PrepareForBuildDependsOn)</PrepareForBuildDependsOn>
and you are all set to rebuild your project.

<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    
    <PrepareForBuildDependsOn>BundleMinify;$(PrepareForBuildDependsOn)</PrepareForBuildDependsOn>
  </PropertyGroup>

**Comment by tomtheisen** [comment]
None of the solutions in this thread helped me.  Here's the evil incantation I came up with.  Maybe it will help you.  Maybe it will not.

```xml
    <Target Name="PreResolveProjectStaticWebAssets" BeforeTargets="ResolveProjectStaticWebAssets">
        <ItemGroup>
            <StashedContent Include="@(Content)" />
            <Content Remove="@(Content)" />
        </ItemGroup>
    </Target>
    <Target Name="PostResolveProjectStaticWebAssets" AfterTargets="ResolveProjectStaticWebAssets">
        <ItemGroup>
            <Content Include="@(StashedContent)" />
        </ItemGroup>
    </Target>
```

**Comment by AntonZhernosek** [comment]
> None of the solutions in this thread helped me. Here's the evil incantation I came up with. Maybe it will help you. Maybe it will not.

Absolute legend. This actually fixes the issue for me when using msbuild typescript

**Comment by GeorgeEBeresford** [comment]
Any chance of this being fixed in visual studio itself? I don't think the ticket should be closed if the bug still remains. Thanks!

**Comment by TimPurdum** [comment]
Why is this closed? This is still happening regularly if you try to do any type of TS->JS custom compilation as part of MSBuild in .NET 9.

**Comment by jwidmer** [comment]
Why was this closed?  I have this issue with Visual Studio Professional 2022 v 17.14.9 and typescript files.  The workaround from @tomtheisen worked but I never had this issue previously with typescript files.

**Comment by mwerberacs** [comment]
Also still experiencing this issue specifically because of typescript files. @tomtheisen's solution worked but I don't want to have to rely on a hacky workaround for longer than necessary.

EDIT: I am using Rider IDE so it's not just a VS2022 issue.

**Comment by gavinfaux** [comment]
```json
{
  "sdk": {
    "version": "9.0.100",
    "rollForward": "latestPatch",
    "allowPrerelease": false
  }
}
```
9.0.109 on my machine works consistently, have not had to use `Microsoft.AspNetCore.ClientAssets`.

`"rollForward": "latestFeature"` (9.0.304) consistently fails trying to pack js asset with previous hash, with or without `Microsoft.AspNetCore.ClientAssets`

**Comment by okarpov** [comment]
> None of the solutions in this thread helped me. Here's the evil incantation I came up with. Maybe it will help you. Maybe it will not.
> 
>     <Target Name="PreResolveProjectStaticWebAssets" BeforeTargets="ResolveProjectStaticWebAssets">
>         <ItemGroup>
>             <StashedContent Include="@(Content)" />
>             <Content Remove="@(Content)" />
>         </ItemGroup>
>     </Target>
>     <Target Name="PostResolveProjectStaticWebAssets" AfterTargets="ResolveProjectStaticWebAssets">
>         <ItemGroup>
>             <Content Include="@(StashedContent)" />
>         </ItemGroup>
>     </Target>

works for me, thx!!!
