### ISSUE TITLE
SemaphoreSlim is bypassing! 

### ISSUE THREAD

**Issue by sa-es-ir** [dotnet/aspnetcore#57157]
We have a project using `SignalR` with high traffic on it, and using events OnConnect/Disconnect to cache some objects based on our logic, there is a `ConcurrentDictionary` as a cache but I can see a few logs in our app insights showing the `TryAdd` method returning `false` as the key already exists. 

It caused some dysfunctionality in our web but after restarting the backend everything became normal.
Here is the code similar to our code base:

```csharp
public class SingletonService
{
    private readonly SemaphoreSlim _semaphore = new SemaphoreSlim(1, 1);
    private readonly CancellationTokenSource _cancellationTokenSource = new();
    private readonly ConcurrentDictionary<int, string> _cache = new();

    public async Task<string> OnConnectAsync(ParamModel model)
    {
        if (_cache.TryGetValue(model.Key, out var value))
        {
            return value;
        }

        await _semaphore.WaitAsync(_cancellationTokenSource.Token);

        try
        {
            if (_cache.TryGetValue(model.Key, out var inValue))
            {
                return inValue;
            }

            //doing some work
            await Task.Delay(500);

            var added = _cache.TryAdd(model.Key, model.Value);

            if (!added) //<------ We saw this 4 times in 30 days app running
                Console.WriteLine($"------Failed to add key: {model.Key}");

            return model.Value;
        }
        finally
        {
            if (!_cancellationTokenSource.IsCancellationRequested)
                _semaphore.Release();
        }
    }

    public async Task OnDisconnect(ParamModel model)
    {
        if (_cache.TryGetValue(model.Key, out var value))
        {
            if (_cache.TryRemove(model.Key, out var _))
            {
                //doing some work
                await Task.Delay(100);
            }
        }
    }
}
```
Those methods are calling in the SignalR hub for connect/disconnect events. The `model.Key` has only up to 20 unique values.
What can be the issue? 
Is it related to context capturing, so before finishing `await Task.Delay(500)` the Key changed to an existing key?
Or is SingalR triggering `OnConnect` event 2 times at the same time?

I couldn't reproduce the issue.

**Comment by slang25** [comment]
If the `_semaphore` field is intended to be a lock that guards the `_cache` collection, then you should also use the same guard mechanism in the `OnDisconnect` method, along with the `_cache.TryGetValue` before and after taking the lock (same pattern as you have in `OnConnectAsync`. Otherwise nothing prevents an `OnDisconnect` from happening midway through an `OnConnectAsync` which breaks your assumptions.

It's odd that you are using a `ConcurrentDictionary<TKey, TValue>` here, as you are adding synchronization around it. It's more common that you put locks around synchronous data structures, or are trying to synchronize between multiple resources.

If this is representative of your code, you can just trust in the concurrent collections thread safe behaviour.

**Comment by sa-es-ir** [comment]
Thanks @slang25, Although the point is true about using the semaphore in `OnDisconnect` I'm not sure can help to solve the main issue, because it is removing items from the dictionary. My concern is on `TryAdd` method which is returning `false`  the only reason I can think of is the key already exists.

This part of the codebase was written a long time ago and because of this issue I was assigned to fix it. Assuming with or without using semaphore that `TryAdd` can happen.

My ideas can be true:
- Is it related to context capturing, so before finishing await Task.Delay(500) the Key changed to an existing key?
- Or is SingalR triggering OnConnect event 2 times at the same time?

**Comment by sa-es-ir** [comment]
Sorry my bad, I think there is one more thing I didn't see:
```csharp
if (_cache.TryGetValue(model.Key, out var inValue) && inValue.IsConnected)
{
	return inValue;
}
```
So there is a chance that the saved value is not connected and skipped. I'm going to use `AddOrUpdate` instead of `TryAdd`.

Also, I should use Semaphore in the Disconnected part as well because there we're setting `IsConnected = false`.

**Comment by slang25** [comment]
@sa-es-ir ah good, cause you had me stumped there 😅 glad you got to the bottom of it
