### ISSUE TITLE
NavLink blazor component does not add CSS isolation attribute to anchor

### ISSUE THREAD

**Issue by moiseiv** [dotnet/aspnetcore#57160]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using the NavLink, if you want to style the `<a>` element, you cannot target it because Blazor will automatically add the CSS isolation attribute to your selectors, and the `<a>` element doesn't have that attribute. Here is an example:

If I create a new Blazor app with the Account UI pages, the ManageNavMenu.razor looks something like this:

```
<ul class="nav nav-pills flex-column">
    <li class="nav-item">
        <NavLink class="nav-link" href="Account/Manage" Match="NavLinkMatch.All">Profile</NavLink>
    </li>
    <li class="nav-item">
        <NavLink class="nav-link" href="Account/Manage/Email">Email</NavLink>
    </li>
    <li class="nav-item">
        <NavLink class="nav-link" href="Account/Manage/ChangePassword">@Localizer["Password"]</NavLink>
    </li>
    <li class="nav-item">
        <NavLink class="nav-link" href="Account/Manage/TwoFactorAuthentication">Two-factor authentication</NavLink>
    </li>
    <li class="nav-item">
        <NavLink class="nav-link" href="Account/Manage/PersonalData">Personal data</NavLink>
    </li>
</ul>
```

if I create a ManageNavMenu.razor.css and add the following

```
.nav-pills .nav-link.active {
    background-color: #1ed663;
    color: black;
}
```
I expect the active nav-item to be green, but because the generated html is:

```
<ul class="nav nav-pills flex-column" b-fe370wzjbd="">
    <li class="nav-item" b-fe370wzjbd=""><a href="Account/Manage" class="nav-link active"
            aria-current="page">Profile</a></li>
    <li class="nav-item" b-fe370wzjbd=""><a href="Account/Manage/Email"
            class="nav-link">Email</a></li>
    <li class="nav-item" b-fe370wzjbd=""><a href="Account/Manage/ChangePassword"
            class="nav-link">Passwort</a></li>
    <li class="nav-item" b-fe370wzjbd=""><a href="Account/Manage/TwoFactorAuthentication"
            class="nav-link">Two-factor authentication</a></li>
    <li class="nav-item" b-fe370wzjbd=""><a href="Account/Manage/PersonalData"
            class="nav-link">Personal data</a></li>
</ul>
```

and the CSS annotated by Blazor looks something like this:

```
.nav-link.active [b-fe370wzjbd] {
    background-color: #1ed663 !important;
    color: black;
}
```

I am not able to target the `<a>` element because it doesn't have the custom attribute

**Comment by javiercn** [comment]
@moiseiv thanks for contacting us.

`scoped css` works at the file level, not at the element level. The `a` element is inside the `NavLink` component, hence why the attribute doesn't get applied to it. If it was, then it would break the isolation rules for the `NavLink` component, defeating the whole purpose of the feature.

What you likely want to do is use the `::deep` pseudo-selector to create a rule like `[parent-scope] a { ...`. See https://learn.microsoft.com/en-us/aspnet/core/blazor/components/css-isolation?view=aspnetcore-8.0#child-component-support for details.

**Comment by moiseiv** [comment]
Many thanks for the response and suggestion!
