### ISSUE TITLE
_blazor/initializer 404 (not found)

### ISSUE THREAD

**Issue by carlo-setldpay** [dotnet/aspnetcore#57176]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello, when setting the render mode to `new InteractiveServerRenderMode(false)` and adding RequireAuthorization() to MapRazorComponents, the site encounters a 404 Not Found error for the /_blazor/initializer when hitting [AllowAnonymous] pages.

### Steps To Reproduce

1. Open attached project
2. Run project
3. Hit `samplepage1`

### .NET Version

8.0.303

### Anything else?

![image](https://github.com/user-attachments/assets/8a5c939b-36a2-48c0-b57f-1b87153ad4e9)

![image](https://github.com/user-attachments/assets/4f045f77-256a-4d2c-8461-291e1d920b4b)

**Comment by MackinnonBuck** [comment]
Thanks for reaching out, @carlo-setldpay. We appreciate the time you took to create the repro - would you please put the code in a GitHub repo? We can't open zip files here. Thank you!

**Comment by carlo-setldpay** [comment]
Hello, I have put the code in this [repository](https://github.com/carlo-setldpay/blazor-initializer-404). Thanks!

**Comment by javiercn** [comment]
@carlo-setldpay seems like you forgot to push after the initial commit?

**Comment by carlo-setldpay** [comment]
Hello @javiercn, I'm sorry I didnt quite understand what I forgot to push. Is it okay if you can clarify what I forgot to push? Thanks.

**Comment by carlo-setldpay** [comment]
I made a mistake in the steps to reproduce, the page previously inputted was incorrect, I have now fixed it.

**Comment by javiercn** [comment]
@carlo-setldpay thanks for the details.

 I see now what's happening. Your cookie is issuing a Challenge and resulting in a 404. You need to add AllowAnonymous to that endpoint.

```csharp
var components = app.MapRazorComponents<App>()
    .AddInteractiveServerRenderMode()
    .RequireAuthorization();

components.Add(e => {
    if(e is RouteEndpointBuilder rb)
    {
        if(rb.RoutePattern!.RawText!.Contains("_blazor")){
            rb.Metadata.Add(new AllowAnonymousAttribute());
        }
    }
});
```

**Comment by carlo-setldpay** [comment]
I see, @javiercn, thanks for the explaination and answer. My knowledge in blazor is really lacking, thanks for the guidance, its really helpful.
