### ISSUE TITLE
Wrong http status code if CreatedResult in Put methods

### ISSUE THREAD

**Issue by Ivanoyashi** [dotnet/aspnetcore#57189]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

If write Put method (mark as [HttpPut]) and return CreatedResult without parameters, we will give HTTP status code 204 NoContent - wrong status code
But if return CreatedResult with parameters, by example Created(string.Empty, string.Empty), will be given 201 Created - correct

**Workaround**: use Created with parameters, if need status 201.

Example code

```
public class BugController : ControllerBase
{
    // returning 204 NoContent
    [HttpPut(nameof(Wrong))]
    [ProducesResponseType(StatusCodes.Status201Created)]
    public IActionResult Wrong() => Created();

    // returning 201 Created
    [HttpPut(nameof(Workaround))]
    [ProducesResponseType(StatusCodes.Status201Created)]
    public IActionResult Workaround() => Created(string.Empty, string.Empty);
}
```

### Expected Behavior

Must return Http status code 201 Created, not 204 NoContent

```
[HttpPut(nameof(Wrong))]
public IActionResult Wrong() => Created();
```

### Steps To Reproduce

1. Create Web-API ASP.Net Core project
2. Write any put method with returning value IActionResult and return Created()

### .NET Version

8.0.303

### Anything else?

OS: Windows 10
IDE: VS 2022 17.10.5
ASP.NET Core: 8.0.7

**Comment by feiyun0112** [comment]
9.0 fixed

https://github.com/dotnet/aspnetcore/commit/2bcfbd783a1e421840b2a638ff193ebb527c184e

**Comment by captainsafia** [comment]
Thanks for chiming in, @feiyun0112! Yes, this was resolved in 9.0 Preview 6.

**Comment by alesdvorakcz** [comment]
Do you plan to fix this bug in 8.x.x as well?

**Comment by captainsafia** [comment]
@alesdvorakcz There are no plans to backport this at the moment given the low severity and the fact that there are workarounds available.
