### ISSUE TITLE
Docker build targets included with default Visual Studio templates don't work because HTTPS is half set up

### ISSUE THREAD

**Issue by catmanjan** [dotnet/aspnetcore#57181]
I couldn't find a Visual Studio Github to report this, but basically the out of the box dotnet templates that most dotnet developers will be using as their first foray into Docker do not work.

The dotnet templates host web services over HTTPS and as such the docker launch target is configured to use SSL, however there is no automatic set up/default creation of development certificates so debugging docker will never work.

If you target something like IIS Express or Kestrel you will be prompted to generate development certificates and Visual Studio will do the registration for you.

**Comment by lbussell** [comment]
Hi @catmanjan, the repo to file issues about the Visual Studio Containers tooling is https://github.com/microsoft/dockertools.

I am interested in your scenario though. Are you able to try out debugging using any of the samples in this repo? They are similar to the VS built-in templates. If there's something we're missing, we'd like to know. https://github.com/dotnet/dotnet-docker/tree/main/samples/aspnetapp

I also wonder if Container Fast Mode debugging in Visual Studio would make a difference here: https://aka.ms/containerfastmode

**Comment by catmanjan** [comment]
@lbussell I think the main reason to use Visual Studio is the debug tools, but I don't see any debug instructions here - at the moment with Kestrel/IIS Express the developer just needs to press the big green debug button and it all just works, but with Docker it will only work if you disable SSL :(

**Comment by camrionnvmff** [comment]
The issue of incomplete HTTPS configuration in the template can be resolved by generating and trusting the development certificate
dotnet dev-certs https --trust
Then, export the certificate:

dotnet dev-certs https -ep ${HOME}/.aspnet/https/aspnetapp.pfx -p yourpassword
In Dockerfile, add certificate related configurations:

COPY ${HOME}/.aspnet/https/aspnetapp.pfx /https/aspnetapp.pfx
ENV ASPNETCORE_Kestrel__Certificates__Default__Password="yourpassword"
ENV ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
Ensure that the Docker configuration in launchSettings. json includes HTTPS:

"Docker": {
"commandName": "Docker",
"launchBrowser": true,
"httpPort": 5000,
"useSSL": true,
"sslPort": 5001
}
In this way, your Docker container can use HTTPS and debug normally.

If you still have HTTPS related issues, you can try using Servbay, which is similar to Docker

**Comment by catmanjan** [comment]
@camrionnvmff I'm sure there is a solution, but it should "just work" like the other build targets... either disable SSL by default or script all these extra steps so they automatically happen...

Also modifying the dockerfile as your suggest is not ideal because it has a password in it, and you will now have to maintain a debug and a production dockerfile

**Comment by amcasey** [comment]
@catmanjan Can you please follow up on https://github.com/microsoft/dockertools as @lbussell suggested?  I'd transfer it for you, but GitHub doesn't support transfers between orgs (i.e. dotnet to microsoft).
