### ISSUE TITLE
Blazor 8 Cannot Handle a Root Path Variable

### ISSUE THREAD

**Issue by GregFinzer** [dotnet/aspnetcore#57192]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Blazor 8 cannot handle variables in a root path and begins serving static files (CSS and JavaScript) as garbage.  Root variable routing works in Blazor 7.

### Expected Behavior

Blazor 8 should not serve static files as garbage when there are root path variables.

Example:
`@page "/{mylocation}/{mypageName}"`

### Steps To Reproduce

I have created a simple project based on the Visual Studio 2022 sample files.  See the readme
https://github.com/GregFinzer/Blazor8RootPathVariable

From the readme:

Steps to reproduce the error:
1.  In Visual Studio 2022, create a Blazor 8 Web App.
2.  Choosing Interactive Render Mode of Server.  
3.  Choose Interactivity location of Per page/component.
4.  Include sample pages
5.  After the solution is created, open App.razor
6.  Change HeadOutlet to this:

    ```html
    <HeadOutlet @rendermode="RenderMode.InteractiveServer" />
    ```
7.  Change Routes to this:

    ```html 
    <Routes @rendermode="RenderMode.InteractiveServer" />
    ```

8.  Change Home.razor to this:

```html
@page "/"
@page "/{mylocation}/{mypageName}"

<PageTitle>Home</PageTitle>

<h1>Hello, world!</h1>

Welcome to your new app.

@((MarkupString)BodyContent)

@code {
    [Parameter] public string? mylocation { get; set; }
    [Parameter] public string? mypageName { get; set; }
    private string BodyContent = "";

    protected override void OnInitialized()
    {
        if (mylocation == null)
        {
            mylocation = "National";
        }

        if (mypageName == null)
        {
            mypageName = "Home";
        }

        BodyContent = $"<p>Location: {mylocation}</p><p>Page Name: {mypageName}</p>";
    }
}
```
9. In the wwwroot folder, create a scripts folder.
10.  Create a JavaScript file called HelloWorldClass.js in the scripts folder with this content:
```javascript
window.HelloWorldClass = {
    HelloWorld: function () {
        alert('Hello World');
    }
}
```
11.  Run the solution
12.  Do a Ctrl-F5 in the Browser to do a hard refresh
13.  View the error in the console

### Exceptions (if any)

In the console, errors will be displayed like:
HelloWorldClass.js:1 Uncaught SyntaxError: Unexpected token '<'

### .NET Version

8.0.303

### Anything else?

Visual Studio 2022 Version 17.10.5

**Comment by javiercn** [comment]
@GregFinzer thanks for contacting us.

Your route is capturing file paths. You need to use a `:nonfile` constraint as in `"/{mylocation}/{mypageName:nonfile}"` or explicitly call

```csharp
app.UseStaticFiles();
app.UseRouting();
```
in your startup code.
