### ISSUE TITLE
Doc comments: Explain UserName is a unique login identity and different from User.Name

### ISSUE THREAD

**Issue by ciel** [dotnet/aspnetcore#5721]
I spent a few hours trying to hunt down what was going wrong with my site - as no matter what I tried, when I would create a new user, their `Name` field continued to come up lowercase ('Normalized').

Eventually I traced it back to the `UserManager<T>` and how it calls for `SetNormalizedUserNameAsync`, etc, on the implementation of `IUserStore<T>`.

The problem here is one of interpretation. Obviously, now that I realize what is going on, I just update `SetNormalizedUserNameAsync`, `GetNormalizedUserNameAsync`, `SetUserName`, `GetUserName`, etc, to be the field I'm personally equating to a unique login identity.

But this naming convention, I feel, could be clearer. I think the intent is that it's supposed to normalize whatever field you're using as a unique identifier (`username`). I actually translated it as a literal `User.Name` - a field where the user's name would be stored.

It might be a bit clearer with a verbose `SetNormalizedUniqueIdentifierAsync` or something that makes it pretty apparent it's used for that purpose. 

Even the documentation isn't really obvious about its intent; Here is the actual docs for `SetNormalizedUserNameAsync`

```
/// <summary>
/// Sets the given normalized name for the specified <paramref name="user"/>.
/// </summary>
/// <param name="user">The user whose name should be set.</param>
/// <param name="normalizedName">The normalized name to set.</param>
/// <param name="cancellationToken">The <see cref="CancellationToken"/> used to propagate notifications that the operation should be canceled.</param>
/// <returns>The <see cref="Task"/> that represents the asynchronous operation.</returns>
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're closing this issue as there was no community involvement here for quite a while now.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
