### ISSUE TITLE
Trailing comma in launchSettings.json breaks `dotnet watch`

### ISSUE THREAD

**Issue by mikeball** [dotnet/aspnetcore#57214]
Trailing commas in `launchSettings.json` cause `dotnet watch` to NOT use a profile. In our case required environment variables where not set with profile specific values.

_Originally seen by @ghost in https://github.com/dotnet/aspnetcore/issues/44363#issuecomment-1770393353_

**Comment by martincostello** [comment]
Duplicate of https://github.com/dotnet/sdk/issues/35558, which is fixed for .NET 9.
