### ISSUE TITLE
Consuming scoped service from App.razor

### ISSUE THREAD

**Issue by lvde0** [dotnet/aspnetcore#57233]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I understand that App.razor is always statically rendered and all injected scoped services will be instantiated twice (See https://learn.microsoft.com/en-us/aspnet/core/blazor/components/render-modes?view=aspnetcore-8.0#service-injection-via-a-top-level-imports-file-_importsrazor). However, in [this example](https://learn.microsoft.com/en-us/aspnet/core/blazor/security/server/additional-scenarios?view=aspnetcore-7.0#pass-tokens-to-a-server-side-blazor-app) it mentions the possibility to initialize the scoped service from the `OnInitializedAsync` of App.razor:

> An alternative to assigning the initial state to the TokenProvider in the preceding example is to copy the data into a scoped service within [OnInitializedAsync](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.componentbase.oninitializedasync) for use across the app.

I am wondering if it the documentation is just misleading here or there actually is a way to get a single instance of a scoped service from App.razor?

### .NET Version

8.0.302

**Comment by MackinnonBuck** [comment]
Thanks for reaching out. Please note that the example you're looking is for .NET 7, and that suggestion won't always work for Blazor Web Apps (the pattern introduced in .NET 8). Please take a look at https://learn.microsoft.com/aspnet/core/blazor/security/server/additional-scenarios?view=aspnetcore-9.0#pass-tokens-to-a-server-side-blazor-app for up-to-date information about how to achieve this.
