### ISSUE TITLE
Placing Interactive Content Inside SectionContent component disables its interactive event handlers

### ISSUE THREAD

**Issue by htmlsplash** [dotnet/aspnetcore#57238]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This bug applies to interactive server render mode, .net 8 Blazor.
When you place some interactive code inside a section content, the interactive handlers will not be invoked (you lose all interactivity). By moving the interactive code logic outside the section content component works just fine.

```razor
<SectionContent SectionName="sidebar">
	@if (_toggleSearchMode)
	{
		<button @onclick=ToggleSearchModeUI type="button" class="btn btn-secondary">
			<span>Advanced Search</span>
			
		</button>
	}
	else
	{
		<button @onclick=ToggleSearchModeUI type="button" class="btn btn-secondary">
			<span>Basic Search</span>
			
		</button>
	}

</SectionContent>

@code {
    private bool _toggleSearchMode = true;
    
    private void ToggleSearchModeUI()
    {
	    _toggleSearchMode = !_toggleSearchMode;
    }
}
```

### Expected Behavior

The event handler should fire.

### Steps To Reproduce

Here's link to the repo:

https://github.com/htmlsplash/BlazorWebAppTest

Run the project, select "Component Inside Section Test" link. A button will appear in the nav bar. When you click the button, a different button should render, but it doesn't.  If you edit the "Components/Pages/ComponentInsideSectionTest.razor", and move the code out of the section, everything works as expected.

### .NET Version

.net 8

**Comment by MackinnonBuck** [comment]
Thanks for reaching out, @htmlsplash.

The reason event handlers are not getting invoked is because the render fragment defined in a `<SectionContent>` inherits the render mode from the corresponding `<SectionOutlet>`. Since the `<SectionOutlet>` is rendered statically, so is the content inside the `<SectionContent>`.

Closing this as by-design.
