### ISSUE TITLE
CancellationTokenSource potential leaks in SignalR HubConnection

### ISSUE THREAD

**Issue by leeriorio** [dotnet/aspnetcore#57232]
### Describe the bug

there is `CancellationTokenSource` type variable in src/SignalR/clients/csharp/Client.Core/src/HubConnection.cs

https://github.com/dotnet/aspnetcore/blob/257d69079e0f7fc84e3f6cd5047272d7f79b4d66/src/SignalR/clients/csharp/Client.Core/src/HubConnection.cs#L1599-L1600

and in `finally` block of this private method only Cancel() method calls

https://github.com/dotnet/aspnetcore/blob/257d69079e0f7fc84e3f6cd5047272d7f79b4d66/src/SignalR/clients/csharp/Client.Core/src/HubConnection.cs#L1704

How about to Dispose this CTS object in finally block or add `using` construction in its declaration to eliminate potential memory leaks?

Found by Linux Verification Center (linuxtesting.org) with SVACE.

**Comment by BrennanConroy** [comment]
Sure, we should dispose as a good practice especially since it should be as easy as adding it after `Cancel()`.

In this specific case there wouldn't be a leak because `Cancel()` disposes the internal timer and the native objects in the `ManualResetEvent` are wrapped in `SafeHandle`s so are finalized. (It'd also be a super slow leak if there was one since we create one of these per connection)

**Comment by AshkanAfsharpour** [comment]
Hi @BrennanConroy, @leeriorio, and team,

I'd like to contribute to resolving this issue regarding the potential memory leak with the `CancellationTokenSource` in `HubConnection.cs`. As discussed, I plan to update the code to ensure that the `CancellationTokenSource` is properly disposed of after calling `Cancel()`.

My approach will involve:
1. Adding a `Dispose()` call after `Cancel()` in the `finally` block to explicitly clean up the `CancellationTokenSource`.
2. Alternatively, I could refactor the code using a `using` statement around the `CancellationTokenSource` to ensure automatic disposal, which would be an even safer way to handle this.

Before I proceed, I wanted to check if anyone else has started working on this or if you have any preferred approach or further suggestions on how to handle this.

Thanks, and I look forward to contributing!

**Comment by BrennanConroy** [comment]
I'd probably go with the `using`.
