### ISSUE TITLE
WithHttpLogging configuration is not respected

### ISSUE THREAD

**Issue by azan-n** [dotnet/aspnetcore#57244]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The following health check map still logs to the console based on the default configuration despite the overridden `WithHttpLogging`.

```
app.MapHealthChecks("/v3/status").WithHttpLogging(Microsoft.AspNetCore.HttpLogging.HttpLoggingFields.None);
```

### Expected Behavior

With the HttpLoggingFields set to `HttpLoggingFields.None`, based on the [precedence](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/http-logging/?view=aspnetcore-8.0#logging-configuration-order-of-precedence), the endpoint should not log.

### .NET Version

8.0.301

**Comment by BrennanConroy** [comment]
Can you show your middleware order?

**Comment by azan-n** [comment]
> Can you show your middleware order?

I've redacted some parts but this is most of it.


```cs
var app = builder.Build();
app.UseHttpLogging();

// some custom headers here

app.UseRouting();
app.UseAuthentication();
app.UseAuthorization();
app.MapControllers().RequireAuthorization(PolicyName.TenantContextRequirementPolicy);

app.MapHealthChecks("/v3/status", new Microsoft.AspNetCore.Diagnostics.HealthChecks.HealthCheckOptions
{
    ResponseWriter = ...
}).WithHttpLogging(Microsoft.AspNetCore.HttpLogging.HttpLoggingFields.None);

app.MapHealthChecks("/healthz", new Microsoft.AspNetCore.Diagnostics.HealthChecks.HealthCheckOptions
{
    ResponseWriter = ...
}).WithHttpLogging(Microsoft.AspNetCore.HttpLogging.HttpLoggingFields.None);

app.Run();
```

**Comment by BrennanConroy** [comment]
Put UseHttpLogging after UseRouting.

**Comment by azan-n** [comment]
That does it. Thanks!
