### ISSUE TITLE
GroupName is applied to all endpoints when it shouldn't be.

### ISSUE THREAD

**Issue by EdLichtman** [dotnet/aspnetcore#57241]
### Describe the bug
When using WebApplication.MapGet(...).WithGroupName("MY_GROUP"), odd behaviors occur.

On an older version of my package libraries, I was able to produce the behavior in which adding a GroupName to one endpoint in a group adds the GroupName to _all_ of the endpoints in the group, however, that seems to have been fixed as of:
* Microsoft.AspNetCore.OpenApi@8.0.7
* Asp.Versioning.Http@8.1.0
* Asp.Versioning.Mvc.ApiExplorer@8.1.0
* Swashbuckle.AspNetCore@6.7.0

There is still a reproducible bug when you mix and match groups and non-groups with versioning -- If you have a group with a versionSet, and you give one single endpoint of that VersionSet a group name, then all ungrouped and/or unversioned endpoints have the same group name.

For example, with the following code: 
```csharp
var versionSet = 
    app
        .NewApiVersionSet()
        .HasApiVersion(1.0)
        .HasApiVersion(1.1)
        .ReportApiVersions()
        .Build();

app.MapGet(string.Empty, () => "Hello World");
var group = app.MapGroup("api/v{version:apiVersion}");
group.MapGet(string.Empty, () => "Hello World!").WithApiVersionSet(versionSet).MapToApiVersion(1.0);
group.MapGet(string.Empty, () => "Hello World!").WithGroupName("highlander").WithApiVersionSet(versionSet).MapToApiVersion(1.0);
```
one would expect that there is only one endpoint part of the highlander group, but when you look at the swagger.json that is produced:

```json
{
    "openapi": "3.0.1",
    "info": {
        "title": "Hi",
        "version": "1.0"
    },
    "paths": {
        "/api/v1": {
            "get": {
                "tags": [
                    "SwaggerBug"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "text/plain": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/": {
            "get": {
                "tags": [
                    "SwaggerBug"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "text/plain": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {}
}
```

There is more than one path.

### To Reproduce
I've added an example of the C# code in a file named "Example.txt". Create a new project with the following csproj, and stick that C# in your program.cs, and you should be able to reproduce

```csharp
<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <InvariantGlobalization>true</InvariantGlobalization>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Asp.Versioning.Http" Version="8.1.0" />
        <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="8.1.0" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.7" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.7.0" />
    </ItemGroup>

</Project>
```
[Example.txt](https://github.com/user-attachments/files/16553233/Example.txt)

**Comment by captainsafia** [comment]
@EdLichtman Thanks for filing this issue! I think I can explain what might be going on here...

> There is still a reproducible bug when you mix and match groups and non-groups with versioning -- If you have a group with a versionSet, and you give one single endpoint of that VersionSet a group name, then all ungrouped and/or unversioned endpoints have the same group name.

The issue is with the default inclusion rules that are used to map endpoints in groups to documents. By default, endpoints that do not have an explicit group set, like your `app.MapGet()` endpoint above, will appear as part of all the groups. We can't exclude an endpoint from the OpenAPI document because it explicitly has no groups so the default behavior is to include it everywhere.

You can resolve the issue by adding a group name to the ungrouped route:

```diff
- app.MapGet(string.Empty, () => "Hello World");
+ app.MapGet(string.Empty, () => "Hello World").WithGroupName("Ungrouped"); 
```

Also, I'm not a total expert on the Asp.Versioning library but I believe there is a subtle distinction between its concept of versioned groups and the "group name" concept that exists in endpoint metadata.
