### ISSUE TITLE
Blazor's startup scripts (<namespace>.lib.module.js) should be loaded by the order of dependencies

### ISSUE THREAD

**Issue by datvm** [dotnet/aspnetcore#57278]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Right now if I have two library `MyLibrary` and `MyLibrary.Optional` (depends on `MyLibrary`) and each has their own startup script:

```
// js/common.js put in a few prototype functions and global variables like this:
globalThis.variableFromCommon ??= { } // ... 

// MyLibrary.lib.module.js
import "./js/common.js";

// MyLibrary.Optional.lib.module.js
variableFromCommon.doSomething();
```

Unfortunately when a project `Demo` that refers to `MyLibrary.Optional`, the load order does not seem to be consistent and sometimes I would receive error because `variableFromCommon` is not available. In the DevTools window, `MyLibrary.Optional.lib.module.js` is requested first all the time as well.

![image](https://github.com/user-attachments/assets/aa419817-d19b-438a-971c-7587977759e0)

In fact, I am convinced maybe the parents' scripts are always loaded **after** the depended scripts.

### Describe the solution you'd like

The initialization script should load by the order of their dependencies (`MyLibrary.lib.module.js` then `MyLibrary.Optional.lib.module.js`).

**Comment by javiercn** [comment]
@datvm thanks for contacting us.

This is not something we ever plan to do and its explicitly out of scope of the design of initializers. 

JavaScript already has a native mechanism for this with the `import` statement, if you have a dependency, you should import it yourself, not expect the framework to do it for you.
