### ISSUE TITLE
[Blazor] rendermode="InteractiveAuto" cleared injection of AuthenticationStateProvider

### ISSUE THREAD

**Issue by AlexNek** [dotnet/aspnetcore#57274]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am working on a .NET 8.0 Blazor project utilizing the "auto" render mode,
with cookie-based authentication.
[Demo repo](https://github.com/ANTestGit/BlazorAuthenticationTest)
When using a client-side component with the render mode `InteractiveAuto` on the server side:

```html
<UserInfo @rendermode="InteractiveAuto"/>
```
And injecting AuthenticationStateProvider within the component:

```csharp
@inject AuthenticationStateProvider AuthStateProvider
```
You might encounter a peculiar issue. Upon logging in or logging out, the following error appears:

```txt
Error: One or more errors occurred. (Cannot provide a value for property 'AuthStateProvider' on type 'BlazorAuthenticationTest.Client.Components.UserInfo'. There is no registered service of type 'Microsoft.AspNetCore.Components.Authorization.AuthenticationStateProvider'.)
    at Jn (marshal-to-js.ts:349:18)
    at Tl (marshal-to-js.ts:306:28)
    at 00b21cf6:0x1fad7
    at 00b21cf6:0x1bf9f
    at 00b21cf6:0xf16c
    at 00b21cf6:0x1e7f1
    at 00b21cf6:0x1efe7
    at 00b21cf6:0xcfbc
    at 00b21cf6:0x44213
    at e.<computed> (cwraps.ts:338:24)
```

Interestingly, if you clear all cookies, the error disappears. In some cases, clearing the solution and rebuilding the project may also resolve the issue.

### Expected Behavior

Independent of render mode I must always have default `AuthenticationStateProvider ` injected

### Steps To Reproduce

[Demo repo](https://github.com/ANTestGit/BlazorAuthenticationTest)
Login/ Logout

### Exceptions (if any)

Error: One or more errors occurred. (Cannot provide a value for property 'AuthStateProvider' on type 'BlazorAuthenticationTest.Client.Components.UserInfo'. There is no registered service of type 'Microsoft.AspNetCore.Components.Authorization.AuthenticationStateProvider'.)
    at Jn (marshal-to-js.ts:349:18)
    at Tl (marshal-to-js.ts:306:28)
    at 00b21cf6:0x1fad7
    at 00b21cf6:0x1bf9f
    at 00b21cf6:0xf16c
    at 00b21cf6:0x1e7f1
    at 00b21cf6:0x1efe7
    at 00b21cf6:0xcfbc
    at 00b21cf6:0x44213
    at e.<computed> (cwraps.ts:338:24)

### .NET Version

8.0

**Comment by javiercn** [comment]
@AlexNek thanks for contacting us.

When running in auto mode you have 2 separate processes, one for server and one for webassembly. They are completely independent, and you are responsible for flowing any necessary information between the two.

Your app will potentially execute in three different scopes:
* SSR when the app prerenders.
* Server Interactive: The first time the interactive component renders on the server.
* Webassembly Interactive: The first time the interactive component renders on webassembly.

These are three different DI scopes and 2 different processes (server/browser) and for all intents and purposes, three different instantiations of most services.

You need to handle the setup and transfer any information between any of the three scopes. Our implementation on the template for auth shows this pattern.

**Comment by AlexNek** [comment]
Thanks for the quick answer
>Our implementation on the template for auth shows this pattern.

It uses MS Identity. Do you have any additional documentation?

**Comment by AlexNek** [comment]
@MackinnonBuck thanks for notice. It was my first try which is not working. 
Look like that I must copy `internal sealed class PersistingRevalidatingAuthenticationStateProvider : RevalidatingServerAuthenticationStateProvider` for server and `internal class PersistentAuthenticationStateProvider : AuthenticationStateProvider` for client /with service registering/ from MS Identity template?

My problem is that all user management is implemented via external API with JWT tokens. So I decided to use cookie identification along with Blazor auto render mode per component.

I try to adapt PersistingRevalidatingAuthenticationStateProvider to cookie authentication:
```csharp
protected override async Task<bool> ValidateAuthenticationStateAsync(
    AuthenticationState authenticationState, CancellationToken cancellationToken)
{
    // Extract the ClaimsPrincipal from the authentication state
    var user = authenticationState.User;

    // Check if the user is authenticated
    if (user.Identity is { IsAuthenticated: false })
    {
        return false; // User is not authenticated, so the state is invalid
    }

    // Optionally, validate specific claims
    var userIdClaim = user.FindFirst(ClaimTypes.NameIdentifier)?.Value;
    if (string.IsNullOrEmpty(userIdClaim))
    {
        return false; // No user ID claim found, invalid state
    }

    // Get the user manager from a new scope to ensure it fetches fresh data
    //await using var scope = scopeFactory.CreateAsyncScope();
    //var userManager = scope.ServiceProvider.GetRequiredService<UserManager<ApplicationUser>>();
    //return await ValidateSecurityStampAsync(userManager, authenticationState.User);
    // TODO check user state, possible check tokens
    return true;
}
```

And the next problem JWT update. Try to use server middleware but again problem with cookie update on client side.

Are you planning a full authentication/authorization library for non-MS identity?

**Comment by javiercn** [comment]
@AlexNek In 9.0 I believe we ship an AuthenticationStateProvider for webassembly that handles persisting the authentication state to the client.

The AuthenticationStateProvider is completely independent of the the Authentication mechanism on the server. Its only "job" is to handle the ClaimsPrincipal.

If you are using cookie authentication there's nothing that should happen client-side, other than transferring the claims principal from the server to the client, either via persisted component state or by hitting an HTTP endpoint from the client to retrieve the data.

There's no magical mechanism for updating the identity on the client unless you create your own via an HTTP endpoint.

**Comment by AlexNek** [comment]
@javiercn Thanks for the explanation

>There's no magical mechanism for updating the identity on the client unless you create your own via an HTTP endpoint.
Why this lines on server working fine for client?
```csharp
await httpContext.SignInAsync(
     CookieAuthenticationDefaults.AuthenticationScheme,
     claimsPrincipal,
     authProperties);

// Force a full reload to apply the cookie
NavigationManager.NavigateTo("/secure-page", forceLoad: true);
```

The problem is only when I call the client component that needs `_email = user.FindFirst(ClaimTypes.Email)?.Value;` which has <UserComponent @rendermode="InteractiveAuto"/>. And I need to use @inject AuthenticationStateProvider AuthStateProvider.
Many other non-interactive components on the client side used AuthenticationStateProvider without any problem.

Or are you just talking for the Interactive mode?

**Comment by javiercn** [comment]
@AlexNek what do you mean by client?

That won't work when running the component on webassembly.

**Comment by AlexNek** [comment]
@javiercn I have Blazor .NET 8.0 with individual rendering mode by components. So I have components on server side and on client side. In addition, I use Blazor FluentUI library in real project another implementation like in [Demo repo](https://github.com/ANTestGit/BlazorAuthenticationTest) I have some components with rendermode InteractiveAuto, some with InteractiveServer and some could work in SSR. I can place components on server side or on client side. If the component uses InteractiveAuto mode, it must be placed on the client side but I can call it from server side. So main project I call server and ProjectName.Client I call client.

**Comment by halter73** [comment]
I took a look at your repro project at https://github.com/ANTestGit/BlazorAuthenticationTest and tried it out. I'm not seeing the issue with the login state disappearing from the top right info.

> Error found: it must be user id defined too.

Is this what resolved the issue with the login state disappearing? Overall, what you have right now looks good to me, but it still has a lot of extraneous stuff. You should no longer need `<PackageReference Include="Microsoft.AspNetCore.Authentication.Cookies" Version="2.1.34" />` in BlazorAuthenticationTest.Client.csproj (which [isn't supported](https://learn.microsoft.com/aspnet/core/migration/22-to-30#remove-obsolete-package-references) on net8.0 anyway). The  It also looks like the Microsoft.Extensions.Http dependency is supported, but no longer needed by the client project. And it looks like `CustomAuthStateProviderClient` and `BaseAuthenticationStateProvider` can be removed.

I see you're still using the IHttpClientFactory for some logout methods, but that shouldn't be necessary. Just linking to your logout page should be enough. If you want to require an anti-csrf token, you can see how that's done in the [Blazor Web OIDC sample](https://learn.microsoft.com/aspnet/core/blazor/security/blazor-web-app-with-oidc) [here](https://github.com/dotnet/blazor-samples/blob/446d842239ab655add0d48e46a7abf7397b88804/8.0/BlazorWebAppOidc/BlazorWebAppOidc.Client/Layout/LogInOrOut.razor#L8-L14) and [here](https://github.com/dotnet/blazor-samples/blob/446d842239ab655add0d48e46a7abf7397b88804/8.0/BlazorWebAppOidc/BlazorWebAppOidc/LoginLogoutEndpointRouteBuilderExtensions.cs#L20-L21), but what you have is fine too. A malicious actor might be able to log people out of your site unwittingly, but that's not a huge deal as far as security risks go imo.

Do you still have any problems with the AuthenticationStateProviders? Or is the persistent component state approach now working well for you?

**Comment by AlexNek** [comment]
@halter73 Thank you for your review. It is only the test project, I do not clear it. Can you recommend good blazor forum? I have some other problem like updating access token user friendly.

>Or is the persistent component state approach now working well for you?

Thank you all for your help, working nice.
