### ISSUE TITLE
Can the Dictionary when TryGetValue false support set the default value or Fun/Action to return?

### ISSUE THREAD

**Issue by Austin-Patrician** [dotnet/aspnetcore#57301]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Sometime  we want' to do extra action after the if condition,   it will make the code not elegant , so that it 's also a very east enhancement  for teams .

### Describe the solution you'd like

it supposed to add the over-load funtion after the out param .

**Comment by martincostello** [comment]
Requests for new APIs for types such as `Dictionary<K, V>` should be filed in the [dotnet/runtime](https://github.com/dotnet/runtime) repository as an API Suggestion: [New Issue](https://github.com/dotnet/runtime/issues/new/choose)

The proposal will need more detail than included above.
