### ISSUE TITLE
Authroization policy evaluation should not implictly require authentication scheme.

### ISSUE THREAD

**Issue by voroninp** [dotnet/aspnetcore#57322]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Here's the [repo](https://github.com/voroninp/AuthorizationRequirementDataTest) to reporduce the issue.
Just comment out the line (line 6) in `Program.cs` file:
```
builder.Services.AddAuthentication().AddBearerToken();
```

If you run the application and access `Get` endpoint, you will get:
>Error: Internal Server Error
System.InvalidOperationException: No authenticationScheme was specified, and there was no DefaultChallengeScheme found. The default schemes can be set using either AddAuthentication(string defaultScheme) or AddAuthentication(Action<AuthenticationOptions> configureOptions).
   at Microsoft.AspNetCore.Authentication.AuthenticationService.ChallengeAsync(HttpContext context, String scheme, AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.<>c__DisplayClass0_0.<<HandleAsync>g__Handle|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

This result is caused by the combination of the following things:
1. No authentication scheme is defined.
2. PolicyEvaluator has this code:
```
...
// If authentication was successful, return forbidden, otherwise challenge
return (authenticationResult.Succeeded)
    ? PolicyAuthorizationResult.Forbid(result.Failure)
    : PolicyAuthorizationResult.Challenge();
```
3. `AuthorizationMiddlewareResultHandler` calls [`ChallengeAsync`](https://github.com/dotnet/aspnetcore/blob/506512fd64a3fe8d23088750b57f463b799110a5/src/Security/Authorization/Policy/src/AuthorizationMiddlewareResultHandler.cs#L37) on `httpContext`.

### Expected Behavior

I'd expect just `401 Unauthorized` in case authorization fails and no Challenge scheme is set.

I understand that pgramatically authorization without authentication is a weird thing, but theoretially it shoud be possible to authrize any request based on the phase of the Moon without being bothered by the need to authenticate.

### Steps To Reproduce

Here's the [repo](https://github.com/voroninp/AuthorizationRequirementDataTest) to reporduce the issue.
Just comment out the line (line 6) in `Program.cs` file.

### Exceptions (if any)

```
System.InvalidOperationException: No authenticationScheme was specified, and there was no DefaultChallengeScheme found.
```

### .NET Version

8.0.303

**Comment by halter73** [comment]
> I understand that pgramatically authorization without authentication is a weird thing, but theoretially it shoud be possible to authrize any request based on the phase of the Moon without being bothered by the need to authenticate.

That's a funny example, but I agree in principle. However, there needs to be some way the authorization middleware to determine what to do when an authorization policy fails. Sending a 401 for an unauthenticated user and a 403 for an authenticated user might be reasonable defaults, and it is indeed what the base implementations of `AuthenticationHandler<TOptions>.HandleChallengeAsync` and `HandleForbiddenAsync` respectively do, but you still need to register an authentication handler for the authorization middleware to call and do this. That vast majority of the time developers run into `System.InvalidOperationException: No authenticationScheme was specified`, it's because they accidently misconfigured authentication rather than them wanting there to be no authentication handler at all, so I doubt we'd ever stop throwing an exception in this scenario.

For advanced users like yourself who might want to authorize the request based on the phase of the moon, it's simple enough to do so in an authentication handler. I recommend fully reading the short [Overview of ASP.NET Core authentication](https://learn.microsoft.com/aspnet/core/security/authentication/?view=aspnetcore-8.0) doc before you do, but it would look something like this:

```csharp
builder.Services.AddAuthentication()
    .AddScheme<MoonAuthenticationOptions, MoonAuthenticationHandler>("moon", options => { });

// ...

internal sealed class MoonAuthenticationOptions : AuthenticationSchemeOptions
{
    public string? AuthorizedPhaseOfMoon { get; set; }
}

internal sealed class MoonAuthenticationHandler : AuthenticationHandler<MoonAuthenticationOptions>
{
    public MoonAuthenticationHandler(IOptionsMonitor<MoonAuthenticationOptions> options, ILoggerFactory logger, UrlEncoder encoder)
        : base(options, logger, encoder)
    {
    }

    protected override Task<AuthenticateResult> HandleAuthenticateAsync()
    {
        // You could use Options and HttpContext here to truly base the result on the phase of the moon.
        // if (Options.AuthorizedPhaseOfMoon == "full") ..
        return Task.FromResult(AuthenticateResult.NoResult());
    }

    protected override Task HandleChallengeAsync(AuthenticationProperties properties)
    {
        // The base implementation returns a 401 already, so this override is unnecessary, but
        // this is where you could redirect to a login page for non-API clients and stuff like that.
        return base.HandleChallengeAsync(properties);
    }

    protected override Task HandleForbiddenAsync(AuthenticationProperties properties)
    {
        // The base implementation returns a 403 already, so this override is also unnecessary.
        // This is doubly unnecessary at the moment, because it is only ever called if this
        // handler returned a successfulAuthenticateResult and authorization fails anyway.
        return base.HandleForbiddenAsync(properties);
    }
}
```

**Comment by voroninp** [comment]
But then you need to call `UseAuthentication` to add the middelware which will cause HandleAuthenticate to run. ;-)

**Comment by halter73** [comment]
That's true, but is it really so bad when `HandleAuthenticateAsync` can just be `=> Task.FromResult(AuthenticateResult.NoResult())`?

**Comment by voroninp** [comment]
No, I am ok with it. Just thinking how doc could be improved.

**Comment by voroninp** [comment]
Btw, `[AllowAnonymous]` also has a very deceiving name. Authentication scheme is still executed (yet its result is ignored), but authorization is not performed.
