### ISSUE TITLE
InputDate Docs has a broken list

### ISSUE THREAD

**Issue by digitaldirk** [dotnet/aspnetcore#57357]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The list of supported types is broken:
https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.forms.inputdate-1?view=aspnetcore-8.0
![image](https://github.com/user-attachments/assets/2e53de7f-5871-4c83-9bee-005033ea7659)

https://github.com/dotnet/aspnetcore/blob/3f1acb59718cadf111a0a796681e3d3509bb3381/src/Components/Web/src/Forms/InputDate.cs#L11-L21

I would like to do a PR to fix this but I an unsure of how to visually test a fix (I have cloned https://github.com/dotnet/aspnetcore.git and found the project/file)

### Expected Behavior

To display the supported types

### Steps To Reproduce

1. Go to: https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.forms.inputdate-1?view=aspnetcore-8.0
2. See supported type list

**Comment by javiercn** [comment]
@digitaldirk thanks for contacting us.

Are you seeing this from a `.cs` file or from a `.razor` file. What would be your proposed fix? I guess https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/recommended-tags#list is it.

The validation could be as simple as trying to use it with a fix on a sample project in VS and seeing the items correctly appear on the UI.

**Comment by digitaldirk** [comment]
> @digitaldirk thanks for contacting us.
> 
> Are you seeing this from a `.cs` file or from a `.razor` file. What would be your proposed fix? I guess https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/recommended-tags#list is it.
> 
> The validation could be as simple as trying to use it with a fix on a sample project in VS and seeing the items correctly appear on the UI.

Hi @javiercn it is a `.cs` file: https://github.com/dotnet/aspnetcore/blob/3f1acb59718cadf111a0a796681e3d3509bb3381/src/Components/Web/src/Forms/InputDate.cs#L11-L21

What you linked would be the fix yes, I just wanted to visually test it. Is there a sample project you can link? I have https://github.com/dotnet/aspnetcore.git cloned but didn't know how to run the docs to test it (or is there guidelines to get this to run?).

Thank you
