### ISSUE TITLE
Blazor - Authentication cookie in a webapi call in the same project

### ISSUE THREAD

**Issue by GLuca74** [dotnet/aspnetcore#57367]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Hello,

I have a Blazor generate template with Individual accounts Identity and `RenderMode WebAssembly.`
At this template, in the server project I added a `webapi controller`(I will enable jwt authentication, but this is not the point)
In a `webassembly `page(`counter`) that is now under authorization, in a `button `I added a call to the `webapi `that is inside the webproject.

```
        var HttpClient = new HttpClient();
        using (var response = await HttpClient.GetAsync("https://localhost:7281/MyWebApi")//jwt token adding is removed for simplicity
                                    .ConfigureAwait(false))
        {
        }

```
When I run the app, I log in and try the `button ` and everithing is ok, but if I inspect the `request `with fiddler I can see that the request contains the `cookie authentication`(and also the `Antiforgery `cookie). I can image that the reason is `HTTPClient `ask to the browser to perform the get call, the browser see that is the same domain and send the `cookie `also(because the same get call to an external domain not add the `authentication cookie`).
But actually I not need to send the `cookie `that is for UI, is there a way to avoid to send the `cookies`?

Thank you

### Describe the solution you'd like

not send the  `authentication cookie`

**Comment by javiercn** [comment]
@GLuca74 thanks for contacting us.

You can try with https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.webassembly.http.webassemblyhttprequestmessageextensions?view=aspnetcore-8.0 and use `request.SetBrowserRequestCredentials(BrowserCredentials.None)`, however, it might result in the auth header also being stripped.

That said, if you are already using cookies for auth, it's not clear what you are gaining from adding a layer with JWTs. You can simply use the cookie in combination with the antiforgery token to authenticate API calls if they are on your same origin.

**Comment by GLuca74** [comment]
hello  @javiercn  and thanks for your quick reply,

I tried `R.SetBrowserRequestCredentials(BrowserRequestCredentials.Omit)` but yes, how you wrote it remove also the auth header so it not fix.

I try to explain and summarize why i need both.
I have the webapp with `rendermode webassembly` that include also the `webapi controller`. The page that access the `webapi` is in a `RCL `referenced by the webapp(client project) and a `MAUI Balzor Hybrid` app. So when the page runs in the webapp yes, you may be right, but when the page runs inside the `MAUI `app, the cookie is not awailble. So, in the shared pages I need to authenticate with a system that is always available. So, I need the cookie to authenticate the UI when the web app runs but I need the JWT to be sure that the shared pages can authenticate in webapp and i MAUI app

I can neither check if I am in webassebly(and not add the JWT) or in MAUI(and add the JWT) because (it is very boring and) also the webapi controller is added from a library(they are all parts of a framework). This means that now the web api is inside the web app project but if the traffic grows I may decide to move the webapi controller in a dedicated web project and in this case when the page runs in the webapp the JWT instead is needed

**Comment by javiercn** [comment]
@GLuca74 are you attaching the token to the request manually?

Have you considered using `HttpClientFactory` and/or a `DelegatingHandler` to attach the token in Maui scenarios only? If you were to use HttpClientFactory or inject an instance of HttpClient into your app, you can configure that logic in the hosting app, and avoid having to make that decision in the library.

Similarly, for your API, it doesn't matter whether it's on a class library or on the web app project itself. You can define an authentication policy and then configure on the host what things its willing to accept.

If you are talking about separating the API into a separate process and/or origin, that's possible, but if you follow the approach above, it shouldn't matter. You could change the auth approach in the host (webassembly/maui) without having to change the code in the RCL.

**Comment by GLuca74** [comment]
Hello @javiercn 

I thought better on your words and you are so right, whether I can remove the cookie or not, If in the page there are at the same time two authenticate systems something is wrong. So I reviewed my logic and I understood that :

When I publish the webapi controller I can set wath type of authorization is required to access or if no authentication is needed
When I add the RCL I can set if webapi to connect to requires JWT Authorization or not requires authentication

So I can publish the webapi that require `JwtBearerDefaults.AuthenticationScheme` or `IdentityConstants.ApplicationScheme`.
From Client Web Project I can add the RCL using the setting that not require authentication (in this case means the context is already authenticate)
From MAUI app I can add the RCL using the settings that JWTAuthentication is required.

If in the future I will move the webapi in a dedicated website, I will use just JWT authentication and also from client webproject i will set that JWT authentication is required for the RCL

Anything works and the design is much more clean

Thank you very much for the time you spent to answer me that indicated me the right way

**Comment by javiercn** [comment]
@GLuca74 great to hear that.

We are happy to help!
