### ISSUE TITLE
IEmailSender does not exist in Microsoft.AspNetCore.Identity.UI when targeting .NET 7/.NET 6

### ISSUE THREAD

**Issue by kikaragyozov** [dotnet/aspnetcore#57364]
This is a repost of https://github.com/dotnet/aspnetcore/issues/56823, as .NET 6 is still in support as far as I can see.

**Comment by martincostello** [comment]
.NET 6 is in support until November, but it won't get any new APIs as new APIs are typically never backported to previous versions.

**Comment by javiercn** [comment]
@kikaragyozov thanks for contacting us.

As per @martincostello that's the case. It's not expected that you try to use higher package versions with older shared framework versions.

**Comment by kikaragyozov** [comment]
@javiercn Thank you for your time!

Seems that was my confusion, as I got confused by how other certain packages behave in their versioning.
