### ISSUE TITLE
Naming inconsistency on `ISkipStatusCodePagesMetadata` feature

### ISSUE THREAD

**Issue by onurkanbakirci** [dotnet/aspnetcore#57382]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

https://github.com/dotnet/aspnetcore/blob/48a07213d4d8df15c6dffccd161844842c196998/src/Http/Http.Abstractions/src/Metadata/IStatusCodePagesMetadata.cs#L4-L12

Why is the class name `ISkipStatusCodePagesMetadata` different from the file name `IStatusCodePagesMetadata` for this interface?

### Expected Behavior

I think that file name should be `ISkipStatusCodePagesMetadata`. If it is ok, i'm gonna open PR

**Comment by amcasey** [comment]
The class probably got renamed during code or API review and the file name was missed.  Sure, go ahead and open a PR.
