### ISSUE TITLE
Make compiler error instead of runtime against using ChildContent

### ISSUE THREAD

**Issue by macias** [dotnet/aspnetcore#57391]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

When you create markup like this:
```
<MyComponent>
  This is ChildContent
</MyComponent>
```

and `MyComponent` does not have `ChildContent` the code will compile, and the error will be postponed until runtime.

### Describe the solution you'd like

Please push the error to compile time instead of runtime. This will allow to faster evaluate the code.

**Comment by javiercn** [comment]
@macias thanks for contacting us.

That's perfectly valid, we can't know on a component whether or not (or how) it processes child content and/or if its required.

**Comment by macias** [comment]
@javiercn Hmm, to process/accept such markup as shown above you need to have `ChildContent` property in component, right? So if there is no such property you know in advance markup is invalid.
