### ISSUE TITLE
Breaking change for IdentityRole object not documented

### ISSUE THREAD

**Issue by GorazdDim** [dotnet/aspnetcore#57427]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The `IdentityRole.ConcurrencyStamp` property has a changed type and default value from the `6.0.33` version to the `7.0.0` version.

In the `6.0.33` version the property is defined like: `public virtual string ConcurrencyStamp { get; set; } = Guid.NewGuid().ToString();`

In the `7.0.0` version the property is defined like: `public virtual string? ConcurrencyStamp { get; set; }`

This is a breaking change and it is not documented anywhere. After a short debugging session I found the issue, but I felt i needed to report this.

**Comment by MackinnonBuck** [comment]
It looks like this change was made accidentally. We should consider adding a default value back.

Out of curiosity, how did this break your app?

**Comment by GorazdDim** [comment]
I implemented custom logic to compare the ConcurrencyStamp to handle concurrency errors manually, instead of relying on catching a DbUpdateConcurrencyException. Previously, the code expected a new Role to have an initial value for the ConcurrencyStamp. However, now that the initial value is null, the comparison logic incorrectly treats this as a concurrency error.

If I remove my custom logic the IdentityFramework properly handles the concurrency, which is probably why this issue wasn't noticed.
