### ISSUE TITLE
[Blazor] Provide a better error message when an asset is not found because the environment is `Production` and the app has not been published.

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#57449]

**Comment by SteveSandersonMS** [comment]
Isn't the issue when we're running in `Production`, not development? I thought we'd need to detect the case where, in `Production`, the SWA files aren't present on disk. Or am I misinterpreting?

**Comment by javiercn** [comment]
@SteveSandersonMS I tried to clarify things a bit.
