### ISSUE TITLE
Cookie auth (with identity) for MAUI Blazor (BlazorWebView) - iOS and Android?

### ISSUE THREAD

**Issue by Laftek** [dotnet/aspnetcore#57456]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Sorry to post it here. I tried reddit, stackoverflow and discussion here but I did not get answer still :/

MSFT says for non browser devices use token based auth. What about MAUI Blazor with BlazorWebView? Can cookie auth be used for login and persist cookie or only token based auth?

So lets say can I convert this
https://github.com/dotnet/blazor-samples/tree/main/8.0/BlazorWebAssemblyStandaloneWithIdentity
to MAUI and use the same auth mechanism for MAUI Blazor (iOS and Android)? Would it work? Or if someone can point to useful resource regarding this topic I would appreciate it.

Thank you.

### Describe the solution you'd like

To have cookie based authentication (with persistent cookie) on MAUI Blazor (iOS and Android).

**Comment by javiercn** [comment]
@Laftek thanks for contacting us.

Cookies won't work because they live in the webview, and not in the .NET Code running in the process hosting the webview.

**Comment by Laftek** [comment]
Thanks @javiercn! Can I pass cookie from webview to .net code?

If not then I can create web API with identity and AddIdentityApiEndpoints and do auth for both cookie (for web) and token (for mobile devices) right?

**Comment by Laftek** [comment]
@Eilon Hi Eilon, sorry to ping you here but I know you are Blazor MAUI master. Do you know if there is any way how to pass cookie from webview to .net code so blazor basic cookie auth with identity can be achieved in such a scenario? Thanks!

**Comment by Laftek** [comment]
@Eilon Thanks Eilon! I knew you would come up with something even if its Copilot 😄
