### ISSUE TITLE
Blazor - Offer a way to force browsers to reload bundle.scp.css files

### ISSUE THREAD

**Issue by jofford** [dotnet/aspnetcore#57472]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

When re-publishing a Blazor app the browser will try and use the cached versions of all bundle.scp.css files, leading to styling issues when they are out of date. Because these are being loaded via the my-app.styles.css file, via an @import statement, I can't find a way to force reload them. Even if you apply a query parameter to the style sheet from index.html, something like my-app.styles.css?v1.1, the bundle.scp.css files will still load from the browser cache first.

### Describe the solution you'd like

Allow users to append a query string on imported bundle.scp.css files, something like "bundle.scp.css?v1.1". The extra query parameter will force the browser to reload the file.

**Comment by javiercn** [comment]
@jofford thanks for contacting us.

This has already been implemented in .NET 9.0 through fingerprinting the files.
