### ISSUE TITLE
Blazor Server App - Problem with accessing request scope in DelegatingHandler

### ISSUE THREAD

**Issue by mdzieg** [dotnet/aspnetcore#57481]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a problem with getting request scope in blazor server app.

I use `HttpClientFactory` to communitace with one of my services. I wanted to inject dynamic header into each request.
To do so I created custom `DelegatingHandler`.
Because `HttpClient` handlers are created in a separate scope (https://andrewlock.net/understanding-scopes-with-ihttpclientfactory-message-handlers/) I took the approach with injecting `IHttpContextAccessor`.

Here is draft of the handler:

```
public class MyHeaderHandler : DelegatingHandler
{
	private readonly IHttpContextAccessor _httpContextAccessor;

	public MyHeaderHandler(IHttpContextAccessor httpContextAccessor)
	{
		_httpContextAccessor = httpContextAccessor;
	}

	protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
	{
		var prov = _httpContextAccessor?.HttpContext?.RequestServices.GetService(typeof(IMyProvider)) as IMyProvider;

		...
	}
}
```

`IMyProvider` (registered as scoped service in DI) instance has some data set during request processing. I need to access that data.

The problem is that the instance I get from `IHttpContextAccessor` from `MyHeaderHandler` is different from the instance I get in blazor components or other services used there directly (not via `DelegatingHandler`).

I tried to set SuppressHandlerScope option to true, but no luck:

```
serviceCollection.Configure<HttpClientFactoryOptions>(builder.Name, options =>
		{
			options.SuppressHandlerScope = true;
		});
```
		
		
AFAIK this approach works in WebApi projects and the problem is with Blazor apps.
To me it looks like a BUG.
If this method of getting request scope is not correct, I would be more than happy to get some advice here.

### Expected Behavior

IHttpContextAccessor.HttpContext.RequestServices gives access to request scope.

### .NET Version

8.0.304

**Comment by mdzieg** [comment]
Solution is to use `CircuitServicesAccessor`:

https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/dependency-injection?view=aspnetcore-8.0#access-server-side-blazor-services-from-a-different-di-scope

**Comment by javiercn** [comment]
@mdzieg seems that you aren't using Blazor web.

I suspect you need to setup the circuit accessor in these two callbacks too

![image](https://github.com/user-attachments/assets/3e62c75d-16fb-4534-b650-492347865e5c)

**Comment by mdzieg** [comment]
@javiercn I added two more overrides and tested the app. Although breakpoints in those extra methods are hit before my component code is executed, the context value is not present. The Order of execution when opening /counter page is the following:

1. ServicesAccessorCircuitHandler->OnCircuitOpenedAsync
2. ServicesAccessorCircuitHandler->OnConnectionUpAsync
3. MainLayout->OnInitialized (context value set here)
4. MyDelegatingHandler->SendAsync (conext value consumed here but null Services collection)
5. CreateInboundActivityHandler

**Comment by mdzieg** [comment]
Thank you, @MackinnonBuck! Will it be included only in net9 or also in net8?

**Comment by javiercn** [comment]
@mdzieg we are unlikely to port this to 8.0 since only affects the old hosting model based on MVC, unless we receive significant feedback otherwise.

We recommend moving to `Blazor Web` with `InteractiveServer` components which essentially serves the same purpose.
