### ISSUE TITLE
Performance degradation for a loop while running in docker container

### ISSUE THREAD

**Issue by marklonquist** [dotnet/aspnetcore#57485]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We are currently having issues where a application seem to be running really bad when in a docker container.

This is from the docker container:
```
integration-1  | Starting processing of styles: 00:01:30.2460992
integration-1  | [08/23/2024 12:54:58 +00:00] Processed 100 styles of 5469
integration-1  | [08/23/2024 12:54:58 +00:00] Processing style: 12263445
integration-1  | [08/23/2024 12:54:58 +00:00] Validation started
integration-1  | [08/23/2024 12:54:58 +00:00] Validation ended
integration-1  | [08/23/2024 12:54:58 +00:00] Product creation started
integration-1  | [08/23/2024 12:54:58 +00:00] Product creation ended
integration-1  |
integration-1  | [08/23/2024 12:56:15 +00:00] Processed 200 styles of 5469
integration-1  | [08/23/2024 12:56:15 +00:00] Processing style: 12152346
integration-1  | [08/23/2024 12:56:15 +00:00] Validation started
integration-1  | [08/23/2024 12:56:15 +00:00] Validation ended
integration-1  | [08/23/2024 12:56:15 +00:00] Product creation started
integration-1  | [08/23/2024 12:56:15 +00:00] Product creation ended
```

When running (on the same machine) through Rider, we get this:
```
Starting processing of styles: 00:01:20.1102731
[23-08-2024 13:18:19 +00:00] Processed 100 styles of 5469
[23-08-2024 13:18:19 +00:00] Processing style: 12263445
[23-08-2024 13:18:19 +00:00] Validation started
[23-08-2024 13:18:19 +00:00] Validation ended
[23-08-2024 13:18:19 +00:00] Product creation started
[23-08-2024 13:18:19 +00:00] Product creation ended

[23-08-2024 13:18:21 +00:00] Processed 200 styles of 5469
[23-08-2024 13:18:21 +00:00] Processing style: 12152346
[23-08-2024 13:18:21 +00:00] Validation started
[23-08-2024 13:18:21 +00:00] Validation ended
[23-08-2024 13:18:21 +00:00] Product creation started
[23-08-2024 13:18:21 +00:00] Product creation ended

[23-08-2024 13:18:24 +00:00] Processed 300 styles of 5469
[23-08-2024 13:18:24 +00:00] Processing style: 12178125
[23-08-2024 13:18:24 +00:00] Validation started
[23-08-2024 13:18:24 +00:00] Validation ended
[23-08-2024 13:18:24 +00:00] Product creation started
[23-08-2024 13:18:24 +00:00] Product creation ended

[23-08-2024 13:18:25 +00:00] Processed 400 styles of 5469
[23-08-2024 13:18:25 +00:00] Processing style: 12194284
[23-08-2024 13:18:25 +00:00] Validation started
[23-08-2024 13:18:25 +00:00] Validation ended
[23-08-2024 13:18:25 +00:00] Product creation started
[23-08-2024 13:18:25 +00:00] Product creation ended
```

As can be seen, it's running waaay faster when running through Rider. I can't seem to find the reason behind this.

All we are doing is looping over products and creating a model with some data (no IO being done)

### Expected Behavior

Speed should be equally fast in a docker container

### Steps To Reproduce

haven't been able to produce a simple repo that reproduces it. How do we go about this? :/

### .NET Version

8.0-noble-chiseled-extra

### Anything else?

```
.NET SDK:
 Version:           8.0.304
 Commit:            352dc5a01f
 Workload version:  8.0.300-manifests.b6724b7a
 MSBuild version:   17.10.4+10fbfbf2e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.304\

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.8
  Architecture: x64
  Commit:       08338fcaa5

.NET SDKs installed:
  8.0.304 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by martincostello** [comment]
> haven't been able to produce a simple repo that reproduces it. How do we go about this?

You could look at creating a simple benchmark using [BenchmarkDotNet](https://github.com/dotnet/BenchmarkDotNet) that runs the code you're concerned about the performance of and run it both on your developer machine and in the Docker environment and compare the results you get.

This isn't going to be actionable as-is without any code to measure or any information about what container image you're using.

It could be something as simple as just the performance penalty of the virtualisation of running a container (i.e. a hardware issue that's nothing to do with .NET as ASP.NET Core).

**Comment by marklonquist** [comment]
> > haven't been able to produce a simple repo that reproduces it. How do we go about this?
> 
> 
> 
> You could look at creating a simple benchmark using [BenchmarkDotNet](https://github.com/dotnet/BenchmarkDotNet) that runs the code you're concerned about the performance of and run it both on your developer machine and in the Docker environment and compare the results you get.
> 
> 
> 
> This isn't going to be actionable as-is without any code to measure or any information about what container image you're using.
> 
> 
> 
> It could be something as simple as just the performance penalty of the virtualisation of running a container (i.e. a hardware issue that's nothing to do with .NET as ASP.NET Core).
> 
> 

I will look more into a simple reproduction repo  

However, the issue is present on my machine in both rider and docker, as well ad running on our kubernetes setup. Really strange.

**Comment by marklonquist** [comment]
I'm gonna close this as I haven't been able to make a small reproduction. Will try and pinpoint the exact cause in our code before making a new/reopen issue.
