### ISSUE TITLE
Misleading error when DI fails

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#57488]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Misleading-error-when-DI-fails/10728338)._

---
[severity:It's more difficult to complete my work]
I recently lost over an hour to this one. I accidentally used:

`@inject Logger<MyComponent>`

instead of

`@inject ILogger<MyCompnent>`

The error it was giving me came from ExecutionContext stating there was a null value in a callback and crashed the entire application. No where in the stack trace did it say where the error was, only that it was coming from SignalR (which is also misleading). This is actually a pretty generic error that you get when any number of things go wrong with a razor page.

In this particular case, I expected to get a typical error stating a dependency could not be resolved. Literally nothing useful was in the stack trace, I had to start putting break points in the .NET Framework source code to finally see something that let me to see that the problem was related to DI caused by a single character typo. Hours lost. I'm sure it is well known that tool support for Razor components is lacking - errors and/unhelpful are quite misleading when they come from a razor component. 

---
#### Feedback Bot on 8/21/2024, 07:30 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by halter73** [comment]
> The error it was giving me came from ExecutionContext stating there was a null value in a callback and crashed the entire application.

Can you please provide a repro app demonstrating this happening due to a missing dependency?
