### ISSUE TITLE
[Blazor] Detect pre compressed assets in packages, avoid compressing those assets and emit a warning instead

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#57518]
Some existing packages ship already compressed versions of assets without the appropriate metadata that conflict with the paths we generate for our own compressed assets.

Instead of erroring out, avoid compressing that asset and emit a warning to indicate the situation.

**Comment by mkArtakMSFT** [comment]
Cleaning the milestone to re-triage.

**Comment by davhdavh** [comment]
This is pretty critical, noone in our team can upgrade to vs 17.2 since it kills all old builds

**Comment by gadjio** [comment]
Is it possible that it also affect AzureDevops build pipeline

https://github.com/actions/runner-images/blob/win22/20241113.3/images/windows/Windows2022-Readme.md

![Image](https://github.com/user-attachments/assets/8a91b7cc-2d50-40b2-aaf5-e4add8cddf52)

**Comment by javiercn** [comment]
There's now a PR to automatically detect this situation and avoid compressing the assets again https://github.com/dotnet/sdk/pull/44976

**Comment by javiercn** [comment]
Done as part of https://github.com/dotnet/sdk/pull/44976
