### ISSUE TITLE
[Blazor] Improve StreamRender diffing and DOM change detection

### ISSUE THREAD

**Issue by audacode** [dotnet/aspnetcore#57523]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

.NET 10 Blazor planning: I would ask that the algorithm for StreamRender be improved to only send required DOM changes to browser; and to not send a blazor-ssr template update if no change is required.

### Describe the solution you'd like

With StreamRender enabled, the current implementation will repeatedly send a blazor-ssr update to the browser, even if no changes are made to the DOM in this example below:
```cs
    protected override async Task OnInitializedAsync()
    {
        StateHasChanged();
        await Task.Yield();
        StateHasChanged();
        await Task.Yield();
        StateHasChanged();
        await Task.Yield();
    }
```
In the above example the rendered ssr templates will have the same content and parameters.  This is extremely inefficient and not consistent with InteractiveServer or InteractiveWebAssembly where no content update will be sent to the client if there was no change to the DOM.

The second part of this request is probably obvious: Can we please improve the diffing algorithm to not send the entire rendered content of a component if only a small change needs to be patched in.  Blazor is so very clever in InteractiveServer and InteractiveWebAssembly mode at diffing and patching.  The current StreamRender algorithm seems to send the entire content of a component on each update in a scenario where you perform multiple asynchronous awaits in OnInitializedAsync and call StateHasChanged before each await.  Surely we can improve on this for .NET 10.

**Comment by iphdav** [comment]
@javiercn I will add that we are not just rendering "a few additional divs".  More realistically, if a component rendered 5 KB and OnInitializedAsync had 5 awaits/StateHasChanged it would end up sending 5 x 5KB = 25 KB instead of maybe sending 6 KB with a better algorithm.

**Comment by iphdav** [comment]
@javiercn Here is a good example.  Imagine a current blazor server component that rendered 10 KB, but was awaiting something that took 30 seconds.  With Blazor InteractiveServer, inside OnInitializedAsync you could be updating some progress indicator every second that is outputting how many seconds had passed.  Yes this is an extreme example, but each second you could have:
```cs
StateHasChanged();
timePassed += 1;
await Task.Delay(1000);
```
In Blazor Server a few hundred bytes would be sent every second.

If that component was used for SSR, it would send the whole 10 KB every second, so send 300 KB in total.

These kind of differences add complexity to the developer story (what the developer needs to understand to be successful).
