### ISSUE TITLE
Multiple Unhandled Exceptions thrown in statics.teams file

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#57569]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Multiple-Unhandled-Exceptions-thrown-in-/10726975)._

---
[severity:It bothers me. A fix would be nice] [regression] [worked-in:17.10.4]
When running my Blazor application, it throws multiple unhandled exceptions, one of which is:
'Error: DiscoverregionGtmInvalidResponse - groupsServiceV2 is missing in discover response' error

---
#### Feedback Bot on 8/21/2024, 03:09 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by KamleshSavaliya1122** [comment]
precompiled-web-work…42423d4.worker.js:1 Uncaught (in promise) Error: Discover::regionGtm::InvalidResponse - groupsServiceV2 is missing in discover response
