### ISSUE TITLE
`JwtBearerHandler` does not handle custom authentication schemes

### ISSUE THREAD

**Issue by less0** [dotnet/aspnetcore#57587]
Some of the extension method `AddJwtBearer` overloads allow custom authentication schemes to be provided

    public static AuthenticationBuilder AddJwtBearer(this AuthenticationBuilder builder, string authenticationScheme, string? displayName, Action<JwtBearerOptions> configureOptions)
    {
        builder.Services.TryAddEnumerable(ServiceDescriptor.Singleton<IConfigureOptions<JwtBearerOptions>, JwtBearerConfigureOptions>());
        builder.Services.TryAddEnumerable(ServiceDescriptor.Singleton<IPostConfigureOptions<JwtBearerOptions>, JwtBearerPostConfigureOptions>());
        return builder.AddScheme<JwtBearerOptions, JwtBearerHandler>(authenticationScheme, displayName, configureOptions);
    }

When trying to use these custom authentication schemes in my controller, it occurred to me that they simply put do not work at all. (I've opened a question on StackOverflow back then, see [here](https://stackoverflow.com/questions/73618495/defining-a-webapi-with-two-jwt-authentication-schemes-does-not-work).)

My approach was to call AddJwtBearer twice in my setup with two different schemes

```csharp
builder.Services.AddAuthentication()
    .AddJwtBearer(
        options =>
            {
                // ...
            })
    .AddJwtBearer(
        AuthenticationDefaults.CustomScheme, 
        options =>
            {
                options.Challenge = AuthenticationDefaults.CustomScheme;
                // ...
            });
```

Furthermore I added

```csharp
builder.Services.AddAuthorization(
    options =>
        {
            var customPolicy = new AuthorizationPolicyBuilder(AuthenticationDefaults.CustomScheme)
                .RequireAuthenticatedUser()
                .Build();

            var azureAdPolicy = new AuthorizationPolicyBuilder(JwtBearerDefaults.AuthenticationScheme).RequireAuthenticatedUser()
                .Build();
            
            options.AddPolicy(AuthenticationDefaults.CustomScheme, customPolicy);
            options.AddPolicy(JwtBearerDefaults.AuthenticationScheme, azureAdPolicy);

            options.DefaultPolicy = customPolicy;
        });
```

to my setup and

```
[Authorize(AuthenticationSchemes = AuthenticationDefaults.CustomScheme)]
```

to my controller method.

Since this did not work at all, I started investigating the original code and it occurred to me, that the `JwtBearerHandler` only checks for `"Bearer "` starting the `Authorization` header:

https://github.com/dotnet/aspnetcore/blob/8af96e042134fb3b2f21df26dd0f32ea1c00dd37/src/Security/Authentication/JwtBearer/src/JwtBearerHandler.cs#L84

In my opinion, this should take into account any custom scheme that is passed to `AddJwtBearer` instead of relying on `"Bearer"` being the correct scheme (albeit `Bearer` is in the name), since this would easily allow custom schemes with JWTs. Of course dropping the custom schemes from `AddJwtBearer` would be another option, but this way, using JWTs with custom schemes would be made way harder. 

I've checked the code in the 9.0 preview 5 branch and the bug still seems to be present.

**Comment by martincostello** [comment]
This looks like it's maybe a duplicate of #57174?

**Comment by less0** [comment]
@martincostello Well at first glance it looks like, I'll have a closer look oater. I'm sorry, did not assume there was an existing issue and thus did not search for one, because this supposed bug is around for so long.

**Comment by less0** [comment]
@martincostello yeah it looks as if it's indeed a dupe. Again, I'm sorry for not looking and hence wasting your time.
