### ISSUE TITLE
AddMicrosoftIdentityWebApi ignores missing configuration

### ISSUE THREAD

**Issue by andreas-valtech** [dotnet/aspnetcore#57596]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using the `AddMicrosoftIdentityWebApi` with the following code:

```
services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
                .AddMicrosoftIdentityWebApi(configuration, "AzureAdB2C", JwtBearerDefaults.AuthenticationScheme, false)
                .EnableTokenAcquisitionToCallDownstreamApi();
```
                
The call succeeds even if the config section is empty. We are using `dotnet user-secrets` and had not added a "AzureAdB2C" section in one of our developers secrets stores. The result was a misbehaving app since authentication was not setup but no other error happened right away.
__

### Expected Behavior

When the "AzureAdB2C" section is missing it should crash with an exception right away.

### Steps To Reproduce

Add a new mvc app with dotnet new mvc -n ExampleApp
Add the package Microsoft.Identity.Web

Add the following to the Porgram.cs:

```
builder.Services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
    .AddMicrosoftIdentityWebApi(builder.Configuration, "AzureAdB2C", JwtBearerDefaults.AuthenticationScheme, false)
    .EnableTokenAcquisitionToCallDownstreamApi()
    .AddInMemoryTokenCaches();
```

Notice that it does not care that the "AzureAdB2C" section is missing.

### .NET Version

8.0.300

### Anything else?

.NET SDK:
 Version:           8.0.300
 Commit:            326f6e68b2
 Workload version:  8.0.300-manifests.6751eab7
 MSBuild version:   17.10.4+10fbfbf2e

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  14.6
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/8.0.300/

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.5
  Architecture: arm64
  Commit:       087e15321b

.NET SDKs installed:
  6.0.423 [/usr/local/share/dotnet/sdk]
  8.0.300 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.31 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.27 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.31 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by MackinnonBuck** [comment]
Thanks for reaching out, @andreas-valtech. It looks like this is an issue with [Microsoft Identity Web](https://github.com/AzureAD/microsoft-identity-web). Could you please file an issue there instead? Thanks!

@jennyf19 FYI

**Comment by andreas-valtech** [comment]
Added the issue here instead: https://github.com/AzureAD/microsoft-identity-web/issues/3001
