### ISSUE TITLE
HttpClient GetAsync always return Not found not hitting API method immediately returning without response

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#57616]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/HttpClient-GetAsync-always-return-Not-fo/10732342)._

---
Response: StatusCode: 404, ReasonPhrase: 'Not Found', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Server: Microsoft-IIS/10.0
  X-Powered-By: ASP.NET
  Date: Tue, 27 Aug 2024 11:41:09 GMT
  Content-Type: text/html
  Content-Length: 1245
}

always same response not hitting the API method and no response. please support

---
#### Nicole Hu [MSFT] on 8/27/2024, 10:08 PM: 

(private comment, text removed)
#### Feedback Bot on 8/27/2024, 10:19 PM: 

(private comment, text removed)
#### Feedback Bot on 8/29/2024, 01:56 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by amcasey** [comment]
Does it work if you access the same API via the browser, curl, or wget?
