### ISSUE TITLE
JwtBearerHandler should trigger OnAuthenticationFailed event, even when there is no Token in Authorization header

### ISSUE THREAD

**Issue by tbebekis** [dotnet/aspnetcore#57636]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

The JwtBearerHandler does NOT trigger OnAuthenticationFailed event when there is no Token in Authorization header.

Or no Authorization header at all.

### Describe the solution you'd like

JwtBearerHandler should trigger OnAuthenticationFailed event, even when there is no Token in Authorization header or no Authorization header at all, when Authentication is required by the Controller Action.

That way the application will have a chance to return a descriptive message, a header, or something, denoting that the Controller Action being called requires authentication.

### Additional context

Here is the relevant screenshot from the JwtBearerHandler.cs

![Screenshot_1](https://github.com/user-attachments/assets/ddd91228-3b81-4150-b0de-f235d917c13a)

**Comment by chrisoverzero** [comment]
As I understand it, `OnAuthenticationFailed` is for when credentials are presented, but they’re invalid or otherwise “don’t work.” Should you be looking at `OnChallenge`?

**Comment by tbebekis** [comment]
Hi @chrisoverzero 
and thanks for the response.

I've already checked the `OnChallenge` event.

The thing is that when a client requests a Controller's Action that requires Authentication, the `OnChallenge` event

- returns `Response.StatusCode = 200 (Ok)`
- the `JwtBearerChallengeContext.AuthenticateFailure` and `Error` properties are `null`.

Later in the middlewares pipeline, and after the `OnChallenge` event is triggered, the `Response.StatusCode` becomes `401 (Unauthorized)`. But inside the `OnChallenge` event there is no such information.

Is there a way to know what really happened and exactly why the `OnChallenge` event is triggered?

Thanks again.

**Comment by svrooij** [comment]
1. Do not post screenshots of codes, just copy the permalink and past that.
2. It's expected that if this Authentication handler cannot handle the request (no token) it will emit the NoResult.

You can use this handler together with other handlers, you'll only get challenged (what ever that means for that handler), if it is set as the default. So if you set `Cookie` as default it will redirect to the login form. And if you set `JWT` as default it will return a `401` error code.

You can also create an authorization policy that specify which handler should be mandatory and what rules you want to check.

**Comment by mkArtakMSFT** [comment]
As others have already mentioned, this behavior is by-design. The `NoResult` response is correctly returned in this case.
