### ISSUE TITLE
🐞 Hot Reload breaks CSS isolation when using a Razor class library 

### ISSUE THREAD

**Issue by MarkusRodler** [dotnet/aspnetcore#57660]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I created a new Blazor-Wasm project from scratch with a linked RCL. If I now edit a component CSS within the Client folder Hot Reload will remove the styles from the linked RCL.
If I inspect the Client.styles.css file it will remove the @import line after every hot reload:
![image](https://github.com/user-attachments/assets/a1696e7d-ffcb-4ba9-85c2-502f0d6b9138)

### Expected Behavior

Hot Reload works...

### Steps To Reproduce

https://github.com/user-attachments/assets/172245e5-4ecd-48f3-8a9c-a30a52ed9d31

### .NET Version

8.0.8

### Anything else?

Reproducible with Windows and Linux

**Comment by MackinnonBuck** [comment]
Thanks for reaching out. We think this issue is getting fixed in an upcoming VS release. If you still experience the problem in Visual Studio 17.12, please file a Visual Studio Feedback ticket.

**Comment by MarkusRodler** [comment]
@MackinnonBuck Well if you look at the video above you can see that this is not an Visual Studio issue. I'm using Visual Studio Code and used the command line to run `dotnet watch run`. So please reopen that issue.

**Comment by MackinnonBuck** [comment]
I was able to reproduce this on the .NET 8 SDK, but it seems to have been fixed in .NET 9. @tmat, does this happen to ring a bell?
It also seems that this issue doesn't repro in VS (even when using the .NET 8 SDK), which makes me think this problem is specific to `dotnet watch`.

**Comment by MackinnonBuck** [comment]
Related: https://github.com/dotnet/aspnetcore/issues/45987

**Comment by tmat** [comment]
I don't know what cased/fixed this issue.

**Comment by GioviQ** [comment]
I have a Blazor Server .NET 6 application, after Visual Studio upgrade to 17.12.1 the file bundle.scp.css is no more generated

Disabling hot reload has no effect.

**Comment by TransparentPro-BV** [comment]
I have the same problem, I am running .Net 9 with Visual studio 2022 17.12.3. 
Even if i start with a fresh Blazor server Web app and gradually copy over my files to that new solution, eventually i will end up with a broken Hot Reload. You can not change CSS on the main startup project. Inspecting the Hot Reload output window, you can see that the ProjectName.Styles.css bundle is not tracked by HotReload (perhaps the bug is in there). This is very frustrating since my productivity drops without hotreload.

**Comment by TransparentPro-BV** [comment]
How is such a critical coding feature postponed to .Net 10 planning?

**Comment by danroth27** [comment]
I'm not able to reproduce this issue with the latest .NET 9 SDK, so we think this was fixed. If you're still seeing this issue, please let us know along with specific details of the .NET SDK version you are using and the project that reproduces the issue so that we can investigate.
