### ISSUE TITLE
Close outdated milestones

### ISSUE THREAD

**Issue by RoderickIveans** [dotnet/aspnetcore#57702]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Close outdated milestones

https://github.com/dotnet/aspnetcore/milestones

### Describe the solution you'd like

Close outdated milestones

**Comment by mkArtakMSFT** [comment]
Closed several. Chasing down some remaining milestones with open issues. Only 3 left it seems.

**Comment by mkArtakMSFT** [comment]
Closed all past milestones.

**Comment by RoderickIveans** [comment]
@mkArtakMSFT Why hasn't 7.0. x been closed?

**Comment by boukenka** [comment]
And also why hasn't [2.1.x](https://github.com/dotnet/aspnetcore/milestone/34) been closed as well?

**Comment by RoderickIveans** [comment]
@boukenka Because 2.1 is still a supported version on the. NET framework.

**Comment by boukenka** [comment]
> @boukenka Because 2.1 is still a supported version on the. NET framework.

Thanks for the information. I had no idea.
