### ISSUE TITLE
Blazor: the parent component always is disposed before the child components.

### ISSUE THREAD

**Issue by natural-tang** [dotnet/aspnetcore#57704]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a simple project, it contains a "Counter" page. In the "Counter" page, it contains a "Parent" component and a "Child" component.
When the "Counter" page disposed, the “parent" component are always disposed before the "Child" component.
``` razor
@implements IDisposable
<h3>Parent</h3>
<Child/>
@code {
    protected override void OnInitialized()
    {
        Console.WriteLine("Parent initialized");
    }
    public void Dispose()
    {
        Console.WriteLine("Parent disposed");
    }
}

@implements IDisposable
<h3>Child</h3>
@code {
    protected override void OnInitialized()
    {
        Console.WriteLine("Child initialized");
    }
    public  void Dispose()
    {
        Console.WriteLine("Child disposed");
    }
}

@page "/counter"
<PageTitle>Counter</PageTitle>
<Parent/>
```

The output:
```
Parent initialized
Child initialized
Parent disposed
Child disposed
```

I debug it by dnspy and found :
In the `Microsoft.AspNetCore.Components.RenderTree.Renderer` class, the `AttachAndInitComponent` function will add the each component state to the `_componentStateById` field from parent component to child component.

But in the `Dispose` function, it will dispose each component by  `_componentStateById` field, so the parent component always are disposed first.

### Expected Behavior

I hope the child components can be disposed first.

### Steps To Reproduce

1. Create a project with "Blazor Server App" template.
2. Add two component "Parent" and "Child".
3. Add "Parent" to Counter page.

### Exceptions (if any)

NA

### .NET Version

8.0.303

### Anything else?

NA

**Comment by javiercn** [comment]
@natural-tang thanks for contacting us.

There's no guaranteed order for disposal between components. Your Dispose implementations shouldn't rely on it.

**Comment by natural-tang** [comment]
If so, how should I ensure the components are disposed in order?
