### ISSUE TITLE
When the Fluent UI Grid is very long, it cannot fully render the background color and grid lines for the hidden sections

### ISSUE THREAD

**Issue by YJFSS** [dotnet/aspnetcore#57721]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

错误如下：
![G1](https://github.com/user-attachments/assets/9fd74305-b96f-41af-94f8-7e638acd4cf8)
![G1](https://github.com/user-attachments/assets/063a6ec9-02e9-436a-b2e9-252858479e64)

### .NET Version

NETCORE 8.0

**Comment by javiercn** [comment]
This issue was moved to microsoft/fluentui-blazor#2625
