### ISSUE TITLE
HttpRequest.BodyReader.ReadAsync stops host from responding under load (from Crank) with body > 5000 bytes

### ISSUE THREAD

**Issue by gradx** [dotnet/aspnetcore#57720]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The following [command ](https://github.com/gradx/PipeReaderIssue/blob/42424fc88d4027b674c29d223c8666d208feaacc/Genie.Web.Api/Program.cs#L8)hangs the server and stop serving requests with a payload of ~5000 bytes **in just a few seconds**.  With a smaller payload of 1200 and 800 bytes it performs fine.

>  await httpContext.Request.BodyReader.ReadAsync(new CancellationToken());

This behavior was observed while benchmarking the minimum payload sizes created from FIPS 203 and 204 encrypted requests

### Expected Behavior

The operation responds successfully as observed with smaller payloads.

### Steps To Reproduce

1. Clone the https://github.com/gradx/PipeReaderIssue
2. Edit the path in [Crank/benchmark.yaml](https://github.com/gradx/PipeReaderIssue/blob/42424fc88d4027b674c29d223c8666d208feaacc/Crank/benchmark.yaml#L25)
>         bodyFile: C:\Temp\help2\GenieDotNet\SharedFiles\EncryptionRequests\kyber_dilithium.req
3. Start the crank agent
4. Run start_crank.bat from the Crank directory

### .NET Version

8.0.400

**Comment by amcasey** [comment]
@gradx Thanks for the detailed repro.  Do you see the same slowdown if you call [`AdvanceTo`](https://learn.microsoft.com/dotnet/api/system.io.pipelines.pipereader.advanceto) after `ReadAsync`?

**Comment by gradx** [comment]
> @gradx Thanks for the detailed repro. Do you see the same slowdown if you call [`AdvanceTo`](https://learn.microsoft.com/dotnet/api/system.io.pipelines.pipereader.advanceto) after `ReadAsync`?

I added your suggestion:

`httpContext.Request.BodyReader.AdvanceTo(read.Buffer.Start, read.Buffer.End);`

and it works as expected!  

Thank you for your assistance.   You may close the issue if you so choose.
