### ISSUE TITLE
unable to gracefully handle Blazor component rendering errors, such as Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]

### ISSUE THREAD

**Issue by aravinda-sn** [dotnet/aspnetcore#57737]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

**Original issue #57724 is not resolved:
 https://github.com/dotnet/aspnetcore/issues/57724**
 
 While it is theoretically possible to extend ErrorBoundaryBase, its CurrentException attribute is read-only, and the Recover method is not extensible, limiting its customization. Access to the ErrorBoundaryBase source code would be invaluable to better understand these constraints and explore potential workarounds. I am still seeking a resolution for this issue.
 
 Description from issue 5774
 
 We are currently unable to gracefully handle Blazor component rendering errors, such as Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]. Here is the desired behavior and challenges we face:

Desired Behavior: We want to log these rendering errors to Azure App Insights or Serilog without disrupting the user experience. These errors are not critical and should not stop the application from rendering components as usual.
Issues with ErrorBoundary: Using ErrorBoundary results in rendering an ErrorComponent once an exception occurs. This is not the desired outcome, as we want to continue rendering the original component.
Lack of Customization Options: Although Blazor is open source, classes like ErrorBoundaryBase and ComponentBase are not easily customizable, limiting our ability to handle errors as needed.
Looking for a Solution: We need a way to log errors such as Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100] without altering the rendering behavior of components. Any suggestions or guidance on achieving this would be greatly appreciated.

### Exceptions (if any)

Error Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]

### .NET Version

8

**Comment by javiercn** [comment]
Closing this issue in favor of the original one.

https://github.com/dotnet/aspnetcore/issues/57724

**Comment by aravinda-sn** [comment]
Hi javiercn, this issue is still not resolved. Not sure why it is being closed. While it is theoretically possible to extend ErrorBoundaryBase, its CurrentException attribute is read-only, and the Recover method is not extensible, limiting its customization. Access to the ErrorBoundaryBase source code would be invaluable to better understand these constraints and explore potential workarounds. I am still seeking a resolution for this issue.
