### ISSUE TITLE
Error serving Blazor Framework files when using MapStaticAssets and UseBlazorFrameworkFiles together.

### ISSUE THREAD

**Issue by hwoodiwiss** [dotnet/aspnetcore#57756]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I spent a while trying to find out why the Blazor framework static assets files in my API project (built from a referenced Blazor WASM project) weren't being served when using `MapStaticAssets`, instead returning a 500 status code, as the requests reached the end of the request handling pipeline without being handled.

### Expected Behavior

I would expect the framework files to be returned, ideally using `MapStaticAssets` endpoints so that the compressed version can be served. I know it's not ideal to have these together, one supersedes the other in my use case, I think it should still fallback to a positive outcome, rather than erroring.

### Steps To Reproduce

There is a minimal reproduction available here:
https://github.com/hwoodiwiss/ReproAspnetcore57756

Build with `./build/publish.ps1 --RuntimeIdentifier <your-rid>` and run from `/artifacts/publish/ReproAspnetcore57756\release_<your-rid>/`

### Exceptions (if any)

```
 System.InvalidOperationException: The request reached the end of the pipeline without executing the endpoint: ''. Please register the EndpointMiddleware using 'IApplicationBuilder.UseEndpoints(...)' if using routing.
         at Microsoft.AspNetCore.Builder.ApplicationBuilder.<>c.<Build>b__25_0(HttpContext context)
         at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Components.WebAssembly.Server.ContentEncodingNegotiator.InvokeAsync(HttpContext context)
         at Microsoft.AspNetCore.Builder.ComponentsWebAssemblyApplicationBuilderExtensions.<>c__DisplayClass3_0.<<UseBlazorFrameworkFiles>b__2>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

(Exception updated from minimal repro)

### .NET Version

9.0.100-preview.7.24407.12

### Anything else?

I spent some time digging into why this happens.

UseBlazorFrameworkFiles branches the request pipeline when the path starts with `/_framework`, meaning in that case, there is only the `ContentEncodingNegotiator` middleware and `StaticFileMiddleware` that it then adds, [here](https://github.com/dotnet/aspnetcore/blob/4bc867dee200dffb10c9e3693b875311407bdfc6/src/Components/WebAssembly/Server/src/ComponentsWebAssemblyApplicationBuilderExtensions.cs#L42). That means that if the `StaticFileMiddleware` doesn't resolve a file, and instead calls `_next(context)`, we'll hit the end of the branched pipeline without having responded.

When `MapStaticAssets` is used, `StaticFileMiddleware` will always call `_next(context)` when the asset to be returned is in the staticwebassets.endpoints.json, as the `EndpointRoutingMiddleware` will have set the endpoint for the request earlier in the pipeline, so [this](https://github.com/dotnet/aspnetcore/blob/4bc867dee200dffb10c9e3693b875311407bdfc6/src/Middleware/StaticFiles/src/StaticFileMiddleware.cs#L60) check will fail, leaving us in a position where requests to mapped `/_framework` files will always fail.

I think the fix would be to add `context.GetEndpoint()?.RequestDelegate is null` to the conditions for branching the pipeline in `ComponentsWebAssemblyApplicationBuilderExtensions`. Happy to raise the fix if you agree.
 
### Workaround

This can be worked around by just removing `UseBlazorFrameworkFiles` and allowing `MapStaticAssets` to return the files.
I had originally opened this as a docs issue to add this as a recommendation to the docs.

cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/33571

**Comment by javiercn** [comment]
@hwoodiwiss thanks for contacting us.

Do you have a small repro?

In this case there are certain aspects about ordering that are important. I suspect you aren't calling `app.UseRouting()` explicitly, which is not normally a problem if the file is not mapped as an endpoint.

You should be able to make this work by calling

```
app.UseBlazorFrameworkFiles();
app.UseRouting();
...
app.MapStaticAssets();
```

In general, we don't think that it's important to make `app.UseBlazorFrameworkFiles` work alongside `app.MapStaticAssets` because the latter supersedes the other one.

In fact, it's not necessary to even call `UseBlazorFrameworkFiles` in 8.0 and onwards, since it's automatically called when invoking `AddInteractiveWebAssemblyComponents`.

**Comment by hwoodiwiss** [comment]
Hey @javiercn, that makes sense, this isn't something that I think there's really a use-case for, I was more looking to blunt a sharp edge moving between `UseBlazorFrameworkFiles` and `MapStaticAssets`, though I think in my case the `UseBlazorFrameworkFiles`, my WASM project was being compiled standalone and served as static content.

I still don't think it would be a _bad_ idea adding the `context.GetEndpoint()?.RequestDelegate is null` guard into the MapWhen condition for `UseBlazorFrameworkFiles`, but it's more just to allow it to do nothing now it isn't needed rather than to support any particular use-case.

**Comment by hwoodiwiss** [comment]
I've updated with a minimal repro, I'd be interested in your thoughts re: making this a little more friendly when you are using `UseBlazorFrameworkFiles` and `MapStaticAssets` together, even if that isn't _really_ a correct usage.
