### ISSUE TITLE
How can one measure how long returning a static file takes?

### ISSUE THREAD

**Issue by notemac** [dotnet/aspnetcore#57763]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

To measure how long it took to transfer the static file to the client.

### Describe the solution you'd like

`
public Action<StaticFileResponseContext> OnAfterResponse { get; set; }

public Func<StaticFileResponseContext, Task> OnAfterResponseAsync { get; set; }
`

### Additional context

I see in log file:
`2024-09-09 17:07:31.9918|INFO|Microsoft.AspNetCore.Hosting.Diagnostics|Request finished HTTP/1.1 GET http://localhost:5237/test.mp4 - 206 5167273 video/mp4 195.1250ms`
How to measure how long it took to transfer the static file to the client when using StaticFileExtensions.UseStaticFiles method?

**Comment by amcasey** [comment]
The [`http.server.request.duration`](https://github.com/dotnet/aspnetcore/blob/ffd5a38ecc618cac8c424a78ea8f452779120276/src/Hosting/Hosting/src/Internal/HostingMetrics.cs#L29) metric seems potentially relevant.

It's worth noting that neither approach will indicate how long it took the client to actually receive the file - only how long it took aspnetcore to push it into the OS buffer.

**Comment by amcasey** [comment]
More on metrics: https://learn.microsoft.com/aspnet/core/log-mon/metrics/metrics
An example of how to do it with middleware: https://weblogs.asp.net/jeff/asp-net-core-middleware-to-measure-request-processing-time

**Comment by amcasey** [comment]
Please let us know if none of the existing approaches work for you.
