### ISSUE TITLE
Blazor Server Side: await Task.Delay needed in order to get UI to refresh

### ISSUE THREAD

**Issue by wstaelens** [dotnet/aspnetcore#57781]
We are experiencing the same issue as described in the workaround here below. In earlier versions of blazor we did not need to add an `await Task.Delay(..);` but now to get our UI to refresh we have to add it otherwise a loading panel does not show.
   
   We have this basic code ( https://docs.devexpress.com/Blazor/DevExpress.Blazor.DxLoadingPanel#display-a-loading-panel ) in a big Blazor Server Side project .net 8 and without adding `await Task.Delay(1000);`  the DxLoadingPanel does not show.
   
   something must have changed inside blazor core.
   
              I've found a work-around:

``` csharp
async Task RunSearchAsync()
{
    Searching = true;
    StateHasChanged();
    await Task.Delay(1); // <-- why is this needed to refresh the UI?
    SearchResults = await GetSearchResults();
    Searching = false;
    StateHasChanged();
}
```

_Originally posted by @panesofglass in https://github.com/dotnet/aspnetcore/issues/22286#issuecomment-635056036_

**Comment by javiercn** [comment]
@wstaelens thanks for contacting us. 

It's impossible for us to give pointed guidance without knowing the context in which that method is being invoked. What we would say is:
* If that method is directly invoked as a result of an EventHandler, you don't need the `StateHasChanged` call nor the `await Task.Delay(1)` (which by the way, what you want is `Task.Yield()`)

If that is a helper method that is invoked from a handler and/or a lifecycle method as in

```
Task OnInitializeAsync()
{
  await RunSearchAsync();
  ...
}
```

Then you need to understand that Blazor can only see the task returned from `InitializedAsync`, not the task returned by `RunSearchAsync`. The behavior in that case is to trigger a render right after `OnInitializedAsync` is called and trigger another render if the task is async (is not completed) when it does so.

**Comment by SiphonRS** [comment]
@wstaelens I believe the behavior you're describing is explained here. https://learn.microsoft.com/en-us/aspnet/core/blazor/components/rendering?view=aspnetcore-8.0#statehaschanged

**Comment by wstaelens** [comment]
@SiphonRS  looks indeed similar. Thanks for pointing out. Also the part of replacing await Task.Delay with await Task.Yield.

**Comment by javiercn** [comment]
@wstaelens did you figure what's going on?

We don't have enough information to understand exactly what problem you are running into. It's unlikely that there's a bug in this area since it's a very well covered part of the framework, but if you are still running into issues, please provide a minimal repro project so that we can make progress.

**Comment by wstaelens** [comment]
> @wstaelens did you figure what's going on?
> 
> We don't have enough information to understand exactly what problem you are running into. It's unlikely that there's a bug in this area since it's a very well covered part of the framework, but if you are still running into issues, please provide a minimal repro project so that we can make progress.

You can close it, I was missing this part as pointed out by @SiphonRS :

> Components are enqueued for rendering, and they aren't enqueued again if there's already a pending rerender. If a component calls [StateHasChanged](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.componentbase.statehaschanged) five times in a row in a loop, the component only renders once. This behavior is encoded in [ComponentBase](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.componentbase), which checks first if it has queued a rerender before enqueuing an additional one.

**Comment by javiercn** [comment]
@wstaelens thanks!
