### ISSUE TITLE
Would it be possible to separate the AspNetCoreCompat DbContext and CookieInterop classes in separate NuGet packages?

### ISSUE THREAD

**Issue by mderriey** [dotnet/aspnetcore#5779]
Hi there :wave:,

We have an existing EF6-, Identity v2-based solution that targets .NET 4.5.1.

We want to create a new ASP.NET Core 2.0 application that targets the same database.
Since ASP.NET Core only supports Identity v3, it means the schema needs to be updated.

This is where the `Microsoft.AspNet.Identity.AspNetCoreCompat` comes into play.
From what I understand, this package allows an application based on Identity v2 to be compatible with the Identity v3 schema. This is done by using the classes in that package.

Now, in our case, since we want to keep the Identity v2 bits running as-is, we're not interested in sharing cookies between the v2 and v3 apps. Still, the package comes with the OWIN-compatible secure data format that allows it to decrypt cookies issues with the new .NET Core DataProtection stack.

This has two implications for us:

 - The need to upgrade every single project that uses the ASP.NET Identity v2 to .NET 4.6.1 to be able to install the NuGet package
 - Since it depends on the new DataProtection stack and the OWIN-interop, it installs 27 dependent packages that we don't use

Is there a possibility to separate these two capabilities in separate NuGet packages?

**Comment by HaoK** [comment]
Compat package no longer exists even so closing
