### ISSUE TITLE
Add API metadata to endpoints created by MapIdentityApis

### ISSUE THREAD

**Issue by mikekistler** [dotnet/aspnetcore#57804]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

The `MapIdentityAPIs` extension method added in .NET 8 gives users an easy way to add APIs for ASP.NET Identity to their app. However, these APIs lack certain metadata to describe their functionality and features in a generated OpenAPI document. In particular
- endpoints do not have a summary or description
- request body properties do not have descriptions or validation information (e.g. allowed characters, min/max length for strings, formats such as email)
- response body properties do not have descriptions

Lack of this metadata makes the APIs hard to consume both for humans and tooling such as AI-powered test generation tooling or GPT plugins.

### Describe the solution you'd like

IdentityAPI endpoints should include
- summary or description on all endpoints
- description on all request body properties
- validation attributes on request body properties where appropriate
- description on all response body properties

### Additional context

Lack of API metadata is more important now that ASP.NET has added support for generation of OpenAPI documents in .NET 8.

**Comment by gfoidl** [comment]
This is a duplicate of https://github.com/dotnet/aspnetcore/issues/57803, so I'm closing this one.

@mikekistler when I'm wrong, please drop a comment, so we can re-open this one.

**Comment by mikekistler** [comment]
This is not a dup of #57803. It's true that both deal with OpenAPI metadata but the type of metadata and means to include it are substantially different, to a degree that @halter73 and I concluded that two separate issues should be created.

**Comment by mikekistler** [comment]
Sorry ... this is a dup. This was a GitHub hiccup.
