### ISSUE TITLE
Issue with Swashbuckle when starting the api (v17.11)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#57861]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Issue-with-Swashbuckle-when-starting-the/10727067)._

---
[severity:I'm unable to use this version] [regression] [worked-in:17.10]
We have a web api project (. NET8) which renders a swagger page with swashbuckle (v6.7.1).
There are some custom operations done so the swagger output has a 'better form'. For this, we depend on the controllername which can be retrieved from the ApiDescription.ActionDescriptor.ControllerName.
Before we can retrieve it, we need to cast the Microsoft.AspNetCore.Mvc.Abstractions.ActionDescriptor to the Microsoft.AspNetCore.Mvc.Controllers.ControllerActionDescriptor type.

With the update from v17.10 to 17.11, that gives an InvalidCastException.
In the past, this bug was also introduced in v17.9 and solved in v17.9.6.

Code:

```csharp
public static IServiceCollection AddSwagger(this IServiceCollection services)
{
    services. AddSwaggerGen(c =>
    {
        // Ordering of operations
        c.OrderActionsBy(apiDesc => //type is Microsoft.AspNetCore.Mvc.ApiExplorer.ApiDescription
        {
            var controllerName = ((ControllerActionDescriptor)apiDesc.ActionDescriptor). ControllerName;
            var routeTemplate = ((ControllerActionDescriptor)apiDesc.ActionDescriptor). AttributeRouteInfo.Template ?? "";
            return $"{controllerName}_{apiDesc.HttpMethod}_{routeTemplate}";
        });

});

return services;
}
```

Exception:

```
System.InvalidCastException
  HResult=0x80004002
  Message=Unable to cast object of type 'Microsoft.AspNetCore.Mvc.Abstractions.ActionDescriptor' to type 'Microsoft.AspNetCore.Mvc.Controllers.ControllerActionDescriptor'.
  Source=CustomerName.Eloket.Web.Api
  StackTrace:
   at CustomerName.Eloket.Web.Api.Infrastructure.ServiceCollectionExtensions.<>c.<AddSwagger>b__7_3(ApiDescription apiDesc) in C:\Projects\CustomerName\Eloket\CustomerName.Eloket.Web.Api\Infrastructure\ServiceCollectionExtensions.cs:line 325
   at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)
   at System.Linq.EnumerableSorter`1.ComputeMap(TElement[] elements, Int32 count)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1. <GetEnumerator>d__19.MoveNext()
   at System.Linq.Lookup`2.Create(IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`2.GetEnumerator()
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator. <GeneratePathsAsync>d__12.MoveNext()

```

---
#### Feedback Bot on 8/20/2024, 06:21 PM: 

(private comment, text removed)
#### Feedback Bot on 8/22/2024, 02:41 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by captainsafia** [comment]
I suspect that what might be going on here is that you need to do some sort of type checking (`is ControllerActionDescriptor`) before casting the `apiDescription.ActionDescriptor` value. It's not always guaranteed to be a `ControllerActionDescriptor` for every route, especially if that route is a minimal API endpoint.

cc: @martincostello for any insights related to the way `OrderActionsBy` runs. I'm going to assume it gets called on every OpenApiOperation, not just those that come from a controller action and that might be why it is causing issues?

**Comment by martincostello** [comment]
While I don't understand why _just_ upgrading Visual Studio would cause this behaviour, Swashbuckle.AspNetCore 6.6.1+ has a `net8.0` target. This means that endpoints that it couldn't "see" before, such as those from Minimal APIs, are now visible, which is exposing the incorrect assumption in the code you're using to sort the endpoints.

The code should instead be something like this:

```csharp
public static IServiceCollection AddSwagger(this IServiceCollection services)
{
    services. AddSwaggerGen(c =>
    {
        c.OrderActionsBy(descriptor =>
        {
            if (descriptor is ControllerActionDescriptor controller)
            {
                var controllerName = controller.ActionDescriptor.ControllerName;
                var routeTemplate = controller.ActionDescriptor.AttributeRouteInfo.Template ?? "";
                return $"{controllerName}_{apiDesc.HttpMethod}_{routeTemplate}";
            }
            else
            {
                // Whatever you want to do for non-Controller endpoints
            }
        });
    });

    return services;
}
```

**Comment by ArnaudB88** [comment]
(I am the author of the devcommunity ticket)

@captainsafia @martincostello Thanks for the suggestion. The code above was actually the fix. The reason why I didn't implement the type check before is, I thought that all endpoint descriptors were from a different type, but in fact it was only one endpoint.

The actual cause is that we added a root endpoint in the program.cs:
```
var app = builder.Build();
...
app.MapGet("/", () => "Success");
```

Only this endpoint has a different descriptor type.
It seems that some VS versions (v17.11.x and v17.9.0-v17.9.6) pass this root endpoint through the swagger generation, and all other VS versions do not.

This ticket can be closed.

**Comment by captainsafia** [comment]
@ArnaudB88 Yep -- having a minimal endpoint in an app that would otherwise only contain controller-based APIs is exactly what would trigger this. Glad your issue has been resolved!
