### ISSUE TITLE
HostBuilder Build PhysicalFileProvider on hostingEnvironment.ContentRootPath

### ISSUE THREAD

**Issue by JtotheThree** [dotnet/aspnetcore#57867]
HostBuilder Build method creates a PhysicalFileProvider on the application root path (hostingEnvironment.ContentRootPath).

https://github.com/dotnet/runtime/blob/fd9b86ec392892646aa34b5f8f9c0712f36e5766/src/libraries/Microsoft.Extensions.Hosting/src/HostBuilder.cs#L247C17-L247C37

var physicalFileProvider = new PhysicalFileProvider(hostingEnvironment.ContentRootPath);

What is the purpose of scanning the entirety of the application root path on start up? Is this for watching files in wwwroot? Or for searching for assemblies?

Maybe there's a good reason I don't know of, but it seems odd as it could blindly add a significant amount of time to startup if there is a folder in the application root with a lot of data or a mounted network path in the application root that it has to crawl through.

Would this be better served adding the PhysicalFileProvder to IHostingEnvironment.WebRootPath instead?

**Comment by javiercn** [comment]
@JtotheThree thanks for contacting us.

Creating a Physical file provider doesn't involve any scanning of the application root on startup as you mention. 

The content root of the app represents the location content is located by default, which for development is typically the app folder, and for published apps is the publish folder. That's where things like appSettings, and other files that are not code, are typically located.

**Comment by JtotheThree** [comment]
> @JtotheThree thanks for contacting us.
> 
> Creating a Physical file provider doesn't involve any scanning of the application root on startup as you mention.
> 
> The content root of the app represents the location content is located by default, which for development is typically the app folder, and for published apps is the publish folder. That's where things like appSettings, and other files that are not code, are typically located.

Hmm, I'm wondering what else could be going on then. 
We have a cifs share with 500k files and if we mount that to the root application folder it takes aspnet a significant amount of time (1 hour) on the IHostBuilder Build step. We can see the files being listed on the file server. If we mount the network share to a path outside of the application root the issue completely goes away.

I've also confirmed this behavior on an unmodified aspnet sample container (mcr.microsoft.com/dotnet/samples:aspnetapp)
