### ISSUE TITLE
Blazor not rendering state changes within a foreach list

### ISSUE THREAD

**Issue by MorneZaayman** [dotnet/aspnetcore#57878]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The easiest way to see the issue is to look at the attached screen recording and to run up the sample application.

https://github.com/user-attachments/assets/930b4ef0-d641-4bca-9fec-fd112c69bf26

When clicking on of the buttons, a new value is added or removed from the `Values` list. The list boxes should update to show these changes. The `<p>` element within the component shows that the component **does** pick the changes up. When the button is clicked a second time, **then** the component only re-renders the foreach loop.

### Expected Behavior

The list boxes are updated immediately when the buttons are clicked.

### Steps To Reproduce

Run up the sample application and click on the buttons.
https://github.com/MorneZaayman/DEMO-BsMultiSelect

### .NET Version

8.0.400

**Comment by javiercn** [comment]
@MorneZaayman thanks for contacting us.

The call is happening though JS interop, which won't trigger a re-render of the component automagically. In that case you need to call `StateHasChanged` manually.

**Comment by MorneZaayman** [comment]
I am already calling `StateHasChanged` , and the `<p>` element in the component does update. If you can suggest where to put another `StateHasChanged` statement, I can try it, but I don't believe that is the issue as I have already tried putting it everywhere without success.

**Comment by mkArtakMSFT** [comment]
The issue you're facing here is that the multi-select component relies on the DOM state to get the correct options rendered. You call the `refresh` in the `OnParametersSet` method, where the DOM isn't yet updated. To make sure that the DOM is updated with all the changes, you can move that call to the `OnAfterRender` handler, as follows:
![image](https://github.com/user-attachments/assets/43cfc972-7266-445a-aad5-8a8eeb03af94)

**Comment by MorneZaayman** [comment]
Thank you for the advice, that works!
