### ISSUE TITLE
.NET 9 rc1 - script importmap not behaving as expected when App.razor is rendered.

### ISSUE THREAD

**Issue by kevin-weir** [dotnet/aspnetcore#57872]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

**Step 1**
> I created a vanilla Blazor Web App with no authentication and the Render mode set to Server.

**Step 2**
> I used libman to add Bootstrap@5.3.3 client library to the project.   See libman.json

**Step 3**
> A reference to the script bootstrap.bundle.min.js is NOT included in App.razor.  

**Step 4**

> When I run the application and then **view the page source** in the browser I see the following:

> <script type="importmap">{
>   "imports": {"./lib/bootstrap/dist/js/bootstrap.bundle.min.js": "./lib/bootstrap/dist/js/bootstrap.bundle.min.493y06b0oq.js"}
> }</script>
> 

### The Problem

Why is a reference to "bootstrap.bundle.min.js" included in importmap when there is no <script> reference to the file anywhere in the project?

[libman.json](https://github.com/user-attachments/files/17003087/libman.json)

### Expected Behavior

The expectation is the <script> importmap is empty or excluded altogether.

> <script type="importmap">{}</script>

This isn't a critical bug as I can work around the issue by removing "bootstrap.bundle.min.js" from "libman.json"   

### .NET Version

9.0.100-rc.1.24452.12

### Anything else?

Microsoft Visual Studio Community 2022 (64-bit) - Preview 
Version 17.12.0 Preview 2.0

**Comment by javiercn** [comment]
@kevin-weir thanks for contacting us.

JS importmaps need to be defined at the root of the document during the initial navigation, they can't be added later on to the page. By default we collect all the scripts and add them to the importmap. It's presence there doesn't cause any harm (the browser will not load nor process the file in any way until actually requested via an import statement or `<script type="module"  />`)

**Comment by kevin-weir** [comment]
Thanks for clarification.
