### ISSUE TITLE
GetGenericParameterConstraints() method changes on Net8

### ISSUE THREAD

**Issue by bifacil** [dotnet/aspnetcore#57873]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This VB test works on Net6 and it doesn't in Net8

```
    <TestMethod> Public Sub Net8BreakingChange()
        Assert.AreEqual(GetType(System.ValueType), GetType(Nullable(Of)).GetGenericArguments.Single.GetGenericParameterConstraints.SingleOrDefault)
    End Sub
```
### 

### Expected Behavior

I believe GetGenericParameterConstraints() should return  `GetType(System.ValueType)` since this is the type definition:

```
public partial struct Nullable<T> where T : struct
{
   [...]
}
```

### Steps To Reproduce

```
Assert.AreEqual(GetType(System.ValueType), GetType(Nullable(Of)).GetGenericArguments.Single.GetGenericParameterConstraints.SingleOrDefault)
```

### .NET Version

8.0.304

### Anything else?

I've not found any documented change on "GetGenericParameterConstraints" method, so I expect the same behaviour on Net6 and Net8

**Comment by martincostello** [comment]
This looks like an issue for dotnet/runtime as it doesn't appear to be specific to ASP.NET Core.

**Comment by bifacil** [comment]
Ok. I'll open it there right now.

**Comment by bifacil** [comment]
I open it here: https://github.com/dotnet/runtime/issues/107832

Close this one.
