### ISSUE TITLE
Blazor Minify Isolated CSS - Built in Feature

### ISSUE THREAD

**Issue by Beblia** [dotnet/aspnetcore#57883]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

I would like to minify Isolated CSS without using any library. Built in feature...
<link href="{ASSEMBLY NAME}.styles.css" rel="stylesheet">

Thank you.

**Comment by javiercn** [comment]
@Beblia thanks for contacting us.

This is not a feature that we are considering any time soon. In general, minification doesn't offer a lot of benefits when compression is applied to the response, which as of .NET 9.0 happens for all assets in the app automatically.

**Comment by Beblia** [comment]
Got it. Thank you.
