### ISSUE TITLE
Blazor WebAssembly uses the AuthorizationMessageHandler exception

### ISSUE THREAD

**Issue by wgh2019** [dotnet/aspnetcore#57956]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am following these instructions from the documentation for attaching authentication tokens to outgoing HTTP requests:
like the documentation

https://learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/additional-scenarios?view=aspnetcore-8.0#handle-token-request-errors

![image](https://github.com/user-attachments/assets/8ce985f3-cf34-493e-866d-1939e0ebbca7)

Using a AuthorizationMessageHandler as described does not work at all; the request doesn't even send to the API.

Either something is broken or the documentation is unclear.

Can't the AuthorizationMessageHandler be used directly?

My code

```
        public static async Task Main(string[] args)
        {
            var builder = WebAssemblyHostBuilder.CreateDefault(args);
            builder.RootComponents.Add<App>("#app");
            builder.RootComponents.Add<HeadOutlet>("head::after");
            builder.Services.AddApiAuthorization();
            builder.Services.AddScoped<IAccessTokenProvider, CustomerAccessTokenProvider>();
            builder.Services.AddScoped<AuthorizationMessageHandler>();
            builder.Services.AddScoped(sp => new HttpClient(sp.GetRequiredService<AuthorizationMessageHandler>().ConfigureHandler(
                authorizedUrls: new[] { builder.HostEnvironment.BaseAddress }
                ))
            { BaseAddress = new Uri(builder.HostEnvironment.BaseAddress) });

            await builder.Build().RunAsync();
        }

```

### Expected Behavior

Authorization: Bearer token should be attached to outgoing request

### Exceptions (if any)

```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: The inner handler has not been assigned.
System.InvalidOperationException: The inner handler has not been assigned.
   at System.Net.Http.DelegatingHandler.SetOperationStarted()
   at System.Net.Http.DelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Components.WebAssembly.Authentication.AuthorizationMessageHandler.<>n__0(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Components.WebAssembly.Authentication.AuthorizationMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at System.Net.Http.Json.HttpClientJsonExtensions.<<FromJsonAsyncCore>g__Core|12_0>d`2[[BlazorApp2.Pages.Weather.WeatherForecast[], BlazorApp2, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[System.Text.Json.JsonSerializerOptions, System.Text.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]].MoveNext()
   at BlazorApp2.Pages.Weather.OnInitializedAsync() in E:\Users\wgh\source\repos\BlazorApp2\BlazorApp2\Pages\Weather.razor:line 44
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
```

### .NET Version

net 8.0

**Comment by MackinnonBuck** [comment]
Thanks for reaching out, @wgh2019.

Per the [docs](https://learn.microsoft.com/aspnet/core/blazor/security/webassembly/additional-scenarios#attach-tokens-to-outgoing-requests), you'll need to call `AddHttpMessageHandler()`.

Could you please try doing this and letting us know if that solves the issue? Thanks.

**Comment by wgh2019** [comment]
![image](https://github.com/user-attachments/assets/da83169a-b546-4b25-9f0a-f7fada4ae641)

Here's '...' What code was omitted?  can this code be completed?

![image](https://github.com/user-attachments/assets/6557d3b8-9a17-4e0c-9c61-37de011d99e6)
Is new HttpClient(HttpMessageHandler handler) the equivalent of AddHttpMessageHandler here?

Can give a complete demo

**Comment by wgh2019** [comment]
> 感谢您的联系，.
> 
> 根据[文档](https://learn.microsoft.com/aspnet/core/blazor/security/webassembly/additional-scenarios#attach-tokens-to-outgoing-requests)，您需要调用 .`AddHttpMessageHandler()`
> 
> 您能否尝试执行此操作并告诉我们这是否解决了问题？谢谢。

HI，Can you give me  a complete demo

**Comment by halter73** [comment]
> Can't the AuthorizationMessageHandler be used directly?

No, it has to be added with something like `AddHttpMessageHandler<AuthorizationMessageHandler>()`. Even though the part of the docs you took a screenshot of doesn't include `AddHttpMessageHandler`, that's left out and implied by the ellipses `...`.

![image](https://github.com/user-attachments/assets/8a8e70af-0644-4b72-ad10-bd8a6a480e3d)

The call you have to `builder.Services.AddApiAuthorization()` also looks unnecessary. That should be removed.

> HI，Can you give me a complete demo

It should look something more like this which is closer to what's shown in the "Attach tokens to outgoing requests" section of the docs.

```
using BlazorApp3.Client;
using Microsoft.AspNetCore.Components.Web;
using Microsoft.AspNetCore.Components.WebAssembly.Authentication;
using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
 
var builder = WebAssemblyHostBuilder.CreateDefault(args);
builder.RootComponents.Add<App>("#app");
builder.RootComponents.Add<HeadOutlet>("head::after");
 
builder.Services.AddHttpClient("BlazorApp3.ServerAPI", client => client.BaseAddress = new Uri(builder.HostEnvironment.BaseAddress))
    .AddHttpMessageHandler<BaseAddressAuthorizationMessageHandler>();
 
// Supply HttpClient instances that include access tokens when making requests to the server project
builder.Services.AddScoped(sp => sp.GetRequiredService<IHttpClientFactory>().CreateClient("BlazorApp3.ServerAPI"));
 
builder.Services.AddApiAuthorization();
 
await builder.Build().RunAsync();
```

**Comment by wgh2019** [comment]
> > 不能直接使用 AuthorizationMessageHandler 吗？
> 
> 不，它必须添加类似 .即使您截取了文档的屏幕截图部分不包括 ，但省略号将其遗漏并暗示了 。`AddHttpMessageHandler<AuthorizationMessageHandler>()``AddHttpMessageHandler``...`
> 
> ![图像](https://private-user-images.githubusercontent.com/54385/370376682-8a8e70af-0644-4b72-ad10-bd8a6a480e3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyMjg4NDksIm5iZiI6MTcyNzIyODU0OSwicGF0aCI6Ii81NDM4NS8zNzAzNzY2ODItOGE4ZTcwYWYtMDY0NC00YjcyLWFkMTAtYmQ4YTZhNDgwZTNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI1VDAxNDIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2OGI2ZDVkYzU2ZWY1MjllYTFjZDE3M2E1ODcyZTc4NWFiMjY2OTVlMmM5NjAzOTA4YjRiNWEzY2M4YzJkMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PzuxuYno2TwEXx6bsOzm5OUnq1iDmNMB2Ay42mLy2G8)
> 
> 您必须拨打的电话看起来也是不必要的。那应该被删除。`builder.Services.AddApiAuthorization()`
> 
> > 嗨，你能给我一个完整的 demo 吗
> 
> 它应该看起来更像这样，更接近文档的 “Attach tokens to outgoing requests” 部分中显示的内容。
> 
> ```
> using BlazorApp3.Client;
> using Microsoft.AspNetCore.Components.Web;
> using Microsoft.AspNetCore.Components.WebAssembly.Authentication;
> using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
>  
> var builder = WebAssemblyHostBuilder.CreateDefault(args);
> builder.RootComponents.Add<App>("#app");
> builder.RootComponents.Add<HeadOutlet>("head::after");
>  
> builder.Services.AddHttpClient("BlazorApp3.ServerAPI", client => client.BaseAddress = new Uri(builder.HostEnvironment.BaseAddress))
>     .AddHttpMessageHandler<BaseAddressAuthorizationMessageHandler>();
>  
> // Supply HttpClient instances that include access tokens when making requests to the server project
> builder.Services.AddScoped(sp => sp.GetRequiredService<IHttpClientFactory>().CreateClient("BlazorApp3.ServerAPI"));
>  
> builder.Services.AddApiAuthorization();
>  
> await builder.Build().RunAsync();
> ```

![image](https://github.com/user-attachments/assets/4477f8f8-37b1-41c1-943b-23a8e2679b65)
I've implemented this way, but I can't use (builder. Services.AddScoped(sp =>new HttpClient(sp. GetRequiredService<AuthorizationMessageHandler>()).I've implemented this way, but I can't use (builder. Services.AddScoped(sp =>new HttpClient(sp. GetRequiredService<AuthorizationMessageHandler>()).

Looking at the official documentation, people mistakenly think that it can be used directly (sp. GetRequiredService<AuthorizationMessageHandler>()) to get the built-in AuthorizationMessageHandler
It's like sp. GetRequiredService<IHttpClientFactory>() to get the built-in IHttpClientFactory

Whether the official documentation wants to mark this is unavailable. You must use .AddHttpMessageHandler() to do so

**Comment by wgh2019** [comment]
> > Can't the AuthorizationMessageHandler be used directly?
> 
> No, it has to be added with something like `AddHttpMessageHandler<AuthorizationMessageHandler>()`. Even though the part of the docs you took a screenshot of doesn't include `AddHttpMessageHandler`, that's left out and implied by the ellipses `...`.
> 
> ![image](https://private-user-images.githubusercontent.com/54385/370376682-8a8e70af-0644-4b72-ad10-bd8a6a480e3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNDQyMjAsIm5iZiI6MTcyNzI0MzkyMCwicGF0aCI6Ii81NDM4NS8zNzAzNzY2ODItOGE4ZTcwYWYtMDY0NC00YjcyLWFkMTAtYmQ4YTZhNDgwZTNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI1VDA1NTg0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4NDI1YThjNWZlY2E4ZjBmM2RlMTUwZDY2ZTE2NWZkZjc1MzEzYWZmOTc2ZWRhMzQ2ZTRmYjVlOTI1NjVkZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HIegbTIE0BFJcx0Hn8So6gt2sXb5gDfe9cm6x_d7VqM)
> 
> The call you have to `builder.Services.AddApiAuthorization()` also looks unnecessary. That should be removed.
> 
> > HI，Can you give me a complete demo
> 
> It should look something more like this which is closer to what's shown in the "Attach tokens to outgoing requests" section of the docs.
> 
> ```
> using BlazorApp3.Client;
> using Microsoft.AspNetCore.Components.Web;
> using Microsoft.AspNetCore.Components.WebAssembly.Authentication;
> using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
>  
> var builder = WebAssemblyHostBuilder.CreateDefault(args);
> builder.RootComponents.Add<App>("#app");
> builder.RootComponents.Add<HeadOutlet>("head::after");
>  
> builder.Services.AddHttpClient("BlazorApp3.ServerAPI", client => client.BaseAddress = new Uri(builder.HostEnvironment.BaseAddress))
>     .AddHttpMessageHandler<BaseAddressAuthorizationMessageHandler>();
>  
> // Supply HttpClient instances that include access tokens when making requests to the server project
> builder.Services.AddScoped(sp => sp.GetRequiredService<IHttpClientFactory>().CreateClient("BlazorApp3.ServerAPI"));
>  
> builder.Services.AddApiAuthorization();
>  
> await builder.Build().RunAsync();
> ```
![image](https://github.com/user-attachments/assets/dfe2fd4d-efe5-44c3-b49b-fa108fed81d1)

I've implemented this way, but I can't use (builder. Services.AddScoped(sp =>new HttpClient(sp. GetRequiredService(AuthorizationMessageHandler)).

Looking at the official documentation, people mistakenly think that it can be used directly (sp. GetRequiredService()) to get the built-in AuthorizationMessageHandler
It's like sp. GetRequiredService(IHttpClientFactory) to get the built-in HttpClientFactory

Whether the official documentation wants to mark this is unavailable. You must use .AddHttpMessageHandler() to do so

![image](https://github.com/user-attachments/assets/fc1e223b-bb04-4795-bffb-f96d1097afea)

The official documentation would make one think that you could get the original AuthorizationMessageHandler directly this way。use builder. Services.AddScoped(sp =>new HttpClient(sp. GetRequiredService(AuthorizationMessageHandler)

**Comment by wgh2019** [comment]
Unresolved
