### ISSUE TITLE
[GB18030] There is an additional letter "j" when press the "Tab" key multiple times in a MVC project using Chinese characters as the project name.

### ISSUE THREAD

**Issue by Rita003** [dotnet/aspnetcore#57983]
**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install SDK 8.0.401

**REPRO STEPS**
1. Open CMD, create a MVC project using Chinese characters as the project name and go to project folder:
```
dotnet new mvc -o mvc项目1
cd mvc项目1
```
2. Press the "Tab" key multiple times in MVC project

**ACTUAL**
There is an additional letter "j"
![MVC](https://github.com/user-attachments/assets/45059824-2c12-4a13-a752-5ce6135f39a9)

**Comment by BrennanConroy** [comment]
That looks like a command prompt issue, nothing related to ASP.NET Core.
