### ISSUE TITLE
RenderMode names really hard to explain and confused a lot beginners.

### ISSUE THREAD

**Issue by FireTruck007** [dotnet/aspnetcore#58023]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

For example:
InteractiveServer = prerender +   InteractiveServer(prerender:false). 
null = prerender/SSR

These are hard to explain to new programmers  and not good for attract people to use blazor.

### Describe the solution you'd like

It would be better if the names are more clearly to understand. Such as:
1. SSR
2. Server   :   mode that without prerender
3. WASM   :  mode that without prerender
4. MixServer   : (= SSR + Server).
5. MixWASM   : (= SSR + WASM).
6. MixAuto   :   (= SSR + Server + WASM)

**Comment by javiercn** [comment]
@FireTruck007 thanks for contacting us.

There's a learning curve to every concept and it's not clear to us that your proposal is better to the current framework implementation. In addition to that, this is not something that we can act on, as even if we wanted to change it, it would result in more confusion and bigger problems at that point.
