### ISSUE TITLE
libreria QuickGrid net core 8

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#58040]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/libreria-QuickGrid-net-core-8/10668070)._

---
It seems to me that there is nothing in the QuickGrid library that provides a built-in event-method or a mechanism designed specifically to intercept page navigation events, i.e. to know by code which page is selected and consequently the row of the selected data. The need arises from the desire to be able to use the cursor keys to select the desired line while browsing.

Greetings
THANK YOU

---
#### Feedback Bot on 5/27/2024, 10:50 PM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further. You will hear from us in about a week on our next steps.</p>

**Comment by javiercn** [comment]
Thanks for contacting us.

This is not something that QuickGrid will or should be responsible for. It's best handled by your app outside of quickgrid itself.
