### ISSUE TITLE
Setting PathBase breaks Browserlink

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#58046]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Setting-PathBase-breaks-Browserlink/10700371)._

---
Hi,
I have a asp.net 8 project that's using a PathBase, like this:

```cs
app.UsePathBase("/myPrefix");
```

With the following launchSettings.json:

```js
{
  "profiles": {
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true
    }
  },
  "iisSettings": {
    "windowsAuthentication": true,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "https://localhost:44320/myPrefix",
      "sslPort": 0
    }
  }
}
```

Now, during debugging, the Browserlink files are not being found:
![image.png](https://aka.ms/dc/image?name=B4bda8dd9ec7046c9a7fe73c7f41ce487638562079303507538_20240710-133209-image.png&tid=4bda8dd9ec7046c9a7fe73c7f41ce487638562079303507538)

The files are searched for at these URLs:
https://localhost:44320/_vs/browserLink
https://localhost:44320/_framework/aspnetcore-browser-refresh.js

But they're only available here: (manually calling this URL works and gives me the scripts)
https://localhost:44320/**myPrefix**/_vs/browserLink
https://localhost:44320/**myPrefix**/_framework/aspnetcore-browser-refresh.js

Is there any way to configure Browserlink to point to the right URLs? 

I did not find anything in the [documentation page](https://learn.microsoft.com/en-us/aspnet/core/client-side/using-browserlink?view=aspnetcore-8.0)

---
#### Feedback Bot on 7/10/2024, 07:16 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 7/12/2024, 09:56 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

**Comment by muraterkan** [comment]
After updating the latest version of insider (the first version before this message), my working routes stopped working. I had to change the signatures of the methods by using extra parameters to access them.
