### ISSUE TITLE
In Blazor WASM with with Open ID Connect how can you force an Auth/ID Token refresh

### ISSUE THREAD

**Issue by baynezy** [dotnet/aspnetcore#58058]
### Discussed in https://github.com/dotnet/aspnetcore/discussions/58014

<div type='discussions-op-text'>

<sup>Originally posted by **baynezy** September 22, 2024</sup>
I have a Blazor WASM app integrated with my IdP via Open ID Connect. There are custom claims that we need that are stored in the ID Token and Auth Token. This all works fine in the most part. However, there are a couple of expected situations where a particular process will update source data for these and so the data in the tokens has become stale. So in the app I would like to force the refreshing of these tokens from the IdP so they have the latest information.

I have tried, unsuccessfully, to find how to so this. However, my Google-fu must be off as I have not found anything that even points me in the right direction.

If it is relevant I am using .Net 8 and my IdP is Auth0.

Anyone have any pointers?</div>

**Comment by halter73** [comment]
We have no built-in support to refresh the token in Blazor WASM if it is still valid. You can start a new login flow if you need a new token.
