### ISSUE TITLE
Improve documentation for remote authentication with Blazor

### ISSUE THREAD

**Issue by joepetrakovich** [dotnet/aspnetcore#58075]
I'm trying to set up remote authentication with a Blazor Server app alongside a legacy Web Forms app that uses Forms Authentication but there are some missing pieces that I can't quite figure out.

The [docs](https://devblogs.microsoft.com/dotnet/incremental-asp-net-migration-tooling-preview-2/),  [other docs](https://learn.microsoft.com/en-us/aspnet/core/migration/inc/remote-authentication?view=aspnetcore-7.0) suggest that "the ASP.NET Core app will see the identity of users logged in to the ASP.NET app and if the ASP.NET Core app challenges authentication, it should redirect to the login page of the ASP.NET app" but it seems like this only applies to ASP.NET Core controller routes.

In Blazor, when I set everything up and use an [Authorize] attribute on a razor page in conjunction with a AuthorizeRouteView, it _does_ seem to properly detect if I am logged into the legacy app and shows the appropriate <NotAuthorized> view if not, however there is no automatic routing to the legacy login page (and thus no subsequent redirect _after_ logging in).  

Is there something I've misconfigured or do I need to manually set this up somehow?  Some docs would be great.

I tried setting up the RedirectToLogin component [mentioned here](https://learn.microsoft.com/en-us/aspnet/core/blazor/security/?view=aspnetcore-7.0#customize-unauthorized-content-with-the-router-component) with a manual navigation to the legacy login page, but it's missing the redirect url behavior that comes with Forms Authentication on the legacy app.

Edit:

I was able to get this to work by manually creating the return url via [this suggestion](https://stackoverflow.com/questions/59728006/how-do-i-pass-returnurl-to-login-page-in-blazor-server-application).  I don't know if it's worth closing this if there's a better way.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We couldn't prioritize this investigation given the number of customers are affected. Hence closing this issue.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
