### ISSUE TITLE
404 Errors for all assets in Test Server – Unable to load assets and check UI tests 

### ISSUE THREAD

**Issue by Cyrus-Sushiant** [dotnet/aspnetcore#58072]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm encountering an issue when trying to open the test server app in the browser. Some assets (e.g., CSS, JS, images, etc.) are returning 404 errors, which prevents the application from loading correctly.

As a result, the app does not display with full functionality, and I am unable to properly check the UI for testing purposes. This issue makes it difficult to run effective UI tests.

### Expected Behavior

The assets should load correctly, allowing the app to display and function as expected to proceed with UI testing.

### Steps To Reproduce

Example steps:
1. Clone my repo at https://github.com/Cyrus-Sushiant/PlaywrightIssue
2. Run the `GotoCounterPage` test in the `MyTest` class in the tests project
3. Open `http://127.0.0.1:2001` in your browser
4. Some assets (e.g., CSS, JS, images, etc.) are returning 404 errors, which prevents the application from loading correctly.

![image](https://github.com/user-attachments/assets/3b4e7d95-6675-4313-a048-ff84a6c84c20)

### .NET Version

8.0.401

**Comment by javiercn** [comment]
@Cyrus-Sushiant thanks for contacting us.

That likely is caused by you running the build output in Production without explicitly setting up static web assets.

Static Web Assets are only loaded in Developmnet environment. You need to call `StaticWebAssetsLoader.UseStaticWebAssets` if you are not running in development.

**Comment by ysmoradi** [comment]
The environment has been set to development, so I assume calling `StaticWebAssetsLoader.UseStaticWebAssets` is not required (Even though I called it without success.

Note that if we set Sdk of test project to `Microsoft.NET.Sdk.Web` the `staticwebassets.development.json` file gets generated, but for some reason, aspnetcore doesn't use it.

**Comment by Cyrus-Sushiant** [comment]
As Yaser said, The environment has been set to development. You can see in this class:
https://github.com/Cyrus-Sushiant/PlaywrightIssue/blob/master/PlaywrightIssue.Tests/MyTest.cs

![image](https://github.com/user-attachments/assets/32e7fb51-513f-4ed2-8733-e72fbed4bf01)

**Comment by javiercn** [comment]
@ysmoradi You need to call this one `StaticWebAssetsLoader.UseStaticWebAssets(builder.Environment, builder.Configuration);` not the one you called.

**Comment by ysmoradi** [comment]
Thanks for your efforts, I really appreciate it.
Two notes to consider:

1- Changing test project sdk to `Microsoft.NET.Sdk.Web` will result into generating all required files such as `staticwebassets.development.json`, so we don't have to look for these files in host project (aspnetcore project)

2- Event though calling `StaticWebAssetsLoader.UseStaticWebAssets(builder.Environment, builder.Configuration);` is not required if dev environment, but even if you call it, it won't work! you can easily test that in the sample source code.

**Comment by ysmoradi** [comment]
The `builder.Environment.ApplicationName` is `testhost` (for the builder that is being built in mstest method)
Assigning appropriate ApplicationName resolved the issue
