### ISSUE TITLE
Blazor JS interop (server side render). Calling InvokeJsAsync does not throw if connection lost

### ISSUE THREAD

**Issue by kefyru** [dotnet/aspnetcore#58089]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Calling JS function from dotnet using InvokeAsync does not throws if connection lost. 
So this task chain will never be completed.

### Expected Behavior

If connection lost InvokeAsync should throw some exception.

### Steps To Reproduce

1. Call js from dotnet
```c# 
try {
  await JS.InvokeVoidAsync("infinityLoopAsyncFunction");
  Console.WriteLine("OK");
} catch {
  Console.WriteLine("Fail");
}
```

2. While js working, close browser tab (to simulate connection lose)

### .NET Version

8.0.401t

**Comment by javiercn** [comment]
@kefyru thanks for contacting us.

It can take some time before the server detects the connection is lost, so the call won't fail until we detect the lost connection.

**Comment by kefyru** [comment]
For example components Dispose methods invoking immediately, but js.InvokeAsync does not returns - i have been waiting for a minutes...
