### ISSUE TITLE
Remove Microsoft.AspNetCore.Identity.UI from Microsoft.AspNetCore.App

### ISSUE THREAD

**Issue by tstivers1990** [dotnet/aspnetcore#5809]
I'm not sure if this is the right project to place the issue in, as I'm not sure what project manages the relevant nuget package. But I believe Identity UI should be removed from `Microsoft.AspNetCore.App`. The reason for this is because if one chooses not to use Identity UI, and instead write their own UI for Identity, they're not going to be using any of Identity UI. I would imagine this is a common scenario, as most production websites aren't likely to be using Identity UI in my eyes. Normally, it's a non-issue. But because of the nature, it's likely people will be using the same names for their own implementation as are used in Identity UI, such as `LoginModel`, `LogoutModel`, etc. This presents issues when using something like ReSharper, which can automatically import missing namespaces. It quickly becomes cumbersome. I believe Visual Studio has a similar feature as well, which also becomes more cumbersome because of this.

Normally, I wouldn't submit an issue over NuGet package organization, as it's largely cosmetic. But I believe that, because of the extremely high likelihood of your class names being the same as Identity UI class names, and the potential for error that this creates, it should be separated from the `Microsoft.AspNetCore.App` package. In my case, these issues have led me to move from using `Microsoft.AspNetCore.App` to manually adding the necessary individual nuget packages to my project to solve the issue. I don't feel this is the ideal scenario, as `Microsoft.AspNetCore.App` is a good package in my eyes. But because of these issues, this is my only acceptable option.

Further, I don't believe that Identity UI will be used often enough in production projects to warrant including it in the all-encompassing package. I believe it is very likely Identity UI will only be used for prototyping projects at most and, therefore, doesn't really fit in `Microsoft.AspNetCore.App`.

**Comment by cocowalla** [comment]
Another good reason to remove it is that it's almost 7MB.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
