### ISSUE TITLE
RFC6238 AuthenticatorService

### ISSUE THREAD

**Issue by slaneyrw** [dotnet/aspnetcore#5811]
Can you please expose the internal Rfc6238AuthenticatorService ( and Base32 ), mostly so we are able to utilize it for TwoFactor authentication using the Google Authenticator class of apps.

The existing TotpSecurityStampBaseTokenProvider cannot be used as the security stamp should not be involved in the code check.

The TimeStep and interval range also needs to be customizable **per token provider** as the default TOTP settings are not always appropriate - effectively this forces us to re-implement ALL of the token providers.

At the moment we have to import 3rd party libraries Base32 and OptSharp to be able to provide this functionality

The PIN length consideration from #1564 should also be customizable.

Lastly, please consider converting this to a instance class, not static, so we can configure the TOTP settings within individual token providers and set the TokenOptions provider instance ( I'd love to do this solely via DI but the MS DI engine cannot support parallel named DI graphs )

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
