### ISSUE TITLE
Add Get and GetOrdered to EndpointMetadataCollection

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#58110]
## Background and Motivation

This is long AF:
```cs
var endpoint = context.GetEndpoint();
var metadata = endpoint.Metadata.GetRequiredMetadata<Foo>();
```

Adding `Get<T>()`, `GetRequired<T>()` and `GetOrdered<T>` would make the API slightly easier to use. This is consistent with `IFeatureCollection`.

## Proposed API

```diff
namespace Microsoft.AspNetCore.Http;

public class EndpointMetadataCollection
{
+    public T? Get<T>();
+    public T GetRequired<T>();
+    public IReadOnlyList<T> GetOrdered<T>();
}
```

## Usage Examples

```cs
if (endpoint.Metadata.Get<Foo>() != null)
{
    // do a thing
}
```

## Risks

Two ways of doing the same thing is confusing. Could add an analyzer. Could hide existing properties from autocomplete with attributes.

**Comment by JamesNK** [comment]
It's interesting that the extension method to get a required feature is more verbose:

https://github.com/dotnet/aspnetcore/blob/e4ca1fd805c3857109bf67c4fee579e10db50113/src/Extensions/Features/src/FeatureCollectionExtensions.cs#L21-L27

It's `GetRequiredFeature` which is similar to metadata's existing `GetRequiredMetadata`.

**Comment by JamesNK** [comment]
Maybe only `Get<T>()` should be added?

I feel like I'm talking myself out of this change 😄

**Comment by amcasey** [comment]
[API Review]

- Why not extension methods?
- This could better be summarized as creating versions of methods without the "Metadata" suffix for terseness
- There could be an argument for consistency between the collection types, but it's weak

We're not sold.  Any more arguments in favor, @JamesNK?
