### ISSUE TITLE
SignalR input binding fails to parse Authorization header

### ISSUE THREAD

**Issue by yohny** [dotnet/aspnetcore#58148]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using the `idToken` property on SignalR input binding as specified in the [documentation](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-signalr-service-input?tabs=isolated-process%2Cnodejs-v4&pivots=programming-language-javascript#annotations-1) it should be possible to use binding expession to specify the header from which the JWT token should be extracted and which extracted claims should be propagated to resulting access token for SignalR Service. However if standard `Authorization` header is specified there, the JWT token parsing fails.
Sample Azure function (nodejs runtime, programing model v4):
```ts
const inputSignalR = input.generic({
  type: "signalRConnectionInfo",
  name: "connectionInfo",
  hubName: "my-hub",
  idToken: "{headers.authorization}", // extract JWT from Authorization header, as commonly done
  claimTypeList: ["name", "email"], // propagate name and email claims to SignalR Service access token
});

async function negotiate(
  request: HttpRequest,
  context: InvocationContext
): Promise<HttpResponseInit> {
    return { body: JSON.stringify(context.extraInputs.get(inputSignalR)) };
}

app.post("negotiate", {
  authLevel: "anonymous",
  handler: negotiate,
  route: "negotiate",
  extraInputs: [inputSignalR],
});
```
when such `negotiate` endpoint is invoked, it however fails with error:
```
Executed 'Functions.negotiate' (Failed, Id=8c21bcd7-d061-4184-bac7-3f1046b00f99, Duration=71ms)
[2024-09-29T20:21:11.648Z] System.Private.CoreLib: Exception while executing function: Functions.negotiate. System.IdentityModel.Tokens.Jwt: IDX12709: CanReadToken() returned false. JWT is not well formed.
The token needs to be in JWS or JWE Compact Serialization Format. (JWS): 'EncodedHeader.EndcodedPayload.EncodedSignature'. (JWE): 'EncodedProtectedHeader.EncodedEncryptedKey.EncodedInitializationVector.EncodedCiphertext.EncodedAuthenticationTag'.
```
this can be resolved by removing the `Bearer ` string from the begginning of the incoming `Authorizzation` request header. If this is done, the JWT header is parsed successfully and the specified claims are propagated to `accessToken` returned by `negotiate` endpoint.

### Expected Behavior

The parsing of JWT token from headers (or at least the Authorization header) should handle the standard `Bearer ` prefix in front of JWT token itself without failure.

### Anything else?

Nodejs 20.15..1
@azure/functions 4.5.1

**Comment by BrennanConroy** [comment]
File at https://github.com/azure/azure-signalr/
