### ISSUE TITLE
SignalR JS client incorrectly appends Authorization header

### ISSUE THREAD

**Issue by yohny** [dotnet/aspnetcore#58146]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a simple Azure function app, that uses Azure SignalR Service in serverless mode to provide some real-time functionality. The function app exposes the `negotiate` endpoint to provide clients with connection info to Azure SignalR Service.
I use SIgnalR JS client in browser and it is configured as folows:
```js
 const connection = new signalR.HubConnectionBuilder()
        .withUrl(apiBaseUrl, {
          headers: {
           authorization: "Bearer a1b2c3...",
          },
        })
        .configureLogging(signalR.LogLevel.Information)
        .build();
connection.start().catch(console.error);
```
the above results in browser making a request to my function app's `/negotiate` endpoint (and it includes the configured `authorization` header as expected). My `negotiate` endpoint returns the SignaR Service connection information:
```json
{
  "url":"http://localhost:8888/client/?hub=my-hub", // using Azure SignalR Local Emulator, but its the same with real SignalR Service
  "accessToken":"d4e5f6..."
}
```
which SignalR client correctly follows by attempting to connect to the specified SIgnalR service by making a request to `http://localhost:8888/client/negotiate?hub=my-hub&negotiateVersion=1`. However instead of using only the `accessToken` provided in the `negotiate` response, it adds it to orignal token, resulting in `Authorization` header with both values: `Bearer a1b2c3..., Bearer d4e5f6...` which is rejected by SignalR Service with `401 Unauthorized`

### Expected Behavior

The Autohorization header should only contain access token returned by `negotiate` endpoint when connectiong to SignalR Service. The Authorization header is not allowed to contain multiple auth. methods and/or tokens.

### Anything else?

SignalR JS client 8.0.7
Azure SignalR Local Emulator 1.3.0

**Comment by BrennanConroy** [comment]
Don't manually set the authorization header, use the accessTokenFactory.

**Comment by yohny** [comment]
using `accessTokenFactory` resolved the issue, thanks
