### ISSUE TITLE
Debugging Blazor Server running in a dev container (WSL)

### ISSUE THREAD

**Issue by TalonZA** [dotnet/aspnetcore#58151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

My company has remove all docker instances from all developer machines due to licensing costs.

We are limited to using docker on WSL for our development.  I have been a massive advocate for Blazor in my organisation and now that I have developed my app, the organisation has asked me to containerize it and get it ready for cloud.

It was a HUGE surprise to find that debugging a container is not available for Blazor.  My specific request is for Blazor Server, I know there is another request for Blazor WASM here #37565 

This is vitally important for me else I need to consider removing the Blazor UI from my application and replacing it with something else.

### Describe the solution you'd like

In Visual Studio, I'd like to be able to debug my application in WSL.  When I run my application, my breakpoints need to work as it would when I am running locally.  I know it works with other standard .net applications.

**Comment by mkArtakMSFT** [comment]
Thanks for detailed explanation of the value this will provide to your company. While I'm going to close this issue as a dupe, we'll take into consideration your input for .NET 10 planning.

**Comment by danroth27** [comment]
@TalonZA Can you please walk me through how you tried running and debugging your Blazor app in WSL?. I tried creating a default Blazor Web App with .NET 8 and VS2022 17.11 and running it in WSL using VS and I was able to debug without issue:

![msedge_YiYIXeIBbu](https://github.com/user-attachments/assets/56807055-571a-464e-9ada-5c0af6875a8e)
