### ISSUE TITLE
Unsafe Two Factor Recovery Codes

### ISSUE THREAD

**Issue by mbeckenbach** [dotnet/aspnetcore#5815]
Hi, 

i've noticed that the two factor recovery codes for authenticator logins are not stored as hashes in AspNetUserTokens table. Shouldn't those be hashed in database like passwords are?

Best regards
Max

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
While this may be a great idea, it is not aligned with our long-term vision to make it part of the framework. For many other ideas which don't belong to the framework we encourage the community to build and ship on their own, contributing to the expanding .NET Ecosystem.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
