### ISSUE TITLE
[Blazor]When using the SSR mode, OnAfterRenderAsync is not called?

### ISSUE THREAD

**Issue by ssccinng** [dotnet/aspnetcore#58150]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using the SSR mode, OnAfterRenderAsync is not called

### .NET Version

net8.0

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is the intended behavior and it's documented: https://learn.microsoft.com/aspnet/core/blazor/components/lifecycle?view=aspnetcore-8.0#after-component-render-onafterrenderasync

> [OnAfterRender](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.componentbase.onafterrender) and [OnAfterRenderAsync](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.componentbase.onafterrenderasync) are invoked after a component **has rendered interactively** and the UI has finished updating (for example, after elements are added to the browser DOM).

> These methods aren't invoked during prerendering or static server-side rendering (static SSR) on the server because those processes aren't attached to a live browser DOM and are already complete before the DOM is updated.

**Comment by ssccinng** [comment]
> Thanks for contacting us. This is the intended behavior and it's documented: https://learn.microsoft.com/aspnet/core/blazor/components/lifecycle?view=aspnetcore-8.0#after-component-render-onafterrenderasync
> 
> > [OnAfterRender](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.componentbase.onafterrender) and [OnAfterRenderAsync](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.componentbase.onafterrenderasync) are invoked after a component **has rendered interactively** and the UI has finished updating (for example, after elements are added to the browser DOM).
> 
> > These methods aren't invoked during prerendering or static server-side rendering (static SSR) on the server because those processes aren't attached to a live browser DOM and are already complete before the DOM is updated.
Is there any good way to use IJSRuntime(?

**Comment by ssccinng** [comment]
> Thanks for contacting us. This is the intended behavior and it's documented: https://learn.microsoft.com/aspnet/core/blazor/components/lifecycle?view=aspnetcore-8.0#after-component-render-onafterrenderasync
> 
> > [OnAfterRender](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.componentbase.onafterrender) and [OnAfterRenderAsync](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.componentbase.onafterrenderasync) are invoked after a component **has rendered interactively** and the UI has finished updating (for example, after elements are added to the browser DOM).
> 
> > These methods aren't invoked during prerendering or static server-side rendering (static SSR) on the server because those processes aren't attached to a live browser DOM and are already complete before the DOM is updated.

Is there any good way to use IJSRuntime?

**Comment by Su-s** [comment]
how can we use interactive components  inside ssr pages. onchange and onclick methods are not working without after render. 

i'm trying to use select component and tab commponent
