### ISSUE TITLE
Use collection expression for ASP.NET Core Web API project template's WeatherForecastController.cs

### ISSUE THREAD

**Issue by tikap** [dotnet/aspnetcore#58175]
**Suggested Change:**

I would like to submit a PR that changes the way an array of strings are initialized in the _WeatherForecastController.cs_ file for the ASP.NET Core Web API project template.

We should use the new [collection expressions](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/collection-expressions) introduced in .NET 8.0 to create the "Summaries" string array to prevent styling warnings, i.e [ide0300](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0300).

**Target file:**
[WeatherForecastController.cs](https://github.com/dotnet/aspnetcore/blob/main/src/ProjectTemplates/Web.ProjectTemplates/content/WebApi-CSharp/Controllers/WeatherForecastController.cs)

**Impact:**
Visual studio uses this template when user selects "ASP.NET Core Web API" in the "Create a new project" wizard.

**Comment by captainsafia** [comment]
@tikap This sounds like a great idea! I'd be happy to review a PR from you for this. 😃

**Comment by tikap** [comment]
Thanks @captainsafia !
