### ISSUE TITLE
Asset fingerprinting does not work for `_content` and `_framework` files

### ISSUE THREAD

**Issue by meenzen** [dotnet/aspnetcore#58187]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

> ASP.NET Core will now generate fingerprinted versions of static web assets when the app is published. The fingerprinted static web assets contain a unique hash of their content in their filename, so that they never clash with earlier versions of the file. ASP.NET Core then exposes the fingerprinted static web assets as endpoints with appropriate cache headers to ensure the content is cached for a long time. Fingerprinting static web assets helps ensure that stale assets aren't used and enables improved caching behavior for faster load times.

This changelog entry lead me to believe that asset fingerprinting works for all static files including embedded assets like `_framework/blazor.web.js` or `_content/MudBlazor/MudBlazor.min.js`. The majority of relevant assets in our production apps are part of frameworks like `MudBlazor` or custom libraries, so IMHO this should be supported.

My testing indicates that fingerprinting only works for files in `wwwroot/` and scoped CSS. This works as expected:

```razor
<link rel="stylesheet" href="@Assets["css/app.css"]"/>
<link rel="stylesheet" href="@Assets["MyApp.styles.css"]"/>
<script src="@Assets["js/app.js"]"></script>

<!-- result -->
<link rel="stylesheet" href="css/app.nbijregqvq.css">
<link rel="stylesheet" href="MyApp.euyk63wjbu.styles.css">
<script src="js/app.v0s5k27cco.js"></script>
```

This does not work:

```razor
<script src="@Assets["_content/MudBlazor/MudBlazor.min.js"]"></script>
<script src="@Assets["_framework/blazor.web.js"]"></script>

<!-- result -->
<script src="_content/MudBlazor/MudBlazor.min.js"></script>
<script src="_framework/blazor.web.js"></script>
```

Is this the expected behavior? If so, this should be added to the docs to avoid confusion.

### Expected Behavior

Asset fingerprints should be generated and used:

```razor
<script src="@Assets["_content/MudBlazor/MudBlazor.min.js"]"></script>
<script src="@Assets["_framework/blazor.web.js"]"></script>

<!-- expected result -->
<script src="_content/MudBlazor/MudBlazor.min.12345abcde.js"></script>
<script src="_framework/blazor.web.12345abcde.js"></script>
```

### .NET Version

9.0.100-rc.1.24452.12

**Comment by javiercn** [comment]
@meenzen thanks for contacting us.

Yes, this is the case. Fingerprinting works with static web assets, if your files are not defined as static web assets and you have your own process to embed and serve them, they won't be processed.

That's why in our case `blazor.web.js` doesn't get the fingerprinting treatment, as it's served through a special endpoint.

**Comment by meenzen** [comment]
> That's why in our case `blazor.web.js` doesn't get the fingerprinting treatment, as it's served through a special endpoint.

That is unfortunate because then there are still potential CDN caching issues which I thought this feature was supposed to solve. It means a hack like this is still required to make sure users always get the latest version:

```razor
<script src="_framework/blazor.server.js?v=@(ThisAssembly.GitCommitId)"></script>
```

This also doesn't answer my question if it's supposed to work with files in `_content` like `MudBlazor` which was explicitly used as an example in the documentation surrounding this feature. These files even get copied to `wwwroot/` and compressed on publish which confuses me even more:

![image](https://github.com/user-attachments/assets/507f0c66-018b-448b-9be1-ef2f223462bc)

Still no fingerprinting:

![374179187-baa519f7-c741-4c98-abae-13a2c6ee7280](https://github.com/user-attachments/assets/8447a55d-9a69-47ed-86b4-5b9bd9e4a0ed)

Shouldn't this work?

**Comment by meenzen** [comment]
This is not resolved.

**Comment by hakenr** [comment]
@meenzen Fortunately, the Razor Class Library (RCL) static web assets (the `_content` folder) are also fingerprinted. However, the RCL needs to be built with .NET 9 as well. You can check the source code at https://blocks.havit.blazor.eu/ where we reference the `net9` version (`v4.7.0-pre01`) of our `Havit.Blazor.Components.Web.Bootstrap` package - the fingerprints are included there.

![Image](https://github.com/user-attachments/assets/221e5292-e30a-429e-9a0f-efdecc4f6d52)

![Image](https://github.com/user-attachments/assets/ab499fd1-5a1a-4777-adc0-42b1095cfcbf)

**Comment by S-Luiten** [comment]
Can confirm fingerprinting works with MudBlazor v8 preview version, which targets .NET 9.0.

Is there a reason why this requirement exists? I was also confused when none of the `_content` files were getting fingerprinted.
IMO either this requirement should be removed, or the docs should be updated to mention it.

**Comment by wolfgangschneider** [comment]
> This is not resolved.

I think so too
