### ISSUE TITLE
Add the ability to load a component using a File path.

### ISSUE THREAD

**Issue by htmlsplash** [dotnet/aspnetcore#58188]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I would like to have the ability to load a component dynamically using file path, similar to TemplateControl.LoadControl() method in web forms. Is this functionality considered?

### Describe the solution you'd like

I know I can load a component dynamically using type information (using render fragment or Dynamic Component), but I would like to do the same using file path (load component from a folder location).

Because this functionality is not available I have 2 options:

1) Use regex or simple string replace to convert folder paths to type information of the component. 
Ex: 
templates/ca/ab/search/projectSearch.ascx => templates.ca.ab.search.projectSearch.razor

2) Hard code folder paths to type information. 
Ex:

`public static class ComponentMapper
{
    public static readonly Dictionary<string, Type> ComponentMap = new()
    {
        { "folder1/componenta", typeof(Folder1.ComponentA) },
        { "folder2/componentb", typeof(Folder2.ComponentB) }
    };
}`

But it would be nice if the framework had one consistent way of doing this, so I don't have to write my own code to accomplish this task using some translation method.

**Comment by MackinnonBuck** [comment]
Thanks for reaching out.

Could you please clarify what the motivation is for wanting this feature? What's your scenario?

**Comment by htmlsplash** [comment]
@MackinnonBuck 
Our current application loads dynamically from disk UI templates (which are UserControls in Webforms) to render parts of the search results UI based on the region in the URL.

The idea is quite simple:
Our applications needs to display different UI/data on various pages that are specific to a certain geo-graphic region. This UI is loaded dynamically by loading the component file (in our case UserControl file with extension .ascx) located in a specific folder that follows a naming pattern where these files for specific region are located on disk.

Example:
For url: http://somedomain/projectSearchResults?loc=ca&region=on

Generated Folder path: {app folder}\templates\ca\on\ProjectSearchResults.ascx

Once the template file is loaded it is bound to data based on a well defined interface and the results are rendered on the page.

**Comment by javiercn** [comment]
@htmlsplash thanks for contacting us.

This is something that you can implement yourself by creating your own mapping from "path/string" to component type, but it's not something that blazor plans to support out of the box.

Components are compiled into classes and don't have a requirement to be on separate/specific files. Adding an indirection like the one you propose adds a lot of overhead to the framework for its limited use cases.

You can probably build this yourself by relying on https://learn.microsoft.com/es-es/dotnet/api/system.runtime.compilerservices.callerfilepathattribute?view=net-8.0 to create a mapping to associate a component with a file path.
