### ISSUE TITLE
Exception is raised in when setting interactivemode in blazor server authentication type enabled web app project

### ISSUE THREAD

**Issue by IndrajithSrinivasan** [dotnet/aspnetcore#58222]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Created a Blazor web app project, and added a web component which has client side interactions, so added interactivemode for the dotnet project and the exception is raised in when setting interactivemode in blazor server authentication type enabled in the web app project. Attached the ensured project with this issue thread.

### Expected Behavior

No script issue while configuring the renderMode, with and without placing any blazor components in the authentication pages. **Login.razor, Register.Razor**

### Steps To Reproduce

[InteractiveServer_auth_application.zip](https://github.com/user-attachments/files/17245627/InteractiveServer_auth_application.zip)

* Launch the above attached sample.
* Navigate to the **Login.razor** page, below script issue is raised in razor pages and browser console.

### Exceptions (if any)

* *Login.razor** page, below script issue is raised in razor pages
![image](https://github.com/user-attachments/assets/94fa9bd0-90bb-4bc1-92f0-44f641826da2)
![image](https://github.com/user-attachments/assets/40f27506-58f4-49c3-aad9-5c459747cbaf)

* Below error in the console
![image](https://github.com/user-attachments/assets/ad768289-5998-49b0-aad0-f4b95c6e27b5)

* Project configuration
![image](https://github.com/user-attachments/assets/0c49b4e4-1314-4056-a211-3e0d74bb2d2b)

### .NET Version

dotnet 8.0.108

**Comment by MackinnonBuck** [comment]
Thanks for reaching out, @IndrajithSrinivasan.

The identity UI pages don't support interactive rendering, per [the docs](https://learn.microsoft.com/en-us/aspnet/core/blazor/security/server/?view=aspnetcore-8.0&tabs=visual-studio#blazor-identity-ui-individual-accounts:~:text=Blazor%20Identity%20depends%20on%20DbContext%20instances%20not%20created%20by%20a%20factory%2C%20which%20is%20intentional%20because%20DbContext%20is%20sufficient%20for%20the%20project%20template%27s%20Identity%20components%20to%20render%20statically%20without%20supporting%20interactivity.).

@guardrex, maybe we could update this document to include a warning about Identity UI pages themselves not supporting interactivity?

**Comment by MackinnonBuck** [comment]
Closing since the docs have been updated.
