### ISSUE TITLE
OpenApi Should support OpenAPI 3.1 AND thus OneOf for Enums AND Generics.

### ISSUE THREAD

**Issue by JohnGalt1717** [dotnet/aspnetcore#58239]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Right now, enums don't populate at all unless you globally override Json serialization.  #58230 

But that's just OpenAPI 2.0 support that doesn't solve the real problem of enums in OpenAPI in that they can't represent key/value pairs. 

Further, there is no support at all for generics in the current implementation so Result<T> just gets generated as endless duplicate types instead of using the OpenAPI 3.1 spec that allows these to just be Result<T> with optional generic definitions as properties inside the object.

### Describe the solution you'd like

By supporting Open API 3.1 across the entire set of libraries for OpenAPI this can be fixed so that C# can generate a full expression of what would create a great cllent: Enums with key/values and Generics that don't repeat themselves. as 2 instances. I'm sure there are other use cases for the Open API 3.1 spec.

This should also be extended with support into Kiota for all of this as well so that it is coordinated across the entire generation cycle from server to client(s).

### Additional context

As noted in the referenced ticket it's possible to hack this functionality in, but it should be at the root and just done automatically as it doesn't break existing client generators by adding this support, while it creates much richer and cleaner clients when it is implemented.

**Comment by captainsafia** [comment]
@JohnGalt1717 Supporting OpenAPI v3.1 is a long-term goal of this effort. However, we're limited by the fact that the underlying OpenAPI library we use (https://github.com/microsoft/openapi.net) doesn't support OpenAPI v3.1 yet.

They are in the process of adding that support in a new major version of the package that we intend on upgrading to consume these new APIs when those updates are released.

**Comment by JohnGalt1717** [comment]
Ok, that's fair, but I'd like to see captured the todo specifically of proper support of Enums and generics. The former of which is currently outright broken while it works using OpenAPI 2 in Swashbuckle and Nswag right now which depend on the same library.

**Comment by JohnGalt1717** [comment]
Why is the bot closing stuff over weekends with 1 day of activity? That's an insane way to ensure that you can claim great close statistics.  Please reopen.
