### ISSUE TITLE
Table mappings not working with Core 2.1

### ISSUE THREAD

**Issue by dpedrelli** [dotnet/aspnetcore#5824]
I have a netcoreapp2.0 in which I mapped the Identity classes to custom table names.  I created the Identity migration and it works fine.  When I update to netcoreapp2.1, I get the following error, when I attempt to access Identity:

`SqlException: Invalid object name 'AspNetRoles'. `

I searched the solution.  CreateIdentitySchema.Designer.cs and ApplicationDbContextModelSnapshot.cs each contain an entry that maps to the correct table.  They also contain a second entry:

```C#
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityRole<string>");


                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasDiscriminator().HasValue("IdentityRole");
                });
```

If I edit these entries to point to the correct table, I still get the above error.  If I rollback to netcoreapp2.0, everything works as expected.

**Comment by dpedrelli** [comment]
@ajcvickers Has this been resolved?

Thanks.

**Comment by ajcvickers** [comment]
@dpedrelli Nope, not yet.

**Comment by dpedrelli** [comment]
I started a new, ASP.NET Core 3.1.1 app.  This still seems to be an issue.  Should I expect this to not work?

**Comment by ajcvickers** [comment]
@HaoK Posted on https://github.com/dotnet/efcore/issues/19767

>  The issue is in Shared/_LoginPartial.cshtml, that needs to be updated to reference the appropriate users, its currently looking for IdentityUser which isn't registered... The callstack here sucks, but if you turn on symbol sources and framework debugging, you can see that's the view causing the error.

> Well I don't think this is a bug, if you customize the user types, you need to also update the _loginPartial.cshtml that's in the app to match.

Removing from Discussions here to re-triage for Identity. (Even if that's just to close as by-design.)

/cc @blowdart @HaoK 

>

**Comment by blowdart** [comment]
Identity Templates are designed for our Identity implementation. If you're not using our default implementations then you are expected to update the templates to match your own. So by design.

**Comment by dpedrelli** [comment]
@blowdart The issue I reported here does not involve _LoginPartial.cshtml.  I changed the names of all of the Identity tables in the ApplicationDbContext.OnModelBuilding().  This works fine in .NET Core 2.0.  Ever since 2.1, Identity only looks for dbo.AspNetRoles under the original name, and ignores the mapping that I entered.   In my Oct 26, 2018 comment, I included a solution with multiple projects and explained what happened in 2.0, upgrading from 2.0 to 2.1, and creating a new 2.1 project.  As of 3.1.1, this still does not work.  I can remap all tables except for AspNetRoles.

`        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);
            // Customize the ASP.NET Identity model and override the defaults if needed.
            // For example, you can rename the ASP.NET Identity table names and more.
            // Add your customizations after calling base.OnModelCreating(builder);
            builder.Entity<ApplicationUser>(entity =>
            {
                entity.ToTable(name: "SmAspNetUser", schema: "security");
                entity.Property(e => e.Id).HasColumnType("varchar(256)");
                entity.Property(e => e.ConcurrencyStamp).HasColumnType("varchar(256)");
                entity.Property(e => e.PhoneNumber).HasColumnType("varchar(256)");
                entity.Property(e => e.SecurityStamp).HasColumnType("varchar(256)");
            });

            builder.Entity<IdentityRole<string>>(entity =>
            {
                entity.ToTable(name: "SmAspNetRole", schema: "security");
                entity.Property(e => e.Id).HasColumnType("varchar(256)");
                entity.Property(e => e.ConcurrencyStamp).HasColumnType("varchar(256)");
                entity.Property(e => e.Name).HasColumnType("varchar(256)");
                entity.Property(e => e.NormalizedName).HasColumnType("varchar(256)");
            });

            builder.Entity<IdentityUserClaim<string>>(entity =>
            {
                entity.ToTable("SmAspNetUserClaim", "security");
                entity.Property(e => e.ClaimType).HasColumnType("varchar(256)");
                entity.Property(e => e.ClaimValue).HasColumnType("varchar(256)");
            });

            builder.Entity<IdentityUserLogin<string>>(entity =>
            {
                entity.ToTable("SmAspNetUserLogin", "security");
                entity.Property(e => e.ProviderDisplayName).HasColumnType("varchar(256)");
            });

            builder.Entity<IdentityRoleClaim<string>>(entity =>
            {
                entity.ToTable("SmAspNetRoleClaim", "security");
                entity.Property(e => e.ClaimType).HasColumnType("varchar(256)");
                entity.Property(e => e.ClaimValue).HasColumnType("varchar(256)");
            });

            builder.Entity<IdentityUserRole<string>>(entity =>
            {
                entity.ToTable("SmAspNetUserRole", "security");
            });

            builder.Entity<IdentityUserToken<string>>(entity =>
            {
                entity.ToTable("SmAspNetUserToken", "security");
            });
        }
`

**Comment by blowdart** [comment]
I don't think we've ever expected you to customise the role tables beyond fieldnames if you changed them. If we did want to consider this it'd be a breaking change and not one that provides a lot of benefit for the pain of schema migrations it would create.

**Comment by dpedrelli** [comment]
@blowdart I don't know, I found multiple documents covering renaming the tables and even one on having multiple sets of Identity tables.  I have a live database, with three different MVC apps, each with it's own ApplicationDbContext and each pointing to a different set of Identity tables.  It works perfectly in 2.0.  Since 2.1, most of the tables remap correctly, but not all of them.  This is from a new project I created in 2.1.  I have the ApplicationDbContext.OnModelCreating that remaps the tables and the subsequent migration.  The migration is correct for all tables except AspNetRoles and AspNetUsers.

`        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);
            // Customize the ASP.NET Identity model and override the defaults if needed.
            // For example, you can rename the ASP.NET Identity table names and more.
            // Add your customizations after calling base.OnModelCreating(builder);
            builder.Entity<ApplicationUser>(entity =>
            {
                entity.ToTable(name: "SmAspNetUser", schema: "security");
                entity.Property(e => e.Id).HasColumnType("varchar(256)");
                entity.Property(e => e.ConcurrencyStamp).HasColumnType("varchar(256)");
                entity.Property(e => e.PhoneNumber).HasColumnType("varchar(256)");
                entity.Property(e => e.SecurityStamp).HasColumnType("varchar(256)");
            });

            builder.Entity<IdentityRole<string>>(entity =>
            {
                entity.ToTable(name: "SmAspNetRole", schema: "security");
                entity.Property(e => e.Id).HasColumnType("varchar(256)");
                entity.Property(e => e.ConcurrencyStamp).HasColumnType("varchar(256)");
                entity.Property(e => e.Name).HasColumnType("varchar(256)");
                entity.Property(e => e.NormalizedName).HasColumnType("varchar(256)");
            });

            builder.Entity<IdentityUserClaim<string>>(entity =>
            {
                entity.ToTable("SmAspNetUserClaim", "security");
                entity.Property(e => e.ClaimType).HasColumnType("varchar(256)");
                entity.Property(e => e.ClaimValue).HasColumnType("varchar(256)");
            });

            builder.Entity<IdentityUserLogin<string>>(entity =>
            {
                entity.ToTable("SmAspNetUserLogin", "security");
                entity.Property(e => e.ProviderDisplayName).HasColumnType("varchar(256)");
            });

            builder.Entity<IdentityRoleClaim<string>>(entity =>
            {
                entity.ToTable("SmAspNetRoleClaim", "security");
                entity.Property(e => e.ClaimType).HasColumnType("varchar(256)");
                entity.Property(e => e.ClaimValue).HasColumnType("varchar(256)");
            });

            builder.Entity<IdentityUserRole<string>>(entity =>
            {
                entity.ToTable("SmAspNetUserRole", "security");
            });

            builder.Entity<IdentityUserToken<string>>(entity =>
            {
                entity.ToTable("SmAspNetUserToken", "security");
            });
        }
`

`        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.EnsureSchema(
                name: "security");

            migrationBuilder.CreateTable(
                name: "AspNetRoles",
                columns: table => new
                {
                    Id = table.Column<string>(nullable: false),
                    Name = table.Column<string>(maxLength: 256, nullable: true),
                    NormalizedName = table.Column<string>(maxLength: 256, nullable: true),
                    ConcurrencyStamp = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AspNetRoles", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "AspNetUsers",
                columns: table => new
                {
                    Id = table.Column<string>(type: "varchar(256)", nullable: false),
                    UserName = table.Column<string>(maxLength: 256, nullable: true),
                    NormalizedUserName = table.Column<string>(maxLength: 256, nullable: true),
                    Email = table.Column<string>(maxLength: 256, nullable: true),
                    NormalizedEmail = table.Column<string>(maxLength: 256, nullable: true),
                    EmailConfirmed = table.Column<bool>(nullable: false),
                    PasswordHash = table.Column<string>(nullable: true),
                    SecurityStamp = table.Column<string>(type: "varchar(256)", nullable: true),
                    ConcurrencyStamp = table.Column<string>(type: "varchar(256)", nullable: true),
                    PhoneNumber = table.Column<string>(type: "varchar(256)", nullable: true),
                    PhoneNumberConfirmed = table.Column<bool>(nullable: false),
                    TwoFactorEnabled = table.Column<bool>(nullable: false),
                    LockoutEnd = table.Column<DateTimeOffset>(nullable: true),
                    LockoutEnabled = table.Column<bool>(nullable: false),
                    AccessFailedCount = table.Column<int>(nullable: false),
                    Discriminator = table.Column<string>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AspNetUsers", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "SmAspNetRole",
                schema: "security",
                columns: table => new
                {
                    Id = table.Column<string>(type: "varchar(256)", nullable: false),
                    Name = table.Column<string>(type: "varchar(256)", nullable: true),
                    NormalizedName = table.Column<string>(type: "varchar(256)", nullable: true),
                    ConcurrencyStamp = table.Column<string>(type: "varchar(256)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_SmAspNetRole", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "SmAspNetRoleClaim",
                schema: "security",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    RoleId = table.Column<string>(nullable: false),
                    ClaimType = table.Column<string>(type: "varchar(256)", nullable: true),
                    ClaimValue = table.Column<string>(type: "varchar(256)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_SmAspNetRoleClaim", x => x.Id);
                    table.ForeignKey(
                        name: "FK_SmAspNetRoleClaim_AspNetRoles_RoleId",
                        column: x => x.RoleId,
                        principalTable: "AspNetRoles",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "SmAspNetUserClaim",
                schema: "security",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    UserId = table.Column<string>(nullable: false),
                    ClaimType = table.Column<string>(type: "varchar(256)", nullable: true),
                    ClaimValue = table.Column<string>(type: "varchar(256)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_SmAspNetUserClaim", x => x.Id);
                    table.ForeignKey(
                        name: "FK_SmAspNetUserClaim_AspNetUsers_UserId",
                        column: x => x.UserId,
                        principalTable: "AspNetUsers",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "SmAspNetUserLogin",
                schema: "security",
                columns: table => new
                {
                    LoginProvider = table.Column<string>(maxLength: 128, nullable: false),
                    ProviderKey = table.Column<string>(maxLength: 128, nullable: false),
                    ProviderDisplayName = table.Column<string>(type: "varchar(256)", nullable: true),
                    UserId = table.Column<string>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_SmAspNetUserLogin", x => new { x.LoginProvider, x.ProviderKey });
                    table.ForeignKey(
                        name: "FK_SmAspNetUserLogin_AspNetUsers_UserId",
                        column: x => x.UserId,
                        principalTable: "AspNetUsers",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "SmAspNetUserRole",
                schema: "security",
                columns: table => new
                {
                    UserId = table.Column<string>(nullable: false),
                    RoleId = table.Column<string>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_SmAspNetUserRole", x => new { x.UserId, x.RoleId });
                    table.ForeignKey(
                        name: "FK_SmAspNetUserRole_AspNetRoles_RoleId",
                        column: x => x.RoleId,
                        principalTable: "AspNetRoles",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_SmAspNetUserRole_AspNetUsers_UserId",
                        column: x => x.UserId,
                        principalTable: "AspNetUsers",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "SmAspNetUserToken",
                schema: "security",
                columns: table => new
                {
                    UserId = table.Column<string>(nullable: false),
                    LoginProvider = table.Column<string>(maxLength: 128, nullable: false),
                    Name = table.Column<string>(maxLength: 128, nullable: false),
                    Value = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_SmAspNetUserToken", x => new { x.UserId, x.LoginProvider, x.Name });
                    table.ForeignKey(
                        name: "FK_SmAspNetUserToken_AspNetUsers_UserId",
                        column: x => x.UserId,
                        principalTable: "AspNetUsers",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "RoleNameIndex",
                table: "AspNetRoles",
                column: "NormalizedName",
                unique: true,
                filter: "[NormalizedName] IS NOT NULL");

            migrationBuilder.CreateIndex(
                name: "EmailIndex",
                table: "AspNetUsers",
                column: "NormalizedEmail");

            migrationBuilder.CreateIndex(
                name: "UserNameIndex",
                table: "AspNetUsers",
                column: "NormalizedUserName",
                unique: true,
                filter: "[NormalizedUserName] IS NOT NULL");

            migrationBuilder.CreateIndex(
                name: "IX_SmAspNetRoleClaim_RoleId",
                schema: "security",
                table: "SmAspNetRoleClaim",
                column: "RoleId");

            migrationBuilder.CreateIndex(
                name: "IX_SmAspNetUserClaim_UserId",
                schema: "security",
                table: "SmAspNetUserClaim",
                column: "UserId");

            migrationBuilder.CreateIndex(
                name: "IX_SmAspNetUserLogin_UserId",
                schema: "security",
                table: "SmAspNetUserLogin",
                column: "UserId");

            migrationBuilder.CreateIndex(
                name: "IX_SmAspNetUserRole_RoleId",
                schema: "security",
                table: "SmAspNetUserRole",
                column: "RoleId");
        }
`
