### ISSUE TITLE
[Blazor] - Issue calling `submitRequest` on data-enhanced form

### ISSUE THREAD

**Issue by Travis-Th** [dotnet/aspnetcore#58244]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Calling `requestSubmit` on a form with the data-enhance attribute prints an uncaught `TypeError` to the console. It complains about accessing a member on a null submitter.

### Expected Behavior

I would expect the navigation to be enhanced, and for the form to post.

### Steps To Reproduce

Put this form in an SSR page, and click the button. The error should be printed to console.
```
<form id="test-form" method="post" @formname="my-form-name" data-enhance>
    <AntiforgeryToken />
    <button type="button" onclick="document.getElementById('test-form').requestSubmit()">I print an uncaught TypeError to the console!</button>
</form>
```

### .NET Version

8.0.200

### Anything else?

I think the issue is caused by this line not properly checking for null, but I could be mistaken. Not super familiar with how enhanced navigation works internally.

https://github.com/dotnet/aspnetcore/blob/870eec223cdb09e5ca8cfdc61bfd5fbc2ca9773b/src/Components/Web.JS/src/Services/NavigationEnhancement.ts#L147

**Comment by mkArtakMSFT** [comment]
Thanks for reporting this issue - good catch.
We've moved this to the backlog, but if you'd be interested, we would happily accept a PR to address this.
