### ISSUE TITLE
[NETSDKE2E][WIX]After configuring the policy key for .NET 9 and set it to nextSession then sign out of the machine and sign back, the net9RC1 Hosting Bundle cannot be removed.

### ISSUE THREAD

**Issue by v-ainigao** [dotnet/aspnetcore#58291]
Repro OS: windows11-x64 and arm64
Repro steps:
1.Adm run: `REG ADD HKLM\SOFTWARE\Microsoft\.NET\9.0 /t REG_SZ /v RemovePreviousVersion /d nextSession`
2.Install 9.0.0-rc.1.24452.1 Hosting Bundle
3.Install 9.0.100-rc.2.24468.15 Hosting Bundle
4.Verify that the RunOnce key exist and that it is targeting the RC1 bundle 
Adm run: `reg query HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\RunOnce /reg:32`
![image](https://github.com/user-attachments/assets/982abb00-b13c-4200-bfef-b6527d448d59)
5.Sign out of the machine and sign back in 
6.Verify that RC1 is now removed

Expected Result:
The RC1 Hosting Bundle is now removed

Actual Result:
The net9RC1 Hosting Bundle cannot be removed
![image](https://github.com/user-attachments/assets/2c7579da-700e-470b-9300-d3e1e0985d94)
![image](https://github.com/user-attachments/assets/adf95955-c900-4563-a8b9-1dd9b6ca677e)
This is the captured log file.
[vslogs.zip](https://github.com/user-attachments/files/17071047/vslogs.zip)

**Comment by wtgodbe** [comment]
Thanks @joeloff - opened https://github.com/dotnet/aspnetcore/pull/58292 & backports to 9.0 to 8.0 (and moved this issue to aspnetcore)
