### ISSUE TITLE
OpenIdConnectHandler.ValidateTokenUsingHandlerAsync() does not copy a value from the _configuration.Issuer

### ISSUE THREAD

**Issue by artem-dudarev** [dotnet/aspnetcore#58327]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

There is a redundant `else` keyword in the `OpenIdConnectHandler.ValidateTokenUsingHandlerAsync()` method on line `1447`:
https://github.com/dotnet/aspnetcore/blob/44a9f8a83a1d20a3e367d5ec0d82111e84c7e5ec/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectHandler.cs#L1443-L1454
Because of this, the `ValidIssuers` property is always `null` when my custom issuer validator is being called.
If I set `OpenIdConnectOptions.UseSecurityTokenValidator` to `true`, then the `ValidateToken()` method is called, which doesn't have this problem:
https://github.com/dotnet/aspnetcore/blob/44a9f8a83a1d20a3e367d5ec0d82111e84c7e5ec/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectHandler.cs#L1394-L1401

### Expected Behavior

The `Issuer` should always be copied to the `ValidIssuers` if `_configuration` is not `null`.

### .NET Version

8.0.400

### Anything else?

.NET SDK:
 Version:           8.0.400
 Commit:            36fe6dda56
 Workload version:  8.0.400-manifests.56cd0383
 MSBuild version:   17.11.3+0c8610977

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.400\

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
 [aspire]
   Installation Source: VS 17.11.35222.181
   Manifest Version:    8.1.0/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.1.0\WorkloadManifest.json
   Install Type:        FileBased

Host:
  Version:      8.0.8
  Architecture: x64
  Commit:       08338fcaa5

.NET SDKs installed:
  6.0.427 [C:\Program Files\dotnet\sdk]
  8.0.400 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.35 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.35 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.35 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by halter73** [comment]
This `else` was added as part of the [breaking change in .NET 8](https://learn.microsoft.com/en-us/dotnet/core/compatibility/aspnet-core/8.0/securitytoken-events) where we moved from `JwtSecurityToken` to `JsonWebToken`. One focus of the change was to reduce per-request allocations like `new[] { _configuration.Issuer }`. As far as I know, the caller of `ValidateTokenAsync` is *not* expected to copy the individual properties from the `BaseConfigurationManager` to the `TokenValidationParameters` top-level properties. When `TokenValidationParameters.ConfigurationManager` is non-null, it's the responsibility of the `TokenHandler` itself to read from `ConfigurationHandler`.

The addition of `TokenValidationParameters.ConfigurationManager` is [relatively new](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/1695), and validators prior to its addition obviously could not be expected to check something that did not exist, but that's partly why the switch to `JsonWebToken` and the `JsonWebTokenHandler` validator was a breaking change.

You can see how the default `JsonWebTokenHandler` issuer validation checks against both `TokenValidationParameters.ValidIssuers` and*`BaseConfigurationManager.Issuer` [here](
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/a7c4b65a99d8e12aaa6a76ae7306e1e43c4cdf10/src/Microsoft.IdentityModel.Tokens/Validation/Validators.Issuer.cs#L82-L91).

FYI @keegan-caruso @brentschmaltz @jennyf19 I want to make sure I'm not saying anything inaccurate.

**Comment by artem-dudarev** [comment]
Thanks for the explanation. I was just thinking that if `OpenIdConnectHandler` already has `_configuration.Issuer`, there is no need to force an issuer validator to load the configuration again.

**Comment by keegan-caruso** [comment]
@halter73 This is correct, the TokenHandler should read from the ConfigurationManager.
