### ISSUE TITLE
Trusting the https certificate on Linux platforms fails with the error: "exporting the HTTPS developer certificate to a file."

### ISSUE THREAD

**Issue by v-sherryfan** [dotnet/aspnetcore#58337]
### To Reproduce

1. Clean machine: Ubuntu 24.04 and Debian 12
2. Install SDK 8.0.403 from download page
3. According to documentation [Ubuntu trust the certificate for service-to-service communication](https://learn.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-6.0&tabs=visual-studio%2Clinux-ubuntu#ubuntu-trust-the-certificate-for-service-to-service-communication) to trust https certificate, you will get an error when you running following code:
    ```
    dotnet dev-certs https
    sudo -E dotnet dev-certs https -ep /usr/local/share/ca-certificates/aspnet/https.crt --format PEM
    ```
### Exceptions (if any)
There was an error exporting the HTTPS developer certificate to a file.
![Image](https://github.com/user-attachments/assets/29b4e5df-5cdb-4214-98b4-f0d6cab782f0)

**Note**

- This issue will block Aspire Project from running
- ![Image](https://github.com/user-attachments/assets/bb8d3056-540e-472a-be73-33f67e5e3f5e)

### Expected
![Image](https://github.com/user-attachments/assets/a14552f3-7367-4a14-8a67-683d360de642)

### Further technical details

parallels@ubuntu-linux-22-04-02-desktop:~$ dotnet --info
.NET SDK:
 Version:           8.0.403
 Commit:            c64aa40a71
 Workload version:  8.0.400-manifests.58db758f
 MSBuild version:   17.11.9+a69bbaaf5

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/lib/dotnet/sdk/8.0.403/

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
 [aspire]
   Installation Source: SDK 8.0.400
   Manifest Version:    8.2.1/8.0.100
   Manifest Path:       /usr/lib/dotnet/sdk-manifests/8.0.100/microsoft.net.sdk.aspire/8.2.1/WorkloadManifest.json
   Install Type:        FileBased

Host:
  Version:      8.0.10
  Architecture: x64
  Commit:       81cabf2857

.NET SDKs installed:
  8.0.110 [/usr/lib/dotnet/sdk]
  8.0.403 [/usr/lib/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.10 [/usr/lib/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.10 [/usr/lib/dotnet/shared/Microsoft.NETCore.App]

**Comment by PhilG0lding** [comment]
We've just had a similar issue with multiple docker image builds failing using mcr.microsoft.com/dotnet/sdk:8.0-alpine. Vite was trying to generate dev-certs, which is where we encountered the issue.

Looks to be an issue in the latest SDK (8.0.403). We downgraded to SDK 8.0.402 (mcr.microsoft.com/dotnet/sdk:8.0.402-alpine3.20) our images build now works.

**Comment by martincostello** [comment]
This might be a dupe of #58330.

**Comment by v-sherryfan** [comment]
> Maybe you should use `dotnet dev-certs https --verbose --trust ` to trust your certificate on Linux.

This solution works fine for me, thanks for your help. Close this.
