### ISSUE TITLE
Blazor `@key` inside the component

### ISSUE THREAD

**Issue by Kebechet** [dotnet/aspnetcore#58339]
I went through the [docs][1] of Blazor `@key` usage. But I am not sure if it works correctly in one specific case that wasn't mentioned there.

What happens if instead of this code in `Page.razor`:

    <div>
        @foreach (var person in people)
        {
            <Details @key="person" Person="@person" />
        }
    </div>

I would place the `@key` inside the `Details` component itself. So for `Details.razor` it would look like:

    <div @key=@Person>
        @* The rest of the component UI *@
    </div>
    
    @code{
        [Parameter] public required Person Person { get; set; }
    }

because that way when I loop this component in multiple pages I dont have to always specify the `@key` parameter in the foreach. But does the blazor take it as the same/different scope ?

  [1]: https://learn.microsoft.com/en-us/aspnet/core/blazor/components/element-component-model-relationships?view=aspnetcore-8.0

StackOverflow question link:
https://stackoverflow.com/questions/79070497/blazor-key-inside-the-component

**Comment by javiercn** [comment]
@Kebechet thanks for contacting us.

That doesn't work because the key needs to be known before the component is instantiated and can't be defined from inside the component itself.

**Comment by Kebechet** [comment]
Thanks @javiercn for clarification
