### ISSUE TITLE
UserStore.UpdateAsync should not always attach TUser entity

### ISSUE THREAD

**Issue by ppech** [dotnet/aspnetcore#5840]
If you set AutoSaveChanges to false and call more then one method of UserManager, you receive DbUpdateConcurrencyException.

> DbUpdateConcurrencyException: Database operation expected to affect 1 row(s) but actually affected 0 row(s). Data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.

To reproduce exception, setup custom UserStore:
```csharp
public class IdentityUserStore : UserStore<ApplicationUser>
{
  public IdentityUserStore(ApplicationDbContext context, IdentityErrorDescriber describer = null) : base(context, describer)
  {
    this.AutoSaveChanges = false;
  }
}
// and register custom user store in Startup.cs
services.AddIdentity<ApplicationUser, IdentityRole>()
                .AddEntityFrameworkStores<ApplicationDbContext>()
                .AddUserStore<IdentityUserStore>()
                .AddDefaultTokenProviders();
```
Then call this example:
```csharp
var user = await _userManager.FindByEmailAsync("test@user.cz");
var claim1 = new Claim("TestClaim1", "one");
var res1 = await _userManager.AddClaimAsync(user, claim1);
var claim2 = new Claim("TestClaim2", "two");
var res2 = await _userManager.AddClaimAsync(user, claim2);
await _dbContext.SaveChangesAsync(); // DbUpdateConcurrencyException
```
Every call of UserManager.AddClaimAsync method internaly calls UserStore.UpdateAsync. This method Context.Attach() and updates ConcurrencyStamp. Because Context.Attach() always attach entity as Unchanged the second call of AddClaimAsync overrides "OriginalValue" of ConcurrencyStamp.
And this cause exception on DbContext.SaveChangesAsync because generated SQL update query a use wrong value of ConcurrencyStamp in where clause.

I think that this line:
https://github.com/aspnet/Identity/blob/8003a5550e7c9b02de035de04b0758f898d8237f/src/EF/UserStore.cs#L185
should by replaced by this:
```csharp
var entry = Context.Entry(user);
if (entry.State == EntityState.Detached)
  Context.Attach(user);
```
What do you think? Thanks

**Comment by sven5** [comment]
This issue still persists. No updates on this? This is really annoying.

**Comment by lakeman** [comment]
That method is virtual, since you are providing your replacement IdentityUserStore, you can copy/paste that method with your fix. It's annoying, but setting AutoSaveChanges to false isn't a well supported / tested use case anyway.

**Comment by lakeman** [comment]
If anyone is touching UserStore<> UserOnlyStore<>, should we shift common behaviour to a new non-generic abstract IdentityStoreBase? Particularly the AutoSaveChanges property (Related #7648). To enable 3rd party libraries to easily change this?
