### ISSUE TITLE
We are having trouble with both `0.0.0.0` and `0.0.0.1` with [Stripe Elements UI](https://docs.stripe.com/payments/payment-element) for collecting payment card details.

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#58415]
We are having trouble with both `0.0.0.0` and `0.0.0.1` with [Stripe Elements UI](https://docs.stripe.com/payments/payment-element) for collecting payment card details.

1. Stripe Elements UI's JavaScript does not allow being hosted on IP-based hostnames
2. Stripe backend does not allow redirecting to IP-based hostnames, to return to the app after adding payment card

Another usecase is locking down google maps API keys to specific domains, we were not able to make this work with `0.0.0.0`. I'm sure there are many similar situations with other JavaScript libraries.

We really need this to be configurable to `localhost` 🙏

_Originally posted by @angularsen in https://github.com/dotnet/maui/issues/24884#issuecomment-2410966903_

**Comment by javiercn** [comment]
This came from the PR where we changed the host for Maui apps. We might need to reconsider what we do here, and offer some level of customization if needed.

**Comment by MarkusRodler** [comment]
+ there are issues with SVG Icons as described in the original issue: https://github.com/dotnet/maui/issues/24363

**Comment by nnphi2304** [comment]
As I can see on iOS, the BlazorWebView.AppHostAddress="app://localhost" which is a non-https protocol will be blocked by stripe elements. It should be https://localhost I guess.

**Comment by javiercn** [comment]
https://github.com/dotnet/maui/issues/11425
