### ISSUE TITLE
JDK zip not found when running `.\eng\scripts\InstallJdk.ps1`

### ISSUE THREAD

**Issue by ShreyasJejurkar** [dotnet/aspnetcore#58457]
Trying to build all repos on my new machine by referring https://github.com/dotnet/aspnetcore/blob/main/docs/BuildFromSource.md. I found that I don't have JDK installed, so tried to install it with the script in the scripts folder, but getting the below error. Looks like the resource is not on the server. 

![Image](https://github.com/user-attachments/assets/51422f91-5a5f-48ab-8574-3ee0dd657236)

Looks like we need to update this, or maybe if we can detect we are on windows (which we can I guess) we can use Winget to install JDK instead of relying on this. It will be simple and less error prone.

**Comment by amcasey** [comment]
```
GET https://netcorenativeassets.blob.core.windows.net/resource-packages/external/windows/java/microsoft-jdk-11-windows-x64.zip
Failed to download 'https://netcorenativeassets.blob.core.windows.net/resource-packages/external/windows/java/microsoft-jdk-11-windows-x64.zip'
WARNING: The remote server returned an error: (404) Not Found.
```

**Comment by amcasey** [comment]
I think @adityamandaleeka may have looked at this recently?

**Comment by BrennanConroy** [comment]
This should be working now. The global.json was using "11", which is another way of saying "use latest version of 11", but it only works for some tooling. Now the global.json is "11.0.24" which should work with the installjdk script.

**Comment by wtgodbe** [comment]
Fixed by https://github.com/dotnet/aspnetcore/pull/58557. Feel free to re-open if you're still having issues
