### ISSUE TITLE
Provide information diagnostic when `public partial class Program { }` declaration is found in code

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#58488]
## Background and Motivation

With the introduction of top-level statements in .NET 6, there is not longer an explicit `Program` class defined in user's ASP.NET Core applications. Instead, we rely on the `Program` class generated by the compiler, which has [a default visibility of `internal`](https://sharplab.io/#v2:CYLg1APgAgjAdLAnACgESwOwAIoCYsCWAzoQHYAuApgE6kCGANqgJQDcQA==).

This introduces an annoying hurdle for users who want to write integration tests on top of our [WebApplicationFactory](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.testing.webapplicationfactory-1?view=aspnetcore-8.0) which requires a public entrypoint as a generic type argument.

To work around this, we document that users can either:

- Add an `IVT` from their application code to their test code
- Add a `public partial class Program {}` declaration

The first approach runs the risk of the user having to expose truly internal types to their test code. The second approach is hard to discover.

To resolve this issue, we introduced a new source generator to the shared framework that will emit the `public partial class Program {}` declaration to applications that:

- Use top-level statements
- Don't declare the `Program` class as public in some other fashion
- Don't use the old-style `Program.Main` declarations

This source generator was implemented in https://github.com/dotnet/aspnetcore/pull/58199. Based on the code generation that we introduced here, users can get rid of the explicit `public partial class Program { }` declarations in their source code and rely on the new default behavior. We propose introducing an analyzer to find these explicit declarations and a code fixer to remove them.

### Title
Explicit class declaration not required

### Message
Using public partial class Program { } to make generated Program class public is no longer required. See https://aka.ms/aspnetcore-warnings/ASP0027 for more details.

### Category

- [ ] Design
- [ ] Documentation
- [ ] Globalization
- [ ] Interoperability
- [ ] Maintainability
- [ ] Naming
- [ ] Performance
- [ ] Reliability
- [ ] Security
- [ ] Style
- [X] Usage

### Severity Level

- [ ] Error
- [ ] Warning
- [X] Info
- [ ] Hidden

## Usage Scenarios

```csharp
using Microsoft.AspNetCore.Builder;

 var app = WebApplication.Create();

 app.MapGet("/", () => "Hello, World!");

 app.Run();

public partial class Program {} // Emit info diagnostic here
```

**Comment by amcasey** [comment]
Isn't there a special category/lever for analyzers that are flagging redundant code?  It might be `Hidden` but I think there might actually be a bool to tell the editor to grey out the span, rather than squiggling it.  Otherwise, LGTM.

**Comment by captainsafia** [comment]
> Isn't there a special category/lever for analyzers that are flagging redundant code? It might be `Hidden` but I think there might actually be a bool to tell the editor to grey out the span, rather than squiggling it. Otherwise, LGTM.

This is the full set of available severities. I think our "Hidden" above aligns with the "None" below.

![Image](https://github.com/user-attachments/assets/71642d8b-4b33-4d0e-99ed-f2d4e18ece88)

**Comment by amcasey** [comment]
This is what I was thinking of: https://github.com/dotnet/roslyn/blob/048a23fcea1ef7346d2a59d4e4345dbb1fb780b9/src/Compilers/Core/Portable/Diagnostic/WellKnownDiagnosticTags.cs#L14

**Comment by captainsafia** [comment]
@amcasey Ah I see -- it looks like this is a tag that can be added in _addition_ to the severity level of the property. I can incorporate this into the PR.

**Comment by danroth27** [comment]
Minor nit on the message text:

Using public partial class Program { } to make **the** generated Program class public is no longer required. See https://aka.ms/aspnetcore-warnings/ASP0027 for more details.

**Comment by amcasey** [comment]
[API Review]

- What brings in the analyzer?
    - It's part of the shared framework
- Are the members of the entrypoint type also public?
    - No
- We think Info goes in the error list but Hidden doesn't
    - It feels like we might not need this in the error list
    - Neither squiggles, as far as we know
- Is there a code fix for the analyzer?
    - Yes, and it has fix-all
- Title candidates: 
    - Public Program partial class declaration not required
    - Unnecessary public Program class declaration
- Message candidates:
    - Using public partial class Program { } to make the generated Program class public is no longer required. See https://aka.ms/aspnetcore-warnings/ASP0027 for more details.

**Comment by amcasey** [comment]
*Title*
Unnecessary public Program class declaration
*Message*
Using public partial class Program { } to make the generated Program class public is no longer required. See https://aka.ms/aspnetcore-warnings/ASP0027 for more details.
*Severity*
Hidden or Info, TBD

API Approved!

**Comment by captainsafia** [comment]
Closing. This will ship in .NET 10 Preview 1.
