### ISSUE TITLE
Razor completion for <text> tags

### ISSUE THREAD

**Issue by Eilon** [dotnet/aspnetcore#5848]
_From @vank-ms on Tuesday, 20 March 2018 17:18:42_

I understand Razor gets opportunities to include C# completion items (like `@page`, `@inject`) and HTML items, which it currently does not participate in.  It would be nice if Razor contributed the <text> tag to HTML completion when appropriate.

_Copied from original issue: aspnet/Razor#2200_

**Comment by Eilon** [comment]
_From @mkArtakMSFT on Tuesday, 20 March 2018 22:30:15_

Thank you for contacting us, @vank-ms.
To evaluate this feature request, we'd like to understand more about your scenario. Could you please elaborate on the scenario and the problem you're trying to solve?

/cc @DamianEdwards, @danroth27, @rynowak

**Comment by Eilon** [comment]
_From @NTaylorMullen on Tuesday, 20 March 2018 22:44:49_

> To evaluate this feature request, we'd like to understand more about your scenario. Could you please elaborate on the scenario and the problem you're trying to solve?

He's just looking to get the Razor `<text>` tag to be included in IntelliSense in the valid contexts (inside of `@{...}`).

**Comment by Eilon** [comment]
_From @vank-ms on Wednesday, 21 March 2018 16:27:32_

Taylor Mullen asked me to open this issue after a discussion of Razor IntelliSense interaction.
He mentioned that Razor is asked to contribute IntelliSense items twice; once for C# and once for HTML, but it did nothing for HTML.
I asked if Razor could offer the <text> tag when asked for HTML items.
Taylor said ‘good idea’ and asked me to open an issue.  He sent me a link to the location used.

**Comment by NTaylorMullen** [comment]
Closing this in favor of https://github.com/dotnet/aspnetcore/issues/18526
