### ISSUE TITLE
SignalR callbacks working on net7.0, not on net9.0

### ISSUE THREAD

**Issue by ispysoftware** [dotnet/aspnetcore#58485]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Updating from net7.0 to net9.0 breaks all callbacks from signalr.

When running this code under net7.0 it works fine, i see "SignalR connection established." followed by messages coming in on "ProcessJSON". I change to net9.0 and I just see "SignalR connection established." - nothing is logged and no messages arrive.

### Expected Behavior

Should function exactly the same as net7.0

### Steps To Reproduce

See repro project

https://github.com/ispysoftware/sigrtest9/tree/main

The test fails. Change the net runtime from net9.0 to net7,0 in the project file and the test passes
Set Trimming to false and the test passes.

### .NET Version

net9.0

**Comment by ispysoftware** [comment]
It's due to trimming - working in net7.0 with trimming enabled. Broken in net8.0 with trimming enabled
    <PublishTrimmed>true</PublishTrimmed>
https://github.com/dotnet/aspnetcore/issues/41704

**Comment by BrennanConroy** [comment]
Trimming isn't supported for SignalR in .NET 8.

**Comment by ispysoftware** [comment]
@BrennanConroy - yes i've spent 3 days finding that out. Do you know if it's supported in .NET 9? The reason I ask is that with trimming our client facing app is 50mb and without it it's 140mb.

**Comment by BrennanConroy** [comment]
https://github.com/dotnet/aspnetcore/issues/41704#issuecomment-2215170852

**Comment by ispysoftware** [comment]
Thanks @BrennanConroy . 
Spent the last 3 days updating our codebase to be compatible with net9.0 and having exactly the same issue with SignalR.
Just says 
"SignalR connection established" and nothing else. No messages back from it.

**Comment by BrennanConroy** [comment]
You are still using the 8.0 package... Trimming support was added in the 9.0 version which means you need the 9.0 package.

**Comment by ispysoftware** [comment]
Thanks @BrennanConroy  - I updated the reference to the latest pre-release. Same issue.

**Comment by ispysoftware** [comment]
@BrennanConroy  Thanks, adding

```
builder.Services.Configure<JsonHubProtocolOptions>(o =>
{
    o.PayloadSerializerOptions.TypeInfoResolverChain.Insert(0, AppJsonSerializerContext.Default);
});

```
resolved it. Much appreciated!
