### ISSUE TITLE
Applying Authorize attribute to Blazor component only works on a page level.

### ISSUE THREAD

**Issue by Notallthatevil** [dotnet/aspnetcore#58508]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Adding the Authorize attribute to a Blazor component does not trigger any authorization. Adding the attribute to a page works as expected. I am referring to a single reusable component. 

### Expected Behavior

If a child component has the Authorize attribute applied, I would expect the authorization flow to be triggered just like it does if a page has the authorize attribute applied.

### Steps To Reproduce

* Create a new Blazor WebApp project in dotnet 8 using the per page/component render mode with interactive auto enabled, and individual accounts. 
* Add the `Auth` component to the `Counter` page.
``` Counter.razor
<PageTitle>Counter</PageTitle>

<h1>Counter</h1>

<p role="status">Current count: @currentCount</p>

<button class="btn btn-primary" @onclick="IncrementCount">Click me</button>

<Auth />
```
* Start the app and navigate to counter
![Image](https://github.com/user-attachments/assets/47eef719-045c-4fba-9e80-eadc76a67318)

### Exceptions (if any)

Even though I am not signed in, I still see the "You are authenticated" header from the `Auth` component. I would expect this to perform the same action as navigating to /auth where it redirects me to the login page.  

### .NET Version

8.0.10

**Comment by javiercn** [comment]
@Notallthatevil thanks for contacting us.

@CrahunGit response is correct.

**Comment by Notallthatevil** [comment]
Thanks for the quick response. Is this documented anywhere?
