### ISSUE TITLE
The referenced MessagePack has a known vulnerability

### ISSUE THREAD

**Issue by davesmits** [dotnet/aspnetcore#58532]
In https://github.com/dotnet/aspnetcore/blob/4b8269fca79f95dc28c0c03546f941e86f663c15/eng/Versions.props#L297 the reference to `MessagePack` is a version (2.5.108) with a known vulnerability https://osv.dev/vulnerability/GHSA-4qm4-8hg2-g2xm

I noticed the .NET 9RC2 still links this package with vulnerability. Is the reference going to be updated to version where this is fixed? (>=
2.5.187)?

**Comment by wtgodbe** [comment]
Thanks for the report - we'll get this fixed for 9.0 RTM

**Comment by wtgodbe** [comment]
https://github.com/dotnet/aspnetcore/pull/58556 ports the fix to 9.0

**Comment by AnthonyMastrean** [comment]
Any chance of patching the 8.0 release (is that LTS along with .NET)?

**Comment by wtgodbe** [comment]
Sure - https://github.com/dotnet/aspnetcore/pull/58676. That will miss the November patch but will go out in the next one
