### ISSUE TITLE
Error Method not found: Microsoft.AspNetCore.Components.EventCallback deploy blazor wasm stand alone  use Lazyload

### ISSUE THREAD

**Issue by tvtoanit88** [dotnet/aspnetcore#58579]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Hello aspnet core team. I have a problem:
I created Razor Lib with name testcomponents and there is a click EventCallback.
When I create app1 blazor wasm standalone and call testcomponents.
After I create app2, load app1 from AssemblyLoadContext.Default.LoadFromStream. In visual studio, run normally, but iis deployment error:
Method not found: Microsoft.AspNetCore.Components.EventCallback
My example:
https://github.com/tvtoanit88/blazorwasmexample

**Comment by tvtoanit88** [comment]
Summary: When you deploy Blazor Wasm StandAlone on NGINX(1.27.2) for both Windows and Linux, there are many errors. List of errors:
1: Unable to resolve token xxx from typeref in System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.
2. Method not found: Eventcallback.
3. Unable to set property xxxevent on object of type ..custom component. The error is: Arg_InvalidCastException.
4. Unable to resolve token xxx in AspNetCore.Component.

**Comment by javiercn** [comment]
@tvtoanit88 thanks for contacting us.

`After I create app2, load app1 from AssemblyLoadContext.Default.LoadFromStream.` Dynamic assembly loading is not supported on Blazor applications as the linker will trim away things for which it sees no use.

Your only potential option here would be to disable linking which will dramatically increase the size of your app. See https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/configure-linker?view=aspnetcore-3.1 for details

**Comment by tvtoanit88** [comment]
> [@tvtoanit88](https://github.com/tvtoanit88) thanks for contacting us.
> 
> `After I create app2, load app1 from AssemblyLoadContext.Default.LoadFromStream.` Dynamic assembly loading is not supported on Blazor applications as the linker will trim away things for which it sees no use.
> 
> Your only potential option here would be to disable linking which will dramatically increase the size of your app. See https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/configure-linker?view=aspnetcore-3.1 for details

Hello @javiercn, thanks your reply 
But I am using .Net 8.0 and it supports Assembly Load from file.
You can check the git link below.
https://github.com/tvtoanit88/blazorwasmexample
