### ISSUE TITLE
Allow ::deep selector in other file types.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#58572]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Allow-::deep-selector-in-other-file-type/10767157)._

---
When using SCSS files in a Blazor project, we get the following warnings all the time:

```
::deep is only allowed in file names ending with ".razor.css" or ".cshtml.css"
```

It would be nice if code analysis could also ignore other "CSS" type files like `.scss` and `.less`. 

---
#### Feedback Bot on 10/11/2024, 08:11 PM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further. You will hear from us in about a week on our next steps.</p>

**Comment by MackinnonBuck** [comment]
Thanks for reaching out.

This is not a direction the product is going to take at this time. The framework would first need to add support for SCSS and Less (something like https://github.com/dotnet/aspnetcore/issues/47586).

**Comment by sloscialo** [comment]
That just sounds ridiculous. 

You don't need to support preprocessors as in that other ticket. You just have to recognize that a small handful of other file extensions can be safely ignored with regard to that rule:
* `.razor.css`
* `.razor.scss`
* `.razor.less`
* `.cshtml.css`
* `.cshtml.scss`
* `.cshtml.less`

Probably less than 10 minutes of actual work.

**Comment by rajsite** [comment]
> This is not a direction the product is going to take at this time. The framework would first need to add support for SCSS and Less

@MackinnonBuck We followed the straightforward [Blazor docs on CSS preprocessor support](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/css-isolation?view=aspnetcore-10.0#css-preprocessor-support) using third party NuGet packages and would appreciate handling `::deep` or a way to suppress the message in Visual Studio.
