### ISSUE TITLE
Customise validation css class names

### ISSUE THREAD

**Issue by lonix1** [dotnet/aspnetcore#58570]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

For invalid form fields, the razor engine outputs [hardcoded css class names](https://github.com/dotnet/aspnetcore/blob/c2cb6009fe07dfb139353bca3e965ed68fc94bd2/src/Mvc/Mvc.ViewFeatures/src/HtmlHelper.cs#L21-L49): `input-validation-error`, `input-validation-valid`, `field-validation-error`, `field-validation-valid`, etc.

When using a ui library (bootstrap, tailwind, etc.) one needs different classes. For example, for bootstrap it's `is-invalid`, `is-valid`, `invalid-feedback`, `valid-feedback`, etc.

One can rename these in JS, but that is a hack. It also makes it very difficult to use various js libraries.

### Describe the solution you'd like

Please allow us to customise those class names during startup.

### Additional context

This problem goes back years. I realise that https://github.com/dotnet/aspnetcore/issues/8573 and https://github.com/dotnet/aspnetcore/issues/40935 are not going to be done in the short term.

So at least allow us to change the css class names, which will give us more flexibility for now.

**Comment by MackinnonBuck** [comment]
Thanks for reaching out.

We're going to use https://github.com/dotnet/aspnetcore/issues/8573 to track this, so closing this out as a duplicate.
