### ISSUE TITLE
Web app fails to load when waiting asynchronously inside an IHostedService

### ISSUE THREAD

**Issue by MarcPilgaard** [dotnet/aspnetcore#58578]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

In a Blazor Web App with interactive render mode adding an IHostedService as a hosted service and await an asynchronous method inside of the StartAsync method will prevent the app from starting

### Expected Behavior

The app should start

### Steps To Reproduce

- Create new solution using the Blazor Web App template with interactive render mode as Server.
- Create a class with implementing IHostedService and add any asyncronous method inside IHostedService and await it

```c#
public class SomeRandomService : IHostedService
{
    public async Task StartAsync(CancellationToken cancellationToken)
    {
        while (true)
        {
            await Task.Delay(10000, cancellationToken);
        }
    }

    public Task StopAsync(CancellationToken cancellationToken)
    {
        throw new NotImplementedException();
    }
}
``` 

Add the service in program.cs
```c#
builder.Services.AddHostedService<SomeRandomService>();
``` 

Run the application and notice that the example page won't start

### .NET Version

8.0.401

### Anything else?

Using Rider 2024.2.6

Host:
  Version:      8.0.8
  Architecture: x64
  Commit:       08338fcaa5

.NET SDKs installed:
  8.0.401 [C:\Users\Marc\.dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.8 [C:\Users\Marc\.dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.8 [C:\Users\Marc\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 8.0.8 [C:\Users\Marc\.dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/33902

**Comment by MarcPilgaard** [comment]
https://github.com/MarcPilgaard/Ihostedservice-bug-blazor

**Comment by halter73** [comment]
The issue appears to be that you expect [IHostedService's](https://learn.microsoft.com/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-8.0#ihostedservice-interface) `StartAsync` method to work the same way [BackgroundService's](https://learn.microsoft.com/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-8.0#backgroundservice-base-class) `ExecuteAsync` method does. Unlike `BackgroundService.ExecuteAsync`, `IHostedService.StartAsync` implementations must complete before ASP.NET Core will start accepting requests. This is useful if you need to do something like warm up caches before serving requests. `ExecuteAsync` is expected to run for the duration of the application.

```csharp
public class SomeRandomService : BackgroundService
{
    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        while (true)
        {
            await Task.Delay(10000, stoppingToken);
        }
    }
}
```

I linked to the documentation for both types, but looking at the [source code for `BackgroundService`](https://github.com/dotnet/runtime/blob/a3fe47ef1a8def24e8d64c305172199ae5a4ed07/src/libraries/Microsoft.Extensions.Hosting.Abstractions/src/BackgroundService.cs) should help clarify how things work. `BackgroundService` is implemented on top of `IHostedService`.

**Comment by MarcPilgaard** [comment]
Thank you, that clarifies it. Then everything is in order.
