### ISSUE TITLE
Blazor: Accessing HttpContext in a Client Project

### ISSUE THREAD

**Issue by sbwalker** [dotnet/aspnetcore#58593]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

When building a Blazor application you may want to create all of your components in the Client project, as this provides the flexibility to be able to use the components in any render mode or hosting model (as long as they are developed in a client/server manner). Some of these components may need to access HttpContext (if they are expected to run on the server at run-time ie. as part of pre-rendering). HttpContext is not available in a Client project by default... and adding a dependency to Microsoft.AspNetCore.Http results in a critical severity vulnerability compilation warning in .NET 9. 

### Expected Behavior

I would expect that there should be a way to access HttpContext in a Blazor Client project in .NET 9 that does not result in a critical severity vulnerability issue.

### Steps To Reproduce

- Create a new Blazor Web App in .NET 9 (use default configuration)
- open the App.Razor in the Server project and add a reference to HttpContext
```
@using Microsoft.AspNetCore.Http
...
@code {
    [CascadingParameter]
    HttpContext? Context { get; set; }

    protected override void OnInitialized()
    {
        var ip = Context?.Connection.RemoteIpAddress?.ToString();
    }
}
```
- build the project and run - everything will work fine
- open the Counter.razor in the Client project and add a reference to HttpContext
```
@using Microsoft.AspNetCore.Http
...
@code {
    [CascadingParameter]
    HttpContext? Context { get; set; }

    protected override void OnInitialized()
    {
        var ip = Context?.Connection.RemoteIpAddress?.ToString();
    }
}
```
- try to build and you will get compilation errors in the Client project because HttpContext does not exist
- to resolve the missing dependency, open the Client project file and add a reference to the Microsoft.AspNetCore.Http package
```
<PackageReference Include="Microsoft.AspNetCore.Http" Version="2.2.2" /> 
```
- rebuild the project and run - everything works fine
- however in the build output you will see a critical severity vulnerability message
```
warning NU1904: Package 'System.Text.Encodings.Web' 4.5.0 has a known critical severity vulnerability, https://github.com/advisories/GHSA-ghhp-997w-qr28
```

### .NET Version

9.0.0-rc.2.24473.5

### Anything else?

In .NET 8 the Microsoft.AspNetCore.Http package is flagged as deprecated, however it does not indicate that it contains a critical severity vulnerability. Since the version of the package has not changed in .NET 9 it seems very strange that it is now reporting a critical severity vulnerability (although the CVE referenced is from 2021).

**Comment by sbwalker** [comment]
The FrameworkReference solution does not work for Blazor. It throws a compiler error:

```
error NETSDK1082: There was no runtime pack for Microsoft.AspNetCore.App available for the specified RuntimeIdentifier 'browser-wasm'.
```

**Comment by javiercn** [comment]
@sbwalker the way to do this is defining an interface on the `.Client` project and providing an implementation for it on the Server project to be used during prerendering. It's not possible to have a `FrameworkReference` to ASP.NET Core in the Client project.

This is one of the reasons why we were pursuing multi-targeting. It allows you to have different set of dependencies as well as avoid additional abstractions when you need to target multiple environments.

**Comment by sbwalker** [comment]
Thank you @javiercn. Is there an example I could review to see a practical implementation of this pattern you are describing? 

The confusing aspect of this issue is that the standard development approach of simply adding a Nuget package dependency for the Microsoft.AspNetCore.Http package works perfectly as it delivers the desired functionality to the Client project. The only problem is that the package is deprecated (and now has a vulnerability flagged).

**Comment by martincostello** [comment]
_Maybe_ the 2.3 packages will help once they ship with regards to the vulnerability warnings: https://github.com/dotnet/aspnetcore/issues/58598

**Comment by sbwalker** [comment]
@martincostello I am not sure if that will help as the 2.3 packages are only intended to be used with .NET Framework.

**Comment by martincostello** [comment]
I'n just speculating, but if they still targeted netstandard2.0 then they'd be the same as using 2.1-era packages? Thus they'd be usable like 2.1 or 2.2, but minus the CVEs.

**Comment by javiercn** [comment]
@sbwalker look at the implementation for NavigationManager.

There's a NavigationManager defined in `Microsoft.AspNetCore.Components.Web` and an `HttpNavigationManager` that's implemented in the pieces that use ASP.NET abstractions.

For everyone else interested, please stop trying to find ways to make this work. It's not meant to and even if you manage it's a pit of failure. This is the type of reason for which we wanted to have the `netx.0-browser` TFM so you don't have to create abstractions all over the place.

>[!CAUTION]
>Do not reference `Microsoft.AspNetCore.Http` in WebAssembly or razor class libraries. 
>This is pointing to an obsolete and unsupported version and will bring in a lot of unnecessary dependencies bloating the size of your app.
>Your webassembly app or any dependency that it has can't reference ASP.NET Core abstractions, you need to wrap those in an abstraction.

**Comment by sbwalker** [comment]
@javiercn it took me a long time to come back to this item... but I wanted to thank you for your guidance as your solution works perfectly! The only dependency which is required is Microsoft.AspNetCore.Http.Abstractions - which is light-weight and does not suffer from any security vulnerabilities.
