### ISSUE TITLE
Cannot attach to browser to debug blazor WebAssembly when using own TLS files

### ISSUE THREAD

**Issue by WellspringCS** [dotnet/aspnetcore#58590]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

I am able to debug code in the browser
- with no TLS
- when using a standard localhost (e.g. https://localhost:9891) while providing no TLS information.

If I provide my using the default localhost certificate, Blazor debugging does not work, and in some cases the TLS is not served up as expected.

### Expected Behavior

When for a Blazor-hosted site I use the same TLS settings that work for a standard website, the server will host with TLS just as the ordinary website would, and debug just as is possible when using no TLS or std localhost TLS.

### Steps To Reproduce

Create a standard website, to ensure there are no errors involving TLS files.

launch.json:
```
{
  "configurations": [
    {
      "name": "straight web",
      "type": "coreclr",
      "request": "launch",
      "preLaunchTask": "build",
      "program": "${workspaceFolder}/bin/Debug/net8.0/StraightWeb.dll",
      "args": [],
      "cwd": "${workspaceFolder}",
      "stopAtEntry": false,
      "serverReadyAction": {
        "action": "openExternally",
        "pattern": "\\bNow listening on:\\s+https?://\\S+",
        "uriFormat": "https://std-dotnet-web.dev.localhost:9891"
      },
      "env": {
        "ASPNETCORE_ENVIRONMENT": "Development",
        "KESTREL__ENDPOINTS__HTTPSINLINECERTANDKEYFILE__URL": "https://std-dotnet-web.dev.localhost:9891",
        "KESTREL__ENDPOINTS__HTTPSINLINECERTANDKEYFILE__CERTIFICATE__PATH": "C:\\<path>\\localhost.crt",
        "KESTREL__ENDPOINTS__HTTPSINLINECERTANDKEYFILE__CERTIFICATE__KEYPATH": "C:\\<path>\\localhost.key"
      },
    }
  ]
}
```

launchSettings.json:
```
{
  "$schema": "http://json.schemastore.org/launchsettings.json",
  "profiles": {
    "https": {
      "commandName": "Project",
      "dotnetRunMessages": true,
      "launchBrowser": true,
      "applicationUrl": "http://localhost:9891",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
  }
}
```

Hit F5.
browser opens to `https://std-dotnet-web.dev.localhost:9891/` and returns (with no TLS errors) "Hello World!"

Now go to a blazor-hosted website:

launch.json:
```
{
  "configurations": [
    {
      "name": "Launch and Debug Hosted Blazor WebAssembly App",
      "type": "blazorwasm",
      "request": "launch",
      "hosted": true,
      "program": "${workspaceFolder}/BlazorApp/BlazorApp/bin/Debug/net8.0/BlazorApp.dll",
      "cwd": "${workspaceFolder}",
      "env": {
        "ASPNETCORE_ENVIRONMENT": "Development",
        "KESTREL__ENDPOINTS__HTTPSINLINECERTANDKEYFILE__URL": "https://my-cert.dev.localhost:9894",
        "KESTREL__ENDPOINTS__HTTPSINLINECERTANDKEYFILE__CERTIFICATE__PATH": "C:\\<path>\\localhost.crt",
        "KESTREL__ENDPOINTS__HTTPSINLINECERTANDKEYFILE__CERTIFICATE__KEYPATH": "C:\\<path>\\localhost.key"
      },
      "browser": "edge",
      "url": "https://my-cert.dev.localhost:9894"
    }
  ]
}
```

launchSettings.json:
```
{
  "$schema": "http://json.schemastore.org/launchsettings.json",
    "profiles": {
      "http": {
        "commandName": "Project",
        "dotnetRunMessages": true,
        "launchBrowser": true,
        "inspectUri": "{wsProtocol}://{url.hostname}:{url.port}/_framework/debug/ws-proxy?browser={browserInspectUri}"
      }
    }
  }
}
```

Hit F5
Edge opens to about:blank, waits a while, eventually returns failure dialog "unable to launch browser" with a unreadable (incomplete) reference, such as  ...:9894/_framework/debug/ws-proxy?browser=ws%3A%2F%2F127.0.0.1%3A51495%2Fdev...

However a new tab can be opened and https://my-cert.dev.localhost:9894  returns with no errors. Also no debugging. Counter increases but no stop is hit.

Now change launch.json:
```
{
  "configurations": [
    {
      "name": "Launch and Debug Hosted Blazor WebAssembly App",
      "type": "blazorwasm",
      "request": "launch",
      "hosted": true,
      "program": "${workspaceFolder}/BlazorApp/BlazorApp/bin/Debug/net8.0/BlazorApp.dll",
      "cwd": "${workspaceFolder}",
      "env": {
        "ASPNETCORE_ENVIRONMENT": "Development",
        "ASPNETCORE_URLS": "https://*:9893",
      },
      "browser": "edge",
      "url": "https://localhost:9893"
    }
  ]
}
```

Hit F5
Edge opens to about:blank, waits a few seconds, the URL changes to https://localhost:9893 and debugging in the Counter page functions as expected, with stops honored.

On a related note, if I attempt to set Kestrel via C#, I find that it is routinely ignored. C# runs fail, for example, because port 5000 is taken, despite the following code being at the top of Program.cs:
```
builder.WebHost.ConfigureKestrel(serverOptions =>
  {
    serverOptions.ListenAnyIP(9891, listenOptions => {
      listenOptions.UseHttps(httpsOptions => {
          listenOptions.UseHttps("my-localhost.pfx", configuration["PFX_PWD"]);
        });
    });
  }
);
```

### .NET Version

8.0.110

### Anything else?

VS Code 1.94.2

.NET SDK:
 Version:           8.0.110
 Commit:            87a66bb3d1
 Workload version:  8.0.100-manifests.18f19b92

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.110\

.NET workloads installed:
 Workload version: 8.0.100-manifests.18f19b92
There are no installed workloads to display.

Host:
  Version:      8.0.10
  Architecture: x64
  Commit:       81cabf2857

.NET SDKs installed:
  8.0.100 [C:\Program Files\dotnet\sdk]
  8.0.110 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not part of the runtime feature-set. Please use the [VS Feedback](https://docs.microsoft.com/en-us/visualstudio/ide/feedback-options?view=vs-2019) to report this issue, so the team who owns the area can track the ask.

@vijayrkn, @deepchoudhery heads-up

**Comment by WellspringCS** [comment]
@mkArtakMSFT So this is considered a Visual Studio issue, though I experienced it in VS Code while running Blazor? Not a snarky question. Really wanting to understand.
