### ISSUE TITLE
my clients logouts after 30 minutes

### ISSUE THREAD

**Issue by Jason9n** [dotnet/aspnetcore#58609]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Hi
I have a big problem with identity After logging, I stay login only for 30 minutes.
in my windows (localhost) it will works perfectly fine but when i publish the project and upload it on the host this problem will shows up

I'm using Identity in my project

AppDb:
`public class AppDb : IdentityDbContext<AppUser, IdentityRole, string> { ..... }`

AppUser:
```
public class AppUser : IdentityUser
{

       [ProtectedPersonalData]
       public virtual string Firstname { get; set; } = string.Empty;

       [ProtectedPersonalData]
       public virtual string Lastname { get; set; } = string.Empty;

}
```

and I've created a simple login
### Login Code :
`await _signInManager.SignInAsync(user, true, default);` (I even tried with password signin but no result)

**after 30 minutes its will logout but the cookie will remain**
**no matter what settings I use in the Program.cs it always logouts after 30 minutes**
**i found some related topics on github , but it should be fixed from asp core 2.2, why i have this problem on .NET 8** 

### Program.cs:
```
var builder = WebApplication.CreateBuilder(args);

builder.Services.AddDbContext<AppDb>(options =>
    options.UseSqlServer(builder.Configuration.GetConnectionString("DefaultConnection")));

builder.Services.AddIdentity<AppUser, IdentityRole>()
                        .AddEntityFrameworkStores<AppDb>()
                        .AddDefaultTokenProviders(); 

builder.Services.ConfigureApplicationCookie(options =>
{
    options.AccessDeniedPath = "/Main/NotFound";
    options.LoginPath = "/Account/Entering";
    options.LogoutPath = "/Account/Logout";
    options.Cookie.HttpOnly = true;
    options.ExpireTimeSpan = TimeSpan.FromDays(30);
    options.SlidingExpiration = true;
});
```

even i tried this code on program.cs but no result:

```
builder.Services.Configure<SecurityStampValidatorOptions>(
    o => o.ValidationInterval = TimeSpan.FromDays(1));
```

### And Again : in my windows (localhost) it will works perfectly fine but when i publish the project and upload it on the host this problem will shows up

Any help would be appreciated
sorry about my english

### .NET Version

.NET 8

### Anything else?

IDE VS

Package version used:
Microsoft.AspNetCore.Identity.EntityFrameworkCore 8.0.10
Microsoft.AspNetCore.Identity.UI 8.0.10
Microsoft.EntityFrameworkCore.SqlServer 8.0.10
Microsoft.EntityFrameworkCore.Tools 8.0.10

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Please enable verbose logs and share these when you get a request timed out after 30 minutes. There should be enough there to help us understanding what happened and guide you accordingly. 
Here is a guide for how to configure logging: https://learn.microsoft.com/aspnet/core/fundamentals/logging/?view=aspnetcore-8.0#configure-logging

If that's a problem, a minimal repro project would help us investigate it on our side.
