### ISSUE TITLE
YAML configuration provider

### ISSUE THREAD

**Issue by stasberkov** [dotnet/aspnetcore#58614]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the solution you'd like

Currently, ASP.NET Core supports configuration providers for JSON, XML, and INI files. However, YAML is a popular configuration format due to its readability and support for complex data structures. Adding a YAML configuration provider would enhance the flexibility and usability of ASP.NET Core applications, especially for developers who prefer or require YAML for their configuration needs.

Benefits:
- Increased flexibility in configuration file formats.
- Improved readability and maintainability of configuration files for developers who prefer YAML.
- Enhanced support for complex configuration scenarios.

### Additional context

YAML is widely used in various applications and tools, such as Kubernetes and Ansible, making it a valuable addition to the ASP.NET Core configuration system. By supporting YAML, ASP.NET Core can better align with the preferences and needs of a broader developer community.

**Comment by martincostello** [comment]
Looks like this issue should be transferred to [dotnet/runtime](https://github.com/dotnet/runtime) as that is where the majority of the configuration providers are implemented.

**Comment by stasberkov** [comment]
Moved to https://github.com/dotnet/runtime/issues/109199
