### ISSUE TITLE
Blazor WebAssembly - HTML select tag with @onchange event does not hit breakpoint when clicking to select values from dropdown using the cursor, but works with up/down key from keyboard

### ISSUE THREAD

**Issue by sly97** [dotnet/aspnetcore#58615]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

In .NET8, in a new Blazor WebAssembly app, when using a `<select>` tag, with the `@onchange` event, if I put a breakpoint in the method being triggered (i.e. `@onchange="Test"`), the breakpoint will not be hit if I click on different values in the dropdown using the mouse.
However, the breakpoint is being hit fine when using the up/down keys from the keyboard.

In addition, when using the mouse, I can see that the method is run and states are changed - the issue I experienced is the breakpoint that is not being hit.

Additional info: doing the same in .NET6 works fine, and breakpoint is being hit just fine in all cases.

```
@page "/"

<select @onchange="Test">
    <option value="1">1</option>
    <option value="2">2</option>
    <option value="3">3</option>
    <option value="4">4</option>
</select>

@code {
    private void Test()
    {
        // Given I've put a breakpoint in VS in the line above
        // It does not get triggered/hit when using the mouse/cursor to click in the dropdown, but it is hit when using up/down key works.
    }
}
```

### Expected Behavior

Breakpoint is being hit when using the mouse/cursor to select different values from a select statement with the `@onchange` event

### Steps To Reproduce

1. Create a new Blazor Web Assembly project in VS2022.
2. Add a select tag to any page (I did it to the `Counter` component)
3. add the `@onchange` event to the select tag, and assign it with a method
4. Put a breakpoint in the method assigned to the `@onchange` event
5. Run the app, click on different values in the dropdown, and see that the breakpoint is not being hit.
Then, try selecting using different values using the up/down keys from the keyboard, and the breakpoint should be hit

### Exceptions (if any)

Breakpoint is hit when using the mouse to select different values from a dropdown menu.

### .NET Version

8

**Comment by javiercn** [comment]
@sly97 thanks for contacting us.

Can you validate that the same behavior works if you switch Blazor Server? Can you also make sure that the underlying JS event is fired on the browser debugger? (You should be able to set a breakpoint when the event is raised).

**Comment by Kevin-Lewis** [comment]
> [@sly97](https://github.com/sly97) thanks for contacting us.
> 
> Can you validate that the same behavior works if you switch Blazor Server? Can you also make sure that the underlying JS event is fired on the browser debugger? (You should be able to set a breakpoint when the event is raised).

I also checked the underlying JS event and verified it is being fired as expected even when the breakpoint for my .>NET event isn't hit. To summarize:

- Click on the select, navigate to an option with arrow keys, click on the option -> **Works**
- Click on the select, click on the option -> **Does not Work**
- Click on the select, navigate to an option with arrow keys, press enter key -> **Does not Work**

**Comment by sly97** [comment]
@javiercn
Apologies for the late reply.
I have checked and it seems to be working fine in Blazor Server (I've created a new project from VS, and chose the Blazor Server template option).
Also, thanks @Kevin-Lewis for your update, and can confirm that I get the same results when looking at the underlying JS events.
Can this issue please be re-opened as it seems to be a valid & ongoing issue?

**Comment by Marques01** [comment]
the problem still persists. It only hits the breakpoint with the arrows and not with clicks on the select

<label class="form-label">Countries</label>
<select class="form-select" @onchange="OnCountryChanged">
    <option value="1">USA></option>
    <option value="2">Canada</option>
    <option value="3">Mexico</option>
</select>
@code {

    private void OnCountryChanged(ChangeEventArgs e)
    {
    }

}

**Comment by affenkonig11b** [comment]
Also seeing this. Any updates?

**Comment by Precyzja** [comment]
Hi, the workaround may be to use "@oninput" instead of "@onchange". Hope it help someone, as it helped me. Cheers.

**Comment by kpi-Peru** [comment]
<InputSelect id="inDepartamento" Value="@pedido.IdDepartamento" ValueExpression="@(()=>pedido.IdDepartamento)" ValueChanged="@((string value)=>mostrarProvincia(value))".......
