### ISSUE TITLE
.Net 9 Blazor Server doesn't find components in interactive mode

### ISSUE THREAD

**Issue by Julien-Marpault** [dotnet/aspnetcore#58625]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

I have a solution with a hierarchy of projects:

Store
|_ Presentation
    |_ Application
       |_Domain
etc.

My App.razor and Routes.razor are in the Store project. My other pages are in the presentation project.

I added AdditionalAssemblies:
```csharp
app.MapRazorComponents<App>()
    .AddInteractiveServerRenderMode()
    .AddAdditionalAssemblies(typeof(Presentation.Pages.Index).Assembly);
```

If I try to use InteractiveServer on Routes component I get a Not found error, the app can't find the '/' route. The same issue occurs when using this mode on HeadOutlet component.

If I don't use InteractiveServer render mode it works fine.

So I tried to apply InteractiveServer to my Layout because I have some interactivity in my layout.
I get this error:

InvalidOperationException: Cannot pass the parameter 'Body' to component 'MainLayout' with rendermode 'InteractiveServerRenderMode'. This is because the parameter is of the delegate type 'Microsoft.AspNetCore.Components.RenderFragment', which is arbitrary code and cannot be serialized.

Last try, I moved my pages to Store project leaving other components to Presentation.
It works fine, but it's an issue to not be able to put my pages in a separate library.

**Comment by javiercn** [comment]
@Julien-Marpault thanks for contacting us.

You also need to add the additional assemblies to the `Router` Component.

**Comment by Julien-Marpault** [comment]
It works fine with additional assemblies added to the router. I forgot that point. Thank you.
