### ISSUE TITLE
Dynamic Loading of Blazor Component in WEB Forms .NET Framework 4.8

### ISSUE THREAD

**Issue by DStarts23** [dotnet/aspnetcore#58626]
Hi, can you tell me how we can dynamically load the Blazor Components in Web Forms? Without using WASM Static strategy and `iframe` as we don't know it's future because google is ending the support for 3rd part cookies.

Created this blazor component in `pages\MyBlazorComponent.razor`:
`@page "/component"
@inject IJSRuntime JS

<h3>Blazor Component</h3>
<p>This is rendered by Blazor!</p>
<button @onclick="ShowAlert">Click Me!</button>
@code {
    private void ShowAlert()
    {
        JS.InvokeVoidAsync("alert", "Blazor button clicked!");
    }
}`

In `program.cs`, addded all the builder services related to CORS, HTTPS Redirection.
`// Enable CORS for localhost:port for your Web Forms app
builder.Services.AddCors(options =>
{
    options.AddPolicy("AllowWebFormsApp",
        builder => builder.WithOrigins("https://localhost:44307")
                          .AllowAnyMethod()
                          .AllowAnyHeader()
                          .AllowCredentials()); // Ensure credentials are allowed if needed
});
var app = builder.Build();
// Configure the HTTP request pipeline.
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler(errorApp =>
    {
        errorApp.Run(async context =>
        {
            context.Response.StatusCode = StatusCodes.Status500InternalServerError;
            await context.Response.WriteAsync("Circuit initialization failed. Please check server logs.");
        });
    });
// The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app.UseHsts();
}
app.UseHttpsRedirection();
app.UseStaticFiles();
app.UseCors("AllowWebFormsApp");
app.UseRouting();
app.UseWebSockets(); // Enable WebSockets explicitly
app.MapBlazorHub();
app.MapFallbackToPage("/_Host");
app.Run();`

And in Web Forms application, I have created a new Page, `Component.aspx` file:
`<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Blazor Web Form</title>
   <base href="https://localhost:7101/" />
</head>
<body>
    <form id="form1" runat="server">
        <div id="blazor-root"></div>
    </form>
   <script>
       window.addEventListener('load', () => {
           // Check if Blazor has already been loaded
           if (!window.BlazorLoaded) {
               const script = document.createElement('script');
               script.src = 'https://localhost:7101/_framework/blazor.server.js';
               script.setAttribute('autostart', 'false');
               script.onload = () => {
                   // Initialize Blazor only once
                   Blazor.start({
                       serverSide: true,
                       applicationBaseUri: 'https://localhost:7101/', // Ensure Blazor uses correct base URI
                       webSocket: true
                   }).then(() => {
                       Blazor.rootComponents.add('MyBlazorComponent', document.getElementById('blazor-root'));
                   });
                   window.BlazorLoaded = true;
               };
               document.body.appendChild(script);
           }
       });
   </script>
</body>
</html>`

But I am still getting these two errors, screenshot is attaches:
![Image](https://github.com/user-attachments/assets/3630582a-2e2d-40b5-a752-2e1a4f565b91)

I also add `builder.Services.AddServerSideBlazor().AddCircuitOptions(o =>
{
    o.DetailedErrors = true;

});`

But it also doesn't seems to resolve the issue. Can anyone tell me how we can load dynamically Blazor Components in Web Forms, We have a huge application in .NET 4.8 Framework, which we need to migrate to Blazor Server, page by page, as the application communicates with real time updates and get data from other clients and server applications.

**Comment by javiercn** [comment]
@DStarts23 thanks for contacting us.

You can't load Blazor Web Components on .NET framework 4.8. It's not a supported platform. The only strategies you can follow are:
* Rendering components inside an iframe (on a separate host process that runs .NET Core if you are using prerendering or Blazor Server).
* Use Blazor Webassembly without prerendering, typically creating a standalone webassembly app and copying the output files into your host webforms app and configuring IIS to serve it.
