### ISSUE TITLE
[SignalR] Connection fails to consume ping messages leading to disconnect

### ISSUE THREAD

**Issue by TimNguyenVN** [dotnet/aspnetcore#58623]
Hi there, I'm currently using SignalR in a Blazor project and encountered an issue after configuring the `HttpMessageHandlerFactory` options as shown below:
 ![Image](https://github.com/user-attachments/assets/20f64ffa-55be-477f-be49-9d62c3426ac0)

The connection seems unable to properly process ping messages from the server, leading to an automatic disconnect. I can see that the connection receives 3 ping messages from the server every 15 seconds:
![Image](https://github.com/user-attachments/assets/9ea994f4-09a1-4677-9e1a-af39af97f49f)
However, after 60 seconds, the connection automatically disconnects with the following error:
`Server timeout (60000.00ms) elapsed without receiving a message from the server.`

When I comment out the `HttpMessageHandlerFactory` configuration, the connection consumes the ping messages and remains active without disconnecting.

Could anyone help explain what's happening here? Is this a bug, or did I miss a configuration step? If possible, could you provide example configurations to help resolve this?

Thanks in advance!

**Comment by BrennanConroy** [comment]
You're in the browser using a websocket connection, so `HttpMessageHandlerFactory` should have 0 effect on how the websocket behaves.

You should look at [client and server logs](https://learn.microsoft.com/aspnet/core/signalr/diagnostics) to see if there are any problems.

Also, try including the inner handler in your custom http handler just in-case there is some weird behavior there.
See https://learn.microsoft.com/aspnet/core/blazor/fundamentals/signalr?#client-side-signalr-cross-origin-negotiation-for-authentication as an example.

**Comment by TimNguyenVN** [comment]
Hi @BrennanConroy, thank you for your response, you were correct that the `HttpMessageHandlerFactory` isn’t the root cause of the issue. 
I've enabled debug configuration in my Blazor WebAssembly application, and you can find the complete log here:
[localhost-1730085365291.log](https://github.com/user-attachments/files/17537006/localhost-1730085365291.log)

From the logs, it appears that the client connection is successfully receiving messages:
```
10:10:38.651 invoke-js.ts:176 dbug: Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport[13]
      Received message from application. Payload size: 11.
10:10:54.649 invoke-js.ts:176 dbug: Microsoft.AspNetCore.SignalR.Client.HubConnection[59]
      Sending PingMessage message.
10:10:54.649 invoke-js.ts:176 dbug: Microsoft.AspNetCore.SignalR.Client.HubConnection[60]
      Sending PingMessage message completed.

``` 
However, it appears that the processing part is missing. When I tested connecting to a simulated hub, it included the processing step, which kept the connection open:
```
10:34:43.410 invoke-js.ts:176 dbug: Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport[13]
      Received message from application. Payload size: 11.
10:34:58.110 invoke-js.ts:176 dbug: Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport[12]
      Message received. Type: Text, size: 11, EndOfMessage: True.
10:34:58.111 invoke-js.ts:176 dbug: Microsoft.AspNetCore.SignalR.Client.HubConnection[56]
      Processing 11 byte message from server.
```

Do you have any ideas on this?

**Comment by BrennanConroy** [comment]
It looks like the server isn't sending anything to the client. You should look at the server logs.

Also, what is a "simulated hub"?

**Comment by TimNguyenVN** [comment]
Hi @BrennanConroy, Thank you for your response.
I'm integrating [Elsa Workflows](https://github.com/elsa-workflows/elsa-core) into my project, and I'm encountering an issue with the client connection when connecting to the Elsa SignalR Hub to receive progress updates.

About "simulated hub" 
To troubleshoot, I set up a separate "simulated hub" with a basic configuration to test SignalR functionality:
```
builder.Services.AddSignalR(options =>
{
    options.EnableDetailedErrors = true;
    options.DisableImplicitFromServicesParameters = true;
});
```


By the way, I have already enabled debug configuration on the server.
This is the complete logs on the server:[ServerLog.log](https://github.com/user-attachments/files/17551055/ServerLog.log)

From the logs, it appears that the server is successfully receiving ping messages:
```
trce: Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport[9]
      Message received. Type: Text, size: 11, EndOfMessage: True.
trce: Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport[9]
      Message received. Type: Text, size: 11, EndOfMessage: True.
trce: Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport[9]
      Message received. Type: Text, size: 11, EndOfMessage: True.
```
However, it seems like the server isn't sending messages back to the client, as there are no logs indicating messages being sent. In contrast, when I tested with the simulated hub, I could see that messages were both received and sent:

```
trce: Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport[9]
      Message received. Type: Text, size: 11, EndOfMessage: True.
trce: Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport[11]
      Sending payload: 11 bytes.
trce: Microsoft.AspNetCore.SignalR.HubConnectionContext[3]
      Sent a ping message to the client.
trce: Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport[9]
      Message received. Type: Text, size: 11, EndOfMessage: True.
```
There are no error logs that provide additional insights into the issue. Do you have any ideas on why messages from the server to the client seem to be missing in this case?
Let me know if I should clarify or add any details! Thank you!

**Comment by BrennanConroy** [comment]
> I'm integrating [Elsa Workflows](https://github.com/elsa-workflows/elsa-core) into my project, and I'm encountering an issue with the client connection when connecting to the Elsa SignalR Hub to receive progress updates.

Ok, so you're having issues when using a library not written by us. Sounds like you should go investigate that.
