### ISSUE TITLE
AOT warnings on minimal API Map* methods outside of Program.cs, especially in web library projects

### ISSUE THREAD

**Issue by sakuk005** [dotnet/aspnetcore#58678]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

When calling the `Map*` methods (`MapGroup`, `MapGet`, `MapPost`, etc.) from a file other than Program.cs with `<IsAotCompatible>true</IsAotCompatible>`, the compiler reports IL3050 warnings even if the delegate closure's type information is known at compile time.

### Expected Behavior

No trim or AOT warnings are produced for calls to `Map*` methods outside of Program.cs when `<IsAotCompatible>true</IsAotCompatible>`.

### Steps To Reproduce

1. Create a new AOT web API with `dotnet new webapiaot`.
2. Create Program.cs:
    ```cs
    // Program.cs
    var builder = WebApplication.CreateBuilder();
    var app = builder.Build();
    app.MapGet("/", () => ""); // This line does not produce an AOT warning.
    app.UseNonProgramCs();
    app.Run();
    ```

3. Create ExternalHandlers.cs:
    ```cs
    // ExternalHandlers.cs
    public static class ExternalHandlerExtensions
    {
        public static IEndpointRouteBuilder UseNonProgramCs(this IEndpointRouteBuilder builder)
        {
            builder.MapGet("/", () => ""); // This line produces IL3050 erroneously.
            return builder;
        }
    }
    ```

4. Observe erroneous compiler warnings in IDE and at build.

### Exceptions (if any)

IL3050: Using member 'Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapGet(IEndpointRouteBuilder, String, Delegate)' which has 'RequiresDynamicCodeAttribute' can break functionality when AOT compiling. This API may perform reflection on the supplied delegate and its parameters. These types may require generated code and aren't compatible with native AOT applications.

### .NET Version

8.0.204

### Anything else?

Known workaround: Add `<EnableRequestDelegateGenerator>true</EnableRequestDelegateGenerator>` to the library project.

**Comment by captainsafia** [comment]
@sakuk005 Thanks for reporting this issue!

The Request Delegate Generator is currently configured as off-by-default _unless_  `PublishTrimmed` = `true` or `PublishAot` = `true` _and_ the project references the Web SDK. Under those scenarios, it is necessary to enable the Request DelegateGenerator manually with the flag that you referenced in the issue.

Given the different in behavior between compile-time and run-time code gen, I don't think we'd expect the set of scenarios in which the `EnableRequestDelegateGenerator` is on by default.
