### ISSUE TITLE
Dotnet 8 - Blazor Server - JS Interopt Can't Be Used In Delegating Handlers with Prerender Off

### ISSUE THREAD

**Issue by grwomack-epicor** [dotnet/aspnetcore#58682]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Hi,

Original closed case: https://github.com/dotnet/aspnetcore/issues/40336

JS Interop throws an error when used inside a `DelegatingHandler` when the render mode is globally set to `@rendermode="@(new [InteractiveServerRenderMode(false))` and calling the `DelegatingHandler` from the `OnAfterRenderAsync(bool firstRender)` lifecycle method.

Dotnet 8 SDK
![Image](https://github.com/user-attachments/assets/4821e791-577e-4ca3-bc39-7d8f44ef56ef)

Github Link:
[Github: DelegatingHandlerBug - JS Interop](https://github.com/grwomack-epicor/DelegatingHandlerBug.git)

1) First JS Alert will trigger when running the project on the homepage using the `OnAfterRenderAsync(bool firstRender)` life cycle method.
2) An HttpRequest is asked to be sent after the user clicks "Okay" to the first alert on the page.
3) The `DelegatingHandler` handler kicks in before sending the request to a bogus endpoint.
4) The `DelegatingHandler` will try to push a JS Alert using the `IJSRuntime` before sending the http request.
5) The 2nd alert throws an error before the http request is sent.

Best,
Garrett

### Expected Behavior

A second JS Alert should show up on the home page.

### Steps To Reproduce

1) Run the solution
2) Click "Okay" on the first alert
3) The error will be immediately thrown after from the delegating handler

### Exceptions (if any)

Changing the rendermode to  `@rendermode="@(new [InteractiveWebAssemblyRenderMode(false))` will result in the expected behavior.

Changing the rendermode to  `@rendermode="@(new [InteractiveAutoRenderMode(false))` will fail if a WebSocket is created and succeed if the browser is refreshed and runs the application as Web Assembly.

### .NET Version

8.0.403

**Comment by javiercn** [comment]
@grwomack-epicor thanks for contacting us.

Your issue is here, `HttpClientFactory` creates its own scope, so you are getting an unitialized IJSRuntime instance.

https://github.com/grwomack-epicor/DelegatingHandlerBug/blob/main/DelegatingHandlerBug/DelegatingHandlerBug/Program.cs#L14-L15

See https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/dependency-injection?view=aspnetcore-8.0#access-server-side-blazor-services-from-a-different-di-scope for docs and samples.

**Comment by grwomack-epicor** [comment]
Hi Javiercn,

I can confirm that this link solved my problem: [CircuitServicesAccessor](https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/dependency-injection?view=aspnetcore-8.0#access-server-side-blazor-services-from-a-different-di-scope).

For anyone in the future, this needs to be manually copy and pasted into your server project (use the link above) and added it to the server's DI container.

The github link above shows the correction on the most recent commit (3rd commit).

Best,
Garrett
