### ISSUE TITLE
Blazor - Why does NavigationManager.BaseUri not output https in the deployed application, but http?

### ISSUE THREAD

**Issue by Zardw** [dotnet/aspnetcore#58685]
I try using Blazor Server to develop the App for the first time. I deployed the App to the Ubuntu server, set up Nginx, and everything worked fine using http. However, when I installed the **SSL certificate**, a problem occurred.

A **Mixed Content** error occurred. I noticed that the output of `@NavigationManager.BaseUri` was still http, not https. but URL path is https, I checked the code and Nginx configuration and found no problem.

Also used `app.UseHttpsRedirection()`, I looked for the answer from Google and tried to add `<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">`, but the database could not be used, so I feel like this doesn't solve the problem :(
please help, thanks in advance!

`<base href="@NavigationManager.BaseUri" />`

`Mixed Content: The page at 'https://domain.com/Login' was loaded over HTTPS, but requested an insecure stylesheet 'http://domain.com/_content/blazor/css/default-base.css?v=5.4.0.0'. This request has been blocked; the content must be served over HTTPS.`

![Image](https://github.com/user-attachments/assets/765ce968-2bd5-409f-a975-b334fb856043)

**Comment by javiercn** [comment]
@Zardw thanks for contacting us.

`NavigationManager.BaseUri` reflects the contents of `document.baseURI` which is what the browser has access to.
