### ISSUE TITLE
Publishing Blazor WASM on .NET 8 Fails Due to Integrity Checks with Cloudflare Script Injection

### ISSUE THREAD

**Issue by JarFrank** [dotnet/aspnetcore#58714]
I am experiencing an issue with Blazor WASM on .NET 8 related to integrity checks. My application is hosted on an Azure Static Web App (SWA), and my subdomain is managed through Cloudflare. However, Cloudflare is injecting JavaScript into my application, which causes integrity checks to fail during deployment.

Unfortunately, I cannot disable the script injection on Cloudflare because it impacts the entire domain configuration, and I’ve been informed that it is necessary for other parts of our infrastructure.

This issue may have broader implications beyond my setup. For example, in SWA, there is a similar capability where tracking scripts can be injected into the `index.html` file. This raises the question: is there a configuration or workaround that would allow integrity checks to pass in such cases where scripts are injected post-deployment?

**Additional Information:**
Link to Cloudflare's documentation on JavaScript injections and their bot detection: [Cloudflare Bot Management - JavaScript Detections](https://developers.cloudflare.com/bots/reference/javascript-detections/#what-are-javascript-detections).

**Environment:**
- .NET Version: 8.0
- Hosting Platform: Azure Static Web Apps
- CDN: Cloudflare

**Questions:**
- Is there a recommended configuration or workaround in Blazor WASM to bypass integrity checks when trusted external scripts are injected?
- Has this issue been encountered in other scenarios, or is there a broader solution for SWA with Cloudflare?

**Comment by javiercn** [comment]
@JarFrank thanks for contacting us

Where are the integrity check failures coming from? Are these coming from the `index.html` in the `service-worker.js` file?

**Comment by JarFrank** [comment]
@javiercn  The integrity check failures are indeed coming from the `index.html` in th `service-worker.js` file.

As a temporary workaround, I'm following the guidance in the documentation to disable integrity checking for PWAs, as outlined here: [Disable integrity checking for PWAs](https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-8.0#disable-integrity-checking-for-pwas). However, this isn't a viable long-term solution for me because I want to ensure integrity checks are in place to prevent potential issues where the application could end up in a broken state.

**Comment by javiercn** [comment]
@JarFrank thanks for the additional details.

Unfortunately, this is one of the situations where you have to choose. You can't have something that injects a script dynamically and validate against a static integrity value generated during build time.

At best you could always force the download of the `index.html` by issuing a request with the `no-cache` directive to bypass any HTTP cache in the browser.

All these changes are up to you to make on the `service-worker.js` file.

**Comment by JarFrank** [comment]
After excluding `index.html` from caching, I'm encountering another integrity issue, this time related to `blazor.boot.json`.

Here’s the configuration in `service-worker.published.js`:

```javascript
const offlineAssetsExclude = [ /^service-worker\.js$/, /^index.html$/];
```

**Error Message:**
```
Failed to find a valid digest in the 'integrity' attribute for resource 'https://my.domain.com/_framework/blazor.boot.json' with computed SHA-256 integrity '0qd128cnohISCo7F4ZhJ8RjvvnwUeMhVFPtqChkgpj0='. The resource has been blocked.
```

**Additional Investigation:**
I compared the `blazor.boot.json` files from different builds, and it appears that a few hashes are consistently different. Specifically, I noticed discrepancies in files like:
- `Polly.Core.wasm`
- `Polly.Extensions.wasm`
- `Polly.RateLimiting.wasm`
- Several files from my own project assemblies

**Comment by javiercn** [comment]
@JarFrank thanks for the additional details.

That might be due to caching that `cloudflare` might be introducing that you might need to configure. Each build might change the hashes of files, as they go through several optimization processes.

**Comment by JarFrank** [comment]
In this case, I’m not entirely sure if the issue is related to `Cloudflare`. For all request `cf-cache-status` is set to `DYNAMIC`. When I open the app in an incognito window or clear the site data, it works as expected. However, it seems that after publishing a new version, the existing Blazor application compares cached files with the new hashes. This leads to the integrity error immediately upon refreshing the page.

Question:
If I exclude `index.html` from caching, does this disrupt the overall loading process of the application? Is there any documentation or recommended approach to skip the integrity check specifically for `index.html` without affecting the integrity of other cached assets?

```
> Navigated to https://my-domain/
> Failed to find a valid digest in the 'integrity' attribute for resource 'https://my-domain/_framework/MyProject.Core.Shared.wasm' with computed SHA-256 integrity 'ksI/+PdDTRxW0dEeMNqHekaSLmua90J5m/Z05AKqZK0='. The resource has been blocked.
> Unknown error occurred while trying to verify integrity.
> Error in mono_download_assets: Error: download 'https://my-domain/_framework/MyProject.Core.Shared.wasm' for MyProject.Core.Shared.wasm failed 0 TypeError: Failed to fetch
> Failed to find a valid digest in the 'integrity' attribute for resource 'https://my-domain/_framework/MyProject.Shared.wasm' with computed SHA-256 integrity 'm/KXF7DZbVku7RhHzfNZmnjWOrG7lCYBOF244qwbGZA='. The resource has been blocked.
> Unknown error occurred while trying to verify integrity.
```

**Comment by JarFrank** [comment]
I tested this today, and surprisingly, everything seems to work without any errors—unexpected, but it’s good news!

I noticed that Blazor WebAssembly uses two types of caches: Offline-Cache-Version and Dotnet-Resources. Here’s my understanding:

Dotnet-Resources: This cache stores DLLs and WASM files, and the application serves these resources from here directly.
Offline Cache: This cache is used to download and retain the WASM and DLL files, likely to support offline functionality for the Blazor application.
Can you confirm if this understanding is correct, or clarify any differences between how these two caches are intended to function in Blazor WebAssembly?

**Comment by epavolucci** [comment]
I 've the same problem mentioned by JarFrank, 

if i esclude index.html from caching and from integrity check, some times integrity check errors appear on other files.
