### ISSUE TITLE
[Blazor WASM] Razor helper methods will not render content when used as inner HTML of components

### ISSUE THREAD

**Issue by DrewM-Hax0r** [dotnet/aspnetcore#58717]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Razor helper methods will not render their HTML content when used inside the inner HTML of a custom razor component.

### Expected Behavior

I would expect the razor helper HTML content to be rendered correctly as child content in the custom component.

### Steps To Reproduce

Please see the linked repl environment to see an example of the issue:
https://blazorrepl.telerik.com/GSbYdOQY29VSi3lC48

In this project, I have created a custom component which renders it's child content using a render fragment parameter. In the main page I have provided inner HTML for this component via a razor helper method defined in the same file. The test component does not render the child content if it is provided from the razor helper method in the main page. Note that the test component does render the child content if the razor helper method is not used. Also note the razor helper method will render its content correctly when used in the main page, not passed as child content to the test component.

### .NET Version

.NET 8

### Anything else?

I have reproduced this issue in an empty Blazor WASM project, running the current version of VS Professional (17.11.5), the latest version of .NET 8, and the latest Blazor WASM packages for ASP.NET Core on .NET 8 (8.0.10).

**Comment by javiercn** [comment]
@DrewM-Hax0r thanks for contacting us.

Please provide a regular repro as the link you provided only shows a couple of files and doesn't seem to show what's going on.

**Comment by DrewM-Hax0r** [comment]
I created a minimal repro project using Telerik REPL here:
https://blazorrepl.telerik.com/GSbYdOQY29VSi3lC48

**Comment by DrewM-Hax0r** [comment]
https://github.com/DrewM-Hax0r/BlazorWasmInnerHtmlUseRazorHelper/tree/main

The two files of note are the main Index.razor page and the TestComponent.razor component. The index page shows examples of different ways to render the content using custom components and razor helper methods. The RenderContent() function in Index.razor does not render its content when used as inner HTML to the TestComponent.

**Comment by javiercn** [comment]
@DrewM-Hax0r thanks for contacting us.

```razor
<h2>Test using inner HTML inside components - does not render when using razor helper</h2>
<TestComponent>
    @{RenderContent();}
</TestComponent>
```

This is not a supported syntax.

If you want to get to the bottom of it, you can look at the compiled code by emitting the source code from the source generator and maybe you find a way to make it work. 

However, this is not an official feature the compiler has, and it just so happens in some cases it happens to work for some scenarios by chance.
