### ISSUE TITLE
Deprecated str.substr warning

### ISSUE THREAD

**Issue by jdarwood007** [dotnet/aspnetcore#58720]
I receive the following warning in Visual Studio
```
TS6387	(JS) The signature '(from: number, length?: number): string' of 'str.substr' is deprecated.	signalr.js	380		
```

The affected code seems to be:

https://github.com/dotnet/aspnetcore/blob/47a0a40e82e55243ac277c5a44ee31f6a2afed24/src/SignalR/clients/ts/signalr/src/Utils.ts#L90
```
function formatArrayBuffer(data) {
    const view = new Uint8Array(data);
    // Uint8Array.map only supports returning another Uint8Array?
    let str = "";
    view.forEach((num) => {
        const pad = num < 16 ? "0" : "";
        str += `0x${pad}${num.toString(16)} `;
    });
    // Trim of trailing space.
    return str.substr(0, str.length - 1);
}
```

Seems to be simple, use `str.substring` instead.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr

**Comment by BrennanConroy** [comment]
https://github.com/search?q=repo%3Adotnet%2Faspnetcore+%22substr%28%22+language%3ATypeScript&type=code&l=TypeScript
and
https://github.com/search?q=repo%3Adotnet%2Faspnetcore+%22substr%28%22+language%3AJavaScript+&type=code

Although the Javascript one is from https://github.com/aspnet/jquery-validation-unobtrusive so we would update it over there.
