### ISSUE TITLE
Using Blazor Web App template in dotnet 8. Upload component doesn't fire "onChange" event

### ISSUE THREAD

**Issue by ghazanfar381** [dotnet/aspnetcore#58729]
Using Blazor Web App template in dotnet 8. Upload component doesn't fire "onChange" event.
then i used same component in blazor sever template by creating new project with dotnet 7 . component works perfectly. Event is being fired. Please fix it.
You can further check it may be possible that no razor controls firing events.

**Comment by chsienki** [comment]
Moving to aspnetcore
