### ISSUE TITLE
Exceptions from IHubActivator.Create are not being propagated to SignalR Client

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#58749]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Exceptions-from-IHubActivatorCreate-are/10778098)._

---
[severity:I'm unable to use this version]
**Issue Summary:**

I have a SignalR server project which implements the Create method from the Microsoft.AspNet.SignalR.IHubActivator interface.

If an exception occurs in this Create method, I do not receive the corresponding exception on the client side.  In other cases, when exceptions occur on the server side, they are propagated to the client so I can handle them appropriately, but not in this case. 

Here is a simple chat application which demonstrates the issue: 
[SignalRSelfHost.zip](https://aka.ms/dc/file?name=B97e92fe3ac8440abab8d7cf8aacc58d5638657442421294075_SignalRSelfHost.zip&tid=97e92fe3ac8440abab8d7cf8aacc58d5638657442421294075)

This is based on the SignalR Self-Host tutorial [here](https://learn.microsoft.com/en-us/aspnet/signalr/overview/deployment/tutorial-signalr-self-host).

In the server portion of the application (SignalRSelfHost.csproj) I throw an exception in my IHubActivator implementation as shown below:

![image.png](https://aka.ms/dc/image?name=B450250fb1c154da0a438ba9cf042b449638657428865282417_20241028-130806-image.png&tid=450250fb1c154da0a438ba9cf042b449638657428865282417)

In the client project (JavascriptClient) I have an error handler which should be called whenever an error occurs when calling the only method on the SignalR hub, as shown below:

![image.png](https://aka.ms/dc/image?name=B861be01a427a4ce8b48c8b9dd3480ae6638657428534940678_20241028-130733-image.png&tid=861be01a427a4ce8b48c8b9dd3480ae6638657428534940678)

But when I run the project, no exception appears in the console window of the browser.

**Questions:**

1. Is there any way I can ensure that the client receives exceptions that are thrown in the IHubActivator.Create method?

2. If I am unable to propagate exceptions from the IHubActivator.Create method, my backup plan is to just return null whenever an exception occurs in IHubActivator.Create, since this does produce an exception on the client side.  This way I can just output a generic message such as "Error occurred when creating SignalR Hub".  Would you see any issue with handling IHubActivator.Create exceptions in this way?

**Reproduction Steps:**

Perform the following steps to reproduce the issue:

1. Download the attached zip folder and extract the SignalRSelfHost solution.
2. Build and run the solution. Both the Chat App and Server should run.
3. Open the developer console window in the Chat App window.
4. Send a test message through the Chat app.
5. Notice that no message appears in the console window even though an exception occured.

---
#### Feedback Bot on 10/28/2024, 06:37 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

**Comment by BrennanConroy** [comment]
Exceptions are not exposed to the user by default to avoid leaking information. https://learn.microsoft.com/aspnet/core/signalr/security?view=aspnetcore-8.0#exceptions

If you are explicitly throwing an error that you are ok with the client seeing, then you can throw a `HubException`.
https://learn.microsoft.com/aspnet/core/signalr/hubs?view=aspnetcore-8.0#handle-errors
