### ISSUE TITLE
Compile Fails in 2022 Preview but works in 2022

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#58748]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Compile-Fails-in-2022-Preview-but-works-/10780787)._

---
When i compile my solution with **Visual Studio 2022 Preview Version 5.0**, it fails, but if i compile the exact same solution with **Visual Studio 2022**, it works fine.  

The following is the error...

System.InvalidOperationException: No file exists for the asset at either location 'wwwroot\css\dx-reporting-skeleton-screen.css' or 'wwwroot\css\dx-reporting-skeleton-screen.css'. 
at Microsoft.AspNetCore.StaticWebAssets.Tasks.StaticWebAsset.ComputeFingerprintAndIntegrity(String identity, String originalItemSpec)
at Microsoft.AspNetCore.StaticWebAssets.Tasks.DefineStaticWebAssets.Execute()

But the file does exist & as i mentioned, if i compile it with Visual Studio 2022, it works fine.  This has been happening for quite some time now.

---
#### Feedback Bot on 10/31/2024, 06:28 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

**Comment by church365** [comment]
I just updated to VS 17.12.4 and am getting this exact error now on build. There have been no other changes to the project other than this upgrade. If I close VS, reopen it, and run my project it works, but as soon as I do a rebuild I get this error and I have to restart VS again. Using WebCompiler 2022+ 1.14.11

**Comment by mmessagie1** [comment]
I have the same problem and literally no one has a solution.  Other than going back to 17.11.4 

SUCH CRAP!
