### ISSUE TITLE
Too many of the same ACCELERATE KEYS (Alt+I) when creating a new project Blazor web app

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#58750]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Too-many-ACCELERATE-KEYS-AltI-when-cr/10516651)._

---
[severity:It's more difficult to complete my work] [regression] [worked-in:17.9 preview 1]
I know I've had this problem before and been ignored but I think this is bad

![Image](https://github.com/user-attachments/assets/e00e28f5-5cf7-404a-8ed7-ac52132c30a3)

 UI design and very cumbersome to use without a mouse.

Please see the file attached for more information.

---
#### Feedback Bot on 11/15/2023, 08:39 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 11/21/2023, 10:44 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

**Comment by javiercn** [comment]
Thanks for contacting us.

@mkArtakMSFT this isn't anything we can control on the templates afaik.

This is a visual studio issue that would require a feature on VS to control the hotkeys.
