### ISSUE TITLE
Stop embedding JS files in Endpoints and Server assemblies

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#58783]
Stop embedding JS files in Endpoints and Server assemblies, so they benefit from compression. Instead make them ship as static web assets. We can put them in the runtime pack for asp.net core and pick them in the SDK. (P1)
blazor.web.js goes from 180 KB to 43KB with brotli.
blazor.server.js goes from 146.58 KB to 35KB with brotli.

**Comment by MarvelTiter** [comment]
is it mean that i can build blazor.web.js myself?
