### ISSUE TITLE
The SignalR server is suspended and can no longer send messages to the client.

### ISSUE THREAD

**Issue by zhenlei520** [dotnet/aspnetcore#58828]
I'm not sure if this is a bug. When using SignalR to push messages to the client, I encountered the following problems:

1. The ConnectionId obtained by the SignalR server is inconsistent with the actual ConnectionId of the client

   ​	Scenario: The client encounters resource shortage, and the following error occurs after the client reconnects

2. The SignalR service is suspended and can no longer send messages to the client.

   This often happens when the SignalR server sends a large amount of data to the client.

**Comment by BrennanConroy** [comment]
> The ConnectionId obtained by the SignalR server is inconsistent with the actual ConnectionId of the client

Can you explain?

> Scenario: The client encounters resource shortage, and the following error occurs after the client reconnects

You didn't include an error.

> The SignalR service is suspended and can no longer send messages to the client.

What do you mean suspended? And by service do you mean your server application?

**Comment by zhenlei520** [comment]
> > The ConnectionId obtained by the SignalR server is inconsistent with the actual ConnectionId of the client

We discovered this problem through logs. In the SignalR server log, we saw that the message was pushed to the client normally, but the corresponding client did not receive the corresponding message. Through the client reconnection log, we found that the corresponding ConnnectionId changed.

> > Scenario: The client encounters resource shortage, and the following error occurs after the client reconnects

The SignalR server pushes messages to the client in BackgroundService. In the BackgroundService task, it is an infinite loop. When timely messages are received, messages are sent to the corresponding clients through SignalR, and this operation is in try catch. However, when SignalR stops pushing messages, no error logs are found. What's even more strange is that checking the client logs shows that during this period, there are still clients connected to the SignalR server, but it is not clear why the server push is blocked. It returns to normal after restarting the SignalR service. I don't know if this is related to the synchronous call to the asynchronous method, but I have never encountered such a problem before using Parallel.ForEach to call the push method.

```
_hub.Clients.Client(data.ConnectionId).SendAsync(nameof(IRelationClient.PublishAsync), data.Dtos.ToArray()).Wait();
```
 
> > The SignalR service is suspended and can no longer send messages to the client.
> 
> What do you mean suspended? And by service do you mean your server application?

**Comment by BrennanConroy** [comment]
> Through the client reconnection log, we found that the corresponding ConnnectionId changed.

That's expected. Connection ID changes across new connections.

It sounds like you might be assuming that the ConnectionId persists and your code is written with that assumption. So `_hub.Clients.Client(data.ConnectionId).SendAsync...` will end up sending to a connection that no longer exists anymore, hence why you think things aren't working.

**Comment by zhenlei520** [comment]
> > Through the client reconnection log, we found that the corresponding ConnnectionId changed.
> 
> That's expected. Connection ID changes across new connections.
> 
> It sounds like you might be assuming that the ConnectionId persists and your code is written with that assumption. So `_hub.Clients.Client(data.ConnectionId).SendAsync...` will end up sending to a connection that no longer exists anymore, hence why you think things aren't working.

After the client reconnects, the client will re-register a new ConnectionId with the server, and there should not be a situation where the values ​​on both sides are different
