### ISSUE TITLE
Unhandled error when using Blazor .NET 8 template in Global page mode with FireFox

### ISSUE THREAD

**Issue by jpacc260** [dotnet/aspnetcore#58824]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Selecting "Global" as the interactivity location on the blazor template generator for "Blazor Web App" with .Net8, produces a web app that crashes in FireFox with the "An unhandled error has occurred" message.
It happens when "Interactive render mode" is set to "Server", but there is also a similar issue with "WebAssembly".
With "Server" as the Interactive mode, it gives errors to both the server console, and the browser console.
PerPage mode does not have this problem.

### Expected Behavior

Expected behaviour is that the page renders, and no error is thrown.

### Steps To Reproduce

Step 1) Use the DotNet 8 "Blazor Web App" Template generator (I use it through Visual Studio)
Step 2) Select Authentication Type: "None"
Step 3) Select Interactive render Mode: "Server"
Step 4) Select Interactive location: "Global"
Step 5) Select Include sample pages.
Step 6) both do not use top level, and aspire are deselected.
Step 7) run the project (mine launches in edge)
Step 8) copy and paste, and browse to the web address into firefox

### Exceptions (if any)

Server Side Console Errors:
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: TypeError: n.parentNode is null
      System.InvalidOperationException: TypeError: n.parentNode is null
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.InvokeRenderCompletedCallsAfterUpdateDisplayTask(Task updateDisplayTask, Int32[] updatedComponents)
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'vHqMuARXfPAdaKduXuOthkYjsDpk7XVbyz0r04Q_5jY'.
      System.AggregateException: One or more errors occurred. (TypeError: n.parentNode is null)
       ---> System.InvalidOperationException: TypeError: n.parentNode is null
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.InvokeRenderCompletedCallsAfterUpdateDisplayTask(Task updateDisplayTask, Int32[] updatedComponents)
         --- End of inner exception stack trace ---
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: Error: No element is currently associated with component 1
      System.InvalidOperationException: Error: No element is currently associated with component 1
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.InvokeRenderCompletedCallsAfterUpdateDisplayTask(Task updateDisplayTask, Int32[] updatedComponents)
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'vHqMuARXfPAdaKduXuOthkYjsDpk7XVbyz0r04Q_5jY'.
      System.AggregateException: One or more errors occurred. (Error: No element is currently associated with component 1)
       ---> System.InvalidOperationException: Error: No element is currently associated with component 1
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.InvokeRenderCompletedCallsAfterUpdateDisplayTask(Task updateDisplayTask, Int32[] updatedComponents)
         --- End of inner exception stack trace ---

FireFox side error:
[2024-11-07T01:11:55.313Z] Error: There was an unhandled exception on the current circuit, so this circuit will be terminated. For more details turn on detailed exceptions by setting 'DetailedErrors: true' in 'appSettings.Development.json' or set 'CircuitOptions.DetailedErrors'. blazor.web.js:1:40375
    log http://localhost:5291/_framework/blazor.web.js:1
    unhandledError http://localhost:5291/_framework/blazor.web.js:1
    startConnection http://localhost:5291/_framework/blazor.web.js:1
    _invokeClientMethod http://localhost:5291/_framework/blazor.web.js:1
    _processIncomingData http://localhost:5291/_framework/blazor.web.js:1
    onreceive http://localhost:5291/_framework/blazor.web.js:1
    onmessage http://localhost:5291/_framework/blazor.web.js:1
    (Async: EventHandlerNonNull)
    connect http://localhost:5291/_framework/blazor.web.js:1
    connect http://localhost:5291/_framework/blazor.web.js:1
    _startTransport http://localhost:5291/_framework/blazor.web.js:1
    _createTransport http://localhost:5291/_framework/blazor.web.js:1
    _startInternal http://localhost:5291/_framework/blazor.web.js:1
    start http://localhost:5291/_framework/blazor.web.js:1
    _startInternal http://localhost:5291/_framework/blazor.web.js:1
    _startWithStateTransitions http://localhost:5291/_framework/blazor.web.js:1
    start http://localhost:5291/_framework/blazor.web.js:1
    startConnection http://localhost:5291/_framework/blazor.web.js:1
    startCore http://localhost:5291/_framework/blazor.web.js:1
    start http://localhost:5291/_framework/blazor.web.js:1
    or http://localhost:5291/_framework/blazor.web.js:1
    nr http://localhost:5291/_framework/blazor.web.js:1
    startCircutIfNotStarted http://localhost:5291/_framework/blazor.web.js:1
    resolveRendererIdForDescriptor http://localhost:5291/_framework/blazor.web.js:1
    determinePendingOperation http://localhost:5291/_framework/blazor.web.js:1
    refreshRootComponents http://localhost:5291/_framework/blazor.web.js:1
    rootComponentsMayRequireRefresh http://localhost:5291/_framework/blazor.web.js:1
    (Async: setTimeout handler)
    rootComponentsMayRequireRefresh http://localhost:5291/_framework/blazor.web.js:1
    onDocumentUpdated http://localhost:5291/_framework/blazor.web.js:1
    Ki http://localhost:5291/_framework/blazor.web.js:1
    (Async: EventListener.handleEvent)
    Ji http://localhost:5291/_framework/blazor.web.js:1
    <anonymous> http://localhost:5291/_framework/blazor.web.js:1
    <anonymous> http://localhost:5291/_framework/blazor.web.js:1

### .NET Version

8.0.403

**Comment by javiercn** [comment]
@jpacc260 thanks for contacting us.

Does it not reproduce with other browsers?

**Comment by jpacc260** [comment]
Microsoft Edge, Google Chrome, and Safari all work okay. I would imagine if it was broken for Edge and Chrome it would have been picked up immediately, but I guess Firefox is used less often. As mentioned, Firefox does not have the issue with perpage server interactive.

Thanks.

On 7 Nov 2024, at 4:21 pm, dotnet-policy-service[bot] ***@***.***> wrote:

﻿

Hi @jpacc260<https://github.com/jpacc260>. We have added the "Needs: Author Feedback" label to this issue, which indicates that we have an open question for you before we can take further action. This issue will be closed automatically in 7 days if we do not hear back from you by then - please feel free to re-open it if you come back to this issue after that time.

**Comment by jpacc260** [comment]
hi @javiercn 

same issue through the command prompt without VS.

Please confirm you are using Server interactive, with global with the template generator.
Steps to reproduce:
1) in a fresh folder, from the command line run (making sure -int Server and -ai are both specified):
dotnet new blazor -int Server -ai
2)
dotnet run
3) 
browse to web address in firefox.

Version of firefox is 132.0.1.
Every version of firefox I have tried has the same issue.
Issue exists when running locally, and also when published to Azure.

**Comment by javiercn** [comment]
@jpacc260 thanks for the additional details.

Yes, I did setup global interactivity and Server interactivity, and I used latest Firefox.

Do you have anything in your environment that might be proxying/intercepting traffic?

If you can publish your project to a public github repository that will give us the best chance to identify any potential delta. As things are now, we aren't able to reproduce this issue.

**Comment by jpacc260** [comment]
@javiercn thanks.

My deepest apologies, it appears the issue is only for Firefox running on my domain joined PC.
It works fine with Firefox on my home PC.
Very weird how it only effects global interactivity mode though, and not per-page; and only for firefox.

I doubt it is a group policy, because we only have them for Edge.
I doubt it is firewall related, as it happens even when running the server on my development PC.
Maybe it is AV related.

Let me know if you are happy to close this issue, or if you would like any further information.

Thanks

**Comment by javiercn** [comment]
@jpacc260 don't worry, and thanks for following up.

We are used to things like AV, firewalls, etc. interfering in random ways with the server on rare occasions, hence why we ask that many questions to try and identify the delta.

I think given the scope of this issue we can close it for now unless we get more reports in the future.

**Comment by aespitia** [comment]
I'm actually seeing this error in my logs now since updating a blazor app from .net 6 to 8.  Same, only on firefox and only certain computers.

**Comment by rbesora** [comment]
> I'm actually seeing this error in my logs now since updating a blazor app from .net 6 to 8. Same, only on firefox and only certain computers.

This happened to me – the culprit turned out to be a password manager extension. Try testing the app with all browser extensions disabled. Hope this helps! Good luck!

**Comment by jpacc260** [comment]
> > I'm actually seeing this error in my logs now since updating a blazor app from .net 6 to 8. Same, only on firefox and only certain computers.
> 
> This happened to me – the culprit turned out to be a password manager extension. Try testing the app with all browser extensions disabled. Hope this helps! Good luck!

Can confirm that the Roboform extension in firefox breaks it. Disabled Roboform in firefox and issue goes away. Roboform extension does not cause the issue in Google Chrome or Microsoft Edge. Is this something that should be raised with Roboform or Microsoft? @rbesora are you referring to Roboform too or some other password manager?

**Comment by rbesora** [comment]
> > > I'm actually seeing this error in my logs now since updating a blazor app from .net 6 to 8. Same, only on firefox and only certain computers.
> > 
> > 
> > This happened to me – the culprit turned out to be a password manager extension. Try testing the app with all browser extensions disabled. Hope this helps! Good luck!
> 
> Can confirm that the Roboform extension in firefox breaks it. Disabled Roboform in firefox and issue goes away. Roboform extension does not cause the issue in Google Chrome or Microsoft Edge. Is this something that should be raised with Roboform or Microsoft? [@rbesora](https://github.com/rbesora) are you referring to Roboform too or some other password manager?

Yes, the specific extension is RoboForm.

**Comment by selaromdotnet** [comment]
i just confirmed this as well on a blazor server site i built (currently .net 9): https://mcallengaragesales.com -- in ff with extension enabled it breaks with the error (TypeError: n.parentNode is null)

I've submitted a support ticket to roboform linking to this thread, but i'm wondering if there is anything I can do on my side to prevent this error from happening? anybody been able to resolve this?

**Comment by jpacc260** [comment]
@selaromdotnet - thanks for making a post to roboform. weird that it breaks it in firefox, but not chrome or edge. It is some sort of issue with firefox+roboform and blazor.web.js

**Comment by garcianova18** [comment]
Empece el dia de ayer a crear un proyecto con la plantilla **blazor web app .net 9** y les comento que tengo este mismo error utilizando el navegador Chrome, utilizo el Reder mode InteractiveAuto  en modo Global,
sucede al utlizar Navigation.ToNavigate("/") ojo solo cuando navego a la raiz si es a otra ruta no sucede. y  cuando se esta ejecutando en el server una vez pasa a WASM ya no sucede
utilizando la soucion que sugiere @selaromdotnet  de cambiar este   /_framework/blazor.web.js por este /_framework/blazor.server.js me soluciono el problema pero no es una solucion verdadera ya que con esto estamos eliminando el el render interactiveAuto  y se convierte en no interactivo

**Comment by dclonch1** [comment]
> > I'm actually seeing this error in my logs now since updating a blazor app from .net 6 to 8. Same, only on firefox and only certain computers.
> 
> This happened to me – the culprit turned out to be a password manager extension. Try testing the app with all browser extensions disabled. Hope this helps! Good luck!

Can confirm on my end - my password managers were causing this
