### ISSUE TITLE
Target net10.0 in RepoTasks

### ISSUE THREAD

**Issue by mthalman** [dotnet/aspnetcore#58823]
The changes made to RepoTasks in https://github.com/dotnet/aspnetcore/pull/58090/files#diff-976f8f3081f5ec8e8aacf560c64825479b33b0953bdc4dec82255c7cbe8d01d9 will need to be reverted. Specifically, `net9.0` should be changed back to `$(DefaultNetCoreTargetFramework)`. This can be done once a dependency on a .NET SDK is taken that has these changes: https://github.com/dotnet/sdk/pull/43015.

Related to https://github.com/dotnet/sdk/pull/44685

**Comment by ViktorHofer** [comment]
@wtgodbe can you please help with this? This involves updating the SDK in this repo to a recent build and reverting the change in RepoTasks.csproj as described above.

**Comment by wtgodbe** [comment]
Sure, we were finally able to upgrade to the `net10.0` SDK yesterday - https://github.com/dotnet/aspnetcore/pull/59058
