### ISSUE TITLE
Not found routes causes Blazor WASM to reload.

### ISSUE THREAD

**Issue by julianadormon** [dotnet/aspnetcore#58834]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

This is in regard to [NotFound route causes reload #23100
](https://github.com/dotnet/aspnetcore/issues/23100)

Not found routes causes Blazor WASM to reload.

### Describe the solution you'd like

As per the conversation on the previous issue, it was closed because "this is by design" with the reason that this would give the server a chance to handle the not found response.

This is fine, however I am using a Blazor wasm standalone project and this is happening. This is jarring and not a great user experience.
I feel like the user is getting penalized with the wasm loading screen again.

Thanks for your consideration.

**Comment by javiercn** [comment]
@julianadormon thanks for contacting us.

You can define a page with a `catch-all` route

NotFound.razor
```
@page "{**slug}
...
```

and implement your own logic within it to handle any fallback path not handled by your standalone wasm app.
