### ISSUE TITLE
Why does the page automatically redirect to "/Account/Login" when the user is not authorized?

### ISSUE THREAD

**Issue by WillowTree1184** [dotnet/aspnetcore#58848]
I have created a Blazor Web App project in auto render mode and added a nuget package  Microsoft.AspNetCore.Authorization in version 8.0.10. 

But when I added  `[Authorize]` attribute to my page, I don't know why that it will automatically redirect to "/Account/Login" when the user is not authorized, even though there is no handler for this route. I would like the page to redirect to "/auth/signin" instead, what should I do?

My dotnet version is 8. I develop it in  Visual Studio 2022.

Thank you for your time and assistance.

PS: I will upload my code later.

**Comment by javiercn** [comment]
@WillowTree1184 thanks for contacting us

Are you using cookies? If that is the case it's because the default challenge for cookies is to redirect to that URL. You can change the path in the cookie options.
