### ISSUE TITLE
Blazor Explicit Rendering

### ISSUE THREAD

**Issue by airwedge1** [dotnet/aspnetcore#58871]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

There are many use cases where:

1. Make change to a state.
2. Render the page.
3. Take an additional action.

A very simple example below: When you try to call _myRef it is null as it has not rendered yet.  There are a bunch of ways usually hacky to get around the issue.  Other similar issues have been raised by other individuals for example https://github.com/dotnet/aspnetcore/issues/49048

```
@if(_shouldShow)
{
<MyComponent @ref="_myRef"/>
}

@code {

void SomeEvent()
{
_shouldShow=true;
StateHasChanged();
_myRef.DoSomething();
}

}
```

### Describe the solution you'd like

What we have started to do is created our own function "RenderAsync" that creates a task then manually resolve it in the OnAfterRender event. This has worked out quite well and reduces other much hackier code.  We've also made this into a base class to promote re-use / organization.

```
        private List<TaskCompletionSource> _renderTasks = new();

        
        public virtual async Task RenderAsync()
        {
            var taskCompletion = new TaskCompletionSource();
            var task = taskCompletion.Task;

            _renderTasks.Add(taskCompletion);
            StateHasChanged();

            await task;
        }

        protected override void OnAfterRender(bool firstRender)
        {
            _renderTasks.ForEach((t) =>
            {
                t.SetResult();

            });

            _renderTasks.Clear();
        }

```

So then our function referenced above changes to look like the below and now _myRef is no longer null.  

```
async Task SomeEvent()
{
_shouldShow=true;
await RenderAsync();
_myRef.DoSomething();
}

```

I think our solution is still a bit hacky however and there is most likely some use cases where this strategy is going to cause a bug.  I think it would be beneficial to have a built in function that accomplishes the same thing as RenderAsync() that is properly unit tested / signed off on by the core Blazor team.

**Comment by javiercn** [comment]
@airwedge1 thanks for contacting us.

I don't think the solution that you folks have is correct. The only time a `@ref` instance is guaranteed to be valid is inside `OnAfterRenderAsync`.

That's the reason you see it show up as `null` until `OnAfterRender` and why you might end up with a stale `@ref` instance.

**Comment by airwedge1** [comment]
@javiercn the first code sample is meant to be incorrect. It is an example to illustrate the use case.   

The code sample that contains the RenderAsync function does execute correctly.  The references are assigned after rendering, OnAfterRenderAsync is called, the task is resolved and then we are returned to the SomeEvent() function.  At this point _myRef is assigned and the code executes correctly.

**Comment by airwedge1** [comment]
This has not been resolved.  Pinging to keep open
