### ISSUE TITLE
[Blazor] Blazor Server - ObjectDisposedException with Scoped Services in Blazor Server During Disconnections

### ISSUE THREAD

**Issue by DrMueller** [dotnet/aspnetcore#58887]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Description: We're using Blazor Server with Lamar as our DI container, registering certain services as scoped to maintain one instance per Blazor circuit. Generally, this works well.

However, when users lose connection or close the browser—thus closing the Blazor circuit and disposing of scoped services—ongoing actions may throw a System.ObjectDisposedException (e.g., in dynamically resolved Mediator preprocessors) due to timing issues. This issue is challenging to troubleshoot and isn't easily resolved by adjusting service registrations. Similar problems occur with objects like DotNetObjectReference.

While scoped services seem appropriate (singletons aren't viable due to per-circuit state, and transients are wasteful), there's little documentation on best practices for this scenario. For example, the [CircuitRegistry class](https://github.com/dotnet/aspnetcore/blob/97c6f0df0d7b643dd5bac6f8a8641bd16738d2c5/src/Components/Server/src/Circuits/CircuitRegistry.cs#L37) notes that detecting disconnections isn't exact, and the [JSDisconnectedException documentation](https://learn.microsoft.com/aspnet/core/blazor/javascript-interoperability/?view=aspnetcore-8.0#detecting-when-a-client-disconnects) suggests catching and logging the exception without further action.

Questions:
- Are there best practices for handling ObjectDisposedException caused by circuit disconnections during in-progress actions?
- Should we reconsider our use of scoped services in this context?
- Is this behavior expected, and do most applications simply ignore these errors?

Request: We'd appreciate guidance or improved documentation on handling service disposal during circuit disconnections in Blazor Server applications.

P.S.: I've asked a similar question on StackOverflow, https://stackoverflow.com/questions/79170784/blazor-server-gracefully-handling-circuit-disconnects?noredirect=1#comment139621653_79170784, but the only helpful comment is to ask here.

### Describe the solution you'd like

- Link to best best practices for this scenario
- Overview of best practices of this scenario
- Information regarding changes / extensions of the behavior described above

**Comment by javiercn** [comment]
@DrMueller I wouldn't say that scoped services should be avoided at all.

It's more a case-by-case basis, if you don't care about the potential error, you can catch it and ignore it. If you need more granular control, the cancellation token is the correct approach.

The circuit doesn't get immediately terminated after it has been disconnected, it takes around 2-3 for the circuit to be disposed. The window for something to happen (beyond work that gets triggered on the background) is the time it takes for us to determine that the connection has been lost. 

You can use a `CircuitHandler` to get information about the circuit state and avoid triggering work or cancel ongoing work.

**Comment by DrMueller** [comment]
> [@DrMueller](https://github.com/DrMueller) I wouldn't say that scoped services should be avoided at all.
> 
> It's more a case-by-case basis, if you don't care about the potential error, you can catch it and ignore it. If you need more granular control, the cancellation token is the correct approach.
> 
> The circuit doesn't get immediately terminated after it has been disconnected, it takes around 2-3 for the circuit to be disposed. The window for something to happen (beyond work that gets triggered on the background) is the time it takes for us to determine that the connection has been lost.
> 
> You can use a `CircuitHandler` to get information about the circuit state and avoid triggering work or cancel ongoing work.

Thank you very much for the feedback, that helped me a lot.

**Comment by DrMueller** [comment]
@javiercn

**Comment by javiercn** [comment]
@DrMueller that is correct.

If you have any async operation going on and want to avoid exceptions, you need to find a way to get notified of the changes in either the connection state or the circuit altogether and stop those operations if necessary.

Cancellation token is usually the way.

**Comment by DrMueller** [comment]
@javiercn Thank you for the explanation, I got a good grasp of the problem now. I went with the easy root and catch the exceptions and just log them as warnings.
