### ISSUE TITLE
Something strange with UserManager's users tracking

### ISSUE THREAD

**Issue by Lavshyak** [dotnet/aspnetcore#58892]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

```
servicesScope0:
var user = new User
userManager0.CreateAsync(user

IdentityUser userToRemember;
servicesScope1:
userToRemember = userManager1.FindByIdAsync(1)

//the presence of this block does not affect the occurrence of an exception, I added it for example
serviceScope2:
tmpUser = userManager2.FindByIdAsync(1)
userManager2.UpdateSecurityStampAsync(tmpUser) // ok

serviceScope3:
userManager3.UpdateSecurityStampAsync(userToRemember) //throws InvalidOperationException exception
```

### Expected Behavior

no exception

### Steps To Reproduce

Project with code to reproduce: https://github.com/Lavshyak/AspNetIdentityUserManagerBug

### Exceptions (if any)

InvalidOperationException with message: "The instance of entity type 'Account' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached..."

### .NET Version

8.0.403
9.0.100

### Anything else?

ASP.NET 8.0.10
ASP.NET 9.0.0
Rider 2024.2.7

### dotnet --info when .net 8:
.NET SDK:
 Version:           8.0.403
 Commit:            c64aa40a71
 Workload version:  8.0.400-manifests.e99c892e
 MSBuild version:   17.11.9+a69bbaaf5

Runtime environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.403\

Installed .NET Workloads:
Configured to use loose manifests when installing new manifests.
There are no installed workloads to display.

Host:
  Version:      8.0.10
  Architecture: x64
  Commit:       81cabf2857

.NET SDKs installed:
  8.0.403 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 8.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

### dotnet --info when .net 9:
.NET SDK:
 Version:           9.0.100
 Commit:            59db016f11
 Workload version:  9.0.100-manifests.c6f19616
 MSBuild version:   17.12.7+5b8665660

Runtime environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\9.0.100\

Installed .NET Workloads:
Configured to use loose manifests when installing new manifests.
There are no installed workloads to display.

Host:
  Version:      9.0.0
  Architecture: x64
  Commit:       9d5a6a9aa4

.NET SDKs installed:
  9.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 8.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 9.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

**Comment by Lavshyak** [comment]
when i do this, there is no exception:
serviceScope3:
mainDbContext.Attach(userToRemember)

**Comment by Lavshyak** [comment]
and it's no matter i remeber account in servicesScope0 or servicesScope1. so i think the problem is either in the UserManager from scope0 or from scope3

**Comment by halter73** [comment]
The `userToRemember` is attached to a `DbContext` in a different scope so it is not tracked by the `DbContext` in scope3 unless you do something to track it.

The easiest fix is to acquire an `Account` instance from the `DbContext` in the current scope using something like `FindByIdAsync` or `GetUserAsync`. But if you want the `userToRemember` to be tracked by a `DbContext` in another scope to avoid change tracking, you have to manually attach it like you would an `Account` you `new` up. That's why it works when you manually attach it. Notice that you'll run into the same problem if you have the following code to scope 3:

```csharp
// scope3:
var account = new Account
{
  Id = accountToRemember.Id,
  UserName = accountToRemember.UserName,
  ConcurrencyStamp = accountToRemember.ConcurrencyStamp,
};
//dbContext.Attach(account);
var result = await userManager.UpdateSecurityStampAsync(account); // Throws the same InvalidOperationException
```

So it's not like the `UserManager` from scope0 or scope3 are broken. It's just that you're required to use accounts that are attached to the `DbContext` of the current scope. This can be done either automatically by acquiring it from the `UserManager` in the current scope like normal or manually by calling `DbContext.Attach()` or `DbContext.Update()` .

https://learn.microsoft.com/en-us/ef/core/change-tracking/explicit-tracking
