### ISSUE TITLE
Support an OnApplicationStart[Async] method or similar pattern

### ISSUE THREAD

**Issue by divega** [dotnet/aspnetcore#5890]
Applications often need to run code once at application startup per web server, e.g. to setup or initialize some external resource to be used by the application. There are two main issues with doing so in `Startup.Configure()`:
1. Lifetime of services can be incorrect at this stage, e.g. services that are registered as scoped will not be disposed correctly and will remain in memory
2. It cannot execute asynchronously  

One general idea that has been discussed is to have a middleware that will run this code on first request but use a lock to make sure it is only done once.

The main example where this have come up is https://github.com/aspnet/EntityFramework/issues/3070 "Pattern for seeding database with EF7 and ASP.NET 5". Note that we cannot recommend a pattern like this in general because it is not safe unless you know there is only one web server, but for many customers this can be enough. Note also that MusicStore [currently uses a workaround](https://github.com/aspnet/MusicStore/blob/dev/src/MusicStore/Models/SampleData.cs#L23).

Another possibly related scenario is described at https://github.com/aspnet/EntityFramework/issues/3070#issuecomment-140017643. Although it is not about code that needs to run at application start, it is about how to get services to be activated with the right lifetime on code that doesn't execute as part of a request:

> Another problematic case is when you use a Timer. During the callback there have no scope. So the used instances are always the same, because you have to use the ServiceProvider of the application, so always the same context. What would be the best way to use DI with a Timer? The Timer sould perhaps create a scope during the callback and pass it in parameter? Use IServiceScopeFactory in the callback? 

cc @Eilon

**Comment by manigandham** [comment]
This seems unnecessary now with Program.Main being async and the current DI system. The WebHost is just a class that you build, instantiate, and then run. You can do anything you want *after* the instantiation but *before* running the host, with access to registered services, scopes, correct disposal and async/await.

```
public static class Program
{
    public static async Task Main(string[] args)
    {
        using (var host = CreateWebHostBuilder().Build())
        {
            // get a service from the DI container and use it
            await host.Services.GetService<SomeService>().Start();
            
            // get and start multiple services at the same time
            await Task.WhenAll(
                host.Services.GetService<SomeService>().Start1(),
                host.Services.GetService<SomeOtherService>().Start2()
            );
            
            // use a scope if you need scoped services
            var sp = host.Services.GetService<IServiceScope>();
            using (var scope = sp.ServiceProvider.CreateScope())
            {
                scope.ServiceProvider.GetService<SomeScopedService>().RunSomething();
            }
            
            // start the actual webhost and run it
            await host.RunAsync();
            
            // webhost also has other methods for more control
            await host.StartAsync();
            await host.WaitForShutdownAsync();
            await host.StopAsync();

            // all services implementing IDisposable will be disposed once the WebHost is disposed
            // and in reverse order from instiantiation so you can control the order of dependencies
        }
    }
}
```

You can wrap this with your own extension methods or a subclass to make it cleaner. We use this on several apps that have similar startup requirements for config, messaging, caching, etc that needs to be available before the app serves request, and also shutdown properly after it.

**Comment by davidfowl** [comment]
Closing in favor of https://github.com/dotnet/aspnetcore/issues/24142
