### ISSUE TITLE
Resolve framework versions correctly in error page footer

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/aspnetcore#5891]
Followup to https://github.com/aspnet/Hosting/pull/726.

Currently we generate footers like
![image](https://cloud.githubusercontent.com/assets/2030323/14864610/7f568244-0c6f-11e6-964b-b2946efb03eb.png)
which uses assembly version as the .NET Framework version. This is not very useful and the version should look like 4.5.1, 4.6, ...

cc @DamianEdwards

**Comment by muratg** [comment]
Looks like a nice-to-have in 3.0.0 and help customers with diagnostics. Hopefully we can get time in 3.0.0.

**Comment by davidfowl** [comment]
This is done
