### ISSUE TITLE
OpenApi won't Contains those Controllers If the Controller not starts with [ApiController] Attribute

### ISSUE THREAD

**Issue by yangbocheng** [dotnet/aspnetcore#58938]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Simply create a newest NET 9  aspnetcore webapi, then add `Microsoft.AspNetCore.OpenApi` and  `Scalar.AspNetCore`. Then add a new Controller without [ApiController], this contoller's actions won't be included in openapi json

### Expected Behavior
Controllers without  [ApiController] should be included in openapi json

### .NET Version
NET 9

**Comment by yangbocheng** [comment]
The reason to not use the  [ApiController] is : Need manual validate some form fields, or api parameters in Project
OpenApi won't Contains those Controllers If the Controller not starts with [ApiController] Attribute
```xml
<ItemGroup>
  <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.0" />
  <PackageReference Include="Scalar.AspNetCore" Version="1.2.36" />
</ItemGroup>
```
so if remove the  [ApiController] from Test1Controller.cs  , then this won't show in openapi/v1.json
![Image](https://github.com/user-attachments/assets/bb8fd77e-d0c5-45c3-ad3f-316b827c51a5)
![Image](https://github.com/user-attachments/assets/f8c35f16-8118-4688-963d-9005b88f91ef)
![Image](https://github.com/user-attachments/assets/b5af17c9-a2c5-4f5d-8d0e-a4c3458b13d6)

**Comment by jaceks2106** [comment]
Try to use `Controller` instead of `ControllerBase` as a base class.

**Comment by yangbocheng** [comment]
I have tested again with the base : `Controller` and `ControllerBase`. They both don't work.
It seems that the only way to make openapi works well is to add `[ApiController]` 
![Image](https://github.com/user-attachments/assets/514c6ff8-fbf9-498a-8f68-1f60b494aaff)
![Image](https://github.com/user-attachments/assets/ce0670e3-b901-4911-80bb-1fb9e5186b03)

**Comment by captainsafia** [comment]
@yangbocheng Thanks for filing this issue!

This is a known limitation of the ApiExplorer infrastructure, the intermediary layer in ASP.NET Core that provides information about registered implementors to OpenAPI tools.

In this particular case, only controllers that are attributed with `[ApiController]` are automatically documented by ASP.NET Core's infrastructure.

Building on top of @jaceks2106's guidance, why are you avoiding the attribution? There maybe other ways to customize the model binding/validation behavior to your desires.

**Comment by yangbocheng** [comment]
Because [ApiController] will auto do things  which i don't need.
So always i avoid to use it in project.

Follow Microsoft->means use the newest openapi-> means add [ApiController] to every controller-> so why not add this attribute to controller default? -> make bugs for multi programs who don't use apicontroller 
Why it must add this limitation, it's very strange.

By the way, when I use the old Swagger, i don't need to add this attribute, everything work well.

**Comment by artenni4** [comment]
> [@yangbocheng](https://github.com/yangbocheng) Thanks for filing this issue!
> 
> This is a known limitation of the ApiExplorer infrastructure, the intermediary layer in ASP.NET Core that provides information about registered implementors to OpenAPI tools.
> 
> In this particular case, only controllers that are attributed with `[ApiController]` are automatically documented by ASP.NET Core's infrastructure.
> 
> Building on top of [@jaceks2106](https://github.com/jaceks2106)'s guidance, why are you avoiding the attribution? There maybe other ways to customize the model binding/validation behavior to your desires.

This issue is still relevant. NSwag/Swashbuckle generators do not require the attribute, generated document will contain all mapped controllers. It can be a real issue to migrate a big project to new generator.

**Comment by msilvers-imis** [comment]
@captainsafia OpenAPI does not contain endpoints defined in controllers if the [ApiController] attribute is applied at the assembly level using `[assembly: ApiController]` instead of on each individual controller.

**Comment by sherlock1982** [comment]
A way to workaround it for me was to add `[ApiExplorerSettings]` to the controller
