### ISSUE TITLE
Blazor Web App Template Global Interactivity location causes Not Found issue when navigate to the page/component in Server project.

### ISSUE THREAD

**Issue by DillionVVV** [dotnet/aspnetcore#58944]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Firstly, I understand the basics of Blazor render mode. When we use "Blazor Web App" template create application, it will generate two projects: main project (server) and .Client project (client), then we need to put the server-side rendering component in the server project and put the client-side rendering component in the .client project.

Recently, I found that when use "Blazor Web App" template create application, in the Additional Information window,

![Image](https://github.com/user-attachments/assets/26d65de2-4846-487f-b196-8249a77c2b27)

 If we select the select the "Auto (Server and WebAssembly)" Interactive render mode and **"Global" Interactivity location**, then in the Blazor Server project add a Test component (set the rendermode as InteractiveServer), after running the application and navigate to the Test page, firstly it will show the Test page content, after some seconds (2 or 3 seconds), it will auto display "Not Found" in the page.

I have also report this issue in this thread: https://github.com/dotnet/aspnetcore/issues/58480

But this issue still not fixed in .NET 9. 

### Expected Behavior

After redirecting to test page, it should stay on the test page instead of showing "Not Found".

### Steps To Reproduce

1. Create a new Blazor application using the **Blazor Web App** Template.
    In the Additional Information window, select the **"Auto (Server and WebAssembly)"** Interactive render mode and **"Global"** Interactivity location:
    ![Image](https://github.com/user-attachments/assets/bf36a769-30f1-4834-b17d-492b44b366c9)

2. In the Server project, add a Testpage component in the Components/Pages folder, like this:

    ![Image](https://github.com/user-attachments/assets/942b96d4-2b91-4128-b665-7771f4f8c5fa)

3. Running the application, navigate to the Test page, firstly the output as below:

    ![Image](https://github.com/user-attachments/assets/f818461e-de98-4fd4-878b-68f0c7ddaf04)

    then, a few seconds later, it will auto display "Not Found", like this:

    ![Image](https://github.com/user-attachments/assets/12f8d1d1-90ac-459c-9b0b-e1ae1ab6ec4c)

### .NET Version

.NET 8 and .NET 9

### Anything else?

I check it using the following version of VS 2022, both of them show the same issue:

Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.11.5

Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.12.0

Microsoft Visual Studio Community 2022 (64-bit) - Preview Version 17.12.0 Preview 3.0

Microsoft Visual Studio Community 2022 (64-bit) - Preview Version 17.13.0 Preview 1.0

Besides, I also compare it with my old Blazor Web Application, it seems that this issue relate the `Routes.razor` component and the Layout content, in previous projects, these files are in the Server project, but now they are in the Client project.

![Image](https://github.com/user-attachments/assets/a14ffd55-21e5-442e-89c8-8551e40a5b38)

And when use "Blazor Web App" template create application, in the Additional Information window, if we select the "Per page/Component" Interactivity location, these files are also in the server project. 

So this might be a bug about the "Blazor Web App" template and Interactivity location. Please help to check and fix it.

**Comment by javiercn** [comment]
@DillionVVV thanks for contacting us.

This behavior is by design. On global interactivity, all the pages should be on the `client` project. Otherwise, they won't be in any assembly downloaded to the browser, not registered on the client router and that will result in the not found that you are seeing.

**Comment by guardrex** [comment]
BTW @danroth27 ... This is what I was covering that you requested I pull it on https://github.com/dotnet/AspNetCore.Docs/issues/34041. If this is a supported scenario, then I recommend we bring that coverage back, as it's hard to guess.
