### ISSUE TITLE
Support access logging with Common Log Format/Extended Log Format

### ISSUE THREAD

**Issue by muratg** [dotnet/aspnetcore#5894]
_From @cesarbs on February 3, 2017 18:6_

Every web server does this:

http://httpd.apache.org/docs/current/logs.html#accesslog

http://redmine.lighttpd.net/projects/1/wiki/Docs_ModAccessLog

http://nginx.org/en/docs/http/ngx_http_log_module.html#access_log

https://www.iis.net/configreference/system.applicationhost/log/centralw3clogfile

There are tools that analyze logs using those formats.

For reference:

https://en.wikipedia.org/wiki/Common_Log_Format

https://www.w3.org/TR/WD-logfile.html

_Copied from original issue: aspnet/KestrelHttpServer#1339_

**Comment by keith-leung** [comment]
> @JeepNL glad that worked for you. Please file issues in that repo for implementation questions so we can avoid distracting this thread.

I stared your GitHub repo, it's good.

**Comment by brianmed** [comment]
If you use Serilog, then you can try this Middleware: 

- https://github.com/brianmed/SerilogW3cMiddleware

**Comment by JeepNL** [comment]
Any new developments on this? Kestrel support for W3C extended log format out of the box? For .NET 5 maybe? 

See also Microsoft Docs: [W3C Logging](https://docs.microsoft.com/en-us/windows/win32/http/w3c-logging)

**Comment by davidfowl** [comment]
This should be implemented in Kestrel directly as a structured log in a specific category.

**Comment by JeepNL** [comment]
@davidfowl Yes, please :) 

(Just FYI): I've mentioned the log analyzer [AWStats](https://www.awstats.org/) already in this thread, [GoAccess](https://goaccess.io/) is another fast and light weight log analyzer which is used by many NGINX/Apache systems. I think this (generating W3C logfiles) is an important feature which Kestrel, like any other stand alone production webserver, should support.

**Comment by CumpsD** [comment]
We removed nginx in front of our system recently and expose Kestrel directly, but didn't except something standard as access logs to be missing. Looking forward to seeing this added too

**Comment by JeepNL** [comment]
FYI @CumpsD The ASP.NET team started with this in ASP.NET Core 6 Preview 4

- Announcement: https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-6-preview-4/#http-logging-middleware
- Docs: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-logging/
- Sample Code: https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/fundamentals/http-logging/samples/6.x

And about W3C logging, Justin Kotalik [tweeted](https://twitter.com/JustinKotalik/status/1388164367426875395) they're working on that for ASP.NET Core 6 Preview 5, see: https://github.com/dotnet/aspnetcore/issues/31843

![Screenshot 2021-06-14 145418](https://user-images.githubusercontent.com/39458532/121895579-aec92f00-cd20-11eb-90e7-4aa5b07c89a3.jpg)

**Comment by davidfowl** [comment]
See https://github.com/dotnet/aspnetcore/pull/33251

**Comment by wtgodbe** [comment]
This is done as of https://github.com/dotnet/aspnetcore/pull/33251/, will be included as part of dotnet 6.0-preview7
