### ISSUE TITLE
OnAfterRenderAsync  Not firing  in MainLayout

### ISSUE THREAD

**Issue by MikkieDo** [dotnet/aspnetcore#58958]
### Description

.net  9  Not sure  why but  OnAfterRenderAsync  does not fire  in MainLayout   it did in in .net  8 
could this just be an oversight  ? 
here's my code 
protected override async Task OnAfterRenderAsync( bool firstRender )
{
    if(firstRender)
    {
        UserId = await Ss.GetInt("UserId") != 0 ? await Ss.GetInt("UserId") : 0;
        UserTypeId = await Ss.GetInt("UserTypeId") != 0 ? await Ss.GetInt("UserTypeId") : 20;
        UserTypeName = (UserTypeId == 0 || UserTypeId == 20) ? "Home" : await Ss.GetString("UserTypeName");
    }
}
help ?

### Reproduction Steps

protected override async Task OnAfterRenderAsync( bool firstRender )
{
    if(firstRender)
    {
       // does not fire
    }
}

### Expected behavior

expect it to fire  

### Actual behavior

none !!

### Regression?

works fine in .net 8 

### Known Workarounds

none  that i know of 

### Configuration

I am using Blazor Server  web app .net 9  C#   Visual Studio Version 17.12.0  .NET SDK 9.0.100

**Comment by javiercn** [comment]
@MikkieDo thanks for contacting us.

are you using per page interactivity? It's likely that you are rendering the layout statically.
