### ISSUE TITLE
Add IAsyncStartup and IAsyncStartupFilter to support async startup classes and filters

### ISSUE THREAD

**Issue by anurse** [dotnet/aspnetcore#5897]
We should introduce a new set of interfaces: `IAsyncStartup` and `IAsyncStartupFilter` with the following API surface:

```csharp
    public interface IAsyncStartup
    {
        IServiceProvider ConfigureServices(IServiceCollection services);

        Task ConfigureAsync(IApplicationBuilder app);
    }

    public interface IAsyncStartupFilter
    {
        Func<IApplicationBuilder, Task> Configure(Func<IApplicationBuilder, Task> next);
    }
```

Startup classes will now support a `Task ConfigureAsync(IApplicationBuilder app)` method, which is **mutually exclusive** with `void Configure(IApplicationBuilder app)`. It shall be an error to have both methods on a startup class.

`IAsyncStartup` and `IAsyncStartupFilter` will be the primitives used by the entire Hosting pipeline. Adapters will exist in Hosting to allow the continued use of `IStartup` and `IStartupFilter` in the public API surface (to reduce breaking changes).

**Comment by NinoFloris** [comment]
Will this actually be revisited for 3.0?

**Comment by anurse** [comment]
Unfortunately no, we had other higher priority work that means this is not scheduled for 3.0.

**Comment by davidfowl** [comment]
I spent a could of minutes looking at this and I don't think it;s possible to implement without blocking. We've basically deprecated IStartup in 3.0 so adding `IAsyncStartup` *could* work (or just supporting it without the interface) but the problem is that you cannot run sync filters around an async startup without blocking (sync over async). It would have to be this way until everyone moves over to async filters.

**Comment by gulbanana** [comment]
this is going to be a problem for blazor if it continues to use the same Startup mechanism. all i/o has to be async in blazor, and you can't just start a task to do it either - so right now there's no way to, say, initialise a service which depends on runtime-loaded data.

**Comment by MV10** [comment]
Is there a reason `ConfigureServicesAsync` would be problematic?

Similar to what @gulbanana notes, there are a lot of scenarios where that would be handy. For example, I inherited several systems that use `.GetAwaiter().GetResult()` to read config values from Azure Key Vault, Blob Storage, and a custom distributed cache mechanism. I've seen similar async database calls in other projects that retrieve auth config and so on. I suspect the guidance is probably "don't do that" but the fact is, people _do_ in the real world. I wouldn't argue for doing-it-wrong on that basis alone, but my question is whether there is anything about `ConfigureServices` that means it _must_ remain synchronous.

More generally, I understand why this change hasn't been made yet, but on the other hand, as people start getting the "async whenever possible" message, I'm seeing more and more `.GetAwaiter().GetResult()` out there. (At work where I do a lot of code reviews and give arch advice, I'm explaining how this is risky at an alarmingly increasing rate, usually after finding it in code and checking whether the dev understands what "sync-over-async" really means). 

I'm of the option that re-factoring `Program.cs` and `Startup.cs` for async isn't _that_ much of a chore for the average ASP.NET app. Tear off the band-aid! 5.0 is a major release, breaking changes are the name of the game.

**Comment by damianh** [comment]
Any progress on this? For 5.0 maybe?

I have several use cases for loading config async (i.e. AWS Secrets Manager / Azure Key Vault) and `GetAwaiter().GetResult()` is... yuck.

**Comment by davidfowl** [comment]
There's no progress for 5.0 no, we don't know how to do this without blocking or breaking changes. It might be possible to run filters in 2 stages that never overlap.

**Comment by davidfowl** [comment]
Hmm, that might actually work now that I've typed it out...

**Comment by davidfowl** [comment]
Ah nope, the problem is the underlying call to Configure itself would need to be async OR sync. They can't interleave or overlap because of the calling pattern. One needs to replace the other.

**Comment by iSeiryu** [comment]
Say yes to breaking changes! Async all the way!
We had to deal with more complex changes in our projects when we had to migrate from .Net Framework to Core and from Core 2.0 to Core 3.1.
This one is more trivial and very much desired.
One article on https://docs.microsoft.com would clarify everything and people would circle it around very quickly.

**Comment by davidfowl** [comment]
Closing in favor of https://github.com/dotnet/aspnetcore/issues/24142
