### ISSUE TITLE
Range Attribute to specify a value inside an array max/min lengths

### ISSUE THREAD

**Issue by jgarciadelanoceda** [dotnet/aspnetcore#58993]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

In this issue domaindrivendev/Swashbuckle.AspNetCore#3120 I thought at first of the RangeAttribute to specify the array min/maxLength, but I do not know if it's the right solution for this matter. I have tested with this property:

```c#
[FromQuery, Length(2, 10), Range(-1, 2)]
public int[] Array { get; set; }
``` 

The issue at hand is that if you set the RangeAttribute over an array of integer then the model validation does not allow you to put any value:
```javascript
{
  "type": "https://tools.ietf.org/html/rfc9110#section-15.5.1",
  "title": "One or more validation errors occurred.",
  "status": 400,
  "errors": {
    "Array": [
      "The field Array must be between -1 and 2."
    ]
  },
  "traceId": "00-2553c36e9a1043817d97dfe2746bbb9b-1404e652aadda666-00"
}
``` 

And also the OpenApi spec generated by the package Microsoft.AspNetCore.OpenApi does not put the maximum or minimun over the items and it does it over the schema(It writes):
```javascript
{
	"name": "Array",
	"in": "query",
	"schema": {
		"maximum": 2,
		"minimum": -1,
		"maxItems": 10,
		"minItems": 2,
		"type": "array",
		"items": {
			"type": "integer",
			"format": "int32"
		}
	}
}
``` 

And I think it should write:
```javascript
{
	"name": "Array",
	"in": "query",
	"schema": {
		"maxItems": 10,
		"minItems": 2,
		"type": "array",
		"items": {
			"type": "integer",
			"format": "int32",
			"maximum": 2,
			"minimum": -1,
		}
	}
}
``` 

### Expected Behavior

The validation of the Annotation to do not occur and also that the OpenApi spec would be the suggested one

### .NET Version

9.0.100

**Comment by captainsafia** [comment]
@jgarciadelanoceda Thanks for filing this issue!

It doesn't look like the current model validation in MVC supports using `RangeAttribute` on anything except an integer-type field. In this case, we don't provide anything out of the box for indicating that the values _within_ an array should be within a given range.

The best option in this case might be for the user to implement custom validation to meet this requirement using a [custom attribute])https://learn.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-9.0#custom-attributes).

In that case, they'd have to use an OpenAPI transformer (or a Swashbuckle filter) to set the annotation correctly.
