### ISSUE TITLE
The default mvc web application template navigation menu created by. net 9 does not display

### ISSUE THREAD

**Issue by HuaFangYun** [dotnet/aspnetcore#59000]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

![Image](https://github.com/user-attachments/assets/dd5d5c30-f519-4b89-870d-18af60180c21)

### .NET Version

.net9

**Comment by martincostello** [comment]
Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) as a GitHub repository that demonstrates the issue you're experiencing so the team can look into this further.

Otherwise all we can guess is that maybe you've got the wrong bootstrap classes on your navbar that are making the text invisible.

**Comment by HuaFangYun** [comment]
![Image](https://github.com/user-attachments/assets/f65f167f-9bd1-45c9-a518-1e1d3ce588d4)
Please press the template to directly create a default application and run it. Menu cannot be displayed. When in mobile mode, it can be displayed and hidden directly when you place the mouse.

**Comment by HuaFangYun** [comment]
![Image](https://github.com/user-attachments/assets/3bb24301-714a-433e-90e1-fdefa9a4282a)

**Comment by HuaFangYun** [comment]
https://github.com/HuaFangYun/MVCTest/tree/new

**Comment by HuaFangYun** [comment]
@martincostello

**Comment by HuaFangYun** [comment]
My code appears normally in html. Put it in an mvc project, and the menu will not be displayed. All the code is the same, but it is not displayed. Later I found that the template we provided had the same problem. Please check it. thank

**Comment by nitish-kaushik** [comment]
Hi @HuaFangYun 
I have tested your repo as well as the default template of .net9 mvc application and the menu is working fine in both the applications.
Here is the screenshot from your application.

![Image](https://github.com/user-attachments/assets/08a6e769-434b-4b93-b791-0d51d9b2c1de)

Kindly mark as answer and close the issue if no further answer is required.

**Comment by HuaFangYun** [comment]
Thank you for your reply, but I am having this issue on my computer where the menu cannot be displayed. I would like to ask how to reinstall this template to test again and find out the problem.

**Comment by HuaFangYun** [comment]
I have recorded a video of 50MB, but I cannot upload it as it is limited to only 25MB.

**Comment by HuaFangYun** [comment]
It may be a problem with my computer or something else. I will try to reinstall it. Thank you for your reply
