### ISSUE TITLE
generate openapi json error when custom IBindingSourceMetadata

### ISSUE THREAD

**Issue by cjdxhjj** [dotnet/aspnetcore#59013]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

![Image](https://github.com/user-attachments/assets/a010aaac-f8f7-4fe4-abf9-e3b673f6aa43)
![Image](https://github.com/user-attachments/assets/d3522db7-9fd7-4965-a9cd-cab3563dd808)
![Image](https://github.com/user-attachments/assets/a6faadb1-a82e-4d06-a230-350dcca24592)
![Image](https://github.com/user-attachments/assets/952f58b0-0d3a-487d-9b2c-98cb26fb3a39)

### .NET Version

9.0.100

**Comment by cjdxhjj** [comment]
another question: the description not work on fromform field
![Image](https://github.com/user-attachments/assets/df71c872-209f-4dfc-9c42-7437a04dd288)
![Image](https://github.com/user-attachments/assets/e840840c-636d-4cb4-aa9d-4ac924d5928f)

**Comment by martincostello** [comment]
Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) as a GitHub repository that demonstrates the issue you're experiencing so the team can look into this further.

Code provided as a screenshot needs to be transcribed from them - providing code as code is much more useful.

Similarly, please also provide error messages as **text** not screenshots. Then it's easy for people to copy-paste things like method names from stack traces.

**Comment by captainsafia** [comment]
@cjdxhjj Thanks for reporting this issue! 👍🏽 to @martincostello's point that when possible error messages and repros are better shared in text or repos over screenshots since it makes it easier to investigate the issue.

With that in mind, I've opened https://github.com/dotnet/aspnetcore/pull/59035 with a proposed resolution for this bug.

**Comment by cjdxhjj** [comment]
thanks very much @captainsafia @martincostello

**Comment by cjdxhjj** [comment]
[HttpPost, EndpointSummary("test dataform")]
public ActionResult<string> DataForm([FromForm, Description("name of person")] string name, [FromForm, Description("age of person")] int age)
{
    return Content(name);
}

**Comment by cjdxhjj** [comment]
![Image](https://github.com/user-attachments/assets/b805bf19-f4ab-4441-bc2f-6a070ea235f7)
the description is missing

**Comment by captainsafia** [comment]
> another question: the description not work on fromform field ![Image](https://github.com/user-attachments/assets/df71c872-209f-4dfc-9c42-7437a04dd288) ![Image](https://github.com/user-attachments/assets/e840840c-636d-4cb4-aa9d-4ac924d5928f)

Do you mind filing this bug report into a separate issue?

**Comment by cjdxhjj** [comment]
ok, i will upload a repo
Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.GetParametersAsync(ApiDescription description, IServiceProvider scopedServiceProvider, IOpenApiSchemaTransformer[] schemaTransformers, CancellationToken cancellationToken)
Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.GetOperationAsync(ApiDescription description, HashSet<OpenApiTag> capturedTags, IServiceProvider scopedServiceProvider, IOpenApiSchemaTransformer[] schemaTransformers, CancellationToken cancellationToken)
Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.GetOperationsAsync(IGrouping<string, ApiDescription> descriptions, HashSet<OpenApiTag> capturedTags, IServiceProvider scopedServiceProvider, IOpenApiOperationTransformer[] operationTransformers, IOpenApiSchemaTransformer[] schemaTransformers, CancellationToken cancellationToken)
Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.GetOpenApiPathsAsync(HashSet<OpenApiTag> capturedTags, IServiceProvider scopedServiceProvider, IOpenApiOperationTransformer[] operationTransformers, IOpenApiSchemaTransformer[] schemaTransformers, CancellationToken cancellationToken)
Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.GetOpenApiDocumentAsync(IServiceProvider scopedServiceProvider, CancellationToken cancellationToken)
Microsoft.AspNetCore.Builder.OpenApiEndpointRouteBuilderExtensions+<>c__DisplayClass0_0+<<MapOpenApi>b__0>d.MoveNext()
Microsoft.AspNetCore.Http.Generated.<GeneratedRouteBuilderExtensions_g>F56B68D2B55B5B7B373BA2E4796D897848BC0F04A969B1AF6260183E8B9E0BAF2__GeneratedRouteBuilderExtensionsCore+<>c__DisplayClass2_0+<<MapGet0>g__RequestHandler|5>d.MoveNext()
Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

**Comment by cjdxhjj** [comment]
the repo is https://github.com/cjdxhjj/openapi-demo.git

**Comment by cjdxhjj** [comment]
@captainsafia the desciption missing issure https://github.com/dotnet/aspnetcore/issues/59042
