### ISSUE TITLE
build Asp.net core 8.0.1 some errors

### ISSUE THREAD

**Issue by xfr128** [dotnet/aspnetcore#59025]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

C:\Users\hp\.nuget\packages\microsoft.dotnet.arcade.sdk\8.0.0-beta.23564.4\tools\Build.proj(268,5): error MSB4181: “MSBuild”任务返回了 fal
se，但未记录错误。

生成失败。

D:\Asp.NetCoreSource\aspnetcore\eng\targets\Npm.Common.targets(92,5): error : Command failed with exit code 2. [D:\Asp.NetCoreSource\
aspnetcore\src\SignalR\clients\ts\signalr\signalr.npmproj]
D:\Asp.NetCoreSource\aspnetcore\eng\targets\Npm.Common.targets(92,5): error : Command failed with exit code 2. [D:\Asp.NetCoreSource\
aspnetcore\src\SignalR\clients\ts\signalr\signalr.npmproj]
C:\Users\hp\.nuget\packages\microsoft.dotnet.arcade.sdk\8.0.0-beta.23564.4\tools\Build.proj(268,5): error MSB4181: “MSBuild”任务返回了 fal
se

**Comment by wtgodbe** [comment]
I recommend passing `--no-build-nodejs` (if building with build.sh) or `-NoBuildNodeJS` (if building with build.cmd/build.ps1) to work around this. Feel free to re-open if that doesn't solve your problem.
