### ISSUE TITLE
Best place to store SQLite database file for Blazor app running on Azure App Service?

### ISSUE THREAD

**Issue by Postlagerkarte** [dotnet/aspnetcore#59028]
I have a Blazor application that uses SQLite for data storage, and deploying it to Azure App Service has been challenging. Where should the SQLite database file be stored?

Using the /home directory in App Service might be fine for development, but it doesn’t seem suitable for production. Azure File Service isn’t recommended for hosting SQLite databases due to file locking and performance issues, and Azure NetApp Files feels like overkill for this use case.

Given this, what’s the best approach for storing the SQLite .db file in a production environment? I assume this is a fairly common scenario.

Thank you for any guidance! 😃

**Comment by javiercn** [comment]
Thanks for contacting us @Postlagerkarte 

It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to StackOverflow.

This is not an area where we are experts on, and we can't provide guidance about what to do.
