### ISSUE TITLE
Package microsoft.aspnetcore.components.customelements/9.0.0 is missing tsconfig.json

### ISSUE THREAD

**Issue by Olivercomputing** [dotnet/aspnetcore#59026]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

After updating a project to .Net 9, I get this build error:

TS5083   Build:Cannot read file ' ... /.nuget/packages/microsoft.aspnetcore.components.customelements/9.0.0/contentFiles/Shared.JS/tsconfig.json'

Evidently, a required tsconfig.json file is missing in the package.

### Expected Behavior

I expect the file to be in the package and no error.

### .NET Version

9.0.100

**Comment by javiercn** [comment]
@Olivercomputing thanks for contacting us.

This package shouldn't contain `contentFiles`. This is a bug in the package. I believe you can probably disable the content items from the package adding `ExcludeAssets="content"` to the `PackageReference` item.
