### ISSUE TITLE
Use names in EventIds for logging

### ISSUE THREAD

**Issue by anurse** [dotnet/aspnetcore#5904]
In https://github.com/aspnet/Hosting/blob/e4350945c56d69523fe36bf33c58b955db3d8985/src/Microsoft.AspNetCore.Hosting/Internal/LoggerEventIds.cs we use `int`s for event ID values, but the `EventId` type that is used can actually also support holding a name. Names are easier to query and inspect in structured log storage.

We should change the fields in this type to `EventId`s and give them names.

(Event ID names don't need a prefix because `EventId` is only unique within a Logger, so there's no need to prefix it).

**Comment by davidfowl** [comment]
We do this now
