### ISSUE TITLE
OpenApi - Does not respect JsonStringEnumConverter

### ISSUE THREAD

**Issue by deinok** [dotnet/aspnetcore#59057]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

As the title says, the new OpenApi package does not respect "JsonStringEnumConverter". It outputs enums as "integer".

### Expected Behavior

The OpenApi takes into consideration the JsonStringEnumConverter and does not output the enums as its underlying primitive

### .NET Version

9.0.0

**Comment by martincostello** [comment]
Where are you using the converter? Attributes in properties of types, or global configuration of MVC/HTTP options?

Some code that reproduces exactly what you're seeing would help.

**Comment by deinok** [comment]
@martincostello Globaly in the `ConfigureServices`

```
serviceCollection.AddControllers()
	.AddJsonOptions(jsonOptions =>
	{
		jsonOptions.JsonSerializerOptions.Converters.Add(new JsonStringEnumConverter());
	});
```

**Comment by captainsafia** [comment]
@deinok Thanks for filing this issue!

Unfortunately, you're running into a long-standing issue with the way configuring JsonOptions evolved in ASP.NET Core. The JSON options instance that you modify when calling `.AddControllers().AddJsonOptions()` is local to MVC and doesn't get picked up by other components in ASP.NET Core. For that, you'll need to modify the lower-level HTTP-based JSON options via `IServiceCollction.ConfigureJsonOptions`.

You can find more background on this problem in this earlier reported issue over at https://github.com/dotnet/aspnetcore/issues/57891.

**Comment by deinok** [comment]
Closing in favour of #58789
