### ISSUE TITLE
OpenAPI: OperationId not set when EndpointName attribute is not available

### ISSUE THREAD

**Issue by hoekstrit** [dotnet/aspnetcore#59053]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

When generating an `openapi.json` using `Microsoft.AspNetCore.OpenApi` and `Microsoft.Extensions.ApiDescription.Server` the OperationId will not be set automically when the `EndpointName` attribute is not present. 

`openapi.json` is based on controllers in AspNetCore.

### Expected Behavior

Expected that OperationId is set following bullet points below. OperationId would be generating following third bullet point.

https://github.com/dotnet/aspnetcore/issues/54598

- If a name is provided on an action via the route method, use that name.
- If a name is provided on an action or endpoint using the EndpointName metadata, use that name.
- If neither is available, attempt to create an operation ID using information available in the route template and endpoint metadata in sequential order.
o The HTTP method associated with the operation stringified (GET, POST, etc.)
o If route segments exist on the application, the route segment values concatenated by _.
o If the route segments contain parameters, use the parameter name sans any constraints.

### Steps To Reproduce

Reproduce using following repository:
https://github.com/hoekstrit/microsoft.openapi.operationid

After building the project/solution it will result in following [openapi.json](https://github.com/hoekstrit/microsoft.openapi.operationid/blob/main/openapi.json)

### .NET Version

9.0.100

**Comment by captainsafia** [comment]
@hoekstrit Thanks for filing this issue!

The behavior that you've referenced was proposed behavior outlined in the original issue but didn't land in the final implementation.

The most accurate guidance on how to set various properties is available [on this docs page](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/openapi/include-metadata#include-openapi-metadata-for-endpoints)).

**Comment by hoekstrit** [comment]
Thank you very much for you answer. I do think that the documentation is missing another option to set the operationId. If I'm correct it's possible to set the operationId as well by setting the name on the HttpMethodAttribute.

Controller
```csharp
[HttpGet(Name = "GetWeatherForecasts")]
public IEnumerable<WeatherForecast> Get()
{
    return Enumerable.Range(1, 5).Select(index => new WeatherForecast
    {
        Date = DateOnly.FromDateTime(DateTime.Now.AddDays(index)),
        TemperatureC = Random.Shared.Next(-20, 55),
        Summary = Summaries[Random.Shared.Next(Summaries.Length)]
    })
    .ToArray();
}
```

openapi.json
```json
{
  "openapi": "3.0.1",
  "info": {
    "title": "OpenApi.Api | v1",
    "version": "1.0.0"
  },
  "paths": {
    "/WeatherForecast": {
      "get": {
        "tags": [
          "WeatherForecast"
        ],
        "operationId": "GetWeatherForecasts",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/WeatherForecast"
                  }
                }
              },
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/WeatherForecast"
                  }
                }
              },
              "text/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/WeatherForecast"
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "WeatherForecast": {
        "type": "object",
        "properties": {
          "date": {
            "type": "string",
            "format": "date"
          },
          "temperatureC": {
            "type": "integer",
            "format": "int32"
          },
          "temperatureF": {
            "type": "integer",
            "format": "int32"
          },
          "summary": {
            "type": "string",
            "nullable": true
          }
        }
      }
    }
  },
  "tags": [
    {
      "name": "WeatherForecast"
    }
  ]
}
```
