### ISSUE TITLE
OnAfterRenderAsync does not fire in MainLayout  .net 9

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#59084]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/OnAfterRenderAsync-does-not-fire-in-Main/10789336)._

---
[regression] [worked-in:Version 17.12.0]
.net 9 Not sure why but OnAfterRenderAsync does not fire in MainLayout it did in in .net 8
could this just be an oversight ?
here's my code
protected override async Task OnAfterRenderAsync( bool firstRender )
{
if(firstRender)
{
UserId = await Ss.GetInt("UserId") != 0 ? await Ss.GetInt("UserId") : 0;
UserTypeId = await Ss.GetInt("UserTypeId") != 0 ? await Ss.GetInt("UserTypeId") : 20;
UserTypeName = (UserTypeId == 0 || UserTypeId == 20) ? "Home" : await Ss.GetString("UserTypeName");
}
}

---
#### Feedback Bot on 11/13/2024, 06:46 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

**Comment by hakenr** [comment]
Tip: `OnAfterRenderAsync` does not fire in static server-side rendering (static SSR) mode (includes prerendering).
