### ISSUE TITLE
Microsoft.AspNetCore.Connections.Abstractions 9.0 needs additional TFM net8.0

### ISSUE THREAD

**Issue by fubar-coder** [dotnet/aspnetcore#59095]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

`Microsoft.AspNetCore.Connections.Abstractions` provides an interface `ITlsHandshakeFeature`, which gained additional members (e.g. `NegotiatedCipherSuite`) in `net8.0`.

The problem here is, that this package `Microsoft.AspNetCore.Connections.Abstractions` targets `netstandard2.0`, `netstandard2.1`, and `net462` in addition to `net9.0`. Now assume that you add `Microsoft.AspNetCore.Connections.Abstractions` 9.0 to a `net8.0` project. This causes the `netstandard2.1` assembly to be used in ASP.NET Core 8, which now has missing members for `ITlsHandshakeFeature`, which results in `MissingMethodException`s.

You can find the original issue here: dotnet/orleans#9238

### Expected Behavior

Adding `Microsoft.AspNetCore.Connections.Abstractions` 9.0 to .NET 8.0 should not result in `MissingMethodException`s.

### Steps To Reproduce

1. Create an ASP.NET Core 8 project
2. Install `Microsoft.AspNetCore.Connections.Abstractions` 9.0
3. Publish
4. Install the web site in your IIS (with HTTPS)

Now watch it crash with the following exception:

```text
[2024-11-19 13:11:34 ERR]  Unexpected exception in static IISHttpServer.HandleRequest.
System.MissingMethodException: Method not found: 'System.Nullable`1<System.Net.Security.TlsCipherSuite> Microsoft.AspNetCore.Connections.Features.ITlsHandshakeFeature.get_NegotiatedCipherSuite()'.
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpServer.IISContextFactory`1.CreateHttpContext
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpServer.HandleRequest(IntPtr pInProcessHandler, IntPtr pvRequestContext)
```

Even if you cannot see the exception, you can always inspect the `Microsoft.AspNetCore.Connections.Abstractions.dll` from the `publish` directory and see that `ITlsHandshakeFeature` misses the `NegotiatedCipherSuite` property, which is only available on .NET Core builds, but a .NET 8.0 target uses the .NET Standard 2.1 build, which contains the incomplete interface.

### Exceptions (if any)

```text
[2024-11-19 13:11:34 ERR]  Unexpected exception in static IISHttpServer.HandleRequest.
System.MissingMethodException: Method not found: 'System.Nullable`1<System.Net.Security.TlsCipherSuite> Microsoft.AspNetCore.Connections.Features.ITlsHandshakeFeature.get_NegotiatedCipherSuite()'.
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpServer.IISContextFactory`1.CreateHttpContext
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpServer.HandleRequest(IntPtr pInProcessHandler, IntPtr pvRequestContext)
```

### .NET Version

9.0.100

### Anything else?

* ASP.NET Core 8
* `net8.0`
* `Microsoft.AspNetCore.Connections.Abstractions` 9.0

**Comment by DeagleGross** [comment]
Marc has explained his thoughts in the [linked orleans issue](https://github.com/dotnet/orleans/issues/9238#issuecomment-2493459032), once we have a decision I will let you know here as well!

**Comment by cadusantos** [comment]
Downgrade Microsoft.AspNetCore.Connections.Abstractions 9.0 to 8.0 or install .net9 runtime on server. It worked for me.

**Comment by fubar-coder** [comment]
@cadusantos : Some problems with your proposal:

1. It wasn't me, but a third party library, which used the 9.0 package
2. Using the .net 9 runtime itself isn't a solution, because you'd have to upgrade to the .NET 9 SDK (including ASP.NET Core)
   1. Updating the projects TFM from LTS (.NET 8.0) to STS (.NET 9.0) isn't always a viable option
   2. The problem is the projects TFM and the wrong interface version in the library for the given TFM

**Comment by JustDre** [comment]
How do we know which NuGet package version this made/will make it to?

**Comment by myz1105** [comment]
Dear Mark Junker i am very thank you bro! I fixed my hosting , and your content helped me
