### ISSUE TITLE
--document-name flag not being respected when generating open api documents at build time.

### ISSUE THREAD

**Issue by WretchedDade** [dotnet/aspnetcore#59097]
I was trying to follow the example in [this guide on learn](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/openapi/aspnetcore-openapi?view=aspnetcore-9.0&tabs=visual-studio#selecting-the-openapi-document-to-generate) for generating documents at build time. It indicates there that you can use the --document-name flag to only generate the document matching the given name. However, I noticed that no matter what value I passed, all of my documents were being generated.

I dug into the code and found the lines where this flag was being consumed. I even saw a comment indicating "If an explicit document name is provided, then generate only that document.". Notably though, I didn't see any code that actually did this restriction prior to the logic iterating over all documents and generating them.

https://github.com/dotnet/aspnetcore/blob/8d0f798cc4de54a2851748be635a58eadbf79593/src/Tools/GetDocumentInsider/src/Commands/GetDocumentCommandWorker.cs#L257-L297

**Comment by captainsafia** [comment]
@WretchedDade Good catch! The current tests don't do a good job of covering this. Would you be interested in opening a PR with a fix?

**Comment by WretchedDade** [comment]
@captainsafia, I’d be happy to take a crack at it!  I should be able to later tonight or over the coming days.
