### ISSUE TITLE
Support port command line argument

### ISSUE THREAD

**Issue by muratg** [dotnet/aspnetcore#5912]
_From @evil-shrike on October 13, 2017 20:59_

`CreateDefaultBuilder(args).UseConfiguration(configuration)` works fine and allows to supply an url via cli: `dotnet run --urls http://localhost:5000`. 
But it'd nice to support `--port` argument as well: 
`dotnet run --port 5000`
Usually we don't need specify IP but only port. 
It was suggested by many people in https://github.com/aspnet/KestrelHttpServer/issues/639. I saw this suggestion many times in many issues but all of them are closed and it's still not supported.

_Copied from original issue: aspnet/KestrelHttpServer#2115_

**Comment by davidfowl** [comment]
Closing this out.
