### ISSUE TITLE
Does Microsoft.AspNetCore.SignalR.Client support AOT?

### ISSUE THREAD

**Issue by JusterZhu** [dotnet/aspnetcore#59133]
Expected behavior
Can Microsoft.AspNetCore.SignalR.Client be used for AOT publishing in a console application or WPF

Actual behavior
When I publish the console application with AOT, it cannot receive server push messages. However, if I cancel the AOT publishing, it can send and receive messages normally. This issue occurs in .NET 9 and the latest version of Microsoft.AspNetCore.SignalR.Client 9.0.0.

Steps to reproduce
The code to reproduce the issue is very simple. It's just a standard example of a SignalR server and client. Once the client is compiled with AOT, it can no longer receive messages.

**Comment by martincostello** [comment]
Looks like not all parts of SignalR support native AoT yet: https://github.com/dotnet/aspnetcore/issues/41704

**Comment by eerhardt** [comment]
@JusterZhu - native AOT is supported on both the client and server of SignalR. However, you need to use the JSON protocol. And you need to hook up the System.Text.Json source generator on both the client and server. See https://learn.microsoft.com/aspnet/core/release-notes/aspnetcore-9.0?view=aspnetcore-9.0#signalr-supports-trimming-and-native-aot

For the Client, this means configuring the `JsonHubProtocolOptions` object and adding a `JsonSerializerContext` to the `PayloadSerializerOptions`. For example:

```C#
[JsonSerializable(typeof(string))]
[JsonSerializable(typeof(int))]
// add all the types you need to serialize
internal partial class AppJsonSerializerContext : JsonSerializerContext
{
}

...

var hubConnectionBuilder = new HubConnectionBuilder()
    .WithUrl(server.Url + "/hub");

hubConnectionBuilder.Services.Configure<JsonHubProtocolOptions>(o =>
{
    o.PayloadSerializerOptions.TypeInfoResolverChain.Insert(0, AppJsonSerializerContext.Default);
});

var connection = hubConnectionBuilder.Build();
```

**Comment by JusterZhu** [comment]
It can now be used normally under AOT compilation according to your description. Thank you very much.
