### ISSUE TITLE
Blazor Authenticate Exception_wasthrown

### ISSUE THREAD

**Issue by hannespreishuber** [dotnet/aspnetcore#59137]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

I migrate a blazor 8 to 9 with SSR and Authentication. As I stuck with issues (eg infinit reload of login) I created a new Blazor Project
Template Blazor Web App, drop down Server per Page
![Image](https://github.com/user-attachments/assets/90f20700-76cd-4128-a61a-b33818c4bf57)
create Database
try to create User 
fail with exception in Identityredirectmanager.cs
![Image](https://github.com/user-attachments/assets/577044d4-ca98-4e07-89f1-ce742c9a41fe)

### Expected Behavior

working default Visual Studio Template 

### Steps To Reproduce

see above

### Exceptions (if any)

![Image](https://github.com/user-attachments/assets/7e2a94a9-2458-417c-bfea-5a476d41a1d5)

### .NET Version

9.0.100

**Comment by mkArtakMSFT** [comment]
As for the redirection cycle that you've observed, that usually is experience when there is a mismatch between the authentication states between the server and the client, which leads to the client to try to redirect to the server for authentication, which in turn, thinking that the user is authenticated, redirects the user back to the page where all this started from. So the cycle repeats.

If you aren't able to figure out the cause for the mismatch, feel free to share a minimal repro project and we can take a look.

**Comment by hannespreishuber** [comment]
it is just click click click project 

https://github.com/[hannespreishuber/BlazorApp2GlobalAuthDeleteMe](https://github.com/hannespreishuber/BlazorApp2GlobalAuthDeleteMe)

create Database- run
Create a user account - Exception

**Comment by javiercn** [comment]
@hannespreishuber the exception is expected.

The framework catches it. The debugger is simply stopping on it, if you run without debugging, the debugger shouldn't break on the exception, and you should be able to execute without pause.

Do you still see an issue when you run without debugging? (Exception and/or login cycle).
