### ISSUE TITLE
How to prevent http-client.env.json copy to publish directory?

### ISSUE THREAD

**Issue by ahdung** [dotnet/aspnetcore#59154]
VS 2022 17.11.5
asp.net core webapi .net8.0 project

I make a `http-client.env.json` file in my project, see [docs](https://learn.microsoft.com/en-us/aspnet/core/test/http-files), then `.csproj` become this:
```xml
...
<ItemGroup>
  <None Include="http-client.env.json" />
</ItemGroup>
...
```
and after I published project, this file appears in publish directory, I don't want it, I tried change `.csproj` to:
```xml
<ItemGroup>
  <None Include(or Update)="http-client.env.json" CopyToPublishDirectory="Never" />
</ItemGroup>
```
Not working, please help.

**Comment by ahdung** [comment]
also tried:
```xml
<None Update="http-client.env.json">
  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
</None>
```

**Comment by WeihanLi** [comment]
Maybe you could try 

```xml
  <ItemGroup>
    <None Remove="http-client.env.json" />
  </ItemGroup>
```

**Comment by ahdung** [comment]
I don't know what happened, issue is gone.
