### ISSUE TITLE
Blazor WASM not supported from Microsoft.SemanticKernel.PromptTemplates.Handlebars from version >= 1.16

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/aspnetcore#59173]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Moved issue from microsoft/semantic-kernel#9830

Microsoft.SemanticKernel.PromptTemplates.Handlebars which depends on uses Handlebars.Net.Helpers, does not support anymore the Blazor WASM projects.
This is because from version 2.4.5 it starts to use using System.Diagnostics in file HandlebarsHelpers in the method Register.

Process.GetCurrentProcess().MainModule?.FileName
System.Diagnostics is not supported for this platform.

### Expected Behavior

Prompt should be sent to the LLM model

### Steps To Reproduce

1. Create a new Blazor application with WebAssembly as Interactive Render Mode
2. Install Semantic Kernel and Microsoft.SemanticKernel with a version 1.30,0
3. Install Semantic Kernel Handlebars with version greater than 1.16
4. Whenever you execute a Kernel function having a prompt with handlebar format

### Anything else?

OS: Windows
IDE: Visual Studio
Language: C#
Source: Microsoft.SemanticKernel = 1.30.0

**Comment by javiercn** [comment]
@luisquintanilla thanks for following up on this repo.

It seems this is already reported on the repo as https://github.com/Handlebars-Net/Handlebars.Net.Helpers/issues/105 and there's a PR https://github.com/Handlebars-Net/Handlebars.Net.Helpers/pull/106 to fix it
