### ISSUE TITLE
OpenAPI document names are case-sensitive in urls

### ISSUE THREAD

**Issue by kpko** [dotnet/aspnetcore#59175]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

I included several different openapi documents via .AddOpenApi("myDoc"). The document name contains upper- and lowercase letters. Later on I want to retrieve my document via /openapi/mydoc.json but I get a 404. After looking into it I found out that this should come from the fact that we're using keyed services:

```csharp
        return endpoints.MapGet(pattern, async (HttpContext context, string documentName = OpenApiConstants.DefaultDocumentName) =>
            {
                // It would be ideal to use the `HttpResponseStreamWriter` to
                // asynchronously write to the response stream here but Microsoft.OpenApi
                // does not yet support async APIs on their writers.
                // See https://github.com/microsoft/OpenAPI.NET/issues/421 for more info.
                var documentService = context.RequestServices.GetKeyedService<OpenApiDocumentService>(documentName);
                if (documentService is null)
                {
                    context.Response.StatusCode = StatusCodes.Status404NotFound;
                    context.Response.ContentType = "text/plain;charset=utf-8";
                    await context.Response.WriteAsync($"No OpenAPI document with the name '{documentName}' was found.");
                }
```

Keyed services seem to be case sensitive. I can resolve this issue by lowercasing everything but this is counter-intuitive for me because the rest of aspnetcore does not use case sensitive routing AFAIK. 

### Expected Behavior

I expect the url for the openapi documents to be case insensitive, so I can receive my document regardless of the casing I use.

### .NET Version

9.0.100

**Comment by sander1095** [comment]
I'm looking into this!
