### ISSUE TITLE
8.0 Helix matrix failing to find JDK

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/aspnetcore#59177]
> ##[error]Could not find the JDK. Either run D:\a\_work\1\s\eng\scripts\InstallJdk.ps1 to install for this repo, or install the JDK globally on your machine (see D:\a\_work\1\s\eng\..\docs\BuildFromSource.md for details).

https://dev.azure.com/dnceng-public/public/_build/results?buildId=879386&view=results

Related: https://github.com/dotnet/aspnetcore/pull/58549

**Comment by BrennanConroy** [comment]
https://github.com/dotnet/aspnetcore/pull/58618?

**Comment by wtgodbe** [comment]
Could be, though I think we'd be seeing it in 9.0 as well if that was the case (that change & the previous one are only in main). It's some combination of that & the build machine most likely

**Comment by wtgodbe** [comment]
Need https://github.com/dotnet/aspnetcore/pull/54631

**Comment by wtgodbe** [comment]
Fixed by https://github.com/dotnet/aspnetcore/pull/59181
