### ISSUE TITLE
Blazor issue with Akamai

### ISSUE THREAD

**Issue by daniel-parra-issatec** [dotnet/aspnetcore#59176]
Hello,

I built a Blazor Web App (server side) and the customer (a bank) needs to run the application through Akamai (masking the base url). When we run the application normally from our Azure server it works fine. However, when we run the application through Akamai and it starts loading it sends the following POST request:

https://[akamai masked domain]/[application name]/_blazor?id=[some ID here]

With the following post data:

{
"mimeType": "text/plain;charset=UTF-8",
"text": "{"protocol":"blazorpack","version":1}\u001e"
}

Akamai is marking the request body as unsafe and the bank wants to know the technical reason behind this post request so they can create an exception rule for this behavior. We did a test with an exception to the request body and it works as intended.

From what I've seen, the post data is always the same so my guess is this as a false positive. The bank is suggesting that I modify Blazor to avoid this behavior (I'm not doing that).

Why does Blazor makes this post request when the application starts running?

Thanks in advance for your help.

cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/34215

**Comment by willdean** [comment]
You may find this page helpful:   https://learn.microsoft.com/en-us/azure/azure-signalr/signalr-concept-client-negotiation

SignalR is the system which is used by Blazor Server to pass events and DOM updates between the client and the server.

**Comment by daniel-parra-issatec** [comment]
Hi,

Thanks for the reply. It helped me understand better what happens.

I just received word from the bank that Akamai is not recognizing the payload data because of the last character "\u001e" which seems to be a " - ". Akamai throws a "parse error: trailing garbage" error and denies the negotiation post request.

Is it possible to modify, or remove this character from the post data? or is this just regular Blazor behavior?

Thanks in advance for your help.

**Comment by BrennanConroy** [comment]
No, you cannot remove it.
Details on it's usage: https://github.com/dotnet/aspnetcore/blob/main/src/SignalR/docs/specs/HubProtocol.md#json-encoding
Also, it's the "record separator" character. https://www.ascii-code.com/30
