### ISSUE TITLE
Razor class library doesn't add associated Js file generated by typescript.

### ISSUE THREAD

**Issue by p6laris** [dotnet/aspnetcore#59188]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

I have a Razor Class Library (RCL) that includes a TypeScript file for JavaScript interop. When the TypeScript compiles into a JavaScript file and outputs it to the wwwroot directory, the generated JavaScript file is not found when using the component and getting 404 notfound error, after migrating to .NET 9.  Also tried #57662

I configured the TS with `tsconfig.json`, then I tried the MSBuild options in the csproj even though added the following configuration to the file, i encounter the same issue:

```xml
<PropertyGroup>
	<TypeScriptOutFile>wwwroot\example.js</TypeScriptOutFile>
	<TypeScriptTarget>ES2016</TypeScriptTarget>
	<TypeScriptAlwaysStrict>true</TypeScriptAlwaysStrict>
	<TypeScriptInclude>Interop\*.ts</TypeScriptInclude>
	<PrepareForBuildDependsOn>
		CompileTypeScript;
		GetTypeScriptOutputForPublishing;$(PrepareForBuildDependsOn)
	</PrepareForBuildDependsOn>
	<TypeScriptSourceMap>false</TypeScriptSourceMap>
</PropertyGroup>
```
Surprisingly, when i include the TS source map with `<TypeScriptSourceMap>true</TypeScriptSourceMap>` it works, but will serve the TS file too.

### Expected Behavior

The js file should be included in the `_content/MyComponent/example.js".

### .NET Version

.NET 9

**Comment by javiercn** [comment]
@p6laris thanks for contacting us.

I don't see why the sourcemap would cause it to be served.

There is a specific issue here for tracking better integration with typescript, I would recommend you upvote that issue. https://github.com/microsoft/TypeScript/issues/60538

As for your case, if you give us a repro, we'll take a look. It's unclear what's going on here, and if/why generating a source map interferes.

**Comment by p6laris** [comment]
@javiercn Thanks for looking into this, I'm looking forward to see some updates and better documentations for Typescript integration.
