### ISSUE TITLE
[Blazor] <details> @ontoggle should support 2-way binding

### ISSUE THREAD

**Issue by S-Luiten** [dotnet/aspnetcore#59200]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I'm trying to create a `<details>` component wrapper with 2-way binding for the 'open' attribute.

### Describe the solution you'd like

The following currently gives an exception: `Unhandled exception rendering component: Object of type 'System.EventArgs' cannot be converted to type 'Microsoft.AspNetCore.Components.ChangeEventArgs'.`
```csharp
<details @bind-open=Open @bind-open:event="ontoggle">
    <summary>Summary</summary>
    <div>
        <span>Content</span>
    </div>
</details>

@code
{
    [Parameter] public bool Open { get; set; }
    [Parameter] public EventCallback<bool> OpenChanged { get; set; }
}
```

Another way to do it would be `open="@Open" @ontoggle="() => Open = !Open"`, but this gives the issue described in #41004. The solution given there is to create separate parameters for the initial and current states, but this solution does not allow 2-way binding.

**Comment by javiercn** [comment]
@S-Luiten thanks for contacting us.

I don't think you can bind to the `toggle` event directly as for binding it needs to be modeled as a `ChangeEvent` (otherwise we can't know the value).

You can probably still use `open="@Open" @ontoggle="() => Open = !Open"` and discard the first call by using some state, since you know you are going to get called at least once. You can discard the first invocation. Something like:

```
public void HandleToggle(EventArgs args)
{
    if(_isFirstTime){
      _isFirstTime = false;
      return;
    }
    Open = !Open;
}
```

**Comment by S-Luiten** [comment]
Hi @javiercn thanks for the reply, I tried something like that initially but ran into issues when trying to update the open state through code. After trying a couple different things I think I have now found a working solution:

```razor
<details open="@Open" @ontoggle=HandleToggle>
    <summary>Summary</summary>
    <div>
        <span>Content</span>
    </div>
</details>

@code
{
    private bool _open;

    [Parameter] public bool Open { get; set; }
    [Parameter] public EventCallback<bool> OpenChanged { get; set; }

    private void HandleToggle(EventArgs e)
    {
        _open = !_open;

        if (_open != Open)
        {
            Open = _open;
            _ = OpenChanged.InvokeAsync(_open);
        }
    }
}
```

Closing as solved
