### ISSUE TITLE
Minor issues with RequestLocalizationMiddleware

### ISSUE THREAD

**Issue by S-Luiten** [dotnet/aspnetcore#59218]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

There's an issue with the constructor documentation for `RequestLocalizationMiddleware`:
![Image](https://github.com/user-attachments/assets/ec13d326-8d72-4516-8ae3-f38cbf7deebc)

Looking at the source code, it seems that line 31 and 32 need to be swapped around.
https://github.com/dotnet/aspnetcore/blob/main/src/Middleware/Localization/src/RequestLocalizationMiddleware.cs

I also noticed there's a null check on lines 138 `if (cultureName != null)` and 186 `if (name == null || supportedCultures == null)`, however `StringSegment` is a struct, so it can never be null.

**Comment by martincostello** [comment]
> Looking at the source code, it seems that line 31 and 32 need to be swapped around.
> https://github.com/dotnet/aspnetcore/blob/main/src/Middleware/Localization/src/RequestLocalizationMiddleware.cs

Feel free to open a PR to switch them the correct way around.

**Comment by S-Luiten** [comment]
I made a PR for the documentation issue. I'm not sure the null checks can be removed because `StringSegment` implements `IEquatable<string?>` and can be implicitly converted from `string`.
