### ISSUE TITLE
Microsoft.VisualStudio.Web.CodeGeneration has vulnerable dependencies, no upgrade available

### ISSUE THREAD

**Issue by ygoe** [dotnet/aspnetcore#59223]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

The NuGet package Microsoft.VisualStudio.Web.CodeGeneration in version 6.0.18 has a transitive dependency on System.Net.Http 4.3.0 that is marked as vulnerable. I guess version 6 is still in support, right? Has somebody already noticed this?

**Comment by ygoe** [comment]
I **should**, because it's there, or I **must** because 6 is no longer supported?!

**Comment by martincostello** [comment]
You could also fix it by explicitly adding a reference to a version of the transitive dependency that isn't vulnerable, but that's not recommended as by continuing to use .NET 6 you'll be vulnerable to new vulnerabilities in the future as they are discovered.
