### ISSUE TITLE
CascadingValue allways triggers OnParametersSet{Async} event if the value is unchanged.

### ISSUE THREAD

**Issue by artyomszasa** [dotnet/aspnetcore#59228]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

In our project we've encountered a strange behaviour: In **blazorwasm** OnParameterSet{Async} was invoked on some (but not all) "page" components when navigating away from them. After some ivestigation we've found that not-fixed CascadingValue in the layout is causing the issue: if a "page" component has a property receiving the affected cascading parameter then OnParametersSet{Async} is invoked when user is navigating to some other component, otherwise this does not happen.

I far as I found [CascadingValue.SetParametersAsync](https://github.com/dotnet/aspnetcore/blob/7e5155df4a44758c05483d8566c4c0b62298175f/src/Components/Components/src/CascadingValue.cs#L51) seem to unconditionally render itself/notify subscribers about "_the change_" thus the following happens:

1. Some navigation event occurs
2. Router is rendering its body
3. When rendering comes to CascadingValue inside the Layout component it notifies all the subscribes about "_the change_" **before** `Body` of the layout is rerendered --> OnParametersSet{Async} is invoked on all the subscribed components (this is the issue as the subscribed components are the "old ones" at this points)
4. `Body` of the layout is rendered --> the "old components" are removed/disposed and new ones are initialized (OnParameterSet{Async} invoked) as it is intended

The problem is that there was no change in the value of the CascadingValue and it seems very strange to me that the components are notified abount "_the change_" event which did not really happen.

I've searched for possible solutions:
- There is no way to pass something like `IEqualityComparer` to `CascadingValue` as rendering/nofitication happends unconditionally..
- There is no way to reimplement `CascadingValue` locally to use any kind of equality comparison as `ICascadingValueSupplier` interface is internal..
- The only option I've found is to lift all not fixed `CascadingValue`-s outside the `Router` which does work in out case yet there are more use-cases when lifting `CascadingValue`-s may not be possible..

I understand that current implementation of the `CascadingValue` is good enough to be easy-to-use and covers most of the use-cases, yet it would be really nice if the functionality could be configured or there were a way to create own implementation for special cases.

### Expected Behavior

`CascadingValue` does not notify subscribed components if its value has not changed.

Optionally it may accept `IEqualityComparer<>` or `ICascadingValueSupplier` may be made public.

### Steps To Reproduce

- Create new blazorwasm solution from a template;
- Add `CascadingValue` with any value to the layout;
- Create at least to components with `@page` annotation, `[CascadingParameter]` and some logging in `OnParamtersSet`;
- Run it and navigate between components and see invocation of `OnParameterSet` being logged twice: once on initialization, once then navigating away from any of the components above.

### .NET Version

8.0.404

**Comment by javiercn** [comment]
@artyomszasa thanks for contacting us.

There's nothing special about cascading value. It likely depends on the value you are using. The Blazor change detection algorithm is very conservative and favors triggering additional renders over potentially getting incorrect results by skipping a given render.

As such, there are only a subset of well-known types that we test for equality against. In particular, those are:
* DBNull
* Boolean
* Char
* SByte
* Byte
* Int16
* UInt16
* Int32
* UInt32
* Int64
* UInt64
* Single
* Double
* Decimal
* DateTime
* String
* Guid
* DateOnly
* TimeOnly
* EventCallback

Anything else is treated as potentially mutable, and hence different, triggering a re-render.

**Comment by artyomszasa** [comment]
@javiercn Thank you for a reply but I think you've misundrestood the problem.

The problem is that `OnParameterSet{Async}` is unconditionally invoked when **leaving** a page if it has any non-fixed cascading paramter.

I pretty sure I understand the change detecting algorithm yet **reredenring a page on leave** still does not seem to be the expected behaviour...

Starting from the default blazorwasm template (`dotnet new blazorwasm`):
- I've added dummy class called `MyStateObject` to the project;
- I've added `private static MyStateObject StateObject { get; } = new();` to the `MainLayout.razor`;
- I've added `<CascadingValue Value=@(StateObject)>` around the `@Body` part of the `MainLayout.razor`;
- I've added `[CascadingParameter] public MyStateObject? GlobalState { get; set; }` to both `Home.razor` és `Counter.razor`;
- I've overidden `OnParamtersSet` of both `Home.razor` és `Counter.razor` to write to console how many times it is invoked;
- I've run the project and switched betweeen `Home` and `Counter`
What I see is that `OnParametersSet` is invoked once I'm opening a page (this is what I've expected) **AND** once I'm **leaving** a page (which does not seem an expected behaviour to me)!

See the example here: https://storage.googleapis.com/artyom-temp/BlazorCascadingValue.zip

As far as I can understand the following happens when I switch from Home to Counter or vice-versa:
- Router is rendering
- MainLayout is rendeing -- and its renders CascadingValue
- Cacading value is **notifying the "old" page component** (the page I am about to **leave**), blazor change detection runs and -- as you've mentioned -- due to `MyStateObject` being considered as potentially mutable the "old" page is rerendered (at least the `SetParametersAsync` is invoked); **I assume this is not the expected behaviour**
- Rendering goes further and rendering `@Body` part which is inside of the the `CascadingValue` --> "old" page is destroyed/disposed and "new" page is created and receives `MyStateObject` --> `SetParametersAsync` of the "new" page is being invoked (which is expected)

Ao do you telling me it is an expected behaviour to invoke `SetParametersAsync` on a component right before destroing/disposing it and it is expected from developer to handle `OnParametersSet{Async}` being invoked at the end of the component's lifecycle?

**Comment by artyomszasa** [comment]
Why has this issue been closed (as completed). 
I've clearly described the problem and attached exmaple to reproduce the issue just yesterday.

The answer I've received does not address the issue, it seem that noone event tried to understand the problem.. Very disappointing..

**Comment by philippdolder** [comment]
@artyomszasa agree, that the MS People didn't bother trying to understand your issue.

interestingly enough, I encounter similar issues. When I have a non-primitive cascading value in my `MainLayout` I observer something similar, but a bit different.

- 1 `OnParametersSet` on the leaving component
- but, 2 `OnParametersSet` on the new (target) component.

I understood you only got 1 trigger for the new component in this case?
Seems we get an extraneous (obsolete) call on leave and enter

Fortunately in our case setting the cascading value to `IsFixed` is a reasonable option and resolves the issue.
