### ISSUE TITLE
Use TraceIdentifier of HttpContext as a span in W3C when possible

### ISSUE THREAD

**Issue by SergeyKanzhelev** [dotnet/aspnetcore#5927]
## Motivation

TraceIdentifier is represented as a unique string. Implementation of TraceIdentifier should be aligned with migration to W3C. TraceIdentifier should match the `span-ID` in W3C distributed tracing context when possible.

CC: @seth-capistron, @vancem, @jacpull, @lmolkova, @glennc, @davidfowl

**Comment by muratg** [comment]
cc @shirhatti @davidfowl @Tratcher

**Comment by anurse** [comment]
Epic https://github.com/aspnet/AspNetCore/issues/8924

**Comment by anurse** [comment]
Waiting on an API on Activity to allow us to set the ID when we have one from the hosting server (IIS, etc.). Moved to 3.1 until we have this API.

**Comment by davidfowl** [comment]
@SergeyKanzhelev after looking at things I agree we should have a plan for this (hopefully as part of 3.0 even if execution happens in 3.1). Right now with activities and w3c, there's no good place to store the trace identifier (I'm not even sure if the format will align in all cases, but maybe we can make it).

**Comment by kzu** [comment]
Heya, coming late to this: has been any movement on it? Can middleware change this and start a new Activity and have that somehow replace the TraceIdentifier more or less automatically?

**Comment by shirhatti** [comment]
@kzu Hosting already does this. We already create a new Activity for each request and set the parent id and trace state if the right headers were present on the incoming request. We've also already changed the default activity format to W3C.

**Comment by shirhatti** [comment]
@davidfowl @tarekgh Is there any work left here or is this issue good to close?

**Comment by tarekgh** [comment]
I think this can be closed. 

CC @noahfalk
