### ISSUE TITLE
Cannot use Client Certificate Authentication in .http files

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#59285]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Cannot-use-Client-Certificate-Authentica/10793161)._

---
I would like to ask for dfferent types of authentication support for HTTP files.

Currently it is possible to specify a token in the Authorization header but Client certificate authentication is not possible via http files. Therefore, we have to use Postman or other tools for testing such APIs.

---
#### Feedback Bot on 11/19/2024, 04:16 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

**Comment by mkArtakMSFT** [comment]
@captainsafia who do you think this issue should go to?

**Comment by halter73** [comment]
This is documented as currently unsupported, so this is more of a VS feature request than a bug:

> ## Unsupported syntax
> ...
> - Certificate based authentication

https://learn.microsoft.com/en-us/aspnet/core/test/http-files?view=aspnetcore-9.0#unsupported-syntax

**Comment by mkArtakMSFT** [comment]
I've reopened the original VS Feedback ticket and pinged @sayedihashimi  to help with routing. Closing this as external.
