### ISSUE TITLE
How to Fix ASP0006 within a loop?

### ISSUE THREAD

**Issue by Grandizer** [dotnet/aspnetcore#59292]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

I initially added this on the documentation page but they said add it here.

I have a .Net 9 Blazor app with a method where I am creating a Fragment and I may or may not have any number of extra attributes. I need those to be part of the `Fragment` and I know there needs to be a sequence number. I have code below and no way I work about it can I get it to work. I cannot get this `ASP0006` warning to go away.

### Expected Behavior

CoPilot has no clue how to help me with any success. Sure it is only a warning, but having a way around it is great. The warning should be at least smart enough to know that I am in a loop and just let it slide or if you guys know of a work-around to make it work, that would rock!

### Steps To Reproduce

    protected override void OnParametersSet()
    {
      base.OnParametersSet();

      var iconData = Constants.Icons.FirstOrDefault(x => x.Name == Name);
      var totalItems = 0;

      if (iconData is null)
          return;

      Fragment = builder =>
      {
          builder.OpenElement(0, "svg");

          builder.AddAttribute(1, "xmlns", "http://www.w3.org/2000/svg");
          builder.AddAttribute(2, "viewBox", iconData.ViewBox);
          builder.AddAttribute(3, "preserveAspectRatio", "xMidYMid meet");

          if (Attributes != null)
          {
              var keys = Attributes.Keys.ToList();
              totalItems = keys.Count + 4;

              for (int i = 0; i < keys.Count; i++)
              {
                  var key = keys[i];
                  var value = Attributes[key];

                  builder.AddAttribute(4 + i, key, value);
              }
          }

          if (!string.IsNullOrWhiteSpace(Title))
          {
              builder.OpenElement(4 + totalItems, "title");
              builder.AddContent(5 + totalItems, Title);
              builder.CloseElement();
          }

          builder.AddContent(6 + totalItems, new MarkupString(iconData.Path));
          builder.CloseElement();
      };
    }

### Exceptions (if any)

Alter the `ASP0006` warning to realize it is within a loop and either ignore the issue (assuming nothing can be done to fix it) or show me how to fix it.

### .NET Version

9.0.100

### Anything else?

While you are at it. Make Tabs the default instead of spaces.
I might suggest just 2 spaces per tab even!

**Comment by javiercn** [comment]
@Grandizer thanks for contacting us.

I don't believe you need to do things that way. You can use `AddMultipleAttributes` instead to add a list and pass a constant to the sequence. You also don't need to pass different sequence numbers for each attribute, you can use the same sequence number when passing down a list of attributes.

See the implementation for `AddMultipleAttributes` [here](https://github.com/dotnet/aspnetcore/blob/3fe06183a8d3ef32de0d16863d232d5652b1fe9b/src/Components/Components/src/Rendering/RenderTreeBuilder.cs#L437-L455)
