### ISSUE TITLE
Includes the endpoint protocal version in the log

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/aspnetcore#59298]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

We're trying to use multi ports in the application

![Image](https://github.com/user-attachments/assets/6538e321-69f6-44fc-90f6-eff89b9ff9be)

```json
{
  "Kestrel": {
    "Endpoints": {
      "Http": {
        "Url": "http://localhost:5000",
        "Protocols": "Http1"
      },
      "Http2": {
        "Url": "http://localhost:5001",
        "Protocols": "Http2"
      },
      "Http2_2": {
        "Url": "https://localhost:5002",
        "Protocols": "Http1AndHttp2"
      }
    }
  }
}
```

when the server starts, now we already have a log likes

```
Now listening on: http://[::]:80
```

Could we also includes the protocol for the endpoint so that we could easily know which port using which protocal

### Describe the solution you'd like

Including the endpoint protocol info in the log

https://github.com/dotnet/aspnetcore/blob/15a058432bee5ac292a1c47481117c9f3d6902f7/src/Hosting/Hosting/src/GenericHost/GenericWebHostService.cs#L203-L206

**Comment by DeagleGross** [comment]
Hey, thanks for posting a proposition. Do you expect it to appear in net10, or you need a workaround to use it today?

_Re .net10:_ We probably can think about providing API to specify what users want to include in the log of "Now listening on ...", but for me "protocol" is too specific for your use case (not all users are using "protocol" as a parameter from the configuration).

Today, you can add your own log by getting the configuration like:
`app.Configuration.GetRequiredSection("Kestrel")`.

let me know what you think

**Comment by WeihanLi** [comment]
@DeagleGross thanks for the input, yeah, we could check the config to determine the protocol info, not sure if it would be too complex to implement, it would be great to support it in dotnet 10 if possible, could be in the backlog I think

**Comment by DeagleGross** [comment]
I have chatted with team members, and this case seems to be very specific to your scenario, @WeihanLi. I dont think there are other users requesting this, and what is even more important - there is a relatively easy workaround of parsing the Configuration in a custom way.

```c#
var endpointSections = app.Configuration.GetSection("Kestrel").GetSection("Endpoints");
foreach (var endpointSection in endpointSections.GetChildren())
{
    var protocol = endpointSection["Protocols"];
    var url = endpointSection["Url"];

    Console.WriteLine($"Endpoint now listening on {url} with protocol {protocol}");
}
```
which gives such output based on input from your sample:
> Endpoint now listening on http://localhost:5000 with protocol Http1
Endpoint now listening on http://localhost:5001 with protocol Http2
Endpoint now listening on https://localhost:5002 with protocol Http1AndHttp2

I will mark an issue as "resolution: won't fix", but feel free to reopen if there are suggestions \ or there are more people looking forward to this.
