### ISSUE TITLE
ASP.NET Core 8.0 AntiforgeryTokenValidation not working correctly for React SPA

### ISSUE THREAD

**Issue by Ninja4Code** [dotnet/aspnetcore#59319]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

I have an ASP.NET 8.0 SPA project with React where I've set up Antiforgery validation in the request pipeline.  However, the necessary cookie/header does not get set.  When I run the exact same code in ASP.NET 8.0 binary I get a 400 bad request and no Response cookie gets generated.  However the Request cookies get generated like before.![Image](https://github.com/user-attachments/assets/e497b03a-e33e-4c8a-a950-cf9a6087497a)

Here's some of my example code:
program.cs
`builder.Services.AddAntiforgery(options => { options.Cookie.Name="X-XSRF-TOKEN"; options.HeaderName = "X-XSRF-TOKEN"; options.Cookie.HttpOnly = false; });
...
app.UseHttpsRedirection();
app.UseStaticFiles();
app.UseRouting();
app.UseAuthentication();
app.UseAuthorization();
app.UseAntiforgery();
app.UseCookiePolicy();
app.UseCors(CorsPolicy);

app.UseEndpoints(endpoints => {
  endpoints.MapGet("antiforgery/token", (HttpContext context) =>
  var antiforgery =app.Services.GetRequiredService<IAntiforgery>();
  var tokens = antiforgery.GetAndStoreTokens(context);
  context.Response.Cookies.Append("X-XSRF-TOKEN", tokens.RequestToken!,
    new CookieOptions { HttpOnly = false });
  return Results.Ok();
});
`

Fetch request
`const postData = async (url = '', data = {}) => {
    // RETRIEVING TOKEN FROM MINIMAL API, WORKS
    let r = await fetch('/antiforgery/token', {
       method: "GET"
    }).then(response => {
        // READS THE COOKIE IN BOTH 6.0 and 8.0
        console.log("Reading my cookie" + readCookie("X-XSRF-TOKEN"));
    })
    const response = await fetch(url, {
        method: 'POST',
        mode: 'cors',
        cache: 'no-cache',
        credentials: 'include',
        headers: {
           'Content-Type': 'application/json'
            // EVEN IF I MANUALLY ADD AN X-XSRF-TOKEN HEADER IN 8.0 IT DOESN'T GET ADDED
        },
        body: JSON.stringify(data)
    });
    return response.text();
  }             
`

### Expected Behavior

The exact same code works with an ASP.NET 6.0 binary.  It generates the necessary Request and Response cookies.  Here's a screen shot.![Image](https://github.com/user-attachments/assets/b14f3bf2-05f1-4696-a82d-9bce3dbbc6a6)

### Steps To Reproduce

1. Configure Antiforgery in program.cs
2. Create Minimal API for a route to create the request token (WORKS, token generated as cookie)
3. Annotate WebAPI Post Action method with [ValidateAntiforgeryToken]
4. Create a POST request in JavaScript using the FetchAPI that posts to the Controller route in step above
5. Submit a request in a React component
6. Request fails (only for 8.0)

### Exceptions (if any)

I will get the following exception:
`Microsoft.AspNetCore.Mvc.Infrastructure.ClientErrorResultFilter (Order: -2000) 
2024-12-04 15:18:41.6399||INFO|Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.ValidateAntiforgeryTokenAuthorizationFilter|Antiforgery token validation failed. The required antiforgery header value "X-XSRF-TOKEN" is not present. **Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The required antiforgery header value "X-XSRF-TOKEN" is not present.
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.ValidateRequestAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.ValidateAntiforgeryTokenAuthorizationFilter.OnAuthorizationAsync(AuthorizationFilterContext context)**
2024-12-04 15:18:41.6399||INFO|Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker|Authorization failed for the request at filter 'Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.ValidateAntiforgeryTokenAuthorizationFilter'. 
2024-12-04 15:18:41.6476||DEBUG|Microsoft.AspNetCore.Mvc.Infrastructure.DefaultOutputFormatterSelector|List of registered output formatters, in the following order: Microsoft.AspNetCore.Mvc.Formatters.HttpNoContentOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.StringOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.StreamOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter `

### .NET Version

8.0.403

### Anything else?

It appears that 8.0 is handling the Antiforgery token validation in a different manner than before.  The code that worked in 6.0 is not working in 8.0.

**Comment by Ninja4Code** [comment]
This is a screen shot from Chrome Dev Tools on a successful ASP.NET 6.0 request.  You'll notice that it created the response cookie.  THIS DID NOT HAPPEN FOR 8.0

![Image](https://github.com/user-attachments/assets/88897663-0ad1-40a5-a33c-cf107beb49e9)

**Comment by gabomartin** [comment]
Antiforgery is composed by two tokens. One is the Cookie token that is sent as a cookie to the backend. The second one is a Request token that must be sent via http headers.
You have to also send the request token as a header which is different from the cookie token. Also I suggest manually setting your cookie token as an http only cookie.

**Comment by Ninja4Code** [comment]
I got it working.  The problem was me.  For SPA you have to set the header explicitly.  It's not looking for a cookie. Here's some of the example code.

Changes: 

- In the MinimalAPI method I removed the appending of cookies.  In fact, I could probably get rid of any cookie setup in the Antiforgery wireup.
- I had to explicitly get the header from the first fetch request (/antiforgery/token) and then set the header in the second fetch request.

`builder.Services.AddAntiforgery(options => { 
    var cookie = options.Cookie;
    cookie.Name= "X-XSRF-TOKEN";
    options.HeaderName = "X-XSRF-TOKEN"; 
    cookie.HttpOnly = false; 
    cookie.SameSite = SameSiteMode.Strict;
    cookie.SecurePolicy = CookieSecurePolicy.Always;
});
....
app.MapPost("/antiforgery/token", async (IAntiforgery forgeryService, HttpContext context) =>
{   
    var tokens = forgeryService.GetAndStoreTokens(context);
    context.Response.Headers.Append("X-XSRF-TOKEN", tokens.RequestToken!);
     return Results.Ok(new {message="success"});    
}).RequireCors().RequireAuthorization("AuthenticatedOnly");

`

ReactJS Code:

The key here is where I get the X-XSRF-TOKEN header from the response of the first request and then append it as a request header of the second fetch request.
`
    let xsrf='';
    let r = await fetch('/antiforgery/token', {
        method: "POST",
        credentials: "include"
        
     }).then(response => {
       xsrf = response.headers.get('X-XSRF-TOKEN');
      })
      try {
        const response = await fetch(url, {
            method: 'POST',
            mode: 'cors',
            cache: 'no-cache',
            credentials: 'include',
            headers: {
                'Content-Type': 'application/json',
                'X-XSRF-TOKEN': xsrf
            },
            body: JSON.stringify(data)
        });
        if (!response.ok) {
            console.log("This is status:"  + response.status)
            throw new Error(`HTTP error! Status: ${response.status}`);
        }
        return await response.json();`

**Comment by Ninja4Code** [comment]
The big problem was that I was appending both a cookie and a header in the response and I'm not sure if it was overriding the autogenerated header/cookie in the antiforgery wireup.  It seems I needed to just append either a cookie or a header, but not both.  I may have still been able to use the cookie.  For now, just will use the header.

So I'll say that ASPNET Core is actually handling the Antiforgery scenario correctly.
