### ISSUE TITLE
OpenAPI's servers property contains inaccessible url when listening to any ip.

### ISSUE THREAD

**Issue by CamusGao** [dotnet/aspnetcore#59313]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

When the program listening to any ip like IPAddress.Any or IPAddress.IPv6Any, the address  IServerAddressesFeature.Addresses returning contains a 0.0.0.0 or {::} host which is inaccessible to web clients.

### Expected Behavior

not explicitly indicate the server URL or use a relative path to ensure that the webapis can be accessed from the same address as accessing the document

### Steps To Reproduce

set the applicationUrl in launchSettings.json to http://*:5113 or any other way to let the program listen to any ip.

### .NET Version

9.0.0

**Comment by captainsafia** [comment]
@CamusGao Thanks for filling this issue.

For local development scenarios, the current OpenAPI implementation uses a strategy that is optimized for API services running against local API services. It's possible for you to customize this default behavior using an OpenAPI document transformer. You can view the docs for [those here](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/openapi/customize-openapi?view=aspnetcore-9.0)).
