### ISSUE TITLE
Weak Encryption in ManagedPbkdf2Provider class

### ISSUE THREAD

**Issue by Anchels** [dotnet/aspnetcore#59329]
I was analyzing **ASP.NET Core** using **Svace** static analyer. It has found **WEAK_ENCRYPTION**  category error with the following message:

`This algorithm is vulnerable, use SHA256 or SHA512 instead`

in method `PrfToManagedHmacAlgorithm()`. Here's the source code:

https://github.com/dotnet/aspnetcore/blob/3fe06183a8d3ef32de0d16863d232d5652b1fe9b/src/DataProtection/Cryptography.KeyDerivation/src/PBKDF2/ManagedPbkdf2Provider.cs#L69-L91

---

What do you think about marking the HMACSHA1 enum value as `obsolete`?

https://github.com/dotnet/aspnetcore/blob/3fe06183a8d3ef32de0d16863d232d5652b1fe9b/src/DataProtection/Cryptography.KeyDerivation/src/KeyDerivationPrf.cs#L9-L25

**Comment by blowdart** [comment]
The default implementation of data protection doesn't use this class at all, it's provided for folks wanting to write their own implementations. If you're doing that we consider that you know what you're doing, and if you must use something that's considered obsolete you have good reason.

Additionally marking an individual enum value has some interesting side effects around serialization.

It's not something we're going to do I'm afraid.
