### ISSUE TITLE
Add factory overload for `UseServiceProviderFactory`

### ISSUE THREAD

**Issue by ChristopherHaws** [dotnet/aspnetcore#5933]
Hello,

I am trying to configure the generic `HostBuilder` to use Autofac, and I am running into an issue that I think could be solved by adding the following overload to `IHostBuilder`:
```csharp
IHostBuilder UseServiceProviderFactory<TContainerBuilder>(Func<HostBuilderContext, IServiceProviderFactory<TContainerBuilder>> configureDelegate);
```

The usage of this api would allow for the following startup:
```csharp
.UseServiceProviderFactory(hostBuilderContext => new AutofacServiceProviderFactory(containerBuilder => containerBuilder.Properties.Add(nameof(HostBuilderContext), hostBuilderContext)));
```

This change would allow all of my Autofac modules to gain access to the `HostBuilderContext`.

```csharp
public abstract class AutofacModule : Autofac.Module
{
    protected sealed override void Load(ContainerBuilder builder)
    {
        base.Load(builder);

        var hostBuilderContext = builder.Properties[nameof(HostBuilderContext)] as HostBuilderContext;

        this.Load(builder, hostBuilderContext);
    }

    protected abstract void Load(ContainerBuilder builder, HostBuilderContext hostBuilderContext);
}
```

**Comment by davidfowl** [comment]
This was [added](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.hostbuilder.useserviceproviderfactory?view=dotnet-plat-ext-5.0#Microsoft_Extensions_Hosting_HostBuilder_UseServiceProviderFactory__1_System_Func_Microsoft_Extensions_Hosting_HostBuilderContext_Microsoft_Extensions_DependencyInjection_IServiceProviderFactory___0___)
