### ISSUE TITLE
UI Not Updating After Task.Delay in .NET MAUI Blazor Component

### ISSUE THREAD

**Issue by nehaProgrammer29** [dotnet/aspnetcore#59347]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

I have a ViewModel that handles the state of a process. When the process completes, I want to disable a button for 8 seconds and then re-enable it. However, the UI does not reflect the state change after the delay.

### Expected Behavior

The button should be re-enabled after the 8-second delay when the process completes.

### Steps To Reproduce

**Create a ViewModel:**

- Implement a ViewModel with a method that includes a Task.Delay and updates a property.
- Raise an event to notify the component of state changes.

**Create a Blazor Component:**

- Inject the ViewModel into the component.
- Subscribe to the ViewModel’s state change event.
- Bind the UI elements (e.g., a button) to the ViewModel properties.

**Trigger the State Change:**

- Call the ViewModel method that includes the Task.Delay from the component.
- Observe that the UI does not update after the delay.

### .NET Version

.NET 8

### Anything else?

- The same logic works correctly in another component when triggered from OnInitializedAsync.
- Calling StateHasChanged directly in the component updates the UI correctly, but I want to avoid calling StateHasChanged in the ViewModel.

**Comment by javiercn** [comment]
@nehaProgrammer29 thanks for contacting us.

Can you please provide a repro project as a public github repository that we can clone?
