### ISSUE TITLE
JIT optimization breaks simple method on Azure App Service in .net 9

### ISSUE THREAD

**Issue by samcic** [dotnet/aspnetcore#59341]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Given the following simple bare-bones .net 9 aspnetcore application...

```
// Program.cs
var builder = WebApplication.CreateBuilder(args);
var app = builder.Build();
app.MapGet("/jitoptimized", () => Helpers.JitOptimized(new Dictionary<string, object>
{
    {"k", null},
}));
app.MapGet("/jitnotoptimized", () => Helpers.JitNotOptimized(new Dictionary<string, object>
{
    {"k", null},
}));
app.Run();

// Helpers.cs
public static class Helpers
{
    public static string JitOptimized(IDictionary<string, object> dictionary)
    {
        var sb = new StringBuilder();
        foreach (var pair in dictionary)
        {
            var valueAsEnumerable = pair.Value as IEnumerable;
            if (!(pair.Value is string) && valueAsEnumerable != null)
            {
                foreach (var value in valueAsEnumerable)
                {
                    sb.Append(pair.Key + "(enumerable)=" + pair.Value);
                }
            }
            else
            {
                sb.Append(pair.Key + "(non-enumerable)=" + pair.Value);
            }
        }
        return sb.ToString();
    }

    [MethodImpl(MethodImplOptions.NoOptimization)]
    public static string JitNotOptimized(IDictionary<string, object> dictionary)
    {
        var sb = new StringBuilder();
        foreach (var pair in dictionary)
        {
            var valueAsEnumerable = pair.Value as IEnumerable;
            if (!(pair.Value is string) && valueAsEnumerable != null)
            {
                foreach (var value in valueAsEnumerable)
                {
                    sb.Append(pair.Key + "(enumerable)=" + pair.Value);
                }
            }
            else
            {
                sb.Append(pair.Key + "(non-enumerable)=" + pair.Value);
            }
        }
        return sb.ToString();
    }
}
```

This app runs fine locally on a Windows 11 machine. When deployed and run on Azure App Service (configured to .net 9 in the Azure settings), it breaks. The `/jitoptimized` route returns the incorrect result `(non-enumerable)=` (i.e. without the "k" at the start). The `/jitnotoptimized` route returns the correct result `k(non-enumerable)=`.

Note that downgrading to `<TargetFramework>net8.0</TargetFramework>` in the `*.csproj` file and redeploying the app to Azure fixes the issue on Azure as well.

In the problematic case of running on Azure App Service with .net 9, the exact same code run with the `[MethodImpl(MethodImplOptions.NoOptimization)]` attribute also fixes the problem (as shown in the `/jitnotoptimized` in the repro steps).

So, based on our investigation so far, it seems like there's some bug with the JIT optimization on Azure App Service when running .net 9 apps.

We first noticed this through a library (see https://github.com/googleapis/google-api-dotnet-client/issues/2897), but managed to isolate and simplify the repro. It's likely that it's affecting lots of other code running on .net 9 on Azure App Service.

### Expected Behavior

Both routes show the same result of `k(non-enumerable)=`.

### Steps To Reproduce

**Reproduction steps:**

1. Deploy the app to Azure App Service on Windows with .NET 9 selected in the configuration
2. Navigate to the `/jitoptimized` route, and also to the `/jitnotoptimized` route and inspect the results

### .NET Version

9.0.101

### Anything else?

Apologies if I've created this issue in the wrong place (happy to recreate in the right place if you can provide a pointer).

**Comment by AndyAyersMS** [comment]
This might be the same issue as in ttps://github.com/dotnet/runtime/issues/108969. If so, there is a fix slated for the first .NET 9 servicing release.

We should probably transfer this over to the dotnet/runtime repo.

cc @jakobbotsch

**Comment by samcic** [comment]
@AndyAyersMS Thanks for the pointer! Yes, if we add `DOTNET_JitEnablePhysicalPromotion=0` as an environment variable on the Azure App Service resource, the issue is resolved. Closing this here as a dup.

**Comment by ThomasFOG** [comment]
Hello there!

It seems that the fix hasn't been backported into .NET 9 as of 9.0.101.
Is it still planed to be backported?

(Running into this issue with a desktop app failing to run google's API if tiered compilation is disabled.)

**Comment by AndyAyersMS** [comment]
Yes. It will be in 9.0.2, which should be available in a few weeks.

**Comment by ThomasFOG** [comment]
Thanks for the heads up!
