### ISSUE TITLE
Access is denied - VS 17.12.3

### ISSUE THREAD

**Issue by rsankardayal** [dotnet/aspnetcore#59342]
Below are the steps to reproduce the issue;

1. Create new **ASP.NET Cor Web API** with name "**WebApplication3Test1**" - See image below
2. Select **.NET 9.0** (Standard Term Support) - See image below
3. Click on "**https**" to run program - See image below
4. The debug window open briefly and then the error popup - See image below

**Other Testing:**

1. If I run it with "**IIS Express**" with .NET 9 and project name (**WebApplication3Test1**) it works.
2. Reference Step (1) - Run the with "**https**", get an error "**Access is Denied**" - See image
3. If I go to the **bin/Debug/net9.0** folder, double click on **WebApplication3Test1.exe**, explorer crashes
4. If I renamed the solution and project from "**WebApplication3Test1**" to "**test1**" it works with "**https**" - See image
5. Reference Step (4) - If I go to the **bin/Debug/net9.0** folder, double click on **Test1.exe**, it's runs

From what I can see it has something to do with the project name length, any project name over 15 char length seems to fail.

![Image](https://github.com/user-attachments/assets/22f85d15-7051-4c92-84cd-b5816e71c273)

![Image](https://github.com/user-attachments/assets/4efc0b5b-8a95-44f5-8b49-32cc9c0bf4c7)

![Image](https://github.com/user-attachments/assets/dd879613-778a-445d-af7f-fd59874e404f)

![Image](https://github.com/user-attachments/assets/46105f14-3c21-4047-a6ae-6e295ea662b0)

![Image](https://github.com/user-attachments/assets/65ca66ac-9a92-4a83-ada8-9d12a0530f02)

**Comment by martincostello** [comment]
(FYI you can still see your user name in screenshots 1 and 4, if that's important to you to hide)

**Comment by rsankardayal** [comment]
@martincostello, thanks, it is, company policy.

**Comment by rsankardayal** [comment]
Hello, Can someone see if they can reproduce my issue with my steps above.

**Comment by rsankardayal** [comment]
Hi, 
I found a workaround,

To solve this issue, you need to add an exclusion path in "**Attack Surface Reduction**" in Windows "**Virus & threat protection**" for the path where your code is located.

There was a similar issue with VS 2017 many years ago, this was how I found the workaround.
