### ISSUE TITLE
Minimal API inconsistent results for 403 status code

### ISSUE THREAD

**Issue by bartlomiejgawel** [dotnet/aspnetcore#59391]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Imagine having the following code:
```csharp
app.MapGet("/with-direct-status-code", () => Results.StatusCode(403));
app.MapGet("/with-direct-result", () => Results.Forbid());
```

Sending `GET http://localhost:8080/with-direct-status-code` returns:
```http
HTTP/1.1 403 Forbidden
Content-Length: 0
Connection: close
Server: Kestrel
```

But sending `GET http://localhost:8080/with-direct-result` returns:
```http
HTTP/1.1 500 Internal Server Error
Connection: close
Content-Type: text/plain; charset=utf-8
Server: Kestrel

System.InvalidOperationException: Unable to find the required 'IAuthenticationService' service. Please add all the required services by calling 'IServiceCollection.AddAuthentication' in the application startup code.
   at Microsoft.AspNetCore.Authentication.AuthenticationHttpContextExtensions.GetAuthenticationService(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationHttpContextExtensions.ForbidAsync(HttpContext context, AuthenticationProperties properties)
   at Microsoft.AspNetCore.Http.HttpResults.ForbidHttpResult.ExecuteAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Http.RequestDelegateFactory.ExecuteResultWriteResponse(IResult result, HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

I did not find any remarks on this subject [here](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.results.forbid?view=aspnetcore-8.0#remarks).

Maybe it is not required to call `AddAuthentication` to simply return `403` status code because:
1. It works without any problems for other statuses:
```csharp
app.MapGet("/with-direct-status-code", () => Results.StatusCode(401));
app.MapGet("/with-direct-result", () => Results.Unauthorized());
```
2. `AddAuthentication` is not included by default in the [minimal API template](https://learn.microsoft.com/en-us/aspnet/core/tutorials/min-web-api?view=aspnetcore-8.0&tabs=visual-studio).
3. It may be more convenient to work with named results than with numbers. 🙂 

### Expected Behavior

Both requests should return `403` status code.

### Steps To Reproduce

1. Run the following code:
```csharp
var builder = WebApplication.CreateBuilder(args);
var app = builder.Build();

app.MapGet("/with-direct-status-code", () => Results.StatusCode(403));
app.MapGet("/with-direct-result", () => Results.Forbid());

app.Run();
```
2. Send `GET http://localhost:8080/with-direct-status-code` and `GET http://localhost:8080/with-direct-result` requests to compare.

### Exceptions (if any)

```csharp
System.InvalidOperationException: Unable to find the required 'IAuthenticationService' service. Please add all the required services by calling 'IServiceCollection.AddAuthentication' in the application startup code.
   at Microsoft.AspNetCore.Authentication.AuthenticationHttpContextExtensions.GetAuthenticationService(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationHttpContextExtensions.ForbidAsync(HttpContext context, AuthenticationProperties properties)
   at Microsoft.AspNetCore.Http.HttpResults.ForbidHttpResult.ExecuteAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Http.RequestDelegateFactory.ExecuteResultWriteResponse(IResult result, HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

### .NET Version

8.0

**Comment by oussamatecnique** [comment]
the problem that I see here is with the template could be missing the part code of adding a default authentication.
for the method Result.Forbid, its main purpose is to forbid based on an authenticated user on specific resource.
docs: [Forbid method documentaion](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.authenticationhttpcontextextensions.forbidasync?view=aspnetcore-8.0)

**Comment by mguinness** [comment]
I've just encountered a similar issue also with the ASP.NET Core Empty template.  The problem I have is when using `Results.Unauthorized()` it returns status code 200 :astonished:

This is problematic since I'm using the [auth_request](http://nginx.org/en/docs/http/ngx_http_auth_request_module.html#auth_request) feature in nginx and the only workaround is to use `Response.StatusCode = 401`.  Interestingly I also tried using `Results.StatusCode(401)`, but it had the same problem.

https://github.com/dotnet/aspnetcore/blob/8b77ff5251b9a90b9a937330bd27bfaf71b701f4/src/Http/Http.Results/src/Results.cs#L29-L31
