### ISSUE TITLE
.NET 9 breaks ShouldSerializeXXX methods in data model (NullReferenceException)

### ISSUE THREAD

**Issue by arisewanggithub** [dotnet/aspnetcore#59402]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

We are currently using .net 8 and we are upgrading to .net 9. But with the upgrade, our service can't start because some ShouldSerializeXXX methods throw NullReferenceException. e.g.
![Image](https://github.com/user-attachments/assets/8acdc83a-f019-42de-89de-34ffbb86eb39)

And from stacktrace, I can see the ShouldSerializeXXX methods are called from here in namespace Newtonsoft.Json.Serialization:
![Image](https://github.com/user-attachments/assets/79e32f45-62e4-4d8d-9cd5-3010f790f3f7)

Microsoft.AspNetCore.Mvc.NewtonsoftJson has already been upgraded to 9.0.0
This works fine in .net 8 but breaks in .net 9

### Expected Behavior

NullReferenceException should not be thrown when start the service

### .NET Version

9.0.101

**Comment by BrennanConroy** [comment]
What makes this a .NET or ASP.NET Core issue? The method you're pointing at is part of Newtonsoft.Json.
https://github.com/JamesNK/Newtonsoft.Json/blob/9317d71ac5f08c354060bad2cd9bfe6ed5856294/Src/Newtonsoft.Json/Serialization/DefaultContractResolver.cs#L1646

If you think it is an ASP.NET Core issue, please provide a minimal repro project.

**Comment by arisewanggithub** [comment]
[WebApiTest.zip](https://github.com/user-attachments/files/18086545/WebApiTest.zip)
I've created a minimum web service that can repro this. From the stack trace, I think the issue is triggered when NSwag OpenAPI documentation is generated on service startup. The same code works in .net 8 but not in .net 9.

**Comment by BrennanConroy** [comment]
Please provide the project as a github repro not a zip
https://github.com/dotnet/aspnetcore/blob/main/docs/repro.md#what-is-a-minimal-repro-project

**Comment by arisewanggithub** [comment]
OK, here is the github repo link: https://github.com/arisewanggithub/dotnetissue59402

**Comment by martincostello** [comment]
> From the stack trace, I think the issue is triggered when NSwag OpenAPI documentation is generated on service startup

Maybe it's an NSwag issue?

**Comment by BrennanConroy** [comment]
Yeah, this looks like an NSwag issue. Closing as I don't see anything from ASP.NET Core in the stack.

**Comment by arisewanggithub** [comment]
OK, I created a new issue on NSWag for this: https://github.com/RicoSuter/NSwag/issues/5065
