### ISSUE TITLE
The video tag does not autoplay when the source is mapped to a variable in a Blazor Server app .net 6.

### ISSUE THREAD

**Issue by vishwanathan3797** [dotnet/aspnetcore#59415]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

While using the source as a variable, the video does not autoplay. However, it works properly if the source is used directly.

### Expected Behavior

The video tag should autoplay properly whether the source is set using a variable or a direct path.

### Steps To Reproduce

You can replicate issue in simple .net6 balzor server app.

### Issue code:

```razor
<video id="videoPlayer" width="100%" height="100%" controls autoplay muted playsinline loop>
    <source src="@src" type="video/mp4">
</video>
@code {
    string src = "Videos/RPReplay_Final1732704033.mp4";
}
```

### working code:

```html
<video id="videoPlayer" width="100%" height="100%" controls autoplay muted playsinline loop>
    <source src="Videos/RPReplay_Final1732704033.mp4" type="video/mp4">
</video>
```

### .NET Version

6

**Comment by vishwanathan3797** [comment]
Hi Team, 

Issue occurs in the .net 8, Interactive server mode also. Could you please provide solution for this issue.

**Comment by capdiem** [comment]
Concatenating to form a MarkupString can solve this.

```razor
@((MarkupString)_markup)

@code {
    private string _src = "...";
    private string _markup = $"<video autoplay muted><source src="{_src}" ..></video>";
}
```
