### ISSUE TITLE
MapStaticAssets issue with images references only in specific build machine

### ISSUE THREAD

**Issue by Gambero81** [dotnet/aspnetcore#59418]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

I have a Blazor App (created in NET6 and migrated through NET7, NET8 and now NET9).

I have enabled the new feature of NET9 related to static assets using `app.MapStaticAssets()` and removing `app.UseStaticFiles()`.

All work great on my build machine, static resources references are converted as below:

`<link href="@Assets["fonts/roboto/roboto.css"]" rel="stylesheet">` -> `<link href="fonts/roboto/roboto.7nk4o7es2x.css" rel="stylesheet">`
`<script src="@Assets["JSInterop.js"]"></script>` -> `<script src="JSInterop.ebfu3oj3j4.js"></script>`
`<link id="css-theme" href="@Assets["css/app.theme.material.css"]" rel="stylesheet" />` -> `<link id="css-theme" href="css/app.theme.material.n4b8annf0v.css" rel="stylesheet" />`

the only problem are for images: on my build machine all work fine also for images and publishing the app images references are converted as below:

`<img src="@Assets["Images\myImage.png"]" />` -> `<img src="Images\myImage.ifv42okdf2.png" />`

**the issue is if build the application from my build server (another machine with same visual studio version 17.12.3)**

in this case, css and js assets are converted fine and work great BUT image references are NOT CONVERTED WELL and are not showing on the page, so:

`<img src="@Assets["Images\myImage.png"]" />` generate `<img src="Images\myImage.png" />` on the page and image does not load.

i can't understand where is the problem. Code is the same, Visual studio version is the same, Build process is the same (done via `MSBuild.exe`).

NOTE: If i restore `app.MapStaticAssets()`  with `app.UseStaticFiles()` all work great also for images.

Any help?

Thanks

### .NET Version

NET9

**Comment by Gambero81** [comment]
investigating the problem, i reach this point:

in the project `wwwroot` there are no "Images" folders at compile time but **we copy this folder from another project location on pre-build event**.

in fact if i reference an image directly in the wwwroot as below:

`<img src="@Assets["myImage.png"]" />` 

it render correctly as:

`<img src="myImage.ifv42okdf2.png" />`

so the question is:

**How and When is the code analyzed to handle the Assets references?**

on pre-build event the project folder `Theme\Images` is copied inside wwwroot, so BEFORE build the project wwwroot result as:
`wwwroot\Images`

Thanks

**Comment by javiercn** [comment]
@Gambero81 thanks for contacting us.

You need to hook your target into `PrepareForBuild`
```xml
<PropertyGroup>
<PrepareForBuildDependsOn>
  CopyImages;$(PrepareForBuildDependsOn)
</PrepareForBuildDependsOn>
</PropertyGroup>
```
