### ISSUE TITLE
Setup unhandled exception handlers in hosting that log errors

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspnetcore#5941]
Handle `TaskScheduler.UnobservedTaskException` and `AppDomain.CurrentDomain.UnhandledException` and log errors to the logger. Today application code needs to manually hook and add these. These are well know system events that our host should just route to the logger.

**Comment by Kahbazi** [comment]
Do you take PR for this?

**Comment by VAllens** [comment]
Does it have any development?

**Comment by davidfowl** [comment]
No, it doesn't.

**Comment by davidfowl** [comment]
It might be a bit late for this. This can also be done manually by user code. Also this would be a generic host feature.
