### ISSUE TITLE
When adding blazor scaffolding AddDBContext overwrites AddDBContextFactory and so cause app not to build

### ISSUE THREAD

**Issue by coderdnewbie** [dotnet/aspnetcore#59423]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

I created an interactive Server Blazor Web app with Identity. 

The program.cs correctly had:

builder.Services.AddDbContextFactory<ApplicationDbContext>(options =>
    options.UseSqlServer(connectionString));

I then added the movie.cs example from Dan Roth using Blazor scaffolding. The program.cs got overwritten to 

builder.Services.AddDbContext<ApplicationDbContext>(options =>
    options.UseSqlServer(connectionString));

This caused the following error:

An unhandled exception occurred while processing the request.

InvalidOperationException: Cannot provide a value for property 'DbFactory' on type 'BlazorAppMovieTest.Components.Pages.MoviePages.Index'. There is no registered service of type 'Microsoft.EntityFrameworkCore.IDbContextFactory`1[BlazorAppMovieTest.Data.ApplicationDbContext]'.

To fix this issue, I had to manually change AddDbContext back to AddDbContextFactory, and then it worked as expected.

### Expected Behavior

Using Blazor CRUD scaffolding does not break the application

### Steps To Reproduce

I created an interactive Server Blazor Web app with Identity. 

The program.cs correctly had:

builder.Services.AddDbContextFactory<ApplicationDbContext>(options =>
    options.UseSqlServer(connectionString));

I then added the movie.cs example from Dan Roth using Blazor scaffolding. The program.cs got overwritten to 

builder.Services.AddDbContext<ApplicationDbContext>(options =>
    options.UseSqlServer(connectionString));

This caused the following error:

An unhandled exception occurred while processing the request.

InvalidOperationException: Cannot provide a value for property 'DbFactory' on type 'BlazorAppMovieTest.Components.Pages.MoviePages.Index'. There is no registered service of type 'Microsoft.EntityFrameworkCore.IDbContextFactory`1[BlazorAppMovieTest.Data.ApplicationDbContext]'.

To fix this issue, I had to manually change AddDbContext back to AddDbContextFactory, and then it worked as expected.

### Exceptions (if any)

An unhandled exception occurred while processing the request.

InvalidOperationException: Cannot provide a value for property 'DbFactory' on type 'BlazorAppMovieTest.Components.Pages.MoviePages.Index'. There is no registered service of type 'Microsoft.EntityFrameworkCore.IDbContextFactory`1[BlazorAppMovieTest.Data.ApplicationDbContext]'.

### .NET Version

dotnet 9.0

**Comment by coderdnewbie** [comment]
I will try to recreate this again, it is doing AddDbContext everywhere now

**Comment by juliomartinezcarrasco** [comment]
I had same issue and same solution already explained works.

**Comment by scearces** [comment]
I just encountered the same issue, Same solution, replace builder.Services.AddDbContext with builder.Services.AddDbContextFactory in Progran.cs in a Blazor app with Identity.
Visual Studio Version 17.13.6
