### ISSUE TITLE
FriendlyName Property for Setting Human Readable Application Name

### ISSUE THREAD

**Issue by rcollette** [dotnet/aspnetcore#5943]
I'm creating this issue to more formally track at a least a passing mention
https://github.com/aspnet/Hosting/pull/1180#issuecomment-323616208
https://github.com/aspnet/Hosting/pull/1180#issuecomment-323617999

that this might be provided in the V3 roadmap.

I was trying to set the application name to be picked up by Dynatrace application monitoring.
https://github.com/aspnet/Hosting/issues/1572

But soon discovered that the documentation
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/web-host?view=aspnetcore-2.1#application-key-name

(at that time) did not accurately reflect that the property specifies the application entry point assembly file name.

My Java/Spring application name via the spring.application.name application property, are named like "MyProduct-TheService" but without setting the application name, the dot net service shows up as "Org.MyProduct.TheService.dll".   The result is that my dotnet micro-services are not grouped with my other product micro-services.

Essentially the proposal is to provide a meta data property that has no behavior.

**Comment by davidfowl** [comment]
We need a new property to make this possible which will likely only work on .NET 6 based scenarios (if we do this). I'm closing this for now. If you feel strongly about being able to specify a name, you can propose an API https://github.com/dotnet/runtime (hopefully a non breaking one).
