### ISSUE TITLE
OpenApi doc is not generated at build time

### ISSUE THREAD

**Issue by azurecorner** [dotnet/aspnetcore#59434]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

`<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>6abc9799-c0eb-443b-b8a6-8cd79acc10c4</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

	<PropertyGroup>
		<OpenApiGenerateDocuments>true</OpenApiGenerateDocuments>
		<OpenApiDocumentsDirectory>$(MSBuildProjectDirectory)</OpenApiDocumentsDirectory>
	</PropertyGroup>

	<ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.ApiDescription.Server" Version="9.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
  </ItemGroup>

</Project>
`

`var builder = WebApplication.CreateBuilder(args);

// Add services to the container.

builder.Services.AddControllers();
// Learn more about configuring OpenAPI at https://aka.ms/aspnet/openapi
builder.Services.AddOpenApi();

var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.MapOpenApi();
}

app.UseHttpsRedirection();

app.UseAuthorization();

app.MapControllers();

app.Run();
`

### Expected Behavior

 LogCorner.EduSync.Speech.Presentation.json with openapi content generated at  bin\Debug\net9.0

### Steps To Reproduce

I use visual studio version 17.12.2 with dotnet 9

Microsoft Visual Studio Enterprise 2022
Version 17.12.2
VisualStudio.17.Release/17.12.3+35527.113
Microsoft .NET Framework
Version 4.8.09037

### .NET Version

9.0.100

**Comment by martincostello** [comment]
`$(MSBuildProjectDirectory)` would evaluate to the directory containing your `.csproj` file, not `bin\$(Configuration)\$(TargetFramework)`.

Are you sure it's not being generated, and isn't just instead somewhere you're not expecting it to be.

See also #59334.

**Comment by azurecorner** [comment]
> `$(MSBuildProjectDirectory)` would evaluate to the directory containing your `.csproj` file, not `bin\$(Configuration)\$(TargetFramework)`.
> 
> Are you sure it's not being generated, and isn't just instead somewhere you're not expecting it to be?
> 
> See also [#59334](https://github.com/dotnet/aspnetcore/issues/59334).

Hi @martincostello , it is generated in root folder not in bin/.....

`{
  "openapi": "3.0.1",
  "info": {
    "title": "LogCorner.EduSync.Speech.Presentation | v1",
    "version": "1.0.0"
  },
  "paths": {
    "/WeatherForecast": {
      "get": {
        "tags": [
          "WeatherForecast"
        ],
        "operationId": "GetWeatherForecast",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/WeatherForecast"
                  }
                }
              },
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/WeatherForecast"
                  }
                }
              },
              "text/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/WeatherForecast"
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "WeatherForecast": {
        "type": "object",
        "properties": {
          "date": {
            "type": "string",
            "format": "date"
          },
          "temperatureC": {
            "type": "integer",
            "format": "int32"
          },
          "temperatureF": {
            "type": "integer",
            "format": "int32"
          },
          "summary": {
            "type": "string",
            "nullable": true
          }
        }
      }
    }
  },
  "tags": [
    {
      "name": "WeatherForecast"
    }
  ]
}`

**Comment by martincostello** [comment]
> $(MSBuildProjectDirectory) would evaluate to the directory containing your .csproj file

The file is being created exactly where you've asked it to be placed.

If you want it in the location that you've put in the expected behaviour then you need to do update the value of `OpenApiDocumentsDirectory` to the desired location.

**Comment by azurecorner** [comment]
> > $(MSBuildProjectDirectory) would evaluate to the directory containing your .csproj file
> 
> The file is being created exactly where you've asked it to be placed.
> 
> If you want it in the location that you've put in the expected behaviour then you need to do update the value of `OpenApiDocumentsDirectory` to the desired location.

It is not generating openapi doc if i have <PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0" /> in my project. 

I have to remove  Swashbuckle.AspNetCore package to make it working (<PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0" />.
The package Swashbuckle.AspNetCore  should not be present but I forgotten to remove it

**Comment by martincostello** [comment]
I can't find it, but that's another known issue. If more than one implementation of `IDocumentProvider` is found in assemblies used by the application, things don't behave correctly as only the first one is used, and the ordering isn't determinstic:

https://github.com/dotnet/aspnetcore/blob/89ef7bbd1ec1b74e51a9dbd2e9b4e0647a902ff9/src/Tools/GetDocumentInsider/src/Commands/GetDocumentCommandWorker.cs#L193-L207

It's probably finding the Swashbuckle one, and then because you're not actually using Swashbuckle, there's nothing to generate.

**Comment by tyler-boyd** [comment]
Honestly I think that should be made more clear somehow; there's no errors, and the runtime openapi generation works fine, yet the build time generation just silently does nothing if you have Swashbuckle installed (which is common when you're migrating from swashbuckle to this new approach)

**Comment by TatianaDolinski** [comment]
Hi, I got to here because the json was not generated. Here is a solution that does actually work -  https://medium.com/@alechka/generating-typescript-client-from-net-webapi-with-openapi-and-orval-855db0486d93
