### ISSUE TITLE
Blazor proper collapsible sidebar suboption indentation

### ISSUE THREAD

**Issue by yarmoliq** [dotnet/aspnetcore#59449]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Currently there is no indentation for suboptions when using collapsible sidebar. There is an [example](https://demos.blazorbootstrap.com/sidebar) of adding indentation for child options that uses padding on the left of the options. However, this results in an indentation when sidebar is collapsed:
![Image](https://github.com/user-attachments/assets/0ca988dd-fe90-48af-91c3-e3c695365b32)

So you either have suboptions without indentation or a little ugly thingy :) or try to fix it by implementing a bicycle.

### Describe the solution you'd like

I think the easiest and straightforward one is to just collapse category. However, I see other viable options:
1) no indentation for child options in collapsed view
2) small visible indentation in collapsed view, which results in a little bit wider collapsed sidebar (there has to be a tradeoff, right?)

**Comment by javiercn** [comment]
@yarmoliq thanks for contacting us.

This repo is for the core framework, and we don't handle third-party packages like the one you seem to be using. We recommend you file the issue directly in the repo for that package.
