### ISSUE TITLE
What is the right way to do GDPR cookie consent in Blazor Server?

### ISSUE THREAD

**Issue by pablosantosluaces** [dotnet/aspnetcore#59457]
Hi,

I'm trying to implement proper GDPR cookie consent in a Blazor Server app.

I tried to follow this: https://learn.microsoft.com/en-us/aspnet/core/security/gdpr?view=aspnetcore-9.0 but it doesn't apply to Blazor server.

So I followed this other post from the folks at SyncFusion: https://www.syncfusion.com/faq/blazor/tips-and-tricks/how-do-i-set-consent-cookies-in-blazor

But it uses IHttpContextAccessor and @javiercn said clearly here https://github.com/dotnet/aspnetcore/issues/18183 that this is not reliable because it is transport specific.

And I'm seeing it because my server is setup on Azure behind APIM and websockets are not working, just long polling, so IHttpContextAccessor  doesn't work.

I guess the good way to solve it is to add somehow the right Features.Get<ITrackingConsentFeature> somehow as a claim or something, but I wonder if there is some documentation on how to do this correctly.

Thanks.

**Comment by pablosantosluaces** [comment]
What I did finally was to capture the required stuff in the OnInitialized of my Layout.razor:

```
@code {
    [CascadingParameter]
    public HttpContext _HttpContext { get; set; }
    string _CookieString;
    bool _ShowCookiesBanner;

    protected override void OnInitialized()
    {
        var httpContext = _HttpContext;

        if (httpContext == null)
        {
            return;
        }

        var trackingConsentFeature = httpContext.Features.Get<ITrackingConsentFeature>();
        _ShowCookiesBanner = !trackingConsentFeature?.CanTrack ?? false;
        _CookieString = trackingConsentFeature?.CreateConsentCookie();
    }
}
```

The pass it to my CookieConsent component like this, so avoiding the component to use any HttpContext

<ConsentCookie CookieString="@_CookieString" ShowBanner="@_ShowCookiesBanner"/>

It worked even that no websockets but long polling is used

**Comment by javiercn** [comment]
@pablosantosluaces thanks for contacting us.

There are a couple of ways to do this:
* You can pass in the value to any root component that you render as a parameter to the component.
* You can also capture the value during prerendering, save it using persistent component state, and retrieve it on the first interactive render of the Blazor Server application.
  * https://learn.microsoft.com/en-us/aspnet/core/blazor/components/prerender?view=aspnetcore-9.0#persist-prerendered-state
