### ISSUE TITLE
I upgraded to 17.12.3 and got a weird error about “DiscoverPrecompressedAssets” task failed unexpectedly. Did not have this issue before upgrading.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#59476]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/I-upgraded-to-17123-and-got-a-weird-er/10805103)._

---
[severity:I'm unable to use this version] [regression] [worked-in:17.12.3]
The "DiscoverPrecompressedAssets" task failed unexpectedly.
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Microsoft.AspNetCore.StaticWebAssets.Tasks.DiscoverPrecompressedAssets.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.&lt;ExecuteInstantiatedTask&gt;d__26.MoveNext()

Got this error in my Microsoft.NET.Sdk.StaticWebAssets.Compression.targets file. I do not know how to fix and will be reverting to older version

---
#### Emily Gabbard on 12/3/2024, 10:54 PM: 

(private comment, text removed)
#### Feedback Bot on 12/4/2024, 06:34 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Mike Rahel on 12/9/2024, 11:54 PM: 

<p>I am also experiencing this once I have upgraded to 17.12.3. Please let us know how to resolve. Thanks!</p>

**Comment by wadebaird** [comment]
I am hitting this same issue, I can't provide a repro as it's occurring in my test project, which I can't share the code, and due to the vague error, have no clue what the issue is to give a repro on.

**Comment by wadebaird** [comment]
Would the project file contents be helpful? I'm not sure what the source of this error is.

**Comment by davinfifield** [comment]
Is there a workaround for this? Seems to be blocking me from building a brand new AspNet Core project.

**Comment by davinfifield** [comment]
I tried falling back to .NET Framework 8, thinking that might solve the problem, but same issue still exists.

**Comment by RyouichirouNakayama** [comment]
check the assembly name duplicated

**Comment by ShortRoundDev** [comment]
Since this still hasn't been fixed, here's my workaround:

```posh
Remove-Item .\bin -Recurse -Force;
Remove-Item .\obj -Recurse -Force;
dotnet build;
```

**Comment by LuckyCloverFarm** [comment]
> Since this still hasn't been fixed, here's my workaround:
> 
> Remove-Item .\bin -Recurse -Force;
> Remove-Item .\obj -Recurse -Force;
> dotnet build;

This workaround worked for me as well.

**Comment by JamesFieldist** [comment]
This isn't a fix. Not sure why this is closed.

**Comment by Hasan0925** [comment]
Removing bin and obj folders worked for me too.

**Comment by SMERKY** [comment]
Removing bin and obj folders worked for me, but will only build in terminal. Building in VSCode or VSPro 22 still comes up with the error

**Comment by xenophilios** [comment]
I get this error when I copy an ASP.NET 9 application and try to compile the copy. The error doesn't occur with the original. I last copied an application in mid-April and did not have this problem then.

**Comment by nguyen-gia-khoi** [comment]
Adding a global.json worked for me. I got the same error when my PC suddenly shut down, but adding the global.json fixed it.

**Comment by daltinkurt** [comment]
> Adding a global.json worked for me. I got the same error when my PC suddenly shut down, but adding the global.json fixed it.

```
{
  "sdk": {
    "version": "8.0.17",
    "rollForward": "latestMinor",
    "allowPrerelease": false
  }
}
```
like this?

**Comment by nguyen-gia-khoi** [comment]
Yes!!

**Comment by iskandersierra** [comment]
`dotnet clean` worked for me too!
