### ISSUE TITLE
Serialization for Blazor 10 app state store/restore capability

### ISSUE THREAD

**Issue by rockfordlhotka** [dotnet/aspnetcore#59489]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the solution you'd like

As you look at .NET 10 and the ability to store and restore application state if the circuit goes away, please keep in mind that not all data can be serialized via JSON.

Or to be more specific, _you_ can serialize everything via JSON, as long as _we_ have a hook to serialize _our_ data into a `byte[]` or `string` that _you_ can then put into the JSON.

In my case, I'm maintaining https://github.com/marimerllc/csla, which has its own serialization tooling. It is easy enough to convert CSLA state into a byte stream or even a string, but we'd need the Blazor API to allow us (or the app developer) to have the opportunity to use our serializer _first_ to get the app state into a form where JSON is an option.

**Comment by javiercn** [comment]
@rockfordlhotka thanks for contacting us.

> Or to be more specific, you can serialize everything via JSON, as long as we have a hook to serialize our data into a byte[] or string that you can then put into the JSON.

We already have such hooks, as long as you give us a string, we will persist it (using persistent component state). We might include APIs that allow you to do your own serialization into a buffer and restore from it directly, but the ability to serialize your state into a string and pass it on to us is already there.

**Comment by javiercn** [comment]
We will be using https://github.com/dotnet/aspnetcore/issues/26794 to track changes.

**Comment by rockfordlhotka** [comment]
> [@rockfordlhotka](https://github.com/rockfordlhotka) thanks for contacting us.
> 
> > Or to be more specific, you can serialize everything via JSON, as long as we have a hook to serialize our data into a byte[] or string that you can then put into the JSON.
> 
> We already have such hooks, as long as you give us a string, we will persist it (using persistent component state). We might include APIs that allow you to do your own serialization into a buffer and restore from it directly, but the ability to serialize your state into a string and pass it on to us is already there.

Excellent, thank you @javiercn 

I was listening to Dan's recent interview where he was talking about this upcoming .NET 10 feature, and just wanted to make sure this was considered. Sounds like that feature is already implemented, which is exciting!
