### ISSUE TITLE
OpenAPI generation leads to invalid openapi.json file

### ISSUE THREAD

**Issue by tyler-boyd** [dotnet/aspnetcore#59496]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Consider the following minimal example:

```cs
app.MapGet("/test", () =>
{
    return "hello"; // not important, we only care about the openapi spec generation
}).Produces<Post>();
app.Run();

public class LinkDetails
{
    public string Name { get; set; }
    public string Url { get; set; }
}

public class Post
{
    public List<LinkDetails> Links1 { get; set; } = [];
    public List<LinkDetails> Links2 { get; set; } = [];
}
```

This leads to the following openapi.json (relevant section):

```json
      "Post": {
        "type": "object",
        "properties": {
          "links1": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/LinkDetails"
            }
          },
          "links2": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/#/properties/links1/items"
            }
          }
        }
      }
```

Note that links1 looks correct, while links2 is different and leads to an error when viewing it in swagger UI ("Semantic error at components.schemas.Post.properties.links2.items.$ref - $ref values must be RFC3986-compliant percent-encoded URIs")

Removing links1 fixes the ref for links2, so it appears that when you have two properties with the same type, the openapi generation is being smart and encoding a ref to the first property, however swagger UI doesn't seem to support it, at least in this scenario.

### Expected Behavior

I would expect .NET 9's openapi generation generates JSON files that are valid according to swagger UI.

### Steps To Reproduce

I included most of a code example above. I think the behaviour here is probably intentional, but seems incompatible with swagger UI, so I'm assuming a complete repro repo isn't needed. If it would be helpful, let me know and I can create one.

### .NET Version

9.0.101

### Anything else?

Brand new `dotnet new webapi` from .net 9.0.101; assuming `dotnet --info` isn't relevant here.

edit: this issue also seems to break the NSwagTypeScript code generator, with basically the same error message `System.InvalidOperationException: Could not resolve the path '#/components/schemas/#/properties/links/items'.`

**Comment by captainsafia** [comment]
@tyler-boyd Thanks for filing this issue!

I'm going to dupe this to https://github.com/dotnet/aspnetcore/issues/58915 and close it since they relate to the same issue. I'll follow-up on that one with the notes and investigation.
