### ISSUE TITLE
[Blazor] JS stopPropagation would prevent the `@onclick` event of blazor

### ISSUE THREAD

**Issue by capdiem** [dotnet/aspnetcore#59499]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Taking the `button` as an example, if a click event is registered via JavaScript and `e.stopPropagation` is used within that event, then the `@onclick` in Blazor will not be triggered. 

I tested this on both .NET 7 and .NET 9.

```razor
<MyButton OnClick="@OnClick">My Button</MyButton>

@code {
    // this method would not be invoked
    private void OnClick(MouseEventArgs e)
    {
        Console.WriteLine("MyButton clicked");
    }
}
```

```razor
@inject IJSRuntime JSRuntime

<button @onclick="OnClick" @ref="@_btn">@ChildContent</button>

@code {
    [Parameter] public EventCallback<MouseEventArgs> OnClick { get; set; }
    [Parameter] public RenderFragment? ChildContent { get; set; }
    private ElementReference _btn;

    protected override Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender)
        {
            JSRuntime.InvokeVoidAsync("stopPropagation", _btn);
        }
        return base.OnAfterRenderAsync(firstRender);
    }
}
```

```html
<script>
    window.stopPropagation = function (el) {
        el.addEventListener('click', function (e) {
            e.stopPropagation();
        });
    }
</script>
```

### Expected Behavior

The button's own event should trigger normally, while the parent element's event will not be triggered.

**Comment by javiercn** [comment]
@capdiem thanks for contacting us.

What are you trying to achieve? 

The behavior that you are seeing is by design. Blazor uses event delegation so if you setup an event handler in JS and stop propagation of the event, the Blazor JS script doesn't even get to see the event and is not able to send it to the .NET Code.

**Comment by capdiem** [comment]
@javiercn Thank you for your response. But are you sure it stops the events of the element itself and not the events of the parent elements?

I have a Menu component with `ActivatorContent` and `ChildContent` slots. The elements in `ActivatorContent` (like a `button`) can automatically trigger whether to show `ChildContent` without needing an additional variable to maintain that state. However, the `button`'s own `@onclick` event can't be triggered because we've prevented event propagation in the trigger's JavaScript.

```razor
<MMenu>
    <ActivatorContent>
        <button @onclick="@(() => "click event not work")"
                @attributes="@context.Attrs">origin button</button>
    </ActivatorContent>
    <ChildContent>
        Content to show
    </ChildContent>
</MMenu>
```

**Comment by javiercn** [comment]
@capdiem yes, because Blazor registers the event listener in the document, so when you prevent the event via JS interop, it doesn't bubble to the handler that Blazor registered and doesn't get sent to the .NET side.

**Comment by capdiem** [comment]
@javiercn I got it, thanks.
