### ISSUE TITLE
Blazor WASM initial download timeout/retry

### ISSUE THREAD

**Issue by Schoof-T** [dotnet/aspnetcore#59522]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

When downloading the initial Blazor WASM files on slow/unstable connections we get timeouts/disconnects of the package downloads. We notice that the packages retry to download X amount of times, but after X times it just stops, with a bunch of errors in the console.

We then have to refresh the page, and the download continues. 

### Expected Behavior

We would like that this process retries forever, until the download is completed.

### Steps To Reproduce

- Set up a normal Blazor WASM (Hosted) website with some libraries, until the download size is about 5.5MB
- Simulate a bad connection (something like: 256kbit down 128kbit up 600ms latency with variance until 2000ms)
- In your browser open developer tools on the network tab
- Navigate to the Blazor WASM website and observe what is happening

### Exceptions (if any)

In the console you will eventually get errors like the following:

```
       GET /_framework/Telerik.Documents.SpreadsheetStreaming.wasm net::ERR_CONNECTION_CLOSED
S @ dotnet.js:3
(anonymous) @ dotnet.js:3
(anonymous) @ dotnet.js:3
await in (anonymous)
oe @ dotnet.js:3
(anonymous) @ dotnet.js:3
Y @ dotnet.js:3
G @ dotnet.js:3
t @ dotnet.js:3
Q @ dotnet.js:3
await in Q
(anonymous) @ dotnet.js:3
setTimeout
(anonymous) @ dotnet.js:3
await in (anonymous)
Ne @ dotnet.js:3
await in Ne
create @ dotnet.js:3
(anonymous) @ blazor.webassembly.js:1
await in (anonymous)
load @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
await in (anonymous)
pn @ blazor.webassembly.js:1
hn @ blazor.webassembly.js:1
mn @ blazor.webassembly.js:1
Cn @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
dotnet.js:3 

```
```
       Uncaught (in promise) TypeError: Failed to fetch
    at Object.S [as fetch_like] (dotnet.js:3:4466)
    at dotnet.js:3:11710
    at dotnet.js:3:11726
S @ dotnet.js:3
(anonymous) @ dotnet.js:3
(anonymous) @ dotnet.js:3
Promise.then
oe @ dotnet.js:3
(anonymous) @ dotnet.js:3
Y @ dotnet.js:3
G @ dotnet.js:3
t @ dotnet.js:3
Q @ dotnet.js:3
await in Q
(anonymous) @ dotnet.js:3
setTimeout
(anonymous) @ dotnet.js:3
await in (anonymous)
Ne @ dotnet.js:3
await in Ne
create @ dotnet.js:3
(anonymous) @ blazor.webassembly.js:1
await in (anonymous)
load @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
await in (anonymous)
pn @ blazor.webassembly.js:1
hn @ blazor.webassembly.js:1
mn @ blazor.webassembly.js:1
Cn @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
dotnet.js:3 
        
```

```
       GET /_framework/System.Runtime.Extensions.wasm net::ERR_HTTP2_PROTOCOL_ERROR
S @ dotnet.js:3
(anonymous) @ dotnet.js:3
(anonymous) @ dotnet.js:3
await in (anonymous)
oe @ dotnet.js:3
(anonymous) @ dotnet.js:3
Y @ dotnet.js:3
G @ dotnet.js:3
await in G
t @ dotnet.js:3
Q @ dotnet.js:3
await in Q
(anonymous) @ dotnet.js:3
setTimeout
(anonymous) @ dotnet.js:3
await in (anonymous)
Ne @ dotnet.js:3
await in Ne
create @ dotnet.js:3
(anonymous) @ blazor.webassembly.js:1
await in (anonymous)
load @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
await in (anonymous)
pn @ blazor.webassembly.js:1
hn @ blazor.webassembly.js:1
mn @ blazor.webassembly.js:1
Cn @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
dotnet.js:3 
```

### .NET Version

.NET 8 (Upgraded from the .NET 7 WASM Hosted template, so not using the Web App)

### Anything else?

We are quite happily using the Blazor WASM technology on bad connections. Once the WASM files have been downloaded everything works smooth, and our users can even work offline.

We would just like to improve the initial download scenario on bad connections, so that it is more stable.

**Comment by javiercn** [comment]
@Schoof-T thanks for contacting us.

The runtime side has some logic to retry downloads, but other than that, not all files can be retried. In this case, Blazor works like any other framework, if a file fails to load, you need to refresh the page.

You can control the way files load using your own resource loader. See https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/startup?view=aspnetcore-9.0#load-client-side-boot-resources for details.
