### ISSUE TITLE
Getting Error In The Time Of Build Application

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#59549]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Getting-Error-In-The-Time-Of-Build-Appli/10814981)._

---
When I build my solutions I have similar message like:

System.InvalidOperationException: No file exists for the asset at either location ‘wwwroot\css\portal.min.css’ or ‘wwwroot\css\portal.min.css’.
at Microsoft.AspNetCore.StaticWebAssets.Tasks.StaticWebAsset.ComputeFingerprintAndIntegrity(String identity, String originalItemSpec)
at Microsoft.AspNetCore.StaticWebAssets.Tasks.DefineStaticWebAssets.Execute()

If I just Build the solution, then it builds.

---
#### Feedback Bot on 12/17/2024, 11:45 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

**Comment by MackinnonBuck** [comment]
Thanks for reaching out. Could you please provide us with a minimal repro project that demonstrates the bug, hosted as a public GitHub repository? This will help us investigate the issue further.
