### ISSUE TITLE
Missing 'value' attribute on native <input> tag when using 'InputDate' component

### ISSUE THREAD

**Issue by Appli4Ever** [dotnet/aspnetcore#59541]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

I am using the [Microsoft.AspNetCore.Components.Forms.InputDate](https://github.com/dotnet/aspnetcore/blob/main/src/Components/Web/src/Forms/InputDate.cs) component in Blazor WASM.

I noticed the value attribute missing, after checking with DevTools:

```html
<input type="date" class="modified valid" _bl_2="">
```

After checking the InputDate source Code I noticed, that the value attribute is being set:
```CSharp
 protected override void BuildRenderTree(RenderTreeBuilder builder)
 {
     builder.OpenElement(0, "input");
     builder.AddMultipleAttributes(1, AdditionalAttributes);
     builder.AddAttribute(2, "type", _typeAttributeValue);
     builder.AddAttributeIfNotNullOrEmpty(3, "name", NameAttributeValue);
     builder.AddAttribute(4, "class", CssClass);

     builder.AddAttribute(5, "value", CurrentValueAsString);

     builder.AddAttribute(6, "onchange", EventCallback.Factory.CreateBinder<string?>(this, __value => CurrentValueAsString = __value, CurrentValueAsString));
     builder.SetUpdatesAttributeName("value");
     builder.AddElementReferenceCapture(7, __inputReference => Element = __inputReference);
     builder.CloseElement();
 }
```

So why is it not present on the <input> tag?

Getting the value with JavaScript:

```js
document.getElementById('Geburtsdatum').value --> '2024-12-18'

document.getElementById('Geburtsdatum').getAttribute('value') --> null
```

### Expected Behavior

'value' attribute is set with the current value:

```html
<input type="date" class="modified valid" value="2024-18-12">
```

### Steps To Reproduce

1. Use the InputDate component (does not matter if DateOnly or DateTime)
```
<InputDate @bind-Value="Model.Geburtsdatum"></InputDate>
```
2. Inspect the <input> tag with DevTools of your browser
3. See that value="2024-18-12" is missing.

### .NET Version

9.0.0

### Anything else?

See InputDate: [DateInput GitHub Source Code](https://github.com/dotnet/aspnetcore/blob/main/src/Components/Web/src/Forms/InputDate.cs) Line 91.

**Comment by Appli4Ever** [comment]
So this article: [ASP.NET Core Blazor data binding](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/data-binding?view=aspnetcore-9.0) says:

_The text box is updated in the UI only when the component is rendered, not in response to changing the field's or property's value. Since components render themselves after event handler code executes, field and property updates are usually reflected in the UI immediately after an event handler is triggered._

I suspect therefor that this is intended behavior. 

Other than using:
```html
  <input value="@InputValue" @onchange="@((ChangeEventArgs __e) =>
            InputValue = __e?.Value?.ToString())" />
```
which is not recommended, is there another way to ensure that the value attribute is set after changing the value?

**Comment by javiercn** [comment]
@Appli4Ever thanks for contacting us.

We don't generate an attribute if the attribute value is null or empty during prerendering, and if you aren't using prerendering, the component doesn't set the attribute it works with the underlying property.
