### ISSUE TITLE
MapStaticAssets issue on .net 9 Asp.Net Core Blazor Auto Mode

### ISSUE THREAD

**Issue by nammadhu** [dotnet/aspnetcore#59565]
### Is there an existing issue for this?

- [x] #59566

### Describe the bug

MapStaticAssets issue on .net 9 Asp.Net Core Blazor Auto Mode .
<img width="886" alt="Image" src="https://github.com/user-attachments/assets/9f4804d5-fedd-49bd-8df5-e37ad8116ba3" />

My Asp.Net core latest all package with .net 9 all working fine. i tried to enable MapStaticAssets but getting issues like. first time page loads then second time onwards issue like above. With this page doesnt display anything and just blank. on f12 above issue
Mine is Blazor auto mode.

### Expected Behavior

Should work normally without any issue.

### Steps To Reproduce

all works properly.

### Exceptions (if any)

blazor.web.js:1 ph: One or more errors occurred. ('<' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.)
    at uu (https://localhost:7116/_framework/dotnet.runtime.o8gq1i8bk6.js:3:16298)
    at gd.resolve_or_reject (https://localhost:7116/_framework/dotnet.runtime.o8gq1i8bk6.js:3:15857)
    at https://localhost:7116/_framework/dotnet.runtime.o8gq1i8bk6.js:3:189869
    at https://localhost:7116/_framework/dotnet.runtime.o8gq1i8bk6.js:3:189931
    at fy (https://localhost:7116/_framework/dotnet.runtime.o8gq1i8bk6.js:3:21324)
    at lb (https://localhost:7116/_framework/dotnet.runtime.o8gq1i8bk6.js:3:189525)
    at wasm://wasm/00b59d1a:wasm-function[287]:0x1f0b5
    at wasm://wasm/00b59d1a:wasm-function[218]:0x1c7c3
    at wasm://wasm/00b59d1a:wasm-function[209]:0xea10
    at wasm://wasm/00b59d1a:wasm-function[280]:0x1eb99
<img width="763" alt="Image" src="https://github.com/user-attachments/assets/e88f6bab-bb41-4a7f-aa89-39c47a25bb0f" />

### .NET Version

9.0

**Comment by javiercn** [comment]
@nammadhu thanks for contacting us.

Does the error go away if you rebuild the app/solution?

**Comment by nammadhu** [comment]
no, instead i had to clear everything and run then it works for while only.
so for timebeing am going with below way of mix up,eventhough not ideal.
<img width="809" alt="Image" src="https://github.com/user-attachments/assets/26b96284-d02a-4cc6-a4f3-c5c0aab552ee" />

**Comment by javiercn** [comment]
@nammadhu thanks for the additional details.

I believe this is an issue with the up-to-date check in VS. use `<AccelerateBuildsInVisualStudio>true</AccelerateBuildsInVisualStudio>` in your project (I believe the Host project, but try the client if not) and it should go away.
