### ISSUE TITLE
audio file gives 416 Error when broser tries to download it in .net 9 (works in .net 8)

### ISSUE THREAD

**Issue by gregoryagu** [dotnet/aspnetcore#59583]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

In a .net 9 Blazor Server App, this code results in a 416 error in the browser:
```
<audio controls="controls">
    <source src="/soundtest.mp3" type="audio/mpeg" />
</audio>

```
To reproduce, create a .net 9 Blazor Server App, add an audio file, and then add an audio element.

![Image](https://github.com/user-attachments/assets/3fbabed7-c7e7-44fc-ba3d-f060710af32a)

The file will play when served directly from the URL, so the file is in fact there on the server and available.

I have tried this in .net 8 and it works perfectly.

### Expected Behavior

Audio file is played.

### Steps To Reproduce

See above.

### Exceptions (if any)

Audio should play.

### .NET Version

9

### Anything else?

Issue occurs in Visual Studio Dev , as well as published to Azure.

**Comment by javiercn** [comment]
@gregoryagu thanks for contacting us.

We have a PR https://github.com/dotnet/aspnetcore/pull/59325 to backport the fix we did on main in a future release
