### ISSUE TITLE
HttpClient.GetFromJsonAsync<T> does not handle 204 returned by ASP.NET Core.

### ISSUE THREAD

**Issue by airwedge1** [dotnet/aspnetcore#59670]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

This is in reference to [https://github.com/dotnet/aspnetcore/issues/43608](url)  It seems bizarre that GetFromJsonAsync does not handle this use case.  I have to to instead use GetAsync, check myself for HttpStatusCode.NoContent and then finally do response.Content.ReadFromJsonAsync.  Lose 5 minutes of time every time it happens trying to figure what is going on.

### .NET Version

8.0.404

**Comment by martincostello** [comment]
What would you expect to be returned given that HTTP 204 is "No content"? Null? A well-behaved application shouldn't return anything back that you could deserialize to JSON for 204.

The extension method comes for assemblies produced from dotnet/runtime, so the issue should be transferred there in any case.

**Comment by airwedge1** [comment]
Yes.  My expectation would be that it return null.  However, I see that if you pass null into System.Text.Json.JsonSerializer.Deserialize it also throws an ArgumentNullException.  It appears that I am just whining.  I apologize.  I will close.
