### ISSUE TITLE
ResponseBufferingMiddleware should expose buffered data or a message digest for HTTP ETags

### ISSUE THREAD

**Issue by ghost** [dotnet/aspnetcore#5977]
I would like to use ResponseBufferingMiddleware to help me automatically calculate an ETag  (for caching) based on a messagedigest from the buffered data and add the ETag to a header. Unfortunately, ResponseBufferingMiddleware does not allow me to inspect the buffer. Could the buffer be exposed, an event with the buffer be exposed OR a messagedigest method be added ? 

BTW: Or are there other places in vnext suited for adding an ETags header based on a message digest of the body content ?

**Comment by JunTaoLuo** [comment]
Note we never shipped Buffering middleware outside of the experimental phase: https://www.nuget.org/packages/Microsoft.AspNetCore.Buffering/.
