### ISSUE TITLE
ResponseBufferingMiddleware - Reading the Response Body

### ISSUE THREAD

**Issue by BadriL** [dotnet/aspnetcore#5979]
`ResponseBufferingMiddleware` uses `BufferingWriteStream` which is write-only. Any reason why it has to be that way? I'd need to read the buffered response and create an HMAC that needs to be sent in a response header.

**Comment by davidfowl** [comment]
This is the direction we're going to go here https://github.com/dotnet/aspnetcore/issues/31146. Not an entire middleware, but a way to let you control the stream. If the buffering comes back up, we can think about adding something more configurable.
