### ISSUE TITLE
Url Rewrite and Mod Rewrite Maps

### ISSUE THREAD

**Issue by jkotalik** [dotnet/aspnetcore#5980]
Both `RewriteMap` in mod_rewrite and `rewriteMap` in UrlRewrite are not supported in our rewrite module. From the initial scraping of examples, both of these features were rarely used, but it would be a nice addition.
From apache:

> The RewriteMap directive defines an external function which can be called in the context of RewriteRule or RewriteCond directives to perform rewriting that is too complicated, or too specialized to be performed just by regular expressions. The source of this lookup can be any of the types listed in the sections below, and enumerated in the RewriteMap reference documentation.

Ex:
 `RewriteMap MapName MapType:MapSource`

From IIS:

> A rewrite map is an arbitrary collection of name-value pairs that can be used within rewrite rules to generate the substitution URL during rewriting. Rewrite maps are particularly useful when you have a large set of rewrite rules and all of these rules use static strings (that is, when there is no pattern matching used). In those cases, instead of defining a large set of simple rewrite rules, you can put all the mappings into the rewrite map as keys and values between the input URL and the substitution URL. Then, to look up the substitution URL based on the input URL, you will have one rewrite rule that references the rewrite map.

Ex:

```
<rewriteMap name="MyRewriteMap" defaultValue="">
    <add key="a.html" value="b.html" />
</rewriteMap>
```

**Comment by natelaff** [comment]
I'd like this. I maintain a site that used IIS rewrite maps. The site has been around for 10+ years, and i use these maps to map old pages to their current page.

**Comment by JeremyLittle** [comment]
I am working on rewriting an existing web application's ASP.NET rewrite module into .NET core using this middleware, and this bug is preventing a large number of existing rewrite files/rewrite maps from being used by our new system. 
Is there any timeline on fixing this issue?

**Comment by jkotalik** [comment]
Hm, I think this issue may be closed. We add rewrite map support a long time ago https://github.com/davidpeden3/BasicMiddleware/commit/30b4b75ae5883d630dabe9c94817854bf5dbfa00,

@JeremyLittle did you run into issues with rewrite maps being in in your rewrite file?

**Comment by JeremyLittle** [comment]
@jkotalik  apologies, I commented on the wrong thread. There is an issue that is open here: https://github.com/dotnet/aspnetcore/issues/24618 
which I just moved my comment to. thanks!

**Comment by jkotalik** [comment]
Okay, going to close this then 😄
