### ISSUE TITLE
Perf: reduce string allocations in rewrite middleware

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/aspnetcore#5983]
There are some small tweaks we could make to reduce string allocations.

Cursory examination with this app

``` c#
    public void Configure(IApplicationBuilder app)
    {
        var options = new RewriteOptions();
        options.Rewrite("app/(.+)", "app?q={R:1}");
        app.UseRewriter(options);

        app.Run(context => context.Response.WriteAsync(context.Request.QueryString.ToString()));
    }
```

Requests: 100

Total strings allocated: 1035
Strings allocated by middleware: 600 (excluding calls made within Regex)

Most allocating call = string.Substring - 400 allocations made in middleware

**Comment by JunTaoLuo** [comment]
This is not something we'll likely get to.
