### ISSUE TITLE
Add/Modify Url Encoding/Decoding for IIS UrlRewrite

### ISSUE THREAD

**Issue by jkotalik** [dotnet/aspnetcore#5985]
I didn't implement UrlDecode, a server variable in IISUrlRewrite, because there wasn't a great library (or static method) to do it. Right now I'm using Uri.Encode for encoding, which doesn't have the best perf.

I think we can use Uri.EscapeDataString, but fundamentally I think this should be changed to a different library.

**Comment by vchy1997** [comment]
Hello 
This is my first request, so please forgive me if there are any shortcomings
I have read the code and the documentation.

#### The methods that I think need to be used.
1. System.Uri.EscapeUriString("");
2. System.Uri.UnescapeDataString("");

#### What I think needs to be changed.
1. src\Middleware\Rewrite\src\UrlEncodeSegment.cs [Modify]
2. src\Middleware\Rewrite\src\PatternSegments\UrlDecodeSegment.cs [ADD]
3. src\Middleware\Rewrite\src\IISUrlRewrite\InputParser.cs (case UrlDecode/UrlEncode) [Modify]
4. src\Middleware\Rewrite\test\IISUrlRewrite\InputParserTests.cs [Modify]

If there is no problem, I think I can modify it

Thanks  :smile:




Translated with www.DeepL.com/Translator (free version)
