### ISSUE TITLE
Figure out pass-through compression for nginx

### ISSUE THREAD

**Issue by Tratcher** [dotnet/aspnetcore#5989]
When a request is proxied behind nginx the Accept-Encoding header is removed. This prevents the back-end from being able to compress the response.

Nginx supports compression on the front end, and compression between the back end and the front end, but it does not seem to allow the back-end compression to pass-through. See the integration tests in the ServerTests repo.

**Comment by TwentyFourMinutes** [comment]
Any updates so far?

**Comment by tebeco** [comment]
@Tratcher sorry to ping you about this, i was looking at the docs here :
https://docs.microsoft.com/en-us/aspnet/core/performance/response-compression?view=aspnetcore-3.1#working-with-iis-dynamic-compression

That pointed to this issue. As we `nginx` in `k8s` for the `ingress` part, i supposed we will be impacted by this as well ?

i'm not sure how to understand this :
> You'll have to take that up with nginx.

Does it means `AspNetCore cannot do this for you and you need to configure your own NGINX to be sure it properly forward the headers ....` ?

**Comment by Tratcher** [comment]
We have not found a way to make this work properly with nginx. If someone figures it out then we'll make any necessary changes to the middleware.

**Comment by martint17r** [comment]
Just a drive by comment - I don't know jack about dot.net...
At least for nginx>=1.14 adding 
```
proxy_http_version 1.1;
gzip on;
```
to the frontend nginx enables the pass-through compression.

**Comment by V4A001** [comment]
Idea to post on Nginx github?

**Comment by andtii** [comment]
I just did a test on latest nginx on kubernetes installed by helm and it looks like nginx is forwarding the Accept-Encoding headers to the upstream server. Below image show the headers in the request from .net core webapp in a pod behind nginx
![image](https://user-images.githubusercontent.com/1434571/105716866-b5950800-5f1f-11eb-842b-d09f6d639281.png)
