### ISSUE TITLE
Facebook crawler rewrite doesn't work - issue with query string rewrite

### ISSUE THREAD

**Issue by HarelM** [dotnet/aspnetcore#5998]
I wanted to add the following rules so I won't need to write separate code for IIS and apache:
```
var rewriteOptions = new RewriteOptions()
   .AddRewrite(".*_escaped_fragment_=%2F%3Fs%3(.*)", "api/opengraph/$1", skipRemainingRules: false);
```
This should redirect Facebook crawler to my opengraph controller with the relevant info I need in order to return the correct metadata for this page.
The full url that needs to be redirected is:
```http://wwwmysite.com/?_escaped_fragment_=%2F%3Fs%3DWIwdS4IoWM```
The problem is that the code does not take the query parameters as a part of the regexp match just the path.
Here:
https://github.com/aspnet/BasicMiddleware/blob/dev/src/Microsoft.AspNetCore.Rewrite/Internal/RewriteRule.cs
```
public virtual void ApplyRule(RewriteContext context)
        {
            var path = context.HttpContext.Request.Path;
```
it should probably be something like:
```
var fullPath = context.HttpContext.Request.Path + context.HttpContext.Request.QueryString
```
Am I missing something?

**Comment by shirhatti** [comment]
We're currently not planning to do this. However, we're leaving this issue open to solicit feedback and ascertain how many folks are impacted by this. We may re-consider based on feedback
