### ISSUE TITLE
app.UseForwardedHeaders gives different result when run in container

### ISSUE THREAD

**Issue by rynowak** [dotnet/aspnetcore#5999]
_From @singlewind on June 5, 2017 1:24_

We use SSL termination on Load balancer, so we use the following code to handle proper redirection of https and url generation.

```
app.UseForwardedHeaders(new ForwardedHeadersOptions
            {
                ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto
            });
```

When debug in windows, it behaves as expected. Even the protocol from LB is http, it will displays https.

![windows](https://cloud.githubusercontent.com/assets/7637/26767182/bd168fe8-49e0-11e7-9cd1-af4a30623e28.PNG)

However, when it hosts inside a container based on image microsoft/aspnetcore:1.1 it fails.

![linux-container](https://cloud.githubusercontent.com/assets/7637/26767197/fd91d622-49e0-11e7-9258-6254250919e3.PNG)

I reckon it can be a deep issue of Kestrel.

_Copied from original issue: aspnet/Mvc#6360_

**Comment by Tratcher** [comment]
@bradygaster another variant of the issue.

**Comment by Tratcher** [comment]
Related: https://github.com/aspnet/AspNetCore/issues/4135

**Comment by JunTaoLuo** [comment]
Looks like this has been resolved with known mitigations, should we close @Tratcher ?
