### ISSUE TITLE
API Analyzer doesn't recognize ControllerBase.ValidationProblem.

### ISSUE THREAD

**Issue by ghost** [dotnet/aspnetcore#6061]
### Describe the bug
The Web API Analyzer doesn't recognize `ControllerBase.ValidationProblem()` and does not prompt a codefix to add a `[ProducesResponseType]` attribute like it does for `ControllerBase.BadRequest()`.

### To Reproduce
1. Using ASP.NET Core 2.2
2. Install Microsoft.AspNetCore.Mvc.Api.Analyzers 2.2.0
3. Add `return ValidationProblem();` to a controller marked with `[ApiController]`.

### Expected behavior
Analyzer catches the issue and underlines `return ValidationProblem();`
Codefix prompt to add appropriate attributes to action.

### Additional context
Using ASP.NET Core 2.2 and Microsoft.AspNetCore.Mvc.Api.Analyzers 2.2.0. Since the default `ModelStateInvalidFilter` uses `ValidationProblemDetails` to build a 400 response object, it makes sense that people may want to do the same for validation problems within actions so that the response format is consistent in both cases. Alternatively or additionally, there should be a way to opt into `ControllerBase.BadRequest(ModelState)` using `ValidationProblemDetails` to build its response object for consistency with `ModelStateInvalidFilter`.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @webwizgordon.
@pranavkm, can you please look into this? Thanks!

**Comment by khellang** [comment]
`ApiControllerBase`, is that a custom base class in your app? Sounds like the same issue as https://github.com/aspnet/AspNetCore/issues/4410?

**Comment by webwizgordon** [comment]
Sorry, that was a typo. It should be `ControllerBase` i.e. the built-in base class for API controllers.

**Comment by khellang** [comment]
Ah, I see. That's probably because it returns `ActionResult` instead of a more specific result type, like `BadRequestObjectResult`, which has been annotated with a `DefaultStatusCodeAttribute`:

https://github.com/aspnet/AspNetCore/blob/74f1ccad0d25fb85d318cf9da5837d15648b36e2/src/Mvc/src/Microsoft.AspNetCore.Mvc.Core/ControllerBase.cs#L1833-L1846

https://github.com/aspnet/AspNetCore/blob/74f1ccad0d25fb85d318cf9da5837d15648b36e2/src/Mvc/src/Microsoft.AspNetCore.Mvc.Core/BadRequestObjectResult.cs#L11-L15

**Comment by webwizgordon** [comment]
Is it intentional that `ValidationProblem` returns `ActionResult` instead of a more specific result type? Every other method in `ControllerBase` returns a specific result type.

**Comment by khellang** [comment]
> Is it intentional that ValidationProblem returns ActionResult instead of a more specific result type?

I'm not sure. I tried to find the PR adding the method to see whether it had been DISCUSSED. @pranavkm probably knows. 

I'm guessing it might be because some people like to use 422 instead of 400, so you could override the method and return a different result.

**Comment by pranavkm** [comment]
> I'm guessing it might be because some people like to use 422 instead of 400, so you could override the method and return a different result.

Yes, that was the intent. 

There are other issues, such as https://github.com/aspnet/AspNetCore/issues/4950, where the analyzer *could* infer the status code of an `ActionResult` returning method by diving into the method call, at least in fairly simple scenarios. Perhaps that would be the fix here.
