### ISSUE TITLE
AzureDataProtectionBuilderExtensions should accept IKeyVaultClient, instead of concrete instance

### ISSUE THREAD

**Issue by wasabii** [dotnet/aspnetcore#6095]
Or, it should resolve said client from the container, instead of requiring a concrete instance, or newing it's own client. I have a `KeyVaultClientFactory` pattern going on, and there's no way to provide these instances.

**Comment by HaoK** [comment]
We are no longer owning the Azure integration packages going forward, feel free to file this issue over in their repo, see https://github.com/aspnet/Announcements/issues/409
