### ISSUE TITLE
Refactorings and Improvements after enabling components in Razor

### ISSUE THREAD

**Issue by rynowak** [dotnet/aspnetcore#6112]
I'm using this issue to track thoughts and feedback from the process of merging the Blazor compiler into the mainline Razor compiler.

Tracking item for improvements and refactorings we should do now that Components are enabled in the mainline Razor compiler:
- [ ] Represent components as their own concept instead of as tag helpers
- [x] Merge Component lowering into IR lowering
- [ ] Remove redundant passes after components become first class
- [ ] Investigate which passes should be specific/limited to components
- [ ] Combine test infrastructure for components and legacy
- [ ] Use new node formatting infrastructure for integration tests
- [x] Revisit handling of `data-` attributes in the compiler https://github.com/aspnet/AspNetCore/issues/6186
- [ ] Address: https://github.com/aspnet/AspNetCore-Tooling/pull/69#discussion_r244620979

**Comment by mkArtakMSFT** [comment]
@rynowak, @NTaylorMullen are all these items done already?

**Comment by NTaylorMullen** [comment]
Pretty much. I'll close this out.
