### ISSUE TITLE
Razor compiler take views from obj folder and not from project itself

### ISSUE THREAD

**Issue by JCFruit** [dotnet/aspnetcore#6160]
## The bug

Razor views compiler (in asp.net core 2.1) get views from /obj folder of the solution, not from the solution itself.

So, if views for project was once compiled and then all *.cshtml files was removed completely, every next compilation will have {ProjectName}.Views.dll generated and every request will fail with TypeLoadException if ViewModels from views was deleted from project.
To fix the problem you need to manualy clear /obj folder, since dotnet clean won't help

## How to reproduce

1. Create new asp.net core project
2. Add view (Index.cshtml)
3. run "dotnet build". {ProjectName}.dll and {ProjectName}.Views.dll will be generated
4. Delete content of /bin folder, run "dotnet clean", delete "Index.cshtml"
5. run "dotnet build". {ProjectName}.dll and {ProjectName}.Views.dll will be generated as in step 3, but there is no *.cshtml files in project

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @JCFruit.
We will try to find time to repro this issue and hopefully try to fix it in the near future. However, given that we haven't heard many reports of this issue, we won't handle it immediately.

**Comment by pranavkm** [comment]
Thanks for contacting us. We're closing this issue as there was no community involvement here for quite a while now.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
