### ISSUE TITLE
Microsoft.AspnetCore.Session setting null value throws exception

### ISSUE THREAD

**Issue by drowhunter** [dotnet/aspnetcore#6162]
### Describe the bug
In Asp.Net setting Session["foo"] = null is ok,  its like removing the session variable

in this version it throws an exception.

*Expected Behavior*
Perhaps setting a null value can internally call Session.Remove("foo")

**Comment by JunTaoLuo** [comment]
It doesn't seem like calling Remove instead is prohibitively difficult. I think this behavioural difference is tolerable.
