### ISSUE TITLE
Components: Add Compiler generated strongly-typed methods for URL generation

### ISSUE THREAD

**Issue by rynowak** [dotnet/aspnetcore#6352]

**Comment by mkArtakMSFT** [comment]
@javiercn do you know what this ask is about? Can you please add more context to the description? Thanks!

**Comment by javiercn** [comment]
Yes, I believe that this is for instead of doing `Url.Action("home", "index", new { id = 5 })` to generate a Url, you can do something like `Url.HomeIndex(5);`.

**Comment by danroth27** [comment]
We've decided that this is not a direction that we want to go with the framework. The concern is that we're not convinced we can make this work generally and it's a non-trivial amount of work.
