### ISSUE TITLE
Add name for EventId in logs

### ISSUE THREAD

**Issue by Kahbazi** [dotnet/aspnetcore#6381]
Can we have log event name for logs in all the projects? Lately it has been added for MVC (https://github.com/aspnet/Mvc/issues/6818)

I can submit a PR if it's ok.

Here's a list of projects so we can see which one already has the event name and which one doesn't.
    
- [x] Microsoft.AspNetCore.DataProtection
- [x] Microsoft.AspNetCore.Hosting
- [x] Microsoft.AspNetCore.Identity
- [x] Microsoft.AspNetCore.Server.HttpSys
- [x] Microsoft.Extensions.Identity.Core
- [x] Microsoft.AspNetCore.Server.Kestrel.Core
- [x] Microsoft.AspNetCore.HostFiltering
- [x] Microsoft.AspNetCore.Antiforgery
- [x] Microsoft.AspNetCore.Routing
- [x] Microsoft.AspNetCore.Cors
- [x] Microsoft.AspNetCore.Diagnostics
- [x] Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore
- [x] Microsoft.AspNetCore.Localization
- [x] Microsoft.AspNetCore.HttpsPolicy
- [x] Microsoft.AspNetCore.ResponseCaching
- [x] Microsoft.AspNetCore.ResponseCompression
- [x] Microsoft.AspNetCore.Rewrite
- [x] Microsoft.AspNetCore.Session
- [x] Microsoft.AspNetCore.StaticFiles
- [x] Microsoft.AspNetCore.Mvc.Core
- [x] Microsoft.AspNetCore.Mvc.Formatters.Json
- [x] Microsoft.AspNetCore.Authentication
- [x] Microsoft.AspNetCore.Authentication.Cookies
- [x] Microsoft.AspNetCore.Authentication.JwtBearer
- [x] Microsoft.AspNetCore.Authentication.OpenIdConnect
- [x] Microsoft.AspNetCore.Authentication.Twitter
- [x] Microsoft.AspNetCore.Authentication.WsFederation
- [x] Microsoft.AspNetCore.Authorization
- [x] Microsoft.AspNetCore.CookiePolicy
- [x] Microsoft.AspNetCore.Http.Connections
- [x] Microsoft.AspNetCore.Http.Connections.Client
- [x] Microsoft.AspNetCore.SignalR.Client.Core
- [x] Microsoft.AspNetCore.SignalR.Core
- [x] Microsoft.AspNetCore.SignalR.StackExchangeRedis

**Comment by blowdart** [comment]
Speaking for the Authentication, Authorization and DataProtection pieces I'd be happy to look at a PR for those

**Comment by JamesNK** [comment]
I'll do Microsoft.AspNetCore.Routing

**Comment by Kahbazi** [comment]
I'll take Microsoft.AspNetCore.Hosting.
There are some logs in this project outside `HostingLoggerExtensions` like this
https://github.com/aspnet/AspNetCore/blob/master/src/Hosting/Hosting/src/Internal/ApplicationLifetime.cs#L61
Should I move them to `HostingLoggerExtensions`?

**Comment by Kahbazi** [comment]
I'll take projects in Middleware.sln

**Comment by Kahbazi** [comment]
There's no `LoggingExtensions`  class in `Microsoft.AspNetCore.Identity` and  `Microsoft.Extensions.Identity.Core`. Should I add one while adding event names?

https://github.com/aspnet/AspNetCore/blob/master/src/Identity/Extensions.Core/src/UserManager.cs#L711

**Comment by Tratcher** [comment]
> There's no `LoggingExtensions` class in `Microsoft.AspNetCore.Identity` and `Microsoft.Extensions.Identity.Core`. Should I add one while adding event names?
> 
> https://github.com/aspnet/AspNetCore/blob/master/src/Identity/Extensions.Core/src/UserManager.cs#L711

At least add a central list of event ids like Hosting.
https://github.com/aspnet/AspNetCore/pull/11379/files#diff-db6cb8ff7c72fa42502138fd3aab3a85

**Comment by Kahbazi** [comment]
@Tratcher ok, I'll work on `Microsoft.AspNetCore.Identity`.

**Comment by kuns200** [comment]
I am planning to take Microsoft.AspNetCore.Server.HttpSys

**Comment by HaoK** [comment]
Looks like that's everything checked off now, thanks to everyone who helped for getting this done!
