### ISSUE TITLE
Transport interface in SignalR Typescript client doesn't match the interface in C# or Java

### ISSUE THREAD

**Issue by mikaelm12** [dotnet/aspnetcore#6464]
The TS client Transport interface uses the verb `connect` vs the C# and Java client that both use `start`. We should change the TS client to start in 3.0 since it'll be a breaking change. 

https://github.com/aspnet/AspNetCore/blob/c60d1e1a14691a624f46b350f6561dc752e3964c/src/SignalR/clients/ts/signalr/src/ITransport.ts#L27

https://github.com/aspnet/AspNetCore/blob/c60d1e1a14691a624f46b350f6561dc752e3964c/src/SignalR/src/Microsoft.AspNetCore.Http.Connections.Client/Internal/ITransport.cs#L13

**Comment by davidfowl** [comment]
@BrennanConroy worth doing or nah?

**Comment by BrennanConroy** [comment]
Nah, in a perfect world it would be nice to be consistent, but why break things when no one has complained about the verbiage?
