### ISSUE TITLE
Cleanup windows installer code

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/aspnetcore#6506]
The code we have in aspnet/AspNetCore for Windows Installers is pretty messy. Here are some things we should consider doing to clean it up:

- [ ] Delete unused code. We copied most of github.com/Microsoft/IIS-Common and IIS-Setup into our repo, but we likely don't need much of it.
- [x] Cleanup the project files. The code has a bunch of quirks as a result of the way this used to build in VSTS with gitsubmodules
- [x]  Backport the cleanup to 2.1 and 2.2.
- [x] Use ProjectReference (e.g. https://github.com/aspnet/AspNetCore/pull/6078)
- [ ] Cleanup source code layout. The nesting of folders under src/Installers/Windows/AspNetCoreModule-Setup is confusing.
- [ ] Update the filenames for ANCM installers to follow our patterns:
   * e.g. `ancm-v2-iis-$(version)-win-x64.msi`, or `ancm-v1-iisexpress-$(version)-win-x86.msi`

cc @jkotalik

**Comment by natemcmaster** [comment]
@rockerinthelocker please open a new issue. Your comment doesn't match the purpose of this issue.

**Comment by shirhatti** [comment]
@jkotalik Will you get to this in 3.0?

**Comment by jkotalik** [comment]
Yeah, let's punt it to preview 3 though.

**Comment by jkotalik** [comment]
I'm pushing this to the backlog; IMO not high priority and has a large chance of breaking things.

**Comment by JunTaoLuo** [comment]
This isn't likely to be addressed.
