### ISSUE TITLE
Add AutoRest code generation support

### ISSUE THREAD

**Issue by dougbu** [dotnet/aspnetcore#6528]
### Is your feature request related to a problem? Please describe.
Enhancement related to #4896

### Describe the solution you'd like
Add new targets wrapping AutoRest code generation in preparation for conversations with the AutoRest team.

### Describe alternatives you've considered
If necessary, we could ship the necessary AutoRest package. But, would prefer we did not own it going forward.

**Comment by SbiCA** [comment]
Are there already pieces one could try out yet? I remember seeing a demo with nswag but not with AutoRest

**Comment by mkArtakMSFT** [comment]
This is not something we will do.
