### ISSUE TITLE
Localised number format and wrong input type for decimal fields

### ISSUE THREAD

**Issue by ygoe** [dotnet/aspnetcore#6566]
### Describe the bug
With a model that contains a `decimal` property, this doesn't work with a locale that uses a decimal comma:

    <input asp-for="Number">
    <input asp-for="Number" type="number">

### To Reproduce
1. Using this version of ASP.NET Core 2.1.5
2. Create the model class and the HTML razor view, then run it

Code:

    class Model
    {
        public decimal Number { get; set; } = 1.0m;
    }

### Expected behavior
This should be the rendered HTML:

    <input type="number" name="Number" value="1.0">

This happens instead, for the two view variants from the top:

    <input type="text" name="Number" value="1,0">
    <input type="number" name="Number" value="1,0">

The first issue is that the `decimal` type isn't rendered with the `type="number"` attribute. If I fix this myself by adding the attribute, the field remains completely empty because there is a **comma** instead of a **point** in the value. This shouldn't be localised because then no browser or frontend library can handle the value anymore.

PS: I haven't even got to try what happens when the correct value "1.0" is sent back to the controller and the model binder should convert it to a `decimal` type. It probably fails for the same reason.

[User reference: Configuration/Endpoint/Edit/Factor]

**Comment by AndreasAmMueller** [comment]
Ran into the same bug and helped me out with a custom TagHelper that recognizes the `For.ModelExplorer.ModelType` as decimal or nullable decimal and then modifies the value attribute.
```
if (For.Model != null)
{
	decimal val = (decimal)For.Model;
	string value = val.ToString(CultureInfo.InvariantCulture);
	output.Attributes.SetAttribute(new TagHelperAttribute("value", value));
}
````
You also might want to set the "step" attrbute to "any".

For the .NET Core MVC Team:    
I found some lines that are part of the bug, but I was not able to solve the wohle problem.

Lines found:
- The type should result in "number" not "text": https://github.com/aspnet/AspNetCore/blob/1aa50faa290ecda304507981cd01ed92651d5e34/src/Mvc/src/Microsoft.AspNetCore.Mvc.TagHelpers/InputTagHelper.cs#L51
- This line has the `CultureInfo.CurrentCulture` (for me, its de-DE!) as value. `CultureInfo.InvariantCulture` is needed to parse correctly: https://github.com/aspnet/AspNetCore/blob/1aa50faa290ecda304507981cd01ed92651d5e34/src/Mvc/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/Binders/DecimalModelBinder.cs#L80

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.

**Comment by ygoe** [comment]
@mkArtakMSFT Can you please explain why you believe the question has been answered / the bug has been fixed? I cannot see how this is the case. Please reopen until this has been fixed. In case you didn't know, there are other regions in the world than those that use a decimal point. And currently I can't use proper HTML with decimal numbers with ASP.NET Core MVC data binding.

**Comment by mkArtakMSFT** [comment]
Looks like I misread this. Reopening for further investigation.

**Comment by ygoe** [comment]
@mkArtakMSFT Did you want to reopen this issue?

**Comment by bernhof** [comment]
This issue needs more attention. It renders `asp-for` useless for decimal inputs in many cultures.

**Comment by StefanOssendorf** [comment]
Any progress on this? I hit the same behavior with Blazor WebAssembly though I think it also applies to Blazor Server Side. The same applies to the min, max and step attribute of an input of type number and range.

**Comment by Kurti123** [comment]
Experiencing the same issue on latest 3.1 stream of .NET Core. I have German culture, so we use "," as decimal separator. When I send a decimal value from an input field to the controller, the value "214,50" is sent to the controller. But when mapped to my ViewModel in the controller, the comma is lost and the value 21450 in mapped to my models attribute which is a decimal type...

However, with a piece of old legacy code within the same solution, the mapping works just fine although the setup is exactly the same.

**Comment by mkArtakMSFT** [comment]
We've moved this issue to the Backlog milestone. This means that it is not going to be worked on for the coming release. We will reassess the backlog following the current release and consider this item at that time. To learn more about our issue management process and to have better expectation regarding different types of issues you can read our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md).

**Comment by ygoe** [comment]
@mkArtakMSFT Thanks for the update. I'd suggest you put a bold warning in the ASP.NET Core documentation then which says that this product does not support other server environments than English (and few more) and will not for an unspecified time. At least everybody knows what to expect then, and when to look for alternatives.

**Comment by ChrTall** [comment]
Does the Fix from @AndreasAmMueller work ?
I am considering removing type number but If it can be fixed like this then I would do it like him. Are there other problems I may run into?

**Comment by Arkiant** [comment]
I am having same problem:

I have this Entity:

```csharp
namespace Backend.Models
{
    public class Tax
    {
        public int ID { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        [Column(TypeName = "decimal(10,3)")]
        public decimal Value { get; set;}

    }
}
```

When I use scaffold Razor Page using Entity Framework (CRUD) and execute the solution I have this html error:

![image](https://user-images.githubusercontent.com/1246874/93457291-1318a880-f8df-11ea-85ad-4b2dcff7c113.png)

Location in spanish, decimal is comma separated, because html throw this error saying is not a number.

Also, if I use dot decimal separator the database save a number without decimals:

![image](https://user-images.githubusercontent.com/1246874/93457505-5d9a2500-f8df-11ea-86ca-c6be0389ff55.png)

¿This can be related to this issue?

¿How can I solve this issue?

Thanks in advance.

**Comment by martonx** [comment]
What about .Net Core 5? Is this fixed?

**Comment by Kurti123** [comment]
> 
> 
> What about .Net Core 5? Is this fixed?

Bro, It's just been almost two years. Give them some time. Come on man!

**Comment by Kasper888** [comment]
Still waiting the fix...

**Comment by ygoe** [comment]
@javiercn What does that mean, "affected-few"? That most ASP.NET Core users in the world use English number formats? That would be new to me. And what does "severity-minor" mean? That it's not a blocking issue to not be able to use decimal numbers in forms? That's a strange ranking app you use there. Must be heavily US-biased.

**Comment by Kasper888** [comment]
Guys, I have changed my culture's number format to EN without changing the whole culture, on the client side I'm formatting date, number, currency(using JS library). In the backend I return/receive them in EN as below code function in a base controller:
`   public override void OnActionExecuting(ActionExecutingContext context)
    {
      SetCultureNumberFormat();
      base.OnActionExecuting(context);
    }
    private void SetCultureNumberFormat()
    {
      if (CultureInfo.CurrentCulture.Name == "ar")
      {
        var cultureInfo = CultureInfo.CurrentCulture.Clone() as CultureInfo;
        cultureInfo.NumberFormat = CultureInfo.GetCultureInfo("en-US").NumberFormat;
        CultureInfo.CurrentUICulture = CultureInfo.CurrentCulture = cultureInfo;
      }
    }`

**Comment by DavidGau** [comment]
Here is how I solved it on my side. I basically did what @Kasper888 did but instead of overriding the `OnActionExecuting `method I changed the number format culture directly in the startup.cs:



            CultureInfo[] cultures = {
                new CultureInfo("fr"),
                new CultureInfo("en")
            };

            cultures[0].NumberFormat = cultures[1].NumberFormat;

            services.Configure<RequestLocalizationOptions>(opt =>
            {
                opt.DefaultRequestCulture = new RequestCulture(cultures[0]);
                opt.SupportedCultures = cultures;
                opt.SupportedUICultures = cultures;
            });

**Comment by clementhervy** [comment]
Just ran into this. 

I did this :
`<input asp-for="Number" class="form-control" type="number" value="@Model.Number.ToString("N", CultureInfo.InvariantCulture)" />`

It is ugly, and I don't like it, but hey, such is life for we few, we rest-of-the-world, minor-severity-bug-affected few.

**Comment by AndreasAmMueller** [comment]
> 
> 
> Just ran into this.
> 
> I did this :
> `<input asp-for="Number" class="form-control" type="number" value="@Model.Number.ToString("N", CultureInfo.InvariantCulture)" />`
> 
> It is ugly, and I don't like it, but hey, such is life for we few, we rest-of-the-world, minor-severity-bug-affected few.

Does this solve the parsing fault (wrong number / comma is not recognized) when submitting the form to the backend too?

**Comment by clementhervy** [comment]
> Does this solve the parsing fault (wrong number / comma is not recognized) when submitting the form to the backend too?

That requires a [custom model binder](https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/custom-model-binding?view=aspnetcore-5.0#custom-model-binder-sample). For brevity's sake I'll only put the actual binding code here:

```javascript
    public Task BindModelAsync(ModelBindingContext bindingContext)
    {
        if (bindingContext == null)
            throw new ArgumentNullException(nameof(bindingContext));

        var valueProviderResult = bindingContext.ValueProvider.GetValue(bindingContext.ModelName);

        decimal result;
        if (decimal.TryParse(valueProviderResult.FirstValue,
            NumberStyles.AllowDecimalPoint | NumberStyles.AllowLeadingSign,
            CultureInfo.InvariantCulture,
            out result))
        {
            bindingContext.Result = ModelBindingResult.Success(result);
            return Task.CompletedTask;
        }

        return _baseBinder.BindModelAsync(bindingContext);
    }
```

**Comment by AndreasAmMueller** [comment]
Yep... I thought so^^

See this Gist here: [FIX: Localised number format and wrong input type for decimal fields ](https://gist.github.com/AndreasAmMueller/38c1a8d76ecd4450b4f75a479f3293c1)

**Comment by clementhervy** [comment]
Wow! You've done your homework, bravo!

**Comment by shapeh** [comment]
> Yep... I thought so^^
> 
> See this Gist here: [FIX: Localised number format and wrong input type for decimal fields ](https://gist.github.com/AndreasAmMueller/38c1a8d76ecd4450b4f75a479f3293c1)

Thanks you so much for this. This has been a pain for as long as I can remember.

**Comment by Joev-** [comment]
For us, this problem was caused by using app.UseRequestLocalization().

I'm not sure how long browsers have been doing this for, but they correctly parse comma based decimals into period based decimals. I believe we want culture-based model binding in all cases except for this, which the Invariant based model binder works perfectly for.

**Comment by Nikkelmann** [comment]
Seems to be an old issue:
https://github.com/aspnet/Mvc/issues/2780
https://github.com/aspnet/Mvc/issues/6024

With locals that use comma as the decimal separator, the rendered value in the text input field causes the client-side validation to fail (when using the jQuery validation library that comes with the razor pages project template).

The expectation by the validator is that the browser [returns the value as a floating-point number](https://html.spec.whatwg.org/multipage/input.html#number-state-(type=number)), but since it only does this for type="number", it fails the validation.

The issue does not seem to be the client-side validation, however, people do seem to workaround this by hacking the client-side validator: https://weblogs.asp.net/jdanforth/jquery-validate-and-the-comma-decimal-separator

**Comment by ygoe** [comment]
FTR, no jQuery validation around here. The problem solely lies in ASP.NET Core.

**Comment by saryeHaddadi** [comment]
Same issue for me. My development environment (Visual Studio) is in English, and my browser in French, and this makes decimal datatype unusable when enabling native .Net JS validation, neither with a dot, nor a comma. Below the screens.

![image](https://user-images.githubusercontent.com/51054901/149214170-446fa4bb-2c3b-4360-9023-e0696b18fcaa.png)
![image](https://user-images.githubusercontent.com/51054901/149214221-bb40aaff-086f-4873-9f58-4976ea0c8af6.png)

**Dot is unusable (ex 1.5):** 
![image](https://user-images.githubusercontent.com/51054901/149214309-84e069c6-ed8a-4720-9d51-e2a1be51687e.png)

**Coma is unusable (ex: 1,5):**
![image](https://user-images.githubusercontent.com/51054901/149214724-ff7823d2-0245-4e81-a452-396ffccb800e.png)

**Comment by ygoe** [comment]
Really good example! This mix of languages is precisely why culture-invariant formats must be used in all protocols (including HTML). Microsoft has miserably failed on this here. Seems they like it so.

**Comment by tlaemmlein** [comment]
> Yep... I thought so^^
> 
> See this Gist here: [FIX: Localised number format and wrong input type for decimal fields ](https://gist.github.com/AndreasAmMueller/38c1a8d76ecd4450b4f75a479f3293c1)
@AndreasAmMueller 
I'm working only with RazorPages. How can I use your Workaroung/Fix with RazorPages technique?
My project is using .NET 6 where only on Program.cs is available (no StartUp.cs). I see there aren't 'ModelBinderProviders' with 'AddRazorPages'
![image](https://user-images.githubusercontent.com/3143027/161616597-5232f64a-64fa-4a7d-be90-2812a50d153f.png)

Or is it possible to mix 'MVC' with RazorPages?

Thanks,
Thomas

**Comment by yonder83** [comment]
> Same issue for me. My development environment (Visual Studio) is in English, my browser in French, and this makes decimal datatype unusable (native .Net JS validation is enabled), neither with a dot, nor a comma. Below the screens.
> 
> ![image](https://user-images.githubusercontent.com/51054901/149214170-446fa4bb-2c3b-4360-9023-e0696b18fcaa.png) ![image](https://user-images.githubusercontent.com/51054901/149214221-bb40aaff-086f-4873-9f58-4976ea0c8af6.png)
> 
> **Dot is unusable (ex 1.5):** ![image](https://user-images.githubusercontent.com/51054901/149214309-84e069c6-ed8a-4720-9d51-e2a1be51687e.png)
> 
> **Coma is unusable (ex: 1,5):** ![image](https://user-images.githubusercontent.com/51054901/149214724-ff7823d2-0245-4e81-a452-396ffccb800e.png)

The latter error is caused because you are using jquery-validation. It has a function that validates number, it has nothing to do with browser language. You can test it here https://jqueryvalidation.org/number-method/.

To get comma validated as a decimal separator, you can override the jquery-validation number validation as suggeted by @Nikkelmann https://github.com/dotnet/aspnetcore/issues/6566#issuecomment-1008360355

**Comment by yonder83** [comment]
> Really good example! This mix of languages is precisely why culture-invariant formats must be used in all protocols (including HTML). Microsoft has miserably failed on this here. Seems they like it so.

The point was, [saryeHaddadi](https://github.com/saryeHaddadi) don't want to use the  culture-invariant format. He want's to use comma as a decimal separator.

**Comment by remcoros** [comment]
According to HTML standard, the 'value' of a number input element should always be in the invariant culture. Browsers may choose to render it differently based on the users browser settings. 

From what I remember this has been a source of pain since Webforms / MVC 1.

**Comment by scorpion86** [comment]
I'm tired of searching for a permanent solution to this problem in every new project for years. Can you please solve this problem in 7.0-rc1 milestone?

**Comment by halter73** [comment]
## Background and Motivation

@MackinnonBuck writes,

>I’m working on a fix for MVC form data binding that changes HTML generation for form inputs. Since this is technically a breaking change, we’re going to introduce a new flag that allows customers to revert to the old behavior. The default value for this flag (false) enables the new behavior.

## Proposed API

```diff
namespace Microsoft.AspNetCore.Mvc.ViewFeatures;

public class HtmlHelperOptions
{
+    public bool SuppressCultureInvariantFormValueFormatting { get; set; }
}

namespace Microsoft.AspNetCore.Mvc.Rendering;

public class ViewContext
{
+    public bool SuppressCultureInvariantFormValueFormatting { get; set; }
}
```

> Setting this flag to true does two things:
>
> 1. Always uses CultureInfo.CurrentCulture to format the value attribute for HTML inputs.
> 2. Prevents the new hidden `<input/>` elements from being generated (these contain metadata about which form values use invariant formatting).

## Usage Examples

N/A

## Alternative Designs

> Alternate names:

> - AlwaysUseCurrentCultureInFormValueFormatting
> - TreatAllFormInputsAsCultureSpecific
> - Other suggestions?

## Risks

N/A

**Comment by halter73** [comment]
@captainsafia writes,

> Have you considered the name `CultureInvariantFormValueFormattingEnabled`​? it seems to match the naming style used for the other boolean-based option (`ClientValidationEnabled`) in the `HtmlHelperOptions​` and `ViewContext`​ classes.

**Comment by halter73** [comment]
How likely do we think it is that people will want to change this? Given the description of the PR it seems like we're just correcting behavior but we're adding an escape hatch out of an abundance of caution. Can we make this an AppContext switch instead of a public API?

**Comment by MackinnonBuck** [comment]
> Have you considered the name `CultureInvariantFormValueFormattingEnabled​`? it seems to match the naming style used for the other boolean-based option (`ClientValidationEnabled`) in the `HtmlHelperOptions`​ and `ViewContext​` classes.

I like this name.

> Can we make this an AppContext switch instead of a public API?

It looks like we've already used `HtmlHelperOptions` to configure changes to HTML generation (for example, [`Html5DateRenderingMode`](https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/Mvc.ViewFeatures/src/Rendering/Html5DateRenderingMode.cs) and [`CheckBoxHiddenInputRenderMode`](https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/Mvc.ViewFeatures/src/Rendering/CheckBoxHiddenInputRenderMode.cs)). Do you think there's any merit to adding a new property in `HtmlHelperOptions` instead of using an `AppContext` switch in order to keep things in the same place?

**Comment by MackinnonBuck** [comment]
Adding on to my previous comment, `Html5DateRenderingMode` and `CheckBoxHiddenInputRenderMode` are both `enum` values. If we decide to add a new API at all, should we make it an `enum` in case we decide to make further changes in the future?

**Comment by halter73** [comment]
> Do you think there's any merit to adding a new property in `HtmlHelperOptions` instead of using an `AppContext` switch in order to keep things in the same place?

I do think there's merit to adding options to `HtmlHelperOptions` given similar options already exist.

> Adding on to my previous comment, `Html5DateRenderingMode` and `CheckBoxHiddenInputRenderMode` are both `enum` values. If we decide to add a new API at all, should we make it an `enum` in case we decide to make further changes in the future?

I like that idea. What would you name the enum? `FormValueFormattingMode`? What about the values? `InvariantCulture` and `CurrentCulture`? Can you leave a comment with the new proposed API with the enum?

By the way, how does this new API interact with the existing `HtmlHelperOptions` does it override or get overridden by any of them?

Also, can you explain how the `HtmlHelperOptions` relates to the `ViewContext` and the `DefaultHtmlGenerator`? Why are `Html5DateRendingMode` and `CheckBoxHiddenInputRenderMode` on the `ViewContext` but `IdAttributeDotReplacement` is on the `DefaultHtmlGenerator`? Would the `ViewContext` API work just as well if it were on the `DefaultHtmlGenerator`?

**Comment by MackinnonBuck** [comment]
## Proposed API

```diff
namespace Microsoft.AspNetCore.Mvc.Rendering;

+public enum FormInputRenderMode
+{
+    DetectCultureFromInputType = 0,
+    AlwaysUseCurrentCulture = 1,
+}

namespace Microsoft.AspNetCore.Mvc.ViewFeatures;

public class HtmlHelperOptions
{
+    public FormInputRenderMode FormInputRenderMode { get; set; }
}
```

## Usage Examples

```csharp
public void ConfigureServices(IServiceCollection services)
{
    services.AddMvc()
        .AddViewOptions(options =>
        {
            options.HtmlHelperOptions.FormInputRenderMode = FormInputRenderMode.AlwaysUseCurrentCulture;
        });
}
```

**Comment by MackinnonBuck** [comment]
> how does this new API interact with the existing HtmlHelperOptions does it override or get overridden by any of them?

It does not interact with other properties - it's completely independent.

> Also, can you explain how the `HtmlHelperOptions` relates to the `ViewContext` and the `DefaultHtmlGenerator`?

`HtmlHelperOptions` can be accessed via `MvcViewOptions` for classes that have it injected via DI. For classes that don't (e.g. tag helpers), the `ViewContext` has its own copies of the properties in `HtmlHelperOptions` that can be read (why it doesn't cache a `HtmlHelperOptions` and expose that as a public property, I'm not sure, but that's not something we can reasonably change at this point).

> Why are `Html5DateRendingMode` and `CheckBoxHiddenInputRenderMode` on the `ViewContext` but `IdAttributeDotReplacement` is on the `DefaultHtmlGenerator`?

Presumably it's because properties on `ViewContext` needed to be used by tag helpers, but `IdAttributeDotReplacement` did not. But follwing that logic, we _could_ remove this new property from `ViewContext` (an older version of my PR did reference it in `InputTagHelper`, but as things currently stand, we could safely remove it). In fact, I've gone ahead and done that in the API proposal in my previous comment, so thanks for bringing it up!

**Comment by halter73** [comment]
The above API makes sense to me. Do we prefer "render" mode over "rendering" mode? `Html5DateRenderingMode` and `CheckBoxHiddenInputRenderMode` are already inconsistent here, so I could go either way. If you prefer "render", I'm good with approving your last proposal as-is.

**Comment by MackinnonBuck** [comment]
> I like that idea. What would you name the enum? `FormValueFormattingMode`?

I think `FormInputRenderMode` might be good because `FormValueFormattingMode` doesn't necessarily represent the fact that this option also controls whether hidden `<input name="__Invariant" ... />` elements are generated.

> What about the values? `InvariantCulture` and `CurrentCulture`?

I've chosen `DetectCultureFromInputType` instead of `InvariantCulture` because it still might use `CurrentCulture` for some input types.

And I think `AlwaysUseCurrentCulture` highlights that while the other option _may_ use `CurrentCulture`, this one will _definitely_ use it.

**Comment by MackinnonBuck** [comment]
> Do we prefer "render" mode over "rendering" mode?

Hm, I really don't have a preference here. _Maybe_ I like "render" a bit more just because the "ing" doesn't really add any important information. Totally willing to change my mind though!

**Comment by halter73** [comment]
If there are no objections, I can mark this `api-approved` Monday. I want to give a little more time for other people to provide input though.

**Comment by ygoe** [comment]
As I understood it, the new default will be the fixed `InvariantCulture` behaviour, so I have no interest in this API and don't care about its name. But keep in mind that this API will retain the current bug behaviour. It will generate invalid or at least unusable HTML output that cannot be understood by web browsers. There should be a good warning attached to it that its only purpose is to retain compatibility with old bugs. But it seems the other two `HtmlHelperOptions` already serve the same purpose.

**Comment by halter73** [comment]
API review notes:

- Do we need this API at all?
  - If this is just a bug fix, can we get away with using just an AppContext switch?
  - This has been the behavior since before ASP.NET core. We are afraid people rely on the old behavior, and this new API isn't exactly in your face.

API Approved!

**Comment by valeriob** [comment]
Hi,
I may be missing something, but it will be difficult to apply this approach in a big application where you will have to incrementally migrate actions from one model to another to leverage the modern browser capabilities, is there a way to have a per request configuration ?
