### ISSUE TITLE
 Static Files not being served on Mac (SCD)

### ISSUE THREAD

**Issue by wis3guy** [dotnet/aspnetcore#6640]
When i create a new AspNetCode (2.1.1, not tested in older versions) app and publish it to a macOS distributable, static files are not being served. Regular action methods work as expected.

I need this to distribute the self contained mvc app (https://docs.microsoft.com/en-us/dotnet/core/deploying/#self-contained-deployments-scd) as part of an Electron application.

## Expectation
Regardles the way of running the app (pre/post publish) that `http://localhost:5000/app` yields an HTTP 200 response.

## Steps to reproduce

In this (https://github.com/wis3guy/StaticFileIssue) public github repo, i have created a minimal sample application to reproduce the issue.

Assuming:

* you cloned the repo
* that your currend directory is the root of the repo
* you are on a Mac

#### Running app using dotnet SDK from the terminal

```bash
cd StaticFileIssue
dotnet run StaticFileIssue.dll
```

Works as expected!

#### Running published SCD app using dotnet SDK from the terminal

```bash
cd StaticFileIssue
dotnet publish -o ../dist/ -r osx.10.11-x64
cd ../dist
dotnet StaticFileIssue.dll
```

Works as expected!

#### Running published SCD app directly from the terminal

```bash
cd StaticFileIssue
dotnet publish -o ../dist/ -r osx.10.11-x64
cd ../
./dist/StaticFileIssue
```

**Does not work** as expected ast it yields an HTTP 404 response!

## Attempted workarounds

Obviously i have scoured the github issues and StackOverflow for a potential workaroud. In one of the (not exact match) SO posts i found an answer that suggested explicitly setting the location of the web root by using the `.UseWebRoot()` method on the web host. I made the following attempts:

```c#
namespace StaticFileIssue
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var builder = WebHost.CreateDefaultBuilder(args)
                //.UseWebRoot("/Users/wis3guy/Projects/StaticFileIssue/StaticFileIssue/wwwroot") // Attempt 1: This hardcodes the location of the wwwroot to the folde rin the codebase
                //.UseWebRoot(Path.Join(Directory.GetCurrentDirectory(), "wwwroot")) // Attempt 2: This emulates the default behavior and uses tha path of the wwwroot folder in the executing directory
                .UseStartup<Startup>();
            
            var host = builder.Build();

            // Put a breakpoint on host.Run() and watch the host.Options.WebRoot (sadly not public) property
            // - Empty by default
            // - Value set in the .UseWebRoot() call

            host.Run();
        }
    }
}
```

### Manually setting the web root

My first attempt was to hardcode the webroot. And it worked. I could access the static html page when running the published SCD app from the terminal. Obviously the solution is undesirable, as the path to the static files will differ on every machine the Electron app will be deployed to.

Then i thought i'd be clever about it and set the web root manually, but mimic the default behavior. So i dynamically determined the location of the web root, based on the current directory. And that **did not work**.

### Conclusion

To be honest i have no clear conclusion. I feel that the problem might be related to:

* a bug int the way the web root directory, when executing the self contained app on macOS (not tested on Windows). Perhaps the app is actually executed in some sort of a temp folder, and not the installation directory?;
* a problem with access permissions on files in the executing directory (unlikely, as elevating permissions using `sudo` has no effect);
* a difference in the SDK betweem the published SCD app and what i have on my machine (unlikely as i publish using and develop and test on the same machine);

#### OS

macOS Mojave Version 10.14.1

#### dotnet --list-runtimes

```
Microsoft.AspNetCore.All 2.1.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
Microsoft.AspNetCore.App 2.1.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 1.0.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 1.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 1.0.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 1.0.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 1.1.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 1.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 1.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 1.1.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 1.1.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 2.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 2.1.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```

#### dotnet --list-sdks

```
1.0.0-preview2-1-003177 [/usr/local/share/dotnet/sdk]
1.0.1 [/usr/local/share/dotnet/sdk]
1.0.4 [/usr/local/share/dotnet/sdk]
1.1.4 [/usr/local/share/dotnet/sdk]
1.1.5 [/usr/local/share/dotnet/sdk]
2.0.3 [/usr/local/share/dotnet/sdk]
2.1.401 [/usr/local/share/dotnet/sdk]
```

#### dotnet --version
2.1.401

**Comment by wis3guy** [comment]
As a workaround, i now pass the path to the web root directory as a command line argument. This allows me to determine the correct path, inside the electron startup code.

For my use case, this is an elegant workaround. People who do not use some sort of shell application to launch the dotnet SCD and those that do not want to start the SCD from the command line, will still suffer from this problem though. So, the issue still stands.

**Comment by wis3guy** [comment]
The fact that i can pass in the path to the web root, and have the application function as expected, leads me to conclude that the root cause is either:

* a problem the way that aspnet resolves the current executing directory
* a problem with the way the static file middleware determines the web root directory

**Comment by Tratcher** [comment]
Web root is determined to be `{content root}\wwwroot`. Content root is usually CurrentDirectory. Content root is logged at the start of the application, do you have a way of checking those logs?

**Comment by wis3guy** [comment]
@Tratcher I'm sorry, but i'm no longer working on that particular (client) project, that was 6(!) months ago. My workaround, described above, is still working like a charm though. Did my sample project not help?

**Comment by Tratcher** [comment]
No problem, we'll take a look at the repro. I just didn't have a mac handy at the time.

**Comment by davidfowl** [comment]
Does this still repro?

**Comment by Tratcher** [comment]
Rereading this the script:
```
cd StaticFileIssue
dotnet publish -o ../dist/ -r osx.10.11-x64
cd ../
./dist/StaticFileIssue
```
It's running the app from the parent directory, so the content root which defaults to the current directory is likely wrong.

**Comment by davidfowl** [comment]
@wis3guy 2 years later, there's your answer. This is by design (unfortunately). The directory that static files is based on by default is the current working directory.

**Comment by wis3guy** [comment]
@davidfowl You made me grin with the 2 years later remark. :)
