### ISSUE TITLE
Typing a newline after @section name { results in a bad smart indent.

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#6679]
### Describe the bug
Original VS issues: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/734823 and https://devdiv.visualstudio.com/DevDiv/_workitems/edit/767171

This is due to WTE not being able to wait for the latest SyntaxTree from us (perf issues) before calling `GetDesiredIndentation`. The fix for this most likely will involve a new API of some sort to ensure expectations on both sides are met; however, the requirement is that the API must be callable from the foreground thread.

### To Reproduce
1. `@section name {|}`
2. Hit enter at the pipe 

### Expected behavior
You get smart indented 4 indentation spaces and it looks like:
```
@section name {
    |
}
```

What actually happens is smart indent does nothing so it looks like:
```
@section name {
|
}
```

**Comment by mkArtakMSFT** [comment]
@NTaylorMullen is this fixed?

**Comment by NTaylorMullen** [comment]
Hmm, not sure. @ToddGrun ?

**Comment by mkArtakMSFT** [comment]
The interactions with the Editor are changing completely so closing this as it'll be reset.

**Comment by ToddGrun** [comment]
FYI: Just fixed this on the WebTools side, should be fixed in 17.0 Preview 2.
