### ISSUE TITLE
 ASP.NET Core SignalR native iOS clients?

### ISSUE THREAD

**Issue by setli** [dotnet/aspnetcore#6783]
Hi , I was wondering is there any hope that we will get native iOS (Swift/Object-C) and Android (Java) clients?  think

**Comment by jkotalik** [comment]
The Java client is already available for use: https://docs.microsoft.com/en-us/aspnet/core/signalr/java-client?view=aspnetcore-2.2.
There is a open source (non-microsoft supported) Swift client here: https://github.com/moozzyk/SignalR-Client-Swift

**Comment by setli** [comment]
@jkotalik Thank you for your reply , Does Microsoft have plans to support IOS(Swift and Object-C) Native client ?

**Comment by jkotalik** [comment]
@bradygaster to respond.

**Comment by davidfowl** [comment]
Yes we plan to offer an iOS client.

**Comment by bradygaster** [comment]
As @davidfowl commented we are planning an iOS client to support native development. We are debating between Swift and Obj-C at the moment, leaning in the Obj-C direction. Open to thoughts on this.

**Comment by bbowman** [comment]
@bradygaster @davidfowl Personally would be in favor of ObjC due to better native interop. My ideal vision here would be to get a C++ client ship able (how is that going btw? I see its still listed as unsuported?) and then use something like xlang(https://github.com/Microsoft/xlang) to get some language projections. @devhawk as well.

My team (https://github.com/Microsoft/project-rome) would be highly interested in using a native + cross plat friendly SignalR lib

**Comment by bradygaster** [comment]
@bbowman the C++ work is going well, @BrennanConroy is spending most of his awake-life dedicated to making sure C++ and SignalR are good friends soon. 

Your comments on Obj-C are appreciated. TBH, the obj-c versus swift discussion *almost* feels like an exercise in yes/no statistics, wherein we'll eventually get to a 50/50 split. :) I am interested in all this feedback, however - do you foresee any objection on either side of the ObjC/Swift discussion?

**Comment by bbowman** [comment]
I guess what I will say is this, probably most folks will want to use the lib from Swift and there is a decent interop story with Swift and ObjC. ObjC has better native interop so it probably depends on what makes your engineering life easier since swift is a "nicer" language but you may get great code reuse with your C++ work.

**Comment by clayellis** [comment]
Now that Swift has reached ABI stability (and soon module stability), I think the "immaturity" argument against Swift has lost most of its steam. Definitely interested in seeing a native iOS client.

**Comment by bradygaster** [comment]
@clayellis we are leaning in the Swift direction per our last conversation on the topic. Have you tried any of the OSS clients out there available for iOS? Would that be an option for you if we can't get it done in time for your requirements?

**Comment by clayellis** [comment]
Glad to hear that. Yes, actually — I'm using [SwiftSignalRClient](https://github.com/moozzyk/SignalR-Client-Swift) at the moment. It's a pretty decent client and does the job.

**Comment by bradygaster** [comment]
I'd love to hear more about your experience with the client and any others you've used. Any chance you'd have some time to chat the week of June 17?

**Comment by clayellis** [comment]
I'd be glad to give some feedback — pick a time that week? My schedule is pretty flexible so I'll work around yours.

**Comment by bradygaster** [comment]
Appreciate the opportunity to sync up, @clayellis. I'd like to get an email address so I can send you an invite. Looking forward to it, will be mid-week next week.

**Comment by clayellis** [comment]
@bradygaster clayellis@me.com

**Comment by mijmattson2** [comment]
Has any progress been made on a Microsoft supported iOS client? If that is underway, any idea when it might be released?

**Comment by davidfowl** [comment]
> Has any progress been made on a Microsoft supported iOS client? If that is underway, any idea when it might be released?

No there's nothing underway at the moment. We're currently planning for the next release at it is under consideration.
