### ISSUE TITLE
Blazor JSRuntime should have <JavascriptRef>

### ISSUE THREAD

**Issue by christoph68** [dotnet/aspnetcore#6815]
It would be great to have something like JavascriptRef.

Often interop code is awkward because no references to JS classes are possible. There needs to be a static function that does then identify the instance to be used/called.

a reference could be obtained like:
JavascriptRef jsRef =JSRuntime.Current.GetReference("JSFuncGet", args);

and then re-used:
JSRuntime.Current.InvokeAsync(jsRef , "JSFuncCall", args)

Looking at Microsoft.JSInterop.ts (module DotNet), it seems that should be possible to achieve?
It surely would ease build wrappers around existing JS libs/components.

**Comment by pranavkm** [comment]
This was resolved as part of the JSObjectReference work that was added in 5.0-rc1. Closing this as a dupe.
