### ISSUE TITLE
Caching per-request objects on reused HttpContexts

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#6895]
ASP.NET Core 3 adds HttpContext reuse - [Reuse HttpContext object per HTTP/1 connection and HTTP/2 stream](https://github.com/aspnet/AspNetCore/pull/6424)

App frameworks and middleware often have their own objects that are allocated every request. Instead of app frameworks/middleware caching with a shared object pool (creating thread contention), what opportunities are there for to cache lightweight per-request objects on `HttpContext`?

Because cached objects would eventually be on every HttpContext this functionality should only be used for lightweight objects, and not something large like buffers.

e.g. generated gRPC methods have objects passed to them like a stream reader, stream writer and context - `Task SayHellos(HelloRequest request, IServerStreamWriter<HelloReply> responseStream, ServerCallContext context)`. These objects are mostly wrappers over the underlying HttpContext.

* Before: IServerStreamWriter and ServerCallContext are allocated every request
* After: IServerStreamWriter and ServerCallContext are fetched from the `HttpContext`. App framework will create and cache them if they don't exist, or reset the existing instances for the current `HttpContext`.

**Comment by JamesNK** [comment]
@davidfowl

**Comment by davidfowl** [comment]
I think resettable features is the feature here. A feature can opt into controlling creation and reset.

**Comment by JamesNK** [comment]
> Could have a cache that drops any object from the pool if it wasn't requested during that request; so it would only live on for 1 request (or a parameterised number e.g. if not used for x Requests then drop)

That's a clever idea. It could be something a feature could track, e.g. each time it is reset it could increment an "unused" counter by 1, when it is "used" then it goes back to zero, and if it is reset and the counter exceeds a number then heavy objects are culled (or could a feature remove itself from its HttpContext?).

> I think resettable features is the feature here. A feature can opt into controlling creation and reset.

What happens to features currently when the HttpContext is reused?

I don't know if this is a thing to worry about but imagine a web app that uses lots of middleware and app frameworks. Eventually there would be a lot of reset-able features in the mix on the `HttpContext`. Could the time spent each request resetting those features have an impact?

**Comment by JamesNK** [comment]
Profiling gRPC and the largest allocation is the gRPC context. Caching this would almost halve allocated memory.

![image](https://user-images.githubusercontent.com/303201/54496790-85ef3080-48b0-11e9-92e5-55553ef69983.png)

**Comment by jkotalik** [comment]
@JamesNK is there anything left here that we'd consider caching or does most of the perf work we did in 3.1/5.0 cover this?

**Comment by JamesNK** [comment]
This is still useful IMO
