### ISSUE TITLE
Scaffolding for Razor Components

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#6921]
It should be possible to scaffold a CRUD UI in much the same way as for MVC.

**Comment by danroth27** [comment]
Maybe something like: https://api-platform.com/docs/client-generator/react/

**Comment by AniAchar** [comment]
@SteveSandersonMS  I would like to pick this issue up as part of the July 2020 sprint.

**Comment by johnmagesh** [comment]
This will be a great feature to have and would make development faster and would attract more audience.

**Comment by mkArtakMSFT** [comment]
This is now supported by VS.
