### ISSUE TITLE
Switch symbols output to snupkg format

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/aspnetcore#6940]
The .snupgk format is more efficient than the .symbols.nupkg format because it only includes .pdbs. It doesn't also include the .dll files and source code, which are unnecessary in most usages due to source-link and the way .symbols.nupkg files are actually handled by our CI.

Changing formats should be a matter adding `<SymbolPackageFormat>snupkg</SymbolPackageFormat>` to Directory.Build.props and ensuring that the .snupkg files end up in the right locations (blob storage, drop shares, symbols servers, etc.)

**Comment by natemcmaster** [comment]
_Triage team:_ let's discuss first with Arcade about how we should handle symbols.

**Comment by JunTaoLuo** [comment]
@dotnet/dnceng Is there a concerted effort to do this across all teams?

**Comment by adiaaida** [comment]
We will also need to update all of our symbols/sourcelink validation scripts at the same time, so that we look for the right file types.

**Comment by riarenas** [comment]
One consideration is that some internal Microsoft tooling require the dlls to be submitted to the symbol servers for indexing. If the new format does not include the dlls, we'll have to tweak the publishing infra to keep submitting them.

**Comment by dougbu** [comment]
`External` and blocked until Arcade does the needful

**Comment by dougbu** [comment]
@markwilkie @riarenas are there any plans to do the needful in Arcade❔ If not, we should close this issue&hellip;

**Comment by dougbu** [comment]
I don't remember the whole history but believe .snupkg packages were smaller, perhaps not containing the assemblies as well as the symbol files❔ @aortiz-msft @DoRonMotter was this a NuGet push and is it still the direction we should be moving❔

**Comment by mmitche** [comment]
I believe the .snupkgs are also pushed to the nuget server, in addition to the normal symbol servers. Note that this appears to be only applicable to nuget.org servers.

https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg

I think we should identify whether there is an experience gap for our customers before we go off and implement this. @hoyosjs who might be an expert in this area?

**Comment by markwilkie** [comment]
Thanks @hoyosjs !

Unless someone thinks differently on this, I'm inclined to close this issue as won't fix for now.  Thoughts?

**Comment by dougbu** [comment]
WFM @markwilkie 

we can always reopen if the arithmetic changes or we get new information
