### ISSUE TITLE
DataProtection storage from DI

### ISSUE THREAD

**Issue by leastprivilege** [dotnet/aspnetcore#6947]
Wouldn't it make sense to resolve the storage provider for data protection keys from DI in the future?

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
