### ISSUE TITLE
2.x: backport src/Templating to build with ProjectRef

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/aspnetcore#6966]
Backport https://github.com/aspnet/AspNetCore/pull/6935 to 2.1 and 2.2.
Depends on https://github.com/aspnet/AspNetCore-Internal/issues/1341 and https://github.com/aspnet/AspNetCore-Internal/issues/1338.

The primary benefit of backporting this change is to simplify the build. The src/Templating/ subfolder is built as if it were a separate git submodule. This means it builds with is own unique build context, variables, MSBuild processes, logs, etc. Removing this approach would allow us to greatly simplify the build targets and tasks require to produce template packages.

**Comment by JunTaoLuo** [comment]
Given it's 2.x, I don't think it's worth the effort.
