### ISSUE TITLE
Dotnet-Watch Restart On Enter Pressed

### ISSUE THREAD

**Issue by DrakeLambert** [dotnet/aspnetcore#6989]
### Describe the solution you'd like
I do a lot of razor pages development. When razor runs into a compilation error, dotnet-watch will wait for a file change to restart, but it doesn't watch razor files. I understand that this is desired behavior, but I would like to be able to just press enter to trigger a restart instead of having to restart the watch.

### Describe alternatives you've considered
Usually, I will use `[ctrl] + [c]`, then `dotnet watch run` again.

### Additional context
![image](https://user-images.githubusercontent.com/17054016/51693279-46991780-1fc4-11e9-994a-befe3b06efaa.png)
This will never restart automatically.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
As of ASP.NET Core 3.0 dotnet watch will also watch .cshtml files for changes.
