### ISSUE TITLE
Consider creating ECDSA based certificates when using dev-certs

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/aspnetcore#7044]
While working on https://github.com/aspnet/KestrelHttpServer/issues/3027, I found that on Windows 8.1 and Windows Server 2012R2 seems to require a certificate generated using an Elliptical Curve based key algorithm to be able to successfully negotiate a cipher suite during TLS handshake for HTTP/2. The current dev-certs tool generate a certificate using the RSA algorithm which will not work by default on Windows 8.1 and Windows Server 2012R2. Note that the default RSA based certificate seems sufficient on Windows 10 for HTTP/2. 

Ideally, the dev-certs tool should be updated to produce certificates that can support HTTP/2 on Windows 8.1 and Server 2012R2. I'm not sure if creating  hybrid RSA/ECDSA certificate or adding a switch to configure using RSA vs ECDSA would be the best approach here so I'll defer to the experts cc @blowdart @javiercn. 

Alternatively, I could manually generate a ECDSA based certificate manually via powershell or dotnet apis (or third parties? though I haven't tried any). However, it's usually not obvious which settings to use so adding this functionality to dev-certs would be more user-friendly.

**Comment by mkArtakMSFT** [comment]
@blowdart is this still important? Should we close this or do you want us to do generate the cert that's more inline with TLS 1.3? If so, please clear the milestone for triage.

**Comment by blowdart** [comment]
If HTTP2 works on Win10, then I'd let this drop away. Win2012 R2 is now in extended support, so if a customer has problems they should engage us through their extended support folks.

Closing.
