### ISSUE TITLE
AnchorTagHelper: automatically add active class

### ISSUE THREAD

**Issue by neville-nazerane** [dotnet/aspnetcore#7049]
The anchor tag helper has properties like `action` and `page` and has access to the current action/page. This tag helper adding the "active" class into the `<a>` if the specified action/page matched the current action/page would be quite handy compared to its currently ugly alternates. While this can't be implimented by default in all anchor elements, there can always be a boolean property like `AspActive`.

**Comment by mkArtakMSFT** [comment]
Reopening as @Ducki posted a similar ask.

**Comment by Ducki** [comment]
To address this issue, I made a nuget package that adds this functionality via a tag helper: https://www.nuget.org/packages/ActiveTagHelper/

As [suggested](https://github.com/dotnet/aspnetcore/issues/39316#issuecomment-1005922064), I'll work an a PR for this.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
