### ISSUE TITLE
Remove obsolete member in src/Http/Http/src/HttpContextFactory.cs

### ISSUE THREAD

**Issue by muratg** [dotnet/aspnetcore#7148]
Remove this obsolete member in [src/Http/Http/src/HttpContextFactory.cs](https://github.com/aspnet/AspNetCore/blob/master/src/Http/Http/src/HttpContextFactory.cs#L11):

```c#
    [Obsolete("This is obsolete and will be removed in a future version. Use DefaultHttpContextFactory instead.")]
    public class HttpContextFactory : IHttpContextFactory
    {
```

And file a new issue in https://github.com/aspnet/Announcements/issues/ if this is a notable breaking change.

**Comment by Tratcher** [comment]
@muratg this type was only made obsolete in 3.0 preview2. Are we ok removing types that were not obsolete in 2.2? Note we do not expect people to have been using this type.

**Comment by muratg** [comment]
Thanks for the update - Let's keep it obsolete in 3.0 then. We'll remove this in a future release.
