### ISSUE TITLE
Remove obsolete member in src/Middleware/StaticFiles/src/StaticFileResponseContext.cs

### ISSUE THREAD

**Issue by muratg** [dotnet/aspnetcore#7149]
Remove this obsolete member in [src/Middleware/StaticFiles/src/StaticFileResponseContext.cs](https://github.com/aspnet/AspNetCore/blob/master/src/Middleware/StaticFiles/src/StaticFileResponseContext.cs#L15):

```c#
        [Obsolete("Use the constructor that passes in the HttpContext and IFileInfo parameters: StaticFileResponseContext(HttpContext context, IFileInfo file)", false)]
        public StaticFileResponseContext()
        {
```

And file a new issue in https://github.com/aspnet/Announcements/issues/ if this is a notable breaking change.

**Comment by Tratcher** [comment]
@muratg The same with this one, the Obsolete was added in 3.0 preview1 (?). This was also not a type we expected anyone to use directly.

**Comment by muratg** [comment]
Thanks for the update - Let's keep it obsolete in 3.0 then. We'll remove this in a future release.
