### ISSUE TITLE
Add benchmarks for auth infrastructure and hot paths

### ISSUE THREAD

**Issue by Tratcher** [dotnet/aspnetcore#7162]
One area we haven't tried to benchmark yet is AuthN and AuthZ.

High priority as these happen on most requests:
- AuthenticationMiddleware, handler resolution, etc..
- Authorization policies
- Cookie Auth, decrypting, deserializing, and verifying
- Jwt bearer auth, deserializing, and verifying

Low priority, these only happen on a small percentage of requests:
- Cookie creation and refresh, seralizing, encrypting
- OAuth and OIDC challenges and logins

**Comment by davidfowl** [comment]
Putting this in a specific preview so it doesn't happen at the end when we can't react.

**Comment by Eilon** [comment]
Moving to a later preview. We should at least check Cookie Auth because it runs on every request. The other middlesware don't run as often so we're less concerned about their per-request perf.

**Comment by davidfowl** [comment]
We should still know the performance of the code we wrote. Some of it was just lazy and could easily be better even if its doesn’t happen as often. 

What about JWT?

**Comment by Eilon** [comment]
We're trying to prioritize the work, so we're open to adjusting priorities based on feedback.

**Comment by davidfowl** [comment]
We should do both JWT and Cookie then. Both Microbenchmarks and Full end to end benchmarks.

**Comment by rynowak** [comment]
I hope you're ready to be sad about the perf of the JWT code 😆

**Comment by Pilchie** [comment]
@sebastienros and @HaoK haven't you been looking at this already?

**Comment by HaoK** [comment]
Yep dupe of https://github.com/dotnet/aspnetcore/issues/27220
