### ISSUE TITLE
Support HostedServices in Blazor

### ISSUE THREAD

**Issue by endeffects** [dotnet/aspnetcore#7213]
The wire up for the HostedServiceExecutor is missing in Blazor.

**Comment by rynowak** [comment]
What do you need this for? We intentionally don't pull in these dependencies and we don't currently plan to do so because of the size impact.

**Comment by endeffects** [comment]
I'm listening for SignalR Notifications in the Background.

**Comment by davidfowl** [comment]
We should figure out if we can refactor some of the abstractions assemblies to lessen the impact. It would be unfortunate to introduce an IHostedService light into Blazor apps specifically. One solution might be to move the IHostedService definition to another assembly (but I’m just brainstorming here)

**Comment by javiercn** [comment]
Another option is to setup and tear down the background service on the root component

**Comment by rynowak** [comment]
> We should figure out if we can refactor some of the abstractions assemblies to lessen the impact.

The big ones to address - banish FileProviders into the nether realm - it's not useful in our context and is just bloat. Get rid of the dependency of Configuration -> Primitives.

**Comment by davidfowl** [comment]
> The big ones to address - banish FileProviders into the nether realm - it's not useful in our context and is just bloat. Get rid of the dependency of Configuration -> Primitives.

If we could avoid breaking too much that would be best. Is it the primitives reference causing most of the problems?

**Comment by rynowak** [comment]
Yes. 

Another way to think of this might be to provide a sample of how to make a "generic host Blazor app". I'm still pretty concerned even if we get this down to like 50kb and include it on the default path.

**Comment by davidfowl** [comment]
OK lets at least try to work on it. I know you spent some time here but we have more time in 3.0.

**Comment by koliyo** [comment]
> Another option is to setup and tear down the background service on the root component

This seems like the best option right now. It is then possible to render an initial GUI with some loading indicator.

Something like this can be used

```blazor
    <div class="main-content">
        @if (!hasConnection) {
          <Heading Size="HeadingSize.Is2">Setting up server connection</Heading>
        }
        else {
            @Body
        }
    </div>


@code {
    bool hasConnection = false;

    protected override async Task OnInitializedAsync() {
        // Start signalR client here instead of Program.cs to avoid blocking with `Loading...` screen
        hasConnection = false;
        await client.Start();
        hasConnection = true;
    }
}
```

**Comment by dazinator** [comment]
Hosted services could be an optional package, and work similar to @koliyo explained but is a component you can add in `App.razor` or your main layout:

The component could look something like:

```
@inject IEnumerable<IHostedService> HostedServices
@implements IDisposable

[Display Child Content Here Shown Whilst Starting Services]

code
{
    protected override async Task OnInitializedAsync()
    {     
          var cts = new CancellationTokenSource();
          await Task.WhenAll(HostedServices.Select(s => s.StartAsync(HostedServicesCancellationToken.Token)));
    }
 
    public void Dispose()
    {
          // make sure services are stopped...
    }
}

```

As far as I can tell all you'd need is a package containing:

1. This Blazor component
2. `IHostedService` interface

Users would add the above component to App.razor or MainLayout, and then just register some `IHostedService`'s in Program.cs

**Comment by dazinator** [comment]
Some areas of slight concern though - I don't think the Blazor WebAssembly Host has a clear concept of a lifetime, with cancellation tokens etc. 

1. If possible, I'd like to have the ability / chance, to signal hosted services to stop before the web assembly application was reloaded i.e via a page reload() or a browser tab close().

**Comment by abspro** [comment]
@davidfowl @rynowak Is there still hope for this?  Was just thinking this would be really cool to have.

**Comment by dazinator** [comment]
I've used the component approach shown above successfully. Use case: Suppose you have two pages in your blazor app, the home page has some static content, and a grid page that does real time updates. Most visitors only see the home page. When a user goes to visitor page you want that page to establish a websocket connection to backend server for real-time updates of grid. You want that websocket connection to be disposed when they navigate away from that page. You could of course just use that pages OnInitialisedAsync() method to perform your async logic, and have it implement IDisposable to dispose of that connection. However suppose you then add another page that also needs to do the same thing. If your websocket connection is instead managed by an IHostedService and you use a component to initialise the IHostedService (and dispose of it) you can compose your app with IHostedServices in the mix, either surrounding specific pages, or sets of pages (via layouts) or globally (by incorporating the component at App level) so pages can be agnostic of background service management but can operate within scopes where background services should be present.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
