### ISSUE TITLE
Https redirect not working with Kestrel hosted server when using ports.

### ISSUE THREAD

**Issue by quintonn** [dotnet/aspnetcore#7215]
### Describe the bug
I am trying to run a console application that hosts a kestrel server.
I set up my server to listen to http and https on different ports.
I've setup https redirection to test that a controller which requires https will be redirected if a call is made to http only.
But currently the redirect is made, but the port is discarded.
Strangely, i have a unit test using TestServer with the same scenario, and it works fine.

### To Reproduce
1. Using this version of ASP.NET Core '2.2'
2. My Program.cs looks like this:

```c#
    public class Program
    {
        public static void Main(string[] args)
        {
            new WebHostBuilder().UseStartup<Startup>()
             .UseKestrel()
             .UseUrls("https://localhost:5000", "http://localhost:5005")
             .Build()
             .Run();
        }
    }
```
3. My Startup.cs:

```c#
    public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvcCore();
            services.AddHttpsRedirection(options =>
            {
                options.HttpsPort = 5000;
            });
        }
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            app.UseMvc();
            app.UseHttpsRedirection();
        }
    }
```

4. My controller:

```c#
    [Route("basic")]
    public class BasicController
    {
        [Route("test1")]
        public IActionResult Test1()
        {
            return new OkObjectResult("Ok, it works");
        }
        [Route("test2")]
        [RequireHttps]
        public IActionResult Test2()
        {
            return new OkObjectResult("Ok, it works");
        }
    }
```

### Expected behavior
I expect to browse to http://localhost:5005/basic/test2 and be redirected to 
https://localhost:5000/basic/test2

### Actual behavious:
I am redirected to https://localhost/basic/test2.
The port number is removed completely.

### Additional context
`dotnet --info` give me this:

> .NET Core SDK (reflecting any global.json):
 Version:   2.2.103
 Commit:    8edbc2570a
Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.103\
Host (useful for support):
  Version: 2.2.1
  Commit:  878dd11e62
.NET Core SDKs installed:
  1.0.0-preview2-003131 [C:\Program Files\dotnet\sdk]
  1.0.0 [C:\Program Files\dotnet\sdk]
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.200 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.2.103 [C:\Program Files\dotnet\sdk]
.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

PS. Sorry i couldn't get the formatting for the sample code right. Not sure what to do here.

**Comment by quintonn** [comment]
I figured out a workaround.
If I change my call `services.AddMvcCore()`
to this:
`services.AddMvcCore(x => x.SslPort = 5000);`
Then the https redirection is working.

This seems redundant. I'm setting the same setting on more than 1 place and it also seems to be ignored in one place.

Should one or the other setting not be removed then?
And since this is the issue, the call to `app.UseHttpsRedirection();` also seems to not do anything.
The https redirection works with and without it.

**Comment by Tratcher** [comment]
Remove `[RequireHttps]`, that's not needed with UseHttpsRedirection. Check your application logs to see what's going on in UseHttpsRedirection.

**Comment by quintonn** [comment]
Removing [RequireHttps] does nothing but break the https redirection, and doesn't enforce an https url on my route.
I've got one method which i want to expose over http and a different one over https.
If i accidentally enter http in my url for the https-only method, it should redirect.
It currently works as is, the problem is that there is an undocument (seemingly unrelated) setting I have to add to get it all working. And that is the SslPort thing.

**Comment by quintonn** [comment]
I've created a test project on github explaining and showing this issue:
https://github.com/quintonn/httpsredirectiontest

**Comment by Tratcher** [comment]
You cannot use UseHttpsRedirection if you want to expose any http endpoints, it applies site wide redirection.

Endpoint specific HTTPS restrictions are discouraged in favor of site wide redirection.

If you're having trouble with UseHttpsRedirection you need to check your app logs.

**Comment by quintonn** [comment]
Endpoint specific https is somewhat secondary.
The call UseHttpsRedirection seems to not work.
The main issue is with the sslport setting inside UseMvcCore which is required to get https redirect to **work at all**.
Where/how do I see app logs?

**Comment by Tratcher** [comment]
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.2

Note UseHttpsRedirection is a new system unrelated to the old RequireHttps & SslPort system.

**Comment by quintonn** [comment]
UseHttpsRedirection is a new system?
How does one use it then? It seems the old RequireHttps & SslPort is taking precedence over UseHttpsRedirection.

**Comment by quintonn** [comment]
Ok, i've got logging and if I remove the SslPort inside AddMvcCore i see the following when I browse to the URL using HTTP and get redirected to https but without a port number.

> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5020/basic/test2
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Route matched with {action = "Test2", controller = "Test"}. Executing action HttpsRedirectionTest.Controllers.TestController.Test2 (HttpsRedirectionTest)
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[3]
      Authorization failed for the request at filter 'Microsoft.AspNetCore.Mvc.RequireHttpsAttribute'.
info: Microsoft.AspNetCore.Mvc.Infrastructure.RedirectResultExecutor[1]
      Executing RedirectResult, redirecting to https://localhost/basic/test2.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action HttpsRedirectionTest.Controllers.TestController.Test2 (HttpsRedirectionTest) in 0.195ms
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 0.3972ms 302

This shows me nothing i didn't know. 
The request is getting redirected without a port number.

All I'm trying to do is figure out what is the correct way to set up https redirection.
And based on what i've found so far, is that the documentation does not match with what i have to do.

**Comment by quintonn** [comment]
I've updated [my test repository](https://github.com/quintonn/httpsredirectiontest) with the 2 scenarios i'm running. 
So to recap, there seems to be 2 problems:
1. In scenario 1, https redirection works as i expect, **except** for the fact that I have to explicitly add the ssl port required for https redirection.
2. In scenario 2, just http endpoints don't work, at all.

In theory, i guess http shouldn't be used really, so it would make both scenarios irrelevant.
**But**, from a functional point of view, this should be possible using .net, should it not?

So if a user insists on having both http and https endpoints, one can go with scenario 1. But the fact that one has to explicitly set the sslport seems incorrect. 
If I want to change my ports using "UseUrls()", i could read that value from a config file, but changing the sslport setting becomes unnecessary overhead i believe.
Also, what if I want to use more than 1 port for each of http/https. I just did a test and using scenario 1 (from my repo), all http redirections are redirected only to the port set using SslPort setting. 
Which I believe is wrong.

**Comment by Tratcher** [comment]
Scenario 2 is the recommended one and it seems like you've gotten it working as expected? Note UseHttpsRedirection belongs inside of the scenario 2 code block, it's has no bearing on scenario 1.

Yes, scenario 1 required setting SslPort, that's how the old system was designed. We're not planning any improvements here since scenario 2 is the recommended one.

For any further questions please pick a scenario and stick to it, mixing confusing and unsupported.

**Comment by quintonn** [comment]
Thanks,
But the problem with scenario 2 is i can't have both http and https endpoints.

**Comment by Tratcher** [comment]
So you're using Scenario 1 and everything works except you have to set SslPort?

**Comment by quintonn** [comment]
yes.

**Comment by Tratcher** [comment]
Then it's working as intended. I understand not wanting to hardcode the port in code, but setting it from config is the only other suggestion I have for you.

We don't plan to make changes here as Scenario 2 is our official guidance.

**Comment by quintonn** [comment]
The main reason i raised this issue is that it was unclear which of the code to use. 
There could maybe be a deprecated warning or something like that then?

Also, you mentioned scenario 2 is the way going forward. So that means it will become impossible to have both https and http endpoints, with redirection on the https endpoints?

**Comment by Tratcher** [comment]
Mixing http and https is discouraged but not deprecated, we're aware of a few cases where you might need to do it. The [docs](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-2.2&tabs=visual-studio) and templates give strong guidance towards scenario 2 already, but maybe we could update the doc comments on RequireHttps to indicate the preference as well.
