### ISSUE TITLE
[Flacky test]Microsoft.AspNetCore.Identity.EntityFrameworkCore.InMemory.Test.Microsoft.AspNetCore.Identity.EntityFrameworkCore.InMemory.Test.InMemoryEFUserStoreTestWithGenerics.EmailFactorFailsAfterSecurityStampChangeTest

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#7345]
This test failed for no apparent reason in a completely unrelated PR.

**Comment by javiercn** [comment]
@Eilon @HaoK

Assert.False() Failure
Expected: False
Actual: True

Stack trace
   at Microsoft.AspNetCore.Identity.Test.UserManagerSpecificationTestBase`2.EmailFactorFailsAfterSecurityStampChangeTest() in /_/src/Identity/Specification.Tests/src/UserManagerSpecificationTests.cs:line 1850
--- End of stack trace from previous location where exception was thrown ---

**Comment by Eilon** [comment]
Is it possible to link to the failure? What platform was it on?

**Comment by javiercn** [comment]
Mac OS. I retriggered the build, let me see if I can get the failed one back. There wan't much information though

**Comment by HaoK** [comment]
Wonder if its related to https://github.com/aspnet/AspNetCore/issues/6942 I can add some more logging to this test to at least print out the token and expected token

**Comment by HaoK** [comment]
@ajcvickers @blowdart note: this actually seems like a potential issue here, updating the security stamp should invalidate tokens, here's the relevant test code.  There's not actually anything I can log that would help other than a more useful error message, its bad if the token is still valid after updating the stamp...  its a real assertion/functional failure at that point.  

```
            token = await manager.GenerateTwoFactorTokenAsync(user, factorId);
            Assert.NotNull(token);
            IdentityResultAssert.IsSuccess(await manager.UpdateSecurityStampAsync(user));
            Assert.False(await manager.VerifyTwoFactorTokenAsync(user, factorId, token));
```

**Comment by Eilon** [comment]
@HaoK - can you start a mail thread?

**Comment by HaoK** [comment]
Mitigation PR merged https://github.com/aspnet/AspNetCore/pull/7364 if we still see this fail, we will need to dig deeper

**Comment by halter73** [comment]
This failed again in the same way.

```
Assert.False() Failure
Expected: False
Actual:   True

Stack trace
   at Microsoft.AspNetCore.Identity.Test.UserManagerSpecificationTestBase`2.EmailFactorFailsAfterSecurityStampChangeTest() in /_/src/Identity/Specification.Tests/src/UserManagerSpecificationTests.cs:line 1660
--- End of stack trace from previous location ---
```

https://dev.azure.com/dnceng/public/_build/results?buildId=847479&view=ms.vss-test-web.build-test-results-tab&runId=26992440&resultId=105276&paneView=debug

**Comment by HaoK** [comment]
https://github.com/dotnet/aspnetcore/commit/f54b590804ecacc328d9050ee1bdbaede9fb57a1#diff-edc31700ffeaf37eb919ab376b59df85b495cef6c49dcee3320b6e4cb757e5b9 should help and this test is no longer quarantined currently already
