### ISSUE TITLE
Model validation takes capitalization of property name from route parameter

### ISSUE THREAD

**Issue by poke** [dotnet/aspnetcore#7457]
When using model validation on a route that also has a router parameter with the same name as a validated property inside the model, a model validation error will copy the capitalization from the route parameter. So the validation error appears to be for the route parameter instead of the model property.

```c#
[Route("foo/{id}")]
public IActionResult Test(int id, MyModel model)
    => Json(ModelState); 

public class MyModel
{
    [Range(1, 100)] // range validation to force an error for default values
    public int Id { get; set; }
}
```

When running the above action in the browser by accessing e.g. `http://localhost:5000/foo/123`, the `ModelState` only contains a single item `id` with the error from the `RangeAttribute`.

If you however change the action to use a different name for the route parameter, then there are two separate entries in the `ModelState`, with `Id` being correctly capitalized to match the model’s property name.

```c#
[Route("foo/{id2}")]
public IActionResult Test(int id2, MyModel model)
    => Json(ModelState);
```

I’ve found this bug through a unit test that checked a validation on the model’s `Id` parameter. Because the action had an `id` route parameter, my test that checked for a key `nameof(MyModel.Id)` failed.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @poke.
@pranavkm, can you please look into this? Thanks!

**Comment by pranavkm** [comment]
Lookups in `ModelStateDictionary` as with most dictionary types in MVC are case insensitive. Validation is performed for the `id` argument first simply because it appears earlier than the other parameter, and results in creating an entry with lowercase `id`. I guess namespacing the second parameter using `model.Id` might be a better way to distinguish between the two entries rather than relying on the casing.

**Comment by dougbu** [comment]
Since `ModelState` lookups are case-insensitive, what problem are you seeing exactly @poke?

For example, are you iterating through the dictionary and performing a case-sensitive comparison? (That would violate the intended `ModelState` case-insensitive semantics.)

**Comment by poke** [comment]
In my particular situation, I return the model validation errors as `ProblemDetails`, so inside of my integration tests, I want to verify that that a certain model validation error was reported for an invalid property. I did that doing `Assert.True(errors.ContainsKey(nameof(MyModel.Id)))` where `errors` is a parsed `IDictionary<string, JToken>`.

The issue I had with this is that tests were failing just because of a route having a route argument named `id` when I am not even validating that at that point. So now I have the above assert in some places, and an `Assert.True(errors.ContainsKey("id"))` in other places.

While I understand the underlying reasoning behind this, it bothers me that this is so inconsistent just because of a route parameter.

If the `ModelState` keys are supposed to be case-insensitive, then maybe the keys should be normalized so that we can get a deterministic result when the model state is being passed elsewhere?

**Comment by pranavkm** [comment]
> If the `ModelState` keys are supposed to be case-insensitive, then maybe the keys should be normalized so that we can get a deterministic result when the model state is being passed elsewhere?

Changing that in general is going to a breaking change with little to gain for most users. We could consider it specifically for `ProblemDetails` \ `ValidationProblemDetails` - process the keys in `ProblemDetails.Extensions` and `ValidationProblemDetails.Errors` to use the contract resolver i.e. effectively treat it as `ProcessDictionaryKeys = true`.  

cc @khellang \ @rynowak for thoughts on this

**Comment by khellang** [comment]
This has been annoying me for years (there's quite a few issues on it as well), so if we could solve this through `ProblemDetails`, it would be awesome 👍

**Comment by danroth27** [comment]
Since this would be a breaking change, I'm inclined to just close this one. @glennc Thoughts on this?

**Comment by mkArtakMSFT** [comment]
Closing per @danroth27 's comment above.
