### ISSUE TITLE
[Components][Tooling] Define a gesture to mark a component as a "root" component

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#7526]
This component will only ever be prerrendered and will be used as the entry point for the entire application. When this is the case we will treat some aspects of the component differently. For example we will allow scripts to appear normally within the component without requiring `suppress-error="BL9992"`

```razor
@* Alternative 1 *@
@root
@* Alternative 2 *@
@prerrendered
@* Alternative 3: Rely on the <!DOCTYPE html> declaration at the beginning of the file *@
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width">
    <title>Razor Components</title>
    <base href="/" />
    <link href="css/bootstrap/bootstrap.min.css" rel="stylesheet" />
    <link href="css/site.css" rel="stylesheet" />
</head>
<body>
    <app></app>
    <script src="_framework/components.server.js"></script>
</body>
</html>
```

**Comment by mkArtakMSFT** [comment]
Related: https://github.com/aspnet/AspNetCore/issues/7528

**Comment by javiercn** [comment]
@rynowak Do you have any input in here?

**Comment by rynowak** [comment]
What are the problems that need to be solved? Is it **just** the warning for scripts?

Like if you suppress the warning, is there anything blocking or wrong or bad? 

OR is there a general problem where you need to be able to separate prerender-only content from dynamically-updating content?

**Comment by javiercn** [comment]
It's essentially the scripts warning for now, but there are other tags that we should warn about on non-pre-rendered content. Some of which are `<base>, <link>, <meta>, <title>, <head>, <body>, <html>`.

In general pre-rendered content can be anything, non-pre-rendered content is more limited to things that go inside the `<body>` tag.

It can also be good to be able to mark a component as `pre-rended only` in order to provide better warning when it gets included in a non static context. Kind of like constexpr (do I get Ryan points for the C++ reference here?)

**Comment by javiercn** [comment]
Also things like '~/' or accessing the HTTP context, etc.

**Comment by javiercn** [comment]
We could probably change this https://github.com/aspnet/AspNetCore-Tooling/blob/master/src/Razor/src/Microsoft.AspNetCore.Razor.Language/Components/ComponentScriptTagPass.cs to be something more like `ComponentsAllowedTagsPass` or something similar.

We could introduce a couple of base classes
* ComponentDocumentBase
* StaticComponentBase

This way we cold have a gesture for 'root' components that is simply `@inherits ComponentDocumentBase` and a gesture for prerendered only content that is `@inherits StaticComponentBase`.

* StaticComponentBase represents using a component as a partial and does a few things:
  * Disables the `html, head, body, and doctype declaration tags`.
  * Enables the `script, link, title, meta, base tags.
  * Our implementation makes HttpContext available through the base class as a cascading parameter (that we include when we call RenderComponentAsync())
  * Makes "~/" resolve to the app virtual path.
  * Disallows using bind, event handlers and other features inside this component that are not going to work.
* DocumentComponentBase
 * Extends StaticComponentBase and enables the remaining tags

**Comment by SteveSandersonMS** [comment]
We pretty much do this now via `<component>` being able to render markers for both client and server-side root components.

As for the other things about `<script>` tags etc., it's not clear we'd want that now we've gone in different directions since this was first filed.

I'll close as I don't think this matches closely with our likely plans, but it could be reopened if I'm wrong!
