### ISSUE TITLE
[Components] Enable a root component to be the entry point for component based apps

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#7528]
This is a tracking issue for enabling applications that only use components end to end. Here we will discuss and track the work that needs to be done to enable this scenario:

- [ ] Support DOCTYPE declarations.
- [ ] Support a way to mark a component as a "root component" so that it can be used as the container for the entire app.
- [ ] Figure out a way to turn prerrendering on and off selectively.
- [ ] Figure out what component equivalents we need for things like the Environment tag helper, '~/' etc.
- [ ] Figure out specific integrations with endpoint routing.

**Comment by Andrzej-W** [comment]
The concept of "root component" is very nice. Please remember about SEO. Prerendered HTML page has to have correct title, description, metatags. More about this here: https://github.com/aspnet/Blazor/issues/1311#issuecomment-413046895

**Comment by mkArtakMSFT** [comment]
Closing as this should be already done.
