### ISSUE TITLE
Migration in Microsoft.AspNetCore.DataProtection.EntityFrameworkCore

### ISSUE THREAD

**Issue by MCFHTAGENTS** [dotnet/aspnetcore#7534]
I have previously implemented DataProtection in MVC Core using the file system provider
```
services.AddDataProtection(opt => opt.ApplicationDiscriminator = "xxxxxx") 
.PersistKeysToFileSystem(new DirectoryInfo(settings.DataProtection.KeyStorePath))
.ProtectKeysWithCertificate(settings.DataProtection.CertificateThumbprint);

```
I would like to migrate this to using the:
`https://www.nuget.org/packages/Microsoft.AspNetCore.DataProtection.EntityFrameworkCore/`
so that I can scale up to multiple servers and not rely on the filesystem.

Is there a documented approach for moving the physical keys?

**Comment by blowdart** [comment]
You're the first person ever to ask.  

Oh boy. @natemcmaster? In theory you'd take the contents of the XML file and write them into the EF fronted database, using the file name (with no extension) as the keyid. You'd still need the certificate for protection/unprotection.

**Comment by natemcmaster** [comment]
@blowdart's suggestion sounds right to me. Let us know how it goes.

**Comment by MCFHTAGENTS** [comment]
Thanks both - have finally got to having a look at this following your feedback. I have created my tables (with a bit of messing around as the sample 
([https://github.com/aspnet/Docs/blob/master/aspnetcore/security/data-protection/implementation/key-storage-providers/sample/MyKeysContext.cs]) passes in an `DbContextOptions<ApplicationDbContext>` in the constructor when it should, imo, pass in a `DbContextOptions<KeysContext>`

Looking at the proposed table design:
```
Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn)
```
It is, understandably, expecting Id to be an identity column. So it won't be as simple as doing an insert - can I discard the Id or is it referenced somewhere else?

Thanks
Mark

**Comment by MCFHTAGENTS** [comment]
Sorry - one other comment - there is a column 'Friendly Name' I the Database - any thoughts on what that should be set to? I can't see any human readable data in the XML file although I obviously could load the certificate and bring in some thing like a canonical name?

**Comment by MCFHTAGENTS** [comment]
I have ended up trashing my keys and recreating them in  the new location. I wonder if some thought could be given to this use case and if people (like me!) don't spot the database provider and need to move from single instance to farms it could happen to others!

**Comment by HaoK** [comment]
@blowdart is this just a docs issue, or is this just a discussion (that's been resolved)?
