### ISSUE TITLE
[Components] More E2E tests for events

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#7566]
There are a lot of browser events and we only have tests for a handful. These usually rely on the JS/.Net definitions for the event being in sync, so we should try and add E2E tests for all of them as it's one of the major interop boundaries (along with JS invocation).

**Comment by javiercn** [comment]
As @SteveSandersonMS has pointed out, some of this things we might not be able to test with browser automation.

That said, we could create a MEGAEVENTSTESTINGPAGE that would work as follows:

* We will launch the site manually. 
* We will navigate to the MEGAEVENTSTESTINGPAGE.
  * On that page we will have a several sections per event category (Touch, Pointer, Focus, Click, and so on).
  * Each of those sections will contain instructions about what the user needs to do.
  * Inside the section there will be one or more controls so that we can exercise the logic.
  * When an event is fired we will register it for validation later.
  * There will be a button to add the section to be validated at the end of the manual test.
* The tester will follow the instructions on each section that needs validation.
* At the end of the test there will be a Validate button where we will iterate over the list of sections that require validation and will produce a green or red mark whether they pass or not.

If we can automate some of these tests with Selenium that would be good.

**Comment by adrianwright109** [comment]
Related issue: #5501

**Comment by mkArtakMSFT** [comment]
Closing as there is no more left to be done here.
