### ISSUE TITLE
Provide swagger generation options for ASP.NET Core Web API project template

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#7639]
The WebAPI project should be extended to support swagger generation options with one of the supported providers

**Comment by dougbu** [comment]
Removed the `feature-code-generation` label because this work isn't about service references. (Will likely have other template updates that _are_ for the service reference feature.)

**Comment by ryanbrandenburg** [comment]
Can we get more background on this? Which provider does @danroth27 think we should go with, NSwag or Swashbuckle? Should we include SwaggerUI too? The title and description says "options", but what command-line option could there be other than "use swagger" (and "use SwaggerUI" if we want that)? We'll have to expose this as VS UI, have we talked with them about this?

**Comment by danroth27** [comment]
@ryanbrandenburg Please work with @glennc on this.

**Comment by ryanbrandenburg** [comment]
From Glen:

> The goal is an option during project creation add either swashbuckle or nswag. Though I think the engineering team still has an ask on them to do the due diligence required to allow us to actually depend on nswag, so it might only be swashbuckle in the short term. This is only the API template. If selected you get the package added and the code to wire it up. Adding the swagger ui endpoint and such. It’s probable that someone needs to enter this in the OSS tools and state that some amount of vetting has been done. This and the nswag thing should both be on one of your managers to organize. Eilon certainly knew about it but we might need to check with Kevin now as it probably fell off.

**Comment by rynowak** [comment]
note: that adding an external dependency like this requires a security review, even if we don't expect to find anything.

**Comment by ryanbrandenburg** [comment]
Per in-person conversation with Glen I'm operating under the assumption that we won't be adding this option to F#.

**Comment by mkArtakMSFT** [comment]
Moved this to `Preview7` as we are still blocked here.

**Comment by mkArtakMSFT** [comment]
Moving this to 3.1 because of the risks involved.

**Comment by pranavkm** [comment]
We did this for 5.0. Swashbuckle is enabled by default for API project templates.
