### ISSUE TITLE
[Discussion] Breaking changes to runtime compilation for Razor views and Razor Pages

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#7647]
As a consequence of cleaning up the ASP.NET Core shared framework to not depend on Roslyn, support for runtime compilation of Razor views and Razor Pages is being moved to a separate package.
Applications that require runtime compilation or re-compilation of Razor files should 
    
* Add a reference to the `Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation` package
* Update the application's `ConfigureServices` to include a call to `AddMvcRazorRuntimeCompilation`:

```C#
services.AddMvc()
    .AddMvcRazorRuntimeCompilation();
```

The following APIs previously available on `Microsoft.AspNetCore.Mvc.Razor.RazorViewEngineOptions` to support runtime compilation would now be available via 
 `Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.MvcRazorRuntimeCompilationOptions`:

* `RazorViewEngineOptions.FileProviders` -> `MvcRazorRuntimeCompilationOptions.FileProviders`
* `RazorViewEngineOptions.AdditionalCompilationReferences` -> `MvcRazorRuntimeCompilationOptions.AdditionalReferencePaths`

In addition, `Microsoft.AspNetCore.Mvc.Razor.RazorViewEngineOptions.AllowRecompilingViewsOnFileChange` has been removed. Recompilation on file changes is enabled by default by referencing the `Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation` package.

Related issues: https://github.com/aspnet/Announcements/issues/312, https://github.com/aspnet/Announcements/issues/325

**Comment by mqudsi** [comment]
(This definitely needs to be in the migration docs for the 3.0 jump.)

Any word on the package will be available via nuget?

**Comment by pranavkm** [comment]
@mqudsi  It'll be available as part of the preview3 release.

**Comment by mqudsi** [comment]
Thanks, @pranavkm. Looking forward to it.

**Comment by ctolkien** [comment]
Is this only for `env == "Production"` scenarios? I assume this doesn't change the development loop (whereby Razor files are recompiled on the fly?)

**Comment by mqudsi** [comment]
No, this applies everywhere (both in my understanding and from what I'm seeing in the latest preview).

**Comment by magiak** [comment]
Ok.. but i am not able to find the Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation package.. :(

**Comment by thewebchameleon** [comment]
This has apparently been resolved with the release of [preview 3](https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-core-3-0-preview-3/) however I am getting the exception below (using the template for MVC in VS2019)

![image](https://user-images.githubusercontent.com/16325369/53971436-9ad80100-4105-11e9-90cb-a8fa79b6eb52.png)

adding the nuget package `Microsoft.AspNetCore.Hosting.Abstractions` does nothing

**Comment by xt0rted** [comment]
After adding a reference to `Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation` I get a version mismatch on the `Microsoft.CodeAnalysis.Common` package. This is because `Microsoft.VisualStudio.Web.CodeGeneration.Design` is referencing an older version. I had to remove the reference to `Microsoft.VisualStudio.Web.CodeGeneration.Design` otherwise view recompilation was throwing an exception.

**Comment by pixeldm** [comment]
Is there any way to set AddMvcRazorRuntimeCompilation() for only the dev environment?  Currently, the only way to get design time recompiling of a view is to turn this feature on.  Otherwise, the project must be restarted to see any changes to a view.  However, enabling this feature also involves adding the `Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation` package.  This package adds a considerable amount of files to the publish folder when publishing.  Furthermore, I don't really want runtime compilation of views for production.  Currently, I can't find any way to limit this feature to just development.  Any suggestions?

**Comment by dazinator** [comment]
Maybe you could make that package reference conditional.

In your csproj
```
<PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <DefineConstants>UseRazorCompilation</DefineConstants>
</PropertyGroup>
```

Then in your startup, use pre processor directive


#if UseRazorCompilation
  .AddMvcRazorRuntimeCompilation();
#endif

**Comment by pixeldm** [comment]
> Maybe you could make that package reference conditional.

Thanks @dazinator !  This does indeed work as expected.  Much appreciated for the help.

**Comment by kle622** [comment]
I'm just trying this out now, and it is working as described. Thanks!
Is there a way to watch for new .cshtml files to compile?

**Comment by janleon** [comment]
Will this be available for .net standard 2.0?

I currently have my razor view compilation in a .net standard 2.0 class library referenced in the web app and when trying to upgrade my web app to use .net core 3 it fails with the following error message: 

`MissingMethodException: Method not found: System.Collections.Generic.IList1<Microsoft.Extensions.FileProviders.IFileProvider> Microsoft.AspNetCore.Mvc.Razor.RazorViewEngineOptions.get_FileProviders()`

I am unable to reference the Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation package in my class library as this package depends on netcoreapp 3.

The code I have working on .net 2,1 atm is based on [https://github.com/mikebrind/RazorEngineViewOptionsFileProviders](https://github.com/mikebrind/RazorEngineViewOptionsFileProviders). 

What is the best upgrade path to get this working again with net core 3.0 and still have my razor compilation code in a separate library?

**Comment by pranavkm** [comment]
@janleon https://github.com/aspnet/AspNetCore/issues/3757#issuecomment-434178759 has details on what library authors need to do to reference parts of AspNetCore. Referencing ASP.NET Core or it's libraries requires targeting `netcoreapp3.0`, so you have to cross-compile to your library.

**Comment by lourencocotta** [comment]
services.AddMvc().AddRazorRuntimeCompilation();

that what worked for me.

**Comment by LucaZiegler** [comment]
1. Install Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation
2. Modify `services.AddRazorPages()` to `services.AddRazorPages().AddRazorRuntimeCompilation();`

**Comment by cocowalla** [comment]
From the OP and [announcement](https://github.com/aspnet/Announcements/issues/343):

> Recompilation on file changes is enabled by default by referencing the `Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation package`

Yet [the docs](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?view=aspnetcore-3.0#runtime-compilation) and other posts here indicate you also need to set:

`services.AddRazorRuntimeCompilation()` - would be worth updating the announcement and OP here if this is indeed needed.

**Comment by clockwiseq** [comment]
Any chance the dev team can undo whatever they did that broke this?  I've added the package reference and I too have concerns with the sheer number of additional files required to implement this fix as well as the speed difference when making a change and simply refreshing vs 2.2's speed and ability to recompile the view.

**Comment by drdamour** [comment]
anyone come up with a good pattern to not have the package in release builds?  best i could come up with is conditioning the package reference and #IF blocking the the code (and using's).

**Comment by rynowak** [comment]
@pranavkm - I think you were working on something here...

**Comment by drdamour** [comment]
bah i should have RTFM https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?view=aspnetcore-3.1

**Comment by marlon-tucker** [comment]
Hello, 

I'm trying to diagnose an issue I'm experiencing on OrchardCore, the runtime compilation is taking a very long time to compile seemingly simple view files. Is there any way I can get additional diagnostics or logging from the `RuntimeViewCompiler`? At the moment it's only giving me total compile time for each view?

For example this page is taking just over 6.5s to compile:
```
@using OrchardCore.ContentManagement;
@using OrchardCore.Mvc.Utilities;
@{
    ContentItem contentItem = Model.ContentItem;
    //Html.AddPageClassNames("detail-" + contentItem.ContentType.HtmlClassify());
}
@await DisplayAsync(Model)
```

**Comment by Pilchie** [comment]
Tagging @sebastienros for the OrchardCore reference.

**Comment by sebastienros** [comment]
@marlon-tucker I saw the other comment you added in OrchardCore, but I think it was unrelated to the issue you commented on.
Can you file an issue with repro steps in OC (how you compile, where is your source code, what version of tools you are using)? Nobody else has reported this issue so far.

**Comment by marlon-tucker** [comment]
@sebastienros yep ok, I'll submit an issue tomorrow morning UK time. Sounds likely it's environmental which means it's going to be difficult to diagnose.
