### ISSUE TITLE
Kestrel not responding to HTTPS protcol with SSL

### ISSUE THREAD

**Issue by brainoverflow98** [dotnet/aspnetcore#7684]
I used the below configuration in my appsettings.json for using SSL with Kestrel when I start the application from command line it works great with HTTP however I get ERR_CONNECTION_CLOSED with HTTPS even though Kestrel successfully starts and listens on port 443 with given certificate file. What are your suggestions ?

```
  "Kestrel": {
      "Endpoints": {
	 "HTTP": { "Url": "http://*:80" },
         "HTTPS": {
            "Url": "https://*:443",
            "Certificate": {
               "Path": "ssl/domain.crt"
            }
         }
      }
   }
```

_Originally posted by @Tratcher in https://github.com/aspnet/KestrelHttpServer/issues/1290#issuecomment-353416087_

**Comment by brainoverflow98** [comment]
As it turns out it doesn't support certificates with "crt" format. I converted my certificate to "pfx" with a password and it's all working now. However I think it has lower performance compared to Nginx web server.

**Comment by blowdart** [comment]
Out of interest, which OS was this on?

**Comment by brainoverflow98** [comment]
@blowdart It was on Ubuntu plus I tested it on Windows 10 and it behaves same.

**Comment by blowdart** [comment]
We should at least have a better error, or better yet bug @bartonjs until he supports crt files :)

**Comment by Tratcher** [comment]
CRT support was implemented.
