### ISSUE TITLE
IdentityResult.Failed results should not be ignored in SignInManager

### ISSUE THREAD

**Issue by ulrichb** [dotnet/aspnetcore#7689]
### Describe the bug
Parts of `SignInManager` ignore failed `IdentityResult`s results of `UpdateUserAsync()` (do not check for `result.Succeeded`).

One example: [`AccessFailedAsync()`](https://github.com/aspnet/AspNetCore/blob/3e47fa7c693447f7ad6c0ef7620ee81c12b730f5/src/Identity/Extensions.Core/src/UserManager.cs#L2020) returns the result of `UpdateUserAsync()`, but [`CheckPasswordSignInAsync()` drops this result](https://github.com/aspnet/AspNetCore/blob/master/src/Identity/Core/src/SignInManager.cs#L349).

Why is this not just a minor issue? Because `UpdateUserAsync()` returns failures in concurrency situations (e.g. see the [EF implementation](https://github.com/aspnet/AspNetCore/blob/master/src/Identity/EntityFrameworkCore/src/UserOnlyStore.cs#L187-L194)). Further it's a public contract of `UpdateUserAsync` to return (storage) failures. So one could even see this as security issue if storage errors on updates are silently ignored (e.g. in the case of persisting an increased "AccessFailedCount").

### To Reproduce
See above. In the case of `CheckPasswordSignInAsync()` / `AccessFailedAsync()` + EF storage: Parallel password sign-in requests (with wrong password).

### Expected behavior
Checks for `.Succeeded` and passing of errors.

**Comment by blowdart** [comment]
Our default implementation doesn't really need to check, because the underlying operations throw. The check is meaningless. Instead the results are there for custom implementations of stores and user managers. Do you have a usermanager you've written that returns fails?

**Comment by ulrichb** [comment]
What about the mentioned (MSFT) EntityFramework implementation? (It catches `DbUpdateConcurrencyException` and returns `IdentityResult.Failed()`, see link above. 

Further it's an public API contract, so if `UpdateUserAsync()` shouldn't return failures (and always throw instead), then the contract should be `Task` instead of `Task<IdentityResult>`.
