### ISSUE TITLE
Replace our implementation of Process.KillTree with new netcoreapp3.0 for this

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/aspnetcore#7711]
https://github.com/dotnet/corefx/pull/34147 added `Process.Kill(bool entireProcessTree)`. We should look into removing [this code](https://github.com/aspnet/AspNetCore/blob/master/src/Shared/Process/ProcessExtensions.cs) which does the same thing, but doesn't implement the behavior as well as the corefx API does.

**Comment by Eilon** [comment]
Placing in commandlinetools area because that's the only non-test usage of this utility.
