### ISSUE TITLE
[Discussion] Using Visual Studio on aspnet repos requires installing or upgrading to 2019

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/aspnetcore#7752]
We are updating the master branch of the following repos to require Visual Studio 2019. 

* aspnet/AspNetCore
* aspnet/AspNetCore-Tooling
* aspnet/EntityFrameworkCore
* aspnet/Extensions

The .NET Core 3.0 SDK requires MSBuild 16, which is only currently supported by Visual Studio 2019. VS 2019 will be [released on April 2](https://devblogs.microsoft.com/visualstudio/join-us-april-2nd-for-the-launch-of-visual-studio-2019/).  In the meantime, you can get VS 2019 Preview 3 here: https://visualstudio.microsoft.com/vs/preview/. 

If you are working on the aspnet/AspNetCore repo, you can run [this script](https://github.com/aspnet/AspNetCore/blob/master/eng/scripts/InstallVisualStudio.ps1) to install or modify your current VS2019 installation to add features required by this repo.

----

This is the discussion issue for https://github.com/aspnet/Announcements/issues/345

**Comment by RickJWagner** [comment]
Just pointing out that this does not seem in alignment with Microsoft's push towards Open Source.

Maybe future declarations can use VS Code as an alternative?

**Comment by khellang** [comment]
Yeah, this sucks 😢

Can you expand on *why* VS 2019 is now a prerequisite? Or link to where this was discussed with the community/contributors?

Why can't I use Rider anymore? 🤔

**Comment by natemcmaster** [comment]
Clarification of the requirement: the actual requirement is that editors/IDE's support MSBuild 16. Most people don't know the difference between MSBuild versions, which is why I chose to word this as "install Visual Studio 2019".

If Rider and omnisharp-vscode support MSBuild 16, then there should be no problem using these editors on aspnet repos.

**Comment by khellang** [comment]
> Most people don't know the difference between MSBuild versions

This announcement was directed at contributors, not "most people" 😉

I'd be interested in an even more detailed explanation. What is it about MSBuild 16 that these repos need? Why wouldn't Rider etc. already support MSBuild 16 if they use the dotnet tooling? 🤔

**Comment by natemcmaster** [comment]
> I'd be interested in an even more detailed explanation. What is it about MSBuild 16 that these repos need?

Our repos use the netcoreapp3.0 target framework, which is only going to be supported by using the .NET Core 3.0 SDK, which needs MSBuild 16 (https://github.com/dotnet/toolset/pull/39).

> Why wouldn't Rider etc. already support MSBuild 16 if they use the dotnet tooling?

I don't know. I said _if_ Rider supports MSBuild 16, then it should be fine. I don't know the details on how Rider's project system works, so things may already work.

**Comment by rynowak** [comment]
Rider has a dropdown where you choose the version/location of MSBuild. I would expect that it's working just fine.

**Comment by natemcmaster** [comment]
Updated the title to clarify. Sorry if initial wording was ambiguous. You can use vim, Emacs, notepad, VS Code, or Rider. Not saying you have to use Visual Studio. But if you are using Visual Studio, you will need VS 2019 to work on our master branch.

**Comment by khellang** [comment]
> Rider has a dropdown where you choose the version/location of MSBuild. I would expect that it's working just fine.

Yes, I've been using Rider with 3.0 nightlies and MSBuild 16 for some time. The lack of details made it unclear whether that would still work though 😊 Nothing to see here... 🙈
