### ISSUE TITLE
[Templating][SPA] Use conditional package-lock.json

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#7825]
Generate package-lock.json files for all Auth options and include them conditionally, in the same way we do for migrations.

The main issue is that we include packages unconditionally right now in our templates, because the package-lock.json needs to be included as part of the template and that would require to have dozens or hundreds of conditionals.

Instead, we can generate different package-lock.json files for each one of the options affecting the packages.json file and conditionally include and rename those files when the template gets instantiated.

This is the same pattern that we follow with the entity framework identity migrations.

**Comment by mkArtakMSFT** [comment]
So will this result in the final instantiated project to potentially have less dependencies?

**Comment by javiercn** [comment]
Yes.
