### ISSUE TITLE
Micro benchmarks don't run anymore

### ISSUE THREAD

**Issue by sebastienros** [dotnet/aspnetcore#7886]
Tested in Mvc:

`dotnet run -c Release`

Output 

```
// Benchmark: NullHtmlEncoderBenchmark.HtmlEncoder: Job-AZLCFO(Runtime=Core, Server=True, Toolchain=.NET Core 3.0, RunStrategy=Throughput)
// *** Execute ***
// Launch: 1 / 1
Did not find f2a5f6e2-9cd2-443e-88ab-37933ea00601.dll in C:\Users\sebros\Documents\Projects\aspnet\AspNetCore\src\mvc\benchmarks\Microsoft.AspNetCore.Mvc.Performance\n\Release\netcoreapp3.0, but the folder contained:
f2a5f6e2-9cd2-443e-88ab-37933ea00601.exe.config
Executable C:\Users\sebros\Documents\Projects\aspnet\AspNetCore\src\mvc\benchmarks\Microsoft.AspNetCore.Mvc.Performance\bin\release\netcoreapp3.0\f2a5f6e2-9cd2-443e-8b-37933ea00601.exe not found
ExitCode != 0
No more Benchmark runs will be launched as NO measurements were obtained from the previous run!
```

**Comment by davidfowl** [comment]
Something must have turned off the validation that used to run on build.

**Comment by mkArtakMSFT** [comment]
Talked to @sebastienros and this seems to be affecting all the repo, rather than just mvc.

**Comment by natemcmaster** [comment]
_Build Team Triage:_ putting in the backlog. We don't plan to address this right now because we're investing effort in converting this repo to use the Arcade SDK. Benchmark validation runs were a few feature of KoreBuild which does not exist in Arcade. We'll need to design a replacement once we complete https://github.com/aspnet/AspNetCore/issues/7280

**Comment by dougbu** [comment]
@sebastienros has anything happened w/ this issue while we weren't looking❔

**Comment by dougbu** [comment]
@JunTaoLuo please link this into the item @rynowak recently added to the DoI project and remove it from the Build board.

----
Further information: Initial work looks fairly quick based on comments in #13350 e.g.
> Arcade does not have support doing a 'dry run' of microbenchmarks projects during the 'Test' phase. See https://github.com/aspnet/BuildTools/blob/803fd176f1ae147aa8af08e49e76ffda7221a4cd/files/KoreBuild/modules/benchmarks/module.targets#L14-L37 for the korebuild implementation

However, it's likely the microbenchmarks themselves haven't been tested lately and are stale. May need to fix a few of them before including them in an AzDO pipeline or running them on Helix.

**Comment by JunTaoLuo** [comment]
I already added it to DOI, will remove from build board.

**Comment by sebastienros** [comment]
@NTaylorMullen can you write down what you had to do to get it to work locally, and what change we should do in the repos to make them work again? I think it was a base folder issue, due to changing some paths at some point.

**Comment by NTaylorMullen** [comment]
My changes in this PR reflect that: https://github.com/dotnet/aspnetcore-tooling/pull/2107

Basically the test data wasn't being included in build output properly + I had to manually pass a config. So in the end I would write: `dotnet run --config profile` to start the process

**Comment by javiercn** [comment]
@BrennanConroy your recent changes addressed this, didn't they? (As well as ensure they keep running)

**Comment by javiercn** [comment]
@BrennanConroy closing as done, but feel free to reopen
