### ISSUE TITLE
Consider adding a HandleError(Task...) method to ComponentBase

### ISSUE THREAD

**Issue by rynowak** [dotnet/aspnetcore#7927]
See: https://github.com/aspnet/AspNetCore/pull/7915/files#r259885617

Now that we have `EventCallback` which does proper error handling, but is async - component authors might have cases where they need to *fire-and-forget* a task (like the example from our code).

We should consider providing a method for this on `ComponentBase`. So it can be used like:
```
HandleError(DoSomethingAsync());
```

The only semantic of this method is that it observes task failures and flows them up to the renderer so they can be logged, etc.

**Comment by rynowak** [comment]
I don't propose that we do this right away. Let's wait and see if it's needed based on feedback.

**Comment by mkArtakMSFT** [comment]
It's been more than 3 years now and no customers askes for this. Closing at this point. Thanks for the suggestion, @rynowak !
