### ISSUE TITLE
[Helix] enable framework unit tests

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/aspnetcore#7939]
src/Framework/test/ is disabled in helix. These tests run against the targeting pack and the shared framework, which are not yet available in the helix test payload.

**Comment by natemcmaster** [comment]
This is a lower priority issue which doesn't have to be done right now.

There is a tangentially related issue -- https://github.com/aspnet/AspNetCore/issues/11128

**Comment by Pilchie** [comment]
Moving to 3.1, since we aren't focusing on Helix support for 3.0.

**Comment by HaoK** [comment]
Resolved by https://github.com/dotnet/aspnetcore/pull/19975
