### ISSUE TITLE
Remove CancelableAsyncEnumerable

### ISSUE THREAD

**Issue by halter73** [dotnet/aspnetcore#7960]
Epic https://github.com/aspnet/AspNetCore/issues/8796

Instead iterate the IAsyncEnumerable manually using GetAsyncEnumerator() and a while loop to avoid an allocation. See https://github.com/aspnet/AspNetCore/pull/6791#discussion_r259196518.

**Comment by davidfowl** [comment]
@mikaelm12 are you taking this one?

**Comment by mikaelm12** [comment]
Yeah, I'll take this too.

**Comment by halter73** [comment]
Reopening #10129

**Comment by davidfowl** [comment]
What happened to this?

**Comment by davidfowl** [comment]
This seems like something we should do. Marked as up for grabs also.

**Comment by BrennanConroy** [comment]
Done via https://github.com/dotnet/aspnetcore/pull/32090
