### ISSUE TITLE
Extract error message in E2ETests when response is 500

### ISSUE THREAD

**Issue by anurse** [dotnet/aspnetcore#8037]
When an E2ETest (such as `E2ETests.NtlmAuthenticationTests.NtlmAuthenticationTest(variant:   Server: HttpSys, TFM: netcoreapp3.0, Type: Portable, Arch: x64)` in MusicStore.E2ETests) fails due to a 500 error, we get a lot of HTML goop and the error is somewhere in there.

We should change the [Validator](https://github.com/aspnet/AspNetCore/blob/master/src/MusicStore/test/MusicStore.E2ETests/Implementation/Validator.cs) class to parse the error and stack trace out of the response to make identifying E2E test failures easier.

cc @muratg

**Comment by pranavkm** [comment]
We sort of get this today from the `DeveloperExceptionPage` which returns plain text by default for non-browsers.
