### ISSUE TITLE
Get rid of ChunkGenerators for special Razor directives

### ISSUE THREAD

**Issue by ajaybhargavb** [dotnet/aspnetcore#8098]
Right now we special case the following directives in the parser and IR,
```
addTagHelper
removeTagHelper
tagHelperPrefix
using
```
They don't follow the same rules as other extensible directives. So, they weren't fully cleaned up when I rewrote the parser. This needs some cleaning up.

**Comment by pranavkm** [comment]
Thanks for contacting us. We're closing this issue as there was no community involvement here for quite a while now.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
