### ISSUE TITLE
Need example on stubbing client HubConnection 

### ISSUE THREAD

**Issue by AndersMalmgren** [dotnet/aspnetcore#8133]
### Describe the bug
None core version had a interface IHubProxy which we could Mock easily, the new client has a none abstract concrete typ called HubConnection, I've spent the last two hours trying to mock all its dependecnies so we can Unit test. But without success, can you point me to en example how to mock the HubConnection? Thanks

**Comment by davidfowl** [comment]
It's not a mockable type. I'd suggest wrapping it in your own interface and mocking that.

**Comment by AndersMalmgren** [comment]
Thansk for reply @davidfowl Yeah thats whats im doing for now, https://github.com/AndersMalmgren/SignalR.EventAggregatorProxy/blob/b2c194df616d8bb319256ccdf551a92ab2655027/SignalR.EventAggregatorProxy.Client.DotNetCore/Bootstrap/Factories/HubProxyFactory.cs#L55

But it feels like a step back from the old aspnet version.

**Comment by drmathias** [comment]
Using HubConnection it is really horrible to test. Wrapping it in a class is not ideal as you still need to access HubConnection to register your handlers and it is preferable to verify actual calls to HubConnection. It would be easier to test if it had an interface, then you could mock the 'Core' methods, but you're mostly using all these static extension methods which could be overloading methods but aren't. I really wonder what the design decisions for this were.

**Comment by bradygaster** [comment]
Like @davidfowl articulated above, the HubConnection isn't really mockable, nor did we really intend on it being mockable. My feeling on this is that it's an functional detail, and thought unfortunate it prevents 100% test coverage, I'd argue that when I've  wanted to test scenarios using a hub, my interest was in validating that "an event fired" when I'd expect it to fire more often than not. In those cases i'd wrap it in a class, or even abstract it into an interface as @davidfowl proposed, and use eventing tests. 

I am interested in other scenarios here and ideas, but I don't foresee us changing this implementation.
