### ISSUE TITLE
Blazor build fails with unhelpful error when there are native dependencies

### ISSUE THREAD

**Issue by MarkStega** [dotnet/aspnetcore#8158]
### Describe the bug
Razor Component app projects not building.

### To Reproduce

ASP.NET Core 3.0.0P2/VS2019P4

I have a solution that I am upgrading from Blazor 0.7.0 to Blazor 0.8.0; There are two client projects in the solution and both fail to build with the same two errors each.
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Format of the executable (.exe) or library (.dll) is invalid.	BusyBeaconsAdmin.App	C:\Solutions\OHI\Busy-Beacons\BusyBeaconsAdmin.App\EXEC	1	
Error	MSB3073	The command "dotnet "C:\Users\ms\.nuget\packages\microsoft.aspnetcore.blazor.build\0.8.0-preview-19104-04\targets\../tools/Microsoft.AspNetCore.Blazor.Build.dll" resolve-dependencies "C:\Solutions\OHI\Busy-Beacons\BusyBeaconsAdmin.App\obj\Debug\netstandard2.0\BusyBeaconsAdmin.App.dll" --references "C:\Solutions\OHI\Busy-Beacons\BusyBeaconsAdmin.App\obj\Debug\netstandard2.0\blazor\resolve-dependencies.txt" --base-class-library "C:\Users\ms\.nuget\packages\microsoft.aspnetcore.blazor.mono\0.8.0-preview-20190204.1\build\netstandard1.0\../../tools/mono/bcl/" --base-class-library "C:\Users\ms\.nuget\packages\microsoft.aspnetcore.blazor.mono\0.8.0-preview-20190204.1\build\netstandard1.0\../../tools/mono/bcl/Facades/" --output "C:\Solutions\OHI\Busy-Beacons\BusyBeaconsAdmin.App\obj\Debug\netstandard2.0\blazor\resolved.assemblies.txt"" exited with code 1.	BusyBeaconsAdmin.App	C:\Users\ms\.nuget\packages\microsoft.aspnetcore.blazor.build\0.8.0-preview-19104-04\targets\Blazor.MonoRuntime.targets	531	
Error		Format of the executable (.exe) or library (.dll) is invalid.	GenerateDataTier.App	C:\Solutions\OHI\Busy-Beacons\GenerateDataTier.App\EXEC	1	
Error	MSB3073	The command "dotnet "C:\Users\ms\.nuget\packages\microsoft.aspnetcore.blazor.build\0.8.0-preview-19104-04\targets\../tools/Microsoft.AspNetCore.Blazor.Build.dll" resolve-dependencies "C:\Solutions\OHI\Busy-Beacons\GenerateDataTier.App\obj\Debug\netstandard2.0\GenerateDataTier.App.dll" --references "C:\Solutions\OHI\Busy-Beacons\GenerateDataTier.App\obj\Debug\netstandard2.0\blazor\resolve-dependencies.txt" --base-class-library "C:\Users\ms\.nuget\packages\microsoft.aspnetcore.blazor.mono\0.8.0-preview-20190204.1\build\netstandard1.0\../../tools/mono/bcl/" --base-class-library "C:\Users\ms\.nuget\packages\microsoft.aspnetcore.blazor.mono\0.8.0-preview-20190204.1\build\netstandard1.0\../../tools/mono/bcl/Facades/" --output "C:\Solutions\OHI\Busy-Beacons\GenerateDataTier.App\obj\Debug\netstandard2.0\blazor\resolved.assemblies.txt"" exited with code 1.	GenerateDataTier.App	C:\Users\ms\.nuget\packages\microsoft.aspnetcore.blazor.build\0.8.0-preview-19104-04\targets\Blazor.MonoRuntime.targets	531	
```

### Expected behavior
Correct build

### Screenshots
n/a

### Additional context

C:\Solutions\OHI\Busy-Beacons>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview-010184
 Commit:    c57bde4593

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview-010184\

Host (useful for support):
  Version: 3.0.0-preview-27324-5
  Commit:  63a01b08e5

.NET Core SDKs installed:
  2.1.600 [C:\Program Files\dotnet\sdk]
  3.0.100-preview-010184 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview-19075-0444 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview-27324-5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview-27325-3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by MarkStega** [comment]
I know the issue, not the resolution. The failing projects reference System.Data.SqlClient (either directly in one case or through the inclusion of a .NetStandard library that has such a reference).

This was working in Blazor 0.6.0 & Blazor 0.7.0

**Comment by MarkStega** [comment]
The resolution is to update the reference of System.Data.SqlClient to 4.7.0-preview3.19128.7

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @MarkStega.
The error you're getting above is because the SqlClient reference has native dependencies. This is something we don't control and there is no way for this to work, unless you switch to an updated version, which will have no native dependencies.
What we'll try to do here, however, is to improve the error message instead.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
