### ISSUE TITLE
"dotnet watch run" should be able to exclude csproj itself

### ISSUE THREAD

**Issue by yilmazdurmaz** [dotnet/aspnetcore#8172]
### Is your feature request related to a problem? Please describe.
I am in learning phase on the console-only with dotnet core. "dotnet watch run" does great for me for every change/save I do. But now I try to advance in versioning too.

I am trying to update version info that I keep in the csproj file with the help of scripting.  I do have a real nice xml-read/write script to change version in csproj, and it is also called from csproj itself during build process. It changes version with "dotnet build" and "dotnet run" without a problem. Yet that means a change that is seen by the "watch" leading to a restart, and every restart means another change in version and the file leading infinite restarts. and as every restart kills previous exe from memory, so no result lives to run. (would be horrible if they do live)

I was working on different parts, different learning levels, some very high, and only by this problem I noticed "dotnet build" is same as "msbuild". but I cut that here. I don't want to bother myself with pre-core solutions like writing assemblyinfo.cs files or msbuild props etc.

short to request: please add a way to ignore "csproj" file itself from being watched. 

### Describe the solution you'd like
I don't know where else you use "csproj" word, but at least putting it into an exclude should make this file unwatched.
  `<Watch Include="**\*.xaml" Exclude="main.csproj" />`

### Describe alternatives you've considered
alternatives? there is none. I just do not use "watch" while versioning

### Additional context
I don't think any file is needed. But if you think you need files I use to change version inside "csproj", just let me know.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
