### ISSUE TITLE
Razore Component Doesn't Support "short" Data Type

### ISSUE THREAD

**Issue by MaiHassanM** [dotnet/aspnetcore#8203]
When I bind a field to a property that has a short datatype it generate the attached error

![shorterror](https://user-images.githubusercontent.com/34300656/53813662-cf618680-3f66-11e9-95f1-c4ec7b714091.png)

**Comment by SteveSandersonMS** [comment]
@rynowak This was deliberate, wasn't it? Do I recall correctly that the reason was just because it's very rare that there's a useful reason to use `short`? Perhaps we should support it just because it's confusing if you can't.

**Comment by rynowak** [comment]
Yeah, we just did this to try and simplify our lives, there's no technical reason why it can't be added.

**Comment by mkArtakMSFT** [comment]
Parking in preview5 for now, so we have a chance to review it during our iteration review meeting and decide what we do with this.

**Comment by SteveSandersonMS** [comment]
This was implemented a while ago.
