### ISSUE TITLE
Visual Studio Angular Template - debugs "dynamic" readonly TypeScript file instead of original TS source

### ISSUE THREAD

**Issue by jimbarrett33** [dotnet/aspnetcore#8206]
### Describe the bug
With ASP.NET Core (2.2) and Angular Template, setting a breakpoint in a TypeScript file creates a "dynamic" version of the file for debugging instead of the original TS source file. This makes debugging difficult and confusing, especially when there are many source files open in Visual Studio.

### To Reproduce
1. Using this version of ASP.NET Core '2.2'
2. Create new project with the Angular template
4. Build/Run
4. Set a breakpoint in the `incrementCounter()` method in TS file **counter.component.ts**
5. Notice the newly created _readonly_ "dynamic" version of the file in Visual Studio
6. In the app, click "Increment" on the Counter view
7. Notice that debugging breaks in the the "dynamic" file

### Expected behavior
The Visual Studio debugger should allow breakpoints in the original TypeScript source file. In addition, the file should editable to support the edit/rebuild/continue process typical in client-side dev.

### Screenshots
![image](https://user-images.githubusercontent.com/8396655/53820778-75e36280-3f3a-11e9-9318-d2751a861130.png)

### Additional context
I am fairly certain this is an issue with where/how the source maps are generated for the Angular App. Before the Angular CLI was mature, I was able to workaround this issue by ejecting the Angular project and editing Webpack myself using `noSources: true` in **SourceMapDevToolPlugin**. However, you can no longer eject the Angular Webpack configuration as of Angular 6.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @jimbarrett33.
@SteveSandersonMS is this something we control, or is this a VS issue?

**Comment by pranavkm** [comment]
This would an issue with the JS debugger in VS. Could you use the VS feedback tool to file an issue so that this gets routed to the right team? Thanks!
