### ISSUE TITLE
[Announcement] Some Cookie SameSite defaults changed to None

### ISSUE THREAD

**Issue by Tratcher** [dotnet/aspnetcore#8212]
SameSite is an option for cookies that can help mitigate some CSRF attacks. Each component that emits cookies need to decide if SameSite is appropriate for their scenarios. When this option was initially introduced inconsistent defaults were used across various AspNetCore APIs that has lead to confusing results. In 3.0.0-preview4 we've better aligned these defaults and made the feature opt-in on a per-component basis.

Affected APIs:
- `CookieOptions` used with `HttpResponse.Cookies.Append` has changed its default from `SameSiteMode.Lax` to `SameSiteMode.None`.
- `CookieBuilder` used as a factory for `CookieOptions` has changed its default from `SameSiteMode.Lax` to `SameSiteMode.None`.
- `CookiePolicyOptions.MinimumSameSitePolicy` has changed its default from `SameSiteMode.Lax` to `SameSiteMode.None`.

Note all AspNetCore components that emit cookies override these defaults with settings appropriate for their scenarios and these values have not changed:
- Session: Lax
- CookieTempDataProvider: Lax
- Antiforgery: Strict
- CookieAuthentication: Lax
- TwitterAuthentication state cookie: Lax
- RemoteAuthentication correlation cookie (OAuth): None
- OpenIdConnect nonce cookie: None

**Comment by NinoFloris** [comment]
For recent browsers what does the change from lax to none technically amount to in terms of behavior? @Tratcher

**Comment by Tratcher** [comment]
@NinoFloris It means more scenarios work by default for iOS.

**Comment by Tratcher** [comment]
SameSite has now also been disabled for the AzureAd and AzureAdB2C cookies.
https://github.com/aspnet/AspNetCore/issues/9115

**Comment by doogdeb** [comment]
Hi, my Asp.Net Core 2.2 site has some issues with OAuth correlation cookie failure in production, although data protection is enabled. Could this be because the default for OAuth cookie is samesite=lax and this causes problems with IOS? Would it be safe to set this to none?

**Comment by Tratcher** [comment]
@doogdeb unlikely. The default for correlation cookies has always been None.
https://github.com/aspnet/AspNetCore/blob/2c9e5c9356d641cba280718cb7a21489ddc31954/src/Security/Authentication/Core/src/RemoteAuthenticationOptions.cs#L26-L33

Please open a new issue with the details for your scenario, including a Fiddler trace if possible.

**Comment by NinoFloris** [comment]
Heads up https://www.chromestatus.com/feature/5088147346030592

Interesting here also is 

>NOTE: There is currently a bug affecting Mac OSX and iOS which causes SameSite=None cookies to be inadvertently treated as SameSite=Strict and therefore not sent with cross-site requests. (See https://bugs.webkit.org/show_bug.cgi?id=198181) Until this is fixed, SameSite=None may not work properly on Safari

This may mean people will actually see more issues due to None than Lax. Combine this with the fact Chrome and Firefox (which is work in progress) are going to default to Lax, people might still not run http locally (meaning None won't stick) this change seems to have complicated outcomes and will confuse a lot of developers.

**Comment by Tratcher** [comment]
@NinoFloris see https://github.com/aspnet/AspNetCore/issues/12125

**Comment by NinoFloris** [comment]
Thanks :)
