### ISSUE TITLE
CPU and Request lag after application has been running for a while

### ISSUE THREAD

**Issue by radderz** [dotnet/aspnetcore#8226]
### Describe the bug
We are getting really large delays in our ASP.NET Core 2.2 API after migrating from ASP.NET, the delay doesn't seem to be from a dependency and our website also in ASP.NET Core 2.2 doesn't have this issue.

The API connects to a SQL database, but application insights is suggesting all the time is spent in the code in the website. The code seems to run fine with exactly the same load after killing the website and letting it start again. The memory seems to be getting a little higher as it goes suggesting some kind of leak but I am really struggling to find the root cause and need some help finding the root cause. We never had this issue with ASP.NET with basically the same code (just ported, but the old one was MVC4 so some routing changes). 

The CPU never gets to 100%, get the requests continuously build up till everything just fails from a user side. Maybe this is related to App Insights Core as I have seen a couple others out there that have experienced similar issues, but we are fully up to date and those issues are shown as closed.

### Expected behavior
Consistent performance based on load instead of complete failure of the application over time

### Screenshots
![image](https://user-images.githubusercontent.com/1195471/53855853-56c8fb80-4034-11e9-888e-17ec0e54ac27.png)

![image](https://user-images.githubusercontent.com/1195471/53855915-90016b80-4034-11e9-94f7-3c2d54ffe0de.png)

This second one is a tiny operation yet is taking 8.8 seconds to run some code and then a fair bit of extra overhead in the routing. So something is killing the ASP.NET Core API part of the system.

In the above you can see the SQL dependency (assuming application insights isn't lying to me) is not the delay. And is instead in the API side. Killing the site and running the same get results in almost all of the time spent in the DB with little overhead

### Additional context
The API is running on a windows server 2016 IIS, running in-process (out of process shows the same issue).

**Comment by radderz** [comment]
Just some extra metrics, during a low time this morning

![image](https://user-images.githubusercontent.com/1195471/53906548-160ec800-40b0-11e9-9d23-3ef5aff4a1e9.png)

only ~20 requests per second on the api, dependency calls are db,


![image](https://user-images.githubusercontent.com/1195471/53906714-79005f00-40b0-11e9-88d5-b0a137295657.png)

This one shows the dependency duration isn't the cause of the request time. I noticed there were about 65 active SQL connections at the time but they were other than a couple all idle. 

![image](https://user-images.githubusercontent.com/1195471/53906582-363e8700-40b0-11e9-8b19-a76222c7fda0.png)
This shows the request duration going back to normal after killing the process with the same load.

**Comment by anurse** [comment]
> The CPU never gets to 100%, get the requests continuously build up till everything just fails from a user side.

The most common cause of this is thread-pool starvation. Do you ever block threads using code like `Task.Wait()`, `Task.Result` or calling `.GetAwaiter().GetResult()` instead of `await`ing asynchronous operations? Those operations freeze the thread-pool threads, meaning there are no threads left to service queued work.

I'd also suggest looking at [this article on diagnosing thread-pool starvation in .NET](https://blogs.msdn.microsoft.com/vancem/2018/10/16/diagnosing-net-core-threadpool-starvation-with-perfview-why-my-service-is-not-saturating-all-cores-or-seems-to-stall/) which could help you find more information.
