### ISSUE TITLE
[Helix] Reenable ProjectTemplatesTests

### ISSUE THREAD

**Issue by HaoK** [dotnet/aspnetcore#8270]
ProjectTemplates are currently disabled entirely on helix

**Comment by HaoK** [comment]
@danroth27 most of the test projects are pretty simple to convert to helix.  I don't think ProjectTemplates tests are one of them, similar to IIS tests, this one is going to need someone who knows these tests well to get them working on helix.  I opened the draft PR as a starting point to help that process.

**Comment by danroth27** [comment]
@HaoK Got it - makes sense.
@mkArtakMSFT Can we get this assigned to someone? What milestone makes sense to address this?

**Comment by natemcmaster** [comment]
Depends on https://github.com/aspnet/AspNetCore/issues/11128

**Comment by mkArtakMSFT** [comment]
Marking this as `blocked` until #11128 is fixed.

**Comment by HaoK** [comment]
@mkArtakMSFT I've got a PR (https://github.com/aspnet/AspNetCore/pull/16828) that includes the shared framework as part of the helix test payload, do you have someone who can help with the project template test specific changes needed to run on helix?

**Comment by mkArtakMSFT** [comment]
@ryanbrandenburg will be able to help with this in two weeks.

**Comment by HaoK** [comment]
This is mostly done now
