### ISSUE TITLE
[Helix] Reenable music store E2E tests

### ISSUE THREAD

**Issue by HaoK** [dotnet/aspnetcore#8343]
Need to reenable these tests on helix

**Comment by natemcmaster** [comment]
These tests are also affected by #10268

**Comment by halter73** [comment]
@HaoK It looks like music store tests are now running on Helix. Should we close this?

**Comment by HaoK** [comment]
I think the E2E ones are still disabled, see https://github.com/dotnet/aspnetcore/blob/5af0c471dde0e4e2e5be4294ce15930828ce2bff/src/MusicStore/test/MusicStore.E2ETests/MusicStore.E2ETests.csproj#L12

**Comment by HaoK** [comment]
Music store has been deleted, closing as this no longer applies
