### ISSUE TITLE
IIS web.config inheritance

### ISSUE THREAD

**Issue by yeskela** [dotnet/aspnetcore#8513]
### Is your feature request related to a problem? Please describe.
I need to get access to an IIS root web.config file in order to get some configuration (connection string, app settings etc.) from .Net Core API hosted in a lower level of IIS website

### Describe the solution you'd like
Now the access to the upper level config files blocked inside PhysicalFileProvider implementation and just prevent the access out of base path. Why web.config inheritance was removed in .Net Core? How we can get this functionality back? Maybe provide another file provide that would run through all upper level web.config files and merge all the app settings and connection string?

**Comment by davidfowl** [comment]
Why are you using web.config for configuration in ASP.NET Core?

**Comment by yeskela** [comment]
I'm using not only web.config... app.settings as well. I need to get connection string from upper level web.confing when deploy it to IIS in production.

**Comment by davidfowl** [comment]
> I'm using not only web.config

Web.config is only read by IIS, not ASP.NET Core so storing configuration settings in there won't be surfaced to your application.

> I need to get connection string from upper level web.confing when deploy it to IIS in production

This won't work without you explicitly adding that file to your configuration system. By default we only add the appsettings.json in the site folder. There is no concept of a configuration hierarchy but it can be simulated by adding multiple configuration sources.

**Comment by yeskela** [comment]
I have a complicated IIS websites structure in a department that built using ASP.NET Forms and use web.config inheritance to propagate parameters to the websites/apis. Now I need to replace one of the low level web app with the ASP.NET Core Web API, but I still have to get app parameters from the top level web.configs. And this is the requirement. I can't change it. 

> There is no concept of a configuration hierarchy but it can be simulated by adding multiple configuration sources.

@davidfowl, could you tell a bit in details how it can be simulated? So far, I stopped on a writing custom `FileConfigurationProvider` that knows how to deal with the appSettings and connectionStrings from web.config. But still use `PhysicalFileProvider` that prevents to get access to the files on the upper level of the app's root. But in order to allow the access I do this when build the host
```
            new WebHostBuilder()
                .UseKestrel()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .ConfigureAppConfiguration((hostingContext, config) =>
                {
                    config
                        .SetBasePath(Path.Combine(Directory.GetCurrentDirectory(), ".."))
                        .AddWebConfig(@"UpperLevelSite\web.config", optional: true)
                        .AddWebConfig("web.config", optional: true);
                })
                .UseIISIntegration()
                .UseStartup<Startup>();
```
main trick here that I do this `.SetBasePath(Path.Combine(Directory.GetCurrentDirectory(), ".."))` and it allows the access to one level up folder. 
But I don't like this solution much cause I don't know exactly how many levels I'll have on top of the app. Any thoughts?

**Comment by yeskela** [comment]
any update on this?

**Comment by yeskela** [comment]
Hello! Any updates, guys? This functionality is very critical for us.

**Comment by anurse** [comment]
Is there a change you're looking for in ASP.NET Core? We don't have plans for a `web.config` config provider. If you're looking for some help with your custom provider, we're happy to give some tips as best we can.

> But still use `PhysicalFileProvider` that prevents to get access to the files on the upper level of the app's root.

You don't have to use `PhysicalFileProvider` here, and I think it makes sense not to (or at least not to use the one provided by `FileBasedConfigurationProvider`). In this case you are dependent upon specific file system behavior (recursively walking up the file system tree and merging `web.config` files). You can just implement [`IConfigurationProvider`](https://github.com/aspnet/Extensions/blob/master/src/Configuration/Config.Abstractions/src/IConfigurationProvider.cs) directly and use any logic you'd like to resolve the files.
