### ISSUE TITLE
Update API template to use new Problem helpers in error handler

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspnetcore#8539]
Relies on #8537

Update error handler action method to use new problem helper method #8537:

``` csharp
[Route("/error")]
public ActionResult<ProblemDetails> HandleError()
{
    return new ProblemDetails
   {
        Title = "An error occurred while processing your request.",
        Status = 500
    };
}
```

**Comment by isaac2004** [comment]
@mkArtakMSFT this good to take now after latest PR?

**Comment by mkArtakMSFT** [comment]
I'm not sure I understand you question, @isaac2004.
Are you asking whether you can take this and send a PR for it? If so - that'll be amazing. We'll happily review a PR for this.

**Comment by ryanbrandenburg** [comment]
#8537 is still open. Has it actually been completed and we just missed updating it? Or does this issue not actually rely on that one somehow?

**Comment by mkArtakMSFT** [comment]
@ryanbrandenburg you're right. The referenced issues would make this much easier to accomplish. So that should come first.

**Comment by pranavkm** [comment]
Unblocked now

**Comment by mkArtakMSFT** [comment]
Moving to 5.0 after discussing this with @glennc and @pranavkm
