### ISSUE TITLE
Apache WebServer in-process hosting support

### ISSUE THREAD

**Issue by SolidSoft-Lda** [dotnet/aspnetcore#8554]
As the title mention, improve ASP.NET Core on Apache WebServer 400% as you did for IIS on .NET Core 2.2.

**Comment by jkotalik** [comment]
While it is an interesting idea, it isn't something we are looking into at the moment.

**Comment by SolidSoft-Lda** [comment]
Well, it was worth asking.
On Windows we have IIS, so don't have this feature it's not so important.
However for Linux environment it's fundamental as you know Kestrel behind WebServer it's 400% slower. If one can't see, it's because is not using a serious application.
And if currently we got SQL Server on Linux and .NET also on Linux, this feature makes a lot of sense to complete to circle.
