### ISSUE TITLE
Review the design of JsonPatch types

### ISSUE THREAD

**Issue by mazhou-msft** [dotnet/aspnetcore#8615]
### Describe the bug
The type `JsonPatchDocument` and related types are not aligned to the .NET Class Design Guidelines and also not following API conventions of other part of ASP.NET Core. Need to review and improve the ASP.NET Core JsonPatch package.

### Observed behaviors

1. `JsonPatchDocument.Operations` is of type `List<Operation>`, a public property should not expose `List<T>` as a return type
2. `Operation.op`, `Operation.path`, `Operation.value` and `Operation.from` -- the names of these properties are camel cases, it should be Pascal case
3. XML comments for methods in `JsonPatchDocument<T>` does not follow conventions, for example, XML comments for methods should start with third person verb forms, for example, "Adds ...", "Gets or sets ..."
4. XML comments for some properties are missing, for example, `Operations`

I feel like this package is not written by ASP.NET Core team, it is in a different style.

**Comment by mkArtakMSFT** [comment]
Thanks for your feedback, @mazhou-msft.
Improving JSONPatch is not a priority for us at the moment. Some of the things you've mentioned above are breaking changes, which we won't be able to do. Some, however, are minor and can technically be done, but the value add is not major.
If you'd like to contribute, we will happily consider a PR with non-breaking issues.

**Comment by mazhou-msft** [comment]
Thanks for the information. In a point, it might be worth doing a refactoring for 2). I understand that most of the camel casing properties are for JSON serialization, however, there are alternatives that can workaround this by using Json.NET package (such as annotating with `JsonProperty`.)

On the other hand, ASP.NET Core 3.0 is getting rid of having Json.NET as a hard dependency, the new `System.Text.Json.Serialization.JsonSerializer` and its associated types may better align with the overall direction of ASP.NET Core, I think it is acceptable to take these break changes as moving source code to netcoreapp3.0, they get to change anyway to work with ASP.NET MVC 3.0.

IMO it is better to refactor earlier than later. It would be very hard to do after this package becomes popular.

**Comment by pranavkm** [comment]
Thanks for contacting us. We're closing this issue as there was no community involvement here for quite a while now.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
