### ISSUE TITLE
A way to prevent IHostingStartup filters form overriding host configuration keys

### ISSUE THREAD

**Issue by aodl** [dotnet/aspnetcore#8631]
### Is your feature request related to a problem? Please describe.
IHostingStartup filters can easily override host configuration keys without the composition root project able to do much to stop them or realise that they've done it, because the host configuration is a private field inside the default implementation of [WebHostBuilder](https://github.com/aspnet/Hosting/blob/3483a3250535da6f291326f3f5f1e3f66ca09901/src/Microsoft.AspNetCore.Hosting/WebHostBuilder.cs#L30), which means you can't observe the entire host configuration until the WebHost is built. You could use GetSetting, but you'd have to have specific keys in mind.

For highly modular application use cases, It would be nice for the composition project to be able to maintain absolute control and prevent any host configuration keys from being overridden.

### Describe the solution you'd like
Either be able to access the host configuration before the first IHostingStartup filter is exectuted, in order to capture it's state before it's mutated, or a flag that can be set on WebHostBuilder that prevents IHostingStartup filters from mutating non-null host configuration keys.

**Comment by anurse** [comment]
If you want full control you can always disable IHostingStartup entirely, or exclude certain assemblies, using the [configuration options](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/platform-specific-configuration?view=aspnetcore-2.2#disable-automatic-loading-of-hosting-startup-assemblies), and use a different mechanism to activate these components.

**Comment by aodl** [comment]
Thanks for the response. Suppose there are many `IHostingStartup` filters being used by a project, and it's not immediately obvious exactly what each startup filter is doing to get their job done (adding / overriding configuration). It would be very useful to be able to inspect/log the host configuration state before each `IHostingStartup` filter augments it. Is there currently a way of doing something like this?

**Comment by anurse** [comment]
I'm not sure off the top of my head how the ordering works here. Thoughts @Tratcher @davidfowl ?

**Comment by Tratcher** [comment]
You should look at the new layering in 3.0 for generic host.
https://github.com/aspnet/AspNetCore/blob/36351647dba78e154dc033feee670ebe12ae4fe0/src/Hosting/Hosting/src/GenericHost/GenericWebHostBuilder.cs#L38-L45

You'll have access to the IHostBuilder before you add the web host on top.

**Comment by aodl** [comment]
^ this looks nice, but it doesn't appear to provide a means of hooking into the builder before **each** hosting startup is executed. This would make it difficult to inspect exactly how hosting startups are augmenting your application (and exactly which one is doing what).

The `HostingStartupWebHostBuilder` wrapper around `GenericWebHostBuilder` looks like it mostly delegates to `GenericWebHostBuilder`, while making sure that `_configureConfiguration` and `_configureServices` doesn't get mixed in with the non-hosting-startup lambdas (I guess so that they're called at the right time to provide the correct override behaviour).

It would be super nice if application code could optionally define a further wrapper, by injecting a factory lambda that returns an additional wrapper around `HostingStartupWebHostBuilder` (`HostingStartupWebHostBuilder`can still get newed up inside `GenericWebHostBuilder`, and then it gets passed into the user-defined factory).  The existing `HostingStartupWebHostBuilder` would act as the base implementation, while the user-defined wrapper allows hooking into any changes that a hosting startup is wanting to make to the user's app.

For building highly modular web applications, I think it would be useful to able to do this. Users would be able to log exactly what hosting startups are doing, and potentially reject certain changes that the hosting startup tries to make (rather than disabling the whole assembly).
