### ISSUE TITLE
Blazor form validation should allow custom validation state [class] attributes:

### ISSUE THREAD

**Issue by kennywangjin** [dotnet/aspnetcore#8695]
### Is your feature request related to a problem? Please describe.
I'm using bootstrap to style blazor components. While [class] attributes for validation state are all hard coded. e.g. [modified],[valid],[invalid]. I have to manually map bootstrap validation state styles to these [class]es.

### Describe the solution you'd like
I would be great if we could customize these state [class]es.

### Describe alternatives you've considered
We could add static read-write fields in [EditorContext] for state classes and allow users to customize these fields in App [Startup] or anywhere people want.

**Comment by shawty** [comment]
So just to confirm I'm reading this right, where not going to see this appear until .NET 5.0 right?

**Comment by XmlmXmlmX** [comment]
> So just to confirm I'm reading this right, where not going to see this appear until .NET 5.0 right?

I understand that Microsoft would like to stabilize Blazor first before new features are added. But this is done quickly.

**Comment by shawty** [comment]
So the 2 tasks that where tracking this have been closed as duplicates of this task, but we are still none the wiser as to why this one has been closed.

Is the work done and just waiting to be added to DN5?

Has it been abandoned?

Is it complete in another ticket we don't know about?

Can someone from MSFT and/or the dev team at large, shed some light on this please?

**Comment by SteveSandersonMS** [comment]
> why this one has been closed

This one is still open. It's never been closed :)

As per the milestone info for this issue, it's currently tracked for .NET 5 preview 2.

**Comment by shawty** [comment]
Hi @SteveSandersonMS dang... forgive me for that one :-)  Apparently learning to read was not one of my greatest skills:

![image](https://user-images.githubusercontent.com/1876454/75255502-f64d4400-57d9-11ea-99a6-bfde472138a6.png)

I looked at that and linked the close button with this issue tracker for some reason.

Cheers
Shawty

PS: Next time your in the UK, gimme a shout, it's been a while, and I probably owe you a pint :-)

**Comment by TanvirArjel** [comment]
It has been more than one year since the issue has been submitted and it's still in `Next sprint planning`! Allowing custom validation state [class] attributes is one of the very basic low-level functionalities of any UI framework!
