### ISSUE TITLE
[Components] Forgetting builder.CloseElement hangs the server

### ISSUE THREAD

**Issue by xclud** [dotnet/aspnetcore#8700]
I am creating a small component library in C# without any Razor code (cshtml). The problem i am facing is if i forget to close tags using `builder.CloseElement`, in runtime the process uses more and memory until the server stops responding and a lot of times i cannot even move my mouse to close the browser.

I would expect to get an Exception with better details or at least not crashing the server.

**Comment by muratg** [comment]
cc @danroth27

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're closing this issue as there was no community involvement here for quite a while now.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
