### ISSUE TITLE
Add support for referencing SignalR C++ client via vcpkg

### ISSUE THREAD

**Issue by anurse** [dotnet/aspnetcore#8719]
Epic #5301 

We want the SignalR C++ client to be usable via [vcpkg](https://github.com/Microsoft/vcpkg). We do need to resolve the possible naming collision with the ASP.NET SignalR client.

**Comment by anurse** [comment]
Let's see about getting this done in Preview 8

**Comment by anurse** [comment]
Moving the C++ stuff out to the backlog to properly reflect 3.0 work.

**Comment by BrennanConroy** [comment]
This is now completed. You can use `vcpkg install microsoft-signalr` with the latest vcpkg.

I'm going to keep this open to track updating the vcpkg port as we do releases until we can find a better way of doing that.

**Comment by mprather** [comment]
I would recommend updating the installation instruction on the main repo with a) information about the vcpkg work and b) correct installation instructions for linux. I literally stumbled upon this issue while trying to research why the installation instructions have failed.  

It's worth noting that the setup/use/config instructions seem like they are a little all over the place. I originally tried the windows manual setup. Then I realized that it would be possible to open in VS as a folder (which is not mentioned). The build times are quite large (range anywhere from 20-25+ minutes) for what seems a relatively small library. Is everything needed (i.e. i would be perfectly fine just using the library and not incorporating the dependencies for any tests)?

**Comment by BrennanConroy** [comment]
> The build times are quite large (range anywhere from 20-25+ minutes) for what seems a relatively small library

The long build time comes from the cpprestsdk (which provides the networking stack). The actual client takes less than 2 minutes to build if you exclude that, but then becomes unusable :D
If you want, you can bring your own networking stack and plug into the provided API. `with_websocket_factory` and `with_http_client` on the `hub_connection_builder`.

**Comment by shirhatti** [comment]
The current vcpkg port is port busted. It behaves like a package without [native cmake support](https://github.com/Microsoft/vcpkg/blob/master/docs/examples/installing-and-using-packages.md#handling-libraries-without-native-cmake-support).

We should fix the behavior of the port to behave like a port with native cmake support

**Comment by BrennanConroy** [comment]
> We should fix the behavior of the port to behave like a port with native cmake support

Done.

Think this issue can be closed.
