### ISSUE TITLE
BrowserLink causes reload in browser to fail in a RazorComponents App

### ISSUE THREAD

**Issue by BitProgress** [dotnet/aspnetcore#8769]
### Describe the bug
When adding browser link in Startup.cs, RazorComponents App does not work properly.

`
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
  if (env.IsDevelopment())
  {
    app.UseDeveloperExceptionPage();
    app.UseBrowserLink();
  }
`

a forced reload of the browser (chrome) using SHIFT+reload icon causes:

![image](https://user-images.githubusercontent.com/12260741/54879279-7f743200-4e37-11e9-8663-b726898c99bb.png)

Using Microsoft.VisualStudio.Web.BrowserLink V2.2.0

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @BitProgress.
@pranavkm can you please look at this? Thanks!

**Comment by mkArtakMSFT** [comment]
Actually, this seems to be an issue unrelated to us. I'll engage the tooling team to look into this.

**Comment by mkArtakMSFT** [comment]
@jodavis, can you please move this as necessary? Thanks!

**Comment by pranavkm** [comment]
@BitProgress sorry for giving you the run around. BrowserLink is a VS feature and any feedback for it should be given via the VS feedback tool so that it's routed to the right team. I suspect that the 2.2 version of the package isn't compatible with newer versions of ASP.NET Core. Thanks!
