### ISSUE TITLE
How to use sdk 3.0.100-preview-010184 after installing latest preview.

### ISSUE THREAD

**Issue by StevenTCramer** [dotnet/aspnetcore#8773]
Not a bug:  Just help if others are trying to do the same:

How to use sdk 3.0.100-preview-010184 after installing latest preview.
https://devblogs.microsoft.com/dotnet/announcing-net-core-3-preview-3/
explains that you upgrade in place, which I think should have been optional vs required.

To continue to be able to use the previous version until migrated you can do the following:

* make a copy "C:\Program Files\dotnet\sdk\3.0.100-preview-010184" to "3.0.100-preview-010184-Copy"
* install the latest preview
* after install rename the copy back to its original

If you have already installed the new preview and the old sdk isn't there then you will have to uninstall the new one download and install the old one the follow the above three steps.

**Comment by Eilon** [comment]
Parking this in the discussions milestone so others can find it for a while (it will be auto-closed eventually).

BTW for the SDK installer you can report issues or suggestions here: https://github.com/dotnet/core-sdk
