### ISSUE TITLE
Consider aligning how the @page directive works in razor components with how it works in razor pages

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#8787]
The fix for this is to align the behavior of the `@page` directive with the Razor Pages behaviour, with one addition. If your *page* is in the Pages folder then that segment will be ignored.

If you don't like this, and you want direct control, you can use `@attribute [Route(....)]`

**Comment by mrlife** [comment]
This makes a lot of sense, especially with razor components used within a razor pages web app.

**Comment by gingters** [comment]
In my opinion, for a Blazor SPA routing should not require attributes at all.
In fact, the actual component should neither need nor require to know if it is used as a page (aka has a route) or a component, or both.

Also, if you want to provide re-usable components and pages for multiple applications under different routes (i.e. in a component or functionality library), the attribute approach is extremely inflexible as you can only have one definition on the attribute, and you need to copy & paste code or unnecessarily derive a new component from the shared one to provide different routes.

It would be much better to have a configurable routing system which you set up in `Startup.cs` (i.e. like in Angular, where you can define what route ends up at what component).
There could be an configuration that (ideally optionally and not even by default) uses the `@page` and `@route` attributes, but usually for real-world applications you want to have explicit control about your application routing and not mix your routing logic into the components which should be as agnostic about their usage as possible.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
