### ISSUE TITLE
Using DPAPI with .net timed out talking to Domain Controller, didn't appear to fail over to another Domain Controller

### ISSUE THREAD

**Issue by Spikeophant** [dotnet/aspnetcore#8866]
We are using DataProtection to encrypt and decrypt data using a domain user as the key.  Today we had a firewall change that blocked the server from talking to one domain controller. However, we have several others which communication worked fine too.  Using a login of a user that had not hit this server in some time showed extended login times, but logins worked.  The decryption process errored out with a Crypto-NCrypt error code of 0x800706d9 which was "There are no more endpoints available from the endpoint mapper," as well as error code 0x8009002c, which I was never able to find.  What is the expected behavior of these libraries in the case when one Doman Controller is unreachable, and we have many others on our network that are?  Will it fail if it cannot hit the first one it tries, or should it be retrying?

**Comment by blowdart** [comment]
That's really weird. @GrabYourPitchforks do you know what should happen? I'd have through it should try for other DCs

**Comment by Spikeophant** [comment]
I have also opened a ticket with MSFT through official channels through our support contract.  If I hear back on that ticket first and am not under NDA on the response, I will post that here for anyone else curious as to how this works, or who finds this ticket in a future search.

**Comment by GrabYourPitchforks** [comment]
The API invokes `CryptProtectData` and `CryptUnprotectData` under the covers when refreshing the keyring, depending on the key protection mechanism in use. If the account making the call is a managed service account or a domain account (as opposed to a local user account), `CryptProtectData` / `CryptUnprotectData` may end up making calls to the domain controller. Often times these failures are transient and trying the operation again a few minutes later will succeed. This is a standard behavior of Windows DPAPI and isn't really related to the ASP.NET libraries.
