### ISSUE TITLE
asp-fallback CSS tag helper affected by Application Insights JavaScript

### ISSUE THREAD

**Issue by paulirwin** [dotnet/aspnetcore#8889]
### Describe the bug
If you have the Application Insights js code in your `<head>` tag ahead of `<link>` tags (such as bootstrap CSS) with the `asp-fallback-*` tag helpers, the first stylesheet with the tag helper will always fall back. The reason for this is that the AI js code is calling `setTimeout` and injecting a `<script>` tag in the head, effectively creating a race condition with the fallback code, such that when the fallback code tries to find its own script tag, it gets the AI-injected tag instead, and calling `previousElementSibling` returns the fallback script tag instead of the `<meta>` tag, which does not have the desired styles, causing the fallback to occur unnecessarily. Subsequent `<link>` tags are not affected, just the first one.

### To Reproduce
1. In an ASP.NET Core web app with Bootstrap CDN CSS in the `<head>` tag and the `asp-fallback-*` tag helpers in place, add the Application Insights JavaScript tracking code before the `<link>` tag.
2. Run the app with the Network inspector open in Firefox/Chrome
3. Notice that the CDN version loads successfully, and then the fallback CSS loads. Alternatively, inspect the DOM and notice that this is true.

### Expected behavior
The CDN version, assuming it returns 200 OK and the tag helper test attributes are correct, should not fall back.

### Screenshots
![image](https://user-images.githubusercontent.com/1874103/55174805-c158ed00-5143-11e9-965c-cbede9cfb1ba.png)

### Additional context
A workaround for this issue is to move the AI code after the stylesheet. However, it's worth noting that it may not be just AI that is an issue; any JavaScript that injects script tags in the head could potentially cause this problem. I would suggest investigating if a unique id could be applied to the meta tag (or script tag, but that would still be somewhat fragile if using `previousElementSibling`) to find it with `document.getElementById` instead of using the current approach of `getElementsByTagName`. If it is necessary to continue with the `previousElementSibling` approach, at least add validation to ensure that it is the meta tag that is expected, and warn and not fall back if it is an unexpected element.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @paulirwin and reporting this issue.
If you'd like to submit a PR, we'd happily consider it.

**Comment by pranavkm** [comment]
Thanks for contacting us. We're closing this issue as there was no community involvement here for quite a while now.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
