### ISSUE TITLE
Can anyone give me a example for .Net Core SignalR with MySQL

### ISSUE THREAD

**Issue by ishara119** [dotnet/aspnetcore#8947]
HI All,

I want to show real-time data which are inserting in to a MySQL table, so appreciate if anyone can suggest me a suitable article or starting point which can explain how to use .Net core singalR with MySql

thanks

**Comment by nosyminotaur** [comment]
Do you need an example specific to SignalR or MySQL? When using Entity Framework, changing database providers is very simple, so you can easily switch from SQL Server to MySQL.

**Comment by ishara119** [comment]
@nosyminotaur I'm want to show real time data in a webpage,
for a example, if a new record insert to database, it should be notify to web applications so I think to use SingleR for this and my database is MySql,  and backend is .net core 2.2

**Comment by daltonks** [comment]
Hello @ishara119 , does this help you?
https://docs.microsoft.com/en-us/aspnet/core/signalr/hubcontext?view=aspnetcore-2.2

The idea is to inject an `IHubContext<HUB_TYPE>` into your services.

**Comment by nosyminotaur** [comment]
@daltonks, I think @ishara119 wants to listen to changes in the database instead of the hub.

**Comment by ishara119** [comment]
@daltonks   @nosyminotaur.
thanks for replying. actually, I was looking to pull database notification from mysql db, I wasn't able to find any articles for that, im not sure whether it's possible at this moment.

anyway, i found a workaround, i created a .net core hosted service and able to get the database changes using a timer service then pushed those to frontend.
its working and stable now.

**Comment by hugoramos** [comment]
Hello, @ishara119 .
Are you "asking" for updates every N seconds?

If you have 3 dozen scenarios where you need real time capabilities do you ask for updates 36x every N seconds, even during night time? 

In my scenario, I would need to monitor hundreds of mysql tables... Unfortunately, I'm not sure if this approach fits my needs.
