### ISSUE TITLE
dotnet-watch should run a script before KillTree

### ISSUE THREAD

**Issue by AdmiralSnyder** [dotnet/aspnetcore#8957]
### Is your feature request related to a problem? Please describe.
I use dotnet-watch on an asp.net core Project in Visual Studio to modify the .razor files.
I attach the VS debugger in the Program.cs of the Web App. 
Because dotnet-watch uses taskkill -T -F, all of its child processes are killed, so there is no way to detach the debugger which keeps a lock on the pdb files, preventing dotnet-watch to rebuild.
(The program i use to attach gets killed, too).

### Describe the solution you'd like
A parameter to dotnet-watch like --notify <scriptfile> or an entry in the csproj would be nice.
Alternatively, an option to first use SIGTERM so the apps can react

### Describe alternatives you've considered
right now, my launch setting is: 
executablePath: c:\windows\system32\cmd.exe
commandLineArgs: /k DebuggerAttachServer && dotnet watch run
where DebuggerAttachServer is the thing making VS attach to the process started by dotnet watch run.
This is a little brittle.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
