### ISSUE TITLE
Application 'MACHINE/WEBROOT/APPHOST/APPNAME' with physical root 'C:\inetpub\path\wwwroot\' created process with commandline 'C:\inetpub\path\proc.exe ' but failed to listen on the given port 'xxx'

### ISSUE THREAD

**Issue by guylando** [dotnet/aspnetcore#8965]
Getting the error in the title each time with some other random port when trying to browse into an uploaded asp.net core website.
There is another asp.net core website on same iis and that one works fine.
iis 10, windows server 2016.
net core+hosting 2.1.7.
app target net472.
Same target and net core app on same iis works well in parallel to this one not working.
Running same code of the problematic site on another server works fine. It works on 2 servers and doesn't work on 2 servers.

Checked ports and the ports are not taken and the error is with different port each time.

What can cause this?

**Comment by jkotalik** [comment]
Can you try enabling stdout logs as shown here: https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/troubleshoot?view=aspnetcore-2.1#aspnet-core-module-stdout-log. 

Most likely there is a startup error occurring in your application which causes the app to fail to listen to a port specified.

**Comment by guylando** [comment]
According to the logs the startup configure method never finishes. Can it cause that error? @jkotalik 
I will investigate why it gets stuck, probably a bug in our code.

**Comment by guylando** [comment]
@jkotalik @shirhatti indeed the problem was some infinite loop caused by extreme case happening on new server installation. However I think there should be better error message for this case because the error message of failing to listen on port made me lose a lot of time on the wrong direction

**Comment by khusainovRuslan** [comment]
@guylando how you fix this problem? show problem code please....

**Comment by guylando** [comment]
@khusainovRuslan add logging in Configure/ConfigureServices code to see what is executed by the code and where it gets stuck. This way can find specific problem. I found some extreme case which caused infinite loop which caused this error.
