### ISSUE TITLE
Kestrel should create strings using newer idiomatic method

### ISSUE THREAD

**Issue by benaadams** [dotnet/aspnetcore#8978]
Currently uses `string key = new string('\0', keyLength)` and then mutates with fixed.

Should use something more like `string.Create`

However, attention needs to be given to avoid any performance regressions.

/cc @GrabYourPitchforks @davidfowl

**Comment by gfoidl** [comment]
> to avoid any performance regressions

Especially on small string-lengths, as the cost for the delegate invocation may be quite high in relation to actual work. `new string(Span)` may be faster in these cases.

**Comment by GrabYourPitchforks** [comment]
Thanks for opening this! 😃

**Comment by gfoidl** [comment]
FYI: I gave this a [try](https://github.com/gfoidl/Benchmarks/tree/28ee168aa8b0319bbb7bf220f277b5d566637569/aspnet/Kestrel/Infrastructure/GetHeaderName). Perf results don't look so bad so far, but I need more testing for the other methods, then I'll submit a PR.

**Comment by GrabYourPitchforks** [comment]
I imagine that once static function pointers come online there would be `string.Create` overloads that would allow using those, which should also help eke out just a little bit greater perf.

**Comment by gfoidl** [comment]
Yeah, I hope so too. That can open a door for a lot of "delegate" usages, and make some generic-struct-tricks obsolete.

**Comment by gfoidl** [comment]
@halter73  this issue can be closed, as the PR got merged?
