### ISSUE TITLE
Clean up UriHelperBase and family

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#8985]
See the thread at https://github.com/aspnet/AspNetCore/pull/8911#pullrequestreview-221045960

Although the typical customer-consumed API surface is OK, the internal API around initialization doesn't really make sense, and is a constant source of churn.

Next time we have any cause to work on `UriHelperBase` or things derived from it, we should attempt to understand why we've been fighting against every version of the design so far and what a better and more natural pattern would look like.

This shouldn't involve any breaking changes to the public API (excluding things that are only intended for framework use, like `Initialize` etc.).

**Comment by pranavkm** [comment]
These are public APIs now, so it's unlikely we're going to want to change it. Feel free to reopen if you feel otherwise.
