### ISSUE TITLE
Clean up Components.Browser.JS

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#8986]
The Components TypeScript code has some design and maintainability issues:

 * Structure is oriented around consumption via `<script>` tag only. Even if we published it as an NPM package, developers couldn't consume it that way because it doesn't export any "start" function you could import and call
 * Extensibility points use are based on globals attached to `window.Blazor` instead of being options you can pass into a "start" function.
 * General stylistic problems (extremely long methods, random mixtures of C#/TS/JS programming styles in different places, etc.)
 * Unjustified inconsistencies in the level of commenting / JSDocs etc.

I'd like to spend a day reorganising this and making it consistent. This will involve some public API changes but will only affect people using the more advanced forms of customisation (e.g., circuit handlers).

@mkArtakMSFT - preview 5? Might get pushed into p6 if we're short on time.

Additional thoughts from @javiercn:

  *  We added eslint to our typescript project.
  *  We should configure a sensible ruleset that defines our style and rules.
  *  We should eslint in autofix mode to clean up what we can.
  *  We should fix the remaining issues as we modify the codebase or do a pass to fix all the issues.

**Comment by pranavkm** [comment]
We can clean this up the next time we spend some time in here.
