### ISSUE TITLE
How to send a offline message by asp.net core signalR?

### ISSUE THREAD

**Issue by farhadibehnam** [dotnet/aspnetcore#8990]
I'm building a chat web application. I can push an online message to a user, but I can't push an offline message, of course, I google it, and I figured out in the old version of signlar we can't push offline message I don't know. Can the new version of signalr push an offline message? If it can't do. How can I implement an offline message by asp.net core signlar?

```
  public async Task SendPrivateMessage(string message, string connectionId,string userId)
        {
    
            await Clients.Client(connectionId).SendAsync("ReciveMessage", Context.User.Identity.Name, DateTimeOffset.Now, message,);
        }

```

**Comment by davidfowl** [comment]
There's no support for offline messages. You need to write that logic yourself. You have to keep track of what users are offline or online using the connection lifetime events, then you need to store the data you want to reply when that user comes online. Then you need to send that data to the user when they come back online.

**Comment by xperiandri** [comment]
Use Azure Notification Hub instead
