### ISSUE TITLE
Clean up ComponentsApp.App/.Server to remove E2E test cases

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#8992]
The intention for `ComponentsApp.*` is to be a sandbox-type app. It should be more or less the same as a default out-of-the-box template project, except it's wired up with project references to the framework instead of package references. This is so we can use it for trying out scenarios during development.

The E2E test cases should be in the `BasicTestApp` instead (which maybe could be renamed - there's nothing particularly "basic" about it).

Recently we've accumulated some E2E test cases in `ComponentsApp.*` so, to avoid having ambiguity about where E2E cases should go, let's migrate them to `BasicTestApp` and restore `ComponentsApp` as a nice happy sandbox place.

This should be a really quick and simple task and can be done as soon as https://github.com/aspnet/AspNetCore/pull/8911 is merged.

**Comment by pranavkm** [comment]
This is done. We have samples now.
