### ISSUE TITLE
Dynamically registered components

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#9006]
* Currently we require that you register components statically with the hub when they are not being prerendered.
  * We expect all the components to be present in the markup when we start the circuit.
  * We can leverage the infrastructure for prerendered components to invert the flow of information and dynamically register the components from within the page/view
    * We do this by creating a circuit and emitting a coment marker into the page to locate it.
    * When the client code loads. We find the comments in the markup, reconnect to the existing circuit and render the components.

* We want to do this because
  * Is more flexible than having to register components in the hub.
  * It allows passing parameters to the rendered root component.
  * It improves our story when you want to serve different components from different pages of the application.

**Comment by rynowak** [comment]
What is this issue supposed to track? Didn't you already do all of these things? 😆

**Comment by javiercn** [comment]
@rynowak The case where you don't prerender them.

**Comment by javiercn** [comment]
Just

```razor
(@await Html.ComponentAsync<App>(params))
```

**Comment by rynowak** [comment]
Ah gotcha. So this is the experience for the case where you just render the markers during the server-side render?

**Comment by javiercn** [comment]
Yep

**Comment by SteveSandersonMS** [comment]
Before implementing this, let's try to come to a decision about the method namings for the three cases:

 * static
 * interactive without prerendering
 * interactive with prerendering

**Comment by mkArtakMSFT** [comment]
Moving this to `Backlog` as we want to understand more the priority of this.

**Comment by ElderJames** [comment]
How are things going now?

**Comment by SteveSandersonMS** [comment]
This was implemented in 5.0 for WebAssembly components (and in 3.0 for server-side ones).
