### ISSUE TITLE
dotnet watch run does not listen to Razor file change events on disk

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#9014]
### Describe the bug
Changing Razor files in a project does not result in `dotnet watch run` re-triggering `run`.

### To Reproduce
1. Open VSCode
2. Open a ASP.NET Core web project
3. In the terminal window type `dotnet watch run`, wait for it to boot
4. Change a `.cshtml` or `.razor` file
5. See `dotnet watch run` not do anything

### Expected behavior
Server is rebooted.

**Comment by rynowak** [comment]
https://github.com/aspnet/AspNetCore/blob/master/src/Tools/dotnet-watch/src/assets/DotNetWatch.targets#L58

**Comment by rynowak** [comment]
I wonder if this should honour `UpToDateCheckInput` since we already have to set this for VS: https://github.com/aspnet/AspNetCore-Tooling/blob/master/src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Sdk.Razor.CurrentVersion.targets#L303

**Comment by NTaylorMullen** [comment]
> I wonder if this should honour `UpToDateCheckInput` since we already have to set this for VS: https://github.com/aspnet/AspNetCore-Tooling/blob/master/src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Sdk.Razor.CurrentVersion.targets#L303

Ah, interesting. Ya I think that'd be wise to do that.

**Comment by mkArtakMSFT** [comment]
Closing as this is fixed now.
