### ISSUE TITLE
Support debugging client-side Blazor from VS

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#9035]

**Comment by ejhewy** [comment]
Is there a technical roadblock to this approach?  
1. Setup Visual Studio for remote debugging.
2. Connect to the mono WASM runtime engine in the browser.
3. Get all of the VS debugging capabilities "for free".

You'd need to use the browser debugger for debugging DOM, styles, etc., but everything else would be through Visual Studio.

**Comment by SteveSandersonMS** [comment]
@ejhewy It's extremely nontrivial but we are working on it (well, mostly the Mono team are). We don't get "all of the VS debugging capabilities for free" because each capability involves detailed work to make the runtime support and present in a form that the IDE can understand.

**Comment by 3x0dv5** [comment]
Is anyone else also having issue debugging on Chrome? I keep getting this error "Debugging connection was closed. Reason: WebSocket disconnected"
I followed the steps "https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-3.0" but no luck, keep getting the error. I have no extensions in Chrome.

![image](https://user-images.githubusercontent.com/250271/58130880-16315500-7c15-11e9-8e8f-e280a4fd1916.png)

**Comment by tedekeroth** [comment]
Its off-topic, I know, just wanted to let @3x0dv5 know that I am getting the same problem with disconnected debugging. I think, however, that I saw some error in the output window, talking about the Blazor.Storage assembly I have referenced, and that it ran into some problem with that one.

**Comment by Fabian-at-VertiQ** [comment]
Debugging in Chrome was working fine until I updated my project to use the Microsoft.AspNetCore.Blazor 3.0.0-preview5-19227-01 version.
Anybody having the same issue?

**Comment by 3x0dv5** [comment]
@Fabian-at-VertiQ that seems to be in line with my issue. I do remember seeing it working a few months ago, and now I am using preview5 and seeing the problem. Looks like we have to wait a bit more, but will be worth it :)

**Comment by 3x0dv5** [comment]
Been using Blazor debugging the old way (console.writeline), updated to preview-7 so I decided to give another go to this debug from browser approach.
So this message "Debugging connection was closed. Reason: WebSocket disconnected" shows up when accessing the HTTPS version, it doesn't show when using HTTP.

I created a new project from scratch by using `dotnet new blazor -o Bzdebug`
When using HTTP I can switch the browser to debugging mode, but I cannot see any assembly in the sources tab.

**Comment by Herdo** [comment]
@SteveSandersonMS Will this feature be included in the GA release of Blazor WebAssembly in May next year?

**Comment by SteveSandersonMS** [comment]
Yes

**Comment by brianrichins** [comment]
The Chrome DevTools [recently announced support for directly debugging WASM via the DWARF format](https://developers.google.com/web/updates/2019/12/webassembly) - I'm wondering if this is something worth trying to support as well, or if VS / VS Code debugging will make DevTools unnecessary?

**Comment by xrkolovos** [comment]
Any news on this one? Is it going to be released in next preview?

**Comment by xrkolovos** [comment]
Can we use this with 3.2 preview 2? Is there any docs about it?

**Comment by chucker** [comment]
@xrkolovos this issue is about VS debug integration. [The roadmap still lists it](https://docs.microsoft.com/en-us/visualstudio/productinfo/vs-roadmap#web-tools) for "through June 2020"

> Introduce Visual Studio support for Blazor Wasm debugging

Presumably, this requires a new **VS** preview, not just a Blazor update.

**Comment by xrkolovos** [comment]
Thank you very much for you feedback

**Comment by ar0311** [comment]
Any word on support in VS Code?

**Comment by mkArtakMSFT** [comment]
@ar0311 debugging from VS Code will also be possible when 3.2-Preview 3 will release As @chucker mentioned, it'll be closer to the end of the month.

**Comment by ar0311** [comment]
Great, thanks!
