### ISSUE TITLE
Health Check Custom Log message

### ISSUE THREAD

**Issue by Poltergeisen** [dotnet/aspnetcore#9042]
### Is your feature request related to a problem? Please describe.
When health checks are reported as unhealthy they are sent with the following hardcoded string:

```
private static readonly string HealthCheckEndText = "Health check {HealthCheckName} completed after {ElapsedMilliseconds}ms with status {HealthStatus} and '{HealthCheckDescription}'";
```

Right now I can only edit the response that is shown when you do a GET request on the health check endpoint, but I also want our logger (using Nlog) to send emails when a service is down. It sends emails but the exception message isn't there so there is no way to know exactly why the service went unhealthy, and in our case the service was only unhealthy for a couple seconds.

### Describe the solution you'd like
It would be good if there was the possibility of allowing a custom log message for each health check status. 

I would like to log the exception message that the health check service received when an unhealthy service is detected. It would be good to know whether it was networking related issues, whether the database was down completely, etc...

**Comment by pranavkm** [comment]
Closing this issue as we haven't heard additional feedback since this was filed.
