### ISSUE TITLE
MissingManifestResourceException forces you to Stop running.

### ISSUE THREAD

**Issue by wstaelens** [dotnet/aspnetcore#9065]
### Describe the bug
I get a lot of these exceptions:

```
System.Resources.MissingManifestResourceException: 'Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "Foo.Bar.Resources.Areas.Identity.Pages.Account.Manage.IndexModel+InputModel.resources" was correctly embedded or linked into assembly "Foo.Bar" at compile time, or that all the satellite assemblies required are loadable and fully signed.'
``` 

sometimes I can just F5 them and continue, 

Other times I just get this and I can only click Stop and run my solution again:

![image](https://user-images.githubusercontent.com/7447285/55555744-4153f980-56e6-11e9-858b-49422a3e0243.png)

### To Reproduce
1. Using this version of ASP.NET Core 2.2 (sdk 2.2.105 - 2.2.3)
2. Visual Studio 2017 15.9.11

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project that illustrates the problem.

**Comment by wstaelens** [comment]
It's in my main solution, (can't reproduce it in a small new app, sorry) 😞

**Comment by wstaelens** [comment]
please find attached a zipped .mp4 video. (github doesn't seem to allow to upload .mp4)

[missingmanifest.zip](https://github.com/aspnet/AspNetCore/files/3053677/missingmanifest.zip)

What you will see:
I'm debugging, going to /Admin and you see that i'm forced to stop my debugging session because of that dialog. Next I debug again, go again to /Admin and again the same error, but this time I can continue (F5) without the Stop dialog.
VERY annoying and I have no clue on how to fix it.

**Comment by Eilon** [comment]
Thanks @wstaelens , we will assign a team member to take a look.

**Comment by wstaelens** [comment]
I thought it had to do with localization and suffix / subfolder in AddViewLocalization, but doesn't change a thing.

```
      var cfgDefaultCulture = Configuration.GetValue<string>("fooconfig:defaultsiteculture"); // "en"
      services.Configure<RequestLocalizationOptions>(
        options =>
        {
          var supportedCultures = new List<CultureInfo> {
            new CultureInfo(cfgDefaultCulture)
          };
          options.DefaultRequestCulture = new RequestCulture(culture: cfgDefaultCulture, uiCulture: cfgDefaultCulture);
          options.SupportedCultures = supportedCultures; // Formatting numbers, dates, etc.
          options.SupportedUICultures = supportedCultures; // UI strings that we have localized.
        });


  ....AddMvc(...)
.SetCompatibilityVersion(CompatibilityVersion.Version_2_2)
        .AddViewLocalization(Microsoft.AspNetCore.Mvc.Razor.LanguageViewLocationExpanderFormat.SubFolder) // localization .AddViewLocalization(Microsoft.AspNetCore.Mvc.Razor.LanguageViewLocationExpanderFormat.SubFolder) // localization
        .AddDataAnnotationsLocalization(); // localization
```

I'm adding cultures at runtime to allow a user to set a preferred language (e.g. when a translation is added in a system and the language is not known yet, it is added to the list. This list is shown in a dropdown in the footer), but that really shouldn't be any problem!

```
   private readonly IOptions<RequestLocalizationOptions> _LocOptions;

    public void AddLocalizationCulture(string languageId)
    {
      try
      {
        CultureInfo ci = new CultureInfo(languageId);
        if (!_LocOptions.Value.SupportedUICultures.Contains(ci))
        {
          _LocOptions.Value.SupportedUICultures.Add(ci);
        }
      }
      catch { }
    }
```

**Comment by rynowak** [comment]
What I think is happening is that you're debugging with first-chance exceptions turned on. We have a bug where a closed razor file with a breakpoint in it will break edit and continue. This looks like another repro for that case.

**Comment by allisonchou** [comment]
This is an older issue that I believe should be fixed in the new editor. If it persists in VS 2022, please file another issue. Thank you!
