### ISSUE TITLE
Razor expression statement completion disappears when typing quickly in Visual Studio

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspnetcore#9137]
Using Visual Studio 16.1.0 Preview 1.0 [28804.136.d16.1] (Internal Dogfooding Preview)

See GIF below for capture. Repro was simply creating a new Razor Components app, opening `Host.cshtml`, then attempting to type a Razor expression that calls `Html.RenderComponentAsync`.

![5YhcFGrC4c](https://user-images.githubusercontent.com/249088/55660556-d96fe280-57bb-11e9-8e9d-299420eeaec2.gif)

**Comment by NTaylorMullen** [comment]
@amadeusw @ToddGrun thoughts? This seems like a regression.

**Comment by NTaylorMullen** [comment]
@ToddGrun made a fix on his end to make this work in 16.1-preview3. There is something wonky happening on our end too that warrants some investigation. VS' modern completion now handles dot commits differently than before.

**Comment by mkArtakMSFT** [comment]
@ajaybhargavb, given that @NTaylorMullen is out, can you please try to figure out what's going on here? Thanks!

**Comment by NTaylorMullen** [comment]
This doesn't need to be in the preview 5 milestone. Todd's fix resolves Damian's problem. Us investigating more just makes us "more correct" for future scenarios

**Comment by NTaylorMullen** [comment]
Wont have time for this and given that it's functionally fixed in the latest VS release going to backlog this.

**Comment by rynowak** [comment]
Could you add the details about what specific improvements you want us to make so they are not forgotten?

**Comment by NTaylorMullen** [comment]
Update our partial parsing to not force reparses when a user types out character by character `@Html.XYZ`

**Comment by allisonchou** [comment]
I believe this should be fixed in the new Razor editor, closing out for now.
