### ISSUE TITLE
ANCM/IIS forces chunking for responses containing a Content-Length header

### ISSUE THREAD

**Issue by kevinchalet** [dotnet/aspnetcore#9139]
For obscure reasons, ANCM or IIS seems to force chunking even if the `Content-Length` header is returned (with the appropriate value):

```
HTTP/1.1 200 OK
Transfer-Encoding: chunked
Content-Type: text/html;charset=UTF-8
Vary: Accept-Encoding
Server: Kestrel
X-Powered-By: ASP.NET
Date: Thu, 05 Jan 2017 20:01:23 GMT
```

```csharp
public void Configure(IApplicationBuilder app) {
    app.UseDeveloperExceptionPage();

    app.Run(context => {
        var encoding = new UTF8Encoding(encoderShouldEmitUTF8Identifier: false);

        var document = @"<!doctype html>
<html>
<body>
<strong>Hello world</strong>
</body>
</html>";

        context.Response.ContentLength = encoding.GetByteCount(document);
        context.Response.ContentType = "text/html;charset=UTF-8";

        return context.Response.WriteAsync(document, encoding, context.RequestAborted);
    });
}
```

When using Kestrel without IIS, chunking is not used (as expected):

```
HTTP/1.1 200 OK
Date: Thu, 05 Jan 2017 20:06:01 GMT
Content-Length: 79
Content-Type: text/html;charset=UTF-8
Server: Kestrel
```

@Tratcher is that the intended behavior?

**Comment by anurse** [comment]
Leaving this open in the backlog to solicit some feedback. The out-of-proc handler is fairly limited here in what it can do to improve upon this. If people have scenarios with the in-proc handler where chunked encoding is used unexpectedly, it would be good to hear about those.

**Comment by shapeh** [comment]
@anurse - I am running in-proc with my above comment.

**Comment by shapeh** [comment]
Bump. Any progress on this one?

**Comment by anurse** [comment]
@shapeh The earlier conversations indicated IIS Dynamic Compression was in play. Is that the situation in your case? If not, perhaps https://github.com/aspnet/AspNetCore/issues/10773 is more appropriate.

@jkotalik @Tratcher it seems like this thread is actually dealing with an external issue (encoding changes in IIS Dynamic Compression). Is that a correct assessment from your understanding? Perhaps we should close this and move discussion of other issues (such as possibly @shapeh 's issue) to #10773 ?

**Comment by shapeh** [comment]
@anurse - I have just checked / problem happens no matter if Dynamic compression is on or off in IIS.

![Capture](https://user-images.githubusercontent.com/29387615/61393644-b3310700-a8c1-11e9-9bc0-777926c0368d.PNG)

**Comment by anurse** [comment]
Ok, let's move that discussion to #10773. Can you isolate a runnable sample that reproduces the problem and post it on that thread?

**Comment by davidfowl** [comment]
In favor of #10773
