### ISSUE TITLE
Problem with RedirectWwwRule

### ISSUE THREAD

**Issue by Bartmax** [dotnet/aspnetcore#9274]
### Is your feature request related to a problem? Please describe.
When using [`RedirectWwwRule`](https://github.com/aspnet/AspNetCore/blob/master/src/Middleware/Rewrite/src/Internal/RedirectToWwwRule.cs) it redirects everything that doesn't start with `www.`
When I create a site on azure for, for example: `example.com` (using the `RedirectWwwRule`) and trying to setup some staging so I can test my site on : `example-staging.azurewebsites.net` i get redirected to `www.example-staging.azurewebsites.net` which makes it impossible to use on this particular scenario. Also testing in `example.azurewebsites.net` turns into `www.example.azurewebsites.net`
*This is not limited to azure.*

### Describe the solution you'd like
Since most of the usages for `RedirectWwwRule` would be for naked domains, it would be great if we have it to work only on naked domains (no subdomain urls). Since this is a breaking change, we may add an option to the rule like to opt-in on naked only redirects.

### Describe alternatives you've considered
Currently an alternative is to make my own Rule which renders the existing Rule completely obsolete.

**Comment by jkotalik** [comment]
Seems like an interesting idea. Have you tried to write your own custom rule to implement this?

**Comment by Bartmax** [comment]
Detecting a naked domain is not a trivial thing (and maybe that's why the rule does not try to do it)

I found 2 workarounds that I'm using based on my use-case scenario.

1) Wrap the code inside a check on production environment.
```c#
if (env.IsProduction()) {
// do de rewrite here
}
```

2) I created a custom IRule that accepts a nake domain string value and I check if the host is naked on this fashion and if it is, I'm applying the redirect. Nothing too fancy
```c#
public class RedirectNakedToWwwRule : IRule
    {
        public readonly string _domain;
        public readonly int _statusCode;

        public RedirectNakedToWwwRule(string domain, int statusCode)
        {
            _domain = domain;
            _statusCode = statusCode;
        }

        public virtual void ApplyRule(RewriteContext context)
        {
            var req = context.HttpContext.Request;

            if (req.Host.Value.Equals(_domain, StringComparison.OrdinalIgnoreCase))
            {
                var wwwHost = new HostString($"www.{_domain}");
                var newUrl = UriHelper.BuildAbsolute(req.Scheme, wwwHost, req.PathBase, req.Path, req.QueryString);
                var response = context.HttpContext.Response;
                response.StatusCode = _statusCode;
                response.Headers[HeaderNames.Location] = newUrl;
                context.Result = RuleResult.EndResponse;
            }
        }
    }
    public static class RewriteOptionsExtensions
    {
        public static RewriteOptions AddRedirectNakedToWww(this RewriteOptions options, string domain, int statusCode)
        {
            options.Rules.Add(new RedirectNakedToWwwRule(domain, statusCode));
            return options;
        }
        public static RewriteOptions AddRedirectNakedToWwwPermanent(this RewriteOptions options, string domain)
        {
            return options.AddRedirectNakedToWww(domain, statusCode: StatusCodes.Status308PermanentRedirect);
        }
    }
```

**Comment by jkotalik** [comment]
> Detecting a naked domain is not a trivial thing (and maybe that's why the rule does not try to do it)

Yeah, I see that your rule is just passing in a domain to string match on. The rule you implemented seems more like `RedirectToWwwWithSpecificHost()`. Without passing in a domain, you can maybe do `IndexOf()` on the host header for the first part of the host header, but it isn't trivial and seems niche.

I don't think this scenario is common enough to justify having a rule/option dedicated to it. I'm going to close for now as it seems you came up with a solution. Feel free to reopen if you disagree or there is more support.

**Comment by delebru** [comment]
Wouldn't allowing RedirectToWww() to receive the desired domains as a parameter be a better option than having to write our own solution? (as long as it stays redirecting all requests when no domains are specified).

**Comment by jkotalik** [comment]
Yeah I agree, it would be a better solution. If you'd like to open a PR to do this, we would happily consider it.
