### ISSUE TITLE
In pressure measurement, InProcess can't recover as quickly as Kestrel

### ISSUE THREAD

**Issue by jmk92** [dotnet/aspnetcore#9278]
I use Performance Testing to test an API request, which may take about 10 ms to execute each time.
It is mainly about the processing of some pictures and the interaction with the database.
If the concurrent settings of Performance Testing are large, the settings exceed the load.

For example, the system may be able to withstand 500 concurrencies. When the concurrency of pressure measurement is set to 1000, the CPU occupies up to 100%, which has exceeded the load, if InProcess is used.

After more than a few seconds, the return is: 

> HTTP error 503.2 - Service Unavailable
> 
> The value set by server Runtime@appConcurrentRequestLimit is exceeding.

Kestrel：

> HTTP error 502.3 - Bad Gateway
> 
> Unable to connect to the server

I checked the database. It was easy, no load, no exception.

This may not be a problem, but when I adjust the concurrency of the pressure measurement to 10, the number of requests for the pressure measurement is immediately reduced, but the CPU is still high, and the service is still unavailable. It may take 10 seconds, or even longer, for him to recover, the CPU is reduced, and the service is available.

But if I use Kestrel, I just adjust web. config and delete hosting model = "InProcess".

Of course, if the load exceeds, the service is unavailable, but when I adjust the concurrency of the pressure measurement to 10, the CPU can be reduced in a very short time, or even 1 second, and the service is available.

I don't know how many times I have tested the above tests, and the results are still the same, without exception.

Attempted version:.NET core 2.2.3/2.2.4/3.0.0-preview 3

System: Windows Server 2019

**Comment by jmk92** [comment]
My service has load balancing outside, but it often has 500 errors for a long time, but when I switch to Kestrel, this problem does not exist. I always want to find out the reason, so I did Performance Testing, and found the above problem.

For example, one of my services can only carry 500 concurrent requests. Suddenly, when a wave of requests over 500 arrives, my service will be paralyzed. It may take some time to recover. When using Kestrel, although this wave of traffic can not resist, the service will still be available after the wave of requests has passed, as long as the concurrency does not exceed 500. The use of InProcess is disastrous, and it takes a while to recover from paralysis, which is a serious problem.

**Comment by davidfowl** [comment]
@jmk92 Would you mind sharing the application with us and the load test you ran?

**Comment by jmk92** [comment]
@davidfowl    

Sorry, our code can't be shared, but we seem to have found a problem. We wrote the simulated code, and then used pressure measurement to set up a large concurrency. If it exceeds the load, we filled up the CPU directly, and waited half a minute to adjust it to 0.

After about 15 seconds of InProcess, the CPU began to decline.

Kestrel also performs the above steps, but after adjusting to zero, about five seconds, the CPU starts to decline.


>   [Route("api/[controller]")]
>     public class TestController : Controller
>     {
>         [HttpGet]
>         public IEnumerable<string> Get()
>         {
>             HashSet<string> resultList = new HashSet<string>();
> 
>             List<string> randList = new List<string>();
> 
> 
>             for (int i = 0; i < 10000; i++)
>             {
>                 randList.Add(new Random(new Guid().GetHashCode()).Next(10000000, 100000000).ToString());
>             }
> 
>             List<string> hashList = new List<string>();
> 
>             for (int i = 0; i < 8; i++)
>             {
>                 hashList.Add(new Random(new Guid().GetHashCode()).Next(10000000, 100000000).ToString());
>             }
> 
> 
>             foreach (var item in randList)
>             {
>                 foreach (var hash in hashList)
>                 {
>                     if (item == hash)
>                     {
>                         resultList.Add(hash);
>                     }
>                 }
>             }
> 
>             return resultList;
> 
>         }
> 
>     }

**Comment by davidfowl** [comment]
What is pressured measurement?

**Comment by jmk92** [comment]
@davidfowl    We use Aliyun's PTS, pay for quick pressure measurement.

**Comment by anurse** [comment]
We need to do a broader exploration of stress issues. Tagging this so we can revisit it.

**Comment by jmk92** [comment]
Preview 5 also had problems

**Comment by jmk92** [comment]
Preview 6 will still be like this

**Comment by jmk92** [comment]
3.0 is still the same. Is it the question of iis? Should we go into the survey? Will 3.1 solve this problem?
@anurse @davidfowl
