### ISSUE TITLE
Provide a tool to get to the commit history for of a dependency repo for a given core-sdk build

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/aspnetcore#9297]
From email:

For a repo X (AspNetCore/Extensions/etc.), provide a n-click (where n is like, 1-3) experience to get to the GitHub commit history for that repo X originating from the commit that is in the latest dotnet/core-sdk build and going backwards.

1. So this link: https://github.com/aspnet/AspNetCore/commits/3b32f43453eba8edf03bebb9d893af59ada0e431
1. But where the commit hash is whatever is currently in core-sdk.
1. I think BARViz is super close to this if they made the commit hash links go to GitHub instead of AzDO.. but even the AzDO view isn’t too bad
1. Looks like most of this is tracked for BARViz in these issues but I figured we can let that team know our priorities:
    1. [Create a nice URL for BARViz](https://github.com/dotnet/core-eng/issues/5749)
    1. [Hash link should go to Github instead of AzDO](https://github.com/dotnet/core-eng/issues/5884)
    1. [Allow read-only access to build visualization](https://github.com/dotnet/core-eng/issues/5798)

cc @anurse @aspnet/build

**Comment by anurse** [comment]
I'd like to split these because the prioritization on these is a little different. I'll do that now.

**Comment by anurse** [comment]
I think these should be handled in BARViz (the three links in 4), I just want us to track it and indicate our priority.

**Comment by anurse** [comment]
Split to: https://github.com/aspnet/AspNetCore/issues/9299

This one I'm less concerned about landing in preview 6.

**Comment by natemcmaster** [comment]
Agreeing with @anurse , I think this should be done via BarVIZ. Let's leave open until our next Arcade sync up to ask about 

1. if there are plans for someone on dnceng to implement
2. and if not, would they accept contributions to BarVIZ from our team.

Until then, putting this in build team backlog.

**Comment by markwilkie** [comment]
@mjanecke - putting this on your radar

cc/ @alexperovich and @chrisboh

**Comment by mjanecke** [comment]
Hi folks, 
I noticed that it was mentioned that we have a couple of items in our backlog that would help meet yours needs. Is there any other functionality that you're looking for us to include in BARViz? Should we set up a meeting to chat? 
Thanks!

**Comment by dougbu** [comment]
This information can be found at pages like https://maestro-prod.westus2.cloudapp.azure.com/131/https:%2F%2Fgithub.com%2Fdotnet%2Fcore-sdk/latest/graph fairly simply and that info goes to GitHub (not AzDO). Unless this is a private page and the request was for external visibility, looks like there's nothing to do here.

Feel free to reopen if you feel otherwise.
