### ISSUE TITLE
DataProtection: Add string extension method wrapping DangerousUnprotect

### ISSUE THREAD

**Issue by mispencer** [dotnet/aspnetcore#9306]
### Is your feature request related to a problem? Please describe.
I am using DataProtect to store a string. I can use the Protect extension method which takes in and returns a string to protect the string, but unprotecting it with DangerousUnprotect only has a single method that takes and returns a byte array. This means I have to duplicate the string/byte conversion logic of the Unprotect extension method exactly in my codebase when calling DangerousUnprotect, or else I wouldn't get the correct string or the unprotect will fail.

### Describe the solution you'd like
There should a DangerousUnprotect extension method that takes and returns a string.

### Describe alternatives you've considered
I can write my own extension method, but this requires locating and duplicating the conversion logic between strings and byte arrays in the existing Protect and Unprotect extension methods.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
