### ISSUE TITLE
Update libuv package with latest libuv and reference it from Kestrel 3.0 package

### ISSUE THREAD

**Issue by Eilon** [dotnet/aspnetcore#9307]
We've had some customer requests to have a newer Libuv package. The latest one we released is 1.10.0 (https://www.nuget.org/packages/Libuv/1.10.0), but Libuv already has a 1.27.0 (https://github.com/libuv/libuv/tree/v1.27.0).

We should update the package to the latest version of Libuv, and then update Kestrel's 3.0 Libuv transport to reference it.

**Comment by YurySolovyov** [comment]
Even cooler would be to automate building new packages for stable releases, but that's a stretch goal.

**Comment by anurse** [comment]
Are there any specific features/bug fixes we need? It would be helpful to see the customer scenarios that updating would enable. I don't disagree that we should update, but it would help prioritize this issue.

**Comment by YurySolovyov** [comment]
It is not like I was looking for specific features or fixes, but rather a reliable source of latest libuv releases (as discussed in https://github.com/libuv/libuv/issues/1042)

**Comment by anurse** [comment]
Gotcha, thanks for the info.

**Comment by deniszykov** [comment]
Any news or progress? We are using `LibUv` package from Nuget in out project. I would like to get a fixes that is in the 1.30.*.

Do you need any help in this?

**Comment by halter73** [comment]
Kestrel's libuv transport is [now obsolete](https://docs.microsoft.com/en-us/dotnet/core/compatibility/aspnetcore#kestrel-libuv-transport-marked-as-obsolete) so we don't plan to update this dependency.
