### ISSUE TITLE
Add support for CSP Nonce to the PrerenderTagHelper

### ISSUE THREAD

**Issue by dima117** [dotnet/aspnetcore#9416]
### Problem

My application uses `PrerenderTagHelper` for SSR. I want to use [Content Security Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) and I need to add the `nonce` attribute for all inline `script` tags. I can't do this because `PrerenderTagHelper` renders the `script` tag [without any attributes](https://github.com/aspnet/AspNetCore/blob/master/src/Middleware/SpaServices/src/Prerendering/PrerenderTagHelper.cs#L124).

### Solution

Add the `Nonce` property into `PrerenderTagHelper` and render `nonce` attribute if this property is not empty.

### Alternatives

Now I use own tag helper which owerrides `PrerenderTagHelper` rendered content:

```cs
    [HtmlTargetElement(Attributes = "asp-prerender-module")]
    public class PrerenderWithNonceTagHelper: PrerenderTagHelper
    {
        [HtmlAttributeName("asp-prerender-nonce")]
        public string Nonce { get; set; }

        public PrerenderWithNonceTagHelper(IServiceProvider serviceProvider) : base(serviceProvider)
        {
        }

        public override async Task ProcessAsync(TagHelperContext context, TagHelperOutput output)
        {
            await base.ProcessAsync(context, output);

            if (!string.IsNullOrEmpty(Nonce))
            {
                if (!Regex.IsMatch(Nonce, "^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$"))
                {
                    throw new Exception("invalid nonce");
                }

                var content = output.PostElement.GetContent();
                output.PostElement.SetHtmlContent(content.Replace("<script>", $"<script nonce=\"{Nonce}\">"));
            }
        }
    }
```

**Comment by blowdart** [comment]
Oh yes, totally this.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @dima117.
@ryanbrandenburg can you please review the provided PR? Thanks!

**Comment by SamuelJohnsonMedia** [comment]
Can I ask what is happening with this as there is a PR but nothing has been merged which is a shame considering its security focus.
