### ISSUE TITLE
[Discussion] Making "pubinternal" types in ResponseCaching internal

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/aspnetcore#9442]
In ASP.NET Core, pubinternal types are types that are declared as public but put in an .Internal namespace. While these types are public they have no support policy and are subject to breaking changes. Unfortunately accidental use of these types has been common, resulting in breaking changes to these projects and limiting our ability to maintain the framework.

In ASP.NET Core 3.0, we are moving pubinternal types in ResponseCaching to internal. This includes the following types:

```
Microsoft.AspNetCore.ResponseCaching.Internal.CachedResponse
Microsoft.AspNetCore.ResponseCaching.Internal.CachedVaryByRules
Microsoft.AspNetCore.ResponseCaching.Internal.IResponseCache
Microsoft.AspNetCore.ResponseCaching.Internal.IResponseCacheEntry
Microsoft.AspNetCore.ResponseCaching.Internal.IResponseCachingKeyProvider
Microsoft.AspNetCore.ResponseCaching.Internal.IResponseCachingPolicyProvider
Microsoft.AspNetCore.ResponseCaching.Internal.MemoryResponseCache
Microsoft.AspNetCore.ResponseCaching.Internal.ResponseCachingContext
Microsoft.AspNetCore.ResponseCaching.Internal.ResponseCachingKeyProvider
Microsoft.AspNetCore.ResponseCaching.Internal.ResponseCachingPolicyProvider
```

In addition, a default implementation for `IResponseCachingPolicyProvider` and `IResponseCachingKeyProvider` will no longer be added to services as part of `AddResponseCaching` method. Also, the constructor for ResponseCachingMiddleware has been changed from:
```C#
public ResponseCachingMiddleware(RequestDelegate next, IOptions<ResponseCachingOptions> options, ILoggerFactory loggerFactory, IResponseCachingPolicyProvider policyProvider, IResponseCachingKeyProvider keyProvider)
```
to:
```C#
public ResponseCachingMiddleware(RequestDelegate next, IOptions<ResponseCachingOptions> options, ILoggerFactory loggerFactory, ObjectPoolProvider poolProvider)
```

If if any changes to these types are critical to your applications, please file an issue in https://github.com/aspnet/Aspnetcore.

**Comment by jeroenheijmans** [comment]
Out of curiosity, what is the typical use case (or if that's unanswerable: what _was_ the use case _here_) for making such "pubinternal" types in the first place?

(Please regard the above as pure curiosity around the design of large frameworks.)
