### ISSUE TITLE
A suggestion to optimize the code of Identity scaffolding based on FxCopAnalyzers

### ISSUE THREAD

**Issue by shadialnamrouti** [dotnet/aspnetcore#9452]
I have [Microsoft.CodeAnalysis.FxCopAnalyzers](https://docs.microsoft.com/en-us/visualstudio/code-quality/install-fxcop-analyzers?view=vs-2019) installed.

Scaffolding identity into a 2.2 .net core project with the option to override the implementation, generates more than150 warnings. 

Summary: 

**CA1819**: Properties should not return arrays
**CA1056**: Change the type of property _SomeUri_ from string to System.Uri.
**CA1034**: Do not nest type _InputModel_. Alternatively, change its accessibility so that it is not externally visible.
**CA2227**: Change _SomeIList_ to be read-only by removing the property setter.
**CA2007**: Do not directly await a Task without calling ConfigureAwait
**CA1307**: The behavior of 'string.Replace(string, string)' could vary based on the current user's locale settings. Replace this call in _SomeRazorPage_ with a call to 'string.Replace(string, string, System.StringComparison)'.
**CA1308**: In method _SomeMethod_, replace the call to 'ToLowerInvariant' with 'ToUpperInvariant'.
**CA1822**: Member _SomeMethod_ does not access instance data and can be marked as static.
**CA1823**: Unused field _SomeField_.

I think it's good to make the resulting code compliant to the above best practices.

**Comment by blowdart** [comment]
Some of those can't be done, for example 

"Change the type of property SomeUri from string to System.Uri"

However, the rest should be looked at, @mkArtakMSFT who is on point for templates right now?

**Comment by blowdart** [comment]
This is going to have to wait for 3.1, so moving to backlog

**Comment by ScotBren** [comment]
3.1 was already released. Is it still in the Backlog?

**Comment by dotnetshadow** [comment]
Has there been any update to this? With the release of .net 5.0 and promotion of using code analyzers, there will be so many errors. Especially **CA1034**, the pattern used in the razor pages nests `InputModel` in each class, what is the workaround for this?

**Comment by msschl** [comment]
@blowdart What are the recommendations for those who have all analyzers turned on?

For example, regarding CA1056 and the `ControllerBase.Redirect(string url)` method?
Turning those individual analyzers off? But why suggest using `System.Uri` when ASP Net Core even doesn't adhere to it?

**Comment by blowdart** [comment]
Does this still occur in 5.0?

**Comment by JohnGalt1717** [comment]
Still looking for guidance on this.

CA1034 breaks the entire model.
Nullable types makes Razor Pages difficult to say the least because of the [BindProperty] which I'd argue should just be passed with [FromForm] in the Post/Put and not a binding property at all so that it follows WebApi. But if it isn't going to, then we need a way that doesn't cause Microsoft's own analyzers to blow up at you.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
While this may be a great idea, it is not aligned with our long-term vision to make it part of the framework. For many other ideas which don't belong to the framework we encourage the community to build and ship on their own, contributing to the expanding .NET Ecosystem.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
