### ISSUE TITLE
"Cookies" was not authenticated. Failure message: "Unprotect ticket failed" 

### ISSUE THREAD

**Issue by mayconbeserra** [dotnet/aspnetcore#9459]
### Describe the bug
from time to time, I'm getting the message below in my logs, and unauthorised status, but for some requests.

**"Cookies" was not authenticated. Failure message: "Unprotect ticket failed"**

### Code

I'm registering the DataProtection in this way
```
services
    .AddDataProtection()
    .SetApplicationName(Environment.ApplicationName)
    .PersistKeysToRedis(
        redisConn,
        $"DataProtection-Keys-{Environment.ApplicationName}-{Environment.EnvironmentName}");
```

### Expected behavior
All the requests should not have the unprotect ticket failed issue

### Additional context

![image](https://user-images.githubusercontent.com/911493/56302272-b50bf280-6139-11e9-980d-bbfcf0007793.png)

   ```
 <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="2.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection.Redis" Version="0.4.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="2.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Rewrite" Version="2.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel.Https" Version="2.1.3" />
    <PackageReference Include="Microsoft.AspNetCore.SpaServices.Extensions" Version="2.1.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="2.1.1" />
```

**Comment by blowdart** [comment]
Has your redis cache recycled or otherwise emptied?

**Comment by mayconbeserra** [comment]
Hi @blowdart 

Yes, but during the night. Our Redis container was recreated and there was no volume for it. I guess the application will recreate the keys on redis in any additional request.

![image](https://user-images.githubusercontent.com/911493/56308299-42a20f00-6147-11e9-8077-cc93f9e58aa1.png)

Besides that, in the screenshot above, you can see two requests, one successful call to the `/configuration` route and another one with the failure `401`, which was in the same moment.

Is there a way to handle those failures when the Redis cache is recycled?

**Comment by blowdart** [comment]
Make the cache persistent would be one way to go, but yea, if your cache empties and all the keys go, then this is rather expected
