### ISSUE TITLE
Clean up baseline reference suppression

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/aspnetcore#9473]
As a part of https://github.com/aspnet/AspNetCore/pull/9405, I added a way to tell the build system when breaking changes to `<References>` are intentional and can be ignored. This is done by adding a `<SuppressBaselineReference>` item to the .csproj file.

After 3.0 is complete, we will update our baseline files, but we should also remove all baseline suppressions to make sure 3.1 is consistent with 3.0.

**Comment by Pilchie** [comment]
![Uploading image.png…]()

**Comment by Pilchie** [comment]
@aspnet/build Should this still be in the `3.1.0` milestone?

**Comment by dougbu** [comment]
@Pilchie not `3.1.0` but soon I hope. We partially fixed things up after `3.0.0` but #14630 blocks removing all suppressions. My hope is @wtgodbe or @JunTaoLuo will have some time to fix that bug next week or one of the three of us could do it the week after.

**Comment by dougbu** [comment]
@wtgodbe and @JunTaoLuo isn't this work done❔ I'm not sure what's missing now that #14630 work is complete

**Comment by wtgodbe** [comment]
I believe it's about seeing what happens when we remove all of these, to make sure 6.0 is consistent with 5.0: https://github.com/dotnet/aspnetcore/search?q=SuppressBaselineReference. Probably an exercise we should do after every release

**Comment by dougbu** [comment]
> an exercise we should do after every release

Ah, good point. When you have a chance, could you see if the baseline suppressions can all be removed❔

**Comment by wtgodbe** [comment]
Done by https://github.com/dotnet/aspnetcore/pull/29934
