### ISSUE TITLE
ApiAuthorizationDbContext<TUser> force TUser to extends IdentityUser instead of IdentityUser<TKey>

### ISSUE THREAD

**Issue by nguyenquyhy** [dotnet/aspnetcore#9548]
### Describe the bug
At the moment, `ApiAuthorizationDbContext<TUser>` force `TUser` to extends `IdentityUser` instead of `IdentityUser<TKey>`. This means it is impossible to use Identity Server on application with `ApplicationUser : IdentityUser<Guid>` (or anything different from `IdentityUser<string>`)

### To Reproduce
1. Using ASP.NET Core 3.0 Preview 4
2. Create a new React or Angular template with Identity
3. Change ApplicationUser to extends `IdentityUser<Guid>` instead of `IdentityUser`
4. Get error: Error CS0311 `The type 'WebApplication.Models.ApplicationUser' cannot be used as type parameter 'TUser' in the generic type or method 'ApiAuthorizationDbContext<TUser>'. There is no implicit reference conversion from 'WebApplication.Models.ApplicationUser' to 'Microsoft.AspNetCore.Identity.IdentityUser'.`

### Expected behavior
I would expect `ApiAuthorizationDbContext` to accept another generic to indicate the key type (e.g. `ApiAuthorizationDbContext<ApplicationUser, Guid>`)

**Comment by ajcvickers** [comment]
@HaoK @blowdart Where does `ApiAuthorizationDbContext` come from?

**Comment by blowdart** [comment]
Part of the identity server support I believe. @javiercn ?

**Comment by javiercn** [comment]
ApiAuthorizationDbContext is just a convenience class for the templates. 

We don’t plan to support all the variants IdentityDbContext supports.

If you want to customize the key you can extend IdentityDbContext directly and implement IPersistentGrantDbContext as ApiAuthorizationDbContext does.

https://github.com/aspnet/AspNetCore/blob/master/src/Identity/ApiAuthorization.IdentityServer/src/Data/ApiAuthorizationDbContext.cs

**Comment by ajcvickers** [comment]
Re-opening, since `ApiAuthorizationDbContext` doesn't follow best practices for a `DbContext` shipped for others to use. In particular:
* It should expose a public constructor that takes a generic `DbContextOptions<TContext>`. Otherwise people resolving this directly will have issues when multiple contexts are registered in D.I.
* It should expose a protected constructor that takes a non-generic `DbContextOptions` for use when other classes inherit from it.

**Comment by ajcvickers** [comment]
@javiercn Is this the correct repo to track this issue? If not, where should I move it?

**Comment by javiercn** [comment]
@ajcvickers This is the correct repo.

Could we use a separate issue to track the items you mention?

**Comment by cherchyk** [comment]
2020 Looks like it was not fixed yet...

Am I wrong?

**Comment by StevenRasmussen** [comment]
@blowdart , @ajcvickers - Would you accept a PR from the community on this one?  I have opened up  [#21100](https://github.com/dotnet/aspnetcore/pull/21100) that should hopefully address everything. Thanks for your consideration.

**Comment by HaoK** [comment]
We've decided not to support this

**Comment by HaoK** [comment]
The idea is that apps can derive from IdentityDbContext directly and utilize the generic support there, this class is just meant to be sugar for the most common scenario
