### ISSUE TITLE
Error whenever a empty response header is emitted

### ISSUE THREAD

**Issue by G-Freart** [dotnet/aspnetcore#9551]
### Describe the bug
Whenever an empty response header is encountered, the response is aborted 
with aspnetcore version 3.0 (also detected with version 2.2)

### To Reproduce
1. Using ASP.NET Core 3 Preview 4 and vs 2019 16.1.0 community preview 1.0
2. Run the minimalist code at https://github.com/G-Freart/Aspnetcore3-preview4-header-issue
3. Using the swagger UI, call the method /api/Trial/error-empty
4. See error inside the output windows of the visual studio
`
  System.ArgumentException: Value does not fall within the expected range.
     at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.SetResponseHeaders()
     at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.ProduceStart(Boolean flushHeaders)
     at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.InitializeResponse(Boolean flushHeaders)
     at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.<>c__DisplayClass310_0.<<FlushAsync>g__FlushFirstAsync|0>d.MoveNext()
  ....
`
### Expected behavior
Response header must be contains 'x-header-digit' and 'x-header-empty' 
Response body must contains 'correct'

### Additional context
* Tested with aspnetcore v 2.2 ... same issue
* Tested with aspnetcore v2.1 ... working as espected

**Comment by Tratcher** [comment]
Ok, that's buggy and we should handle it better. Note elsewhere we filter out empty headers.

What's your scenario for sending an empty response header? Such headers have no semantic meaning in HTTP. Host is the only exception I'm aware of.

**Comment by G-Freart** [comment]
Hi @Tratcher,

I've detected when porting a home-made generated code which retreived a set of entity.
The method perform a paging / ordering / filtering and is used by an angular spa.

I'm sending back the 'sorting' and the 'filtering' value which has been received inside http request header.

The response body contains only the array of wished entities and ''metadata'' are within response header.

As a work-around, i have put a one space string instead of an empty string as null replacement.

```
int total = await (orderedQuery ?? query).CountAsync ();

Response.Headers.Add ("X-PageCount",                   ((total + pageSize -1) / pageSize).ToString ());
Response.Headers.Add ("X-PageIndex",                   pageIndex.ToString ());
Response.Headers.Add ("X-PageSize",                    pageSize .ToString ());
Response.Headers.Add ("X-Total",                       total    .ToString ());
#if NETCOREAPP2_1
Response.Headers.Add ("X-Order",                       sorting   ?? ""       );
Response.Headers.Add ("X-Filter",                      filtering ?? ""       );
#else
Response.Headers.Add ("X-Order",                       sorting   ?? " "     ); // sorting is either a filled string or a null value
Response.Headers.Add ("X-Filter",                      filtering ?? " "     ); // idem 
#endif

Response.Headers.Add ("Access-Control-Expose-Headers", "X-Total,X-Filter,X-Order,X-PageSize,X-PageIndex,X-PageCount");

````

**Comment by Tratcher** [comment]
The client isn't actually consuming the empty headers are they? I'd think a better fix would be:
```
if (!string.IsNullOrEmpty(sorting)) Response.Headers.Add ("X-Order", sorting);
```
That's likely how the server will fix this, by skipping the header.

**Comment by Alexcei88** [comment]
I have the same issue with Net Core 2.2.6
As soon As I am adding an empty header value like below
              
         `context.Response.Headers.Add(USER_ID_HEADER, string.Empty);`

At once I am catching the error.

**Comment by HaoK** [comment]
I tried this on 5.0 with a new WebAPI app and the following method copied from the repro repo:

```
        [Route("error-empty")]
        [HttpGet()]
        public string HeaderDigitEmpty()
        {
            Response.Headers.Add("X-header-digit", "1");
            Response.Headers.Add("X-header-empty", "");

            return "correct";
        }

```

Looks like this was fixed in https://github.com/dotnet/aspnetcore/pull/12486/files
