### ISSUE TITLE
Question: How change HttpClientHandler in IHttpClientFactory?

### ISSUE THREAD

**Issue by Temoxa** [dotnet/aspnetcore#9610]
I use for example create controller

```
public class ValuesController : Controller
{
    private readonly IHttpClientFactory _httpClientFactory;
  
    public ValuesController(IHttpClientFactory httpClientFactory)
    {
        _httpClientFactory = httpClientFactory;
    }
  
    [HttpGet]
    public async Task<ActionResult> Get()
    {
        var client = _httpClientFactory.CreateClient();
        client.BaseAddress = new Uri("http://api.github.com");
        string result = await client.GetStringAsync("/");
        return Ok(result);
    }
}
```
How change HttpClientHandler after get httclient
`var client = _httpClientFactory.CreateClient();` ?

maybe i can use ?

```
var credential = new HttpClientHandler()
            {
                UseDefaultCredentials = true,
                Credentials = new NetworkCredential("", ""),
            };
var client = _httpClientFactory.CreateClient(credential);
```

**Comment by huysentruitw** [comment]
Do you want to use the same credentials for all `HttpClient` instances in the application or only for certain calls?

**Comment by Temoxa** [comment]
I want set credentials for create httpclient from httpfactory)

**Comment by huan086** [comment]
Is is possible to set it in Startup.cs instead, and use a named client?
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-2.2#configure-the-httpmessagehandler

**Comment by TemoxaGreenMoney** [comment]
Credentials dynamic changes....

**Comment by BrennanConroy** [comment]
You can use a named client to do this
https://docs.microsoft.com/aspnet/core/fundamentals/http-requests?view=aspnetcore-3.1#createclient
