### ISSUE TITLE
Why are we still needing MVC now in the popularity of microservices?

### ISSUE THREAD

**Issue by DrDao** [dotnet/aspnetcore#9707]
From the .NET framework to the current .Net Core, MVC has been around for many years. Why don't we abandon or introduce new design concepts (such as Spring Boot WebFlux) to improve our application performance? Today, microservices are popular, we are still using MVC to design and build our API.

**Comment by davidfowl** [comment]
what do you think is unique about webflux and springboot compared to ASP.NET Core MVC?

**Comment by DrDao** [comment]
> what do you think is unique about webflux and springboot compared to ASP.NET Core MVC?

Faster response performance, non-blocking, streaming, etc.

**Comment by benaadams** [comment]
> Faster response performance,

By which measure? [Spring vs ASP.NET Core MVC](https://www.techempower.com/benchmarks/#section=data-r17&hw=ph&test=fortune&l=zik0vx-1&c=6&f=zijunz-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-qmx0qn-zik0zj-e7)

![image](https://user-images.githubusercontent.com/1142958/56630711-1eb06300-664a-11e9-9d6d-fa4b73cd3bc2.png)

> non-blocking 

ASP.NET Core is async so not blocking if you don't all blocking apis. If you call blocking IO in ASP.NET Core 3.0 it will prevent you by default https://github.com/aspnet/Announcements/issues/342

**Comment by davidfowl** [comment]
Right as @benaadams mentioned this is all doable with ASP.NET Core itself and even mvc. Unlike most java frameworks, it’s non blocking at the core and very lean and fast. 

> Faster response performance, non-blocking, streaming, etc.

Easy to do and IMO more elegant in c# than in java

**Comment by DrDao** [comment]
Maybe we need a faster, more advanced technology, because we often hear about how Microsoft is still engaged in MVC. In today's more and more front-end separation technology, why do we need MVC? Instead of creating a better one. Come out.

**Comment by benaadams** [comment]
You may want to watch this week's ASP.NET Community Standup where @rynowak talks about the unbundling of features for MVC so they can be utilised by other approaches and areas of the technology stack: https://youtu.be/R36j2KGBBhE?t=1295 it may unlock what you are looking for...

**Comment by davidfowl** [comment]
Right, the name MVC has stigma and really is just the name that was picked years ago (mostly because of rails and the MVC pattern) that stuck. The framework itself is modern and we're pushing more concepts into the core.

**Comment by DrDao** [comment]
Personally feel that .NET CORE is a new .NET branch or modern technology or architecture, you should not continue to use the term MVC, or the feeling is that Microsoft has been playing MVC this old technology for years. And there should be a more resounding name to tell everyone, hey, I have a new generation of next-generation WEB technology, we have good performance and a more agile development language, want to try it?

**Comment by DrDao** [comment]
The development friends and colleagues around me are puzzled. Why do we still use the old MVC framework when the micro-service usage rate is getting higher and higher? Why do we need to use ASP.NET MVC to complete the whole application development? Why not directly Use "Vue.js, AngularJS, NodeJS" for page rendering?

**Comment by davidfowl** [comment]
> Personally feel that .NET CORE is a new .NET branch or modern technology or architecture, you should not continue to use the term MVC, or the feeling is that Microsoft has been playing MVC this old technology for years.

I generally agree with you. It's a double edged sword, it's a detractor for people like you that are looking at seemingly newer technologies on other stacks when comparing it to .NET Core but it's a comfort to people porting older applications for ASP.NET MVC to ASP.NET Core MVC. 

> And there should be a more resounding name to tell everyone, hey, I have a new generation of next-generation WEB technology, we have good performance and a more agile development language, want to try it?

We're working on it though, it's mostly marketing and it's really hard to rename things in .NET without breaking everyone. If one were to look past the artifical naming, the framwork itself is modern and fast.

> The development friends and colleagues around me are puzzled. Why do we still use the old MVC framework when the micro-service usage rate is getting higher and higher? Why do we need to use ASP.NET MVC to complete the whole application development? Why not directly Use "Vue.js, AngularJS, NodeJS" for page rendering?

I've heard the same thing from folks that don't know what the tech stack has to offer. While the naming is unfortunate, the stack itself supports multiple ways of writing applications (you can easily remove the V from MVC). Just look at the wide variety of application types we offer (and this is just a small set) with ASP.NET Core 3.0:

![image](https://user-images.githubusercontent.com/95136/56667781-4fe95d00-6663-11e9-9d63-b11e3c0bcdc0.png)
