### ISSUE TITLE
BLAZOR - "Find All References" Feature in VS 2019.

### ISSUE THREAD

**Issue by BenHayat** [dotnet/aspnetcore#9731]
Just like any CS file that we can right click and select "Find All References", to give us all other files that are referencing this file, it would be very useful to get a reference list of components/files that use a specific component.

Thanks!
..Ben

**Comment by rynowak** [comment]
Agreed. We have this for C# code (and it will work for the `@functions` block in VS 2019) - however we don't have this support right now for component types and parameters used from markup. 

Sadly, we won't get to this in the 3.0 release.
