### ISSUE TITLE
Add ability to use IgnoreQueryFilters with UserManager

### ISSUE THREAD

**Issue by BetimShala** [dotnet/aspnetcore#9782]
Hi there,

I'm having trouble to use IgnoreQueryFilters  with UserManager, for example I've used HasQueryFilter like this :
` 
public void Configure(EntityTypeBuilder<ApplicationUser> b)
        {  b.HasQueryFilter(e => e.EmailConfirmed); }
`

When I'm trying to find an User by Email (not confirmed yet) : 
`
                var user = await _userManager.FindByEmailAsync(request.Email);
` 
it returns me null, so I'm not able to do something like this : 
`
                var user = await _userManager.IgnoreQueryFilters().FindByEmailAsync(request.Email);
`
Do you have any suggestion what to do in this case?

**Comment by blowdart** [comment]
@ajcvickers to explain the EF pieces :)

**Comment by BetimShala** [comment]
I forgot to mention that I am able to do smth like this 
`
var user = await _userManager.Users.IgnoreQueryFilters().FirstOrDefaultAsync(u => u.Email.Equals(request.Email));
`

**Comment by HaoK** [comment]
Going through users is what you need to do.  The UserManager.Users is an IQueryable
