### ISSUE TITLE
Parity with asp.net: control ordering of middleware to simplify consumer experience

### ISSUE THREAD

**Issue by chuanboz** [dotnet/aspnetcore#9787]
### Is your feature request related to a problem? Please describe.
In asp.net, there is http message handlers that's similar concept as asp.net core middleware.
And there is HttpConfiguration with property of MessageHandlers that library owner could use to control the ordering of the handlers.

For example, I could use below to ensure the handler are executed early.
```C#
// make sure it is the first message handler
config.MessageHandlers.Insert(0, new RequestTrackingMessageHandler(config));
```

Similarly, with the access to MessageHandlers list, library owner could also add logic to ensure handler executed after authentication for example.

The ask is something similar in asp.net core that allow library owner to control the ordering of middleware based on the best knowledge from library owner about the ordering constraints.

### Describe the solution you'd like
If we could change IApplicationBuilder to ether expose the internal middleware list, or some mechanism to allow control of the ordering, that would solve the issue.

### Describe alternatives you've considered
Without this, the only thing we could do is to document the required sequence and hoping the owner will follow that, but this has a few issues:
1. Sometimes the ordering is kind of complex, especially with lots of different middlewares.
2. Does not response to change easily when library owner needs to change the ordering of the middleware.

### Additional context
Below are related issues raised that would be addressed if this is supported.
https://github.com/aspnet/AspNetCore.Docs/issues/5172
https://github.com/aspnet/AspNetCore.Docs/issues/11389
https://github.com/aspnet/AspNetCore/issues/1811

**Comment by Tratcher** [comment]
We have three approaches for addressing ordering today:
- Docs - https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-2.2#built-in-middleware
- Analyzers - Gives you warnings during development if we think your middleware is not where it should be.
- Bundling, builders, etc. - When some middleware are interdependent we've found it best to bundle them together under combine extension methods, or to offer builder patterns that help you group and configure those things together. E.g. UseFileServer is an aggregate of DefaultFiles, DirectoryBrowsing, and StaticFiles in the appropriate order.

The ASP.NET Core middleware pipeline is far more flexible and complex than the old ASP.NET pipeline. It's non-linear, branching and joining as the application sees fit. We've found it more practical to help people set up their pipeline correctly than it would be to re-order it for them after the fact. Ultimately we want the ordering decisions to lie with the developer, they'll do what makes sense for their application, where libraries and frameworks can only advise.

**Comment by chuanboz** [comment]
thanks @Tratcher for the details explanation. for Analyzers, can you give some source code reference for the built-in one? want to learn more details there.

**Comment by anurse** [comment]
Moving this to discussions for now as we don't plan to add the ability to manipulate the middleware list (since as @Tratcher says, it's not linear).

**Comment by Tratcher** [comment]
@rynowak for analyzers.
