### ISSUE TITLE
Convert from ApiCheck to ApiCompat

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/aspnetcore#9927]
As a part of Arcade convergence, we plan to drop our ApiCheck tool and convert to ApiCompat, which is the tool other teams use to ensure public API remains compatible between releases.

**Comment by natemcmaster** [comment]
@anurse is this something you might be able to drive while I'm out? This is closely related to #10597.

**Comment by anurse** [comment]
Sure, I'll swap it to assigned to me for now.

**Comment by natemcmaster** [comment]
Thanks!

**Comment by Pilchie** [comment]
@anurse - bump to Preview 9?

**Comment by anurse** [comment]
I don't think I'll be able to drive this until I'm back from leave. If this is something we want to take, it'll probably have to be post-3.0. I don't think this is something we have to do before shipping though.

**Comment by anurse** [comment]
I think we'll have to revisit this for 5.0. We didn't get anywhere with it in 3.0/3.1

**Comment by wtgodbe** [comment]
We're now using Roslyn analyzers for this purpose, closing (CC @dougbu who did that work)
