### ISSUE TITLE
[Epic] Templating

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspnetcore#9937]
## Simplification
- Make the templates as simple as they can be while continuing to serve their primary purpose
- Defaults for most of these should not use packages to ensure projects can be created offline. OK for optional parameters to result in packages being added.

## ILogger - https://github.com/aspnet/AspNetCore/issues/10332
  - Update all our activated types to take `ILogger<T>`
  - e.g. Controllers, Pages, Hubs, etc.
  - Inject in constructor and place on a property

## Worker
 - Add context to the hostbuilder (done)
 - Doc the ability to use Windows Services instead of using an option
 - No options for Worker

## API
- [Option to add Swashbuckle (modulo 3rd-party OSS prep)](https://github.com/aspnet/AspNetCore/issues/7639)
- [Open API client generation: This will be a doc and packages in 3.0](https://github.com/aspnet/AspNetCore.Docs/issues/8461)
- [Changing `ValuesController` to `WeatherController`](https://github.com/aspnet/AspNetCore/issues/10333)
  - GET only (scaffolding covers the POST/PUT/DELETE scenarios)
  - Overload one, accepts two parameters: `string location` (returns Celsius)
  - Overload two, accepts two parameters: `string location, TemperatureUnit unit`
  - Enum `TemperatureUnit` defined in project: `public enum { Celsius, Fahrenheit }`
  - Returns: `new WeatherResult { Location = location, Temperature = randomTemp, TemperatureUnit = unit }`
  - If Swashbuckle opted in to then ensure wired up for enums correctly
- [API Conventions & Analyzers: always on, no options](https://github.com/aspnet/AspNetCore/issues/10334)
- [API Auth via IdentityServer, details TBD but likely just adds IdentityServer & JWT middleware then points user to docs for further configuration](https://github.com/aspnet/AspNetCore/issues/10335)
- [Certificate Auth option?](https://github.com/aspnet/AspNetCore/issues/10336)
- [Kerberos Auth option?](https://github.com/aspnet/AspNetCore/issues/10337)
- [Remove HSTS](https://github.com/aspnet/AspNetCore/issues/8533)

## Web Application
- [Single project template](https://github.com/aspnet/AspNetCore/issues/10345)
- [Option to select view engine: Razor Pages or Razor Views (MVC)](https://github.com/aspnet/AspNetCore/issues/10345)
- [Alias existing "mvc" template to this and make it pre-select "Razor Views" for option above](https://github.com/aspnet/AspNetCore/issues/10345)
- [Move cookie-consent content to a doc](https://github.com/aspnet/AspNetCore/issues/10346)
- [Simplify the JS and CSS links (no CDNs & environments)](https://github.com/aspnet/AspNetCore/issues/10347)
- [No LibMan](https://github.com/aspnet/AspNetCore/issues/5415)

## Blazor - https://github.com/aspnet/AspNetCore/issues/10348
- In-box is called "Blazor Server App" / blazorserver
- OOB is called "Blazor WebAssembly App" / blazorwasm
  - With an option to add a hosting ASP.NET Core project

## Naming & Options Summary
- Empty Web App
- Web App
  - Auth: all the options we have today
  - MVC boolean option:
    - `dotnet new webapp` (equiv to `dotnet new razor`) or `dotnet new webapp --mvc`
- Blazor Server App
- Worker Service
  - Keywords: Windows Service, Background
- API Service
  - Keywords: REST, HTTP+JSON, etc.
- gRPC Service
- Blazor Server App
- Blazor WebAssembly App
  - Blazor WebAssembly App (ASP.NET Core hosted)
  - This becomes an option of the "Blazor WebAssembly App" template when VS can render it
- Angular App (OOB it?)
- React App (OOB it?)
- React with Redux App (OOB it?)
- Vue App (theoretical OOB)

## VS Item templates
TBD

**Comment by Andrzej-W** [comment]
It would be nice to have `Auth` option in `Blazor WebAssembly App (ASP.NET Core hosted)` and ` Blazor Server App`

**Comment by DamianEdwards** [comment]
@Andrzej-W there is a plan for auth for Blazor apps that is being executed on for preview6 I believe @danroth27?

**Comment by danroth27** [comment]
Yup: #4048

**Comment by los93sol** [comment]
It would be awesome if the Blazor templates were closer aligned to the other web templates.  That layout is the first thing I strip out of every project.

**Comment by JamesNK** [comment]
gRPC template is pretty close to final. Just minor tweaks to the project name left.

**Comment by mkArtakMSFT** [comment]
A lot of this work has been done in 3.0. Moving the issue to 5.0 to tackle the remaining work.

**Comment by captainsafia** [comment]
Closing in favor of the newer issues created around template strategy in 6.0.

https://github.com/dotnet/aspnetcore/issues/27338
