### ISSUE TITLE
NavLink inside SVG tag causes full page reload

### ISSUE THREAD

**Issue by chrisevich** [dotnet/aspnetcore#9951]
**### Describe the bug**
When using a NavLink inside an svg tag, clicking the link causes a full page reload. Clicking the html text link causes a partial page update as expected.

**### To Reproduce**
Past the following code into Index.razor from the starter project. 

@page "/"
<svg height="200" width="200" viewBox="0 0 200 200">
<NavLink href="counter">
    <circle cx="100" cy="100" r="10"></circle>
</NavLink>
</svg>

<NavLink href="counter"><h1>no svg</h1></NavLink>
<style>
    circle {
        fill: green;
    }
</style>

**### Expected behavior**
Clicking on the svg circle should route to 'counter' page with a partial page update.

**### Actual behavior**
Clicking on the svg circle routes correctly to the 'counter' page but causes a full page reload.

**### Additional context**
PM> dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview4-011223
 Commit:    118dd862c8

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview4-011223\

Host (useful for support):
  Version: 3.0.0-preview4-27615-11
  Commit:  ee54d4cbd2

.NET Core SDKs installed:
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.700-preview-009601 [C:\Program Files\dotnet\sdk]
  3.0.100-preview4-011223 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview4-19216-03 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview4-27615-11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview4-27613-28 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by chrisevich** [comment]
Sorry here's the code:

```
`@page "/"
<svg height="200" width="200" viewBox="0 0 200 200">
    <NavLink href="counter">
        <circle cx="100" cy="100" r="10"></circle>
    </NavLink>
</svg>

<NavLink href="counter"><h1>no svg</h1></NavLink>
<style>
    circle {
        fill: green;
    }
</style>`
```

**Comment by SteveSandersonMS** [comment]
Thanks for reporting this, @chrisevich!

We'd like to understand exactly why this happens and what a reasonable solution would be. Hopefully we would be able to investigate this ourselves at some point, but to be honest we have a lot of other more highly prioritised items in the short term.

If you were interested in debugging this into the framework yourself and coming up with a proposal about what the minimal fix would be, we might be able to resolve it sooner (if it turns out to be valid to resolve it at all).

**Comment by mkArtakMSFT** [comment]
Closing as we will be tackling this as part of https://github.com/dotnet/aspnetcore/issues/18271
